### ISSUE TITLE
Expose MarkForRemoval for BehaviorContext (add a warning when a network entity is deleted without such a call)

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#10006]
**Is your feature request related to a problem? Please describe.**
I am unable to correctly destroy a network entity on the server.

**Describe the solution you'd like**
Expose `INetworkEntityManager::MarkForRemoval` to BehaviorContext, so that a network entity can be removed from scripting.
Note: calling DestroyGameEntity directly on a networt entity is incorrect.

**Additional context**
Network entities have a number of systems processing them and thus require special care to be properly removed from the game.

**Comment by lmbr-pip** [comment]
Lowest impact script, will impact single player scripts moving to networking scripting.

Preferred fix would be to have entities self clean up, but that work needs more investigation.
