### ISSUE TITLE
More apparent Z-fighting/flicker on overlapping geometry inside *single* imported assets

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#10023]
**Is your feature request related to a problem? Please describe.**
This was exposed in a Walk the Engine session, and could potentially be a feature looking into. DCC applications typically show some type of visual cue when there are identical pieces of overlapping geometry. This is usually in scenarios when there might be an item that has mistakenly been duplicated one or more times, or when vertices of faces have been accidentally fused together, creating an overlap within the same planar space (which was the condition of the geometry in the attached video). In the case of Walk the engine, a piece of geometry was purposefully created that contained Ngons and overlapping faces. In the engine there was no visual indication that that the surface of this geometry was flawed, while in Maya the overlapping faces  had a "flicker" effect that helped to expose that there was something wrong with the Geo (see video). 

https://user-images.githubusercontent.com/50616575/172954614-70913013-c209-46bc-913d-a49e96c01cb5.mp4

**Describe the solution you'd like**
In the interests of safeguarding against users mistakenly adding flawed geometry that can effect the visual quality of their creations, as well as adding extra geometry that could have some bearing on file size, performance, etc., it may be worth adding some type of visual cue in the viewport display when this type of scenario is present. 

**Describe alternatives you've considered**
The alternative is to have handling remain as it exists now. In many cases a user won't even notice visually that something is off, but it is unpredictable how flawed geometry may interfere with the quality of visual representation if nasty geometry passes through without any kind of notification

**Additional context**
I want to make note of the fact that Z fighting IS present when you are looking at two different assets that occupy the same space (such as a floor plane imported from a scene occupying the same space as our default ground plane). This request is concerned more with how the Z flicker is absent when the overlapping geo is contained _within the same mesh_

**Comment by yuyihsu** [comment]
Per @galibzon , this is by design. we don't use the editor to design the geometry as Maya does.

**Comment by galibzon** [comment]
This feature is why people pay big bucks for DCC Tools licenses. There's no point in trying to do this in O3DE.
