### ISSUE TITLE
Material Editor thumbnails do not consistently update when changes to material are made

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#10028]
**Describe the bug**
When making modifications to materials in the Material Editor, the thumbnail of edited materials often will not update (typically they will not show diffuse map changes, which should be the most visible). In this particular case (this is new to me) the thumbnail of the material on shader ball is replaced with a file icon, which appears to be a bug. Updating the material also does not translate to an updated shader ball in the Material Component (as you can see in the video, it is still the file icon). Often what happens is that you will make changes to the material in the Material Editor and save it, but when switching back from the Material Editor to the Editor the thumbnail will not update and will remain black, OR it will faintly show signs that an update has occurred to SOME channels of the material (like Roughness or Normals most likely), but the Diffuse, which should be most apparent, does not change.

One underlying factor that I personally feel could be contributing to this problem is the Texture Blend setting under Base Color being set to multiply, and the Color by default being set to Black. This will cause problems immediately with seeing your Diffuse texture map displayed properly (see attached video):

https://user-images.githubusercontent.com/50616575/172964077-b0ac2549-606b-43da-b454-f045dc91e7bc.mp4

**Assets required**
Please email me to request assets used in the video (benblac@amazon.com) and I can set up a drive link for you to download the assets shown in the video above

**Steps to reproduce**
Follow the exact steps shown in the video. The assets are in a location where the asset processor can see them, and the Asset Browser can reach them.

**Expected behavior**
I would expect for the file icon to not be present at any point in the place of the thumbnail. This has never been the expected behavior and is likely a bug. I would expect that when I assign a Diffuse texture, I see it update on the shader ball, and most importantly- BE VISIBLE. If the default settings is to set a background color to black and a layer mode to Multiply, it is very obvious that there is no part of black where the color of the Diffuse texture will be visible, as multiplying any pixel value by any channel of a solid black (0,0,0) is going to equal zero. I have see the Material editor set up this way for a long time, and I do not understand the rationale for why this would be the desired default setting.

**Actual behavior**
Thumbnails at no point update to the expected appearance, which should be to give users a preview of what the material looks like. Also, users need to perform a very unintuitive change of the background color, or change the texture blending to Lerp, or something that will not output pure black in the diffuse when using file textures that clearly aren't solid black.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.
![file_icon_material_editor](https://user-images.githubusercontent.com/50616575/172964889-47db6011-6b0a-4fc7-b381-065a17c5dc70.PNG)

**Found in Branch**
Current Development 

**Desktop/Device (please complete the following information):**
 - PC
 - Windows
 - 10
 - Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz   3.30 GHz
 - NVidia GeForce RTX 2080
 - 64.0 GB

**Additional context**

**Comment by gadams3** [comment]
The issues involving the white file icon should never happen again. This was being caused because the material preview failed to load within some set time frame, which caused it to display a default file thumbnail. Once that thumbnail appears, it will never be replaced. This is an issue in the thumbnail system that needs to be addressed separately. If the thumbnail ever fails to render, it will display a black image that will be updated as soon as the thumbnail is updated or reloaded.

It sounds correct that if the base color is black and the blend mode is multiply then the material and thumbnail would also be black. Standard PBR material type has a default color of white and blend mode of multiply. If you are seeing black by default then it may be coming from your model or the model builder.
