### ISSUE TITLE
[MultiplayerSample]Client can not connect to Server if using TCP protocol and enable MulitplayerCompression Gem

### ISSUE THREAD

**Issue by xiapeng78** [o3de/o3de#10030]
**Describe the bug**
Clinet can not connect to Server if using TCP protocol and enable MulitplayerCompression Gem. If disable MulitplayerCompression Gem MultiplayerSample can work on TCP protocol. 

**Steps to reproduce**
1. Enable  MulitplayerCompression Gem in the Project Management, and rebuild project
![image](https://user-images.githubusercontent.com/17897322/172971013-3206c5a7-e361-43ea-a902-b3e5dfe8917b.png)

2. Run MultiplayerSample.ServerLauncher.exe with -sv_protocol="tcp"
3. Run MultiplayerSample.GameLauncher.exe with -sv_protocol="tcp"
4. Client can not connect to Server

**Found in Branch**
Latest code of development branch.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-11700]
 - GPU [NVidia RTX 3060 Ti]
 - Memory [32GB]

**Additional context**
[log.zip](https://github.com/o3de/o3de/files/8875023/log.zip)

**Comment by AMZN-puvvadar** [comment]
Thanks for reporting this, it should be fixed as of changes made in https://github.com/o3de/o3de/pull/10153.
