### ISSUE TITLE
[MultiplayerSample]The network entities created by SpawnIfAuthority.scriptcanvas will disappear after almost forty seconds

### ISSUE THREAD

**Issue by xiapeng78** [o3de/o3de#10031]
**Describe the bug**
The network entities created by SpawnIfAuthority.scriptcanvas will disappear after almost forty seconds.

**Steps to reproduce**
1. Run MultiplayerSample.ServerLauncher.exe, SpawnIfAuthority.scriptcanvas create some network entities in level
![1](https://user-images.githubusercontent.com/17897322/172976002-dd06b6e8-0e66-49e1-9525-c317f461843d.JPG)

2. After almost forty seconds these entities disappear, but level did not add any script to destroy these entities
![2](https://user-images.githubusercontent.com/17897322/172976108-12b2fa2b-b0a6-4a84-84aa-c4ad0db7676f.JPG)

**Found in Branch**
Latest code of development branch.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-11700]
 - GPU [NVidia RTX 3060 Ti]
 - Memory [32GB]

**Comment by lmbr-pip** [comment]
@xiapeng78 Would be great to share scripts to aid reproduction of issue.

**Comment by AMZN-puvvadar** [comment]
I've repro'd this locally. The script referred to is the default SpawnIfAuthority used in the SampleBase level. The prefab spawned from that script (FilteredGroup) disappears from the server first followed by the client.

**Comment by AMZN-puvvadar** [comment]
After further investigation, this seems like an issue involving Prefabs and Scripting.

```
 	MultiplayerSample.ServerLauncher.exe!AzFramework::SpawnableEntitiesManager::DecrementTicketReference(void * ticket) Line 325	C++
 	MultiplayerSample.ServerLauncher.exe!AzFramework::EntitySpawnTicket::~EntitySpawnTicket() Line 315	C++
 	[External Code]	
>	MultiplayerSample.ServerLauncher.exe!AZ::BehaviorContext::DefaultDestruct<AzFramework::EntitySpawnTicket>(void * object, void * userData) Line 1565	C++
 	MultiplayerSample.ServerLauncher.exe!AZ::ScriptContextImpl::DefaultBehaviorCaller::Destroy(lua_State * lua) Line 4623	C++
 	[External Code]	
 	MultiplayerSample.ServerLauncher.exe!AZ::ScriptContext::GarbageCollectStep(int numberOfSteps) Line 5907	C++
 	MultiplayerSample.ServerLauncher.exe!AZ::ScriptSystemComponent::OnSystemTick() Line 314	C++
```

Essentially, the script creates an EntitySpawnTicket. At some point lua deems it's time to garbage collect it which leads to the creation of a Destruction command for the item spawned. It seems like ownership of the ticket needs to be handed off or GC should not be occurring for this script at the time it is.

**Comment by monroegm** [comment]
Currently you need to hold a reference to the spawn ticket to keep spawned entities alive. See https://www.o3de.org/docs/learning-guide/tutorials/entities-and-prefabs/spawn-a-prefab/ for details on how to store the spawn ticket in a variable. Let us know if this doesn't solve your issue.

**Comment by monroegm** [comment]
Related to #9690

**Comment by AMZN-puvvadar** [comment]
Thanks @monroegm , that had exactly the detail being missed. Fix proposed in https://github.com/o3de/o3de-multiplayersample/pull/156.

**Comment by AMZN-puvvadar** [comment]
Fix merged.
