### ISSUE TITLE
Feature Request - O3DE script support external subdirectory for enable-gem

### ISSUE THREAD

**Issue by cgalvan** [o3de/o3de#10066]
**Is your feature request related to a problem? Please describe.**
There are several places in our documentation (e.g. https://www.o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/) that make reference to specifying the project path on the `o3de` command-line script via both `-espp` and `-pp`. The `-es` flag denotes an external subdirectory. This external subdirectory flag is currently only available on the `register` command, but not the `enable-gem` command. This inconsistency has confused some users.

**Describe the solution you'd like**
We should either add support for this flag to the `enable-gem` command or update our documentation so that it's clearer when to use which flag.

**Comment by lumberyard-employee-dm** [comment]
@cgalvan The enable-gem command can only be used with a project.

Only Projects can explicitly activate or not activate a gem.

For registration, the external subbdirectory is being added to a particular "o3de object".
Be that the engine.json, o3de_manifest.json, or the gem.json, the project.json

**Comment by lumberyard-employee-dm** [comment]
Closing the issue as the documentation clearly distinguishes which argument to use for each.
The `enable-gem` command only supports a project path argument and is documented as part the page linked in this issue as well as the [Adding and Removing Gems in a Project](https://www.o3de.org/docs/user-guide/project-config/add-remove-gems/#using-the-command-line-interface-cli) page.

The [Registering Gems to a Project](https://www.o3de.org/docs/user-guide/project-config/register-gems/) pages indicates to use the external subdirectory project path argument.

The [O3DE CLI Reference](https://www.o3de.org/docs/user-guide/project-config/cli-reference/#register) for the `register` command explains that the `--project-path` or `-pp` parameter is used to register the project with an engine or the o3de manifest, while the `--external-subdirectory-project-path` or `-espp` parameter is used to register an external subdirectoryor gem with a project.
