### ISSUE TITLE
AR Bug Report: test_Multiplayer_AutoComponent_NetworkInput fails periodically

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#10061]
**Describe the bug**
`test_Multiplayer_AutoComponent_NetworkInput` automated test fails periodically on AR.

**Failed Jenkins Job Information:**
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-10009/1/pipeline/715

````
Failure: Failed to find expected line: System: Editor Server completed receiving the editor's level assets, responding to Editor...
````

**Attachments**
[log.txt](https://github.com/o3de/o3de/files/8880373/log.txt)

**Comment by lmbr-pip** [comment]
Test is sandboxed, https://github.com/o3de/o3de/blob/2bcf230c88ef3ae3b78820df02e8b8cc25b01040/AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py#L34 

Resolving, test will be stablizied prior to its return.
