### ISSUE TITLE
Entity Outliner Redraws With Missing Entities

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#10075]
**Describe the bug**
This is redraw / refresh bug of the Entity Outliner panel. Seems to occurs for levels that have several entities and several prefabs. When I open the level I don't always get the Entity Outliner to show all the entities in the right place. Sometimes they appear "outside" of the root "Level" entity, etc. Closing and reopening the Entity Outliner produces different visual results.

Interestingly, even though some entities do not appear in the Entity Outliner, they still exist in the level and there are no crashes going in and out of game mode. Seems to be a scary visual artifact of the Entity Outliner panel. I say scary because it makes you believe that the entities have been deleted.

**Assets required**
I'd recommend to create a test level with lots of entities and 

**Steps to reproduce**
Create a level with 50+ entities, have them nested, also have them load some prefabs, etc. Open the level if everything looks good, close and open the Entity Outliner several times. You should get missing entities from the outliner, or sometimes they render outside of the "Level" entity.

**Expected behavior**
Entities should not disappear from the Entity Outliner.

**Actual behavior**
Entities disappear from the Entity Outliner, but they are still part of the level.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/66021303/173192494-252bd191-fc34-4e6a-ab41-79d1ff524f8a.png)

![image](https://user-images.githubusercontent.com/66021303/173192660-aed606b2-9534-41d9-b7c2-02598ad09d3c.png)

![image](https://user-images.githubusercontent.com/66021303/173192503-8845c218-c939-4327-989f-dca34c444b5b.png)

**Found in Branch**
commit 47a2dc800d42315a43645d4511493d1f7e43fb5c (upstream/development, development)
Author: Mike Balfour <82224783+mbalfour-amzn@users.noreply.github.com>
Date:   Fri Jun 10 19:54:05 2022 -0500

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [AMD Ryzen Threadripper 3970X 32-Core Processor    3.70 GHz ]
 - GPU [NVidia RTX 3070]
 - Memory [64GB]

**Additional context**
I've seen this bug since three months ago or so, still occurs in the latest "development" branch listed above.

Something I noticed is that all entities that appear outside of the `Level` entity don't have a `Parent Entity` in the Transform component.

**Comment by galibzon** [comment]
Changed the priority to blocker because there are some loose entities (no idea how they appeared in the level) that were part of Prefabs and I can not delete anymore because the Entity Outliner still believes the entity is associated with a prefab. Those entities, don't have a a Parent in the Transform component either.

**Comment by AMZN-daimini** [comment]
Could you attach the level/prefab? This sounds like the result of a corrupted prefab file that is not loaded correctly.

Looping in @srikappa-amzn @monroegm to see what we could do to handle these cases more gracefully.

**Comment by galibzon** [comment]
It's a very heavy project, it has lots of assets. I think the best way would be to create a level in AutomatedTesting with lost of entities and nested prefabs etc. Do you guys have python scripts to generate such levels for validation?

**Comment by galibzon** [comment]
I just tried with latest development branch at commit 6f5e553acab390f907625898b4d28bce04268743
and initially only entities with Actor component appeared outside of the Level prefab tree. I re-parented them back to the Level prefab entities and now I have 0 issues with the Entity Outliner. Closing this issues as resolved.
