### ISSUE TITLE
Re-enabling ScriptCanvas component results in full path being saved to level .prefab

### ISSUE THREAD

**Issue by allisaurus** [o3de/o3de#10070]
**Describe the bug**
Adding a script canvas component to an entity results in the full(ish?) file path being added to the component's entry in the level's .prefab file. This breaks portability of the path reference, since anything before the project name will not necessarily be the same on other machines.

Also: removing the "path" argument completely breaks things. 

Example:
```
"Component_[6251151424244415885]": {
                    "$type": "EditorScriptCanvasComponent",
                    "Id": 6251151424244415885,
                    "configuration": {
                        "sourceHandle": {
                            "id": "{3DCA213D-534E-5C86-9308-2F7675A08029}",
                            // FULL PATH
                            "path": "Users/USERNAME/source/o3de/AutomatedTesting/ScriptCanvas/lambdademo.scriptcanvas"
                        },
                        "sourceName": "lambdademo.scriptcanvas",
                        "propertyOverrides": {
                            "source": {
                                "id": "{3DCA213D-534E-5C86-9308-2F7675A08029}",
                                // FULL PATH
                                "path": "Users/USERNAME/source/o3de/AutomatedTesting/ScriptCanvas/lambdademo.scriptcanvas"
                            }
                        }
                    }
                },
```

_Workaround_: removing portions of the file path before "ScriptCanvas" seems to leave it in a working state.

**Assets required**
None (though you need to create a script canvas file to repro)

**Steps to reproduce**
1. In the editor, remove and then re-add an existing script canvas component (with a file reference) to an entity. Or disable, then re-enable it. 
2. Hit `Ctrl + S` to save.
3. The resulting LEVEL.prefab file contains the full path (minus drive letter, on Windows at least) within the `configuration.sourceHandle.path` and `propertyOverrides.source.path` values.

**Expected behavior**
File paths would be relative to the project.

**Actual behavior**
They are not relative to the project

**Screenshots/Video**
See above example file contents.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PS 
 - OS: Windows
 - Version: 10
 - GPU:  NVidia RTX 3070]
 - Memory: 32GB

**Comment by lumberyard-employee-dm** [comment]
@carlitosan 
This should be able to be fixed by updating the [SanitizePath](https://github.com/o3de/o3de/blob/development/Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp#L288-L292) function in the SourceHandle class to not use the AZ::IO::RelativePath function, but instead use the AssetSystemBus [GenerateRelativeSourcePath](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorAssetSystemAPI.h#L55-L63) function to return the best candidate relative path among the Asset Processor Scan Folders.
