### ISSUE TITLE
Terrain: Terrain World Renderer and Terrain World Debugger level components are not drawing terrain properly

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10083]
**Describe the bug**
Terrain drawn by the Terrain World Renderer level component is invisible, unless a PhysX Heightfield component entity is created on it, and a Game Mode is launched. Wireframe of the Terrain World Debugger is drawn only around boundaries of the terrain, but not separate colliders. It should be noted that the PhysX Heightfield Collider - Draw collider property, and the `physx_debug 1` Console command are drawing the collider wireframes properly.

**Prerequisites**
Terrain Gem enabled in the project.

**Steps to reproduce**
1. Create a new level.
2. Add the Terrain World, Terrain World Renderer, and Terrain World Debugger level components to the <level>.prefab.
3. Create an entity, add Axis Aligned Box Shape (Dimensions: X:5.0m; Y: 5.0m; Z: 5.0m), Terrain Layer Spawner, Terrain Height Gradient (add a Gradient Entity, and select any entity with the entity picker, e.g. Shader Ball), Terrain Physics Heightfield Collider, and PhysX Heightfield Collider (Draw collider enabled) components to it.
4. Place the entity created in step 3 so that it intersects the terrain boundaries (red wireframe).
5. Enter the Game Mode.

**Expected behavior**
Terrain is drawn constantly across the shown boundary. There's a red wireframe present on the collision regions from the Terrain World Debugger level component.

**Actual behavior**
Terrain is drawn only within the Heightfield entity after entering the Game Mode. The Terrain World Debugger level component is drawing only the terrain boundaries, and not wireframe on the collision areas.

**Video**

https://user-images.githubusercontent.com/86952082/173365484-461e4ce1-efe7-49a9-8528-af723371f650.mp4

**Found in Branch**
Development (47a2dc8)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by mbalfour-amzn** [comment]
Everything up through 0:45 in the video is "as designed" - the previous behavior of drawing a ground plane across the entire world was a bug. It should *only* draw terrain inside of terrain layer spawners, which is what you're now seeing.

There are a few bugs still being demonstrated in the video though:
* At 0:45, when the Terrain Layer Spawner is added, it has "Use Ground Plane" checked, which *should* draw a ground plane in the spawner box if no heights are provided. It currently does not do that.
* At 0:51, when the "Shader Ball" entity is selected as a gradient entity input to the Terrain Height Gradient List, the terrain becomes valid with a ground plane, which can be seen by the wireframe showing up. However, the rendered terrain mesh doesn't refresh itself to match. At this point, either we should continue to have the ground plane from the Terrain Layer Spawner, or we should continue to have no valid terrain. We shouldn't be in a state where the terrain suddenly becomes valid, and we also shouldn't be in a state where the mesh hasn't refreshed itself.

**Comment by mbalfour-amzn** [comment]
(See https://github.com/o3de/o3de/pull/9936 for the fix to only draw inside of terrain layer spawners)

**Comment by LB-ArturZieba** [comment]
"Use Ground Plane" setting verified as fixed on the Development (5dd4d9f) build. I have checked the Gradient Entity selection you have mentioned at 0:51 as well, and it does not seem to affect drawing of the terrain anymore. Thanks for the detailed breakdown of what exactly was wrong on the attached video! Please close the issue if there's nothing else to verify.
