### ISSUE TITLE
Bug Report: O3DE Editor's 'Help' search bar goes to incorrect website URL

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de#10122]
**Describe the bug**
Searching in the "Help" menu in the Editor does not lead to the correct URL.

**Steps to reproduce**
Search for something (e.g. "postfx") in the "Help" menu of the Editor.
  ![image](https://user-images.githubusercontent.com/75444793/173666712-38a6c821-5932-429f-9e68-17cb6c74b9df.png)

**Expected behavior**
Browser opens to URL: `https://www.o3de.org/search/?query=postfx`
![image](https://user-images.githubusercontent.com/75444793/173666814-8856f2b3-5d97-4410-8eee-2d1d98ea41e0.png)

**Actual behavior**
Browser opens to URL: `https://www.o3de.org/docs/?query=postfx`
![image](https://user-images.githubusercontent.com/75444793/173666967-6b4f31a6-744b-41b9-be21-2ba66443026c.png)

**Found in Branch**
Name of or link to the branch where the issue occurs.
`development`

**Desktop/Device (please complete the following information):**
-  OS: Windows

**Comment by pollend** [comment]
this was already resolved with this PR: https://github.com/o3de/o3de/pull/9939

**Comment by lmbr-pip** [comment]
@pollend Linked PR is marked closed rather than merged, is there a plan for a new PR?

**Comment by monroegm** [comment]
Fixed by #9939
