### ISSUE TITLE
Script Canvas:  every time undo, there will be one more slot in the outslot of MULTI_RESULTS_NODE

### ISSUE THREAD

**Issue by Hsuehnj** [o3de/o3de#10145]
**Describe the bug**
If there is MULTI_RESULTS_NODE in script, every time you operate Undo, there will be one more slot in the outslot of MULTI_RESULTS_NODE.

**Assets required**
NA

**Steps to reproduce**
1. Open Script Canvas Editor
2. Add node BoxCastWithGroup to script
3. Change the value of an input parameter
4. Undo the operation of step 3
5. there will be one more slot "Distance" in the OutSlots of node BoxCastWithGroup 

**Expected behavior**
The value of  input parameter restores, no change of OutSlots of node BoxCastWithGroup 

**Actual behavior**
Every time you operate Undo, there will be one more  slot "Distance" in the OutSlots of node BoxCastWithGroup.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/41571619/173838212-7ee45295-f905-4440-a388-9406e60c6c0f.png)

**Found in Branch**
releases/22.05.0

**Desktop/Device (please complete the following information):**
Device: PC,
OS: Windows
Version 10,
CPU Intel xeon
GPU NVidia RTX 5000
Memory 128GB

**Additional context**

**Comment by monroegm** [comment]
Routing to SIG-Simulation as this is a physics related node

**Comment by Hsuehnj** [comment]
https://github.com/o3de/o3de/pull/9318 has fixed the bug.
