### ISSUE TITLE
[Linux] Adding any component in Editor on non-ubuntu distributions causes unwanted duplicated components

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#10142]
**Describe the bug**
Ubuntu add a component at once one works, and the other Arch Linux/OpenSUSE distributions has two components at once

**Steps to reproduce**
1. Add a component 
2. Click select any component two is duplicated bug

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/173769963-dc06d410-f275-4997-a02e-7fcc8aa5faf6.mp4

**Found in Branch**
22.05.0

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Arch Linux
 - Version: latest

**Comment by lmbr-pip** [comment]
Tagged in both SIG/content and SIG/Platform here. Looks like it should be an issue for SIG/platform as it only occurs on some linux distributions, but will let SIGs decide.

**Comment by Darkinggq** [comment]
verified fixed (development 14076b4f932a768e9d12b041ca16a13903ac6be5)
checking distribution manjaro (arch linux) does not duplicate components, everything is good
