### ISSUE TITLE
Show/Hide and Lock/Unlock affect all prefab instances

### ISSUE THREAD

**Issue by monroegm** [o3de/o3de#10147]
**Describe the bug**
Show/Hide and Lock/Unlock affect all instances of the same prefab. These should be treated like transforms and always be unique per instance.

**Assets required**
N/A

**Steps to reproduce**
1. Create or instantiate a prefab with a visible model. One way to do this is to search for "_Box_1x1.fbx" in the Asset Browser and drag it into the viewport. Then right click on it and "Create Prefab..."
2. Duplicate the prefab (Ctrl+D)
3. Click "Show/Hide Entity" (eye icon) on one of the prefab instances.

**Expected behavior**
Only the prefab instance whose eye icon was clicked is hidden

**Actual behavior**
Both prefab instances are hidden

**Screenshots/Video**
https://user-images.githubusercontent.com/71404632/173885759-06e358b7-751d-4e98-8946-09c08afe2e9a.mp4

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Xeon E5-1650 v3
 - GPU: NVIDIA GeForce GTX 1080
 - Memory: 32GB

**Comment by AMZN-daimini** [comment]
Verified as fixed in latest development.
