### ISSUE TITLE
[Linux] Run project in O3DE display the problem display does not see anything

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#10140]
**Describe the bug**
Problem with black display when starting a project due to Vulkan (22.05.0 was fine)

**Steps to reproduce**
1. Run O3DE Editor
2. Black display

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/173762551-c7999907-b30b-42cd-94c2-ee632d415018.mp4

**Found in Branch**
development nightly build: 9ff52ad99bd737156be52667a7a6107de36a32d4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Arch Linux
 - Version: latest
 - GPU: AMD 5500 XT(8GB) Mesa 22.1.1

**Comment by lmbr-pip** [comment]
Graphics issue but on specific Linux distribution.

**Comment by byrcolin** [comment]
No longer the case
