### ISSUE TITLE
Feature Request - The ability for the material editor to use Packed Textures.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#10165]
**Is your feature request related to a problem? Please describe.**
Many material pipelines will pack many different textures into the individual channels of a texture.
![image](https://user-images.githubusercontent.com/87207603/174127376-5a15f01c-2508-46eb-830f-eb4f92f64da6.png)
In the above example, notice the use of three texture in one texture, split in the RGB channels. AO,Roughness and Metallic gray float 1 are divided into the 3 RGB channels.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/87207603/174131936-a7dcdf54-a84d-4386-8567-222f3ba6c380.png)
As shown above, A Texture Channel Drop Down Menu, You Can selected which channel target (RGB, R, G, B, A)

**Describe alternatives you've considered**
The alternative is to unpack textures and use them in O3DE. 

**Additional context**
Here is a sample packed texture, it is a Roughness / Height packed texture.:
![Char_materials_Rough_Height](https://user-images.githubusercontent.com/87207603/174126558-e671ccad-32db-4411-b52c-37dde938d942.png)

**Comment by gadams3** [comment]
The behavior and properties for each material are defined by the material type and referenced shaders. The material editor surfaces all the properties through the inspector and provides a preview for the final result. Support for packed textures would need to be implemented by each material type and shader for each texture input and sample. With material canvas, it will eventually be easier for users creating material types and materials to swizzle or redirect the channels of any color or texture sample. But that would only apply at the material type level and derived materials would still require the packed texture settings for every texture input to be customizable at the material level.

**Comment by galibzon** [comment]
This feature is in our roadmap. Worst case scenario will be released by mid 2023.

**Comment by yuyihsu** [comment]
Per @galibzon, this ticket will be addressed in Material Canvas.

**Comment by gadams3** [comment]
Material canvas now supports texture mapping but we still need to create a suite of material template types as feature rich as the rest of our PBR materials.
