### ISSUE TITLE
Hovering over certain Script Canvas nodes can cause brief visual glitches

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10188]
**Describe the bug**
If a Script Canvas node has an output pin, where a variable is assigned, hovering over it causes that output pin to flicker. It should be noted that on Linux the output pin seems to be displaced, while on Windows the node itself can shrink to its original size for a brief moment.

**Steps to reproduce**
1. Go to Tools > Script Canvas.
2. In the Script Canvas go to File > New Script.
3. Add a node that has an output pin with a slot for a variable (for example Length from the Math category) to the graph.
4. Create a variable that has the same type as the output pin of the node from step 3 (for example Number for the Length node).
5. Drag and drop the variable onto the slot next to the output pin.
6. Quickly hover over the node.

**Expected behavior**
Node does not change in appearance.

**Actual behavior**
Node has brief visual glitches.

**Videos**

https://user-images.githubusercontent.com/86952082/174309254-28f72944-8c2e-4e1a-a530-c5f870c7b935.mp4

https://user-images.githubusercontent.com/86952082/174309260-082bfe54-d729-41d7-8a63-bafd8a6f4db5.mp4

**Found in Branch**
Development (8d15edf)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by ParasiteSt** [comment]
This is actually more than a visual glitch, some nodes (like the switch node) with enough output pins when the visual glitch happens it makes it so you are not able to grab the output unless you wait on the node and slowly try to grab the output from the inside of the node out, so the glitch does not happen.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (4212e91) build on both Windows and Linux OS.
