### ISSUE TITLE
Certain GitHub O3DE repositories contain licenses named "Unknown" and are inconsistent

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10184]
**Describe the bug**

Multiple GitHub O3DE repositories contain one or two licenses named "Unknown", and are inconsistent in which other licenses are present.

Licenses in repositories:
* o3de/o3de (https://github.com/o3de/o3de): 
   * Unknown (https://github.com/o3de/o3de/blob/development/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/o3de/blob/development/LICENSE_APACHE2.TXT) 
   * MIT (https://github.com/o3de/o3de/blob/development/LICENSE_MIT.TXT)
* o3de/sig-build (https://github.com/o3de/sig-build):
   * Apache-2.0 license (https://github.com/o3de/sig-build/blob/main/LICENSE)
* o3de/o3de.org (https://github.com/o3de/o3de.org):
   * Unknown (https://github.com/o3de/o3de.org/blob/main/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/o3de.org/blob/main/LICENSE-APACHE2.txt)
   * MIT (https://github.com/o3de/o3de.org/blob/main/LICENSE-MIT.txt)
   * Unknown (https://github.com/o3de/o3de.org/blob/main/LICENSE-docs.md)
* o3de/sig-ui-ux (https://github.com/o3de/sig-ui-ux):
   * None present
* o3de/o3de-atom-sampleviewer (https://github.com/o3de/o3de-atom-sampleviewer):
   * Unknown (https://github.com/o3de/o3de-atom-sampleviewer/blob/development/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/o3de-atom-sampleviewer/blob/development/LICENSE_APACHE2.TXT)
   * MIT (https://github.com/o3de/o3de-atom-sampleviewer/blob/development/LICENSE_MIT.TXT)
* o3de/artwork (https://github.com/o3de/artwork):
   * Apache-2.0 license (https://github.com/o3de/artwork/blob/main/LICENSE) 
* o3de/sig-testing (https://github.com/o3de/sig-testing):
   * None present 
* o3de/tsc (https://github.com/o3de/tsc):
   * Apache-2.0 license (https://github.com/o3de/tsc/blob/main/LICENSE)
* o3de/community (https://github.com/o3de/community):
   * Apache-2.0 license (https://github.com/o3de/community/blob/main/LICENSE)
* o3de/sig-network (https://github.com/o3de/sig-network):
   * None present 
* o3de/o3de-multiplayersample (https://github.com/o3de/o3de-multiplayersample):
   * Unknown (https://github.com/o3de/o3de-multiplayersample/blob/development/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/o3de-multiplayersample/blob/development/LICENSE_APACHE2.TXT)
   * MIT (https://github.com/o3de/o3de-multiplayersample/blob/development/LICENSE_MIT.TXT)
* o3de/o3de-atomtest (https://github.com/o3de/o3de-atomtest) (Repository seems to be deprecated - "[DEPRECATED] This repository will be removed on 6/15/2022. Atom test project for the Open 3D Engine"):
   * Unknown (https://github.com/o3de/o3de-atomtest/blob/development/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/o3de-atomtest/blob/development/LICENSE_APACHE2.TXT)
   * MIT (https://github.com/o3de/o3de-atomtest/blob/development/LICENSE_MIT.TXT)
* o3de/o3de-netsoaktest (https://github.com/o3de/o3de-netsoaktest):
   * Unknown (https://github.com/o3de/o3de-netsoaktest/blob/development/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/o3de-netsoaktest/blob/development/LICENSE_APACHE2.TXT)
   * MIT (https://github.com/o3de/o3de-netsoaktest/blob/development/LICENSE_MIT.TXT)
* o3de/sig-core (https://github.com/o3de/sig-core):
   * None present 
* o3de/sig-release (https://github.com/o3de/sig-release):
   * None present
* o3de/3p-package-source (https://github.com/o3de/3p-package-source):
   * Unknown (https://github.com/o3de/3p-package-source/blob/main/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/3p-package-source/blob/main/LICENSE_APACHE2.TXT)
   * MIT (https://github.com/o3de/3p-package-source/blob/main/LICENSE_MIT.TXT)
* o3de/sig-security (https://github.com/o3de/sig-security):
   * None present
* o3de/sig-graphics-audio (https://github.com/o3de/sig-graphics-audio):
   * None present
* o3de/sig-content (https://github.com/o3de/sig-content):
   * None present
* o3de/ChatCambrioleur (https://github.com/o3de/ChatCambrioleur):
   * None present
* o3de/sig-simulation (https://github.com/o3de/sig-simulation):
   * Apache-2.0 license (https://github.com/o3de/sig-simulation/blob/main/LICENSE)
* o3de/o3de-azslc (https://github.com/o3de/o3de-azslc):
   * Unknown (https://github.com/o3de/o3de-azslc/blob/development/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/o3de-azslc/blob/development/LICENSE_APACHE2.TXT)
   * MIT (https://github.com/o3de/o3de-azslc/blob/development/LICENSE_MIT.TXT)
* o3de/sig-platform (https://github.com/o3de/sig-platform):
   * None present
* o3de/sig-docs-community (https://github.com/o3de/sig-docs-community):
   * Apache-2.0 license (https://github.com/o3de/sig-docs-community/blob/main/LICENSE)
* o3de/3p-package-scripts (https://github.com/o3de/3p-package-scripts):
   *  Unknown (https://github.com/o3de/3p-package-scripts/blob/main/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/3p-package-scripts/blob/main/LICENSE_APACHE2.TXT)
   * MIT (https://github.com/o3de/3p-package-scripts/blob/main/LICENSE_MIT.TXT)
* o3de/DirectXShaderCompiler (https://github.com/o3de/DirectXShaderCompiler):
   * Unknown (displayed as "View license") (https://github.com/o3de/DirectXShaderCompiler/blob/master/LICENSE.TXT) 
* o3de/antlr4 (https://github.com/o3de/antlr4):
   * Unknown (displayed as "View license") (https://github.com/o3de/antlr4/blob/master/LICENSE.txt)
* o3de/sig-operations (https://github.com/o3de/sig-operations):
   * Apache-2.0 licence (https://github.com/o3de/sig-operations/blob/main/LICENSE)
* o3de/sample-code-gems (https://github.com/o3de/sample-code-gems):
   * None present 
* o3de/GnomebodysHome (https://github.com/o3de/GnomebodysHome):
   * Unknown (https://github.com/o3de/GnomebodysHome/blob/main/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/GnomebodysHome/blob/main/LICENSE_APACHE2.TXT)
   * MIT (https://github.com/o3de/GnomebodysHome/blob/main/LICENSE_MIT.TXT) 
* o3de/rfcs (https://github.com/o3de/rfcs):
   * None present 
* o3de/Planet_Storm (https://github.com/o3de/Planet_Storm):
   * Unknown (https://github.com/o3de/Planet_Storm/blob/main/LICENSE.txt)
   * Apache-2.0 (https://github.com/o3de/Planet_Storm/blob/main/LICENSE_APACHE2.TXT)
   * MIT (https://github.com/o3de/Planet_Storm/blob/main/LICENSE_MIT.TXT)
* o3de/qt5 (https://github.com/o3de/qt5):
   * Unknown (https://github.com/o3de/qt5/blob/dev/LICENSE.FDL)
   * Unknown (https://github.com/o3de/qt5/blob/dev/LICENSE.GPL3-EXCEPT)
   * Unknown (https://github.com/o3de/qt5/blob/dev/LICENSE.GPLv2)
   * Unknown (https://github.com/o3de/qt5/blob/dev/LICENSE.GPLv3)
   * Unknown (https://github.com/o3de/qt5/blob/dev/LICENSE.LGPLv21)
   * Unknown (https://github.com/o3de/qt5/blob/dev/LICENSE.LGPLv3)
   * Unknown (https://github.com/o3de/qt5/blob/dev/LICENSE.QT-LICENSE-AGREEMENT) 
* o3de/qtbase (https://github.com/o3de/qtbase):
   * Unknown (https://github.com/o3de/qtbase/blob/dev/LICENSE.FDL)
   * GPL-2.0 (https://github.com/o3de/qtbase/blob/dev/LICENSE.GPL2)
   * GPL-3.0 (https://github.com/o3de/qtbase/blob/dev/LICENSE.GPL3)
   * Unknown (https://github.com/o3de/qtbase/blob/dev/LICENSE.GPL3-EXCEPT)
   * LGPL-3.0 (https://github.com/o3de/qtbase/blob/dev/LICENSE.LGPL3)
   * Unknown (https://github.com/o3de/qtbase/blob/dev/LICENSE.LGPLv3)
   * Unknown (https://github.com/o3de/qtbase/blob/dev/LICENSE.QT-LICENSE-AGREEMENT)
* o3de/qtimageformats (https://github.com/o3de/qtimageformats):
   * Unknown (https://github.com/o3de/qtimageformats/blob/dev/LICENSE.FDL)
   * GPL-2.0 (https://github.com/o3de/qtimageformats/blob/dev/LICENSE.GPL2)
   * GPL-3.0 (https://github.com/o3de/qtimageformats/blob/dev/LICENSE.GPL3)
   * Unknown (https://github.com/o3de/qtimageformats/blob/dev/LICENSE.GPL3-EXCEPT)
   * Unknown (https://github.com/o3de/qtimageformats/blob/dev/LICENSE.GPLv2)
   * Unknown (https://github.com/o3de/qtimageformats/blob/dev/LICENSE.GPLv3)
   * LGPL-3.0 (https://github.com/o3de/qtimageformats/blob/dev/LICENSE.LGPL3)
   * Unknown (https://github.com/o3de/qtimageformats/blob/dev/LICENSE.LGPLv21)
   * Unknown (https://github.com/o3de/qtimageformats/blob/dev/LICENSE.LGPLv3)
* o3de/wikicollection (https://github.com/o3de/wikicollection):
   * Repository empty
* o3de/.github (https://github.com/o3de/.github):
   * Apache-2.0 license (https://github.com/o3de/.github/blob/main/LICENSE) 
* o3de/SPIRV-Cross (https://github.com/o3de/SPIRV-Cross):
   * Apache-2.0 license (https://github.com/o3de/SPIRV-Cross/blob/master/LICENSE) 

For more information, please refer to the **Screenshots** section.

**Steps to reproduce**
1. Go to https://github.com/orgs/o3de/repositories?page=1 (O3DE GitHub repositories page).
2. Open each available repository, and verify their licenses in their About section.

**Expected behavior**
All licenses are named, and consistent with each other.

**Actual behavior**
Some of the licenses are named "Unknown", and the licenses are inconsistent between different repositories.

**Screenshots**
Example of licenses in the repository's About section:
![RepositoryLicenses](https://user-images.githubusercontent.com/86952082/174244889-62763ff3-3664-48d1-bf55-e53467ef1811.PNG)
When opened:
![RepositoryLicensesDetails](https://user-images.githubusercontent.com/86952082/174244913-01ed2e5f-ed62-4a9a-9d7a-1c3c0643ab41.PNG)

**Found in Branch**
Development (8d15edf) (N/A)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by amzn-pratikpa** [comment]
@OBWANDO, tagging you for visibility and input on how to deal with licenses for code which has been forked.

**Comment by lumberyard-employee-dm** [comment]
Hello @OBWANDO  any updates for this ticket on Licensing.
Especially for licenses of forked repositories.

**Comment by lumberyard-employee-dm** [comment]
Adding the TSC tag for now, as I don't believe we have a tag for licensing.

**Comment by lmbr-pip** [comment]
Tagging in sig/release as issue needs to be owned by SIG (as TSC has no issue audit process). @jeremyong as TSC chair, who should own this?

**Comment by jeremyong-az** [comment]
This issue was discussed at a prior TSC meeting with @lumberyard-employee-dm and I am closing this issue. All licenses have already been vetted by LF legal prior to O3DE's release, including copy left dependencies such as Qt that are distributed in a manner restricted to tooling. No other dependencies with such license restrictions have been added since the O3DE release.
