### ISSUE TITLE
SpawnableUtils::SortEntitiesByTransformHierarchy fails to sort hierarchies of depth greather than 2

### ISSUE THREAD

**Issue by AMZN-puvvadar** [o3de/o3de#10196]
**Describe the bug**
Given a prefab of the following construction
![image](https://user-images.githubusercontent.com/32854265/174402693-68e22ec9-cd2a-4954-b86c-99ec32319ab5.png)
such that Hierarchy Root looks like
![image](https://user-images.githubusercontent.com/32854265/174402790-88e08712-2103-480c-8e65-8d2a957163e5.png)
and all other entities look like
![image](https://user-images.githubusercontent.com/32854265/174402817-0953a808-4327-4a59-a287-c8606c575f8a.png)

SpawnableUtils::SortEntitiesByTransformHierarchy should produce the sort order
[Hierarchy, Root, Child, Child 1, Child 2]

instead it produces the order
[Hierarchy, Child 2, Root, Child, Child 1]

This causes downstream failures in engine when attempting to setup hierarchical entities.

**Assets required**
A prefab of the above construction used in the MultiplayerSample project (https://github.com/o3de/o3de-multiplayersample)

**Steps to reproduce**
1. Setup AssetBuilder for debugging of the prescribed prefab
2. Place a breakpoint in PrefabCatchmentProcessor line 96 `SpawnableUtils::SortEntitiesByTransformHierarchy(*spawnable);`
3. Step into the function and observe sorted order

**Expected behavior**
Sorted order is [Hierarchy, Root, Child, Child 1, Child 2]

**Actual behavior**
The sort order produced is [Hierarchy, Child 2, Root, Child, Child 1]

Note that this Prefab was created initially without Child 2. Child 2 was then added after the fact and the prefab was resaved. This may be a factor in reproduction. A copy of the failing prefab can be supplied on request.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
This issue was discovered while investigating https://github.com/o3de/o3de/issues/10152

**Comment by srikappa-amzn** [comment]
Couple of things to investigate while fixing this bug:

1. Does this happen for any prefab or  does it happen only when there are network components on the entities. This is important to find out because the prefab processing stack builds a network spawnable containing entities with network components. So, this might be an issue of some missing logic in network spawnable generation
2. Add tests to validate the order of entities in the spawnable since that is apparently important to other systems. (Not sure why that is important- try to find this as well)

**Comment by AMZN-puvvadar** [comment]
> Couple of things to investigate while fixing this bug:
> 
> 1. Does this happen for any prefab or  does it happen only when there are network components on the entities. This is important to find out because the prefab processing stack builds a network spawnable containing entities with network components. So, this might be an issue of some missing logic in network spawnable generation
> 2. Add tests to validate the order of entities in the spawnable since that is apparently important to other systems. (Not sure why that is important- try to find this as well)

I can add some context to these.

1. I haven't confirmed this but I would think it's any prefab given that this function isn't unique to Networking.
2. The order is important due to how parent - child relationships are formed for entities. A child entity will locate its parent by Entity ID search. If the parent is not yet activated, this fails entirely which can lead to the child being orphaned. In the example posted in the bug, Child 2 will never locate its parent meaning it never even makes it into the hierarchy during runtime. This affects networking directly during hierarchy rebuild but likely means that the state of the prefab instance is likely never correct.
