### ISSUE TITLE
RHI::ComparisonFunc Not Reflected to BehaviorContext

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#10203]
**Describe the bug**
It appears that RHI::ComparisonFunc is not reflected to BehaviorContext, and is therefore not available to lua material functors or other scripts.

**Steps to reproduce**
This was noticed by code inspection. 

**Expected behavior**
ComparisonFunc should be handled more like other render state structs in RenderStates.h, like StencilOp.

**Actual behavior**
ComparisonFunc is declared as an enum class and reflected to SerializeContext manually in ReflectSamplerStateEnums(). There is no reflection to BehaviorContext. If you search for StencilOp_Invalid you will find it in StencilOp_Invalid.names. But if you search for ComparisonFunc_Invalid there are no hits.

**Comment by gadams3** [comment]
I noticed this while reflecting other rhi classes to edit and behavior context. If all of the enums are updated to use AZ_ENUM_CLASS_WITH_UNDERLYING_TYPE and AZ_ENUM_DEFINE_REFLECT_UTILITIES then functions will be generated to automatically register them with edit and behavior context. I also added a new utility function to register them with edit context with a simple template function call. 

See 
https://github.com/o3de/o3de/pull/10183
https://github.com/o3de/o3de/pull/10204
https://github.com/o3de/o3de/blob/development/Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/RenderStates.h#L20-L33
https://github.com/o3de/o3de/blob/development/Gems/Atom/RHI/Code/Source/RHI.Reflect/RenderStates.cpp#L17-L45
