### ISSUE TITLE
Editor crashes when clicking "shape" button in the Shape Example (C++) tool while no level is loaded

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#10213]
**Describe the bug**
After adding Shape Example (C++) tool from https://github.com/o3de/sample-code-gems while no level is loaded, clicking the "shape" button in said tool, results in a crash.

**Steps to reproduce**
1. Open CMD in the o3de directory.
2. Execute the following command: `scripts\o3de.bat create-gem -gp C:\Gems\CppTool --template-name CppToolGem` to create a new Gem.
3. Execute the following command: `scripts\o3de.bat register -gp C:\Gems\CppTool -espp <path_to_project>` to register the Gem into the Project.
4. Open the Project Manager from the o3de directory.
5. Navigate to Configure Gems... page for the Project.
6. Search for the newly created Gem and enable it in the Project.
7. Press Save.
8. Rebuild the Project.
9. Open the project without loading any level.
9. Go to Tools > Shape Example (C++).
10. Click any shape button.

**Expected behavior**
Editor remains stable and in the console there is an information that entity cannot be created due to no level being loaded.

**Actual behavior**
Editor crashes.

**Video**

https://user-images.githubusercontent.com/100559077/174594410-3420adde-ee7b-4f11-8f8e-4964c61f1177.mp4

**Additional files**
[Editor.log](https://github.com/o3de/o3de/files/8940320/Editor.log)
[error.log](https://github.com/o3de/o3de/files/8940321/error.log)
[crashdmppart1.zip](https://github.com/o3de/o3de/files/8940404/crashdmppart1.zip)
[crashdmppart2.zip](https://github.com/o3de/o3de/files/8940406/crashdmppart2.zip)
[crashdmppart3.zip](https://github.com/o3de/o3de/files/8940407/crashdmppart3.zip)

**Found in Branch**
Development (6f5e553)

**Desktop:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Comment by LB-BartoszCwiek** [comment]
The same crash occurs when trying to create an entity by executing one of scripts from Python Scripts tool.
[error.log](https://github.com/o3de/o3de/files/9001095/error.log)
[Editor.log](https://github.com/o3de/o3de/files/9001097/Editor.log)

**Comment by LB-HubertUberman** [comment]
Verified as fixed in Stabilization (https://github.com/o3de/o3de/commit/021d32ab66ee4daebfe55eb7804b3b6bba1d9ed9) and development (https://github.com/o3de/o3de/commit/511a88c6ab7a3ed54898f568816e76708a6c9455) branches.
