### ISSUE TITLE
Prefabs: Creating a new entity at the root of a level causes level components to deactivate / activate

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#10215]
**Describe the bug**
When creating a new entity at the root of a level in the Editor, all existing level components deactivate and reactivate. If the new entity is created underneath any other entity this doesn't occur.

**Steps to reproduce**
1. Open the Editor.
2. Create a new level.
3. Add Terrain World, Terrain World Renderer components to the level.
4. Create a new entity at (512, 512, 20) with:
- Axis Aligned Bounding Box of (1024, 1024, 5) in size.
- Terrain Layer Spawner
- Terrain Height Gradient List
5. Create an entity with a Constant Gradient on it.
6. Add an entry to the Terrain Height Gradient List and point it at the Constant Gradient
7. Create a new entity in the level.

**Expected behavior**
The new entity is created without causing the entire terrain to refresh.

**Actual behavior**
The terrain refreshes, because the Terrain World and Terrain World Renderer components are deactivated and reactivated.

**Screenshots/Video**
The flashing of the terrain quad comes about from the level components getting deactivated:
https://user-images.githubusercontent.com/82224783/174642957-30f73061-54a3-4202-a946-66c6437202b4.mp4

In contrast, creating an entity that isn't at the root of the level doesn't deactivate the level components:
https://user-images.githubusercontent.com/82224783/174643168-a344095a-4333-413e-84fd-daaf550980d7.mp4

**Found in Branch**
Development

**Comment by forkercat** [comment]
Update: "Add Entity" workflow is updated in #11160. Will update the PR accordingly.

**Comment by forkercat** [comment]
Update: The refresh no longer exists as the new workflow has triggered preemptive cache update already.

**Comment by forkercat** [comment]
Closed as it is fixed in #11160.
