### ISSUE TITLE
Request for a "kind/project-management" label in Github

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#10221]
**Is your feature request related to a problem? Please describe.**
We have a member of the community interested in contributing towards project management work for O3DE. We do not currently have a way to track this sort of work across the project. As a result, we do not have any "queue" of this type of work that we can point someone to so they may begin contributing. 

**Describe the solution you'd like**
A new O3DE-wide label "kind/project-management" : Categorizes issue or PR as related to project management.

**Describe alternatives you've considered**
Ad-hoc posting to Discord "Does anyone need project management assistance?" when a PM wants to offer their services. The problem with this is 1) it does not give us a way to capture project management needs of the project on an ongoing basis 2) it relies on sigs monitoring Discord. This also runs the risk of having community members feel like there's no place for them since they are having to ask or "pull" the information. This doesn't seem like a good experience, especially for new members.

**Additional context**
See message link at https://discord.com/channels/805939474655346758/821692567355523152/984191752137212014

**Comment by jeremyong-az** [comment]
Closing, as discussed before on the June 21 meeting, process and project management-specific issues/discussion should find a home in the community repo. Thanks!
