### ISSUE TITLE
[GraphModel] Several instances of AZ_CRC macro are actually the wrong CRC

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#10234]
This is a problem in the code, but does not appear to be generating errors at the moment.

Summary:

The AZ_CRC macro comes in two forms
AZ_CRC("x")
or
AZ_CRC("x",y)

The former will call a runtime CRC32 function on the string x, and return the uint32 CRC32 of it lowercase, at runtime, coming at a runtime cost.

The latter actually just returns y. "x" is unused. Its supposed to be generated by a tool which calculates the CRC of "x" and adds the y parameter to the code, so as to avoid a runtime CRC computation.

That tool is defunct. NOw we use AZ_CRC_CE("x") which does the CRC in the compiler as a constexpr.

You can verify that the below are wrong by using the lowercase of the string in any online crc32 generator.

Problem: Due to copy and paste or people modifying the string without recalculating the CRC, a lot of CRCs in the code are now incorrect. These should be updated to not have the second term and instead use just AZ_CRC_CE(...)

````
CRC32("shadercanvas") = 0x0a1dff96 MISMATCH! AZ_CRC("ShaderCanvas", 0xa6d1a85a) in file Gems/GraphModel/Code/Include/GraphModel/Integration/NodePalette/InputOutputNodePaletteItem.h
CRC32("shadercanvas") = 0x0a1dff96 MISMATCH! AZ_CRC("ShaderCanvas", 0xa6d1a85a) in file Gems/GraphModel/Code/Include/GraphModel/Integration/NodePalette/ModuleNodePaletteItem.h
CRC32("shadercanvas") = 0x0a1dff96 MISMATCH! AZ_CRC("ShaderCanvas", 0xa6d1a85a) in file Gems/GraphModel/Code/Include/GraphModel/Integration/NodePalette/StandardNodePaletteItem.h
````

**Comment by Mattt47** [comment]
so basically  ` AZ_CRC("ShaderCanvas", 0xa6d1a85a)` should be replaced with  `AZ_CRC_CE("shadercanvas")` ??

**Comment by mprettner-huawei** [comment]
This issue was made obsolete with #18120.
