### ISSUE TITLE
Editor crashes when ending Game Mode in a Slice level

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#10261]
**Describe the bug**
When using the Editor in slice mode, exiting Game Mode results in a crash.

**Steps to reproduce**
1. Open the Editor in slice mode (go to `YourProject\user\Registry\editorpreferences.setreg` and change `Amazon/Preferences/EnablePrefabSystem` to false);
2. Create a new level or open an existing one;
3. Start Game Mode with the toolbar button, the file menu item, or via Ctrl+G;
4. Close Game Mode by pressing Esc

**Expected behavior**
Game Mode is ended correctly and the user can control the Editor again.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**
![GameModeSliceCrash](https://user-images.githubusercontent.com/82231674/174921771-21223b52-a1f2-46be-bbe4-ebbab41dd99d.gif)

**Found in Branch**
Latest development

**Additional context**
The snippet that crashes is in `\\Code\Framework\AzToolsFramework\AzToolsFramework\Viewport\LocalViewBookmarkLoader.cpp`
```
    LocalViewBookmarkComponent* LocalViewBookmarkLoader::FindOrCreateLocalViewBookmarkComponent()
    {
        auto prefabEditorEntityOwnershipInterface = AZ::Interface<PrefabEditorEntityOwnershipInterface>::Get();
        const AZ::EntityId containerEntityId = prefabEditorEntityOwnershipInterface->GetRootPrefabInstance()->get().GetContainerEntityId();
```

This function should actually check whether `prefabEditorEntityOwnershipInterface ` is initialized correctly, since the interface is not handled in Slice mode. Unsure if the ViewBookmark system is actually meant to be running at all in Slice mode, actually, so just disabling it in those instances may be the fastest route.

**Comment by hultonha** [comment]
Thanks for logging this @AMZN-daimini, I'll see if I can take a look later in the week or early next week. Cheers!
