### ISSUE TITLE
[Linux] Aws Resource Mapping Tool has improper name in the taskbar thumbnail preview

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#10298]
**Describe the bug**
There is an inconsistency between Windows version, where taskbar thumbnail preview of the Aws Resource Mapping Tool is named Resource Mapping, while on Linux it is resurce_mapping_tool.py

**Steps to reproduce**
1. Go to AWS > Aws Resource Mapping Tool.
2. Hover over the said tool icon on the taskbar.

**Expected behavior**
Aws Resource Mapping Tool's taskbar thumbnail preview is named Resource Mapping.

**Actual behavior**
Aws Resource Mapping Tool's taskbar thumbnail preview is named resurce_mapping_tool.py

**Screenshots**
Windows: 
![image](https://user-images.githubusercontent.com/100559077/175276724-48a80020-7c10-4f49-b649-df5a7c4caca6.png)

Linux:
![image](https://user-images.githubusercontent.com/100559077/175276765-0a176c06-0aff-4175-916b-577c68150f90.png)

**Found in Branch**
Development (ce30d41)

**Desktop:**
- Device: PC
- OS: Ubuntu 20.04.4 LTS
- Version: Ubuntu 20.04.4 LTS
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Comment by lmbr-pip** [comment]
Am assuming this how we fork the python tool under the hood on these platforms.

Note: Launching the tool is also broken on Linux currently: https://github.com/o3de/o3de/issues/14957
