### ISSUE TITLE
Default Procedural Prefab for multiple_mesh_multiple_material.fbx is incorrect

### ISSUE THREAD

**Issue by AMZN-stankowi** [o3de/o3de#10291]
**Describe the bug**
The default procedural prefab generated for the multiple_mesh_multiple_material.fbx has incorrect placement for the azmodels within it.

**Assets required**
I reproduced this with the FBX file in this folder, minus the assetinfo file https://github.com/o3de/o3de/tree/development/AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshTwoMaterial
[MultipleMeshesMultipleMaterials.zip](https://github.com/o3de/o3de/files/8961354/MultipleMeshesMultipleMaterials.zip)

**Steps to reproduce**
This bug seems specific to this FBX file, I've not seen it repro in other files.

1. Place the associated FBX and PNG in AutomatedTesting somewhere that will get processed by the Asset Processor.
2. Make sure Asset Processor processes them.
3. Launch the Editor
4. In the Asset Browser, locate the FBX file.
5. Create an entity in the outliner that references the AZ Model for the primary default mesh group of this FBX file (multiple_mesh_multiple_material.azmodel)
6. Notice that the azmodel contains both meshes, the cube and the cylinder, offset from each other, as in this screenshot. 
![image](https://user-images.githubusercontent.com/4838196/175141053-8e849660-1e54-4671-9d78-a508aea5994e.png)
7. Right click in the Outliner and Instantiate Procedural Prefab
8. Select the multiple_mesh_multiple_material_fbx.procprefab file to instantiate
9. Look at the instantiate prefab in the viewport, and notice that the cylinder and cube overlap.
![image](https://user-images.githubusercontent.com/4838196/175141279-520e3916-18f7-46a7-bb0b-b0da13b7cac3.png)

**Expected behavior**
The cube and cylinder are offset from each other in the procedural prefab, matching their positions in the source FBX file and the default mesh group.

**Actual behavior**
The cube and cylinder overlap with each other in the procedural prefab.

**Screenshots/Video**
Attached above

**Found in Branch**
A branch that last merged from Development at https://github.com/o3de/o3de/commit/27a9f7fea6c1babb42d0fb388fa919c6a201729e

**Desktop/Device (please complete the following information):**
Device: PC
OS: Windows
Version 10
CPU Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz 3.10 GHz
GPU RTX 2070 Super
Memory 32 GB

**Additional context**
N/A

**Comment by jackalbe** [comment]
https://github.com/o3de/o3de/pull/10217 should fix this
