### ISSUE TITLE
Building engine fails due to incorrect version of numpy package

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de#10325]
**Describe the bug**
Setting up O3DE from Github using the [following documentation](https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/) fails due to incorrect version of numpy package. The following error is displayed during package downloading:

![Numpy error](https://user-images.githubusercontent.com/99716227/175511337-d7bd51b6-47b2-4aa5-9ad5-13f4c5e60a11.PNG)

As for the 1.22 version of numpy, the [release notes]( https://numpy.org/devdocs/release/1.22.0-notes.html) states that the python 3.7 is not supported anymore and a higher version is needed.
Building the engine afterwards results in error being displayed, blocking further progress.

![build error](https://user-images.githubusercontent.com/99716227/175511377-a3125ff6-7293-4ce4-9db8-3c9f037e6e1f.PNG)

It should be noticed that there is a workaround. After reverting changes made in this commit: https://github.com/o3de/o3de/commit/0a016131bd6665439dad278650686546e1feb868 the building ends successfully.

Additionally, when updating already installed engine, the numpy error is displayed but building is successful and Editor is functional.

**Steps to reproduce**
1. Clone your O3de repository and follow the build documentation up until you have to use the `python\get_python.bat`.
2. Use the `python\get_python.bat` and observe the errors.
3. Continue the steps and input the Cmake command for building the engine.

**Expected behavior**
Building the engine ends successfully and all of the packages are downloaded without issues.

**Actual behavior**
Error is displayed blocking further building.

**Found in Branch**
Development (42d917e)

**Desktop/Device:**
• Device: PC
• OS: Windows
• Version: 10
• CPU Intel Core i7-9700K
• GPU Nvidia GeForce RTX 2070
• Memory 16GB

**Comment by amzn-changml** [comment]
This was discovered as a bug in the cmake build script for `LYPython.cmake`. Will file a bug for that one.

Short term, the commit has been reverted and merged: https://github.com/o3de/o3de/pull/10327

**Comment by amzn-pratikpa** [comment]
Bug has been resolved by amzn-changml's PR. Closing for now.
