### ISSUE TITLE
Can't install the engine.

### ISSUE THREAD

**Issue by e2002e** [o3de/o3de#10361]
I installed the .deb archive from your website but dpkg cannot configure it and returns 1.
dpkg.log simply restates that with no further explanations.
```
uname -a
Linux ideapad3 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Zorin OS 16.1 x64

o3de_2205_0

**Comment by monroegm** [comment]
Removing needs-sig as this issue now has several SIGs applied to it

**Comment by byrcolin** [comment]
Zorin is not currently an officially supported platform. Please feel free to add support, but this is not an officially supported platform.
