### ISSUE TITLE
Actor Skin Attachment crash if you pick the Target Enitiy as itself, LOOP of death crashes o3de editor.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#10373]
**Describe the bug**
Actor Skin Attachment crash if you pick the Target Entity as itself, LOOP of death crashes o3de editor.

Please see example... at the end of the video O3DE is unresponsive and will eventually crash after a period of time.

https://user-images.githubusercontent.com/87207603/175976639-2b1b373b-34de-44ae-b9d1-6a6ce3228c57.mp4

**Steps to reproduce**
1. Go to a Actor and attach an Skin Attachment to the Actor
2. Click on Target Entity and Select itself as the target.

**Expected behavior**
Maybe a pop-up warning that this is a loop dependency, or maybe just do not allow this to take place.

**Actual behavior**
A loop of death this will eventually crashing the editor.

**Found in Branch**
Nightly 6-26-2022

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I9-9900k
 - GPU NVidia RTX 2080ti
 - Memory [e.g. 16GB]

**Additional context**

**Comment by GraphiteSIX** [comment]
Seems the same issue as #9703 there is a message in the log but the exception is not caught to prevent a crash.

**Comment by lgleim** [comment]
@amzn-jillich Could you have a quick look at this, please?

**Comment by amzn-rhhong** [comment]
![ezgif-5-013a41a7e8](https://user-images.githubusercontent.com/69218254/182272586-c54b0f36-23e1-4b50-bcb3-7d1a9d5bb666.gif)
I think the bug is fixed with https://github.com/o3de/o3de/issues/9703

**Comment by lgleim** [comment]
@shawstar Would you mind verifying that https://github.com/o3de/o3de/pull/10385 fixed this issue for you?

**Comment by hultonha** [comment]
@shawstar Please see earlier comments, would you please be able to verify if this issue is fixed? Thanks!

**Comment by shawstar** [comment]
This is now fixed, you are not able to target itself. :)

**Comment by amzn-jillich** [comment]
Thanks for verifying @shawstar! Closing the ticket.
