### ISSUE TITLE
test_Multiplayer_SimpleNetworkLevelEntity failed repeatedly in both development and AR

### ISSUE THREAD

**Issue by greerdv** [o3de/o3de#10392]
https://jenkins.build.o3de.org/job/O3DE/job/development/2616/
https://jenkins.build.o3de.org/job/O3DE/job/development/2617/
https://jenkins.build.o3de.org/job/O3DE/job/development/2618/
https://jenkins.build.o3de.org/job/O3DE/job/development/2619/
https://jenkins.build.o3de.org/job/O3DE/job/development/2620/

as well as multiple AR runs all failed on this test on both windows and linux with 

[2022-06-27T19:07:13.661Z] E   [FAILED ] Failure: Failed to find expected line: Script: SimpleNetworkLevelEntity: On Graph Start

**Comment by lmbr-pip** [comment]
All the multiplayer tests have moved to sandbox. Resolving as per https://github.com/o3de/o3de/pull/10434
