### ISSUE TITLE
Script Canvas graphs saved in wrong location

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#10398]
**Describe the bug**
When attempting to save a Script Canvas graph, the popup Save As... window opens the folder the build is in, instead of the folder the project is located in. When trying to save the graph in that location, an error message pops up and the file is not saved. If the user navigates to the folder the project is located in and attempts to save there, the file seems to have saved correctly, and Script Canvas shows a notification that the file was saved. However, the file is not actually saved on disk. The issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Open Script Canvas.
2. Create a new script.
3. Navigate to File>Save or File>Save As...
4. In the popup Save As... window observe the folder the file is being saved in and click Save.
5. Repeat step 3.
6. In the popup Save As... window navigate to the project folder and click Save.

**Expected behavior**
The file is saved.

**Actual behavior**
After step 4, an error window pops up, with the message "Failed to save Untitled-1^: Failure to create temporary file name". The file is not saved. After step 6, there are no errors and a notification pops up saying that the file was saved, but the file is not actually saved.

**Video**

https://user-images.githubusercontent.com/99388484/176196931-217ccccb-8313-4ce4-8d5c-90c5784f765d.mp4

**Found in Branch**
Development (5b058c4)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by LB-ArturZieba** [comment]
Reopening the issue. This issue does not occur on Windows, however it is still active on Linux. Verified on the Development (9a3a99f) build.

**Comment by robhaco** [comment]
Still seeing this on Windows as of commit c24bd0dbc5d from earlier today.

**Comment by LB-KatarzynaDylska** [comment]
Issue verified as fixed on the Development (59df478) build.
