### ISSUE TITLE
Selecting AcesLut Tone Mapping crashes the Material Editor

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#10396]
**Describe the bug**
In the Material Editor, selecting AcesLut in the Tone Mapping menu results in a crash of the Material Editor. The O3DE Editor remains stable. Other Tone Mapping settings do not cause this issue. The issue does not occur on Linux.

**Steps to reproduce**
1. Open the Material Editor.
2. Click the Tone Mapping button in the Material Editor toolbar.
3. Select AcesLut from the dropdown menu.

**Expected behavior**
Tone mapping is changed to AcesLut, the Material Editor remains stable.

**Actual behavior**
The Material Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/99388484/176155055-5a8a0066-dc23-4136-96d7-b2bcf7fc3a60.mp4

**Found in Branch**
Development (5b058c4)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB
 
 **Additional context**
 
 [MaterialEditor.log](https://github.com/o3de/o3de/files/9000048/MaterialEditor.log)

**Comment by gadams3** [comment]
This is not happening on latest development branch

**Comment by LB-KatarzynaDylska** [comment]
Verified that the issue no longer occurs on Development (db9d67d).
