### ISSUE TITLE
The Camera Rig Component is not working as expected.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#10405]
**Describe the bug**
The Camera Rig Component is not working as expected It's hard to really explain what is wrong.. it seems like everything is not working as expected. 

**Assets required**
Video of a typical set-up and results. 

https://user-images.githubusercontent.com/87207603/176256775-d941ed15-906c-4f5b-b8dc-ca1cb2f47697.mp4

**Steps to reproduce**
1. Select Camera Entity
2. Click on Add Camera Rig Component.
3.Press Play

**Expected behavior**
The Camera Component will look at and follow the character with an offset

**Actual behavior**
The Camera Component behaves unexpectedly. 

**Found in Branch**
Nightly 6-28-2022

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS:  Windows
 - Version 10
 - CPU Intel I9-9900k
 - GPU NVidia RTX 2080ti
 - Memory [e.g. 16GB]

**Additional context**

**Comment by shawstar** [comment]
Update: The Camera rig will work... but not if the Character is in a Prefab, testing with script canvas also, I can not get the Transform movement from an Entity if its a prefab only if its a normal entity. After detaching the prefab from the Entity, it all started to work. 
![image](https://user-images.githubusercontent.com/87207603/176270326-0615640a-76cf-433f-b376-4fb4f372e8da.png)
See Movie:

https://user-images.githubusercontent.com/87207603/176270395-ab343449-b37a-423a-be83-814f26ceddfb.mp4

**Comment by hultonha** [comment]
Adding sig/graphics-audio to check if they own the Camera Rig component - this isn't something owned by sig-content or sig-simulation at the moment

**Comment by lgleim** [comment]
Given that the component apparently works as expected without prefabs, we assign the `feature/prefabs` label and refer this issue to  `sig/content` for further investigation.

**Comment by srikappa-amzn** [comment]
Update : Was able to reproduce this. To be able to see the issue in action, it'll help to have a character/object in the level that can be moved with user input. As the character moves, the camera should follow him. The issue is that if the camera rig component targets the container entity of the prefab that has the character, it doesn't follow the character. Whereas if the camera rig component targets a non-prefab entity, it works. So it looks like when entering game mode, the transforms on the container entity might be being set incorrectly in the spawnable. Needs further investigation.

**Comment by forkercat** [comment]
Update: Was able to reproduce this. It is necessary to set up with user input as srikappa-amzn mentioned above. I verified that the _CameraRigComponent_ and _AcquireByEntityId::AcquireTarget_ work as expected. In the function, it is trying to retrieve the target transform but it is always returning the same transform.

```cpp
AZ::TransformBus::EventResult(targetsTransform, m_target, &AZ::TransformInterface::GetWorldTM);
```

However, the camera component can capture the initial transform which means the camera is able to focus on the target on game mode start. It is not updated correctly later. Will do more investigation in spawnable stuff.

fyi CameraRigComponent Configuration:

<img src="https://user-images.githubusercontent.com/11157226/183713226-99992393-2408-40ac-8c8e-633b054ba6c5.png" height=220px>

**Comment by forkercat** [comment]
**Update:** Tried digging into spawnable but didn't find useful info yet. I was thinking it could be related to _PrefabProcessorContext_ as it is in charge to convert everything to spawnable assets. With printing out game transform components, it looks like the container entity's transform keeps unchanged (which is weird).

However, from another direction, it looks like everything works as expected. That is, the reason why the camera does not follow the prefab's container entity is WE DIDN'T ACTUALLY MOVE the container entity. I can verify this with the below experiment.

1. Create a **PlayerEntity** prefab with a mesh component in **Mesh** entity
2. Set up input and attach an input script canvas (that moves parent entity) to the **Mesh** entity
3. Set up CameraRigComponent's target to **PlayerEntity**

The above setup will move _PlayerEntity_'s container entity. It is working as expected.

https://user-images.githubusercontent.com/11157226/183780558-14b1ed4f-016a-48ec-9222-58278e31e251.mp4

@shawstar In your first video, is the input script attached to **Main_Player** or **Main_Char**? AFAIK, we could not attach script canvas to a prefab container entity at this time.

**Comment by shawstar** [comment]
Looks good! I can't wait to try it!

**Comment by michabr** [comment]
Confirmed with @shawstar that this is no longer an issue
