### ISSUE TITLE
Moving an entity outside of an instantiated prefab is not working

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#10435]
**Describe the bug**
When in the Prefab focus mode, dragging and dropping an entity outside of the prefab is not working

**Preconditions**
*  A prefab with several entities inside of it
    * [Obstacles.zip](https://github.com/o3de/o3de/files/9014544/Obstacles.zip)

**Steps to reproduce**
1. Open the O3DE editor to any level
2. Instantiate your Prefab into the Entity Outliner
3. Open the Prefab Focus Mode for the instantiated prefab
4. Attempt to drag one of the entities outside of the Prefab into the Level

**Expected behavior**
Entity is relocated to the Level entity in the Entity Outliner

**Actual behavior**
Entity cannot be relocated outside off the Instantiated Prefab

**Screenshots**
![2B8E21DC-AA8F-493B-84FE-60B1BB8CF4E4](https://user-images.githubusercontent.com/29718640/176545676-faa8f37b-b69b-4ecb-af01-40bd89f9339a.GIF)

**Found in Branch**
Development

**Comment by michabr** [comment]
This is as designed. When in Prefab Edit Mode, we only want to modify the file for that particular prefab, and no other prefabs (such as the level prefab). Once overrides are supported, you will be able to expand the prefab instance and reparent.
