### ISSUE TITLE
Bug Report: FileIO FindFiles returns aliased file path

### ISSUE THREAD

**Issue by onecent1101** [o3de/o3de#10436]
**Describe the bug**
While using FileIO FindFiles function, especially by using callback it returns file path with alias inside. Should it return alias resolved file path instead?

Refer to the code comment, it seems like trying to resolve alias, but it uses the wrong function?
https://github.com/o3de/o3de/blob/development/Code/Framework/AzFramework/Platform/Common/WinAPI/AzFramework/IO/LocalFileIO_WinAPI.cpp#L68-L70

**Expected behavior**
Expected file path is in correct format.

**Actual behavior**
File path has alias inside.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Comment by lumberyard-employee-dm** [comment]
For context, the `FileIOBase::FindFiles` tries to convert any located files back into an aliased path.
This is not only costly as a temporary buffer needs to be made to copy the aliased path into and then invoke a find files callback, but is also surprising as the user would most likely expect an path is that can be used directly with any filesystem APIs would be supplied to the callback.
