### ISSUE TITLE
Support to retrieve AWS credentials from EC2 instance profile

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#10452]
**Is your feature request related to a problem? Please describe.**
Currently the AWSCore gem doesn't support the [instance profile provider](http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_auth_1_1_instance_profile_credentials_provider.html) or use the [default AWS credentials provider chain](http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_auth_1_1_default_a_w_s_credentials_provider_chain.html), which makes it impossible to retrieve credentials for EC2 metadata directly for sending requests. This becomes a problem if we want to send requests from a server application running on EC2 (e.g. send server metrics to the AWS backend).

**Describe the solution you'd like**
Update [AWSDefaultCredentialHandler.cpp](https://github.com/o3de/o3de/blob/development/Gems/AWSCore/Code/Source/Credential/AWSDefaultCredentialHandler.cpp) to retrieve credentials from instance profile provider if no credentials are provided by the environment or profile config file providers, or make use of the default credentials provider chain provided by AWS Native SDK.

**Describe alternatives you've considered**
A workaround is to set up AWS credentials on the EC2 instance manually or pass credentials via CVAR, but the CVAR solution doesn't support temporary credentials with access token.

**Additional context**

**Comment by lmbr-pip** [comment]
Support delivered in https://github.com/o3de/o3de/pull/11692
