### ISSUE TITLE
Bug Report : Script Canvas Unable to save, Absolute path issue.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#10476]
**Describe the bug**
After updating to the newest dev branch I can no longer save script canvas graphs. This issue seems to be due to this pull request that got merged : https://github.com/o3de/o3de/pull/10404 

**Steps to reproduce**
1. Grab the newest development branch
2. Create a new project or rebuild one you already have
3. Open script canvas and try to save the graph.

**Expected behavior**
When I try to save a script canvas graph it should save without any issues.

**Actual behavior**
When I try to save a script canvas graph it gives an error and does not allow you to save the graph.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/100494538/176833824-cdb6c67b-9256-468a-9658-b7697a0fe3cc.png)

**Found in Branch**
(https://github.com/o3de/o3de/commit/2a7d81f85f36f183c1aadc739987902179700c2a)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Additional context**
I have only tried with graphs I have had before updating the dev branch. It should do the same for new graphs, but it has not been tested locally.

**Comment by ParasiteSt** [comment]
![image](https://user-images.githubusercontent.com/100494538/176868399-267045e4-e36f-4271-be55-433884dcd319.png)
This is what I get in the console when trying to save a script canvas graph that just has changes made to it.

**Comment by carlitosan** [comment]
Do you have change #10440  ? Are the graphs you are trying to save in your project, or elsewhere on disk? Also, when you save as, what is the default file location supplied?

**Comment by ParasiteSt** [comment]
I have that change as well, the graphs I am trying to save are in my projectDir/scriptcanvas folder. When I try and save it, it only gives the error in script canvas, and this warning in the console. Where should I look for the default file location supplied?

**Comment by ParasiteSt** [comment]
![image](https://user-images.githubusercontent.com/100494538/176967880-18085a9d-20ec-41eb-ba68-4936d24de529.png)
This is what I get when I open a graph, and I tried saving it twice after adding a change, and it gives the same warning each time I try to save and errors on the graph.

**Comment by ParasiteSt** [comment]
I just tested with all changes pulled as of 2 hours ago, and I have tried a new script, saving that script works, but any saves past do not. So this is for new and old graphs alike. I have found a way to save graphs, and that is overwriting them using Save As instead of save, and overwrite the graph this way. There is at least a workaround right now, but not an ideal one.

**Comment by carlitosan** [comment]
I was able to reproduce, I should have a fix for you shortly to use while you wait for the PR to go through.

**Comment by carlitosan** [comment]
![image](https://user-images.githubusercontent.com/82187351/176971894-be4815e9-08d1-4c27-a1f9-f71c97aa5b2b.png)

@ParasiteSt  please make the following change to o3de\Gems\ScriptCanvas\Code\Editor\View\Windows\MainWindow.cpp  insert:
`activeGraph = SourceHandle::MarkAbsolutePath(activeGraph, fullPath);`

right after line 1353 
`auto activeGraph =  SourceHandle::FromRelativePath(result.m_handle, assetInfo.m_assetId.m_guid, assetInfo.m_relativePath);` 

and that should fix you right up. PR en route.

**Comment by ParasiteSt** [comment]
That works like a charm, thanks for the quick fix can't thank you enough!
