### ISSUE TITLE
It is possible to expand and modify prefabs while Focus mode is not enabled

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#10483]
**Describe the bug**
Entering the **Focus Mode by clicking the "Edit Prefab"** icon and exiting it results in arrow appearing on the left side of the **prefab** mentioned earlier. This arrow indicates that the **prefab** can be collapsed or expanded. When hovering the mouse cursor over this **prefab**, the proper "Edit Prefab" icon is displayed on the left side of the prefab instead of the arrow icon, however clicking the icon will result in expanding the **prefab** and not enabling the **Focus Mode**. Please note that it is possible to modify the entities in previously mentioned **prefab** while **Focus Mode** is not enabled.

Note that this issue does not occur when the **Focus Mode** is entered by double clicking on **prefab**, but only by using an icon on the left side of the **prefab**.

**Steps to reproduce**
1. Create an entity on the level.
2. Create a **prefab** out of entity from 1st step.
3. Enter the **Focus Mode** by clicking on icon on the left side of the **prefab**.
4. Exit the **Focus Mode** (After this step an arrow on the left side of **prefab** appears).
5. Hover over **prefab** (An "Edit prefab" icon appears on the left side of **prefab**).
6. Click on the "Edit prefab" icon on the left side of the **prefab** (**prefab** expands).

Additional reproduction steps to edit prefab when Focus mode is **not** enabled:
7. Select the entity inside prefab.
8. Add any component to the entity selected.
9. Ctrl+S (Pop-up message appear asking about saving **prefab**).

**Expected behavior**
It is **not** possible to expand the **prefab** and make changes to it after exiting the **Focus Mode** which was enabled by clicking on the "Edit prefab" icon on the left side of the **prefab**.

**Actual behavior**
It is possible to expand and modify **prefab** after entering the **Focus Mode** for that **prefab** by clicking the "Edit prefab" icon on the left side of the **prefab** and exiting it.

**Video**

https://user-images.githubusercontent.com/86951967/176875740-8b53e3cc-c0ca-4b60-833c-52630afb57d6.mp4

**Found in Branch**
Development (2a7d81f)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by AMZN-daimini** [comment]
Closing as this has been fixed by #10730

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed on the Development (bc74b3b) build.
