### ISSUE TITLE
[Spike] Focus Mode - It should be possible to drag entities in focus and reparent them to entities out of focus

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10490]
[Migrated from JIRA LYN-7179]

When a prefab is in focus, it is possible to drag entities from outside the focus in (one at a time), but it is not possible to drag an entity from the prefab to something outside of it (since entities are unselectable).

We need a way to drag entities out of the currently focused prefab. This will likely need changes to the drop checks in the Outliner (I suspect the function returns false since the drop onto entity is disabled).

**Comment by hultonha** [comment]
Tagging @AMZN-daimini, @monroegm and @lsemp3d for visibility

**Comment by monroegm** [comment]
Duplicates #10435
