### ISSUE TITLE
EditorSV_Hidden True Doesn't Work on Linux

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#10505]
**Describe the bug**
The cvar EditorSV_Hidden doesn't hide the server window when running on Linux

This is because AzFramework::ProcessLauncher::ProcessLaunchInfo::m_showWindow is not supported on Linux; maybe there is an Atom cvar that can be used instead.

**Steps to reproduce**
1. Open a project with Multiplayer enabled (for exmaple: MultiplayerSample or AutomatedTesting)
2. Set editorsv_enable = true and editorsv_hidden=true
3. Press CTRL+G to enter playmode

**Expected behavior**
The server window doesn't popup and instead server starts as a background app

**Actual behavior**
Server window appears

**Found in Branch**
development latest 

**Desktop/Device (please complete the following information):**
 - OS: Ubuntu Linux

**Comment by AMZN-Gene** [comment]
This is because AzFramework::ProcessLauncher::ProcessLaunchInfo::m_showWindow is not supported on Linux.

**Comment by junbo75** [comment]
Seems like an issue on the ProcessLauncher. m_showWindow is not supported on Linux. Send to sig/platform for triage.
