### ISSUE TITLE
Asset Processor failure to find Shader Files

### ISSUE THREAD

**Issue by NiklasHenricson** [o3de/o3de#10517]
**Describe the bug**
Following the tutorial by the letter as described here: https://www.o3de.org/docs/atom-guide/look-dev/get-started-materialtypes-and-shaders/

Causes the following error reported by the Asset Processor:
![image](https://user-images.githubusercontent.com/5524755/177193814-d6e160c5-d719-4262-a1da-14fe24d04950.png)

**Steps to reproduce**

1. Create a new project outside the o3de installation somewhere in your hard drive and register it with o3de.
2. Compile the project
3. Follow the tutorial linked above and let the Asset Processor compile the newly added files.
4. The Asset Processor refuses to compile since it can't find related files.

**Expected behavior**
Expecting the Asset Processor to find the files if you work on a Project-centric rather than Engine-centric file structure. It does find however the Atom-related references under the O3DE installation folder, with lots and lots of file path escapes (eg. `../../../../..`)

**Guys, could we please start using Environment Variables to point to folders and executables? Over time you'll be moving things around, and the only thing you need to do is change the environment variables, that are being referred to inside the code from Asset Processor, Atom engine, etc, etc. instead of hardcoding stuff,  or invent a range of local files to help out, that also be moving around or become obsolete over time. 
Let the OS built-in feature of env variables help you out. Oracle, Java, Microsoft, Database vendors, C++ and all kinds of dev tools have been using these env variables for decades. They also function for Unix/Linux and Mac systems.
Devs are in general used to these. The command is also easy for a developer to quickly figure out where things are, for example `echo %o3de-gems%` or `echo %o3de-atom%`, etc. instead of using a Windows File explorer search function or go for file hunting**

I see two problems here

1. The documentation is outdated (see my comments below in a separate entry). It refers to outdated principles such as `AssetProcessorPlatformConfig.ini` that file isn't either documented on how it's supposed to be used. 
2. The Asset Processor doesn't handle file references really well. See my comments down below. I am expecting Atom-based and generic/central pieces of the game engine not to be referred to actual paths but should be parsed in automatically, no matter where your game project is located.

**Suggested Solution**
Please read the comments to this original entry down below. I figured out why it's behaving the way it does...

**Found in Branch**
Using the following developer edition of the code:
![image](https://user-images.githubusercontent.com/5524755/177194051-66b1327b-7269-44e6-93e9-acf73bfbf83f.png)

**Desktop/Device (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows 10
 - OS Version: 10.0.19043 Build 19043
 - CPU: AMD Ryzen 7 3700X 8-Core Processor 3.60 GHz, 8 Cores, 16 Logical Processors
 - RAM: DDR4 64GB
 - GPU Nvidia GeForce RTX 3060
 - GPU Driver: 516.59 Release Date: 06/28/2022
 - GPU Memory: 12 GB
 - GPU Shared System Memory: 32 GB

**Comment by NiklasHenricson** [comment]
Could you please called "Asset Processor" to "the Asset Processor" (see for example step 5 title vs. step 5 textual description)
Same thing with "Material Editor" changed to "the Material Editor".

Just more proper English to refer to the specific software's name, rather than unpacifically refer to any Asset Processor as a separate software. It's all part of O3DE...

**Comment by NiklasHenricson** [comment]
MyUnlitColor.materialtype needs to look like this now (due to changes over time, since the tutorial was written)

```json
{
    "description": "Renders a model unlit with a single suface color value.",
    "version": 3,
    "propertyLayout": {
        "properties": {
            "settings": [
                {
                    "id": "color",						// Unique, C-style identifier 		
                    "displayName": "Color",				// Name (appears in the Material Editor)
                    "type": "Color",					// Data type
                    "defaultValue": [ 0.5, 0.0, 0.5 ],	// Default value (depends on data type)
                    "connection": {						// Establish a connection between the property and a variable in the shader.
                        "type": "ShaderInput",			// - Any changes made to this 'color' property serialize to the 'm_unlitColor' 
                        "id": "m_unlitColor"            // - variable in the UnlitSingleColor shader.
                    }
                }
            ]
        },
        "groups": [
            {
                "id": "settings",
                "displayName": "Settings"
            }
        ]
    },
    "shaders": [
        {
            "file": "../../../../../../../../o3de/Gems/Atom/Feature/Common/Assets/Shaders/Depth/DepthPass.shader"
        },
        {
            "file": "../../../../../../../../o3de/Gems/Atom/Feature/Common/Assets/Shaders/Shadow/Shadowmap.shader"
        },
        {
            "file": "MyUnlitColor.shader"
        }
    ]
}
```

I can't get it to work otherwise, cause my project is located elsewhere, compared to where the O3DE is installed
My O3DE is installed under **C:\O3DE**
My project files are located under **C:\Workspaces\MyProject\ProjectSubfolder\Gems\Shaders**

Hence why all the path escapes ../../... etc....

**Comment by NiklasHenricson** [comment]
I had to also change the MyUnlitColor.shader to look like this now

```json
{
    "Source" : "MyUnlitColor.azsl",

    "DepthStencilState" :
    {
        "Depth" :
        {
            "Enable" : true,
            "CompareFunc" : "GreaterEqual"
        }
    },

    "DrawList" : "forward",

    "BlendState" : {
        "Enable" : false
    },

    "CompilerHints" : { 
        "DxcDisableOptimizations" : false
    },

    "ProgramSettings":
    {
      "EntryPoints":
      [
        {
          "name": "MainVS",
          "type": "Vertex"
        },
        {
          "name": "MainPS",
          "type": "Fragment"
        }
      ]
    }  
}
```

**Comment by NiklasHenricson** [comment]
Finally, I looked how the Atom implemented its AZSL:s so the code is somewhat changed to the original one in the tutorial,

```cpp
#pragma once

#include <viewsrg.srgi>
#include <Atom/Features/PBR/DefaultObjectSrg.azsli>
#include <Atom/Features/PBR/ForwardPassOutput.azsli>
#include <Atom/Features/SrgSemantics.azsli>

ShaderResourceGroup UnlitColorSrg : SRG_PerMaterial
{
    float3 m_unlitColor;
}

struct VertexInput
{
    float3 m_position : POSITION;
};

struct VertexOutput
{
    float4 m_position : SV_Position;    
};

VertexOutput MainVS(VertexInput input)
{
    VertexOutput ouput;
    const float4x4 worldMatrix = ObjectSrg::GetWorldMatrix();

    float3 worldPosition = mul(worldMatrix, float4(input.m_position, 1.0)).xyz;
    ouput.m_position = mul(ViewSrg::m_viewProjectionMatrix, float4(worldPosition, 1.0));

    return ouput;
}

struct PixelOutput
{
    float4 m_color : SV_Target0;
};

ForwardPassOutput MainPS(VertexOutput input)
{
    ForwardPassOutput ouput;

    // standard ForwardPassOutput G-buffer layout
    ouput.m_diffuseColor = float4(UnlitColorSrg::m_unlitColor, -1.0); // Subsurface scattering is disabled
    ouput.m_specularColor = float4(0.0, 0.0, 0.0, 0.0);   // Disable specular lighting

    return ouput;
}
```

**Comment by galibzon** [comment]
@NiklasHenricson , take a look at this readme file for details on how the shader build pipeline discovers the Include Paths: https://github.com/o3de/o3de/blob/development/Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/README.md

**Comment by NiklasHenricson** [comment]
Hi @galibzon,

Thank you I'll have a look and let you know how it went. I appreciate the quick response.

**Comment by NiklasHenricson** [comment]
> @NiklasHenricson , take a look at this readme file for details on how the shader build pipeline discovers the Include Paths: https://github.com/o3de/o3de/blob/development/Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/README.md

Unfortunately it didn't work, but again the post you're referring to mentions something vaguely and conceptually. It doesn't give a full example on which JSON properties to be using in that file. I went to o3de folder again to find an example, there was only 1 file that had some kind of property that I used and that didn't work.

**Comment by NiklasHenricson** [comment]
> Thanks @NiklasHenricson for detailing your experience with this doc and workflow, this will surely need an update to be accurate with the latest and overall more clear.
> 
> As for the use of "**the**", there's debate on [whether to use "the" before a proper noun](https://english.stackexchange.com/questions/59271/why-there-is-the-before-some-names-but-not-others) (such are software names). I think what docs needs to do is to use or not use "the" consistently. It's true though that the software names should never succeed "a" or "an", if there's only a single instance.

Thank you @chanmosq

**Comment by lmbr-pip** [comment]
As this is blocking developer, we are raising priority of issue so increase visibility

**Comment by jeremyong-az** [comment]
I think the folks maintaining this aspect of the system would appreciate some additional clarity on what the conclusion is from the discussion above. Is the problem a bug in the documentation, or are the workarounds/alternatives to what was originally tried not suitable?

**Comment by galibzon** [comment]
@NiklasHenricson , can you please change:

**Comment by AMZN-stankowi** [comment]
Why are the MaterialType files referencing the Shader files via path and not via source asset UUID?

Also, let me know if there's anything you need the asset pipeline team to take a look at. Reading this thread I think the problem's being handled, but I can provide additional assistance, if needed.

**Comment by galibzon** [comment]
For example this document: https://www.o3de.org/docs/user-guide/assets/pipeline/scan-directories/  
Requires more details into what folders inside a `Gem` are considered `scan directory`.

**Comment by AMZN-stankowi** [comment]
I've been working on documentation updates for the asset pipeline, I've added that page to my list to go back over.

**Comment by AMZN-stankowi** [comment]
I've put an update to the documentation to address issues with assets referencing other files, here https://github.com/o3de/o3de.org/pull/1882

**Comment by NiklasHenricson** [comment]
> @NiklasHenricson , can you please change:
> 
> ```
>     "shaders": [
>         {
>             "file": "../../../../../../../../o3de/Gems/Atom/Feature/Common/Assets/Shaders/Depth/DepthPass.shader"
>         },
>         {
>             "file": "../../../../../../../../o3de/Gems/Atom/Feature/Common/Assets/Shaders/Shadow/Shadowmap.shader"
>         },
>         {
>             "file": "MyUnlitColor.shader"
>         }
>     ]
> ```
> 
> For
> 
> ```
>     "shaders": [
>         {
>             "file": "Shaders/Depth/DepthPass.shader"
>         },
>         {
>             "file": "Shaders/Shadow/Shadowmap.shader"
>         },
>         {
>             "file": "MyUnlitColor.shader"
>         }
>     ]
> ```

Hi @AMZN-stankowi @galibzon sorry for replying late in your process. I'll be experimenting later tonight and keep you updated on my results.

Thank you

**Comment by santorac** [comment]
> Why are the MaterialType files referencing the Shader files via path and not via source asset UUID?
@AMZN-stankowi Because these .materialtype files are hand-authored, and UUIDs are hard to work if you don't have tools to do it for you.

**Comment by NiklasHenricson** [comment]
@AMZN-stankowi @santorac @galibzon 

I've run a few tests with the most recent dev branch code and things work fine. Thank you for looking into this!

The issue can be closed.
