### ISSUE TITLE
Font size setting in Lua Editor is not applied correctly

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#10514]
**Describe the bug**

After changing the font size in the Lua Editor settings, there are issues with some characters.
* Dots marking spaces and arrows marking tabs remain the default size. The width of tabs scales, but the width of spaces does not, making them harder to see as the font size gets bigger.
* Brackets temporarily revert to the default font size whenever the text cursor is placed right by them - this affects single brackets as well as pairs of brackets if the cursor is by one of them. This affects parentheses, square brackets, and curly brackets, but not angle brackets.
* If the font size is increased to 14 or more, line numbering for empty lines is cropped.

Spaces, tabs, and brackets within comments are not affected by this issue.
This issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Open the Lua Editor.
2. Create a new script.
3. Fill some lines with text, spaces, and tabs. Insert a few empty lines, and use some brackets of different types.
4. Go to Options>Settings and increase the font size to at least 14.
5. Place the text cursor next to different brackets.

**Expected behavior**
All characters in the file should adjust to match the font size setting. Line numbering should remain readable.

**Actual behavior**
Space and tab markers remain the default size. Brackets revert to the default font size whenever the text cursor is placed right by them. Line numbering for empty lines is cropped.

**Screenshots/Video**

![lua_sc3](https://user-images.githubusercontent.com/99388484/177155436-19da6b9e-3b58-41b2-8029-b1c97e4fe0cd.png)

**Found in Branch**
Development (db9d67d)
**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by LB-JaroslawGaweda** [comment]
Verified this issue as fixed on build Development (1ee9f0b).
