### ISSUE TITLE
Editor crashes during editing entity with White Box component

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#10543]
**Describe the bug**
With Edit mode of the **White Box** component enabled, holding Ctrl + Shift and moving any of the manipulators with LMB will result in warnings being printed in the console:

`[Warning] (Manipulators) - MouseMove action received, but this manipulator is not performing an action`

The **Editor** crashes when one of the **vertices** is pressed instead of a polygon.

This issue occurs on Windows as well as on Linux OS.

**Steps to reproduce**

1. Create a new entity.
2. Add the **White Box** component to the entity in the **Entity Inspector**.
3. Enter the Edit mode by pressing "Edit" button in the **White Box** component.
4. Press LMB on one of the vertices and hold it.
5. Press and hold Ctrl + Shift.
6. Hover the cursor (warnings mentioned in the description appear in the console).
7. Release the LMB.

**Expected behavior**
The **Editor** remains stable at all times, no warnings are being printed in the console.

**Actual behavior**
The **Editor** crashes after releasing the LMB when Ctrl + Shift is being pressed when moving the **White Box** vertex in the Edit mode.

**Video**

https://user-images.githubusercontent.com/86951967/177555500-f7116595-f7a0-49e3-8435-1f73430b2cc7.mp4

**Found in Branch**
Development (d002a4a)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Additional context**
[error.log](https://github.com/o3de/o3de/files/9054911/error.log)
[error.zip](https://github.com/o3de/o3de/files/9054912/error.zip)
[Editor.log](https://github.com/o3de/o3de/files/9054914/Editor.log)

**Comment by jonawals** [comment]
The issue appears to be that a garbage `MultiLinearManipulator` is referred to that, when the LMB is released and the mouse up handler is called, the access violation occurs.

This is an ongoing investigation and I will update this ticket accordingly as new information is revealed.

**Comment by hultonha** [comment]
Tagging @pollend in case they have a chance to reproduce or investigate this. This is something I can also try and have a look at but it might not be until the end of the week. Thanks!

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed on the Stabilization/2305 (c4dd0ce) build.
