### ISSUE TITLE
Multi-Position Audio component does not have the Behavior Type default value set

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10542]
**Describe the bug**
Multi-Position Audio component does not have the "Behavior Type" property default value set. As per the documentation page (https://www.o3de.org/docs/user-guide/components/reference/audio/multi-position/) it should be set to "Separate". It should also be noted that adding Multi-Position Audio component results in warning being printed to the Console: `[Warning] (AzToolsFramework) - GenericValue could not be found in the combo box`.

**Steps to reproduce**
1. Create an entity.
2. Add the Multi-Position Audio, Audio Trigger, and Audio Proxy components to the entity from step 1.

**Expected behavior**
Multi-Position Audio "Behavior Type" property is set to Separate by default.

**Actual behavior**
Multi-Position Audio "Behavior Type" property is blank, and warning is printed to the Console.

**Video**

https://user-images.githubusercontent.com/86952082/177534560-b42011ba-e2e4-4b93-9b56-1403a3e0cfe8.mp4

**Found in Branch**
Development (d002a4a)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (5889b75) build.

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed using Stabilization/2210 (https://github.com/o3de/o3de/commit/99608ffd4f7d3d347cb015b243046a3438da23c7) build.
