### ISSUE TITLE
Opening project results in invalid server address error being displayed

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de#10559]
**Describe the bug**
Launching a new project results in a Startup Error window being displayed. It should be noted that this error pops up every time the project is launched. However, the Editor works without noticeable issues. This occurs on both Windows and Linux.

**Steps to reproduce**
1. Open Project Manager and create a new project from minimal template.
2. Build the new project.
3. When it's ready open it.

**Expected behavior**
Project should open with no errors.

**Actual behavior**
Startup Error window displays an error.

*Screenshots/Video*

![Startup Error](https://user-images.githubusercontent.com/99716227/177752896-c678322f-3a21-45cc-a72d-a98c0016d8ec.png)

**Found in Branch**
Development (049db2e)

**Desktop/Device:**
• Device: PC
• OS: Ubuntu
• Version: Ubuntu 20.04.4 LTS
• CPU Intel Core i7-9700K
• GPU Nvidia GeForce RTX 2070
• Memory 16GB

**Additional context**
[AP_GUI.log](https://github.com/o3de/o3de/files/9062719/AP_GUI.log)

**Comment by amzn-mike** [comment]
A fix for this is up for review here: https://github.com/o3de/o3de/pull/10551

**Comment by LB-JakubSkoczylas** [comment]
Verified this issue as Fixed on build Development (049db2e).
