### ISSUE TITLE
The editor breaks down occasionally when the demo exits.

### ISSUE THREAD

**Issue by fufushang** [o3de/o3de#10557]
Describe the bug
The editor breaks down occasionally when the demo exits..

Assets required
 Specials Assets is not needed.

Steps to reproduce
1. Open the demo
2. Run the demo
3. then Exit from running

Expected behavior
The editor Normal exit 

Actual behavior
The editor Abnormal exits and crash.

Screenshots/Video
If applicable, add screenshots and/or a video to help explain your problem.
![image](https://user-images.githubusercontent.com/7249380/177676119-87fab723-50e2-4274-a9bd-1ecf2ce0dd45.png)

![image](https://user-images.githubusercontent.com/7249380/177676549-ff704741-02ac-490d-9016-5fdf04527fa1.png)

Found in Branch

Desktop/Device (please complete the following information):
Device: PC
OS: Windows
Version 10
Intel(R) Xeon(R) W-2245
GPU NVidia RTX 4000
Memory 64GGB

Additional context
error.log
Executable: Editor.exe (debug: no
Exception Code: 0xC0000005
Exception Addr: 0x0033:0x00007FFFDBB4805C
Exception Module: 
Exception Description: EXCEPTION_ACCESS_VIOLATION, Attempt to read from address 0x00000000

The memory could not be "read"

Call Stack Trace:
23) 00007FF84CD2F67A (KERNELBASE) : UnhandledExceptionFilter
22) 00007FF84F1C4AF2 (ntdll) : memset
21) 00007FF84F1AC6D6 (ntdll) : _C_specific_handler
20) 00007FF84F1C11FF (ntdll) : _chkstk
19) 00007FF84F18A289 (ntdll) : RtlRaiseException
18) 00007FF84F1BFE6E (ntdll) : KiUserExceptionDispatcher
17) 00007FFFDBB4805C (Atom_RHI_DX12.Private) : UninitializeDynamicModule
16) 00007FFFDBB5CDFE (Atom_RHI_DX12.Private) : UninitializeDynamicModule
15) 00007FFFDBB5CEBC (Atom_RHI_DX12.Private) : UninitializeDynamicModule
14) 00007FFF9BCE0AF2 (HWParticleSystem.Editor.Gem) : UninitializeDynamicModule
13) 00007FFF9BA9F3C4 (HWParticleSystem.Editor.Gem) : UninitializeDynamicModule
12) 00007FFF9BB16035 (HWParticleSystem.Editor.Gem) : UninitializeDynamicModule
11) 00007FFF9BB15D82 (HWParticleSystem.Editor.Gem) : UninitializeDynamicModule
10) 00007FFF9BB0DFB0 (HWParticleSystem.Editor.Gem) : UninitializeDynamicModule
 9) 00007FFF9BB00DE7 (HWParticleSystem.Editor.Gem) : UninitializeDynamicModule
 8) 00007FFF9BAB587B (HWParticleSystem.Editor.Gem) : UninitializeDynamicModule
 7) 00007FFF589F963C (EditorLib) : InjectEnvironment
 6) 00007FFF589F990B (EditorLib) : InjectEnvironment
 5) 00007FFF589FAA56 (EditorLib) : InjectEnvironment
 4) 00007FFF58A508AE (EditorLib) : InjectEnvironment
 3) 00007FF84C850E72 (ucrtbase) : beginthreadex
 2) 00007FF84DC67BD4 (KERNEL32) : BaseThreadInitThunk
 1) 00007FF84F18CED1 (ntdll) : RtlUserThreadStart

Editor.log:
Exited game mode
(System) - 
==================================================================
(System) - Trace::Assert
\Gems\Atom\RHI\DX12\Code\Source\RHI/DX12.h(56): (44352) 'bool __cdecl AZ::DX12::AssertSuccess(long)'
(System) - HRESULT not a success 887a0005
(System) - ------------------------------------------------
(System) - 00007FFFDBB37776 (Atom_RHI_DX12.Private) : UninitializeDynamicModule
(System) - 00007FFFDBB436AF (Atom_RHI_DX12.Private) : UninitializeDynamicModule
(System) - 00007FFFDBB5C2CE (Atom_RHI_DX12.Private) : UninitializeDynamicModule
(System) - 00007FFFDBAFC796 (Atom_RHI_DX12.Private) : UninitializeDynamicModule
(System) - 00007FFFDBAEE262 (Atom_RHI_DX12.Private) : UninitializeDynamicModule
(System) - 00007FFFDBB23365 (Atom_RHI_DX12.Private) : UninitializeDynamicModule
(System) - 00007FFFCBB9924B (Atom_Feature_Common.Editor) : UninitializeDynamicModule
(System) - 00007FFFCBA4CC9D (Atom_Feature_Common.Editor) : UninitializeDynamicModule
(System) - 00007FFFCA545524 (Atom_RPI.Editor) : UninitializeDynamicModule
(System) - 00007FFFCA554144 (Atom_RPI.Editor) : UninitializeDynamicModule
(System) - 00007FFFCA30ECB7 (Atom_RPI.Editor) : UninitializeDynamicModule
(System) - 00007FFF58902A3E (EditorLib) : InjectEnvironment
(System) - 00007FFF5893A817 (EditorLib) : InjectEnvironment
(System) - 00007FFF5847AAB5 (EditorLib) : CCryEditApp::IdleProcessing
(System) - 00007FFF5847F714 (EditorLib) : CCryEditApp::OnIdle
(System) - 00007FFFE4F88530 (Qt5Core) : QObject::objectNameChanged
(System) - 00007FFFE4F8BFA3 (Qt5Core) : QTimer::timerEvent
(System) - 00007FFFE4F7CE0D (Qt5Core) : QObject::event
(System) - 00007FFFF3B28471 (Qt5Widgets) : QApplicationPrivate::notify_helper
(System) - 00007FFFF3B27B9A (Qt5Widgets) : QApplication::notify
(System) - 00007FFFE4F5541B (Qt5Core) : QCoreApplication::notifyInternal2
(System) - 00007FFFE4FA9517 (Qt5Core) : QEventDispatcherWin32Private::sendTimerEvent
(System) - 00007FFFE4FAB5A1 (Qt5Core) : QEventDispatcherWin32::event
(System) - 00007FFFF3B28471 (Qt5Widgets) : QApplicationPrivate::notify_helper
(System) - 00007FFFF3B27B9A (Qt5Widgets) : QApplication::notify
(System) - ==================================================================
(System) - ====Assert added to ignore list by spec and verbosity setting.====
(System) - 
==================================================================
(System) - Trace::Assert
../Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingTlas.cpp(130): (44352) 'enum AZ::RHI::ResultCode __cdecl AZ::DX12::RayTracingTlas::CreateBuffersInternal(class AZ::RHI::Device &,const class AZ::RHI::RayTracingTlasDescriptor *,const class AZ::RHI::RayTracingBufferPools &)'
(System) - failed to create TLAS scratch buffer
(System) - ------------------------------------------------
(System) - 00007FFFDBB23388 (Atom_RHI_DX12.Private) : UninitializeDynamicModule
(System) - 00007FFFCBB9924B (Atom_Feature_Common.Editor) : UninitializeDynamicModule
(System) - 00007FFFCBA4CC9D (Atom_Feature_Common.Editor) : UninitializeDynamicModule
(System) - 00007FFFCA545524 (Atom_RPI.Editor) : UninitializeDynamicModule
(System) - 00007FFFCA554144 (Atom_RPI.Editor) : UninitializeDynamicModule
(System) - 00007FFFCA30ECB7 (Atom_RPI.Editor) : UninitializeDynamicModule
(System) - 00007FFF58902A3E (EditorLib) : InjectEnvironment
(System) - 00007FFF5893A817 (EditorLib) : InjectEnvironment
(System) - 00007FFF5847AAB5 (EditorLib) : CCryEditApp::IdleProcessing
(System) - 00007FFF5847F714 (EditorLib) : CCryEditApp::OnIdle
(System) - 00007FFFE4F88530 (Qt5Core) : QObject::objectNameChanged
(System) - 00007FFFE4F8BFA3 (Qt5Core) : QTimer::timerEvent
(System) - 00007FFFE4F7CE0D (Qt5Core) : QObject::event
(System) - 00007FFFF3B28471 (Qt5Widgets) : QApplicationPrivate::notify_helper
(System) - 00007FFFF3B27B9A (Qt5Widgets) : QApplication::notify
(System) - 00007FFFE4F5541B (Qt5Core) : QCoreApplication::notifyInternal2
(System) - 00007FFFE4FA9517 (Qt5Core) : QEventDispatcherWin32Private::sendTimerEvent
(System) - 00007FFFE4FAB5A1 (Qt5Core) : QEventDispatcherWin32::event
(System) - 00007FFFF3B28471 (Qt5Widgets) : QApplicationPrivate::notify_helper
(System) - 00007FFFF3B27B9A (Qt5Widgets) : QApplication::notify
(System) - 00007FFFE4F5541B (Qt5Core) : QCoreApplication::notifyInternal2
(System) - 00007FFFE4F5629D (Qt5Core) : QCoreApplicationPrivate::sendPostedEvents
(System) - 00007FFFFE6386CF (qwindows) : qt_plugin_instance
(System) - 00007FFFE4FA988B (Qt5Core) : QEventDispatcherWin32::processEvents
(System) - 00007FFFFE6386A9 (qwindows) : qt_plugin_instance
(System) - ==================================================================
(System) - ====Assert added to ignore list by spec and verbosity setting.====
(DX12) - DXGI_ERROR_DEVICE_RESET - The device failed due to a badly formed command. This is a run-time issue; The application should destroy and recreate the device.

**Comment by galibzon** [comment]
What is the Demo?

**Comment by galibzon** [comment]
Issues close due to lack of response.

**Comment by fufushang** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
