### ISSUE TITLE
Diffuse Probe Grid Component not providing Global Illumination Real Time or Baked.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#10564]
**Describe the bug**
Diffuse Probe Grid Component not providing Global Illumination Real Time or Baked. This is also with the Level Diffuse Global Illumination Component on.

**Assets required**
![image](https://user-images.githubusercontent.com/87207603/177820835-9b8dee3a-6fce-44a6-8d43-9565a4a9a25d.png)

**Steps to reproduce**
1. Go to add Entity 
2. Click on Component Diffuse Probe Grid
3. Move GI Box around a model.
5. See error

**Expected behavior**
GI works as past expected behavior.

**Actual behavior**
GI is no long working as expected

**Found in Branch**
Nightly 7-7-2022

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I9-9900k]
 - GPU NVidia RTX 2080ti]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by shawstar** [comment]
I just opened the loft and the GI is working...but projects are set up the same way. But one is a brand new project with just default gems....
![image](https://user-images.githubusercontent.com/87207603/177872199-46dbff0e-d8cf-4168-9b78-6a31a7ed0d74.png)

**Comment by shawstar** [comment]
Looks better... but also not correct. Went over both scenes with Johnny. So, there are issues.
![image](https://user-images.githubusercontent.com/87207603/177874844-87e84252-bc12-43a6-bb2e-7f2cb0583d76.png)

**Comment by HogJonny-AMZN** [comment]
I believe this is the same issue I was having in the Loft scene.
- The directional light is not rendering into the reflection probes
- I believe that it's possible the light energy is likewise not propagating into the GI

![image](https://user-images.githubusercontent.com/23222931/177875246-648a442e-861c-4b2b-abdb-5c838f6b5dcc.png)

**Comment by HogJonny-AMZN** [comment]
@shawstar should we make a level (or levels) with all the light types, so we can validate in automated testing they are captured correctly in probes as updates occur?  I can clearly see the can lights in the probe, so they are working right now.

I assume the 'Light Component' and all of its types work (because it is unified), and that just the 'Directional Light' is broken because it's separate and somehow got missed in some update.

**Comment by dmcdiarmid-ly** [comment]
This is a known issue - probes are occluded from the directional light by transparent geometry, since they are currently treated as opaque geometry in the RT acceleration structure.  This is on my list to fix in the near future.

**Comment by dmcdiarmid-ly** [comment]
DiffuseProbeGrids and RayTracing now support transparent geometry, see the following PR: https://github.com/o3de/o3de/pull/11734.
