### ISSUE TITLE
EditContext Should Pass Around Prefabs Not Spawnables

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#10570]
**Describe the bug**
When components need to spawn something, it's required to store a AZ::Data::Asset<<AzFramework::Spawnable>>. Ideally though, users should only deal with assets they produce (prefabs), not the artifacts which Asset Processor produces (spawnables) 

**Steps to reproduce**
1. Create a new component which stores AZ::Data::Asset<<AzFramework::Spawnable>>
2. Make sure the Reflect method editContext exposes the spawnable to editor
example: ->DataElement(nullptr, &NetworkPrefabSpawnerComponent::m_defaultSpawnableAsset, "Default Prefab", "Default prefab to spawn upon request.")
3. Compile and open editor and pass the component a spawnable

**Expected behavior**
Edit context should accept a prefab

**Actual behavior**
Edit context accepts a spawnable

**Found in Branch**
development

**Additional context**
The networking teams also needs a way to check that the prefab passed into the edit context produces a network spawnable. 

Relates to #9511 and #9513

**Comment by AMZN-mnaumov** [comment]
I am not sure if I understand your question. Prefab is a source file, and spawnable is the product it generates. SpawnableManager API operates on products (spawnables). 

However in asset picker, when you assign an asset it does actually accept .prefab, (internally it picks the first valid spawnable product). Which as I am thinking right now could be an issue as some prefabs have multiple products - e.g. spawnable and network spawnable. So some UI change in AssetPicker filters may be necessary to allow for more fine-grained product selection.

**Comment by AMZN-Gene** [comment]
Yeah, this originally came up because Network  components have no way of filtering out asset to only show prefabs that produce network spawables. More generally, users want to interact with the assets they authored (prefabs). Script canvas has something nice for their Spawner variables. The asset picker windows only shows prefabs (no .spawnables) are ever seen, and so avoid and confusion on what should be selected.

**Comment by AMZN-mnaumov** [comment]
I don't know if there's anything more we can do here. Since spawnable and network.spawnable are the same asset type, they will get treated the same by property control. We can't add exception to 'hide' network spawnables in Asset Browser. As far as entity inspector with custom components, users will need to manually add
```
->Attribute(AZ::Edit::Attributes::ShowProductAssetFileName, false)
->Attribute(AZ::Edit::Attributes::HideProductFilesInAssetPicker, true)
```
when reflecting the spawnable field.

**Comment by AMZN-Gene** [comment]
Closing. Users will pass around spawnables, not prefabs. We we filter out the asset picker where needed so that users select network.spawnables when needed.
