### ISSUE TITLE
[Arch Linux] CMake fails: libcrypto.so.1 does not exist. (instead, libcrypto.so.1.1 exists)

### ISSUE THREAD

**Issue by Houkime** [o3de/o3de#10601]
**Describe the bug**
On Arch Linux CMake fails to configure the project and exits with a libcrypto error (see `Actual Behavior`) and a wrong syntax error. I cannot say if they are related causally. 

**Assets required**
No assets are requred

**Steps to reproduce**
* `git clone https://github.com/o3de/o3de`
* `cd o3de`
* `cmake .`

**Expected behavior**
CMake generating buildfiles and exiting successfully or telling me to make an out-of-tree build.

**Actual behavior**
```
...
/home/user/clones/o3de/python/runtime/python-3.7.12-rev2-linux/python/bin/python: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
CMake Error at cmake/LyAutoGen.cmake:42 (add_custom_command):
  add_custom_command Wrong syntax.  A TARGET or OUTPUT must be specified.
Call Stack (most recent call first):
  cmake/LYWrappers.cmake:404 (ly_add_autogen)
  Gems/Multiplayer/Code/CMakeLists.txt:11 (ly_add_target)
  ...
  <repeats with variations>
```

**Found in Branch**
development 31412043ce89a560f13cec877caf4f91c04c5af1

**Desktop/Device (please complete the following information):**
 - Device: Desktop
 - OS: Arch Linux
 - openssl: 1.1.1.q (note: there indeed is no libcrypto.so.1, instead, there is libcrypto.so.1.1)
 - Installed python: 3.10.5 (but here o3de-bundled python 3.7 is used)
 - CMake 3.23.2
 - Memory: 6 GB

**Additional context**
I could not find the preferred Linux build procedure in repo or wiki so proceeded with standard cmake->make workflow.

**Comment by Darkinggq** [comment]
@Houkime Hi, you better go to the Discord there discussions https://discord.com/channels/805939474655346758/816043694762754088/995405231305265253

**Comment by spham-amzn** [comment]
Python has been updated to 3.10.5, and included with the [commit ](https://github.com/o3de/o3de/commit/607c548791f2170b4d23a8cac191be1b834ca15b)is a portable version of OpenSSL 1.1.1. This issue should be fixed now.
