### ISSUE TITLE
'sys_report_files_not_found_in_paks' cvar is duplicated.

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#10609]
**Describe the bug**
'sys_report_files_not_found_in_paks' cvar is created in 2 places:

In Archive.cpp
````
AZ_CVAR(int, sys_report_files_not_found_in_paks, 0, nullptr, AZ::ConsoleFunctorFlags::Null,
        "Reports when files are searched for in paks and not found. 1 = log, 2 = warning, 3 = error");
````
And in SystemInit.cpp
````
REGISTER_CVAR2("sys_report_files_not_found_in_paks", &g_cvars.sys_report_files_not_found_in_paks, 0, VF_NULL, "Reports when files are searched for in paks and not found. 1 = log, 2 = warning, 3 = error");
````

This causes the following message in the log:

````
[CVARS]: [DUPLICATE] CXConsole::RegisterString(const char*): variable [sys_report_files_not_found_in_paks] is already registered
````

**Steps to reproduce**
1. I saw it running default level on Android, but I guess this should appear when running the launcher on any platform.

**Expected behavior**
CVars are not duplicated

**Actual behavior**
CVar "sys_report_files_not_found_in_paks" is duplicated.

**Found in Branch**
Development 5801ff7ad1beca136eb28a16ce90bd16694d2a80

**Comment by lumberyard-employee-dm** [comment]
We can just remove the copy of this CVar from SystemInit.cpp

**Comment by Mattt47** [comment]
> We can just remove the copy of this CVar from SystemInit.cpp

That simple?

**Comment by lumberyard-employee-dm** [comment]
> > We can just remove the copy of this CVar from SystemInit.cpp
> 
> That simple?

Yes, it is that simple.
Since the CVar is being registered with the current AZ Console system, registering it with the legacy Cry Console system is no longer needed.
