### ISSUE TITLE
Feature Request: Json Import Across Gems

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#10623]
**Is your feature request related to a problem? Please describe.**
.materialtype files can be composed of properties from .json files using the $import keyword. However, all of those files must be part of the same gem. It would be beneficial for a project or an external gem to be able to import property groups from the Atom/Features/Common gem.

See https://discord.com/channels/805939474655346758/816043622558335046/983734984055607316 and https://discord.com/channels/805939474655346758/816043622558335046/986436779190132769

**Describe the solution you'd like**
Currently, the JsonImporter supports importing json files using either relative or absolute paths. When using relative paths, we take the absolute path of the parent file and look for the file being imported in the same directory.
We would like to be able to look for relative paths in other locations as well eg: cache or user directory. In order to let the user of the import API decide how to resolve relative paths, we can add a callback to resolve paths. The default behavior will be the same as it is now. If a callback was provided, the callback will be used to resolve paths instead.

**Describe alternatives you've considered**

**Additional context**

**Comment by santorac** [comment]
@amzn-pratikpa Just a heads up, this issue is impacting the development of a tutorial, forcing the use of an absolute path and a link to this Issue: https://github.com/o3de/o3de.org/pull/1757

**Comment by shawstar** [comment]
Would be cool to have this, as I wanted to use the VegetationBending in the RosCon project, but see that it will require customers to add in a absolute path in at lest 13 different imports. Or.. roll the dice and assume that the engine is installed in the default location.

**Comment by HogJonny-AMZN** [comment]
I agree, we should re-open this.  I also wanted to use the veg tutorial shaders, but it was too much hassle, which makes it a distraction.

**Comment by santorac** [comment]
I marked needs-triage to make sure the sig is seeing these comments. ;)

**Comment by lumberyard-employee-dm** [comment]
Adding a call to [FileIO::ReplaceAlias](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/IO/FileIO.h#L223-L226)  in the JsonImporter [ResolveImports](https://github.com/o3de/o3de/blob/eb4c6fb24c8429bfafca4a6a51613abb3a2756bb/Code/Framework/AzCore/AzCore/Serialization/Json/JsonImporter.cpp#L170) function will allow filesystem aliases such as `@gemroot:<gem-name>@` to be used.

A developer needs to make that change and test it

**Comment by lumberyard-employee-dm** [comment]
@santorac The issue has been triaged already.
Are looking for a priority bump to the issue?

**Comment by santorac** [comment]
Yes, that's kind of what I was getting at. Sorry if I'm being a nuisance :)

**Comment by lumberyard-employee-dm** [comment]
I have updated the priority to Critical.
I proposed a solution to the issue in the comment above my previous comment.
