### ISSUE TITLE
Prefabs - Dragging a Prefab from the Asset Browser to the Outliner or Viewport instantiates it twice.

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#10627]
**Describe the bug**
Dragging a Prefab from the Asset Browser to the Outliner or Viewport instantiates it twice.

**Assets required**
Any prefab file.

**Steps to reproduce**
1. Open a level
2. Find a prefab file in the Asset Browser
3. Drag the asset to the Entity Outliner or Viewport

**Expected behavior**
The prefab is instantiated

**Actual behavior**
The prefab is instantiated twice.

**Screenshots/Video**
![Twice](https://user-images.githubusercontent.com/82231674/178561380-da216e7c-cca9-4319-b2b2-f35d4aba57c8.gif)

**Found in Branch**
Latest development

**Comment by monroegm** [comment]
@lawsonamzn You were looking into drag and drop. Can you take a look at this one?

**Comment by lawsonamzn** [comment]
I also just discovered that Qt item views (which have rows _and columns_) will return each selected item (column, row) as its own selection, even if operating in "select whole row" mode.  So for example the Asset Browser has 2 columns, but has whole-row selection, so any time you select anything, both columns of that item are selected.

This means that when you start dragging and call "Get selection" it will always have 2 items in it (one for each column, even though its the same row) and this results in duplicates in the drag and drop list.  I can fix this..

**Comment by lawsonamzn** [comment]
The above ticket should close the issue.
