### ISSUE TITLE
As a Dev I want an IMGui Option to "Host Level"

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#10625]
**Is your feature request related to a problem? Please describe.**
Figuring out how to start a local multiplayer session is difficult.
1. Launch Server
2. Load Level
3. Host
4. Launch Game
5. Connect

If these steps happen out of order, the multiplayer game will fail to start.
For example a failure state can occur if...
 The user loads a level before hosting
 The user connects before the host loads a level
 The user loads a non-networked level on the host

This fixes #9630

**Describe the solution you'd like**
Add a GUI option to "Host Level" and "Launch Client"
This way, the player doesn't accidently load a level without hosting, We also will only show levels that are networked levels, so users cannot accidently select a non-networked level. This also eliminates much of the need to use/understand cfg's for launching server/client since it'll be so easy to do so from ImGUI

**Describe alternatives you've considered**
When opening a ServerLauncher it would be cool to display this option immediately on start up, or to have a default "Server" menu popup. Although this might be tricky as LyShine is disabled on server.

**Comment by yuyihsu** [comment]
related to LYN-13879

**Comment by rainbj** [comment]
Some ideas from UX review. We should consider some option to hide show the menu with a button icon or arrow, or a [~] icon. This also should be in combination with the changing the menu option from [home] to [~].

We should also consider that the [~] is currently assigned to opening and closing the console menu. We need to change this shortcut to a different shortcut. The exact shortcut still needs to be discussed further.

**Comment by AMZN-Gene** [comment]
> Some ideas from UX review. We should consider some option to hide show the menu with a button icon or arrow, or a [ ~ ] icon. This also should be in combination with the changing the menu option from [home] to [~].
> 
> We should also consider that the [~] is currently assigned to opening and closing the console menu. We need to change this shortcut to a different shortcut. The exact shortcut still needs to be discussed further.

https://github.com/o3de/o3de/issues/9668

**Comment by rainbj** [comment]
![ImGui - open](https://user-images.githubusercontent.com/82551958/181131191-4fec28c2-e145-4b2b-b66e-1198fd1ff5ec.png)
![ImGui - close](https://user-images.githubusercontent.com/82551958/181131196-8173857b-b4f7-4449-bf81-ccb4e1bc531a.png)

Design considerations based on our conversations.
