### ISSUE TITLE
[Linux] Minimal project created on Source configuration can not be opened in Editor

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#10638]
**Describe the bug**
After building O3DE using Source configuration, the Minimal template project can be build, however Editor crashes on attempt to open it. Projects with all Gems enabled or standard template can be build and opened in the Editor.

**Steps to reproduce**
1. Build O3DE using Source configuration.
2. Launch Project Manager.
3. Create a new project using the Minimal Template.
4. Build the project.
5. Attempt to open the project.
 
**Expected behavior**
Project is opened in the Editor.

**Actual behavior**
Editor silently crashes during start up.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/178714721-f744ca7d-072b-4168-b3af-94d5bccaeda8.mp4

**Found in Branch**
Development (f7649a0)

**Desktop/Device:**
- Device: PC
- OS: Ubuntu
- Version 20.04
- CPU AMD Ryzen 3600
- GPU Nvidia GeForce RTX 2060 SUPER
- Memory 16GB

**Additional context**
[Logs.zip](https://github.com/o3de/o3de/files/9101274/Logs.zip)

**Comment by spham-amzn** [comment]
What is the installed and current display driver?
Either type in
```
nvidia-smi
```
or
```
sudo lshw -C display
```

**Comment by LB-RostyslavGavryliuk** [comment]
@spham-amzn I no longer have access to the machine on which the bug originally occurred. Issue does not occur on latest Stabilization, however https://github.com/o3de/o3de/issues/11849 occurs.
