### ISSUE TITLE
Viewport: File > Save menu text fails to grey out after successfully saving a level

### ISSUE THREAD

**Issue by dm-amzn** [o3de/o3de#10632]
**Describe the bug**
Viewport: The File > Save menu text is not greyed out after successfully saving a level.prefab through the File dropdown menu or the hotkey shortcut Ctrl + S.

**Steps to reproduce**

1. Steps to reproduce the behavior:
2. Launch the Editor
3. Create a new level, or load an existing level
4. Make changes to the level
5. Save the level via FIle > Save and/or hotkey shortcut Ctrl + S
6. Select and open the File dropdown menu
7. Observe issue

**Expected behavior**
The File > Save menu text is greyed out after successfully saving a level.

**Actual behavior**
The File > Save menu text fails to grey out after successfully saving a level.

**Screenshots/Video**
![2022-07-12 17_04_02-Greenshot](https://user-images.githubusercontent.com/97991771/178620949-df48b483-6500-4cac-a625-67bc06717072.png)

https://user-images.githubusercontent.com/97991771/178620959-0a4229e2-e94a-4436-bbbd-c6e22a641602.mp4

**Found in Branch**
commit 1a8dab25b482bfc3f537e27faf49c2fb7688da67

**Comment by AMZN-daimini** [comment]
Is disabling the `Save` menu item if there's nothing to save standard in other DCC tools? Don't think I've noticed it anywhere else before :)

**Comment by dm-amzn** [comment]
True, it doesn't seem to be, I can close this one out.

I think getting more visual feedback that a save operation was completed successfully would probably be a better option. In UE5, there's a quick cursor transition from cross to cursor to cross when saving after changes have been made. In Blender, there's a quick cursor transtion to the Windows blue circle/wheel and back to the cursor when saving a project, even without changes being made. I created a feature request for something like that here: https://github.com/o3de/o3de/issues/10631

**Comment by AMZN-daimini** [comment]
Completely agree! We were hoping to implement a notification system, and this would be a great candidate to use it for sure.

**Comment by dm-amzn** [comment]
Closing.
