### ISSUE TITLE
[Multiplayer] Server-Only Entities

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#10633]
**Is your feature request related to a problem? Please describe.**
In the multiplayer sample there is an entity with a Camera component and a FlyCameraInputComponent. If you run the game sever with a 3d viewport enabled, this entity allows the user to navigate the authoritative scene. However, when this same entity is activated on the game client it conflicts with the character camera and causes it adverse behavior like popping and jittering. Removing this entity entirely will solve the character camera issues, but it also removes the ability to navigate the scene on the server.

**Describe the solution you'd like**
Make some way to mark the camera entity as server-only so it is never created/activated on the local game client. We suggest adding a server-only setting to the Network Binding component. When this flag is set, the entity will only be created/activated if the role is NetEntityRole::Authority.

**Describe alternatives you've considered**
It might be worth considering making the setting a bit more generalized, mark any applicable roles, per the NetEntityRole enum. Then an entity could be marked as only relevant to a user-configured subset of the available roles.

**Additional context**
See this PR https://github.com/o3de/o3de-multiplayersample/pull/167 where we attempted to fix the jittering game camera but inadvertently broke the server camera controls.

**Comment by santorac** [comment]
> Thanks @santorac for finding the cause of this issue. It's been mind boggling us for a while

Actually @AMZN-puvvadar gets the credit for finding the cause :)

**Comment by lmbr-pip** [comment]
Consensus seems to be we should avoid server only entities, instead fully implement the fly camera (see https://github.com/o3de/o3de/issues/10672)

@kberg-amzn and @AMZN-Gene to comment. For now closing as won't do.
