### ISSUE TITLE
Linux: IMGUI does not invoke on the first project launch and disabling it afterwards breaks it

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10641]
**Describe the bug**
On Linux, on a freshly built project, the Home key causes the mouse cursor to disappear, but no IMGUI bar shows up at the top of the Viewport. If that same project is closed, it's Immediate Mode GUI (IMGUI) Gem is disabled, then that project is rebuilt, the IMGUI ceases to work altogether (re-enabling it/rebuilding the project does not do anything).

It should be noted that on Windows, the IMGUI works without issue from the first project launch all the way through the rest of the listed reproduction steps.

**Steps to reproduce**
1. Create a new Default Template project, and build it.
2. Open the Editor, and wait for the Asset Processor to process all of the assets.
3. Create a level.
4. With the Viewport in focus, press Home. (Mouse cursor should disappear, but IMGUI bar is not invoked, pressing the Home key again returns it to normal behavior as if "closing" the IMGUI)
5. Close the Editor.
6. Open the Gems Configuration on the project created in step 1.
7. Disable the Immediate Mode GUI (IMGUI) Gem.
8. Rebuild the project.
9. Open the Editor, and launch the level created in step 3.
10. With the Viewport in focus, press Home. (As expected, nothing happens)
11. Close the Editor.
12. Open the Gems Configuration on the project created in step 1.
13. Enable the Immediate Mode GUI (IMGUI) Gem.
14. Rebuild the project.
15. Open the Editor, and launch the level created in step 3.
16. With the Viewport in focus, press Home.

**Expected behavior**
IMGUI bar shows up at the top of the Viewport, and issue mentioned in step 4 does not occur.

**Actual behavior**
Nothing happens, as if the IMGUI Gem was disabled.

**Video**

https://user-images.githubusercontent.com/86952082/178735660-69f89fb3-0137-40e1-b529-ebd72b40ea5a.mp4

**Found in Branch**
Development (f23a666)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by yuyihsu** [comment]
removing UI-UX sig label as this is just a bug and no need UX solution.
