### ISSUE TITLE
Feature Request - Set World Rotation Node for Script Canvas

### ISSUE THREAD

**Issue by LesaelR** [o3de/o3de#10647]
**Is your feature request related to a problem? Please describe.**
  Set World Rotation is only available as a node using quaternions.
  Set Local Rotation has the option for both euler angles and quaternions. 

**Describe the solution you'd like**
  Add a Set World Rotation node to script canvas.

**Describe alternatives you've considered**
  A single world/local rotation node with a bool for quaternions vs euler?

**Additional context**
![image](https://user-images.githubusercontent.com/89800757/178773878-56e74481-162a-4f4d-88cc-563edf9559cf.png)

**Comment by ParasiteSt** [comment]
Could I ask, what would be the need for a Set World Rotation node, and not just use the Set Local Rotation Node? I have been searching, and cannot find any reason to use world rotation over local.
