### ISSUE TITLE
Animation Editor Unified Inspector Window

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10666]
## Description

Currently the animation editor (EMFX) contains many separate panels that can be hard to understand and use efficiently. This roadmap items covers unifying the attribute windows into one contextual-based window to improve usability and consistency across the editor.

## Feature Points of Contact

Stakeholders: @amzn-jillich, @hultonha, @yuyihsu, @bhanuja-s 

## Links

https://github.com/o3de/sig-simulation/pull/22

**Comment by lgleim** [comment]
@hultonha Please add the relevant PR that close this issue. Please add the `notable` label if appropriate. Thanks.

**Comment by lgleim** [comment]
https://github.com/orgs/o3de/projects/7/views/1

**Comment by hultonha** [comment]
- https://github.com/o3de/o3de/pull/11114
- https://github.com/o3de/o3de/pull/11167
- https://github.com/o3de/o3de/pull/12809
- https://github.com/o3de/o3de/pull/11562
- https://github.com/o3de/o3de/pull/11595
- https://github.com/o3de/o3de/pull/11620
- https://github.com/o3de/o3de/pull/12694
- https://github.com/o3de/o3de/pull/12041
- https://github.com/o3de/o3de/pull/13216
- https://github.com/o3de/o3de/pull/13200
- https://github.com/o3de/o3de/pull/12060
- https://github.com/o3de/o3de/pull/12429
- https://github.com/o3de/o3de/pull/12594
- https://github.com/o3de/o3de/pull/13395
- https://github.com/o3de/o3de/pull/13400
- https://github.com/o3de/o3de/pull/13359
- https://github.com/o3de/o3de/pull/13384
- https://github.com/o3de/o3de/pull/13315
- https://github.com/o3de/o3de/pull/13360
- https://github.com/o3de/o3de/pull/13216
- https://github.com/o3de/o3de/pull/13371
- https://github.com/o3de/o3de/pull/13400
- https://github.com/o3de/o3de/pull/13416
- https://github.com/o3de/o3de/pull/13454
- https://github.com/o3de/o3de/pull/13385
- https://github.com/o3de/o3de/pull/13491
