### ISSUE TITLE
Navigation Support

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10663]
## Description

Path-finding/navigation support is a highly requested feature in all game engines and until recently, O3DE did not support a free, built-in navigation solution. To support this feature, an open source navigation library ([Recast](https://github.com/recastnavigation/recastnavigation)) will be integrated into O3DE and made available as an optional Gem in the main O3DE repo.

## Feature Points of Contact

Stakeholders: @hultonha, @AMZN-Olex 

## Links

- RFC - https://github.com/o3de/sig-simulation/issues/10
- PR(s) - https://github.com/o3de/o3de/pull/9799, https://github.com/o3de/o3de/pull/9900 (many more, search closed PRs with Navigation keyword, author: @AMZN-Olex

**Comment by ParasiteSt** [comment]
@hultonha Should this issue be closed as Navigation Support does seem to be included now in the Main O3DE repo?

**Comment by hultonha** [comment]
That's a great point @ParasiteSt 😄 Yes it most likely should be.

@AMZN-Olex would you be able to add any additional noteworthy PRs to the description (or as a comment) and I'll close this out as complete for now. Thank you!

**Comment by hultonha** [comment]
Closing issues as complete as O3DE does now support an integration with Recast navigation

**Comment by hultonha** [comment]
Note: I've also updated the roadmap - https://github.com/o3de/o3de/projects/1

**Comment by AMZN-Olex** [comment]
Here are the important PRs:
- https://github.com/o3de/o3de/pull/9799
- https://github.com/o3de/o3de/pull/9900
- https://github.com/o3de/o3de/pull/10105
- https://github.com/o3de/o3de/pull/10294
