### ISSUE TITLE
Migrate Multiplayer automation tests back from Sandox

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#10673]
**Describe the bug**
All the Multiplayer tests were sandboxed due to instability in https://github.com/o3de/o3de/pull/10434. This issue is a placeholder to stabilize and migrate tests back to main AR runs.

**Assets required**
None

**Steps to reproduce**
1. Look at https://github.com/o3de/o3de/pull/10434
2. Notice all the tests have been sandboxed

**Expected behavior**
Critical networking tests are running in AR.

**Actual behavior**
Tests are not running AR leading to potentially ungated PRs that could destabilize networking/Multiplayer.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by lmbr-pip** [comment]
@robhaco Assigning you to own ensuring tests are migrated back in by SIG-Network contributors. We should track this as an open issue until tests are re-enabled or we have new agreed test coverage plan for AR.

**Comment by AMZN-Gene** [comment]
This has cropped up again. The Walk the Engine (WTE) build failed to launch the server when using CTRL+G in editor. A mainline test would have caught that.

**Comment by AMZN-Gene** [comment]
Reopening, the last PR was a partial fix. It brought back 1 test (simple connection test) which doesn't rely on any scripting.
