### ISSUE TITLE
Uniform scale changes do not save when updating a prefab

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#10671]
**Describe the bug**
If the user instantiates a prefab and makes a change to the scale, then proceeds to save prefab to file.  The next time the user instantiates the prefab, the changes to scale will not be applied.

**Steps to reproduce**
1. Create a new prefab with a mesh component or similar for visibility
2. Scale the prefab
3. Right click in the Entity Outliner and select "Save Prefab to File"
4. Instantiate another copy of the now updated prefab

**Expected behavior**
Changes to the scale of a prefab are saved when updating the prefab on disk

**Actual behavior**
Changes to scale are not saved when the prefab is saved/updated

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82236902/179035823-4b8f056c-c9e6-4d86-ae82-89ecb7c98793.png)

**Found in Branch**
Development 4c8dabd8218

**Comment by monroegm** [comment]
This is by design if what you are changing the scale of is the prefab container. Transform changes on the container are always unique to the prefab instance. Please reopen if you were referring to something else.
