### ISSUE TITLE
GPU Device got removed while using the editor

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#10684]
**Crash when the GPU device is removed due to unknown reason**

During the production of a game jam entry, I experienced very frequent crashes due to the GPU device getting removed. There is no clear or consistent repro. Sometimes it happened during material editing, other times at runtime while testing the game.

**Assets required**
No custom assets needed, the issue can happen through normal use

**Found in Branch**
development

[callstack.txt](https://github.com/o3de/o3de/files/9117820/callstack.txt)

[main_thread_callstack.txt](https://github.com/o3de/o3de/files/9117822/main_thread_callstack.txt)

![gpu_removed](https://user-images.githubusercontent.com/58790905/179151468-7081527c-99bd-452b-8e60-f065f853e89e.png)

[DxDiag.txt](https://github.com/o3de/o3de/files/9117821/DxDiag.txt)

![dump_save](https://user-images.githubusercontent.com/58790905/179151463-d5be6566-0a64-43f6-bf46-22eaca57d3d8.png)

**Desktop/Device (please complete the following information):**
dxdiag.txt attached

Was unable to attach crash dump, Visual Studio failed when trying to produce it, see screenshot

```
The thread 0x24c8 has exited with code 0 (0x0).
D3D12: Removing Device.
Device: Device was removed because of the following reason:
<08:59:02> (Device) - Device was removed because of the following reason:
DX12: DXGI_ERROR_DEVICE_HUNG - The application's device failed due to badly formed commands sent by the application. This is an design-time issue that should be investigated and fixed.
<08:59:02> (DX12) - DXGI_ERROR_DEVICE_HUNG - The application's device failed due to badly formed commands sent by the application. This is an design-time issue that should be investigated and fixed.
DRED: Device removed! Writing DRED log to Logs\DRED/DRED_20220715.085902.log
<08:59:02> (DRED) - Device removed! Writing DRED log to o3de\Logs\DRED/DRED_20220715.085902.log
DRED: Finished writing DRED log 
```

**Comment by lsemp3d** [comment]
Also noticed the problem happens far more frequently when the editor is running on a secondary display and not the main display.

**Comment by moudgils** [comment]
@lsemp3d This is a gpu crash and unless I can repro (I will try syncing to the latest to check) it debugging it is much harder. There are ways to debug gpu crashes which are documented at the bottom of the page here - https://github.com/o3de/o3de/wiki/GPU-Crash-Debugging-and-Reporting
Since you are able to repro this easily my recommendation for you is to maybe try **DRED** or the recently added **CPU GPU lockstep mode** and see if either of those provide leads into why the gpu crashed.

**Comment by mcphedar** [comment]
@moudgils I can reproduce this by having the editor open and then running the MultiplayerSample.ServerLauncher, having it host a level and then running the multiplayerSample.GameLauncher  from the multiplayersample\build\windows\bin\profile directory. This also crashes the editor.

**Comment by HogJonny-AMZN** [comment]
For AMZN people: LYN-17803 (call stack in there)
That specifically started a reproducible TDR after I added GI to the level.
After saving, it then started crashing every time I tried to open the level.
https://github.com/aws-lumberyard-dev/o3de-multiplayersample/pull/103
