### ISSUE TITLE
Better default location for saving ScriptCanvas files

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#10698]
**Is your feature request related to a problem? Please describe.**
When saving a ScriptCanvas file, it always defaults to the folder where Editor.exe lives. This occurs not just the first time a new script is saved, but every time a new script is created and saved, or saved in a new file with 'save as'. This creates a source of friction while iterating when you have to browse through your directories looking for the right location, especially if your project is external to where the engine executables are.

**Describe the solution you'd like**
A better default location would be in the <project>/Scripts folder, or the most recently used (for ScriptCanvas) location.

**Describe alternatives you've considered**

**Additional context**
I'm seeing this on the development branch, commit 4c8dabd8218fc732a90fbb025944f3150ee1c7e1

**Comment by ParasiteSt** [comment]
I use a custom folder called /ScriptCanvas , and use the /Scripts folder for lua scripts, and lua includes. I like the idea of the most recently used location, this would suite everyone's location choice.
