### ISSUE TITLE
Material instance texture value is not maintained when changing levels.

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#10695]
**Describe the bug**
Removing the texture on a material instance works while the level is opened. Then after switching to another level and back, the texture value is not the same as when the level was saved.

**Steps to reproduce**
1. Open editor
2. Create new level called "Test".
3. Select Ground entity
4. In its material compoent select the arrow of the groundplane material.
5. Click on "Edit Material Instance"
6. Change the color
7. Remove the texture
8. Save level
9. Open another level.
10. Open back the "Test" level

**Expected behavior**
The changes done to the material instance is kept.

**Actual behavior**
The material instance has changed, the texture is back to be assigned to the material.

**Screenshots/Video**
https://user-images.githubusercontent.com/27999040/179268975-93937b2d-0d08-4566-9894-d6c90a9617d6.mp4

**Found in Branch**
development 9a15f038

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]

**Comment by gadams3** [comment]
Thanks for reporting! The last time anything like this happened it was related to prefab serialization. Will investigate to see if something has changed with material component serialization.

**Comment by gadams3** [comment]
This was likely related to prefabs and does not seem to be occurring anymore.
