### ISSUE TITLE
AR Bug Report

### ISSUE THREAD

**Issue by jcurtisk** [o3de/o3de#10711]
**Describe the bug**
`AutomatedTesting::EditorTests_Main.main::TEST_RUN` and `AutomatedTesting::SmokeTest.smoke::TEST_RUN` failed during an AR run for unrelated changes. `AutomatedTesting::SmokeTest.smoke::TEST_RUN` failed in both windows and linux jobs, but `AutomatedTesting::EditorTests_Main.main::TEST_RUN` only failed on the windows build.

**Failed Jenkins Job Information:**
The name of the job that failed, job build number, and code snippit of the failure.
Platform/Job: Windows/test_cpu_profile and Linux/test_profile_nounity
**Attachments**
Attach the Jenkins job log as a .txt file and any other relevant information.
[Windows AR Failures](https://github.com/o3de/o3de/files/9130851/windows.ar.failures.txt)
[linux ar failures.txt](https://github.com/o3de/o3de/files/9130866/linux.ar.failures.txt)

**Comment by lmbr-pip** [comment]
Looks like this should be split into two issues, one for EditorTests and one for SmokeTest

**Comment by jckand-amzn** [comment]
Both of these issues are either already logged, or have been addressed:

https://github.com/o3de/o3de/issues/6731
https://github.com/o3de/o3de/pull/11143

Closing this ticket out.
