### ISSUE TITLE
Typos in tooltips of Script Canvas nodes in the Math category

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#10713]
**Describe the bug**
Some of the node tooltips in the Math category have typos.
Math>Substract node tooltip says "Substracts two **of** more elements", should be "Substracts two **or** more elements".
Math>Multiply node tooltip says "Multiplies two **of** more values", should be "Multiplies two **or** more values".
Tooltips of all nodes that set single fields of vectors (full list in steps to reproduce) say "Returns **a the** vector(...)", should be "Returns **a** vector(...)".

**Steps to reproduce**
1. Open the Editor.
2. Open the Script Canvas tool and create a new graph.
3. Open the Node Palette (Tools>Node Palette).
4. In the Node Palette, hover over Math>Substract and Math>Multiply nodes.
5. Add following nodes to the graph:
- Math>Vector2>SetX
- Math>Vector2>SetY
- Math>Vector3>SetX
- Math>Vector3>SetY
- Math>Vector3>SetZ
- Math>Vector4>SetX
- Math>Vector4>SetY
- Math>Vector4>SetZ
- Math>Vector4>SetW
6. Hover the mouse over nodes added in step 5.

**Expected behavior**
Tooltips are free of typos.

**Actual behavior**
Tooltips have typos.

**Screenshots**
![image (5)](https://user-images.githubusercontent.com/99388484/179523969-6044086c-a203-4ee6-904f-534008e66224.png)
![image (4)](https://user-images.githubusercontent.com/99388484/179523973-a78fea52-6d8d-48b6-bc08-b173141e2c93.png)
![image (3)](https://user-images.githubusercontent.com/99388484/179523975-a200b597-5fc7-4510-91e6-cfa03b0f5271.png)

**Found in Branch**
Development (403ff18)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by LB-KatarzynaDylska** [comment]
Reopening the issue. The vector nodes have all been corrected, but the Maths/Substract and Maths/Multiply nodes still contain typos mentioned above. Verified on Development (59df478) build.

**Comment by lsemp3d** [comment]
> Reopening the issue. The vector nodes have all been corrected, but the Maths/Substract and Maths/Multiply nodes still contain typos mentioned above. Verified on Development ([59df478](https://github.com/o3de/o3de/commit/59df478f5f8cd0af0c0d14f76eb5595b195ba29e)) build.

Ah, I missed those

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (ec2bdbe) build.
