### ISSUE TITLE
Feature Request - Look for already previous generated source materials of added mesh.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#10723]
**Is your feature request related to a problem? Please describe.**
Look for already previous generated source materials of added mesh. Example, Bringing a 3D mesh asset from another project that had already o3de materials generated for the asset, did not automatically find these materials and needed to have them manually added over again.

**Describe the solution you'd like**
Maybe a Button to Scan for Generated Materials maybe..
![image](https://user-images.githubusercontent.com/87207603/179612896-aaf5f6c3-4ce6-46f1-806e-f341f7074166.png)

**Comment by shawstar** [comment]
Sorry, I just noticed that Generate Manage Source Materials did exactly that.. I guess I was just scared I would wipe mine out do to the wording Generate/Manage ... maybe the button actually Generate/Scan Source Materials?

**Comment by lmbr-pip** [comment]
Unsure if SIG-Graphics or SIG-Content owns the mesh or material components. Assuming SIG-Graphics, please reassign if incorrect.

**Comment by galibzon** [comment]
It seems there's no bug here. Closing.
