### ISSUE TITLE
Bug Report - Spawning Prefabs of levels does not preserve Material Instances

### ISSUE THREAD

**Issue by cdomingo** [o3de/o3de#10728]
**Describe the bug**
A clear and concise description of what the bug is. Try to isolate the issue to help the community to reproduce it easily and increase chances for a fast fix.

When using Prefab Spawning to spawn a level, materials which are saved as Material Instances are not preserved - only material sources are preserved.

**Assets required**
None

**Steps to reproduce**
- Create a new level (1)
- Apply a material instance to an entity
- Create a different level (2)
- Use Prefab Spawn within the level (2) to spawn the previous level (1)
- The entity with the material instance will only show the material source

**Expected behavior**
Any material within a level should be preserved when that level is spawned

**Actual behavior**
Only source materials are preserved when a level is spawned

**Screenshots/Video**

https://user-images.githubusercontent.com/4985611/179627825-08cdeade-d510-4874-a599-a861edb3464d.mp4

https://user-images.githubusercontent.com/4985611/179627802-26173c6e-de09-44da-a201-85f3cd4d8582.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel i9-11900H
 - GPU: NVIDIA RTX 3070 Laptop
 - Memory: 32 GB

**Comment by monroegm** [comment]
Rerouting to SIG-Graphics-Audio to see if this is a material issue. SIG-Content can take it back if it is determined this is likely an issue with the prefab system.

**Comment by cdomingo** [comment]
@lsemp3d No this is still open

**Comment by gadams3** [comment]
Resolved by the following PR https://github.com/o3de/o3de/pull/11325
