### ISSUE TITLE
Bug Report: Navigation Mesh with Terrain 

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#10739]
**Describe the bug**
If you use the navigation with a terrain set up, and Update Navigation Mesh Async in script canvas the ram usage skyrockets, and your level's fps drops dramatically. (Update Navigation Mesh, not just the Async node both have the same effect)

**Assets required**
Terrain Gem
Recast Navigation Gem

**Steps to reproduce**
1. Create a terrain that is more complex than just the groundplane, make it have small hills.
2. Set up a navigation region, and create a script canvas that updates the Navigation Mesh Async
3. Go into game view, and see the error.

**Expected behavior**
Using navigation with Terrain should be no different than using the navigation with a pre-made mesh.

**Actual behavior**
The Navigation update bogs down the level and does not seem to recover from it in runtime.

**Found in Branch**
Development [cd1594b]

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11

**Comment by AMZN-Olex** [comment]
Could you prepare a test level, zip it up and attach it to this issue for an easier repro? I have played around with a terrain and didn't notice sluggishness.

**Comment by ParasiteSt** [comment]
Sure no problem, this is the level zip :
[NavigationTerrainLevel.zip](https://github.com/o3de/o3de/files/9144019/NavigationTerrainLevel.zip)

You just have to put the script canvas graph in the entity that specifies it. Other than that, the gems that are needed to be enabled are Terrain, Recast Navigation, and Gradient gems.
