### ISSUE TITLE
Linux: Input stutters after a while of holding it down

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10759]
**Describe the bug**
On Linux, holding an input key causes it to stutter/slow down, while in the Game Mode.

Stutters/slowdowns can be seen on the BasicMovementLinux.mp4 video in the **Videos, and entity setup screenshots** section, for example on: 0:42, 0:46, 0:49, 0:50, or 0:54 - 0:59 ("stair-like" movement diagonally). 

It should be noted that this issue does not occur on Windows on neither the DX12, nor the Vulkan RHI (relevant Windows videos can be found in the **Videos, and entity setup screenshots** section).

Please note that this issue is created as requested in the https://github.com/o3de/o3de/issues/10637#issuecomment-1189447553.

**Assets required**
A player entity as shown on the videos, or the attached screenshots in the **Videos, and entity setup screenshots** section, .scriptcanvas, and .inputbindings assets can be found here: [ScriptCanvas&InputBindings.zip](https://github.com/o3de/o3de/files/9149970/ScriptCanvas.InputBindings.zip) (or if the assets provided cannot be used for any reason, their screenshots can be used to recreate them).

**Steps to reproduce**
1. Create a new level.
2. Remove the "Camera" child entity of the Atom Default Environment.
3. Recreate a player entity mentioned in the **Assets required** section.
4. (Optional) Copy the "Shader Ball" child entity of the Atom Default Environment non-symmetrically around the level, and/or add additional Mesh entities, so that the movement is more distinguishable during motion.
5. Enter the Game Mode.
6. Navigate the level by holding W, A, S, D (or any of their combinations) by holding them for a few seconds at a time, and rotating using the mouse.

**Expected behavior**
Movement is fluid.

**Actual behavior**
Movement seems to slow down while moving in straight lines (W, A, S, D), and stutter while moving diagonally (for example W + A - forward + left, or S + D - back + right).

**Videos, and entity setup screenshots**

https://user-images.githubusercontent.com/86952082/179978428-6efd3f6d-0b26-486e-acbc-860c59109b30.mp4

https://user-images.githubusercontent.com/86952082/179978528-669a4f0c-c466-425b-befc-2b747b75d5bf.mp4

https://user-images.githubusercontent.com/86952082/179978781-46a02f15-0773-45b9-827d-24278a96d17e.mp4

Player entity component setup:
![BasicMovementPlayerEntitySetup0](https://user-images.githubusercontent.com/86952082/179978887-2cf5c4ef-d2ea-481d-b7e8-721a9e4741a3.png)
![BasicMovementPlayerEntitySetup1](https://user-images.githubusercontent.com/86952082/179978891-eba30683-7ffc-41f3-a0ef-297942ae6f6a.png)
![BasicMovementPlayerEntitySetup2](https://user-images.githubusercontent.com/86952082/179978897-78995a74-12e6-4844-ab37-1973e58d1610.png)

Player entity .inputbindings asset:
![BasicMovementInputBindings](https://user-images.githubusercontent.com/86952082/179979042-03557afd-a4b0-4a23-a118-c2fafd1a7a9c.png)

Player entity .scriptcanvas asset:
![BasicMovementScriptCanvas](https://user-images.githubusercontent.com/86952082/179979088-b641489b-84f0-4061-9d15-c5037075353e.png)

**Found in Branch**
Development (fece32d)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by monroegm** [comment]
Sending this over to SIG-Core who we believe own the underlying input runtime

**Comment by lumberyard-employee-dm** [comment]
Adding @o3de/sig-platform since the issue is related to the xcb bindings on Linux

**Comment by gralco** [comment]
However, if I throw in an `AZ_Printf` statement inside my `OnPressed(float value)` function, I see that when I press and hold a single key (such as the one I use for moving forward) it will print the message once, then nothing for maybe around 1 second, and then continuously spam that message after that approximately 1 second has elapsed.

Contracting this with a windows machine, apparently it only gets printed the one time, when it was initially pressed. When held it does not repeatedly call the `OnPressed(float value)` function.

So there is likely still some underlying bug with xcb that makes it inconsistent with what's happening on windows.

The behavior is effectively identical to when you press and hold a key inside a text editor. There's approximately 1 second of dead time before it starts to "spam" the character.
