### ISSUE TITLE
Enabling the Use Baked Heightfield slider without having Heightfield baked crashes the Editor

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#10792]
**Describe the bug**
The Use Baked Heightfield option in the PhysX Heightfield Collider can be enabled without having the Heightfield baked. Enabling it in such state crashes the Editor.
Please refer to the attached video and log files for more details.

**Steps to reproduce**
1.  Steps to reproduce the behavior:
2. Create an entity with PhysX Heightfield Collider component.
3. Add required components.
4. Click on the Use Baked Heightfield slider.

**Expected behavior**
 The Use Baked Heightfield option is grayed out when Heightfield is not baked. Another option is to show a pop-up warning when Heightfield is used without baking first. The Editor remains stable.
 
**Actual behavior**
 The Editor crashes.
 
**Video**

https://user-images.githubusercontent.com/86953282/180210999-d8b6f6a0-5848-4ee6-9e11-7d13dbb7724d.mp4

**Found in Branch**
Development (6be9441)

**Desktop/Device:**
 • Device: PC
 • OS: Windows
 • Version: 10 Pro
 • CPU: Intel Core i7 11700F
 • GPU: Nvidia RTX 3070 LHR
 • Memory: 32GB
 
 **Attachments**
[Editor.log](https://github.com/o3de/o3de/files/9159256/Editor.log)
[error.log](https://github.com/o3de/o3de/files/9159257/error.log)
[error.001.zip](https://github.com/o3de/o3de/files/9159384/error.001.zip)
[error.002.zip](https://github.com/o3de/o3de/files/9159382/error.002.zip)
[error.003.zip](https://github.com/o3de/o3de/files/9159383/error.003.zip)

**Comment by lgleim** [comment]
@SergeyAMZN Could you have a look at this?

**Comment by LB-KacperSzczepanski** [comment]
The Use Baked Heightfield option is grayed out on Windows but the fix was not applied on Linux. Both platforms were tested on build Development (663ed56)

https://user-images.githubusercontent.com/86953282/180992122-1f1ca2fa-fe40-480d-985a-aab16a7a0135.mp4

**Comment by LB-KacperSzczepanski** [comment]
The issue does not reproduce on other machines. I will verify it tomorrow on a new build and closed if it does not occur.

**Comment by LB-KacperSzczepanski** [comment]
Issue verified as fixed on build Development (616902d).
