### ISSUE TITLE
It is impossible to add remote gem using the project launcher (o3de.exe)

### ISSUE THREAD

**Issue by amzn-rhhong** [o3de/o3de#10811]
**Describe the bug**
https://github.com/o3de/o3de-multiplayersample-assets I tried to follow the steps in here but using the project launcher, but it is not possible to register the gem in this GUI tool.

**Assets required**
![image](https://user-images.githubusercontent.com/69218254/180329635-d269b178-d539-45b7-955d-820bb9ca4083.png)
![image](https://user-images.githubusercontent.com/69218254/180329670-2c27a76d-734d-41f9-a4b5-9b82f2fdca32.png)

**Steps to reproduce**
1. Build the editor and multiplayer project using project centric way.
2. Download the multiplayer sample gem
3. Open project launcher
4. Click Gems -> Add existing gem, browse to multiplayer asset gem
5. Error pop up

**Expected behavior**
Gem got added

**Actual behavior**
![image](https://user-images.githubusercontent.com/69218254/180329953-f16ce5e5-8194-4345-88fb-ce5bca9fabcf.png)

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by lmbr-pip** [comment]
Assuming this is sig/content but unsure if adding gems is owned by SIG/build. Tagged both SIGs and will allow their triage process to decided owner.

**Comment by AMZN-alexpete** [comment]
Hi @amzn-rhhong I think there are a couple issues here.  The first is that https://github.com/o3de/o3de-multiplayersample-assets is not a gem repo (it has no repo.json) file so it cannot be added using the Gem repository functionality. 

The second issue is that  https://github.com/o3de/o3de-multiplayersample-assets does not contain a single gem (no gem.json at the root) and so when you clone it you cannot just register that path as a gem.  It contains 7 gems in the `Gems` subfolder https://github.com/o3de/o3de-multiplayersample-assets/tree/main/Gems, so you'd need to add/register each Gem individually using `Add existing Gem` or register the single "group" gem I added recently which will add them all.  For your use case, that path looks like this:
`F:\o3de\gamejam\o3de-multiplayersample-assets\Gems`

You can use the 'Add exiting Gem' option with that path or the command line like so:
`o3de register -gp F:\o3de\gamejam\o3de-multiplayersample-assets\Gems`

**Comment by AMZN-alexpete** [comment]
Marking as fixed as the group gem path has been added to the o3de-multiplayersample-assets to address this issue.
