### ISSUE TITLE
[Network] Hosting in a Game Launcher is broken

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#10824]
**Describe the bug**
Game Launcher is not able to act as a network host when using `host` command.

**Steps to reproduce**
1. Create a multiplayer project or use o3de-multiplayersample
2. Launch AP
3. Launch game launcher
4. In a game launcher, bring up imgui console and enter `host` command
5. Then load a level, for example `loadlevel samplebase` if you using o3de-multiplayersample

**Expected behavior**
Game launcher acts as a network host and able to host a level.

**Actual behavior**
Host command fails.
Loading a level afterwards results in a broken level.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/5432499/180483364-604004ac-abc4-44e8-befd-46624ee0289e.png)

**Found in Branch**
o3de-multiplayersample development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Comment by AMZN-Gene** [comment]
Because hosting in game launchers with use a ClientServer agent type a new client will try to be added to the game as soon as hosting starts however there’s no level loaded so there’s no spawner.

We also don’t support loading into a networked level before hosting.
