### ISSUE TITLE
ServerLauncher Debug Text

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#10839]
**Is your feature request related to a problem? Please describe.**
Even when running a server with graphics enabled, the debug text doesn't render. 
I'd like to see my normal debug stats (like fps, etc).
This would also open the oppurtunity to display Multiplayer information. For example: My agent type (dedicated-server or client-server) or the number of clients connected.

**Describe the solution you'd like**
It seems even though rendering is enabled, the font system isn't? Enable the Atom font system.

Blocked by #10868

**Comment by lmbr-pip** [comment]
Code currently always uses the NullFont in `AtomFontSystemComponent::OnCrySystemInitialized` which then causes all Atom rendered draw text to be skipped.

Need to remove/change the gEnv->IsDedicated check in this code, temporarily disabling this check allows debug draw text rendering and shows FPS blocks

**Comment by lmbr-pip** [comment]
Tagging in sig/graphics-audio for comment and thoughts. IMHO looks like we should tie use of null font to render options rather dedicated server check ie if using null renderer then use null font?

**Comment by lmbr-pip** [comment]
This issue relates to https://github.com/o3de/o3de/issues/10868

**Comment by AMZN-Gene** [comment]
Fixed! #11128
