### ISSUE TITLE
Bug Report: Viewport Controls UI Clusters are missing when in Component Editing Mode

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de#10832]
**Describe the bug**

When a user enters Component Editing Mode, the Viewport UI Clusters (Transform, Rotate and Scale) should still be visible to the user.

For some reason it is missing all the Viewport UI Clusters for all the component modes. Although when I enter White Box Component Editing Mode, I can still see some viewport UI clusters there. 

The Transform, Rotate and Scale Viewport UI Cluster should be there for all component editing modes, to allow the user to move their object as pleases.

**Assets required**
No assets needed.

**Steps to reproduce**
1. Create an entity in O3DE editor.
2. Add a box shape component.
3. The Transform, rotate and Scale Viewport UI Clusters are missing.
4. This is relevant for all component editing modes that involve a shape of some sort.

**Expected behavior**
I expect to see the basic Transform, Rotate and Scale Viewport UI Cluster Controls when I am in most of the component editing modes.

**Actual behavior**
They are missing from the top left. (Its weird that on my build it was completely missing, but it was not missing from another person's build when they tested it)

**Screenshots/Video**
Video attached of me demonstrating the workflow for missing buttons

https://user-images.githubusercontent.com/82846749/180578614-50bb7dc4-e875-4538-9ed5-9106a5a5cadb.mp4

**Found in Branch**
Release normal exe 2205

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**

**Comment by hultonha** [comment]
@amzn-leenguy This is by design - in Component Mode, you cannot change the global translate/rotate/scale options, so we don't show them. They are replaced by Edit/Component Mode specific options.
