### ISSUE TITLE
Feature Request- [Prism] Working PythonTool Gem sample, in a Remote Gem Repo

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#10836]
Description:  We need a working repot gem repo, which has various types of working examples of Gems; one of these should be a python tool gem.

This docs link, refers to a sample-code-gems github repo: https://www.o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/

The repo is: https://github.com/o3de/sample-code-gems/tree/main/py_gems/PyShapeExample

During an RTE session, the User tried to add this regular to the o3de project manager: https://github.com/o3de/sample-code-gems/tree/main/py_gems/PyShapeExample

The User didn't know what a Remote Gem Repository is...
They didn't know that this sample-code-gems repo was just a normal repo and not a remote gem repo (this confused them)
AC:

We need a working Remote Gem repo (and/or revise the sample-code-gems repo to be one)
UX/CX to help users understand the concept of a remote gem repo
Update the RTE user-test scenarios to have the user have a task to add access to a remote gem repo to the project manager and enable a sample gem in their project.  This task should happen early before asking them to craft their own Gem.
RTE WF8 docs to be updated:

C++ user-test scenario doc: https://quip-amazon.com/Zt5mAAkfa3ea/WF8-Item-16a-C-Engine-Editor-Extension-User-Test-Scenarios

Python version: https://quip-amazon.com/9Yo4AhmT40a9/WF8-Item-16b-Python-Editor-Extension-User-Test-Scenarios

**Comment by yuyihsu** [comment]
related to LYN-13701.

**Comment by Ulrick28** [comment]
If I understand correctly, WTE would like a remote repo setup for the python gem. We can provide documentation how how to set this up to whomever owns the gem.

**Comment by yuyihsu** [comment]
@cgalvan , can you work with @Ulrick28 and @AMZN-Phil  to have the sample gem repo ready, and @Ulrick28 will help setup the repo to support the remote gem.

**Comment by chanmosq** [comment]
@o3de/sig-content Is there a workflow for downloading remote gem repos through the Project Manager?

When there's updates and solution to this issue, Docs can update the tutorial (e.g. PyShapeExample) to use the workflow for remote Gem repos.

**Comment by cgalvan** [comment]
https://github.com/o3de/sample-code-gems has been updated to be a remote gem repository and can now be accessed in the Project Manager, which then pulls down the gems.
