### ISSUE TITLE
Bug Report: the FBX Settings Dialog covers the loading error log dialog

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de#10835]
**Describe the bug**
When a user double clicks an asset in the asset browser for an FBX, the FBX Settings window overlays and seems "Frozen", but really the error log is hidden behind it. This can be confusing and frustrating to the user, since the FBX setting appears as disabled, but if you dont see the dialog with the error log in it, you can be confused.

**Assets required**
I was loading this tree asset that I downloaded, and it had errors, so its a good example to test.
https://www.turbosquid.com/3d-models/tree-pixel-low-poly-3d-model-1764347

**Steps to reproduce**
1. Go to Asset Browser
2. Double click on an FBX asset, to launch the FBX Settings for that asset
3. As long as the asset has some sort of errors, you will notice that the error dialog box is not loading on top (and taking focus priority) 

**Expected behavior**
The error log dialog box should take focus priority. 

**Actual behavior**
The error log dialog box is hidden behind.

**Screenshots/Video**
Video of me demonstrating the bad ux.

https://user-images.githubusercontent.com/82846749/180579003-59432bb5-ad62-419b-990d-966e228decf8.mp4

**Found in Branch**
Release 2205 exe 

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
@rainbj may have a proposed solution to rework the section of this workflow, but as an short term solution, this frustrating for the user.

**Comment by AMZN-stankowi** [comment]
Assigning to myself, this will get fixed when we embed that log window into the scene settings window itself

**Comment by lmbr-pip** [comment]
Believe this will be addressed as part of https://github.com/o3de/o3de/pull/11719

**Comment by AMZN-stankowi** [comment]
This can no longer occur because the dialog has been replaced with log cards in the window
