### ISSUE TITLE
[Linux] Ubuntu. Does #9889 solve ssl problem??

### ISSUE THREAD

**Issue by L4exp** [o3de/o3de#10855]
**Describe the bug**
Installation from git or running Editor, which installed from deb package breaks of missing ssl lib.

**Assets required**

**Steps to reproduce**
Download git and run python installation 
python/get_python.sh

or 

after installation from deb output of running editor, gives error of missing ssl 1.1

**Expected behavior**
Engine installing from git and Editor runs from deb installation without ssl errors 

**Actual behavior**
Installation and Editors breaks down of ssl errors

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Development: git and deb, 
for git:
    commit 13bd32de6aae98b4ff8ac9d56ebce11b1419b413
for deb - from 2022-07-25 build

**Desktop/Device (please complete the following information):**
Device:PC
OS: Linux
Version: Ubuntu 22.04
CPU: dual intel xeon 2699v3
GPU: AMD Radeon VII
Memory: 192Gb

**Additional context**
After migrating to ubuntu,
through two ways of installing engine(from deb, from git) gives errors related with ssl.
1) From deb, installing fine, but after run Editor - this:
./Editor: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

2) In git version(commit 13bd32de6aae98b4ff8ac9d56ebce11b1419b413), on
python/get_python.sh
it could not download and install python lib:
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/atomicwrites/

libssl already installed. It is 3rd version.

ldconfig -p | grep libssl
        libssl3.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl3.so
        libssl3.so (libc6) => /lib/i386-linux-gnu/libssl3.so
        libssl.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.3
        libssl.so.3 (libc6) => /lib/i386-linux-gnu/libssl.so.3
        libssl.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so

It seems, that renaming .so triks not a good way in this case.
AFAIK, something like including crypto in libssl in v3 and in v1 it is thow different entities...

Or i something misunderstand and there is way(s) to solve it, and,
some recipies like
[https://help.dreamhost.com/hc/en-us/articles/360001435926-Installing-OpenSSL-locally-under-your-username](openssl1.1 installation)
should give result? But that does'nt.

**Comment by L4exp** [comment]
Ok, after reboot - it just work. Most likely solution is v1.1 lib after installation. Anyway try it on VM later. But messages like missing ssl 1.1 is not good sign.

**Comment by spham-amzn** [comment]
This was fixed with the [Python 3.10.5 update](https://github.com/o3de/o3de/commit/607c548791f2170b4d23a8cac191be1b834ca15b)

**Comment by L4exp** [comment]
Cool! Thanks!
