### ISSUE TITLE
[Linux] Ubuntu. Is #9824 - MaxUnboundedArrayDescriptors (GHI-9812) - enough to fix issue with descryptors?

### ISSUE THREAD

**Issue by L4exp** [o3de/o3de#10875]
Describe the bug
Activating terrain renderer gives editor's quit
(Vulkan) - Failed to initialize DescriptorSet

Steps to reproduce
Add terrain gem to project.
To level, add terrain world and terrain renderer component(activate)

Expected behavior
Adding terrain world and terraint renderer allows work with terrain

Actual behavior
Adding terrain world and renderer invokes quit from editor

Found in Branch
Development: git and deb,
for git:
commit https://github.com/o3de/o3de/commit/13bd32de6aae98b4ff8ac9d56ebce11b1419b413
for deb - from 2022-07-25 build

Desktop/Device (please complete the following information):
Device:PC
OS: Linux
Version: Ubuntu 22.04
CPU: dual intel xeon 2699v3
GPU: AMD Radeon VII
Memory: 192Gb

Additional context
Before migrating to ubuntu, #9824 not solve problem, but it seems like duplicating any entity on NON DEB distributives - gives this overflow.
But after migrating to Ubuntu, without any duplication of entities, problem still exists.

**Comment by pollend** [comment]
can you provide the logs from the editor?

**Comment by L4exp** [comment]
> can you provide the logs from the editor?

Something like this
[Editor.log](https://github.com/o3de/o3de/files/9187990/Editor.log)

**Comment by rgba16f** [comment]
I'm able to add the Terrain World and Terrain Render components to the level on my machine on comit 60d1a0955

Desktop/Device (please complete the following information):
Device:PC
OS: Linux
Version: Ubuntu 20.04.4 LTS
CPU: Intel Core i7-5930
GPU: Radeon RX Vega (VEGA10, DRM 3.42.0, 5.15.0-41-generic, LLVM 12.0.0)
Memory: 64GB

I can also load the terrain test level in the AutomatedTesting project - o3de/AutomatedTesting/Levels/Terrain/TerrainPhysicsCollider_MaterialMapping_Works

I'll

**Comment by rgba16f** [comment]
I don't see the crash on the AutomatedTesting project @ 13bd32d on the same machine. I can load the base level and add the terrain world and terrain world render components to the level entity.

**Comment by rgba16f** [comment]
From the log you have exceeded your GPU's memory
`(System) - ASSERT: Vulkan API method failed: Out of device memory`

Is the level already populated with a lot of assets?
