### ISSUE TITLE
Unassigning a Model Asset in the Material Editor turns its viewport red

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10879]
**Describe the bug**
If a Model Asset used in the Material Editor's Viewport Settings > Model Settings is removed, the Material Editor viewport turns red.

**Steps to reproduce**
1. Go to Tools > Material Editor.
2. In the Material Editor go to Tools > Viewport Settings.
3. In the Viewport Settings go to Model Settings, and press the "X" next to the assigned Model Asset.

**Expected behavior**
Viewport does not display any mesh. The background remains unchanged.

**Actual behavior**
Viewport turns red.

**Video**

https://user-images.githubusercontent.com/86952082/181003059-962d953a-7df4-4506-a427-204294bfa69e.mp4

**Found in Branch**
Development (663ed56)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by galibzon** [comment]
@gadams3 , I think this is by design. Can you confirm?

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization/2210 (2a5ac3d) build.
