### ISSUE TITLE
Feature Request - [DCCsi] Wrap Maya FBX Exporter with Studio Tools

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#10887]
As a User, I would like a set of validation tools for meshes while working in DCC tools, so I can more easily identify issues with a model before it is exported to the engine.

One example is an nGon checker. Due to things like winding order or algorithm, an nGon could be triangulated differently ... and we have seen this happen, where Assimp incorrectly triangulates the nGon and this can not be fixed on the engine side (it would be better to flag the concern upstream)

FBX also already has a 'triangulate flag' in it's setting, theoretically this is another way to fix this issue, as the nGon would be triangulated within the exported FBX.  We can also wrap the FBX exporter and it's settings to provide both an automated validation and export workflow.

Description:

Create a set of automated validation tools (added to Maya via python in DCCsi)
User can manually run validation tools, this validation would flag nGons with a warning and help user easily repair/triangulate them.
Provide a tool that wraps the FBX exporter and settings, enable settings like 'triangulation' by default.
Validation tools are enabled by default as a pre-flight check during automated FBX export
User workflow:

O3DE studio tools include a FBX exporter panel
This panel manages the FBX exporter settings to provide the best defaults for O3DE
This panel also includes settings and configuration of validation tools
The User uses the O3DE FBX export tool:
The tool runs validation and generates a log/report
The tool performs the ideal export

**Comment by HogJonny-AMZN** [comment]
A 'scene exporter' for Maya, could wrap the FBX exporter (similar to what we've done with Blender)

One of the options would be to enable triangulation in the exported FBX data:
https://github.com/o3de/o3de/issues/10023

**Comment by HogJonny-AMZN** [comment]
There is a critical path planned for the CX in an internal AWS doc, which connect with other work in progress to complete an end-to-end CX, here is a brief outline to get to this GHI (from the user perspective)

User enables  DccScriptingInterface Gem (aka DCCsi) in their project (enabled 'Studio Tools' menu in editor)
File menu bar > Tools > Studio Tools > DccScriptingInterface Help (take User to readme.md)
User can Launch DCC tool (Maya) from 'Studio Tools' menu.
File menu bar > Tools > Studio Tools > DCC > Maya
In DCC tool (Maya) there is an 'O3DE Tools' menu
User can start 'O3DE Scene Exporter'
DCC File Menu > O3DE Tools > Scene Exporter
User can run the validation tools.
User can export with O3DE FBX options.

**Comment by tonybalandiuk** [comment]
Will this be in the 22.10.0 release @svitlani ? If no, then please remove the "Release/2210" milestone. Thanks

**Comment by HogJonny-AMZN** [comment]
The last PR did not complete this story, it was closed on accident.

**Comment by HogJonny-AMZN** [comment]
The nGon  checker and validation tools was split off: https://github.com/o3de/o3de/issues/13056

**Comment by HogJonny-AMZN** [comment]
We closed  this ticket as the main FBX  Scene Export tool exists in the last PR
