### ISSUE TITLE
BUG - Asset browser - prefab filter not working

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#10889]
BUG details
In the Asset Browser, the filter for prefab doesn't actually find prefab. Users. I assume this is because there is a child procprefab inside every FBX. However, users in this instance are not looking for a procprefab they are just looking for prefabs.

**Describe the solution you'd like**
Inside the dropdown, separate out procprefab and prefabs. Also make sure prefabs only find levels and prefabs not FBX. We have an FBX filter and should also have a procprefab filter

**Describe alternatives you've considered**
@lsemp3d  and @monroegm  - for visibility.

**Comment by rainbj** [comment]
Currently searching for prefabs in the asset browser, it doesn't locate prefabs, it only pretends to find them.

<img width="569" alt="2022-08-04_11-48-57" src="https://user-images.githubusercontent.com/82551958/182906669-956f30db-100b-4f35-b6b4-4b7dfff98d77.png">

**Comment by amzn-leenguy** [comment]
Since this is a bug, we will remove ourselves (UX) from this ticket. Thanks @sphrose
