### ISSUE TITLE
Feature Request - regroup the component under Atom based on feature

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#10891]
**Is your feature request related to a problem? Please describe.**
A bunch of components are grouped under Atom. However, Atom isn't a feature, and it makes it hard for users to be able to quickly identify the components they are looking for.

**Describe the solution you'd like**
We should regroup the components under Atom, and regroup them based on features, such as Lighting, PostFX, etc.

**Describe alternatives you've considered**
N/a
**Additional context**
N/A

**Comment by galibzon** [comment]
Here is a proposed arrangement:

> Graphics - Lights
- Light
- Directional Light
- Global Skylight (IBL)
- CubeMap Capture
- Diffuse Probe Grid
- Occlusion Culling Plane
- Reflection Probe

> Graphics - Mesh
- Mesh
- Decal
- Material
- Hair

> Graphics - PostFX
- Look Modification
- HDR Color Grading
- Exposure Control
- Display Mapper
- Depth Of Field
- Bloom
- Chromatic Aberration
- Deferred Fog
- PostFX Gradient Weight Modifier
- PostFX Layer
- PostFX Radius Weight Modifier
- PostFX Shape Weight Modifier
- SSAO

> Graphics - Environment
- HDRi Skybox
- Physical Sky
- Sky Atmosphere
- Stars

> Graphics - Other
- Entity Reference
- Grid

**Comment by galibzon** [comment]
This feature request has been completed.
