### ISSUE TITLE
Linux: Material Canvas crashes when more than 16 nodes are added to the graph

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10904]
**Describe the bug**
Adding more than 16 nodes to the Material Canvas graph on Linux causes it to silently crash. 

It should be noted that on Windows this does not occur - 25 nodes were added and the Material Canvas remained stable. 

It should also be noted that no error.log/error.dmp files were generated, so a fresh MaterialCanvas.log was provided in the **Video and log** section instead.

**Prerequisites**
A project built in O3DE.

**Steps to reproduce**
1. In the Terminal, navigate to the build Default folder (for example /o3de-install/bin/Linux/profile/Default/).
2. Launch the MaterialCanvas with --project-path argument referencing built O3DE project (for example `sudo ./MaterialCanvas --project-path=/root/O3DE/Projects/<Project name>`).
3. In the Material Canvas, create a new graph (File > New).
4. Add 16 nodes to the graph.
5. Add one more node to the graph.

**Expected behavior**
Material Canvas remains stable.

**Actual behavior**
Material Canvas crashes.

**Video and log**

https://user-images.githubusercontent.com/86952082/181237009-c5f48ec3-05b0-40ad-abe9-c36a7b4edde7.mp4

[MaterialCanvas.log](https://github.com/o3de/o3de/files/9198099/MaterialCanvas.log)

**Found in Branch**
Development (616902d)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment]
verified that this no longer occurs on development linux build on users machine

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (adc2f3f) build.
