### ISSUE TITLE
Material canvas viewport does not update consistently or responsively after making changes to the graph

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10907]
**Describe the bug**
Example PBR Material Canvas nodes updates inconsistently after focusing/unfocusing the node's values instead of being applied automatically after changing the values.

**Prerequisites**
A project built in O3DE.

**Steps to reproduce**
1. In the Terminal, navigate to the build Default folder (for example /o3de-install/bin/Linux/profile/Default/).
2. Launch the MaterialCanvas with --project-path argument referencing built O3DE project (for example sudo ./MaterialCanvas --project-path=/root/O3DE/Projects/<Project name>).
3. In the Material Canvas, create a new graph (File > New).
4. Add an Example PBR node to the graph (for example right-click the graph, type "Example PBR" in the search bar, and select the matching node).
5. Modify any of the node's values (for example change the Base color X to 0), and observe the Viewport.

**Expected behavior**
Material changes are applied to the material overview in the Viewport instantly, or some loading is displayed if it takes a while.

**Actual behavior**
To see the material changes the Example PBR node values have to be selected/deselected using the left mouse button several times.

**Video**

https://user-images.githubusercontent.com/86952082/181243555-626529f4-094c-4a31-9b07-f4de302eeb32.mp4

**Found in Branch**
Development (616902d)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment]
https://github.com/o3de/o3de/wiki/Faster-Shader-Iteration

**Comment by LB-ArturZieba** [comment]
After modifying the .setreg files as linked above, the issue no longer occurs. The shader compilation process is fast enough that it does not seem to be stuck. Please close the issue if this information is sufficient.

**Comment by gadams3** [comment]
I have added health text and options that will allow the user to enable or disable minimal shader build settings. Enabling this setting from the tools->settings menu dialog and restarting material canvas and the asset processor will automatically manage the settings mentioned in the link above to allow better viewport responsiveness.

**Comment by LB-ArturZieba** [comment]
I have reverified this on the Stabilization/2210 (d327e2f) build, and enabling the *Enable Minimal Shader Builds* setting seems to decrease Viewport update time slightly compared to the base one, however the base time seems to be a bit faster as well. It appears that the updates take about 1 - 3 seconds.
