### ISSUE TITLE
Material Canvas node search highlight obscures the matching names

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10905]
**Describe the bug**
Searching nodes under the right-click context menu in Material Canvas is obscuring the matching names.

**Prerequisites**
A project built in O3DE.

**Steps to reproduce**
1. In the Terminal, navigate to the build Default folder (for example /o3de-install/bin/Linux/profile/Default/).
2. Launch the MaterialCanvas with --project-path argument referencing built O3DE project (for example sudo ./MaterialCanvas --project-path=/root/O3DE/Projects/<Project name>).
3. In the Material Canvas, create a new graph (File > New).
4. Right-click the graph, and start typing out a node's name in the search bar (for example "Example PBR").

**Expected behavior**
Matching names are highlighted.

**Actual behavior**
Matching names are obscured behind grey rectangles.

**Video**

https://user-images.githubusercontent.com/86952082/181240288-805214cc-7a07-4cba-96f4-402c35df2553.mp4

**Found in Branch**
Development (616902d)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as Fixed on the latest Development (a912a04) branch.
