### ISSUE TITLE
Feature Request - O3DE Release Install Binary Supports newer versions of Community Visual Studio.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#10911]
**Is your feature request related to a problem? Please describe.**
O3DE Release Install Binary Supports newer versions of the Community Visual Studio.
Installing O3DE Release V22.05.0 and also Nightly 7/27/22 will not see installed Visual Studio Community 2022, I needed to downgrade to Visual Studio Community 2019... however this was hard to troubleshoot as the error when building was just that o3de could not find Visual Studio installed.

**Describe the solution you'd like**
O3DE to report that the version of Visual Studio currently installed is not the correct version and what steps to take, or support 2019+ versions of Visual Studio Community.

**Comment by lmbr-pip** [comment]
Relates to https://github.com/o3de/o3de/issues/8478

**Comment by amzn-changml** [comment]
This issue was resolved with the added project manager support for VS2022
