### ISSUE TITLE
"Helpers" and "Icons" visualization should work only on the selected entities.

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#10922]
**Describe the bug**
Enabling "Helpers" and "Icons" visualization in the viewport when there are thousand of visible entities
can bring the performance down to 2 fps. There should be a way to only enable auxiliary geometry for the entity in focus.

**Assets required**
See: https://github.com/o3de/o3de/issues/10798

**Steps to reproduce**
See: https://github.com/o3de/o3de/issues/10798

**Expected behavior**
The "Helpers" and "Icons" should only display on the selected entity.

**Actual behavior**
All entities get the "Helpers" and "Icons" which brings the editor performance down for levels with thousands of entities

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
See: https://github.com/o3de/o3de/issues/10798

**Desktop/Device (please complete the following information):**

    Device: PC
    OS: Windows
    Version 10
    CPU AMD Ryzen Threadripper 3970X 32-Core Processor 3.70 GHz
    GPU NVidia RTX 3070
    Memory 64GB

**Additional context**
See: https://github.com/o3de/o3de/issues/10798

**Comment by monroegm** [comment]
@AMZN-daimini Can you see if this has already been implemented?

**Comment by AMZN-daimini** [comment]
Functionality is available for Helpers in the latest development
![image](https://user-images.githubusercontent.com/82231674/214655082-1e4b348d-a6bb-4882-92d7-dcf5f2f78c1c.png)
