### ISSUE TITLE
Bug Report: `ExeSelectPropertyHandler` causes suprious CRC warning because its not correctly registed with the DocumentPropertyEditor

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#10927]
**Describe the bug**
When starting Automated testing, or any project, users always see this warning:

```
`[Warning] (DPE) - No name found for CRC, falling back to CRC value: <value>`
```

This is because `ExeSelectPropertyHandler` tries to use a CRC value which is not in scope at the time. Handler appears not to have `RegisterPropertyEditor` call for control so looks like handler is not correctly setup to work with DPE.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Open automated test project
2. See error on start
3. Add breakpoint in `PropertyEditorSystem::LookupNameFromId` and confirm warning comes when `ExeSelectPropertyHandler` is being registered

**Expected behavior**
* All DPE property editors owned by O3DE register correctly. Customers are not presented with cryptic warning messages.

**Actual behavior**
* Warning message occurs, can only take action on warning using breakpoint as we print the hash value as u32 value.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Development based on  663ed5632447fa70040557c407ed15f29ae7f1ef

**Desktop/Device (please complete the following information):**
 - Device: [PC 

**Additional context**

**Comment by lmbr-pip** [comment]
Assigning to core as DPE is defined in o3de\o3de\Code\Framework\AzFramework\AzFramework\DocumentPropertyEditor

**Comment by alexmontAmazon** [comment]
Fixed by https://github.com/o3de/o3de/pull/11323/files
