### ISSUE TITLE
Opening UI Editor with Terrain components added to level crashes Editor

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#10931]
**Describe the bug**
The Editor crashes if the World Terrain and World Renderer components are added to the level prefab.

**Call Stack Trace:**
25) 00007FFDBC230057 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFDBBCEC888 (InProcessClient64) : (function-name not available)
23) 00007FFDBBCEC4D1 (InProcessClient64) : (function-name not available)
22) 00007FFDBEA753B0 (ntdll) : memset
21) 00007FFDBEA5C766 (ntdll) : _C_specific_handler
20) 00007FFDBEA7229F (ntdll) : _chkstk
19) 00007FFDBEA21454 (ntdll) : RtlRaiseException
18) 00007FFDBEA70DCE (ntdll) : KiUserExceptionDispatcher
17) C:\Users\GPC-613\.o3de\3rdParty\packages\RapidJSON-1.1.0-rev1-multiplatform\RapidJSON\include\rapidjson\document.h (1324) : rapidjson_ly::GenericValue<rapidjson_ly::UTF8<char>,rapidjson_ly::MemoryPoolAllocator<rapidjson_ly::CrtAllocator> >::FindMember
16) C:\Builds\Branch\Dev\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\PrefabDomUtils.cpp (213) : AzToolsFramework::Prefab::PrefabDomUtils::FindPrefabDomValue
15) C:\Builds\Branch\Dev\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\PrefabPublicHandler.cpp (546) : AzToolsFramework::Prefab::PrefabPublicHandler::RemoveLink
14) C:\Builds\Branch\Dev\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\PrefabPublicHandler.cpp (1265) : AzToolsFramework::Prefab::PrefabPublicHandler::DeleteFromInstance
13) C:\Builds\Branch\Dev\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\PrefabPublicHandler.cpp (1055) : AzToolsFramework::Prefab::PrefabPublicHandler::DeleteEntitiesAndAllDescendantsInInstance
12) C:\Builds\Branch\Dev\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Application\EditorEntityManager.cpp (65) : AzToolsFramework::EditorEntityManager::DeleteEntitiesAndAllDescendants
11) C:\Builds\Branch\Dev\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Application\ToolsApplication.cpp (886) : AzToolsFramework::ToolsApplication::DeleteEntitiesAndAllDescendants
10) C:\Builds\Branch\Dev\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1541) : AZ::Internal::EBusContainer<AzToolsFramework::ToolsApplicationRequests,AzToolsFramework::ToolsApplicationRequests,0,0>::Dispatcher<AZ::EBus<AzToolsFramework::Too
 9) C:\Builds\Branch\Dev\o3de\Code\Editor\Plugins\ComponentEntityEditorPlugin\SandboxIntegration.cpp (1232) : SandboxIntegrationManager::DeleteSelectedEntities
 8) C:\Builds\Branch\Dev\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1541) : AZ::Internal::EBusContainer<AzToolsFramework::EditorRequests,AzToolsFramework::EditorRequests,0,0>::Dispatcher<AZ::EBus<AzToolsFramework::EditorRequests,AzToolsF
 7) C:\Builds\Branch\Dev\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\UI\Outliner\EntityOutlinerWidget.cpp (741) : AzToolsFramework::EntityOutlinerWidget::DoDeleteSelectionAndDescendants
 6) 00007FFD5FEC09AA (Qt5Core) : QObject::qt_static_metacall
 5) 00007FFD4EA85DBF (Qt5Widgets) : QAction::activate
 4) 00007FFD4EA86D5B (Qt5Widgets) : QAction::event
 3) 00007FFD4EA949A1 (Qt5Widgets) : QApplicationPrivate::notify_helper
 2) 00007FFD4EA93A23 (Qt5Widgets) : QApplication::notify
 1) 00007FFD5FEA17CB (Qt5Core) : QCoreApplication::notifyInternal2

**Steps to reproduce**
1. Enable Terrain Gem.
2. Add Terrain World and World Renderer components to the level prefab.
3. Open UI Editor.

**Expected behavior**
The UI Editor opens without errors.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/181468832-f6581578-41cc-43cb-b3ea-a85a3a70d5ea.mp4

**Additional files**
[error.zip](https://github.com/o3de/o3de/files/9207647/error.zip)
[Editor.log](https://github.com/o3de/o3de/files/9207648/Editor.log)
[error.log](https://github.com/o3de/o3de/files/9208204/error.log)

**Found in Branch**
Development (5dd4d9f)

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU Nvidia GeForce RTX 2060 SUPER
Memory 16GB

**Comment by mbalfour-amzn** [comment]
This is related to issue 6272 - UiRenderer::CreateScene() is adding all feature processors, including terrain, to its viewport. It should be a little more particular in choosing which feature processors it needs.

**Comment by forkercat** [comment]
Could reproduce the issues and verified that disabling the terrain FP can fix the crash.

[UiRenderer.cpp#L100](https://github.com/aws-lumberyard-dev/o3de/blob/development/Gems/LyShine/Code/Source/UiRenderer.cpp#L100)
```cpp
atomScene->EnableAllFeatureProcessors();
if (atomScene->GetFeatureProcessor(terrainFeatureProcessor))
{
    atomScene->DisableFeatureProcessor(terrainFeatureProcessor);
}
```
Reference: #10546 

A better solution would be enable only the required feature processors as currently implemented in [PreviewRenderer.cpp#L40](https://github.com/aws-lumberyard-dev/o3de/blob/development/Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp#L40).

**Comment by monroegm** [comment]
Rerouting to SIG-Graphics-Audio as this is now on Atom to fix

**Comment by VickyAtAZ** [comment]
Fixed in PR: https://github.com/o3de/o3de/pull/11034

**Comment by LB-JakubSkoczylas** [comment]
Issue verified as fixed.
