### ISSUE TITLE
Large assets in Gems/AtomLyIntegration/CommonFeatures/Assets/Objects

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de#1093]
Gems/AtomLyIntegration/CommonFeatures/Assets/Ojects has a few very large files and what look to be a lot of work in progress files for 3rd Party applications. Some of these assets can take a very long time to process.

Noteable assets:
.wip/bake_channels.psd 1.2GB
.wip/high.fbx 126MB
.wip/marmoset_bake.obscene 291MB
.wip/Brass 538MB
.wip/stone 603 MB
Lucy_High.fbx 146MB
There are also several very large 16bpc textures in this directory.

**Comment by monroegm** [comment]
These look like assets pertaining to graphics

**Comment by superkitcath** [comment]
This was resolved last year. Closing.
