### ISSUE TITLE
Value indicator on child materials gets updated only on reloading Materials

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#10935]
**Describe the bug**
 Blue arrow indicator, indicating values that are different from the parent material on the child material only gets updated when reloading the child material.

**Steps to reproduce**
 1. Launch Material Editor.
2. Create and save a Material.
3. RMB on the Material and create a child Material.
4. Change any value on the child Material and save it.
5. Introduce the same change to the parent Material and save it.
6. Observe the blue arrow still present on the child Material.
7. Reopen the child Material.
8. Observe the blue arrow now gone.

**Expected behavior**
 Indicator disappears without reloading the Material.

**Actual behavior**
 Indicator disappears only after reloading the child Material.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/181498983-eb25a193-4f98-4b07-af29-a9d936e09c46.mp4

**Found in Branch**
 Development (5dd4d9f)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 3600
 - GPU Nvidia GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment]
What was displayed in the video is the correct behavior. At 32 seconds, after the parent material was saved, a message box appeared to ask the user if they wanted to apply changes to the child material. The user clicked no. Had the user click yes, the changes would have been applied to the child material. There are settings in the tools, settings menu to disable these prompts and automatically apply changes.
