### ISSUE TITLE
Axis Aligned Box Shape Component mode header name displays "Box Edit Mode"

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#10937]
**Describe the bug**
The Component mode header name of the **Axis Aligned Box Shape** is displayed as "Box Edit Mode" instead of "Axis Aligned Box Edit Mode".

**Steps to reproduce**
1. Create an entity.
2. Add **Axis Aligned Box Shape** component to the entity.
3. Enter the Component mode by clicking "Edit" on previously added component.

**Expected behavior**
The header name of **Axis Aligned Box Shape** Component mode is "Axis Aligned Box Edit Mode".

**Actual behavior**
The header name of **Axis Aligned Box Shape** Component mode is "Box Edit Mode".

**Screenshots**
![AxisAlignedBoxComponentModeName](https://user-images.githubusercontent.com/86951967/181504075-5100726c-bf97-4a15-af44-9bb684658a55.png)

**Found in Branch**
Development (5dd4d9f)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed in Development (511a88c), however it still occurs in the latest Stabilization/2210 (021d32a).
