### ISSUE TITLE
Script Canvas: Newly created graph needs to be saved twice for a successful save

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#10936]
**Describe the bug**
When a newly created graph in Script Canvas is saved, the "*" appears next to a name of the said graph, which results in a need of saving it for the second time. This issue might be related to https://github.com/o3de/o3de/issues/6448.

**Steps to reproduce**
1. Go to Tools > Script Canvas.
2. In the Script Canvas File > New Script.
3. Create a simple graph (e.g. Game Entity > Print).
4. Save it.
5. Close the Script Canvas.

**Expected behavior**
Prompt about saving a newly created script appears only when the script was not saved previously.

**Actual behavior**
Prompt about saving a newly created script appears despite the script being already saved.

**Video**

https://user-images.githubusercontent.com/100559077/181498896-b38891d8-b840-495e-94d4-6f17fb464e5b.mp4

**Found in Branch**
Development (5dd4d9f)

**Desktop:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Comment by lsemp3d** [comment]
I just tried to reproduce this, upon saving the new graph, the ^ at the end of the filename goes away and the * does not show up. Once I closed, I did not get a prompt to save again. I'll close it as cannot-reproduce, but if you run into it again please reopen. Thanks!

**Comment by LB-BartoszCwiek** [comment]
Issue verified as fixed on the Development (c1c018b) build.
