### ISSUE TITLE
Deleting of prefab after exiting focus crashes the editor

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/o3de#10942]
**Describe the bug**
If you come out of focus mode of a prefab and delete it, it crashes the editor

**Steps to reproduce**
1. Create new level or open existing level
2. create a prefab or instantiate any prefab
3. Enter focus mode of the prefab (double click it)
4. Modify any entity within the prefab (change transform, add mesh, etc.)
5. Come out of focus mode (click the icon to the left of the row)
6. Delete the prefab

**Expected behavior**
Prefab gets deleted without any issues

**Actual behavior**
Editor crashes

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
Device: PC
OS: Windows
Version 10
CPU Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz
GPU NVidia GeForce RTX Super 2700
Memory 64GB

**Additional context**
Did some debugging here. The issue appears to be that when entering focus mode, template dom is loaded into the instance object. So, LinkId will be removed. When exiting focus mode, linkId is not populated again on the instance. So, when deletion happens, it can't find a linkId and crashes

**Comment by srikappa-amzn** [comment]
The reason this happens is because if an entity gets modified while in focus, the dom used to deserialize it will also be cached, which doesn't have a linkId. So, when you exit out of focus and try to delete it, it tries to look for the LinkId and it can't find it and it crashes.

**Comment by forkercat** [comment]
Did some investigation. The public handler workflow looks good. The issue occurs in InstanceUpdateExecutor during template propagation. InstanceDomGenerator::GenerateInstanceDom() [#L191](https://github.com/aws-lumberyard-dev/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp#L191) returns a instance DOM with link ID removed. Before the call, I can confirm the link id is valid.

Previous PR that introduced the changes: #10407

Not sure if it might be related, but would be better to prioritize this fix over #10765 (preemptive cache update).

**Comment by srikappa-amzn** [comment]
So, the solution here imo would be to deserialize the current focused instance with the appropriate dom when entering and exiting focus. If we do that, then the cached doms will be in the right state.

1. Create new level or open existing level
2. create a prefab or instantiate any prefab
3. Enter focus mode of the prefab (double click it) - **call InstanceDomGenerator::GenerateInstanceDom() and load it into the focused instance. (also use selective deserialization here)**
4. Modify any entity within the prefab (change transform, add mesh, etc.)
5. Come out of focus mode (click the icon to the left of the row) - **call InstanceDomGenerator::GenerateInstanceDom() and load it into the focused instance. (also use selective deserialization here)**
6. Delete the prefab

**Comment by forkercat** [comment]
Had a discussion with srikappa to get some clarifications on the intent of InstanceDomGenerator::GenerateInstanceDom(). One important note is when we are focused on an instance, we expect the instance DOM to be without link id. The link id should be set up (restored) when stepping out the focus mode.

Will try to prototype the ideas mentioned above to see if it works.
