### ISSUE TITLE
Create separator widget (No dependency)

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10958]
[Migrated from JIRA LYN-14045]

For the new joint inspector, we will need a generalized separator widget shown in the image below.

The widget is probably pretty similar to the AzQtComponents::Card, which is also shown in the image.

The difference is that it doesnt have any margins, nor changes its background color for the owning widget.

The new widget shall also be part of AzQtComponents.

![image-2022-07-21-13-34-47-654](https://user-images.githubusercontent.com/82228511/181767326-0f9d415d-0c0e-470d-a972-6ac902d00f7c.png)

**Acceptance Criteria:**

 * New widget is part of AzQtComponents
 * New widget can be collapsed and the parent layout re-sizes appropriately
 * At the right side there is a button (visualized by 3 dots) that shows a context menu that can be customized by the user of the widget

**Additional Info**

![CardAccordion](https://user-images.githubusercontent.com/82228511/181767401-18c95612-aac0-4060-924e-e336670beff6.gif)

Could this potentially just be an AZQtComponents::Card with a different style? We have similar setups with Tabs and other widgets.

The established pattern for restyling widgets without changes in functionality is to provide a static function that sets the style. For example, in `\\o3de\Code\Framework\AzQtComponents\AzQtComponents\Components\Widgets\CheckBox.h`

```
//! Applies the "ToggleSwitch" style class to a QCheckBox.
static void applyToggleSwitchStyle(QCheckBox* checkBox);
//! Applies the "Expander" style class to a QCheckBox.
static void applyExpanderStyle(QCheckBox* checkBox); 
```

So unless there are specific reasons to create a new class, that would be my recommendation.

(Note that the Card widget can contain any widget, not just the RPE, although that is its main usage in the Editor)

**Comment by hultonha** [comment]
@amzn-leenguy @rainbj @bhanuja-s (also tagging @AMZN-daimini and @cgalvan for visibility) We wanted to check if there's an existing icon for the hotdog menu in this ticket (see below)

<img width="32" alt="image" src="https://user-images.githubusercontent.com/82228511/182830627-b1e791ca-3ab2-44fe-89b0-79bfc3574725.png">

We can't see one that's used right now (there just seems to be the hamburger menu). If you could point us at it if it exists or please create one we can use that would be great. Thank you!

**Comment by MiKom** [comment]
wouldn't that be kebab menu: https://ux.stackexchange.com/questions/115468/what-the-difference-between-the-2-menu-icons-3-dots-kebab-and-3-lines-hambur :)

**Comment by amzn-leenguy** [comment]
> wouldn't that be kebab menu: https://ux.stackexchange.com/questions/115468/what-the-difference-between-the-2-menu-icons-3-dots-kebab-and-3-lines-hambur 😊

There's no official name for it, but I just call it the overflow menu icon 😂

I will add one in my task to make one this week.

**Comment by bhanuja-s** [comment]
> @amzn-leenguy @rainbj @bhanuja-s (also tagging @AMZN-daimini and @cgalvan for visibility) We wanted to check if there's an existing icon for the hotdog menu in this ticket (see below)
> 
> <img alt="image" width="32" src="https://user-images.githubusercontent.com/82228511/182830627-b1e791ca-3ab2-44fe-89b0-79bfc3574725.png">
> 
> We can't see one that's used right now (there just seems to be the hamburger menu). If you could point us at it if it exists or please create one we can use that would be great. Thank you!

Hey @hultonha, this would be the drag-dot icon that is currently persistent in the engine. I've tried implementing it in the card/accordion to indicate that it is draggable within the card and its panel. I can work with the developer to ensure that it's interaction is similar to its other instances within the engine.

![Drag-dot](https://user-images.githubusercontent.com/84036086/182874981-1cf1d592-862b-4cc4-ae8b-743394ec8b24.svg)

@amzn-leenguy there is no need to create one, as we currently have it in the Figma library. It is under System Icons.

@MiKom I believe that's a paradigm that exists in mobile navigation menus, but we use it in O3DE to indicate dockability or draggability.

**Comment by rainbj** [comment]
@hultonh, @bhanuja-s, @amzn-leenguy, @yuyihsu - we should talk about this before implementing the trip dots elsewhere. Currently, this pattern is being used a separator drag bar symbol. I want to make sure we are not using the same symbol in two different place meaning two different things.

<img width="268" alt="2022-08-04_9-51-34" src="https://user-images.githubusercontent.com/82551958/182878323-d2358b9a-f35d-4bfb-b482-91625ca13ea8.png">

**Comment by hultonha** [comment]
Thanks very much for the updates @bhanuja-s, @amzn-leenguy and @rainbj 👍 I understand the use-case for this now (to drag the card/s) and that we have an existing icon. Let me know if that unblocks you @MiKom. Cheers!

**Comment by MiKom** [comment]
@hultonha 
I think so, yes. The requirement here is that this icon is supposed to represent a menu so it makes sense to not reuse the triple-dot that denotes draggable elements.

If I understand correctly, I should go with the regular card menu icon, the tree lines.

@bhanuja-s I'm not touching the draggability code in any way for this widget, it's essentially a differently-styled card so the effor to include the three dots to denote draggability can be done separately.

**Comment by bhanuja-s** [comment]
> If I understand correctly, I should go with the regular card menu icon, the tree lines.

I don't think there is a need to have the three line menu icon for the accordion card (in this example, "Cloth Colliders"). We would retain the menu icon in the sub-cards ("Capsule").

> I'm not touching the draggability code in any way for this widget, it's essentially a differently-styled card so the effor to include the three dots to denote draggability can be done separately.

That makes sense, but this is a very important UX element for this effort. I would envision through your first-pass, the accordion card would look like this:

<img width="654" alt="Screenshot 2022-08-05 at 12 37 37" src="https://user-images.githubusercontent.com/84036086/183131167-094411dd-34e4-43b6-9847-8cdc392e3b67.png">

**Comment by MiKom** [comment]
@bhanuja-s 
Hey,
that's how the card looks like in the EmotionFX now:
![image](https://user-images.githubusercontent.com/104767/183405496-90e5c837-c1ab-47db-89a7-a7fcf9f0bdfa.png)
Please note, that I added the purple underline just to show how it looks. It won't be there in the upcoming EmotionFX patch.

**Comment by bhanuja-s** [comment]
> @bhanuja-s Hey, that's how the card looks like in the EmotionFX now: ![image](https://user-images.githubusercontent.com/104767/183405496-90e5c837-c1ab-47db-89a7-a7fcf9f0bdfa.png) Please note, that I added the purple underline just to show how it looks. It won't be there in the upcoming EmotionFX patch.

That looks great! Thank you for working on this ☺️

**Comment by FuzzyCarterAWS** [comment]
@hultonha 

Added references to testing this in the Animation Editor Workflow Automation Updates.

https://github.com/o3de/sig-simulation/pull/22

**Comment by hultonha** [comment]
Awesome thanks @FuzzyCarterAWS 🙂
