### ISSUE TITLE
Use new separator widget for motion set window (Dep: Separator widget)

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10960]
[Migrated from JIRA LYN-14136]

Use the new separator widget in the motion sets plugin. 

Currently/before change:

![image-2022-07-26-14-31-16-007](https://user-images.githubusercontent.com/82228511/181768141-9e8c11c8-056f-4580-8100-86ceac8318f4.png)

After change:

The separators should say "Available Motion Sets" and "Selected Motion Set" and not "Cloth Colliders", I just copy pasted that from the UX designs.

![image-2022-07-26-14-32-47-961](https://user-images.githubusercontent.com/82228511/181768163-9cd8e2cf-f9b1-4b57-8c5c-9a7b2aa7b7cb.png)

**Comment by FuzzyCarterAWS** [comment]
@hultonha 

Added references to testing this in the Animation Editor Workflow Automation Updates.

https://github.com/o3de/sig-simulation/pull/22

**Comment by hultonha** [comment]
Excellent thanks @FuzzyCarterAWS!

**Comment by hultonha** [comment]
@MiKom I reviewed this and one thing that seems wrong is the names of the panels should be different (see below)

![image](https://user-images.githubusercontent.com/82228511/201085651-26927f88-bfe6-4e7d-b96e-d72adbaa74e4.png)

Is this something you'd be able to quickly fix-up please?

**Comment by FuzzyCarterAWS** [comment]
Title name updates found in #13272
