### ISSUE TITLE
Move anim graph parameter properties to inspector

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10965]
[Migrated from JIRA LYN-11489]

**Description**
The properties of a parameter that are currently shown inside the "Edit Parameter" window shall be moved into the Inspector window.

**Old workflow:**
Anim graph parameters are shown and edited in the "Parameters" window on the bottom right. They are listed by their name and have a widget to control the current value.

![image](https://user-images.githubusercontent.com/43751992/183882460-06bbfe5a-82a4-43cd-b4ad-4ed9361e90dc.png)

When selecting a parameter and then pressing the gears icon, the properties of the parameter appear in a pop-up window named "Edit Parameter".

![image](https://user-images.githubusercontent.com/43751992/183882527-9475eb51-a8ee-4bd1-bbe2-d82b2546a486.png)

The content from the window shown in the image above shall be moved to the "Inspector" window and should be shown when selecting a parameter. The gears icon shall be removed from the "Parameters" window. Also, the context menu option named "Edit" that can be opened on a parameter shall be removed.

**New way / the change:**
The whole content of the "Edit Parameter" window shall be moved into the "Inspector" window, including the "Apply" and "Cancel" buttons. The source code for the "Edit Parameter" window can be found in the ParameterCreateEditDialog.h/.cpp files. This QDialog needs to be changed into a QWidget so that it can be sent to the Inspector window.

In case a new single parameter gets selected, the new widget needs to be sent to the "Inspector" window by calling
`EMStudio::InspectorRequestBus::Broadcast(&EMStudio::InspectorRequestBus::Events::Update,...)`
Please see other instances like for example the `AttributesWindow `that also communicates with the Inspector as reference.

The result should look something like this:
![image](https://user-images.githubusercontent.com/43751992/183884678-ab7ecbf7-9397-48e2-8955-070b4a07fa19.png)

**Acceptance Criteria:**
* The gears icon is not present in the "Parameters" window anymore.
* The context menu that can be opened on a selected parameter in the "Parameters" window is not present anymore.
* The content of the old "Edit Parameter" window is shown in the "Inspector" window when clicking/selecting a parameter. When clicking on e.g. an anim graph node in the "Anim Graph" window, the properties of the node are shown.
* When multiple parameters are shown, the Inspector window will go back into a no selection state as we currently can't display the properties of multiple parameters.

**Comment by FuzzyCarterAWS** [comment]
@hultonha @MiKom 

This looks great.

Updated the workflow docs in o3de/sig-simulation#22
