### ISSUE TITLE
Character selection in Skeleton Outliner (No dependency)

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10962]
[Migrated from JIRA LYN-12679]

Currently, we have two duplicated plugins that show the skeleton hierarchy, the EMotionFX::SkeletonOutlinerPlugin and the legacy EMStudio::NodeWindowPlugin.

This task is about the new EMotionFX::SkeletonOutlinerPlugin. The SkeletonOutlinerPlugin contains a tree view that shows all the nodes/joints/bones inside a skeleton (of the currenty selected character). Root joints of the skeleton are root joints in the tree view currently - and this has to be changed as currently there is no way to select the actual character and show the properties of the character inside the inspector window.

We want to introduce a new root node in the tree view called "Character" and all root joints of the skeleton shall be children of that new Character node in the tree view. This has to be implemented in the EMotionFX::SkeletonModel which is the model that the tree view uses inside the SkeletonOutlinerPlugin. The EMotionFX::SkeletonModel::NodeInfo class has to be extended to also support this type of node with a "m_isCharacter" or something which is true when selecting the Actor or ActorInstance object.

In the image below you can see the skeleton outliner showing a root joint. To bring the editor in this state, use the File -> Open Actor menu action to load a character, then use the combo box on the top right to switch to the "Physics" layout. You can see the skeletal hierarchy in the tree view of the outliner, while there is no root item to select the actual character itself yet.

![image-2022-07-21-13-28-07-188](https://user-images.githubusercontent.com/82228511/181769697-c5b36c56-e7c1-4b52-8c0d-de935ce2fc94.png)

**Acceptance criteria:**

- A new "Character" root item is shown in the skeleton outliner.
- All root joints of the skeleton are parented to the new Character item in the tree view.
- When selecting a joint, the Ragdoll/HitDetection etc. windows on the right show the properties of the selected joint as before this change.
- When selecting the new Character element, the Ragdoll/HitDetection etc. windows shall act as if no joint is selected and should show this:
![image-2022-07-21-13-27-13-835](https://user-images.githubusercontent.com/82228511/181769781-13a34fc1-89b2-4730-ba26-7687b05abe62.png)

**Comment by FuzzyCarterAWS** [comment]
@hultonha 

Added references to testing this in the Animation Editor Workflow Automation Updates.

https://github.com/o3de/sig-simulation/pull/22
