### ISSUE TITLE
Asset Processor crash in Debug

### ISSUE THREAD

**Issue by AMZN-stankowi** [o3de/o3de#10978]
**Describe the bug**
A clear and concise description of what the bug is. Try to isolate the issue to help the community to reproduce it easily and increase chances for a fast fix.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Sync to 6b5073dabb756fa482e5ff2932b222c9d5551a48
2. Build Asset Processor in Debug
3. Launch Asset Processor
4. Wait for Asset Processor to process some content (I'm not sure on exact crash timing)
5. Notice you get a lot of debug popups about invalid Qt indices
6. Notice the Asset Processor shuts itself down

**Expected behavior**
AP doesn't crash

**Actual behavior**
AP crashes

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/4838196/181846038-9a9df879-d05c-4483-9a0a-fb1916bd2b1c.png)

![image](https://user-images.githubusercontent.com/4838196/181846358-b97e4e44-96e5-4573-8d0c-ea2536503138.png)

**Found in Branch**
development with commit 6b5073dabb756fa482e5ff2932b222c9d5551a48

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU intel
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by lmbr-pip** [comment]
Debug crash, treating as crticial. Automated processes accidentally took off needs-triage label so for now re-applied so can be accepted by SIG

**Comment by lmbr-pip** [comment]
Resolving as fixed
