### ISSUE TITLE
Floats in asset properties loses values on editor restart when system number format is french

### ISSUE THREAD

**Issue by jonatjano** [o3de/o3de#10987]
**Describe the bug**
When restarting the editor assets and UI canvas with float values get these values reset to 0,
This is due to the number format of my system : the french number format uses a comma as the decimal separator (123,45)
When changing my system number format to English the issue is solved (123.45)

The assets seems to be saved correctly since when I changed my system language, it loaded the right value directly without having to recreate them

**Assets required**
When restarting the editor with french number format, the event value multiplier will be set to 0
![image](https://user-images.githubusercontent.com/17279801/181879296-76ae68b0-7f7a-4632-bcb1-31716e8eae55.png)

**Steps to reproduce**
1. set your system number format to "french (France)"
2. open o3de
3. create any asset/UI canvas with float values in their properties
4. restart the editor

**Expected behavior**
The assets/UI canvas should keep it's properties value

**Actual behavior**
The float values on the asset/UI canvas is set to 0

**Found in Branch**
release 22.05

**Desktop/Device:**
 - Device: PC 
 - OS: Ubuntu
 - Version 22.04 LTS Jammy Jellyfish
 - CPU 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
 - GPU NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile]
 - Memory 8GB

**Comment by monroegm** [comment]
This is a good question for the TSC about which regional formats we support

**Comment by alexmontAmazon** [comment]
@hultonha Didn't your team deal with decimal point localization like this recently? If not, do you remember who did?

**Comment by hultonha** [comment]
That was @jjjoness, I think they might have some more details
