### ISSUE TITLE
Quaternion::GetEulerRadians() computes incorrect values for some cases

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de#11000]
**Describe the bug**
For certain Quaternions, `GetEulerRadians()` returns incorrect values. This could have significant consequences overall. In my case, it results in incorrect Transforms when importing models from formats such as URDF.

**Steps to reproduce**
1. Set Quaternion to `(0.5, 0.5, 0.5, 0.5)`
2. Run GetEulerRadians() for this quaternion and print XYZ values.

**Expected behavior**
Value for `(0.5, 0.5, 0.5, 0.5)` should be `(1.57, 1.57, 0)`.

**Actual behavior**
Value for `(0.5, 0.5, 0.5, 0.5)` is `(0, 1.57, 0)`.

**Found in Branch**
development, tested with `#6ec1466f63b476cfe`

**Desktop/Device (please complete the following information):**
 - Irrelevant, this is platform independent, pure computational, unit behavior

**Additional context**
A good resource to look at for understanding: https://quaternions.online/

~~Likely fix: first line of the function, roll formula seems incorrect (minus sign instead of plus for `m_w * m_w + m_z * m_y`).
I might submit a patch, but it could be a connected issue (with the reverse transformation). Unit tests should be extended to include at least `(0.5, 0.5, 0.5, 0.5)` case~~

**Comment by adamdbrw** [comment]
Patch that works for me (haven't tested it in the broad context):

```
diff --git a/Code/Framework/AzCore/AzCore/Math/Quaternion.inl b/Code/Framework/AzCore/AzCore/Math/Quaternion.inl
index bd51a90fca..2a9b6da20b 100644
--- a/Code/Framework/AzCore/AzCore/Math/Quaternion.inl
+++ b/Code/Framework/AzCore/AzCore/Math/Quaternion.inl
@@ -537,7 +537,7 @@ namespace AZ
     AZ_MATH_INLINE Vector3 Quaternion::GetEulerRadians() const
     {
         // roll (x-axis rotation)
-        const float roll = Atan2(2.0f * (m_w * m_x - m_z * m_y), 1.0f - 2.0f * (m_x * m_x + m_y * m_y));
+        const float roll = Atan2(2.0f * (m_w * m_x + m_z * m_y), 1.0f - 2.0f * (m_x * m_x + m_y * m_y));
 
         // pitch (y-axis rotation)
         const float sinp = 2.0f * (m_w * m_y + m_z * m_x);
```

**Comment by hultonha** [comment]
I believe @pollend has been working on a PR related to this and might be worth reaching out to - see https://github.com/o3de/o3de/pull/10852 for more details

**Comment by pollend** [comment]
> I believe @pollend has been working on a PR related to this and might be worth reaching out to - see #10852 for more details

sound like something I can look into after https://github.com/o3de/o3de/pull/10852. Those test cases I have can be used to test the reverse case of going from quaternion back to euler.

**Comment by greerdv** [comment]
Sorry, only just saw this issue.

The signs are not incorrect. Our rotations are applied in the order Z, then Y, then X and a lot references do X, then Y, then Z, so will have different signs. The problem is that if the y rotation is exactly 90 degrees, then the arguments that go into the two atan2 expressions both go to zero and all information in those terms about the X and Z rotations is lost. We do have unit tests, but apparently none that have exactly 90 degree rotation around Y.

**Comment by greerdv** [comment]
The CreateFromEuler functions should not be affected by this problem, because there is an unambiguous conversion from Euler angles to quaternion.

**Comment by amzn-pratikpa** [comment]
Please reference https://github.com/o3de/o3de/pull/10852

**Comment by pollend** [comment]
> Please reference #10852

my change does not touch `GetEulerRadians`.

**Comment by greerdv** [comment]
Yeah I checked 10852 and it is has nothing to do with this issue.

**Comment by pollend** [comment]
> Yeah I checked 10852 and it is has nothing to do with this issue.

if its easier to just fix the method then that can happen first. I plan to introduce these methods afterwards. 

```
getEularRadiansXYZ()
getEularRadiansZYX()
getEularRadiansYXZ()

getEularDegreesXYZ()
getEularDegreesZYX()
getEularDegreesYXZ()
```

**Comment by greerdv** [comment]
Yeah, it's a fairly straightforward fix, hopefully I should be able to squeeze it in tomorrow

**Comment by hultonha** [comment]
Awesome thanks for following-up both @greerdv and @pollend (sorry knew it wasn't exactly the same problem but did seem in a similar ballpark at least 😅). Thanks!
