### ISSUE TITLE
Crash with null prefabEditorEntityOwnershipInterface in LocalViewBookmarkLoader

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#11050]
**Describe the bug**
In the editor I went to 

**Assets required**
none

**Steps to reproduce**
1. Open a level in the editor
2. Go to Tools->Viewport->Viewport Camera Selector

**Expected behavior**
The Viewport Camera Selector opens

**Actual behavior**
Crash with a null prefabEditorEntityOwnershipInterface with the following callstack
>	EditorLib.dll!AzToolsFramework::LocalViewBookmarkLoader::FindOrCreateLocalViewBookmarkComponent() Line 510	C++
 	EditorLib.dll!AzToolsFramework::LocalViewBookmarkLoader::LoadLastKnownLocation() Line 496	C++
 	EditorLib.dll!EditorViewportWidget::SetDefaultCamera() Line 1931	C++
 	[Inline Frame] Camera.Editor.dll!AZStd::Internal::INVOKE(void(Camera::EditorCameraRequests::*)(const AZ::EntityId &, bool) &) Line 177	C++
 	[Inline Frame] Camera.Editor.dll!AZStd::invoke(void(Camera::EditorCameraRequests::*)(const AZ::EntityId &, bool) &) Line 54	C++
 	[Inline Frame] Camera.Editor.dll!AZ::EBusEventProcessingPolicy::Call(void(Camera::EditorCameraRequests::*)(const AZ::EntityId &, bool) &) Line 437	C++
 	Camera.Editor.dll!AZ::Internal::EBusContainer<Camera::EditorCameraRequests,Camera::EditorCameraRequests,0,1>::Dispatcher<AZ::EBus<Camera::EditorCameraRequests,Camera::EditorCameraRequests>>::Broadcast<void (__cdecl Camera::EditorCameraRequests::*)(AZ::EntityId const &,bool),AZ::EntityId &,bool &>(void(Camera::EditorCameraRequests::*)(const AZ::EntityId &, bool) && func, AZ::EntityId & <args_0>, bool & <args_1>) Line 1360	C++
 	Camera.Editor.dll!Camera::Internal::ViewportCameraSelectorWindow::currentChanged(const QModelIndex & current, const QModelIndex & previous) Line 216	C++
 	[External Code]	
 	[Inline Frame] Camera.Editor.dll!Camera::Internal::ViewportCameraSelectorWindow::OnViewportViewEntityChanged(const AZ::EntityId &) Line 228	C++
 	Camera.Editor.dll!Camera::Internal::ViewportCameraSelectorWindow::ViewportCameraSelectorWindow(QWidget * parent) Line 196	C++
 	[Inline Frame] Camera.Editor.dll!Camera::Internal::ViewportSelectorHolder::{ctor}(QWidget *) Line 327	C++
 	Camera.Editor.dll!Camera::Internal::CreateNewSelectionWindow(QWidget * parent) Line 333	C++
 	[Inline Frame] EditorCore.dll!AZStd::function_intermediate<QWidget *,QWidget *>::operator()(QWidget * &&) Line 604	C++
 	[Inline Frame] EditorCore.dll!AZStd::function<QWidget * __cdecl(QWidget *)>::operator()(QWidget * <args_0>) Line 684	C++
 	EditorCore.dll!QtViewPane::CreateWidget() Line 192	C++
 	EditorCore.dll!QtViewPaneManager::OpenPane(const QString & name, QFlags<enum QtViewPane::OpenMode> modes) Line 720	C++
 	EditorLib.dll!LevelEditorMenuHandler::checkOrOpenView() Line 1182	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 3955	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 54	C++
 	Editor.exe!main(int argc, char * * argv) Line 31	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
 	[External Code]	

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development branch commit 968527d43a930a448c5f1c7fb2844700a06c00b6

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel I9-10900X
 - GPU: NVidia GeForce RTX 2080 SUPER
 - Memory: 64GB

**Additional context**

**Comment by hultonha** [comment]
@amzn-tommy could you please confirm if this still happens with this recent fix - https://github.com/o3de/o3de/pull/10969. Thanks!

**Comment by amzn-tommy** [comment]
Resolving as a duplicate of a prior issue that was already fixed by https://github.com/o3de/o3de/pull/10969/files

**Comment by hultonha** [comment]
> Resolving as a duplicate of a prior issue that was already fixed by https://github.com/o3de/o3de/pull/10969/files

Cool thanks!
