### ISSUE TITLE
The editor interface does not provide a method to modify far plane distance of Editor camera

### ISSUE THREAD

**Issue by xipuhu** [o3de/o3de#11066]
**Is your feature request related to a problem? Please describe.**
The default far-plane distance of Editor camera is too small to apply to large-scale scenarios. I can't adjust the far plane distance attribute in EditorViewportWidget.

**Describe the solution you'd like**
I'd like to add distance setting of Editor camera to EditorViewportWidget

**Describe alternatives you've considered**
I can just use camera component which can set the far-plane distance, but the maximum far-plane distance of camera component is still not large enough, it's only 65535:
![image](https://user-images.githubusercontent.com/25362325/182792532-285cbe3f-c7be-41b9-85cb-8c37eee3a378.png)

**Additional context**
The Editor camera in o3de editor interface:
![image](https://user-images.githubusercontent.com/25362325/182792602-79603326-f3bf-40ae-bb1e-6a44ab11f355.png)

**Comment by lmbr-pip** [comment]
Does this relate to https://github.com/o3de/o3de/pull/11052 ?

**Comment by hultonha** [comment]
Correct, this is fixed by https://github.com/o3de/o3de/pull/11052

Please see below:

![image](https://user-images.githubusercontent.com/82228511/217033295-4212a964-290c-4426-b824-bf152688a445.png)
