### ISSUE TITLE
Launching the Development O3DE Installer executable displays a Windows Defender warning

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#11067]
**Describe the bug**
After turning on the Development O3DE installer downloaded
from the link (https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe),
the following error is displayed in Windows Defender:
Windows protected your PC
Microsoft Defender SmartScreen prevented an unrecognized app from
starting. Running this app might put your PC at risk.
App: o3de_installer.exe
Publisher: Unknown publisher

**Steps to reproduce**

1. Go to https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe site.
2. Press keep in drop down menu of downloading file.
3. Press show more > Keep anyway.
4. Open downloaded installer file.

**Expected behavior**
An installer window is opened.

**Actual behavior**
Windows Defender and User Account Control warning windows are
opened (Black screen in attached video) with a different name of an app - App: o3de_0.0.0.0_installer.exe.

**Video**

https://user-images.githubusercontent.com/86953282/182810827-bd33e5b1-a695-4bb2-b640-da6b4079a2ef.mp4

**Found in Branch**
https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe

**Desktop/Device:**
• Device: PC
• OS: Windows
• Version: 10 Pro
• CPU: Intel Core i7 11700F
• GPU: Nvidia RTX 3070 LHR
• Memory: 32GB

**Comment by amzn-changml** [comment]
This was due to a renewal of the Windows code signing cert last week. There was an issue with having two certs (the old one and the new one) that caused issues in signing the binary. Removing the old cert once it expired and re-running the installer build/depot resolved the issue.

@LB-KacperSzczepanski can you confirm this with the latest development installer on your end?

**Comment by LB-KacperSzczepanski** [comment]
@amzn-changml The fix was verified on the latest development installer.

**Comment by LB-KacperSzczepanski** [comment]
The fix was verified on the latest development installer.
