### ISSUE TITLE
[Pre Release] Ensure PRs are created for branch merge for 4 Repos 

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#11098]
Ensure the Release SIG creates PRs for the final merge from the stabilization branch to main for each of the following repos:
- o3de
- o3de-atom-sampleviewer
- o3de-multiplayersample
- o3de-netsoaktest

Replace the [PR] placeholders in the below successor task with the correct information for this release.
- Successor Task: #11096 

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by tonybalandiuk** [comment]
@AMZN-alexpete  please post your PRs here in preparation for tomorrow. Thanks

**Comment by AMZN-alexpete** [comment]
PRs
* o3de https://github.com/o3de/o3de/pull/12537
* o3de-atomsampleviewer https://github.com/o3de/o3de-atom-sampleviewer/pull/534
* o3de-multiplayersample https://github.com/o3de/o3de-multiplayersample/pull/202
* o3de-netsoaktest https://github.com/o3de/o3de-netsoaktest/pull/29

**Comment by tonybalandiuk** [comment]
thanks!
