### ISSUE TITLE
[Release Day] Execute Launch for O3DE 22.10.0

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#11096]
- Predecessor Task: [Planning] Prepare for Launch (#11089)

On Release Day, confirm each of the following launch activities is completed as expected:

- Release Team
   - [x] [@tonybalandiuk ] Confirm all members of the release team are in attendance and available for the launch 10:30am Pacific:
      - [x] [@tonybalandiuk ] - Release Manager
      - [x] [@AMZN-alexpete] - Responsible for Merge
      - [x] [@brianherrera ] - Responsible for applying the 22.10.0 version number (Release Tag), and publishing the version number update to o3debinaries.org
      - [x] [@chanmosq ] - Responsible for (1) merging the docs (2) updating/verifying both Windows and Linux text to show 22.10.0 on (https://www.o3de.org/download/)
      - [x] [@Ulrick28] - Responsible for main branch verification
      - [x] [@AMZN-Dk] - Responsible for installer and o3debinaries.org verification

- Launch Prerequisites
   - [x] [@tonybalandiuk ] Confirm the following pre-requisites are complete:
      - [x] #11429
      - [x] #11094
- Merge of Stabilization to Main
   - [x] Execute the following steps:
      - [x] [@tonybalandiuk ] Confirm the following pre-requisites are complete:
         - [x] #11098
         - [x] #11419
      - [x] [@AMZN-alexpete ] Click the Merge button on the PR (via. GitHub) for all of the following 4 repos:
         - [x] o3de: https://github.com/o3de/o3de/pull/12537
         - [x] o3de-atom-sampleviewer: https://github.com/o3de/o3de-atom-sampleviewer/pull/534
         - [x] o3de-multiplayersample: https://github.com/o3de/o3de-multiplayersample/pull/202
         - [x] o3de-netsoaktest: https://github.com/o3de/o3de-netsoaktest/pull/29
- Installers
   - [x] [@tonybalandiuk ] Confirm the following pre-requisites are complete:
      - [x] #11424
- Release Tag
   - [x] [@brianherrera ] Create the release tag [22.10.0], and apply it to the following repos:
        - [x] o3de 
        - [x] o3de-atom-sampleviewer 
        - [x] o3de-multiplayersample 
        - [x] o3de-netsoaktest 
    - [x] [@brianherrera] Begin work to add LFS binary objects to the artifacts under the new release tag, per the steps documented in this issue:
        - #12455
- Docs Updates
   - [x] [@tonybalandiuk ] Confirm the following pre-requisites are complete:
      - [x] #11420
      - [x] #11095
      - [x]  #11428 
      - [x] #11421
   - [x] [@chanmosq] Merge PR for applying the generated API reference to the docs site https://github.com/o3de/o3de.org/pull/2009
   - [x] [@chanmosq] Merge PR for bumping the version number in the Linux install instructions https://github.com/o3de/o3de.org/pull/2007
   - [x] [@chanmosq] Merge PR for docs from stabilization to main (includes release notes and update to o3de.org download screen version number) https://github.com/o3de/o3de.org/pull/2028
   - [x] @chanmosq Re-target open PRs against stabilization against main
- Website Updates for binaries
   - o3debinaries.org
      - [x] [@tonybalandiuk ] Confirm the following pre-requisite is complete: stage website update
      - [x] [@brianherrera] Publish version number update to o3debinaries.org https://github.com/o3de/o3debinaries.org/pull/1 

- Verification
   - [x] [@Ulrick28] Confirm the [main branch](https://github.com/o3de/o3de/tree/main) has the latest code on Github 
   - [x] [@brianherrera ] Confirm the release tag is applied to main branch
   - [x] [@Ulrick28] Confirm the mainline build has begun (it should auto-start)
   - [x] [@AMZN-Dk] Confirm the version number is updated on o3debinaries.org
   - [x] [@AMZN-Dk] Confirm the Windows installer is the correct version by downloading it from o3debinaries.org
   - [x] [@AMZN-Dk] Confirm the Linux debian package is the correct version by downloading it from o3debinaries.org
   - [x] [@AMZN-Dk] Confirm the installed Windows editor shows the correct version on the splash screen
   - [x] [@AMZN-Dk] Confirm the installed Linux editor shows the correct version on the splash screen
   - [x] [@Ulrick28] Confirm the version number is updated on o3de.org (Required for Major Releases only)
   - [x] [@Ulrick28] Confirm the release notes are updated

**Comment by sptramer** [comment]
Proposed step for end of docs to add to template:

[ ] Re-target open PRs against `stabilization` against `main`

**Comment by tonybalandiuk** [comment]
future TODO - make sure we add a step to update the Linux has (SHA256) and upload it to O3DEbinaries.org
