### ISSUE TITLE
[Pre Release] Ensure installers are created

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#11102]

**Comment by brianherrera** [comment]
Installers are created for both Windows and Linux and uploaded to the staging bucket: s3://o3de-prism-prod-us-west-2/stabilization-2210/Latest/

**Comment by brianherrera** [comment]
Installers can be downloaded here: 

- Windows: https://o3debinaries.org/stabilization-2210/Latest/Windows/o3de_installer.exe
- Linux: https://o3debinaries.org/stabilization-2210/Latest/Linux/O3DE_latest.deb
