### ISSUE TITLE
Clicking on Editor UI while Viewport Camera is being moved causes movement to be applied constantly

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#11112]
**Describe the bug**
If the Viewport Camera is being moved by holding down a key, and a mouse input is provided on Editor's UI, then the input from that key will be constantly applied, until it is pressed again.

**Steps to reproduce**
1. In the Editor Viewport hold any key that moves the Camera down (for example "A").
2. Without letting go of the key in step 1, click inside the Editor's UI with any of the mouse buttons (for example Right Mouse Button).
3. Let go of the held key.

**Expected behavior**
Viewport camera movement stops.

**Actual behavior**
Viewport camera constantly moves.

**Video**

https://user-images.githubusercontent.com/86952082/183070094-4e7cd120-136c-4654-87e3-f583357e5f64.mp4

**Found in Branch**
Development (59df478)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by hultonha** [comment]
Fixed by https://github.com/o3de/o3de/pull/13433

Could you please retest on latest develoment @LB-ArturZieba. Thanks!

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (7ce6550) build. Clicking inside the UI during movement stops it.
