### ISSUE TITLE
Linux: Asset Editor: mouse_button_other1 and mouse_button_other2 from the InputBindings are not working

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#11111]
**Describe the bug**
When the User assigns Input Bindings to an entity and selects mouse_button_other1 and mouse_button_other2, the Editor does not recognize the said inputs when in the Game Mode.
Issue is not active on Windows.

**Prerequisites**
Recreate .inputbindings and .scriptcanvas assets as shown on the screenshots attached under the Screenshots, .inputbindings and .scripcanvas section.
Additionally, mouse with the extra buttons is needed.

**Steps to reproduce**
1. Create the entity, add Input, Mesh and Script Canvas components to it.
2. Assign Mesh and assets mentioned in the Prerequisites.
3. Enter the Game Mode.
4. Press the extra button.

**Expected behavior**
The entity moves.

**Actual behavior**
The Editor does not recognize the extra button input and the entity does not move.

**Screenshots**

.scriptcanvas
![ScriptCanvas](https://user-images.githubusercontent.com/100559077/183071752-cacd069d-255e-46dc-8b20-a58caa5bc339.png)

.inputbindings
![AssetEditor](https://user-images.githubusercontent.com/100559077/183071765-d0c0e615-7f1d-477c-887b-a33d330164b2.png)

**Found in Branch**
Development (59df478)

**Desktop:**
- Device: PC
- OS: Ubuntu 20.04.4 LTS
- Version: Ubuntu 20.04.4 LTS
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Comment by byrcolin** [comment]
@nick-l-o3de Not sure if you know anything about this but I know you did some input work recently if you want to take a look.
