### ISSUE TITLE
Linux: Asset Editor: ThumbstickInputEventMap class is inconsistently present while the gamepad is not available in the Input Device Type dropdown list

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#11113]
**Describe the bug**
Input Bindings in the Asset Editor has the ThumbstickInputEventMap class (which is for the gamepads) inconsistently present, because the Input Device Type dropdown list has no gamepad available.
Issue is not active on Windows.

**Steps to reproduce**
1. Go to Tools > Asset Editor.
2. In the Asset Editor go to File > Input Bindings.
3. In Input Bindings add Event Generator and observe that the ThumbstickInputEventMap class (which is for the gamepads) is available.
4. Select the InputEventMap class.
5. From Input Device Type expand the dropdown list and observe that the gamepad is not present.

**Expected behavior**
The ThumbstickInputEventMap class is not present or the gamepad is available in the Input Device Type dropdown list.

**Actual behavior**
The ThumbstickInputEventMap class is available while the gamepad is not present in the Input Device Type dropdown list.

**Video**

[InputBindings.webm](https://user-images.githubusercontent.com/100559077/183078193-d0ae23c2-1c10-4e1d-97f8-219096490a70.webm)

**Found in Branch**
Development (59df478)

**Desktop:**
- Device: PC
- OS: Ubuntu 20.04.4 LTS
- Version: Ubuntu 20.04.4 LTS
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Comment by byrcolin** [comment]
@nick-l-o3de If your interested, do you think this still occurs after your update?
