### ISSUE TITLE
Linux: Create prefab current mesh in Editor any distributions causes unwanted duplicated prefabs

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#11138]
**Steps to reproduce**
1. Add a component mesh
2. Add a box to mesh
2. Create a prefab
3. Save prefab
4. Delete current prefab
5. Сlick move there screen prefab
5. Prefab two duplicate bug

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/183424508-bf80a4b4-09a7-4c67-8fa6-931250b1560b.mp4

**Found in Branch**
development: 8b8ee819ce8d0bdf9426eda02cf59f74c574fcaa

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Arch Linux
 - Version: latest

**Comment by monroegm** [comment]
Duplicates #10627
