### ISSUE TITLE
Cannot import jinja2

### ISSUE THREAD

**Issue by e2002e** [o3de/o3de#11142]
```
Traceback (most recent call last):
  File "/home/i20/Documents/o3de/cmake/AzAutoGen.py", line 391, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
CMake Error at cmake/LyAutoGen.cmake:42 (add_custom_command):
  add_custom_command Wrong syntax.  A TARGET or OUTPUT must be specified.
Call Stack (most recent call first):
  cmake/LYWrappers.cmake:404 (ly_add_autogen)
  Code/Framework/AzNetworking/CMakeLists.txt:12 (ly_add_target)
```

I'm sure the module in on my system and can be imported.
Tried modifying the shebang with all versions of python, also tried to make the import on start (why is it not ?)

**Comment by lgleim** [comment]
Hi @e2002e , we discussed this issue today in Sig Simulation issue triage and we suspect, that this issue might already have been solved by https://github.com/o3de/o3de/pull/11213. Could you check if this solves your issue already?

**Comment by e2002e** [comment]
Hi @lgleim, I checked out to development and got the same errors.
Why would a file refuse importing while another would ?

**Comment by AMZN-Olex** [comment]
This isn't related to sig-network.

**Comment by lsemp3d** [comment]
Can you verify that the file `https://github.com/o3de/o3de/blob/development/python/requirements.txt` is correct and has the following item:
```
jinja2==2.11.3 \
    --hash=sha256:03e47ad063331dd6a3f04a43eddca8a966a26ba0c5b7207a9a9e4e08f1b29419 \
    --hash=sha256:a6d58433de0ae800347cab1fa3043cebbabe8baa9d29e668f1c768cb87a333c6 \
    # via -r .\requirements.txt
```

**Comment by e2002e** [comment]
Yes jinja is included in the requirements.
