### ISSUE TITLE
Allow providing only 'changed' data to update System + Scene Configuration APIs

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#11145]
[Migrated from JIRA LYN-1321]

Currently to update a single param in the system configuration.

```c++
SystemConfiguration config = physicsSystem.GetSystemConfiguration();
//apply update to config params
physicsSystem.UpdateSystemConfiguration(config); //this applies all values
```

We should make it possible to do something like this:

```c++
SystemConfiguration config;
config.gravity= myNewValue;
physicsSystem.UpdateSystemConfiguration(config); //this should now only apply the new gravity value
```

**Comment by lgleim** [comment]
After discussing in today's issue triage, we concluded that the risk of "forgetting to  call the `physicsSystem.UpdateSystemConfiguration(config)`" after making a change to the config is greater then the benefit of adding this kind of update API. We also so not currently see that users have the need to update the parameters continuously.
