### ISSUE TITLE
Multiplayer auto-component with an rewindable array property fails to compile

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#11156]
**Describe the bug**
If one defines a multiplayer auto-component with a rewindable array property, then a compilation error occurs.

Here is an example of such a property:
```
<NetworkProperty Type="uint16_t" Name="CoinsPerPlayer" Container="Array" Count="8" IsRewindable="true" ...
```

This results in the following compilation error:
```
2>C:\git\o3de\build\External\o3de-multiplayersample-8c819da3\Gem\Code\Azcg\Generated\Source\AutoGen\MatchPlayerCoinsComponent.AutoComponent.h(203,30): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>        const RewindableArray<uint16_t, 8>& GetCoinsPerPlayerArray() const;
```

From the first look it appears that it is missing `Multiplayer` namespace.

```
        const RewindableArray<uint16_t, 8>& GetCoinsPerPlayerArray() const;
```

**Assets required**
o3de-multiplayersample with the following auto-component:
[MatchPlayerCoinsComponent.AutoComponent.xml.txt](https://github.com/o3de/o3de/files/9285158/MatchPlayerCoinsComponent.AutoComponent.xml.txt)

**Steps to reproduce**
1. Use o3de-multiplayersample or a project with enabled compilation of multiplayer components
2. Add a network property such as `<NetworkProperty Type="uint16_t" Name="CoinsPerPlayer" Container="Array" Count="8" IsRewindable="true" ...`
3. Compile

**Expected behavior**
No compilation errors once the stub .cpp and .h are created and added to the project.

**Actual behavior**
Compilation error:

```
2>C:\git\o3de\build\External\o3de-multiplayersample-8c819da3\Gem\Code\Azcg\Generated\Source\AutoGen\MatchPlayerCoinsComponent.AutoComponent.h(203,30): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>        const RewindableArray<uint16_t, 8>& GetCoinsPerPlayerArray() const;
```

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Comment by AMZN-Gene** [comment]
When implementing the fix, be sure to add a rewindable array property to any of the autocomponent's inside of that AutomatedTest project, that will catch any compile errors in the future.
