### ISSUE TITLE
Bug Report: ScriptCanvas Editor assign graph to entity is broken

### ISSUE THREAD

**Issue by onecent1101** [o3de/o3de#11180]
**Describe the bug**
Assign active graph to selected entities are broken

**Steps to reproduce**
1. Select any entity in the level
2. Open ScriptCanvas Editor, create any graph and save it.
3. Click button (a box with right direction arrow) to assign active graph to selected entity

**Expected behavior**
ScriptCanvas component is created and assigned with active graph.

**Actual behavior**
ScriptCanvas component is created without any graph assigned.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Additional context**
Related issue was first reported in https://github.com/o3de/o3de/issues/8019, but it focused on read-only procedural prefab modification

**Comment by lsemp3d** [comment]
Closed by PR #11705
