### ISSUE TITLE
Projects cannot be built in Project Manager on Pre-built SDK configuration engine

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#11191]
**Describe the bug**
Attempting to build a project via Project Manager on an engine built with the Pre-built SDK configuration fails. It should also be noted that occasionally Project Manager would crash while attempting to build the project, however no consistent reproduction steps for it were found. 

It should be noted that this occurs on both Windows, and Linux.

It should also be noted that on Source engine configuration, the projects can be built without issues.

Please refer to the **Project build error logs** for more information.

**Steps to reproduce**
1. Go to https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/ (or https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/), and follow the commands listed for the Pre-built SDK engine build configuration, build, and registration.
2. Launch the Project Manager.
3. In the Project Manager go to New Project... > Create New Project.
4. Create Default Template project.
5. Click the Build Project button on the created project's tile in the Project Manager.

**Expected behavior**
Project builds.

**Actual behavior**
Project fails to build, or Project Manager crashes.

**Project build error logs**
[CMakeProjectBuildErrorPCWindows.log](https://github.com/o3de/o3de/files/9299471/CMakeProjectBuildErrorPCWindows.log)
[CMakeProjectBuildErrorPCLinux2.log](https://github.com/o3de/o3de/files/9299473/CMakeProjectBuildErrorPCLinux2.log)
[CMakeProjectBuildErrorPCLinux1.log](https://github.com/o3de/o3de/files/9299474/CMakeProjectBuildErrorPCLinux1.log)

**Found in Branch**
Development (a88f38d)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (c1c018b) build.

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed using Stabilization/2210 (https://github.com/o3de/o3de/commit/99608ffd4f7d3d347cb015b243046a3438da23c7) build.
