### ISSUE TITLE
AR Bug Report: Linux test_profile_nounity failed due Subprocess aborted in AzCore test run

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#11197]
**Describe the bug**
Linux tests failed due to AzCore test run "subprocess aborted" error.

````
2 - AZ::AzCore.Tests.main::TEST_RUN (Subprocess aborted)
````

````
[----------] 1 test from AssetManagerEbusSafety
[ RUN      ] AssetManagerEbusSafety.OnAssetReady_GetAsset_DoesNotDeadlock
pure virtual method called
terminate called without an active exception
````

**Failed Jenkins Job Information:**
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/2895/pipeline/400 

**Attachments**
[log.txt](https://github.com/o3de/o3de/files/9301374/log.txt)

**Comment by lumberyard-employee-dm** [comment]
@amzn-mike Do you know if this failure is related to your recent AssetManager thread EBus changes

**Comment by amzn-mike** [comment]
Yes this is a new test I added.  I'm looking into it.  It doesn't seem to reproduce on windows at all so far

**Comment by moraaar** [comment]
The next execution of AR went green... which suggests this is an intermittent issue, making it harder to find and fix.

**Comment by amzn-mike** [comment]
https://github.com/o3de/o3de/pull/11202 might fix this.  It should fix some of the other failures that have popped up, it's hard to say if this one is the same or not though.
