### ISSUE TITLE
Prefab Focus Mode | Pressing ESC changes focus to root prefab instead of direct parent prefab

### ISSUE THREAD

**Issue by forkercat** [o3de/o3de#11214]
**Describe the bug**

When pressing ESC in a prefab focus mode, it will always change the focus to level prefab. However, if there are two levels of nested prefabs, the focus should not always change to level.

**Assets required**

N/A

**Steps to reproduce**

1. Create an empty level
2. Create a Car entity and create a prefab from it
3. Create a Wheel entity and create a prefab from it
4. Reparent the Wheel prefab under Car prefab
5. Focus on Car prefab then on Wheel prefab
6. Hit ESC

**Expected behavior**

Focus on Car prefab

**Actual behavior**

Focus on Level prefab

Pressing ESC should behave as we click the "X" button, that is, focus on the direct parent instance.

**Screenshots/Video**

https://user-images.githubusercontent.com/11157226/184056102-3ac538c6-78a7-4a36-83bb-54c7f12e3751.mp4

- 1st attempt: Clicking "X" button
- 2nd & 3rd attempt: Pressing ESC

**Found in Branch**

Development 6173c6c65b on 8/10/2022

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10
 - CPU: AMD Ryzen 5950x
 - GPU: NVIDIA RTX 3070
 - Memory: 64 GB

**Additional context**

N/A

**Comment by monroegm** [comment]
This is currently by design. The shortcut to go up one level is "-". Feel free to discuss with UX if you want something different.
