### ISSUE TITLE
AR Bug Report - AZ::AssetProcessor.Tests.main::TEST_RUN Failed

### ISSUE THREAD

**Issue by amzn-ahmadkrm** [o3de/o3de#11220]
**Describe the bug**
`AZ::AssetProcessor.Tests.main::TEST_RUN` failed running on the AR with an unrelated change

**Failed Jenkins Job Information:**

Platform/Job: Windows [profile_pipe] - test_cpu_profile

https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-11201/1/pipeline

**Attachments**
[log.txt](https://github.com/o3de/o3de/files/9310173/log.txt)

**Comment by AMZN-stankowi** [comment]
This may have been fixed and the ticket not updated, we'll keep an eye on job failures to see if this happens again, if it doesn't in the next few days we'll close this ticket.

**Comment by AMZN-stankowi** [comment]
Closing as per previous comment. If we see this again, let's make a new ticket.
