### ISSUE TITLE
ClientServer support in the Editor Ctrl-G

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#11230]
**Is your feature request related to a problem? Please describe.**
A multiplayer project with editorsv_enabled = true takes a while to get into game mode with ctrl-g, primarily due to waiting on the dedicated server to startup. It would be great to have a editorsv_hosted = true or similar cvar so that the editor acts as both a client and a server, thus allowing for very fast ctrl-g experience and to test non-dedicated server scenario in the Editor.

**Describe the solution you'd like**
Add a cvar, such as: `editorsv_hosted = true` to enabled client-server of game mode in the Editor.

**Additional context**
This applies only to multiplayer projects.

This behavior is what is possible on a game launcher by calling `host` and then `loadlevel`.

**Comment by AMZN-Olex** [comment]
This should help WF6 workflows by speeding them up and reducing requirements, such as having to compile Server Launcher ahead of time each time.

**Comment by AMZN-puvvadar** [comment]
Is this not resolved by https://github.com/o3de/o3de/pull/12656 @AMZN-Olex ?

**Comment by AMZN-Gene** [comment]
Fixed by @AMZN-Olex 
_editorsv_clientserver_ will launch multiplayer game in the editor where the editor is running as both a host and player.
