### ISSUE TITLE
 [track view] when there is a dual screen, the track view window is on the secondary screen. Open the trackview events window and find that the window is very long.

### ISSUE THREAD

**Issue by lanbingluyu** [o3de/o3de#11249]
**Describe the bug**
when there is a dual screen, the track view window is on the secondary screen. Open the trackview events window and find that the window is very long. 

**Steps to reproduce**
1. Open the track view window, select the completed sequence, and move the track view window to the secondary screen
2. Right click the blank space of the node browser and click Edit events

**Expected behavior**
The trackview events window pops up normally

**Actual behavior**
The trackview events window that pops up is very long.

**Desktop/Device (please complete the following information):**
Device: PC
OS: Windows
Version 10
CPU Intel i7-10700
GPU Intel UHD Graphics 630
Memory 32GB

**Additional context**

**Comment by Jackie9527** [comment]
There are some PRs trying to fix the issues, such as #14661 #14787 , please have a try with the latest codes.
