### ISSUE TITLE
Feature Request - Reduce log warning spam for deprecated components

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#11262]
**Is your feature request related to a problem? Please describe.**

Currently when deprecating a Component (removing it from a .prefab file if it is no longer required - see https://github.com/o3de/o3de/pull/9430 for an example), a lot of log spam is generated that may be disconcerting for the user. It would be better to handle this in a cleaner way (maybe not silent but less noisy).

**Describe the solution you'd like**

An indication a component has been deprecated once in the log (not per instance that was removed ideally).

In addition (note the level does not show changes right now which is the behavior we want to keep), when a component is deprecated (and needs to be removed from a level/prefab), instead of showing that the level has changes (and needs saving) it would be better to identify deprecated components during level loading and show a more useful dialog where we explain why saving a level would be useful. This would be in addition to reducing the amount of log spam.

**Describe alternatives you've considered**

Handling this completely silently (what the older `SerializeContext` does for reference)

**Additional context**

See this PR for details - https://github.com/o3de/o3de/pull/9430

Tagging @srikappa-amzn for visibility

**Comment by monroegm** [comment]
@michabr FYI

**Comment by hultonha** [comment]
Closing this issue now https://github.com/o3de/o3de/pull/11822 is merged. Awesome work @michabr! 🥳
