### ISSUE TITLE
ClientServer - Autonomous to Authority RPCs do not execute in a ClientServer scenario

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#11283]
**Describe the bug**
In a client-server state, where a game launcher is hosting a server, a network component on an autonomous entity does not receive RPCs that are marked as Autonomous -> Authority.

For example, an RPC of type:
```
	<RemoteProcedure Name="RPC_FromLocalPlayerToServer" InvokeFrom="Autonomous" HandleOn="Authority" ... >
	</RemoteProcedure>
```

This type of RPC when invoked on an Autonomous entity does not invoke its Handle_____ counterpart. In this case, it would be on the same controller on the same entity, as an Autonomous component in a client-server host also has Authority role.

This same behavior occurs correctly in a client -> dedicated server setup.

**Steps to reproduce**
1. Configure a multiplayer with an RPC definition as above.
2. Launch a game launcher.
3. host
4. loadlevel
5. invoke rpc Autonomous -> Authority
6. observe if HandleRPC_Name is called on the same controller or not

**Expected behavior**
Autonomous -> Authority RPC is not sent and received on the same component controller in a client-server hosted scenario.

**Actual behavior**
Autonomous -> Authority RPC should be received on the same component controller in a client-server hosted scenario.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Comment by kberg-amzn** [comment]
Good catch 👍

**Comment by lmbr-pip** [comment]
Relates to clientserver test mode for ctrl+g. Would be much easier to catch these type of issues if mode was supported.
