### ISSUE TITLE
Add functoinality to determine whether a given CMake target is a 3rd party import or an internally aliased target.

### ISSUE THREAD

**Issue by jonawals** [o3de/o3de#11280]
**Is your feature request related to a problem? Please describe.**
The Test Impact Analysis Framework needs to be able to filter out 3rd party dependencies form its internal model of the build system. As it stands, there is no way to conclusively do this so instead the framework is excluding all targets with the `3rdParty` namespace. However, this is a brittle solution that will break should a 3rd party dependency be added without this namespace. 

**Describe the solution you'd like**
A CMake function to be able to determine whether or not a given target is a 3rd party target.

**Describe alternatives you've considered**
Right now I am excluding targets in the namespace `3rdParty`. However, this is not a sustainable solution. A suggestion by @lumberyard-employee-dm was to check each target for the `IMPORTED` property but, as can be seen in the listing below of targets with this property, target aliases also have this property (in the namespace `Gem`), yet these target aliases should not be excluded. Checking whether or not a given target is an alias would also be a brittle solution as there would be nothing stopping customers from aliasing 3rd party dependencies.

```
3rdParty::AWSGameLiftServerSDK
3rdParty::AWSNativeSDK::AWSClientAuth
3rdParty::AWSNativeSDK::AWSCore
3rdParty::AWSNativeSDK::Core
3rdParty::AWSNativeSDK::GameLiftClient
3rdParty::Blast
3rdParty::Crashpad
3rdParty::Crashpad::Handler
3rdParty::DirectXShaderCompilerDxc
3rdParty::Freetype
3rdParty::GoogleBenchmark
3rdParty::ISPCTexComp
3rdParty::Lua
3rdParty::NvCloth
3rdParty::OpenEXR
3rdParty::OpenGLInterface
3rdParty::OpenImageIO
3rdParty::OpenImageIO::Tools::Binaries
3rdParty::OpenImageIO::Tools::PythonPlugins
3rdParty::OpenSSL
3rdParty::PNG
3rdParty::PhysX
3rdParty::Python
3rdParty::Qt::Concurrent
3rdParty::Qt::Core
3rdParty::Qt::Gui
3rdParty::Qt::Network
3rdParty::Qt::OpenGL
3rdParty::Qt::Svg
3rdParty::Qt::Test
3rdParty::Qt::Widgets
3rdParty::Qt::Xml
3rdParty::RapidJSON
3rdParty::RapidXML
3rdParty::SPIRVCross
3rdParty::SQLite
3rdParty::TIFF
3rdParty::ZLIB
3rdParty::assimplib
3rdParty::astc-encoder
3rdParty::azslc
3rdParty::cityhash
3rdParty::d3dx12
3rdParty::expat
3rdParty::glad_vulkan
3rdParty::googletest::GMock
3rdParty::googletest::GTest
3rdParty::libsamplerate
3rdParty::lz4
3rdParty::mcpp
3rdParty::md5
3rdParty::mikkelsen
3rdParty::poly2tri
3rdParty::pybind11
3rdParty::pyside2
3rdParty::squish-ccr
3rdParty::v-hacd
3rdParty::vulkan-validationlayers
3rdParty::xxhash
3rdParty::zstd
Gem::AWSCore.Clients
Gem::LyShine.Clients.API
Gem::MaterialCanvas.Builders
Gem::MaterialEditor.Builders
Gem::ShaderManagementConsole.Builders
Gem::UiBasics.Builders
Gem::UiBasics.Tools
```

**Comment by jonawals** [comment]
Fixed with using `o3de_extract_aliased_target_dependencies` to extract the de-aliased name(s) first (will add PR here).

**Comment by lumberyard-employee-dm** [comment]
We also had the `GEM_MODULE` property to the alias targets
