### ISSUE TITLE
Assert in EditorViewportWidget during editor startup

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/o3de#11296]
**Describe the bug**
It looks like PR https://github.com/o3de/o3de/pull/11052 introduced a new assert during editor startup

**Steps to reproduce**
1. Have asserts enabled. (add this to any setreg in your project)
 "O3DE": {
		"Autoexec": {
			"ConsoleCommands": {
				"bg_assertsAutoBreak": true
			}
		}
	}
2. start the editor

**Expected behavior**
Editor starts without any asserts

**Actual behavior**
Assert is thrown. When continued, everything works during debugging.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
Device: PC
OS: Windows
Version 10
CPU Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz
GPU NVidia GeForce RTX Super 2700
Memory 64GB
**Additional context**
**Callstack:**
 	EditorLib.dll!AZ::Debug::Platform::DebugBreak() Line 90	C++
 	EditorLib.dll!AZ::Debug::Trace::Assert(const char * fileName, int line, const char * funcName, const char * format, ...) Line 445	C++
 	EditorLib.dll!AZ::EventHandler<float>::Connect(AZ::Event<float> & event) Line 125	C++
>	EditorLib.dll!EditorViewportWidget::SetViewportId(int id) Line 958	C++
 	EditorLib.dll!CLayoutViewPane::AttachViewport(QWidget * pViewport) Line 303	C++
 	EditorLib.dll!CLayoutViewPane::SetViewClass(const QString & sClass) Line 219	C++
 	[Inline Frame] EditorLib.dll!CLayoutWnd::BindViewport(CLayoutViewPane * vp, const QString &) Line 165	C++
 	EditorLib.dll!CLayoutWnd::MaximizeViewport(int paneId) Line 205	C++
 	EditorLib.dll!CLayoutWnd::LoadConfig() Line 515	C++
 	EditorLib.dll!MainWindow::InitCentralWidget() Line 444	C++
 	EditorLib.dll!MainWindow::Initialize() Line 469	C++
 	EditorLib.dll!CCryEditApp::InitInstance() Line 1745	C++
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 4011	C++
**Error:**
<11:33:00> (System) - Trace::Assert
 D:\o3de\Code\Framework\AzCore\AzCore/EBus/Event.inl(124): (27976) 'void __cdecl AZ::EventHandler<float>::Connect(class AZ::Event<float> &)'
System: Handler is already registered to an event, binding a handler to multiple events is unsupported
<11:33:00> (System) - Handler is already registered to an event, binding a handler to multiple events is unsupported

It looks like the same handler(m_nearFarPlaneDistanceHandler) is being used to register to 2 events, which isn't supported.

**Comment by srikappa-amzn** [comment]
@hultonha , tagging you since this is related to viewport code. Please feel free to assign/modify the issue as needed.

**Comment by hultonha** [comment]
This is fixed by https://github.com/o3de/o3de/pull/11257 - should hopefully be merged soon

**Comment by hultonha** [comment]
Closing as this was fixed by #11257
