### ISSUE TITLE
AR Bug Report - Gem::Atom_RPI.Tests.main::TEST_RUN Failed

### ISSUE THREAD

**Issue by amzn-ahmadkrm** [o3de/o3de#11290]
**Describe the bug**
Gem::Atom_RPI.Tests.main::TEST_RUN failed running on the AR with an unrelated change

**Failed Jenkins Job Information:**
Platform/Job: Windows [profile_pipe] - test_cpu_profile

https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-11203/1/pipeline

**Additional context**
[log.txt](https://github.com/o3de/o3de/files/9336891/log.txt)

**Comment by lumberyard-employee-dm** [comment]
This was fixed by #11269
