### ISSUE TITLE
Rapidly and simultaneously pressing Esc and Done buttons in Component Mode may result in Editor's softlock

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#11309]
**Describe the bug**
When the User is rapidly and simultaneously pressing Esc and Done buttons in Component Mode it may result the Editor's softlock.
What can be then observed is O3DE acting like in the Component Mode despite the mode being closed.
Please note that this issue seems inconsistent to reproduce and has the reproduction rate of about 6/10.

**Steps to reproduce**
1. Create a new entity.
2. Open pinned Entity Inspector on the said entity and undock it.
3. Add any component with Component Mode (e.g. Box Shape).
4. Click Edit Mode.
5. Rapidly and simultaneously press Esc and Edit buttons.
6. Repeat the combination from the step 5 until the Editor softlocks itself in Component Mode.

**Expected behavior**
 Rapidly and simultaneously pressing Esc and Done buttons in Component Mode does not result in Editor's softlock.

**Actual behavior**
Rapidly and simultaneously pressing Esc and Done buttons in Component Mode may result in Editor's softlock.

**Video**

https://user-images.githubusercontent.com/100559077/184889087-25757c5b-723a-4f21-bcc4-6190de450bf6.mp4

**Found in Branch**
Development (bc74b3b)

**Desktop:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Comment by LB-JakubSkorupka** [comment]
Verified the issue as fixed on builds Development (74bb8dd), and Stabilization/2210 (37c7b44).
