### ISSUE TITLE
Drawn rotation angle becomes solid color after few spins

### ISSUE THREAD

**Issue by LB-KrzysztofPinkowski** [o3de/o3de#11308]
**Describe the bug**
After rotating entity in rotate mode, drawn rotation angle becomes a solid color, and the rotated entity could not be visible through it.

**Steps to reproduce**
1. Select entity.
2. Switch to rotate mode.
3. Start rotating entity with rotation manipulator and make a couple of full turns.

**Expected behavior**
Drawn rotation angle becomes a solid color.

**Actual behavior**
Drawn rotation angle stays transparent.

**Screenshots/Video**

https://user-images.githubusercontent.com/110379578/184889067-fa5184df-0654-44d0-b9fe-2896c171323c.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/bc74b3baf20b095049542c073aa6362ea642cab4)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 5600H
 - GPU NVIDIA GeForce RTX 3070 Laptop GPU
 - Memory 16GB

**Comment by guillaume-haerinck** [comment]
Can be closed as it was fixed by the merge above (I did not linked the issue properly)

**Comment by LB-KrzysztofPinkowski** [comment]
Closed as fixed. Verified in Stabilization (021d32a) and development (511a88c) branches.
