### ISSUE TITLE
Selecting Monochromatic mode in the Edit Mode dropdown menu does not have any effect on the Edit Mode

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#11303]
**Describe the bug**
In the top toolbar above the viewport there is the Edit Mode dropdown menu, but selecting Monochromatic and Normal modes from it does not provide any changes when the Edit Mode is entered.
Please note that this feature also lacks any information about it in the documentation.

**Steps to reproduce**
1. Select Monochromatic mode in the Edit Mode dropdown menu.
2. Add the Box Shape component to an entity.
3. Click Edit Mode in the said component.

**Expected behavior**
Selecting Monochromatic will likely change the viewport to Monochromatic when in the Edit Mode.

**Actual behavior**
Selecting Monochromatic does not change anything when in the Edit Mode.

**Video**

https://user-images.githubusercontent.com/100559077/184850465-e699e94c-7092-43c0-a054-76253976aed6.mp4

**Found in Branch**
Development (bc74b3b)

**Desktop:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Comment by LB-MateuszSzweda** [comment]
I have found a workaround that requires the user to:

1. Enable the EditorModeFeedback by providing the project's editorpreferences.setreg with
`"EnableEditorModeFeedback": true,` line
2. Switch Edit mode to Monochromatic.
3. Add any component with component mode capability to the entity in the Viewport.
4. Enter the component mode and exit it.

The Monochromatic mode will then trigger itself and can be then switched at will.
This workaround can be observed in the video below.

https://user-images.githubusercontent.com/86953456/185939049-39b30572-282d-448d-b2ff-b52db9259ba7.mp4

**Comment by jonawals** [comment]
This appears to be due to EMVF being disabled at the feature flag level but the UI elements are still visible. A fix will be put in place to ensure that no EMVF UI elements are visible when the feature is disabled.

**Comment by AMZN-daimini** [comment]
@jonawals I am currently porting that selector to the new action manager, reach out if you are thinking of working on it soon :) Thanks!

**Comment by LB-ArturZieba** [comment]
We will reverify this issue when fix is pushed. Currently on the Development (a881574) build, the issue still occurs as described and the "EnableEditorModeFeedback": true workaround does not work anymore.

**Comment by hultonha** [comment]
@LB-ArturZieba - I believe this issue is by design because we do not enable the Editor Mode Feedback Effect for Component Mode (only for prefab editing) so I think you not seeing the feedback is consistent with the design (tagging @rainbj for confirmation). Thanks!

**Comment by AMZN-daimini** [comment]
I think the confusion currently stems from the fact that `Component Mode` and `Prefab Focus Mode` are both referred to as `Edit Mode` sometimes. We may want to clarify that menu - making it only appear during prefab focus mode would help (that is the current intention and the task is already tracked elsewhere)

**Comment by LB-ArturZieba** [comment]
Thanks for the explanation!

**Comment by hultonha** [comment]
> I think the confusion currently stems from the fact that `Component Mode` and `Prefab Focus Mode` are both referred to as `Edit Mode` sometimes. We may want to clarify that menu - making it only appear during prefab focus mode would help (that is the current intention and the task is already tracked elsewhere)

Also 'Focus' mode terminology should no longer be used 😝 (I'm certain this was the last guidance from @rainbj)

So we now have...

**Component Edit Mode** (blue border)
**Prefab Edit Mode** (screen-space effect)

**Comment by AMZN-daimini** [comment]
I am currently restructuring the viewport toolbar, and in the new design I have changed the labeling to say "Prefab Edit":
![image](https://user-images.githubusercontent.com/82231674/204872996-6c1cf4a4-059a-42a8-a564-55e2ff2f3576.png)

Hope that does clarify things enough. If it still feels confusing, I would open a ticket directed to sig-ui-ux to take a look at this.

**Comment by hultonha** [comment]
Nice change! 🙂 Thanks for the update @AMZN-daimini, looks good to me!
