### ISSUE TITLE
Create joint properties widget for the inspector

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#11314]
[Migrated from JIRA LYN-14046]

## Description

The aim of this task is to create a new widget for the inspector window that shows the basic joint attributes. Basic in this case here means the upper part shown in the screenshot below, the not crossed-out part. The part which is crossed-out is part of https://github.com/o3de/o3de/issues/11313.

This is the UX design and how it shall look like:

![image-2022-07-21-14-15-49-090](https://user-images.githubusercontent.com/82228511/184929453-83fc944b-5711-46e2-b05f-c26070d0fe4c.png)

The "Node attributes" above shall be one of the new card widgets done with https://github.com/o3de/o3de/issues/10958.

We don't need to start from scratch for the content as well. As you can see in the image below there is a legacy "Joint outliner" window (EMStudio::NodeWindowPlugin). That holds a skeletal hierarchy and a "Node attributes" section at the bottom which shows the joint name, position, rotation etc. basically the things that we also see in the image above.

We can just move and use that code. The bottom "Node attributes" section is part of the EMStudio::NodeWindowPlugin::m_propertyWidget member variable.

To get to the screen shown below use the following steps:
 - File -> Load Actor (load any actor asset)
 - Use the combo at the top right to go to the Character layout
 - Select any of the joints and see the node attributes in the bottom widget

![image-2022-07-21-14-55-45-592](https://user-images.githubusercontent.com/82228511/184929571-e560be03-fcca-4ca9-8041-80e4102ba53a.png)

This is how it looks like when selecting the actor instance / character rather than a joint:

![image-2022-07-21-15-26-01-919](https://user-images.githubusercontent.com/82228511/184929664-ab7562e0-8e52-4281-8425-2d9fd86dd1e3.png)

Now that we know where the legacy code is, let's check into how the new thing shall work.

Let's switch to the "Physics" layout, as there we have the new and not the legacy skeleton outliner.

Whenever we select a joint in the skeleton outliner, we want to display the properties of the joint in the inspector window. To do that we need to call the following EBus:

```
EMStudio::InspectorRequestBus::Broadcast(&EMStudio::InspectorRequestBus::Events::Update,...)
```

from inside the `EMotionFX::SkeletonOutlinerPlugin` as well as the Joint outliner.

Note: The inspector window can be opened via the file menu: View -> Inspector.

Also please note, that you need to bring up the new skeleton outliner to test selection. On default for the Character layout, the joint outliner is opened.

To sum it up again:

 * Create new `JointPropertyWidget`
 * Move `EMStudio::NodeWindowPlugin::m_propertyWidget` over from the `EMStudio::NodeWindowPlugin` to the new `JointPropertyWidget`
 * Call `EMStudio::InspectorRequestBus::Broadcast(&EMStudio::InspectorRequestBus::Events::Update,...)` whenever the selection in the `EMotionFX::SkeletonOutlinerPlugin` is changed and feed in the new `JointPropertyWidget` to the Inspector

**Acceptance criteria:**

 * When selecting a new joint in the Skeleton Outliner (which is there by default when using the Physics layout, otherwise has to be opened via the menu), the joint properties are shown inside the Inspector window.
 * When selecting the root item in the Skeleton Outliner, the Character itself, the properties from the character are shown.
 * The "Node Attributes" inside the "Joint outliner" got removed.

**Comment by ablepharus** [comment]
![image](https://user-images.githubusercontent.com/57981/188496993-7c3f8a08-395e-418c-96ae-438c75670f03.png)

**Comment by hultonha** [comment]
I think that is along the lines of what we're after but it would be good to feedback from @bhanuja-s if possible. Thanks for the update @ablepharus :+1:

**Comment by hultonha** [comment]
Tagging @amzn-leenguy for visibility as well

**Comment by bhanuja-s** [comment]
That is exactly what we were thinking @ablepharus, thank you!
