### ISSUE TITLE
Move simulated object properties to shared joint properties in inspector

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#11312]
[Migrated from JIRA LYN-11491]

## Description

This task is very similar to https://github.com/o3de/o3de/issues/11313 and should be done after it.

The highlighted part in red, the currently called "Simulated Object Inspector", shall be consolidated into the "Inspector" window together with the other joint properties inside another section using the new separator widget from https://github.com/o3de/o3de/issues/10958.

![image-2022-08-11-10-30-23-911](https://user-images.githubusercontent.com/82228511/184927124-9959389d-b4ab-4603-8eb0-96dba0c2644c.png)

### Acceptance Criteria

 * When selecting a joint in the skeletal outliner the joint properties will be shown in the inspector window
 * There is a new section for "Simulated Object" that shows the content of the "Simulated Object Inspector" shown in the image above (minus the joint name, as that is part of the base joint properties already).

**Comment by ohmaya** [comment]
Do we still have access to "Collides with" mentioned in https://version-2305--o3deorg.netlify.app/docs/user-guide/visualization/animation/set-up-simulated-object-collider/?
