### ISSUE TITLE
Move ragdoll/hit detection/cloth colliders to shared joint properties in inspector

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#11313]
[Migrated from JIRA LYN-11493]

## Description

This will extend the joint properties created with https://github.com/o3de/o3de/issues/11314

The new joint properties shall be extended with the following content:

 * Ragdoll
 * Hit detection
 * Cloth

**Current way:**

Currently, we have three different plugins/windows for ragdoll/hit detection and cloth colliders as seen in the screenshot below. The corresponding source files are:

 * Cloth: `ClothJointInspector.h/.cpp`
 * Hit Detection: `HitDetectionJointInspectorPlugin.h/.cpp`
 * Ragdoll: `RagdollNodeInspectorPlugin.h/.cpp`

![image-2022-08-03-15-23-55-670](https://user-images.githubusercontent.com/82228511/184928487-43b8ffe7-314a-418f-986f-56dbfcb47502.png)

**Changes:**

Each of these currently separated widgets shall be consolidated in the new joint properties window created with https://github.com/o3de/o3de/issues/11314 according to the UX design below:

![image-2022-07-21-14-10-03-209](https://user-images.githubusercontent.com/82228511/184928514-5bea9dd9-aed0-468e-89f8-380f8d935f4b.png)

### Acceptance Criteria:

 * `ClothJointInspector.h/.cpp`, `HitDetectionJointInspectorPlugin.h/.cpp`, `RagdollNodeInspectorPlugin.h/.cpp` got removed and are not part of the code base anymore. Only the actual content widgets are still there (and used and shown in the Inspector)
 * The hit detection collider area is grouped with the new separator widget from https://github.com/o3de/o3de/issues/10958 and the content from the previous HitDetectionNodeInspectorPlugin.h/.cpp is shown.
 * Same for the ragdoll properties
 * Same for the cloth properties
 * Once a joint in the "Skeleton Outliner" is selected all of the joint properties are shown (base joint properties, hit detection, ragdoll and cloth colliders).

**Comment by ablepharus** [comment]
![image](https://user-images.githubusercontent.com/57981/188421278-1f39fa09-8a4d-4326-9be3-f78a421b193b.png)

**Comment by hultonha** [comment]
Thanks for adding the image @ablepharus, looking really cool! Tagging @bhanuja-s and @yuyihsu for visibility.

**Comment by ablepharus** [comment]
Still looking silly when empty
![image](https://user-images.githubusercontent.com/57981/188486394-e071d25f-f5c6-40e7-a560-b6df6a78771e.png)

**Comment by hultonha** [comment]
Hmm interesting 🤔 I wonder how we want this to look, is it possible to hide them entirely? Likely something for @bhanuja-s to decide

**Comment by bhanuja-s** [comment]
That looks great @ablepharus! I have a few thoughts, @yuyihsu feel free to chime in!

1. There's a typo in Hit Detection, just want to make sure that gets fixed.
2. To the point of it looking silly when empty, I completely agree. I believe there should be an interaction, where if there are no contained cards, the widget is hidden from view. If the user has at least one card in, say Ragdoll, only the Ragdoll container should be shown.
3. Having the two Add Collider buttons (one on top and then one in Ragdoll) is slightly confusing. I would propose that we change the top dropdown button to be "Add Property" and include the Ragdoll properties in there (as shown in the attached image)
4. We should make use of the Menu button on each card, and include "Remove from [X Container]" as a right-click menu option (also shown in image). This would make the current Remove from ragdoll button redundant, which we're proposing to get rid of.  

<img width="1583" alt="#11313" src="https://user-images.githubusercontent.com/84036086/189141574-54442b6b-fde6-4477-a9da-744fea1b8197.png">

**Comment by FuzzyCarterAWS** [comment]
@hultonha @ablepharus 

Updated the workflow docs in o3de/sig-simulation#22
