### ISSUE TITLE
ComponentModeSwitcher allows the User to enter component mode on newly created prefab crashing the Editor

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#11334]
**Describe the bug**
Creating a new prefab out of an entity consisting of any component, which can have its component mode entered via Viewport's **Component Mode Switcher** allows the user to enter the component mode of the newly created prefab and crashes the Editor.

Please note that this action is only possible when new prefab was created out of the entity and the entity was not deselected.
Deselecting the created prefab and selecting it again removes the option to enter its component mode.

For more information please refer to the attached video file and crash logs.

**Prerequisites**:
 * The selected project was built and Component Mode Switcher was enabled for it by including
```
 "Amazon": {
    "Preferences": {
        "Editor": {
            "ComponentSwitcherEnabled": true,
```
lines in project's _editorpreferences.setreg_ file.

**Steps to Reproduce**:
 1. Launch the Editor and create a new level.
 2. Create a new entity and add **Box Shape** component to it.
 3. Right-click the entity and select the "Create Prefab..." option.
 4. Select a name for the prefab and save it.
 5. Without deselecting the newly created prefab navigate to the **Component Mode Switcher** menu
 located in the upper left corner of the Viewport.
 6. Click the _Enter Box Shape Edit mode_ button on the **Component Mode Switcher** menu.

**Expected behavior**
Newly created prefabs do not have the option to enter their component modes with the Component Mode Switcher.

**Actual behavior**
Newly created prefabs have the option to enter their component mode with the Component Mode Switcher and it crashes the Editor.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/185144506-e1da0996-f7a7-481c-b98d-d9014dfeb14b.mp4

**Found in Branch**
Development  (b5158ab)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 9 3900X
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/9363000/Editor.log)
[error.zip](https://github.com/o3de/o3de/files/9363001/error.zip)
[error.log](https://github.com/o3de/o3de/files/9363002/error.log)

**Comment by hultonha** [comment]
Update: Dropping this to `priority/major` as we intentionally have this feature disabled by default so users won't encounter this unless the opt-in to turning it on. 

Please can you take a look at this @amzn-ahmadkrm. Thanks!

**Comment by amzn-ahmadkrm** [comment]
Fix in https://github.com/o3de/o3de/pull/11341

**Comment by LB-MateuszSzweda** [comment]
I can confirm that on Development (f1d46fc) the crash with box shape no longer occurs.
But repeating the above steps with any other component with component mode still reproduces the crash.

The affected components are: **PhysX Collider**, **Whitebox** , **Spline**, **Polygon Prism Shape** and **Axis Aligned Box Shape** .

For further information please refer to the result with whitebox component posted below.

https://user-images.githubusercontent.com/86953456/185446305-9a0207b0-4d6c-414f-983f-c0e3b69cb28b.mp4

[error.log](https://github.com/o3de/o3de/files/9375704/error.log)

[Editor.log](https://github.com/o3de/o3de/files/9375706/Editor.log)
[error.zip](https://github.com/o3de/o3de/files/9375708/error.zip)

**Comment by amzn-ahmadkrm** [comment]
Fixed merged: https://github.com/o3de/o3de/pull/11341

**Comment by LB-MateuszSzweda** [comment]
Verified as fixed and not occuring with all components mentioned above in Stabilization/2210 (4952439) and Development (5851cf8)

**Comment by hultonha** [comment]
Great to hear! Thanks for the update @LB-MateuszSzweda 🥳
