### ISSUE TITLE
Deleting all entities from prefab in its focus mode result in "Exit Focus Mode" button disappearing

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#11332]
**Describe the bug**
When in focus mode of prefab, deleting all entities in that prefab results in "Exit Focus Mode" button on the left side of prefab in **Entity Outliner** disappearing.

Note that it is still possible to exit the focus mode of previously mentioned prefab by pressing Esc or double-clicking that prefab in **Entity Outliner**.

**Steps to reproduce**
1. Create a new level.
2. Create an entity in **Entity Outliner** then create a prefab out of it.
3. Enter the focus mode of previously created prefab by clicking button on the left side of it in **Entity Outliner**.
4. Delete all entities present in the prefab.

**Expected behavior**
"Exit Focus Mode" button on the left side of the prefab does **not** disappear after deleting all entities in that prefab.

**Actual behavior**
"Exit Focus Mode" button on the left side of the prefab disappear after deleting all entities in that prefab.

**Video**

https://user-images.githubusercontent.com/86951967/185127808-84904093-4062-4cd7-af73-3079ff5a03e6.mp4

**Found in Branch**
Development (e4abc2a)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by guillaume-haerinck** [comment]
Can be closed as it was fixed by the merge above (I did not linked the issue properly)

**Comment by LB-JakubSkorupka** [comment]
Closing the issue as verified the fix on build Development (d54a18a).
