### ISSUE TITLE
PhysX .pxmesh generation using the asset importer does not respect defined coordinate system changes

### ISSUE THREAD

**Issue by lgleim** [o3de/o3de#11330]
**Describe the bug**
When specifying a `Coordinate system change`  (such as scaling or rotation) in the asset importer, it are correctly applied to the visual mesh, yet ignored by the pxmesh generation. Subsequently, pxmesh and visual mesh are ill-aligned / ill-scaled.

**Assets required**
[monkey.zip](https://github.com/o3de/o3de/files/9358761/monkey.zip) (an `.fbx` export of Blender's Suzanne)

**Steps to reproduce**
To reproduce the behavior:
1. Add the `monkey.fbx` to the scene and wait for the asset processor to complete
2. Click right on `monkey.fbx` in the `Asset Browser` and select `Edit Settings` 
3. In the `Meshes` tab, `Add Modifier` -> `Coordinate System Change`
4. Specify a transform of choice
5. In the `PhysX` tab, configure the generation of at least one pxmesh
6. `Update` the asset and add it to the scene
7. Add a `PhysX Collider` component to the monkey object (uses the PhysicsAsset by default)
8. Enable `helper` rendering
9. See the monkey business

**Expected behavior**
Derived `.pxmesh` assets generated by the asset importer should be aligned and uniformly scaled.
Therefore, the pxmesh generation should:
1. support the coordinate change modifier
2. by default follow/mirror any coordinate system change defined for the visual mesh 

**Actual behavior**
The assets are not aligned and not uniformly scaled and no mechanism is provided to address this issue during asset import. 
The user must manually align the assets each time they are added to the scene.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/3898904/185094398-fe4aced5-3b1b-444b-96fd-82dd6efaa6bd.png)

![image](https://user-images.githubusercontent.com/3898904/185096345-2badaa64-3f65-4edf-b17e-18d5fe027653.png)

**Found in Branch**
development @ cc6c0964babf3ff5a7d5eed93c1b19852c100012

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04
 - CPU: Intel I9
 - GPU: RTX 3080 Mobile
 - Memory: 32 GB RAM, 16GB VRAM

**Additional context**
While the provided asset is in `FBX` format, this behavior is consistent across asset formats (tested with `.glb`)

**Comment by lgleim** [comment]
The second screenshot apparently also exhibits the incorrect scaling behavior tracked in https://github.com/o3de/o3de/issues/6283

**Comment by lgleim** [comment]
Potentially related to https://github.com/o3de/o3de/issues/2426 https://github.com/o3de/o3de/issues/5981 https://github.com/o3de/o3de/issues/5987

**Comment by lgleim** [comment]
After discussing in today's issue triage:
* A `coordinate system change` modifier should be added to the PhysX tab (temporary workaround)
* Further discussion about the overall asset import pipelines is needed and how the UX can be improved
* Consider the coordinate system change to be a global setting per FBX (import asset) instead of per "output" group

**Comment by rainbj** [comment]
@HogJonny-AMZN and @shawstar is this something your DCCsi tool could help with? It sounds like this is not a UX specific bug, but a bug that happens during the import process. Let Sig-UI-UX know if there is something we can do to help.
