### ISSUE TITLE
[SMC] Custom Shader Variant List Generation

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#11383]
**Is your feature request related to a problem? Please describe.**
It is hard to predict how game teams will need to generate a shader variant list for a particular shader. Even though Shader Management Console (SMC) can provide a best-effort material scan (https://github.com/o3de/o3de/issues/11380), there will likely be custom shaders or unique game-specific situations that require some other process.

**Describe the solution you'd like**
Users should be able to duplicate the original material scan script (https://github.com/o3de/o3de/blob/development/Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListForMaterials.py) and customize it, or create an entirely new script with some other procedure for generating the shader variant list for a .shader file. This script should be easily accessible from SMC.

As described in https://github.com/o3de/o3de/issues/11380 there is a set of Shader Actions that show up in the context menu for a .shader file, as well as in a dialog prompt when opening a .shader file. One of these Shader Actions should be something like "Run Python on Shader..." which can run any python script with the shader file as an input. The user can then select their custom script (or they could even select the original GenerateShaderVariantListForMaterials.py script).

Additionally, the user should be able to register their script so that it shows up as a dedicated Shader Action. This will be useful on projects where a custom script becomes a central part of the team's workflow, and should be readily accessible without having to navigate to find a particular python script. This can be done with a simple registry setting somewhere in the user's project. Use a key like "/O3DE/Atom/ShaderManagementConsole/ShaderActionScripts", and the value is map of action name to python script path.

In the screenshot here, "Default Material Scan..." is built in, and runs GenerateShaderVariantListForMaterials.py, while "My Custom Material Scan..." comes from the settings registry and links to a custom python script.

**Open Shader Dialog Prompt**
![image](https://user-images.githubusercontent.com/55155825/185490013-c60f5595-79d7-4a69-8a75-2509530931ba.png)

**Context Menu**
![image](https://user-images.githubusercontent.com/55155825/185485217-3a0e761f-67c5-4388-a29d-f2c480aab505.png)

**Describe alternatives you've considered**
Instead of explicitly registering the python scripts using a registry key, we could use a custom extension like ".shaderaction.py" similar to how Material Editor searches for preview models and lighting presets. But I don't think there will be that many custom shader action scripts so I think the setreg approach is simpler in this case.

The exact design of the UI could change, especially based on feedback from @o3de/sig-ui-ux 

**Additional context**

**Comment by etherealchain** [comment]
Most requirements are completed in #11602

**Comment by santorac** [comment]
I think there is one problem with the current implementation that needs to be fixed. Because the registry setting uses a map, you can only have one script per folder. See https://github.com/o3de/o3de/blob/19056977eb1a0f8260afe2c4c733e9bb90337ec6/Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp#L640

The current script GenerateShaderVariantListForMaterials.py uses key "" and no other script can use the same key. Since the key is interpreted as a folder name, you end up having to put every script in a different folder. So instead of a map, I suggest using a list, where each entry has a file path for the script and an optional folder name. Then multiple entries can use the same folder name.

**Comment by etherealchain** [comment]
The key "" is not really a folder name, more like a category, if you add something like this in `ProjectRoot\user\Registry\usersettings.shadermanagementconsole.setreg`
```
"O3DE": {
        "AtomToolsFramework": {
            "AssetBrowser": {
                "ContextMenuScripts": {
                    "": [ "@gemroot:ShaderManagementConsole@/Scripts/GenerateShaderVariantListForMaterials.py"],
                    "123": ["@PROJECTROOT@/TestScript.py"]
                }
            }
        }
    }
```
TestScript.py is under project root
You will see the script in the sub-menu
![image](https://user-images.githubusercontent.com/4178768/199451695-c7d3c202-2c3f-4e3a-a9f9-1635ba8e1c43.png)

Also you can put the script in the non-category array like this
```
"O3DE": {
        "AtomToolsFramework": {
            "AssetBrowser": {
                "ContextMenuScripts": {
                    "": [ 
                            "@gemroot:ShaderManagementConsole@/Scripts/GenerateShaderVariantListForMaterials.py",
                            "@PROJECTROOT@/TestScript.py"
                         ]
                }
            }
        }
    }
```
TestScript.py will be listed with GenerateShaderVariantListForMaterials.py
![image](https://user-images.githubusercontent.com/4178768/199459462-1865b44c-5424-4635-b170-acee6adc3e9f.png)

TestScript.py can be put in the same folder as GenerateShaderVariantListForMaterials.py, or any folder under @gemroot:...@ or @PROJECTROOT@
