### ISSUE TITLE
[SMC] Improve the Shader Variant List File Save Workflow

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#11388]
**Is your feature request related to a problem? Please describe.**
The .shadervariantlist file can only be stored in two specific locations, in order to be found at runtime. It can either be in the same folder as the .shader file, or it can be in a specific path under the user's project folder. However Shader Management Console's (SMC's) current File menu items allow the user to save the file to any location. There is no good way for the average user to know where the file ought to be saved.

**Describe the solution you'd like**
Users can save the .shadervariantlist to either the original .shader location or to their game project folder, in the appropriate required path. If the shader is {SomeGem}/Assets/Ocean/Shaders/ComputeWaves.shader then the shader variant list must be in {MyProject}/ShaderVariants/Ocean/Shaders/ComputeWaves.shadervariantlist.

These are the changes we should make to the File menu:
1. Change Save As to only give the user the two valid options. This can just be a dialog with radio buttons for "Next to the .shader file" and "In the project folder".
1. Remove Save As Child, it doesn't make sense for variant lists.
2. If the file has not been saved before, the Save menu item should show the same dialog as Save As
3. (optional) Provide a third "Custom Location" radio button option that opens a typical Save As dialog where the user can pick their location. This would mostly be used by developers for testing.

**Describe alternatives you've considered**
n/a

**Additional context**
The user should be able to create some data first, and then save it later (or discard it if they want). Normally, an application would prompt the user for a save location when the file is saved the first time, but since the .shadervariantlist is a special circumstance, we expect the user to know where to save the file and have it actually work.

**Comment by etherealchain** [comment]
Update:
The basic workflow is working now

1. Right click .shader file > GenerateShaderVariantListForMaterials.py
2. File > Save as Child
3. A window popup to select saving location ( in project or in engine)
4. File saved successfully
![image](https://user-images.githubusercontent.com/4178768/188085794-ef4be1e4-b8bd-428f-8b82-12b4ee3c13b5.png)

To do:

1. Make sure it worked in all condition (both generated and opened shader variant list)
2. The Save and Save as button is grey out when document is created but not opened.

**Comment by santorac** [comment]
There are a couple issues with the current implementation:
1. Once you click Save or Save As and the dialog is open, there is no way to cancel. If you click the "X" it does "Save to engine". There should be a cancel button, and clicking "X" should cancel as well.
2. Save all produces an error message: 
![image](https://user-images.githubusercontent.com/55155825/193162838-8c2a3534-9ec9-45c7-b5e4-65efa93ff2fb.png)

**Comment by etherealchain** [comment]
I have a PR to resolve issue 1, #12796
For issue 2, should the window pop up one by one for each newly created document? (Newly created document doesn't have a path yet, hence the error message)
If so we may need some new functions in AtomToolsDocumentMainWindow and  AtomToolsDocumentSystem

Also, I notice now when you run GenerateShaderVariantListForMaterials.py (on StandardPBR_ForwardPass.shader, for example), this warning will be report many times
```
==================================================================
python: Trace::Warning
 D:/o3de/Gems/EditorPythonBindings/Code/Source/PythonMarshalComponent.cpp(669): 'bool __cdecl EditorPythonBindings::Container::LoadPythonToPairElement(struct _object *,enum AZ::BehaviorParameter::Traits,const struct AZ::SerializeContext::ClassElement *,class AZ::SerializeContext::IDataContainer *,unsigned __int64,class AZ::SerializeContext *,void *)'
python: Could not convert to pair element type value2 for the pair<>; failed to marshal Python input <class 'str'>
python: ==================================================================
python:
==================================================================
```

and it will create an empty shader variant list (11 variants without any value set)
![image](https://user-images.githubusercontent.com/4178768/197821789-324eaa70-38ad-4f33-ad20-9470af5f9473.png)

**Comment by santorac** [comment]
>should the window pop up one by one for each newly created document?

I would expect it to behave the same way as a typical Save All action, which would open a new browser dialog for each file one at a time. In this case, it would be the Project/Engine dialog instead. And I think the Cancel button should abort the entire Save All operation, not just the current file.

**Comment by santorac** [comment]
I don't know about the warnings. @gadams3 do you know what's going on there?

**Comment by gadams3** [comment]
> I don't know about the warnings. @gadams3 do you know what's going on there?

The document error or the Python warnings?
Do you know what variable the Python marshaling is failing on? If it is just up here, it might be something that is not fully reflected or you have to call RegisterGenericType for on the serialize context.
There should be virtual functions on the application main window that you can override for your own file open and save dialogs.
Save all with normally save to a pre established path. But if it is a new document That was not previously saved it should open a save dialog. It's been a few weeks but I'm pretty sure I made changes to support that along with the changes for specifying a custom open and save dialog.

**Comment by etherealchain** [comment]
The warning is printed here in GenerateShaderVariantListForMaterials.py
```
if len(options) != 0:
    # variantInfo.options = options        <- Line 114
    shaderVariants.append(variantInfo)
    stableId += 1
```
`options` is an AZStd::unordered_map<Name/*optionName*/, Name/*valueName*/>

To reproduce:

1. Run ShaderManagementConsole
2. Right-click on StandardPBR_ForwardPass.shader, select GenerateShaderVariantListForMaterials.py
3. Observe the warning 
4. Comment out line 114 and run GenerateShaderVariantListForMaterials.py again, no warning this time

In both cases, the output list will be empty.

**Comment by gadams3** [comment]
> AZStd::unordered_map<Name/*optionName*/, Name/*valueName*/>
Use RegisterGenericType to add the pair and map to the serialize context in the reflect function for whichever class has the map. You should be able to search for other examples where containers need to be registered like that. Try that and let me know if there is still a problem.

**Comment by etherealchain** [comment]
I tried as follow, but nothing changed, I will keep testing.
```
void ShaderVariantListSourceData::Reflect(ReflectContext* context)
{
    if (auto serializeContext = azrtti_cast<SerializeContext*>(context))
    {
        serializeContext->RegisterGenericType<ShaderOptionValuesSourceData>();
        ...
    }
}

```

**Comment by etherealchain** [comment]
All issues had been resolved, we can close this one.
