### ISSUE TITLE
Material editor failing to launch on some game projects because of editor mode feature processor access violation

### ISSUE THREAD

**Issue by rainbj** [o3de/o3de#11382]
**Describe the bug**
After a recent build on development.  Sometime in the first two weeks of August, the Material Editor stopped launching for projects after pulling latest on the development branch. This error happens to any project that live outside the main O3DE build folder on my local C drive. If I build AutomatedTesting (that lives inside the main build engine folder) it works fine and launches with no errors.  

Things we have tried so far:

- Pulling latest and rebuilding - no change
- Pulling the logs. No errors reported in the logs
- Clearing O3DE build and cache folders and rebuilding - no change
- Clearing project build and cache folders and rebuilding - no change
- Removing asset from the projects - No change. 
- Building automated testing project to test if it's related to project - Material editor launches

![2022-08-18_12-58-56](https://user-images.githubusercontent.com/82551958/185484134-39511121-d38d-4222-b1a2-a877d014beab.png)

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Open the editor
2. Click on 'Material editor' button in the main toolbar
3. Scroll down to console and watch it stick and not move.
5. See no errors, no launching of 

**Expected behavior**
I expect that the material editor opens

**Actual behavior**
It does nothing and sit there.

**Found in Branch**
Development - Aug (15th)

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC,] 
 - OS: [e.g. Windows, ]
 - Version [e.g. 10, Monterey, Oreo]
 - CPU [ Intel I9-9900k , ]
 - GPU [NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**
Please note that I have sent my project to Guthrie already. This ticket is to help track this work.

**Comment by gadams3** [comment]
Fixed posted for review and development. https://github.com/o3de/o3de/pull/11676
