### ISSUE TITLE
ScriptCanvas node width flicker during hover

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#11398]
**Describe the bug**
Nodes in ScriptCanvas can have their width flicker during mouse hover, which can make it extremely difficult to connect nodes.

The Windows machine this reproduced on had OS-level DPI scaling enabled, which is most likely the cause.

**Assets required**
n/a

**Steps to reproduce**
1. Open the Windows Settings menu and navigate to 'System > Display'
2. Set the drop down box under 'Scale and Layout' to 200%
3. Apply settings and restart the machine
4. Launch the O3DE Editor and open ScriptCanvas
5. Add multiple nodes to a canvas, and attempt to attach their ports together

**Expected behavior**
Node dimensions do not change.

**Actual behavior**
Intermittent flickering of dimensions occurs during mouse hover, causing user interaction with ports to fail.

**Screenshots/Video**
Video can be provided upon request.

**Found in Branch**
Development @ 08c19df92e943388a308fadfb4e7e86a474527a0

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 3970X
 - GPU NVidia RTX 3080
 - Memory 32GB

**Additional context**
Reproduced over remote desktop as well as in person.

**Comment by lsemp3d** [comment]
This is fixed in PR  #10952
