### ISSUE TITLE
Deleting an entity does not close its context menu

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#11411]
**Describe the bug**
If a context menu is opened on an entity, and that entity is deleted using the Delete key, the context menu remains opened. This can lead to unintended behavior, and potentially crashing (for example, as shown on the video, attempting to detach a prefab on a deleted prefab causes the Editor to freeze, and crash).

Please note that the crash shown on the video only occurs on Windows.

**Steps to reproduce**
1. Create an entity.
2. Right-click the created entity.
3. Press the Delete key.

**Expected behavior**
The context menu closes.

**Actual behavior**
Context menu remains open, and can be interacted with.

**Video**

https://user-images.githubusercontent.com/86952082/185622202-fef4e72e-8804-4e3c-afdb-a5d2fcd811cc.mp4

**Found in Branch**
Development (e876c36)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by rainbj** [comment]
Reviewed issue. We (sig-ui-ux team) agree with needing to fix this

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as Fixed on the latest Development (a912a04) branch.
