### ISSUE TITLE
[Pre Release] Ensure version number updates to CMake parameters are complete

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#11422]
Ensure the Build SIG updates CMake parameters with the new version number.

- Successor task: [Pre Release] Ensure installers are tested 

Discord: [#sig-build](https://discord.com/channels/805939474655346758/816043576034328636)
Build SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Build SIG meeting agendas: [GHI](https://github.com/o3de/sig-build/issues)

**Comment by brianherrera** [comment]
Confirming parameters were updated:
```
O3DE_VERSION = 22.11.0
O3DE_BUILD_VERSION = 2211.0
```
