### ISSUE TITLE
[Pre Release] Ensure final release notes are documented, and a PR is created

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#11428]
Ensure the Release SIG documents the final customer-facing release notes in preparation for release (using the draft release contents as input), and creates a PR to have the release notes merged on launch day.

We also need to update https://www.o3de.org/docs/release-notes/archive/22-05-0/feature-state/

Replace the [PR] placeholder in the below successor task with the correct information for this release.
- Successor Task: #11096 

- Predecessor Task: release contents drafted

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by tonybalandiuk** [comment]
release notes from Physics that should be added:
The way physics material assets are stored and used have been completely updated. The physics material library asset has been removed and we now support individual physics material assets, much like render materials and other assets in O3DE. This makes working with physics materials much easier and more consistent.

What actions will I need to take?
If you work with AutomatedTesting, atom-sampleviewer, multiplatyersample or netsoaktest, you don't need to do anything, all physics material assets will be converted already.

For any other project, one person will need to convert assets following these steps:
  1. Run Editor. Do not open any level, just close the "Welcome to O3DE" screen.
  2. Wait until Asset Processor has finished processing all the assets
  3. Open Console: Tools > Console
  4. Enter the following console command to convert old physics material libraries: "ed_physxConvertMaterialLibrariesIntoIndividualMaterials"
  5. Wait until Asset Processor has finished processing all the assets
6. Enter the following console command to fix prefabs and fbx manifests that reference old assets: "ed_physxFixAssetsUsingPhysicsLegacyMaterials"
7. Wait until Asset Processor has finished processing all the assets
8. Commit the source assets changes into Github.

**Comment by chanmosq** [comment]
The above feature note about physics is in Features section, and added the workaround steps to Known Issues section.

**Comment by amzn-changml** [comment]
As discussed in the sig-release meeting, another known issue:

#### Linux editor splash screen shows "Development build" instead of release, if both release and development are installed: https://github.com/o3de/o3de/issues/9519

**Comment by chanmosq** [comment]
Got it!
