### ISSUE TITLE
[Pre Release] Ensure installers are uploaded to S3

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#11424]
Ensure the Build SIG uploads the installers for Windows and Linux  to the below S3 buckets:

Windows s3://o3de-prism-prod-us-west-2/main/Latest/Windows/

Linux s3://o3de-prism-prod-us-west-2/main/Latest/Linux/

- Predecessor task: ensure installers tested

Discord: [#sig-build](https://discord.com/channels/805939474655346758/816043576034328636)
Build SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Build SIG meeting agendas: [GHI](https://github.com/o3de/sig-build/issues)

**Comment by brianherrera** [comment]
Installers uploaded to staging bucket. Pending copy over to s3://o3de-prism-prod-us-west-2/main/Latest/

**Comment by brianherrera** [comment]
Confirming installers uploaded to S3

- Linux: https://o3debinaries.org/main/Latest/Linux/o3de_2210_0.deb
- Windows: https://o3debinaries.org/main/Latest/Windows/o3de_installer_2210_0.exe

Website will be updated tomorrow.
