### ISSUE TITLE
[Pre Release] Total image area exceeds maximum alotted area is 16777216

### ISSUE THREAD

**Issue by renmingbao** [o3de/o3de#11439]
**Describe the bug**
When I edit the .texatlas file, the total resolution of the images in the same format exceeds 4096 x 4096, that is, 16777216.
When I save the texatlas file, the compilation fails.
The error message "Total image area exceeds maximum alotted area. 71303168 > 16777216" is displayed.

**Steps to reproduce**
1. Open the editor.
2. Edit the .texatlas file, add the existing picture to the file, and save the file.
3. Check the compilation of the .texatlas file on the AP.
4. The compilation fails, and the error message "Total image area exceeds maximum alotted area. 71303168 > 16777216" is displayed.

**Expected behavior**
I hope to that the engine suports a bigger picture.

**Actual behavior**
Total image area exceeds maximum alotted area is 16777216.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I7-11900k
 - GPU NVidia RTX 3090
 - Memory 64GB

**Additional context**

**Comment by michabr** [comment]
Hi @renmingbao, the max dimension by default is 4096. However, this value is configurable. Please refer to https://docs.o3de.org/docs/user-guide/interactivity/user-interface/canvases/texture-atlases/texture-atlases-creating/ for details on how to override the default.
