### ISSUE TITLE
[RHI] The engine uses quite a lot of VRAM

### ISSUE THREAD

**Issue by CyaNinix** [o3de/o3de#11446]
Hello there, sorry if I step a bit outside of the bug format since this isn't really a bug, it's more about raising awareness of an issue with the way O3DE handle video memory.

# The issue

O3DE D3D12 and Vulkan buffers allocators use a tremendous amount of video memory (VRAM), which prevents us to launch our game of most of our computers.

This is because of multiple issues, first O3DE will allocate a lot of buffers in their own memory block (unique allocations), I've seen a lot of calls to vkAllocateMemory and ID3D12Device::CreateCommittedResource with very little size (~200 bytes), which is problematic with D3D12 because every unique allocation is aligned to `D3D12_DEFAULT_RESOURCE_PLACEMENT_ALIGNMENT` (65335):
```cpp
        BufferMemoryView BufferMemoryAllocator::AllocateUnique(const RHI::BufferDescriptor& bufferDescriptor)
        {
            AZ_PROFILE_FUNCTION(RHI);

            const size_t alignedSize = RHI::AlignUp(bufferDescriptor.m_byteCount, Alignment::CommittedBuffer);
```

When you have several differents meshes and actors, you can easily gets out of memory errors.

On Vulkan you have the very same issue because "Allocations returned by vkAllocateMemory are guaranteed to meet any alignment requirement of the implementation.", but it's even more problematic because the number of unique allocations supported by the API is quite low:
> The maximum number of valid memory allocations that can exist simultaneously within a [VkDevice](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDevice.html) may be restricted by implementation- or platform-dependent limits. The [maxMemoryAllocationCount](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#limits-maxMemoryAllocationCount) feature describes the number of allocations that can exist simultaneously before encountering these internal limits.
(https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkAllocateMemory.html)

[maxMemoryAllocationCount](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#limits-maxMemoryAllocationCount) is guaranteed to be at least [**4096**](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#limits-minmax), and [basically every Vulkan implementation on Windows use this limit](https://vulkan.gpuinfo.org/displaydevicelimit.php?platform=windows&name=maxMemoryAllocationCount), which is a very small number considering the number of unique allocations O3DE tries to make.

The reason O3DE tries to perform so many unique allocations seems to be because of this:

**DX12:**
Gems/Atom/RHI/DX12/Code/Source/RHI/BufferMemoryAllocator.cpp in `BufferMemoryAllocator::Init`
```cpp
...
            // Buffers that can be attachments can independently transition state, which precludes them from
            // being sub-allocated from the same ID3D12Resource.  
            // [GFX-TODO][ATOM-6230] Investigate performance of InputAssembly buffers with the page allocator
            // The page allocator is currently disabled for InputAssembly buffers.
            // Based on performance we may want to enable the page allocator for InputAssembly buffers. In order to do that we will
            // need to make sure they are aligned correctly. There is a restriction on buffer alignment where the alignment
            // needs to be a multiple of elementsize as well as divisible by DX12::Alignment types.
            m_usePageAllocator = false;

            if (!RHI::CheckBitsAny(descriptor.m_bindFlags, RHI::BufferBindFlags::ShaderWrite | RHI::BufferBindFlags::CopyWrite | RHI::BufferBindFlags::InputAssembly | RHI::BufferBindFlags::DynamicInputAssembly))
            {
...
```

**Vulkan:**
Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferPool.cpp in `BufferPool::InitBufferInternal`
```cpp
...
            // Note that InputAssembly, RayTracingAccelerationStructure, and RayTracingShaderBindingTable buffers must be unique allocations.
            // This is necessary since the alignment on a paged memory allocation is not compatible with the required raytracing alignment.
            bool forceUnique = RHI::CheckBitsAny(
                bufferDescriptor.m_bindFlags,
                RHI::BufferBindFlags::InputAssembly |
                RHI::BufferBindFlags::DynamicInputAssembly |
                RHI::BufferBindFlags::RayTracingAccelerationStructure |
                RHI::BufferBindFlags::RayTracingShaderTable);
```

I'm not very familiar with GPU raytracing, but from what I read the alignement requirements are not huge (I found [here](https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html) multiple alignements, with the most restrictive being 256). I see no reason why this wouldn't be compatible with a page allocator (looks a bit like unfinished work).

We're not even using raytacing in our project (yet?) so for now we have to pay a high price for no reason.

After asking someone on Discord a few months ago, I worked on a quick DX12 fix to re-enable page allocator for input buffers:
https://github.com/cyanide-studio/o3de/commit/8650028b183ff858a6917029d5ca8b5683460107

It's a bit hacky but it fixed our out of memory errors and lowered VRAM usage a bit.

As for Vulkan, things were worse, we couldn't even start the game without getting a out of memory error (I'm on a NVidia RTX 2080 Ti with 11GB of VRAM).

I tried to perform a similar fix bug got a lot of driver crash, got tired of it and decided to use [Vulkan Memory Allocator](https://gpuopen.com/vulkan-memory-allocator/) instead of O3DE page allocator.
https://github.com/cyanide-studio/o3de/commit/cd760faaf1e9b0f70c2b529d0489abc733a3247b

With this, the game started and ran fine, and consumes **3 to 4 GB of VRAM less** than what it tries to allocate with O3DE before crashing, this is huge.

I ran a test where I start the editor with DX12/Vulkan and open a scene with quite a lot of meshes and measured GPU VRAM with [HWiNFO](https://www.hwinfo.com).

Here are the results:

### DX12:

1) Before starting the editor: ~2400MB (reference)
2) Editor started: ~2800MB (~400MB of VRAM used)
3) Scene fully loaded: ~8700MB (6300MB of VRAM used)

![DX12_nofix_hwinfo](https://user-images.githubusercontent.com/99494374/185964115-16236402-a8c4-42a2-9f13-36e5e4eca8e7.png)
![DX12_nofix_O3DE](https://user-images.githubusercontent.com/99494374/185964138-b34869f5-9847-4510-8f5c-a941169dcef7.png)

### Vulkan:

1) Before starting the editor: ~2300MB (reference)
2) Editor started: ~2800MB (~500MB of VRAM used)
3) Scene fully loaded: ~8700MB (~5900MB of VRAM used) with a spike at 9900MB

![Vulkan_nofix_hwinfo](https://user-images.githubusercontent.com/99494374/185964728-8f5e3464-5e2e-479b-ad13-221c824a3bb2.png)
![Vulkan_nofix_O3DE](https://user-images.githubusercontent.com/99494374/185964753-246e401d-5fb3-44b6-996c-f74ff5d870c0.png)

### DX12:

1) Before starting the editor: ~2400MB (reference)
2) Editor started: ~2900MB (~500MB of VRAM used)
3) Scene fully loaded: ~8300MB (~5900MB of VRAM used, around 400MB less)

![DX12_dx12fix_hwinfo](https://user-images.githubusercontent.com/99494374/185966305-e15bb4c0-5474-4a0e-9b00-e7ed5184d49a.png)
![DX12_dx12fix_O3DE](https://user-images.githubusercontent.com/99494374/185966316-a7807fe9-6989-43cb-a408-ec2a1be4a511.png)

### Vulkan:
 
1) Before starting the editor: ~2400MB (reference)
2) Editor started: ~2600MB (~200MB of VRAM used, 300MB saved)
3) Scene fully loaded: ~6300MB (3900MB used, this is **2GB less**) with a spike at 7500MB (2.4GB less)

![Vulkan_vkfix_hwinfo](https://user-images.githubusercontent.com/99494374/185966346-44ee4593-f120-4e0f-bce9-907c288c067e.png)
![Vulkan_vkfix_O3DE](https://user-images.githubusercontent.com/99494374/185966363-81fafc99-560c-44b4-91e0-8303f8cfd2a4.png)

In that scene, we don't even have any actor, in the full game we do and we've seen memory usage decrease by numbers as high as **4 to 5GB VRAM** with Vulkan + VMA.

# Conclusions

O3DE doesn't manage the video memory quite right, and it's possible to decrease its VRAM usage **a lot** (assuming that there's no reason D3D12 should consume more memory than Vulkan with VMA).

We are sharing this issue (and our commits) to pinpoint a problem we've been dealing with for months, and which is quite severe as it causes memory issues with even a RTX 2080 Ti.

Of course, our commits are not generic enough (and are way too hacky) to be pushed to the main repository, a real fix probably requires a lot more work.

**Comment by VickyAtAZ** [comment]
@CyaNinix It seems both the VRAM usage of buffers and images are effected by your fix especially on Vulkan. The VRAM used by the textures on Vulkan was reduced for 1.1G after the fix. 
And the level you used for profiling has used a decent amount of the textures. (it reached the memory budget of 4G for dx12) 
The VRAM used by the textures on Vulkan was reduced for 1.1G after the fix. 
I am currently working on the texture memory allocation and streaming and memory usage of StreamingImagePool is something I am keeping a close eye on. The change for DX12 has been submitted to development branch. And the change to have better streaming control is on the way. After that, I will work on the memory allocation for texture on Vulkan. I will definitely get a better idea on the textures' memory allocation and see if I can address the memory problem you found with texture allocation on Vulkan.  

The buffer allocation on Vulkan seems to be a bigger issue since the memory usage appear to be reduced by 1G after your change. We may want to discuss in sig-graphics meeting to rise the priority to address the issue.

**Comment by AMZN-alexpete** [comment]
@CyaNinix thank you for posting this excellent data on VRAM usage at scale!  Definitely something we want to address (as indicated by the critical priority).  Please continue to post your issues/feedback as you discover them!

**Comment by moudgils** [comment]
FYI - We did have plans to replace O3de's allocator with the following allocators for DX12 and Vk as they support TLSF
DX12MA  - https://gpuopen.com/d3d12-memory-allocator/
Vulkan VMA  - https://gpuopen.com/vulkan-memory-allocator/
but it is not on our immediate roadmap. This work will need some sort of a tech doc to indicate how these allocators will be used and which resources will they impact.

**Comment by moudgils** [comment]
We are also going to focus on the following Buffer changes (https://github.com/o3de/sig-graphics-audio/discussions/58) relatively soon. We are hoping this will allow IA buffers to use paging as oppose to using unique committed allocation which is bloating your memory pools.

**Comment by rgba16f** [comment]
One additional point is that vertex welding/deduplication was broken in the asset pipeline in Dec 2021. That has recently been fixed and we are now seeing memory usage come on geometry come down.

**Comment by Jackie9527** [comment]
#14547 maybe a relief for vulkan.

**Comment by moudgils** [comment]
There is also an RFC to move to VMA which will address this issue. - https://github.com/o3de/sig-graphics-audio/issues/121

**Comment by moudgils** [comment]
VMA and DX12MA has been added to the engine. Can this ticket be closed? Tagging @CyaNinix

**Comment by CyaNinix** [comment]
Sure, I think it can be closed now, thanks for addressing this.
