### ISSUE TITLE
Bug Report: The location of mesh and bones sometimes is incorrect when importing some fbx models

### ISSUE THREAD

**Issue by MoMoPF** [o3de/o3de#11472]
**Describe the bug**
The location of mesh and bones sometimes are incorrect when importing some fbx models. 

**Assets required**
Please see the fbx model in the end.

**Steps to reproduce**
1. Add the .fbx in the .zip attachment to the fold where the engine can scan.
2. Import this TRM_SKIN_A.fbx to a Actor component
3. Open the Animation Editor from the Actor component in STEP 2.
4. See error that the location of mesh and bones are incorrect.

**Expected behavior**
The bones should fit the mesh.

**Actual behavior**
The bones are out from the mesh.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/49116245/186122869-e4c64ef9-a834-4740-850d-53817b39c5cc.png)

**Found in Branch**
[main branch](https://github.com/o3de/o3de/tree/main)

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [20.04]
 - CPU [Intel(R) Xeon(R) W-2245]
 - GPU [NVidia RTX 4000]
 - Memory [64GB]

**Additional context**
This is the fbx. And this fbx may have some parent nodes without any mesh or bone.
[TRM_SKIN_A.zip](https://github.com/o3de/o3de/files/9401217/TRM_SKIN_A.zip)

**Comment by lmbr-pip** [comment]
This has been fixed in development already, trying to track down commit #

**Comment by MoMoPF** [comment]
> This has been fixed in development already, trying to track down commit #

Yes! This has been fiexed in development in [#9678](https://github.com/o3de/o3de/pull/9678). Thanks!

**Comment by MoMoPF** [comment]
> What branch are you on? Which commit hash on that branch? The attached FBX file loads and renders correctly for me, the bones are in the right places, at commit [14c366c](https://github.com/o3de/o3de/commit/14c366cabc906ac1367492c457959333c2eaafc5) (HEAD, upstream/development)
> 
> ![image](https://user-images.githubusercontent.com/4838196/186204033-f9911800-06fd-483d-bf07-77aa4282c5ce.png)

Yes! This has been fiexed in development in [#9678](https://github.com/o3de/o3de/pull/9678). Thanks!
