### ISSUE TITLE
New Script Canvas graphs fail to save after closing Script Canvas tool

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#11479]
**Describe the bug**
The newly created **Script Canvas** graphs fail to save after closing the **Script Canvas** tool by clicking X in the top right corner and clicking the "Save" in the popup. The following message is displayed instead: "Failed to save : Failure to create temporary file name".

Note that this issue does not reproduce when closing the **tab** of newly created graph.

**Steps to reproduce**

1. Open **Script Canvas** tool.
2. Create a new graph.
3. Close the **Script Canvas** tool by clicking X in the top right corner.
4. Click "Save" in the popup.

**Expected behavior**
Newly created **Script Canvas** graphs save after closing the **Script Canvas** tool and clicking "Save" in the popup.

**Actual behavior**
Newly created **Script Canvas** graphs fail to save after closing the **Script Canvas** tool and clicking "Save" in the popup.

**Video**

https://user-images.githubusercontent.com/86951967/186167039-d3f38514-2886-41b0-a156-f651164c6427.mp4

**Found in Branch**
Development (1ee9f0b)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by LB-JakubSkorupka** [comment]
Note - This issue also reproduced on Windows Pre-built SDK engine.

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed in Development (3f3f133).
