### ISSUE TITLE
Prefabs: Level Prefab is still reported as dirty after saving newly added entity changes

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11489]
**Describe the bug**
 Level Prefab is still reported as dirty after saving newly added entity changes.

Edit > Editor Settings > Global Preferences > General Settings > Prefab Save Settings > Save All Nested Prefabs

**Steps to reproduce**
1. Launch the Editor.
2. Change the Editor Global Preference for Save All Nested Prefabs to "Ask every time" 
3. Create a new level.
4. File > Save the level.
5. Add a new entity with any component.
6. File > Save the level.
7. Observe the Level prefab's dirty state.
8. File > Open the same level and discard the reported prefab changes when prompted.
9. Observe the entities in the level.

**Expected behavior**
All changes are saved and level prefab dirty state is properly reported.

**Actual behavior**
When changes are saved, level prefab reports it is still dirty, even though all the changes appear to have saved properly.

**Screenshots/Video**
https://user-images.githubusercontent.com/82226555/186223699-0ff1d7b9-8b66-4e88-8249-e347dfe56f3f.mp4

**Found in Branch**
development@ dc576766a459cda94b083a84ea018197f9d13ffb

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by forkercat** [comment]
Related to #11452

**Comment by monroegm** [comment]
@jckand-amzn Can you see if this still reproduces following the above fix?

**Comment by jckand-amzn** [comment]
Verified fix on development@ 1a35cb8c57ba3ddf80410ade4aaa0a696289a63b.
