### ISSUE TITLE
Long names of Gems are not fully displayed

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#11519]
**Describe the bug**
Names of Gems with with 20 or more characters are not fully displayed, no matter the size of the Project Manager window.

**Steps to reproduce**
1. Open Asset Processor.
2. Navigate to Gems.
3. Verify the Gems with long names.

**Expected behavior**
 User is able to read full names of all Gems.

**Actual behavior**
 User is unable to read the full name of long named Gems.

**Screenshots/Video**

![Gems](https://user-images.githubusercontent.com/86951905/186409287-df816be6-a7e7-49a4-9c74-43997aa383c1.png)

**Found in Branch**
 Development (e1a0472)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 3600
 - GPU Nvidia GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-RostyslavGavryliuk** [comment]
This issue may be a duplicate of #5516

**Comment by tkothadev** [comment]
As of PR https://github.com/o3de/o3de/pull/13106, this should be fixed(this fix was implemented before the PR however):




![](https://user-images.githubusercontent.com/112996779/201162530-ce9b059f-b486-4a6f-a478-efe4a2432406.gif)
