### ISSUE TITLE
"Save as..." window opens instead of saving Script Canvas graph on closing Script Canvas tool

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#11547]
**Describe the bug**
When a **Script Canvas** tool is closed with a modified graph opened, that has been previously created and saved within the same session, the popup "Save Script Canvas Changes?" appears. After pressing "Save", a "Save as..." window appears instead of the graph being saved. 

This issue will not occur if **Script Canvas** tool is closed and reopened after creating and saving a graph for the **first** time.

This issue occurs on both Windows and Linux OS's.

**Steps to reproduce**

1. Open Script Canvas tool.
2. Create a new graph.
3. Add any node to the graph.
4. Save the graph by File -> Save / Save as...
5. Make any change to the graph (e. g. Move the node, add another node).
6. Click X in top right corner of Script Canvas window.
7. In "Save Script Canvas Changes?" popup select "Save".

**Expected behavior**
Closing the **Script Canvas** tool with modified graph that was created and saved earlier results in saving that script after clicking "Save" in "Save Script Canvas Changes?" popup.

**Actual behavior**
Closing the **Script Canvas** tool with modified graph that was created and saved earlier results in displaying "Save As.." window instead of saving that script after clicking "Save" in "Save Script Canvas Changes?" popup.

**Video**

https://user-images.githubusercontent.com/86951967/186663467-6392596c-1f02-4597-926d-fd42601710ba.mp4

**Found in Branch**
Development (3f3f133)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by LB-JaroslawGaweda** [comment]
Verified as fixed in Stabilization (021d32a) and development (511a88c) branches.
