### ISSUE TITLE
【Bug Report】 UI Canvas Chinese characters cannot be displayed correctly

### ISSUE THREAD

**Issue by zhangbaochong** [o3de/o3de#11543]
**Describe the bug**
Use font which support Chinese，But in UI Canvas, Chinese characters still cannot be displayed correctly.

**Assets required**
use this font: 

[fangzheng.zip](https://github.com/o3de/o3de/files/9423425/fangzheng.zip)

**Steps to reproduce**
1. open the UI Editor
2. create UI Canvas
3. Add Text component and use font that support Chinese
4. Input the test string ‘Start测试环境你好哈哈不是中文字体显示不正确End’
5. See error

**Expected behavior**
chinese character can be displayed correctly

**Actual behavior**
Some character display ok, but most character was wrong

**Screenshots/Video**
Test string: Start测试环境你好哈哈不是中文字体显示不正确End
![uiCanvasChinese](https://user-images.githubusercontent.com/16303584/186628083-e94eac8a-7858-4a7c-a3f8-a94ec263100f.PNG)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: [ PC] 
 - OS: [Windows]
 - Version [10]

**Additional context**

**Comment by zhangbaochong** [comment]
In addition to the corresponding characters of ASCII code, other characters (Chinese, Japanese, etc.) cannot be found and displayed because the font image cache cannot be updated. There may be a problem with the character picture cache update method.

**Comment by zhangbaochong** [comment]
To avoid this issue:  when  text is added, we can use the character picture cache initialization method directly instead of updating and searching in the original font picture cache.  In 'Gems\AtomLyIntegration\AtomFont\Code\Source\FFont.cpp' 'DrawStringUInternal' function, change the code `if (fxSize && !m_fontImage && !InitTexture())` to `if (fxSize && !InitTexture())` can avoid this issue. But it is not the final plan, The real issueis why non-ascii characters(Chinese,Japanese etc.) cannot be updated in the character picture cache.

**Comment by JJJoker** [comment]
Very useful

**Comment by JJJoker** [comment]
Very useful ,but the code location is not in 'DrawStringUInternal' function,it's in 'WriteTextQuadsToBuffers' function.Change the code  in 'Gems\AtomLyIntegration\AtomFont\Code\Source\FFont.cpp' 'DrawStringUInternal' function do not work.

**Comment by zhangbaochong** [comment]
> Very useful ,but the code location is not in 'DrawStringUInternal' function,it's in 'WriteTextQuadsToBuffers' function.Change the code in 'Gems\AtomLyIntegration\AtomFont\Code\Source\FFont.cpp' 'DrawStringUInternal' function do not work.

oh，Yes, its in 'WriteTextQuadsToBuffers' function,
