### ISSUE TITLE
Script Canvas: Pressing Esc while running the Debugger results in a crash

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#11584]
**Describe the bug**
After pressing Esc while running the Debugger, Editor silently crashes. The issue is also active on Linux.
For more detailed information, please refer to the attached video, logs and crash dmp.
Additionally, the issue might be related with: https://github.com/o3de/o3de/issues/2583 .

**Steps to reproduce**
1. Create or open a level.
2. Go to Tools > Script Canvas.
3. In the Script Canvas go to Tools > Debugging.
4. In the Debugging tool press the Caption button and then Esc.

**Expected behavior**
Pressing Esc while running the Debugger exits the debugging.

**Actual behavior**
Pressing Esc while running the Debugger results in a crash.

**Video**

https://user-images.githubusercontent.com/100559077/186887790-5fa0945a-a149-419f-8917-779a39d67200.mp4

**Attached Files**

[Editor.log](https://github.com/o3de/o3de/files/9432457/Editor.log)
[error.log](https://github.com/o3de/o3de/files/9432459/error.log)
[error1.zip](https://github.com/o3de/o3de/files/9432468/error1.zip)
[error2.zip](https://github.com/o3de/o3de/files/9432476/error2.zip)

**Found in Branch**
Development (851c98d)

**Desktop:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Comment by LB-TomaszSerwanski** [comment]
Verified that the issue does not occur on the latest Development (780d8fc), however it is still active in Stabilization/2210 (38005c3).
