### ISSUE TITLE
Meshlets Gem Fails to Build

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#11604]
**Describe the bug**
I tried hooking up the Meshlets gem to AtomSampleViewer according to the readme instructions (https://github.com/o3de/o3de/blob/development/Gems/Meshlets/ASV_GPU_and_CPU_Demo/Readme.txt). I was not able to get the project to build. First there were unresolved include files, which I was able to fix locally. Then it failed to link, meshoptimizer symbols were missing. I gave up because fixing this is outside the scope of my current tasking.

**Assets required**
You need the AtomSampleViewer project https://github.com/o3de/o3de-atom-sampleviewer 

**Steps to reproduce**
1. Follow the instructions in https://github.com/o3de/o3de/blob/development/Gems/Meshlets/ASV_GPU_and_CPU_Demo/Readme.txt
2. Build AtomSampleViewer.
3. It fails to compile because MeshletsAssets.h and MeshletsRenderObject.h cannot be found
4. Edit AtomSampleViewer/Gem/Code/CMakeLists.txt to add the Meshlets gem to the build dependencies, like this:
    ```
            ly_add_target(
                NAME AtomSampleViewer.Private.Static STATIC
                ...
                BUILD_DEPENDENCIES
                    PUBLIC
                        Gem::Meshlets
    ```
5. Build AtomSampleViewer again.
6. Get link failures like: 
    ````
    LNK2019 unresolved external symbol meshopt_buildMeshlets referenced in function "protected: unsigned int __cdecl AZ::Meshlets::MeshletsRenderObject::CreateMeshlets(struct AZ::Meshlets::GeneratorMesh &)" (?CreateMeshlets@MeshletsRenderObject@Meshlets@AZ@@IEAAIAEAUGeneratorMesh@23@@Z)	D:\o3de\build\External\Meshlets-938daa6b\Code\Meshlets.Static.lib(unity_0_cxx.obj)	Meshlets (Gems\Meshlets\Code\Meshlets)	1	
    ````

**Expected behavior**
AtomSampleViewer should be able to build with the Meshlets sample included, by following the instructions in the readme.txt.

**Actual behavior**
The code does not compile or link.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
 - GPU RTX 2080 Super MaxQ
 - Memory 32.0 GB (31.7 GB usable)

**Additional context**

**Comment by adiblev** [comment]
Ping for Adi - I tested it about two weeks ago following the footsteps and it worked for me.  The lib cannot be provided due to O3DE restrictions (since it's a single platform binary library and should not be checked) but the branch should contain it for anyone that want to try. Chris can ping me and I'll guide him through and if required upgrade the steps to make sure it is built with less hustle
