### ISSUE TITLE
Projects cannot be built on Windows 11 with Visual Studio 2022

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#11615]
**Describe the bug**
Projects cannot be built on Windows 11 with Visual Studio 2022 with neither Windows 10 SDK, Windows 11 SDK nor both SDKs enabled at the same time.

It should be noted that on Windows 10, the Visual Studio 2022 allowed for the projects to be built.

Please refer to the **Relevant logs** section for more information.

**Prerequisites**
* Windows 11 with Visual Studio 2022 setup (https://visualstudio.microsoft.com/downloads/ this link was used, and a Professional trial version was used in testing), make sure that both Windows 11, and 10 SDKs are installed (for example Windows 11 SDK (10.0.22621.0), and Windows 10 SDK (10.0.20348.0)).

**Steps to reproduce**
1. Follow a https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/ guide, and setup for example a Pre-built SDK engine.
2. Launch the Project Manager, and build a Default Template project.

**Expected behavior**
Project is built.

**Actual behavior**
Project fails to start building. Compiler is listed as "unknown" in the .logs.

**Relevant logs**
Original setup ([VS2019Win1011SDK.log](https://github.com/o3de/o3de/files/9443651/VS2019Win1011SDK.log)):
* Visual Studio 2019 16.11.18
   * Windows 11 SDK (10.0.22000.0)
   * Windows 10 SDK (10.0.19041.0)
   * Windows 10 SDK (10.0.18362.0)
   * Outcome: Default project built via Project Manager, launched, assets processed, and level was created/modified.

Both VS at once setup ([VS20192022Win1011SDK.log](https://github.com/o3de/o3de/files/9443664/VS20192022Win1011SDK.log)):
* Visual Studio 2019 16.11.18
   * Windows 11 SDK (10.0.22000.0)
   * Windows 10 SDK (10.0.19041.0)
   * Windows 10 SDK (10.0.18362.0)
* Visual Studio 2022 17.3.2
   * Windows 11 SDK (10.0.22621.0)
   * Windows 10 SDK (10.0.20348.0)
   * Outcome: Default project built via Project Manager, launched, assets processed, and level was created/modified.

Visual Studio 2022 both SDK ([VS2022Win1011SDK.log](https://github.com/o3de/o3de/files/9443671/VS2022Win1011SDK.log)):
* Visual Studio 2022 17.3.2
   * Windows 11 SDK (10.0.22621.0)
   * Windows 10 SDK (10.0.20348.0)
   * Outcome: Default project fails to start building via Project Manager.

Visual Studio 2022 Windows 11 SDK ([VS2022Win11SDK.log](https://github.com/o3de/o3de/files/9443676/VS2022Win11SDK.log)):
* Visual Studio 2022 17.3.2
   * Windows 11 SDK (10.0.22621.0)
   * Outcome: Default project fails to start building via Project Manager.

Visual Studio 2022 Windows 10 SDK ([VS2022Win10SDK.log](https://github.com/o3de/o3de/files/9443685/VS2022Win10SDK.log)):
* Visual Studio 2022 17.3.2
   * Windows 10 SDK (10.0.20348.0)
   * Outcome: Default project fails to start building via Project Manager.

**Found in Branch**
Development (9abaadb)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by Ulrick28** [comment]
Reading through the instructions, they assume you have VS 2019 installed. We need to update these docs to also account for VS 2022.

**Comment by amzn-changml** [comment]
@LB-ArturZieba Can we get the version of CMake you're using? If it is not 3.24+, can you verify that this still occurs with the latest non-RC version of CMake?

**Comment by LB-ArturZieba** [comment]
I have reverified this on the Development (394f780) build, after updating the CMake to 3.24.1 version (previously 3.20.5), and the projects were built, processed, and launched without issues. I have built an additional project to verify the used Visual Studio, and it indeed used Visual Studio 17 2022 as can be seen in this log: [CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/9451595/CMakeProjectBuildError.log). I believe that in this case, the documentation regarding O3DE System requirements (https://www.o3de.org/docs/welcome-guide/requirements/) should be updated with the information mentioning potential VS2022 17.3.2 support, when paired with CMake 3.24.1 on Windows 11.

As for the Visual Studio workloads here are the relevant screenshots:
![VS22Workloads0](https://user-images.githubusercontent.com/86952082/187401274-4c44ed9c-3874-4dd9-8b08-f59c3e208050.png)
![VS22Workloads1](https://user-images.githubusercontent.com/86952082/187401278-d02c7589-05ba-4482-80b7-c1c20de7c65e.png)
![VS22Workloads2](https://user-images.githubusercontent.com/86952082/187401281-cb6fcf23-131b-4869-a37e-5e06eb1e38f0.png)

**Comment by amzn-changml** [comment]
Thanks! There is indeed a ticket to add documentation for the minimum requirements for VS2022: https://github.com/o3de/o3de.org/issues/1933

Can you also test this with CMake 3.21? That version that introduced VS2022 support. Also, does this issue occur in Windows 10?

**Comment by LB-ArturZieba** [comment]
When tested originally on Windows 10 on other machine, there were no issues with Visual Studio 2022. I've asked for the CMake version on that PC, and it is 3.22.3. I will post another comment after checking CMake 3.21 on my end.

**Comment by LB-ArturZieba** [comment]
I have verified the project building on CMake 3.21 as requested (Development (394f780) build), and I have found out that on 3.21.0 (non-RC) the build fails, however on the latest CMake 3.21 release (3.21.7) the build goes through without issue.

**Comment by amzn-changml** [comment]
Ok, I'll update the doc PR to include that version. I think we can close this as a documentation, rather than a code issue, as it is not a blocker for release.
