### ISSUE TITLE
Camera: Active camera can change unexpectedly and without user input

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11618]
**Describe the bug**
Active camera can change unexpectedly and without user input. This has only been reproduced in a single level in the QA Test Project, Ceres_2022.

**Assets required**
Must pull down, build, and process assets for the QA Test Project: https://github.com/aws-lumberyard/o3de-qa-test-project

**Steps to reproduce**
1. Launch the Editor with the Ceres_2022 project active.
2. Open the SandboxRacers level.
3. Close the Viewport Camera Selector pane if opened.
4. Right-click in the upper-left corner of the Viewport and switch to the "BetterEditorCam" camera.
5. Left-click in the Viewport (may require a few clicks).

**Expected behavior**
Camera remains set to BetterEditorCam camera.

**Actual behavior**
The camera switches to the basic Editor camera (but with seemingly broken clipping settings). Visually, the BetterEditorCam camera will still appear selected in the Viewport's camera selection.

**Screenshots/Video**
https://user-images.githubusercontent.com/82226555/187237490-c73d1d7e-6f3a-40bc-9418-4013eace7f53.mp4

**Found in Branch**
development@ cb56fc2b0221af8c3f1c6391e8bfa123b3dad323

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Additional context**
When done with the Viewport Camera Selector pane open, the cameras visually change positions in the list of cameras when clicking in the Viewport, however the view doesn't change to the (worse) Editor camera while the pane is open.

**Comment by hultonha** [comment]
@jckand-amzn As this issue was only reproducible on a particular level, would you be able to test this with #14269? Or potentially closing as it may be difficult/impossible to repro. Thanks!

**Comment by jckand-amzn** [comment]
@hultonha I'm actually unable to reproduce this issue even on base development without the changes noted above. Will re-open if issue occurs elsewhere, but I'll close this out for now.

**Comment by hultonha** [comment]
Thanks for following-up @jckand-amzn, appreciate you testing. Hopefully with my new changes coming soon this should also be less of an issue. Cheers!
