### ISSUE TITLE
UI Editor: Curve Editor does not work

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#11616]
**Describe the bug**
The Curve Editor does not have any functional tools and does not accept any inputs. After dock/undock actions the Curve Editor becomes blank (undocked) or displays values for Keys Editor (docked).

**Steps to reproduce**
1. Go to UI Editor.
2. (Optional) Create a sequence and add a few elements to it for better visibility.
3. Select Curve Editor for Animation Editor.
4. Undock the Curve Editor.

**Expected behavior**
The Curve Editor is functional while docked/undocked.

**Actual behavior**
The Curve Editor does not accept any inputs, has no tools, and displays no visual info.

**Screenshots/Video**
![CurveEditor](https://user-images.githubusercontent.com/86952591/187180397-87bdb09d-0f28-4b6d-89d0-fb15fcb221c5.JPG)

https://user-images.githubusercontent.com/86952591/187180492-8870d644-f2e4-45fb-a1fa-03800aa0836c.mp4

**Found in Branch**
Development (9abaadb)

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU Nvidia GeForce RTX 2060 SUPER
Memory 16GB

**Additional context**
Curve Editor in the Track View works correctly.

**Comment by monroegm** [comment]
This was reported against dev before stabilization was created. Need to confirm that this issue repros in stabilization.

**Comment by LB-JakubSkoczylas** [comment]
I verified that this issue occurs on stabilization build. Verified this on build Stabilization/2210 (840e1f4).

**Comment by jckand-amzn** [comment]
On stabilization@ 6f65b80fc0caa26ae83a38152621037169ed6924, I'm able to see information on the Curve Editor while both docked/undocked. There do appear to be missing icons above the Curve Editor graph area, however I can add/manipulate keys on curves in the Editor without issue.

![image](https://user-images.githubusercontent.com/82226555/192370109-272fd421-340d-4134-8ebe-354116627d6c.png)

The behavior matches that in the 2205 Release.
