### ISSUE TITLE
SelectionComponent warnings on level load are not cleared on re-saving the level

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11619]
**Describe the bug**
SelectionComponent warnings on level load are not cleared on re-saving the level. This has only been reproduced in a single level in the QA Test Project, Ceres_2022.

**Assets required**
Must pull down, build, and process assets for the QA Test Project: https://github.com/aws-lumberyard/o3de-qa-test-project

**Steps to reproduce**
1. Launch the Editor with the Ceres_2022 project active.
2. Open the SandboxRacers level.
3. Re-save and re-open the level.

**Expected behavior**
Warnings regarding SelectionComponent removal are cleared upon re-saving the level.

**Actual behavior**
Warnings remain after re-saving the level. 

NOTE:
To resolve a previous save issue with the level, the level was resaved with a new name via File > Save As. The Local View Bookmark Component still references the older level name, which may or may not be related to this issue.

**Screenshots/Video**
https://user-images.githubusercontent.com/82226555/187238727-77d7431a-3716-4cf9-951a-2c4bef7733b3.mp4

**Found in Branch**
development@ cb56fc2b0221af8c3f1c6391e8bfa123b3dad323

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Additional context**

**Comment by hultonha** [comment]
Assigned this to myself as this is related to a change I made. I'll do my best to investigate later this week as I'm curious what's causing this. I won't have access to a build until Thursday so might be a little while but I'll do my best to take a look. If you could include the .prefab level (ideally in a before and after save state too) that would be really helpful. I also want to check are you making a small edit to the level before attempting to save (so you see the * appear). This is necessary to have changes detected. Thanks!

**Comment by hultonha** [comment]
Okay I've been able to verify what is causing this issue.

The reason this is happening is the scene (`SandboxRacers.prefab`) contains a Prefab (`Fence.prefab`) that needs to be re-saved independently to have the `SelectionComponent` removed.

So this isn't so much a bug as just something inherent in the design of how Prefabs are composed within the scene.

Tagging @srikappa-amzn, @AMZN-daimini and @michabr for visibility as I know they are looking into ways to improve this in future.

We may want to make this issue more known by making people aware how to resolve it but I don't think it's actually a bug that needs fixing (short of the bigger improvement to remove this noisy warning). See https://github.com/o3de/o3de/issues/11262 for more info on a longer-term improvement.

**Comment by jckand-amzn** [comment]
Ideal solution seems to be to notify the user of WHICH prefab has the deprecated component, as the warning message is confusing.

**Comment by hultonha** [comment]
Hmm that might be possible. Tagging @srikappa-amzn to see if they have any thoughts. I do agree it's ugly and annoying but it's not actually a _bug_, it's just an irritating usability thing (that we do have plans for fix) so I would in the short-term at least be supportive of closing this bug and either adding to https://github.com/o3de/o3de/issues/11262 or creating a separate task GitHub issue to track those improvements.

**Comment by hultonha** [comment]
This issue has been resolved thanks to the fix by @michabr
