### ISSUE TITLE
Multitest exception during crash reporting

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#11629]
**Describe the bug**
When the executable test crashes, the multitest framework can also error out during reporting the crash. This occurs from attempting to access the values of a NoneType at https://github.com/o3de/o3de/blob/development/Tools/LyTestTools/ly_test_tools/o3de/multi_test_framework.py#L1215

**Assets required**
N/A

**Steps to reproduce**
1. Have a multitest-test crash

**Expected behavior**
Crash is reported

**Actual behavior**
```
_ TestMaterialEditor.run_batched_tests[windows-windows_material_editor-AutomatedTesting] _
\o3de\tools\lytesttools\ly_test_tools\o3de\multi_test_framework.py:459: in shared_run
    getattr(self, function.__name__)(
\o3de\tools\lytesttools\ly_test_tools\o3de\multi_test_framework.py:877: in _run_batched_tests
    results = self._exec_multitest(
\o3de\tools\lytesttools\ly_test_tools\o3de\multi_test_framework.py:1215: in _exec_multitest
    crashed_result.test_spec, output, return_code, crash_error, crashed_result.log_output)
E   AttributeError: 'NoneType' object has no attribute 'test_spec'
```

**Found in Branch**
Development

**Additional context**
Editor crash can be forced by sending `sys_crashtest 1` on the CLI

**Comment by Kadino** [comment]
Appears to be in review in https://github.com/o3de/o3de/pull/11915

**Comment by jromnoa** [comment]
Yes I may have solved this one when adding MaterialCavnas support for Multi Test Framework

**Comment by jromnoa** [comment]
This is fixed once I can merge https://github.com/o3de/o3de/pull/11915

**Comment by jromnoa** [comment]
This is resolved now.
