### ISSUE TITLE
Multiplayer Editor 5 Second Timeout Too Short on Slower Machines

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#11635]
**Describe the bug**
The 5 seconds time out when connecting the Editor to Server wasn't enough time to allow the server to connect.

**Steps to reproduce**
On a slow computer...
1. Open Editor
2. Open a Multiplayer level
3. Press CTRL+G
4. Notice the time it takes to connect 
     _Attempting to connect to server in order to send level data. Attempt 4 of 5_

**Expected behavior**
The server connects  

**Actual behavior**
editorsv_max_connection_attempts is too short and times out

**Found in Branch**
Development 8/29/2022

**Additional context**
It's possible the server just crashes or there's a bug that causes connection to not occur, so there _should_ be a time out. However, we probably want to increase the time between connect attempts so that relatively fast machines connect on the 1st or 2nd attempt at most. And increase the editorsv_max_connection_attempts for slower machines.

We could also leave the connections attempts infinite since users can exit anytime; seeing the attempts is enough to let them know the editor did not hang. Keep in mind if the server crashes we should already be detected that, so this would only occur should an actual bug occur and the server fail to connect even after it's loaded without crashing

**Comment by lmbr-pip** [comment]
Issue is that 5s on a slow machine there is not enough time to connect per attempt.

Potential Fixes:
* Update time per connection attempt
* migrate to exponential backoff for retries? Add connection time?
* Add cvar for tuning max connection attempts?
* Document cvars to make it more visible to users?
