### ISSUE TITLE
[Project Manager] Remote templates do not display in the project creation screen until the user cancels and restarts

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#11637]
**Describe the bug**
If the user adds a valid url for a remote template, it doesn't display in the template list until the user cancels project creation and starts again.  I.E. The template list doesn't seem to refresh after the user adds a remote template.

**Assets required**
Test url for remote templates: https://github.com/AMZN-Phil/RemoteO3DETemplate.git

**Steps to reproduce**
1. From Project Manager project list, go to New Project > Create New Project
2. From the project template list, go to Add Remote Template
3. Enter a valid URL and confirm to add the template

**Expected behavior**
The template found at the added remote source displays in template list as eligible to download

**Actual behavior**
The user needs to exit project creation and return to creating a new project for it to display in the list

**Found in Branch**
Development Nightly Installer from 8/29/2022

**Additional context**
This can be worked around by adding the url through Engine > Remote Sources prior to project creation.

**Comment by amzn-leenguy** [comment]
I can verify after walking through this myself, this bug does happen too (for me)
