### ISSUE TITLE
Remote Sources update attempts to fetch file using invalid link

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#11648]
**Describe the bug**
 When user attempts to update Remote Sources, Project Manager attempts to fetch .json file from https://github.com/AMZN-Phil/RemoteO3DETemplate.git/repo.json, when https://raw.githubusercontent.com/AMZN-Phil/RemoteO3DETemplate/main/repo.json must be used instead.

**Steps to reproduce**
1. Open the Project Manager.
2. Navigate to Engine → Remote Sources.
3. Add a repository.
4. Attempt to update the repository.

**Expected behavior**
 Repositories are updated by downloading files using the correct links.

**Actual behavior**
 Repositories are not updated due to invalid links being used.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/187447559-a9032a7a-af0a-4e46-a250-7fa46be2df55.mp4

**Found in Branch**
Development (394f780)
Stabilization/2210 (99608ff)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version 18.04
 - CPU AMD Ryzen 3600
 - GPU Nvidia GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as fixed in Stabilization/2210 branch (1a540ad), however it still occurs in the latest Development (d6342fb).
