### ISSUE TITLE
Unhelpful error message is displayed when creating Project from remote Template

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#11647]
**Describe the bug**
After adding a new Remote Template and attempting to create a project with it, an error “Project creation failed” pops up with no further details. In order to create the Project user first needs to press on “Download Template”, which is not mentioned in the error.

**Steps to reproduce**
1. Open the Project Manager.
2. Navigate to Engine → Remote Sources.
3. Add a repository.
4. Navigate to Projects.
5. Create a new Project.
6. Choose the newly added Template.
7. Attempt to create the Project.

**Expected behavior**
 A detailed error is shown with instructions for the user.

**Actual behavior**
 Error with no further details is shown.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/187442188-155e1f7f-d3bc-476d-b561-181f255736a9.mp4

**Found in Branch**
Development (394f780)
Stabilization/2210 (99608ff)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 3600
 - GPU Nvidia GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by robhaco** [comment]
The issue here is that the template hasn't been downloaded yet.  The error message should include something about this fact.

**Comment by amzn-leenguy** [comment]
Thanks for bringing this error to our attention @LB-RostyslavGavryliuk . I have walked through this same workflow and @robhaco is right. I encountered the same error here: 

![image](https://user-images.githubusercontent.com/82846749/188221627-c5d7748f-da4f-4540-af4c-e6393ed6cb28.png)

I would advise that we don't even need to update the error message, if a user went down this path. 
What we can do is disable the Create Project button, if the user selects a template that hasn't been downloaded yet.

The tooltip can read (if the developers can set this logic that the user has selected a template that isn't downloaded yet and attempts to hover over the create project button): "Please download the template first to continue."

What are your thoughts on this solution @robhaco ? Do you think our users will get confused if the button is disabled?

**Comment by rainbj** [comment]
Can we retest this ticket ? We believe this has been updated from the time this video was created.

**Comment by robhaco** [comment]
@rainbj Confirmed in development this is no longer an issue.  The following error displays with correct information about the issue: 
![image](https://user-images.githubusercontent.com/82236902/203116803-573bb9c2-0728-4aa0-9644-60f0593cd829.png)

**Comment by LB-RostyslavGavryliuk** [comment]
Issue no longer present on latest Development!
