### ISSUE TITLE
Project Manager: User is unable to add Remote Project

### ISSUE THREAD

**Issue by LB-HubertUberman** [o3de/o3de#11646]
**Describe the bug**
After pasting any GitHub project repository link into the Remote URL text field, all of the options present in the "Add a remote project" window remain greyed out with no functionality. The issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Launch Project Manager.
2. Select Add a Remote Project option.
3. Paste any GitHub link with the public project repository.

**Expected behavior**
The window is fully functional and the user is able to add Remote Project.

**Actual behavior**
Options present in the window remain greyed out and user is unable to add Remote Project.

**Video**

https://user-images.githubusercontent.com/96232062/187427975-9df8bf7a-5103-42d2-a5cd-557de3d86a53.mp4

**Found in Branch**
Stabilization/2210 (https://github.com/o3de/o3de/commit/99608ffd4f7d3d347cb015b243046a3438da23c7)
Development (https://github.com/o3de/o3de/commit/394f780dbc0eb7495fd97c8479847e02ff3f8e3c)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by amzn-leenguy** [comment]
The loading indicator on the right hand side is missing from the build. If the user was to wait about 3-4 seconds more, the buttons would of enabled and the download of the information would of been complete.

Any chance you can try again, but wait a few seconds more?

Thanks

**Comment by robhaco** [comment]
@LB-HubertUberman I created an issue covering the lack of indicator that the project manager is working on something.  https://github.com/o3de/o3de/issues/11654  Please retest this, giving it more time to resolve, and then close out this issue if it functions after. Thank you.

**Comment by LB-HubertUberman** [comment]
@robhaco @amzn-leenguy  Retested the issue on Stabilization/2210 (https://github.com/o3de/o3de/commit/99608ffd4f7d3d347cb015b243046a3438da23c7) with all three links from the video attachments, I have waited for around 10 minutes with each of them and the results are the same as described in the ticket.

**Comment by AMZN-Phil** [comment]
The first two repositories are missing the required metadata to make them usable repositories for the current system (need a repo.json and origin_uri field in the project.json). The 3rd link is a remote template link so is not possible to add t his from the add a remote project screen. #11696 adds additional feedback that the link is not a valid project remote source.

**Comment by LB-HubertUberman** [comment]
Based on the comment above verified that issue does not reproduce on Stabilization/2210 (https://github.com/o3de/o3de/commit/021d32ab66ee4daebfe55eb7804b3b6bba1d9ed9) and Development (https://github.com/o3de/o3de/commit/511a88c6ab7a3ed54898f568816e76708a6c9455) branches. Closing the ticket.
