### ISSUE TITLE
[Project Manager] There is no indicator that the Project Manager is processing a remote source url

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#11654]
**Describe the bug**
When the user adds a remote source, like a remote project, there's no indicator that the Project Manager is working on processing the URL and gathering information.  This can cause confusion when adding a remote project, as it may seem like the URL didn't work and the user will cancel the operation before it has managed to process the URL.

**Steps to reproduce**
1. In Project Manager, go to New Project... > Add Remote Project
2. In the Add a Remote Project dialog, add a valid URL (https://github.com/AMZN-Phil/RemoteO3DEProject.git)

**Expected behavior**
A visual indicator makes it clear that the URL is being processed

**Actual behavior**
There is no indicator and it appears as if the URL doesn't work (the user can't click Download)

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82236902/187484402-f280ba64-c015-4c5b-b61d-bb600b49da58.png)

**Found in Branch**
Stabilization (https://github.com/o3de/o3de/commit/99608ffd4f7d3d347cb015b243046a3438da23c7)
Development (https://github.com/o3de/o3de/commit/394f780dbc0eb7495fd97c8479847e02ff3f8e3c)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows, Ubuntu

**Additional context**
After waiting, the remaining information and functionality would display, but this could take longer on larger projects.

**Comment by amzn-leenguy** [comment]
![01-5](https://user-images.githubusercontent.com/82846749/187487677-0c929388-b554-4a83-8e53-c9a3ff448888.png)
![01-6](https://user-images.githubusercontent.com/82846749/187487681-35e6e493-9638-4231-a83e-0a66b9fe104b.png)

I've attached two images of how the states should appear as.

**Comment by amzn-leenguy** [comment]
After running through the nightly build on 9/2, I do not see the progress spinner in the dialog box. Instead I got this error when I tried to download and build: 
![image](https://user-images.githubusercontent.com/82846749/188220802-3087c8dd-32c9-4894-9272-95407773f7cb.png)

**Comment by AMZN-Phil** [comment]
The attached PR with these fixes have not been merged yet
