### ISSUE TITLE
[BJDS] Publish Figma Toolkit v1.0

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#11664]
The Blue Jay Design System defines UI Components and a Style Guide, these are also built as reusable symbols in Figma; enabling UX Designers and/or Developers from the O3DE community to leverage our design system to design and prototype before implementing.

The Toolkit's Version 1.0 includes the following UI Components and a Style Guide:

Buttons (https://github.com/o3de/o3de/issues/12568)
Card (https://github.com/o3de/o3de/issues/12567)
Dropdown Menu (https://github.com/o3de/o3de/issues/12566)
Input Fields (https://github.com/o3de/o3de/issues/12565)
Progress Indicator (https://github.com/o3de/o3de/issues/12574)
Scrollbar (https://github.com/o3de/o3de/issues/12573)
Segment Controls (https://github.com/o3de/o3de/issues/12572)
Selection Control (https://github.com/o3de/o3de/issues/12571)
Sliders (https://github.com/o3de/o3de/issues/12570)
Tooltips (https://github.com/o3de/o3de/issues/12569)

Color Palette & Typography (https://github.com/o3de/o3de/issues/12579)

--

We will be publishing the Figma Toolkit (Version 1.0) for the community by the end of 2022.

**Comment by amzn-leenguy** [comment]
For Phase 3 of the Publish Figma design toolkit task, please see https://github.com/o3de/o3de/issues/11999

**Comment by bhanuja-s** [comment]
We released Version 1.0 of the [Blue Jay Design System Toolkit](https://www.figma.com/community/file/1186743434046274167) on December 19, 2022. It is available on Figma under O3DE's [Community profile](https://www.figma.com/@o3dengine).

**Comment by bhanuja-s** [comment]
We released Version 1.0 of the [Blue Jay Design System Toolkit](https://www.figma.com/community/file/1186743434046274167) on December 19, 2022. It is available on Figma under O3DE's [Community profile](https://www.figma.com/@o3dengine).
