### ISSUE TITLE
Remove AudioSystem and LyShine Dependency on Legacy::Cry ILevelSystemListener 

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#11669]
**Is your feature request related to a problem? Please describe.**
[A recent change](https://github.com/o3de/o3de/pull/11603) added an AzFramework API for listening into level events.
AudioSystem and LyShine still use ILevelSystemListener which requires them (among other things) to depend on Legacy::CryCommon

**Describe the solution you'd like**
AudioSystem and LyShine still use ILevelSystemListener but could be quickly upgraded to use AzFramework instead.

**Describe alternatives you've considered**
Can also leave this alone, but it seems like a good (easy) step toward removing cry dependency

**Comment by lmbr-pip** [comment]
@AMZN-Gene - as these components are owned by two different SIGs it may be better to split this into two issues.
