### ISSUE TITLE
Editor Layout: Saving a custom layout with a "/" in the name causes issues

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11688]
**Describe the bug**
Saving a custom layout with a "/" in the name causes issues. If text is added after the "/", the layout will simply not save. If a layout is saved with a name like "Test/", it will save properly, but will be unable to be Deleted.

**Steps to reproduce**
1. Launch the Editor.
2. Resize a few panes/open a few tools to make a custom layout.
3. Click View > Layouts > Save Layouts and name the new layout "Test/Test"
4. Attempt to reload the newly saved layout.
5. Click View > Layouts > Save Layouts and name the new layout "Test/"
6. Attempt to Delete the newly saved layout.

**Expected behavior**
Layouts save without issue with special characters, or alert the user that the name can't be used.

**Actual behavior**
Custom layouts aren't saved if text is added after a "/" in the layout name, and cannot be deleted if "/" is used with text after it.

**Found in Branch**
stabilization/2210@ d3760da0ab375a21d67a3be5ecefbedad2440d27

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by amzn-leenguy** [comment]
As a UX representative, I would like to suggest that we don't allow users to use / in their names.
