### ISSUE TITLE
About O3DE popup window adds visual artifacts to the Viewport

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11684]
**Describe the bug**
About O3DE popup window adds visual artifacts to the Viewport.

**Steps to reproduce**
1. Launch the Editor.
2. Click on Help > About O3DE

**Expected behavior**
About O3DE dialog displays cleanly.

**Actual behavior**
Visual artifacts appear in the Viewport at the bottom and right sides of the About O3DE dialog.

**Screenshots/Video**
![about_splash_artifacts](https://user-images.githubusercontent.com/82226555/187747017-ddc8f893-f667-404a-986f-591b3ae4282f.jpg)

**Found in Branch**
stabilization/2210@ d3760da0ab375a21d67a3be5ecefbedad2440d27

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by monroegm** [comment]
Already resolved by above PR
