### ISSUE TITLE
[Linux] EMotionFX: Pressing Play button in Time View results in errors and motion not being played

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#11680]
**Describe the bug**
The attempt of playing the motion in the **Animation Editor** by clicking the **Play** button in **Time View** window, results in error popup being displayed and multiple errors being printed in the Editor console. The animation preview does not start.

The following errors are displayed in **popup** that appears when using Rin Actor and its Rin_Idle motion:

```
#1:
 The value (0,000000) of float parameter 'blendInTime' is not a valid
float. The value (0,000000) of float parameter 'blendOutTime' is not a
valid float. The value (1,000000) of float parameter 'playSpeed' is not a
 valid float. The value (1,000000) of float parameter 'targetWeight' is
not a valid float. The value (0,000000) of float parameter
'eventWeightThreshold' is not a valid float. The value (0,000000) of
float parameter 'maxPlayTime' is not a valid float.
```

Please note that errors in the **console** differ from the errors in the popup:

```
[Error]
 (EMotionFX) - Execution of command 'PlayMotion -filename
"/home/gpc-460/Github/o3de/AutomatedTesting/Cache/linux/animations/motions/rin_idle.motion"
 -blendInTime 0,000000 -blendOutTime 0,000000 -playSpeed 1,000000
-targetWeight 1,000000 -eventWeightThreshold 0,000000 -maxPlayTime
0,000000 -numLoops -1 -priorityLevel 0 -blendMode 0 -playMode 0
-mirrorMotion false -mix false -playNow true -motionExtraction true
-retarget false -freezeAtLastFrame false -enableMotionEvents true
-blendOutBeforeEnded true -canOverwrite true -deleteOnZeroWeight true
-inPlace false' failed (result='The value (0,000000) of float parameter
'blendInTime' is not a valid float.
The value (0,000000) of float parameter 'blendOutTime' is not a valid float.
The value (1,000000) of float parameter 'playSpeed' is not a valid float.
The value (1,000000) of float parameter 'targetWeight' is not a valid float.
The value (0,000000) of float parameter 'eventWeightThreshold' is not a valid float.
The value (0,000000) of float parameter 'maxPlayTime' is not a valid float.
')
[Error] (EMotionFX) - The value (0,000000) of float parameter 'blendInTime' is not a valid float.
The value (0,000000) of float parameter 'blendOutTime' is not a valid float.
The value (1,000000) of float parameter 'playSpeed' is not a valid float.
The value (1,000000) of float parameter 'targetWeight' is not a valid float.
The value (0,000000) of float parameter 'eventWeightThreshold' is not a valid float.
The value (0,000000) of float parameter 'maxPlayTime' is not a valid float.
```

**Assets required**
Rin Actor and its motions are included in the AutomatedTesting project.

**Steps to reproduce**
1. Open Animation Editor.
2. Import Actor.
3. Add any motion to default Motion Set and save it.
4. Select the motion from 3rd step.
5. Click Play button in Time View window.

**Expected behavior**
The motion is played without errors when pressing **Play** button in the **Time View** window in **Animation Editor**.

**Actual behavior**
Errors are being displayed in the popup and in Editor console and the motion is not being played.

**Video**

https://user-images.githubusercontent.com/86951967/187686645-482c239b-2396-4858-9011-b711f25afed4.mp4

**Found in Branch**
Stabilization/2210 (99608ff)
Development (a8bb125)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by hultonha** [comment]
@LB-JakubSkorupka We are pretty sure this is related to a localization issue with characters (using `,` instead of `.`). I believe @moraaar ran into a similar issue with this somewhere else while working with the LB team. I think there is a related issue that is a wider change to fix this in general. If @moraaar knows the ticket and can link it here that would be great. Thanks!

**Comment by hultonha** [comment]
Please move to `priority/minor` if this is the same localization issue as there is a known workaround and a plan to fix it

**Comment by moraaar** [comment]
From the log this seems to be the same issue provoked by this https://github.com/o3de/o3de/issues/11139 

To work around it until it's fixed, please make sure your linux machine Region&Language is set to USA.

Please close this issue if the workaround fixes it, as the root bug is already tracked by #1139

**Comment by hultonha** [comment]
Thanks very much for following-up @moraaar, @LB-JakubSkorupka could you please try @moraaar's suggestion above? Thanks!

**Comment by LB-JakubSkorupka** [comment]
I changed the Language and Format to the USA and the issue still occurs - 


https://user-images.githubusercontent.com/86951967/188153185-f8fb22a6-dc43-465f-a70f-bdf726c9f160.mp4

**Comment by LB-KatarzynaDylska** [comment]
The proposed workaround to change the format to USA works on Development (73b2163) build. The animations can be played without errors. Changing priority to minor.
