### ISSUE TITLE
Proc Prefabs: Proc Prefabs can be edited by dragging and dropping assets from the Asset Browser onto the Entity Inspector

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11693]
**Describe the bug**
Proc Prefabs can be edited by dragging and dropping assets from the Asset Browser onto the Entity Inspector.

**Assets required**
A proc prefab such as AutomatedTesting\Objects\sphere_5lods.fbx

**Steps to reproduce**
1. Launch the Editor and create a new level.
2. Instantiate the ProcPrefab into the level.
3. Open the ProcPrefab container entity, and select an entity in the ProcPrefab.
4. Drag and drop an FBX file from the Asset Browser to the Entity Inspector.

**Expected behavior**
ProcPrefabs are read-only.

**Actual behavior**
ProcPrefabs can be edited by dragging and dropping an asset from the Asset Browser.

**Screenshots/Video**
https://user-images.githubusercontent.com/82226555/187790669-d976a5e9-abe9-47c0-aa7f-4cc6cea1510e.mp4

**Found in Branch**
stabilization/2210@ d3760da0ab375a21d67a3be5ecefbedad2440d27

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by chiyenteng** [comment]
Same GHI: https://github.com/o3de/o3de/issues/8019

**Comment by AMZN-Dk** [comment]
@monroegm @AMZN-daimini  this looks like it was duped to https://github.com/o3de/o3de/issues/8019 which has an open PR https://github.com/o3de/o3de/pull/12105 for Stabilization, but the comment on 8019 says the PR only fixes "some of the issues". What's the current status for this?

**Comment by AMZN-daimini** [comment]
Fixed in stabilization by https://github.com/o3de/o3de/pull/12105
