### ISSUE TITLE
Port Node Palette in EMotionFX to `GraphCanvas::NodePaletteWidget`

### ISSUE THREAD

**Issue by MiKom** [o3de/o3de#11691]
In [10963](https://github.com/o3de/o3de/issues/10963) the node palette dock widget was hidden by default. However, It wasn't migrated to the common `GraphCanvas::NodePaletteWidget` like the context menu. It stayed as a custom tree view without a search box.

![Image](https://user-images.githubusercontent.com/104767/187777434-48fce664-09ee-44f6-b2fb-b764157a3275.png)

To achieve similar UX across all tools that use nodes palette, it should be replaced with a solution that uses `GraphCanvas::NodePaletteWidget`

Likely, the classes developed in #10963 (`BlendGraphMimeEvent`, `BlendGraphNodePaletteTreeItem`) can be re-used for this view.

The class is located in `Gems\EMotionFX\Code\EMotionFX\Tools\EMotionStudio\Plugins\StandardPlugins\Source\AnimGraph\NodePaletteWidget.{h,cpp}`

**Comment by FuzzyCarterAWS** [comment]
No usability changes here, references not needed in workflow docs.
