### ISSUE TITLE
Assert is being printed in console after adding element to Skeleton LOD modifier in FBX Settings

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#11704]
**Describe the bug**
After adding an element to the **Skeleton LOD** modifier in Actors tab in **FBX Settings** tool, an assert is being printed in the Editor console.

Note that assert is printed each time element is added to the **Skeleton LOD** modifier.

This issue is inconsistent and differs depending on asset and OS used:

**Linux:**
Assert is printed when using following assets:
 - rin_skeleton.fbx
 - chicken.fbx
 - Rin.fbx (Motion Matching Gem)

**Windows:**
Assert is printed only when using **rin_skeleton.fbx** asset included in AutomatedTesting project.

**Assert**

**File**:
`/home/gpc-460/Github/o3de/Code/Tools/SceneAPI/SceneUI/RowWidgets/NodeTreeSelectionWidget.cpp`

**Condition**:

```
(139878733503744) 'void AZ::SceneAPI::UI::NodeTreeSelectionWidget::UpdateSelectionLabel()'
(System) - Selected count of nodes should not be greater than the total count
```

**Line**:
`171`

**Assets required**
 rin_skeleton.fbx is included in the AutomatedTesting project.

**Steps to reproduce**
1. Create a new level.
1. Search for rin_skeleton.fbx asset in Asset Browser.
2. RMB on the Actor asset and select "Edit Settings..."
3. In Actors tab, add **Skeleton LOD** modifier to the Actor.
4. Click on the "+" button in **Skeleton LOD** modifier to add new element.

**Expected behavior**
Modifier is added without issues.

**Actual behavior**
Assert is being printed in Editor console.

**Screenshot/Video**

https://user-images.githubusercontent.com/86951967/187869182-12a2d343-7bee-48fe-bd5a-000e5f55bd79.mp4

![WindowsAssert_SkeletonLOD](https://user-images.githubusercontent.com/86951967/187890673-c7b9725e-4eeb-4ba0-b9e8-353c3d04a2fc.png)

**Found in Branch**
Stabilization/2210 (d3760da)
Development (a8bb125)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/9468122/Editor.log)

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as fixed in Development (https://github.com/o3de/o3de/commit/d6342fb74b53c13b7e10356e10ca9748375494a4) branch, however it still occurs in the latest Stabilization/2210 (https://github.com/o3de/o3de/commit/1a540addf51410165f5e05fab275d3ccc9579ace)
