### ISSUE TITLE
Asset Processor does not detect changes in external gems

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#11712]
**Describe the bug**
The Asset Processor does not automatically detect changes made in external gems.  It does detect them if a full rescan is performed and it does automatically detect changes in the project and core gems folders.

The setup for my use-case is a little unusual in that I have a Gem group with Gem's inside (like Atom)
```
d:\o3de-multiplayersample-assets\Gems\
    gem.json <-- group gem.json has external_subdirectory entries for gem subdirs
    character_mps\
        gem.json
        Assets\ <-- AP does not detect changes
        Registry\assetprocessor_settings.setreg
    kb3d_mps\
        Assets\ <-- AP does not detect changes
        Registry\assetprocessor_settings.setreg  
```
But I have both the Gem group and `character_mps` Gem paths registered as `external_subdirectories` in the `o3de_manifest.json` and changes are detected with a full rescan.

The `gem.json` for the group gem looks like this
```json
{
    "gem_name": "MPSGems",
    "display_name": "MPS Gems",
    "license": "Apache-2.0 Or MIT",
    "license_url": "https://github.com/o3de/o3de/blob/development/LICENSE.txt",
    "origin": "Open 3D Engine - o3de.org",
    "origin_url": "https://github.com/o3de/o3de-multiplayersample-assets",
    "type": "Code",
    "summary": "Provides multiple gems for the Multiplayer Sample",
    "canonical_tags": [
        "Gem"
    ],
    "user_tags": [
        "Multiplayer"
    ],
    "requirements": "",
    "documentation_url": "",
    "external_subdirectories": [
        "character_mps",
        "kb3d_mps",
        "landscape_mps",
        "level_art_mps",
        "particlefx_mps",
        "pbr_material_pack_mps",
        "props_mps"
    ],
    "dependencies": [
        "character_mps",
        "kb3d_mps",
        "landscape_mps",
        "level_art_mps",
        "particlefx_mps",
        "pbr_material_pack_mps",
        "props_mps"
    ]
}
```

**Steps to reproduce**
1. Open the Editor for a project that has an external Gem with an Assets folder
2. Open the Asset Processor
3. Add an .fbx asset to the external Gem's Asset folder

**Expected behavior**
The asset is picked up by the Asset Processor and processed

**Actual behavior**
The asset is not detected, nor are changes to existing assets detected in the external gem

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/26804013/187963668-3ec1a6ca-50d6-4c46-b414-e6d5eb770549.png)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
n/a

**Comment by lumberyard-employee-dm** [comment]
NOTE: For developers working on this issue
The scan folders are gathered from AzFramework::GetGemInfos call and added to the list of Scan Folders in [PlatformConfiguration::InitializeFromConfigFiles](https://github.com/o3de/o3de/blob/development/Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp#L770-L779) function.

That would be the first place to check to make sure external the gem folders are added to the list of scan folders.

The second place to check is the [AssetScannerWorker::ScanForSourceFiles](https://github.com/o3de/o3de/blob/development/Code/Tools/AssetProcessor/native/AssetManager/assetScannerWorker.cpp#L70) function to make sure that the scan folders of external Gems(Gems that are outside the project root) are passed into that function.

**Comment by tonybalandiuk** [comment]
@AMZN-alexpete , @lmbr-pip , @AMZN-Dk  based on the timing of this being create, I think it could exist in stabilization. If so, fo you think this needs to be resolved in the upcoming release? If so, we should add it to the "Release/2210" milestone. If not, please add it to the "Backlogged Issues" milestone. Thanks. @AMZN-Dk  and I are working to understand what's still required to fix for the upcoming release - your assistance here will help.

**Comment by AMZN-alexpete** [comment]
It's possible this is an issue with how the "parent" gem is setup - I was testing with a "parent" gem that had no CMakeLists.txt or preview.png https://github.com/o3de/o3de-multiplayersample-assets/tree/main/Gems
![image](https://user-images.githubusercontent.com/26804013/195136049-d5e96e02-e6ba-4b6e-b106-0d6774c7b518.png)

**Comment by lumberyard-employee-dm** [comment]
> It's possible this is an issue with how the "parent" gem is setup - I was testing with a "parent" gem that had no CMakeLists.txt or preview.png https://github.com/o3de/o3de-multiplayersample-assets/tree/main/Gems ![image](https://user-images.githubusercontent.com/26804013/195136049-d5e96e02-e6ba-4b6e-b106-0d6774c7b518.png)

Yes, that would be the issue.
The formal definition of a gem is "a directory containing a gem.json which contains a "gem_name" field and a CMakeLists.txt"

**Comment by AMZN-alexpete** [comment]
> Yes, that would be the issue.
> The formal definition of a gem is "a directory containing a gem.json which contains a "gem_name" field and a CMakeLists.txt"

OK, then we can close this issue as "user error"

**Comment by lumberyard-employee-dm** [comment]
> > Yes, that would be the issue.
> > The formal definition of a gem is "a directory containing a gem.json which contains a "gem_name" field and a CMakeLists.txt"
> 
> OK, then we can close this issue as "user error"

We should add an empty CMakeLists.txt at least.

**Comment by AMZN-stankowi** [comment]
> 

Sure, closing this as designed for now.

**Comment by lumberyard-employee-dm** [comment]
The `Path::IsRelativeTo` function will be fine even in a hot code path.

**Comment by AMZN-alexpete** [comment]
Hmm all of these paths are `QStrings` so we'd have to use something like this which would allocate and be slow right?
```
QString pathA;
QString pathB;
auto pathViewA = AZ::IO::PathView(pathA.toUtf8().constData));
auto pathViewB = AZ::IO::PathView(pathB.toUtf8().constData));

return pathViewA.IsRelativeTo(pathViewB);
```
