### ISSUE TITLE
Prefab MonoChromatic Mode Doesn't Work

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#11727]
**Describe the bug**
A clear and concise description of what the bug is. Try to isolate the issue to help the community to reproduce it easily and increase chances for a fast fix.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Open Editor.exe
2. Open any level
3. Drag a prefab into the scene and double click it to edit
4. Select Edit Mode > Monochromatic

**Expected behavior**
Everything in the level besides the prefab should be black and white greyscale

**Actual behavior**
The level is still colorful

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32776221/188023860-ad1ff03c-f7ac-43a9-b3ae-3733a597be59.png)

**Found in Branch**
Development latest August 25 2022

**Comment by jckand-amzn** [comment]
Also hit confusion with this toggle in my workflow testing. I found this other existing ticket regarding the issue: https://github.com/o3de/o3de/issues/11303

The functionality appears to be hidden behind a setreg flag, and is for component edit mode rather than prefab edit mode.

**Comment by AMZN-daimini** [comment]
As @jckand-amzn mentioned above, the setreg flag should also hide the combobox selection in the viewport toolbar if the visualization is disabled.

**Comment by jonawals** [comment]
Closed as addressed in https://github.com/o3de/o3de/issues/11303.
