### ISSUE TITLE
UI Editor: Slice Library context menu entry doesn't expand

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11724]
**Describe the bug**
Slice Library context menu entry doesn't expand. This makes users unable to instantiate a UI element from the slice library context menu. Users can still add an element from the Slice Browser.

**Steps to reproduce**
1. Launch the Editor and open a new or existing level.
2. Open the UI Editor.
3. Right-click on the canvas area, and hover over New > Element from Slice Library

**Expected behavior**
Slice Library expands, allowing users to quickly add UI Slices to their canvas.

**Actual behavior**
Slice Library context menu entry doesn't expand.

**Screenshots/Video**
![no_expand_slice_library](https://user-images.githubusercontent.com/82226555/188022315-563fb66d-a6e2-40c6-b2a2-1d3a6f25dea0.jpg)

**Found in Branch**
stabilization/2210@ d3760da0ab375a21d67a3be5ecefbedad2440d27

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by srikappa-amzn** [comment]
Maybe the library gets populated when a gem is enabled. We should hide that menu option if that gem is disabled then instead of doing nothing.

**Comment by jckand-amzn** [comment]
> Maybe the library gets populated when a gem is enabled. We should hide that menu option if that gem is disabled then instead of doing nothing.

That makes sense, however in my case I was in the AutomatedTesting project which has all of the required gems enabled, so something else seems to be going on.
