### ISSUE TITLE
Deprecated component warning on new level

### ISSUE THREAD

**Issue by michabr** [o3de/o3de#11735]
**Describe the bug**
When creating and opening a new level, there are error messages regarding the deprecated SelectionComponent.

**Steps to reproduce**
1. Open Editor and create a new level
5. See errors in console

**Expected behavior**
New levels should not have any errors.

**Actual behavior**
Errors are logged in the console regarding deprecated component.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Stabilization

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Monterey, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**
To fix this, the Assets/Editor/Prefabs/Default_Level.prefab file needs to be updated.

**Comment by srikappa-amzn** [comment]
Closed by https://github.com/o3de/o3de/pull/11729

**Comment by srikappa-amzn** [comment]
This is closed in stabilization/2210 branch. Will be closed in development at a later time because of the scheduled integrations from stabilization -> development.
