### ISSUE TITLE
Script Canvas: Asset assigned to Create Spawn Ticket node via Node Inspector is not recognized.

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#11746]
**Describe the bug**
If you assign an asset to create spawn ticket node by using the node inspector the script will throw a null reference error during gameplay.

**Steps to reproduce**
1. Open Script Canvas
2. Create a new script
3. Create a graph that spawns a prefab ( see image below)
4. Attach the script to an entity's script canvas component
5. Run the game and observe the console output

![image](https://user-images.githubusercontent.com/98843754/188182152-bb8933f4-61cf-4280-8e99-cd57be231e77.png)

**Expected behavior**
the prefab is spawned

**Actual behavior**
a null reference exception
`[Error] (Script) - Lua failed to call method: cannot convert parameter 2 from nil to AzFramework::EntitySpawnTicket
 ---------- START STACK TRACE ---------- 
=[C](-1): RequestSpawn
=?(-1): ?

 ---------- END STACK TRACE ----------`

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device PC win 10
 - CPU Ryzen 5950x, ]
 - GPU NVidia RTX 3070]
 - Memory [e.g. 32GB]

**Additional context**

**Comment by AMZN-daimini** [comment]
The script in the repro steps does not pass a Prefab parameter to the `Create Spawn Ticket` node, which is likely the cause of the crash.
The `Spawn` node should just do nothing when a default-initialized spawn ticket is passed to it, though.
Redirecting this to the prefab team since they handle the implementation of the Spawn node.

**Comment by srikappa-amzn** [comment]
Making sure that the users can't pick the prefab at all might be a quick and easy way to fix this issue without modifying the node behavior or running into backward compatibility issues. We also need better hint messages and naming but need to be careful about migrating previously created sc files.

**Comment by chiyenteng** [comment]
Related PR:
- hiding the assignment through node inspector for now:  https://github.com/o3de/o3de/pull/12014
- adding error handling/logs when prefab is not valid: https://github.com/o3de/o3de/pull/11991

**Comment by onecent1101** [comment]
Created a long term plan for this issue https://github.com/o3de/o3de/issues/12120
