### ISSUE TITLE
UI Editor: Entering Game Mode can cause Canvas element properties to no longer be editable

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11757]
**Describe the bug**
Entering Game Mode can cause Canvas element properties to no longer be editable. This only appears to occur when a mesh in the level has been setup to display a UI Canvas, and the entity holding that mesh is selected when Game Mode is entered.

**Assets required**
User must create a source .attimage file locally to use as a render target as described in https://www.o3de.org/docs/user-guide/interactivity/user-interface/canvases/canvas-properties/#attachment-image-assets

**Steps to reproduce**
1. Launch the Editor, and create a new or existing level.
2. Open the UI Editor, and create a simple canvas to render to a mesh.
3. With no UI elements selected, set the canvas to Render to Texture, and assign the source .attimage as the Render Target, and then save the canvas.
4. Minimize the UI Editor, and create a new entity in the level with a Mesh component (with any valid mesh assigned), Material component, and UI Canvas Asset Ref with the saved canvas assigned and set to Load Automatically.
5. Edit the Mesh's Material Instance, and set the attimage as the Base Color texture.
6. With the Mesh entity selected, enter/exit Game Mode.
7. Return to the UI Editor and attempt to edit the properties on any element.

**Expected behavior**
Canvas element properties remain editable.

**Actual behavior**
Properties pane is locked to whatever was displayed upon entering Game Mode. This persists until the canvas is reloaded in the UI Editor.

**Screenshots/Video**
https://user-images.githubusercontent.com/82226555/188232958-f5e1e42e-51b0-40c3-adff-1c60a5ef7bbb.mp4

**Found in Branch**
stabilization/2210@ d3760da0ab375a21d67a3be5ecefbedad2440d27

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by AMZN-daimini** [comment]
If upon further investigation it seems to be related to game mode code, feel free to redirect to `feature/editor`.
