### ISSUE TITLE
UI Editor window opens off-center, even when maximized, in various Portrait modes using 2k resolution with 100% scaling

### ISSUE THREAD

**Issue by dm-amzn** [o3de/o3de#11761]
**Describe the bug**
The UI Editor window opens off-center, even when maximized, in either Portrait modes using 2k resolution with 100% scaling.

- Occurs on both a regular 2k and 4k monitors using a 1920 x 1080 resolution setting.
- Does not occur when using a Hi DPI (4k +) resolution. 

**Steps to reproduce**

1. In Windows, open Display Settings
2. Identify and select your display in the preview
3. For Scaling, set to 100%
4. In Scale and Layout, set the Display resolution to 1920 x 1080
5. Set the Display orientation to either Portrait or Portrait (flipped)
6. Select Keep Settings
7. Launch the Editor
8. Create a new level, or load an existing level
9. Open the UI Editor (Tools > UI Editor)
10. Observe issue
11. Maxmize the UI Editor window
12. Observe issue

**Expected behavior**
The UI Editor window opens, centered to screen, with access to all tools and features, especially when maximized.

**Actual behavior**
The UI Editor window opens off-center, even when maximized, in either Portrait modes using 2k resolution with 100% scaling.

**Screenshots/Video**

https://user-images.githubusercontent.com/97991771/188249769-47619b6d-7205-4100-8559-fd2f3cdbfb72.mp4

**Found in Branch**
stablization/2210

**Comment by AMZN-daimini** [comment]
Relates to #11773

**Comment by monroegm** [comment]
Marking as resolved based on linked PR being merged
