### ISSUE TITLE
SaveData gem is not available in Editor only game launcher

### ISSUE THREAD

**Issue by petrocket** [o3de/o3de#11770]
**Describe the bug**
After enabling the SaveData gem I was attempting to test it in the Editor, but gems that do not declare an alias or target for `PAL_TRAIT_BUILD_HOST_TOOLS`  are not loaded in the editor.
What is the correct fix? I added a `Tools` alias to work around this issue, but could imagine there are other gems out there that declare `Clients` but not `Tools` alias or targets and are left out when the editor is loaded.

**Steps to reproduce**
1. Enable the SaveData gem or any gem with a `Clients` alias or target but not a `Tools` alias or target
2. Run the editor

**Expected behavior**
Functionality from all gems that are enabled for the client are available in the editor also

**Actual behavior**
Gems that do not declare a `Tools` target or alias are not available in the editor

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Comment by lumberyard-employee-dm** [comment]
Not all gems need to be available for the Editor.

In this case the saveData gem provides no Editor functionality.
It is meant for saving and loading the save data of a running game.

**Comment by petrocket** [comment]
I think the issue was that I expected every gem that is available for running in the game launcher to be available in the editor so that when I run the game in the editor I get the same functionality.  I was confused why I was unable to test any save/loading of data while in the editor until I realized this gem wasn't loaded. I would not be surprised if other game developers run into this same issue with this gem and with others - they expect a gem that provides something in the launcher to also be available for when they run their game in the editor.
