### ISSUE TITLE
Monolithic and non-monolithic release profile launchers have white screens and are unresponsive

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#11776]
**Describe the bug**
GameLauncher, and ServerLauncher executables built using the release profile launch with a white screen, and are unresponsive. It should be noted that a default level was created, and added to the autoexec.game.setreg file.

This issue also occurs on the Development (0222ef9) build.

**Steps to reproduce**
1. Perform project-centric release monolithic, and non-monolithic builds following the https://www.o3de.org/docs/user-guide/packaging/windows-release-builds/ guide.

**Expected behavior**
Monolithic, and non-monolithic GameLauncher, and ServerLauncher opens up the level specified in the autoexec.game.setreg file, or a grey background if no level is avaliable/selected.

**Actual behavior**
Monolithic, and non-monolithic GameLauncher, and ServerLauncher launch with white screen, and are unresponsive.

**Videos**
Stabilization/2210 (4952439):

https://user-images.githubusercontent.com/86952082/188598565-0c486b68-edc3-4df1-abcb-23e7543ff54a.mp4

Development (0222ef9):

https://user-images.githubusercontent.com/86952082/188598531-59383b5f-e48b-4bd8-8f78-50dbd94c330f.mp4

**Found in Branch**
Stabilization/2210 (4952439)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by lumberyard-employee-dm** [comment]
Should be fixed by PR #11781

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization/2210 (58fb16c) build.
