### ISSUE TITLE
Project Manager: Automatically build project for remote project does not work

### ISSUE THREAD

**Issue by AMZN-Phil** [o3de/o3de#11789]
Automatically build a remote project toggle does not work.

1. Click add a remote project
2. Add a remote source and make sure that the automatically build project is toggled on
3. Download the project

Expected behavior:
Project downloads and the commences building

Actual behavior:
Project downloads but does not build

**Comment by tonybalandiuk** [comment]
@AMZN-Phil  @Ulrick28   based on the timing of this being created, I think it could exist in stabilization. If so, do you think this needs to be resolved in the upcoming release? If so, we should add it to the "Release/2210" milestone. If not, please add it to the "Backlogged Issues" milestone. Thanks. @AMZN-Dk  and I are working to understand what's still required to fix for the upcoming release - your assistance here will help us in that endeavor.

**Comment by Ulrick28** [comment]
We will check in stab, but it was likely already fixed there as I remembering seeing this. Either way, we will make sure this is addressed.



On Sep 18, 2022, at 8:28 AM, Tony Balandiuk ***@***.***> wrote:

﻿

@AMZN-Phil<https://github.com/AMZN-Phil> @Ulrick28<https://github.com/Ulrick28> based on the timing of this being created, I think it could exist in stabilization. If so, do you think this needs to be resolved in the upcoming release? If so, we should add it to the "Release/2210" milestone. If not, please add it to the "Backlogged Issues" milestone. Thanks. @AMZN-Dk<https://github.com/AMZN-Dk> and I are working to understand what's still required to fix for the upcoming release - your assistance here will help us in that endeavor.

**Comment by AMZN-Phil** [comment]
Fixed by linked PR
