### ISSUE TITLE
CMake does not check for presence of libcurl for AWSCore

### ISSUE THREAD

**Issue by Be-ing** [o3de/o3de#11783]
**Describe the bug**
Building on a fresh Fedora 36 installation, linking failed due to the libcurl-devel package not being installed. This should have failed earlier at CMake configure time rather than failing with a linker error.

**Assets required**
none

**Steps to reproduce**
1. Install Fedora 36
2. Follow https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/ then https://www.o3de.org/docs/welcome-guide/create/creating-projects-using-cli/creating-linux/

**Expected behavior**
CMake checks for presence of libcurl at configure time and exits with a fatal error if it is not found.

**Actual behavior**
```
[648/1307] Linking CXX shared module bin/profile/libAWSCore.so
FAILED: bin/profile/libAWSCore.so 
: && /usr/bin/clang++-14 -fPIC -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Wno-inconsistent-missing-override -Wrange-loop-analysis -Wno-unknown-warning-option -Wno-parentheses -Wno-reorder -Wno-switch -Wno-undefined-var-template -msse4.1  -O2 -g -fstack-protector-all -fstack-check  -fuse-ld=mold -Wl,--no-undefined -fpie -Wl,-z,relro,-z,now -Wl,-z,noexecstack -shared  -o bin/profile/libAWSCore.so External/AWSCore-1a09c2de/Code/CMakeFiles/AWSCore.dir/profile/Unity/unity_0_cxx.cxx.o  -Wl,-rpath,"\$ORIGIN"  lib/profile/libAzCore.a  lib/profile/libAWSCore.Static.a  lib/profile/libAzFramework.a  /usr/lib64/libxcb-xkb.so  /usr/lib64/libxcb-xfixes.so  /usr/lib64/libxcb.so  /usr/lib64/libxkbcommon-x11.so  /usr/lib64/libxkbcommon.so  /usr/lib64/libX11.so  -lxcb-xinput  lib/profile/libAzNetworking.a  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  /home/be/.o3de/3rdParty/packages/lz4-1.9.3-vcpkg-rev4-linux/lz4/lz4/lib/liblz4.a  lib/profile/libAWSNativeSDKInit.a  lib/profile/libAzCore.a  /home/be/.o3de/3rdParty/packages/unwind-1.2.1-linux/unwind/lib/linux-x86_64-clang-release/libunwind.a  -lpthread  -latomic  -lpthread  -latomic  /home/be/.o3de/3rdParty/packages/Lua-5.4.4-rev1-linux/Lua/lib/release/liblualib.a  /home/be/.o3de/3rdParty/packages/zlib-1.2.11-rev5-linux/zlib/lib/libz.a  /home/be/.o3de/3rdParty/packages/zstd-1.35-multiplatform/zstd/bin/linux-clang-3.8/release/libzstd.a  /home/be/.o3de/3rdParty/packages/cityhash-1.1-multiplatform/cityhash/build/linux/clang-3.8/release/libcityhash.a  bin/profile/libO3DEKernel.so  -ldl  /home/be/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-linux-openssl-3/AWSNativeSDK/bin/Release/libaws-cpp-sdk-core.so  /home/be/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-linux-openssl-3/AWSNativeSDK/bin/Release/libaws-cpp-sdk-dynamodb.so  /home/be/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-linux-openssl-3/AWSNativeSDK/bin/Release/libaws-cpp-sdk-lambda.so  /home/be/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-linux-openssl-3/AWSNativeSDK/bin/Release/libaws-cpp-sdk-s3.so  -lcurl && cd /home/be/O3DE/Projects/MyProject/build/linux/External/AWSCore-1a09c2de/Code && /usr/bin/cmake -P /home/be/sw/o3de/cmake/Platform/Linux/ProcessDebugSymbols.cmake /usr/bin/strip /usr/bin/objcopy /home/be/O3DE/Projects/MyProject/build/linux/bin/profile/libAWSCore.so dbg MODULE_LIBRARY DETACH
mold: fatal: library not found: curl
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
[673/1307] Building CXX object External/CommonFeatures-fe50267c/Code/CMakeFiles/AtomLyIntegration_CommonFeatures.dir/profile/Unity/unity_0_cxx.cxx.o
ninja: build stopped: subcommand failed.
```

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development (commit 76f27de54a5af7417f2700fc6b22a803802e51aa)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Fedora
 - Version 36
 - CPU Intel Core i9 12900K
 - GPU NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate]
 - Memory 64 GB

**Comment by lumberyard-employee-dm** [comment]
I am bring this issue to your attention @spham-amzn

**Comment by spham-amzn** [comment]
There is detection on OpenSSL during Cmake, but not for libCurl. This probably needs to be done in the AWSNativeSDK's 3P package.

**Comment by spham-amzn** [comment]
The code to link [AWSCore](https://github.com/o3de/3p-package-source/blob/30e7001c515ed5fe0a596a89e59907c8e7911482/package-system/AWSNativeSDK/FindAWSNativeSDK.cmake.Linux#L110-L115) does specify `curl`, and the [packaging script](https://github.com/o3de/3p-package-source/blob/30e7001c515ed5fe0a596a89e59907c8e7911482/package-system/AWSNativeSDK/docker_build_aws_sdk.sh#L204) does copy the local `libcurl.a` to its intended location.
