### ISSUE TITLE
Project Manager tries and fails to clone GitHub archive URLS

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#11802]
**Describe the bug**
If you use a GitHub archive URL for a remote gem/project/template archive Project Manager will attempt to clone it instead of download it.
The ProjectManager just looks for `github.com` in the URL, which archive and release URLs will have, e.g. `https://github.com/AMZN-alexpete/o3de-remote-gem-repo-demo/archive/main.zip` or `https://github.com/AMZN-alexpete/o3de-remote-gem-repo-demo/releases/download/1.0.0/o3de-remote-gem-repo-demo-main.zip``

**Assets required**
n/a

**Steps to reproduce**
1. Add the following repository in Project Manager https://github.com/AMZN-alexpete/o3de-remote-gem-repo-demo
2. Attempt to download the included gem by enabling it in a project

**Expected behavior**
The Gem is downloaded and enabled in the project

**Actual behavior**
The Gem fails to download because ProjectManager treats it as a git repo but cannot clone it

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/26804013/188961407-69d499a7-dc2f-4456-a8b4-0a9736c4892c.png)

**Found in Branch**
development and stabilization

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Comment by hultonha** [comment]
Speculatively adding `sig/content` as the owning sig but I may be wrong here so please feel free to reassign. Thanks!

**Comment by cgalvan** [comment]
Verified this is fixed by https://github.com/o3de/o3de/pull/12085
