### ISSUE TITLE
Terrain: Terrain stops rendering in Viewport after any modification of Terrain World Renderer

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#11824]
**Describe the bug**
After modifying **any** value in the **Terrain World Renderer** the terrain present on level disappears. Undoing the modification of **Terrain World Renderer** or deleting the **Terrain World Renderer** component and adding it again to the level prefab resolves this issue as the terrain appear again in **Viewport**. Entering the Game Mode also resolves this issue as terrain is rendered again.

This issue occurs also on Windows OS.

**Steps to reproduce**

1. Select the level.prefab.
2. Add Terrain World and Terrain World Renderer components to it.
3. Create an entity, make sure it is visible in Viewport.
4. Add Terrain Layer Spawner and Axis Aligned Box Shape to previously created entity.
5. Select level.prefab and modify any value in Terrain World Rendered component.

**Expected behavior**
**Terrain World Renderer** component can be modified without issues.

**Actual behavior**
Modifying **Terrain World Renderer** component stops rendering of the terrain in Viewport.

**Video**

https://user-images.githubusercontent.com/86951967/189121375-3ae36cc1-89b5-49b2-99ec-9554f718aace.mp4

**Found in Branch**
Stabilization latest installer
Stabilization/2210 (358c6b0)
Development (e57be91)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by jckand-amzn** [comment]
Also reproduced on Windows.

**Comment by LB-JakubSkorupka** [comment]
Verified the issue as fixed on builds Development (74bb8dd), and Stabilization/2210 (37c7b44)
