### ISSUE TITLE
Linux: Minimal project level has multiple issues

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#11825]
**Describe the bug**
In the minimal template project, created levels have multiple issues.

* Saving the level prints multiple warnings and an error to the console: "Failed to de-serialize Prefab instance from Prefab DOM. Unable to Proceed". Upon reloading the level, changes are present but an Error Log window appears. 
* Most of the entities cannot be moved:
-Atom Default Environment
-Global Sky
-Shader Ball
-Grid
-Ground
* Entities cannot be hidden or locked.
* Any disabled components in entities are immediately removed. This also affects components missing requirements (e.g., Audio Animation) and conflicting components (e.g., Actor component added to an entity that already has the Mesh component).

Entities can still be deleted.
This issue does not affect newly created entities, duplicates of original entities, or entities that were deleted and then the deletion was undone. Creating entities in any of these ways also allows the level to save without errors.

This issue only occurs on Linux. Please note that reproducing the issue on a Source build might be blocked due to https://github.com/o3de/o3de/issues/10638.

**Steps to reproduce**
1. Create a project with the Minimal template.
2. Run the editor and create a level.
3. Save the level.
4. Reload the level.
5. Try hiding and locking entities in the Entity Outliner.
6. Try to move all the entities present in the level.
7. Disable a component in an entity.
8. Duplicate one of the original entities.
9. Delete one of original the entities and Undo.
10. Create a new entity.
11. Repeat steps 5-7 with entities from steps 8-10.

**Expected behavior**
The level saves and reloads without errors. Entities can be hidden, locked, moved, and components can be edited without issues. 

**Actual behavior**
There are errors upon saving and loading the level. Original entities in the level cannot be hidden, locked, or have disabled components. Most of the entities cannot be moved.

**Screenshots/Video**

https://user-images.githubusercontent.com/99388484/189135537-9a184047-844c-41e2-8bbd-8a333407d206.mp4

**Found in Branch**
Stabilization/2210 (358c6b0)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version: 20.04.4 LTS
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by lumberyard-employee-dm** [comment]
This sounds like some gem is required by the prefab system that is missing.

**Comment by tonybalandiuk** [comment]
is this a major or a critical? it has both labels

**Comment by monroegm** [comment]
@tonybalandiuk It is supposed to be a critical. Fixed.

**Comment by michabr** [comment]
Update: I was able to remote to an existing Linux instance that already has the necessary O3DE setup, and will debug from there.

**Comment by tonybalandiuk** [comment]
thanks for the update. Note @monroegm that once this PR is prepared, it will require an exception which should be easy to get.

**Comment by tonybalandiuk** [comment]
@monroegm Can this be worked around by duplicating the entities the deleting the originals? If so this may be a candidate for a Known Issues.

**Comment by michabr** [comment]
After some investigation it turns out this is already fixed indirectly by this PR https://github.com/o3de/o3de/pull/11822. Before, the prefab deserializer halted when hitting an unrecognizable component which put the level prefab in a weird state, but with this PR the deserializer skips and continues.

I've verified that none of the issues in this ticket occur anymore (and that they used to occur before this PR).

There is still the issue that the default level has a EditorColliderComponent but the Minimal Project template does not enable the PhysX gem which defines this component, so the user will still see a warning in the console. However, this is not Linux specific. We could address this warning in a lower priority ticket.

**Comment by tonybalandiuk** [comment]
thank you for the update. Glad to see this is fixed. @AMZN-Dk FYI

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization/2210 (d327e2f) build.
