### ISSUE TITLE
Add Cylinder shape support to Editor Collider Component

### ISSUE THREAD

**Issue by SergeyAMZN** [o3de/o3de#11848]
**Is your feature request related to a problem? Please describe.**

We would like to use cylinder colliders in the same way as other primitive colliders are used.
Currently it is only possible to have a cylinder collider with Cylinder Shape Component is used. However this limits to have only 1 cylinder per entity and doesn't support offsets and rotation.

**Describe the solution you'd like**

To have an option in Editor Collider Component to choose Cylinder and have full support of the rest of Editor Collider Component functionality.

**Describe alternatives you've considered**

Alternative is to use multiple entities with a Cylinder Shape Component however this doesn't support dynamic objects, only static colliders.

**Additional context**

![image](https://user-images.githubusercontent.com/60428010/189309033-92c3f422-e595-4490-b733-8b59bf2f54c6.png)

**Comment by hultonha** [comment]
@SergeyAMZN Please can you add a link to the relevant PR here

**Comment by hultonha** [comment]
@lgleim and @epsilon-delta - We are attempting to follow the guidance outlined here - https://github.com/o3de/o3de/projects?type=classic about getting features approved to go into the stabilization/2210 branch.

As chairs of sig-simulation to which Physics belongs, would you please be able to add a comment with your approval here. This is a very important feature we would like to get added to the release.

Please see this PR for details - https://github.com/o3de/o3de/pull/11797

**Comment by hultonha** [comment]
We also need approval from @o3de/sig-testing and @o3de/sig-ui-ux. If someone from each sig could please add an approval either here or on the PR linked above we'd really appreciate it. Thank you!

**Comment by lgleim** [comment]
This certainly has my approval for merging into the stabilization branch.

**Comment by tonybalandiuk** [comment]
to remain consistent with the exception tracking we have used for other requests, I will track the approvals under the PR https://github.com/o3de/o3de/pull/11797. I see @lgleim 's approval here and will note that.

**Comment by hultonha** [comment]
Understood, thanks @tonybalandiuk, I'll use the PRs for future reference :+1:

**Comment by SergeyAMZN** [comment]
Done in #11797
