### ISSUE TITLE
Bug Report: Build node installs Python 2.7

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#11842]
**Describe the bug**
Build node setup installs Python 2.7 which is a security risk. Python 2.7 is End of Life as of Jan 1st 2020 and is not being patched, updated or fixed. See https://www.python.org/downloads/ for details and https://www.python.org/doc/sunset-python-2/

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Go to https://github.com/o3de/o3de/blob/3cb342ce6c7469d814c5ebb31e9e8eaebc7ab3cf/scripts/build/build_node/Platform/Windows/install_python.ps1#L8
2. See that Python 2.7 is being installed

**Expected behavior**
Nothing should be using Python 2.7 due to security risks

**Actual behavior**
Python 2.7 is installed

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Monterey, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by lmbr-pip** [comment]
2.7.15 is still installed in the development branch:
https://github.com/o3de/o3de/blob/development/scripts/build/build_node/Platform/Windows/install_python.ps1#L8 

Issue appears to have been closed prematurely, should not be closed until changes are propagated to development from stabilization 2210.

**Comment by spham-amzn** [comment]
Fix has been propagated to development, closing issue
