### ISSUE TITLE
Terrain: Terrain components sliders have improper value range in comparison to value tooltip

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#11850]
**Describe the bug**
Sliders in particular Terrain components have improper value range - it is not possible to set the values by using the slider, to number described in the tooltip. Note that it is possible to set values in range described in tooltips by using number fields and typing desired number.

This issue occurs also on Windows OS.

Affected values in particular components : 

 - Terrain Macro Material - Normal Factor, Priority
 - Terrain Layer Spawner - Sub Priority
 - Terrain World Debugger - Spacing (m), Height Point Size (m), Normal Height (m)
 - Terrain World Renderer - First LOD Distance, CLOD Distance, Detail Material Scale

**Steps to reproduce**

1. Create a new level.
2. Create a new entity.
3. Add **Terrain Macro Material** and **Axis Aligned Box Shape** components to previously created entity.
4. Use slider to set **Normal Factor** value to maximum.
5. Hover mouse cursor over "Normal Factor" so the tooltip appears.

**Expected behavior**
Parameters with very high range of value do not have slider feature (only number field is present) as it is very hard to set desired value when the range is very high e. g. -10000 - 10000.
Alternatively - It is possible to set value as described in tooltip of parameters by using slider.

**Actual behavior**
It is not possible to set parameter values as described in tooltip by using slider.

**Video**

https://user-images.githubusercontent.com/86951967/189648225-9a916332-e540-4f5b-a58b-486d137c64a3.mp4

**Found in Branch**
Stabilization latest installer
Stabilization/2210 (441e2b3)
Development (f73f81b)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by mbalfour-amzn** [comment]
This is "as designed". The slider UX components have a feature called "soft min" / "soft max" that lets us set a range for the slider that's smaller than the full min/max range. We use this feature to reduce the slider range to only contain recommended or common values.

For example, the Normal Factor field supports values of 0 - 10, but most people shouldn't need values outside of the 0 - 2 range, so we have a soft max on the slider to end at 2. You can still type in larger values in the uncommon case where you need something larger, but the reduced slider range helps guide you towards choosing better values in the common cases.
