### ISSUE TITLE
why the Audio Control Editor have nothing,please look at the picture 

### ISSUE THREAD

**Issue by ouxiaoyang** [o3de/o3de#11857]
![1](https://user-images.githubusercontent.com/45101398/186406402-ec6b0b9a-e02a-4382-b27a-4a76bf5c53ca.png)
i have add the gem and re-compile

**Comment by galibzon** [comment]
@ouxiaoyang , can you please add more info into what version/commit are you using, what kind of machine, OS, etc?

**Comment by amzn-phist** [comment]
@ouxiaoyang This is likely to occur if CMake is unable to locate the Wwise install location during configure.

- Make sure you have downloaded and installed Wwise.  You should include the `SDK(C++)` component and select any platforms you need.
- Next time you configure CMake, check the output for a line that looks _similar_ to this:
`Using Wwise SDK version 2021.1.8.7831 at D:\tools\audiokinetic\Wwise 2021.1.8.7831`
If you see this line being printed, then you know CMake found the Wwise SDK.
- CMake can use two things to find the Wwise install:
  1. During install of Wwise it will automatically set two environment variables: `WWISEROOT` and `WWISESDK`.  These will usually point to the most recently installed version of Wwise on your system.  (There's also a way to explicitly set these environment variables to point to a specific version in the `Wwise Launcher` application).  Usually this is sufficient.
  2. Alternatively, you can specify the Wwise path as a CMake variable `LY_WWISE_INSTALL_PATH`.  Setting this will take precedence over the environment variables listed above.

**Comment by galibzon** [comment]
@ouxiaoyang Please let us know if Following Eric's instructions helped you. Otherwise we can reopen this ticket.
