### ISSUE TITLE
Feature Request: Set Cursor Position Node : Script Canvas

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#11894]
**Is your feature request related to a problem? Please describe.**
There is no way to set the position of your cursor with script canvas 

**Describe the solution you'd like**
A good solution would be to have a new node in the same category as Get Cursor Position, and instead of having the output of the cursor position you would have an input of a Vector 2 to determine where on screen you want the cursor to be at. Utilizing the 0-1 percentage on the X and Y so for example, 0.5 for both X and Y would end up having the cursor set to the center of the viewport.

**Describe alternatives you've considered**
I have not come up with a good alternative so far, but if anyone has an idea I would love to hear about it with a comment below.

**Additional context**
The Vector 2 does not need to utilize the 0-1 value range, I just believe it would be the most user friendly for now into the future.

**Comment by lsemp3d** [comment]
`InputSystemCursorRequestBus` used to be exposed to the Behavior Context which enables this support but I can't find it, I'm unaware if someone removed it, or if it's in a gem that I don't currently have enabled. @AMZN-alexpete do you know?

**Comment by AMZN-alexpete** [comment]
`UiCursorBus` Has the following exposed to Behavior Context:
```
                ->Event("IncrementVisibleCounter", &UiCursorBus::Events::IncrementVisibleCounter)
                ->Event("DecrementVisibleCounter", &UiCursorBus::Events::DecrementVisibleCounter)
                ->Event("IsUiCursorVisible", &UiCursorBus::Events::IsUiCursorVisible)
                ->Event("SetUiCursor", &UiCursorBus::Events::SetUiCursor)
                ->Event("GetUiCursorPosition", &UiCursorBus::Events::GetUiCursorPosition)
```
That's one possible place to add `SetUiCursorPosition`

**Comment by ParasiteSt** [comment]
Hi @lsemp3d just wondering if there is an ETA on this? I am working on animations right now, but once this is possible I can move back to ui, as this feature is needed for the workflow the ui will be using.

**Comment by ParasiteSt** [comment]
Is it possible to set the cursor position in LUA? I am trying to make a workaround for now, but cannot find many docs on what is possible in LUA.
