### ISSUE TITLE
Delete physics levels from Automated testing project used only by disabled tests

### ISSUE THREAD

**Issue by greerdv** [o3de/o3de#11916]
The physics automated tests are currently largely or completely disabled pending a complete overhaul, which should include creating prefabs as part of the test rather than loading saved levels. This means there are a lot of stale levels which should be removed.

**Comment by lgleim** [comment]
@FuzzyCarterAWS Tagging you for visibility.  We discussed this issue in today's Sig-simulation triage meeting.  Is this something you may be able to look into during your work on testing?

**Comment by FuzzyCarterAWS** [comment]
@lgleim I suppose we could delete everything and use a branch that keeps the levels around for the refactor and test redesign for reference.

**Comment by greerdv** [comment]
Discussed in sig-simulation triage with @lgleim. That sounds like a good way to proceed @FuzzyCarterAWS. We might want to make a backup of the levels for reference in case they are not recoverable from git-lfs. However, I think they should only be used for reference because levels should be created in memory rather than loaded from disc when the tests are redesigned.
