### ISSUE TITLE
Landscape Canvas: Terrain node connections are not retained on re-opening a Landscape Canvas graph

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11917]
**Describe the bug**
Terrain node connections are not retained on re-opening a Landscape Canvas graph.

**Steps to reproduce**
1. Launch the Editor and open a new or existing level.
2. Open Landscape Canvas.
3. Drag a Terrain Layer Spawner to the graph area to create a new graph and node.
4. Click Add Extender on the Terrain Layer Spawner node and add a Terrain Height Gradient List extender.
5. Add a new Perlin Noise Gradient to the graph, and connect the Perlin Noise's Outbound Gradient slot to the Inbound Gradient slot on the Terrain Height Gradient List extender.
6. Close Landscape Canvas.
7. Click Edit button on the Landscape Canvas root entity.

**Expected behavior**
Connection remains drawn from the Perlin Noise's Outbound Gradient slot to the Inbound Gradient slot on the Terrain Height Gradient List extender.

**Actual behavior**
Connection is no longer drawn on graph re-open, though the reference remains set.

**Screenshots/Video**
![layerspawner_connections_missing](https://user-images.githubusercontent.com/82226555/189771907-a6e2ae18-04aa-484c-9328-016b8f86fe07.jpg)

**Found in Branch**
development@ ad8d7693c21e08fd040e79233518a42c10da98b1 

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by cgalvan** [comment]
Fixed by https://github.com/o3de/o3de/pull/12067
