### ISSUE TITLE
[Android] NavMesh levels do not load entities properly on Android device

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#11923]
**Describe the bug**
Levels with NavMesh entities deployed to an Android device do not load properly. Only the Navigator entity can be seen.
Levels under test are NavigationSample.prefab (AutomatedTesting level) and navtest3.prefab (custom created level based on the following Workflow https://github.com/o3de/sig-simulation/blob/main/testing-guidance/workflow-tests/ai/ai-lkg-workflows.md).

For further information please refer to the attached videos, screenshot and log files.

**Assets required**
[navtest3.zip](https://github.com/o3de/o3de/files/9555997/navtest3.zip)

**Prerequisites**
- AutomatedTesting project is built for Windows.
- Assets for the Android platform are enabled and processed.
- An autoexec.cfg file has been created inside the _/o3de/AutomatedTesting_ directory containing:
`LoadLevel Levels/Navigation/NavigationSample/NavigationSample.spawnable`
or
`LoadLevel Levels/navtest3/navtest3.spawnable`
- All the required environment variables are set as described in the instructions: https://o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/

In this test the following settings have been used:

```
SET O3DE_ENGINE_PATH=C:\o3de
SET O3DE_PROJECT_PATH=C:\o3de\AutomatedTesting
SET O3DE_BUILD_ROOT=C:\o3de-build
```
```
SET O3DE_ANDROID_SIGNCONFIG_FILE=%O3DE_BUILD_ROOT%\o3de.keystore
SET O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD=o3de_android
SET O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS=o3de_key
SET O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD=o3de_android
SET O3DE_ANDROID_SIGNCONFIG_KEY_SIZE=2048
SET O3DE_ANDROID_SIGNCONFIG_VALIDITY_DAYS=10000
SET O3DE_ANDROID_DN="cn=AutomatedTesting, ou=o3de, o=LF, c=US"
```
```
set O3DE_ANDROID_SDK_PATH=C:\Android\Sdk
set O3DE_ANDROID_NDK_VERSION=22.1.7171670
set O3DE_ANDROID_SDK_API_LEVEL=30
set O3DE_ANDROID_ASSET_MODE=LOOSE
set O3DE_ANDROID_DEPLOY_TYPE=BOTH
```

**Steps to reproduce**
1. Generate KeyStore to allow APK signing:
`keytool -genkey -keystore %O3DE_ANDROID_SIGNCONFIG_FILE% -storepass %O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD% -alias %O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS% -keypass %O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD% -keyalg RSA -keysize %O3DE_ANDROID_SIGNCONFIG_KEY_SIZE% -validity %O3DE_ANDROID_SIGNCONFIG_VALIDITY_DAYS% -dname %O3DE_ANDROID_DN%`
2. Use Python to run generate_android_project.py:
`%O3DE_ENGINE_PATH%\python\python.cmd %O3DE_ENGINE_PATH%\cmake\Tools\Platform\Android\generate_android_project.py --engine-root %O3DE_ENGINE_PATH% --project-path %O3DE_PROJECT_PATH% --build-dir %O3DE_BUILD_ROOT%\android --third-party-path %USERPROFILE%\.o3de\3rdParty --android-sdk-path %O3DE_ANDROID_SDK_PATH% --android-ndk-version %O3DE_ANDROID_NDK_VERSION% --android-sdk-platform %O3DE_ANDROID_SDK_API_LEVEL% --include-apk-assets --asset-mode %O3DE_ANDROID_ASSET_MODE% --signconfig-store-file %O3DE_ANDROID_SIGNCONFIG_FILE% --signconfig-store-password %O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD% --signconfig-key-alias %O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS% --signconfig-key-password %O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD%`
3. Build the Android project:
`cd %O3DE_BUILD_ROOT%\android`
`gradlew assembleProfile`
4. Deploy the GameLauncher to the Android device:
`%O3DE_ENGINE_PATH%\python\python.cmd %O3DE_ENGINE_PATH%\cmake\Tools\Platform\Android\deploy_android.py --build-dir %O3DE_BUILD_ROOT%\android --configuration profile --clean -t %O3DE_ANDROID_DEPLOY_TYPE%`
5. Launch the deployed GameLauncher.

**Expected behavior**
NavMesh levels load all entities properly on a device.

**Actual behavior**
Only the Navigator entity is loaded on a device.

**Screenshots/Video**
Windows NavigationSample:

https://user-images.githubusercontent.com/86953659/189878205-c4f84e16-ce93-4904-8f84-070eacfa7186.mp4

Android NavigationSample:
![NavigationSample_Android](https://user-images.githubusercontent.com/86953659/189878269-253a7428-8b96-4088-9c79-1c45e2ef8910.jpg)

Windows navtest3:

https://user-images.githubusercontent.com/86953659/189878337-26f79500-b7ef-49f9-b9e1-b8bf838a1623.mp4

Android navtest3:

https://user-images.githubusercontent.com/86953659/189878379-86fbc060-1f37-43dd-8190-cb77876f4068.mp4

**Found in Branch**
Stabilization/2210 (49b412d)

**Device**
 - Device: Samsung S20+
 - OS: Android
 - Version 11 (API 30)

**Additional context**
[logcat_NavigationSample_AutomatedTesting.txt](https://github.com/o3de/o3de/files/9556039/logcat_NavigationSample_AutomatedTesting.txt)
[logcat_navtest3_AutomatedTesting.txt](https://github.com/o3de/o3de/files/9556040/logcat_navtest3_AutomatedTesting.txt)

**Comment by forhalle** [comment]
@AMZN-Olex - Are you able to look into this?

**Comment by LB-KacperKapusta** [comment]
It has been observed that the described issue is still active and affects the Stabilization/2310 ([bc8eb66](https://github.com/o3de/o3de/commit/bc8eb66f885cfa99a444703792482f169692ffdc)) branch. This time, when compared to the original issue, the "Ground" White Box entity is visible, however, the "Obstacle" Mesh entities are still missing and the "Navigator" entity is not moving when the application is being run on an Android device:

https://github.com/o3de/o3de/assets/86953659/eb6a55fd-5bbf-4b77-91c9-5dbc0a0565f5


https://github.com/o3de/o3de/assets/86953659/bcda3575-3746-4492-a372-34716561b928

Please note that the deployed levels work fine when verified in the GameLauncher on Windows:


https://github.com/o3de/o3de/assets/86953659/5d9571bb-1396-41cb-84b3-2e09052ba3c4

Device under test: Samsung S20+ (API 30)
