### ISSUE TITLE
EMotionFX: Editor freezes after modifying Actor

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#11925]
**Describe the bug**
Modifications made inside the Animation Editor to the corresponding Actor that is present in the Viewport freezes the Editor.

This issue does NOT repro on Rin in the AutomatedTesting Project.

**Assets required**
Rin actor from MotionMatching gem.

**Steps to reproduce**
1. Create an entity with Actor component.
2. Add Rin as actor.
3. Open the Animation Editor
4. Open Rin actor.
5. Change Layout to Physics
6. Add Ragdoll joints.
7. Save all changes.
8. Wait a few seconds.

**Expected behavior**
The Editor remains stable, changes are saved.

**Actual behavior**
The Editor freezes after a few seconds.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/189910955-f8cd7c5d-f568-4d99-b4b9-f38f1d1bd9f1.mp4

**Found in Branch**
Stabilization/2210 (021d32a)
Development (511a88c)

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU Nvidia GeForce RTX 2060 SUPER
Memory 16GB

**Additional info:**
No logs were generated.

**Comment by amzn-rhhong** [comment]
Wasn't able to repo this one. Can you pause it in visual studio and see what thread / stack it is stuck at?

**Comment by amzn-rhhong** [comment]
@LB-JakubSkoczylas can you try copying the rin asset to automated testing project and see it that also trigger the freeze? also could you perhaps upload the version that trigger the freeze. Thanks!

**Comment by greerdv** [comment]
I could maybe believe it might be related to my changes if it froze while modifying the joints, but I don't immediately see how freezing while saving could be related.

**Comment by LB-JakubSkoczylas** [comment]
I am unable to upload Rin.fbx here (file format not supported) that I used for tests, but this is Rin.fbx from MotionMatching gem. No modifications needed. Also, in AT Project the freeze does not occur.

**Comment by hultonha** [comment]
@LB-JakubSkoczylas if you just add .txt to the asset and then upload the it'll work and we can then download and rename. That could help @amzn-rhhong debug the issue. Thanks!

**Comment by LB-JakubSkoczylas** [comment]
Added .txt extension. Hope it will help you.
[Rin.txt](https://github.com/o3de/o3de/files/9565508/Rin.txt)

**Comment by amzn-rhhong** [comment]
@LB-JakubSkoczylas what project you are running has this issue?

**Comment by LB-JakubSkoczylas** [comment]
I created my own Project with default settings plus MotionMatching gem. Also, verified this on Project with all gems enabled.

**Comment by greerdv** [comment]
I hit a deadlock in the animation editor yesterday which may possibly be the same problem. @amzn-tommy has more details.

**Comment by amzn-tommy** [comment]
This is fixed in stabilization with https://github.com/o3de/o3de/pull/12286, and should be fixed in development after the next stabilization->development merge.

**Comment by hultonha** [comment]
Awesome news, thanks @amzn-tommy!

**Comment by LB-JakubSkoczylas** [comment]
This issue no longer occurs. Verified this on build Stabilization/2210 (731cff1).
