### ISSUE TITLE
[FEATURE REQUEST] Sensible defaults for memory/core limits on MSVC

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de#11931]
**Is your feature request related to a problem? Please describe.**

In some development environments, the MSVC compiler defaults for threading cause the dreaded **fatal error C1060: compiler is out of heap space** (see https://github.com/o3de/o3de.org/issues/949, https://github.com/o3de/o3de/discussions/2077). [Microsoft has guidance on which command-line flags to pass in these situations](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1060?redirectedfrom=MSDN&view=msvc-160) and the discussion contained some information about why O3DE pushes up against these limits:

* The 32-bit toolchain is in use for O3DE.
* Each compilation thread takes around 2Gb.
* MSVC defaults are to consume _all available logical cores_.
* MSVC requires frobbing both `/m` and `/p:CL_MPCount` by the user to constrain compilation, and relies on the users doing some napkin math based on system spec to find appropriate bounds for these settings. Each `k` cores in use takes about `2*k` Gb of memory, so users need to understand the subtleties between `/m` and `CL_MPCount` in particular.
* Swap thrashing is real, meaning swap needs to be appropriately managed and users are likely to require SSD/NVME drives for speedy compilation when pushing the limits of their system memory. This affects the napkin math in, again, subtle ways.

While users can toggle these values manually (and should always be able to), it would be good for O3DE build to set "sensible defaults" better than the MSVC defaults.

**Describe the solution you'd like**

The best solution is to provide "sensible defaults" for `/m` and `CL_MPCount` by doing the napkin math for the user. CMake should have reasonable support for detecting system spec information with regards to core/RAM. Depending on how options are passed to the compiler and interpreted, this may require a new CMake cache variable to turn off (should be on by default.) This should help reduce (but will probably not eliminate) C1060 errors.

**Describe alternatives you've considered**

Moving to a 64-bit toolchain _could_ resolve some of these issues, but is clearly a much larger undertaking. Another alternative is to handle this through _documentation only_ but would require, again, providing the napkin math information for users to do it themselves in CPU/RAM-bound situations. Such documentation would also require regular updates, making it difficult to maintain and keep accurate.

**Additional context**

It's _unclear_ if this feature is needed for Linux systems; Clang tends to play nicer with threading constraints and Linux swap is less volatile than Windows swap under heavy memory pressure.

**Comment by lumberyard-employee-dm** [comment]
The 32-bit toolchain isn't for use for O3DE.
Only the 64-bit toolset is available.

Also using VS2022, it is a 64-bit application, so it is allowed to use more than 4GiB.

**Comment by sptramer** [comment]
My mistake on the 32b toolchain - I saw some reference to it in the old thread.

Obviously there are ways for the user to set appropriate configurations through Visual Studio or as a command-line option; This is just a feature proposal to handle the napkin math without a user having to engage with doing it themselves. That the MSVC defaults are "use everything" is a compelling argument for O3DE's default being "use everything", but at the same time, most people aren't building a project of this scale. C1060 is a real killer for heavily templatized projects in particular.

I should add one other detail - this issue occurred for me under both unity and non-unity builds, although unity builds did tend to choke out sooner.

**Comment by lumberyard-employee-dm** [comment]
> My mistake on the 32b toolchain - I saw some reference to it in the old thread.
> 
> Obviously there are ways for the user to set appropriate configurations through Visual Studio or as a command-line option; This is just a feature proposal to handle the napkin math without a user having to engage with doing it themselves. That the MSVC defaults are "use everything" is a compelling argument for O3DE's default being "use everything", but at the same time, most people aren't building a project of this scale. C1060 is a real killer for heavily templatized projects in particular.
> 
> I should add one other detail - this issue occurred for me under both unity and non-unity builds, although unity builds did tend to choke out sooner.

Well because we have support for [CMakePresets](https://github.com/o3de/o3de/blob/development/CMakePresets.json).
We can provide build presets with a customized arguments to supply to msbuild which doesn't attempt to use all the machines cores. The cmake-presets Build Preset supports a [nativeToolOption](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html?highlight=presets#build-preset) field, where msbuild options such as `/m` or `/p:CL_MPCount` can be specified.

We could add have presets such as `windows-default-6-core-max`, `windows-default-12-core-max`, etc...
by updating our Windows [CMakePresets.json](https://github.com/o3de/o3de/blob/development/cmake/Platform/Windows/CMakePresets.json#L123-L132) file
Such as
```JSON
    "buildPresets": [
        {
            "name": "windows-default-6-core-max",
            "displayName": "Windows",
            "description": "Builds all targets for Windows",
            "configurePreset": "windows-default",
            "inherits": [
                "host-windows"
            ],
            "nativeToolOptions": [
                "/m:6
            ]
        },
        ...
```

**Comment by sptramer** [comment]
Wasn't aware of the presence of CMake presets files - that opens up the options a bit more and gives us the choice to keep it purely a documentation issue, advising users on how to create their own presets file, with some "recommended" settings for various common specs that users report.

**Comment by lumberyard-employee-dm** [comment]
I think it would be useful, to provide some Cache Variables, that can be used to allow the user to
1. set the `/m:<number>` option if enabled (`O3DE_COMPUTE_MULTICORE_COUNT`).
2. Configure how much memory per core they would like to use(we can default this to a specific amount such as 2 GiB (`O3DE_MEMORY_PER_CORE`)
3. Configure how many cores they would would like to use(we can default this to a value such as 75%) (`O3DE_CORES_TO_USE`).
