### ISSUE TITLE
Outdated o3de logo is used for remote Project and remote Template icons

### ISSUE THREAD

**Issue by LB-KrzysztofPinkowski** [o3de/o3de#11971]
**Describe the bug**
The icon of remote Template in Project Manager has outdated o3de logo. The same issue is observed when the remote Project is deleted without deleting the Remote Source.

**Steps to reproduce**
1. Open Project Manager.
2. Open "New Project" menu.
3. Select "Add Remote Project".
4. Download a valid remote Project.
5. Delete the remote Project.
OR
1. Open Project Manager.
2. Open "New Project" menu.
3. Select "Create a New Project".

**Expected behavior**
A current O3DE logo is used for remote Project and remote Template icons.

**Actual behavior**
Outdated O3DE logo is used for the remote Project and remote Template icons.

![outdated_icon1](https://user-images.githubusercontent.com/110379578/190168440-25c5fd91-4385-44e1-94bb-5b1e62973b46.PNG)
![outdated_icon2](https://user-images.githubusercontent.com/110379578/190168471-f92cf3b2-8458-4846-93d5-5fdde7623de4.PNG)

**Found in Branch**
Development (5f71fd1)
Stabilization/2210 (04e3edb)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 5600H
 - GPU NVIDIA GeForce RTX 3070 Laptop GPU
 - Memory 16GB

**Comment by monroegm** [comment]
Fixed by #12086

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as Fixed in Stabilization/2210 (7fa9f5d), however it still occurs in Development (6b9465d).
