### ISSUE TITLE
Bug Report: Automated Periodic Failure bug reports do not auto assign to a SIG or lack `needs-sig` label

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#11974]
**Describe the bug**
All issues need to be routed to a SIG for triage, issues that do not have a SIG or a clear path to triage with `needs-sig` label, will not be correctly triaged.

Right now automated testing failures are being cut without either a SIG (as extracted from codeowners file) or a `needs-sig` label so they will not be correctly triaged.

For example https://github.com/o3de/o3de/issues/11950 

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Go to https://github.com/o3de/o3de/issues?q=is%3Aissue+is%3Aopen+label%3Aperiodic_failure%2Fdevelopment

**Expected behavior**
All issues are cut with a SIG assigned for triage or the `needs-triage` label

**Actual behavior**
Periodic failure issues are cut:
* Without the correct triage labels
* Without titles that allow for rapid triage 

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
N/a

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Monterey, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by Kadino** [comment]
Autocut tool is maintained by @o3de/sig-build ...and this is notably similar to https://github.com/o3de/o3de/issues/11985

**Comment by dshmz** [comment]
Build SIG has triaged this issue. Shirang from Build SIG is working on Auto Assigning the Git Hub Issues to their particular SIGs and he will take up this along with that work.

**Comment by lmbr-pip** [comment]
@shirangj Believe this has been addressed and can be closed out

**Comment by shirangj** [comment]
Adding the ‘needs-sig’ label has been done, but auto-assign the GHI is still in progress, I think we can close this one
