### ISSUE TITLE
Script Canvas does not receive On Graph Start or On Entity Activated when on a LyShine UI entity

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#11988]
**Describe the bug**
On Graph Start and On Entity Activated nodes are not fired when a script is on a UI entity.

**Assets required**
AutomatedTesting project, Navigation/NavigationSample level

**Steps to reproduce**
1. Create a UI Canvas Asset Ref
![image](https://user-images.githubusercontent.com/5432499/190248753-2d9a2578-69e1-4d94-a222-07ff7b4301e0.png)

2. In UI Editor place a script canvas component on an element in a UI canvas
![image](https://user-images.githubusercontent.com/5432499/190248914-da080c0d-287c-4583-9497-d2ee3f1665c1.png)

3. Attempt to start a script from On Graph Start or On Entity Activated events
![image](https://user-images.githubusercontent.com/5432499/190249059-5326c931-e347-4156-bb20-7d8e5fbeca3a.png)

4. Save and run the game in the Editor with ctrl-g

**Expected behavior**
Print nodes print to the console or game actions from those nodes are fired.

**Actual behavior**
On Graph Start or On Entity Activated are not fired.

I found that this only works if I open the UI Editor with that canvas, then those events are fired otherwise they do not fire.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Comment by monroegm** [comment]
@michabr Is this supported behavior?

**Comment by AMZN-Olex** [comment]
FYI: this is currently blocking the use of SC in UI. And in turns breaks Navigation Sample level in Automated Testing project that tests Recast Navigation gem.

**Comment by AMZN-Olex** [comment]
Something fixed it since last week. Win!
