### ISSUE TITLE
O3DE 22.10.0 Release: Core Features Grid Updates 

### ISSUE THREAD

**Issue by vincent6767** [o3de/o3de#12006]
Hi @amzn-pratikpa @lumberyard-employee-dm  (sorry I don't know your GitHub username)

As part of the 22.10.0 release action, we need your help to update [the features grid](https://www.o3de.org/docs/release-notes/archive/22-05-0/feature-state/) with the latest updates. [Here ](https://github.com/o3de/community/tree/main/features)is the repo that contains the features grid. There is also instruction on how to update the features grid in the readme file. Can we have this completed by September 23rd, 2022? Once you have completed it, please close the ticket and move it to "Pre-Release - Done". Let me know if you have any questions!

**Comment by lumberyard-employee-dm** [comment]
This is now up for PR

**Comment by vincent6767** [comment]
Thanks @lumberyard-employee-dm ! I think this will be merged together with 22.10.0. Can you confirm? @tonybalandiuk

**Comment by tonybalandiuk** [comment]
@vincent6767  I'm not sure.
@chanmosq do you know the process for bringing in a snapshot of the feature grid for the release? Typically it's part of the release notes. @Ulrick28  may know as well.

**Comment by chanmosq** [comment]
@vincent6767 The instructions here might help: https://github.com/o3de/community/tree/main/features

**Comment by vincent6767** [comment]
Thanks @chanmosq ! I'll share this with the SIG members.
