### ISSUE TITLE
O3DE 22.10.0 Release: UI/UX Features Grid Updates

### ISSUE THREAD

**Issue by vincent6767** [o3de/o3de#12005]
Hi @rainbj and @yuyihsu ,

As part of the 22.10.0 release action, we need your help to update [the features grid](https://www.o3de.org/docs/release-notes/archive/22-05-0/feature-state/) with the latest updates. [Here ](https://github.com/o3de/community/tree/main/features)is the repo that contains the features grid. There is also instruction on how to update the features grid in the readme file. Can we have this completed by September 23rd, 2022? Once you have completed it, please close the ticket and move it to "Pre-Release - Done". Let me know if you have any questions!

**Comment by rainbj** [comment]
@yuyihsu for visibility

**Comment by vincent6767** [comment]
Hi @rainbj and @yuyihsu, are there any updates?

**Comment by amzn-leenguy** [comment]
I have updated this @vincent6767 sorry for the delay!

**Comment by vincent6767** [comment]
No worry! Can you link your PR to the community repo? @amzn-leenguy

**Comment by amzn-leenguy** [comment]
> No worry! Can you link your PR to the community repo? @amzn-leenguy

Oops. it seems that my file upload didn't go through properly. I am pretty new to Github. Can you help me make the PR? Thanks

[SIG-UI-UX-Development-21.11.2.json.zip](https://github.com/o3de/o3de/files/9669048/SIG-UI-UX-Development-21.11.2.json.zip)

**Comment by amzn-leenguy** [comment]
I have just updated the sig ui ux file directly on github. it has updated the content on the form grey form page. But i am waiting to see it update on the webpage seen here: https://www.o3de.org/docs/release-notes/archive/22-05-0/feature-state/

**Comment by vincent6767** [comment]
Alright. Thanks for the confirmation. I'll close the ticket for now then.

**Comment by rainbj** [comment]
@amzn-leenguy thanks for working on this.

**Comment by amzn-leenguy** [comment]
> @amzn-leenguy thanks for working on this.

Thanks should go out to @AMZN-daimini as well. He did 51% of the work.
