### ISSUE TITLE
Editor crashes in AZ::TraskGraphEvent::Signal occasionally

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#12015]
**Describe the bug**
Occasionally the following crash occurs in the Editor:

```
>	[Inline Frame] EditorLib.dll!std::_Atomic_storage<int,4>::compare_exchange_strong(int &) Line 1038	C++
 	[Inline Frame] EditorLib.dll!std::atomic<int>::compare_exchange_weak(int & _Desired, const int) Line 2360	C++
 	EditorLib.dll!AZ::TaskGraphEvent::Signal() Line 42	C++
 	EditorLib.dll!AZ::Internal::CompiledTaskGraph::Release() Line 88	C++
 	EditorLib.dll!AZ::Internal::TaskWorker::Run() Line 276	C++
 	EditorLib.dll!AZStd::Internal::thread_run_function(void * param) Line 38	C++
```

![parallel_stacks_of_editor_crash_in_dev](https://user-images.githubusercontent.com/5432499/190493586-0228d1bf-1019-4b6d-af1a-ab997d96081f.png)

**Assets required**
Was seen in o3de-multiplayersample level

**Steps to reproduce**
1. use the Editor with vulkan backend on Windows

**Actual behavior**
Occasionally a crash occurs in the Editor.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Additional context**

[Editor.log](https://github.com/o3de/o3de/files/9578475/Editor.log)

**Comment by AMZN-Olex** [comment]
I let the Editor run for a while, after I came back from lunch, I saw the debugger greet me.

**Comment by tonybalandiuk** [comment]
We are ok to ship the release with this. "It took around 48hours of leaving the Editor running to catch the event." It is not a frequent issue from what we have seen. @chanmosq  please add to known issues. @AMZN-Dk  FYI.

**Comment by chanmosq** [comment]
Added to known issues: 
> - Editor crashes in `AZ::TraskGraphEvent::Signal` occasionally. [#12015](https://github.com/o3de/o3de/issues/12015)

**Comment by rgba16f** [comment]
This should be fixed in development now. PR [#12080 ](https://github.com/o3de/o3de/pull/12080) has been submitted

**Comment by rgba16f** [comment]
@AMZN-Olex can you validate you no longer see the issue with the fix?
