### ISSUE TITLE
Creating a prefab requires the user to save the level twice

### ISSUE THREAD

**Issue by forkercat** [o3de/o3de#12013]
**Describe the bug**

Creating a prefab requires the user to save the level twice

**Steps to reproduce**
1. Open any level
2. Create an entity and select it
3. Create a prefab for the entity
4. Hit Ctrl+S or file->save. Notice that the level is still marked dirty
5. Hit Ctrl+S again. Notice that it is saved now.

**Expected behavior**
Level is not marked dirty after hitting ctrl+s for the first time.

**Actual behavior**
Level is still marked dirty after hitting ctrl+s for the first time.

**Found in branch**
stabilization/2210 and development

**Comment by ParasiteSt** [comment]
A second case of this is when you already have a prefab created and alter the prefab. Once altered if you save the level it will save the prefab's changes, but not the level, a second save is needed for the level here as well.

**Comment by forkercat** [comment]
> A second case of this is when you already have a prefab created and alter the prefab. Once altered if you save the level it will save the prefab's changes, but not the level, a second save is needed for the level here as well.

From what I understand in the workflow, the right state after create-prefab operation is only the level is marked as dirty, not the prefab itself. The prefab does not need to be saved because it was already saved to disk in this operation. In-memory and on-disk representations should be in sync already.

**Comment by ParasiteSt** [comment]
Ok, I understand what your saying now. I misunderstood the issue, yes these two are unrelated, and you are correct that the level is all that should need to be saved after creating a prefab as that prefab is not dirty upon creation (or at least it shouldn't be.)
