### ISSUE TITLE
ProcPrefab issues with complex Hierarchy with empty transforms and child transforms with local transforms.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#12021]
**Describe the bug**
A clear and concise description of what the bug is. Try to isolate the issue to help the community to reproduce it easily and increase chances for a fast fix.

Hierarchy works great if all the mesh transforms pivots are 0,0,0.
![image](https://user-images.githubusercontent.com/87207603/190502948-33e22611-192e-435f-a09d-27faa77a8465.png)

When Exporting a model with a more complex Hierarchy, where I might have Parents with 0,0,0 Transforms, but have child meshes with Pivots that are local, customized positions for a custom pivot point.
![image](https://user-images.githubusercontent.com/87207603/190503246-8a102baa-425a-48d5-a33f-9f4fa25f4530.png)

This is where issues are shown.
![image](https://user-images.githubusercontent.com/87207603/190502388-7e27a84f-8395-4d5e-9a4e-ff7e0e12ad60.png)

If I where to just export the meshes with no empty transform parents:
![image](https://user-images.githubusercontent.com/87207603/190503654-2093a136-f0fe-4718-b3c7-19e83d0af50d.png)

If I open the failed export in Maya with the complex transforms it will import correctly:
![image](https://user-images.githubusercontent.com/87207603/190503972-ce792420-a99d-405b-b695-527f4e4f3b36.png)

Here is the complex test file used: (I created this file)
[RobotCart_Complex.zip](https://github.com/o3de/o3de/files/9578857/RobotCart_Complex.zip)

I did a simple test model which work correctly:
![image](https://user-images.githubusercontent.com/87207603/190505218-bc467d20-a9d7-4623-8801-5c970183f92b.png)
![image](https://user-images.githubusercontent.com/87207603/190505471-99600738-bc5b-4c50-9588-590a0b9e2781.png)

Detaching, everything looks correct.
![image](https://user-images.githubusercontent.com/87207603/190505655-7fbde719-8708-4d79-9dfa-472839d54b15.png)
Here is the file: 
[Simple_Complex.zip](https://github.com/o3de/o3de/files/9578936/Simple_Complex.zip)

Would be interesting to see what caused the car to flip while the simple model is successful. 

**Steps to reproduce**
1. Build a model with a complex Hierarchy
2. Import into o3de with a procedural prefab. 

**Expected behavior**
Model transforms, even if they are not 0,0,0 are respected.

**Actual behavior**
Model will flip, however when testing in another tool such as Maya, the Blender file is correct.

**Found in Branch**
Nightly 9-15-2022

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPUIntel I9-9900k
 - GPU NVidia RTX 2080ti
 - Memory [e.g. 16GB]

**Additional context**

**Comment by tonybalandiuk** [comment]
Does this exist in stabilization? If so, do you think this needs to be resolved in the upcoming release? If so, we should add it to the "Release/2210" milestone. If not, please add it to the "Backlogged Issues" milestone. Thanks. @AMZN-Dk  and I are working to understand what's still required to fix for the upcoming release - your assistance here will help us in that endeavor.
