### ISSUE TITLE
O3DE 22.10.0 Release: Build Features Grid Updates

### ISSUE THREAD

**Issue by vincent6767** [o3de/o3de#12032]
Hi @dshmz @amzn-changml  ,

As part of the 22.10.0 release action, we need your help to update [the features grid](https://www.o3de.org/docs/release-notes/archive/22-05-0/feature-state/) with the latest updates. [Here ](https://github.com/o3de/community/tree/main/features)is the repo that contains the features grid. There is also instruction on how to update the features grid in the readme file. Can we have this completed by September 23rd, 2022? Once you have completed it, please close the ticket and move it to "Pre-Release - Done". Let me know if you have any questions!

**Comment by vincent6767** [comment]
hi @dshmz @amzn-changml , are there any updates?

**Comment by amzn-changml** [comment]
Hi, there are no current updates for this release. All current work are bug fixes or cross-cutting initiatives not directly related to the SIG-Build roadmap. I will close issue and move it to done.
