### ISSUE TITLE
[Android] The .log files are not properly generated on the device after running the app

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#12039]
**Describe the bug**
After execution of the app folder (\Card\Android\data\org.o3de.DefaultProject\files) remains completely empty, showing 0 files inside.
Folder (\Phone\Android\data\org.o3de.DefaultProject\files\user\log) has Game.log file inside, but also completely empty (0 bytes).

Please refer to the attached screenshots.

**Prerequisites**
- Follow Project Requirements and either the "Assets in APK or Assets in sdcard" Workflow from https://github.com/moraaar/sig-platform/blob/Andoid_LKG_Workflow/testing-guidance/workflow-tests/android/android-lkg-workflows.md.

**Steps to reproduce**
1. Launch the deployed DefaultProject app.
2. After a while close the application.
3. Look for the .log files in directories mentioned in the description.

**Expected behavior**
Log files are correctly generated.

**Actual behavior**
Log files are not generated.

**Screenshots**
![sdcard_log](https://user-images.githubusercontent.com/86953659/190643138-b5c280a0-a58a-4720-a2b0-3f72c5c17728.PNG)
![phone_log](https://user-images.githubusercontent.com/86953659/190643151-4071f1dd-c12b-469f-936c-cf5fcb303d09.PNG)

**Found in Branch**
Development 511a88c

**Device**
 - Device: Samsung S20+
 - OS: Android
 - Version 11 (API 30)

**Comment by forhalle** [comment]
@moraaar - Can you see if the logs are perhaps generated in a different path (and perhaps the docs need to be updated?)?

**Comment by moraaar** [comment]
Yeah, I will verify it on my next Android execution.

**Comment by LB-KacperKapusta** [comment]
It has been observed using Development (ce8bfb7) build that after executing the "Assets in sdcard" packaging mode, the game.log was properly generated inside the "\Phone\Android\data\org.o3de.DefaultProject\files\user\log" folder - no longer being 0 bytes.
