### ISSUE TITLE
O3DE 22.10.0 Release: Content Features Grid Updates

### ISSUE THREAD

**Issue by vincent6767** [o3de/o3de#12031]
Hi @monroegm and @lsemp3d , 

As part of the 22.10.0 release action, we need your help to update [the features grid](https://www.o3de.org/docs/release-notes/archive/22-05-0/feature-state/) with the latest updates. [Here ](https://github.com/o3de/community/tree/main/features)is the repo that contains the features grid. There is also instruction on how to update the features grid in the readme file. Can we have this completed by September 23rd, 2022? Once you have completed it, please close the ticket and move it to "Pre-Release - Done". Let me know if you have any questions!

**Comment by vincent6767** [comment]
Hi @monroegm and @lsemp3d , are there any updates?

**Comment by vincent6767** [comment]
Hi @monroegm and @lsemp3d , are there any updates around this? We need this to be completed before the communication goes out on October 13th. Target to complete October 7th.

**Comment by vincent6767** [comment]
Talked with @monroegm He will take a look at it by this week.

**Comment by monroegm** [comment]
Posted a PR with partial updates. Need to meet with @hultonha next week to update the remaining sections

**Comment by vincent6767** [comment]
Can we complete this by October 10th or 11th? @monroegm @hultonha 

CC: @chanmosq @aFinchy FYI.

**Comment by hultonha** [comment]
Please see this PR with updates for Viewport and White Box - https://github.com/o3de/community/pull/165 @vincent6767

**Comment by vincent6767** [comment]
Thanks! I have asked @chanmosq help to review it.
