### ISSUE TITLE
O3DE 22.10.0 Release: Testing Features Grid Updates

### ISSUE THREAD

**Issue by vincent6767** [o3de/o3de#12033]
Hi @Kadino @AMZN-Dk  ,

As part of the 22.10.0 release action, we need your help to update [the features grid](https://www.o3de.org/docs/release-notes/archive/22-05-0/feature-state/) with the latest updates. [Here ](https://github.com/o3de/community/tree/main/features)is the repo that contains the features grid. There is also instruction on how to update the features grid in the readme file. Can we have this completed by September 23rd, 2022? Once you have completed it, please close the ticket and move it to "Pre-Release - Done". Let me know if you have any questions!

**Comment by AMZN-Dk** [comment]
No updates from me since last release on the SIG Testing feature grid, @Kadino take a look and see if there are any from you.

**Comment by Kadino** [comment]
The table is a bit inaccurate, so I'm updating it.

**Comment by Kadino** [comment]
Submitted for approval in @o3de/sig-docs community repo
