### ISSUE TITLE
Project Manager: Unable to cancel project build

### ISSUE THREAD

**Issue by AMZN-Phil** [o3de/o3de#12059]
There is no way to cancel a currently building project.

**Steps to reproduce**
1. Start a project build
2. See available actions.

**Expected behavior**
A cancel build button is visible while a project is building which cancels the project.

**Actual behavior**
No cancel button is visible.

**Comment by tonybalandiuk** [comment]
@AMZN-Phil looks like some condition in GHI behind the scenes is not being met to automatically close this issue upon merge of the PR. I'm closing it.
