### ISSUE TITLE
Landscape Canvas: Allow adding wrapped nodes via script without creating new entities

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#12079]
**Is your feature request related to a problem? Please describe.**
Currently, when using the following code, rather than simply becoming wrapped nodes, new entities are created to hold the new node information, resulting in a lot of unwanted duplication.

```
            extenderNode = landscapecanvas.LandscapeCanvasNodeFactoryRequestBus(bus.Broadcast,
                                                                                'CreateNodeForTypeName', newGraph,
                                                                                extenderName)
            graph.GraphControllerRequestBus(bus.Event, 'WrapNode', newGraphId, areaNode, extenderNode)
```

**Describe the solution you'd like**
Some way to specify a node to be created/wrapped at the same time, so new entities aren't created for nodes that the user wishes to be wrapped.

**Comment by cgalvan** [comment]
I've added a fix (https://github.com/o3de/o3de/pull/12174) where you will now be able to use the existing API above to call `WrapNode` on a newly created node and it won't trigger a new entity being created in Landscape Canvas. We no longer need to call `AddNode` before `WrapNode`. There was actually already logic in GraphModel that properly adds the node to the graph when you call `WrapNode` if it wasn't already.
