### ISSUE TITLE
Non-zero return code after test success when running MaterialCanvas automated tests (successes should return exit code 0).

### ISSUE THREAD

**Issue by jromnoa** [o3de/o3de#12152]
**Describe the bug**
Exit code 0xc0000005 is being returned from the MaterialCanvas automated tests referencing a crash in C:/git/o3de/Gems/AtomTressFX/Code/Passes/HairGeometryRasterPass.cpp. The tests are not yet merged to our repo but are currently in a PR: https://github.com/o3de/o3de/pull/11915 
I may mark the tests skip if the bug is hard to fix or requires substantial time. I can remove the skip once this bug is fixed.

**Assets required**
You just need the MaterialCanvas program built and have the ability to launch python automated tests locally. Also make sure to process the assets before running the test so that no timeout failures occur during the automated test run.

**Steps to reproduce**
1. Run the test from https://github.com/o3de/o3de/pull/11915 locally (its the first automated MaterialCanvas test): `C:\git\o3de\python\runtime\python-3.10.5-rev1-windows\python\python.exe -m pytest -vv -s --build-directory="C:\git\o3de\build\bin\profile" C:\git\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_Null_Render_MaterialCanvas_01.py`
2. Observe the test output (side note: the test doesn't really do anything other than run MaterialCanvas, verify it launched, then closes it so I 'm not sure why the HairGeometryRasterPass.cpp code would cause a non-zero return code on exit since there are no visible errors during the run).

**Expected behavior**
 An exit code of 0 success is generated with no log errors.

**Actual behavior**
An exit code of 0xc0000005 is returned with a crash referencing C:/git/o3de/Gems/AtomTressFX/Code/Passes/HairGeometryRasterPass.cpp:
```
E   Starting test MaterialCanvas_Launched_SuccessfullyLaunched...
E   Test MaterialCanvas_Launched_SuccessfullyLaunched finished.
E   Report:
E   [SUCCESS] Success: Inspector pane is visible, MaterialCanvas launch succeeded
E   Test result:  SUCCESS
E   JSON_START({"name": "MaterialCanvas_Atom_LaunchMaterialCanvas", "success": true, "exception": null, "output": "Test MaterialCanvas_Launched_SuccessfullyLaunched finished.\nReport:\n[SUCCESS] Success: Inspector pane is visible, MaterialCanvas launch succeeded\nTest result:  SUCCESS"})JSON_END
E   Starting test MaterialCanvas_Launched_SuccessfullyLaunched...
E   Test MaterialCanvas_Launched_SuccessfullyLaunched finished.
E   Report:
E   [SUCCESS] Success: Inspector pane is visible, MaterialCanvas launch succeeded
E   Test result:  SUCCESS
E   JSON_START({"name": "MaterialCanvas_Atom_LaunchMaterialCanvas", "success": true, "exception": null, "output": "Test MaterialCanvas_Launched_SuccessfullyLaunched finished.\nReport:\n[SUCCESS] Success: Inspector pane is visible, MaterialCanvas launch succeeded\nTest result:  SUCCESS"})JSON_END
E
E   ----------------------------------------------------
E   | Executable (i.e. Editor or MaterialEditor) log  |
E   ----------------------------------------------------
E
E   [material_editor_test.log]  2022-09-21T17:18:07{0000000000004E04}[      Hair Gem]
E   [material_editor_test.log]  ==================================================================
E   [material_editor_test.log]  2022-09-21T17:18:07{0000000000004E04}[      Hair Gem]     Trace::Error
E   [material_editor_test.log]   C:/git/o3de/Gems/AtomTressFX/Code/Passes/HairGeometryRasterPass.cpp(145): 'bool __cdecl AZ::Render::Hair::HairGeometryRasterPass::LoadShaderAndPipelineState(void)'
E   [material_editor_test.log]  2022-09-21T17:18:07{0000000000004E04}[      Hair Gem]     Scene could not be acquired
E   [material_editor_test.log]  2022-09-21T17:18:07{0000000000004E04}[      Hair Gem]     ==================================================================
E   [material_editor_test.log]  2022-09-21T17:18:07{0000000000004E04}[      Hair Gem]
E   [material_editor_test.log]  ==================================================================
E   [material_editor_test.log]  2022-09-21T17:18:07{0000000000004E04}[      Hair Gem]     Trace::Error
E   [material_editor_test.log]   C:/git/o3de/Gems/AtomTressFX/Code/Passes/HairGeometryRasterPass.cpp(145): 'bool __cdecl AZ::Render::Hair::HairGeometryRasterPass::LoadShaderAndPipelineState(void)'
E   [material_editor_test.log]  2022-09-21T17:18:07{0000000000004E04}[      Hair Gem]     Scene could not be acquired
E   [material_editor_test.log]  2022-09-21T17:18:07{0000000000004E04}[      Hair Gem]     ==================================================================
E   [material_editor_test.log]  2022-09-21T17:18:07{0000000000004E04}[        System]     Network layer shut down 
```

**Screenshots/Video**
N/A but can be provided if need be. The steps are straightforward.

**Found in Branch**
development branch from https://github.com/o3de/o3de @ commit id 402811b8d0cb626ee0606f2043bd8ef2fb2d47d

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - GPU: NVIDIA GeForce RTX 2080 with Max-Q Design
 - Memory: 16 GB

**Comment by gadams3** [comment]
@jromnoa Before I investigate this deeper, could you please make another attempt at running the test after your latest refactor is done? Looking at the logs in the issue, it looks like the material canvas tests are referencing material editor logs. Other than enabling or disabling graph canvas and graph model gems, the projects are set up in the same way. Running the same series of tests should return the same results.

**Comment by jromnoa** [comment]
@gadams3  Sure, I will update you after I finish the re-factor and re-run the tests.

**Comment by jromnoa** [comment]
@gadams3 As discussed, the re-factor did not address the underlying problem. Pushed re-factor update to https://github.com/o3de/o3de/pull/11915 and also marked the MaterialCanvas tests there as skip until we can resolve this issue. It appears that we're always getting a non-zero return code when using this code inside `multi_test_framework.py` and only when running MaterialCanvas tests (MaterialEditor works just fine):
```py
        elif type(executable) in [LinuxAtomToolsLauncher, WinAtomToolsLauncher]:
            log_path_function = editor_utils.atom_tools_log_path
            log_content_function = editor_utils.retrieve_non_editor_log_content
            cmdline = ["-runpythontest", test_filename,
                       "-logfile", os.path.join(log_path_function(run_id, workspace), log_name)] + test_cmdline_args
        executable.args.extend(cmdline)
        executable.start(backupFiles=False, launch_ap=False, configure_settings=False)

        try:
            executable.wait(test_spec.timeout)
            output = executable.get_output()
            return_code = executable.get_returncode()
            executable_log_content = log_content_function(run_id, log_name, workspace)
            # Save the executable log.
            workspace.artifact_manager.save_artifact(
                os.path.join(log_path_function(run_id, workspace), log_name), f'({run_id}){log_name}')
            if return_code == 0:
                test_result = Result.Pass(test_spec, output, executable_log_content)
            else:
                has_crashed = return_code != self._test_fail_retcode
 
```

Does not matter if its a batched test, single test, etc. I am never able to generate a success zero even when all tests pass for MaterialCanvas.
