### ISSUE TITLE
Crash in ImageProcessingAtom ImageProcessingSystemComponent::OpenSourceTextureFile

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#12166]
**Describe the bug**
Somehow when I double right clicked on the asset to open the texture settings `textureSourceID` was invalid which caused a crash in `AssetBrowserEntry::GetFullPath()`

Normally this doesn't crash, but this once randomly it did.  I think the Asset Processor may have been processing the asset when this happened.

Call stack:
``` 	
ImageProcessingAtom.Editor.dll!AzToolsFramework::AssetBrowser::AssetBrowserEntry::GetFullPath() Line 184	C++
 	ImageProcessingAtom.Editor.dll!ImageProcessingAtomEditor::EditorTextureSetting::EditorTextureSetting(const AZ::Uuid & sourceTextureId) Line 146	C++
 	ImageProcessingAtom.Editor.dll!ImageProcessingAtomEditor::TexturePropertyEditor::TexturePropertyEditor(const AZ::Uuid & sourceTextureId, QWidget * parent) Line 46	C++
>	ImageProcessingAtom.Editor.dll!ImageProcessingAtom::ImageProcessingSystemComponent::OpenSourceTextureFile(const AZ::Uuid & textureSourceID) Line 121	C++
 	[External Code]	
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserTableView::OnContextMenu(const QPoint & point) Line 187	C++
```
![image](https://user-images.githubusercontent.com/26804013/191882508-20be4d46-2df1-4f76-af73-1670bb491e5c.png)

**Assets required**
n/a

**Steps to reproduce**
1. Right click on a texture asset in the Asset Browser window while the asset is being processed.  Try a .exr file which takes a while to process

**Expected behavior**
No crash

**Actual behavior**
Crash

**Screenshots/Video**
n/a

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
n/a

**Comment by VickyAtAZ** [comment]
It's the same crash mentioned in this GHI (https://github.com/o3de/o3de/issues/13771)
It's fixed in this PR: https://github.com/o3de/o3de/pull/13886
