### ISSUE TITLE
Multiplayer: sv_isTransient Doesn't Shut Down Dedicated Server 

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#12198]
**Describe the bug**
sv_isTransient true should shut down the dedicated if all existing connections disconnect, but it doesn't

**Steps to reproduce**
1. Open ServerLauncher.exe
2. Set sv_isTransient true
3. Open and connect a client using your favorite method. Ex: open ImGui [home] > Multiplayer > Launch Local Client
4. Open the client console (~) and run the Disconnect command
5. Notice the server

**Expected behavior**
Server should shut down

**Actual behavior**
Server stays open even though there are 0 clients
![image](https://user-images.githubusercontent.com/32776221/192191104-4694b855-4d09-4036-805b-b00c8a4adbaa.png)

**Found in Branch**
Development latest

**Comment by allisaurus** [comment]
Triage note: consider renaming variable to make it clearer what behavior this effects (if true, dedicated should shut down), adding more explanation to docs

**Comment by lmbr-pip** [comment]
Split rename request to https://github.com/o3de/o3de/issues/12290

**Comment by AMZN-puvvadar** [comment]
It appears this CVAR does in fact clear the level, free resources and uninitializes the server but it does not actually terminate the process. This means the server would have to load a level and call 'host' again.

Calling 

`AzFramework::ApplicationRequests::Bus::Broadcast(&AzFramework::ApplicationRequests::ExitMainLoop);`

after the call to `Terminate` should lead to process termination.
