### ISSUE TITLE
Visual-nodes with data out flicker on first hover-over by cursor.

### ISSUE THREAD

**Issue by eyedoteye** [o3de/o3de#12208]
**Describe the bug**
Visual-nodes with data out flicker on first hover-over by cursor.

**Assets required**
No assets required. Occurs with any visual script.

**Steps to reproduce**
1. Drag a 'Multiply By Number' node or any node with a data out.
2. Deselect nodes.
3. Hover over node.
4. The node width will flicker.

**Expected behavior**
Visual nodes should not flicker when hovered over.

**Actual behavior**
Visual nodes flicker when hovered over.

**Screenshots/Video*
![O3DE BUG - GIF 2022-09-26 5-54-33 PM](https://user-images.githubusercontent.com/7110358/192387692-08fe0322-b427-4a88-8eb2-e1fd6ae6fe0b.gif)
*

**Found in Branch**
O3DE 22.05.0 Release

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 7 3700X
 - GPU: NVIDIA GeForce RTX 2060 SUPER
 - Memory: 16 GBytes DDR4

**Comment by ParasiteSt** [comment]
This issue has been solved, and will be in the new upcoming release. 
Here is the PR : https://github.com/o3de/o3de/pull/10952

**Comment by lsemp3d** [comment]
#10952
