### ISSUE TITLE
Prefab Can't Be Edited After Adding a Required Component Service

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#12225]
**Describe the bug**
If a prefab contains a component, and then that component is updated to require a new service, the prefab becomes un-editable. Users must delete the prefab, and create a new one.

**Steps to reproduce**
1. Create a new component
2. Add the new component to an entity and create prefab
3. Update the component to require a new component service 
```
static void GetRequiredServices(AZ::ComponentDescriptor::DependencyArrayType& required)
{
      required.push_back(AZ_CRC_CE("PhysicsRigidBodyService"));
}
```
6. Recompile, open editor, and open the prefab
7. Attempt to add the newly required service to the prefab

**Expected behavior**
Clicking on the "Add Required Component" button should populate a list of components that fulfil the service. Users can select the component to add and fix their prefab.

**Actual behavior**
You are unable to add any new components. Adding a new component appears to do nothing and is not actually added to the prefab

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development latest September 21 2022

**Comment by michabr** [comment]
Adding the required component worked properly in latest development branch when following the repro steps, so it looks like this is no longer an issue.
