### ISSUE TITLE
BaseColor incorrect

### ISSUE THREAD

**Issue by HogJonny-AMZN** [o3de/o3de#12227]
**Describe the bug**
Something seems fishy with this BaseColor value

StanrdardPBR, with Basecolor color swatch value: #323333
- this values sampled from a texture in photoshop
- the color swatch preview looks correct, the material visual preview does not
- closing and reopening does not correct this
![image](https://user-images.githubusercontent.com/23222931/192574240-ad2ad1ee-058b-41c6-ab57-3aa82a7aca0b.png)

BasePBR, with Basecolor color swatch value: #323333
- is not correct
- reopening does not correct
![image](https://user-images.githubusercontent.com/23222931/192574612-c1c5d979-250e-4ea6-b397-984ebd19a387.png)

BasePBR with texture (of the same color value)
- same material as above, only I reset the swatch to white, and loaded the texture (note: the texture preview is the correct color)
- related to another bug (the wysiwyg preview isn't working) the material is white (note: that after saving, the same materials preview in the asset browser looks correct)
![image](https://user-images.githubusercontent.com/23222931/192574971-3d3fa286-de15-4b18-936e-6f4f8e7d9197.png)

Close/Re-Open the material above (with texture)
- This does look correct (but it's more efficent to use a color swatch then a texture in some cases similar to this)
![image](https://user-images.githubusercontent.com/23222931/192575623-07039c34-2f54-4fc4-976d-365f7ddb50a2.png)

**Expected behavior**
BasePBR / StandardPBR looks the same whether color is the same value in swatch or texture input.
WYSIWYG material updated, no need to save and close/re-open material to correct.

**Actual behavior**
Use of color swatch values versus textures result in inconstant visuals.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win 11
 - CPU threadripper
 - GPU RTX 3070

**Comment by HogJonny-AMZN** [comment]
![MaterialEditor_tKT269jGiR](https://user-images.githubusercontent.com/23222931/192588780-fe03311f-b81d-4dc1-aeb8-13110aa62d6b.gif)

In this case here ....
the color swatch preview value closely matches the texture preview value 
they are slightly different, so there may be a rounding error?
![image](https://user-images.githubusercontent.com/23222931/192589116-3dce4032-22a5-49f7-af60-649e9fbb1d1b.png)

But if I lerp between two values that are effectively identical, the material response should be imperceptible.  This rubber material should be dark whether I use a the same value in a color swatch verus texture map.

**Comment by HogJonny-AMZN** [comment]
just the previews alone in sRGB screenspace, are slightly different

the preview for the color swatch is
![image](https://user-images.githubusercontent.com/23222931/192589796-8e10b19f-c5d9-4fb2-be55-ba16ba5eef45.png)

the color for the texture preview is
![image](https://user-images.githubusercontent.com/23222931/192589871-ebd8f64a-4db8-4a20-b1eb-74afce5b3563.png)

This indicates that it's possible errors have been introduced in color space conversions (before values even get to the material shading itself.)

**Comment by HogJonny-AMZN** [comment]
The texture preview color is correct, see this image below the where I sample the texture value directly in photoshop.
This indicates that in fact color value conversion with the color picker / color swatch is where the error is introduced.

![image](https://user-images.githubusercontent.com/23222931/192590926-d617615d-7aac-4b2a-aa8c-6867d4055473.png)

**Comment by galibzon** [comment]
Changed priority to critical. Assigned to @santorac and @gadams3 to start investigating in parallel if it’s an issue in the Material System or in the Material Editor.

**Comment by HogJonny-AMZN** [comment]
One of the issues in thi ticket, is isoltaed in this ticket (having to close, reopen a material to update visuals):
https://github.com/o3de/o3de/issues/12224

**Comment by santorac** [comment]
I thinks issue is a duplicate https://github.com/o3de/o3de/issues/11166

**Comment by santorac** [comment]
Okay, everything should be fixed now, except for "the color swatch preview value closely matches the texture preview value,
they are slightly different, so there may be a rounding error?". That one is a result of compression. If you change to a lossless image preset then the difference goes away.
