### ISSUE TITLE
Sky Atmosphere component reports errors in console when is added to entity

### ISSUE THREAD

**Issue by NeilGitGud** [o3de/o3de#12233]
**Describe the bug**
Sky Atmosphere component reports errors in console when is added to entity

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Launch Editor
2. Create an entity
3. Add a "Sky Atmosphere" component to your entity

**Expected behavior**
No errors on component creation

**Actual behavior**
Several errors reported (see screenshot)

Error Text:

[Error] (PassSystem) - Pass::FrameBegin - Pass [Root.MainPipeline_0.Shadows.Cascades] is attempting to render, but is not in the Idle state.
[Error] (ImGuiPass) - Default ImGui pass is already set on this pipeline, ignoring request to set this pass as default. Only one ImGui pass should be marked as default in the pipeline.
[Error] (PassSystem) - Pass::FrameBegin - Pass [Root.MainPipeline_0.Shadows.Cascades] is attempting to render, but is not in the Idle state.
[Error] (PassSystem) - Pass::FrameBegin - Pass [Root.MainPipeline_0.OpaquePass.SkyAtmosphereParentPass] is attempting to render, but is not in the Idle state.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/79114701/192629500-a13e423d-598f-4726-a9c7-aaed441d443b.png)

**Found in Branch**
O3de stabilization branch "origin/stabilization/2210":
commit 358c6b02bb2b071a2c936b8731b160f1a81fb253

**Comment by AMZN-alexpete** [comment]
This no longer occurs in latest development branch.
