### ISSUE TITLE
Set Property Value Script Canvas node does not accept common variable types

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#12258]
**Describe the bug**
Set Property Value (Render > Material Component Request Bus) Script Canvas node does not accept any common variable types onto it's "Property Value" slot. When attempting to do so the following warning is shown on the tooltip:
```
Unable to drop onto slot
AZStd::any is not a type match for <Variable Type>
```
It should be noted that converting the pin to Reference does not recognize common variable types as valid options (the selection dropdown remains empty).
It should also be noted that there are multiple explicit Set Property Value nodes for specified variable types (for example Set Property Value Bool) and they accept listed variables without issues.

This issue also occurs on the Development (3b58972) build.

**Steps to reproduce**
1. Go to Tools > Script Canvas.
2. In the Script Canvas go to File > New Script.
3. Add a Set Property Value node to the graph.
4. Create a variable that is usable with other explicit Set Property Value <Variable Type> node (for example Boolean - as in Set Property Value Bool node).
5. Drag and drop the created variable onto Set Property Value's *Property Value* pin.

**Expected behavior**
The variable is assigned to the pin.

**Actual behavior**
The variable cannot be assigned to the pin.

**Video**

https://user-images.githubusercontent.com/86952082/192771923-5b6a63eb-14a8-4729-8c31-4b5f2affe6f5.mp4

**Found in Branch**
Stabilization/2210 (0fd1b90)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment]
As mentioned, there are set property functions for specific types that should be used with script canvas. The generic function that accepts AZStd::any works in C++ and lua. This is a minor issue because there are other functions that accomplish the expected functionality. The best option would be for a method to hide this specific function from script canvas.

**Comment by monroegm** [comment]
Reassigning to SIG-Graphics-Audio, the owners of the node

**Comment by LB-ArturZieba** [comment]
On the Development (3f742f7) build the *Set Property Value* node can still be found in the Script Canvas, as can be seen on the attached image:
![SetPropertyValue](https://user-images.githubusercontent.com/86952082/194552168-d19bec5e-86c6-4239-95ad-2a1b9067d897.png)
