### ISSUE TITLE
Bug Report: Lua Editor (LuaIDE.exe) Can't Connect With Editor.exe For Debugging

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#12259]
**Describe the bug**
Can not debug Lua scripts because LuaIDE.exe can not connect to the running Editor instance.

**Assets required**
Any level that contains a Lua script.

**Steps to reproduce**
1. Open a level that has an entity with a Lua script component with a valid Lua script.
2. From the Lua script component open the Lua Editor.
3. From the Lua Editor try to connect to the Editor.

**Expected behavior**
When clicking on the button for selecting an Editor target, a list of Editor instances appears and the user can pick an Editor target.

**Actual behavior**
When clicking on the button for selecting an Editor target no valid option shows up.

**Screenshots/Video**

https://user-images.githubusercontent.com/66021303/192782307-7993c3af-0520-4467-8b6a-a860b859360c.mp4

**Found in Branch**
commit 0fd1b90dfbb406df878a24592fa44a76983b0632 (HEAD -> stabilization/2210, upstream/stabilization/2210)
Merge: a932cba2b3 f1b729d0ed
Author: Guthrie Adams <82461473+gadams3@users.noreply.github.com>
Date:   Tue Sep 27 18:41:42 2022 -0500

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen Threadripper 3970X 32-Core Processor    3.70 GHz
 - GPU NVidia RTX 3070
 - Memory 64GB

**Additional context**
Here is the complete `user/` folder zipped in 74KB. Not sure where the LuaIDE.exe logs go to:  

[user.zip](https://github.com/o3de/o3de/files/9666136/user.zip)

**Comment by robhaco** [comment]
@galibzon I'm trying to repro this, but wanted to confirm. Debugging with Lua requires the Remote Tools Connection gem to be enabled, and the AutomatedTesting project doesn't have it enabled by default.  Was this gem enabled?

**Comment by galibzon** [comment]
@robhaco Was not aware of it. Will give it a try.

**Comment by AMZN-puvvadar** [comment]
> @robhaco Was not aware of it. Will give it a try. Btw, did I miss an "Impactful Change" notification/email? Or such notification has not been shared so far?

There was an Impactful Change announcement made on August 4th, 2022 regarding this change. Documentation has been submitted to the development branch of o3de.org but has not yet made it to main. You can find that documentation at https://github.com/o3de/o3de.org/blob/development/content/docs/user-guide/scripting/lua/debugging-tutorial.md for reference.

**Comment by galibzon** [comment]
Validated it actually works after enabling the Remote Tools Connection gem. Closing.

**Comment by galibzon** [comment]
Here is the PR that enables Remote Tools Gem in AutomatedTesting: https://github.com/o3de/o3de/pull/12274
