### ISSUE TITLE
Asset Browser context menu access for FBX files is inconsistent

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de#12281]
If you browse for FBX assets in Asset Browser, you can right-click on any asset to open the context menu and access tools like Edit Settings.

If you use the search box in Asset Browser to filter the list, right-click doesn't work on FBX files in the results. You have to double left-click or double right-click on a result FBX file to open the context menu.

This has been reported by more than one user and might affect file types other than FBX.

**Assets required**
You can use the assets included with O3DE.

**Steps to reproduce**
1. In Asset Browser, locate an FBX file.
2. Right-click the FBX. The context menu opens with a single right-click even if the FBX is not previously selected.
3. Type `fbx` in the Asset Browser search bar so the list filters to only FBX files.
4. Right-click on any FBX file in the results. The context menu doesn't open.
5. Double left-click or double right-click on a result. The context menu opens.

**Expected behavior**
Right clicking on an asset in Asset Browser always displays the context menu, even when the asset is not previously selected.

**Actual behavior**
When the Asset Browser list is filtered with a search term for FBX files, right-click doesn't open the context menu. This might happen for other file types as well.

**Found in Branch**
Stabilization/2210

**Desktop/Device (please complete the following information):**
Windows 10 Alienware Laptop. Has been reported by another user as well.

**Comment by sphrose** [comment]
Fixed by PR #14678
