### ISSUE TITLE
Feature Request: Rename sv_isTransient and update description

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#12290]
**Is your feature request related to a problem? Please describe.**
Split from https://github.com/o3de/o3de/issues/12198

The netowrking CVAR `sv_isTransient` does not accurately describe what this CVAR controls. Suggest adding more semantic context to CVAR to highlight this will cause the server to close once all connected players leave. 

The CVAR is important when running on cloud compute to ensure servers correct clean up ie on Amazon GameLift and other hosting services, to prevent zombie servers that incur unexpected hosting costs.

Consider renaming ie `sv_AutoShutdown`, `sv_terminateOnPlayerExit`

**Describe the solution you'd like**
* Propose new CVAR
* Deprecate old CVAR
* Update CVAR description in code and docs to be clear to avoid confusion (https://www.o3de.org/docs/user-guide/networking/settings/)

**Describe alternatives you've considered**
Just updating docs https://www.o3de.org/docs/user-guide/networking/settings/ 

**Additional context**

**Comment by neelmewada** [comment]
Hello @lmbr-pip @AMZN-Olex! I have created a pull request for this issue here: https://github.com/o3de/o3de/pull/12515

**Comment by lmbr-pip** [comment]
Code is merged
