### ISSUE TITLE
Frequent use of GetFeatureProcessor function causes performance issues

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#12339]
**Describe the bug**
GetFeatureProcessor is not a free lookup function due to its use of RTTI, and generally speaking pointers to feature processors should be cached and re-used. This has a noticeable performance impact when the transform of many mesh components are updated every frame, since UpdateObjectSrg is calling GetFeatureProcessor many times per frame.

Several Pass::IsEnabled() functions also call GetFeatureProcessor every frame.

**Steps to reproduce**
1. Create a scene with a large number of mesh components that move every frame.

**Screenshots/Video**
![GetFeatureProcessor](https://user-images.githubusercontent.com/82672795/193346331-120e7e1a-dcd1-423b-b198-19ffc0967bf7.PNG)

**Comment by burelc-amzn** [comment]
Does #14421 alleviate any of this issue?

**Comment by amzn-tommy** [comment]
This issue was actually fixed at a higher level by https://github.com/o3de/o3de/pull/13686 which updates it to not call GetFeatureProcessor so frequently, but instead call it once and cache the result.

So I'm not sure if #14421 helped, or if this was a case where not enough information is known at compile time for it to be evaluated at compile time.
