### ISSUE TITLE
Rects are painted via debug draw in the 3D scene for no reason.

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#12347]
**Describe the bug**
At some size ratios for the viewport, debug draw lines are displayed in the 3D scene.

**Steps to reproduce**
1. Open any level
2. Resize the viewport and move the camera around

**Actual behavior**
Debug draw lines are painted in a corner (see images)

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82231674/193364807-480cf245-6306-4b87-a6fc-6c6846af7aaa.png)
![DebugDraw](https://user-images.githubusercontent.com/82231674/193365157-124ab33e-a8d7-4cc3-b1e2-7e838802dc95.gif)

**Found in Branch**
Latest development

**Additional context**
Upon further inspection, these seem to be safe frames for 2D cameras that are rendered in 3D scenes as well, for some reason?

**Comment by pollend** [comment]
I might look at this over the weekend.

**Comment by hultonha** [comment]
Hmm this is an odd one for sure 🤔 Thanks for mentioning it @AMZN-daimini but I'd say this definitely falls under minor for now. If it's possible to put a breakpoint in where we're doing the line drawing and seeing where it's coming from that would be helpful (maybe something you could try @pollend if you're interested in giving it a look 🙂)

**Comment by hultonha** [comment]
Nice find @AMZN-daimini! All this is crazy old legacy cruft, I'll try and find a quite afternoon to just delete that code as I'm 99% sure it's unused. All the safe frame stuff for UI will be handled by LyShine separately anyway. Thanks!

**Comment by hultonha** [comment]
Fixed by https://github.com/o3de/o3de/issues/12347

**Comment by hultonha** [comment]
Lol yes sorry 🙈 My bad, thanks @pollend 👍
