### ISSUE TITLE
[Android][Quest2] Vulkan validation error: VUID-vkResetFences-pFences-01123

### ISSUE THREAD

**Issue by akioCL** [o3de/o3de#12355]
Describe the bug
When running an O3DE level on Oculus Quest 2 with Vulkan validation layer enabled the following error appears:

`2022-09-30 17:03:07.882 17358-17996/org.o3de.AtomSampleViewer I/: [Error] (vkDebugMessage) - ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkResetFences-pFences-01123 ] Object 0: handle = 0x6218d20000000239, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0x68a5074e | VkFence 0x6218d20000000239[] is in use. The Vulkan spec states: Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkResetFences-pFences-01123)`

From the callstack, it looks like this validation error is not triggered by the O3DE code but from the OpenXR implementation of the device. Have to investigate if O3DE is doing (or not doing) something that is causing this issue to appear from the OpenXR implementation.

Steps to reproduce

Build O3DE for Android
Add Vulkan-ValidationLayer binaries to the apk and enable it.
i. Download Vulkan-ValidationLayer binaries from https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases
ii. Copy the folder "arm64-v8a" into "LY_BUILD_DIR\app\src\main\jniLibs"
iii. Build again.
iv. Validation layer will be enabled by default on debug configuration. To enable it on profile pass the following argument by command line "rhi-device-validation enable".
Deploy and run a level to Oculus Quest 2.
Expected behavior
No vulkan errors

Actual behavior
Vulkan errors printed in the log.

Desktop/Device (please complete the following information):

Device: Oculus Quest 2
OS: Android

**Comment by moraaar** [comment]
Verified that these fence errors are due to the low performance.
These are different percentages of the view resolution, its frame rate and the error reported:

````
100% -> Width=1440 Height=1584 --> 1FPS -> gpu fence timeout errors every frame
70% -> Width=1007 Height=1108 --> 8FPS -> gpu fence timeout errors every frame
60% -> Width=864 Height=950 --> 11 FPS -> gpu fence timeout errors some frames
50% -> Width=720 Height=792 --> 13 FPS -> No gpu fence timeout errors
````

Since the optimization effort is tracked by this https://github.com/o3de/o3de/issues/12356 I'll close this bug because it'll stop happening when the optimization task is closed.
