### ISSUE TITLE
[Android][Quest2] The "Features/OpenXR" sample runs really slow on device (1 fps)

### ISSUE THREAD

**Issue by akioCL** [o3de/o3de#12356]
**Describe the bug**
The Features/OpenXR sample runs really slow (maybe 1 fps) on the Quest 2.

Steps to reproduce

Build O3DE for Android
Add Vulkan-ValidationLayer binaries to the apk and enable it.
i. Download Vulkan-ValidationLayer binaries from https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases
ii. Copy the folder "arm64-v8a" into "LY_BUILD_DIR\app\src\main\jniLibs"
iii. Build again.

Deploy and run the Features/OpenXR sample to Oculus Quest 2.
Expected behavior
The sample runs at least at 10 fps.

Actual behavior
The sample runs at 1 fps or slower

Desktop/Device (please complete the following information):

Device: Oculus Quest 2
OS: Android

**Comment by moraaar** [comment]
As temporary solution added setting to be able to scale the resolution of OpenXR views to bring up the framerate: https://github.com/o3de/o3de-extras/pull/44

Further work will be done to optimize VR render pipeline.

Closing this ticket.
