### ISSUE TITLE
Scene Settings UX Refresh

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#12369]
The Editor [Scene Settings UX](https://github.com/o3de/o3de/tree/development/Code/Editor/Plugins/EditorAssetImporter) is used to mange the processing settings when working imported scene files in a project. 

This roadmap item breaks down updating the Scene Settings UX to improve the user experience including polishing the UX, fixing known issues around the save workflow and providing much clearer information on what is happening when edits are applied.

**Comment by AMZN-stankowi** [comment]
@mcphedar this tool does not import scene files, the import tool is separate and unrelated to this tool. This tool is used to manage the settings used to process scene files.

**Comment by lmbr-pip** [comment]
Updated description to be more accurate based on your suggestion @AMZN-stankowi

**Comment by lmbr-pip** [comment]
Work is completed.
