### ISSUE TITLE
OpenXR Platform Support - Milestone 2

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#12372]
Initial integration of OpenXR with support for Meta Quest 2. It will feature a simple level with multiple meshes using the full VR pipeline.

Note that the performance will not be optimal to build a full application at this stage. That will come in a subsequent deliverable.

**Comment by moraaar** [comment]
## o3de-extras Links
https://github.com/o3de/o3de-extras/pull/2
https://github.com/o3de/o3de-extras/pull/5
https://github.com/o3de/o3de-extras/pull/9
https://github.com/o3de/o3de-extras/pull/14
https://github.com/o3de/o3de-extras/pull/15
https://github.com/o3de/o3de-extras/pull/16
https://github.com/o3de/o3de-extras/pull/22
https://github.com/o3de/o3de-extras/pull/31
https://github.com/o3de/o3de-extras/pull/34
https://github.com/o3de/o3de-extras/pull/37
https://github.com/o3de/o3de-extras/pull/38
https://github.com/o3de/o3de-extras/pull/43
https://github.com/o3de/o3de-extras/pull/44
https://github.com/o3de/o3de-extras/pull/46
https://github.com/o3de/o3de-extras/pull/48
https://github.com/o3de/o3de-extras/pull/49
https://github.com/o3de/o3de-extras/pull/50
https://github.com/o3de/o3de-extras/pull/51

## o3de Links
https://github.com/o3de/o3de/pull/9664
https://github.com/o3de/o3de/pull/10170
https://github.com/o3de/o3de/pull/10475
https://github.com/o3de/o3de/pull/11310
https://github.com/o3de/o3de/pull/11670
https://github.com/o3de/o3de/pull/12146
https://github.com/o3de/o3de/pull/12271
https://github.com/o3de/o3de/pull/12424
https://github.com/o3de/o3de/pull/12467
https://github.com/o3de/o3de/pull/12491
https://github.com/o3de/o3de/pull/12559
https://github.com/o3de/o3de/pull/12737
https://github.com/o3de/o3de/pull/13063

**Comment by moraaar** [comment]
##OpenXR documentation 

https://github.com/o3de/o3de-extras/wiki/Build-and-Run-OpenXR-in-O3DE

##Profiling on Quest 2

https://github.com/o3de/o3de-extras/wiki/Profiling-tools-for-Meta-Quest-2
https://github.com/o3de/o3de-extras/wiki/Advanced-GPU-profiling-tools-for-Meta-Quest-2

**Comment by moraaar** [comment]
Completed
