### ISSUE TITLE
Viewport Experience Improvements

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#12388]
This roadmap item covers improvements to the overall editor viewport to make it easier and more flexible to use. It also covers an overhaul and rewrite of the O3DE viewport documentation to make it much clearer and easier to understand for customers.

**Comment by hultonha** [comment]
Last remaining work has been merged

- https://github.com/o3de/o3de/pull/12504
- https://github.com/o3de/o3de/pull/5906
- https://github.com/o3de/o3de/pull/12218
- https://github.com/o3de/o3de/pull/11201
- https://github.com/o3de/o3de/pull/7752
- https://github.com/o3de/o3de/pull/7676
- https://github.com/o3de/o3de/pull/8648
- https://github.com/o3de/o3de/pull/8612
- https://github.com/o3de/o3de/pull/11195
- https://github.com/o3de/o3de/pull/10109
- https://github.com/o3de/o3de/pull/11819
