### ISSUE TITLE
Linux: Editor crashes when opening any level after all assets have processed

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#12394]
**Describe the bug**
Editor crashes when opening any level after all assets have processed.

**Steps to reproduce**
1. Download/Install the latest Linux installer: https://jenkins.build.o3de.org/view/Tools/job/O3DE-stablization_2210_nightly-installer/
2. Open O3DE Project Manager.
3. Create a new project using the Default or Minimal Template.
4. Build the project.
5. Launch the Editor for the project.
6. Create/save a new level.
7. Wait for all project assets to process.
8. Re-open the saved level.
9. Create a new level.

**Expected behavior**
Previously saved and newly created levels open without issue.

**Actual behavior**
Previously saved and newly created levels open fine UNTIL all assets have finished processing. After that occurs, the Editor crashes when attempting to open any existing or new levels. No Call Stack is generated in a crash.log/error.log. The last part of Editor.log reads:

```
Document successfully savedLoading map '/home/aus1/O3DE/Projects/NewProjectDefaultInstaller/Levels/NewLevel2' into engine...(Vulkan) - Resizing swapchain from (1133, 744) to (100, 30).
(Vulkan) - Swapchain created. Width: 100, Height: 30.

(Swapchain) - Obtained presentable images.

(Swapchain) - Acquired the first image.

(Vulkan) - Swapchain created. Width: 1133, Height: 744.

(Swapchain) - Obtained presentable images.

(Swapchain) - Acquired the first image.
```

**Found in Branch**
stabilization2210 - Latest Installer

**Comment by jckand-amzn** [comment]
Reproduced this issue via the latest installer as well as a local Git build.

**Comment by tonybalandiuk** [comment]
are we ready to flag this as a release blocker?

**Comment by spham-amzn** [comment]
I was unable to reproduce this from a local github example on a physical machine. I can try the installer as well

**Comment by LB-BartoszDudzinski** [comment]
We were unable to reproduce this issue. We verified the latest installer with 2 different PC's and GitHub build with 3 PC's (2 prebuilt SDK config and 1 source config).

**Comment by jckand-amzn** [comment]
This seems to be an issue with the EC2 instance setup. Today I reinstalled the graphics driver, and an existing project that was earlier able to reproduce this issue is no longer able to. After updating the graphics drivers, building new projects seems to be broken on the EC2 instance where they previously worked fine, so there seems to be a general issue with the software/hardware setup on the instance I'm working to figure out. Seems safe to close this issue out as it does not appear to be an O3DE issue.
