### ISSUE TITLE
Periodic build Bug Report: Linux and Windows project_generate jobs red due to error finding DefaultProject

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#12485]
**Failed Jenkins Job Information:**
Windows
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/123/pipeline/1348
Linux
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/123/pipeline/1528

```
[ci_build] python/python.sh -u install/scripts/o3de.py create-project -pp /data/workspace/TestProject --force
[ERROR] o3de.engine_template: Could not find the template path using name DefaultProject.
Has the engine been registered yet. It can be registered via the "o3de.py register --this-engine" command
```

**Attachments**
[log.txt](https://github.com/o3de/o3de/files/9732711/log.txt)

**Comment by amzn-changml** [comment]
The issue appears to be resolved as of Nov 29th's periodic build and is succeeding the CI portion: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/179/pipeline/2090 

Closing issue as resolved
