### ISSUE TITLE
Material Canvas Sample Texture 2d node does not apply texture to the material or crashes the tool itself

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#12496]
**Describe the bug**
Attempting to use Sample Texture 2d does not work as expected when compared to the analogous action in the Material Editor. This issue occurs on both Windows and Linux OS. On Windows used image seems to be treated as a color data and its average color used as the material color (as can be seen on the screenshot in the **Video and screenshot** section). On Linux this can happen as well, however most of the time Material Canvas simply silently crashes when the Viewport attempts to refresh the image.

This issue also occurs on the Development (3f742f7) build.

**Steps to reproduce**
1. Go to Tools > Material Canvas (Experimental).
2. Create a new Material Canvas graph by going to File > New > New Material Canvas Document... and saving it.
3. Add a *Sample Texture 2d* node to the graph and select it.
4. In the Inspector pane click the folder icon next to the Value property and select a valid image (for example preview.png).
5. Add an *Experimental PBR* component to the graph.
6. Connect the *Sample Texture 2d* Color output pin to the *Experimental PBR* Base Color input pin.

**Expected behavior**
Image assigned in the *Sample Texture 2d* node is used as a texture on the material.

**Actual behavior**
Image assigned in the *Sample Texture 2d* node is used as a color or the Material Canvas crashes.

**Video and screenshot**
Linux:

https://user-images.githubusercontent.com/86952082/194567788-5f3b9d4d-b04d-48a9-8608-2e2e8989eb7c.mp4

Windows (contains comparison of using the preview.png image in the Material Editor and via *Sample Texture 2d* node in the Material Canvas):
![MaterialCanvasWindowsTexturingActual](https://user-images.githubusercontent.com/86952082/194567820-ee56d3c1-3629-47b0-92a4-dfdc53570f73.png)

**Found in Branch**
Stabilization/2210 (7c4e3ca)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by monroegm** [comment]
SIG-Graphics-Audio owns Material Canvas

**Comment by LB-ArturZieba** [comment]
I have reverified this issue on the Development (7ce6550) build (using Base PBR and Standard PBR nodes, as Experimental PBR is no longer available) and did not have any crashes. However, the texture is still not being applied to the mesh, should this issue be reopened?

**Comment by gadams3** [comment]
In order for the sample texture 2D node to apply to the entire model, it requires the UV node or another node that can be used to provide texture coordinates across the surface of your model. There are examples of this in the test data folder that should also show the sample texture 2D node working

**Comment by LB-ArturZieba** [comment]
Thanks for the tip! I was able to get the Sample Texture 2d to work after viewing the test .materialgraph files.
