### ISSUE TITLE
Material Canvas Utilities category nodes do not have any properties available in the Inspector pane

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#12494]
**Describe the bug**
Material Canvas *Comment* and *Node Group* nodes do not have any properties exposed in the Inspector pane. Due to this they always have the same font/background coloration and all of the Node Groups are named the same. As a comparison the same nodes in the Script Canvas have full customization of fonts/backgrounds available.

This issue occurs on both Windows and Linux OS.

This issue also occurs on the Development (3f742f7) build.

**Steps to reproduce**
1. Go to Tools > Material Canvas (Experimental).
2. Create a new Material Canvas graph by going to File > New > New Material Canvas Document... and saving it.
3. Add *Comment* and *Node Group* nodes to the graph.
4. Select each of them separately while looking at the Inspector pane.

**Expected behavior**
*Comment* and *Node Group* nodes have the same Inspector properties available as their counterparts in the Script Canvas.

**Actual behavior**
*Comment* and *Node Group* nodes do not have any properties available in the Inspector.

**Video**

https://user-images.githubusercontent.com/86952082/194566333-38c96587-23af-44b0-b57d-9ece5582ae72.mp4

**Found in Branch**
Stabilization/2210 (7c4e3ca)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by monroegm** [comment]
SIG-Graphics-Audio owns Material Canvas
