### ISSUE TITLE
Material Canvas nodes do not have distinct coloration

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#12492]
**Describe the bug**
All Material Canvas nodes have indistinct colors (or in the case of the Utility category none at all), while for example Script Canvas has different colors for different types of nodes/categories.

This issue occurs on both Windows and Linux OS.

This issue also occurs on the Development (3f742f7) build.

**Steps to reproduce**
1. Go to Tools > Material Canvas (Experimental).
2. Look at the Node Palette.

**Expected behavior**
All categories/types of nodes have distinct coloration.

**Actual behavior**
All categories/types of nodes are colored black or in the case of Utilities no color is assigned.

**Screenshot**
![MaterialCanvasNodesColors](https://user-images.githubusercontent.com/86952082/194562011-a1db0e47-8715-4651-9a8c-5027b5abf37e.png)

**Found in Branch**
Stabilization/2210 (7c4e3ca)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by monroegm** [comment]
SIG-Graphics-Audio own Material Canvas

**Comment by LB-ArturZieba** [comment]
On the Development (7f642a1) build there are still some nodes with no color:
* Math Functions > Acos
* Math Functions > Noise
* Utilities > Comment
* Utilities > Node Group

![MaterialCanvasNoColor0](https://user-images.githubusercontent.com/86952082/200564353-66a268cf-8d87-4fae-b419-8ebe3e21281d.png)
![MaterialCanvasNoColor1](https://user-images.githubusercontent.com/86952082/200564373-7329c8f8-1821-4469-ac42-95356e065c4b.png)
![MaterialCanvasNoColor2](https://user-images.githubusercontent.com/86952082/200564389-4c624124-1541-4271-a155-e45d4dddbfad.png)

It should be noted that all other nodes have a color assigned.
