### ISSUE TITLE
Cancelling the unsaved changes prompt in Material Editor and Material Canvas closes the tool which leads to a loss of any unsaved changes

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#12495]
**Describe the bug**
Cancelling or closing the unsaved changes prompt in Material Editor and Canvas does not return to the edited file. Instead, the tool is closed and any unsaved changes made to the asset are lost.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Launch Material Canvas.
2. Go to File -> New Material Canvas Document -> OK.
3. Add any node to the graph area and move it so that the graph is indicated as having unsaved changes.
4. Press the *X* button to close the Material Canvas.
5. On the unsaved changes prompt select _Cancel_.

**Expected behavior**
The tool remains open. Unsaved changes prompt is dismissed.

**Actual behavior**
The tool closes. Any unsaved changes are lost.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/194568928-86b7e67b-9abf-45b3-8a9c-956408b98712.mp4

**Found in Branch**
Development (3f742f7)
Stabilization/2210 (7c4e3ca)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by monroegm** [comment]
SIG-Graphics-Audio owns Material Canvas

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as fixed in Development (95e4836).
