### ISSUE TITLE
Material Canvas: Dragging and dropping a node from the Node Palette to the graph area is not detected as a change

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#12493]
**Describe the bug**
Adding nodes by dragging and dropping them from the Node Palette to the graph area in the Material Canvas does not indicate the files as having unsaved changes (the * does not appear next to the file name). Additionally, such action cannot be undone/redone.

Please note that this does not occur for the nodes added from the RMB context menu.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Open Material Canvas.
2. Go to File -> New Material Canvas Document -> OK.
3. Add any node to the graph by dragging and dropping it from the Node Palette.
4. Attempt to undo the above action.
5. Note that there is no * symbol next to the file name.

**Expected behavior**
Adding the nodes by dragging and dropping from the Node Palette is correctly detected as a change in the file and can be undone/redone.

**Actual behavior**
Adding the nodes by dragging and dropping from the Node Palette is not correctly detected as a change in the file and cannot be undone/redone.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/194564350-55f5cd1c-cf01-46e5-8e7a-c50bb60ea548.mp4

**Found in Branch**
Development (3f742f7)
Stabilization/2210 (7c4e3ca)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by monroegm** [comment]
SIG-Graphics-Audio owns Material Canvas

**Comment by gadams3** [comment]
Resolved with the PR listed above

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed in Development (72b2163).
