### ISSUE TITLE
Network auto-gen - using NetEntityId as a NetworkInput leads to a compile error

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#12513]
**Describe the bug**
When a multiplayer component declares a network input as:
```
	<NetworkInput Type="Multiplayer::NetEntityId"   Name="FireAtEntity"    Init="Multiplayer::InvalidNetEntityId" />
```

This results in the following compilation error:
```
1>...\Gems\Multiplayer\Code\Include\Multiplayer/MultiplayerDebug.inl(28,17): error C2665: 'AZStd::to_string': none of the 28 overloads could convert all the argument types
1>            AZStd::to_string(m_clientServerValue.first), AZStd::to_string(m_clientServerValue.second));
1>                ^
```

It's not clear if there is a header file that resolves this error.

**Assets required**
o3de-multiplayersample

**Steps to reproduce**
1. Create or use a multiplayer project
2. Modify or create a new multiplayer component
3. Add a network input with Multiplayer::InvalidNetEntityId type
4. Compile the project
5. See error

**Expected behavior**
The project compiles.

**Actual behavior**
A compilation occurs:
```
1>...\Gems\Multiplayer\Code\Include\Multiplayer/MultiplayerDebug.inl(28,17): error C2665: 'AZStd::to_string': none of the 28 overloads could convert all the argument types
1>            AZStd::to_string(m_clientServerValue.first), AZStd::to_string(m_clientServerValue.second));
1>                ^
```

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Comment by AMZN-puvvadar** [comment]
The MultiplayerDebug logic expects types used to have a defined to_string function. Since NetEntityId is a Type Safe Integral, it technically doesn't have one.

Defining one in MultiplayerTypes.h and adding a MultiplayerTypes.inl implementing it would do it. Alternatively, use a uint64_t for the type and convert to NetEntityId where necessary. I'd recommend the former.
