### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by danielemorra98** [o3de/o3de#12517]
**Describe the bug**
Trying to compile the [o3de-ros2-gem](https://github.com/RobotecAI/o3de-ros2-gem/tree/development), I met some errors related to 
`no type named <...> in namespace 'AZ'` 
The engine was built against **main** branch

For examples:
![Screenshot from 2022-10-10 17-13-40](https://user-images.githubusercontent.com/48955695/194899165-447e11e4-efdb-4dfb-aeff-e79f91445f4b.png)
![Screenshot from 2022-10-10 17-13-24](https://user-images.githubusercontent.com/48955695/194899237-d363f7c0-77a9-40a2-88b4-1dc12f029764.png)

**Comment by lmbr-pip** [comment]
@danielemorra98 is the rosgem supposed to work against main? Main was last updated in May. I would suspect this Gem has been developed against a different tracking branch.

Note: we are just about to update main with the October release.

**Comment by danielemorra98** [comment]
we were using the development branch of [https://github.com/RobotecAI/o3de-ros2-gem/tree/development](https://github.com/RobotecAI/o3de-ros2-gem/tree/development) against main O3DE. 
Now switched to development o3DE and it worked. Thanks
