### ISSUE TITLE
Bug Report: UI Canvas does not update when out of focus.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#12521]
**Describe the bug**
If you do not have the UI Editor in focus, but it is on your monitor, you can zoom in and out of the canvas like you would if in focus, but the ui elements do not follow the canvas anymore until you focus back in.

**Steps to reproduce**
1. Create a ui canvas and add a ui element with an image component.
2. Unfocus the ui editor/o3de all together, and zoom in and out while hovering over the canvas.
3. The ui image will stay where it is at while the canvas moves.

**Expected behavior**
When you do not have the ui editor in focus the ui editor should either move the elements with the canvas, or not move the canvas when out of focus.

**Actual behavior**
The canvas moves, but the ui elements stay where they were at.

**Screenshots/Video**
Will send one below once editor build is over

**Found in Branch**
Development [49aaa67]

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Comment by ParasiteSt** [comment]
This is a small clip showing the bug;
https://user-images.githubusercontent.com/100494538/194963482-b497c736-f7c7-41b5-b1e6-fe5149b2c2e6.mp4

**Comment by monroegm** [comment]
Duplicates #12365
