### ISSUE TITLE
Action Manager: AWS Menu does not appear when using the new Action Manager Menus

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#12527]
**Describe the bug**
AWS Menu does not appear when using the new Action Manager Menus.

**Steps to reproduce**
1. Launch the Editor with the new Action Manager created Menus active:
```
Editor.exe --regset=O3DE/ActionManager/EnableNewActionManager=true
```
2. Attempt to use the AWS Menu.

**Expected behavior**
All previously available Menu functionality is present when running the Editor with the new Action Manager active.

**Actual behavior**
AWS Menu is not available/usable with the new Action Manager active.

**Screenshots/Video**
![missing_aws_menu](https://user-images.githubusercontent.com/82226555/194952648-c254a897-127a-473a-82ef-39271e5d7cbd.jpg)

**Found in Branch**
development@ 221cd9e5c29ecc480d9cb0155c00a6280e678c2f

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by AMZN-daimini** [comment]
Best solution would be to rewrite the AWS Gem to use the Action Manager hooks and API to create that menu.

Quickest fix would be to move the current code to be triggered on the `OnPostActionManagerRegistrationHook` notification call. That menu would not be controlled by the Action Manager and would disappear if something refreshes the menu bar, but it should be a workable band-aid until the proper solution is implemented. (If this is chosen, please create a follow-up task for the proper solution)
