### ISSUE TITLE
[Linux] Animation Editor crashes the Editor inconsistently

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#12536]
**Describe the bug**
Editor behaves differently while opening the Animation Editor. It might:

- crash right upon opening the Animation Editor
- crash after moving the Animation Editor's window couple of times
- not crash at all

The result varies between projects (being the same Default template projects) or even levels within the same project. It does not reproduce on every machine. 
For further information please refer to the attached videos. Note that the crash.log is not generated.

**Steps to reproduce**
1. Open the Editor.
2. Open the Animation Editor (might crash).
3. Move the Animation Editor's window couple of times.

**Expected behavior**
Editor remains stable.

**Actual behavior**
Editor crashes while moving the Animation Editor's window.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/195089949-5d6d7633-a5a0-4b91-9a84-6b2b249da5d6.mp4

https://user-images.githubusercontent.com/86953659/195090003-309bc9c1-9fc8-4f1f-9406-b09568e7ac10.mp4

https://user-images.githubusercontent.com/86953659/195090040-c4744a33-7b9b-425c-bfcd-0c3ad54e3894.mp4

**Found in Branch**
Stabilization installer

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.3 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/9755849/Editor.log)

**Comment by burelc-amzn** [comment]
This seems pretty similar to #6800

**Comment by hultonha** [comment]
Thanks for the info @burelc-amzn - I believe @pollend removed the legacy OpenGL viewport entirely (please correct me if I'm wrong) so I'm not sure it's the same thing (unless there is some old OpenGL code kicking around? 🤔). Will discuss with @amzn-rhhong and @pollend to see if they have any ideas. Thanks!

**Comment by burelc-amzn** [comment]
Issue #6800 is not about the legacy OpenGL viewport. It is about using `QOpenGLWidget` in any Editor view pane, which the Animation Editor does. You can reproduce the crash by making any view pane that uses `QOpenGLWidget`, so there is nothing specific that the Animation Editor is doing to cause this. It is better documented in this [comment I made on #6800]( https://github.com/o3de/o3de/issues/6800#issuecomment-1026017698).  When I profiled it, there was a 10x performance hit to the AnimGraph paint time when reverted to non-hardware-accelerated painting, but doing so works around the crash.

**Comment by hultonha** [comment]
I see, thank you for confirming @burelc-amzn, if this is the case and is independent of anything directly O3DE related should we open an issue with Qt about this? Is it possible to create a sample application that reproduces the crash independent of O3DE we could submit a bug report for there? Thanks!

**Comment by byrcolin** [comment]
cannot repro as of 23.10 release on ubuntu 24.04 and Fedora 38
