### ISSUE TITLE
Action Manager: Show Helpers/Icons icon above Viewport is not properly highlighted when selections are active with the new Action Manager active

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#12541]
**Describe the bug**
Show Helpers/Icons icon above Viewport is not properly highlighted when selections are active with the new Action Manager active. Even with Show Helpers and/or Show Icons options active, the icon above the Viewport is not properly highlighted.

**Steps to reproduce**
1. Launch the Editor with the new Action Manager created Menus active:
```
Editor.exe --regset=O3DE/ActionManager/EnableNewActionManager=true
```
2. Toggle on Show Helpers/Show Icons if necessary.
3. Observe Show Helpers/Icons icon at the top-right of the Viewport.

**Expected behavior**
Icon is highlighted if selections in the menu are active.

**Actual behavior**
Icon is not highlighted, even with active menu selections.

**Screenshots/Video**
![helpers_icon_missing_highlight](https://user-images.githubusercontent.com/82226555/195139486-c66c79ea-714f-4382-9f97-e3cfd3dd4ec6.jpg)

**Found in Branch**
development@ 221cd9e5c29ecc480d9cb0155c00a6280e678c2f

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by AMZN-daimini** [comment]
PR above fixes the issue
