### ISSUE TITLE
Integrate Radeon GPU Analyzer for Register Statistics

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#12550]
**Is your feature request related to a problem? Please describe.**
When analyzing GPU performance, one of the more important factors to consider is register (VGPR) pressure. We need a convenient way to determine the register usage for compiled shaders, to better understand the impact of specific shader options and shader variants. Render capture tools such as Nsight and PIX typically report this information, but it can be time consuming for developers to run the tools, run the engine, get into an appropriate runtime state, take a capture, and then browse to find information about VGPR usage. 

**Describe the solution you'd like**
[Radeon GPU Analyzer (RGA)](https://gpuopen.com/rga/) is a MIT licensed tool, capable of performing various offline analysis of HLSL code, including register usage. We should integrate this tool with the shader build pipeline to automatically report register usage (and other statistics) when compiling shader assets.

Since running this analysis could take considerable time on large data sets, and most users don't need this information, it should by off by default in most cases. When enabled, it would ideally be downloaded and/or installed automatically by the build system. Graphics engineers likely will only need to analyze a small number of shaders, so even when the tool is enabled, there should be away to enable only for specific shaders. This could be in the .shader file, in the .shadervariantlist file, or a .setreg file (it's up to the implementer to determine the best course).

Since the command line configuration for RGA is complex, and experience shows that usage of the tool is rather fragile, we should try to incorporate it into the Automated Review process, so we'll know right away if the integration breaks. This should be pretty simple, by enabling the statistics only one or two core shaders (like StandardPbr_ForwardPass.shader for example) in the AutomatedTesting project. That if the integration ever breaks, the shader fail to process, and this will fail the AR asset processing jobs on Jenkins. Since only one or two shaders would get this treatment, it won't have much impact on AR times.

**Describe alternatives you've considered**

**Additional context**
Some experimentation was done under this other task to determine how RGA can work together with O3DE's intermediate HLSL files in the cache. https://github.com/o3de/o3de/issues/11792

**Comment by galibzon** [comment]
@santorac RGA is integrated in CMake, but is this task complete?

**Comment by santorac** [comment]
I think we should still do this part before closing the ticket:
> Since the command line configuration for RGA is complex, and experience shows that usage of the tool is rather fragile, we should try to incorporate it into the Automated Review process, so we'll know right away if the integration breaks. This should be pretty simple, by enabling the statistics only one or two core shaders (like StandardPbr_ForwardPass.shader for example) in the AutomatedTesting project. That if the integration ever breaks, the shader fail to process, and this will fail the AR asset processing jobs on Jenkins. Since only one or two shaders would get this treatment, it won't have much impact on AR times.

**Comment by etherealchain** [comment]
If RGA outputs are missing, the shader process will still succeed, only a warning will be printed.
You suggested this in #12710

> I think we should report a warning here, but don't return Failure. If I understand correctly, the .exe will not be downloaded when the o3de installer is used. In that case, we don't want to fail the job because the main product here is the shader variant asset, which is not impacted by the failed rga process, that's only a debug utility.

Should we report an error when the warning is printed?
AutomatedTesting looks like a normal project, I'm not familiar with how the testing system worked, is there a place for expected results for me to update?

**Comment by santorac** [comment]
Right. So we'll need something that can actually check the expected location where the statistics are supposed to be saved, and report an error if they don't show up. You'll probably have to make a python automated test to check this.
The test scripts are kept here: https://github.com/o3de/o3de/tree/development/AutomatedTesting/Gem/PythonTests/Atom/tests

**Comment by etherealchain** [comment]
https://github.com/o3de/o3de/pull/14385 has been merged.
We can close this one.
