### ISSUE TITLE
Add azlmbr undo() and redo() functions for Atom Tools automated tests (MaterialEditor, MaterialCanvas, etc.).

### ISSUE THREAD

**Issue by jromnoa** [o3de/o3de#12584]
**Is your feature request related to a problem? Please describe.**
Editor python tests can use the `azlmbr.legacy.general` library to call on the `undo()` and `redo()` functions which work as the names imply (un-does the last action or re-does the last action taken). It does so using the following code (which Atom Tools tests don't have access to, only Editor tests):
```py
import azlmbr.legacy.general as general

general.undo()
general.redo()
```

If you search for similar bindings inside MaterialEditor python bindings you won't see any `undo()` or `redo()` functions:
```py
] dir(azlmbr.atomtools)
['AtomToolsDocumentRequestBus', 'AtomToolsDocumentSystemRequestBus', 'AtomToolsMainWindowRequestBus', 'DynamicNodeConfig', 'DynamicNodeSlotConfig', 'EntityPreviewViewportSettingsNotificationBus', 'EntityPreviewViewportSettingsRequestBus', 'InspectorRequestBus', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'general', 'util']
] dir(azlmbr.atomtools.general)
['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'crash', 'exit', 'idle_wait_frames', 'test_output']
] dir(azlmbr.atomtools.util)
['GetDisplayNameFromPath', 'GetDisplayNameFromText', 'GetFileFilterFromSupportedExtensions', 'GetFirstMatchingSupportedExtension', 'GetFirstValidSupportedExtension', 'GetOpenFilePathsFromDialog', 'GetPathToExteralReference', 'GetPathWithAlias', 'GetPathWithoutAlias', 'GetPathsInSourceFoldersMatchingWildcard', 'GetSaveFilePathFromDialog', 'GetStringListFromDialog', 'GetSymbolNameFromText', 'GetUniqueFilePath', 'GetUniqueUntitledFilePath', 'IsDocumentPathEditable', 'IsDocumentPathInSupportedFolder', 'IsDocumentPathPreviewable', 'ValidateDocumentPath', '__doc__', '__loader__', '__name__', '__package__', '__spec__'
```

**Describe the solution you'd like**
`azlmbr` bindings for `undo()` and `redo()` available in Atom Tools automated tests (for MaterialEditor, MaterialCanvas, etc.).

**Describe alternatives you've considered**
There are no clear alternatives to this functionality. We either have it setup for the `azlmbr` bindings or we don't.

**Comment by gadams3** [comment]
This tools framework does not have a global concept of undo redo. Undo redo is managed by each individual document. You can use functions from the following bus and add utility functions to atom_tools_utils.py

https://github.com/o3de/o3de/blob/development/Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp#L28-L52

**Comment by jromnoa** [comment]
```py
def undo(document_id):
    return azlmbr.atomtools.AtomToolsDocumentRequestBus(bus.Event, "Undo", document_id)
```
