### ISSUE TITLE
Asset Processor errors: specific Scene compilation jobs

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#12612]
**Describe the bug**
This issue was created based on the comment in [#12588](https://github.com/o3de/o3de/issues/12588).
The following Scene compilation jobs complete processing with errors:

`\o3de\Gems\Atom\Tools\MaterialEditor\Assets\MaterialEditor\ViewportModels\Cube.fbx` platform: pc
`\o3de\Gems\Atom\Tools\MaterialEditor\Assets\MaterialEditor\ViewportModels\Caduceus.fbx` platform: pc
`/o3de/Gems/AtomLyIntegration/CommonFeatures/Assets/Objects/Hermanubis/Hermanubis_High.fbx` platform: linux
`/o3de/Gems/AtomTressFX/Assets/TestData/HeadBoneChainHairStyle/test_hair_bone_chain_head_style.fbx` platform: linux

The error messages for the mentioned jobs are:

- `AssetImportRequest: Failed to get watch folder for source`
- `Prefab: Relative source path for C:o3deGemsAtomToolsMaterialEditorAssetsMaterialEditorViewportModelsCube_fbx.procprefab' could not be determined. Using project path as relative root.`
- `EMotionFX: Ambigious mesh for actor asset. More than one mesh group found. Defaulting to the first one.`
- `QtForPython: Unable to load python library libpython3.10.so for Pyside2: libpython3.10.so: cannot open shared object file: No such file or directory`

Please note that Linux affected assets have to be verified on Linux OS.

**Steps to reproduce**
1. Create a new project in Project Manager built in Source engine configuration (https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/).
2. Build the project.
3. Run the Asset Processor and wait for the scan to finish.

**Expected behavior**
All assets are processed without errors.

**Actual behavior**
The Scene compilation jobs complete processing with errors.

**Found in Branch**
Development (c28de14)

**Desktop/Device**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[Caduceus.fbx-4119011412-14855.log](https://github.com/o3de/o3de/files/9786149/Caduceus.fbx-4119011412-14855.log)
[Cube.fbx-2759012889-14851.log](https://github.com/o3de/o3de/files/9786150/Cube.fbx-2759012889-14851.log)
[test_hair_bone_chain_head_style.fbx-3078959659-2454.log](https://github.com/o3de/o3de/files/9786152/test_hair_bone_chain_head_style.fbx-3078959659-2454.log)
[Hermanubis_High.fbx-267745240-11798.log](https://github.com/o3de/o3de/files/9786153/Hermanubis_High.fbx-267745240-11798.log)

**Comment by AMZN-stankowi** [comment]
I've split https://github.com/o3de/o3de/issues/12618 off into its own ticket, it's a different error than the rest of the files https://github.com/o3de/o3de/issues/12618

For the other files, can you give additional details, the scan directory (watch folder) issue says to me there's something unique to your setup, because I'm not getting errors with those files.

**Comment by LB-KacperKapusta** [comment]
The setup was done from clean state going step by step with the instruction mentioned in the description for Source engine configuration. Is there any other information except for that and the attached .log files we can provide that will be useful in resolving this issue?

**Comment by AMZN-stankowi** [comment]
Do you get these errors with those files with AutomatedTesting, or just your new project? I'm wondering if maybe a Gem wasn't activated or something.

**Comment by AMZN-stankowi** [comment]
I've created a new, minimal project, and I didn't get the error.

**Comment by LB-KacperKapusta** [comment]
It has been reverified on Development (https://github.com/o3de/o3de/commit/14076b4f932a768e9d12b041ca16a13903ac6be5) build using a new project with all gems enabled that the assets mentioned in the description (`Cube.fbx`, `Caduceus.fbx`, `Hermanubis_High.fbx`) do no longer produce errors for their respective platforms.

It has been observed that the following new to this issue Scene compilation jobs produce errors exclusively on Windows:
`\o3de\Gems\MotionMatching\Assets\Animations\Crouching1.fbx` platform: pc, android, server
`\o3de\Gems\MotionMatching\Assets\Animations\TurnOnSpot1.fbx` platform: pc, android, server
`\o3de\Gems\MotionMatching\Assets\Animations\WalkPivotTurn1.fbx` platform: pc, android, server
`\o3de\Gems\MotionMatching\Assets\Animations\WalkStopTurn1.fbx` platform: pc
`\o3de\Gems\MotionMatching\Assets\Animations\WalkTurns1.fbx` platform: pc

[Crouching1.fbx-1710888947-10166.log](https://github.com/o3de/o3de/files/9809488/Crouching1.fbx-1710888947-10166.log)
[WalkStopTurn1.fbx-3240174131-22528.log](https://github.com/o3de/o3de/files/9809489/WalkStopTurn1.fbx-3240174131-22528.log)
[WalkTurns1.fbx-1532029632-22016.log](https://github.com/o3de/o3de/files/9809491/WalkTurns1.fbx-1532029632-22016.log)
[WalkPivotTurn1.fbx-1606648-22380.log](https://github.com/o3de/o3de/files/9809492/WalkPivotTurn1.fbx-1606648-22380.log)
[TurnOnSpot1.fbx-4099548688-7000.log](https://github.com/o3de/o3de/files/9809493/TurnOnSpot1.fbx-4099548688-7000.log)

Additionally, the AutomatedTesting has been verified and only the following jobs complete with errors for that project:
`o3de\AutomatedTesting\TestAssets\Animation\AlphabetP\P_Freeze_Transforms_DotName.fbx` platform: pc, android, server
`o3de\AutomatedTesting\TestAssets\Animation\AlphabetP\P_No_Freeze_Transforms_DotName.fbx` platform: pc, android, server

[P_No_Freeze_Transforms_DotName.fbx-44979723-3941.log](https://github.com/o3de/o3de/files/9809591/P_No_Freeze_Transforms_DotName.fbx-44979723-3941.log)
[P_Freeze_Transforms_DotName.fbx-3868291478-2264.log](https://github.com/o3de/o3de/files/9809593/P_Freeze_Transforms_DotName.fbx-3868291478-2264.log)

**Comment by monroegm** [comment]
Can @LB-KacperKapusta can you close this one and create a new issue for the new failures?

**Comment by LB-KacperKapusta** [comment]
Closing the issue according to the comment above. A new issue with new failures has been created under #12984.
