### ISSUE TITLE
test_hair_bone_chain_head_style.fbx asset processing error - ambiguous mesh group

### ISSUE THREAD

**Issue by AMZN-stankowi** [o3de/o3de#12618]
**Describe the bug**
test_hair_bone_chain_head_style.fbx has an asset processing error: Ambigious mesh for actor asset. More than one mesh group found. Defaulting to the first one.

**Assets required**
/o3de/Gems/AtomTressFX/Assets/TestData/HeadBoneChainHairStyle/test_hair_bone_chain_head_style.fbx

**Steps to reproduce**
1. /o3de/Gems/AtomTressFX/Assets/TestData/HeadBoneChainHairStyle/test_hair_bone_chain_head_style.fbx
2. View the results in the asset processor

**Expected behavior**
No errors

**Actual behavior**
error message
`Ambigious mesh for actor asset. More than one mesh group found. Defaulting to the first one.`

**Screenshots/Video**
N/A

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/c28de148b36251255ab6bd046d89d2c4e34551e4)

Desktop/Device
    Device: PC
    OS: Windows
    Version: 10
    CPU: AMD Ryzen 5 3600
    GPU: NVIDIA GeForce RTX 2060 SUPER
    Memory: 16GB

**Additional context**
https://github.com/o3de/o3de/issues/12612

[test_hair_bone_chain_head_style.fbx-3078959659-2454.log](https://github.com/o3de/o3de/files/9786861/test_hair_bone_chain_head_style.fbx-3078959659-2454.log)

**Comment by AMZN-stankowi** [comment]
Triage: This is an animation error. It's probably going to need a content update to address, but sending to the sig simulation, who owns characters, to look at first.

**Comment by hultonha** [comment]
Discussed in sig-simulation triage - tagging @amzn-rhhong and @moraaar for visibility on this for something to take a quick look at when possible. This hopefully should be something simple to update and resolve. Thanks!

**Comment by moraaar** [comment]
This error won't appear anymore with the latest, the error has been downgraded to a warning: https://github.com/o3de/o3de/pull/12587

So I think this bug can be closed based on the description.

If there is a further issue with `test_hair_bone_chain_head_style.fbx` about the actor generated not using the right mesh group... then that's not a bug but a feature request.

**Comment by hultonha** [comment]
Okay excellent thanks @moraaar - I do have an internal ticket for this that tracks the work but haven't migrated yet, it's on my todo list! :) Thanks for the info!
