### ISSUE TITLE
Component Mode Switcher doesn't handle component dependency changes

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#12628]
**Describe the bug**
If a component with Component Mode gets activated or deactivated by having a component it depends on added or removed, the Component Mode Switcher doesn't refresh.

**Steps to reproduce**
1. Run the Editor and create or open a level.
2. Create a new entity.
3. Add a tube shape component.
4. Add a spline component.

**Expected behavior**
Both the tube shape and spline components show up in the Component Mode Switcher.

**Actual behavior**
Only the spline shows up until you click off of the entity and back onto it.

**Screenshots/Video**
https://user-images.githubusercontent.com/82224783/195917605-fbd399ac-8831-429f-94d8-d107ce86c53e.mp4

**Found in Branch**
development

**Comment by hultonha** [comment]
Fixed by #12746
