### ISSUE TITLE
[PC][Quest2] Running Launcher/Editor on PC crashes when OpenXR is enabled and Quest2 is not connected

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#12659]
**Describe the bug**
Running O3DE launcher/editor with openxr enable and no openxr device connected leads to a crash.

**Steps to reproduce**
1. Build PC with a project that has XR and OpenXRVk gems enabled from o3de-extras repo.
2. Without a Quest2 device connected to PC, run Editor or Launcher with the command line options: `-rhi=vulkan -openxr=enable`

**Expected behavior**
Editor/Launcher runs normally as if openxr was disabled.

**Actual behavior**
Editor/Launcher crashes

**Comment by LB-HubertUberman** [comment]
Issue verified as fixed on the Development (https://github.com/o3de/o3de/commit/daed680fc7b2842b1afc37f1a7be6da5fe74e9f4).
