### ISSUE TITLE
Bug - Procprefab hierarchy is not correct and is different than other DCCs tools.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#12651]
**Describe the bug**
Procprefab hierarchy is not correct and is different than other DCCs tools.

Example of this model hierarchy in Autodesk Fusion 360:
![BaseLinkFusion](https://user-images.githubusercontent.com/87207603/196261094-0297ef07-2794-42b8-bfec-530061ef0dc4.png)

Exported as .FBX and opened in Blender, the hierarchy matches.
![BaseLinkBlender](https://user-images.githubusercontent.com/87207603/196261291-2ceb79bb-596c-42a8-858a-9b0c38dd2ccf.png)

If imported into O3DE it will have the base_link no parented to children.

![BaseLinkO3DE](https://user-images.githubusercontent.com/87207603/196261489-befcf4e6-95a3-4321-be96-d44f4aec096c.png)

**Assets required**
Here is .FBX asset: 
[Simple_Robot.zip](https://github.com/o3de/o3de/files/9803767/Simple_Robot.zip)

**Steps to reproduce**
1. Go to Asset Browser in O3DE Editor
2. Click on 'Instantiate a procedural prefab
3. Select attached Simple_Robot.fbx (Unzip the attached zip first)
4. Open Procedural Prafab in Entity Outliner
5. See error

**Expected behavior**
The Procprefab hierarchy is in the same order as DCCs tools

**Actual behavior**
The Procprefab hierarchy is in a different order as DCCs tools

**Found in Branch**
Nightly 10-17-2022

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Intel I9-9900k
 - GPU NVidia RTX 2080ti
 - Memory [e.g. 16GB]

**Comment by michabr** [comment]
Hi @shawstar, when I import the included Simple_Robot.fbx to Blender, I see the same hierarchy as that of O3DE where base_link:1 is a child of Simple_Robot V16. I don't see a Simple_Robot_URDF_Ready v6 at all:

![ProcPrefabHierarchy](https://user-images.githubusercontent.com/82236305/196758682-50dd3879-cd56-40c5-97b1-9811a4506ad5.jpg)

**Comment by shawstar** [comment]
Maybe it was Blender that changed it on export. When opening the FBX attached I also see it as such. 
![image](https://user-images.githubusercontent.com/87207603/196798672-702774e9-cedb-495b-bc83-bb392b76bf11.png)

**Comment by shawstar** [comment]
My Bad. After retesting it seems to work fine! 
![image](https://user-images.githubusercontent.com/87207603/196802057-34f7080f-7e3b-4663-913b-0ed837e322a6.png)
