### ISSUE TITLE
Asset Processor errors: specific Process Slice jobs

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#12666]
**Describe the bug**
This issue was created based on the comment in https://github.com/o3de/o3de/issues/12588.
The following Process Slice jobs complete processing with errors:

`/o3de/Gems/Vegetation/Assets/Slices/Examples/AreaBlender_Combined_Weighted.slice` platform: pc, android, server, linux
`/o3de/Gems/Vegetation/Assets/Slices/Examples/SimpleGrass_Area_01.slice` platform: pc, android, server, linux
`/o3de/Gems/Vegetation/Assets/Slices/Examples/SimpleFlowers_Area_02.slice` platform: pc, android, server, linux

The error messages for the mentioned jobs are:

- `Serialize: Element 'BaseClass1'(0xd4925735) with class ID '{8F3A2792-3E0E-5318-B87F-24E1C97E1ECF}' found in 'EditorReferenceShapeComponent' is not registered with the serializer!`
- `Dynamic Vegetation: Replacing legacy vegetation spawner with an empty instance spawner`
- `Serialize: Element 'InstanceSpawner'(0x47ea27f1) in class 'Descriptor' is of type {9247512F-7312-5DD7-91DA-344396014B5C} but needs to be type {7C7046DE-F8B1-529D-AD8C-829C6C0E2FCD}.`

**Steps to reproduce**
1. Create a new project with all gems enabled in Project Manager built in Source engine configuration (https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/).
2. Build the project.
3. Run the Asset Processor and wait for the scan to finish.

**Expected behavior**
All assets are processed without errors.

**Actual behavior**
The Process Slice jobs complete processing with errors.

**Found in Branch**
Development (14076b4)

**Desktop/Device**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[AreaBlender_Combined_Weighted.slice-543527810-17565.log](https://github.com/o3de/o3de/files/9810637/AreaBlender_Combined_Weighted.slice-543527810-17565.log)
[SimpleFlowers_Area_02.slice-629885878-8943.log](https://github.com/o3de/o3de/files/9810638/SimpleFlowers_Area_02.slice-629885878-8943.log)
[SimpleGrass_Area_01.slice-1237682155-11517.log](https://github.com/o3de/o3de/files/9810639/SimpleGrass_Area_01.slice-1237682155-11517.log)

**Comment by lmbr-pip** [comment]
Have slices ready to delete in https://github.com/o3de/o3de/pull/12679

**Comment by lmbr-pip** [comment]
Slices have been deleted

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed using Development (b746994) build.
