### ISSUE TITLE
Feature Request: Sky Atmosphere nodes in Script Canvas

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#12681]
**Is your feature request related to a problem? Please describe.**
As of right now there is no way to change the sky atmosphere's parameters through script canvas. 

**Describe the solution you'd like**
I would like to be able to change all the parameters that can be changed on the component also be changeable inside of script canvas.

**Describe alternatives you've considered**
An alternative is getting some of the parameters inside of script canvas that are more likely to be changed during runtime, including the sun size/falloff or all the sun parameters.

**Additional context**
The main parameters that I am looking for in script canvas nodes are the sun group of parameters.

**Comment by AMZN-alexpete** [comment]
A `SkyAtmosphereBus` was added in this PR https://github.com/o3de/o3de/pull/13815, which exposes the sky atmosphere parameters to Lua/ScriptCanvas via BehaviorContext and to Maestro via VirtualProperties.
