### ISSUE TITLE
Bug Report: Null Draw Packet Console Spam

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#12682]
**Describe the bug**
The Console spams a Null Draw Packet Error when having an entity selected. 

**Steps to reproduce**
1. Start up O3DE and open a level.
2. Place an entity with a mesh component and mesh attached.
3. Select the entity in the viewport.

**Expected behavior**
There is no Null Draw Packet console spamming.

**Actual behavior**
There is one message that keeps getting executed on the console every frame.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/100494538/196579303-a7f9f134-3271-4129-9014-e14dd376a735.png)

**Found in Branch**
Development [ce8bfb7]

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11

**Comment by LB-ArturZieba** [comment]
This also occurred on Development (18bd190), however we have noticed that restarting the Editor after first launch fixes this issue.

**Comment by ParasiteSt** [comment]
Hmm, I have had this issue for a couple development updates/rebuilds, and restarting the editor does not seem to fix the issue on my end. (Around 2 weeks now)

**Comment by ParasiteSt** [comment]
I just grabbed the newest Dev branch [a5e2145] and this issue still occurs. The upside is it does not seem to affect development in terms of a crash, but it does overtake the console, and makes it hard to debug aspects of your project.
