### ISSUE TITLE
Crash in AZSLC on a full asset cache rebuild

### ISSUE THREAD

**Issue by jackalbe** [o3de/o3de#12718]
**Describe the bug**

After clearing the asset cache the AZSLC tool will crash during a full asset rebuild when the "Child Process Debugger" Visual Studio extension is enabled. 

**Assets required**

The current assets in the Automated Testing project are enough to reproduce.

**Steps to reproduce**

Requirements: https://marketplace.visualstudio.com/items?itemName=vsdbgplat.MicrosoftChildProcessDebuggingPowerTool

1. Go to Visual Studio 
2. Click on Debug | Other Debug Targets | Child Process Debugging Settings...
3. Check "Enalble child process debugging"
4. Clear the asset cache
5. Debug the AssetProcessor GUI in the Visual Studio

![menu_child_proc_settings](https://user-images.githubusercontent.com/23512001/197048251-2ae8ca88-cd5c-4af2-bedd-6d0cad31f4ce.png)

![child_proc_settings](https://user-images.githubusercontent.com/23512001/197048287-688267f5-96d1-4617-86ab-e04178631a4c.png)

**Expected behavior**

No crashes encountered from AZSLC. 

**Actual behavior**

Crashes encountered from AZSLC. 

**Call Stack**

azslc.exe in Main Thread:
```
ntdll.dll!LdrpDoDebuggerBreak()
ntdll.dll!LdrpInitializeProcess()
ntdll.dll!_LdrpInitialize()	
ntdll.dll!LdrpInitialize()	
ntdll.dll!LdrInitializeThunk()
```

**Found in Branch**

Development 

**Desktop/Device (please complete the following information):**

 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Ryzen 5900x
 - GPU NVidia RTX 
 - Memory 32GB

**Additional context**

It is possible to "Continue" past the 'LdrpDoDebuggerBreak' statement, but this issue slows down debugging the Asset Processor issues.

**Comment by galibzon** [comment]
I don't think there's no way to workaround this problem, other than customizing the "Child Process Debugger" to only attach to processes for which there's code.
