### ISSUE TITLE
Link not found errors get thrown when switching prefab edit modes

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/o3de#12725]
**Describe the bug**
When switching between edit modes for different prefabs, error messages pop up in the console with the text : "PrefabUndoLinkUpdate: Link not found."

**Assets required**
See the 'OverrideTesting_Assets.zip' zip file
[OverrideTesting_Assets.zip](https://github.com/o3de/o3de/files/9834285/OverrideTesting_Assets.zip)

**Steps to reproduce**

1. Download the zip file
2. Put the 'ModelCity' folder in your {project}/Levels folder
3. Put the 2 prefabs in {Project}/Prefabs folder
5. Start the editor and open the 'modelCity' level
5. Enter edit mode for the first 'modelBlock' prefab
6. Enter edit mode for the fourth 'modelHouse' prefab within the above prefab
8. Switch back to the edit mode for the first 'modelBlock' prefab under the city

**Expected behavior**
no errors get shown

**Actual behavior**
errors get shown

**Screenshots/Video**

https://user-images.githubusercontent.com/11157226/197249467-5e8c8d54-b7ab-4bbd-ace3-fed5bf1cf9d4.mp4

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen Threadripper 3970X 32-Core Processor  3.70 GHz
GPU NVidia GeForce RTX Super 2060
Memory 64GB

**Comment by forkercat** [comment]
Looks like the issue did show up anymore after this change got merged for create-prefab improvement: https://github.com/o3de/o3de/pull/12506. The new change ensures the template is updated correctly so no more weird patches get generated and saved to file.

I will resolve the issue for now and reopen if it shows up again.
