### ISSUE TITLE
Incorrect override changes get propagated to prefabs when switching focus

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/o3de#12724]
**Describe the bug**
Switching between the edit mode of multiple prefabs makes incorrect override change to get propagated

**Assets required**
See the 'OverrideTesting_Assets.zip' zip file
[OverrideTesting_Assets.zip](https://github.com/o3de/o3de/files/9834278/OverrideTesting_Assets.zip)

**Steps to reproduce**
1. Download the zip file
2. Put the 'ModelCity' folder in your {project}/Levels folder
3. Put the 2 prefabs in {Project}/Prefabs folder
4. Start the editor and open the 'modelCity' level
5. Enter edit mode for the first 'modelBlock' prefab
6. Enter edit mode for the fourth 'modelHouse' prefab within the above prefab
7. Enter edit mode for the second 'modelBlock' prefab under the city
8. Switch back to the edit mode for the first 'modelBlock' prefab under the city

**Expected behavior**
After all the steps, notice that the unique override from the level gets propagated to all the 'modelBlock' prefabs

**Actual behavior**
When switching to 'modelBlock' prefab, remaining 3 instances should remain untouched.

**Screenshots/Video**

https://user-images.githubusercontent.com/82230713/197069454-126a48e5-e411-4d81-9f43-f4f599e8dea0.mp4

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen Threadripper 3970X 32-Core Processor  3.70 GHz
GPU NVidia GeForce RTX Super 2060
Memory 64GB

**Additional context**

In the asset, there are two overrides:
- One is in ModelCity that makes the house look green.
- The other one is in ModelBlock that makes the house look blue.

This should explain why color of the house is changing in the video.

**Comment by srikappa-amzn** [comment]
Marking it as critical since this can leave the user's level in a pretty bad state.

**Comment by forkercat** [comment]
Added additional context about what are overridden in this asset. Also link to the other issue https://github.com/o3de/o3de/issues/12725 that could be related.

**Comment by michabr** [comment]
This issue is no longer reproducible, perhaps for the same reason as https://github.com/o3de/o3de/issues/12725.
