### ISSUE TITLE
Bug Report: CMAKE 3.23.2 with O3DE 22.10.0 config issues

### ISSUE THREAD

**Issue by OBWANDO** [o3de/o3de#12731]
**Describe the bug**
When configuring CMAKE 3.23.2 with O3DE 22.10.0 release install, it fails to configure citing issues.

**Assets required**
N/A

**Steps to reproduce**
1. Install Using O3DE release installer
2. start cmake 3.23.2 GUI
3. Select installed path and new build folder
4. Click "Configure"
5. See error

**Expected behavior**
Configure and generate completes without error

**Actual behavior**
Configure fails to complete.

**Screenshots/Video**
Log file: (Verbose enabled)
Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.22000.
Using package C:/Users/OBWANDO/.o3de/3rdParty/packages/zlib-1.2.11-rev5-windows
Using package C:/Users/OBWANDO/.o3de/3rdParty/packages/qt-5.15.2-rev7-windows
Using package D:/o3de/release/22.10.0/python/runtime/python-3.10.5-rev1-windows
Using Python 3.10.5 at D:/o3de/release/22.10.0/python/runtime/python-3.10.5-rev1-windows/python/python.exe
    Python_EXECUTABLE:  D:/o3de/release/22.10.0/python/runtime/python-3.10.5-rev1-windows/python/python.exe
    Python_HOME:        D:/o3de/release/22.10.0/python/runtime/python-3.10.5-rev1-windows/python
    Python_PATHS:       D:/o3de/release/22.10.0/python/runtime/python-3.10.5-rev1-windows/python/Lib;D:/o3de/release/22.10.0/python/runtime/python-3.10.5-rev1-windows/python/Lib/site-packages;D:/o3de/release/22.10.0/python/runtime/python-3.10.5-rev1-windows/python/DLLs
Python: linking D:/o3de/release/22.10.0/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools into python site-packages...
pip uninstall result: 0
pip uninstall output: WARNING: Skipping editor-python-test-tools as it is not installed.

pip install result: 1
pip install output: ERROR: D:/o3de/release/22.10.0/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

Python: linking D:/o3de/release/22.10.0/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools into python site-packages... - Failed to install D:/o3de/release/22.10.0/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools: ERROR: D:/o3de/release/22.10.0/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
 - use CMAKE_MESSAGE_LOG_LEVEL to VERBOSE for more information
CMake Error at CMakeLists.txt:64 (add_subdirectory):
  The source directory

    D:/o3de/release/22.10.0/Assets

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:65 (add_subdirectory):
  The source directory

    D:/o3de/release/22.10.0/Code

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:66 (add_subdirectory):
  The source directory

    D:/o3de/release/22.10.0/python

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:67 (add_subdirectory):
  The source directory

    D:/o3de/release/22.10.0/Registry

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:68 (add_subdirectory):
  The source directory

    D:/o3de/release/22.10.0/scripts

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:69 (add_subdirectory):
  The source directory

    D:/o3de/release/22.10.0/Templates

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:70 (add_subdirectory):
  The source directory

    D:/o3de/release/22.10.0/Tools

  does not contain a CMakeLists.txt file.

add_subdirectory will be called on the following external subdirectories in order:
D:/o3de/release/22.10.0/Gems/Achievements
D:/o3de/release/22.10.0/Gems/AssetValidation
D:/o3de/release/22.10.0/Gems/Atom/RHI/DX12
D:/o3de/release/22.10.0/Gems/Atom/RHI/Metal
D:/o3de/release/22.10.0/Gems/Atom/RHI/Vulkan
D:/o3de/release/22.10.0/Gems/Atom/RHI/Null
D:/o3de/release/22.10.0/Gems/Atom/RHI
D:/o3de/release/22.10.0/Gems/Atom/RPI
D:/o3de/release/22.10.0/Gems/LmbrCentral
D:/o3de/release/22.10.0/Gems/ImGui
D:/o3de/release/22.10.0/Gems/Atom/Feature/Common
D:/o3de/release/22.10.0/Gems/Atom/Asset/Shader
D:/o3de/release/22.10.0/Gems/Atom/Bootstrap
D:/o3de/release/22.10.0/Gems/Atom/Component/DebugCamera
D:/o3de/release/22.10.0/Gems/GraphCanvas
D:/o3de/release/22.10.0/Gems/GraphModel
D:/o3de/release/22.10.0/Gems/Atom/Tools/AtomToolsFramework
D:/o3de/release/22.10.0/Gems/Atom/Asset/ImageProcessingAtom
D:/o3de/release/22.10.0/Gems/SurfaceData
D:/o3de/release/22.10.0/Gems/GradientSignal
D:/o3de/release/22.10.0/Gems/AtomLyIntegration/CommonFeatures
D:/o3de/release/22.10.0/Gems/Atom/Tools/MaterialCanvas
D:/o3de/release/22.10.0/Gems/Atom/Tools/MaterialEditor
D:/o3de/release/22.10.0/Gems/Atom/Tools/ShaderManagementConsole
D:/o3de/release/22.10.0/Gems/AtomLyIntegration/ImguiAtom
D:/o3de/release/22.10.0/Gems/AtomLyIntegration/AtomImGuiTools
D:/o3de/release/22.10.0/Gems/EMotionFX
D:/o3de/release/22.10.0/Gems/AtomLyIntegration/EMotionFXAtom
D:/o3de/release/22.10.0/Gems/AtomLyIntegration/AtomFont
D:/o3de/release/22.10.0/Gems/AtomLyIntegration/AtomViewportDisplayInfo
D:/o3de/release/22.10.0/Gems/AtomLyIntegration/AtomViewportDisplayIcons
D:/o3de/release/22.10.0/Gems/AtomLyIntegration/AtomBridge
D:/o3de/release/22.10.0/Gems/Atom
D:/o3de/release/22.10.0/Gems/AtomContent/Sponza
D:/o3de/release/22.10.0/Gems/AtomContent/ReferenceMaterials
D:/o3de/release/22.10.0/Gems/AtomContent
D:/o3de/release/22.10.0/Gems/AtomLyIntegration/EditorModeFeedback
D:/o3de/release/22.10.0/Gems/AtomLyIntegration
D:/o3de/release/22.10.0/Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface
D:/o3de/release/22.10.0/Gems/AtomTressFX
D:/o3de/release/22.10.0/Gems/AudioSystem
D:/o3de/release/22.10.0/Gems/AudioEngineWwise
D:/o3de/release/22.10.0/Gems/AWSCore
D:/o3de/release/22.10.0/Gems/HttpRequestor
D:/o3de/release/22.10.0/Gems/AWSClientAuth
D:/o3de/release/22.10.0/Gems/AWSGameLift
D:/o3de/release/22.10.0/Gems/AWSMetrics
D:/o3de/release/22.10.0/Gems/BarrierInput
D:/o3de/release/22.10.0/Gems/PhysX
D:/o3de/release/22.10.0/Gems/EditorPythonBindings
D:/o3de/release/22.10.0/Gems/PythonAssetBuilder
D:/o3de/release/22.10.0/Gems/Blast
D:/o3de/release/22.10.0/Gems/Camera
D:/o3de/release/22.10.0/Gems/CameraFramework
D:/o3de/release/22.10.0/Gems/CertificateManager
D:/o3de/release/22.10.0/Gems/Compression
D:/o3de/release/22.10.0/Gems/CrashReporting
D:/o3de/release/22.10.0/Gems/CustomAssetExample
D:/o3de/release/22.10.0/Gems/DebugDraw
D:/o3de/release/22.10.0/Gems/DevTextures
D:/o3de/release/22.10.0/Gems/DiffuseProbeGrid
D:/o3de/release/22.10.0/Gems/ExpressionEvaluation
D:/o3de/release/22.10.0/Gems/FastNoise
D:/o3de/release/22.10.0/Gems/GameState
D:/o3de/release/22.10.0/Gems/LocalUser
D:/o3de/release/22.10.0/Gems/TextureAtlas
D:/o3de/release/22.10.0/Gems/UiBasics
D:/o3de/release/22.10.0/Gems/LyShine
D:/o3de/release/22.10.0/Gems/SaveData
D:/o3de/release/22.10.0/Gems/MessagePopup
D:/o3de/release/22.10.0/Gems/LyShineExamples
D:/o3de/release/22.10.0/Gems/GameStateSamples
D:/o3de/release/22.10.0/Gems/Gestures
D:/o3de/release/22.10.0/Gems/InAppPurchases
D:/o3de/release/22.10.0/Gems/LandscapeCanvas
D:/o3de/release/22.10.0/Gems/Maestro
D:/o3de/release/22.10.0/Gems/Metastream
D:/o3de/release/22.10.0/Gems/Microphone
D:/o3de/release/22.10.0/Gems/MotionMatching
D:/o3de/release/22.10.0/Gems/Multiplayer
D:/o3de/release/22.10.0/Gems/MultiplayerCompression
D:/o3de/release/22.10.0/Gems/NvCloth
D:/o3de/release/22.10.0/Gems/PhysXDebug
D:/o3de/release/22.10.0/Gems/Prefab/PrefabBuilder
D:/o3de/release/22.10.0/Gems/Presence
D:/o3de/release/22.10.0/Gems/PrimitiveAssets
D:/o3de/release/22.10.0/Gems/Streamer
D:/o3de/release/22.10.0/Gems/Streamer/StreamerProfiler
D:/o3de/release/22.10.0/Gems/Profiler
D:/o3de/release/22.10.0/Gems/QtForPython
D:/o3de/release/22.10.0/Gems/RecastNavigation
D:/o3de/release/22.10.0/Gems/RemoteTools
D:/o3de/release/22.10.0/Gems/SceneLoggingExample
D:/o3de/release/22.10.0/Gems/SceneProcessing
D:/o3de/release/22.10.0/Gems/ScriptAutomation
D:/o3de/release/22.10.0/Gems/ScriptEvents
D:/o3de/release/22.10.0/Gems/ScriptCanvas
D:/o3de/release/22.10.0/Gems/ScriptCanvasDeveloper
D:/o3de/release/22.10.0/Gems/ScriptCanvasPhysics
D:/o3de/release/22.10.0/Gems/ScriptCanvasTesting
D:/o3de/release/22.10.0/Gems/ScriptedEntityTweener
D:/o3de/release/22.10.0/Gems/SliceFavorites
D:/o3de/release/22.10.0/Gems/Stars
D:/o3de/release/22.10.0/Gems/StartingPointCamera
D:/o3de/release/22.10.0/Gems/StartingPointInput
D:/o3de/release/22.10.0/Gems/StartingPointMovement
D:/o3de/release/22.10.0/Gems/Terrain
D:/o3de/release/22.10.0/Gems/TestAssetBuilder
D:/o3de/release/22.10.0/Gems/TickBusOrderViewer
D:/o3de/release/22.10.0/Gems/Twitch
D:/o3de/release/22.10.0/Gems/Vegetation
D:/o3de/release/22.10.0/Gems/VideoPlaybackFramework
D:/o3de/release/22.10.0/Gems/VirtualGamepad
D:/o3de/release/22.10.0/Gems/WhiteBox
Using package C:/Users/OBWANDO/.o3de/3rdParty/packages/RapidJSON-1.1.0-rev1-multiplatform
Note: ly_enable_gems called with no PROJECT_NAME name, applying to all projects: 
   - GEMS     PrefabBuilder 
   - GEM_FILE 
CMake Error at CMakeLists.txt:91 (ly_delayed_generate_static_modules_inl):
  Unknown CMake command "ly_delayed_generate_static_modules_inl".

Configuring incomplete, errors occurred!
See also "D:/o3de/release/22.10.0/build/vs2022/CMakeFiles/CMakeOutput.log".

**Found in Branch**
Main

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 
 - Version 11 Pro
 - CPU I9-12900k
 - GPU NVidia RTX 3090 Ti
 - Memory 64GB

**Additional context**

**Comment by lumberyard-employee-dm** [comment]
The installer shouldn't actually contain the AutomatedTesting project within it.
Based on the failure it looks like it the installer is missing files as if all the artifacts weren't downloaded by the installer

**Comment by amzn-changml** [comment]
Hi @OBWANDO, can you confirm that this is still an issue with @lumberyard-employee-dm's guidence?

**Comment by lsemp3d** [comment]
This is from an older release and no longer present
