### ISSUE TITLE
The Editor cannot be closed if the UI Editor is docked in a separate window with another tool

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#12739]
**Describe the bug**
The Editor cannot be closed if there is a separate window open that contains UI Editor and a different tool docked together. Additionally, attempting to close the UI Editor in that window causes it to become blank. This can be worked around by reopening/closing the UI Editor in the Tools menu.

It should be noted that on Linux this reproduced each time, however on Windows this only occurred on 1 out of 4 PCs.

**Steps to reproduce**
1. Go to Tools > UI Canvas.
2. If the UI Editor pane is docked, undock it and leave it floating as a separate window.
3. Open another tool that can be docked along with the UI Editor (for example Tools > Script Canvas).
4. Dock the tool opened in step 3 in the window with UI Editor, so that there are two tabs in that window.
5. Close the Editor by clicking the *X* in the top right corner of the window.
6. Attempt to close the UI Editor tab.

**Expected behavior**
Editor closes on step 5.

**Actual behavior**
Editor does not close on step 5, instead it distorts for a moment and remains open. Attempting to close the UI Editor leaves its window blank.

**Video**

https://user-images.githubusercontent.com/86952082/197204053-5ea2536d-4583-4336-a4cf-8f908304b045.mp4

**Found in Branch**
Development (b746994)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by rainbj** [comment]
@LB-ArturZieba Sig-UI-UX agrees this is a bug and UX is ok with the team moving forward with a fix without UX help. Please let us know if any global changes are being made because of this. Thanks.

**Comment by michabr** [comment]
Hi @LB-ArturZieba, I was able to repro on Linux and put up a PR for the fix.

On Windows I was not able to repro the issue. This could happen if a user has made changes to a UI Canvas and then tries to close the Editor but presses "Cancel" when prompted to save the UI Canvas, but that's expected behavior.

**Comment by LB-KacperMetelski** [comment]
Issue still occurs on commit e12b937 on Linux; issue doesn't occur on Windows.
