### ISSUE TITLE
Intermediate Assets Can Cause Transient Asset Processor Failures

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#12745]
**Describe the bug**
I encountered this issue while utilizing intermediate asset processing for the new material pipeline system. See https://github.com/o3de/o3de/pull/12717

I have asset A producing intermediate assets B and C. It looks like the AP sees B before it sees C, so it processes B and fails (because when a job dependency is missing, the AP ignores it the dependency). Then later it discovers C, processes C, and then processes B again and passes. (This occurred in 1 of 3 Jenkins runs)

Similarly (but possibly a separate underlying issue), there is another source file D that has a source dependency on the intermediate file B. The AP processes D before processing A, so the intermediate file is missing, and D fails.

In both cases, everything builds correctly in the end. C is finally discovered, the AP reprocesses B and passes, then reprocesses D and passes. **But** Jenkins finds failure messages in the log and so fails the AR process. This blocks us from being able to check in assets that use the material pipeline. (This occurred in 3 of 3 Jenkins runs)

There are couple instances of this situation in the log, one for a "Basic" material type and one for an "Animated" material type. Here is a concrete breakdown of the files involved for one of these instances:
A=MaterialPipelineTest_Animated.materialtype (Source) It produces B and C.
B=materialpipelinetest_animated_generated.materialtype (Intermediate) It has a job dependency on C.
C=MaterialPipelineTest_Animated_LowEndPipeline_ForwardPass.shader (Intermediate)
D=MaterialPipelineTest_Animated.material (Source) It has a source dependency on B.

The original failure log is here: https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-12717/2/execution/node/501/log/?consoleFull
I have attached a copy here: [APLog.txt](https://github.com/o3de/o3de/files/9841382/APLog.txt)

For now I am going to work around this issue by disabling the material pipeline system in the AutomatedTesting project.

**Assets required**
This will be a bit tricky, since I have changes in flight on a feature branch, and I'm going to work around the issue by disabling the material pipeline system in the AutomatedTesting project. If the code has not been merged yet, you'll need to check out my branch at https://github.com/aws-lumberyard-dev/o3de/tree/Atom/santorac/MaterialPipeline1. Also checkout AtomSampleViewer, again using this branch if the changes have not been merged yet: https://github.com/aws-lumberyard-dev/o3de-atom-sampleviewer/tree/Atom/santorac/MaterialPipeline1

**Steps to reproduce**
This is a little tricky because the failures are transient and will correct themselves. I think there are a couple ways you can see this occur. 

A
1. Clear the cache (or just delete and later replace the MaterialTypes folder)
1. Run the AP.
1. Type a filter for "MaterialPipeline"
1. You might be able to see red failure icons by some assets temporarily.

B
1. Clear the cache (or just delete and later replace the MaterialTypes folder)
1. In visual studio, enable auto-attach to child processes.
1. Run the AssetProcessor with a debugger attached.
1. The debugger will break, like a process crashed. I think this is related.

C
1. Clear the cache (or just delete and later replace the MaterialTypes folder)
1. Put a breakpoint where MaterialTypeBuilder::CreateJobs and ProcessJob return.
1. Put a breakpoint where MaterialBuilder::CreateJobs and ProcessJob return.
1. Run the AP.
1. Attach a debugger to AssetBuilder.exe(s)
1. Look for error return

D
1. Run Jenkins AR against my feature branch at commit 6f88edb883a16a7d0301b0db0a15d1214bcf4201

**Expected behavior**
Jeknins should pass because all assets passed in the end. But ideally there should be no transient error states. The AP should understand what's going on well enough to avoid processing source files or intermediate files that aren't ready.

**Actual behavior**
The AP experiences transient failures that later correct themselves, but the Jenkins jobs sees this as a blocking failure.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
https://github.com/aws-lumberyard-dev/o3de/tree/Atom/santorac/MaterialPipeline1

**Comment by santorac** [comment]
My workaround is to just disable the new material system in the AutomatedTesting project while I continue iterative development. However, this issue will block integration of the new feature, and I won't be able to use it for our actual material types until it's fixed. So while I'm not immediately blocked, this issue will be critical within the next couple weeks.

**Comment by junbo75** [comment]
Thanks for the info, @santorac. I'll change this to a critical.

**Comment by amzn-mike** [comment]
Closing this as both of the fixes for this have been merged and this should now be resolved.
