### ISSUE TITLE
Component Mode Switcher allows switching to disabled / hidden component modes

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#12768]
**Describe the bug**
The Image Gradient component has states in which its component mode isn't active, but the Component Mode Switcher allows switching to the component mode anyways, potentially resulting in errors or crashes.

**Steps to reproduce**
1. Run the Editor and open or create a level.
2. Create a new entity.
3. Add components in the following order:  Box Shape, Gradient Transform Modifier, Image Gradient

**Expected behavior**
Because the Image Gradient doesn't have an image selected yet, the "Edit" button is hidden on the component. Therefore, it ought to be hidden or disabled on the Component Switcher as well.

**Actual behavior**
The Image Gradient component mode is available on the Component Switcher and can be switched to, resulting in undefined behavior.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82224783/197560638-4712952f-edd3-4d76-b87c-8291341791d9.png)

**Found in Branch**
Development

**Comment by lmbr-pip** [comment]
Assigned to both content and graphics as its unclear if fix is in the image gradient component (assume that is owned by graphics) or in the component switcher (editor). Please make a call and assign to correct SIG, thanks.

**Comment by galibzon** [comment]
Assigned to @hultonha as this is just a CMS issue.

**Comment by hultonha** [comment]
This is something @amzn-ahmadkrm will be looking at shortly, I've updated the labels and assigned 👍
