### ISSUE TITLE
EMotionFX Editor is very laggy with O3DE 22.10

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#12767]
**Describe the bug**
EMotionFX Editor runs at a very low fps even with no assets loaded.

**Assets required**
o3de 22.10 installer, brand new project

**Steps to reproduce**
1. Installer O3DE 22.10
2. Create a new project
3. Build the project
4. Launch the Editor
5. Create a brand new test level
6. Create an entity
7. Add Anim Graph component
8. Open EMotionFX Editor from that component
9. Observe performance of EMFX editor by clicking around the menus, no need to even load the assets

**Expected behavior**
EMFX editor performs well

**Actual behavior**
EMFX editor is lagy

**Found in Branch**
22.10 installer

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU 5900x
 - GPU NVidia RTX 3090
 - Memory 1286GB

**Comment by amzn-rhhong** [comment]
@AMZN-Olex reported the problem went away over time. I tried on a fresh machine but I cannot reproduce the problem. I will close the problem for now, but keep an eye about it. 
We had some discussion to offer a better emfx performance monitoring system in the past. This would be another very valuable evidence that such system is needed.
