### ISSUE TITLE
Create Material Document: As a Dev I want to Type My Own Path

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#12782]
**Is your feature request related to a problem? Please describe.**
When creating a new material I want to type my own file path

**Describe the solution you'd like**
It might be that I dont actually want to type my own path, but the color looks like I can type in there. Maybe grey out the textbox if I cant type in it.

![image](https://user-images.githubusercontent.com/32776221/197641856-9feea3b1-36f1-43fd-b6ca-cd480af4575a.png)

**Comment by gadams3** [comment]
Duplicates https://github.com/o3de/o3de/issues/12781
