### ISSUE TITLE
Import graphics files without UV maps

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#12795]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I work with poorly exported meshes - it is rendered without any shading.
Such meshes are commonly provided in ROS2 description packages. Some examples you can be found here
https://github.com/husky/husky/blob/foxy-devel/husky_description/meshes/wheel.dae
The problem is missing UV mapping. 
In the image left monkey was created in Blender and exported without UV, right, on another hand was created with UV.
![Screenshot from 2022-10-25 16-16-00](https://user-images.githubusercontent.com/3209244/197799861-1341e5e6-f4a1-4505-93d0-9b759df02ab6.png)

**Describe the solution you'd like**
Have some simple shading when mesh without UV maps is imported

**Describe alternatives you've considered**
Generate placeholder by AssetProcessor

**Additional context**
Two DAE files I used for screenshots:
https://gist.github.com/michalpelka/b82d5898cda935c6cb84d99d2430b438

**Comment by lmbr-pip** [comment]
Most likely involves a default shader when then are no UVs, assigning to Graphics and removing asset pipeline labels.

**Comment by AMZN-stankowi** [comment]
STL files are a good way to test this, too. The STL file format does not support UVs.

**Comment by pawelbudziszewski** [comment]
And it seems that models of some robots are distributed in STL instead of Collada (eg. https://github.com/husarion/rosbot_ros), which causes more problems when importing such robots.

**Comment by lawsonamzn** [comment]
For the robotics usecase the prevalance of things that have no uv coords is actually very high, this needs to be fixed somehow.

**Comment by lawsonamzn** [comment]
I see at least 2 possible ways to fix this...

One way to do it may be to give normals and uvs the same same treatment as we do tangents - that is, there is an option to "generate tangents" (based on normals and uvs).   In the same way, it might be possible to generate normals using average or face normals, and then use xatlas or even just basic spherical coordinate mapping to generate uvs.  Then generate tangents from that.  So there's already kind of a trail blazed here - however the 'generate tangents' feature works (and shows up in the GUI) could be duplicated for 'generate uvs' and 'generate normals'.

**Comment by lawsonamzn** [comment]
I've got a working prototype of this (in case anyone was planning to work on it, trying to avoid duplicate work)
stay tuned

**Comment by lawsonamzn** [comment]
Note that the above feature is a new feature, an was thus added to Development, not Stabilization.  An argument _could_ maybe be made for stabilization but it seems like a stretch to claim that this is stabilizing something.
