### ISSUE TITLE
[Android] The Default Project app does not launch with assets by VFS setup

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#12839]
**Describe the bug**
Upon launching the app on a device for Default Project setup with "assets by VFS" the following error is thrown:
```
O3DE Initialization Failed
O3DE could not initialize correctly for the following reason(s):
Unable to find product asset 'Shaders/SimpleTextured.azshader'. Has
the source asset finished building?
Could not load font: Fonts/default.font
Could not load font: Fonts/default-ui.font
```
Additionally, the Asset Processor does not obtain connection displaying the following error:
```
Negotiation Failed
An attempt to connect to the game or editor has failed. The game or editor 
appears to be running from a different folder or different project. Please
restart the asset processor from the correct branch or make sure the game/
editor is running the same project as the asset processor.
```
Please note that the "assets in APK" and "assets in sdcard" packaging modes launch correctly.
For further information refer to the attached screenshots.

The setup was working correctly on Development (ce8bfb7) when it was last checked.

**Prerequisites**
- Follow Project Requirements and "Assets by VFS (minimum assets in sdcard)" https://github.com/o3de/sig-platform/blob/main/testing-guidance/workflow-tests/android/android-lkg-workflows.md

**Steps to reproduce**
1. Launch the Asset Processor for Default Project.
2. With the mobile device connected to PC run this command from the console: `adb reverse tcp:45643 tcp:45643`.
3. Launch the deployed app.

**Expected behavior**
Asset Processor obtains connection and the app launches successfully.

**Actual behavior**
Asset Processor does not obtain connection and the app does not launch displaying errors.

**Screenshots/Video**
![O3DEInitializationFailed](https://user-images.githubusercontent.com/86953659/198244104-4cc84c3c-d3b1-4574-891a-c71a3e64eda9.jpg)
![NegotiationFailed](https://user-images.githubusercontent.com/86953659/198244118-b30ff56e-da1e-4fc0-8376-9877d6247b8a.PNG)

**Found in Branch**
Development (52059cb)

**Device**
 - Device: Samsung S20+
 - OS: Android
 - Version 11 (API 30)

**Comment by byrcolin** [comment]
@moraaar Have you run into this? leave some feedback.

**Comment by moraaar** [comment]
Thanks for the tag. I was able to run with VFS using the Quest 2 with the latest from today. I'll double check tomorrow using an android phone and no openxr. I'll comment the result here.

**Comment by moraaar** [comment]
I checked running Android using VFS with the latest today and worked as expected. I can think of 2 potential issues:

1. The `.setreg` files created under `<project-path>/user/Registry/` were not picked up by AP. To avoid this mistake to happen again I've created a [PR](https://github.com/o3de/sig-platform/pull/61) updating the LKG page to use `<project-path>/Registry/` folder instead. Please @LB-KacperKapusta run the steps again but using `<project-path>/Registry/` folder for the .setreg files.

2. Minimum assets have not been copied to the device. This is done in step 3.d under "Assets by VFS" in the doc. Make sure you use the option `BOTH` in the `deploy_android-py`.

I'll close the bug, but feel free to reopen it if you still have issues.

**Comment by LB-KacperKapusta** [comment]
I have reverified the VFS setup using Development (6c2ed5b) and following the steps described by @moraaar in the comment above and the issue does no longer occur.

**Comment by LB-KacperKapusta** [comment]
Reopening the issue as it has been observed reoccurring on today's Development ([a775010](https://github.com/o3de/o3de/commit/a775010c5c3ea6b067df2ef0a398fbe02bb54434)) and last week's commit ([9c57ede](https://github.com/o3de/o3de/commit/9c57ede2d6c25fb5fd7ede42a30cc9240d9a46da)) as mentioned in #14723. The only difference between now and the original issue is that the app on the device no longer displays the `O3DE Initialization Failed` message but crashes on launch instead with the following log: 
[Logcat_VFS_crash.txt](https://github.com/o3de/o3de/files/10861568/Logcat_VFS_crash.txt)

Please note that all Android assets have been processed by the AP without failures and potential solutions from the comments above have been applied carefully.
![AP_VFS](https://user-images.githubusercontent.com/86953659/222155041-874aeebc-5a91-4f48-8360-00d352842364.PNG)
Additional info:
[bootstrap.game.profile.setreg.txt](https://github.com/o3de/o3de/files/10861598/bootstrap.game.profile.setreg.txt)

**Comment by byrcolin** [comment]
I haven't seen this when using the correct AP, often this means you are connecting the client to the wrong running AP. The negotiation fails because it checks to make sure this is the correct AP root. I think this is just user error. I will retry and close if not seen.

**Comment by LB-KacperKapusta** [comment]
The issue has been reproduced when using only the correct Asset Processor. It has been verified multiple times.
