### ISSUE TITLE
Building engine fails with error message

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#12838]
**Describe the bug**
The following error occurs during the engine building which stops the process.
```
C:\Builds\o3de\Code\Framework\AzCore\AzCore/std/utility/expected.h(193,1): error C2938: 'std::enable_if_t<false,AZStd::
expected<ValueT,AZStd::unexpect_t>&>' : Failed to specialize alias template
[C:\Builds\o3de\build\windows_vs2019\Code\Framework\AzCore\AzCore.vcxproj]
```
[CMDoutput10272022.txt](https://github.com/o3de/o3de/files/9877943/CMDoutput10272022.txt)

- Full CMD output is attached to the issue.

- Please note that this issue does not occur on Linux platform.

- We have noticed that the issue started to occur with the following commit - 3fe4b89

**Steps to reproduce**

1. Clone and setup the Development branch from Github.
2. Build the engine using the following commands:
- cmake -B build/windows_vs2019 -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\O3DE\o3de-packages -DLY_UNITY_BUILD=ON -DLY_VERSION_ENGINE_NAME=o3de-install -DCMAKE_INSTALL_PREFIX=C:\O3DE-install
- cmake --build build\windows_vs2019 --target INSTALL --config profile -- /m

**Expected behavior**
The engine building is finished successfully.

**Actual behavior**
A C2938 error occurs during the engine building, blocking the process.

**Found in Branch**
Development (8a9db6c)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows, Linux
 - Version: Windows 11 21H2 , Ubuntu 24.04.1
 - CPU Intel I7-11700F
 - GPU NVidia RTX 3070
 - Memory 32GB

**Comment by LB-BartoszDudzinski** [comment]
Closing the issue as fixed. The pull request which fixes it was already merged into development in commit (575a293). The issue no longer occurs.
