### ISSUE TITLE
Drag and dropping .fbx assets from Asset Browser to Viewport works inconsistently

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#12844]
**Describe the bug**
After drag and dropping a .fbx asset from the **Asset Browser** to the **Viewport** window, an entity is created with a localization path of used asset as its name (e. g. If BeveledCone.fbx asset was drag and dropped, the name of entity will be:  "buildso3deGemsAtomToolsMaterialEditorAssetsMaterialEditorViewportModelsBeveledCone_fbx").

Also, the asset assigned to the **Mesh** component is different:
`default_BeveledCone_327C2260_D9FF_575F_8406_7C8F651CEC27_` instead of `beveledcone`.

Assigning the **BeveledCone.fbx** manually in the **Mesh** component works as expected and mesh is displayed in the **Viewport**.

Note that this issue does **not** reproduce on every asset as the _Sphere_1x1.fbx (included in the **Primitive Assets** Gem) works correctly.

**Steps to reproduce**
1. Create a new level.
2. In **Asset Browser** find **BeveledCone.fbx** asset.
3. Drag the **BeveledCone.fbx** asset from **Asset Browser** into the **Viewport** window.

**Additional steps**
4. In **Asset Browser** find **_Sphere_1x1.fbx** asset.
5. Drag the **_Sphere_1x1.fbx** asset from **Asset Browser** into the **Viewport** window.

**Expected behavior**
Drag and dropping .fbx assets from **Asset Browser** to the **Viewport** window results in creating an entity with the name of the used asset and correctly assigned .fbx asset to the component.

**Actual behavior**
Drag and dropping .fbx assets is inconsistent. When using particular assets, created entity name becomes a path of the used asset, the mesh is not displayed in the **Viewport** and the asset assigned in the **Mesh** component is also incorrect.

**Video**

https://user-images.githubusercontent.com/86951967/198290421-f73503dc-d6ae-4cb1-b212-c328cbc09ccd.mp4

**Found in Branch**
Development installer
Development (73b2163)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by AMZN-stankowi** [comment]
There is no issue with drag and drop here. It's working exactly as it should, it's instantiating the procedural prefab and breaking the connection to the procedural prefab.

The problem is the procedural prefab itself, the name is the full path to the file for some reason:
![image](https://user-images.githubusercontent.com/4838196/198337316-df2039c8-6685-4b83-885e-18d680ccb8c9.png)

**Comment by jackalbe** [comment]
the full name being used for the procedural prefab is certainly an issue (such as buildso3deGemsAtomToolsMaterialEditorAssetsMaterialEditorViewportModelsBeveledCone_fbx) but a current work around is to reprocess the asset again

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed on build Development (ff129ee).
