### ISSUE TITLE
20 - Add navigation buttons in the header of Asset browser ( back and forward )

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#12859]
**Use Story:**

As a user I need the ability to have navigation buttons in the header (previous, forward). Next level down could be added as a bonus feature. See windows explorer for example. This will allow user to focus on content editing instead of memorizing the last folder user viewed. Instead they can focus on the issue in which is the priority for user in the moment.

 **Notes:**

This navigation feature will become very useful when we have two column view. we are ok with having Search and URLs bar being the same input of different  depending on the level of effort of getting up and running. The QT workflow and what comes free should help determine this

**Design Specs:**

![image](https://user-images.githubusercontent.com/58790905/198412011-20c29e40-b7e7-4d15-abca-3de3de76671f.png)

**Comment by rainbj** [comment]
examples - https://www.figma.com/file/TfXXZD1xjlw67MMeRYEbi0/Asset-Browser-Design-Document?node-id=862%3A29972
