### ISSUE TITLE
Asset Browser - List view

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#12864]
As a user, I would like a single column view of my Asset Browser experience - This view is this simplest view of all three of our views. This view would be experienced as an accordion view that almost uses the same look and feel we have today without the side detail panel. This would be a flat, long scrollable list that can be docakable on the left-hand side of the page. On top of the outliner view. However, to make this view helpful we will need to adjust and add a few additional features. They are as followed:
 * We no longer need the detail panel (thumbnail side panel) in this view. The detail panel should now live on its own as an Asset detail panel. Please look for that ticket within the AB project. We want to make sure that this panel exist first before removing thumbnails here.
 * This view has new sections, including collapsible high level folders (favorites and project).
 * This view will include the layout switcher icons in the header. List view (this view), thumbnail view, and table view. When you are in a specific view, the color behind the icons should be blue, represented the selected state.
 * Save fav search icon (in header). This will allow you to make a custom search and save this search to your favorite. Allowing you to return to this search later on.
 * This view will also include a breadcrumb trail. Same as in other views. Indicating which level you are on. Specifically in this view breadcrumbs will be useful as searching through a hierarchy can make users get lost.
 * Horizontal header compression view. Notice that there are two images below. The first image shows a view of the AB on the sidebar and one on the bottom near the console. In the view with it near the outliner, please note that the header bar for AB is broken up over two level instead of all living on one bar. This is because with limited horizontal space. We need a way to account for all of the overflow buttons. The hope is that this can be implemented similar to how CSS does "@media (max-width: 800px) {" I have rearranges a few of the elements when it has broken over two lines that is not consistent when it is all on one line. Grouping most important items together.
 * The menu button inside this view should remain the same as the other views.
 * Thumbnail icons in this view are not needed. So please just use vector svg icons to represent each asset type instead of showing the thumbnail of an asset directly. This should also make this view faster for processing content.

![Image](https://user-images.githubusercontent.com/82551958/202798485-0a67be6d-5ce1-4020-87e4-8561f4846088.png)

![Image](https://user-images.githubusercontent.com/82551958/202798493-211e5c39-bf1e-4fdc-9e3f-161f0bb73b84.png)

**Comment by MiKom** [comment]
hey @lsemp3d 

Is this task really actionable? I have a feeling that almost all the points in the description are covered by other tasks or are already done:

 * moving the detail panel: #12856 
 * favorites: #12867 
 * layout switching: #12860 & #12855 
 * Breadcrumbs: #13236
 * responsive layout: also #13236 
 
The only not covered thing is that icons for assets in the tree view should not be thumbnails but symbolic ones.

Am I correct with my assessment? If yes, I suggest creating a separate, focused task for the icon thumbnails and close this one.

**Comment by rainbj** [comment]
@dtamkin1 - Do you think this feature is done? I think the only specific here is the compressed header bar and the switcher button.

**Comment by dtamkin1** [comment]
@rainbj It looks like we've implemented everything from this view except for favorites, which are currently being worked on.

**Comment by rainbj** [comment]
@dtamkin1 and @sphrose - Sounds like we should close this ticket. Thoughts?

**Comment by sphrose** [comment]
@rainbj Looks like it's all covered to me, closing it is fine.

**Comment by rainbj** [comment]
Hi @sphrose and @MiKom the above list is about supporting those functionalities in this specific view. For example. 

- As a user, I can use favorites (in this specific view)
- As a user, I see responsive table works (in this specific view)
- As a user, clicking on breadcrumbs works (in this specific view)

Previously we had issues that not all functionality was working in each view. I assume this is why I included these items on this particular ticket.
