### ISSUE TITLE
4 - Drag and drop content into and out from of Asset Browser 

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#12866]
**Details**

As a user I need ability to **drag and drop content inside and outside of asset browser** (windows explorer). As an example I have an asset on my desktop and I want to drag this asset to a specific folder inside AB. I should be able to do so. Same with removal of assets from AB. I have an asset I no longer I want to include in my game or simulation

AC:

This ticket is not specific to one file type. Drag and drop should work regardless of file type. If exception comes up we should determine the appropriate outcome for these files.

 

**Additional details from meetings**

 Three different types, between AB files, in O3DE as tool, between two external tools. Talk to Helios about existing functionality we can take from the Asset relocation tool.

 

----
 

**Further investigation details specific to FBX -> Scene, Drag and Drop**
 * Asset Browser has special logic for dragging FBX files out of the asset browser to other parts of the editor's UI, see I:\git\o3de\Code\Editor\AzAssetBrowser\AzAssetBrowserRequestHandler.cpp for details
 * Expected behavior is defined for dragging and dropping scene files from the asset browser, to each drop target.
 * Drag and drop for all scene files matches that behavior.

**Comment by sphrose** [comment]
@rainbj  When dragging an asset from one AssetBrowser window to another, how should it be handled, i.e. should they be moved (which might cause issues if they're in use), copied, or should there be a way to choose which method you want?

**Comment by rainbj** [comment]
So operationally, I would like to keep it feeling as similar to Windows explorer as possible. In Windows explorer, it tells the user that they cannot "move" an asset while in use. Can we do something along these lines?
