### ISSUE TITLE
14 -  Favorite URLs and searches queries inside Asset Browser

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#12867]
**Use Story:**

As a user, I need the ability to have favorite URLs and favorite searches inside AB. This includes a favorites list in your left column ways or removing favorites, as well as renaming their favorites. 

- We should support an accordion section of the main window which list out all the favs.
- you should be able to add fav from any view. This means if the search query area is clear, we base the bookmark of the favorite based on the user breadcrumb/URL.
- If the user has something inside the search bar we save the search results
- If the user is inside the advanced search, we save the results based on what was indicated on that screen. That window also has a star for saving. 
- In the right click dropdown, we might also want to consider adding "update". This would allow you to update your current favorite selection with whatever was in the search bar first and if that is blank, then where ever the user has navigated to via url.

 ![Image](https://user-images.githubusercontent.com/82551958/202594620-07dd2be5-cf62-4a68-b144-539e11e83b1f.png)

**Comment by rainbj** [comment]
Other examples - https://www.figma.com/file/TfXXZD1xjlw67MMeRYEbi0/Asset-Browser-Design-Document?node-id=862%3A30016

**Comment by bhanuja-s** [comment]
I'm adding notes relevant to this ticket from an earlier discussion with @rainbj and @yuyihsu.

We should make the different types of favourite-able items visible.

This should follow Windows Explorer's paradigm, with default (curated) favourite items – including a file, folder, and search query. This would tie in with the toolbox work, as this panel can lead to important pages we want to surface.

**Comment by sphrose** [comment]
@rainbj @bhanuja-s Is there an existing svg for the star used for favorites, if not could I have one please?

**Comment by bhanuja-s** [comment]
Hey @sphrose, I recently designed the following icons for this feature:

[SVGs.zip](https://github.com/o3de/o3de/files/11289190/SVGs.zip)

The folder contains three different ones, 

![image](https://user-images.githubusercontent.com/84036086/233452223-1d9c2c70-bbfc-4f22-8d9e-d68794be3176.png)

1: Favorites
2: Favorited File
3: Favorited Folder
