### ISSUE TITLE
17 - Create Asset Browser inspector panel

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#12872]
**Use Story:**

**Migrate and create an associated asset panel in the asset browser inspector panel**

As a user, I need the ability to see my asset related details in it's own panel that is not integrated tightly into the asset browser. Currently the integrated asset preview and details of that asset in Asset Browser makes the viewing experience extremely hard to see thumbnail and or details because too many things are going on in one small panel. It also make it difficult for user to pick any other different configurations for the AB beside along the bottom row. We would like to move the preview and details to a new panel. This is a current standard among all the other game engines we would like to support. See other examples of this below in the ticket.

**AC**
 * By default, the panel should be docked with entity inspector and is pulled to the front based on when an asset from asset browser is selected.
 * We should also do this in reverse that when any entity / prefab in Outliner or Viewport is selected we should pull the entity inspector to the front.
 * This new panel should have 4 main sections and 3 accordions.
 **** Section 1 - The preview image panel
 **** Section 1 - main property details (name, size, type, dimensions, last modified, date create, status, and repo)
 **** Section 2 -  secondary details - editable  ( these can be configurable based on selected asset type)
 ***** file location
 ***** Source tool it came from
 ***** Comments user would like to include for game team.
 ***** FBX related settings (later)
 ***** PhysX related settings (later)
 **** Section 3 - related assets.  
 **** Section 4 -
 ***** "Tagging" assets for searching. This will allow user to define labels for an asset for easy discovery later. Is this object a [--- blank---] type of asset. Example Vegetation, weapon, particle, animation, etc.

 

![image](https://user-images.githubusercontent.com/58790905/198414375-9a3d3b33-7d50-44b1-a2d7-bbac751c224c.png)

 

![image](https://user-images.githubusercontent.com/58790905/198414382-ea285c18-393a-4f54-b21a-5a960f51aea1.png)

**Comment by MiKom** [comment]
Since in this task we will be changing the detail panel to look differently, I suggest renaming this issue to e.g. "Asset details panel redesign". Otherwise it's a bit confusing with #12856

**Comment by amzn-rhhong** [comment]
Instead of showing the preview of the fbx model in the inspector, what about showing the fbx setting page 
directly at the inspector too?
![Screenshot 2022-11-17 191820](https://user-images.githubusercontent.com/69218254/202609032-aa9e3314-f70f-402b-9a43-82d55a321b4f.png)

**Comment by rainbj** [comment]
@amzn-rhhong thanks for the ideas. Yes, we have considered this and the new inspector panel will incorporate FBX settings (eventually). The hope is that this new inspector panel will inspect any element you select. That could be a prefab, a material, and an FBX. The first layer is to get it working with the asset browser. At this point, we are unsure if we want to include all setting (as is) or only a subset of setting and have the rest come up as a pop-up window. We are prioritizing the information based on user the highest needs. That means the first layer is just information about the FBX (what it looks like, how many vertex does it have. How large is the file, where did the asset come from, etc. In the next layer, we will work with our DT team to prioritize which settings do they need easy access to, while which setting can be more abstracted.
