### ISSUE TITLE
27 - Asset Browser - Context aware inspector (Merge inspectors)

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#12876]
User Story: As a user I would like one inspector instead of managing several inspectors within my workflows. This new inspector experience should be context aware and always show what is in my selection state. This means if I'm clicking on asset in my asset browser it should show asset related details. If I'm clicking on entities or prefabs it should show the current entity inspector. Making the inspector a general inspector instead of separate inspectors for different experiences. Then we would drop all the secondary naming conventions and just call it the "Inspector".

 

I've also hear from other LY team such as animation and large world teams about utilizing a global that can cover more of everyone experience. Example the animation inspector can be use in the main inspector. Or landscape canvas can inspect nodes in the main window.   Simplifying the approach for the user of having to keep track of multiple open panels

 

![image](https://user-images.githubusercontent.com/58790905/198415446-bdee163c-9da6-4d65-9576-2b12a8636177.png)

**Comment by AMZN-stankowi** [comment]
I would personally prefer these as separate inspectors. There are workflows that are nice to have these up side by side, both visible at the same time.
