### ISSUE TITLE
Feature Request: Casting Shadows should be a flag on materials

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#12897]
**Is your feature request related to a problem? Please describe.**
Right now the only way to make an object not cast a shadow is a hack by setting the objects opacity to 0.99, as shadows do not cast from transparent objects.

**Describe the solution you'd like**
Having a flag that could be toggled on or off to allow a material to either cast shadows or not cast shadows is the best approach.

**Describe alternatives you've considered**
The only alternative right now is setting the objects opacity to 0.99 to stop shadows from casting, but this is not a good way to do this.

**Additional context**
The small conversation from the discord server ;
![image](https://user-images.githubusercontent.com/100494538/198902704-d4c68778-cabc-400f-b0d4-14c6e7f28e27.png)
![image](https://user-images.githubusercontent.com/100494538/198902708-a1ab2faf-ed15-4be5-85a9-825421f58801.png)

**Comment by santorac** [comment]
This would be really easy to implement on a per-material basis.
