### ISSUE TITLE
Bundled assets cannot be loaded by the release game launcher due to incorrect file attributes

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#12915]
**Describe the bug**
It is noticed that bundled assets from pak files other than engine.pak cannot be loaded in the release game launcher. 

**Assets required**
Any O3DE project

**Steps to reproduce**
1. Build the game launcher in release and bundle its assets following https://www.o3de.org/docs/user-guide/packaging/asset-bundler/bundle-assets-for-release/. Two asset bundles should be created: game_pc.pak and engine_pc.pak.
2. Package the game and run the launcher in release

**Expected behavior**
The game launcher could run without issue and load the game level from game_pc.pak

**Actual behavior**
The game launcher doesn't seem to load the .pak files other than engine.pak. The call to `AssetCatalogRequestBus::Events::GetRegisteredAssetPaths` returns 0 loaded asset paths and in `FileRecordList::MakeZipCDR`, it set `h.lAttrExternal = 0`. Note that the assets can be loaded successfully after set the 'A' attribute on files.

**Found in Branch**
Development

**Comment by lmbr-pip** [comment]
This has been fixed.
