### ISSUE TITLE
Bug Report - Typing in Tag names in an Entity Component very difficult, 1 letter at a time then need to wait a few moments.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#12924]
**Describe the bug**
Typing in Tag names in an Entity Component very difficult, 1 letter at a time then need to wait a few moments.

![image](https://user-images.githubusercontent.com/87207603/199263437-d02dfbf4-6c80-4cec-9a60-bf5e3bd210a6.png)

**Steps to reproduce**
1. Create an Entity and add a component that needs a tag, like the one shown above.
2. Type in the Tag Field 
5. See error

**Expected behavior**
Typing in Tag field works like any other.

**Actual behavior**
Typing in the Tag field is very slow.

**Found in Branch**
Nightly 10/31/22

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Intel I9-9900k
 - GPU NVidia RTX 2080Ti
 - Memory [e.g. 16GB]

**Additional context**

**Comment by monroegm** [comment]
We should check to see if prefab propagation is happening after each letter is typed
