### ISSUE TITLE
Prebuilt linux binary debian packages from o3de.org fail to install

### ISSUE THREAD

**Issue by xA98Kx** [o3de/o3de#12928]
Installer doesnt work on linux

![image](https://user-images.githubusercontent.com/116504369/199281663-082c7002-e8bc-4b69-814a-959499cc6fcd.png)

**Steps to reproduce**
1. Go to terminal
2. Click on apt install <dir>/<o3de ver>.deb
3. See error

error msg
```
dpkg: error processing package o3de (--configure):
 installed o3de package post-installation script subprocess returned error exit 
status 1
Errors were encountered while processing:
 o3de
N: Download is performed unsandboxed as root as file '/home/a98k/Documents/o3de_2210_0.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
the fix given on the guide doesn't work

**Comment by rgba16f** [comment]
I also see this fail on a new Ubuntu 22.04 setup using the UI to install.

**Comment by xA98Kx** [comment]
> I also see this fail on a new Ubuntu 22.04 setup using the UI to install.

I also faced that when trying to install through software manager

**Comment by BytesOfPiDev** [comment]
I remember seeing this error several times when I try to run the installer on linux. Running `sudo dpkg -i ./o3de_2210_0.deb` allows it to complete.

**Comment by xA98Kx** [comment]
Thanks I'll try @BytesOfPiDev

**Comment by amzn-changml** [comment]
Hi @xA98Kx, can you confirm that this is still an issue for you? This is also called out as a known issue in the setup documentation here: https://www.o3de.org/docs/welcome-guide/setup/installing-linux/

**Comment by xA98Kx** [comment]
> Hi @xA98Kx, can you confirm that this is still an issue for you? This is also called out as a known issue in the setup documentation here: https://www.o3de.org/docs/welcome-guide/setup/installing-linux/

yes it is, i have tried the method in the docs but it seems to fail :(

you can close this if you want, I'll try figuring out somethin on my own :)

**Comment by amzn-changml** [comment]
You can also try moving the `.deb` file to `/tmp`. What might be happening here is that that `_apt` system user may not be able to access your home directory and is getting its permissions denied unpacking the `.deb` package.

**Comment by xA98Kx** [comment]
> You can also try moving the `.deb` file to `/tmp`. What might be happening here is that that `_apt` system user may not be able to access your home directory and is getting its permissions denied unpacking the `.deb` package.

oh it works now thanks! I'm closing this issue, thnx a lot tho
