### ISSUE TITLE
IMGUI Unusable: Mouse Doesn't Work

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#12932]
**Describe the bug**
The mouse cannot select IMGUI menu items

**Steps to reproduce**
1. Open a game or serve launcer
2. Press HOME key to open IMGUI
3. Try to select an IMGUI option

**Expected behavior**
I should be able to open the IMGUI menus and select buttons and such

**Actual behavior**
IMGUI is unusable. The mouse is stuck on the top left of the screen and I cannot select IMGUI menu items

**Screenshots/Video**
**Notice my Windows mouse is moving around, but the app mouse is stuck in upper-left-hand corner**
https://user-images.githubusercontent.com/32776221/199294797-4ec62a89-f702-47a4-b0e8-cd286ef44c62.mp4

**Found in Branch**
Development Friday October 28 2022

**Desktop/Device (please complete the following information):**
Windows

**Comment by AMZN-Gene** [comment]
Setting to critical, not blocker because I think most IMGUI options are possible via cvars?

**Comment by galibzon** [comment]
@santorac Did some work around ImGui mouse a few weeks ago. Will assign to him to see if he can identify an easy fix.

**Comment by AMZN-puvvadar** [comment]
@galibzon Is there any update on this? This renders certain ImGui based tools completely unusable.

**Comment by lmbr-pip** [comment]
Can you use arrow keys + space bar to navigate? Can you change behaviour by toggling input mode? See https://github.com/o3de/o3de.org/pull/2074

**Comment by AMZN-puvvadar** [comment]
> Can you use arrow keys + space bar to navigate? Can you change behaviour by toggling input mode? See [o3de/o3de.org#2074](https://github.com/o3de/o3de.org/pull/2074)

You can use arrows + space to navigate and action some of the menus but many of the windows that are then opened are not operable.

**Comment by santorac** [comment]
I've been doing a "git bisect" to track this down. I have to step away from this for a few days, though. Here's what I have so far:
```
D:\o3de>git bisect log
# bad: [c59c38219a33913b87753f57019009976da85607] Merge pull request #13170 from aws-lumberyard-dev/jckand/AddEntityTestFix
# good: [a7baa576b413e24c6503e2aab45cc89947b7318d] Merge pull request #11124 from aws-lumberyard-dev/Atom/santorac/FixImGuiManagerMouseInput
git bisect start 'development' 'a7baa576b413e24c6503e2aab45cc89947b7318d'
# good: [8f595d4697abdfa83c0b08162141a568d90767d9] init more forgiving to not fail editor bootstrap when no dev settings
git bisect good 8f595d4697abdfa83c0b08162141a568d90767d9
# skip: [77e504be611dfa36014b538a1c88c8e69e9bf1b4] Merge commit '6eb028bf6dcf0e9745103a7eec933199f70547fd' into AssetProcessor_Prototype_SourceAssetReference
git bisect skip 77e504be611dfa36014b538a1c88c8e69e9bf1b4
# bad: [080b1af6b1ef983f754b27313f5edaefe78cb042] Merge pull request #12625 from aws-lumberyard-dev/cherry_pick_python_scripts_fix
git bisect bad 080b1af6b1ef983f754b27313f5edaefe78cb042
# good: [550bd9cd5baa9babdef6ebddaf4384e2c0a719ea] Merge pull request #12228 from aws-lumberyard-dev/amzn-mike_ActorReloadingFix
git bisect good 550bd9cd5baa9babdef6ebddaf4384e2c0a719ea
```

(I'm sorry, I thought I posted this comment a few days ago but I guess I didn't click "Comment" or something went wrong).

**Comment by santorac** [comment]
The issues was introduced by this PR https://github.com/o3de/o3de/pull/12609
