### ISSUE TITLE
Search View: Keyword highlighting

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#12942]
Include a feature like the one that is already implemented in the Entity Outliner in which the matching words between the string filter and each entry will be highlighted.

Please verify that the results are not pulling in items that are not highlighted. Meaning, if it's showing results that are not highlighted we should have a conversation about why this is happening and adjust the UX to fix this issue.

![Image](https://user-images.githubusercontent.com/82551958/202586424-f1359dae-6aac-49d9-942f-561699578415.png)

**Comment by svitlani** [comment]
Depending on complexity we might want to move it to Phase 3

**Comment by lsemp3d** [comment]
@jjjoness will this be covered by your search work?

**Comment by jjjoness** [comment]
@lsemp3d No. Can look at this and the other issues over the next few weeks.
