### ISSUE TITLE
Dafault symbolisim for Procprefab is getting mixed up in the editor

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#12948]
During a review of the FBX's procprefab workflow, an icon confusion problem came up. This symbolism and iconography are being represented differently in a couple places, plus the symbol needs to be defined further.

 

This can be seen in:
 * In the Outliner when we instantiate a procprefab, this asset looks like a prefab but only with a different background color (purple instead of blue). In this case, someone with visual impairment will not be able to see the difference between blue and purple, as they exist on the same side of the color spectrum. It is suggested that the icon itself needs to be updated and be different than the prefab icon. A couple variations have been provided. See prefab design document (template page)
 * 
 * In the Asset Browser, the icon being used for AB does not match the symbol / icon being used in the Outliner. This too creates confusion for users. The icons used for procprefab inside the Outliner should match the Asset Browser. The icon seen below (3d box ) is related to 3d shape and is not the correct icon to use for procprefab.

![image](https://user-images.githubusercontent.com/58790905/199350135-1813c730-2605-4fca-a5ab-37429561cb34.png)

Because this ticket sit between Asset Browser work and Game object team work. 

I have provided two examples. My first example uses a lock to let users know that this is an un-editable file object. I believe there was some initial pushback because this object is more complex than that when overrides come into play. The second example. Is a mono reverse version of a prefab icon, so user can tell a difference at a glance. Either example will work for UX.

 

![image](https://user-images.githubusercontent.com/58790905/199350196-e4462f7d-09c3-4810-b947-fbd0a2bcf093.png)

![image](https://user-images.githubusercontent.com/58790905/199350324-d7ccf054-f4a7-4edc-8839-afd54cfb7e52.png)

AC:

Replace the icons in both Asset Browser and Outliner for Procprefab. Using the same icon in both places. Please select one of the attached examples. I have also provided a symbol for a locked entity if you decided to go that direction.

**Comment by rainbj** [comment]
@lsemp3d I don't think this is an asset browser related tickets. We might want to remove AB project from this task. @monroegm this same ticket was assigned to you Jira (LYN-14952). Let me know if you have any questions. @AMZN-daimini for visibility.

**Comment by lsemp3d** [comment]
This was fixed while updating all icons #15596
