### ISSUE TITLE
Material Canvas nodes have inconsistent letter casing

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#12986]
**Describe the bug**
Nodes in the Material Canvas have inconsistent letter casing. Nodes in the *Math Functions* and *Scene* categories are starting with a lower case letter, while all others are starting with upper case letter.

**Steps to reproduce**
1. Go to Tools > Material Canvas.
2. Expand all of the categories in the Node Palette.

**Expected behavior**
All node names have consistent letter casing.

**Actual behavior**
Node names in different categories have different letter casing.

**Material Canvas Node Palette Screenshots**
![MaterialCanvasNodes0](https://user-images.githubusercontent.com/86952082/199730567-38ddb0b7-c73f-4ace-b77e-567a86d97776.png)
![MaterialCanvasNodes1](https://user-images.githubusercontent.com/86952082/199730575-8b9874df-c3e5-4180-8ad8-bd9565854b77.png)
![MaterialCanvasNodes2](https://user-images.githubusercontent.com/86952082/199730578-dcc56b1c-5f5c-41f9-92af-86db242b12eb.png)

**Found in Branch**
Development (1e41006)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by lsemp3d** [comment]
@gadams3 I recommend using the GraphCanvas Translation system for this, it makes the updating of all these elements data driven, even in gems (for example, if someone were to create a new gem with custom nodes). This way you can take advantage of the `.names` files which allow users to provide names, tooltips, and more, both on the node palette and on the nodes themselves.

**Comment by LB-ArturZieba** [comment]
On the Development (7f642a1) build there is still one node with lower case name - Math Functions > Noise:

![MaterialCanvasLowerCase](https://user-images.githubusercontent.com/86952082/200563820-4f807e1a-0565-47de-8978-259c2d641257.png)

It should be noted that all other letter cases were fixed.
