### ISSUE TITLE
ASV: eyematerialtest.bv.lua automated screenshot compare test fails.

### ISSUE THREAD

**Issue by NeilGitGud** [o3de/o3de#12980]
eyematerialtest.bv.lua automated screenshot compare test fails.

Found in Build:

O3de:
commit dcc57b87f5aff7e89d05c67cdeea33654661074f

ASV:
commit 757dc363a21889a86688f5e99805896f544ac3e4

Reproducibility:
100% DX12 and Vulkan, tested on windows

Prerequisites:
You have built the above commits and processed all assets

Steps to Reproduce:
1. Launch AtomSampleViewerStandalone.exe
2. Go to Automation > Run Script...
3. Run "eyematerialtest.bv.lua"

Expected Result:
All tests pass

Actual Result:
One screenshot compare fails (see attached screenshots)
 
![screenshot_eye](https://user-images.githubusercontent.com/79114701/200661460-e18c29bf-737d-4ffd-ae17-d061adc788e1.png)

**Comment by NeilGitGud** [comment]
@santipaprika I believe this would be your issue based on this Eye Material PR: https://github.com/o3de/o3de/issues/7247

**Comment by santipaprika** [comment]
Hm, probably some recent change broke it. 
Can you attach the screenshots?

**Comment by NeilGitGud** [comment]
ack must have missed that, sorry. Attached now!

**Comment by jiaweig-amzn** [comment]
> Visually, I perceive that the normal map influence is more pronounced now. If the material refactor (#11016) passed the test, the only change affecting the eye shader files after that is #12173 , which modified the TBN computation.
> 
> @jiaweig-amzn I see in your PR that it passed the test initially, but is it possible that the test suite wasn't run after addressing some PR comments? My guess is that some of the code added there could have caused the eye screenshot to fail. If you think the new result from the code you added is more physically-correct, then I would suggest simply updating the reference screenshot.

I took a look into this. And tried to revert my changes on the eye shader. It seems the changes did introduce some extra diff.
The bitangent from the vertex stream is different from the one calculated in the pixel shader (as the new change did).
So I am gonna put the bitangent back in the eye shader to temporary fix the screenshot failure. Meanwhile, I will try to utilize the vertex stream debug shader to see what's actually going on with the bitangent.

![BeforeTBNChange](https://user-images.githubusercontent.com/51759646/201426911-9d7a68c5-18de-47cb-859c-f6118d5752b8.JPG)
![AfterTBNChange](https://user-images.githubusercontent.com/51759646/201426915-63d3a5cf-99d9-4fdf-8e1c-28f7956bb8ad.JPG)

**Comment by jiaweig-amzn** [comment]
Temp fix:
https://github.com/o3de/o3de/pull/13154

**Comment by santipaprika** [comment]
Awesome, thanks! :)
