### ISSUE TITLE
Bug: missing icon for collapse all button in Asset Browser

### ISSUE THREAD

**Issue by MiKom** [o3de/o3de#13005]
There's a "Collapse all" button in the asset browser window but it's currently invisible because the icon isn't properly set:

![Image](https://user-images.githubusercontent.com/104767/199941091-ed5d0253-f156-42a7-ba1e-8df9fd34ac1f.png)

As you can see in `Code\Editor\AzAssetBrowser\AzAssetBrowserWindow.cpp` the icon is created from a path that isn't a qrc resource:

```cpp
namespace AzToolsFramework
{
    namespace AssetBrowser
    {
        static constexpr const char* CollapseAllIcon = "Assets/Editor/Icons/AssetBrowser/Collapse_All.svg";
        static constexpr const char* MenuIcon = ":/Menu/menu.svg";
    } // namespace AssetBrowser
} // namespace AzToolsFramework

/*... SNIP ...*/

m_ui->m_collapseAllButton->setIcon(QIcon(AzAssetBrowser::CollapseAllIcon));
```

We should probably move such resources to qrc-managed place.

**Comment by rainbj** [comment]
@MiKom I think we should move the collapse all function into the dropdown menu. It doesn't use the space effectively in this instance. However this functionality still seems useful, so I don't think we should get rid of it. Good find.

**Comment by MiKom** [comment]
@rainbj PR that moves the functionality to menu is opened
