### ISSUE TITLE
AzNetworking: Add ISerializer Support for AZ::u64 and AZ::s64

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#13019]
**Is your feature request related to a problem? Please describe.**
The AZNetworking ISerializer supports serializing int64_t and uint64_t but not AZ::u64 and AZ::s64 because on some platforms this will be long and on others this will be long long, leading to a compiler error.

**Describe possible solutions you'd like**
There's a few approaches...
1. Stick to AZ types, basically enforce anyone using network serializer to stay in the AZ ecosystem and stick with AZ::u64 and AZ::s64. 

2. Add something to hide the standard int64_t
#define int64_t int64_typeconsistent
#define int64_typeconsistent signed long long
And then just use int64_t (and uint64_t) everywhere in code normally

3. Add a virtual method to ISerializer specifically for AZ::s64 and AZ::u64 #if AZ_TRAIT_COMPILER_INT64_T_IS_LONG

**Comment by lmbr-pip** [comment]
#3 is the preferred option.
