### ISSUE TITLE
macOS: Initial building of Development branch build can fail due to failed ReflectedPropertyEditorStandalone command

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#13010]
**Describe the bug**
Initial attempt at building the Development branch build on macOS machine can fail due to the following error:

```
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution CMake\ PostBuild\ Rules /Users/macpro15/git/o3de/o3deeditor/Code/Framework/AzQtComponents/O3DE.build/profile/ReflectedPropertyEditorStandalone.build/Script-62E69DC8AE4CB926F7FC3690.sh (in target 'ReflectedPropertyEditorStandalone' from project 'O3DE')
(1 failure)
Elapsed time: 1535 s. (time), 0.084047 s. (clock)
macpro15@MacPro15s-MacBook-Air osx_build % 
```

Please note that running the build command again after failing restarts the building process, which will then finish the building process successfully and result in a working build.

The issue was found on MacBook Air 2020 (M1 chipset, Monterey 12.6, XCode 14.0.1) with and without AutomatedTesting selected as a project to build together with the engine.

For further information please refer to the attached building log.

**Steps to reproduce**
1. Obtain the Development branch build via GitHub.
2. Create a new or move your preexisting 3rdParty folder containing CMake into the o3de folder.
3. Obtain python packages with the _get_python.sh_ script located in the _o3de/python_ directory.
4. Create the _osx_build_ folder under the o3de location.
5. Set the following temporary environment variables in the Terminal:
```
export PATH=$PATH:/Users/<home_folder_name>/o3de/3rdParty/CMake/CMake.app/Contents/bin
export LY_3RDPARTY_PATH=/Users/<home_folder_name>/o3de/3rdParty
export LY_PACKAGE_SERVER_URLS=https://d2c171ws20a1rv.cloudfront.net
```
6. Configure and generate the Xcode solution with the following command:
`cmake .. -G "Xcode" -DLY_3RDPARTY_PATH=$LY_3RDPARTY_PATH -DLY_UNITY_BUILD=1 -DCMAKE_OSX_ARCHITECTURES=x86_64`

7. Build Mac binaries with the following command:
`cmake -E time cmake --build . --target ALL_BUILD --config profile`

**Expected behavior**
Building process finishes successfully without errors.

**Actual behavior**
Building fails.

**Found in Branch**
Development (ea9f21c)

**Desktop/Device**
- Device: Mac
- OS: macOS
- Version: Monterey 12.6
- CPU: M1
- GPU: M1
- Memory: 16GB

**Additional context**
[building initial fail with no project selected.txt](https://github.com/o3de/o3de/files/9938943/building.initial.fail.with.no.project.selected.txt)
[building initial fail with AutomatedTesting project selected.txt](https://github.com/o3de/o3de/files/9938945/building.initial.fail.with.AutomatedTesting.project.selected.txt)
[Successful building after initial failure.txt](https://github.com/o3de/o3de/files/9938982/Successful.building.after.initial.failure.txt)

**Comment by byrcolin** [comment]
In the description we note that the hardware is M1 which is ARM, but the build description says -DCMAKE_OSX_ARCHITECTURES=x86_64
Is this a copy/paste error?

**Comment by LB-MateuszSzweda** [comment]
@byrcolin Long ago when M1 was introduced it had problems configuring due to not detecting TARGET correctly.

We were informed that this is due to O3DE not yet build natively for ARM and that _DCMAKE_OSX_ARCHITECTURES=x86_64_ should be used during configuration to workaround that.

Originally I have reproduced the issue with _DCMAKE_OSX_ARCHITECTURES=x86_64_ present in configuration command but I have verified that indeed this argument is no longer needed and configuration step passes without it.

However I was also able to confirm that the above **ReflectedPropertyEditorStandalone** error is present on initial M1 building regardless of using _DCMAKE_OSX_ARCHITECTURES=x86_64_ argument during the configuration step.

**Comment by moraaar** [comment]
From the log attached in the description, this is the error reported:

````
CMake Error at /Users/macpro15/o3de/3rdParty/CMake/CMake.app/Contents/share/cmake-3.24/Modules/BundleUtilities.cmake:997 (message):
  error: fixup_bundle: not a valid bundle
Call Stack (most recent call first):
  /Users/macpro15/o3de/o3de_build/runtime_dependencies/profile/ReflectedPropertyEditorStandalone.cmake:299 (fixup_bundle)
````

Something related with CMake maybe? It'd odd that it only fails the first time, tagging @lumberyard-employee-dm in case he knows what this could be about.
