### ISSUE TITLE
Feature Request: Material Canvas Compiling Visual Feedback

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#13050]
**Is your feature request related to a problem? Please describe.**
When working in the Material Canvas I am always having to wait and check the AP to see if it has finished compiling to know if what I did is working correctly or not.

**Describe the solution you'd like**
Having a visual icon or text would allow people to see that the material is compiling and has compiled once it has finished. This will make it easier to stay in one window and not have to bounce around to make sure things are compiling correctly.

**Describe alternatives you've considered**
I have not had a good alternative yet, if others have one I would love to hear about it.

**Additional context**
If you look at other visual shader editors like Unreal's once you hit the compile button it shows in the viewport that the shaders or compiling, and once they hit 0 your shader is updated. Having this visual feedback lets the developer know how long it should take, once its finished, etc.

**Comment by gadams3** [comment]
Thank you for the feedback. This is on the list. Are you also aware of options in the tools settings menu that enable faster iteration/preview times by disabling shader compilation for inactive platforms? Could you please also provide info on your hardware and how long it takes to see updates with that setting enabled or disabled?

**Comment by ParasiteSt** [comment]
Thanks for the assurance its on the list @gadams3 . I did a few small tests, and compilation times without this feature toggled on is around 12.8 - 13.06 seconds, and with the feature toggled on it is around 4.6 -4.84 seconds.
Without it toggled on ;
![image](https://user-images.githubusercontent.com/100494538/201410458-a6454d4a-8a70-4124-a7b7-00bf62a86c70.png)
With it toggled on ;
![image](https://user-images.githubusercontent.com/100494538/201410673-2f871fea-1684-4bce-8d08-931030b8d4c5.png)


Hardware is Intel i5-8400, 16gb ram, Nvidia GTX 1050 Ti.
