### ISSUE TITLE
Baking image using default file name in the Gradient Baker causes an Asset Processor fail to pop up

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#13064]
**Describe the bug**
If the image baked using the *Gradient Baker* component is saved under its default name (baked_output_gsi.png), an Asset Processor fail will pop up, even though the image saves correctly and when viewed in the Asset Processor it shows no issues.

It should be noted that this does not occur with other names.

**Steps to reproduce**
1. Create an entity and add *Perlin Noise Gradient*, *Gradient Transform Modifier* and *Box Shape* components to it.
2. Create another entity and add *Gradient Baker* component to it.
3. In *Gradient Baker* set the *Gradient Entity Id* and *Input Bounds* to the entity created in step 1.
4. In *Gradient Baker* set the *Output Path* to any path (for example the project's *Assets* folder), do not change the image's name (should be baked_output_gsi.png by default).
5. Click the *Bake image* button on the *Gradient Baker* component.

**Expected behavior**
No fail pops up.

**Actual behavior**
An Asset Processor fail pops up.

**Video and Asset Processor screenshot**

https://user-images.githubusercontent.com/86952082/200578295-d5b71366-b2db-433e-9de4-f360512e29ab.mp4

Images generated on the video in the Asset Processor:
![GradientBakerImagesAssetProcessor](https://user-images.githubusercontent.com/86952082/200578313-6c81debf-19ff-426c-ac38-93aac3d8b0fd.png)

**Found in Branch**
Development (7f642a1)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by AMZN-stankowi** [comment]
This isn't just for this asset type, this occurs with any non-instant write operation to asset files. If you copy a large file, or perform a longer file save operation, the asset processor will start attempting to process the file before the operation finishes, fail, and then need to re-process the asset when the write operation actually finishes.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (ba92844) build.
