### ISSUE TITLE
Action Manager: An Editor crash can occur if levels are changed while the Paint Brush Settings tool is opened

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#13080]
**Describe the bug**
An Editor crash can occur if levels are changed while the Paint Brush Settings tool is opened while the new ActionManager is enabled. Without the ActionManager, the user does not have the option to open a level while in Component Edit mode.

**Prerequisites**
1. Editor is launched with the new ActionManager enabled.

```
Editor.exe --regset=O3DE/ActionManager/EnableNewActionManager=true
```

**Steps to reproduce**
1. Open a new or existing level.
3. Create a new entity with an Image Gradient component and all dependencies.
4. Assign an asset to the Image Gradient component, and click the Edit button on the component card to bring up the Paint Brush Settings tool.
5. Click File > Open level and open any different level without saving any changes.

**Expected behavior**
Paint Brush Settings tool is closed without saving any changes.

**Actual behavior**
Paint Brush Settings tool is closed, however the Viewport remains in Component Edit mode, and the newly opened level cannot be interacted with. After a few seconds, the Editor crashes.

```
Call Stack Trace:
 7) 00007FFD4CFB02E7 (KERNELBASE) : UnhandledExceptionFilter
 6) 00007FFD4F495530 (ntdll) : memset
 5) 00007FFD4F47C876 (ntdll) : _C_specific_handler
 4) 00007FFD4F49241F (ntdll) : _chkstk
 3) 00007FFD4F4414A4 (ntdll) : RtlRaiseException
 2) 00007FFD4F490F4E (ntdll) : KiUserExceptionDispatcher
 1) D:\GitHub\o3de\Gems\GradientSignal\Code\Source\Editor\EditorImageGradientComponentMode.cpp (275) : GradientSignal::PaintBrushUndoBuffer::Changed
```

**Found in Branch**
development@ 1498390c98f7836c343130f7c323192151ce12bb

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by AMZN-daimini** [comment]
@mbalfour-amzn @hultonha Isn't paintbrush mode a Component Mode? If not, should it be?

**Comment by hultonha** [comment]
Didn't @mbalfour-amzn fix something very similar recently? Though this might have just been on shutdown and not when changing level. Do you have this change @jckand-amzn? https://github.com/o3de/o3de/pull/13023

**Comment by mbalfour-amzn** [comment]
I only fixed the Quit flow, not the "Close Level" flow. This will need to get fixed separately. :(

**Comment by mbalfour-amzn** [comment]
@AMZN-daimini Pretty sure the actual bug here is that the Action Manager is _letting_ you select "Open Level" while in Component Mode. With the Action Manager disabled, you can't do that.

**Comment by jckand-amzn** [comment]
Yes, apologies all. I didn't realize I still had the new ActionManager enabled via setreg. Updating the ticket description.

**Comment by jckand-amzn** [comment]
I can still hit this crash without the new ActionManager enabled, but the steps are much more unlikely to be hit inadvertently:

**Steps to reproduce**
1. Open a new or existing level.
3. Create a new entity with an Image Gradient component and all dependencies.
4. Assign an asset to the Image Gradient component, and click the Edit button on the component card to bring up the Paint Brush Settings tool.
5. Run a Python script via the console that opens a different level, e.g.:

```
pyRunFile D:\GitHub\o3de\AutomatedTesting\Gem\PythonTests\editor\EditorScripts\Menus_ViewMenuOptions.py
```

**Comment by AMZN-daimini** [comment]
That makes sense, still working on Component Mode support with the Action Manager. Should be fixed with the new work that will be coming in soon.

**Comment by hultonha** [comment]
Thanks for the update @jckand-amzn and additional info @AMZN-daimini and @mbalfour-amzn 👍

**Comment by AMZN-daimini** [comment]
> I can still hit this crash without the new ActionManager enabled, but the steps are much more unlikely to be hit inadvertently:
> 
> **Steps to reproduce**
> 
> 1. Open a new or existing level.
> 2. Create a new entity with an Image Gradient component and all dependencies.
> 3. Assign an asset to the Image Gradient component, and click the Edit button on the component card to bring up the Paint Brush Settings tool.
> 4. Run a Python script via the console that opens a different level, e.g.:
> 
> ```
> pyRunFile D:\GitHub\o3de\AutomatedTesting\Gem\PythonTests\editor\EditorScripts\Menus_ViewMenuOptions.py
> ```

The PR above will fix the issue by disabling the File menu options to change the level while a Component Mode is active with the new Action Manager.

If we want to fix the issue with the Python script, we may need to add a guard to changing levels while a component mode is enabled. If it seems worth fixing, I'd just move that to a separate Issue.

**Comment by AMZN-daimini** [comment]
PR was merged, so this should have been fixed to the extent discussed (changing levels from the file menu)
