### ISSUE TITLE
Gradient Paint Brush: Allow configuring color of Viewport brush gizmos

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#13089]
**Is your feature request related to a problem? Please describe.**
The Viewport brush gizmo is red by default. When working with terrain that had a red macro material applied, the gizmo was very hard to see. 

**Describe the solution you'd like**
We should allow configuring the color of the gizmo for working with different color terrain. Perhaps just a few different choices to swap between with a CVar.

**Comment by mbalfour-amzn** [comment]
https://github.com/o3de/o3de/pull/13152
