### ISSUE TITLE
Gradient Paint Brush: Entering/Exiting Edit mode on an Image Gradient component throws a warning to the Console

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#13102]
**Describe the bug**
Entering Edit mode on an Image Gradient component throws a warning to the Console.

```
[Warning] ((null)) - Make sure you use aznew, offers better tracking! (EditorBaseComponentMode)
```

**Steps to reproduce**
1. Launch the Editor and open a new or existing level.
2. Create an entity, and add an Image Gradient and all required dependencies.
3. Assign any valid Image Gradient asset to the component.
4. Enter Edit mode on the Image Gradient component and observe the Console.

**Expected behavior**
Paint mode is entered free of warnings/errors.

**Actual behavior**
A warning is thrown to the Console on entering/exiting Edit mode.

**Found in Branch**
development@ 9080579e3e388388913a9f73a140d19442cb10cc

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by mbalfour-amzn** [comment]
This should get rechecked after https://github.com/o3de/o3de/pull/12797 is submitted, since I believe the allocator changes have removed the concept of "aznew".

**Comment by mbalfour-amzn** [comment]
This no longer occurs.
