### ISSUE TITLE
Pip install failed during configure on a newly setup Ubuntu 22.04 LTS machine

### ISSUE THREAD

**Issue by rgba16f** [o3de/o3de#13113]
**Describe the bug**
During configure of AtomSampleViewer pip failed to install the AtomicWrites and PSUtil packages. Pip attempted to fall back to downloading the software and building the packages locally, this also failed as gcc is not installed.

**Assets required**
o3de source & o3de-atom-sampleviewer source

**Steps to reproduce**
1. Set up a new/clean machine with Ubuntu 22.04 LTS
2. Follow the setup steps here - https://www.o3de.org/docs/welcome-guide/requirements/#linux
3. Install the optional Ninja build system
4. Clone https://github.com/o3de/o3de
5. In terminal, cd to o3de source folder, run ./python/get_python.sh
6. In terminal (o3de folder) run ./scripts.o3de.sh register --this-engine
7. Clone https://github.com.o3de/o3de-atom-sampleviewer
8. In terminal attempt to cmake configure the build with cmake -B build -G "Ninja Multi-Config"
9. See error

**Expected behavior**
Build configures correctly

**Actual behavior**
Build fails to configure because python cannot set up the atomicwrites and psutils packages

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu 
 - Version 22.04 LTS
 - CPU Intel Core i7-7820X
 - GPU NVidia GTX 1080
 - Memory [64GB

[Configure_log.txt](https://github.com/o3de/o3de/files/9982928/Configure_log.txt)

**Comment by lawsonamzn** [comment]
this also happens on windows.  
Linux command line (from the command prompt) to easily reproduce:
```
./python/python.sh -m pip uninstall psutil
./python/python.sh -m pip install --only-binary :psutil: -v --require-hashes --no-deps --only-binary :none: --only-binary psutil -r python/requirements.txt
```

Windows repro
```
.\python\python.cmd -m pip uninstall psutil
.\python\python.cmd -m pip install --only-binary :psutil: -v --require-hashes --no-deps --only-binary :none: --only-binary psutil -r python\requirements.txt
```

**Comment by lawsonamzn** [comment]
SO this happens on windows (and probably mac too)

The remedy might just be to upgrade the version of psutil to the latest to satisfy python 3.x

**Comment by hultonha** [comment]
Preemptively adding sig/core and removing needs-sig - please feel free to update if it should go to another sig
