### ISSUE TITLE
Bug Report - Unexpected transform update for container entity in prefab template

### ISSUE THREAD

**Issue by forkercat** [o3de/o3de#13155]
**Describe the bug**

When we add/remove entity or prefab under a focused container entity, there will be an unexpected patch for updating the container entity's transform in the source template. The container entity's transform in source template is supposed to be empty (as it will be replaced by linkDom during template-template propagation).

So, if users continue saving the changes, that update will be saved to disk, then it would likely cause more weird issues in the future.

Note:
1. It is not obvious without looking into the DOM representation. Operations in Editor might work without any noticeable issues.
2. CreatePrefab/Instantiate prefab might also have this issue. Check PrefabUndoHelpers::UpdateEntity.

**Steps to reproduce**
1. Create an empty level
3. Create a prefab with one nested entity
4. Focus on the prefab
5. In source code, adds a breakpoint in PrefabUndoAddEntity.cpp#L63 to observe what are generated in `m_redoPatch`.
6. Add/Delete an entity **under the container entity**

**Actual behavior**

There are 3 patches. One extra patch to update the transform component.

![Create Entity](https://user-images.githubusercontent.com/11157226/201429042-239182c5-e8ca-4547-ae44-660f3bf487e0.png)

![RedoPatch Data](https://user-images.githubusercontent.com/11157226/201429056-d0a854e7-e1d2-49af-bfa7-2b70e351949b.png)

**Expected behavior**

There should only be one patch for adding the entity and one patch to update parent entity's child sort order.

**Found in Branch**

development https://github.com/o3de/o3de/commit/772758ec0e045fb8638c792eac7fb2fe24c3c798

**Desktop/Device (please complete the following information):**

* Device: PC
* OS: Windows 10
* CPU: AMD Ryzen 5950x
* GPU: NVIDIA RTX 3070
* Memory: 64 GB

**Additional Context**

For override editing, this won't be an issue because the parent entity that needs to be updated can't be the focused container entity.

**Comment by forkercat** [comment]
Proposed Fix: Check if the parent is the focused container entity. If it is, we call InstanceDomGenerator's GenerateContainerEntityDomFromRootInstance or GenerateEntityDom to get the DOM; if it is not, it is safe to fetch from focused template.

I noticed this in unit testing. How might we avoid this kind of issues by verifying the patches in unit testing?

**Comment by forkercat** [comment]
This PR resolves the issue for delete-workflow https://github.com/o3de/o3de/pull/13171

**Comment by srikappa-amzn** [comment]
@forkercat , what the remaining steps here? Should this be also fixed for the 'add-entity' case like you mentioned ?

**Comment by forkercat** [comment]
I will create a backlog task to fix 'add-entity' case. Also investigate other operations that depend on PrefabUndoHelpers::UpdateEntity.

**Comment by forkercat** [comment]
Fix is up. I also verified that this is the only remaining place for this issue. UpdateEntity is good.
