### ISSUE TITLE
Bug Report: Any graph editor not working save screenshot on linux

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#13162]
**Describe the bug**
Click screenshot on canvas material or canvas script it doesn't work

![image](https://user-images.githubusercontent.com/17591539/201544570-b93d96ce-adb6-48c9-89d6-6051e847564f.png)

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Open any graph editor 
2. Click full resolution screenshot
3. No screenshot file

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/201544448-ced1956d-e859-4c94-9068-2ea4e399b42a.mp4

**Found in Branch**
development: ff129eef52fbe6933fb29f5c06a6173c5349cf40

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Fedora
 - Version 36

**Comment by Darkinggq** [comment]
but however there is only works for example button full resolution screenshot paste in phoshop/gimp/krita keyboard `Ctrl+V` is that correct? or I'm wrong ?

https://user-images.githubusercontent.com/17591539/201544878-e5882257-ad7b-4b3a-a417-69e1526f6fff.mp4


https://user-images.githubusercontent.com/17591539/201544879-930c9044-0311-4a7d-ad9e-7e14fb415204.mp4

**Comment by lsemp3d** [comment]
This is working as designed, the screenshot option copies the selection into the clipboard, allowing you to paste it into imaging software. This is documented here: https://www.docs.o3de.org/docs/user-guide/scripting/script-canvas/editor-reference/shortcuts/ 



Ctrl+Shift+P | Screenshot | Creates an image of the area around all selected nodes and adds it to the clipboard. If no nodes are selected, an image of the entire active graph is added to the clipboard.
-- | -- | --
