### ISSUE TITLE
Material Instance Editor does not open

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#13165]
**Describe the bug**
Selecting "Open Material Instance Editor..." from the Material component does not open the desired window and nothing is happening.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Create a new level.
2. Select an entity (e.g. Shader Ball).
3. Add Material component to the entity.
4. Assign a material to Default Material or Model Material slot.
5. Click on the preview icon with an arrow next to the assigned material.
6. Select "Open Material Instance Editor...".

**Expected behavior**
Material Instance Editor opens.

**Actual behavior**
Nothing is happening.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/201655224-877b8a6b-8007-495e-a6b9-e791539f6e54.mp4

**Found in Branch**
Development (ff129ee)

**Desktop/Device**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by gadams3** [comment]
Addressed as part of this pull request https://github.com/o3de/o3de/pull/13253

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development (cb09e08) branch.
