### ISSUE TITLE
Asset Browser: Moving an empty folder or moving the last item from a folder results in that folder being deleted

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#13193]
**Describe the bug**
Moving an empty folder in the Asset Browser to a different location results in that folder being deleted. Folder also disappears when the last asset is moved out from that folder to a different location. Please note that the issue does not occur for folders with content inside.

For further information please refer to the attached video.

**Prerequisites**

- O3DE built in Pre-built SDK engine configuration.
- Folder with only 1 asset present in the project directory.

**Steps to reproduce**
1. Open Asset Browser.
2. Create a new folder.
3. RMB on the created folder and select "Move to" to any directory.
4. RMB on the 1 asset present in the folder mentioned in prerequisites and select "Move to" to any directory.

**Expected behavior**
The folder is present in the directory it has been moved to. An empty folder remains when the last asset is moved out of it.

**Actual behavior**
The folders are deleted.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/201929268-e4fe6a27-f598-4a7b-b2d6-69b7f5441264.mp4

**Found in Branch**
Development (ba92844)

**Desktop/Device**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by LB-ArturZieba** [comment]
On the Development (5234076) build I have also found out that renaming an empty folder deletes it. Renaming a folder with any contents does not cause it to be removed. Should this be reported as a separate issue, or the root cause can be considered as the same as this one?

**Comment by LB-BartoszDudzinski** [comment]
Issue verified as Fixed in the latest development branch (4df30e4).
