### ISSUE TITLE
Opening Animation Editor causes a message to be printed to the Console

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#13197]
**Describe the bug**
Opening Animation Editor in any way causes the following message to be printed to the Console:
```
(System) -> r_enablePerMeshShaderOptionFlags: false
```

**Steps to reproduce**
1. Go to Tools > Animation Editor.

**Expected behavior**
Animation Editor opens and no unexpected message is printed to the Console.

**Actual behavior**
Animation Editor opens and an unexpected message is printed to the Console.

**Video**

https://user-images.githubusercontent.com/86952082/201947273-89ec2d84-c755-48bf-afe7-e0c05ae86276.mp4

**Found in Branch**
Development (ba92844)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by moraaar** [comment]
Closing this bug based on the comment above.
