### ISSUE TITLE
Asset Browser: Using "Move to" option on multiple assets at once can lead to Editor freeze

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#13195]
**Describe the bug**
Selecting multiple assets and moving them to another location can lead to the Editor freeze requiring its restart. Please note that the issue occurs with 2/3 repro rate. The assets are moved to the expected location.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Open Asset Browser.
2. Select at least 2 assets (Ctrl + LMB).
3. Press RMB and select "Move to" choosing another location.

**Expected behavior**
Assets are moved without issues.

**Actual behavior**
Assets are moved and the Editor freezes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/201934816-4cd8d3cd-0912-4ddc-852f-19ecd3e91683.mp4

**Found in Branch**
Development (ba92844)

**Desktop/Device**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by jjjoness** [comment]
@LB-KacperKapusta Could you try this again, please? I believe code recently added to development may have fixed this.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (7cb2c3f) build. Closing the issue.
