### ISSUE TITLE
Asset Browser View can be only changed if there is text entered in the search bar

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#13194]
**Describe the bug**
Asset Browser Views (List View or Tree View) can be only changed while there is any text in the Asset Browser's search bar, otherwise the dropdown button with their selection is grayed out.

**Steps to reproduce**
1. Make sure that there is no text entered in the Asset Browser's search bar.
2. Attempt to open the View selection dropdown (hamburger button in the top right corner).

**Expected behavior**
Dropdown opens.

**Actual behavior**
Hamburger button is grayed out and cannot be clicked.

**Video**

https://user-images.githubusercontent.com/86952082/201935303-6a7d24cf-ee8f-453b-a7da-2bb7d216cc36.mp4

**Found in Branch**
Development (ba92844)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by rainbj** [comment]
These dropdown options should go away in the dropdown menu. We want to make sure the searches work on the specific layout of your choosing and not create a special layout just for the search.

**Comment by dtamkin1** [comment]
Resolved by #13237. After discussion with @rainbj, these dropdown options will be removed in a new task.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (92af95a) build. View switch functions as described in https://github.com/o3de/o3de/pull/13237. Views can be changed, however by default everything is in Tree View, unless a List View is active and an asset is selected.
