### ISSUE TITLE
Incorrect rendering of search highlight in anim graph node palette window

### ISSUE THREAD

**Issue by MiKom** [o3de/o3de#13235]
## Steps to reproduce
1. Open animation editor
2. Open some anim graph asset (e.g. AutomatedTesting\Animations\AnimationEditorFiles\sample0.animgraph)
3. Open the node palette window (View → Palette window)
4. Enter some search term (e.g. `ect`)

## Expected result
Highlights of the text match in the tree are semi-transparent

## Actual result
Highlights of the text matches are opaque:

![Image](https://user-images.githubusercontent.com/104767/202231579-7ff93fe9-8cf0-48e6-a65e-79b1f04e3456.png)

**Comment by FuzzyCarterAWS** [comment]
Verified that this is an issue for me too. This wasn't present before the widget was converted.

**Comment by MiKom** [comment]
Yup. I finally found the root cause today. I'll work on a solution tomorrow.
