### ISSUE TITLE
Anim graph node group window can be opened

### ISSUE THREAD

**Issue by MiKom** [o3de/o3de#13233]
## Steps to reproduce
1. Open Animation Editor
2. Click View → Node groups

## Expected result
It's not possible to open the node groups menu. It should be gone

## Actual result
The menu is still there, and shows nothing.

![image](https://user-images.githubusercontent.com/82228511/203589950-4bf5c969-dfec-4d2a-9ecf-1d36717bc7e6.png)

**Comment by hultonha** [comment]
Tagging @amzn-rhhong for confirmation on this. Thanks!

**Comment by hultonha** [comment]
> @hultonha To clarify, the whole NodeGroupsPlugin class should be removed, right?

I believe so, but would be good to get confirmation from @amzn-rhhong before doing so. Thanks!

**Comment by amzn-rhhong** [comment]
![image](https://user-images.githubusercontent.com/69218254/203612168-0982d985-69cb-4687-a4dd-eb1dea37593b.png)
I'm not super familiar with the node groups plugin, but it looks like it's a grouping mechanic for joints. I don't think that has been used in years thus can be removed.
Be careful not remove the functionality to create a NodeGroup for anim graph tho. Those two different feature share the same name for some reason. If you removing the code by name, just be careful.

**Comment by hultonha** [comment]
Thanks for confirming @amzn-rhhong

**Comment by FuzzyCarterAWS** [comment]
Verified node group cannot be opened.

No references to node group widget made in workflow docs.

Updated the workflow docs in o3de/sig-simulation#22
