### ISSUE TITLE
Anim graph node group can be re-used in different graph levels. Crashes when moved

### ISSUE THREAD

**Issue by MiKom** [o3de/o3de#13232]
## Steps to reproduce

1. Open some anim graph (e.g. AutomatedTesting\Animations\AnimationEditorFiles\sample0.animgraph)
2. Add a node group in the root graph by selecting both nodes and choosing "Create Node Group"
3. Double click on a RinAnims node to enter sub-graph
4. Select some nodes, right click and choose "Assign To Node Group → NodeGroup0
5. Try moving the node group

## Expected result
* It shouldn't be possible to add nodes to a node group created on a different level of a graph
* Application shouldn't crash

## Actual result
* It's possible to add nodes to the same node group across anim graph level (check if it indeed worked like that in the past)
* Application crashes when such node group is moved

**Comment by FuzzyCarterAWS** [comment]
This is a 100% repro when attempting to move the node group while in a different level.

It's also possible to periodically encounter a crash when deleting the node group & nodes from a different level than originally creating it.

Guarding node groups by graph level/depth will likely prevent this issue from rearing its head.

**Comment by FuzzyCarterAWS** [comment]
@aambrosano @hultonha 

This looks great.

Updated the workflow docs in o3de/sig-simulation#22
