### ISSUE TITLE
Click to rename not working consistently for AnimGraph groups

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#13279]
The click to rename for groups in Anim Graph will break after multiple selections are made and the name can no longer be changed

![Image](https://user-images.githubusercontent.com/82228511/202690950-9064f1b2-0449-414a-b76c-0eccf307fa8d.png)

**Comment by FuzzyCarterAWS** [comment]
@Be-ing  @hultonha 

This looks great.

Updated the workflow docs in o3de/sig-simulation#22
