### ISSUE TITLE
Update Motion Sets section to say 'Motions' instead of 'Selected Motion Set'

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#13272]
The Motion Sets tab in the EMFX Editor needs to be updated to have 'Selected Motion Set' heading to say 'Motions'

![Image](https://user-images.githubusercontent.com/82228511/202679284-2fe8079e-562f-42fb-a750-fca0bb5f3355.png)

**Comment by FuzzyCarterAWS** [comment]
@hultonha there's a request for similar, yet conflicting, instructions in #10960 on comment https://github.com/o3de/o3de/issues/10960#issuecomment-1310179195

**Comment by hultonha** [comment]
> @hultonha there's a request for similar, yet conflicting, instructions in #10960 on comment [#10960 (comment)](https://github.com/o3de/o3de/issues/10960#issuecomment-1310179195). I've left a comment pointing towards this issue for updated names.

This is the newer ticket, there was already a name change, this is the second one and is correct after the UX review we had. It should now say -> 'Motions'

**Comment by FuzzyCarterAWS** [comment]
@hultonha @MiKom 

Verified.

Updated the workflow docs in o3de/sig-simulation#22
