### ISSUE TITLE
Material Editor Crash On Shutdown In ThumbnailerComponent

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#13311]
**Describe the bug**
If you close Material Editor while it is rendering thumbnails, it might crash.

**Steps to reproduce**
1. Run Material Editor from Visual Studio with a debugger attached.
2. Scroll the asset browser window so that material thumbnails start rendering.
3. Close Material Editor while thumbnails are still rendering (some icons are blue spinning circle)

**Expected behavior**
Clean shutdown

**Actual behavior**
Exception thrown at 0x00007FFE6AF91B58 (Qt5Core.dll) in MaterialEditor.exe: 0xC0000005: Access violation reading location 0x00007FFE5B2E7208.
```
 	Qt5Core.dll!00007ffe6af91b58()	Unknown
>	MaterialEditor.exe!AzToolsFramework::Thumbnailer::ThumbnailerComponent::~ThumbnailerComponent() Line 43	C++
 	[External Code]	
 	MaterialEditor.exe!AZ::Entity::Reset() Line 121	C++
 	MaterialEditor.exe!AZ::Entity::~Entity() Line 99	C++
 	[External Code]	
 	[Inline Frame] MaterialEditor.exe!std::default_delete<AZ::Entity>::operator()(AZ::Entity *) Line 3090	C++
 	[Inline Frame] MaterialEditor.exe!std::unique_ptr<AZ::Entity,std::default_delete<AZ::Entity>>::reset(AZ::Entity *) Line 3233	C++
 	MaterialEditor.exe!AZ::ComponentApplication::Destroy() Line 892	C++
 	MaterialEditor.exe!AtomToolsFramework::AtomToolsApplication::Destroy() Line 270	C++
 	MaterialEditor.exe!AzFramework::Application::Stop() Line 272	C++
 	[External Code]	
 	MaterialEditor.exe!main(int argc, char * * argv) Line 21	C++
 	[External Code]	
```

**Found in Branch**
development b14f7a80ca3caf01e5c85cb5a685542693b8d522

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen Threadripper 3970X 32-Core Processor    3.69 GHz
 - GPU: NVIDIA RTX 3070 Ti
 - Memory: 64 GB

**Comment by gadams3** [comment]
Fixed by  https://github.com/o3de/o3de/pull/17154
