### ISSUE TITLE
Material Editor Preview Is All Black At First

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#13312]
**Describe the bug**
Sometimes when starting Material Editor, the preview window is all black. If you change the lighting preset then it will be fine. It only seems to happen with the "Goegap" preset.

**Steps to reproduce**
1. Run Material Editor.
2. Change the lighting preset to "Goegap"
3. Close Material Editor
4. Run Material Editor again.
5. Notice the entire preview is black.
6. Change the lighting preset to something else.
7. Notice the viewport is as-expected.
8. Change the lighting preset back to "Goegap".
9. This time the viewport is as-expected.

**Expected behavior**
The preview should be valid at startup for any and all lighting presets.

**Actual behavior**
If the initial lighting preset is "Goegap", the preview will initially be all black.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/55155825/203138242-e5ae8010-6888-4ad7-8e9f-77b03d3db044.png)

**Found in Branch**
development b14f7a80ca3caf01e5c85cb5a685542693b8d522

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen Threadripper 3970X 32-Core Processor    3.69 GHz
 - GPU: NVIDIA RTX 3070 Ti
 - Memory: 64 GB

**Comment by gadams3** [comment]
Most likely fixed with changes from this PR https://github.com/o3de/o3de/pull/13300
