### ISSUE TITLE
Action Manager: TEST_SUITE_main crashes in PythonBindingsExample.Tests with the new Action Manager enabled

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#13369]
**Describe the bug**
TEST_SUITE_main crashes in PythonBindingsExample.Tests with the new Action Manager enabled.

```
 	Qt5Core.dll!00007fffea9104d8()	Unknown
 	Qt5Core.dll!00007fffea90e74d()	Unknown
 	Qt5Widgets.dll!00007fffea3d16f8()	Unknown
 	Qt5Widgets.dll!00007fffea3d14e5()	Unknown
>	PythonBindingsExample.Tests.exe!AzToolsFramework::ActionManagerSystemComponent::Init() Line 31	C++
 	PythonBindingsExample.Tests.exe!AZ::Entity::Init() Line 177	C++
 	PythonBindingsExample.Tests.exe!AzFramework::Application::StartCommon(AZ::Entity * systemEntity) Line 217	C++
 	PythonBindingsExample.Tests.exe!AzToolsFramework::ToolsApplication::StartCommon(AZ::Entity * systemEntity) Line 327	C++
 	PythonBindingsExample.Tests.exe!AzFramework::Application::Start(const AZ::ComponentApplication::Descriptor & descriptor, const AZ::ComponentApplication::StartupParameters & startupParameters) Line 210	C++
 	PythonBindingsExample.Tests.exe!AzToolsFramework::ToolsApplication::Start(const AZ::ComponentApplication::Descriptor & descriptor, const AZ::ComponentApplication::StartupParameters & startupParameters) Line 312	C++
 	PythonBindingsExample.Tests.exe!PythonBindingsExample::Application::SetUp() Line 42	C++
 	[External Code]	
 	[Inline Frame] PythonBindingsExample.Tests.exe!RUN_ALL_TESTS() Line 2341	C++
 	PythonBindingsExample.Tests.exe!AZ::Test::AzUnitTestMain::Run(int argc, char * * argv) Line 163	C++
 	PythonBindingsExample.Tests.exe!main(int argc, char * * argv) Line 42	C++
 	[External Code]	

```

**Steps to reproduce**
1. Update your AutomatedTesting\Registry\editorpreferences.setreg file to include the following under O3DE:
```
		"ActionManager": {
			"EnableNewActionManager": true
		}
```
2. In Visual Studio, set TEST_SUITE_main as the startup program, and run.

**Expected behavior**
Tests complete successfully.

**Actual behavior**
A crash occurs in PythonBindingsExample.Tests.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82226555/203610561-3010847f-38af-4b15-9ce7-6d9d8e65d68e.png)

**Found in Branch**
development@ 6504b003e050a0b006b04a21e48974aeae0de4d2

**Comment by Kadino** [comment]
Adding @o3de/sig-content for ownership of PythonBindings

**Comment by AMZN-daimini** [comment]
@jckand-amzn I have tried to repro this but was unable to, do you know if it's still active?
Right now I do get an error message stating that a QWidget cannot be created without a QApplication, but no crash. Trying to build in profile since my build was debug to see if it makes any difference.

**Comment by jckand-amzn** [comment]
@AMZN-daimini I'm no longer seeing this when running locally. The PythonBindings tests passed without issue both with, and without the new action manager enabled. There are a lot of other failures I'm seeing when running locally, however they don't seem to be due to the action manager. I think we can close this out and potentially open up a new ticket to address any failures that are encountered in AR when the flag is flipped.

**Comment by AMZN-daimini** [comment]
Thank you for verifying this. Closing for the Action Manager project, but will keep an eye on updates if something new comes up.
