### ISSUE TITLE
AnimGraph nodes cannot be directly moved to another node group when already in a node group.

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#13373]
**Describe the bug**
When multiple node groups are present, right-clicking on a node in an existing node group should give an option to move the node to another node group.

This behavior was requested in #10961 

**Steps to reproduce**
1. Open the Animation Editor
2. Set Animation Editor to **AnimGraph** mode 
3. Select the AnimGraph panel
4. Add a few nodes
5. Create multiple node groups
6. Right-click a node in an existing node group and attempt to move it to another node group.

**Expected behavior**
Right-click context menu provides an option to move the node to another existing node group.

**Actual behavior**
Right-click context menu does not provide the option to move the node to another existing node group.

**Screenshots/Video**
![3AE84629-E842-441E-B487-49B278C10867](https://user-images.githubusercontent.com/29718640/203632368-cde5bcef-877e-4411-84e9-d62dcc989996.GIF)

**Found in Branch**
Development

**Workaround**
You can relocate a node to another node group by removing it from its current node group before assigning it to another node group.

**Comment by Be-ing** [comment]
This was implemented originally by @aambrosano but the way it worked was by assigning the node to multiple groups, so I removed that. I suppose it would make sense to reuse that menu to *move* the node to another group instead of *add* it to another group.

**Comment by hultonha** [comment]
@Be-ing Just wanted to check-in if this is something you're looking at doing. If it's a  larger change or is difficult to do I think we can close this issue as it's not really a bug and more of a feature request anyway. Thanks!

**Comment by hultonha** [comment]
@Be-ing We discussed this in our planning session and would like the behavior where a node is immediately removed and added to a different group (rather than it being added to both groups or having to first remove it).

Tagging @aambrosano as well to see if it's something they could pick-up and complete having worked on this originally and having made some changes to Anim Graph code recently.

**Comment by Be-ing** [comment]
Implemented in https://github.com/o3de/o3de/pull/13416

**Comment by hultonha** [comment]
That's great to hear @Be-ing, thanks for confirming. I'll add this issue will be fixed by that PR. Cheers!

**Comment by FuzzyCarterAWS** [comment]
@hultonha @aambrosano 

Updated the workflow docs in o3de/sig-simulation#22

**Comment by FuzzyCarterAWS** [comment]
@hultonha @aambrosano 

verified fixed.
