### ISSUE TITLE
Animation Editor's Node Palette view widget cannot be opened.

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#13375]
**Describe the bug**
After porting of the Animation Editor's Node Palette widget #11691, the Node Pallet view is not available to be opened via the editor's view menu.

**Steps to reproduce**
1. Open the Animation Editor
2. Set Animation Editor to **AnimGraph** mode 
3. Attempt to open the Node Group widget panel
   * View → Node Palette

**Expected behavior**
Node Palette can be opened/closed via the view menu

**Actual behavior**
Node Palette cannot be opened/closed via the view menu and is not available by default when the Animation Editor is set to AnimGraph mode.

**Screenshots/Video**
![C0F2A3F2-4171-4AA5-BAE6-257115E4571B](https://user-images.githubusercontent.com/29718640/203637161-4cf736a9-8596-4431-a1db-21db4ff1bb00.GIF)

**Found in Branch**
Development

**Work around**
A node palette can still be accessed by right clicking the Anim Graph canvas.

**Comment by MiKom** [comment]
@FuzzyCarterAWS Across other node-based tools (landscapecanvas, scriptcanvas, materialcanvas) this windows is always called just "Node Palette". For consistency, I'd call it like that here as well.

**Comment by FuzzyCarterAWS** [comment]
@hultonha @MiKom 

This looks great.

Updated the workflow docs in o3de/sig-simulation#22

**Comment by hultonha** [comment]
Great to hear, thanks for the update @FuzzyCarterAWS
