### ISSUE TITLE
Bug Report: [Animation] Modification of FBX in animation editor makes actor keep bind pose in Editor

### ISSUE THREAD

**Issue by MoMoPF** [o3de/o3de#13393]
**Describe the bug**
When I set the extracted node of an actor in animation editor and then save the fbx, the actor in Editor(not animation editor) will always keep bind pose even though motion is working. However, if I draw skeleton at the same time, skeleton moves correctly.

**Assets required**
The asset size is over 25MB. Maybe I could send asset by email.

**Steps to reproduce**
1. Create Actor component and set an asset.
2. Add Simple Motion component and set a motion.
3. The motion works well in the Editor.
4. Then open animation editor and select a joint for motion extraction.
![image](https://user-images.githubusercontent.com/49116245/203940871-cc243eae-e3cb-4095-9827-4f3a74881648.png)
5. Ctrl + S save the fbx.
![image](https://user-images.githubusercontent.com/49116245/203941048-ba607495-990d-469a-ab3f-e8be1aec3370.png)
6. Wait AP until asset processing finished
7. See Error that the motion doesn't work for skinned mesh (always bind pose) but works well for skeleton(If you turn on drawing skeleton in actor component).

**Expected behavior**
Animation is played well.

**Actual behavior**
The motion doesn't work for skinned mesh (always bind pose) but works well for skeleton(If you turn on drawing skeleton in actor component).

**Found in Branch**
2205.

**Desktop/Device (please complete the following information):**
Device: [PC]
OS: [Windows]
Version [10]
CPU [Intel Xeon Gold 6234]
GPU [NVidia RTX 5000]
Memory [32GB]

**Comment by MoMoPF** [comment]
![image](https://user-images.githubusercontent.com/49116245/203947172-eabc1d98-baa9-4104-94d4-c536ef072981.png)

**Comment by amzn-rhhong** [comment]
@amzn-tommy perhaps the hot-reload broken again?

**Comment by MoMoPF** [comment]
When I debug in the case:
1. Skeleton plays correctly, which means skinning matrix is updated normally. (I check skinning matrix in cpu and it changes every frame, so debug draw could draw skeleton correctly from it and the problem may be caused by gpu resource). 
2. Buffers and buffer views seem to be re-created correctly in SkinnedMeshInputBuffers after reloading the fbx, which means the input resources are created correctly  for skinning pass.
3. m_boneTransforms is same as  2nd point, which determines the transform to source position.
4. Output stream asset is also created and the target offsets are calculated, which means  at least the source position should be copied to the out put stream buffer in LinearSkinningCS.azsl
It seems that every source works well ! But absolutely some buffer is not processed probably by GPU. I think point 2 may be the most likely suspect.

**Comment by hultonha** [comment]
@MoMoPF We see this issue was reported in 2205, have you been able to test this on the latest development branch as quite a few fixes went in for the 2210 release (and potentially later) to resolve these hot-reload issues @amzn-rhhong mentioned. Thanks!

**Comment by hultonha** [comment]
@LB-RobertBaczkowski - is this something one of the LB- team could try to reproduce on the latest development branch to see if it's still occurring please? A lot of work did go into hot-reloading and we think it may be possible this is fixed now (just not in the 2205 build). Thanks!

**Comment by LB-ArturZieba** [comment]
This issue does not occur on Development (3f384ad), however the setup I tested this on is slightly different than the one described. I used the Rin.fbx and jog1 motion available in the Motion Matching Gem. The Rin.fbx has a Motion extraction joint set to *root* by default, so to get a similar effect of assigning it, I simply unassigned it > saved the change > assigned the *root* again > saved the change again. Skeleton and the actor itself were both animated properly before and after the Animation Editor changes.

**Comment by LB-MateuszSzweda** [comment]
I've also not been able to reproduce the issue on Development (3f384ad) using the Jack.fbx. 
No Asset Processor error was observed when new motion extraction joint was selected and the fbx was saved. The actor with skinned mesh played all assigned motions correctly.

**Comment by MoMoPF** [comment]
> @amzn-tommy perhaps the hot-reload broken again?

Hi! @amzn-rhhong  I have an extra question about the SkinnedMeshInputBuffers and hope you could give some suggestions. In the condition that multi Actor Components use the same .fbx model, should these actors share the same SkinnedMeshInputBuffers ? 
I think this may make sense because input data may not change during rendering, instead data changes in output buffer. However, I find when we create an Actor Component with same .fbx model for another entity,  the actor asset will initialize m_renderActor which contains SkinnedMeshInputBuffers again and create a new SkinnedMeshInputBuffers (because m_renderActor is reset to a new render actor), which means two different entity using same actor asset won't share the SkinnedMeshInputBuffers.
![image](https://user-images.githubusercontent.com/49116245/205535518-7f5cbc74-fc50-42ea-9802-71b2e9455a1d.png)
![image](https://user-images.githubusercontent.com/49116245/205535466-fc37a7cd-6858-4e1d-b9c3-d3de1bf7401a.png)

**Comment by MoMoPF** [comment]
Maybe I get the reason --
In my error case, **SkinMetaAsset is not ready** when ConstructMeshes() in actor's Finalize() so that there is no map from vertex to joint, which makes some error in later long long process to build **SkinnedMeshInputBuffers**. However, SkinMetaAsset not ready is a probabilistic event. In case that  SkinMetaAsset is ready, this problem goes away.
![image](https://user-images.githubusercontent.com/49116245/205637160-9b518bf0-b764-44a5-ad5f-d653bd0406ed.png)
code in 2205

I notice that newest code add some warnings when SkinMetaAsset is not ready. Then my question comes to what the expected behavior is when SkinMetaAsset is not ready in dev branch.
1. When SkinMetaAsset is ready again, there is some callback for actor and the actor will re-construct render actor automaticly.
2. As current codes, show some errors to remind the actor asset is not prepared completely and users should re-select the actor asset to actor component after a while.
3. Try to control the parameter **loadReq** of Actor::Finalize(**loadReq**) to be **RequireBlockingLoad**.
![image](https://user-images.githubusercontent.com/49116245/205638350-0927d72f-5cc5-4bd0-b81c-077f765f73d7.png)
Hope to get some guidance! Thanks! @amzn-rhhong @hultonha @LB-ArturZieba @LB-MateuszSzweda  @AMZN-stankowi @amzn-mike

**Comment by amzn-mike** [comment]
Hi @MoMoPF
This is the fix that was added to address this issue: https://github.com/o3de/o3de/pull/12228
It basically does what you described in 1 - when the actor is reloaded, it unloads and reloads the Model, which then triggers a reload of the actor when the model has finished reloading.

**Comment by hultonha** [comment]
Awesome thanks for responding @amzn-mike, I hope that answers your question @MoMoPF 👍

**Comment by MoMoPF** [comment]
@amzn-mike @hultonha Thanks for keeping tracking this issue! For some network reasons recently, I have tried many times and still can't download the dependencies for building the DEV branch codes. And for the same reason, I can't upload the asset regardless via github or discord. But I can provide the asset download url.
Actor: https://www.mixamo.com/#/?page=1&query=jakie&type=Character
Motion: [motion.zip](https://github.com/o3de/o3de/files/10166505/motion.zip)

If you could help try above assets, that will really help. 
![image](https://user-images.githubusercontent.com/49116245/205915186-2af206b9-9d9e-4403-a5be-4d6505fd9ea8.png)


If you want to test the assets, you just need few steps:
1. Create an entity, add an actor component with downloaded Actor Jakie above and add a simple motion component with Walking_no_disp.fbx. 
2. Then change motion extraction joint and CTRL+S to save fbx in animation editor. 
3. Try 2 or 3 times **step2**. Every time you need to wait for AP to finish processing the fbx.

In addition, I do what I can do in my current codes. I pick up the commit in the issue [#12228](https://github.com/o3de/o3de/pull/12228) @amzn-mike provides. When the problem occurs (means SkinMetaAsset is not ready), behavior changes to that the actor disappears and won't reload back to the scene unless I re-pick the asset in Actor Component. This may be reasonable for current tips. So maybe a warning or an error tip (like current code in DEV) to users is a better way to mark the problem ?
![image](https://user-images.githubusercontent.com/49116245/205869842-94e69ef3-a19d-41cd-97a4-fe1822397eef.png)
