### ISSUE TITLE
Box Component Mode dots do not follow along Translation Offset

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#13392]
**Describe the bug**
The Box Component Mode dots always remain in the entity center. This becomes an issue when the Translation Offset is changed. For high values for Translation Offset, the User may not see the dots and the modified shape.

**Prerequisites**
Translation Offset mode enabled - Add "EnableShapeComponentTranslationOffset": true under "Amazon" -> "Preferences" in editorpreferences.setreg.

**Steps to reproduce:**
1. Create an Entity with Box shape (any shape with Edit mode will do).
2. Set "X" value to 10 for Translation Offset.
3. Press the "Edit" button to enter the Box Component Mode.

**Expected behavior**
Box Component Mode dots follow the modified shape.

**Actual behavior**
The dots remain around entity's center.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/203942915-131cc1cc-a02d-4cee-ab19-4fda23dea8a8.mp4

**Found in Branch**
Development (f4bda1f)

**Desktop/Device:**
Device: PC
OS: Linux
Version Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU Nvidia Geforce RTX 2060 SUPER
Memory 16GB

**Comment by greerdv** [comment]
Sorry, I should have mentioned that there is a separate epic to update all the manipulators once the underlying shape offset behaviour is working everywhere, so this is not expected to work yet. Thanks for finding this though.

**Comment by hultonha** [comment]
@LB-JakubSkoczylas I believe this issue should now be fixed. Could you please verify again and close if it's confirmed to be working. Thank you!
