### ISSUE TITLE
Scaling entities with Shape components with modified Translation Offsets moves the Shape center

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#13397]
**Describe the bug**
If a Shape component has its Translation Offset modified, scaling that entity uniformly (or non-uniformly along changed Translation Offset axes in the case of Box Shape) will move its center.

**Prerequisites**
Translation Offset mode enabled - Add "EnableShapeComponentTranslationOffset": true under "Amazon" -> "Preferences" in editorpreferences.setreg.

**Steps to reproduce**
1. Create an entity and add a Shape component to it that has the Translation Offset property (for example Box Shape).
2. Change the Translation Offset property on the Shape component (for example to [0, 1, 0]).
3. Change the entity's Uniform Scale.
4. (If the Shape component accepts the Non-uniform Scale component) Change the Non-uniform Scale property along the changed axis/axes (for example Y for the [0, 1, 0] offset).

**Expected behavior**
Shape component scales in place.

**Actual behavior**
Shape component moves along changed Translation Offset axes while scaling.

**Video**

https://user-images.githubusercontent.com/86952082/203994317-df3ed415-bd0f-4bc6-9ba4-b6c8b87321c7.mp4

**Found in Branch**
Development (da550ef)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by greerdv** [comment]
That is the intended behaviour - the translation offset is also affected by both the entity scale and the non-uniform scale. If that were not the case, the shape of the entity as a whole would change as it was scaled.

**Comment by LB-ArturZieba** [comment]
Closing the issue based on the above comment.
