### ISSUE TITLE
EMotionFX: Saving AnimGraph with group and reopening Animation Editor may cause issue where it is not possible to add other nodes to that group

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#13426]
**Describe the bug**
Creating the AnimGraph with a group, saving, and then reopening it in Animation Editor with that AnimGraph may result in an issue where it is not possible to assign other nodes to previously created group.

Note that this issue is inconsistent - the issue was reproduced on 2 out of 4 machines.

**Steps to reproduce**
1. Open the Animation Editor.
2. Create a new AnimGraph.
3. Add Motion and Blend Tree nodes to the graph.
4. Click RMB on the Motion node and choose "Create Node Group" from context menu.
5. Click RMB on the Blend Tree node and verify (do not click) that "Assign To Node Group" option appears in context menu.
6. Save the created AnimGraph on the disk.
7. Reopen the Animaton Editor with previously created AnimGraph.
8. Click RMB on Blend Tree node and notice that "Assign To Node Group" option is missing.

**Expected behavior**
All nodes can be added to the group that was created in previous session.

**Actual behavior**
It is not possible to add nodes to the group if that group was created in a previous session.

**Video**

https://user-images.githubusercontent.com/86951967/204518850-2dac6de9-b237-48a2-83f9-676ece8cfad3.mp4

**Found in Branch**
Development (a881574)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by hultonha** [comment]
Discussed in sig-simulation triage

Tagging @Be-ing, @ablepharus and @aambrosano for visibility in case this could be related to recent changes to the animation editor.

**Comment by hultonha** [comment]
Tagging @FuzzyCarterAWS as well for visibility who's been looking into changes in the animation editor recently

**Comment by Be-ing** [comment]
I can reproduce this.

**Comment by Be-ing** [comment]
This is a regression from #13395. Commenting out the checks introduced in that PR shows the groups reloaded from the file in the right click menu to assign nodes to a group.

**Comment by FuzzyCarterAWS** [comment]
@hultonha 

Updated the workflow docs in o3de/sig-simulation#22 to reflect this bug.

**Comment by aambrosano** [comment]
#13491 looks quite sound to me. The new check was failing because the id values weren't restored properly, because they weren't saved in the first place.

**Comment by hultonha** [comment]
Okay excellent, thanks for confirming @aambrosano. I've started a build for https://github.com/o3de/o3de/pull/13491 now @Be-ing. Cheers!

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed on build Development (4ac8adf).
