### ISSUE TITLE
Using Scale manipulator on entity with Ctrl held changes manipulator size globally

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#13430]
**Describe the bug**
If the Scale manipulator is adjusted with Ctrl button, the manipulator's size will be adjusted with it on all entities until the Editor is restarted. It should be noted that using Ctrl with Translate/Rotate manipulators changes the entity pivot point and the Scale does not seem to be doing anything other than changing the manipulator size.

**Steps to reproduce**
1. Select an entity.
2. Change the manipulator mode to *Scale* (for example by pressing 3 on the keyboard).
3. While holding Ctrl, left-click the Scale manipulator and change it.
4. Select any other entity.

**Expected behavior**
Scale manipulator is not affected when changed with the Ctrl key pressed, or it has some effect on an entity.

**Actual behavior**
Adjusting Scale manipulator with Ctrl key pressed changes the manipulator's size.

**Video**

https://user-images.githubusercontent.com/86952082/204541528-2c3b98eb-7ff4-42c7-85a6-0b71829aea45.mp4

**Found in Branch**
Development (a881574)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by hultonha** [comment]
This is by design - this allows user to adjust the size of the manipulator dynamically (it can be reset to the default size with Ctrl-R). This makes things consistent it 'Ctrl' being held changing details of the manipulator (position with translation, orientation with rotation, and size with scale).
