### ISSUE TITLE
Typo in arithmetic error in Graph Validation in Script Canvas

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#13432]
**Describe the bug**
When using arithmetic nodes (Add (+), Subtract (-), Multiply (*), Divide (/)), if less than 2 arguments are specified, an error is printed. The error contains a typo - it says, "Less **then** two valid arguments for arithmetic operator", but it should say "Less **than** two valid arguments for arithmetic operator".

**Steps to reproduce**
1. Open Script Canvas.
2. Create a graph like in the attached screenshot: On Entity Activated -> Add (+).
3. Save the graph.
4. Observe the errors in Graph Validation.

**Expected behavior**
The error text is "Less **than** two valid arguments for arithmetic operator".

**Actual behavior**
The error text is "Less **then** two valid arguments for arithmetic operator".

**Screenshots**

![typo](https://user-images.githubusercontent.com/99388484/204548448-e6be8760-331d-4758-8c9c-2531aa5d6e2e.png)

**Found in Branch**
Development (a881574)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version: 20.04.4 LTS
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by LB-BartoszDudzinski** [comment]
Issue verified as Fixed in the latest development branch (4df30e4).
