### ISSUE TITLE
When the user launches two instances of Asset Processor, the error incorrectly refers to bootstrap.cfg

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#13449]
**Describe the bug**
If the user attempts to launch asset processor for two separate projects, they will be presented with an error that suggests resolving the issue by updating a value in "bootstrap.cfg".  This file no longer exists, but the comparable key/values can be found in bootstrap.setreg found in the o3de/Registry directory.

**Steps to reproduce**
1. Create or acquire two different projects
2. Build both projects
3. Launch Asset Processor for the first project
4. Launch the Asset Processor for the second project
5. See error

**Expected behavior**
The error suggests a correct solution

**Actual behavior**
The error suggests an outdated solution

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82236902/204679337-a93b047d-8776-454d-8290-44e096425013.png)

**Found in Branch**
Development @ 96a5d33921c5

**Comment by AMZN-Gene** [comment]
Relates to https://github.com/o3de/o3de.org/issues/2135

**Comment by amzn-mike** [comment]
Fixed by https://github.com/o3de/o3de/pull/15298
