### ISSUE TITLE
Server launcher crashes when a server/client version mismatch occurs

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#13450]
**Describe the bug**
When the user connects a client to a server where a version mismatch occurs, resulting in the client getting disconnected, the server launcher crashes at the same time.

**Steps to reproduce**
1. Acquire two copies of a multiplayer enabled project (MultiplayerSample)
2. Add a net property to one of the project multiplayer components (for only one of the projects - creating a mismatch)
3. Build both projects
4. Launch the server launcher for one project and host
5. Launch the client launcher from the other project and connect

**Expected behavior**
The client is disconnected, but both launchers remain stable

**Actual behavior**
The client is disconnected and the server closes/crashes

**Found in Branch**
Development @ 96a5d33921c5

**Additional context**
Part of the resulting server log:
<18:14:20> (System) - Disconnecting from remote address 127.0.0.1:49189 due to VersionMismatch
<18:14:20> [Error] (System) - No IReplicationWindow found OnPlayerDisconnect.
<18:14:20> [Warning] (System) - Disconnecting an already disconnecting connection due to TerminatedByServer
<18:14:20> (System) - Multiplayer operating in Uninitialized mode
<18:14:20> [Warning] (System) - Unitialized agent type isn't supported for networking metrics.
<18:14:20> CSystem::Quit invoked from thread 35748 (main is 35748)
<18:14:21> System Shutdown

Call stack:
>	MultiplayerSample.dll!AZ::Module::~Module() Line 19	C++
 	[External Code]	
 	MultiplayerSample.ServerLauncher.exe!AZ::ModuleDataImpl::~ModuleDataImpl() Line 142	C++
 	[External Code]	
 	[Inline Frame] MultiplayerSample.ServerLauncher.exe!AZStd::Internal::sp_counted_base::release() Line 87	C++
 	[Inline Frame] MultiplayerSample.ServerLauncher.exe!AZStd::Internal::shared_count::{dtor}() Line 289	C++
 	[Inline Frame] MultiplayerSample.ServerLauncher.exe!AZStd::Internal::destroy<AZStd::shared_ptr<AZ::ModuleDataImpl> *,AZStd::shared_ptr<AZ::ModuleDataImpl>,0>::single(AZStd::shared_ptr<AZ::ModuleDataImpl> *) Line 68	C++
 	[Inline Frame] MultiplayerSample.ServerLauncher.exe!AZStd::vector<AZStd::shared_ptr<AZ::ModuleDataImpl>,AZStd::allocator>::pop_back() Line 580	C++
 	MultiplayerSample.ServerLauncher.exe!AZ::ModuleManager::UnloadModules() Line 263	C++
 	MultiplayerSample.ServerLauncher.exe!AZ::ComponentApplication::Destroy() Line 888	C++
 	MultiplayerSample.ServerLauncher.exe!AzFramework::Application::Stop() Line 273	C++
 	MultiplayerSample.ServerLauncher.exe!O3DELauncher::Run(const O3DELauncher::PlatformMainInfo & mainInfo) Line 614	C++
 	MultiplayerSample.ServerLauncher.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 31	C++

![image](https://user-images.githubusercontent.com/82236902/204861917-f9138511-b76f-413f-a9c8-0017bd2e4f17.png)

![image](https://user-images.githubusercontent.com/82236902/204862401-ebf5b249-0259-4de1-951a-1ae9b517b2ad.png)

**Comment by AMZN-Gene** [comment]
would have been great to have a log line
https://github.com/o3de/o3de/issues/13463
