### ISSUE TITLE
Feature Request: Toggle to not spawn/render vegetation while in editor. (excluding runtime)

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#13456]
**Is your feature request related to a problem? Please describe.**
I have been working with the terrain gem for a while now, and one big issue I see is while working in the editor the vegetation seems to slow down the editor a little, and a lot while moving around the level.

**Describe the solution you'd like**
A solution would be to have a toggle for rendering/spawning the vegetation while in the editor. This would exclude runtime in the editor, since going into runtime respawns and renders the vegetation anyway. The toggle could have multiple locations, one could be on an already existing component for the vegetation like the Vegetation Spawner component, to make this feature a per spawner toggle (which could be nice for seeing trees, but removing the grass if its in another spawner.) Another place for the toggle could be in its own component that could be only related to the level entity (similar to how the terrain has components that only go onto the level entity). The last approach would be a preference setting in the editor itself, but this would be the least liked location, as it would be hidden, and it would be harder to switch if needed.

**Describe alternatives you've considered**
Alternatives is disabling the component Vegetation Spawner, and enabling it when going into runtime.

**Comment by mbalfour-amzn** [comment]
You can already accomplish this by clicking on the "eyeball" icon next to the vegetation spawner entities in the editor. This will hide the vegetation while editing but still have it display in game mode. (This also works with terrain spawners)

You can also click the eyeball icon on individual gradients to disable just that gradient's effect on vegetation and terrain.

![image](https://user-images.githubusercontent.com/82224783/204845681-02abc7e3-67f0-4803-8b1e-7d76eaee3625.png)
