### ISSUE TITLE
Asset Browser: Whole filesystem hierarchy is shown when project is not under engine folder

### ISSUE THREAD

**Issue by MiKom** [o3de/o3de#13462]
## Steps to reproduce

1. Create a new project _not_ under the engine folder. E.g. on your desktop
2. Open the project in the Editor

# Expected result

Engine and project assets are shown next to each other in the asset browser, same as when the project is located in the engine folder:

![Image](https://user-images.githubusercontent.com/104767/204862570-884ecd09-80cc-4ed3-91f2-269d74c0233b.png)

## Actual result

![Image](https://user-images.githubusercontent.com/104767/204862376-db8c5a53-7c3f-4711-81b0-7e1880cfda43.png)

The root of the filesystem is shown in the Asset Browser and the tree is filtered to engine and project assets.

**Comment by lmbr-pip** [comment]
Related to https://github.com/o3de/o3de/issues/2552
