### ISSUE TITLE
When opening a project in the editor, it says that there are no existing levels when there are

### ISSUE THREAD

**Issue by bgfalcone** [o3de/o3de#13460]
**Describe the bug**
When opening a project in the editor (e.g., Multiplayer Template), it says "no level file created for this project." even when there are. Users can click "Open" and click drop down "levels" to see the existing levels.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.
<img width="488" alt="demolevel" src="https://user-images.githubusercontent.com/116661164/204654343-c755a502-2469-45ba-a217-4c525187f110.png">
<img width="503" alt="existinglevelnotshown" src="https://user-images.githubusercontent.com/116661164/204654344-c19733b0-20ba-44a6-9f5b-e62ab8d4510f.png">
<img width="632" alt="levelsnotexpanded" src="https://user-images.githubusercontent.com/116661164/204654346-1d3a59fb-935e-47b3-89be-e0761f4199f2.png">

**Steps to reproduce**
1. Create new project with a template that has levels
2. Open project in editor
3. See dialog says "no level file created for this project"
4. Click Open button
5. Click Levels drop down and notice that levels actually do exist

**Expected behavior**
When opening a project that has existing levels (including those that have never been opened, like a template with existing levels),  the module where there is a "Create New" button, should indicate that levels exist and make it easy to select them.

**Actual behavior**
When opening a project in the editor (e.g., Multiplayer Template), it says "no level file created for this project." even when there are. Users can click "Open" and click drop down "levels" to see the existing levels.

**Screenshots/Video**
<img width="503" alt="existinglevelnotshown" src="https://user-images.githubusercontent.com/116661164/204654976-a6f8d09e-9be8-4b4b-933a-7ee0259184ab.png">
<img width="632" alt="levelsnotexpanded" src="https://user-images.githubusercontent.com/116661164/204654977-56daac18-b452-4e1d-b559-1197b739b49a.png">
<img width="488" alt="demolevel" src="https://user-images.githubusercontent.com/116661164/204654975-aab0ed1e-fb23-49cd-806c-4cd953630004.png">

**Found in Branch**
(https://o3debinaries.org/2210RTE/Windows/o3de_installer.exe)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Please provide the SHA/hash that identifies the latest commit from the o3de/o3de repository if the issue is reproducible in the development or other official branches. 
You can get the commit ID by running the `git rev-parse HEAD` command on your current branch.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by AMZN-daimini** [comment]
Label is incorrect - that view only displays recently opened levels.
We should either change the label to match the behavior, or change the behavior to match the label.
Looping in @o3de/sig-ui-ux to advise.

**Comment by amzn-leenguy** [comment]
> Label is incorrect - that view only displays recently opened levels. We should either change the label to match the behavior, or change the behavior to match the label. Looping in @o3de/sig-ui-ux to advise.

I agree. We should have a more context aware label depending on behavior / scenario.
