### ISSUE TITLE
Monolithics builds are broken

### ISSUE THREAD

**Issue by CyaNinix** [o3de/o3de#13473]
**Describe the bug**
After updating to the latest version of O3DE a few weeks ago, our release version (a monolithic build) was broken because it couldn't load any asset (including critical ones) from its .pak files.

We tracked down the issue, and it turns out it was because the engine tried to register the .pak manifests before the `BundlingSystemComponent` activated (and registered to the `AZ::IO::ArchiveNotificationBus`).

Essentially, `Archive::OnSystemEntityActivated()` is triggered before system entities are activated.

This is because of this change: https://github.com/o3de/o3de/commit/0f02a6485a9af08c962304b37e8b0b633428cb51

which added those lines:
https://github.com/o3de/o3de/blob/92278197f7567cd63c92560658252bd47b150862/Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp#L1509-L1513

This causes an issue because of the way the engine starts, in ComponentApplication.cpp:
https://github.com/o3de/o3de/blob/92278197f7567cd63c92560658252bd47b150862/Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp#L751-L764

As you can see, settings are merged before creating the system components (which is normal), this will load the "boostrap.game.release.setreg" file which contains all .setreg settings, including those:
https://github.com/o3de/o3de/blob/92278197f7567cd63c92560658252bd47b150862/Registry/application_lifecycle_events.setreg#L9-L15

Before https://github.com/o3de/o3de/commit/0f02a6485a9af08c962304b37e8b0b633428cb51 this triggered an event telling that the root key changed, not triggering bundle loading.

However, since this commit triggers a notification for every merged key, it will trigger an event telling `/O3DE/Application/LifecycleEvents/SystemComponentsActivated` changed, which will cause https://github.com/o3de/o3de/blob/92278197f7567cd63c92560658252bd47b150862/Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp#L369-L378 to trigger, calling `Archive::OnSystemEntityActivated` too early (before system components are even created).

This empties `m_archivesWithCatalogsToLoad`, even though they couldn't load, which prevent them to load correctly later.

With bundles not being loaded, critical assets can't load and we got this error at startup:
![image](https://user-images.githubusercontent.com/99494374/205014280-91035c7e-0bb4-4e65-bf52-57f5bd44d1b5.png)

Commenting out those lines fixes the issue:
https://github.com/o3de/o3de/blob/92278197f7567cd63c92560658252bd47b150862/Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp#L1509-L1513

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
92278197f7567cd63c92560658252bd47b150862

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU: AMD R9 5950X
 - GPU: RTX 2080 Ti
 - Memory: 64GB

**Comment by lumberyard-employee-dm** [comment]
> Thanks for reporting this @CyaNinix, this looks incredibly important. Seems like an issue for @o3de/sig-core (tagging @amzn-pratikpa and @lumberyard-employee-dm for visibility).

Yeah I'll look into this issue. I am thinking of adding a check to the Lifecycle callback that verifies that the lifecycle event is active by checking an `active` key underneath the `/O3DE/Application/LifecycleEvents` setting

**Comment by hultonha** [comment]
Thanks @lumberyard-employee-dm! Much appreciated :+1:
