### ISSUE TITLE
Asset Browser: Support Undo for file deletion, or always show a confirmation dialog

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#13488]
**Is your feature request related to a problem? Please describe.**
It is very easy to delete a file from the Asset Browser, potentially even inadvertently with the Delete key or via context menu with an unintended asset selected. If this is done, and there are no references found to the asset, the file is simply deleted with no way to get it back. 

**Describe the solution you'd like**
Support Undo for file deletions, or at least always show a confirmation dialog (potentially with a toggle box to hide in the future) with a warning that it's an irreversible action.

**Describe alternatives you've considered**
Being very precise about what files to delete.

**Comment by rainbj** [comment]
![Delete files](https://user-images.githubusercontent.com/82551958/208215080-bda92c5e-54cb-4ba9-a476-e8484aa3d234.png)

Ideally, we would like to support both workflows. However, In this image, I have given both option if we are unable to support undo file deletion.

**Comment by rainbj** [comment]
@micronAMZN and @chanmosq - Please let me know if my text works for you or if you have further suggestions to refine the copy.
