### ISSUE TITLE
Asset Browser: Only one new folder can be created at a time without renaming the newly created folder

### ISSUE THREAD

**Issue by jckand** [o3de/o3de#13482]
**Describe the bug**
Only one new folder can be created at a time without renaming the newly created folder. Until the user renames the new folder with default New Folder name, Create Folder will simply not function. This is exacerbated by the folder creation not immediately selecting the new folder with the rename interface up, much like what happens when a new asset is created.

**Steps to reproduce**
1. Launch the Editor and open the Asset Browser.
2. Create a new folder in any valid directory.
3. Without renaming the new folder, create another new folder.

**Expected behavior**
Default new folder name is incremented so a new folder can be created, or the user is immediately asked to rename the newly created folder, much like asset creation works.

**Actual behavior**
Nothing happens on the 2nd create folder operation without renaming/moving the first created folder.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
83fe1b7041c8d68a9ed79a62f4807a72affe9d06

**NOTE**
1. This also affects moving a newly created default name folder to another directory that already has a default name folder.

**Comment by jckand-amzn** [comment]
Verified fix on development@ b25c961520462444316cab8eae0ccc1a8c850fb3.
