### ISSUE TITLE
EMotionFX: Unfocusing viewport causes drastic zoom in if Follow Character option is enabled

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#13502]
**Describe the bug**
When the User unfocuses viewport in the Animation Editor, it zooms in drastically. This issue occurs only if the Follow Character option under Camera settings is enabled.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Open the Animation Editor (Tools -> Animation Editor).
2. Make sure that Follow Character option under Camera settings is enabled.
3. Click LMB on the Animation Editor's viewport.
4. Click LMB on any other window inside the Animation Editor.

**Expected behavior**
Position of the camera does not change when the viewport loses focus.

**Actual behavior**
Camera drastically zooms in when the viewport loses focus.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952318/205319195-0069e11f-c9ce-4be3-8bae-f24749b298ac.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
3f384ad

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600 6-Core Processor
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

**Comment by hultonha** [comment]
@LB-MichalRodzos I don't suppose you don't have this change https://github.com/o3de/o3de/pull/13433 get @LB-MichalRodzos? My guess is that either fixes this or might unfortunately have caused it 😅 🙈 I'll try and take a look soon but would be good to confirm. Thanks!

**Comment by LB-BartoszDudzinski** [comment]
Hi @hultonha! I verified the commits and this issue occurs on https://github.com/o3de/o3de/commit/3f384adebe9e2dfc9e926d34fd3fa70c5bad9d37 which is newer than commit with your PR https://github.com/o3de/o3de/pull/13433 so it should be included in the tested build. Just to be sure we will try to reproduce this issue with the latest development.

**Comment by LB-BartoszDudzinski** [comment]
We just confirmed that this issue occurs on the latest development branch.

**Comment by hultonha** [comment]
Okay understood, thanks very much for following-up @LB-BartoszDudzinski

**Comment by LB-JaroslawGaweda** [comment]
Issue verified as Fixed in the latest development branch (https://github.com/o3de/o3de/commit/4df30e4c42f20374bec352aad39fe5e36d3eaad1).
