### ISSUE TITLE
Feature Request: Deploy O3DE as a Snap package

### ISSUE THREAD

**Issue by amzn-changml** [o3de/o3de#13511]
**Is your feature request related to a problem? Please describe.**
As a user and developer of O3DE, I would like to install the O3DE binary as a Ubuntu Snap package

**Describe the solution you'd like**
I would like the entire install contained in the Ubuntu Snap store, which would ease discoverability and improve the installer experience. From a CD side, it would help reduce relance on self-hosted infrastructure that we would have to manage to continuously deploy O3DE

**Describe alternatives you've considered**
We could publish a Apt repository, but that would also incur costs for managing the infrastructure for deployed packages and increase user friction. However, both the Apt repository and Snap package can be published simultaneously if desired.

We would still need to publish packages compatible with other distro's default package manager (Yum, Pacman, Nix, etc.), but that can be a separate feature request, depending on the motivation of the community to target these platforms.

**Additional context**
Documentation about packaging for the Snap store can be found here: https://snapcraft.io/docs/snapcraft-overview

**Comment by amzn-changml** [comment]
Will need to bring this up in the next TSC agenda for acceptance and direction, with coordination with @o3de/sig-release

**Comment by tonybalandiuk** [comment]
@amzn-changml  can you attend the SIG-release meeting at 10am 12/20 to discuss further? I can add this to the agenda.

**Comment by Ulrick28** [comment]
We brought snap up in the 12/13 meeting. We were told that the LF/Royal needs to make the call concerning snap as there are some marketing/trademark issues they would need to resolve. @OBWANDO is aware and is working on getting the appropriate approvals.

**Comment by amzn-changml** [comment]
Great to hear! Once we get the approvals, we can plan out workflow mapping in conjunction with the release team.

@tonybalandiuk Sure, I can attend the meeting, unless what @Ulrick28 brought up answers our next steps

**Comment by amzn-changml** [comment]
Completed as of 23.05.1
