### ISSUE TITLE
Bug Report: Script Canvas prefab path asset immediately crashes from the editor

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#13534]
**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/205665228-a88b90bf-f01b-4578-a2b4-e4a5a0d0ac6a.mp4

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
4ac8adffbe54068a43b7e90d3248b7cf309ee843

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Fedora
 - Version 36

**Additional context**
```(Script Canvas) - 
Root:
TimeDelay:Done[FunctionDefinition] # children: 1
	Done:FindParameterName:In[FunctionCall] # children: 1
		Out:SetNamedParameterBool:In[FunctionCall] # children: 1
			Out:Get Variable:In[FunctionCall] # children: 1 <<<< MARKER <<<< 
[Error] (ScriptCanvas) - Script Canvas parsing failed
(Script Canvas) - 
Root:
TimeDelay:Done[FunctionDefinition] # children: 1
	Done:FindParameterName:In[FunctionCall] # children: 1
		Out:SetNamedParameterBool:In[FunctionCall] # children: 1
			Out:Get Variable:In[FunctionCall] # children: 1 <<<< MARKER <<<< 
```

[Editor.log](https://github.com/o3de/o3de/files/10155139/Editor.log)

**Comment by lsemp3d** [comment]
Cannot reproduce on latest development [21c1414](https://github.com/o3de/o3de/commit/21c1414)
