### ISSUE TITLE
Bug Report: EMFX Add motion event specify location mouse cannot click on motion drag mouse for time view

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#13535]
**Describe the bug**
motion event specify location mouse cannot click motion mouse drag to move it is not convenient to set time to another location

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/205690362-b61ff1bc-c636-40e9-ba0e-1a7361e2dc8f.mp4

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
4ac8adffbe54068a43b7e90d3248b7cf309ee843

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Fedora
 - Version 36

**Comment by hultonha** [comment]
Thanks for reporting @Darkinggq. @amzn-rhhong had a look at this and found the middle mouse scroll behavior is broken so it might be easiest to just disable it. @amzn-rhhong is going to take a look and report back!

**Comment by Darkinggq** [comment]
@amzn-rhhong @hultonha I tested today nothing has changed on linux (development: 35ee6319dac8bbfeaac69b045d57ca51ac12f7d7)

https://user-images.githubusercontent.com/17591539/207359875-0aa10b7c-5320-4c81-a5e1-a60208c52609.mp4
