### ISSUE TITLE
Feature Request: Refactor the bus bindings strings in atom_tools_utils.py to be easily maintained

### ISSUE THREAD

**Issue by jromnoa** [o3de/o3de#13544]
**Describe the bug**
This came from feedback for https://github.com/o3de/o3de/pull/13509#discussion_r1038563578
A lot of bus calls for various buses used by `azlmbr.atomtools` have duplicated values in the `atom_tools_utils.py` file located here: https://github.com/o3de/o3de/blob/development/AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_tools_utils.py 
We should create a new class object to store these bus call values and have functions within the class that return the proper bus calls. This way in the future we will only have to update 1 bus value instead of a bunch of them (whack a mole).

**Assets required**
N/A

**Steps to reproduce**
N/A this is more of a re-factor for keeping code clean.

**Expected behavior**
Bus calls are written once for each bus and stored inside a class that has functions to return the desired result from the bus.

**Actual behavior**
Bus calls have duplicated code for the same buses just changing the behavior context string to call. There should be 1 bus object stored to a parent class that utilizes it child functions to return the desired bus call values.

**Screenshots/Video**
See https://github.com/o3de/o3de/pull/13509#discussion_r1038563578 for the source of this ticket.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
development @ commit id 5c19ca7f00eb004d0563c06f22a44ef85166b533

**Desktop/Device (please complete the following information):**
N/A

**Additional context**
N/A just a simple re-factor ticket.

**Comment by FuzzyCarterAWS** [comment]
Alternatively to class functions, you can use a class store of  "CONSTS" to keep thing light-weight.

**Comment by Kadino** [comment]
May be appropriate to autogenerate these in the .pyi files

**Comment by jromnoa** [comment]
Adding this here: https://github.com/o3de/o3de/pull/14103 
Will close once the PR is merged.
