### ISSUE TITLE
Material Canvas curve type setting is not applied immediately

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#13559]
**Describe the bug**
In Material Canvas, if the curve type setting is changed, it is not applied immediately to open graphs. A graph must be closed and opened anew for the setting to be applied. This is inconsistent with the behaviour of this setting in Script Canvas, where the change is applied immediately.

**Steps to reproduce**
1. Open Material Canvas.
2. Create any graph with connections, for example with a Bool Constant node connecting to an another Bool Constant node.
3. In Tools>Settings change the Connections>Data Connection Curve Type setting.

**Expected behavior**
Curve type is updated immediately.

**Actual behavior**
Curve type does not update until a graph is closed and opened again.

**Screenshots/Video**

https://user-images.githubusercontent.com/99388484/205941148-a4db3f7c-87c2-47bf-8755-e69631e153b9.mp4

**Found in Branch**
Development (0ed5937)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/0ed5937e2d69078e5f73966d84e6d0de17f86627

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by LB-KonradJuszczak** [comment]
Issue verified as fixed on build Development (8b58313).

**Comment by LB-KonradJuszczak** [comment]
Issue verified as fixed on build Development (https://github.com/o3de/o3de/commit/8b58313b373ccc23395cdcdc54ebd95cb14caabd).
