### ISSUE TITLE
Add support for PhysX 5

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#13624]
**Is your feature request related to a problem? Please describe.**

NVIDIA recently announced that PhysX 5 is being made open source (https://developer.nvidia.com/blog/open-source-simulation-expands-with-nvidia-physx-5-release/).

O3DE currently relies on PhysX 4.1 as its only physics backend, and as it is no longer receiving updates (it is end of life (EOL)) it makes sense for O3DE to begin the upgrade to PhysX 5 sooner rather than later.

**Describe the solution you'd like**

Update PhysX third-party libraries to PhysX 5 and upgrade the PhysX Gem to support PhysX 5.

**Describe alternatives you've considered**

Continuing to use PhysX 4 (or looking into other candidates for physics engines).

**Additional context**

PhysX 5.1 RFC - https://github.com/o3de/sig-simulation/issues/31.

**Comment by moraaar** [comment]
## PhysX Links
https://github.com/o3de/PhysX/pull/1
https://github.com/o3de/PhysX/pull/2
https://github.com/o3de/PhysX/pull/3
https://github.com/o3de/PhysX/pull/4

## 3p-package-source Links
https://github.com/o3de/3p-package-source/pull/165
https://github.com/o3de/3p-package-source/pull/171

## o3de Links
https://github.com/o3de/o3de/pull/13802

**Comment by hultonha** [comment]
All relevant work to support PhysX 5 has been completed. Closing issue.
