### ISSUE TITLE
Wrong Thumbnail Shown in Material Component

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#13637]
**Describe the bug**
After changing a material override, the thumbnail will show the original material from the model instead of the new override material.

**Steps to reproduce**
1. Create a new level
2. Select the ground plane
3. Note the groundplane material icon, and the fact that it's using the default "groundplane_512x512..." material.
![image](https://user-images.githubusercontent.com/55155825/206808669-ec99c8c8-f991-405d-b36a-7ff907c693e5.png)
4. Change this to some other material, say red.azmaterial.
5. Note that the plane in the viewport is red, but the thumbnail is still the same as before.
![image](https://user-images.githubusercontent.com/55155825/206808832-14efee39-ba47-45e3-816c-b1259616e767.png)
6. Save the level.
7. Close the level.
8. Open the level again.
9. Select the ground plane
10. This time the icon is red as expected.
![image](https://user-images.githubusercontent.com/55155825/206808915-7ea57704-f7bc-4288-80cd-37d01072d953.png)
11. Change the material to blue.azmaterial
12. Note that the plane in the viewport is blue, but the thumbnail has reverted to the default groundplane material instead of showing blue.
![image](https://user-images.githubusercontent.com/55155825/206809021-eb52ca29-7322-4dec-9be1-51752df9634c.png)

**Expected behavior**
The preview thumbnail should show the material that has been selected.

**Actual behavior**
After changing the material override, the thumbnail always reverts to the default material from the model.

**Found in Branch**
WIP feature branch, so I'm not 100% sure, but I suspect this is happening in development too.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
0ab46df8ca16bc2b6f3a07f34168563af8ef91f8 on my feature branch
1522b3fe54210eb6d9e74117cd9dc4083b451b72 on development

**Comment by monroegm** [comment]
Seems to be an issue with the Material Component owned by SIG-Graphics-Audio

**Comment by gadams3** [comment]
cannot reproduce with latest
