### ISSUE TITLE
Camera: Middle mouse button incorrectly zoom out the scene

### ISSUE THREAD

**Issue by amzn-rhhong** [o3de/o3de#13645]
**Describe the bug**
There seems to be inconsistent behavior about the camera control in main editor when pressing the middle mouse button.
When pressing the middle mouse button, it behave like a free look camera. However, when you use the right button to move the camera first, then press the middle mouse button, it zoom the camera far away from the center.

**Steps to reproduce**
1. Open an empty level
2. Press the middle mouse button, move around
3. Release middle mouse button, press right button, move camera
4. Release right mouse button, press middle mouse button

**Expected behavior**
Camera behavior should stay the same

**Actual behavior**
Camera zoom out to far away from screen

**Screenshots/Video**

https://user-images.githubusercontent.com/69218254/206958825-fc0cd096-19c6-4419-a41b-2509c5a6ee97.mp4

**Found in Branch**
12/11/2022 dev

P.S I also don't like how the middle mouse button behave by default. I'm move in favor of how the blender editor works.
In Blender: Middle mouse orbiting around the selected point. When press middle mouse + shift, then it behave the same like what o3de does today. (see video)

https://user-images.githubusercontent.com/69218254/206959093-4fc2c4f2-6cff-49bc-87a5-bb578ce9fbd0.mp4

**Comment by hultonha** [comment]
@amzn-rhhong I tried reproducing this locally but things worked as expected and I did not get the zoom out behavior you mention. Could you please try again on latest. Also to confirm were you holding Alt at any point while doing this? Or was it just MMB, RMB and then MMB again?

On the behavior side of things, I think it'd be best to create a separate feature request issue and tag @benblack75 for feedback.

**Comment by hultonha** [comment]
If you press and hold Alt and use LMB that gives the orbit behavior you showed in the video below, I'm not sure what is the standard across all tools but I believe most game engines behave this way. It might be possible to update/change though to be more consistent.

**Comment by amzn-rhhong** [comment]
I tried using a second mouse to verify locally but couldn't repo.
Although using my first mouse, i don't the the same problem in maya or blender. Since for now this is only happening to my mouse, I will close this.

**Comment by hultonha** [comment]
> I tried using a second mouse to verify locally but couldn't repo. Although using my first mouse, i don't the the same problem in maya or blender. Since for now this is only happening to my mouse, I will close this.

Thanks for the response Roman and the additional info. If you do see this happening again in future definitely let me know. Thanks!
