### ISSUE TITLE
Create an Add new button in the header of Asset Browser

### ISSUE THREAD

**Issue by rainbj** [o3de/o3de#13652]
As a user, I need the ability to "add new" from the main navigation bar instead of just right click behavior. Currently, we already have the ability to add new via the right click menu. However, this is a hidden action. Right click should be a secondary behavior for add new instead of the primary. Primary will be this new "Add new" button.

The add new button should apply to the selected folder the user has selected. So this means if a user clicks onto a directory and then hits add new. The add new will be applied to that folder.

If no folder is selected, we should ask the user where they would like this file to be added to. Maybe via selector menu.

![Image](https://user-images.githubusercontent.com/82551958/207124198-11141801-db70-4d5c-af43-64703b1dabaa.png)

**Comment by rainbj** [comment]
https://www.figma.com/file/TfXXZD1xjlw67MMeRYEbi0/Asset-Browser-Design-Document?node-id=971%3A36645&t=52vP54kHeA4LkkQd-1

**Comment by jjjoness** [comment]
@rainbj ![Editor_N1NxfvwrtK](https://user-images.githubusercontent.com/82226755/208099074-4c4dfeeb-346d-4f4c-896c-b1e79848b9db.gif)
