### ISSUE TITLE
AssetNotificationMessage where materials are registered without a type.

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#13677]
**Describe the bug**
When starting up the engine, a handful of messages are logged that look like "AssetCatalog: Received `AssetNotificationMessage` network message with no AssetType.  Asset "materials/terrain/pbrterrain_allproperties.material" will be registered without a type."

**Steps to reproduce**
1. Start the Editor.
2. Read the debug log.

**Expected behavior**
No log messages should exist that warn about assets without types. If a warning is printed, it should contain clearly actionable steps and a definitive statement as to whether or not this is something to be concerned about. (i.e. "material will be registered without a type. If the material is expected to be an asset type that users interact with, the material builder needs to be fixed to emit the asset type.")

**Actual behavior**
A handful of messages that look vaguely concerning, saying things like: "AssetCatalog: Received `AssetNotificationMessage` network message with no AssetType.  Asset "materials/terrain/pbrterrain_allproperties.material" will be registered without a type."

**Found in Branch**
development

**Comment by AMZN-stankowi** [comment]
Triage: We had a discussion off github about this, it's an issue with the material asset type, sending this to sig graphics.
