### ISSUE TITLE
Script Canvas: The Ungroup button is active even if an ungrouped node is selected

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#13673]
**Describe the bug**
The _Ungroup_ button becomes active after any node is selected, even if the node does not belong to any group. 
Pressing the button in such case does not have any effect.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Launch Script Canvas.
2. Add any node to the graphs.
3. Select the node.

**Expected behavior**
The _Ungroup_ button remains grayed out until a Group is selected.

**Actual behavior**
The _Ungroup_ button becomes active when any node is selected.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/207321960-c9b27b15-aec3-46b8-900a-4ee457275886.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
35ee631

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development ([fc7f51a](https://github.com/o3de/o3de/commit/fc7f51a5748612eb069ec4623908311e2af99915)).
