### ISSUE TITLE
Script Canvas: The Command Line tool is missing the header bar

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#13671]
**Describe the bug**
The Command Line tool in Script Canvas does not have the header bar with the tool's name and a _X_ (close) button. This is not consistent with all the other tools within the Script Canvas.

Please refer to the attached screenshot for more details.

**Steps to reproduce**
1. Launch Script Canvas.
2. Open the Command Line tool by either selecting Tools -> Command Line or pressing the _CTRL+P_ hotkey.

**Expected behavior**
The Command Line tool has a header bar with its name and the _X_ button.

**Actual behavior**
The Command Line tool is missing a header bar with its name and the _X_ button.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/86953108/207320276-13bd3391-be0f-4d2b-989d-760f9d1c2e48.png)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
35ee631

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by lsemp3d** [comment]
This was by design, it's intended to behave like the command line in visual studio, but, it's an experimental, incomplete feature that has been disabled by default

**Comment by LB-MateuszSzweda** [comment]
Confirming the issue has been closed as it cannot be reproduced in Development ([fc7f51a] . The command line was successfully flagged as experimental and is hidden by default in Script Canvas.
