### ISSUE TITLE
Editor Model Asset Preview Never Loads

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#13691]
**Describe the bug**
The editor model asset previewer never finishes loading.

**Steps to reproduce**
1. Open Editor
2. Select a Model in the Asset Browser

**Expected behavior**
A preview of the model appears in the preview window

**Actual behavior**
Model never appears. The blue loading spinner spins forever.

![image](https://user-images.githubusercontent.com/32776221/207521850-6a16e921-f9bf-48c3-ba27-9f8e025d8b2a.png)

https://user-images.githubusercontent.com/32776221/207521907-60f5d8c1-baed-4dbf-8424-ed3ee17d1dc1.mp4

Found in Branch
development

Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository
https://github.com/o3de/o3de/commit/076fd1943f87323993fa564c3b16e1b24b083d21
Tue Dec 6 2022

**Comment by HogJonny-AMZN** [comment]
I've seen this with material previews also (in version areas of the editor)
And it may be possible, that this could be why prefabs with these materials assigned are not rendering their materials correctly?

![image-2023-01-23-17-52-02-898](https://user-images.githubusercontent.com/23222931/214185719-8c260662-73b5-4519-a695-c620903e3e46.png)

**Comment by gadams3** [comment]
fixed in point release 23.10 .1 preparing to be merged to main and development
