### ISSUE TITLE
Crash: Animation Editor: Inspector Node Properties doesn't clear if bone is deselected

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#13732]
**Describe the bug**
If a user deselects the actor instance after they've selected a skeleton bone they can attempt to add a property that will result in an editor crash

**Steps to reproduce**
1. Open Animation Editor
2. Select the Physics Layout
3. Import an Actor
4. Select the Actor Instance in the  Actor Manager
5. Select a bone
6. Add a Property from the Inspector window
7. Navigate away from a valid bone:
   * Deselect the Actor Instance in the Actor Manager
   * Select the Character Node from the Skeleton Outliner
8. Attempt to add a Property from the Inspector window

**Expected behavior**
Inspector window clears when a valid is not selected.

**Actual behavior**
Inspector window shows Node Properties and allows the user to attempt to add properties that can result in an editor crash.

**Screenshots/Video**
![1F878FA0-7686-4C92-94FB-9D5D39F67AA0](https://user-images.githubusercontent.com/29718640/208005790-7cf80cbb-3e0a-4ff4-b963-e182848615ae.GIF)
![28000C8C-DFA7-4FA3-A8AF-146B04BC1755](https://user-images.githubusercontent.com/29718640/208006059-c5b6e93f-0468-4ce6-891d-4677619750a5.GIF)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c6da6778c74425fb1a1193c7381cdd80dbc8b8a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10

**Comment by hultonha** [comment]
Assigning critical for now as this is a bit of an edge case after discussing with @FuzzyCarterAWS so may downgrade to major in future.
