### ISSUE TITLE
In Edit mode Cylinder shaped PhysX Collider cannot be rescaled and changes made to Offset and Rotation are not applied immediately

### ISSUE THREAD

**Issue by LB-HubertUberman** [o3de/o3de#13735]
**Describe the bug**
In Edit Mode, PhysX Collider with Cylinder shape does not have resize points when in Scale mode, and changes made in Offset or Rotate modes are only applied after exiting the Edit Mode and moving the entity containing it. The issue occurs on both Linux and Windows.

**Steps to reproduce**
1. Open any level.
2. Create a new entity with the PhysX Collider component.
3. Set Shape to Cylinder.
4. Enter Edit mode.
5. Choose Offset Mode and try to make any changes.
6. Choose Rotate Mode and try to make any changes.
7. Choose Scale Mode and try to make any changes.
8. Exit Edit mode and move the entity.

**Expected behavior**
All collider shapes can be edited in Edit mode without any issues.

**Actual behavior**
In Edit mode Cylinder shaped PhysX Collider cannot be rescaled and changes made to Offset and Rotation are not applied immediately.

**Screenshots/Video**

https://user-images.githubusercontent.com/96232062/208076900-1f1a3e54-0f0c-465b-a5a0-1212fd13cbc6.mp4

**Found in Branch**
PhysX5Support (https://github.com/o3de/o3de/commit/de24f8a32e91184db2988bba9f60aa40a8e97374)
Development (https://github.com/o3de/o3de/commit/a16d07a0c0c13bdc184dbb49bbb00bf28ee5456d)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[aws-lumberyard-dev](https://github.com/aws-lumberyard-dev/o3de/tree/PhysX5Support)
[Development](https://github.com/o3de/o3de)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by hultonha** [comment]
This is the same issue as https://github.com/o3de/o3de/issues/13912

Closing as duplicate.

**Comment by LB-HubertUberman** [comment]
Further progress on the issue will be covered in #13912, as per the comment above. Removing the status/duplicate label as the mentioned issue has been logged after the original one.
