### ISSUE TITLE
The "Gem name" in the "Create New Gem" window is incorrectly described as unique 

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#13738]
**Describe the bug**
According to the [Create a gem workflow tests](https://github.com/o3de/sig-content/blob/main/testing-guidance/workflow-tests/create-a-gem/create-a-gem-workflow-tests.md) it should be possible to use two gems that share the same name, however, the _Gem name_ field in the _Create New Gem_ window has the following description:
 "_The **_unique_** name for your gem consisting of only alphanumeric characters, '-' and '\_'._"

**Steps to reproduce**
1. Launch the Project Manager.
2. Navigate to the Gems tab.
3. From the hamburger menu select Create New Gem.
4. Choose any template and select Next.
5. Verify the _Gem name_ field description.

**Expected behavior**
The _Gem name_ description does not suggest that the name has to be unique.

**Actual behavior**
The _Gem name_ description suggests that the name has to be unique.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/86953108/208118260-0ac7fd80-fd41-4865-a125-978d39e3ae98.png)

![image](https://user-images.githubusercontent.com/86953108/208441729-82288f38-6ae2-409a-9c60-27b0304171cd.png)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
35ee631

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by monroegm** [comment]
If the description just needs to be updated then this might be a good first issue.

**Comment by tkothadev** [comment]
I would recommend modifying the workflow rather than the system here, as what you state is correct. Per @LB-TomaszSerwanski's suggestion, I am closing this issue, as correcting the workflow should be a separate concern.
