### ISSUE TITLE
(EditorViewportWidget) - Internal logic error

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#13744]
**Describe the bug**
I opened a level, and got this error in the console:
[Error] (EditorViewportWidget) - Internal logic error - active view changed to an entity which is not an editor camera. Please report this as a bug.

**Assets required**
I was using the ROSConDemo project, but I suspect this could be replicated by creating two levels which each have an entity with an entity camera.

**Steps to reproduce**
1. Open the 'Main' level
2. In the entity outliner, select a camera entity
3. In the entity inspecter, click 'Be this camera'
4. Open another level, which also has a entity with a camera
5. See error message in console
6. Go back to the first level
7. Click 'Be this camera' on the entity again
8. The camera remains in the position of the editor camera, not the position from the entity camera

**Expected behavior**
No console error message, and clicking 'Be this camera' on an entity always takes the viewport camera to the position of that camera

**Actual behavior**
Console error message, and camera remains in the position of the editor camera

**Screenshots/Video**

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
37b99bfa3e5e88a1d545c1fe40784531d70766e2

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel I9-10900X
 - GPU: NVidia GeForce RTX 2080 SUPER
 - Memory: 64GB

**Additional context**

**Comment by hultonha** [comment]
This in-progress branch https://github.com/aws-lumberyard-dev/o3de/tree/hultonha_GHI-13525_editor-camera-component-updated has more fixes that's getting close to being ready to share that fixes this problem.
