### ISSUE TITLE
Asset Browser - Remove folder selection for move when location is selected by user already.

### ISSUE THREAD

**Issue by rainbj** [o3de/o3de#13759]
**Describe the bug**
As a user, It doesn't make sense to show a location bar to me when I already selected my location in the left had panel of the Asset Browser. I would however expect a location selector IF I haven't already selected a folder location. This means if no location is selected we should verify location with the user.

![2022-12-16_17-59-59](https://user-images.githubusercontent.com/82551958/208218266-7011a30d-f5d1-4034-a5e0-2b2eef518a7d.png)

**Comment by svitlani** [comment]
@dtamkin1 , can you please verify this feature already exists. @rainbj for visibility.

**Comment by dtamkin1** [comment]
@svitlani Just tested it on latest dev and this is still the current prompt when a user tries to add a new material or material graph.

**Comment by rainbj** [comment]
@dtamkin1 and @svitlani there was also an additional issue found about renaming a material from untitled material. To change the name you cannot do it from that line, but it allows you to change it but it doesn't accept the change after changing it
