### ISSUE TITLE
"Be This Camera" Mode Blocks Editing Transform

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#13763]
**Describe the bug**
While in "be this camera mode" I cannot make micro-adjustments to the camera position by changing the values by hand in the transform component.

**Steps to reproduce**
1. Open the default level
3. Select the camera entity
4. Select "Be this camera"
5. Try to edit the camera position by editing the transform component

**Expected behavior**
Editing the transform component should move the camera

**Actual behavior**
User must click "Return to default editor camera" in order to hand-edit the transform 

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32776221/208367904-82fff8fa-f736-4e9d-ac0e-b82acf0cf349.png)

Notice in the video I change the X rotation value to 0.0, 2.0, and 10.0 but it always snaps back to the original value.
https://user-images.githubusercontent.com/32776221/208368292-00d626a4-75fc-403a-8016-4a1d2e3b034d.mp4

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
47eea0c820a3639fcbcb04aff991235e9132adb1 
Monday December 12 2022

**Comment by hultonha** [comment]
This in-progress branch https://github.com/aws-lumberyard-dev/o3de/tree/hultonha_GHI-13525_editor-camera-component-updated has more fixes that's getting close to being ready to share that fixes this problem.
