### ISSUE TITLE
Child Materials Not Automatically Rebuilt in Some Cases

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#13766]
**Describe the bug**
There are some situations where a .materialtype can be changed and fail to trigger rebuilds of all relevant .material files.

**Assets required**
This was tested using AtomSampleViewer, but should also work with the AutomatedTesting project.

**Steps to reproduce**
1. Make sure all assets are built.
2. Open the Asset Processor
3. Set the filter rule to "_detailmaps_.*material" for easier viewing
4. Delete Gems\Atom\Feature\Common\Assets\Materials\Types\EnhancedPBR.materialtype
5. Force the detail maps materials to reprocess, by right click "Reprocess Source Asset".
   1. TestData/Materials/StandardPbrTestCases/101_DetailMaps_BaseNoDetailMaps.material
   2. TestData/Materials/StandardPbrTestCases/102_DetailMaps_All.material
   3. TestData/Materials/StandardPbrTestCases/105_DetailMaps_BlendMaskUsingDetailUVs.material
   4. TestData/Materials/StandardPbrTestCases/103_DetailMaps_BaseColor.material
   5. TestData/Materials/StandardPbrTestCases/104_DetailMaps_Normal.material
   6. TestData/Materials/StandardPbrTestCases/104_DetailMaps_NormalWithMask.material
   7. TestData/Materials/StandardPbrTestCases/103_DetailMaps_BaseColorWithMask.material
8. Note that each one should now be failed.
9. Restore the EnhancedPBR.materialtype file

**Expected behavior**
All of the detail maps materials should automatically reprocess and have the Completed status again

**Actual behavior**
Several of the child materials were not reprocessed and remain in the Failed state. If you manually force them to reprocess, they will complete.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/55155825/208386285-c20b55a9-5d04-4cce-9fce-185f4ba946c6.png)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
5b4e14838121bc221b72a754738bd9815dfddf86

**Comment by gadams3** [comment]
This should be resolved by the additional fingerprinting logic added to material and material type builders
