### ISSUE TITLE
The "Edit Gem" button on the gem tab is not functional when pressed from the "Configure Gems..." window 

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#13770]
**Describe the bug**
Pressing the _Edit Gem_ button on the gem tab in the _Configure Gems..._ menu has no effect. Please note that the same button pressed from the _Gems_ tab is fully functional.

Refer to the attached video for more details.

**Prerequisite**
Any project created and displayed in the Project Manager.

**Steps to reproduce**
1. Launch the _Project Manager_.
2. From the project's hamburger menu select _Configure Gems..._.
3. Select any gem.
4. On the gem tab select _Edit Gem_.

**Expected behavior**
The _Edit gem_ window opens.

**Actual behavior**
Nothing happens.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/208444769-aa64afcc-b7ca-4d8f-9688-de856951b561.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
5b4e148

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by AMZN-alexpete** [comment]
Closing as fixed
