### ISSUE TITLE
AWS Resource Mapping Tool won't open

### ISSUE THREAD

**Issue by BytesOfPiDev** [o3de/o3de#13798]
**Describe the bug**
Launching the Resource Mapping Tool from the O3DE editor or the command line does not work. Instead of launching the tool's GUI, an error log is generated.

**Assets required**
N/A

**Steps to reproduce**
1. Open the O3DE editor.
2. Close the welcome screen.
3. In the menu bar, click AWS.
4. Click `AWS Resource Mapping Tool...`
5. See that nothing happens.
6. Check your project's `user/log` folder and open `resource_mapping_tool.log` to see the following error:

```
22:13:02,106 __main__ INFO Using C:\o3de-projects\Test\user\log\resource_mapping_tool.log for logging.
22:13:02,106 __main__ INFO Setting up Qt environment ...
22:13:02,123 __main__ INFO Importing tool required modules ...
22:13:02,161 __main__ ERROR Failed to import module [QtCore] DLL load failed while importing QtCore: The specified module could not be found.
```

Alternatively...

1. Go to the root of your O3DE engine folder.
2. Open a powershell window at the location.
3. Enter `.\python\python.cmd .\Gems\AWSCore\Code\Tools\ResourceMappingTool\resource_mapping_tool.py --binaries-path C:\o3de-projects\<Your Project>\build\windows\bin\profile\AWSCoreEditorQtBin`
4. See that nothing happens.
5. Check `.\Gems\AWSCore\Code\Tools\ResourceMappingTool\resource_mapping_tool.log` to see the following error:

```
22:31:37,536 __main__ INFO Using C:\repos\o3de\Gems\AWSCore\Code\Tools\ResourceMappingTool\resource_mapping_tool.log for logging.
22:31:37,537 __main__ INFO Setting up Qt environment ...
22:31:37,557 __main__ INFO Importing tool required modules ...
22:31:37,603 __main__ ERROR Failed to import module [QtCore] DLL load failed while importing QtCore: The specified module could not be found.
```

**Expected behavior**
The AWS Resource Mapping Tool should successfully launch from the editor without errors. From the command line, provided requirements are met, the tool should successfully launch without errors.

**Actual behavior**
The tool fails to launch. No GUI is shown. No feedback is given to indicate that the program attempted to run or generated an error. Invisibly, an error is generated in the project's `user/log` directory. 

**Screenshots/Video**
N/A

**Found in Branch**
main, built as SDK, as well as the 22.10 installer.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
3704e30b2092770be8593c9ec0a8c98d16d7c3d6

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10, Build 19044
 - CPU AMD Ryzen 3700X 8-Core Processor
 - GPU NVIDIA RTX 3070
 - Memory 64GB

**Additional context**
https://www.o3de.org/docs/user-guide/gems/reference/aws/aws-core/resource-mapping-tool/

There is no `QtCore.dll` in my `AWSCoreEditorQtBin` folder. Instead, it has `Qt5Core.dll`.

**Comment by lmbr-pip** [comment]
Can reproduce this issue locally:
```
10:21:44,199 __main__ ERROR Failed to import module [QtCore] DLL load failed while importing QtCore: The specified module could not be found.
```

**Comment by lmbr-pip** [comment]
Looks like the upgrade to Python 3.10 may have broken DLL loading here.

Hack to fix is to add 1 line to `Gems\AWSCore\Code\Tools\ResourceMappingTool\resource_mapping_tool.py`
```
if __name__ == "__main__":
    if arguments.binaries_path and not environment_utils.is_qt_linked():
        logger.info("Setting up Qt environment ...")
        environment_utils.setup_qt_environment(arguments.binaries_path)
        os.add_dll_directory(arguments.binaries_path) << --- Add this
```

**Comment by BytesOfPiDev** [comment]
I cherry-picked https://github.com/o3de/o3de/pull/13826 into `main`, and it worked! Thank you.

**Comment by BytesOfPiDev** [comment]
Issue resolved
