### ISSUE TITLE
Modifying a prefab instance while not in focus mode then making the same modification in focus mode creates a dangling override

### ISSUE THREAD

**Issue by raktalen** [o3de/o3de#13825]
**Describe the bug**
If the user makes a modification to a prefab (remove a component for example) and saves it as an override in the level, then goes to the prefab and makes the same change, the override created earlier is left in the level file and is now dangling.
The user has no way to clean this up from the editor.

**Steps to reproduce**
1. Create a prefab with two entities
2. On either of the entities , add a component and save that prefab
3. Get out of focus mode and remove the component added in 2
4. Save
5. Go into focus mode and remove the component added in 2
6. Save the prefab to file
7. Open the level file
8. Notice that there is a remove operation that is now dangling.
9. Close the editor and open the level again
10. Notice the error message that crops up.

**Expected behavior**
Redundant or invalid override operations are safely cleaned, while erroneous operations are reported to the user with clear recourse in the editor.

**Actual behavior**
Override operations can be left dangling.

**Screenshots/Video**

### Example of dangling remove operation
`                {
                    "op": "remove",
                    "path": "/Entities/Entity_[502959369132]/Components/Component_[17962080546363069677]"
                }
`

### Error message dialog
![image](https://user-images.githubusercontent.com/118857486/209213610-1bce70fe-a35b-4573-bd18-e1215b0d83e6.png)

**Found in Branch**
development - overrides enabled

**Comment by monroegm** [comment]
The current behavior is intended

**Comment by AMZN-daimini** [comment]
I think current behavior is correct and intended, but that extra override should be resolved without erroring out then. We should have a way for users to see which overrides were not applied and why, but it shouldn't be through the error panel.

**Comment by raktalen** [comment]
Is there a ticket to address the error message ? I'm not 100% sure about this , but I believe the error message is currently modal and just wont let you load the level at all.
