### ISSUE TITLE
Crash Saving a new Prefab after deleting an old one with the same name

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#13832]
**Describe the bug**
Trying to create a new prefab and delete an old one with the same name leads to a crash. The fix could be as simple as a null check, but would like someone more familiar with the system to weigh in on if there is something deeper that needs to be addressed.

**Assets required**

**Steps to reproduce**
1. Open any level in the editor
2. In the main editor viewport, right-click and choose "create prefab"
3. Give it a file name like myprefab and save it. This will create a prefab out of the currently selected entity
4. ctrl+z to undo the prefab creation and make the entity a regular entity again
5. In the main viewport, righ-click->create entity
6. In the entity outliner, select the new entity and right click->save as prefab
7. Try to save it as myprefab, and see a warning that it will break other prefabs
8. Ignore the warning, because you know that one was just now created by mistake, and nothing is using it or inheriting from it
9. Delete myprefab.prefab via the windows file dialog
10. Save the new prefab as myprefab.prefab

**Expected behavior**
No crash, new prefab saves successfully, original prefab is deleted

**Actual behavior**
Crash with the following callstack:
>	EditorLib.dll!AzToolsFramework::Prefab::Template::IsValid() Line 88	C++
 	EditorLib.dll!AzToolsFramework::Prefab::PrefabSystemComponent::FindTemplateDom(unsigned __int64 templateId) Line 505	C++
 	EditorLib.dll!AzToolsFramework::Prefab::PrefabPublicHandler::CreatePrefabInMemory(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entityIds, AZ::IO::PathView filePath) Line 246	C++
 	EditorLib.dll!AzToolsFramework::Prefab::PrefabPublicHandler::CreatePrefabAndSaveToDisk(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entityIds, AZ::IO::PathView filePath) Line 390	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::Prefab::PrefabIntegrationManager::ContextMenu_CreatePrefab(AZStd::vector<AZ::EntityId,AZStd::allocator> selectedEntities) Line 790	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AzToolsFramework::Prefab::PrefabIntegrationManager::PopulateEditorGlobalContextMenu::__l76::<lambda_6>::operator()() Line 499	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,`AzToolsFramework::Prefab::PrefabIntegrationManager::PopulateEditorGlobalContextMenu'::`76'::<lambda_6>>::call(AzToolsFramework::Prefab::PrefabIntegrationManager::PopulateEditorGlobalContextMenu::__l76::<lambda_6> &) Line 146	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!QtPrivate::Functor<`AzToolsFramework::Prefab::PrefabIntegrationManager::PopulateEditorGlobalContextMenu'::`76'::<lambda_6>,0>::call(AzToolsFramework::Prefab::PrefabIntegrationManager::PopulateEditorGlobalContextMenu::__l76::<lambda_6> &) Line 256	C++
 	ComponentEntityEditorPlugin.dll!QtPrivate::QFunctorSlotObject<`AzToolsFramework::Prefab::PrefabIntegrationManager::PopulateEditorGlobalContextMenu'::`76'::<lambda_6>,0,QtPrivate::List<>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 443	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 3997	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 54	C++
 	Editor.exe!main(int argc, char * * argv) Line 32	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
 	[External Code]	

Specifically, in
PrefabDom& PrefabSystemComponent::FindTemplateDom(TemplateId templateId)
        {
            TemplateReference findTemplateResult = FindTemplate(templateId);
            AZ_Assert(
                findTemplateResult.has_value(),
                "PrefabSystemComponent::FindTemplateDom - Unable to retrieve Prefab template with id: '%llu'. "
                "Template could not be found",
                templateId);

            AZ_Assert(findTemplateResult->get().IsValid(),
                "PrefabSystemComponent::FindTemplateDom - Unable to retrieve Prefab template with id: '%llu'. "
                "Template is invalid", templateId);

            return findTemplateResult->get().GetPrefabDom();
        }
findTemplateResult was null

**Screenshots/Video**

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
5b4e14838121bc221b72a754738bd9815dfddf86

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel I9-10900X
 - GPU: NVidia GeForce RTX 2080 SUPER
 - Memory: 64GB

**Additional context**
I wanted to create a prefab, which normally in the editor's main viewport I'd right-click->create entity and then try and save it as a prefab. However, when I right-clicked I saw "Create Prefab" was an option so I tried that. I did not realize that would create a prefab out of the currently selected entity (or the entity I right-clicked on, not sure which one was the case). I expected it to create a new entity, since I was not meaning to click on an existing entity. That's a minor UX quirk, and it sort of makes sense if I think about my action as right-clicking an entity vs. right-clicking a point in space. (Maybe we can do something to color code or make sections in the drop down menu to make it clear which options apply to the entity you're clicking on vs. which do not). That's a minor UX quirk to follow up on, but not the point of the bug. That's just how I ended up in my situation.

**Comment by srikappa-amzn** [comment]
Investigating a fix for this that doesn't require hot reloading. Will post an update once its ready
