### ISSUE TITLE
When using lambdas with Attributes in the EditContext, the lambda signature requires a void* handler

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#13830]
**Describe the bug**
When trying to use a lambda with an Attribute in an EditContext, the expectation is that it would have a signature that receives a typed instance of the class, similar to passing a member function in. Instead, the lambda is required to receive a void*.

**Steps to reproduce**
1. Change the code for the AttributeData_WithCallableType_Succeeds in AzCore/Tests/Serialization.cpp to the following. The only change to the method is changing `AZ::AttributeInvoker invoker` to `AZ::AttributeReader invoker`:
```
    TEST_F(Serialization, AttributeData_WithCallableType_Succeeds)
    {
        constexpr AZ::Crc32 invokableCrc = AZ_CRC_CE("Invokable");
        constexpr AZ::Crc32 nonInvokableCrc = AZ_CRC_CE("NonInvokable");
        auto ReadFloat = [](SerializeTestClasses::BaseNoRtti* instance) -> float
        {
            auto noRttiInstance = instance;
            if (!noRttiInstance)
            {
                ADD_FAILURE() << "BaseNoRtti instance object should not be nullptr";
                return 0.0f;
            }
            EXPECT_FALSE(noRttiInstance->m_data);
            return 2.0f;
        };

        m_serializeContext->Class<SerializeTestClasses::BaseNoRtti>()
            ->Attribute(invokableCrc, ReadFloat)
            ->Attribute(nonInvokableCrc, 4.0f)
            ;

        SerializeTestClasses::BaseNoRtti baseNoRttiInstance;
        baseNoRttiInstance.Set();
        auto classData = m_serializeContext->FindClassData(azrtti_typeid<SerializeTestClasses::BaseNoRtti>());
        ASSERT_NE(nullptr, classData);
        AZ::Attribute* attribute = AZ::FindAttribute(invokableCrc, classData->m_attributes);
        ASSERT_NE(nullptr, attribute);
        AZ::AttributeReader invoker(&baseNoRttiInstance, attribute);
        float value = 0;
        EXPECT_TRUE(invoker.Read<float>(value));
        EXPECT_FLOAT_EQ(2.0f, value);

        AZ::Attribute* nonInvokeAttribute = AZ::FindAttribute(nonInvokableCrc, classData->m_attributes);
        ASSERT_NE(nullptr, nonInvokeAttribute);
        invoker = { &baseNoRttiInstance, nonInvokeAttribute };
        value = {};
        EXPECT_TRUE(invoker.Read<float>(value));
        EXPECT_FLOAT_EQ(4.0f, value);
    }
```
2. Run the unit test. Observe it failing.
3. Change the ReadFloat definition to start with the following:
```
        auto ReadFloat = [](void* instance) -> float
        {
            auto noRttiInstance = (SerializeTestClasses::BaseNoRtti*)instance;
```
4. Run the unit test. Observe it succeeding.

**Expected behavior**
The first unit test change succeeds, the second one fails.

**Actual behavior**
The AttributeReader type creates an AttributeInvoker<void>, so when the invoker.Read() call is made, the AZ::Internal::AttributeRead() method tries to cast the attribute to an AttributeInvokable<float(void*&)> instead of an AttributeInvokable<float(BaseNoRtti*&)>, so the cast only succeeds if the lambda takes in a void*.

Ideally this would successfully call the lambda with a strongly-typed instance pointer. 

Even better, it should warn if the lambda is defined with the wrong parameters and print the expected function signature instead of just silently ignoring it.

**Found in Branch**
development

**Comment by lumberyard-employee-dm** [comment]
@mbalfour-amzn Well the code is actually working as intended for the AttributeReader.
It can only be used with an function object that accepts a `void*` as the first argument.

However, I have a change that can workaround the issue by providing a function on the base `Attribute` class that can return an `AttributeReader` that internally can cast the `void*` to the strongly-typed instance pointer and make the function call in the following branch: https://github.com/aws-lumberyard-dev/o3de/pull/new/attribute-void-pointer-call-wrapper
