### ISSUE TITLE
Material Canvas crashes when materialtype is being generated

### ISSUE THREAD

**Issue by LB-KonradJuszczak** [o3de/o3de#13847]
**Describe the bug**
Material Canvas crashes when materialtype is being generated. The issue is inconsistent but occurs more often at the beginning of the Material Canvas session and when the Float input nodes are used.
Please note that the issue occurs with DX12 and Vulkan.

**Steps to reproduce**
1. Launch Material Canvas.
2. Add Float2 input node.
3. Add Experimental PBR node.
4. Connect color pins.

**Expected behavior**
Material Canvas remains stable and the material is generated without issues.

**Actual behavior**
Material Canvas crashes.

**Screenshots/Video**

[Call_Stack.txt](https://github.com/o3de/o3de/files/10313875/Call_Stack.txt)

**Found in Branch**
Development
**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
(https://github.com/o3de/o3de/commit/55856fbb15081d199b0d0b666882bb5edec339e6)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPERS
- Memory: 16 GB

**Comment by LB-KacperMetelski** [comment]
Issue verified as fixed in commit 0a66664.
