### ISSUE TITLE
Material Canvas with Vulkan enabled crashes after connecting Sample Texture 2D node to Experimental PBR node

### ISSUE THREAD

**Issue by LB-KonradJuszczak** [o3de/o3de#13848]
**Describe the bug**
Material Canvas crashes after connecting the Sample Texture 2D node to the Experimental PBR node. This issue occurs only with the Vulkan version of the Material Canvas.

**Steps to reproduce**
1. Open the Material Canvas with Vulkan.
2. Add Sample Texture 2D node.
3. Add Experimental PBR node.
4. Connect color pins.

**Expected behavior**
Material Canvas remains stable.

**Actual behavior**
Material Canvas crashes.

**Screenshots/Video**
[Call_Stack.txt](https://github.com/o3de/o3de/files/10314252/Call_Stack.txt)

https://user-images.githubusercontent.com/108653853/209813885-31ddd4eb-608d-41d2-a5be-901aea75e2ea.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
(https://github.com/o3de/o3de/commit/55856fbb15081d199b0d0b666882bb5edec339e6)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPERS
- Memory: 16 GB

**Comment by OBWANDO** [comment]
This also crashes in DirectX as of development branch on 1/3/2003.
If you quickly save it before the asset processor completes the compilation, you can load it back up and it may not crash.

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed on build Development (ff756fc).
The Experimental PBR node is no longer available in the Material Canvas, verified that the issue is no longer active using Base PBR and Standard PBR nodes.
