### ISSUE TITLE
Unified Launcher is unable to load a level

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#13859]
**Describe the bug**
The Unified Launcher is unable to load a level.  This is due to current limitations/safety measures that block level loading while clients are connected.  Since the unified launcher acts as client host and inherently has the host machine as a client, it is unable to load/change levels.

**Steps to reproduce**
1. Create a multiplayer project or use MultiplayerSample
2. Build the project
3. Launch the Unified Launcher
4. Attempt to load a level

**Expected behavior**
The level is loaded with the host client already connected

**Actual behavior**
The level is blocked from loading/changing due to an already connected client

**Found in Branch**
mp_cliser_macro @ 17f23b820d

**Comment by AMZN-Gene** [comment]
Reading the repro are you sure you're just not trying to load a multiplayer level even though you're not hosting? I think we guard rail against that, but the logs would tell you for sure. I dont see a repro step for calling "host" or "connect".
What happens when you call "loadlevel" with a non-network level?

**Comment by robhaco** [comment]
@AMZN-Gene it looks like that was part of it.  After testing again with host AND a fully set up multiplayer level, it seems to be working as expected. Closing this issue.

**Comment by robhaco** [comment]
Created a related feature request for Server and Unified launcher to automatically host when it detects it's loading a multiplayer level: https://github.com/o3de/o3de/issues/13894
