### ISSUE TITLE
Frequent Editor Crash using Component Mode (White Box)

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#13873]
**Describe the bug**
The editor commonly crashes when using the whitebox tool (and likely any component that has an alternative "component mode")

**Steps to reproduce**
1. Open a level
2. Create a white box
3. Enter white-box component editor mode and edit the white box
4. Hit escape to exit component mode
5. Select another entity 

**Expected behavior**
Editor doesn't crash

**Actual behavior**
Editor crashes
`
>	EditorLib.dll!AzToolsFramework::ComponentModeFramework::ComponentModeSwitcher::RemoveNonCommonComponents(const AZ::Entity & entity) Line 339	C++
 	EditorLib.dll!AzToolsFramework::ComponentModeFramework::ComponentModeSwitcher::UpdateSwitcher(const AZStd::vector<AZ::EntityId,AZStd::allocator> & newlySelectedEntityIds, const AZStd::vector<AZ::EntityId,AZStd::allocator> & newlyDeselectedEntityIds) Line 143	C++
 	[Inline Frame] EditorLib.dll!AZStd::Internal::INVOKE(void(AzToolsFramework::ToolsApplicationEvents::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &, const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &) Line 177	C++
 	[Inline Frame] EditorLib.dll!AZStd::invoke(void(AzToolsFramework::ToolsApplicationEvents::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &, const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &) Line 54	C++
 	[Inline Frame] EditorLib.dll!AZ::EBusEventProcessingPolicy::Call(void(AzToolsFramework::ToolsApplicationEvents::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &, const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &) Line 437	C++
 	EditorLib.dll!AZ::Internal::EBusContainer<AzToolsFramework::ToolsApplicationEvents,AzToolsFramework::ToolsApplicationEvents,0,1>::Dispatcher<AZ::EBus<AzToolsFramework::ToolsApplicationEvents,AzToolsFramework::ToolsApplicationEvents>>::Broadcast<void (__cdecl AzToolsFramework::ToolsApplicationEvents::*)(AZStd::vector<AZ::EntityId,AZStd::allocator> const &,AZStd::vector<AZ::EntityId,AZStd::allocator> const &),AZStd::vector<AZ::EntityId,AZStd::allocator> &,AZStd::vector<AZ::EntityId,AZStd::allocator>>(void(AzToolsFramework::ToolsApplicationEvents::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &, const AZStd::vector<AZ::EntityId,AZStd::allocator> &) && func, AZStd::vector<AZ::EntityId,AZStd::allocator> & <args_0>, AZStd::vector<AZ::EntityId,AZStd::allocator> && <args_1>) Line 1360	C++
 	EditorLib.dll!AzToolsFramework::ToolsApplication::MarkEntitiesSelected(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entitiesToSelect) Line 629	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZStd::Internal::INVOKE(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &&) Line 177	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZStd::invoke(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &&) Line 54	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZ::EBusEventProcessingPolicy::Call(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &&) Line 437	C++
 	ComponentEntityEditorPlugin.dll!AZ::Internal::EBusContainer<AzToolsFramework::ToolsApplicationRequests,AzToolsFramework::ToolsApplicationRequests,0,0>::Dispatcher<AZ::EBus<AzToolsFramework::ToolsApplicationRequests,AzToolsFramework::ToolsApplicationRequests>>::Broadcast<void (__cdecl AzToolsFramework::ToolsApplicationRequests::*)(AZStd::vector<AZ::EntityId,AZStd::allocator> const &),AZStd::vector<AZ::EntityId,AZStd::allocator>>(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) && func, AZStd::vector<AZ::EntityId,AZStd::allocator> && <args_0>) Line 1541	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::EntityOutlinerWidget::OnSelectionChanged(const QItemSelection & selected, const QItemSelection & deselected) Line 383	C++
 	[External Code]	
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AzToolsFramework::EntityOutlinerTreeView::ProcessQueuedMousePressedEvent(QMouseEvent * event) Line 455	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::EntityOutlinerTreeView::mouseReleaseEvent(QMouseEvent * event) Line 177	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 3997	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 54	C++
 	Editor.exe!main(int argc, char * * argv) Line 32	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++

`
![image](https://user-images.githubusercontent.com/32776221/210315811-94146abf-28ac-462a-9eee-fd8c47c667e1.png)

**Screenshots/Video**
https://user-images.githubusercontent.com/32776221/210316226-b2938406-5209-4e98-b553-ca7aaacb06ba.mp4

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c9368cc69f38f139394c6fb59e890b248f972a1f
Thu Dec 29 2022

**Comment by hultonha** [comment]
@amzn-ahmadkrm This looks like something you would know about as it relates to the Viewport UI Switcher

**Comment by AMZN-Gene** [comment]
Fixed by #13923
