### ISSUE TITLE
Multiplayer: As a Dev I'd Like AutomatedTesting to Use the Built-In SimplePlayerSpawner

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#13879]
**Is your feature request related to a problem? Please describe.**
The AutomatedTesting project is currently using a custom built network player spawner. AutomatedTesting should have the least amount of custom code as possible to reduce maintenance costs, and compile time.

**Describe the solution you'd like**
Change AutomatedTesting to use the built-in Multiplayer gem SimplePlayerSpawner component

**Comment by lmbr-pip** [comment]
Requires modifying the network specific levels and delete the custom spawner code.
