### ISSUE TITLE
Material Canvas: Connecting Refraction Vector node to Experimental PBR node causes .materialgraph to fail in Asset Processor

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#13891]
**Describe the bug**
If a Refraction Vector node is connected directly or indirectly (for example by pathing it through a different node) to the Experimental PBR node, the .materialgraph will fail processing in the Asset Processor. Please refer to the **Video and Asset Processor log** section for full log.

This issue occurs on Linux as well as Windows (DX12 RHI).

**Steps to reproduce**
1. Go to Tools > Material Canvas (Preview).
2. In the Material Canvas, right-click on the graph, find the Experimental PBR node and select it.
3. Add a Refraction Vector node the same way.
4. Connect the Refraction Vector's *Value* output pin to a compatible input pin on the Experimental PBR node (for example *Base color*).

**Expected behavior**
Asset Processor successfully process the .materialgraph asset.

**Actual behavior**
Asset Processor fails to process the .materialgraph asset.

**Video and Asset Processor log**

https://user-images.githubusercontent.com/86952082/210551148-68f589cb-515e-4e9e-b369-59d344126220.mp4

[untitled_ForwardPass.shader-2392495840-14111.log](https://github.com/o3de/o3de/files/10343831/untitled_ForwardPass.shader-2392495840-14111.log)

**Found in Branch**
Development (9849ab8)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
9849ab86323026e59189aa38b5451ef03bd36d44

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-KatarzynaDylska** [comment]
Issue verified as fixed in Development (ecf542f) build. All the mentioned nodes have been deprecated.
