### ISSUE TITLE
Material Canvas: Highlighting remains partially after defocusing selected row

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#13917]
**Describe the bug**
After defocusing the highlighted row in the Node Palette, a part of the highlighting still remains where the selection was previously displayed.

**Steps to reproduce**
1. Open the Material Canvas.
2. Select rows in Node Palette.
3. Press LMB somewhere else in the Node Palette.

**Expected behavior**
Rows in the Node Palette are highlighted consistently.

**Actual behavior**
Highlighting of the previously selected row still remains.

**Screenshots/Video**
https://user-images.githubusercontent.com/110163473/210779331-1a5e242d-759a-4a52-a599-069ffcf836c6.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
af94a59

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: Windows 11 21H1
 - CPU: i7-17000F
 - GPU: RTX-3070 MSI
 - Memory: 32GB

**Comment by gadams3** [comment]
Cannot reproduce
