### ISSUE TITLE
Material Canvas: Undo/redo actions cause selection of all nodes in graph

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#13919]
**Describe the bug**
Undoing or redoing an action selects all of the nodes added to the graph.

**Steps to reproduce**
1. Open Material Canvas.
2. Create three or more random nodes.
3. Press Ctrl-Z or CTRL+Y.

**Expected behavior**
Only the undo/redo action is executed.

**Actual behavior**
Every node in the graph is selected.

**Screenshots/Video**
https://user-images.githubusercontent.com/110163473/210789650-c274f2c3-e43d-4ac3-9204-75684ba882ef.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
af94a59

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: Windows 11 21H1
 - CPU: i7-17000F
 - GPU: RTX-3070 MSI
 - Memory: 32GB

**Comment by LB-MichalRodzos** [comment]
Issue verified as fixed on build Stabilization/2305 (169ab99). On Development build (73e54c6) the issue still occurs on Windows platform.
