### ISSUE TITLE
AR Bug Report: editor_test.log Wrong Time Stamp

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#13913]
**Describe the bug**
When Automated Testing fails during an editor py test, the editor-log is printed, but the timestamp on every log output in Jenkins is the same making it hard to tell what occurred at certain times. If my test timed out, I cannot tell which part of the process is taking too long and failing.

https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-13898/1/pipeline

![648D03A8-449E-45BE-A7E9-0CBBC2205154](https://user-images.githubusercontent.com/32776221/210680228-f7e2f1c5-fff2-41b1-9446-cb1cd4342703.jpeg)

![image](https://user-images.githubusercontent.com/32776221/210681467-46e72138-ba5c-49ef-9a6f-bd9292b53ae9.png)

**Comment by Kadino** [comment]
These are Jenkins' timestamps. This likely occurs due to logs being piped in one batch on failure to Jenkins, after failure occurs.

I wonder if there is a flag for enabling timestamps in the editor log itself?

**Comment by lumberyard-employee-dm** [comment]
Yes there is actually an option for showing timestamp, which is the [log_IncludeTime](https://github.com/o3de/o3de/blob/development/Code/Legacy/CrySystem/Log.cpp#L42-L51) CVAR which is set to 1 logs the current time to the log files.
That is currently working as of the latest change to the transition the CVAR over to use the AZ Console in this [commit](https://github.com/o3de/o3de/commit/c9bb592ac78264b2850d12d4ef31a1a6bb548073).
![image](https://user-images.githubusercontent.com/56135373/213248459-7dcd0d09-19b0-4632-bfe2-12fb047dd830.png)

**Comment by Kadino** [comment]
Timestamps from when the log event occurred should now appear inside the logging statements, though everything will also still be preceeded by the Jenkins-timestamp.
