### ISSUE TITLE
Material Canvas: Certain Experimental PBR values are not clamped

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#13921]
**Describe the bug**
Metallic, Specular F0 Factor, Roughness and Alpha values in the Experimental PBR node are not clamped, while they should be restricted to values [0 - 1] (for example in Material Editor on StandardPBR materials they are). Exceeding these values in either way will cause some graphical issues with the material.

Please note, while this is an issue, it would be nice to keep this node "as is"(with unlimited values) separate from the Experimental PBR node with properly clamped values. Some of these values (especially set to negative numbers) create quite unique materials, especially when applied to different Meshes setup in a scene.

**Steps to reproduce**
1. Go to Tools > Material Canvas (Preview).
2. In the Material Canvas, right-click on the graph, find the Experimental PBR node and select it.
3. Type in values different than [0-1] to Metallic, Specular F0 Factor, Roughness and Alpha values.

**Expected behavior**
Metallic, Specular F0 Factor, Roughness and Alpha values do not accept values outside of the [0 - 1] range.

**Actual behavior**
Metallic, Specular F0 Factor, Roughness and Alpha values accept values outside of the [0 - 1] range and actually affect the material.

**Video**

https://user-images.githubusercontent.com/86952082/210790126-5ebdf82a-6641-4337-8514-abf139fe4bbb.mp4

**Found in Branch**
Development (af94a59)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
af94a59086da9fc7e5af403a56ce12e6aba2f800

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment]
Ranges, sliders, and drop downs can be implemented for certain properties and input nodes. It's debatable whether the values should be clamped in the UI. Even if the text fields are clamped, users can create inputs using the nodes that generate values outside of any predetermined ranges. It would also have to be clamped in the shader code to absolutely prevent any bad values from getting in. But the user might have a use case for going beyond those thresholds. If the user wants to clamp values they can use the clamp node. We can implement support for ranges and clamping but need to itemize which values that should apply to.

**Comment by gadams3** [comment]
As mentioned above, the user can input any values into the fields or connect other nodes that may not respect any input ranges placed on the ui controls. I recommend leaving the nodes unclamped but adding support for ranges to material inputs that generate the material type properties. Those can have ranges, enumerations, and other options.
