### ISSUE TITLE
CCD and Kinematic settings can be turned on at the same time

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#13981]
**Describe the bug**
CCD and Kinematic settings can be turned on simultaneously and can't be turned off afterwards. The following error is printed in console afterwards:
> [Error] (PhysX) - PxErrorCode 4: RigidBody::setRigidBodyFlag: kinematic bodies with CCD enabled are not supported! CCD will be ignored. (line 476 in /tmp/tmpy49ykj1y/buildtrees/physx/src/38fe6fd5fa-764b391545.clean/physx/source/physx/src/NpRigidBodyTemplate.h)

This issue is related to the following commit - [a6943b6779bccd8f8b5a285e965f63307124279a](https://github.com/o3de/o3de/commit/a6943b6779bccd8f8b5a285e965f63307124279a)

**Steps to reproduce**
1. Create an entity with the PhysX Rigid Body Component.
2. Turn Kinematic ON.
3. Turn the CCD ON.

**Expected behavior**
CCD setting becomes read only when Kinematic is enabled and vice versa.

**Actual behavior**
An error occurs. Both CCD and Kinematic settings cannot be disabled anymore.

**Screenshots/Video**
https://user-images.githubusercontent.com/110163473/211572915-c6d1ad73-d2dd-4713-a74b-15f0863b3e5b.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
446de8a

**Desktop/Device (please complete the following information):**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.5 LTS
- CPU: i7-17000F
- GPU: RTX-3070 MSI
- Memory: 32GB

**Comment by AMZN-daimini** [comment]
@amzn-ahmadkrm FYI :)

**Comment by LB-KacperMetelski** [comment]
Issue doesn't occur as of commit 681d577; CCD and Kinematic mode can't be enabled at the same time.
