### ISSUE TITLE
Nightly Build: Several builds failed with ModuleNotFoundError: No module named 'jinja2'

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#14000]
**Describe the bug**
Several builds failed with ModuleNotFoundError: No module named 'jinja2'.

**Failed Jenkins Job Information:**
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/221/pipeline

**Attachments**
[log(1).txt](https://github.com/o3de/o3de/files/10394417/log.1.txt)

**Additional context**
This appears to affect all jobs.

**Comment by amzn-changml** [comment]
Being addressed by https://github.com/o3de/o3de/pull/14004

**Comment by robhaco** [comment]
Looks like this might be related/the same issue: https://github.com/o3de/o3de/issues/13992

**Comment by jackalbe** [comment]
https://github.com/o3de/o3de/pull/14004

**Comment by moraaar** [comment]
Today's nightly build confirmed this issue is not happening anymore.
