### ISSUE TITLE
Asset Browser-  Thumbnail View: show global results on Thumbnail View when typing a string in the search box

### ISSUE THREAD

**Issue by aambrosano** [o3de/o3de#14003]
Currently when filtering assets by string, both the Asset Tree View and the Asset Thumbnail View are updated to show results.
However, the Thumbnail View only shows results for the folder currently selected on the Asset Tree View.

What we want instead is to see all folders and files that match the search string on a flattened view.

The workflow is as follows:
- When the user types a string in the search box, folders and files from the whole asset database will be filtered according to the search string and shown in the thumbnail view (global results)
- When clicking on an item on the Asset Tree View after a search operation, the Thumbnail View will work as before, by showing all assets and folder contained in the selected folder
- (optional) right clicking on a result shows a context menu with a "go to folder" entry. Clicking on that item, the Thumbnail View will show the content of the folder in which the asset is.

**Comment by monroegm** [comment]
Appears to already be addressed by #14077
