### ISSUE TITLE
Multiplayer: Server Launcher is Missing Multiplayer IMGUI Menu 

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#14039]
The Server Launcher is missing the "Multiplayer" ImGui Menu. IMGUI can be used to host multiplayer levels as well as launch local clients.

**Steps to reproduce**
1. Run ServerLauncher
2. Hit [HOME] key to open IMGUI

**Expected behavior**
Multiplayer IMGUI option is available

**Actual behavior**
Multiplayer IMGUI option is missing

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32776221/212267709-a21ff649-4ff7-45e8-8b39-4c8f68ae5048.png)

**Found in Branch**
development branch January 12 2023

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
199205f7e62b39906c06c78f239d080e2aeddeb3

**Comment by AMZN-puvvadar** [comment]
This is actually by design. The long term philosophy here is for **ServerLauncher** to be a headless dedicated server. The logic and dependencies for Multiplayer's ImGUI tools are fully compiled out to that effect. To make use of these tools in a Server context, favor using the **UnifiedLauncher**.
