### ISSUE TITLE
get_python.sh script fails to obtain packages on M1 machine with fresh macOS system due to Bad CPU type in executable error

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#14042]
**Describe the bug**
Trying to obtain required python packages by using get_python.sh script located in _o3de/python_ directory failed on freshly setup
M1 chipset MacBook Air 2020 machine with the following error:

```
macpro@macpros-MacBook-Air python % ./get_python.sh
Using cmake located at: /Users/macpro/o3de/3rdParty/Cmake/CMake.app/Contents/bin/cmake
cmake version 3.25.1 CMake suite maintained and supported by Kitware (kitware.com/cmake).
-- Downloading package into /Users/macpro/o3de/python/runtime/python-3.10.5-rev2-darwin
'/Users/macpro/o3de/3rdParty/CMake/CMake.app/Contents/bin/cmake' '-E' 'tar' 'xf' '/Users/macpro/o3de/python/downloaded_packages/python-3.10.5-rev2-darwin.tar.xz'
-- Installed And Validated package at /Users/macpro/o3de/python/runtime/python-3.10.5-rev2-darwin - OK
-- Using package /Users/macpro/o3de/python/runtime/python-3.10.5-rev2-darwin
installing via pip...
~/o3de/python ~/o3de
./python.sh: line 29: /Users/macpro/o3de/python/runtime/python-3.10.5-rev2-darwin/Python.framework/Versions/3.10/bin/python3: Bad CPU type in executable
```

The exact software specifications of the machines is:
* MacBook Air 2020 (M1 chipset, Ventura 13.0.1 , XCode 14.2 , CMake 3.25.0)

A working workaround was found which consisted of following steps:
1. Running `softwareupdate --install-rosetta` command in terminal. 
2. Setting terminal app to _Open using Rosetta_ via right clicking the app and opening _get info_ panel
After these steps the script was able to obtain and install all of the required packages.

Please note that this started to occur only on the freshly setup machine with macOS Ventura 13.0.1 system being installed from the scratch and not being updated from previous macOS versions.
It can also be reproduced by performing **System Settings > General > Erase All Content and Settings** on the already setup machine and reinstalling the macOS system.

For further information please refer to the full log _get_python.sh_ included as an attachment. 

**Prerequisites**
A macOS machine with M1 chipset with Ventura 13.0.1 system installed from the scratch.

**Steps to reproduce**
1. Obtain the Development branch build via GitHub.
2. Create a new or move your preexisting 3rdParty folder containing CMake into the o3de folder.
3. Open the terminal in  _o3de/python_ directory.
4. Set the following temporary environment variables in the Terminal:
```
export PATH=$PATH:/Users/<home_folder_name>/o3de/3rdParty/CMake/CMake.app/Contents/bin
export LY_3RDPARTY_PATH=/Users/<home_folder_name>/o3de/3rdParty
export LY_PACKAGE_SERVER_URLS=https://d2c171ws20a1rv.cloudfront.net
```
5. Obtain python packages with the _get_python.sh_ script.

**Expected behavior**
 _get_python.sh_ script obtains and installs required packages.

**Actual behavior**
 _get_python.sh_ script fails to obtain required packages due to Bad CPU type in executable error.

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
d9efce5

**Desktop/Device (please complete the following information):**
- Device: Mac
- OS: macOS
- Version: Ventura 13.0.1
- CPU: M1
- GPU: M1
- Memory: 16GB

**Additional context**
[Macbook Air M1 failed get python log.txt](https://github.com/o3de/o3de/files/10411222/Macbook.Air.M1.failed.get.python.log.txt)

**Comment by byrcolin** [comment]
We will go with major instead of critical and this does stop it from working but on a currently unsupported platform, not sure what architecture is returned to python while using rosetta, needs testing.

**Comment by byrcolin** [comment]
We don't officially support Mac or the arm version, so we will keep this because we think it is a good first issue for someone to document the rosetta for x86.
