### ISSUE TITLE
Crash in OpenImageIO from Image Gradient Component when creating image on debug

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#14065]
**Describe the bug**
When creating an image via the Image Gradient Component on latest development built in debug, the Editor crashes.
![image](https://user-images.githubusercontent.com/82231674/212469585-cb48a90f-1820-429e-b57a-643c3e092bf6.png)

**Steps to reproduce**
1. Start a debug version of the Editor and open a level
2. Add an Image Gradient Component to an entity
3. Press the button to create a new image
4. Click Ok on the dialog for the image size (default values)

**Expected behavior**
The image is created

**Actual behavior**
The Editor crashes

**Found in Branch**
Latest development

Windows 10 built on debug. Profile build works as expected.

**Comment by AMZN-daimini** [comment]
@mbalfour-amzn FYI :)

**Comment by mbalfour-amzn** [comment]
Just for clarification, the crash in the picture above is in lines 219 / 220, not line 226. :) The callstack looks like this:
```
 	KernelBase.dll!00007ff94fd9cd29()	Unknown
 	vcruntime140.dll!00007ff93f7c64c0()	Unknown
 	OpenImageIO.dll!00007ff801b8e0cf()	Unknown
 	OpenImageIO.dll!00007ff801ef73dd()	Unknown
 	OpenImageIO.dll!00007ff8010bea20()	Unknown
 	OpenImageIO.dll!00007ff800ffbf0b()	Unknown
 	OpenImageIO.dll!00007ff801005030()	Unknown
 	OpenImageIO.dll!00007ff8016502e8()	Unknown
 	OpenImageIO.dll!00007ff8016569b4()	Unknown
 	OpenImageIO.dll!00007ff80165719f()	Unknown
 	OpenImageIO.dll!00007ff801657384()	Unknown
 	OpenImageIO.dll!00007ff801d86fb8()	Unknown
>	GradientSignal.Editor.dll!GradientSignal::ImageCreatorUtils::WriteImage(const AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> & absoluteFileName, int imageResolutionX, int imageResolutionY, int channels, GradientSignal::OutputFormat format, const AZStd::span<unsigned char const ,-1> & pixelBuffer, bool showProgressDialog) Line 220	C++
 	GradientSignal.Editor.dll!GradientSignal::ImageCreatorUtils::PaintableImageAssetHelperBase::SaveImageInternal(AZ::IO::BasicPath<AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator>> & fullPath, AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> & relativePath, int imageResolutionX, int imageResolutionY, int channels, GradientSignal::OutputFormat format, AZStd::span<unsigned char const ,-1> pixelBuffer) Line 567	C++
 	GradientSignal.Editor.dll!GradientSignal::ImageCreatorUtils::PaintableImageAssetHelperBase::CreateNewImage() Line 524	C++
...
```

I suspect that there's a problem with the way we've built the debug version of the OpenImageIO dll.

**Comment by mbalfour-amzn** [comment]
Looking closer, I believe the issue is with the FindOpenImageIO.cmake file. It isn't correctly redirecting the debug builds of O3DE to use "OpenImageIO_d.dll", as can be seen in the callstack above.

**Comment by mbalfour-amzn** [comment]
Just a quick note for anyone who works on this - I tried a quick test to change FindOpenImageIO.cmake to always load the debug dlls to see if that would fix the crash, and on startup the Editor it immediately unloads the debug dlls after loading them and fails to finish starting up, so there might be a bit more required to fix this than just fixing the cmake file. :(

**Comment by lawsonamzn** [comment]
Somehow this logic in the windows is failing, but its probably because of DEBUG vs debug vs Debug or something
```
# windows has Debug libraries available.
if (${CMAKE_SYSTEM_NAME} STREQUAL Windows)
    set(_OCIO_DEBUG_POSTFIX "")
    if ("${CMAKE_BUILD_TYPE}" STREQUAL Debug)
        set(_OCIO_DEBUG_POSTFIX "d")
        set(OpenColorIO_SHARED_LIB_DEBUG ${OpenColorIO_BIN_DIR}/${CMAKE_SHARED_LIBRARY_PREFIX}OpenColorIO${_OCIO_DEBUG_POSTFIX}_2_1${CMAKE_SHARED_LIBRARY_SUFFIX})

        set_target_properties(OpenColorIO::OpenColorIO PROPERTIES
            IMPORTED_LOCATION_DEBUG ${OpenColorIO_SHARED_LIB_DEBUG}
            IMPORTED_IMPLIB_DEBUG ${OpenColorIO_LIB_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}OpenColorIO${_OCIO_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
        )
    endif()

    set_target_properties(OpenColorIO::OpenColorIO PROPERTIES
        IMPORTED_IMPLIB ${OpenColorIO_LIB_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}OpenColorIO${CMAKE_STATIC_LIBRARY_SUFFIX}
    )
endif()

```

**Comment by lawsonamzn** [comment]
Yeah none of that is right.  You can't use ```if ("${CMAKE_BUILD_TYPE}" STREQUAL Debug)``` for a configure script.

**Comment by lawsonamzn** [comment]
Using a proper package of this that loads debug when in debug seems to avoid the issue.
I'll prepare a new package.
