### ISSUE TITLE
Material Editor: Crashes when editing the second material when the material editor is opened.

### ISSUE THREAD

**Issue by amzn-rhhong** [o3de/o3de#14066]
**Describe the bug**
Crashes when editing the second material when the material editor is opened.

**Assets required**
[Test_character.zip](https://github.com/o3de/o3de/files/10419365/Test_character.zip)

**Steps to reproduce**
1. Open the o3de editor
2. Drag an fbx, add actor, add material component
3. Generate a material, open with material editor
4. leave the material editor open, go back to o3de main editor
5. Generate another material (on the same actor), click open with material editor again.
6. Editor crashes.

**Expected behavior**
Editor not crash, can still editor the second material

**Actual behavior**
Editor crash

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/69218254/212520550-98f82dc4-db28-4f0b-8ee1-42362e587779.png)

https://user-images.githubusercontent.com/69218254/212524897-0ef08171-76f9-4aa7-bde5-fa15cf8b7ebe.mp4

**Found in Branch**
Main

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Please provide the SHA/hash that identifies the latest commit from the o3de/o3de repository if the issue is reproducible in the development or other official branches. 
You can get the commit ID by running the `git rev-parse HEAD` command on your current branch.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Monterey, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by gadams3** [comment]
@amzn-rhhong I'm unable to reproduce this issue using the asset you provided or other models in the automated testing project. I have tested in combination with the mesh and actor components. I have generated source materials for the entire model as well as assigned other arbitrary materials from the project. I'm able to open multiple materials in the material editor without issue. I am also able to enable automatic saving in the material editor and make changes to multiple materials that are reflected in the main editor. This was just out as a stress test for working with multiple materials. If this issue reoccurs, please reopen the issue and attach the materialeditor.log file. It's possible that something with the renderer, thumbnails, or any other active gem could have caused the crash but I will need the log to determine that.
