### ISSUE TITLE
Unable to run large number of render-to-texture pipelines concurrently.

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#14080]
**Describe the bug**
I have a problem with creating multiple render-to-texture pipelines. 
For more than 2 of those pipelines O3DE crashes. 
The bug persists in o3de_extras/Gems/ROS2. I've decided to prepare a simple project where such a crash exists:
https://github.com/michalpelka/test-atom-multicam .

**Assets required**
https://github.com/michalpelka/test-atom-multicam

**Steps to reproduce**
1. Build project `test-atom-multicam`
2. Open `SampleLevel.prefab`
3. Activate  component called 'CameraTestComponent' for 'Camera3'
4. Start game mode
5. Experience a crash

**Expected behavior**
For such a simple scene, we should be able to run at least a dozen of pipelines. It should not crash.
If the number of camera pipelines is too great, it should return failed outcome.

**Actual behavior**
The O3DE Editor crashes, without assertion. Please find the stack from the debugger (22.10):
```
<unknown> 0x00007fffdedcc779
<unknown> 0x00007fffdedce93a
AZ::Vulkan::DescriptorSet::UpdateNativeDescriptorSet DescriptorSet.cpp:394
AZ::Vulkan::DescriptorSet::CommitUpdates DescriptorSet.cpp:38
AZ::Vulkan::ShaderResourceGroupPool::CompileGroupInternal ShaderResourceGroupPool.cpp:182
AZ::RHI::ShaderResourceGroupPool::CompileGroup ShaderResourceGroupPool.cpp:351
AZ::RHI::ShaderResourceGroupPool::CompileGroupsForInterval ShaderResourceGroupPool.cpp:373
<lambda#2>::operator()() const FrameScheduler.cpp:306
AZ::Internal::TaskTypeEraser::Invoker(<lambda#2> *) Task.h:84
AZ::Internal::Task::Invoke Task.inl:66
AZ::Internal::TaskWorker::Run TaskExecutor.cpp:264
<lambda#1>::operator()() const TaskExecutor.cpp:215
AZStd::Internal::INVOKE<…>(<lambda#1> &&) invoke_traits.h:208
AZStd::invoke<…>(<lambda#1> &&) invoke.h:54
AZStd::Internal::apply_impl<…>(<lambda#1> &&, std::tuple<…> &&, std::integer_sequence<…>) tuple.h:308
AZStd::apply<…>(<lambda#1> &&, std::tuple<…> &&) tuple.h:316
<lambda#1>::operator()() thread_UnixLike.h:37
AZStd::Internal::thread_info_impl::execute() thread.h:193
AZStd::Internal::thread_run_function thread_UnixLike.cpp:35
start_thread 0x00007ffff6d7eb43
clone3 0x00007ffff6e10a00
```
**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Exists in:
-  https://github.com/o3de/o3de/commit/b07240a7283bbdfccc5e05a0bcce179aa49bc01c 
-  https://github.com/o3de/o3de/commit/932a0327a58580028bb4a314b2d464dd974edaef 
-  main (22.10)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu 
 - Version 22.04
 - CPU 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
 - GPU  NVIDIA GeForce RTX 3070 Laptop GPU @ 525.60.11  
 - Memory 64 Gb
 
**Note**
I do not know if issue is caused with our way to integrate with RHI or problem in o3de.
Problem seems to be platform specific, do not exists on Windows with and without " --rhi=vulkan"

**Comment by VickyAtAZ** [comment]
@michalpelka It seems the crash happened when compile RayTracingSceneSrg. So if we disable raytracing for linux, the crash is gone.
The current workaround is to disable the raytracing for linux (if you are not using any raytracing related features, for example DiffuseProbeGrid )
\o3de\Gems\Atom\RHI\Vulkan\Code\Source\RHI\Device.cpp line 1003
            ```
//StringList::iterator itRayTracingExtension = AZStd::find(deviceExtensions.begin(), deviceExtensions.end(), VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME);
            m_features.m_rayTracing = false;//(itRayTracingExtension != deviceExtensions.end());
```
We are continuing to investigate the issue.
