### ISSUE TITLE
[Linux] Configuring engine fails due to missing libunwind-dev package

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#14092]
**Describe the bug**
The configure command fails with error:
`cmake -B build/linux -S . -G "Ninja Multi-Config" -DLY_3RDPARTY_PATH=$HOME/o3de-packages -DLY_VERSION_ENGINE_NAME=o3de-install -DCMAKE_INSTALL_PREFIX=$HOME/o3de-install`

The following error is displayed:
```
gpc-xxx@gpc-xxx:~/DEMO_BASE/o3de$ cmake -B build/linux -S . -G "Ninja Multi-Config" -DLY_3RDPARTY_PATH=$HOME/o3de-packages -DLY_VERSION_ENGINE_NAME=o3de-install -DCMAKE_INSTALL_PREFIX=$HOME/o3de-install
-- Checking for module 'libunwind'
--   No package 'libunwind' found
CMake Error at cmake/Platform/Linux/libunwind_linux.cmake:15 (message):
  Compiling on linux requires the unwind development libraries and headers as
  well as pkg-config.  Try using your package manager to install the
  libunwind-dev libraries.
Call Stack (most recent call first):
  cmake/Platform/Linux/PAL_linux.cmake:56 (include)
  cmake/PAL.cmake:426 (include)
  CMakeLists.txt:37 (include)


-- Configuring incomplete, errors occurred!
See also "/home/gpc-460/DEMO_BASE/o3de/build/linux/CMakeFiles/CMakeOutput.log".
```
Note that this issue occurs when building both - Source, and  Pre-Built SDK engines.

Workaround is available for this issue, which includes installing required package:
`sudo apt-get update -y`
`sudo apt-get install -y libunwind-dev`

This issue is related to the - https://github.com/o3de/o3de/commit/b6eed4b4b66f4b18ed0c56c6a0cb751ae7f55891 commit.

**Steps to reproduce**
1. Clone o3de repository and follow the [Building for Linux](https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/) documentation.

**Expected behavior**
The configure is complete without errors.

**Actual behavior**
Configuring fails due to the missing package.

**Screenshots**
![Creating_Build_Project_Fail](https://user-images.githubusercontent.com/86951967/213126286-063cf2b0-dc24-4868-81e2-8ed53573ca17.png)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
2bd2ade

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.5 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by lawsonamzn** [comment]
The minimum requirements/getting started for linux page was updated to mention that you need to install the libunwind-dev package.  The build nodes were also updated. 
When this fails, the error message tells you to install the libunwind-dev package.

 Is there anything more that needs to be done here?

**Comment by LB-ArturZieba** [comment]
Verified that libunwind-dev is mentioned in https://www.o3de.org/docs/welcome-guide/requirements/#additional-library-dependencies, that Pre-built SDK engine can be built, and that Default Template project can be successfully built and launched on the Development (47b9ab3). Closing the issue.
