### ISSUE TITLE
Build Failure: GradientSignal.Editor.Tests.main fails in test_debug on Windows in daily run

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#14095]
**Describe the bug**
GradientSignal.Editor.Tests.main fails in test_debug on Windows. 

**Failed Jenkins Job Information:**
[The name of the job that failed, job build number, and code snippit of the failure.](https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/228/pipeline/2583)

**Attachments**
[log(2).txt](https://github.com/o3de/o3de/files/10449003/log.2.txt)

**Additional context**
From the logs, I don't see a specific test failure. Perhaps this is a timeout or lock?

**Comment by cgalvan** [comment]
This was an OIIO debug issue that was fixed with this PR: https://github.com/o3de/o3de/pull/14242

Verified here: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/241/pipeline/2368
