### ISSUE TITLE
Material Canvas crashes after adding Standard PBR or Base PBR nodes to graph

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14121]
**Describe the bug**
Adding the Standard PBR or Base PBR nodes to the Material Graph Document freezes the Canvas, which afterwards leads to the crash upon any interaction within the Material Canvas.

After this issue occurs, the untitled.material file is being saved on the disk and searching it (i.e. in Asset Browser) causes the Editor to crash.

**Steps to reproduce**
1. Launch the Material Canvas.
2. Add a Standard or Base PBR Node.
3. Click anywhere on the Canvas repeatedly.

**Expected behavior**
All of the nodes are added correctly without causing any stability issues.

**Actual behavior**
The Material Canvas crashes.

**Screenshots/Video**
[2023-01-19 12-11-40.mp4
](https://user-images.githubusercontent.com/110163473/213465990-ab727efe-96a1-4158-8b83-55a9d38619c2.mp4)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c601866

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11 22H2
 - CPU: I7-11700f
 - GPU: Geforce RTX3070 MSI
 - Memory: 32GB
 
 **Additional context**
[MaterialCanvas.log](https://github.com/o3de/o3de/files/10457642/MaterialCanvas.log)

**Comment by LB-JakubSkoczylas** [comment]
Hi, I was able to add both PBR nodes and no crash occurred on Development (ecf542f). After adding the PBR node, my PC froze for a few seconds. Without clicking anything, the AP processed the new assets and I was able to work with the Material Canvas. However after adding Base PBR node to the canvas that already had the Standard PBR, a new assets were created and failed in the Asset Processor. I am not sure if these fails are somehow connected to the freeze and crash, so would you like me to open a new ticket for this issue?

**My Device:**
Device: PC
OS: Linux
Version Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU Nvidia Geforce RTX 2060 SUPER
Memory 16GB

Failed asset logs: 
[untitled_6_DepthPass_WithPS.shader-295053385-36668.log](https://github.com/o3de/o3de/files/10466474/untitled_6_DepthPass_WithPS.shader-295053385-36668.log)
[untitled_6_Shadowmap_WithPS.shader-3254568574-36652.log](https://github.com/o3de/o3de/files/10466477/untitled_6_Shadowmap_WithPS.shader-3254568574-36652.log)


https://user-images.githubusercontent.com/86952591/213698217-25162cde-ed73-4ed9-8db2-ad9d8207acc0.mp4

**Comment by LB-KacperMetelski** [comment]
Issue doesn't seem to occur as of commit 563293d; the freeze after adding the PBRs doesn't cause a severe freeze.
