### ISSUE TITLE
Display version change breaks PopcornFX

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#14123]
**Describe the bug**
The PopcornFX gem can no longer compile successfully due to the recent change to o3de version strings.

**Steps to reproduce**
1. Try to build multiplayersample

**Expected behavior**
It builds successfully.

**Actual behavior**
```
CMake Error at D:/github/o3de/cmake/O3DEJson.cmake:54 (message):
  Error reading field at key O3DEVersion in file "D:/github/o3de/engine.json"
  : member 'O3DEVersion' not found
Call Stack (most recent call first):
  D:/github/o3de-multiplayersample-assets/Gems/O3DEPopcornFXPlugin/CMakeLists.txt:23 (o3de_read_json_key)
```

**Found in Branch**
development

**Comment by lmbr-pip** [comment]
Prob need to cut issue/PR to https://github.com/PopcornFX/O3DEPopcornFXPlugin

**Comment by AMZN-alexpete** [comment]
I've restored the old versions and PopcornFX has merged the update that should enable the support for the new fields moving forward see https://github.com/PopcornFX/O3DEPopcornFXPlugin/pull/31
