### ISSUE TITLE
New Action Manager doesn't support "Esc" to exit entity picking while in paintbrush mode

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#14146]
**Describe the bug**
When using the paintbrush component mode, if the new Action Manager has been enabled, "Esc" doesn't work to exit entity picking.

**Steps to reproduce**
1. In user/registry/editorpreferences.setreg, enable the new Action Manager:
```
    "O3DE": {
        "ActionManager": {
            "EnableNewActionManager": true
	},
```
2. Open the Editor with a new or existing level.
3. Create a new entity with an Image Gradient, a Gradient Transform Modifier, and a Box Shape.
4. On the Image Gradient, select any available existing image for the Image Asset.
5. On the Image Gradient, press the Edit button to start the paintbrush component mode.
6. On the Image Gradient, press the Entity Picker icon next to the "Pin Preview to Entity" field.
7. Press Esc to exit entity picking.
8. Press Esc to exit component mode.

**Expected behavior**
The first "Esc" press exits entity picking mode and returns to painting mode in the viewport. The second "Esc" exits the component mode entirely.

**Actual behavior**
Pressing "Esc" does nothing.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
31b8100ecaebaa9ad4f65e67e403afdd458afb17

**Additional context**
This works correctly when the new Action Manager is not enabled.

**Comment by mbalfour-amzn** [comment]
This is related to #13467 though even after that is fixed, this bug should still remain, because there's currently no code in PaintBrushManipulator::RegisterActions() to override the Esc key while picking entities. In contrast, in PaintBrushManipulator::PopulateActionsImpl() there is some logic at the top to override it while in entity-picking mode. The logic doesn't transfer over as-is because PopulateActionsImpl() is called during component mode and can refresh the actions, but RegisterActions() doesn't have an equivalent concept of refreshing actions.

**Comment by hultonha** [comment]
Assigning to @AMZN-daimini to take a look at. Let me know if you have any questions. Thanks!
