### ISSUE TITLE
Feature Request: Provide API to set network control of Anim Graph rather than as side effect of snapshot creation

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#14142]
**Is your feature request related to a problem? Please describe.**
When Anim graph properties require updates for networked control, the code patch currently requires create a snapshot to induce network control. Creating a network authoritative snapshot causes EMFX to not clobber entity transforms during its tick (see code below)

However creating a snapshot to induce network control is heavyweight and leads to unexpected behavior at times:

![image (1)](https://user-images.githubusercontent.com/61438964/213629887-059f7d79-70e6-474b-91fb-47864c5a4cfe.png)

Snapshot is basically just a collection of animation data. Once you turn it on, it will store the necessary data per update. There should be a separate flag to say this is network controlled or not.

**Describe the solution you'd like**
Flag or path to setting this control is exposed via request or API rather than as a side effect of Snapshot. Networking doesn't need snapshot behaviour, we just need a path to force the graph into network mode so that we have control over entity transforms.

**Describe alternatives you've considered**
None

**Additional context**

See https://github.com/o3de/o3de-multiplayersample/blob/development/Gem/Code/Source/Components/NetworkAnimationComponent.cpp

`NetworkAnimationComponent` in o3de-multiplayersample uses snapshots as follows to induce network control:

```
void NetworkAnimationComponent::OnPreRender(float deltaTime)
    {
        ...

        if (m_networkRequests->HasSnapshot() == false)
        {
            constexpr bool isAuthoritative = true;
            m_networkRequests->CreateSnapshot(isAuthoritative);
        }
 ```  
      
  Then we can sync the parameters
        
        
 ```
 void NetworkAnimationComponent::OnAnimGraphInstanceCreated([[maybe_unused]] EMotionFX::AnimGraphInstance* animGraphInstance)
    {
        // We don't need any more notifications
        EMotionFX::Integration::AnimGraphComponentNotificationBus::Handler::BusDisconnect();

        // Disable automatic EMotionFX updates of transform, network has control
        if (m_networkRequests != nullptr)
        {
            constexpr bool isAuthoritative = true;
            m_networkRequests->CreateSnapshot(isAuthoritative);
        }
    }
```

```
void AnimGraphComponent::CreateSnapshot(bool isAuthoritative)
        {
            if (m_animGraphInstance)
            {
                m_animGraphInstance->CreateSnapshot(isAuthoritative);
                m_animGraphInstance->OnNetworkConnected();

                // This will stop the MCore Job schedule update the actor instance and anim graph for authoritative entity.
                // After doing so, we will have to update this actor manually in the networking update.
                m_animGraphInstance->GetActorInstance()->SetIsEnabled(!isAuthoritative);
            }
            else
            {
                AZ_Error("EMotionFX", false, "Cannot create snapshot as anim graph instance has not been created yet. "
                    "Please make sure you selected an anim graph in the anim graph component.");
            }
        }
```

**Comment by amzn-rhhong** [comment]
void NetworkAnimationComponent::OnPreRender(float deltaTime)
    {
        ...

        if (m_networkRequests->HasSnapshot() == false)
        {
            constexpr bool isAuthoritative = true;
            m_networkRequests->CreateSnapshot(isAuthoritative);
        }
....

I think the real issue is when the network component is creating the snapshot before anim graph instance is created.

**Comment by lmbr-pip** [comment]
Feature delivered in https://github.com/o3de/o3de/pull/14150

**Comment by lgleim** [comment]
@lmbr-pip Could you please clarify if #14150 closes this issue?

**Comment by amzn-rhhong** [comment]
https://github.com/o3de/o3de/pull/14150 should close this.
