### ISSUE TITLE
Material Editor: Skin Material Slider Out of Range

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#14159]
The skin material > Detail layer > Factor slide allows users to slide to 2.0, but the max value is only 1.0

**Steps to reproduce**
1. Open Material Editor
2. Create a new Skin Material
3. Enable Detail Layer 
4. Pull the "Factor" slider to the far right

**Expected behavior**
Slider stops at 1.0

**Actual behavior**
Slider goes to 2.0, but max value is clamped to 1

![image](https://user-images.githubusercontent.com/32776221/213904207-70c6307c-f238-4261-bbaa-7f832c515643.png)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
512bc8fef46e5dfcc2d4df6e9056643f637cb0ab

**Comment by gadams3** [comment]
Looking at the detail map properties config file, I do not think this is a bug. The slider has a soft range of common values [0,2] but the text field is uncapped. I would probably ask someone like @HogJonny-AMZN if the range seems reasonable. If so, we can reopen and change them.

\o3de\Gems\Atom\Feature\Common\Assets\Materials\Types\MaterialInputs\DetailMapsPropertyGroup.json

**Comment by AMZN-Gene** [comment]
Thanks for investigating. Since the  slider and text field contain 2 different values which one is correct?

**Comment by AMZN-Gene** [comment]
Others are reporting this same issue. #14624

**Comment by gadams3** [comment]
@o3de/sig-ui-ux @AMZN-Gene This has come up before in other situations. The text/slider controls support an absolute minimum/maximum that the value can never exceed as well as a soft minimum/maximum, which is like sweet spot for a slider. The slider needs finite limits to be useful. The text edit box could allow the user to enter any other value. To resolve the confusion, we could get rid of the slider or change the slider to 0 to 1 and unbound the edit box. We just don't want to prevent someone from being able to enter a value outside of that 0 to 1 range.

**Comment by gadams3** [comment]
After reviewing this again, the correct answer is probably to rename it from factor to scale or strength. It is a multiplier that does not need to be constrained between zero and one. There is no upper limit.
