### ISSUE TITLE
Project Manager crashes after attempting to build project on installer build

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de#14164]
**Describe the bug**
Building a project in Project Manager on installer build results in a crash. This was reproduced on minimal and default template and on all gems project. The issue was reproduced on Windows and Linux.
It should be noted that O3de default folder created during the installation was C:\O3DE\0.0.0 (changing it to 0.0.0.0 - as it was the default path until recently - did not fix the issue).
This issue does not occur on the Github builds.
It may be related to the following commit - 8b5391e.

**Steps to reproduce**
1. Download the latest installer build (https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe)
2. Install the O3de engine.
3. Launch the Project Manager from desktop shortcut.
4. Create a project from default template and build it.

**Expected behavior**
Project builds without any issues.

**Actual behavior**
The Project Manager crashes.

**Found in Branch**
Development installer

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
(83cf889)

• Device: PC
• OS: Ubuntu
• Version: Ubuntu 20.04.4 LTS
• CPU Intel Core i7-9700K
• GPU Nvidia GeForce RTX 2070
• Memory 16GB

**Additional context**
[CMakeError.log](https://github.com/o3de/o3de/files/10478112/CMakeError.log)
[CMakeOutput.log](https://github.com/o3de/o3de/files/10478113/CMakeOutput.log)
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/10478114/CMakeProjectBuildError.log)

**Comment by AMZN-alexpete** [comment]
I believe this is blocked in #14177

**Comment by AMZN-alexpete** [comment]
@LB-JaroslawGaweda This issue should be resolved by https://github.com/o3de/o3de/pull/14172 could you please verify? Our nightly installer tests create a project and build it from the installer and have been passing since the fix was introduced.  Thanks!

**Comment by LB-JaroslawGaweda** [comment]
Issue verified as fixed on build (0a66664).
