### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by git2013vb** [o3de/o3de#14162]
**Describe the bug**
I have an error when I try to install it

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
I downloaded the .deb version and I tried to install it.

**Expected behavior**
Installing without errors

**Actual behavior**
I have this error:
```
(base) vale@debianace:~/Downloads/apps$ sudo apt install ./o3de_2210_0.deb 
[sudo] password for vale: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'o3de' instead of './o3de_2210_0.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 o3de : Depends: clang-12 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Please provide the SHA/hash that identifies the latest commit from the o3de/o3de repository if the issue is reproducible in the development or other official branches. 
You can get the commit ID by running the `git rev-parse HEAD` command on your current branch.

**Desktop/Device (please complete the following information):**

 - OS: Debian 
 - Version 11
 - Memory 16GB

**Additional context**

**Comment by byrcolin** [comment]
This needs to be investigated.

**Comment by byrcolin** [comment]
closed out of date
