### ISSUE TITLE
Editor crash because of lack of right drivers

### ISSUE THREAD

**Issue by danielemorra98** [o3de/o3de#14185]
**Describe the bug**
My PC has the `nvidia-driver-515` installed and when I launch the Editor  it crashes anomalously without providing any clues.

**Expected behavior**
The engine should do some sanity checks and throw helpful warnings concerning the lack of compatibility with the current driver.

**Actual behavior**
The engine starts up fine, but it crashes after having selected the Level because of Segmentation Fault.

**Solution found**
I installed the `nvidia-driver-520` and I solved the issue.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Branch: development
Commit: 9480fb79d8e5cf10865c4f7d71d871eb9b26a655

**Desktop/Device (please complete the following information):**
 - Device: Workstation
 - OS: Linux
 - Version: Focal - 20.04
 - CPU: 11th Gen Intel Core i9-11900K
 - GPU: NVIDIA RTX A5000
 - Memory: 64 Gb

**Additional context**
The issue is very similar to [this one (11849)](https://github.com/o3de/o3de/issues/11849).

**Comment by galibzon** [comment]
@danielemorra98 , We now have validation layer debugging available on Linux. It provides more information whenever there are crashes or anomalies. Get the latest version of the engine and start the Editor, for example, as:
```
./Editor -rhi-device-validation="enable"
```
