### ISSUE TITLE
[iOS] Asset Processor fails to process numerous iOS assets

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#14187]
**Describe the bug**
Enabling iOS assets and running the Asset Processor results in huge number of iOS assets fail processing for AutomatedTesting project. It has also been confirmed on a Linux machine after enabling the iOS assets for a new project using default template that those fail as well. The affected file types are: .shadervariantlist, .material, .materialtype, .fbx, .shader.

The following errors are logged for the specific Job Keys:

Shader Variant:
`| ERROR | ShaderVariantAssetBuilder: asset [/Users/macpro13/o3de/AutomatedTesting/Cache/ios] from shader source /Users/macpro13/o3de/Gems/LyShine/Assets/LyShine/Shaders/LyShineUI.shader and subId 6 doesn't exist from AssetBuilder`

Material Builder:
`| ERROR | AssetUtils: Could not load MaterialTypeAsset [Source='@gemroot:Atom_Feature_Common@/Assets/Materials/Types/EnhancedPBR.materialtype' Cache='<unknown>' AssetID={4698C373-9546-5142-B78B-EFF0396C5314}:0] from AssetBuilder`

Shader Asset:
`| ERROR | AZSLc: Invalid namespace 'mt,vk' from AssetBuilder`
`| ERROR | ShaderPlatformInterface: AZSLc has exited with error code 1 from AssetBuilder`

Scene Compilation:
`| ERROR | Error: Failure during conversion and exporting. from AssetBuilder`

Please refer to the attached video for more information.

**Prerequisites**

- Built the AssetProcessor for macOS platform with AutomatedTesting set as active project.
- Modified the AssetProcessorPlatformConfig.setreg file in the o3de/Registry directory to enable the iOS assets.

**Steps to reproduce**
1. Launch the Asset Processor.
2. Wait for the assets to finish processing.

**Expected behavior**
All assets complete processing without errors.

**Actual behavior**
Huge number of iOS assets fail processing.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/214295749-2d88e33a-1820-4eba-ad67-e91f34d895a7.mov

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[681d577](https://github.com/o3de/o3de/commit/681d577efaef9cc645bf83e3e574296b3b797636)

**Desktop/Device**
- Device: MacBook Pro
- OS: macOS
- Version: Big Sur 11.3.1
- CPU: Intel Core i5 2.0GHz Quad-Core
- GPU: Intel Iris Plus Graphics 1536 MB
- Memory: 16GB

**Comment by lmbr-pip** [comment]
I would not expect iOS asset building to work outside of building on Mac (and potentially windows) as its not a typical path to process these assets and would assume not previously tested.

Shaders have to be built on macOS I believe so would expect shaders and materials that depend on them to not be buildable.

**Comment by LB-KacperKapusta** [comment]
@lmbr-pip Please note that the issue originally occurs on macOS. Enabling the iOS assets on Linux was an additional check.
