### ISSUE TITLE
Destruction: Blast chunks .fbx assets fail to be processed by the Asset Processor on Blast enabled Development build due to the “python: No EBus connection detected for event 'OnPrepareForExport'.” error

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#14209]
**Describe the bug**
When latest Development branch build has Blast gem re-enabled _pab_box_2_chunks.fbx_, _box_2_chunks.fbx_, _cinder_wall_complex.fbx_ scene compilation assets are processed by the Asset Processor with the following error:

`python: No EBus connection detected for event 'OnPrepareForExport'. Make sure to call to connect() on the ScriptBuildingNotificationBus bus, first.`

It was also observed that the same error shows in the console when any of the above assets is tried to be open with **FBX Settings** tool in the Editor.

As a result of the above  assets are not present in the Asset picker of **Blast Family Mesh Data** component and can not be picked.

In order to generate a working Blast entities a workaround of using **Blast Family Mesh Data** _show mesh assets_ option and adding meshes manually has to be used.

The issue occurs in default AutomatedTesting project and any project that has the above assets migrated.

For further information please refer to the attached screenshot and Asset Processor logs.

**Prerequisites**

* **Blast** and **AzQtComponentsForPython** gems were obtained from cloned https://github.com/o3de/o3de-extras/tree/blast-experimental repository.
* The o3de Development branch build with the above gems enabled was configured with **-DAZ_USE_PHYSX5=OFF** argument and built.
* Destruction assets from cloned _o3de-extras\Gems\Blast\AutomatedTesting\Assets\Destruction_ directory were copied into
an active o3de project directory.

**Steps to reproduce**
1. Launch the Editor and wait until Asset Processor finishes processing all assets.
2. Create a new level.
3. Create a new entity.
4. Add **Blast Family** and **Blast Family Mesh Data** components to it.
5. Provide the **Blast Family** component with the _cinder_wall_complex.blast_ asset.
6. Try to pick any asset for **Blast Family Mesh Data** component with its asset picker window.
7. Open the Asset Browser and try to open _cinder_wall_complex.fbx_ asset in **Fbx Settings** tool.

**Expected behavior**
Blast  .fbx assets are successfully processed by the Asset Processor and are able to be picked for **Blast Family Mesh Data** component and opened in **Fbx Settings** tool.

**Actual behavior**
Blast .fbx assets process through the Asset Processor with error and unable to be detected and picked for **Blast Family Mesh Data** component.

**Screenshots/Video**
![No EBus connection detected for event AP error destruction chunks](https://user-images.githubusercontent.com/86953456/214550582-5732d546-0d36-4e13-98bc-22328120e9a6.png)

**Found in Branch**
Development

**Commit ID from** [o3de/o3de](https://github.com/o3de/o3de) **Repository**
681d577

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 9 3900X
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[cinder_wall_complex.fbx-380023773-16489.log](https://github.com/o3de/o3de/files/10498748/cinder_wall_complex.fbx-380023773-16489.log)
[box_2_chunks.fbx-982310958-16485.log](https://github.com/o3de/o3de/files/10498749/box_2_chunks.fbx-982310958-16485.log)
[pab_box_2_chunks.fbx-150828949-16503.log](https://github.com/o3de/o3de/files/10498750/pab_box_2_chunks.fbx-150828949-16503.log)

**Comment by lmbr-pip** [comment]
As Blast asset processing has not been recently tested some of the AP ebus events mav have changed and the Blast processor will need some updates. Please reach out to SIG/content for guidance.

**Comment by moraaar** [comment]
This bug is similar to https://github.com/o3de/o3de/issues/13362 which seem to have regressed.
Tagging @AMZN-stankowi since he appears as assignee in that bug.

**Comment by lgleim** [comment]
Discussed in today's SIG Simulation issue triage. We will await assessment by @o3de/sig-content and revisit this issue as appropriate.

**Comment by lgleim** [comment]
Revisited today in sig simulation triage. Removing sig simulation label until sig content had a chance to triage. Feel free to re-add sig simulation if appropriate.

**Comment by amzn-mike** [comment]
I've posted a fix for this, it's the same bug as #13362

**Comment by hultonha** [comment]
Oh sorry I see this is the PR you meant - https://github.com/o3de/o3de-extras/pull/228
