### ISSUE TITLE
Linux: Project startup splash screen does not display jobs remaining

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#14223]
**Describe the bug**
On Linux, the splash screen that shows up on project launch does not display number of jobs remaining to be processed via the Project Manager. It should be noted that on Windows that counter is present.

**Steps to reproduce**
1. Create a new project and build it (or use a project with Cache folder not present, so that Asset Processor will take a while to process everything).
2. Launch the Editor and observe the splash screen.

**Expected behavior**
Remaining jobs count is displayed.

**Actual behavior**
Remaining jobs count is not displayed.

**Screenshots**
Linux:
![LinuxSplashScreenJobsCount](https://user-images.githubusercontent.com/86952082/214845532-8c2feb94-1b8f-45f2-8ce0-881875430123.png)

Windows:
![WindowsSplashScreenJobsCount](https://user-images.githubusercontent.com/86952082/214845558-52d3277e-112c-4444-aa0a-c7002e47757e.png)

**Found in Branch**
Development (57a500f)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
57a500f3eaf2b0d8450003dd04016f5147e940a7

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by spham-amzn** [comment]
Resolved with https://github.com/o3de/o3de/pull/16661
