### ISSUE TITLE
Bug Report: Material Canvas Naming Crash

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#14243]
**Describe the bug**
Material Canvas will crash on save/compile if two namable nodes have the same name.

**Steps to reproduce**
1. Open Material Canvas, create a new canvas, and add in any input node that has a naming area (Texture Sampler, Material Inputs)
2. Use the same name on both of them and make sure they both hook up into the output node.
3. Compile the graph and the Material Canvas should crash.

**Expected behavior**
Having the same naming should either not crash and throw an error that cancels the compile, or make it so if you input the same naming twice it wont let you complete the naming on the second node until changed.

**Actual behavior**
Having the same naming on two or more nodes results in the Material Canvas crashing on save/compile.

**Screenshots/Video**
N/A

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
fc57a9a46f3b869609874887cc0a4bde2bd01b73

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Additional context**
N/A

**Comment by gadams3** [comment]
Addresses issues when inputs have empty spaces or numeric characters
https://github.com/o3de/o3de/pull/14206

Addresses issues when inputs have duplicate names
https://github.com/o3de/o3de/pull/14251
