### ISSUE TITLE
Launching Nightly Development Build o3de_installer.exe causes Microsoft Defender SmartScreen warning to popup

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#14256]
**Describe the bug**
Launching o3de_installer.exe downloaded from the https://o3debinaries.org/download/windows.html Nightly Development Build  causes Microsoft Defender SmartScreen warning to popup. 

This could be related to https://github.com/o3de/o3de/issues/11067 as well as https://github.com/o3de/o3de/pull/14183.

**Steps to reproduce**
1. Go to https://o3debinaries.org/download/windows.html.
2. Download the o3de_installer.exe by clicking the hyperlink at the bottom of the screen (`Try out features and fixes currently in development by downloading the [Nightly Development Build here](https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe).`)
3. Launch the o3de_installer.exe.

**Expected behavior**
Installer window opens up.

**Actual behavior**
Microsoft Defender SmartScreen warning pops up.

**Video**

https://user-images.githubusercontent.com/86952082/215108687-5a38f7d4-f5ba-4bc5-a980-3899d3b5f05b.mp4

**Found in Branch**
Development (0a66664)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
0a666643fd39795fbb33383764017a8ec8e1a4d7

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by lmbr-pip** [comment]
Tagged in SIG/build for visibility

**Comment by amzn-changml** [comment]
I'm unable to reproduce this with today's development build. Can you verify that this is still occurring and if so, can you screenshot the file properties > Digital Signatures tab?

**Comment by amzn-changml** [comment]
Verified that this was a order of operations issue. Can you verify that last night's build has a valid certificate?

**Comment by LB-ArturZieba** [comment]
Verified that the night build has a valid certificate and the Microsoft Defender SmartScreen does not pop up anymore when launching the executable. Closing the issue.
