### ISSUE TITLE
Linux: Project Manager occasionally crashes when building a project

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#14259]
**Describe the bug**
Using the Project Manager to build a project sometimes crashes it with average 1/3 repro rate.
This issue occurs only on Linux. Issue was observed on pre-built SDK build set up from O3DE GitHub repository.
This issue might be related to https://github.com/o3de/o3de/issues/13504, but occurs on a different system version (20.04 instead of 22.04) and O3DE setup (pre-built SDK instead of installer).

**Steps to reproduce**
1. Build the engine in pre-SDK configuration and register it.
2. Open Project Manager and create a new project.
3. Build the project using the Project Manager.
4. If the Project Manager has not crashed, build the project using the Project Manager a few more times (by selecting "Build" from the hamburger menu by the project's name).

**Expected behavior**
The Project is built successfully.

**Actual behavior**
Project Manager crashes with segmentation fault.

**Screenshots/Video**

https://user-images.githubusercontent.com/99388484/215108043-283d163e-708c-44a5-87f2-b2518f7f2556.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/0a666643fd39795fbb33383764017a8ec8e1a4d7)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/0a666643fd39795fbb33383764017a8ec8e1a4d7

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version: 20.04.4 LTS
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Additional context**
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/10519644/CMakeProjectBuildError.log)
[terminal.log](https://github.com/o3de/o3de/files/10519646/terminal.log)
Project Manager did not generate any crash logs.

**Comment by AMZN-Dk** [comment]
For triage team - 1/3 repro rate seems like this may be more of a critical issue than major. @robhaco is this something you have encountered?

**Comment by dshmz** [comment]
SIG Build checked this issue and it is a Prism issue, it should be taken by SIG/Core or SIG/Platform.

**Comment by LB-KacperMetelski** [comment]
Verified issue as fixed on build Development (7ce6550).
