### ISSUE TITLE
Find in Viewport function is described inconsistently

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14252]
**Describe the bug**
The option to find Entities in the Viewport is available in two places, yet described differently.

This issue occurs on both Linux and Windows.

**Steps to reproduce**
1. Select any Entity.
2. Select 'Find in viewport' from the context menu of the Entity.
3. Select 'Go to selected object' in the top toolbar.

**Expected behavior**
The 'Find in viewport' function is described consistently.

**Actual behavior**
Two descriptions are given to one function.

**Screenshots/Video**
https://user-images.githubusercontent.com/110163473/215033702-204dfe52-cfc0-48e7-8586-1503a37be52c.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
57a500f

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu
 - Version: 20.04.5 LTS
 - CPU: I7-11700f
 - GPU: Geforce RTX3070 MSI
 - Memory: 32GB

**Comment by AMZN-daimini** [comment]
Additionally, the same functionality can be achieved with View > Viewport > Center on Selection in the file menu.
![image](https://user-images.githubusercontent.com/82231674/215061206-d66ce8bc-4c80-4412-8f23-89a8a3dcf3df.png)

**Comment by monroegm** [comment]
@o3de/sig-ui-ux FYI we're going to be changing all the labels to be consistent

**Comment by amzn-leenguy** [comment]
This task seems straight forward @monroegm . Feel free to add a comment on your suggestion and tag us. This is a two way door decision, so I can give pre approval on what you decide on and move forward with room to provide feedback if necessary. 

Honestly though: "View Selected Object" seems fine too.

**Comment by AMZN-daimini** [comment]
Now that the Action Manager is enabled, these menu items are all labeled the same way (and using the same code under the hood!)

Entity Outliner context menu
![image](https://user-images.githubusercontent.com/82231674/229488661-6390c4cd-e1b4-4c6e-b917-a6354835bbd4.png)

View menu
![image](https://user-images.githubusercontent.com/82231674/229488708-287cc5b8-8fc5-459f-9ffc-898c3cc9cfc8.png)

(item is no longer shown as part of the top toolbar)

**Comment by LB-KacperMetelski** [comment]
Issue verified as fixed on commit c4dd0ce on branch Stabilization/2305
