### ISSUE TITLE
Material Canvas: Inconsistent value display for Constant nodes

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#14258]
**Describe the bug**
The displayed values for the Constant nodes are changed to scientific notations for values 10 or above (for Int and UInt nodes) and 10000 or above for the Float node. If the User hovers over the nodes, the values are displayed correctly.

This is only a visual issue, as the values inside the nodes are verified to work correctly for the PBR nodes.

**Steps to reproduce**
1. Go to Material Canvas.
2. Add the Float Constant, UInt Constant, Int Constant nodes
3. Set values 10 for UInt and Int nodes. Set 10000 for the Float node.

**Expected behavior**
The values are displayed correctly.

**Actual behavior**
The values are displayed as scientific notations.

**Screenshots/Video**

![Constants](https://user-images.githubusercontent.com/86952591/215109146-8e01ccb3-7c5b-470c-8db8-4985ffad8664.PNG)

**Found in Branch**
Development (0a66664)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
0a66664

**Desktop/Device:**
Desktop/Device:
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU Nvidia GeForce RTX 2060 SUPER
Memory 16GB

**Comment by gadams3** [comment]
This is pre-existing behavior from graph canvas, script canvas, landscape canvas, where the control defaults displaying 4 decimal places when it's not in focus. If it's greater than 4 decimal places and not being edited then it switches notation.

**Comment by LB-JakubSkoczylas** [comment]
@gadams3 Please note that this does not occur in Script Canvas.
![SC](https://user-images.githubusercontent.com/86952591/225287332-e1f32d45-3630-4c3a-ac29-fa97024aa613.PNG)

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed in the latest development (d6ef267).
