### ISSUE TITLE
[MacOS] Editor crashes after a few hours of constant use

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#14253]
**Describe the bug**
The Editor on mac crashes for unknown reason after a few hours of constant use. It happened twice in one day and once on the next day. Seemingly unrelated action of clicking in an empty part of a component to deselect a property closed the Editor without an option to save. Repeating the same actions after launching the Editor again did not cause the same issue. For further information please refer to the attached logs. Until this issue is resolved it is recommended to manually restart the Editor on mac every 2 hours to prevent potential data loss.

**Assets required**
Built AutomatedTesting project.

**Steps to reproduce**
1. Launch AutomatedTesting project.
2. Wait for Asset Processor to process all assets.
3. Use the editor for 3-6 hours.

**Expected behavior**
The Editor remains stable.

**Actual behavior**
The Editor crashes.

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/2bd2ade59e81a4289d81c0283c2ea4c40c26fec9

**Device :**
Device: Macbook Pro 2019
OS: macOS
Version: Big Sur 11.6.1
CPU: Intel i9
GPU: AMD Radeon Pro 5500M 4 GB
Memory: 16GB

**Additional context**
[crash_report.txt](https://github.com/o3de/o3de/files/10518026/crash_report.txt)
[Editor.log](https://github.com/o3de/o3de/files/10518027/Editor.log)
[AP_GUI.log](https://github.com/o3de/o3de/files/10518028/AP_GUI.log)

**Comment by RoddieKieley** [comment]
@LB-KacperSzczepanski while as indicated this happens on platform/macos, do we also know if it is platform specific or no? i.e. have we seen similar behaviour on either of the other platforms as of yet?

**Comment by LB-KacperSzczepanski** [comment]
@RoddieKieley This issue occurs only on MacOS. Windows and Linux does not show similar behavior.
