### ISSUE TITLE
Breadcrumbs.cpp fails to compile in Japanese-speaking countries

### ISSUE THREAD

**Issue by ShivAlley** [o3de/o3de#14286]
**Describe the bug**
https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/
the project is created with VS2022's default SHIFT-JIS (or, more precisely, with Microsoft's SJIS extension code page 932), and a warning is printed because u00a0 and u203a in Breadcrumbs.cpp cannot be encoded in SHIFT-JIS. -The /WX option is applied to Breadcrumbs.cpp to treat the warning as an error, which causes the compile error.

**Steps to reproduce**
1. Generate Project on VS2022
2. Open Project
3. Search for Breadcrumbs in Solution Explorer
4. Go to Breadcrumbs.cpp and compile with Ctrl+F7

**Expected behavior**
No warning should occur.

**Actual behavior**
C2220 error occurs.
However, since the source code alone is specified and only compiled, the intermediate generated Moc_breadcrumbs.cpp cannot be included and another error occurs.

**Found in Branch**
Development:c346c3e5df98cdeb97caa86b2e45fb57f777b9bd

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c346c3e5df98cdeb97caa86b2e45fb57f777b9bd

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Ryzen5800X
 - GPU NVidia RTX 3070
 - Memory 16GB

**Comment by ShivAlley** [comment]
If there is no problem, I will make a PR shortly because it will be solved if I enclose the line where the warning occurs with the AZ_DISABLE_WARNING macro.

**Comment by AMZN-daimini** [comment]
Hi @ShivAlley ,
Thanks for opening this issue. Yes, it would be great if you already have a fix you want to submit :) Feel free to ping me and the sig-content group in general so we can help with automated review and the submission process :)

Also note, that specific file seems to be causing a crash even in non-Japanese machines, so maybe your changes may help that effort as well: https://github.com/o3de/o3de/issues/14169

**Comment by ShivAlley** [comment]
Thanks! I made modest changes and committed. I noticed a compile error, so I will build the editor and see if I can reproduce that Issue 14169.
