### ISSUE TITLE
Actor is not displayed in Viewport after assigning Actor in Actor component

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#14291]
**Describe the bug**
After assigning an Actor asset in the Actor component, the Actor mesh is not displayed in the Viewport. This issue occurs even for entities have "Draw character" option enabled by default.

There are 3 possible workarounds for this issue:
 1. Enable "Draw skeleton".
 2. Disable "Draw character" then enable it.
 3. Enable "Draw bounds".

Note that the Actor disappears from the Viewport after performing following actions:
 - Adding any component to the entity.
 - Removing any component from the entity.
 - Exiting the Game Mode.

Please note that, while in Game Mode, the Actor is visible.

Please refer to the attached video for more information.

**Assets required**
Any Actor, e. g. Rin Actor included in Motion Matching Gem.

**Steps to reproduce**
1. Create an entity with Actor component
2. Assign Actor in Actor component.

**Expected behavior**
After assigning the Actor in Actor component its mesh is displayed in Viewport.

**Actual behavior**
After assigning the Actor in Actor component the mesh of the Actor is **not** displayed in the Viewport.

**Video**

https://user-images.githubusercontent.com/86951967/215471910-6e1b878d-dc1b-4a9f-8270-1e4bb4930fc9.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/c346c3e5df98cdeb97caa86b2e45fb57f777b9bd

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by lgleim** [comment]
@amzn-rhhong FYI, maybe you could have a look at this?

**Comment by amzn-rhhong** [comment]
fixed by https://github.com/o3de/o3de/pull/14325/

**Comment by LB-JakubSkorupka** [comment]
Verified issue as fixed on build Development (7ce6550).
