### ISSUE TITLE
[Linux] Editor executable gets stuck at "Asset Processor Working"

### ISSUE THREAD

**Issue by danielemorra98** [o3de/o3de#14309]
**Describe the bug**
When launching the Editor, it remains stuck with the "Asset Processor Working". The asset Processor window does not open. I think this could relate to the [ROS2 Gem](https://github.com/o3de/o3de-extras/tree/development/Gems/ROS2) which is registered to the project I am attempting to launch.

It never happened to me. It looks like there is some connection issue. On the terminal it shows me:
```
AssetProcessorConnection: Network connection attempt failure, Connect returned error AzSockError::eASE_ECONNREFUSED
```

In fact, if I terminate the execution by `Ctrl+C` the Editor view pops up. Anyway, when I play it crashes and it throw out the following error:

```
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  could not create subscription: rcl node's context is invalid, at /tmp/binarydeb/ros-galactic-rcl-3.1.4/src/rcl/node.c:426
```

It has sometimes happened to me since I switched working on a virtual desktop through NoMachine. When I used physically the same workstation it never happened. 
The only way to make it work again is to shut down the virtual session and start up a new one.

**Actual behavior**
Launching routine gets stuck at "Asset Processor Working". If I press Ctrl+C the engine starts up but it will crash if I run the simulation.

**Found in Branch**
o3de: branch `development` commit `57a500f3eaf2b0d8450003dd04016f5147e940a7`
o3de-extras (ROS2 Gem): branch `development` commit `6350192c054188122bc12be767f3f1c80ae6fe77`

**Desktop/Device (please complete the following information):**
 - Device: Workstation
 - OS: Linux
 - Version: Focal - 20.04
 - CPU: 11th Gen Intel Core i9-11900K
 - GPU: NVIDIA RTX A5000
 - Memory: 64 Gb

**Comment by AMZN-stankowi** [comment]
I just ran Linux Editor, it has no issues at commit: 66edf817bef0e3cdc311a812e0c5c5737bd2d7fd

This might be an issue with that specific Gem, I recommend working with the team that manages that Gem to understand why it might not be working.
