### ISSUE TITLE
Material Canvas: Align option is visible for Bookmarks

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14313]
**Describe the bug**
Bookmarks in Material Canvas cannot be aligned. However; alignment buttons (in the top left of the Material Canvas window) are highlighted when a Bookmark is selected.

This issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Open Material Canvas.
2. Add a Bookmark.
3. Attempt to align the Bookmark.

**Expected behavior**
The option to align Bookmarks isn't highlighted.

**Actual behavior**
The option to align Bookmarks is highlighted.

**Screenshots/Video**
![31 01 2023bookmarks](https://user-images.githubusercontent.com/110163473/215782220-0f45168a-b9c1-4421-bc76-a2892ed4d906.png)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
adc2f3f

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11 22H2
 - CPU: I7-11700f
 - GPU: Geforce RTX3070 MSI
 - Memory: 32GB

**Comment by gadams3** [comment]
This is consistent with the other graph tools. No filtering is done based on the type of graph item, just if there is a selection. It might be worth exploring implementing support for aligning bookmarks.

**Comment by LB-KonradJuszczak** [comment]
Confirming the issue has been closed as not planned.
