### ISSUE TITLE
[MacOS] PhysX Force Region does not work while paired with PhysX Collider

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#14388]
**Describe the bug**
An entity with PhysX Force Region and PhysX Collider components does not apply set force type to entities within the force region. 

Please note that this issue does not occur when using PhysX Force Region component with PhysX Shape Collider component. 

Also please refer to the attached videos packed in .zip files for more information. This issue might be related to https://github.com/o3de/o3de/issues/14352
 
**Steps to reproduce**
1. Create a force region entity with  PhysX Force Region,  PhysX Collider and Box Shape components.
2. Create a sphere rigid body entity with PhysX Collider, PhysX Rigid Body and Mesh components.
3. Position the sphere rigid body entity over the force region entity.
4. Enable the trigger option in PhysX Collider component of the force region entity.
5. Enter the game mode.

**Expected behavior**
The falling entity is affected by the force within set area of the force region entity.

**Actual behavior**
The falling entity passes through set area of the force region entity with no reaction.

**Video**
[Bug_Occuring_PhysXCollider_003.zip](https://github.com/o3de/o3de/files/10579559/Bug_Occuring_PhysXCollider_003.zip)
[Bug_Occuring_PhysXCollider_002.zip](https://github.com/o3de/o3de/files/10579560/Bug_Occuring_PhysXCollider_002.zip)
[Bug_Occuring_PhysXCollider_004.zip](https://github.com/o3de/o3de/files/10579561/Bug_Occuring_PhysXCollider_004.zip)
[Bug_Occuring_PhysXCollider_005.zip](https://github.com/o3de/o3de/files/10579562/Bug_Occuring_PhysXCollider_005.zip)
[Bug_Occuring_PhysXCollider_006.zip](https://github.com/o3de/o3de/files/10579563/Bug_Occuring_PhysXCollider_006.zip)
[Bug_Occuring_PhysXCollider_007.zip](https://github.com/o3de/o3de/files/10579564/Bug_Occuring_PhysXCollider_007.zip)
[Bug_Occuring_PhysXCollider_008.zip](https://github.com/o3de/o3de/files/10579566/Bug_Occuring_PhysXCollider_008.zip)
[Bug_Occuring_PhysXCollider_009.zip](https://github.com/o3de/o3de/files/10579567/Bug_Occuring_PhysXCollider_009.zip)
[Bug_Occuring_PhysXCollider_011.zip](https://github.com/o3de/o3de/files/10579568/Bug_Occuring_PhysXCollider_011.zip)
[Bug_Occuring_PhysXCollider_010.zip](https://github.com/o3de/o3de/files/10579569/Bug_Occuring_PhysXCollider_010.zip)
[Bug_Occuring_PhysXCollider_012.zip](https://github.com/o3de/o3de/files/10579570/Bug_Occuring_PhysXCollider_012.zip)
[Bug_Occuring_PhysXCollider_013.zip](https://github.com/o3de/o3de/files/10579572/Bug_Occuring_PhysXCollider_013.zip)
[Bug_Occuring_PhysXCollider_014.zip](https://github.com/o3de/o3de/files/10579574/Bug_Occuring_PhysXCollider_014.zip)
[Bug_Occuring_PhysXCollider_016.zip](https://github.com/o3de/o3de/files/10579575/Bug_Occuring_PhysXCollider_016.zip)
[Bug_Occuring_PhysXCollider_015.zip](https://github.com/o3de/o3de/files/10579576/Bug_Occuring_PhysXCollider_015.zip)
[Bug_Occuring_PhysXCollider_001.zip](https://github.com/o3de/o3de/files/10579578/Bug_Occuring_PhysXCollider_001.zip)

[Reference_PhysXShapeCollider_006.zip](https://github.com/o3de/o3de/files/10579602/Reference_PhysXShapeCollider_006.zip)
[Reference_PhysXShapeCollider_007.zip](https://github.com/o3de/o3de/files/10579605/Reference_PhysXShapeCollider_007.zip)
[Reference_PhysXShapeCollider_001.zip](https://github.com/o3de/o3de/files/10579607/Reference_PhysXShapeCollider_001.zip)
[Reference_PhysXShapeCollider_002.zip](https://github.com/o3de/o3de/files/10579608/Reference_PhysXShapeCollider_002.zip)
[Reference_PhysXShapeCollider_003.zip](https://github.com/o3de/o3de/files/10579609/Reference_PhysXShapeCollider_003.zip)
[Reference_PhysXShapeCollider_005.zip](https://github.com/o3de/o3de/files/10579610/Reference_PhysXShapeCollider_005.zip)
[Reference_PhysXShapeCollider_004.zip](https://github.com/o3de/o3de/files/10579612/Reference_PhysXShapeCollider_004.zip)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/2bd2ade59e81a4289d81c0283c2ea4c40c26fec9

**Device :**
Device: Macbook Pro 2019
OS: macOS
Version: Big Sur 11.6.1
CPU: Intel i9
GPU: AMD Radeon Pro 5500M 4 GB
Memory: 16GB

**Comment by LB-KacperSzczepanski** [comment]
This issue was only verified with PhysX5 turned on as of yet. Verification with PhysX4 will be performed.

**Comment by LB-KacperSzczepanski** [comment]
The issue occurs also with PhysX4 turned on in build Development (4f917ff).

**Comment by RoddieKieley** [comment]
Added in sig/simulation after looking at the associated #14352 and #14390 where the the associated fix that was implemented was reviewed and approved by the o3de/sig-simulation-reviewers group.

**Comment by hultonha** [comment]
Tagging @greerdv and @moraaar for visibility if this is something we think now might be resolved? Thanks!

**Comment by lgleim** [comment]
@LB-KacperSzczepanski Discussed in today's issue triage. This is hard to replicate for the dev teams as there is limited access to MacOS systems. Could you provide a PhysX Visual Debugger Trace to make the process of narrowing down the cause of this behaviour easier?

**Comment by LB-KacperSzczepanski** [comment]
According to the official PhysX Visual Debugger website (https://developer.nvidia.com/physx-visual-debugger) the PVD is only available on PC, so we are unable to provide a trace from it on MacOS. If there is another way to provide more information please let us know.

**Comment by moraaar** [comment]
The following 2 PRs that were submitted after the tested commit (https://github.com/o3de/o3de/commit/4f917ff7561db3f454be1141185c11f6d493a59a) might have fixed this issue:
- https://github.com/o3de/o3de/pull/14418
- https://github.com/o3de/o3de/pull/14462

@LB-KacperSzczepanski would you mind retesting with the latest from development branch please? Thanks!

**Comment by LB-KacperSzczepanski** [comment]
@moraaar I have tested it on commit (ebcb440) that includes both of the mentioned PRs. The issue still occurred. To test this I had to add one of PhysX Rigid Body components to the entity with a PhysX Force Region component, but once that was done the reproduction steps and the results were the same.

**Comment by moraaar** [comment]
Thanks @LB-KacperSzczepanski for confirming the issue happens with a more recent commit. Currently I don't have the bandwidth to switch to MacOS. But I'll look at this when I can (@hultonha).

**Comment by moraaar** [comment]
I tried last Friday to reproduce this, but Mac Editor currently crashes with RPI System error (https://github.com/o3de/o3de/issues/14069) so this is currently blocked until that bug is fixed.
