### ISSUE TITLE
Multiplayer Crash: SetReg File "Host"   

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#14405]
Calling "host" from inside a .setreg JSON file will crash the game.

**Assets required**
[settings.multiplayersample_serverlauncher.zip](https://github.com/o3de/o3de/files/10583280/settings.multiplayersample_serverlauncher.zip)

**Steps to reproduce**
1. Create setreg or use the one provided and call "host"

_Registry/settings.multiplayersample_serverlauncher.setreg_
```
{
    "Amazon": {
        "AzCore": {
            "Runtime": {
                "ConsoleCommands": {
                    "host": "",
                }
            }
        }
    }
}
```

3. Run ServerLauncher.exe

**Expected behavior**
Host is called and the server begins hosting

**Actual behavior**
Runtime crash due to null reference. The AZ::Interface<IMultiplayer>is null.

**Found in Branch**
development

**Comment by lmbr-pip** [comment]
@gene-walt 

Have you tried moving this to

```
 "O3DE": {
        "Autoexec": {
            "ConsoleCommands": {
                  "host"
```

ConsoleCommands should be added to the deferred queue ie https://github.com/o3de/o3de/blob/6d5a045386e20bc0d587007a65cf32f5b33baadd/Code/Framework/AzCore/AzCore/Console/Console.cpp#L612-L628

**Comment by lmbr-pip** [comment]
I missed you had a fix for this, https://github.com/o3de/o3de/pull/14408
