### ISSUE TITLE
Asset Browser: Windows Explorer URLs/paths do not work in the Asset Browser

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#14431]
**Describe the bug**
Windows Explorer URLs/paths do not work in the Asset Browser. Per the feature request outlined in https://github.com/o3de/o3de/issues/12854, users should be able to copy/paste an Explorer URL into the AB to jump directly to a specific directory.

**Steps to reproduce**
1. Launch the Editor and enable WIP Asset Browser features via the Console:
```
ed_useWIPAssetBrowserDesign true
```
2. Open the Asset Browser.
3. In Windows Explorer, copy/paste the path to AutomatedTesting/Assets, (e.g. D:\GitHub\o3de\AutomatedTesting\Assets)
4. Paste the copied path into the Asset Browser URL/breadcrumbs bar.

**Expected behavior**
The pasted directory is jumped to in the AB.

**Actual behavior**
The pasted directory is cleared out and the previously opened directory replaces the pasted content.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
1fdc3d4c1c2bbc38b729733c1df53bb8e15cb231

**Additional context**
1. This also occurs in reverse. Copying from the Asset Browser URL bar doesn't append letter drives or anything to the path, so copying out something like AutomatedTesting/Assets/Prefabs won't be able to pull anything up in Windows Explorer.

**Comment by svitlani** [comment]
From UX review:
It does not work as expected;

When right-clicked the highlight isn't visible.
The URL text should be in the same format as Windows
CTRL C/V should be in a Windows format; Ctrl C should take the absolute path and Ctrl V should be in the windows format
When copied from Windows into Editor; when pasted and click enter—nothing happens it should be a two-sided relation; if you cut and paste a URL, it should have a modal pop-up “this URL is not in your current project”.
Cut does not work as expected when right-clicked.
The background isn't changing (same as our input fields)
There is no hover state to indicate that user can use the URL field (this is a separate hover style to the breadcrumbs)
