### ISSUE TITLE
Bug Report: Drag and drop of FBX files has confusing UX - inconsistently seeing icon of a circle with a line through it indicating that dragging and dropping is not possible.

### ISSUE THREAD

**Issue by omacx** [o3de/o3de#14434]
**Describe the bug**
When importing any type of file into O3DE, the first time it works when dragging from a Windows Explorer window into the O3DE interface, but when grabbing an additional FBX file or any other file, it has an icon of a circle with a line through it indicating that dragging and dropping is not possible. If I restart the editor, I can import again, but the same error occurs. After this error happens, if I try to use the 'Import from File' dropdown method, it works but it re-imports the original file that was first imported. Also, if I import using the 'File' dropdown and attempt to import again, the same error occurs, re-importing the first file and prompting me that the file already exists.

**Steps to reproduce**
1. with o3de open drag any file that you wish to import into project from a explorer window or file import
2. repeat step one with a different asset
3. error when dragging from explorer. will not let you drag in asset
4. error when using file import will import the file u wish to import but will also reimport the original file that was imported

**Expected behavior**
to import the same as the first time i imported a file

**Actual behavior**
A clear and concise description of what actually happened.

**Screenshots/Video**
https://youtu.be/vDY9p4GDW14

**Found in Branch**
Nightly Development Build

**Comment by monroegm** [comment]
For whoever takes this up, we may need to split this into two separate issues.
