### ISSUE TITLE
Action Manager: Exiting component modes requires a click before ESC works as a hotkey to exit

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#14446]
**Describe the bug**
Exiting component modes requires a mouse click somewhere in the Editor window before ESC works as a hotkey to exit.

**Steps to reproduce**
1. Launch the Editor with the new Action Manager created Menus active:
```
Editor.exe --regset=O3DE/ActionManager/EnableNewActionManager=true
```
2. Open a new or existing level.
3. Add a new entity to the level with a Box Shape component.
4. Click the Edit button on the Box Shape component to enter component mode.
5. Hit ESC.

**Expected behavior**
Component mode is immediately exited.

**Actual behavior**
Nothing happens.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
57a7df88f77a5e741e0a70dd06831314e3cf427c

**Additional context**
1. After the user enters component mode, if they click somewhere in the Editor window, the ESC hotkey will then work. This is a regression from the pre-Action Manager setup.

**Comment by AMZN-daimini** [comment]
Working on this...
