### ISSUE TITLE
AssetBundler: "Generate Asset Lists" fails from Gem_Dependencies.xml

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#14453]
**Describe the bug**
I'm trying to get the `*_[1+].azshadervariant` and `*.azshadervarianttree` assets included in the assets bundle.
I made it all work with AutomatedTesting (Engine Centric build) only when adding this line:  
```
<Dependency path="*.azshadervariant*" optional="false" />
```
to `AutomatedTesting/AutomatedTesting_Dependencies.xml`.  

BUT my initial plan (which failed) was to add the following file to
`Gems/Atom/Asset/Shader/Assets/AtomShader_Dependencies.xml`, which the AssetProcessor
accepted and processed, but AssetBundler failed to use:  
```
<EngineDependencies versionnumber="1.0.0">
    ...
    <Dependency path="*.azshadervariant*" optional="false" /> <!-- The wildcard includes azshadervarianttree assets too -->
</EngineDependencies>
```  
  
The bugs are (Reproduced the bug also with LoftSample in project centric build:
1- It seems, per instructions here: https://www.o3de.org/docs/user-guide/packaging/asset-bundler/default-dependencies/  
The dependency list should be automatically picked up by the AssetBundler when started with `--addDefaultSeedListFiles`. Which did not occur.
2- Even when I manually add a new Seed List file, when I include "atomshader_dependencies.xml" and click `Generate Asset Lists` I get the following error:
```
No files were generated. Please refer to the console for more information.
```

**Assets required**
The AutomatedTesting project should suffice.

**Steps to reproduce**
Instructions mentioned above.

**Expected behavior**
1- The AssetBundler should automatically recognize the file "atomshader_dependencies.xml" and treat it as a seed list.
2- At least the manually created seed list should work too.

**Actual behavior**
See above

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/66021303/217394593-7ffaa64d-8e48-44a9-93b4-152e2b779de6.png)

**Found in Branch**
o3de development branch:  
commit d2004b0e82b0f41d05de7f1a5bf5a12aa1cab0dd (HEAD -> development, upstream/development)
Merge: d8d81ea561 76661b23b8
Author: greerdv <82226198+greerdv@users.noreply.github.com>
Date:   Mon Feb 6 21:32:59 2023 +0000

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Linux
 - Version Ubuntu 22.04
 - CPU AMD Ryzen Threadripper 3970X 32-Core Processor    3.70 GHz
 - GPU NVidia RTX 3070
 - Memory 128GB
 - Storage Device: 2TB Sabrent Rocket NVMe 4.0 (M2 SSD PCIe 4.0)

**Additional context**
Discovered while debugging this issue: https://github.com/o3de/o3de/issues/14439

**Comment by AMZN-stankowi** [comment]
I tried a few variations on this workflow and it's working for me.

1. I created a few different filename variations on "atomshader_dependencies.xml" in Gems\Atom\Asset\Shader\Assets, with the filter you listed above.
2. I Processed assets
3. I opened asset bundler, and made several seed lists in the default location in Automated Testing with different names, each one only having a _dependencies.xml file.
4. I converted each seed list to an asset list, and verified they contained the shaders.
5. I created a seedList.seed in Gems\Atom\Asset\Shader\Assets
6. I opened Asset Bundler, and verified it saw that seed list.
7. I added AtomShader_Dependencies.xml to that seed list.
8. I generated an asset list with just that seed list, and verified it had the shaders.
9. I clicked "Select default seed lists" and verified that seed list was selected.
10. I generated an asset list from the defaults, and verified that had the shaders.

Did you run Asset Processor after creating the atomshader_dependencies.xml, before opening Asset Bundler?
