### ISSUE TITLE
Multiplayer: Support Calling "Connect" from Commandline or SetReg File

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#14474]
Calling "connect" via commandline or setreg file doesn't work.
The command is called too early, before IMultiplayer singleton has been activated. 

**Describe the solution you'd like**
Update MultiplayerSystemComponent to register the "connect" command once it's ready to execute such commands.

**Comment by lmbr-pip** [comment]
We should be able to move this to deferred execution especially as .cfg support appears to be on path to deprecation.
