### ISSUE TITLE
The MultiplayerSample level broke from the Static Rigid Body change

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#14470]
**Describe the bug**
With the PR that introduced Static Rigid Body, the character in the Multiplayer Sample can no longer run around the level. He immediately goes into a falling pose without actually falling vertically and cannot move.

**Assets required**
The Multiplayer Sample project

**Steps to reproduce**
1. Set up and build the Multiplayer Sample project using the following repos, branches, and commits:
```
o3de/development: 84368e90b32bbe25ec657c2048a4cb2e9881f91f
o3de-multiplayersample/GameJam_2022_07: af181e78250a1461315212d168d2433fadf7aac4
o3de-multiplayersample-assets/development: 9978030c94e9222aa5b9933d49ac7a0d63ac7c68
```
2. Build the ServerLauncher and the Editor
4. Run the Editor
5. Load the NewStarbase level
6. Press Ctrl-G to go into game mode

**Expected behavior**
Character can run around the level.

**Actual behavior**
Character remains in a falling pose and cannot move.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82224783/217633651-ebfe1f22-d9dd-4d21-9fd1-5c2f0b8db42e.png)

**Comment by mbalfour-amzn** [comment]
Note: Using the commit just prior to the one listed for o3de/development runs as expected, other than a lot of errors from the StaticRigidBodyComponents in the data that can't be serialized in prior to StaticRigidBody commit.

**Comment by allisaurus** [comment]
This is also reproducible with the o3de-multiplayersample `development` branch, commit `2c84827ff` (see [related issue](https://github.com/o3de/o3de-multiplayersample/issues/220)). Though in that case, the character is not in a fall animation just the stationary "standing" one.

**Comment by hultonha** [comment]
Tagging @moraaar for visibility. I believe a PR has been created to resolve this issue, it can be found here - https://github.com/o3de/o3de/pull/14484.

**Comment by moraaar** [comment]
Fixed by https://github.com/o3de/o3de/pull/14484
