### ISSUE TITLE
Track View: Viewport freezes and console displays errors after Renderer Output generates files

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#14499]
**Describe the bug**
Generating output for the Render Output tool results in many errors displayed in the Editor's console. Also, after the generation is completed, the Viewport becomes unresponsive. The User cannot enter the Game Mode, focus on the selected entity (Z key), or move the Editors camera. The rest of the Editor remains functional. The Editor returns to a normal state after the restart.

**Assets required**
The FFmpeg plugin has to be installed manually. Instructions in comments for the issue: https://github.com/o3de/o3de/issues/5362

**Steps to reproduce**
1. Open the Track View.
2. Add a new sequence.
3. Add Director (Scene) Node.
4. Open Tools > Renderer Output.
5. Set the Output directory.
6. Add batch director.
7. Press the Start button.

**Expected behavior**
The files are generated and no error occurs. The Editor remains functional.

**Actual behavior**
The files are generated, but there are many errors in the Console. The Viewport becomes unresponsive.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/217840557-6f5d9c63-fb20-442b-8b92-8e39853f9566.mp4

**Found in Branch**
Development (7ce6550)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
7ce6550

**Desktop/Device:**
Desktop/Device:
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU Nvidia GeForce RTX 2060 SUPER
Memory 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/10698200/Editor.log)

**Comment by Jackie9527** [comment]
Sounds like the same problem, which #14715 wants to resolve.

**Comment by AMZN-daimini** [comment]
> Sounds like the same problem, which #14715 wants to resolve.

Thanks, I linked the PR to this issue. When the PR goes in, we can verify whether that change fixed this issue or not.

**Comment by LB-JakubSkorupka** [comment]
We verified that the Viewport is functional after the fix, however we noticed that the errors and asserts are still being printed in the console.
Verified on build Development (37b6a48).

Should we create a separate issue for the errors and asserts or this issue is sufficient to track this?

Please refer to the attached Editor.log for more details.
[Editor.log](https://github.com/o3de/o3de/files/10823557/Editor.log)

**Comment by AMZN-daimini** [comment]
Re-opened to track the issue with errors showing in the logs.
