### ISSUE TITLE
Bug Report Create a Gem from the PythonToolGem template - gem.json issue.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#14500]
**Describe the bug**

Wanted to update my GEM with the newest PythonToolGem template code. However, I found that this has an issue. Below are the issues and the work around I found.

Template used:
https://www.o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/

gem.json has issues, see below
![image](https://user-images.githubusercontent.com/87207603/217869323-7847e4fa-e55d-4e80-bfde-ce8dce1244c0.png)

However, removing some of the new gem.json elements, the gem imported with out issue. I used a gem.json that was a few months older.
This Issue:
The FIX:
![image](https://user-images.githubusercontent.com/87207603/217869223-5d05f531-b5e6-481e-ad0a-3a33664f3054.png)

**Steps to reproduce**
1. Used CLI to create gem: scripts\o3de create-gem --gem-name MyPyShapeExample --gem-path C:\o3de-gems\MyPyShapeExample --template-name PythonToolGem

2. Register and Import into O3DE.
3. See Above for issues.

**Expected behavior**
Generated Template gem.json will Python Parse the gem without issue.

**Actual behavior**
Python has a issue with the gem.json

**Found in Branch**
Development. 

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Please provide the SHA/hash that identifies the latest commit from the o3de/o3de repository if the issue is reproducible in the development or other official branches. 
You can get the commit ID by running the `git rev-parse HEAD` command on your current branch.

**Desktop/Device (please complete the following information):**
 - Device: [Linux] 
 - OS: Ubuntu 22.04
 - Version [e.g. 10, Monterey, Oreo]
 - CPU [e.g. Intel I9-9900k  ]
 - GPU [NVidia 1080]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by AMZN-alexpete** [comment]
Thanks @shawstar! I believe this bug was fixed in  commit 9e15255452f5edd22d383d0dabea93fdb07ce570, and pulling latest should resolve the issue.  The issue was bogus validation logic that was throwing an error when given a list of empty `compatible_engines`.

**Comment by shawstar** [comment]
After this fix... no error adding or building the gem, but the gem will not show up in o3de anymore. :( I still think there is an issue.

**Comment by shawstar** [comment]
This is just using the template and not a specific gem.

**Comment by shawstar** [comment]
This is now fixed with:
![image](https://user-images.githubusercontent.com/87207603/218179923-b16d13f0-90b3-45d2-a6c4-46af89bc5a58.png)
