### ISSUE TITLE
New Asset Browser Search: Cannot Drag Prefab Into Scene

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#14522]
When searching in the new asset browser (ed_useWIPAssetBrowserDesign), I cannot drag and drop a prefab asset into the level

**Steps to reproduce**
1. Open Editor with cvar _ed_useWIPAssetBrowserDesign_ enabled
2. Search for a prefab in the asset browser
3. Attempt to drag and drop prefab into the level

**Expected behavior**
Drag and drop works and the prefab appears in editor

**Actual behavior**
Cannot drag and drop
![image](https://user-images.githubusercontent.com/32776221/217978778-eb2ff99c-b182-4da1-998c-69907e374137.png)

**Found in Branch**
Development 

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Wed Feb 8 09:08:36 2023
commit 4e0c46be1febf66c61749c72851692de8ab0ce2d

**Comment by monroegm** [comment]
Closing this as it is being tracked as part of the Asset Browser project

**Comment by dtamkin1** [comment]
This issue is being tracked here #14398.
