### ISSUE TITLE
Changing values of Input Bindings comboboxes in Asset Editor causes them to go blank

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#14529]
**Describe the bug**
If a value of *Input Bindings* combobox (for example *Input Device Type* property) is changed, it and potentially other available comboboxes can go blank. This can be fixed by restarting the Editor, or sometimes by relaunching or folding/unfolding certain categories. 

It should be noted that this issue was only observed on *Input Bindings* and not any other *Asset Editor* file types.

**Steps to reproduce**
1. Go to *Tools > Asset Editor*.
2. In the *Asset Editor* choose *File > New > Input Bindings*.
3. In the created *Input Bindings* add a new *Input Event Group*.
4. In the added *Input Event Group* add a new *Event Generator* (either class can be chosen).
5. In the added *Event Generator* change *Input Device Type* or *Input Name*.

**Expected behavior**
Combobox remains functional.

**Actual behavior**
Combobox and potentially other comboboxes in the *Input Bindings* go blank .

**Video**

https://user-images.githubusercontent.com/86952082/218082539-af816059-c878-450b-84d7-08811c09224e.mp4

**Found in Branch**
Development (99f7137)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
99f713702e5e0a8949e38c7b92bf00682c2633ca

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by sphrose** [comment]
@LB-ArturZieba I have been unable to duplicate this despite trying all the build types and experimental features I can think of, is there any more information you can give me that might help?

**Comment by LB-ArturZieba** [comment]
We have verified that the issue no longer occurs on the Development (0dcc790) build on our end as well. Closing the issue.
