### ISSUE TITLE
Periodic Test Failure: MaterialEditor_Atom_PeriodicTests is consistently failing in Periodic test suites

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#14540]
**Describe the bug**
MaterialEditor_Atom_PeriodicTests is consistently failing in Periodic test suites.

**Failed Jenkins Job Information:**
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/251/pipeline/1907

**Attachments**
Windows - [log.txt](https://github.com/o3de/o3de/files/10711209/log.txt)
Linux - [log(1).txt](https://github.com/o3de/o3de/files/10711210/log.1.txt)

**Additional context**
This is the only test executing in this suite. Updating CMakeLists.txt to move this test to execute in the Sandbox test suite.

**Comment by jromnoa** [comment]
Got a PR here to fix this: https://github.com/o3de/o3de/pull/14570

**Comment by jromnoa** [comment]
Fixed has been merged
