### ISSUE TITLE
ShaderManagementConsole: SMC shouldn't do work every frame.

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#14562]
**Describe the bug**
I noticed on the bottom right corner of SMC UI that it is printing: CPU Time, GPU Time and FPS. This is indicative that this application
is doing some kind of rendering loop, mostly due to the fact that its code is based on Material Editor and Material Canvas.
The ShaderManagementConsole is not a rendering application and shouldn't waste CPU/GPU cycles unnecessarily.

**Assets required**
N/A

**Steps to reproduce**
Run the SMC.

**Expected behavior**
The SMC shouldn't run rendering loops in the background. CPU Time, GPU Time and FPS should be removed.

**Actual behavior**
The SMC is "rendering" something in the background. CPU Time, GPU Time and FPS  are constantly updating.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/66021303/218518961-512e0627-5f34-44b5-bb42-0a796e247a40.png)

**Found in Branch**
"devevelopment"

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
commit 1366b4f8d4ef099aa65bdc0349341dcde37afaf5 (HEAD -> development, upstream/development)
Merge: 095d1b02d7 38a7764afa
Author: Chris Galvan <chgalvan@amazon.com>
Date:   Mon Feb 13 10:32:52 2023 -0600

    Merge pull request #14554 from Jackie9527/1-5201
    
    bugfix for text color.

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Linux
 - Version Ubuntu 22.04
 - CPU AMD Ryzen Threadripper 3970X 32-Core Processor    3.70 GHz
 - GPU NVidia RTX 3070
 - Memory 128GB
 - Storage Device: 2TB Sabrent Rocket NVMe 4.0 (M2 SSD PCIe 4.0)

**Additional context**

**Comment by gadams3** [comment]
There is an application timer that triggers at a fixed but configurable interval. That timer invokes the tick bus. The timing information on the status bar is standard across all of the tools. It's only making requests for the timing information from atom, not actually doing any real “work”. I would ignore it. If it's a concern, hide it. I've been wondering for a while if there was something that could be displayed in SMC, like rendering geometry with the shader or a specific variant applied to see how performance is affected.

**Comment by gadams3** [comment]
As mentioned, this is standard behavior for the application framework upon which the tool is built. While nothing is currently being rendered, there is potential for doing so in the future. The timing is simply reflective of the idle event processing loop used in all the tools.
