### ISSUE TITLE
[Android] Building a project with all gems enabled fails with an exception

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#14561]
**Describe the bug**
Building a project with all available gems enabled for Android fails with the following error:
```
> Task :app:packageProfile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageProfile'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.lang.OutOfMemoryError (no error message)
```
Note that project created from the default template builds without issues.

Please refer to the attached log for more information.

**Prerequisites**
- A project with all available gems enabled is created and built in Source configuration
- The project's assets for the Android platform are enabled and processed
- All the required environment variables are set as described in the instructions: https://o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/

In this test the following settings have been used:

```
SET O3DE_ENGINE_PATH=C:\o3de
SET O3DE_PROJECT_PATH=C:\Users\GPC-462\O3DE\Projects\AllProject
SET O3DE_BUILD_ROOT=C:\o3de-build\android_sdcard
```
```
SET O3DE_ANDROID_SIGNCONFIG_FILE=%O3DE_BUILD_ROOT%\o3de.keystore
SET O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD=o3de_android
SET O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS=o3de_key
SET O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD=o3de_android
SET O3DE_ANDROID_SIGNCONFIG_KEY_SIZE=2048
SET O3DE_ANDROID_SIGNCONFIG_VALIDITY_DAYS=10000
SET O3DE_ANDROID_DN="cn=AllProject, ou=o3de, o=LF, c=US"
```
```
set O3DE_ANDROID_SDK_PATH=C:\Android\Sdk
set O3DE_ANDROID_NDK_VERSION=22.1.7171670
set O3DE_ANDROID_SDK_API_LEVEL=30
set O3DE_ANDROID_ASSET_MODE=LOOSE
set O3DE_ANDROID_DEPLOY_TYPE=BOTH
```

**Steps to reproduce**
1. Generate KeyStore to allow APK signing:
`keytool -genkey -keystore %O3DE_ANDROID_SIGNCONFIG_FILE% -storepass %O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD% -alias %O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS% -keypass %O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD% -keyalg RSA -keysize %O3DE_ANDROID_SIGNCONFIG_KEY_SIZE% -validity %O3DE_ANDROID_SIGNCONFIG_VALIDITY_DAYS% -dname %O3DE_ANDROID_DN%`
2. Use Python to run generate_android_project.py:
`%O3DE_ENGINE_PATH%\python\python.cmd %O3DE_ENGINE_PATH%\cmake\Tools\Platform\Android\generate_android_project.py --engine-root %O3DE_ENGINE_PATH% --project-path %O3DE_PROJECT_PATH% --build-dir %O3DE_BUILD_ROOT%\android --third-party-path %USERPROFILE%\.o3de\3rdParty --android-sdk-path %O3DE_ANDROID_SDK_PATH% --android-ndk-version %O3DE_ANDROID_NDK_VERSION% --android-sdk-platform %O3DE_ANDROID_SDK_API_LEVEL% --enable-unity-build --asset-mode %O3DE_ANDROID_ASSET_MODE% --signconfig-store-file %O3DE_ANDROID_SIGNCONFIG_FILE% --signconfig-store-password %O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD% --signconfig-key-alias %O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS% --signconfig-key-password %O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD%`
3. Build the Android project:
`cd %O3DE_BUILD_ROOT%\android`
`gradlew assembleProfile`

**Expected behavior**
Building finishes successfully. 

**Actual behavior**
Building a project with all gems enabled fails with an exception.

**Screenshots/Video**
![AllGemsAndroid](https://user-images.githubusercontent.com/86953659/218473467-83f608b6-a570-4df4-9ac7-fcce9cd51014.PNG)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[16bc450](https://github.com/o3de/o3de/commit/16bc450bdc1b2e356b3a3e519f86df4cd7bc8ecd)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i5-9600K
 - GPU: NVIDIA GeForce RTX 2070
 - Memory: 16GB

**Additional context**
[AllGemsAndroid.txt](https://github.com/o3de/o3de/files/10722738/AllGemsAndroid.txt)

**Comment by Jackie9527** [comment]
Modify JVM arguments in `gradle.properties`, using `org.gradle.jvmargs` to increase size of JVM heaps, such as:
```
org.gradle.jvmargs=-Xmx2g -Xms2g -XX:+HeapDumpOnOutOfMemoryError
```

**Comment by LB-KacperKapusta** [comment]
It has been reverified in Development ([7607430](https://github.com/o3de/o3de/commit/76074304573950182e2d48283ff4b01b798bab03)) after modifying the JVM arguments as described in the above comment:
![jvmargs](https://user-images.githubusercontent.com/86953659/221584385-ad180073-b5a8-433c-b415-76aa280d1181.PNG)

the following error still occurred while building the Android project for a project with all gems enabled: 
![GradleBuildFail](https://user-images.githubusercontent.com/86953659/221584455-47136713-2c58-4de9-8c67-baec89c24bee.PNG)
