### ISSUE TITLE
Aligning options are highlighted for singular nodes

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14577]
**Describe the bug**
Aligning options are highlighted for singular nodes in both Script Canvas and Material Canvas.

This issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Open the Material Canvas.
2. Create any (singular) node.
3. Select the node.
4. Look at the top toolbar.

**Expected behavior**
Aligning options are not highlighted for the singular node selection.

**Actual behavior**
Aligning options are highlighted.

**Screenshots/Video**
https://user-images.githubusercontent.com/110163473/218757858-32a38571-a517-4a8d-9d57-891fef01dd40.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
f829a06

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11 22H2
 - CPU: I7-11700f
 - GPU: Geforce RTX3070 MSI
 - Memory: 32GB

**Comment by gadams3** [comment]
The current logic is just checking to see if anything is selected at all. It could be updated to check if more than one item is selected.

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development ([d5c1fdb](https://github.com/o3de/o3de/commit/d5c1fdb52eb78b91a1b837ca147b657a726a3001)).
