### ISSUE TITLE
As a Dev I want Editor to Close/Warn of Existing Rogue ServerLauncher

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#14586]
Multiplayer Editor simulation will fail if a server is already running. Unless _editorsv_launch_ is false, all existing server launchers should be shut down before starting up a new server when pressing CTRL+G

**Describe the solution you'd like**
If the editor is entering into a multiplayer simulation, search for other applications matching the server name and display a popup in Editor is an existing server exists. Provide a prompt to forcefully shutdown the rogue server processes
This would work both when editorsv_clientserver is enabled or not.

**Comment by amzn-rhhong** [comment]
We should have a pop-up there to warn user the port is taken.
