### ISSUE TITLE
Intermediate assets and shader variants cause invalid product dependencies

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#14601]
**Describe the bug**
When using AssetBundler with the dependencies xml file included below, generating an asset list produces a number of missing asset ID errors. Reprocessing the xml file in the Asset Processor resolves the issue.

**Assets required**
A file like the following (named MultiplayerSample_Dependencies.xml):
```
<EngineDependencies versionnumber="1.0.0">
    <Dependency path="*.azshadervariant*" optional="false" /> <!-- The wildcard includes azshadervarianttree assets too -->
</EngineDependencies>
```

**Steps to reproduce**
1. Run Asset Processor and let it go to idle.
2. Run the Asset Bundler.
3. Select the seed file entry that matches with the above xml file.
4. Press "Generate Asset List" and generate the asset list.

**Expected behavior**
The asset list generates without errors.

**Actual behavior**
The Asset Bundler prints out a bunch of errors of the form "Could not find asset with id (%s) on platform (%s)". The asset IDs can't be found as source or product assets in the Asset Processor.

Reprocessing the xml file in the Asset Processor and then going thru the repro steps again produces a clean output.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
a386127e171014410000364abd5a31efa23d1c17

**Desktop/Device (please complete the following information):**
PC

**Comment by AMZN-stankowi** [comment]
Is this ticket the same as https://github.com/o3de/o3de/issues/14453 ?

**Comment by AMZN-stankowi** [comment]
I talked to the author about this ticket, we think it was related to https://github.com/o3de/o3de/pull/15518 , that file also had the paths that are fixed up in that pull request, which may have lead to some confusion that it was shaders being added later when it may have been the paths that resolved differently on later runs.

**Comment by AMZN-stankowi** [comment]
We think this might resolve this issue https://github.com/o3de/o3de/pull/15518
