### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Ulrick28** [o3de/o3de#14613]
**Is your feature request related to a problem? Please describe.**
It is difficult to investigate O3DE as a potential robotics/simulation platform due to a lack of build in sample sensors. This requires a user to search for actual simulated sensors to test with.

**Describe the solution you'd like**
Ros demo sensor for O3DE. This sensor is not meant to be used for a real simulation, but instead is meant to provide an example of a sensor to test O3DE simulation functionality with.

**Describe alternatives you've considered**

**Additional context**

**Comment by lgleim** [comment]
Thank you for your report. The ROS2 Gem already supports a variety of simulated sensors. Please have a look at the getting started notes on the ROS2 Gem or one of the sample projects such as https://github.com/o3de/ROSConDemo. The Gem does not yet have a stable release and documentation on this topic will be continuously improved. Please reach out in Discord if you need further assistance.

**Comment by Ulrick28** [comment]
Yes it supports a variety of sensors, but it does not ship with a variety of sensors to test with. A user has to hunt for sensors to test with, which adds another point of friction for anyone investigating O3DE for robotics. The suggestion is we could provide a sample sensor to include in any templates, tutorials, etc. My team is considering creating some robotics tutorials, hence the request.
