### ISSUE TITLE
Editor Freezes after filtering assets in Asset Browser

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14645]
**Describe the bug**
The Editor freezes for a long time after selecting any of the filtering options in the Asset Browser's search engine. In some cases the Editor crashes afterwards.

This issue occurs on both Windows and Linux.

Please note that the issue occurs inconsistently in 3 out of 4 times with a better reproduce rate when the assets were freshly processed in a new project. Deleting the Cache folder and reprocessing the assets once again can also leads to this issue to occur. No logs were generated.

**Steps to reproduce**
1. Create a new Project.
2. Wait for the assets to be processed.
3. Select any of the filtering options in the Asset Browser's search engine (i.e. Shader, slice).

**Expected behavior**
The filter is applied.

**Actual behavior**
The Editor freezes.

**Screenshots/Video**
https://user-images.githubusercontent.com/110163473/219664068-933930c8-1729-47ce-9520-6d6aac278330.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
288619c

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11 22H2
 - CPU: I7-11700f
 - GPU: Geforce RTX3070 MSI
 - Memory: 32GB

**Comment by lawsonamzn** [comment]
I encountered this too, and from the debugger it looks like its doing some sort of recursive filtering in a really unoptimized way (the same item being encountered many times).
