### ISSUE TITLE
The ed_physxUpdatePrefabsWithColliderComponents command can invisibly corrupt level files.

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#14656]
**Describe the bug**
When running the ed_physxUpdatePrefabsWithColliderComponents command on a level that contains prefabs with Collider components in it, the command appears to generate "add" patches in the level that can't be viewed in the Editor, but overrides whatever Collider data is in the prefab, preventing changes to the prefab from working.

**Steps to reproduce**
1. Create a level
2. Add an entity named "PhysicsEntity" with a PhysX Collider component and a Static Rigid Body.
3. Right-click on the entity and make it a prefab. Save the prefab in the level folder.
4. Save the level
5. Close the Editor
6. Manually edit the PhysicsEntity.prefab in a text editor to remove the EditorStaticRigidBodyComponent
7. Restart the Editor
**8. Load the created level** - this goes against the "important notice" instructions, but it's needed to recreate the bug.
9. Run the "ed_physxUpdatePrefabsWithColliderComponents" command.
10. Save the level and the prefab.
11. Examine the level prefab file.

**Expected behavior**
The level prefab file should remain untouched.

**Actual behavior**
The level prefab gets a bunch of "add" patches added to it that silently start affecting how the level works and what happens when you edit the prefab. It can lead to a lot of subtle bugs in which physics stops working correctly.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
5ba0c190f738d5d9c1f148ab1fd83a99cfa45b7b

**Desktop/Device (please complete the following information):**
PC

NOTE: This was discovered on MultiplayerSample after painstakingly investigating why physics on the teleporters stopped working, even though everything about them appeared correct in the teleporter prefab and the Editor.

**Comment by moraaar** [comment]
>the command appears to generate "add" patches in the level that can't be viewed in the Editor

The command doesn't add patches, it opens prefabs, add Static Rigid Body components where needed, and resaves the prefabs.

>  8. Load the created level - this goes against the "important notice" instructions, but it's needed to recreate the bug.

This is most likely the reason, the command modifying and saving a prefab that it's currently opened.
I could add a check to the command that if there is a level opened it tells the user and doesn't do anything, as a protecting measure for the case the command is run without following the instructions.

> NOTE: This was discovered on MultiplayerSample after painstakingly investigating why physics on the teleporters stopped working, even though everything about them appeared correct in the teleporter prefab and the Editor.

I'm sorry you hit this issue. You can reach me anytime about static rigid body issues.

Thanks.
