### ISSUE TITLE
Multiplayer Timeout If Level Load Too Long

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#14659]
Servers will terminate a client connection if the client takes too long to load a level. The default _net_udpDefaultTimeoutMs_ is 10 seconds, the client/server wont send/receive any network traffic during the level load leading the client to disconnect. A real level could take a minute to load and require a loading screen, etc. The network should be able to handle long level load times.

**Steps to reproduce**

1. For the purposes of testing it helps to reduce _net_udpDefaultTimeoutMs_ to something small like 1 second (1000 ms)
2. Ensure timeouts are enabled _net_UdpTimeoutConnections true_
3. Create a level with enough entities to cause a level load time longer than _net_udpDefaultTimeoutMs_
4. Launch a server and begin hosting the large level
5. Open a client and connect

**Expected behavior**
Client connects to the host, loads the large level, and begins the network simulation

**Actual behavior**
The client connects, but is then disconnected after a second because it did not send/receive any network packets while the level was being loaded. The spawnable system should spread out the level load over multiple ticks, or asynchronously so that the multiplayer system can continually send heartbeat packets 
![image](https://user-images.githubusercontent.com/32776221/219923198-45e5cea8-3c72-442a-8ba6-9ccf3909cbe9.png)

**Found in Branch**
development February 17 2023

----
## Research Spike
**Cvars to debug network traffic:**
 --LoggerSystemComponent.EnableLog NET_Acks 
 --LoggerSystemComponent.EnableLog NET_CorePackets 
 --LoggerSystemComponent.EnableLog NET_DebugPacketSend

**Remove Non-Essential Network Traffic**
CorePackets::Heartbeat should be keeping a valid connection alive even during times of lag. As long as the game is running (not crashed, shutdown), heartbeats should persist. As such, it's good to remove other (non-heartbeat) network traffic for debugging.

_Note: This is not to say games _should_ stay connected if the client becomes too laggy. Developers may want to add game logic which terminates a connection should an individual cpu become too laggy to maintain good gameplay._ 

 1. Stop sending _MultiplayerPackets::SyncConsole_
       This is found in MultiplayerSystemComponent.cpp and is the server sending over 1000s of cvars. See related https://github.com/o3de/o3de/issues/16587
 2. Stop sending _MultiplayerPackets::EntityUpdate_. While required for playing a real game, we just want to test heartbeats and EntityUpdates adds a lot of traffic.

### Quick Validations
1. **Question:** Does moving the client code to send _MultiplayerPackets::ReadyForEntityUpdates_ until AFTER the level is loaded resolve this timeout issue? Current _MultiplayerPackets::ReadyForEntityUpdates_ is send once the level begins loading, _OnRootSpawnableAssigned_. _OnRootSpawnableReady_ is the callback once all the entities are finished loading. 
   Answer: No. The timeout still occurs.

2. **Question:** Are we should it's the level load causing the problem?
    Answer: Yes. Removing the _loadlevel_ command from MultiplayerSystemComponent shows that the connect remains alive. Even after disabling _MultiplayerPackets::EntityUpdate_ from being sent, the heartbeat packets keep the connection alive.

### Why Isn't Server Sending Heartbeats As Timeout Draws Near?
After the client begins level loading and goes dark, the server isn't sending any heartbeat requests; ie `CorePackets::HeartbeatPacket(true)`, where `true` signifies that the receiver should sent a heartbeat packet back to acknowledge that it's still alive. I was expecting the server to send heartbeats during the time it's not receiving any traffic from client.

The server does call UdpNetworkInterface::HandleConnectionTimeout, but there's an explicit check which causes only clients to send/request a heartbeat.
`if (udpConnection->GetConnectionRole() != ConnectionRole::Connector)`

<strike>I cannot imagine why the server wouldn't want to request heartbeats during this time of radio silence. </strike>
EDIT: Servers intentional do NOT send request heartbeats in order to hear back if a client is alive. If the server doesn't receive any network traffic from the player for x-seconds, then that UDP connection is disconnected. The player is the one requesting to connect, if they then don't send any information back, the connection is cut. In that sense, it's the client's responsibility to keep itself alive. The server will, however, send a non-request heartbeat if it's received a lot of the packets from the client, but hasn't sent anything back in a while (see cvar [net_UdpMaxUnackedPacketCount](https://github.com/o3de/o3de/blob/9f91681991d21dbd2e9260753d282c3021911159/Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpConnection.cpp#L22)).

There also appears to be a bug around how often `UdpNetworkInterface::HandleConnectionTimeout` is called. It's called once every time _net_udpDefaultTimeoutMs_ milliseconds go by without hearing from the client. This might sound good, but really, the logic to heartbeat ought to be occurring _net_UdpUnackedHeartbeats_ times in-between _net_udpDefaultTimeoutMs_. IE, if the timeout is 10 seconds, and _net_UdpUnackedHeartbeats_ is 5, should we try to send 5 heartbeats during those 10 seconds (1 beat per 2 seconds)?

In either case, even if a heart beat is sent, the client still isn't responding back until the level is finished loading. A responsive client will be a requirement before any other bugs are crushed.

### Current Reading and Handling of Packets
Reading packets off the socket and handling packets occur on 2 separate threads.

**Reading packets** occurs using a `TimedThread` wrapper class that makes it easy to have a time throttled thread. `UdpReaderThread` derives from `TimedThread` and starts updating as soon as it's registered with a UDP socket.
`UdpReaderThread::OnUpdate` is called automatically at regular intervals and packets are read off the socket, and are stored for later when the main thread has time to handle the packets.

**Handling packets** occurs on the main-thread starting with  `NetworkingSystemComponent::OnSystemTick()`. Handling heartbeats is what's also responsible for sending back heartbeat responses, which is why it's important for catching time outs.

Most packets should be handled on the main thread since most will result in game logic. However, core packets aren't broadcast out into the game for anyone to handle, instead they are handled especially by the udp connection's _HandleCorePacket_ function. There are only 5 types of core packets: _InitiateConnectionPacket_, _ConnectionHandshakePacket_, _TerminateConnectionPacket_, _HeartbeatPacket_, and _FragmentedPacket_. _Heartbeat_ is particular is quite self-contained, its only job is to pong-back a heartbeat. 

Moving forward, could heartbeats be moved off the mainthread, and handled directly from the `UdpReaderThread`? To answer this, it's important to know how packets are sent. If packets are sent on the main-thread, then even if we send a pong-heartbeat from  the UDP reader thread, it'll only end up stored in basket once the main-thread is done loading the level.

### Sending Packets from Other Threads?
UdpSocket::SendInternal results in the operating system directly calling the operating system's networking `sendto` from whatever thread the call came from; ie, there is no queuing up of packets to be sent later by the main-thread. Luckily, there's already a precedent set for sending packets from multiple threads; see `sv_multithreadedConnectionUpdates` and `UdpConnection::m_sendPacketMutex`. This existing code allows us to confidently (and safely) send heartbeat packets from another thread.

### Detecting a Heartbeat from Raw Bytes
The socket only receives a raw byte stream from the network. These bytes must be interpreted using AzNetworking to determine which packet is actually being received. Normally this occurs inside of `UdpNetworkInterface::Update()`, but if we want to detect heartbeats as soon as they are received from inside the network reader thread, we'll have to know how packets are interpreted.
Moving forward, we may want to deserialize all incoming packet headers from the reader-thread, just to determine if it's a heartbeat. 

**Heartbeat structure**
1. Encryption: Before reading a packet, it may need to be decoded.
2. Packet Header
   a. Compression: The packet may have undergone compression; header flag can be used to determine if compression is ON or OFF.
   b. Packet Type: Packet type 4 is a heartbeat. `CorePackets::PacketType::HeartbeatPacket = 4`
3. Request Response:
    a. True. A true value means someone is wondering if we're still alive; we should send back a heartbeat right away to let the other side know the app is still running. 
    b. False. A false value means this heartbeat is a pong-packets back to us (the requestor); these are read and tell us the other connect is still alive.

### Performance Impact of Deserializing Headers
We'll need to make sure deserializing all of the packet headers from the reader thread doesn't impact performance. Currently, `UdpNetworkInterface::Update` discards packets if processing packets takes too long (see _net_UdpPacketTimeSliceMs_). If performance is impacted, perhaps we can open a port specifically for heartbeats; we'll know this port is only going to send/receive heartbeats on it. Another option is to at least cache the header information so that `UdpNetworkInterface::Update` doesn't need to re-calculate the header.
`NetworkInterfaceMetrics` should be updated to include a `m_updateHeartbeatsTimeMs`. Tests can be ran to see how much `m_updateHeartbeatsTimeMs` is adding.

### Throttling Reader Thread
@todo
reuse socket?
https://github.com/o3de/o3de/blob/development/Code/Framework/AzNetworking/AzNetworking/Utilities/NetworkCommon.cpp#L64-L69

**Comment by kberg-amzn** [comment]
"The spawnable system should spread out the level load over multiple ticks, or asynchronously so that the multiplayer system can continually send heartbeat packets"

We should discuss this solution. There are other potential solutions that might work just as well or better with varying levels of effort and side-effects.

**Comment by lmbr-pip** [comment]
We should put dev in control of load times and provide flexibility as games in dev will have poorly optimized content.

**Comment by lmbr-pip** [comment]
This probably needs a simple RFC to cover the solution.

**Comment by lmbr-pip** [comment]
@AMZN-Gene I believe you added a cvar to help here. Can you confirm if further work is required?

**Comment by AMZN-Gene** [comment]
> @AMZN-Gene I believe you added a cvar to help here. Can you confirm if further work is required?

The existing net_udpDefaultTimeoutMs cvar is a just a work around. In production you would not want to increase this since keeping players around that have actually dropped can lead to bad consequences. We need networking to run in its other thread or specifically design a custom timeout just for level loads so it can heartbeat even if the level is loading.

**Comment by FrankenwareStudios** [comment]
Hello, yep this is an issue for me as well when testing things out.  I'm having to raise timeouts just to get the multiplayer sample client/server to run.  Would love to see this resolved.

Thanks

**Comment by AMZN-Gene** [comment]
Noticing that after the client begins level loading and goes dark, the server isn't sending any heartbeat requests. I was expecting the server to send heartbeats during the time it's not receiving any traffic from client

**Comment by AMZN-Gene** [comment]
> "The spawnable system should spread out the level load over multiple ticks, or asynchronously so that the multiplayer system can continually send heartbeat packets"
> 
> We should discuss this solution. There are other potential solutions that might work just as well or better with varying levels of effort and side-effects.

How about reading the packet header directly inside the reader thread, only handling heartbeats, and sending back heartbeats from the reader thread instead of waiting for main thread?
