### ISSUE TITLE
Older Project Manager Can't See or Register Projects Made By Newer Project Manager

### ISSUE THREAD

**Issue by LesaelR** [o3de/o3de#14711]
**Describe the bug**
Any project made by the engine after the changes to enable Side-By-Side engines can't be seen or registered by an older Project Manger.

**Steps to reproduce**
1. Launch Project Manager with Engine build post-changes
2. Create a new project
3. Launch Project and verify it works
4. Launch Project Manager with Engine build pre-changes
5. Attempt to Register project created with the post-change engine
6. Observe the project is missing and can not be added

**Expected behavior**
The project is visible and added to the engine. 
If not compatible, a UI element appears to explain the Project is not compatible as it is from a future version of the engine. 

**Actual behavior**
The project is not visible and can not be added. No errors or UI appear to explain the issue. 

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/89800757/220484056-895f2c19-5327-4888-a5ea-fe6d26e52e97.png)
![image](https://user-images.githubusercontent.com/89800757/220484084-67c4bfa1-d1f7-487a-bfe5-162a3902ee67.png)
First Image is Old, Second Image is New

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
1f7a8d2234a5aa140aa655bd659dcb6867d89184

**Additional context**
This may be useful UI to have moving forward for any future changes that modify projects and break backwards-compatibility.

**Comment by monroegm** [comment]
@AMZN-alexpete Was there an impactful change communication that accompanied this change? Doesn't seem like a scenario that specifical needs a fix, but just a heads up about the impact

**Comment by AMZN-alexpete** [comment]
Thanks for bringing this up - I just posted the impactful change communication in Discord.  I'll take a look at why Project Manager isn't displaying the appropriate error message.

**Comment by AMZN-alexpete** [comment]
I haven't been able to repro this issue using the commit right before the change https://github.com/o3de/o3de/commit/669bc3b and a project created with the latest Project Manager https://github.com/o3de/o3de/commit/71162fde882549daf9b21f68b42dd8a8c0982467.
Repro steps are:
1. Launch older Project Manager
2. Launch newer Project Manager
3. Create new project with new Project Manager and verify it appears on the Projects page
4. Switch to the older Project Manager - see the project shows up on the Projects page without having to do anything.

I also tried unregistering the new project and adding it in the old Project Manager which worked without errors.

I wonder if there is something else going on here that is different about our setups.  

@LesaelR are you building the engine from source or testing with the nightly installers?

**Comment by AMZN-alexpete** [comment]
@LesaelR  I'm going to mark this as closed - cannot repro.  Please let me know if you have additional information and want to re-open.
