### ISSUE TITLE
Update AR build nodes for Windows 21H2

### ISSUE THREAD

**Issue by amzn-changml** [o3de/o3de#14733]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to ensure that AR runs on the latest versions of Windows that we support as a min spec

**Describe the solution you'd like**
Update the AR build nodes to Windows 20H2 or above without changing the minimum OS spec, if possible

**Describe alternatives you've considered**
Not upgrading until further discussions with the SIGs

**Additional context**
Currently blocking a PR here: https://github.com/o3de/o3de/pull/12009

**Comment by jhmueller-huawei** [comment]
Is there any update on this? Would be really nice to have!

**Comment by amzn-changml** [comment]
We're at the final stages of testing this for Windows 21H1. I'm writing up the updates to the install scripts, then looking to deploy this within the next few weeks. I'll be communicating a change to the minimum requirements, likely sometime before the 2305 release, but it will not be part of the featureset of 2305 itself.

**Comment by jhmueller-huawei** [comment]
Great, thank you!

**Comment by amzn-changml** [comment]
Upgrade complete. https://github.com/o3de/o3de/pull/12009 is now passing AR
