### ISSUE TITLE
Atom Hair component name should just be Hair in the Atom group

### ISSUE THREAD

**Issue by smurly** [o3de/o3de#14735]
[Migrated from JIRA ATOM-17699]
The hair component is currently in the Atom component group and also named "Atom Hair" with no icon. it needs an icon and it should be called "Hair"

----
Found in Build:
commit 1660c73d73962195ed810f0d880c8be975191e21 (HEAD -> development
Reproducibility:

Prerequisites:

Steps to Reproduce:
# create an entity in editor
# add component from the menu locate "Atom Hair" in the Atom group

Expected Result:
in the Atom group the component is labeled "Hair" since no other components are prefixed with Atom that are in the Atom group

Actual Result:
in group "Atom" the component is labeled "Atom Hair"
![atom_hair](https://user-images.githubusercontent.com/26234397/221253839-2809e19a-f443-4932-929f-4eef4c4e6481.png)

**Comment by galibzon** [comment]
Fixed
