### ISSUE TITLE
DepthPassTransparentMin/Max will not respect parallax usage for transparent objects

### ISSUE THREAD

**Issue by smurly** [o3de/o3de#14738]
[Migrated from JIRA ATOM-17201]
The DepthPassTransparentMin and DepthPassTransparentMax shaders currently assume non-deforming geometry which could result in mis-matching depth bounds.

**Comment by galibzon** [comment]
@smurly Can you please check if it still occurs. or ask LB to re-validate?

**Comment by galibzon** [comment]
@adiblev , @thefranke , do you have somebody working on this aspect of the PBR materials?

**Comment by galibzon** [comment]
Closing this issue as both Parallax effect and transparency should not be active at the same time. Will create another GHI to do the work to validate the scenario.
