### ISSUE TITLE
Alpha cutout edges not anti-aliasing

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#14754]
**Describe the bug**
There is a problem with the anti-aliasing of alpha cutout images. I was investigating a ticket filed long ago where shadows were coming out with strange artifacts as light was passing through cutout alpha cards. The issue has evolved in that now the shadows look ok but the cutout themselves are coming through with jagged edges. This should not be a resolution issue- I attached the file texture used to make the cutout- its a 4k image. 

**Assets required**
You can see this by loading the 1X1 plane mesh that ships with O3DE, generating a material for the mesh, and then in the material editor assigning the "shadow_artifact_test" as you see in the material editor screenshot.

**Steps to reproduce**
1. Open a new level with the default prefab present.
2. Create a mesh entity, assign the 1x1 plane, and assign the supplied texture map to the alpha slot as seen in the material editor screenshot.
3. Position plane over the default scene groundplane and you should see the alpha edges are aliased, while if you inspect the "shadow_artifact_test.png" image itself those edges are smooth.

**Expected behavior**
Edges should be smooth

**Actual behavior**
Edges are crunchy

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Current build

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Please provide the SHA/hash that identifies the latest commit from the o3de/o3de repository if the issue is reproducible in the development or other official branches. 
You can get the commit ID by running the `git rev-parse HEAD` command on your current branch.

**Desktop/Device (please complete the following information):**
 - PC
 - Windows
 - 10
 - Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz   3.30 GHz
 - NVidia GeForce RTX 2080
 - 64.0 GB

![alpha_antialiasing_screenshot_materialEditor](https://user-images.githubusercontent.com/50616575/220798953-519357f0-ac3e-4e49-8191-dc3d2455201c.png)
![alpha_antialiasing_screenshot_viewport](https://user-images.githubusercontent.com/50616575/220798958-6c5b1882-2450-4434-be1d-03f3130fc94b.png)
![shadow_artifact_test](https://user-images.githubusercontent.com/50616575/220798960-dbfc3d34-8f49-40d0-ad3a-2b50dd773f74.png)

**Comment by galibzon** [comment]
@invertednormal

**Comment by invertednormal** [comment]
I don't think this is a bug. When alpha is set to cutout, it doesn't matter if the holes in the source image are anti-aliased, it's going to clamp everything to either 0 or 1. This means each pixel rendered is going to be transparent or not. Without some other anti-aliasing running on top, it's going to look jaggy. MSAA does not fix this, it only super-samples triangle edges, so it can't handle this. If you run with some other anti-aliasing like TAA this should look fine.

**Comment by invertednormal** [comment]
The screenshot does seem particularly jaggy. I think what's happening is that any opacity value less than 1.0 is being clipped, but we probably should make that configurable, and maybe default to like 0.5. One possibility with the screenshot is that the image was a jpeg and block compression was causing some blocks in the jpeg to be like 99% opaque, but they are getting clipped entirely by the shader.

**Comment by invertednormal** [comment]
I don't think there's any work to do here, cutout alpha is a per-pixel boolean operation. AA is needed to make it look smooth. TAA or SMAA probably solve this problem reasonably well.
