### ISSUE TITLE
Editor does not start on Windows fresh builds

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#14767]
**Describe the bug**
If the Editor was built from a fresh o3de/o3de repository clone (meaning all files related to past builds were removed before cloning/building), the Editor will crash before opening the window. This occurred on:
* Source and Pre-built SDK engine build.
* Default and Minimal Template projects, as well as a project with all Gems enabled.
* DX12 and Vulkan RHIs.

Additionally asserts can be seen in the Editor.log after the crash occurs:
* RPISystem.cpp(252)
* RPISystem.cpp(258)
* RPISystem.cpp(264)

For more information please refer to the **Video, failed assets, Editor.log, error.log and error.dmp** section.

Updating GPU drivers to the latest version did not resolve this issue (for reference driver used on my machine was Game Ready Driver Version 528.49 for the NVIDIA GeForce RTX 2060 SUPER).

This issue did not occur on Linux nor on Windows if the build was updated (latest commit was fetched and merged to existing build without deleting its files).

This issue can be related to https://github.com/o3de/o3de/issues/14069.

**Steps to reproduce**
1. Build a project.
2. Launch the Editor on that project.

**Expected behavior**
Editor launches.

**Actual behavior**
`O3DE Fatal Error - RPI System could not initialize correctly. Check log for detail.` pops up. Editor crashes before opening up.

**Video, failed assets, Editor.log, error.log and error.dmp**

https://user-images.githubusercontent.com/86952082/220894591-4c332be1-e091-4c80-bd9a-ff1c164ee118.mp4

![FailedAssets](https://user-images.githubusercontent.com/86952082/220894861-7ec8bf58-86a9-487f-9587-09d560309969.png)

[Editor.log](https://github.com/o3de/o3de/files/10813075/Editor.log)
[error.log](https://github.com/o3de/o3de/files/10813078/error.log)
[error.zip](https://github.com/o3de/o3de/files/10813081/error.zip)

**Found in Branch**
Development (0dcc790)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
0dcc79054d5eb1fa71ebe609348e2571bb9b13cc

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-ArturZieba** [comment]
This issue did not occur on Development (7607430) build.

**Comment by galibzon** [comment]
Fixed.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (3f0b4de) build.
