### ISSUE TITLE
Material Tools' Viewport doesn't display models when using most Render Pipelines

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14770]
**Describe the bug**
The Viewport model isn't visible when using any other Render Pipeline than the Main Render Pipeline. In the Material Canvas, after adding any Material Output it becomes visible with the settings used in the PBR. In the Material Editor this issue occurs on any type of document except Material Graph Name.

This issue occurs on both Linux and Windows, although on Windows it is only visible on Low Render Pipeline due to [14596](https://github.com/o3de/o3de/issues/14596).

**Steps to reproduce**
1. Open the Material Canvas/Editor
2. Change Render Pipeline to anything **but** the Main Render Pipeline in the Viewport

**Expected behavior**
The Viewport model is visible in the Viewport.

**Actual behavior**
The Viewport model is not visible in the Viewport when using any other Render Pipeline than the Main Render Pipeline.

**Screenshots/Video**
https://user-images.githubusercontent.com/110163473/220915942-fd88f20a-c214-4464-aaa0-24219bf92ed0.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
0dcc790

**Desktop/Device (please complete the following information):**
- Device: PC
- OS: Windows
- Version: 11 22H2
- CPU: I7-11700f
- GPU: Geforce RTX3070 MSI
- Memory: 32GB

**Comment by galibzon** [comment]
@VickyAtAZ

**Comment by moudgils** [comment]
This is happening because the person did not add the pipeline to material_pipelines.setreg which is a new change as part of material override work. For context look at my comment in discord here - https://discord.com/channels/805939474655346758/869974333009854464/1086862458662174770

**Comment by moudgils** [comment]
https://github.com/o3de/o3de/pull/15439 should fix this
