### ISSUE TITLE
Track View: Adding Motion track to Simple Motion component node results in an assert

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#14801]
**Describe the bug**
Adding Motion track to Simple Motion component node results in the following assert being printed in the console:

**File:** 
`/home/gpc-589/o3de/Gems/Maestro/Code/Source/Cinematics/AnimTrack.h`

**Condition:**  
```
(140188788076928) 'virtual void TAnimTrack<AZ::IAssetBlendKey>::SetValue(float, const Maestro::AssetBlends<AZ::Data::AssetData> &, bool) [KeyType = AZ::IAssetBlendKey]'
(System) - 0
```

**Line:**
 `176`

The issue occurs with and without assets being assigned to the Actor or Simple Motion components.
Please refer to the attached video and log for more information.

**Steps to reproduce**
1. Create an entity.
2. Add Actor and Simple Motion components to it.
3. Open Track View.
4. Select 'Add Sequence'.
5. In the Entity Outliner select the created entity from Step 1. and RMB in the empty Track View's new sequence's node browser.
6. Press 'Add Selected Entity'.
7. RMB on the Simple Motion component node and select Add Track -> Motion -> Motion.

**Expected behavior**
The track is added without any issues.

**Actual behavior**
Adding the Motion track results in an assert being printed in the console.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/221185266-41c486dd-9d2a-48ab-99dd-b9c411a5be25.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[37b6a48](https://github.com/o3de/o3de/commit/37b6a48ccae8efa3da8a7c2295cd34b38d1d5b1f)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/10824308/Editor.log)

**Comment by Aleks-Starykh-TR** [comment]
PR https://github.com/o3de/o3de/pull/18495 merged
