### ISSUE TITLE
Animation Editor: Delete key does not work in AnimGraph graphs

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#14827]
**Describe the bug**
In the Animation Editor, it is not possible to delete selected nodes and transitions by pressing Delete key in the AnimGraph graphs.

Note, that it is still possible to delete nodes and transitions by using context menu.

**Steps to reproduce**
1. Open the Animation Editor.
2. Create a new AnimGraph.
3. Add two nodes to the graph (e. g. Motion nodes).
4. Create a transition between two nodes.
5. Select the transition or node.
6. Press Delete key.

**Expected behavior**
Selected nodes and transitions can be deleted in AnimGraph graph by using Delete key.

**Actual behavior**
Selected nodes and transitions cannot be deleted by using Delete key in AnimGraph graphs.

**Video**

https://user-images.githubusercontent.com/86951967/221552689-e3556432-70c2-4d52-8f52-0ebd5f577b74.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
76074304573950182e2d48283ff4b01b798bab03

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by AMZN-daimini** [comment]
Moving to `sig/content` `feature/editor` to verify if it's related to the recent Action Manager changes.

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed on build Development (ba791dc).
