### ISSUE TITLE
Editor crashes in EditorActionsHandler

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#14822]
**Describe the bug**
Randomly the Editor crashes

**Assets required**
Any level would do.

**Steps to reproduce**
In the Editor, do work in a level, add components, move between different Editor menus, etc until it crashes.

**Expected behavior**
The Editor doesn't crash

**Actual behavior**
At random times in between doing Editor related actions, the Editor crashes

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/66021303/221424968-425df47a-5010-4cfa-bdbe-90feb81ad3fc.png)

**Found in Branch**
commit 76074304573950182e2d48283ff4b01b798bab03 (upstream/development, development)
Author: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>
Date:   Fri Feb 24 17:19:34 2023 -0600

    Test Impact Analysis Framework clang build fixes (#14789)

    Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen Threadripper 3970X 32-Core Processor    3.70 GHz
 - GPU NVidia RTX 4090 (24GB VRAM)
 - Memory 128GB
 - Storage: WD_BLACK 2TB SN850 NVMe M2 SDD PCIe 4.0
 

**Additional context**
Callstack:
```
 	Qt5Cored.dll!00007ffe68eaca51()	Unknown
>	EditorLib.dll!EditorActionsHandler::IsRecentFileEntryValid(const QString & entry, const QString & gameFolderPath) Line 2094	C++
 	EditorLib.dll!EditorActionsHandler::UpdateRecentFileActions() Line 2177	C++
 	EditorLib.dll!EditorActionsHandler::OnMenuRegistrationHook::__l4::<lambda_1>::operator()() Line 1589	C++
 	EditorLib.dll!QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,`EditorActionsHandler::OnMenuRegistrationHook'::`4'::<lambda_1>>::call(EditorActionsHandler::OnMenuRegistrationHook::__l4::<lambda_1> & f, void * * arg) Line 146	C++
 	EditorLib.dll!QtPrivate::Functor<`EditorActionsHandler::OnMenuRegistrationHook'::`4'::<lambda_1>,0>::call<QtPrivate::List<>,void>(EditorActionsHandler::OnMenuRegistrationHook::__l4::<lambda_1> & f, void * __formal, void * * arg) Line 257	C++
 	EditorLib.dll!QtPrivate::QFunctorSlotObject<`EditorActionsHandler::OnMenuRegistrationHook'::`4'::<lambda_1>,0,QtPrivate::List<>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 449	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 3996	C++
 	Editor.exe!AZStd::Internal::INVOKE<int (__cdecl*&)(int,char * * const),int &,char * * &>(int(*)(int, char * *) & f, int & <args_0>, char * * & <args_1>) Line 209	C++
 	Editor.exe!AZStd::invoke<int (__cdecl*&)(int,char * * const),int &,char * * &>(int(*)(int, char * *) & f, int & <args_0>, char * * & <args_1>) Line 55	C++
 	Editor.exe!main(int argc, char * * argv) Line 31	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
 	[External Code]	
```

**Comment by galibzon** [comment]
FYI: @lsemp3d , @AMZN-daimini

**Comment by hultonha** [comment]
Checking is this PR related? https://github.com/o3de/o3de/pull/14821

**Comment by AMZN-daimini** [comment]
> Checking is this PR related? #14821

Yes, but I think I have a better refactoring. Will post a PR soon.

**Comment by hultonha** [comment]
> > Checking is this PR related? #14821
> 
> Yes, but I think I have a better refactoring. Will post a PR soon.

Okay perfect thanks 🙂
