### ISSUE TITLE
LuaIDE Breakpoint Step Marker randomly goes out of sync when "Lua Locals" are enabled.

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#14823]
**Describe the bug**
When debugging Lua scripts with LuaIDE.exe, and "Lua Locals" are enabled, the  debug step marker stops moving, even though you may still "Step Over" lines of code. When LuaIDE.exe enters in this bad state, you'll have to remove the breakpoints, run "Continue", and detach from the Editor. And kill the LuaIDE.exe to start anew.

**Assets required**
[LuaLocalsTest.zip](https://github.com/o3de/o3de/files/10834375/LuaLocalsTest.zip)
Unzip the attached level into `<Game>/Levels/` folder.

**Steps to reproduce**
1. In the Editor.exe Open the attached `LuaLocalsTest` Level, let's say in the AutomatedTesting/ game project.
2. In the `Entity Outliner`, select the **EntityMover** entity, In the **Lua Script** component click the `Open In Lua Editor` button.
3. Wait until LuaIDE.exe loads `entity_mover.lua`.
4. In LuaIDE.exe attach to Editor.exe.
5. In LuaIDE.exe click the `Lua Locals` button which should open the `Lua Locals` panel.
6. Place a breakpoint in line 36 of `entity_mover.lua` (just below `function entity_mover:OnTick(deltaTime, timePoint)`).
7. In Editor.exe enter game mode (Ctrl + G).
8. The LuaIDE should regain focus and the red Breakpoint should be in the same position as the "Breakpoint Step Marker" (green triangle).
9. Click "Step Over" until the   "Breakpoint Step Marker" (green triangle) stops moving and LuaIDE.exe becomes visually unresponsive. Sometimes you may end up stepping 5 times over the "OnTick" function, but most of the time within a few "Step Over" events the bug occurs.

**Expected behavior**
You should be able to "Step Over" as needed and the "Breakpoint Step Marker" (green triangle) should move to the next line as you "Step Over".

**Actual behavior**
Eventually  the "Breakpoint Step Marker" (green triangle) stops moving to the next line as you click "Step Over"

**Screenshots/Video**
In this picture, the LuaIDE is already stuck. The  "Breakpoint Step Marker" (green triangle)  doesn't move anymore and and the "Lua Locals" panel stops updating.
![image](https://user-images.githubusercontent.com/66021303/221429225-8a100912-ab64-4084-b941-a7dd6bac9b81.png)

**Found in Branch**
commit https://github.com/o3de/o3de/commit/76074304573950182e2d48283ff4b01b798bab03 (upstream/development, development)
Author: lumberyard-employee-dm [56135373+lumberyard-employee-dm@users.noreply.github.com](mailto:56135373+lumberyard-employee-dm@users.noreply.github.com)
Date: Fri Feb 24 17:19:34 2023 -0600

**Desktop/Device (please complete the following information):**
    Device: PC
    OS: Windows
    Version 11
    CPU AMD Ryzen Threadripper 3970X 32-Core Processor 3.70 GHz
    GPU NVidia RTX 4090 (24GB VRAM)
    Memory 128GB
    Storage: WD_BLACK 2TB SN850 NVMe M2 SDD PCIe 4.0

**Additional context**
It is very important to have the `Lua Locals` panel open for this bug to reproduce.

**Comment by galibzon** [comment]
FYI @lsemp3d

**Comment by galibzon** [comment]
I've been debugging this issue and noticed, that once the bug starts, the LuaIDE still sends tcp packets to the Editor.  
The Editor appears as never receiving those packets. But a low level breakpoint in `TcpConnection::ReceivePacketInternal` it is receiving packets, and the problem appears to be in m_recvRingBuffer which somehow reads bad TcpHeader data and the sizes do not match causing an early return here:  
```
    bool TcpConnection::ReceivePacketInternal(TcpPacketHeader& outHeader, TcpPacketEncodingBuffer& outBuffer, AZ::TimeMs currentTimeMs)
    {
        NetworkOutputSerializer serializer(m_recvRingbuffer.GetReadBufferData(), m_recvRingbuffer.GetReadBufferSize());
        if (!outHeader.Serialize(serializer))
        {
            return false;
        }

        uint16_t packetSize = outHeader.GetPacketSize();
        const uint32_t unreadSize = serializer.GetUnreadSize();
        if (packetSize > unreadSize)
        {
            // We don't have all the data required for this packet yet
            return false;
        }
```
Will run wireshark to see if the data sent by LuaIDE is fine, or the m_ringBuffer in Editor.exe that is corrupted.

**Comment by lumberyard-employee-dm** [comment]
@o3de/sig-content What are your thoughts on this ticket? 
Is the Lua IDE slated for replacement with a VS Code plugin?

**Comment by lumberyard-employee-dm** [comment]
Thanks @galibzon !
