### ISSUE TITLE
Play in editor (ctrl + g) doesn't work when AWSGameLift gem is enabled

### ISSUE THREAD

**Issue by allisaurus** [o3de/o3de#14848]
**Describe the bug**
After enabling the AWSGameLift gem on the project by adding it to the list of enabled gems and adding the `Gem::AWSGameLift.Client.Static` and `Gem::AWSGameLift.Server.Static` targets to the game's client & server targets, the Editor and launchers build, but fail to run with the following errors:

```
...
(MultiplayerEditor) - Editor TCP connection attempt #2.
[Error] (EditorServer) - [2023-02-27 13:49:46] [info] asio async_connect error: system:10061 (No connection could be made because the target machine actively refused it)
[Error] (EditorServer) - [2023-02-27 13:49:46] [info] Error getting remote endpoint: system:10057 (A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied)
[Error] (EditorServer) - [2023-02-27 13:49:46] [error] handle_connect error: Underlying Transport Error
(MultiplayerEditor) - Editor TCP connection attempt #3.
[Error] (EditorServer) - [2023-02-27 13:49:53] [info] asio async_connect error: system:10061 (No connection could be made because the target machine actively refused it)
[Error] (EditorServer) - [2023-02-27 13:49:53] [info] Error getting remote endpoint: system:10057 (A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied)
[Error] (EditorServer) - [2023-02-27 13:49:53] [error] handle_connect error: Underlying Transport Error

... (eventually stops trying after failed attempt #5)
```

**Assets required**
A working O3DE multiplayer game, such as [o3de-multiplayersample](https://github.com/o3de/o3de-multiplayersample)

**Steps to reproduce**
1. Follow [the instructions to enable the AWS GameLift gem](https://www.o3de.org/docs/user-guide/gems/reference/aws/aws-gamelift/gem-setup/#2-enable-the-aws-gamelift-gem)
2. Rebuild the project editor and server launcher
3. Start the editor
4. Hit `ctrl` + `g` to start playing
5. See error logs described above

**Expected behavior**
In-editor play of the multiplayer game would work.

**Actual behavior**
Game play did not work, appears server failed to start.

**Found in Branch**
development, `40682b7ef30`

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - CPU:  Intel
 - GPU: NVidia RTX 3070
 - Memory: 16GB

**Comment by lmbr-pip** [comment]
Would assume logs would tell us the server address and port. But would assume as crtrl+g experience has changed a lot, no recent testing has occurred with the older GameLift gem.

**Comment by allisaurus** [comment]
After some more debugging, it seems the server launcher gets stuck on an a call to `Aws::GameLift::Server::InitSDK()` not returning.  

Running [GameLiftLocal](https://docs.aws.amazon.com/gamelift/latest/developerguide/integration-testing-local.html) on my machine before playing in-editor with `ctrl` + `g` allows that call to proceed and the server eventually launches, so that's a workaround until we come up with a way to skip that call when no GL process is actually available. 

Will work on adding a CVAR to skip this call by default.

**Comment by allisaurus** [comment]
resolved by: https://github.com/o3de/o3de/pull/14964
