### ISSUE TITLE
Action Manager: Lua Editor is not available from the Tools menu with the Action Manager enabled

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#14845]
**Describe the bug**
 Lua Editor is not available from the Tools menu with the Action Manager enabled.

**Steps to reproduce**
1. Launch the Editor.
2. From the Tools menu, attempt to open the Lua Editor.

**Expected behavior**
Lua Editor is available via the Tools menu.

**Actual behavior**
Lua Editor option is not present in the Tools menu. Likely related to the same issue that caused https://github.com/o3de/o3de/issues/12563.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
945c0ee96955487f0fabc35deaff1ea6629a4fd3

**Comment by AMZN-daimini** [comment]
Working on it. In case you need a workaround, the Lua Editor is still accessible by creating/accessing a Lua Component on an entity and clicking on the "open" button next to the asset selection, or via the Asset Browser via a lua asset (although this last option could still be hidden behind a flag? Not sure).
