### ISSUE TITLE
Asset Browser: Min-width for docked Asset Browser Inspector is unusable

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#14842]
**Describe the bug**
Min-width for docked Asset Browser Inspector is unusable.

**Steps to reproduce**
1. Launch the Editor and enable WIP Asset Browser features via the Console:
```
ed_useWIPAssetBrowserDesign true
```
2. Open the Asset Browser, and select any asset.
3. Open the Asset Browser Inspector and dock the window NOT on the Entity Inspector window.
4. Resize the docked Asset Browser Inspector to it's smallest allowed width.

**Expected behavior**
Tool remains usable when resized.

**Actual behavior**
Text wraps un-intuitively and tool is largely unusable.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82226555/221679775-187ab9d9-863f-43e9-83e9-49b3879adef6.png)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
945c0ee96955487f0fabc35deaff1ea6629a4fd3

**Comment by AMZN-daimini** [comment]
Would a horizontal scrollbar suffice, or do we want a larger min-width? I remember feedback from users that would make panels really thin temporarily as part of their workflow, so I'd go for the former (narrow min-width for the widget, scrollable area, larger min-width for the content) unless it makes things overly complicated.

**Comment by svitlani** [comment]
Min-width should be the same size Inspector Panel per UX AC
