### ISSUE TITLE
DPE View: Resizing DPE Entity Inspector will cut off property editor widgets

### ISSUE THREAD

**Issue by forkercat** [o3de/o3de#14864]
**Describe the bug**

Prerequisite: `ed_enableDPE` is on

Resizing entity inspector will cut off some property editor widgets.

Example: Translate/Rotate rows in Transform Component

**Steps to reproduce**
1. Enable DPE flag
1. Create an empty level
1. Create an entity
1. Resize entity inspector

**Expected behavior**

Like we're seeing in RPE Entity Inspector, the property editor widgets get resized correctly.

**Actual behavior**

<img width=300px src="https://user-images.githubusercontent.com/11157226/222003517-f98c8438-68f5-42a8-b8ae-fab7423528bd.png">

**Screenshots/Video**

See screenshot above

**Found in Branch**

Development

**Desktop/Device**
* Device: PC
* OS: Windows 10
* CPU: AMD Ryzen 5950x
* GPU: NVIDIA RTX 3070
* Memory: 64 GB

**Additional context**

None

**Comment by alexmontAmazon** [comment]
Intermediate fix: re-enable horizontal scrollbar  as needed
