### ISSUE TITLE
Reflection: Component properties are different in DPE Inspector than in RPE

### ISSUE THREAD

**Issue by forkercat** [o3de/o3de#14869]
**Describe the bug**

Prerequisite: `ed_enableDPE` is on

Some component properties are not consistent between DPE and RPE inspectors.

Example: Camera Component

**Steps to reproduce**
1. Enable DPE flag
1. Create an empty level
1. Create an entity with Camera Component and see it in Entity Inspector

**Expected behavior**

RPE Entity Inspector:

<img width=400px src="https://user-images.githubusercontent.com/11157226/222007363-21e1ae90-d7e7-4b12-a8c0-fae1ed53b18e.png">

**Actual behavior**

DPE Entity Inspector:

<img width=400px src="https://user-images.githubusercontent.com/11157226/222007405-ee631684-6616-49a3-8dc1-ff8f6c737224.png">

Arrangement is different. FOV is new in DPE.

**Screenshots/Video**

See screenshots above

**Found in Branch**

Development

**Desktop/Device**
* Device: PC
* OS: Windows 10
* CPU: AMD Ryzen 5950x
* GPU: NVIDIA RTX 3070
* Memory: 64 GB

**Additional context**

None

**Comment by cgalvan** [comment]
The various issues mentioned in this bug have been split out into specific bugs #16060 and #16070
