### ISSUE TITLE
Linux: mouse_delta_x listens to the mouse wheel input

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#14877]
**Describe the bug**
On Linux, *mouse_delta_x* Input listens to both the mouse X axis movement and the mouse wheel scrolling. Mouse wheel scrolling should be picked up only by the *mouse_delta_z* Input.

This issue does not occur on Windows.

**Assets required**
Script Canvas and Input Bindings shown on the image below are required to reproduce this issue:
![mouse_delta_xSCandIB](https://user-images.githubusercontent.com/86952082/222140781-9fc7e736-b0ac-489d-831d-c0df473321f3.png)

**Steps to reproduce**
1. Create an entity, add *Script Canvas* and *Input* components to it.
2. Assign assets mentioned in the **Assets required** section to their respective components.
3. Enter the Game Mode (for example *Ctrl + G*).
4. Scroll the mouse wheel.

**Expected behavior**
Nothing happens.

**Actual behavior**
Script Canvas prints output to the Console.

**Video**

https://user-images.githubusercontent.com/86952082/222140406-25d5c95d-b617-4e75-9dad-6cc914c854f7.mp4

**Found in Branch**
Development (a775010)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
a775010c5c3ea6b067df2ef0a398fbe02bb54434

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gralco** [comment]
I can verify this also happens on my end, this has been the case in 2210 and 2305.

**Comment by nick-l-o3de** [comment]
This happens on my end, but debugging into it, it seems like when I roll the mouse wheel, I get a `xcb_input_raw_motion_event_t` with an axis value that is legitimate:
```cpp
case XCB_INPUT_RAW_MOTION:
            {
                const xcb_input_raw_motion_event_t* mouseMotionEvent = reinterpret_cast<const xcb_input_raw_motion_event_t*>(event);

                int axisLen = xcb_input_raw_button_press_axisvalues_length(mouseMotionEvent);
                const xcb_input_fp3232_t* axisvalues = xcb_input_raw_button_press_axisvalues_raw(mouseMotionEvent);
                for (int i = 0; i < axisLen; ++i)
                {
                    const float axisValue = fp3232ToFloat(axisvalues[i]);

                    switch (i)
                    {
                    case 0:
                        QueueRawMovementEvent(InputDeviceMouse::Movement::X, axisValue);
                        break;
                    case 1:
                        QueueRawMovementEvent(InputDeviceMouse::Movement::Y, axisValue);
                        break;
                    }
                }
            }
            ```
It enters the Movement::X block...  Note that this same thing happens when you move the mouse around horizontally.  I'm not sure why I'm getting a horizontal axis event from XCB when I only roll the mouse wheel.  Perhaps there is something else in the event that informs that its a wheel event

**Comment by nick-l-o3de** [comment]
There's nothing in the event struct (I inspected it in the debugger) coming from XCB to discern between a mouse axis (x and y movement) and wheel event.  The device id and other fields are identical.   Maybe there's some way to discern in the XCB api?

**Comment by nick-l-o3de** [comment]
I think I figured it out.  I'll upload a fix soon.  It looks like in XCB (poorly documented) a xcb_input_raw_motion_event_t is also a raw button press, and inside that struct is a valuator bitmask.
so this code should fix it
``cpp
uint32_t mask = *(xcb_input_raw_button_press_valuator_mask(mouseMotionEvent));
                if ((mask[0] & 0x3) == 0)
                {
                    // x and y movement are not present in the mask.  This is not necessarily a wheel roll,
                    // but its also not x and y movement.  What it is depends on how many axes the device actually has.
                    // Since we capture wheel roll as button presses (above), ignore this.
                    break;
                }
                ```

**Comment by nick-l-o3de** [comment]
Note that my solution was chosen since it impacts the smallest amount of code I could find.

Another solution would be to stop using the button press wheel and use the axis instead.    Or add a new axis to the mouse input API in O3DE that represents 'smooth' scrolling from the axis rather than 'wheel clicks'.
