### ISSUE TITLE
Feature Request: Add a way to change gizmo center position on edited White Box components

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#14880]
**Is your feature request related to a problem? Please describe.**
*White Box* components always keep their gizmo wherever it was in the original shape (for example Cube has the gizmo in its center). Significantly modifying the White Box can put this gizmo in a position where it is for example difficult to snap the White Box's base to the face of another mesh or simply rotate it.

**Describe the solution you'd like**
There should be a way to somehow move gizmo of the White Box component. Being able to snap it to vertices, lines, faces or just adjust it freely to any position would help with White Box workflows.

**Additional context**
Sample video of the described problem:

https://user-images.githubusercontent.com/86952082/222152878-1d0dacaf-aa42-4033-9088-7542cf80bde8.mp4

**Comment by pollend** [comment]
is this what you are talking about: https://github.com/o3de/o3de/pull/9925

its disabled behind a CVAR umm not sure where this was left off though ...

**Comment by LB-ArturZieba** [comment]
Hi @pollend, I believe that #9925 is not related to this Feature Request, however I have noticed that center/origin point of any entity can be moved by using Ctrl+Left-click. This behavior solves the need for this Feature Request. Closing the issue.
