### ISSUE TITLE
[Linux] get_python script does not work in the newest installer build on Ubuntu 22.04

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#14902]
**Describe the bug**
There is an issue with launching the Editor from installer build on Linux Ubuntu 22.04. When launching the newest installer Project Manager on the machine the pop up widow to register the engine is displayed. After confirming registration the window attempts to use python/get_python.sh script which fails as shown on the screenshot. When running the get_python.sh through terminal the effect is the same as in the pop up window.

The device uses openssl 3.0.2.

This bug may be related to the following issue: https://github.com/o3de/o3de/issues/11640

**Steps to reproduce**
1. Download the file from: https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb.
2. Open a terminal in the download folder.
3. Run commands in the terminal window:
``sudo chown -Rv _apt:root /var/cache/apt/archives/partial/``
``sudo chmod -Rv 700 /var/cache/apt/archives/partial/ `` 
``sudo apt install  ~/Downloads/<debian_package_name>.deb ``
4. Open the second terminal window in the location: 
``/opt/O3DE/1.0.0/bin/Linux/profile/Default``
6. Run command in the second terminal:
``sudo ./Editor``
8. Click OK in the window that pops up.

**Expected behavior**
Get_python.sh script is run and Project Manager is opened.

**Actual behavior**
Get_python.sh script fails to run and editor cannot be launched.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/86953282/222424675-aacdfc72-a3c8-4063-9262-fd0fbf094160.png)

**Found in Branch**
(https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb)

**Desktop:**
• Device: PC
• OS: Linux
• Version: Ubuntu 22.04.2 LTS
• CPU: Intel Core i7 11700F
• GPU: Nvidia RTX 3070 LHR
• Memory: 32GB

**Comment by byrcolin** [comment]
I think there might be a fix for this already, I'll look into it. I think it was that the package was not listed on the install instructions for linux.

**Comment by LB-KacperMetelski** [comment]
Issue verified as fixed on the latest development branch (8b58313).

**Comment by amzn-changml** [comment]
There's a related issue in the snap package. The python runtime is not able to be used and cannot write into the snap install directory, as it's read-only. See screenshots below:

![image](https://user-images.githubusercontent.com/62353586/233511631-233f8441-8687-42a6-8d55-c3c3e3950ae0.png)

![image](https://user-images.githubusercontent.com/62353586/233511574-c6ff6b3e-fa60-42e3-be75-17aa8672c49f.png)

![image](https://user-images.githubusercontent.com/62353586/233511751-c63f8881-7113-4eff-b8af-15ae455525ac.png)

**Comment by LB-KacperSzczepanski** [comment]
Using today's Stabilization/2305 installer (https://o3debinaries.org/stabilization-2305/Latest/Linux/O3DE_latest.deb) the popup window from the issue does not open and Project Manager window opens instead but core of the issue remains when attempting to build any project. Building a project fails immediately due to OPENSSL_1_1_1 not being found.
![image](https://user-images.githubusercontent.com/86953282/234236281-cf34abf7-fc1b-4126-a366-3ff1fb0976fd.png)

Should this be reported as a separate issue?

**Comment by amzn-changml** [comment]
Yes, please report this as a separate issue

**Comment by amzn-changml** [comment]
Tested the latest stabilization build and it appears that the issue has been resolved as of [434dcf0](https://github.com/o3de/o3de/commit/434dcf02a78e069a67801aef20dde1be833de706). Python does not write to the snap folder and detects the pre-packaged runtime on startup. @LB-KacperMetelski can you confirm this on your end?

**Comment by AMZN-alexpete** [comment]
@amzn-changml were both issues resolved in your test? (OPENSSL_1_1!- and python doesn't write to snap folder)

**Comment by LB-KacperSzczepanski** [comment]
Closing the issue as it doesn't occur on today's Stabilization/2305 installer (https://o3debinaries.org/stabilization-2305/Latest/Linux/O3DE_latest.deb).

**Comment by amzn-changml** [comment]
> @amzn-changml were both issues resolved in your test? (OPENSSL_1_1_1- and python doesn't write to snap folder)

I only tested the python write location issue, but I didn't see any errors with OpenSSL when opening project manager in the snap package. It built and created a dummy project without issue.
