### ISSUE TITLE
The Toggle Shadow Catcher button tooltip in Material Editor has additional empty text line

### ISSUE THREAD

**Issue by LB-MateuszPlatakis** [o3de/o3de#14901]
**Describe the bug**
The "Toggle Shadow Catcher" button in the Material Editor has a tooltip that is not aligned with the text and has one unnecessary empty line of text.

This issue occurs on both Windows and Linux systems.

**Steps to reproduce**

1. Open the Editor.
2. Open Tools -> Material Editor.
3. Hover the mouse over the "Toggle Shadow Catcher" button and observe the issue.

**Expected behavior**
All tooltip sizes are aligned with the tooltip text.

**Actual behavior**
The "Toggle Shadow Catcher" button tooltip in Material Editor has an additional empty text line.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/119418207/222443542-0c6584c1-1238-4822-94a2-ee7e24abe7bd.png)

https://user-images.githubusercontent.com/119418207/222443464-728d35b7-90f1-42e7-858d-1511ee392cd9.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[ba791dc](https://github.com/o3de/o3de/commit/ba791dc178da125b1c07eec544d22c6719565b0f)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: Windows 10 Pro
- CPU: Intel® Core™ i7-9700K CPU @ 3.60GHz × 8
- GPU: NVIDIA GeForce RTX 2070
- Memory: 16GB

**Comment by gadams3** [comment]
There is no special formatting for this tool tip. There are no line breaks in the string that's being displayed. Not sure why the tooltip code is causing the line to break and wrap at the end of the string.

**Comment by LB-MateuszPlatakis** [comment]
Confirming the issue has been closed as not planned.
