### ISSUE TITLE
Material Canvas: Asset processing fails when PBR Node Groups are being continuously collapsed and expanded

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14903]
**Describe the bug**
Collapsing and expanding Node Groups containing multiple Material Output Nodes may cause the Asset Processor to fail processing the untitled_DepthPass.shader; moreover, there is a slight chance that the processing may fail indefinitely (the Viewport is stuck with the base material) until the user decides to save the Material Graph.

The reproduction rate of this issue may vary greatly due to timing in which the Group is collapsed/expanded.

**Steps to reproduce**
1. Open the Material Canvas.
2. Add both Material Outputs(PBRs).
3. Group them.
4. Collapse and expand the group at least 4 times.

**Expected behavior**
Assets are processed successfully.

**Actual behavior**
Asset processor fails to process the asset. (rarely)
![image](https://user-images.githubusercontent.com/110163473/222438427-9107fba0-c71c-4a3c-aff3-0a709d247d80.png)

**Screenshots/Video**
https://user-images.githubusercontent.com/110163473/222448519-874e43d1-c8e4-4909-9adb-dffd10013895.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
ba791dc

**Desktop/Device (please complete the following information):**
- Device: PC
- OS: Windows
- Version: 11 21H2
- CPU: I7-11700f
- GPU: Geforce RTX3070 MSI
- Memory: 32GB

**Comment by galibzon** [comment]
@gadams3

**Comment by LB-KacperMetelski** [comment]
Issue verified as fixed on commit 3a3fce2.
