### ISSUE TITLE
Scrollbar in Viewport Camera Selector doesn't work correctly

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14925]
**Describe the bug**

The scrollbar in the Viewport Camera Selector doesn't move alongside the entity's selection when the arrow keys are being used.

This issue occurs both on Windows and Linux.

**Steps to reproduce**
1. Spawn 10 Entities with the Camera Component.
2. Open Viewport Camera Selector and make sure that the slider is present.
3. Select one of the cameras and use down arrow key to navigate to the bottom of the list.

**Expected behavior**
The list is scrolled down alongside the selection.

**Actual behavior**
The list isn't scrolled down.

**Screenshots/Video**
[Video](https://user-images.githubusercontent.com/110163473/222742145-85f4c581-6cd9-45a8-985f-d2e18969e907.mp4)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
15fce3e

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 11 21H2
- CPU: I7-11700f
- GPU: Geforce RTX3070 MSI
- Memory: 32GB

**Comment by hultonha** [comment]
@LB-KacperMetelski would it be possible to please include a video demonstrating the issue. I think I understand what's happening but seeing it in the issue would be super helpful. Thanks!
