### ISSUE TITLE
Multiple instances of AWS Resource Mapping and missing credential warning pop-up can be opened

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14924]
**Describe the bug**
The AWS Resource Mapping Tool or missing credential window doesn't close alongside the Editor, and it can be open multiple times after restarting the Editor.

**Steps to reproduce**
1. Open the AWS dropdown menu in the upper section of the Editor.
2. Select the Resource Mapping Tool.
3. Restart Editor.
4. Repeat steps 1. to 3. twice.

**Expected behavior**
The AWS Resource Mapping Tool window closes alongside the Editor.

**Actual behavior**
The AWS Resource Mapping Tool window doesn't close alongside the Editor.

**Screenshots/Video**
[Video](https://user-images.githubusercontent.com/110163473/222735092-a5ae1d80-1a0e-4fc7-90cb-821c39b50dbb.mp4)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/15fce3e12665ef38a760a3067fbe202a1d2f2748

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 11 21H2
- CPU: I7-11700f
- GPU: Geforce RTX3070 MSI
- Memory: 32GB

**Comment by lmbr-pip** [comment]
Seems like a logic bug as we use a process watcher here: https://github.com/o3de/o3de/blob/3606388ce5ff481f7d6ef76b1de44dfc642fc911/Gems/AWSCore/Code/Source/Editor/UI/AWSCoreEditorMenu.cpp#L26

**Comment by lmbr-pip** [comment]
On latest windows, if I try to open Resource Manager again I get a popup warning `Resource Mapping Tool is running...`

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as fixed in the latest development branch (9c8d4f2).
