### ISSUE TITLE
AWS Resource Mapping tool broken link

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14923]
**Describe the bug**
The link provided in the missing AWS credential pop-up leads to the non-existing page.

**Prerequisites**
No valid AWS credentials in .aws folder.

**Steps to reproduce**
1. Open the AWS dropdown menu in the upper section of the Editor.
2. Select the Resource Mapping Tool.
3. Click on the [documentation](https://docs.o3de.org/docs/user-guide/gems/reference/aws/aws-core/configuring-credentials/) hyperlink.

**Expected behavior**
The pop-up leads to a correct [documentation page](https://www.o3de.org/docs/user-guide/gems/reference/aws/aws-core/configuring-credentials/).

**Actual behavior**
The pop-up contains a [broken link](https://docs.o3de.org/docs/user-guide/gems/reference/aws/aws-core/configuring-credentials/).

**Screenshots/Video**
[Video](https://user-images.githubusercontent.com/110163473/222726689-4463b38d-e05f-486e-b06b-610d4b881bf1.mp4)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
15fce3e

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 11 21H2
- CPU: I7-11700f
- GPU: Geforce RTX3070 MSI
- Memory: 32GB

**Comment by lmbr-pip** [comment]
Fixed in https://github.com/o3de/o3de/pull/15011

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as fixed in the latest development branch (9c8d4f2).
