### ISSUE TITLE
[MacOS] Building the latest Development branch fails

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#14921]
**Describe the bug**
Building --target Editor on macOS fails. The following error appears:

```
/Users/macpro14/github/o3de/Code/Framework/AzCore/AzCore/Math/Uuid.h:134:9: note: candidate constructor not viable: cannot convert argument of incomplete type 'void' to 'const GUID &' (aka 'const _GUID &') for 1st argument
        Uuid(const GUID& guid);
        ^
/Users/macpro14/github/o3de/Code/Framework/AzCore/AzCore/Math/Uuid.h:51:28: note: explicit constructor is not a candidate
        constexpr explicit Uuid(AZStd::string_view uuidString);
                           ^

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/macpro14/github/o3de/osx_build/External/Metal-69b2f455/Code/O3DE.build/profile/Atom_RHI_Metal.Private.build/Objects-normal/x86_64/unity_0_cxx.o /Users/macpro14/github/o3de/osx_build/External/Metal-69b2f455/Code/CMakeFiles/Atom_RHI_Metal.Private.dir/Unity/unity_0_cxx.cxx normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Atom_RHI_Metal.Private' from project 'O3DE')
(1 failure)
Elapsed time: 742 s. (time), 0.023279 s. (clock)
macpro14@macpro14s-macbook-pro osx_build %
```

The issue has been confirmed on the following machines:
MacBook Pro 2019 Big Sur 11.6.1 XCode version 13.2.1

MacBook Air 2020 Ventura 13.0.1 XCode version 14.2

This issue occurs when building AutomatedTesting.

Please refer to the attached building logs for more information.

**Steps to reproduce**

1. Create new or move your preexisting 3rdParty folder containing CMake into the o3de folder.
2. Obtain python packages with get_python.sh script located in the o3de/python directory.
3. Create osx_build folder under the o3de location.
4. Set the following temporary environment variables in the Terminal:
`export PATH=$PATH:/Users/<home_folder_name>/github/o3de/3rdParty/CMake/CMake.app/Contents/bin`
`export LY_3RDPARTY_PATH=/Users/<home_folder_name>/github/o3de/3rdParty`
5. Configure and generate the Xcode solution using this command:
`cmake .. -G "Xcode" -DLY_3RDPARTY_PATH=$LY_3RDPARTY_PATH -DLY_PROJECTS=AutomatedTesting -DLY_UNITY_BUILD=1 -DAZ_USE_PHYSX5=ON`
6. Build Mac binaries:
`cmake -E time cmake --build . --target ALL_BUILD --config profile -j 4`

**Expected behavior**
Building completes successfully.

**Actual behavior**
Building fails due to a command failure.

**Found in Branch**
Development

Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository
15fce3e

**Device :**
Device: Macbook Pro 2019
OS: macOS
Version: Big Sur 11.6.1
CPU: Intel i9
GPU: AMD Radeon Pro 5500M 4 GB
Memory: 16GB

**Additional context**
[building_fail_15fce3e.txt](https://github.com/o3de/o3de/files/10880583/building_fail_15fce3e.txt)

**Comment by galibzon** [comment]
Fixed by: https://github.com/o3de/o3de/pull/14932

**Comment by LB-KacperSzczepanski** [comment]
Issue verified as fixed on Development https://github.com/o3de/o3de/commit/3f0b4dee328f4f5f2381b30f690132ec3c345fc4 MacBook Air 2020 Ventura 13.0.1 XCode version 14.2.
