### ISSUE TITLE
Unable to download multiplayer template from Project Manager

### ISSUE THREAD

**Issue by willihay** [o3de/o3de#14968]
While trying to add the multiplayer template to an install of 22.10, when I try to download it using **Download Template** in Project Manager, I'm getting this security violation error now, indicating a manifest mismatch:

![image](https://user-images.githubusercontent.com/17654918/223177940-18ac1701-5169-46df-adfa-b0f34c497af8.png)

**Expected behavior**
Can use o3de-extras project template as a remote project template

**Actual behavior**
Security violation warning, but internally sha256s match.

**Comment by lawsonamzn** [comment]
Why is that second check done at all?  What security purpose (as in, proposed attack from a malicious person) does it cover that is not already covered by the hash check, or already vulnerable if the attacker gets to modify the repo.json anyway?

**Comment by Ulrick28** [comment]
Need to determine if this is a problem with the template, the remote repo settings, or project manager remote feature.
