### ISSUE TITLE
Script Canvas: The Delete hotkey does not work in Variable Manager

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#14977]
**Describe the bug**
It is not possible to delete a _Script Canvas_ _Variable_ using the _Delete_ key on the keyboard. 
Please note that other hotkeys (such as _CTRL+C_, _CTRL+V_, _CTRL+D_ to copy, paste or duplicate) work correctly.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Launch Script Canvas.
2. Create a new script.
3. Create a new Variable of any type.
4. Select the Variable in the _Variable Manager_.
5. Press the _Delete_ key on the keyboard.

**Expected behavior**
The Variable is deleted.

**Actual behavior**
Nothing happens.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/223425606-935e0701-d8c3-48c8-8e28-b32efc53dcfb.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
602b668

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by AMZN-daimini** [comment]
Fixed by the PR above.

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed on build Stabilization/2305 (169ab99), this issue still occurs on build Development (73e54c6) as the PR was merged only to Stabilization branch.
