### ISSUE TITLE
Script Canvas: Changing a Variable type from a non-container to any container type minimizes all O3DE windows

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#14979]
**Describe the bug**
If the Script Canvas Variable type is changed from a non-container (i.e. _Boolean_) to any container type (i.e. _Array_ of _Booleans_), all the O3DE windows minimize. 

Please note that this issue does not occur on Linux.

Refer to the attached video for more details.

**Steps to reproduce**
1. Launch Script Canvas.
2. Create a new graph.
3. Create a new Variable of any non-container type (i.e. _Boolean_).
4. Right click the Variable and select _Configure Variable_.
5. Change the Variable type to any container type (i.e. _Array_ of _Booleans_) and press OK.

**Expected behavior**
The Variable type changes. O3DE windows do not minimize.

**Actual behavior**
The Variable type changes. O3DE windows minimize.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/223436710-95424252-873e-49a5-9dfe-5fe61298b413.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
602b668

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development ([7291081](https://github.com/o3de/o3de/commit/72910817cc838ecf3aaae1fc0b2448ead354ee7d)).
