### ISSUE TITLE
[MacOS] Editor does not verify names length and restricted words

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#14976]
**Describe the bug**
An issue occurs when creating new file through O3DE or using Save As option. The created file can have any name including ones longer than 64 characters and "Default". Only found verification is for non alphanumeric characters, hyphens(-), underscore (_), and dots (.).  
This issue occurs when creating:

- Level
- Lua Script
- Script Canvas
- Any File from Asset Editor
- Landscape canvas
- Material
- UI Canvas
- Possibly more

**Steps to reproduce**
1. Open the Editor.
2. Create new level.
3. In pop up window write a name for the level that is longer than 64 characters.
4. Press OK.

**Expected behavior**
A warning pops up forbidding user from saving with set name.

**Actual behavior**
File of any name can be created through O3DE.

**Screenshots**
<img width="1792" alt="Level_Name" src="https://user-images.githubusercontent.com/86953282/223421967-6b2bbe74-d818-4813-946f-0e8069b504d5.png">
<img width="1156" alt="physxcanvas_Name" src="https://user-images.githubusercontent.com/86953282/223421973-ac334967-afcd-4cda-b4ea-eb5271dd55aa.png">
<img width="1487" alt="UIcanvas_Name" src="https://user-images.githubusercontent.com/86953282/223421977-b65ecc3c-9ce0-4e47-a15a-dbecdf322f52.png">

**Found in Branch**
Development

Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository
fde60c8

**Device :**
Device: Macbook Pro 2019
OS: macOS
Version: Big Sur 11.6.1
CPU: Intel i9
GPU: AMD Radeon Pro 5500M 4 GB
Memory: 16GB

**Comment by byrcolin** [comment]
It might be better to not allow than to warn.
