### ISSUE TITLE
Running Missing Dependency Scanner results in 1 error and 5 warnings

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#14974]
**Describe the bug**
Running Missing Dependency Scanner results in 1 error and 5 warnings, with no output about dependencies.

[MissingDependencyScannerOutputWINDOWS.txt](https://github.com/o3de/o3de/files/10909430/MissingDependencyScannerOutputWINDOWS.txt)
[MissingDependencyScannerOutputLINUX.txt](https://github.com/o3de/o3de/files/10909428/MissingDependencyScannerOutputLINUX.txt)

1. Build AssetProcessorBatch.
2. Process all of the assets using Asset Processor.
3. Shut down Asset Processor.
4. Attempt to run Missing Dependency Scanner (`AssetProcessorBatch --zeroAnalysisMode --dsp=%testReferenceFile.xml project-path=%project-path%`)

**Expected behavior**
Information about dependencies is outputted.

**Actual behavior**
1 Error and 5 warnings are present in the output.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/86951905/223408730-d9cb199e-2a74-4d62-80de-5f889da61150.png)

**Found in Branch**
Development (602b668)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository** 602b668

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 11
- CPU i7 - 11700F
- GPU RTX 3070 Lite Hash Rate
- Memory 32GB

**Comment by amzn-mike** [comment]
Closing as issue seems resolved by correctly specifying the project path
