### ISSUE TITLE
Asset Browser: Sorting content via right click

### ISSUE THREAD

**Issue by rainbj** [o3de/o3de#14990]
**Is your feature request related to a problem? Please describe.**
As a user of Asset Browser, I would like the ability to sort my content via right click option. This sort should work on all three of our views. (List, table, thumbnail view) The tags I would expect to see are 

Sort by >
 - Name
 - Kind
 - Last Modified
 - Size

![2023-03-07_16-21-21](https://user-images.githubusercontent.com/82551958/223587631-f35cca8c-c62e-4c47-ac6b-794214b6af1b.png)

**Describe the solution you'd like**
Currently, we do not have the ability to sort, Except on table view. This functionality of sorting in table view is similar to the functionality we need in all three views. This sorting should be possible in table, list, and thumbnail view. All the same.

**Comment by lsemp3d** [comment]
@sphrose what's the status of this one?
