### ISSUE TITLE
Linux: Closing the Editor leaves a ghost O3DE Editor icon on the taskbar

### ISSUE THREAD

**Issue by LB-MateuszPlatakis** [o3de/o3de#15000]
**Describe the bug**
If the Editor is closed on Ubuntu 20.04.5 LTS, it leaves a ghost _O3DE Editor_ icon on the taskbar. The icon cannot be dismissed either by clicking _Quit_ or pressing _X_ on the _All Windows_ option from the icon context menu. There are also no active processes correlated with O3DE Editor in the System Monitor.

Note that this is a machine specific Issue. We were unable to reproduce this on other available PCs with Ubuntu 20.04 and 22.04.

Please refer to the attached logs, screenshots and video for more information.

**Steps to reproduce**

1. Launch the Project Manager.
2. Open any working project.
3. Close the Editor. 
4. Check the taskbar for _O3DE Editor_ icon.
5. Try to close the _O3DE Editor_ application icon.

**Expected behavior**
There should be no ghost _O3DE Editor_ icon left when closing the editor.

**Actual behavior**
After closing the editor there is a ghost _O3DE Editor_ icon on the taskbar.

**Logs/Screenshots/Video**

[Editor.log](https://github.com/o3de/o3de/files/10920110/Editor.log)
[hardinfo_report.txt](https://github.com/o3de/o3de/files/10920112/hardinfo_report.txt)

![image](https://user-images.githubusercontent.com/119418207/223702385-5b9fac1d-7139-4282-a6ef-cc199a2b46d4.png)
![SM1](https://user-images.githubusercontent.com/119418207/223702423-99cde6ad-b0ff-4566-b448-05b32c24d64b.png)
![SM2](https://user-images.githubusercontent.com/119418207/223702427-f8717cc0-5553-4381-800d-b55780a39b6e.png)
![SM3](https://user-images.githubusercontent.com/119418207/223702429-46e4aa16-e8f2-40a9-9ee6-50cd0cae66ec.png)
![SM4](https://user-images.githubusercontent.com/119418207/223702434-a8062c11-b5ed-4e8d-83b2-282eb167b675.png)
![SM5](https://user-images.githubusercontent.com/119418207/223702437-284c97ce-a2f3-48e4-8265-a8c89092825b.png)

https://user-images.githubusercontent.com/119418207/223702700-f08ce638-64b8-4533-b078-76e2b5d7537d.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[3f0b4de](https://github.com/o3de/o3de/commit/3f0b4dee328f4f5f2381b30f690132ec3c345fc4)

**Desktop/Device:**
- Device: PC
- OS: Linux 
- Version: Ubuntu 20.04.5 LTS
- CPU: Intel® Core™ i7-9700K CPU @ 3.60GHz × 8
- GPU: NVIDIA GeForce RTX 2070
- Memory: 16GB

**Comment by TheShed412** [comment]
I am able to reproduce this issue on my machine in the most recent development branch commit 377cb88f0a5cb0cee94eb91c776bc8f537c9e00a 

My machine specs:
```
OS: Ubuntu 20.04.5 LTS x86_64
CPU: AMD Ryzen 9 3900X (24) @ 3.800G
GPU: AMD ATI Radeon RX 5600 OEM/5600
Memory: 32gb
```

Seems like it isn't a hardware specific issue since I am on a full AMD machine. This could be an issue with this specific version of Ubuntu? I am on the same `.5` patch version.

I might look in to this since it is a little annoying testing other stuff with my taskbar getting full of editor icons.
