### ISSUE TITLE
Delete option is available in context menu of Level prefab

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#15044]
**Describe the bug**
The non-functional **Delete** option is available in the context menu of the Level prefab.

**Steps to reproduce**
1. Create a new level.
2. In Entity Outliner, press RMB on Level prefab.

**Expected behavior**
The **Delete** option is **not** available in context menu of Level prefab.

**Actual behavior**
The **Delete** option is available in context menu of Level prefab.

**Screenshots**
![level-prefab-rmb-delete](https://user-images.githubusercontent.com/86951967/224329543-725ac0ca-f9db-41f5-a9e1-59d190e27ccd.png)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
9c8d4f2

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by monroegm** [comment]
Duplicate is there too

**Comment by AMZN-daimini** [comment]
Fixed by the PR above.
