### ISSUE TITLE
Exiting the Game Mode can cause Duplicate and Delete keyboard shortcuts for entities to stop functioning

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#15090]
**Describe the bug**
Entering and exiting the Game Mode, while moving camera and/or manipulating entities between Game Mode launches can cause *Duplicate* and *Delete* keyboard shortcuts for entities to stop functioning. Please note that this issue can be inconsistent and occur after first Game Mode exit or after several, though it seems that moving camera or entities between Game Mode entries causes it.

This issue can be fixed by restarting the Editor.

**Steps to reproduce**
1. Select an entity (for example *Shader Ball*) and use *Ctrl+D* or *Delete* shortcut on it.
2. Enter and exit the Game Mode.
3. Move the Camera or manipulate entities around the level.
4. Enter and exit the Game Mode.
5. Repeat step 1.

**Expected behavior**
*Duplicate* and *Delete* keyboard shortcuts still work.

**Actual behavior**
*Duplicate* and *Delete* keyboard shortcuts disappear from the entity context menu and do not function.

**Video**

https://user-images.githubusercontent.com/86952082/224995631-cef52d25-bf2d-4592-9e0b-05222ae2b4e6.mp4

**Found in Branch**
Development (3a3fce2)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
3a3fce230fbc9733ed56026fa89382d7c3fa4340

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by AMZN-daimini** [comment]
Judging from the video, it looks like during the repro the act of right-clicking in the Outliner does not select the entity underneath, hence why the duplicate/delete menu items are not displayed (among many others). So fixing this may be a matter of identifying why that (does not) happen.

**Comment by LB-ArturZieba** [comment]
@AMZN-daimini Clicking "through" the UI on Linux issue can be viewed here: https://github.com/o3de/o3de/issues/7235.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization/2305 (392d44b) build, however it still occurs on Development (7244dec).
