### ISSUE TITLE
Exiting Game Mode can set the Viewport Camera to 0,0,0 coordinates and print an error message to the Console

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#15091]
**Describe the bug**
Exiting Game Mode inconsistently sets the Viewport Camera to 0,0,0 World Translation and prints an error message to the Console on every exit after second one:
`[Error](ViewportContextManager) - Attempted to pop the root view for context "Default ViewportContext"`

**Steps to reproduce**
1. Note the Viewport Camera position (place it visibly away from 0,0,0 World Translation).
2. Enter and exit the Game Mode.
3. Move the Viewport Camera around.
4. Enter and exit the Game Mode again.

**Expected behavior**
Camera returns to the last place it was before entering the Game Mode each time and no errors are printed to the Console.

**Actual behavior**
Camera is set inconsistently to 0,0,0 World Translation and error is printed to the Console every Game Mode exit after the second one.

**Video**

https://user-images.githubusercontent.com/86952082/225001458-b378fb14-055a-4752-832b-b8e51d7874c1.mp4

**Found in Branch**
Development (3a3fce2)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
3a3fce230fbc9733ed56026fa89382d7c3fa4340

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by hultonha** [comment]
@LB-ArturZieba This issue should now be fixed by PR https://github.com/o3de/o3de/pull/15119 (https://github.com/o3de/o3de/commit/e1fa4744ef21f4c3f6b80a103a84d335c956846b). Could you please verify this again, I'm 99% sure it's fixed! 😅 Thanks!

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on both the Development (50b62ea) and Stabilization/2305 (25641ec) builds. Closing the issue.

**Comment by hultonha** [comment]
Awesome thank you @LB-ArturZieba 🥳
