### ISSUE TITLE
Folder sorting only sorts alphabetically

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#15109]
Clicking a column header will not sort the contents of the folder by that column's values

1 - Launch the Editor and enable WIP Asset Browser features via the Console:

ed_useWIPAssetBrowserDesign true

2 - Open the Asset Browser, and switch to Thumbnail View if necessary.
3 - Drill down into a folder in the AutomatedTesting project such as AutomatedTesting/Assets/Objects/Foliage
4 - Click a column header to sort the folder contents

The contents are only ever sorted alphabetically. Never by size, vertices, etc

**Comment by lsemp3d** [comment]
@sphrose is this fixed with your sorting changes?

**Comment by sphrose** [comment]
Not quite, thumbnail and list view are done, tableview wasn't ready when I submitted this, I'll get onto that now.
