### ISSUE TITLE
Vertices column only displays 130

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#15108]
1 - Launch the Editor and enable WIP Asset Browser features via the Console:

ed_useWIPAssetBrowserDesign true

2 - Open the Asset Browser, and switch to Thumbnail View if necessary.
3 - Drill down into a folder in the AutomatedTesting project such as AutomatedTesting/Assets/Objects/Foliage

vertices is 130 for each item in the folder

![Image](https://user-images.githubusercontent.com/98843754/225119066-35da71e0-aee7-45c0-a587-e5b215b7939f.png)

**Comment by jckand-amzn** [comment]
Verified fix on development@ b25c961520462444316cab8eae0ccc1a8c850fb3.
