### ISSUE TITLE
Inconsistent thumbnail preview for fbx files

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#15103]
Some thumbnail preview show a mini render of the asset while others show a generic icon

1 - Launch the Editor and enable WIP Asset Browser features via the Console:

```ed_useWIPAssetBrowserDesign true```

2 - Open the Asset Browser, and switch to Thumbnail View if necessary.
3 - Drill down into a folder in the AutomatedTesting project such as AutomatedTesting/Assets/Objects/Foliage

![Image](https://user-images.githubusercontent.com/98843754/225101405-102c788b-9b6f-49b0-a947-904cd87fc276.png)

**Comment by lsemp3d** [comment]
![image](https://github.com/o3de/o3de/assets/58790905/753c8a77-d8b8-4272-b898-2b306c0b6b19)
Updated screenshot

**Comment by rainbj** [comment]
I would agree with @lsemp3d feedback here. If we cannot read the mesh data or show an asset image for some reason, we should just show the default icon as stated above. Good call out.
