### ISSUE TITLE
Updating Viewport settings in Material Editor or Material Canvas results in infinite UI refreshment

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#15137]
**Describe the bug**
Changing any setting of Viewport in Material Editor or Material Canvas results in an infinite UI refreshment. Loop can be stopped by reopening the tools, and Minimizing and Maximizing them.

The issue may be related to the following PR - [#15111](https://github.com/o3de/o3de/pull/15111)

1. Open the Material Editor.
2. Enable Viewport Settings via Tools menu.
3. Change any setting located in the Viewport Settings.

**Expected behavior**
UI is refreshed once after updating settings.

**Actual behavior**
Infinite UI update cycle.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/225618281-0bb406be-5e85-4dd3-96db-37c298ea4f35.mp4

**Found in Branch**
Development (d6ef267)
Stabilization/2305 (9e5047f)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository** 602b668

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 11
- CPU i7 - 11700F
- GPU RTX 3070 Lite Hash Rate
- Memory 32GB

**Comment by LB-MateuszPlatakis** [comment]
Issue verified as fixed on build Stabilization/2305 (https://github.com/o3de/o3de/commit/25641ec8f6225d2eaf31ae5507257f2095f98987) this issue still occurs on build Development (https://github.com/o3de/o3de/commit/50b62ead332fa1523a8f5c7e763f408ca9b60ce4) as the PR was merged only to Stabilization.
