### ISSUE TITLE
GetTranslationOffset not implemented warning for Quad Shape

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#15141]
**Describe the bug**
When using a light component with a Quad Shape, a "GetTranslationOffset not implemented" warning is printed.

**Steps to reproduce**
1. Create or open a level.
2. Create an entity
3. Add a light component
4. Set the light type to "Quad"

**Expected behavior**
No warning should print.

**Actual behavior**
A warning prints.

**Found in Branch**
stabilization/2305

**Comment by greerdv** [comment]
Fixed in #15143. https://github.com/o3de/o3de/commit/0962a5a8048aed29fa39c3cf5cec39a9f3c3e774
