### ISSUE TITLE
Duplicating entities causes errors to be printed in console

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#15164]
**Describe the bug**
Duplicating Entities causes an error to be printed in the Console:
`[Error] (Prefab) - Failed to find an owning instance for entity with id X`

This issue occurs both on Windows and Linux, as well as both Stabilization/2305 and Development branches.

**Steps to reproduce**
1. Launch a level.
2. Duplicate an Entity.

**Expected behavior**
Entity is duplicated without issues.

**Actual behavior**
An error is printed.

**Screenshots/Video**
[Video](https://user-images.githubusercontent.com/110163473/225901345-afa28d45-1ccd-4b07-a58d-366a24178a48.mp4)

**Found in Branch**
Stabilization/2305

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
db92736

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 11 21H2
- CPU: I7-11700f
- GPU: Geforce RTX3070 MSI
- Memory: 32GB

**Comment by AMZN-daimini** [comment]
Can no longer reproduce this.
