### ISSUE TITLE
Editor Crashes When Loading Prefabs With EditorMaterialComponent  That Have Their First Material Slot Empty

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#15186]
**Describe the bug**
I have some prefabs that I created months ago and they now crash the Editor when loading said prefabs directly (on the level prefab) or indirectly (some prefab referenced by the level prefab).

Root Cause:
It seems at some point in the past when a material component had the default material slot empty, it would be saved like this
in the prefab:
```json
    "Component_[3886310797281406819]": {
        "$type": "EditorMaterialComponent",
        "Id": 3886310797281406819,
        "Controller": {
            "Configuration": {
                "materials": [
                    {
                        "Key": {},
                        "Value": {}
                    },
                    {
                        "Key": {
                            "materialSlotStableId": 2697354941
                        },
                        "Value": {
                            "MaterialAsset": {
                                "assetId": {
                                    "guid": "{864532C5-ABEE-5EAD-82F9-B56D7E1DF9D8}"
                                },
                                "assetHint": "assets/meshes/shield/shield.azmaterial"
                            }
                        }
                    }
                ]
            }
        }
    },
```

As you can see in the json snippet above, the first material slot has empty `Key` and `Value`, this would cause a null pointer exception in the latest version of O3DE.  

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
This bug can not be re-created today because it seems the empty material slot is not written to the output prefabs anymore.
You'd need to manually insert a first empty slot in the prefab to recreate the scenario... Or find a prefab file created several months ago
where the first material slot is empty like shown above.

**Expected behavior**
The Editor should be able to load older prefabs.

**Actual behavior**
The Editor crashes because the MaterialComponentController doesn't have null pointer guards on empty material slots.

**Screenshots/Video**
N/A

**Found in Branch**
commit 8fbad22e9545137ea45b9019941fe3fea63c0af6 (upstream/development, development)
Author: Nikhil Raktale <raktalen@amazon.com>
Date:   Fri Mar 17 14:31:11 2023 -0700

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen Threadripper 3970X 32-Core Processor    3.70 GHz
 - GPU NVidia RTX 4090 (24GB VRAM)
 - Memory 128GB
 - Storage: WD_BLACK 2TB SN850 NVMe M2 SDD PCIe 4.0

**Additional context**
The work around is to manually remove the empty material slot data from all the prefabs:
```
                    {
                        "Key": {},
                        "Value": {}
                    },
```

Callstack of the crash:
```
```
 	Editor.exe!AZ::Debug::Trace::Assert(const char * fileName, int line, const char * funcName, const char * format, ...) Line 400	C++
 	AtomLyIntegration_CommonFeatures.Editor.dll!AZStd::intrusive_ptr<AZ::RPI::Material>::operator->() Line 190	C++
 	AtomLyIntegration_CommonFeatures.Editor.dll!AZ::Render::EditorMaterialComponent::OnMaterialsCreated(const AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> & materials) Line 285	C++
 	AtomLyIntegration_CommonFeatures.Editor.dll!AZStd::Internal::INVOKE<void (__cdecl AZ::Render::MaterialComponentNotifications::*&)(AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> const &),AZ::Internal::HandlerNode<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,AZ::Internal::EBusContainer<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,1,1>::HandlerHolder,1> &,AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> &,void>(void(AZ::Render::MaterialComponentNotifications::*)(const AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> &) & f, AZ::Internal::HandlerNode<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,AZ::Internal::EBusContainer<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,1,1>::HandlerHolder,1> & arg0, AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> & <args_0>) Line 178	C++
 	AtomLyIntegration_CommonFeatures.Editor.dll!AZStd::invoke<void (__cdecl AZ::Render::MaterialComponentNotifications::*&)(AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> const &),AZ::Internal::HandlerNode<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,AZ::Internal::EBusContainer<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,1,1>::HandlerHolder,1> &,AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> &>(void(AZ::Render::MaterialComponentNotifications::*)(const AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> &) & f, AZ::Internal::HandlerNode<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,AZ::Internal::EBusContainer<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,1,1>::HandlerHolder,1> & <args_0>, AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> & <args_1>) Line 55	C++
 	AtomLyIntegration_CommonFeatures.Editor.dll!AZ::EBusEventProcessingPolicy::Call<void (__cdecl AZ::Render::MaterialComponentNotifications::*&)(AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> const &),AZ::Internal::HandlerNode<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,AZ::Internal::EBusContainer<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,1,1>::HandlerHolder,1> &,AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> &>(void(AZ::Render::MaterialComponentNotifications::*)(const AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> &) & func, AZ::Internal::HandlerNode<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,AZ::Internal::EBusContainer<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,1,1>::HandlerHolder,1> & iface, AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> & <args_0>) Line 438	C++
 	AtomLyIntegration_CommonFeatures.Editor.dll!AZ::Internal::EBusContainer<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications,1,1>::Dispatcher<AZ::EBus<AZ::Render::MaterialComponentNotifications,AZ::Render::MaterialComponentNotifications>>::Event<void (__cdecl AZ::Render::MaterialComponentNotifications::*)(AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> const &),AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> &>(const AZ::EntityId & id, void(AZ::Render::MaterialComponentNotifications::*)(const AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> &) && func, AZStd::unordered_map<AZ::Render::MaterialAssignmentId,AZ::Render::MaterialAssignment,AZStd::hash<AZ::Render::MaterialAssignmentId>,AZStd::equal_to<AZ::Render::MaterialAssignmentId>,AZStd::allocator> & <args_0>) Line 150	C++
 	AtomLyIntegration_CommonFeatures.Editor.dll!AZ::Render::MaterialComponentController::OnSystemTick() Line 186	C++
```
```

**Comment by galibzon** [comment]
FYI @gadams3

**Comment by gadams3** [comment]
https://github.com/o3de/o3de/pull/15187
