### ISSUE TITLE
Bug Report - Decals stop working when one of the decal materials is removed

### ISSUE THREAD

**Issue by pawelbudziszewski** [o3de/o3de#15193]
**Describe the bug**
If the material for one of the decals on the scene is removed, all decals disappear (after reloading the scene). This applies to existing, as well as new/modified decals. The only way to solve this is to re-assign the missing material. However, it may be not easy to find the decal with incorrect material, especially if there is a large number of decals on the scene. Typically, if the material for any entity is incorrect, it's marked red icon in the "Entity Inspector". But not in this case - the material is displayed normally. There are also no clear messages informing about the problem. Only the following warning message in the output when the level is loaded:
```
[Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {D34B50C3-D2FD-519E-8F52-6D2FE4761477}:0
```

**Assets required**
Tested on default O3DE project

**Steps to reproduce**
1. Create a default project
2. Create 2 materials with bitmaps as a base color. Name them "decal1_mat" and "decal2_mat"
3. On the scene create 2 entities "decal1" and "decal2". Create a decal component for each and assign decal materials respectively
4. Place both decals in the way, the bitmaps are visible (eg. on the floor)
5. Delete "decal1_mat" using "Asset Browser" or file manager
6. Restart O3DE and load the level

Result:
- "decal2" (with the correct material) is invisible. Changing material doesn't help.
- All new-created decals are invisible
- In the entity inspector of the "decal1" nothing indicates, that the material is missing

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
8fbad22e9545137ea45b9019941fe3fea63c0af6

**Desktop/Device (please complete the following information):**
Linux, Ubuntu 22.04

**Comment by pawelbudziszewski** [comment]
May be linked with #15190

**Comment by invertednormal** [comment]
I'm going to start looking at this.
