### ISSUE TITLE
Entity Outliner: Entity lacks multiple options in its context menu right after duplication and cannot be duplicated with keyboard shortcut afterwards

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#15212]
**Describe the bug**
In the **Entity Outliner**, after entity is duplicated and duplicate is still selected, it lacks following options in its context menu:

- Create Prefab
- Instantiate Prefab
- Instantiate Procedural Prefab...
- Duplicate
- Move Up

The entity cannot be duplicated afterwards by using keyboard shortcut - **Ctrl+D**.

Note that after reselecting the entity, all options that were absent in context menu are now available. Also, the duplicated entity can be duplicated with keyboard shortcut after reselecting it.

This issue also occurs on Development (e282c39), however the issue differs - The context menu of duplicated entity lacks only the following options:

 - Create Prefab
 - Move Up
 - Move Down
 
Also, the duplicated entity can be duplicated again with the keyboard shortcut.

**Steps to reproduce**
1. Create a new level.
2. Create a new entity.
3. Select created entity in the Entity Outliner.
4. Press Ctrl+D to duplicate selected entity.
5. When duplicate entity is still selected, press RMB on it and note that the context menu lacks multiple options.
6. Press Ctrl+D again (entity is not duplicated).

**Expected behavior**
The duplicated entity does not lack options in its context menu and can be duplicated with keyboard shortcut.

**Actual behavior**
After duplicating entity, while its still selected in the **Entity Outliner** it cannot be duplicated with keyboard shortcut and lacks multiple options in its context menu.

**Video**

https://user-images.githubusercontent.com/86951967/226577809-cac20671-8b77-4074-a34a-1fe175d68c4a.mp4

**Found in Branch**
Stabilization/2305

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
2a36873

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.5 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by LB-HubertUberman** [comment]
Issue verified as fixed on branch Stabilization/2305 (https://github.com/o3de/o3de/commit/25641ec8f6225d2eaf31ae5507257f2095f98987).
