### ISSUE TITLE
Initial reduced coordinate articulation model editor authoring

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#15220]
[Migrated from JIRA LYN-18066]

### Summary

Using the newly created reduced coordinate articulation component, implement a simple arm (hinge only) to validate workflow of setting-up an articulation hierarchy.

**Comment by hultonha** [comment]
Tagging @michalpelka for visibility.

Once the articulation work is ready to use, could you carry out this task to verify articulations can be authored as expected? (I think you've been doing that already but this would just track/formalize it).

I'll let you know when to test, in the meantime can I assign to you if that's okay? Thanks!

**Comment by michalpelka** [comment]
Authored here: https://github.com/o3de/o3de-physics-test-scene/pull/12

**Comment by hultonha** [comment]
> Authoring in Editor is now possible after this PR [aws-lumberyard-dev#519](https://github.com/aws-lumberyard-dev/o3de/pull/519) Closing this issue.

Great to hear, thanks @moraaar and @michalpelka 👍
