### ISSUE TITLE
Action Manager: Delete and Duplicate hotkeys are no longer listed in Entity Outliner context menu, and do not function after using them and then entering Game Mode

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#15270]
**Describe the bug**
Delete and Duplicate hotkeys are no longer listed in Entity Outliner context menu, and do not function after using them and then entering Game Mode.

**Steps to reproduce**
1. Launch the Editor and open a new or existing level.
2. Add a new entity via the Entity Outliner.
3. Select the entity and CTRL-D.
4. Select the entity and DEL.
5. Enter Game Mode.
6. Right-click the entity created in step 2, and observe the context menu.
7. CTRL-D and DEL once again.

**Expected behavior**
Delete and Duplicate hotkeys are listed in context menu and function.

**Actual behavior**
Delete and Duplicate hotkeys are not listed and do not function after being used once, and entering/exiting Game Mode.

**Screenshots/Video**
![duplicate_delete_hotkeys](https://user-images.githubusercontent.com/82226555/227025241-ebcb26d5-e49d-4f16-b26b-1b44a1942e71.jpg)

https://user-images.githubusercontent.com/82226555/227031315-66e7a351-3935-42e4-8c69-1a27bb39a9a5.mp4

**Found in Branch**
stabilization/2305

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
85ede2c0dd8518fb11aa23dce6e8da40deff2372

**Comment by AMZN-daimini** [comment]
The issue should be fixed by this PR: https://github.com/o3de/o3de/pull/15465
