### ISSUE TITLE
Asset Browser: Deleting a folder deletes files within it but not the nested folders

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#15320]
**Describe the bug**
When attempting to delete a folder in Asset Browser, it will not be deleted if it contains any other folders within it. Any non-folder files in the folder or nested folders will be deleted, but all the folders will remain. Nested folders have to be removed one by one, starting from the folder that contains no other folders.
This issue occurs on both Windows and Linux on stabilization branch.
On development branch, files cannot be deleted (see Additional Context section at the bottom).

**Steps to reproduce**
1. Open the Asset Browser.
2. Create a new folder somewhere, for example in the Assets folder (do not name this new folder due to https://github.com/o3de/o3de/issues/15319).
3. Create a new folder within the new folder from step 2 (do not name this new folder either).
4. Create some files (materials, script canvases, etc.) in the innermost folder.
5. Delete the top folder (the one that contains everything else).

**Expected behavior**
The top folder is deleted along with all of its contents and nested folders.

**Actual behavior**
All files within the folder and its nested folders are deleted, but all folders remain in place.

**Screenshots/Video**

https://user-images.githubusercontent.com/99388484/227230370-87fd2f3a-17c7-40b9-a17a-12772b903cc4.mp4

**Found in Branch**
Stabilization

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
(https://github.com/o3de/o3de/commit/25641ec8f6225d2eaf31ae5507257f2095f98987)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version: 20.04.4 LTS
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB
 
**Additional context**
On development branch (https://github.com/o3de/o3de/commit/50b62ead332fa1523a8f5c7e763f408ca9b60ce4), attempting to delete any folder or file via the Asset Browser results in a popup window warning the user about deleting the file. If "Delete" is chosen, the file is not deleted anyway. This might be related to https://github.com/o3de/o3de/issues/13111.

![folder_warning](https://user-images.githubusercontent.com/99388484/227232012-c35092ad-c85a-4b74-b668-528668726e39.png)

![asset_warning](https://user-images.githubusercontent.com/99388484/227232066-5ea9c4aa-5685-4cb1-8072-3a5174bbe6e1.png)

**Comment by jjjoness** [comment]
@jckand-amzn I'm looking at this now.

**Comment by jckand-amzn** [comment]
Issue still occurs as described on development@ b25c961520462444316cab8eae0ccc1a8c850fb3. Reopening.

**Comment by jckand-amzn** [comment]
Retested on development@ 40c42f7f800b9278d8a3729d3e260f70eae19514. Issue does appear to be resolved. Previous test may have involved a .materialgraph file which currently can't be deleted and can cause folders to remain, however that issue is separately logged (https://github.com/o3de/o3de/issues/13716).

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed on build Development (https://github.com/o3de/o3de/commit/18205539abf1b1d2eb3959c0a1c42a3eea16a455).
Note that this issue still occurs on build Stabilization/2305 (https://github.com/o3de/o3de/commit/1ff603a58ff71e79b70988d48540672c09c3879b) as fix has been merged only to the Development branch.
