### ISSUE TITLE
Stabilization/2305 Installer displayed version is not updated to newest release

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#15349]
**Describe the bug**
The latest Stabilization/2305 installer is displaying Development build version instead of O3DE 1.2.0 in splash screen, about O3DE screen and the Editor's window. The installer window, engine directory and project manager display correct version of the build.  
The issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Launch the Editor (observe the splash screen while launching).
2. Press Help - About O3DE.

**Expected behavior**
The installer displays the accurate engine version.

**Actual behavior**
The installer displayed version is not updated to the newest release.

**Screenshots/Video**
![versioningAbout](https://user-images.githubusercontent.com/86953659/227479309-eee04ccb-3376-407b-a8f9-589c9e11ce9b.png)

**Found in Branch**
Stabilization/2305 Installer build (https://o3debinaries.org/stabilization-2305/Latest/Linux/O3DE_latest.deb)

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.3 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by amzn-changml** [comment]
The lastest stabilization installer build now applies 23.05.0 to the version number in the installer and splash screen. @LB-KacperKapusta Can you confirm?

**Comment by LB-KacperKapusta** [comment]
Closing the issue as it has been confirmed using the latest Stabilization/2305 Installer (https://o3debinaries.org/stabilization-2305/Latest/Windows/o3de_installer.exe) that the version number in the Installer now displays **23.05.0** and **2305** is displayed in the splash screen and the about O3DE screen @amzn-changml.
