### ISSUE TITLE
Double right arrow button `>>` on the Viewport Toolbar is not functional

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de#15351]
**Describe the bug**
When the Editor window is not Maximized and the User shrinks the Viewport Toolbar horizontally, some menus are hidden and a double right arrow button (>>) appears, but it is not functional. Making the menus inaccessible in a smaller Editor window.
This issue occurs on Stabilization and Development branches on Windows and Linux.

**Steps to reproduce**
1. Launch the O3DE Editor.
2. If the Editor window is maximized, restore it.
3. Shrink the Editor window horizontally so the `>>` button appears on the Viewport Toolbar.
4. Press the `>>` button.

**Expected behavior**
A dropdown menu appears.

**Actual behavior**
The button in not functional.

**Screenshots/Video**

https://user-images.githubusercontent.com/99716227/227493081-37058e1a-d9cb-4a6d-9ebf-a84d9d240c67.mp4

**Found in Branch**
Stabilization

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
 (f7f388f)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 11
 - CPU AMD Ryzen 5 5600H
 - GPU NVIDIA GeForce RTX 3070 Laptop GPU
 - Memory 16GB

**Comment by AMZN-daimini** [comment]
Fixed by the PR above.

**Comment by LB-MateuszPlatakis** [comment]
Confirming the issue has been closed as already completed.
