### ISSUE TITLE
Lua Editor: Hot reload behaves unexpectedly

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#15419]
**Describe the bug**
After enabling hot reload with a .setreg file, editing a .lua file when in Game mode causes unexpected behavior. In this example, when a script is printing some text to the console after receiving a script event every second, changing the printed string in the code results in, at first, nothing being updated. After the second and additional changes, multiple lines of text are printed, but there is seemingly no consistent pattern. Sometimes it will be the same line copied multiple times, sometimes lines from different previous edits. In either scenario, hot reload is never up to date and it is not executing the newest saved code.
This issue occurs on Windows and Linux.

**Assets required**

[assets.zip](https://github.com/o3de/o3de/files/11089862/assets.zip)

**Steps to reproduce**
1. Navigate to o3de/Gems/ScriptCanvas/Registry.
2. Paste the attached LuaHotReload.setreg file in this location.
3. Close Project Manager, Editor, and all O3DE tools if they were open, so that the registry change is applied when they are relaunched.
4. Create a project with Remote Tools Connection gem.
5. Create a new level.
6. Create a new Script Event in the Asset Editor (Tools>Asset Editor).
7. Name it SimpleScriptEvent.
8. Add an event to SimpleScriptEvent and name it SendNumber.
9. Add a parameter to the SendNumber event with the name Number and type Number.
10. Save the .scriptevents file in the project's Assets folder with the name SimpleScriptEvent.
11. Create two entities with Lua Script components attached to them.
12. Attach SendEvent.lua file to one of them, and ReceiveEvent.lua to the other (see Assets Required section).
13. Open the ReceiveEvent.lua file that was attached to an entity in step 12 in the Lua Editor.
14. Connect Lua Editor to O3DE.
15. Close Asset Editor and reopen it.
16. Open SimpleScriptEvent in the Asset Editor (steps 15 and 16 are needed due to https://github.com/o3de/o3de/issues/14210).
17. Start Game mode (text should now be printed to the Console about every second).
18. While in Game mode, edit the Debug.Log function call (ReceiveEvent.lua, line 11) in the Lua Editor to have it print something different.
19. Save the ReceiveEvent.lua file and observe the Editor console.
20. Repeat steps 18 and 19 a few times.

**Expected behavior**
Each time ReceiveEvent.lua is saved and compiled, the Console starts printing the new string in accordance with the changes made.

**Actual behavior**
After the first edit to ReceiveEvent.lua, nothing changes, and after additional edits multiple lines are displayed, corresponding to previous edits.

**Screenshots/Video**

https://user-images.githubusercontent.com/99388484/228247958-ab1d9428-eb87-42e6-802e-eec87891d97c.mp4

**Found in Branch**
Stabilization/2305 Installer build (https://o3debinaries.org/stabilization-2305/Latest/Linux/O3DE_latest.deb)
Development (https://github.com/o3de/o3de/commit/2c16b8c76d4a3b8ffda835b9d48a9478a40654ce)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version: 20.04.4 LTS
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by hultonha** [comment]
Discussed in sig-simulation. This issue seems much more closely related to @o3de/sig-content, assigning them to triage.
