### ISSUE TITLE
Script Canvas: Multiple nodes added via Command Line tool cause Editor to crash

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#15415]
**Describe the bug**
In the Script Canvas tool, it is possible to add nodes to the graph by opening Command Line tool. After typing the desired node name, selecting it and pressing "Enter", it is added to the graph. Moving the node afterwards may results in a crash.
Note that we only verified nodes that did not have "Deprecated node" description.

Following nodes cause crash of the Editor after adding them to the graph and selecting/moving them:
 - StringFormatted
 - ExpressionNodeBase
 - NodeableNodeOverloaded
 - ArithmeticExpression
 - UnaryExpression
 - UnaryOperator
 - BinaryOperator
 - BooleanExpression
 - OperatorArithmetic
 - OperatorArithmeticUnary
 - OperatorBase
 - EqualityExpression
 - ScriptEventBase
 - ComparisonExpression
 - BaseTimerNode
 - NodeableNode
 - Nodeling

Two following nodes cause Editor to crash right after pressing Enter key:
 - FunctionCallNode
 - SendScriptEvent

Please refer to the attached crash logs for more information.

**Steps to reproduce**
1. Open the Script Canvas.
2. Create a new empty graph.
3. Open the Command Line tool (Tools -> Command Line / Ctrl+P)
4. Find any of the following nodes and select it by pressing LMB :  StringFormatted, ExpressionNodeBase, NodeableNodeOverloaded, Arithmetic Expression etc.
5. Press Enter key.
6. In the graph, select the added node and try to move it.

**Expected behavior**
Editor remains stable at all times, adding nodes from the Command Line tool does not crash the Editor.

**Actual behavior**
Editor crashes after adding or moving nodes from the Command Line tool.

**Video**

https://user-images.githubusercontent.com/86951967/228223940-359725c2-f09e-43a7-8094-54a835b8b975.mp4

https://user-images.githubusercontent.com/86951967/228223965-13a7d255-1628-4753-a484-31cede48fe4e.mp4

**Found in Branch**
Stabilization/2305 installer
Development (2c16b8c)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Additional context**

Logs of crash caused by node **OperatorArithmeticUnary**:
[Editor.log](https://github.com/o3de/o3de/files/11088771/Editor.log)
[error.log](https://github.com/o3de/o3de/files/11088773/error.log)
[error.zip](https://github.com/o3de/o3de/files/11088774/error.zip)

Logs of crash caused by node **SendScriptEvent**:
[Editor.log](https://github.com/o3de/o3de/files/11088778/Editor.log)
[error.log](https://github.com/o3de/o3de/files/11088779/error.log)
[error.zip](https://github.com/o3de/o3de/files/11088780/error.zip)

**Comment by lsemp3d** [comment]
Changed priority to major, the command line option is an experimental tool that is not part of the critical path for using Script Canvas

**Comment by lsemp3d** [comment]
@monroegm any reason to bump priority back up to critical ? This command line tool is experimental and not required to use Script Canvas, nor does it offer much functionality and could be removed altogether.

**Comment by LB-MateuszSzweda** [comment]
Confirming the issue has been closed as it cannot be reproduced in Development ([fc7f51a] . The command line was successfully flagged as experimental and is hidden by default in Script Canvas.
