### ISSUE TITLE
DPE: Some component property controls can be hidden by reducing width of Inspector

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#15507]
**Describe the bug**
Some component property controls can be hidden by reducing width of Inspector.

**Steps to reproduce**
1. Launch the Editor with the DPE enabled:
```
Editor.exe --ed_enableDPE=true
```
2. Create a new level.
3. Create 2 entities
4. Reduce the width of the Entity Inspector (if necessary) and attempt to change the Parent Entity on the Transform component for either entity.

**Expected behavior**
All component properties can be set with a narrow Inspector, or at the very least scrolled to.

**Actual behavior**
Entity picker button is hidden if the Entity Inspector's width is reduced.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82226555/229210650-d80add7f-9cf4-4fcc-a968-c757649a8a68.png)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
9ad956e7560014794cd056d499c5adfb47cbb6c8

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by forkercat** [comment]
duplicate: https://github.com/o3de/o3de/issues/14864
