### ISSUE TITLE
AssetBrowser causes Editor to become non-responsive

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#15511]
**Describe the bug**
After launching the editor and loading the default level, I switched tabs to another application for a while. After switching back, the editor is non-responsive. Breaking into a debugger, the callstack shows that AssetBrowserEntryFilter::Match is running on the main thread in response to AssetEntryChangeset. 

It's possible assets were processing while I was using another application, so there may have been many changes queued up as a result of that. AssetBrowserComponent::m_changeset has an m_changes vector with 9669 items. 
![Capture](https://user-images.githubusercontent.com/82672795/229232879-af04b60a-d898-4a8d-beee-05f37a522c44.PNG)

**Assets required**
Automated Testing project

**Steps to reproduce**
1. Launch the Editor with the AutomatedTesting project
2. Load DefaultLevel
3. Have the AssetBrowser open
4. alt-tab to a different application
5. Come back 30 minutes later
6. Editor is non-responsive

**Expected behavior**
Editor is interactive when returning to it.

**Actual behavior**
Editor is non-responsive, with the following callstack. It does not appear to be deadlocked. There is nothing in the parallel callstacks that looks like a problem, and I can step through the code. But it never seems to get outside of AssetEntryChangeset::Synchronize.

 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserEntryFilter::MatchDown(const AzToolsFramework::AssetBrowser::AssetBrowserEntry * entry) Line 203	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserEntryFilter::MatchDown(const AzToolsFramework::AssetBrowser::AssetBrowserEntry * entry) Line 203	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserEntryFilter::MatchDown(const AzToolsFramework::AssetBrowser::AssetBrowserEntry * entry) Line 203	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserEntryFilter::MatchDown(const AzToolsFramework::AssetBrowser::AssetBrowserEntry * entry) Line 203	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserEntryFilter::MatchDown(const AzToolsFramework::AssetBrowser::AssetBrowserEntry * entry) Line 203	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserEntryFilter::MatchDown(const AzToolsFramework::AssetBrowser::AssetBrowserEntry * entry) Line 203	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserEntryFilter::MatchDown(const AzToolsFramework::AssetBrowser::AssetBrowserEntry * entry) Line 203	C++
>	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserEntryFilter::Match(const AzToolsFramework::AssetBrowser::AssetBrowserEntry * entry) Line 122	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserFilterModel::filterAcceptsRow(int source_row, const QModelIndex & source_parent) Line 121	C++
 	[External Code]	
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserModel::EndAddEntry(AzToolsFramework::AssetBrowser::AssetBrowserEntry * parent) Line 438	C++
 	[Inline Frame] EditorLib.dll!AZStd::Internal::INVOKE(void(AzToolsFramework::AssetBrowser::AssetBrowserModelRequests::*)(AzToolsFramework::AssetBrowser::AssetBrowserEntry *) &&) Line 177	C++
 	[Inline Frame] EditorLib.dll!AZStd::invoke(void(AzToolsFramework::AssetBrowser::AssetBrowserModelRequests::*)(AzToolsFramework::AssetBrowser::AssetBrowserEntry *) &&) Line 54	C++
 	[Inline Frame] EditorLib.dll!AZ::EBusEventProcessingPolicy::Call(void(AzToolsFramework::AssetBrowser::AssetBrowserModelRequests::*)(AzToolsFramework::AssetBrowser::AssetBrowserEntry *) &&) Line 437	C++
 	EditorLib.dll!AZ::Internal::EBusContainer<AzToolsFramework::AssetBrowser::AssetBrowserModelRequests,AzToolsFramework::AssetBrowser::AssetBrowserModelRequests,0,0>::Dispatcher<AZ::EBus<AzToolsFramework::AssetBrowser::AssetBrowserModelRequests,AzToolsFramework::AssetBrowser::AssetBrowserModelRequests>>::Broadcast<void (__cdecl AzToolsFramework::AssetBrowser::AssetBrowserModelRequests::*)(AzToolsFramework::AssetBrowser::AssetBrowserEntry *),AzToolsFramework::AssetBrowser::AssetBrowserEntry *>(void(AzToolsFramework::AssetBrowser::AssetBrowserModelRequests::*)(AzToolsFramework::AssetBrowser::AssetBrowserEntry *) && func, AzToolsFramework::AssetBrowser::AssetBrowserEntry * && <args_0>) Line 1541	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserEntry::AddChild(AzToolsFramework::AssetBrowser::AssetBrowserEntry * child) Line 93	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::RootAssetBrowserEntry::AddProduct(const AZStd::pair<AZ::Uuid,AzToolsFramework::AssetDatabase::ProductDatabaseEntry> & productWithUuidDatabaseEntry) Line 335	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AddProductChange::Apply(AZStd::shared_ptr<AzToolsFramework::AssetBrowser::RootAssetBrowserEntry> rootEntry) Line 136	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetEntryChangeset::Synchronize() Line 79	C++
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserComponent::OnTick(float __formal, AZ::ScriptTimePoint __formal) Line 170	C++
 	[Inline Frame] EditorLib.dll!AZStd::Internal::INVOKE(void(AZ::TickEvents::*)(float, AZ::ScriptTimePoint) &) Line 177	C++
 	[Inline Frame] EditorLib.dll!AZStd::invoke(void(AZ::TickEvents::*)(float, AZ::ScriptTimePoint) &) Line 54	C++
 	[Inline Frame] EditorLib.dll!AZ::EBusEventProcessingPolicy::Call(void(AZ::TickEvents::*)(float, AZ::ScriptTimePoint) &) Line 437	C++
 	EditorLib.dll!AZ::Internal::EBusContainer<AZ::TickEvents,AZ::TickEvents,0,2>::Dispatcher<AZ::EBus<AZ::TickEvents,AZ::TickEvents>>::Broadcast<void (__cdecl AZ::TickEvents::*)(float,AZ::ScriptTimePoint),float const &,AZ::ScriptTimePoint>(void(AZ::TickEvents::*)(float, AZ::ScriptTimePoint) && func, const float & <args_0>, AZ::ScriptTimePoint && <args_1>) Line 1360	C++
 	EditorLib.dll!AZ::ComponentApplication::Tick() Line 1511	C++
 	EditorLib.dll!CGameEngine::Update() Line 812	C++
 	EditorLib.dll!CCryEditApp::IdleProcessing(bool bBackgroundUpdate) Line 2372	C++
 	EditorLib.dll!CCryEditApp::OnIdle(long lCount) Line 2269	C++
 	EditorLib.dll!Editor::EditorQtApplication::maybeProcessIdle() Line 320	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 4067	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 54	C++
 	Editor.exe!main(int argc, char * * argv) Line 31	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
 	[External Code]	

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
7244dec1760126501947fca3a323fc638aa82a5b

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel I9-10900X
 - GPU: NVidia GeForce RTX 2080 SUPER
 - Memory: 64GB
 
**Additional context**

**Comment by jjjoness** [comment]
@amzn-tommy This was fixed in development commit SHA-1: 497ea922c966bec9176f327113a2b6af283eb69c
