### ISSUE TITLE
Bug - Asset Browser - Basic search is broken in table view

### ISSUE THREAD

**Issue by rainbj** [o3de/o3de#15524]
Hi, I've included a video below about the bug. However, for context, this bug is about in the Asset Browser new table view. Search is completely ignored and doesn't show any result.  I would expect that search operates exactly like the other two views, thumbnail and list view. 

If we are unable to fix this bug before the general release, Luis, Daniel and I spoke about a good back up plan being that we disable search in table view until we can get the feature working. We would also need to prevent a user from switching into table view IF a use started a search in a different view and then tried to switch into table view while a search is in process. I showed this in the video.

Repo steps:
- Open the editor (windows box) 
- Open the asset browser (if not already open)
- On the far right side of the Asset browser window, change your view to table view.
- On the far left, start a search for anything that's in your project.
-  Notice the results are incorrect.

https://user-images.githubusercontent.com/82551958/229607491-21a1f80d-c73d-4577-a0b5-04d72b9680cb.mp4

**Comment by jjjoness** [comment]
@rainbj I spent some time today looking at fixing this properly, but it will probably take some days. I've implemented the backup plan and will continue with the proper fix tomorrow.

**Comment by jjjoness** [comment]
Re-opening to fix properly.

**Comment by jjjoness** [comment]
I have the functionality working now, working on the look and feel. Basing it on the Figma doc.
