### ISSUE TITLE
Bug - Asset Browser - Remove lines between buttons

### ISSUE THREAD

**Issue by rainbj** [o3de/o3de#15526]
**Describe the bug**
In the main header bar for the Asset Browser (button bar). This bar includes back and forward arrow buttons, filter button, and Add new button. You will notice that between each of the buttons, there are random divider lines being added behind each button. We should remove these lines between each of these elements as they are touching the icon buttons (no spacing), making the interface look like they are broken. This divider line styles are also not the correct divider lines to be used.

![2023-04-03_12-45-00](https://user-images.githubusercontent.com/82551958/229611446-0c8e94ce-ef02-490d-a549-4ed31e2328c8.png)

**IF we can figure out how to add a divider line properly** 
- We should only have one divider in the button bar, and it should be located between the (forward/back) button and add new button.
- It should be the same as in the main header, which is only 1px wide.
- About half the height (Height would need to be verified on main header bar)
- padding is 10-15px on both sides of the
- Color is black.

![2023-04-03_12-54-55](https://user-images.githubusercontent.com/82551958/229613528-7bbf40fe-dee4-4147-9802-ca8c4b83f9fd.png)

**Comment by sphrose** [comment]
@rainbj Should this be closed considering the changes coming in https://github.com/o3de/o3de/pull/15942?

**Comment by dtamkin1** [comment]
Closed by #15942
