### ISSUE TITLE
Multiplayer System Script Nodes Require System Entity Id

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#15533]
Multiplayer System Script Canvas nodes require passing in an entity id, even though, as a system component, there can only be 1 provider for the node's functionality.

**Steps to reproduce**
1. Open Script Canvas
2. Add a Multiplayer System node (example: GetOnEndpointDisconnectEvent)
3. See nodes

**Expected behavior**
The node doesn't require passing in any input. Node's are properly labelled.

**Actual behavior**
The node requires passing in an entity id. But the expected entity id is the system entity which is entity(0). Instead, this should be handled for developers behind the scenes. The nodes are also missing there labels.
![image](https://user-images.githubusercontent.com/32776221/229692739-942fab87-326a-4b1c-b1cd-8964e61f7130.png)

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
26273c22ff71950eb68d137fed25125ebbaa12d6
Tue Mar 28 18:46:50 2023

**Comment by lmbr-pip** [comment]
Issue has been fixed by Gene. 

Global system entity is only valid input.
