### ISSUE TITLE
Empty type-name component alias for pending and disabled components

### ISSUE THREAD

**Issue by forkercat** [o3de/o3de#15546]
**Describe the bug**

The issue was discovered in a DPE inspector issue https://github.com/o3de/o3de/issues/15509 where PrefabComponentAdapter asserts on empty component alias.

The component alias is empty after these operations:
1. Add a pending component that has dependency on other components that are missing
2. First loading a prefab with entity that has disabled components (e.g. loading a level, instantiate-prefab, etc)
3. First loading a prefab with entity that has pending components (same)

**Steps to reproduce**
1. Create an empty level
3. Create an entity
4. Disabled Component - Add any component and disable the component
5. Pending Component - Add 'Vegetable Surface Mask Filter' or 'Audio Animation' component which has dependency on components that are not available in the entity.

**Found in Branch**

Development https://github.com/o3de/o3de/commit/ec299f7b6c27f03e48a7b0a9788637c23d90b598

**Cause**

After the PR https://github.com/o3de/o3de/pull/15256 that introduces type-name component alias, a new function `OnPrepareForAdditionToEntity` is used to set up the component alias before the entity is added to the entity. It is added right after `Component::SetEntity`. However, it is not called in the following places:
1. [EditorEntityActionComponent::AddExistingComponentsToEntityById()](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityActionComponent.cpp?L695)
2. [EditorPendingCompositionComponent::Init()](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorPendingCompositionComponent.cpp?L96:14)
3. [EditorDisabledCompositionComponent::Init()](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorDisabledCompositionComponent.cpp?L83:14)

**Question 1 - Should we keep track of component alias in these two editor composition components?**

Yes, we should. Before the type-name change, the component can be tracked in the composition components. Basically, we set component alias in `SetEntity` based on the component id for each component stored in the composition component.

We need to continue keeping track of the component alias to prevent issue of unexpected component alias change. Override patches are dependent on the invariant component alias, including the suffix number.

**Question 2 - Why can't we just add additional missing OnPrepareForAdditionToEntity calls?**

We can, but I think it doesn't resolve the potential problem that component alias suffix would unexpectedly change if we have multiple components of the same type.

My understanding is that this alias setup call is only invoked after `SetEntity` and before adding the component to the `m_components` in an entity. For components that are being added to composition components, if we add the call there, it means that we try to calculate and set up the component alias there. Inside `OnPrepareForAdditionToEntity`, the calculation depends on what components we already have in `m_components` to get the right suffix. I think eventually it would lead to unexpected suffix change for a component alias. Imagine the case where users may disable and enable the component and its suffix might change if there are multiple components of the same type in the entity.

To learn more about how suffix is calculated, see this PR that introduces type-name based component alias: https://github.com/o3de/o3de/pull/15256

To resolve this, we should consider these points:
1. We need to have component alias serialized for each component stored in composition components.
2. In `OnPrepareForAdditionToEntity`, we need to calculate the alias based on existing components on entity's `m_components` and pending and disabled components, to prevent same suffix.

**Comment by forkercat** [comment]
Adding some additional notes.

**EditorPendingCompositionComponent?**

It is an editor component that holds components that are pending. One instance is that if the component is dependent on some missing components, that component would be absent in entity's component list but added to the pending composition component.

```json
"EditorPendingCompositionComponent": {
    "$type": "EditorPendingCompositionComponent",
    "Id": 155833809691917884,
    "PendingComponents": [
    {
        "$type": "EditorAnimAudioComponent",
        "Id": 10381824783235843033
    }
}
```

**EditorDisabledCompositionComponent?**

Similar to the pending composition component, a disabled component would be added to `EditorDisabledCompositionComponent`. Property values are stored right after the type and id fields if any.

```json
"EditorDisabledCompositionComponent": {
    "$type": "EditorDisabledCompositionComponent",
    "Id": 832198321983129831,
    "DisabledComponents": [
    {
        "$type": "EditorTagComponent",
        "Id": 821938219389128392198
    }
}
```

When we try to enable a disabled component, the component would be removed from the disabled composition component and then added to the pending composition component (ref: [EditorEntityActionComponent::EnableComponents](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityActionComponent.cpp?L365)). Once added, a following call [ScrubEntity](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityActionComponent.cpp?L788) will examine the pending components and add them to entity's component list if they are ready, which will eventually call 'OnPrepareForAdditionToEntity'.

**Comment by monroegm** [comment]
@forkercat If this has been fixed with the above PR, can this be closed?

**Comment by forkercat** [comment]
No, the above PR just mitigated the asserts on the empty alias. Having discussions with @michabr on this issue.

Tagging @srikappa-amzn for visibility.
