### ISSUE TITLE
O3DE Project Manager: Adding a valid remote gem depot with a URL with a trailing slash or space causes errors

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#15557]
**Describe the bug**
When attempting to add a valid remote gem depot link that has either a trailing slash in the url or trailing white space will cause the O3DE Project manager to throw an error.

**Assets required**
A URL to a remote repository that has a `repo.json` configured for remote gems. (EG: https://canonical.o3de.org/)

**Steps to reproduce**
1. Open O3DE Project Manager
1. Open the Gem Catalog
1. Open the Remote Gem Sources manager
   * `Hamburger Menu → Show Gem Repos`
1. Click the Add Repository Button
1. Put in the valid URL using the various valid formats:
   * `https://canonical.o3de.org/`
   * `https://canonical.o3de.org/ ` (trailing white space is intentional)
   * `https://canonical.o3de.org ` (trailing white space is intentional)
   * `https://canonical.o3de.org`

**Expected behavior**
Trailing white space and trailing slashes are trimmed from the URL before attempting to resolve allowing for the remote gem depot to be added to the Remote Gem Sources Manager.

**Actual behavior**
* **Trailing White Space**: Throws a python parsing error
* **Trailing Slash**: Open
* **No Trailing White Space, No Trailing Slash**: Remote Gem depot is added to the Remote Gem Sources Manager.

**Found in Branch**
stabilization/2305

**Commit ID from**
[o3de/o3de/stabilization/2305@49407a3](https://github.com/o3de/o3de/commit/49407a3f8c132b90f4850937963a7ade43fa7640)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Screenshots/Video**

The following video shows the 3 encountered behaviors (trailing slash error, trailing white space error, successful remote gem depot resolution):
![8290220E-8003-4F5D-9C88-882F4F2738D3](https://user-images.githubusercontent.com/29718640/229933721-1261077d-aab1-44cd-ba2c-0049ba883fbf.GIF)

High Def:  https://user-images.githubusercontent.com/29718640/229933435-93597453-770c-4355-a482-30450f379cc3.MP4

**Comment by AMZN-alexpete** [comment]
This should be fixed by https://github.com/o3de/o3de/pull/15411

**Comment by AMZN-alexpete** [comment]
Closing as fixed by [linked](https://github.com/o3de/o3de/pull/15474)
