### ISSUE TITLE
Console is flooded with MeshDrawPacket errors when opening a level or resizing the Viewport

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#15561]
**Describe the bug**
MeshDrawPacket errors (8x) can be observed in the Console upon opening a level or creating a new one. Resizing the Viewport makes the following error spam the Console even more: `[Error] (MeshDrawPacket) - All draw items in a draw packet need to share the same root constants layout. This means that each pass (e.g. Depth, Shadows, Forward, MotionVectors) for a given materialtype should use the same layout.`

The same issue occurs on both Linux and Windows.

Please note that the issue does not occur in the latest Stabilization/2305 build.

Refer to the attached video and log for more information.

**Steps to reproduce**
1. Launch the Editor.
2. Create a new level or open an existing one.
3. Resize the Viewport.

**Expected behavior**
No errors appear in the Console when opening a level or resizing the Viewport.

**Actual behavior**
Console is flooded with MeshDrawPacket errors when opening a level or resizing the Viewport.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/230054766-8305795a-e6a9-471c-afdb-ed342a5516fe.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[475973d](https://github.com/o3de/o3de/commit/475973d5c2586fa2b3026b7ccddbda4296a35de4)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i5-9600K
 - GPU: NVIDIA GeForce RTX 2070
 - Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/11157657/Editor.log)

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed on the latest Development (e495f15).
