### ISSUE TITLE
DPE Inspector: Component widgets in the Entity Inspector are sized according to the first component added in the level

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#15576]
**Describe the bug**
Component widgets in the Entity Inspector are sized according to the first component added in the level.

**Steps to reproduce**
1. Launch the Editor with the DPE and Inspector Overrides enabled:
```
Editor.exe --ed_enableDPE=true --regset=O3DE/Preferences/Prefabs/EnableInspectorOverrideManagement=true
```
2. Create 2 new entities.
3. On the first entity, add a Camera component.
4. On the second entity, add a Comment component.

**Expected behavior**
Component widgets are appropriately sized to properly display all properties.

**Actual behavior**
Component widget size appears to be based on that of the first component added in a level.

**Screenshots/Video**
![component_widget_size](https://user-images.githubusercontent.com/82226555/230155786-a992e0dc-0a48-4e31-8959-c527c1141a00.jpg)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
3a1423a5cecf928aa256acf1c1f9bdf7ea99814c

**Comment by alexmontAmazon** [comment]
Will be fixed by https://github.com/o3de/o3de/pull/15928
