### ISSUE TITLE
DPE Inspector: Component property labels are inconsistently greyed out for inactive components

### ISSUE THREAD

**Issue by jckand** [o3de/o3de#15577]
**Describe the bug**
Component property labels are inconsistently greyed out for inactive components.

**Steps to reproduce**
1. Launch the Editor with the DPE enabled:
```
Editor.exe --ed_enableDPE=true
```
2. Create a few new entities.
3. Add various components which are inactive until additional components are added to the various entities (e.g. Perlin Noise Gradient, Image Gradient, etc.)
4. Observe the component properties on the component widgets.
5. Deselect/reselect the same entity a few times.

**Expected behavior**
Inactive component property labels are greyed out.

**Actual behavior**
Some inactive component properties appear as though they're enabled (though the actual editable fields are properly disabled). This can also change from selection to selection.

**Screenshots/Video**
![component_property_labels](https://user-images.githubusercontent.com/82226555/230157997-4b63de19-db7f-46c8-b95b-283e24807456.jpg)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
3a1423a5cecf928aa256acf1c1f9bdf7ea99814c

**Comment by lawsonamzn** [comment]
The components in the inactive or pending list are not valid to query for any purpose and their properties should not show up.  They are in a list of inactive components, and have not been "initialized" or "activated" - and thus they are not connected to busses, haven't created any internal pointer data they may access if you start talking to them, etc.    Trying to show their properties will cause crashes.

**Comment by alexmontAmazon** [comment]
Likely fixed by:
https://github.com/o3de/o3de/pull/15793

Could you please verify?

**Comment by alexmontAmazon** [comment]
This is just label enabling/disabling which I don't believe we do yet. This should be a quick fix

**Comment by alexmontAmazon** [comment]
Fixed now, likely by disabling Handler recycling

**Comment by alexmontAmazon** [comment]
not fixed, I misunderstood the given description. We need to make sure the entire DPE widget is disabled, it is not an individual label problem.

**Comment by alexmontAmazon** [comment]
please retest!

**Comment by alexmontAmazon** [comment]
for real fixed.
