### ISSUE TITLE
Linux: Snap installer does not include required Qt Libraries for GUI applications to launch

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#15581]
**Describe the bug**
After installing the Linux snap package, the GUI applications fail to launch due to missing Qt libs.

This issue is related to o3de/o3de#11640.

**Assets required**

- Latest O3DE Snap installer: https://o3debinaries.org/2.0.0/Linux/o3de_2.0.0_amd64.snap
- Linux Snap installer is installed
   -  In terminal run `sudo apt update` then `sudo apt install snapd`

**Steps to reproduce**

1. Download the latest O3DE Snap installer.
1. Install using the following command
   * `snap install o3de_<version>_amd64.snap --classic --dangerous`
1. After installed attempt to Launch the **O3DE Project Manager**

**Expected behavior**
Application launches with no errors

**Actual behavior**
Application fails to launch with an error alerting the user that `libQt5Concurrent.so.5` was not found.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/29718640/230168643-70ebf438-5e02-4b50-bce8-4594508a925b.png)

**Found in Branch**
2305/stabilization installer

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu 20.04

**Comment by amzn-changml** [comment]
Does this occur in Ubuntu 22.04?

**Comment by LB-ArturZieba** [comment]
We checked the snap installer on three machines: two with Ubuntu 20.04 and one with Ubuntu 22.04.

O3DE can be installed and uninstalled using both the .deb and .snap packages on both Ubuntu 20.04 and 22.04, however built projects cannot be launched. All of the project assets were processed via the Asset Processor, however multiple shader assets were failing and the Editor itself crashed when launching after reaching a certain number of assets processed.

Installer from the .deb package worked without new issues; projects were created and launched successfully.

Please refer to the https://github.com/o3de/o3de/issues/15856 for more information.

**Comment by AMZN-Dk** [comment]
We are closing this out, I've also verified this specific issue does not occur. New issue tracked in #15856
