### ISSUE TITLE
Outliner Overrides: Undo/Redo for add/delete entity override operations results in error message

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#15606]
**Describe the bug**
Undo/Redo for add/delete entity override operations results in error message

```
[Error] (Prefab) - Failed to find an owning instance for entity with id 15090783851798142479.
```

**Steps to reproduce**
1. Launch the Editor.
2. Open a new or existing level.
3. Create a new prefab or instantiate an existing prefab.
4. Delete an entity from the prefab as an override.
5. Undo, and note the Console
6. Add an entity to the prefab as an override.
7. Undo, and then Redo, and note the Console.

**Expected behavior**
Prefab overrides can be undone/redone free of errors.

**Actual behavior**
An error message is thrown when the entity is restored to the prefab in either case.

**Found in Branch**
stabilization/2305

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Latest installer (4/6)

**Comment by forkercat** [comment]
duplicate: I think it should be related to this issue https://github.com/o3de/o3de/issues/15087 opened a while ago. I put down some findings and possible solutions in that ticket.

**Comment by forkercat** [comment]
Fixed. See updates in #15087.
