### ISSUE TITLE
O3DE 23.05.0 Release: Testing Features Grid Updates

### ISSUE THREAD

**Issue by Naomi-Wash** [o3de/o3de#15633]
Hi @Kadino @AMZN-Dk,

As part of the 23.05.0 release action, we need your help to update [the features grid](https://www.o3de.org/docs/release-notes/22-10-0/feature-state/) with the latest updates. [Here ](https://github.com/o3de/community/tree/main/features)is the repo that contains the features grid. There is also instruction on how to update the features grid in the readme file. Can we have this completed by April 20th, 2023? Once you have completed it, please close the ticket and move it to "Pre-Release - Done". Let me know if you have any questions!

**Comment by Kadino** [comment]
No major features from SIG-Testing this release, but I'll look through the grid and make any necessary updates shortly.

**Comment by Naomi-Wash** [comment]
Thank you!
