### ISSUE TITLE
Cleanup - Delete the 23.05 stabilization branch

### ISSUE THREAD

**Issue by Naomi-Wash** [o3de/o3de#15643]
Need to delete delete the stabilization/2305 branch once the release is done for all repos involved in the release.

**Comment by vincent6767** [comment]
@Naomi-Wash will help follow up about this

**Comment by amzn-changml** [comment]
I'll send out an impactful change notification, then delete the branches

**Comment by vincent6767** [comment]
https://discord.com/channels/805939474655346758/852574203437121586/1106332145196216391
I confirmed the branch was deleted. Thanks, @amzn-mike !
