### ISSUE TITLE
DPE Inspector Overrides: "Parent activation" and "Static" properties on the Transform component continue to display override visualization after being manually reverted

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#15661]
**Describe the bug**
"Parent activation" and "Static" properties on the Transform component continue to display override visualization after being manually reverted.

**Steps to reproduce**
1. Launch the Editor with the DPE and Inspector Overrides enabled:
```
Editor.exe --ed_enableDPE=true --regset=O3DE/Preferences/Prefabs/EnableInspectorOverrideManagement=true
```
2. Open a new or existing level.
3. Create a new or instantiate an existing prefab.
4. Select any entity in the prefab, and toggle the "Static" property on the Transform component.
5. Untoggle the "Static" property.
6. Change the "Parent activation" property on the Transform component.
7. Change the "Parent activation" property back to the original value.

**Expected behavior**
Manually reverting property overrides reverts the override visualization.

**Actual behavior**
Override visualization remains on "Static" and "Parent activation" properties, even after manually reverting the properties to their original values.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82226555/231012122-ceb272d2-c5e3-4e6a-bf1e-ed5299f72efd.png)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
311c24f1a5264b6e4e3b6709831759d014d24168

**Comment by jckand-amzn** [comment]
After more testing, this seems like a general issue with many different components and properties. Some work as expected where if the value is manually changed back to the default, the override visualization is cleared, but several properties continue to display the override visualization.

**Comment by forkercat** [comment]
It should be fixed for now. Note that manually changing values back to the default, it is expected that the override visualization stays.
