### ISSUE TITLE
Assert "Pipeline layout is null."

### ISSUE THREAD

**Issue by l-sempe** [o3de/o3de#15684]
**Describe the bug**
I'm working towards learning how to render simple things using the Atom renderer, even though I followed existing examples, created a feature processor (followed the "Stars" gem example)  I ran into this assert:

`AZ_Assert(false, "Pipeline layout is null.");`

I also noticed this debug log:

```
[Error] (PipelineState) - Failed to compile graphics pipeline state. Check the D3D12 debug layer for more info.
[Error] (PipelineStateCache) - Failed to compile pipeline state. It will remain in an initialized state.
System: 
```

The assert is not helpful in troubleshooting the problem. What can cause the pipeline layout to be null? as far as I can see, I am providing one in the code. Is there documentation I can reference? did I miss an important step in setting up my feature processor?

Also, the error messages do not provide enough information as to which PipelineState failed to compile. or why, or, even how to "check the D3D12 debug layer". For example, in the Asset Processor the shaders compiled without errors, is there something else that is required?

**Expected behavior**
As much as possible, asserts should provide some guidance on how to solve the issue, or point towards documentation on troubleshooting

**Actual behavior**
An minimal assert, through debugging I can see the pipeline is in fact null, though comparing against another gem, I cannot see where it should get initialized correctly, or where it failed, nor could I find documentation that lead to a solution. I will update this issue when I find the missing link.

Eventually found the cause:

```
D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Vertex Shader - Pixel Shader linkage error: Stages are incompatible with each other. Semantic 'COLOR' is always read by the downstream shader, but never written by the upstream shader (even though the semantic is present in its output signature). [ STATE_CREATION ERROR #664: CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_NEVERWRITTEN_ALWAYSREADS]
Exception thrown at 0x00007FFD1E73FDEC in Editor.exe: Microsoft C++ exception: _com_error at memory location 0x0000002C29CE83B0.
```

**Comment by moudgils** [comment]
I think this may have been fixed by my PR in popcornfx repo - https://github.com/PopcornFX/O3DEPopcornFXPlugin/pull/40 especially if the shader in question is BillboardDistortion shader. But we will need to update our commit to get this fix.

**Comment by l-sempe** [comment]
> I think this may have been fixed by my PR in popcornfx repo - [PopcornFX/O3DEPopcornFXPlugin#40](https://github.com/PopcornFX/O3DEPopcornFXPlugin/pull/40) especially if the shader in question is BillboardDistortion shader. But we will need to update our commit to get this fix. Tag @mbalfour-amzn

Thanks! in this case it was in a shader I wrote, the error I got from the DX Debug Layer was correct, I had not linked the OUT.m_color parameter. My suggestion is to have a troubleshooting guide that the asserts point towards that explain how to enable the DX Debug Layer and what to look for. I've put this on my list to contribute to the docs and update the asserts, as I continue learning Atom.

**Comment by moudgils** [comment]
More information - 
- https://github.com/o3de/o3de/wiki/GPU-Crash-Debugging-and-Reporting
- https://github.com/o3de/o3de/wiki/CPU-&-GPU-Debugging-Tools
and a video to go with it - https://youtu.be/WIUhaVXFDkc

**Comment by moudgils** [comment]
@l-sempe If this issue is fixed can we close this? We will track Gene's UI component issue in a separate GHI. Thanks
