### ISSUE TITLE
Linux: Viewing AnimGraph in the Asset Browser's Tree View causes an assert to be printed to Console

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#15698]
**Describe the bug**
If a folder containing an AnimGraph is opened in the *Asset Browser* while the Tree View is active, an assert is printed to the Console.

Assert information:
File:
```
/home/gpc-610/builds/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp
```
Condition:
```
(140716550726848) 'int AzToolsFramework::AssetBrowser::EntryDelegate::DrawThumbnail(QPainter *, const QPoint &, const QSize &, const AzToolsFramework::AssetBrowser::AssetBrowserEntry *) const'
Asset Browser Icon not found for file 'Editor/Images/AssetBrowser/AnimGraph_80.svg'
```
Line: 151

This issue does not occur on Windows.

This issue also occurs on the Development (1820553) branch.

**Steps to reproduce**
1. Make sure the *Asset Browser* is in the Tree View (fourth button from the right in the top-right corner).
2. In the *Asset Browser* navigate to any folder that contains an AnimGraph (if none are present, you can create the asset by right-clicking the folder and selecting *Create* > *AnimGraph* from the context menu).

**Expected behavior**
Nothing of note happens.

**Actual behavior**
An assert is printed to the Console.

**Video and full assert log**

https://user-images.githubusercontent.com/86952082/231767368-332fa724-e8f6-4e89-b7f2-f79e224b9fdc.mp4

[AnimGraphTreeViewFull.txt](https://github.com/o3de/o3de/files/11222465/AnimGraphTreeViewFull.txt)

**Found in Branch**
Stabilization/2305 (1ff603a)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
1ff603a58ff71e79b70988d48540672c09c3879b

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-ArturZieba** [comment]
It should be noted that this issue seems to be related to: https://github.com/o3de/o3de/issues/15697 and https://github.com/o3de/o3de/issues/15699.

**Comment by AMZN-daimini** [comment]
Could no longer reproduce. Closing.
