### ISSUE TITLE
Linux: Viewing AnimGraph in the Asset Browser's List View causes an assert to be printed to Console

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#15699]
**Describe the bug**
If a folder containing an AnimGraph is opened in the *Asset Browser* while the List View is active, an assert is printed to the Console.

Assert information:
File:
```
/home/gpc-610/builds/o3de/Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
```
Condition:
```
(140716550726848) 'virtual void AzToolsFramework::AssetBrowser::ExpandedTableViewDelegate::paint(QPainter *, const QStyleOptionViewItem &, const QModelIndex &) const'
Asset Browser Icon not found for file 'Editor/Images/AssetBrowser/AnimGraph_80.svg'
```
Line: 456

This issue does not occur on Windows.

This issue also occurs on the Development (1820553) branch.

**Steps to reproduce**
1. Make sure the *Asset Browser* is in the List View (second button from the right in the top-right corner).
2. In the *Asset Browser* navigate to any folder that contains an AnimGraph (if none are present, you can create the asset by right-clicking the folder and selecting *Create* > *AnimGraph* from the context menu).

**Expected behavior**
Nothing of note happens.

**Actual behavior**
An assert is printed to the Console.

**Video and full assert log**

https://user-images.githubusercontent.com/86952082/231768852-12effa63-3336-497e-96f0-76dc89194a7c.mp4

[AnimGraphListViewFull.txt](https://github.com/o3de/o3de/files/11222502/AnimGraphListViewFull.txt)

**Found in Branch**
Stabilization/2305 (1ff603a)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
1ff603a58ff71e79b70988d48540672c09c3879b

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by AMZN-daimini** [comment]
Could no longer reproduce. Closing.
