### ISSUE TITLE
"Show in Asset Browser" doesn't work with the new Asset Browser

### ISSUE THREAD

**Issue by AMZN-stankowi** [o3de/o3de#15703]
**Describe the bug**
The "Show in Asset Browser" feature of the Asset Processor no longer works with the new Asset Browser.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Open the Editor and Asset Processor
2. In the Editor, make sure "Hide Engine Folders" and "Hide Unusable Assets" are unchecked, to verify those features aren't hiding the asset.
3. In the Asset Processor, on the Jobs tab, right click any asset and select "Show in Asset Browser"

**Expected behavior**
The Asset Browser navigates to, and shows this asset as selected.

**Actual behavior**
Nothing happens in the Editor or with the Asset Browser.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/4838196/231818136-ccbfc1ac-3a4e-4f04-999d-d28ed888dd23.png)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
18205539abf1b1d2eb3959c0a1c42a3eea16a455

**Desktop/Device (please complete the following information):**
Windows

**Comment by guillaume-haerinck** [comment]
Tested on dev branch on e9aa8824bff99da011d9a636885243b763a7081a without repro. I think ticket can be closed

![repro](https://github.com/o3de/o3de/assets/19243508/ee10a426-1e39-4b87-91a9-66bdde79670b)
