### ISSUE TITLE
DPE Inspector: Color properties do not update until related properties are update or game mode is run

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#15727]
If you make changes to a color property you will not see the effects in the scene until you run the game or change a related property such as intensity.

Steps to reproduce

1.     Launch the Editor with the DPE enabled:

`Editor.exe --ed_enableDPE=true`

 2. Create a new entity.
 3. Add a lighting component with a color property (directional easiest to repro)
 4. Change the lighting color by either modifying the color values or using the color picker

Expected results:
The color of entities reflecting the light in the scene changes as you modify the color property in entity inspector

Actual results:
You do not see the color changes until you change another property such as intensity or run the game.

**Comment by alexmontAmazon** [comment]
fixed in PR: https://github.com/o3de/o3de/pull/15870
