### ISSUE TITLE
O3DE.bat Usage Menu Missing "Keep-License-Text" Param

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#15720]
When creating a new gem from a template the o3de license is stripped out by default unless using the "keep-lincense-text" parameter. But this parameter is not included as a valid parameter.
![image](https://user-images.githubusercontent.com/32776221/232170446-f5a6219e-a804-4d5f-af06-9eeab429aeb3.png)

**Describe the solution you'd like**
Add --keep-license-text as a valid usage 

**Describe alternatives you've considered**
Leave the O3DE license enabled by default and instead require a parameter for stripping out the license. 
Keeping the license makes it easier for developers who want to contribute to o3de.

**Comment by lumberyard-employee-dm** [comment]
This option is shown in the help menu when as it is the `-kl` option.

When using the `o3de.bat create-gem --help` option the full description for the option is detailed
![image](https://user-images.githubusercontent.com/56135373/232542245-57264221-ed42-49c8-a67a-f21ae7c1d5e1.png)
