### ISSUE TITLE
Project Manager: Multiplayer Template "Failed to Create Project"

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#15732]
Creating a new project using Multiplayer Template results in an error popup "Failed to Create Project"

1. Open o3de.exe (Aka Project Manager)
1. Select "Create New Project"
1. Add the o3de-extra remote repository  https://github.com/o3de/o3de-extras.git remote
1. Download MultiplayerTemplate
1. Create a new project using Multiplayer Template

**Expected behavior**
The new project is created

**Actual behavior**
Error popup. A project is placed on my hard drive, but the project is not populated inside of ProjectManager and is not registered with O3DE
![image](https://user-images.githubusercontent.com/32776221/232608357-9f45d70f-c110-4e54-877d-2b455edb30f1.png)

[O3DE.log](https://github.com/o3de/o3de/files/11255711/O3DE.log)

**Found in Branch**
stabilization/2305

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/c4dd0ce2cb370446c18a951296c306073ddcf193

**Comment by Ulrick28** [comment]
@AMZN-Gene Is the issue only with multiplayer template, or does this occur with other templates as well?

**Comment by AMZN-Gene** [comment]
Not sure, we have a ROS remote template, but it breaks for other reasons (isn't zipped up for download)

**Comment by AMZN-Gene** [comment]
Thanks to @AMZN-alexpete this appears to be Multiplayer only, since it's using a Blast gem that is not longer available. I'll create another issue for improving the error message

**Comment by AMZN-Gene** [comment]
See https://github.com/o3de/o3de/issues/15734

**Comment by AMZN-alexpete** [comment]
The ProjectManager side of things should now be fixed via https://github.com/o3de/o3de/pull/15711
