### ISSUE TITLE
Project Manager: Improve "Failed to Create Project" Error

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#15734]
**Is your feature request related to a problem? Please describe.**
When Project Manager fails to create a project using a remote project template a generic "Failed to Create Project" appears.
There is no call to action for users to take on where to look to learn more, or how to fix it.

Original bug: https://github.com/o3de/o3de/issues/15732

**Describe the solution you'd like**
Add something to the popup to either be more specific based on the use case, or provide instructions of what .log file to look into to find clues as to what went wrong.

**Comment by Ulrick28** [comment]
Absolutely agree with this recommendation for a future release.

**Comment by AMZN-alexpete** [comment]
This has been addressed in https://github.com/o3de/o3de/pull/15711 which provides better messaging around what went wrong.
