### ISSUE TITLE
DPE Inspector: "Enable shadow" toggle on Light component does not allow corresponding properties to be edited

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#15731]
**Describe the bug**
"Enable shadow" toggle on Light component does not allow corresponding properties to be edited.

**Steps to reproduce**
1. Launch the Editor with the DPE enabled:
```
Editor.exe --ed_enableDPE=true
```
2. Open a new or existing level.
3. Create a new entity.
4. Add a Light component to the entity.
5. Toggle on "Enable shadow".
6. Attempt to adjust "Bias" or "Normal shadow bias" properties.

**Expected behavior**
Properties enabled post-toggle can be edited.

**Actual behavior**
Properties disabled until a toggle is flipped remain disabled after flipping the toggle.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82226555/232602827-0cb07c5b-4e40-434f-8de2-0713b9a8653f.png)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
eb6620ec705c4fdc1de63e3f34abb58b15e30926

**Comment by alexmontAmazon** [comment]
missing "group toggle" feature

**Comment by cgalvan** [comment]
This is duplicated by #16071
