### ISSUE TITLE
LyShine/Atom Assert Rendering JSON Table Ui Text

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#15755]
Ui Input text field causes assert when displaying a JSON table

**Steps to reproduce**
1. Create a UI Canvas with a Text Input 
2. Run the game and open the menu containing text input
3. Copy+Paste JSON into the text field
```
{\n"FleetId": "fleet-6ae4d52f-4a6b-4591-99da-122d37922490",\n"GameSessionId": "arn:aws:gamelift:us-west-2::gamesession/fleet-6ae4d52f-4a6b-4591-99da-122d37922490/gsess-f2c14a63-e5fe-462f-9f8e-6be95b9dda26",\n"IpAddress": "35.87.147.200",\n"PlayerId": "abc123",\n"PlayerSessionId": "psess-abbf0c36-14a6-4497-8441-1a89119d2bca"\n}
```

**Expected behavior**
UI renders the JSON table as text

**Actual behavior**
Assert  "Failed to draw due to invalid index or vertex data"
[Game.log](https://github.com/o3de/o3de/files/11269501/Game.log)

'''
 	MultiplayerSample.GameLauncher.exe!AZ::Debug::Platform::DebugBreak() Line 90	C++
 	MultiplayerSample.GameLauncher.exe!AZ::Debug::Trace::Assert(const char * fileName, int line, const char * funcName, const char * format, ...) Line 437	C++
 	LyShine.dll!AZ::RPI::DynamicDrawContext::DrawIndexed(const void * vertexData, unsigned int vertexCount, const void * indexData, unsigned int indexCount, AZ::RHI::IndexFormat indexFormat, AZStd::intrusive_ptr<AZ::RPI::ShaderResourceGroup> drawSrg) Line 478	C++
>	LyShine.dll!LyShine::PrimitiveListRenderNode::Render(UiRenderer * uiRenderer, const AZ::Matrix4x4 & modelViewProjMat, AZStd::intrusive_ptr<AZ::RPI::DynamicDrawContext> dynamicDraw) Line 157	C++
 	LyShine.dll!LyShine::RenderGraph::Render(UiRenderer * uiRenderer, const AZ::Vector2 & viewportSize) Line 980	C++
 	LyShine.dll!UiCanvasComponent::RenderCanvas(bool isInGame, AZ::Vector2 viewportSize, UiRenderer * uiRenderer) Line 2063	C++
 	LyShine.dll!UiCanvasManager::RenderLoadedCanvases() Line 629	C++
 	LyShine.dll!CLyShine::Render() Line 441	C++
 	[Inline Frame] Atom_RPI.Private.dll!AZStd::Internal::INVOKE(void(AZ::RPI::ViewportContextNotifications::*)() &) Line 177	C++
 	[Inline Frame] Atom_RPI.Private.dll!AZStd::invoke(void(AZ::RPI::ViewportContextNotifications::*)() &) Line 54	C++
 	[Inline Frame] Atom_RPI.Private.dll!AZ::EBusEventProcessingPolicy::Call(void(AZ::RPI::ViewportContextNotifications::*)() &) Line 437	C++
 	Atom_RPI.Private.dll!AZ::Internal::EBusContainer<AZ::RPI::ViewportContextNotifications,AZ::RPI::NotifyByViewportNameTraits,1,1>::Dispatcher<AZ::EBus<AZ::RPI::ViewportContextNotifications,AZ::RPI::NotifyByViewportNameTraits>>::Event<void (__cdecl AZ::RPI::ViewportContextNotifications::*)(void)>(const AZ::Name & id, void(AZ::RPI::ViewportContextNotifications::*)() && func) Line 146	C++
 	Atom_RPI.Private.dll!AZ::RPI::ViewportContext::OnBeginPrepareRender() Line 184	C++
 	[Inline Frame] Atom_RPI.Private.dll!AZStd::Internal::INVOKE(void(AZ::RPI::SceneNotification::*)() &) Line 177	C++
 	[Inline Frame] Atom_RPI.Private.dll!AZStd::invoke(void(AZ::RPI::SceneNotification::*)() &) Line 54	C++
 	[Inline Frame] Atom_RPI.Private.dll!AZ::EBusEventProcessingPolicy::Call(void(AZ::RPI::SceneNotification::*)() &) Line 437	C++
 	Atom_RPI.Private.dll!AZ::Internal::EBusContainer<AZ::RPI::SceneNotification,AZ::RPI::SceneNotification,1,1>::Dispatcher<AZ::EBus<AZ::RPI::SceneNotification,AZ::RPI::SceneNotification>>::Event<void (__cdecl AZ::RPI::SceneNotification::*)(void)>(const AZ::Uuid & id, void(AZ::RPI::SceneNotification::*)() && func) Line 146	C++
 	Atom_RPI.Private.dll!AZ::RPI::Scene::PrepareRender(AZ::RHI::JobPolicy jobPolicy, float simulationTime) Line 731	C++
 	Atom_RPI.Private.dll!AZ::RPI::RPISystem::RenderTick() Line 317	C++
 	Atom_RPI.Private.dll!AZ::RPI::RPISystemComponent::OnSystemTick() Line 171	C++
 	[Inline Frame] MultiplayerSample.GameLauncher.exe!AZStd::Internal::INVOKE(void(AZ::SystemTickEvents::*)() &) Line 177	C++
 	[Inline Frame] MultiplayerSample.GameLauncher.exe!AZStd::invoke(void(AZ::SystemTickEvents::*)() &) Line 54	C++
 	[Inline Frame] MultiplayerSample.GameLauncher.exe!AZ::EBusEventProcessingPolicy::Call(void(AZ::SystemTickEvents::*)() &) Line 437	C++
 	MultiplayerSample.GameLauncher.exe!AZ::Internal::EBusContainer<AZ::SystemTickEvents,AZ::SystemTickEvents,0,1>::Dispatcher<AZ::EBus<AZ::SystemTickEvents,AZ::SystemTickEvents>>::Broadcast<void (__cdecl AZ::SystemTickEvents::*)(void)>(void(AZ::SystemTickEvents::*)() && func) Line 1360	C++
 	MultiplayerSample.GameLauncher.exe!AZ::ComponentApplication::TickSystem() Line 1522	C++
 	[Inline Frame] MultiplayerSample.GameLauncher.exe!?A0xf794850f::RunMainLoop(AzGameFramework::GameApplication &) Line 108	C++
 	MultiplayerSample.GameLauncher.exe!O3DELauncher::Run(const O3DELauncher::PlatformMainInfo & mainInfo) Line 571	C++
 	MultiplayerSample.GameLauncher.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 29	C++
```


**Found in Branch**
development 
80c93f8dbde0cfa0e3cacba2c7ad38136739055e Mon Apr 17 17:30:01 2023 -0700

**Comment by moudgils** [comment]
@michabr Are you able to check why RPI is given bad index/verted data
