### ISSUE TITLE
Logging errors in material editor when setting MSAA samples to 1

### ISSUE THREAD

**Issue by lijianwen13** [o3de/o3de#15763]
**Describe the bug**
When I set "Samples" to 1 in file "MainRenderPipeline.azasset" which means turning off the MSAA, it shows many errors in material editor logging, and the shading in material editor isn't correct.
![image](https://user-images.githubusercontent.com/93694249/233250126-39d1986f-fded-45f3-b699-4357aa809f91.png)

**Assets required**
Just create a default standard material file, and open it in material editor.

**Steps to reproduce**
1. Go to file "MainRenderPipeline.azasset"
2. Change the "Samples" like this:
```    
"RenderSettings": {
    "MultisampleState": {
        "samples": 1
    }
}
```
3. Open the engine, and open the material editor
4. Look into the Logging window in material editor
5. See errors in the Logging window and incorrect shading result in the Preview window of material editor

**Expected behavior**
Don't show errors, correct shading result.

**Actual behavior**
So many errors about ShaderResourceGroup.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
latest commit

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel I9-12900k
 - GPU: NVidia RTX 3090
 - Memory: 128GB

**Comment by moudgils** [comment]
@dmcdiarmid-ly - It seems like a super variant related issues. Are you able tot take a look at Material editor with 1 msaa sample count? This error has been reported by multiple people now.

**Comment by dmcdiarmid-ly** [comment]
https://github.com/o3de/o3de/pull/15833
