### ISSUE TITLE
Linux: Saving White Box mesh asset without the .wbm file extension causes it to not be usable

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#15788]
**Describe the bug**
If a *White Box* mesh asset is saved with a name that does not contain the .wbm file extension, it won't be added afterwards, causing the file to not be usable. For example in *Script Canvas* when saving the graph, the .scriptcanvas file extension is in the dropdown and not in the file name itself and is added after saving.

This issue does not occur on Windows.

This issue also occurs on Development (a98541f).

This issue may be related to https://github.com/o3de/o3de/issues/7399 or https://github.com/o3de/o3de/issues/8354.

**Steps to reproduce**
1. Create an entity and add *White Box* component to it.
2. In the *White Box* component click on the *Save As ...* button.
3. Change the file save name so that it does not contain the .wbm file extension (for example to "abcd").
4. Attempt to assign the file saved in step 3 to *Mesh Asset* property in the *White Box* component.

**Expected behavior**
Mesh asset abcd.wbm is available to assign.

**Actual behavior**
No asset is available to assign.

**Video**

https://user-images.githubusercontent.com/86952082/234010261-ff702b69-3246-4928-885b-c549945db776.mp4

**Found in Branch**
Stabilization/2305 (706bafa)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
706bafaf918cd4e7c63a902d466b942011835047

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by pollend** [comment]
I'll have a look at this tomorrow.

**Comment by LB-ArturZieba** [comment]
Verified that the issue does not occur on build Development (5a77589) anymore. Closing the issue.
