### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by moudgils** [o3de/o3de#15794]
**Is your feature request related to a problem? Please describe.**

CommonSRG.azsli
```
partial ShaderResourceGroup PassSrg : SRG_PerPass_WithFallback
{ 
    float var;
}
```

ShaderX.azsl
```
#include "CommonSRG.azsli"
partial ShaderResourceGroup PassSrg : SRG_PerPass_WithFallback
{ 
    float varX;
}
```

ShaderY.azsl
```
#include "CommonSRG.azsli"
partial ShaderResourceGroup PassSrg : SRG_PerPass_WithFallback
{ 
    float4 varY;
}
```

As you can see above ShaderX and ShaderY have Pass Srg with a different layout. Currently if someone was to use this setup the runtime will incorrectly use ShaderX's SRGPool for ShaderY thinking that ShaderX and Shader Y have the same srg layout for pass srg. This happens due to this code

```
 // Create a uuid that combines string data for both the srgLayout and the srgName
            AZ::Uuid instanceUuid =
                AZ::Uuid::CreateData(reinterpret_cast<const AZStd::byte*>(srgLayout->GetUniqueId().data()), srgLayout->GetUniqueId().size())
                + AZ::Uuid::CreateData(reinterpret_cast<const AZStd::byte*>(srgName.GetStringView().data()), srgName.GetStringView().size());

```

The instanceUuid is created via using a combination of unique id and srg name to help de-duplicate RPI::SRGPool. Unique Id is the file path name related to the srg in question. In this specific use case ShaderX and Shader Y has unique id of "CommonSRG.azsli" and srg name "PassSrg". This results in ShaderY getting the SRGPool of ShaderX and hence the SRGdata layout does not match the layout associated with low level RHI descriptor table/set/argument table.

**Describe the solution you'd like**

One solution is to just ensure the shader never uses such use case and splits the SRGs into different files but we think that this use case is nice feature to have. As a result a possible way to support this is to modify the UniqueId and instead of using filename we use filename_srglayouthash (converted to string). The shader pipeline will need to essentially tag on the layout hash at the end of the filename which will ensure that ShaderY will get a different SRGPool.

**Additional context**
This issue arose from EditorFeedback feature. PR (https://github.com/o3de/o3de/pull/15795) fixed this by creating one big PassSrg which actually helps perf a little at the cost of a little gpu memory. Regardless it will be nice to have this support in case someone else tries to use it in future

**Comment by VickyAtAZ** [comment]
We may revert the change in https://github.com/o3de/o3de/pull/15795 after the feature is implemented since it's a good candidate to show how to use partial srg for pass srg and also validate the implementation.

**Comment by moudgils** [comment]
As discussed in the meeting this feature is lower in priority and should be addressed after Shader Management Console work is wrapped up.

**Comment by gadams3** [comment]
This should be resolved by the following pr lines listed below. The change is now include the SRG layout hash as part of the instance id.
https://github.com/o3de/o3de/pull/16871
https://github.com/o3de/o3de/pull/16871/files#diff-879be00ebc62c5a2c3edf1886254d07759744939a3f54084f371b1c283725e15R42-R57
