### ISSUE TITLE
Exception Request: Fix serialization error of Joint components in GameLauncher 

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de#15802]
Exception Requested to merge to stabilization by @adamdbrw.

## Related issue

- [x] https://github.com/o3de/o3de/issues/15798

### Final PR

- [x] https://github.com/o3de/o3de/pull/15799

## Exception Tracking

- [x] 1. Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
- [x] 2. Owning SIG comments on the PR explaining impact if this code does not go into stabilization.
- [x] 3. Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [x] 4. UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [x] 5. Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [x] (Must occur at some point before SIG-Release approval) Code has been approved for merging by maintainers
- [x] 6. SIG-Release Release Manager or co-Release Manager approves the exception, adding a comment indicating approval and the SIG they represent.
- [x] 7. If all approvals are accepted, then the exception PR may be merged
- [x] 8. Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
- [x] 9. Exception is complete

**Comment by tonybalandiuk** [comment]
@adamdbrw Please confirm that this has been tested in stabilization. Thanks.

**Comment by adamdbrw** [comment]
I confirm this has been tested in stabilization

**Comment by rainbj** [comment]
Approved from Sig-UI-UX.

**Comment by lgleim** [comment]
Approved & confirmed tested from SIG-Simulation
