### ISSUE TITLE
Source `release`  builds fail due to several `Wunused-but-set-variable` errors.

### ISSUE THREAD

**Issue by BytesOfPiDev** [o3de/o3de#15812]
**Describe the bug**
Compiling release builds fail due to several `Wunused-but-set-variable` errors.

Example:
https://github.com/o3de/o3de/blob/b5a1b571a63d45999440ebe0f83c9c7bebd08688/Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp#L389-L404

**Assets required**
N/A

**Steps to reproduce**
1. Create a project against the o3de source, not a pre-built  SDK. Alternatively, build the engine from source without a project.
2. Configure the project.
```
cmake -B build/linux -S . -G "Ninja Multi-Config" -DLY_UNITY_BUILD=OFF
```
4. Build the project in the `release` config.
```
cmake --build build/linux --target all --config release
```
6. See error.

```
2/4636] Building CXX object o3de/Code/Framework/AzFramework/CMakeFiles/AzFramework.dir/release/AzFramework/Archive/Archive.cpp.o
FAILED: o3de/Code/Framework/AzFramework/CMakeFiles/AzFramework.dir/release/AzFramework/Archive/Archive.cpp.o
/usr/bin/clang++-16.0.2 -DAZ_BUILD_CONFIGURATION_TYPE=\"release\" -DAZ_RELEASE_BUILD -DLINUX -DLINUX64 -DNDEBUG -DPAL_TRAIT_LINUX_WINDOW_MANAGER_XCB -DRELEASE -D_FORTIFY_SOURCE=2 -D_HAS_EXCEPTIONS=0 -D_RELEASE -D__linux__ -DCMAKE_INTDIR
=\"release\" -I/home/andre/repos/o3de/Code/Framework/AzFramework/. -I/home/andre/repos/o3de/Code/Framework/AzFramework/Platform/Linux -I/home/andre/repos/o3de/Code/Framework/AzFramework/Platform/Common -I/home/andre/repos/o3de/Code/Fram
ework/AzFramework/Platform/Common/Xcb -I/home/andre/repos/o3de/Code/Framework/AzCore/. -I/home/andre/repos/o3de/Code/Framework/AzCore/Platform/Linux -I/home/andre/repos/o3de/Code/Framework/AzCore/Platform/Common -I/home/andre/repos/o3de
/Code/Framework/AzNetworking/. -I/home/andre/repos/o3de/Code/Framework/AzNetworking/Platform/Common -I/home/andre/repos/o3de/Code/Framework/AzNetworking/Platform/Linux -I/home/andre/o3de-projects/Dink/build/linux/o3de/Code/Framework/AzN
etworking/Azcg/Generated/AzNetworking -isystem /home/andre/.o3de/3rdParty/packages/Lua-5.4.4-rev1-linux/Lua/include -isystem /home/andre/.o3de/3rdParty/packages/RapidJSON-1.1.0-rev1-multiplatform/RapidJSON/include -isystem /home/andre/.
o3de/3rdParty/packages/RapidXML-1.13-rev1-multiplatform/RapidXML/include -isystem /home/andre/.o3de/3rdParty/packages/zlib-1.2.11-rev5-linux/zlib/include -isystem /home/andre/.o3de/3rdParty/packages/zstd-1.35-multiplatform/zstd/lib -isy
stem /home/andre/.o3de/3rdParty/packages/cityhash-1.1-multiplatform/cityhash/src -isystem /home/andre/.o3de/3rdParty/packages/lz4-1.9.4-rev2-linux/lz4/include -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror
 -Wno-inconsistent-missing-override -Wrange-loop-analysis -Wno-unknown-warning-option -Wno-parentheses -Wno-reorder -Wno-switch -Wno-undefined-var-template -msse4.1  -O2 -std=c++17 -fPIC -MD -MT o3de/Code/Framework/AzFramework/CMakeFile
s/AzFramework.dir/release/AzFramework/Archive/Archive.cpp.o -MF o3de/Code/Framework/AzFramework/CMakeFiles/AzFramework.dir/release/AzFramework/Archive/Archive.cpp.o.d -o o3de/Code/Framework/AzFramework/CMakeFiles/AzFramework.dir/release
/AzFramework/Archive/Archive.cpp.o -c /home/andre/repos/o3de/Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp
/home/andre/repos/o3de/Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp:389:18: error: variable 'numFilesForcedToClose' set but not used [-Werror,-Wunused-but-set-variable]
        uint32_t numFilesForcedToClose = 0;
```

**Expected behavior**
Compilation succeeds.

**Actual behavior**
Compilation fails.

**Screenshots/Video**
N/A

**Found in Branch**
stabilization/2305

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
18f6f224c15b9d75762b3f2a31fabd50d852457d

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Opensuse Tumbleweed version 
 - Version 20230424
 - CPU AMD Ryzen 3700X
 - GPU RTX 3070
 - Memory 64GB

**Additional context**
I'm working on a PR to fix each occurrence by using `[[maybe_unused]]`, unless there's an alternate solution.

**Comment by lumberyard-employee-dm** [comment]
For unused variables such as `numFilesForcedToClose`, it can be removed from the code instead of marked with `[[maybe_unused]]`.

Newer versions of clang is better at detecting variables that are written to, but never read.

For those variables, since they are never read, they can just be removed.

**Comment by lumberyard-employee-dm** [comment]
> > For unused variables such as `numFilesForcedToClose`, it can be removed from the code instead of marked with `[[maybe_unused]]`.
> > Newer versions of clang is better at detecting variables that are written to, but never read.
> > For those variables, since they are never read, they can just be removed.
> 
> These are used in different trace methods, like `AZ_Warning`. It is just that these macros don't exist in release mode.

Ok, for variables that are only used in non-release configuration macros, then `[[maybe_unused]]` is the correct method to use then.
