### ISSUE TITLE
metal_mercury.material is missing two similar materials compared to other metal_ materials

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#15811]
**Describe the bug**
metal_mercury.material found here: https://github.com/o3de/o3de/tree/development/Gems/Atom/Feature/Common/Assets/Materials/Presets/PBR is missing two similar materials when compared with other metal_ materials found in the folder. Other materials also have _matte and _polished variants - for example metal_aluminium.material, metal_aluminium_matte.material and metal_aluminium_polished.material.

This issue also occurs on Development (360445e).

**Steps to reproduce**
1. Go to https://github.com/o3de/o3de/tree/development/Gems/Atom/Feature/Common/Assets/Materials/Presets/PBR and compare metal_mercury.material to other materials.

**Expected behavior**
All materials are consistent.

**Actual behavior**
Only metal_mercury.material is missing _matte and _polished variants.

**Found in Branch**
Stabilization/2305 (18f6f22)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
18f6f224c15b9d75762b3f2a31fabd50d852457d

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by moudgils** [comment]
This is not a bug.(By design)

**Comment by LB-ArturZieba** [comment]
Confirming the issue has been closed.
