### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by ghost** [o3de/o3de#15837]
Right after loading all assets on startup this happens:

`Module: Attempting to load module:/home/O3DE/Projects/MyProject/build/linux/bin/profile/libCrySystem.so
Module: Success!
Segmentation fault (core dumped)
`

On Fedora 38.  Everything compiles fine but the project editor won't start.  Haven't had a working build in over a week, on development branch.

**Comment by lmbr-pip** [comment]
@michaelbaudais - Can you provide your commit id for o3de/o3de as well as any logs/callstacks?

**Comment by RoddieKieley** [comment]
There was some discussion in discord, and I had noted that I could not reproduce it on Fedora 35. However today for the jam I did a new clean linux_clang_unity build of type profile and proceeded to create a new project to use. I now see the behaviour as described.

Running it through the debugger I see that it segfaults in EditorViewportCamera.cpp at line 187:
```
    AZ::Transform GetDefaultViewportCameraTransform()
    {
        auto viewportContextManager = AZ::Interface<AZ::RPI::ViewportContextRequestsInterface>::Get();
        if (auto viewportContext = viewportContextManager->GetDefaultViewportContext())
.
.
.
```
 as the viewportContextManager is NULL.
 
 Two other hints thus far:
 In CLayoutWnd::LoadConfig for the check if (layout < 0) layout is 0 and then segfault. Manually changing it to 7 and continuing allows the Editor to come up but without a rendering viewport and subsequently I notice that there is no note about initializaing the video card that I normally see:
 
![Screenshot from 2023-05-05 18-10-07](https://user-images.githubusercontent.com/980979/236567281-413788e6-81f4-494f-b08b-9fdd50324ef6.png)

Entire log from the run:
```
/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/Editor --project-path /wip/Projects/airvoid0
Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libEditorLib.so
Module: Success!
Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libCamera.Editor.so
Module: Success!
Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libLmbrCentral.Editor.so
Module: Success!
Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libMaestro.Editor.so
Module: Success!
Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libPrefabBuilder.Builders.so
Module: Success!
Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libSceneProcessing.Editor.so
Module: Success!
Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libSceneCore.so
Module: Success!
Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libSceneData.so
Module: Success!
Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libSceneBuilder.so
Module: Success!
SettingsRegistryMergeUtils: Optional config file "/wip/Projects/airvoid0/Cache/linux/user.cfg" not found.
System: Network layer initialized
AssetCatalog: Initializing asset catalog with root "/wip/Projects/airvoid0/Cache/linux"AssetCatalog: Loaded registry containing 118 assets.
Asset System Connection: Asset Processor Connection IP: 127.0.0.1, port: 45643, branch token 0x1E2C80BF
AssetProcessorConnection: 
==================================================================
AssetProcessorConnection: Trace::Warning
 /wip/src/github.com/o3de/o3de/Code/Framework/AzFramework/AzFramework/Asset/AssetSystemComponent.cpp(691): 'virtual bool AzFramework::AssetSystem::AssetSystemComponent::WaitUntilAssetProcessorConnected(AZStd::chrono::duration<float>)'
AssetProcessorConnection: Network connection attempt failure, Connect returned error AzSockError::eASE_ECONNREFUSED
AssetProcessorConnection: ==================================================================
AssetSystem: Ping time to asset processor: 0.44 milliseconds
Editor: Connected to Asset Processor
AssetSystem: Ping time to asset processor: 0.42 milliseconds
Editor: CriticalAssetsCompiled
AssetCatalog: Initializing asset catalog with root "/wip/Projects/airvoid0/Cache/linux"AssetCatalog: Loaded registry containing 118 assets.
Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libCrySystem.so
Module: Success!
Signal: SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0))
```

**Comment by LB-KacperBieniek** [comment]
The `Segmentation fault (core dumped)` now also appears when launching the Editor via Terminal on the latest development snap installer (https://o3debinaries.org/2.0.0/Linux/o3de_2.0.0_amd64.snap) on Ubuntu 22.04. . Here is the full log from launching the Editor with project path provided: [SnapEditorFailsToLaunch.txt](https://github.com/o3de/o3de/files/11429469/SnapEditorFailsToLaunch.txt)

**Comment by frizrh** [comment]
Reproduced this on my machine, I plan on looking into this to see what can be done

**Comment by nicholas-rh** [comment]
> There was some discussion in discord, and I had noted that I could not reproduce it on Fedora 35. However today for the jam I did a new clean linux_clang_unity build of type profile and proceeded to create a new project to use. I now see the behaviour as described.
> 
> Running it through the debugger I see that it segfaults in EditorViewportCamera.cpp at line 187:
> 
> ```
>     AZ::Transform GetDefaultViewportCameraTransform()
>     {
>         auto viewportContextManager = AZ::Interface<AZ::RPI::ViewportContextRequestsInterface>::Get();
>         if (auto viewportContext = viewportContextManager->GetDefaultViewportContext())
> .
> .
> .
> ```
> 
> as the viewportContextManager is NULL.
> 
> Two other hints thus far: In CLayoutWnd::LoadConfig for the check if (layout < 0) layout is 0 and then segfault. Manually changing it to 7 and continuing allows the Editor to come up but without a rendering viewport and subsequently I notice that there is no note about initializaing the video card that I normally see:
> 
> ![Screenshot from 2023-05-05 18-10-07](https://user-images.githubusercontent.com/980979/236567281-413788e6-81f4-494f-b08b-9fdd50324ef6.png)
> 
> Entire log from the run:
> 
> ```
> /wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/Editor --project-path /wip/Projects/airvoid0
> Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libEditorLib.so
> Module: Success!
> Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libCamera.Editor.so
> Module: Success!
> Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libLmbrCentral.Editor.so
> Module: Success!
> Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libMaestro.Editor.so
> Module: Success!
> Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libPrefabBuilder.Builders.so
> Module: Success!
> Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libSceneProcessing.Editor.so
> Module: Success!
> Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libSceneCore.so
> Module: Success!
> Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libSceneData.so
> Module: Success!
> Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libSceneBuilder.so
> Module: Success!
> SettingsRegistryMergeUtils: Optional config file "/wip/Projects/airvoid0/Cache/linux/user.cfg" not found.
> System: Network layer initialized
> AssetCatalog: Initializing asset catalog with root "/wip/Projects/airvoid0/Cache/linux"AssetCatalog: Loaded registry containing 118 assets.
> Asset System Connection: Asset Processor Connection IP: 127.0.0.1, port: 45643, branch token 0x1E2C80BF
> AssetProcessorConnection: 
> ==================================================================
> AssetProcessorConnection: Trace::Warning
>  /wip/src/github.com/o3de/o3de/Code/Framework/AzFramework/AzFramework/Asset/AssetSystemComponent.cpp(691): 'virtual bool AzFramework::AssetSystem::AssetSystemComponent::WaitUntilAssetProcessorConnected(AZStd::chrono::duration<float>)'
> AssetProcessorConnection: Network connection attempt failure, Connect returned error AzSockError::eASE_ECONNREFUSED
> AssetProcessorConnection: ==================================================================
> AssetSystem: Ping time to asset processor: 0.44 milliseconds
> Editor: Connected to Asset Processor
> AssetSystem: Ping time to asset processor: 0.42 milliseconds
> Editor: CriticalAssetsCompiled
> AssetCatalog: Initializing asset catalog with root "/wip/Projects/airvoid0/Cache/linux"AssetCatalog: Loaded registry containing 118 assets.
> Module: Attempting to load module:/wip/src/github.com/o3de/o3de/build/linux_clang_unity/bin/profile/libCrySystem.so
> Module: Success!
> Signal: SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0))
> ```

The issue you're describing sounds different than mine, since the segfault seems to happen at a different point in the code. Based on discussions my issue seems to be caused by attempting to make use of Vulkan raytracing features which are not supported by my drivers/hardware without checking. Here's the stack trace for reference:

`* thread #1, name = 'Editor', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x0000000000000000
    frame #1: 0x00007fff39e7f7c9 libAtom_RHI_Vulkan.Private.so`AZ::Vulkan::RayTracingPipelineState::InitInternal(this=0x000055555f6b4f18, deviceBase=0x0000555560070020, descriptor=0x00007fffffffaf40) at RayTracingPipelineState.cpp:176:48
    frame #2: 0x00007ffedacb2390 libDiffuseProbeGrid.Editor.so`AZ::RHI::RayTracingPipelineState::Init(this=0x000055555f6b4f18, device=0x0000555560070020, descriptor=0x00007fffffffaf40) at RayTracingPipelineState.cpp:143:37
    frame #3: 0x00007ffeda7656a1 libDiffuseProbeGrid.Editor.so`AZ::Render::DiffuseProbeGridRayTracingPass::CreateRayTracingPipelineState(this=0x0000555561cfdfa0) at DiffuseProbeGridRayTracingPass.cpp:108:40
    frame #4: 0x00007fff2b81bdc5 libAtom_RPI.Editor.so`AZ::RPI::Pass::Build(this=0x0000555561cfdfa0, calledFromPassSystem=false) at Pass.cpp:1200:13
    frame #5: 0x00007fff2b81bca7 libAtom_RPI.Editor.so`AZ::RPI::ParentPass::BuildInternal(this=<unavailable>) at ParentPass.cpp:366:24
    frame #6: 0x00007fff2b81bdc5 libAtom_RPI.Editor.so`AZ::RPI::Pass::Build(this=0x0000555561c9a760, calledFromPassSystem=false) at Pass.cpp:1200:13
    frame #7: 0x00007fff2b81bca7 libAtom_RPI.Editor.so`AZ::RPI::ParentPass::BuildInternal(this=<unavailable>) at ParentPass.cpp:366:24
    frame #8: 0x00007fff2b81bdc5 libAtom_RPI.Editor.so`AZ::RPI::Pass::Build(this=0x0000555561c2f380, calledFromPassSystem=false) at Pass.cpp:1200:13
    frame #9: 0x00007fff2b81bca7 libAtom_RPI.Editor.so`AZ::RPI::ParentPass::BuildInternal(this=<unavailable>) at ParentPass.cpp:366:24
    frame #10: 0x00007fff2bbf2e7e libAtom_RPI.Editor.so`AZ::RPI::RenderToTexturePass::BuildInternal(this=0x0000555561c2bd90) at RenderToTexturePass.cpp:73:19
    frame #11: 0x00007fff15ec5c65 libAtomToolsFramework.Editor.so`AZ::RPI::Pass::Build(this=0x0000555561c2bd90, calledFromPassSystem=false) at Pass.cpp:1200:13
    frame #12: 0x00007fff15ecd512 libAtomToolsFramework.Editor.so`AZ::RPI::Pass::ManualPipelineBuildAndInitialize(this=<unavailable>) at Pass.cpp:1399:13
    frame #13: 0x00007fff15fa087e libAtomToolsFramework.Editor.so`AZ::RPI::RenderPipeline::InitializeRenderPipeline(pipeline=0x0000555561c106f0, desc=<unavailable>) at RenderPipeline.cpp:177:46
    frame #14: 0x00007fff15fa04eb libAtomToolsFramework.Editor.so`AZ::RPI::RenderPipeline::CreateRenderPipeline(desc=0x00007fffffffbca0) at RenderPipeline.cpp:53:13
    frame #15: 0x00007fff1590cecf libAtomToolsFramework.Editor.so`AtomToolsFramework::PreviewRenderer::PreviewRenderer(this=0x0000555557a014d8, sceneName=<unavailable>, pipelineName=0x00007fffffffbd80) at PreviewRenderer.cpp:68:28
    frame #16: 0x00007fff1591e152 libAtomToolsFramework.Editor.so`void AZStd::Internal::function_util::get_invoker<void (), AZStd::Internal::function_util::function_obj_tag, AZStd::stateless_allocator>::call<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()>(AZStd::Internal::function_util::function_buffer&) [inlined] AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0::operator()(this=<unavailable>) const at PreviewRendererSystemComponent.cpp:67:55
    frame #17: 0x00007fff1591e0ac libAtomToolsFramework.Editor.so`void AZStd::Internal::function_util::get_invoker<void (), AZStd::Internal::function_util::function_obj_tag, AZStd::stateless_allocator>::call<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()>(AZStd::Internal::function_util::function_buffer&) [inlined] decltype(InvokeTraits::forward<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(fp)()) AZStd::Internal::INVOKE<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(f=<unavailable>) at invoke_traits.h:208:20
    frame #18: 0x00007fff1591e0ac libAtomToolsFramework.Editor.so`void AZStd::Internal::function_util::get_invoker<void (), AZStd::Internal::function_util::function_obj_tag, AZStd::stateless_allocator>::call<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()>(AZStd::Internal::function_util::function_buffer&) [inlined] AZStd::invoke_result<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>::type AZStd::invoke<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(f=<unavailable>) at invoke.h:54:16
    frame #19: 0x00007fff1591e0ac libAtomToolsFramework.Editor.so`void AZStd::Internal::function_util::get_invoker<void (), AZStd::Internal::function_util::function_obj_tag, AZStd::stateless_allocator>::call<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()>(AZStd::Internal::function_util::function_buffer&) [inlined] void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate(this=<unavailable>)::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()::operator()() at BusImpl.h:875:21
    frame #20: 0x00007fff1591e0ac libAtomToolsFramework.Editor.so`void AZStd::Internal::function_util::get_invoker<void (), AZStd::Internal::function_util::function_obj_tag, AZStd::stateless_allocator>::call<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()>(AZStd::Internal::function_util::function_buffer&) [inlined] decltype(InvokeTraits::forward<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(fp)()) AZStd::Internal::INVOKE<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()&>(f=<unavailable>) at invoke_traits.h:208:20
    frame #21: 0x00007fff1591e0ac libAtomToolsFramework.Editor.so`void AZStd::Internal::function_util::get_invoker<void (), AZStd::Internal::function_util::function_obj_tag, AZStd::stateless_allocator>::call<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()>(AZStd::Internal::function_util::function_buffer&) [inlined] AZStd::invoke_result<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>::type AZStd::invoke<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()&>(f=<unavailable>) at invoke.h:54:16
    frame #22: 0x00007fff1591e0ac libAtomToolsFramework.Editor.so`void AZStd::Internal::function_util::get_invoker<void (), AZStd::Internal::function_util::function_obj_tag, AZStd::stateless_allocator>::call<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()>(AZStd::Internal::function_util::function_buffer&) [inlined] void AZStd::Internal::function_util::invoke_void_return_wrapper<void>::call<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()&>(args=<unavailable>) at function_template.h:41:21
    frame #23: 0x00007fff1591e0ac libAtomToolsFramework.Editor.so`void AZStd::Internal::function_util::get_invoker<void (), AZStd::Internal::function_util::function_obj_tag, AZStd::stateless_allocator>::call<void AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZ::BusInternal::EBusImplTraits<AZ::TickEvents, AZ::TickEvents>>::QueueFunction<AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0>(AtomToolsFramework::PreviewRendererSystemComponent::Activate()::$_0&&)::'lambda'()>(function_obj_ptr=<unavailable>) at function_template.h:147:28
    frame #24: 0x00007ffff14d09d4 libEditorLib.so`AZ::EBusQueuePolicy<true, AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZStd::recursive_mutex>::Execute() [inlined] AZStd::function_intermediate<void>::operator()(this=<unavailable>) const at function_template.h:604:16
    frame #25: 0x00007ffff14d0998 libEditorLib.so`AZ::EBusQueuePolicy<true, AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZStd::recursive_mutex>::Execute() [inlined] AZStd::function<void ()>::operator()(this=<unavailable>) const at function_template.h:684:31
    frame #26: 0x00007ffff14d0998 libEditorLib.so`AZ::EBusQueuePolicy<true, AZ::EBus<AZ::TickEvents, AZ::TickEvents>, AZStd::recursive_mutex>::Execute(this=<unavailable>) at Policies.h:266:17
    frame #27: 0x00007ffff1961e4c libEditorLib.so`CCryEditApp::InitInstance() at BusImpl.h:366:38
    frame #28: 0x00007ffff1961e31 libEditorLib.so`CCryEditApp::InitInstance(this=0x0000555557225700) at CryEdit.cpp:1715:5
    frame #29: 0x00007ffff1967ed8 libEditorLib.so`CryEditMain(argc=<unavailable>, argv=<unavailable>) at CryEdit.cpp:4018:57
    frame #30: 0x0000555555698d60 Editor`main [inlined] decltype(InvokeTraits::forward<int (*&)(int, char**)>(fp)(InvokeTraits::forward<int&>(fp0), InvokeTraits::forward<char**&>(fp0))) AZStd::Internal::INVOKE<int (*&)(int, char**), int&, char**&>(f=<unavailable>, args=<unavailable>, args=<unavailable>) at invoke_traits.h:208:20
    frame #31: 0x0000555555698d59 Editor`main [inlined] AZStd::invoke_result<int (*&)(int, char**), int&, char**&>::type AZStd::invoke<int (*&)(int, char**), int&, char**&>(f=<unavailable>, args=<unavailable>, args=<unavailable>) at invoke.h:54:16
    frame #32: 0x0000555555698d59 Editor`main(argc=1, argv=0x00007fffffffe058) at main.cpp:31:15
    frame #33: 0x00007ffff6a49b4a libc.so.6`__libc_start_call_main + 122
    frame #34: 0x00007ffff6a49c0b libc.so.6`__libc_start_main@@GLIBC_2.34 + 139
    frame #35: 0x0000555555698bb5 Editor`_start + 37
`

**Comment by xeechou** [comment]
hello @nicholas-rh , how did you get the stack trace? I compiled with debug build, but I am getting a lot of unknown frames.

**Comment by TheShed412** [comment]
Running in to this issue as well. I am using a build from the current development branch on commit cd07167884f06e7813a2a5f7175c45360a56cef8

I have a fresh build using profile and I was starting from the command line in the project folder.

I saw this on Ubuntu 20.04 and Linux Mint 20.3

This is the last blob of the output before the segfault:

```
AssetProcessorConnection: Network connection attempt failure, Connect returned error AzSockError::eASE_ECONNREFUSED
AssetProcessorConnection: ==================================================================
AssetSystem: Ping time to asset processor: 0.07 milliseconds
Editor: Connected to Asset Processor
AssetSystem: Ping time to asset processor: 0.66 milliseconds
Editor: CriticalAssetsCompiled
AssetCatalog: Initializing asset catalog with root "/home/shed/O3DE/Projects/Test/Cache/linux"AssetCatalog: Loaded registry containing 5179 assets.
Module: Attempting to load module:/home/shed/O3DE/Projects/Test/build/linux/bin/profile/libCrySystem.so
Module: Success!
[1]    39145 segmentation fault (core dumped)  ./build/linux/bin/profile/Editor

```
I saw Vulkan mentioned above, my machine seems
