### ISSUE TITLE
Feature Request add "Feature Request" label

### ISSUE THREAD

**Issue by drakeredwind01** [o3de/o3de#15876]
**Is your feature request related to a problem? Please describe.**
hard to find labels

**Describe the solution you'd like**
what to add a "Feature Request" label for quick triage

**Describe alternatives you've considered**
having a big collection of labels together that you can search through easily. I know that there is a way to search through labels but it isn't very easy use. I feel like even a list of labels would be easier to ctrl+f through then using the GitHub search function.
@jayrulez commented in the 2023.05.04 SIG-networkingthere is already a label called "feature-need" but a "Feature Request" isn't as necessary as a need. would be nice to have something to throw in to quickly triage out of the way.

**Additional context**
NA

**Comment by lmbr-pip** [comment]
We have [kind/feature](https://github.com/o3de/o3de/labels/kind%2Ffeature) to demonstrate an item is a feature request.

You can also find a list of labels on any GitHub repro via: https://github.com/o3de/o3de/labels

**Comment by drakeredwind01** [comment]
thanks for the advice!

**Comment by lgleim** [comment]
Closing based on the OP's feedback
