### ISSUE TITLE
Breaking Package Manager depsite following instructions

### ISSUE THREAD

**Issue by Gant696t04** [o3de/o3de#15878]
I attempted to install o3de but I ran into a major problem. Not only did it not install and actually hang on installation but it also broke the package manager. The apt package manager cannot install or remove anything anymore. I am on Linux Mint by the way.
Here is a test of installing Kate but I run into this 

![image](https://user-images.githubusercontent.com/101918732/236317312-b259cff4-49a2-47e3-832a-c6a7d58a14ea.png)

I will be going off to fix apt but I need to know why. What is causing this? Fix this now!

**Comment by Gant696t04** [comment]
I fixed apt but something is causing this to not install. Get it done.

**Comment by AMZN-alexpete** [comment]
I don't think this involves the project manager, but rather that `apt package manager`

**Comment by AMZN-alexpete** [comment]
@Gant696t04 Did you use the .deb package and if so was this issue due to one of the known issues posted in the docs when using the .deb package? https://www.o3de.org/docs/welcome-guide/setup/installing-linux/

**Comment by Gant696t04** [comment]
> I don't think this involves the project manager, but rather that `apt package manager`

What do you think I said?

**Comment by Gant696t04** [comment]
> @Gant696t04 Did you use the .deb package and if so was this issue due to one of the known issues posted in the docs when using the .deb package? https://www.o3de.org/docs/welcome-guide/setup/installing-linux/ There are a couple known apt bugs that have fixes.
> 
> https://bugs.launchpad.net/ubuntu/+source/synaptic/+bug/1522675 https://salsa.debian.org/apt-team/apt/-/merge_requests/177

Yes. I assume you did not at all read the issue fully. Fixing apt only took a few seconds. I will look into the fixes.

**Comment by AMZN-alexpete** [comment]
> I don't think this involves the project manager, but rather that `apt package manager`
@Gant696t04 I was explaining why I removed the `feature/projectmanager` label

**Comment by Gant696t04** [comment]
> > I don't think this involves the project manager, but rather that `apt package manager`
> 
> @Gant696t04 I was explaining why I removed the `feature/project-manager` label.

I know it's been a year but first off, I would like to apologize for being so rude last time. I was very irritated but it still wasn't appropriate.
Next, this issue was adressed and all is functioning here. You were right, thanks.
