### ISSUE TITLE
PopcornFX 2.16.2 gem does not activate after adding

### ISSUE THREAD

**Issue by petrocket** [o3de/o3de#15893]
**Describe the bug**
After adding PopcornFX 2.16.2 Gem in O3DE SDK 23.05.0 Project Manager and rebuilding, the PopcornFX components are not visible in the Editor

It's possible this is related to how the gem appears in `project.json` where it includes the version `PopcornFX==2.16.2` but maybe there is a bug that prevents the dll from being added to the setreg list of dlls to load when the "==2.1.6.2" version specifier is present.

**Assets required**
PopcornFX Gem

**Steps to reproduce**
1. Install O3DE SDK 23.05.0
2. Add the PopcornFX 2.16.2 gem to a project 
3. Build the project
4. Open the Editor

**Expected behavior**
PopcornFX components are visible in the editor

**Actual behavior**
No PopcornFX components are visible

**Found in Branch**
main

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[8c1421e](https://github.com/o3de/o3de/commit/8c1421e2a0d168d34ae9ca6c763270fe8395a809)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Comment by OBWANDO** [comment]
when adding, it puts the version number in the json list "PopcornFX=2.16.2" which doesn't work.
IF you rename to "PopcornFX" and then add or remove a gem in the project manager, it will compile.
If you just rename, save and compile, it doesn't pick it up.

**Comment by lmbr-pip** [comment]
Unsure if this is build or editor issue, so tagging both SIG/build and SIG/content
