### ISSUE TITLE
Splash screen shows in Material Editor

### ISSUE THREAD

**Issue by petrocket** [o3de/o3de#15897]
**Describe the bug**
If a splash screen is enabled, it appears in the viewport when the Material Editor opens.  Kinda cool, but probably a bug.

**Assets required**
a splash screen enabled

**Steps to reproduce**
1. Activate the o3de-multiplayersample game and launch the material editor

**Expected behavior**
No splash screen in tools

**Actual behavior**
splash screen shows in material editor viewport

**Found in Branch**
main

**Comment by gadams3** [comment]
@petrocket @lmbr-pip Does this also happen in the main editor? How is the splash screen implemented? I see it appearing in material editor and material canvas on startup. The atom tools initialize the same gems, system components, pipelines, and passes as the game project. The splash screen logic will need to be updated to only run in the launcher.

**Comment by AMZN-alexpete** [comment]
It doesn't happen in the main editor, but possibly that's just because there is no viewport initially until you open a level
