### ISSUE TITLE
DPE Inspector: Terrain World Renderer component is missing the toggle for "Clipmap Enabled" when using the DPE

### ISSUE THREAD

**Issue by jckand** [o3de/o3de#15900]
**Describe the bug**
Terrain World Renderer component is missing the toggle for "Clipmap Enabled" when using the DPE

**Steps to reproduce**
1. Launch the Editor with the DPE enabled:
```
Editor.exe --ed_enableDPE=true
```
2. Create a new level.
3. Add a Terrain World and Terrain World Renderer component to the Level entity.
4. Attempt to toggle on "Clipmap Enabled" in the Terrain World Renderer component.

**Expected behavior**
Toggle is present and functional.

**Actual behavior**
No toggle is available next to the "Clipmap Enabled" property.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82226555/236871779-3f9880f5-13b9-4ce9-a3ae-95dee11aed64.png)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
42a9733b187a5c72616e450a506e91a08d18829b

**NOTES**
1. The affected property is also duplicated under its own property hierarchy.

**Comment by cgalvan** [comment]
Duplicated by #16071
