### ISSUE TITLE
Linux snap package O3DE installer: Projects fail to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#15907]
**Describe the bug**
Building a project fails via Project Manager from snap package O3DE installation due to the following errors:
```
[1/13] Linking CXX static library lib/profile/libTest1.Private.Object.a
FAILED: lib/profile/libTest1.Private.Object.a 
: && /snap/o3de/x1/usr/bin/cmake -E rm -f lib/profile/libTest1.Private.Object.a && /usr/bin/llvm-ar-14 qc lib/profile/libTest1.Private.Object.a  External/Gem-3fa137cd/CMakeFiles/Test1.Private.Object.dir/profile/Unity/unity_0_cxx.cxx.o && /usr/bin/llvm-ranlib-14 lib/profile/libTest1.Private.Object.a && cd /home/gpc-589/O3DE/Projects/Test1/build/linux/External/Gem-3fa137cd && /snap/o3de/x1/usr/bin/cmake -P /snap/o3de/x1/2.0.0/cmake/Platform/Linux/ProcessDebugSymbols.cmake /snap/o3de/x1/usr/bin/strip /snap/o3de/x1/usr/bin/objcopy /home/gpc-589/O3DE/Projects/Test1/build/linux/lib/profile/libTest1.Private.Object.a dbg STATIC_LIBRARY DETACH
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/o3de/x1/usr/lib/x86_64-linux-gnu/libLLVM-14.so.1)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/o3de/x1/usr/lib/x86_64-linux-gnu/libLLVM-14.so.1)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /snap/o3de/x1/usr/lib/x86_64-linux-gnu/libLLVM-14.so.1)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /snap/o3de/x1/usr/lib/x86_64-linux-gnu/libLLVM-14.so.1)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/core22/current/lib/x86_64-linux-gnu/libedit.so.2)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/core22/current/lib/x86_64-linux-gnu/libtinfo.so.6)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/o3de/x1/usr/lib/x86_64-linux-gnu/libxml2.so.2)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/o3de/x1/usr/lib/x86_64-linux-gnu/libxml2.so.2)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/core22/current/lib/x86_64-linux-gnu/libbsd.so.0)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/o3de/x1/usr/lib/x86_64-linux-gnu/libicuuc.so.70)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/o3de/x1/usr/lib/x86_64-linux-gnu/libicuuc.so.70)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /snap/core22/current/lib/x86_64-linux-gnu/liblzma.so.5)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/core22/current/lib/x86_64-linux-gnu/liblzma.so.5)
/usr/bin/llvm-ar-14: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/core22/current/lib/x86_64-linux-gnu/libmd.so.0)
ninja: build stopped: subcommand failed.
```
Note that all of the [Linux system requirements](https://www.o3de.org/docs/welcome-guide/requirements/#linux) were met. We were unable to update the `GLIBC` nor the `ldd` to any higher version. The issue does not occur on Ubuntu 22.04. The same issue occurs while using and not using `sudo` during installation and launching the O3DE. Please note that the View Logs button is not functional in O3DE snap package and those have to be accessed manually.

Please refer to the attached video and logs for more information.

**Steps to reproduce**
1. Download the O3DE snap package from https://o3debinaries.org/2.0.0/Linux/o3de_2.0.0_amd64.snap.
2. Follow instructions listed in https://www.o3de.org/docs/welcome-guide/setup/installing-linux/#installing-o3de-from-a-snap-package.
3. Launch Project Manager as mentioned in the instruction in step 2.
4. Create a project.
5. Build the created project.

**Expected behavior**
Building the project completes without issues.

**Actual behavior**
Building the project fails.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/11dada7d-b401-4511-acd4-2ce238ed21d7

**Found in Branch**
https://o3debinaries.org/2.0.0/Linux/o3de_2.0.0_amd64.snap (downloaded 5/9/2023 at 11:20 AM GMT+2)

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.6 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/11430360/CMakeProjectBuildError.log)

**Comment by byrcolin** [comment]
This is the same issue as https://github.com/o3de/o3de/issues/15939 and I think we should come to the same conclusion that we should not support older releases of Ubuntu, there are too many issues beyond our control.
