### ISSUE TITLE
DPE Inspector: Component properties are frequently in a different order than represented in the RPE

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#15911]
**Describe the bug**
Component properties are frequently in a different order than represented in the RPE.

**Steps to reproduce**
1. Launch the Editor with the DPE enabled:
```
Editor.exe --ed_enableDPE=true
```
2. Open a new or existing level.
3. Create a new entity.
4. Add a Dither Gradient Modifier component to the entity. (Only serves as an example. Many components have properties listed in a different order in the DPE)
5. Observe the component properties.
6. Toggle ed_enableDPE to false in the Console.
7. Observe the component properties.

**Expected behavior**
Some components such as the Dither Gradient Modifier, have component properties listed in a certain order to simplify workflows. This order should be preserved in the DPE.

**Actual behavior**
Component properties are in a different order on many components.

**Screenshots/Video**
![image](https://github.com/o3de/o3de/assets/82226555/c917100b-2189-437a-97c0-1de685d5066c)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
42a9733b187a5c72616e450a506e91a08d18829b

**Comment by cgalvan** [comment]
Looks like we will need a similar fix for `UIElement` ordering in the DPE:

https://github.com/o3de/o3de/pull/9569

**Comment by cgalvan** [comment]
Duplicated by #16069
