### ISSUE TITLE
DPE Inspector: Camera component's "Target texture" property field is missing

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#15910]
**Describe the bug**
Camera component's "Target texture" property field is missing.

**Steps to reproduce**
1. Launch the Editor with the DPE enabled:
```
Editor.exe --ed_enableDPE=true
```
2. Open a new or existing level.
3. Add a new entity.
4. Add a Camera component to the entity.
5. Set the "Target texture" property.

**Expected behavior**
Target texture field is available with an asset picker button.

**Actual behavior**
Target texture property field is completely missing.

**Screenshots/Video**
![image](https://github.com/o3de/o3de/assets/82226555/aaa5632c-273f-4579-8946-863dd2667802)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
42a9733b187a5c72616e450a506e91a08d18829b

**Comment by cgalvan** [comment]
The target texture asset field now is now usable after https://github.com/o3de/o3de/issues/15743
