### ISSUE TITLE
Materials generated from Material Canvas graph can create ghosts in the previous Position Offsets

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#15920]
**Describe the bug**
Material generated from a Material Canvas graph can create ghosts whenever material's *Position Offset* is changed in the graph. 
For example if a material is first properly generated with a [1; 1; 1] *Position Offset*, then changed to [0.1; 0.1; 0.1], the mesh it is applied will properly display at the changed offset, but there will be a grey copy of that mesh in the previous *Position Offset* ([1; 1; 1] in this case.)

It should be noted that this ghost effect only occurs in the Editor's Viewport, while in the Material Canvas' Viewport it is displayed properly.

It should also be noted that reproduction of this issue can be inconsistent (for example on the attached video, it can be seen that the *Position Offset* had to be changed twice for this to occur) - about 3/4 reproduction rate was encountered.

This issue occurs on both Windows and Linux.

**Assets required**
* Material Canvas graph shown on the screenshot created and processed: 
![MaterialCanvasGraph](https://github.com/o3de/o3de/assets/86952082/98f78999-315d-4048-a536-02a7a27c4a81)

**Steps to reproduce**
1. Create a new level.
2. Select the *Atom Default Environment* > *Shader Ball* entity and add a *Material* component to it.
3. Assign the material generated from Material Canvas graph mentioned in the **Assets required** to the *Material* component's *Default Material* property.
4. Go to *Tools* > *Material Canvas (Preview)*.
5. In the *Material Canvas (Preview)* open the Material Canvas graph mentioned in the **Assets required**.
6. Change the *Value* in the *Float Constant* node from 1 to 0.1.
7. Save the graph (*File* > *Save* or Ctrl + S).
8. Wait for the graph to be processed (there should be (Completed) visible in the bottom bar).
9. Look at the Shader Ball in the Editor's Viewport (if issue did not occur repeat steps 6 - 9 with different *Float Constant* values).

**Expected behavior**
Shader Ball in the Editor's Viewport looks like the Shader Ball in the Material Canvas' Viewport.

**Actual behavior**
A grey ghost appears in the previous Shader Ball position, along with the properly rendered one.

**Video**

https://github.com/o3de/o3de/assets/86952082/720d4803-a588-4cba-b842-2f68a21709f8

**Found in Branch**
Development (c5a910b)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c5a910b3eabb2e9f546adb00c56c6dad2b594a40

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by moudgils** [comment]
@gadams3 - Mesh motion vector needs to be updated.

**Comment by gadams3** [comment]
The following pr and subsequent changes converted the material graph templates to generate materials using the material pipeline and its shaders. As part of that, custom depth and motion vector shaders were implemented for the material graph templates. As long as the material updates after changes are saved there should be no ghosting. It is possible for it to happen temporarily if the depth and forward shaders do not reload at the same time. But the issue will resolve itself once the material Is reloaded. https://github.com/o3de/o3de/pull/16838
