### ISSUE TITLE
Debian installation package reporting invalid dependencies

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#15923]
**Describe the bug**
When running the install from the latest development installer, the debian package reports the following packages are missing
```
Unpacking o3de (2.1.0) ...
dpkg: dependency problems prevent configuration of o3de:
 o3de depends on libffi7; however:
  Package libffi7 is not installed.
 o3de depends on clang-12; however:
  Package clang-12 is not installed.
 o3de depends on mesa-common-dev; however:
  Package mesa-common-dev is not installed.
```

* **libffi7** is not required (anymore), this was an old python 3.7.x dependency that has long since been resolved
* ***libzstd-dev*** is now required
* ***clang-12*** is version specific, and may force a downgrade of versions (ie clang-14 is default on Ubuntu 22.04 when installing clang).

**Steps to reproduce**
1. On Linux 20.04 (or 22.04) Download the latest development installer from https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb
2. In the terminal, go to the location of the pacakge (e.g. ~/Downloads) and run
    ```
    sudo dpkg -i O3DE_latest.deb
    ```
3. See the results

**Expected behavior**
* The installation completes informing of any missing dependency other than the ones listed above

**Actual behavior**
***see above***

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
f85c397c50e9e61428e45eba173bd59464ecb1fa

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version : Ubuntu 22.04
 - CPU: Intel I9
 - GPU GeForce RTX 2080 Mobile
 - Memory : 16GB

**Comment by amzn-changml** [comment]
Accepting this on behalf of @o3de/sig-build. Taking a look.

**Comment by chinepun** [comment]
I encountered a similar issue yesterday and it turns out it's better to use `sudo apt install <path_to_deb_package>/<debian_package_name>.deb` as the [documentation](https://docs.o3de.org/docs/welcome-guide/setup/installing-linux/) suggests. Using `sudo dpkg -i <path_to_deb_package>/<debian_package_name>.deb` seems to have dependency issues

**Comment by amzn-changml** [comment]
Yes, the docs instructions were updated and supersede these steps. We've also solved some of the dependency issues with https://github.com/o3de/o3de/pull/16372
