### ISSUE TITLE
[Linux] Editor crashes upon opening ImGui for a project with all gems enabled

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#15959]
**Describe the bug**
Opening ImGui (~) leads to a silent crash of the Editor for projects with all gems enabled. The issue does not occur for a project using the Default template. Please note that no logs are generated during this crash.

The issue does not reproduce on Windows.
Please refer to the attached video for more information.

**Steps to reproduce**
1. Create a project with all gems enabled.
2. Build the project.
3. Process the assets.
4. Launch the Editor.
5. Press tilde (~) to open the ImGui.

**Expected behavior**
ImGui opens for all projects.

**Actual behavior**
ImGui does not open for projects with all gems enabled.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/693ee71b-d0ff-4cea-9982-381850ea4c80

**Found in Branch**
Development
Installer build (https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb) downloaded on 5/15/2023 at 8:30 AM GMT+2

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[018f149](https://github.com/o3de/o3de/commit/018f14991c4d849a74c8a6cccf1a7cefecb4960a) 

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.6 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/11477982/Editor.log)

**Comment by nicholas-rh** [comment]
Plan on investigating this next

**Comment by nicholas-rh** [comment]
Reproduced on my machine running Fedora 38

**Comment by nicholas-rh** [comment]
It looks like the problem gem is "Script Canvas Developer," and when disabling it ImGui works as normal

**Comment by lgleim** [comment]
@o3de/sig-content Since you own Script Canvas Developer, could you look into this issue?

**Comment by nick-l-o3de** [comment]
This is likely an issue I repro'd to do with the SCD gem and its assert on startup.  (Discussed in discord).  I'll add a fix.

**Comment by nick-l-o3de** [comment]
Note that from the logs, its unclear if its the same bug, but for me, there'd be an assert, and potentially memory corruption with ScriptCanvasDeveloper gem enabled.  

The short version of it is that there is a size mismatch in the size of the Script Canvas Developer Component on creation time (which happens in the gem module dll) and from the functions it actually runs (which comes from the static lib, I think?).  Basically, the gem does not define IMGUI_ENABLED but the static lib does.  This means that functions taken from the static lib will call into places after the end of the class.

**Comment by byrcolin** [comment]
Has not been reported in a while, potentially fixed.
