### ISSUE TITLE
[Linux] User is unable to leave the Game Mode upon entering it

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#15958]
**Describe the bug**
After entering the Game Mode there is no way of leaving it which makes closing the Editor using standard methods also impossible. "Esc" button does not work. We were only able to terminate the Editor by killing the Terminal it has been run from.

The issue does not reproduce on Windows.
Please refer to the attached video for more information.

**Steps to reproduce**
1. Launch the Editor.
2. Create a level or open an already existing one.
3. Enter the Game Mode (Ctrl+G).
4. Try to leave the Game Mode.

**Expected behavior**
User is able to leave the Game Mode by pressing the "Esc" button.

**Actual behavior**
User is unable to leave the Game Mode by any means and restart of the Editor is required.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/5f2ed01b-a195-41f1-85cc-de1baed70dd2

**Found in Branch**
Development
Installer build (https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb) downloaded on 5/15/2023 at 8:30 AM GMT+2

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[018f149](https://github.com/o3de/o3de/commit/018f14991c4d849a74c8a6cccf1a7cefecb4960a) 

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.3 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/11477860/Editor.log)

**Comment by nicholas-rh** [comment]
Reproduced on my machine using Fedora 38

**Comment by nicholas-rh** [comment]
@LB-KacperKapusta Is this a recent issue that popped up or something that has been a problem for a while? I've been looking through the Qt code to try and figure out what's causing it to happen, but haven't found anything yet. My current guess is that some widget is stealing the focus when entering game mode but I haven't tracked it down/confirmed this yet, and also it wouldn't explain why it happens on Linux but not Windows.

**Comment by LB-KacperKapusta** [comment]
@nicholas-rh This rather seems like a recent issue that popped up. Previously it did not happen and entering/exiting Game Mode is often times verified.

**Comment by nicholas-rh** [comment]
Found a working commit & will run a git bisect to track down the cause.

**Comment by nicholas-rh** [comment]
Sorry about the delay, it looks like this is the problem commit https://github.com/o3de/o3de/commit/89fe77d780d984c4d84a069dce164379c729eb34. I suspect one solution would be to move the removed XConsole ESC key handler [here](https://github.com/o3de/o3de/commit/89fe77d780d984c4d84a069dce164379c729eb34#diff-ae2cee1ed3809d5d332862061afadbe6201d0f3d92e34d6dd14cc30c1638ddf1L1096) to ImGui somewhere around [here](https://github.com/o3de/o3de/commit/89fe77d780d984c4d84a069dce164379c729eb34#diff-2b9f05844aecafd8d7677fb4178a42fc0e2aa0d35f503850cc4f77f7927ca7dcL440) although there may be a better approach. I'll test it and open a PR for more discussion if it works out

**Comment by michalpelka** [comment]
I've experienced the same issue on ubuntu 22.04.

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development (https://github.com/o3de/o3de/commit/050371c2a634310c144d160c8dc308c4d5300f62).
