### ISSUE TITLE
Discrepancies between Linux and Windows versions of the Development Installer

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#15968]
**Describe the bug**
After downloading the Linux Development Installer (https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb) it has been observed that it installs in `O3DE/2.1.0` directory and `2.1.0` is the version displayed in the Project Manager as well. Windows Development Installer (https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe) however, installs in 'O3DE/2.0.0' directory and `2.0.0` is the version displayed in the Project Manager.

Please note that the Linux Development Installer is more up to date than the Windows one.

**Steps to reproduce**
1. Download and install O3DE on Linux (https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb).
2. Create a project.
3. Download and install O3DE on Windows (https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe).
4. Create a project.

**Expected behavior**
Development Installer versions match for both platforms.

**Actual behavior**
Development Installer versions do not match for Linux (2.1.0) and Windows (2.0.0).

**Screenshots/Video**
Linux:
![LinuxInstaller](https://github.com/o3de/o3de/assets/86953659/b8d5f1eb-879d-41be-87a7-2f2d90acbdc6)
![LinuxPM](https://github.com/o3de/o3de/assets/86953659/385af01c-dbb6-403c-8380-68ae773156e5)
Windows:
![WindowsInstaller](https://github.com/o3de/o3de/assets/86953659/1287d231-a07b-4200-882e-1ce277d14bc7)
![WindowsPM](https://github.com/o3de/o3de/assets/86953659/e89f9666-9477-4996-8ce7-1841589202b4)

**Found in Branch**
Development Installer 
(https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb), (https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe)

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.6 LTS
- CPU: CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Comment by AMZN-alexpete** [comment]
This appears to be because the windows installer job was failing.  It should now be fixed and the latest Linux and Windows versions should be available tonight.

**Comment by LB-MateuszSzweda** [comment]
Unfortunately verifying the fix is currently blocked by https://github.com/o3de/o3de/issues/15979 making Microsoft Defender SmartScreen warning popup when Windows Development Installer is launched, so we can not run it due to security reasons.

But as soon as the Windows Defender issue is resolved the verification will commence.

**Comment by AMZN-alexpete** [comment]
@LB-MateuszSzweda thanks for checking back in, #15979 should now be resolved, unblocking you from verifying this issue is also fixed. Thanks!

**Comment by LB-KacperKapusta** [comment]
Closing the issue. It has been verified using the latest installers that both Linux and Windows now use the same `2.1.0` version.
