### ISSUE TITLE
Launching Nightly Development Build Installer obtained from official o3de download site causes Microsoft Defender SmartScreen warning

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#15979]
**Describe the bug**
Downloading and launching Nightly Development Build obtained via [Nightly Development Build here](https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe) hyperlink located on https://o3debinaries.org/download/windows.html site will cause Microsoft Defender SmartScreen warning popup.

This can be related to https://github.com/o3de/o3de/issues/14256.

Please note that this issue does not occur if installer link is obtained from different and older source than https://o3debinaries.org/download/windows.html site such as hyperlink from https://github.com/o3de/o3de/issues/15968.

**Steps to reproduce**

1. Go to https://o3debinaries.org/download/windows.html site.
2. Download the o3de_installer.exe by clicking the hyperlink at the bottom of the screen "Try out features and fixes currently in development by downloading the [Nightly Development Build here](https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe)".
3. Launch the o3de_installer.exe.

**Expected behavior**
o3de installer launches without triggering Microsoft Defender SmartScreen popup.

**Actual behavior**
Launching o3de installer obtained from https://o3debinaries.org/download/windows.html site triggers Microsoft Defender SmartScreen popup.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953456/902cc124-17d1-48fb-974c-08757fe864cf

**Found in Branch**
Development

**Commit ID from** [o3de/o3de](https://github.com/o3de/o3de) **Repository**
455192c

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 9 3900X
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by lmbr-pip** [comment]
I believe Installers are owned by SIG/Build so tagging them in.

**Comment by AMZN-alexpete** [comment]
The signing process had a credential issue that has been resolved.  The nightly installer test is now passing including the signing verification step which was failing.

**Comment by LB-MateuszSzweda** [comment]
Issue verified as fixed on 5/22 . Installer downloaded with [Nightly Development Build here](https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe) hyperlink no longer causes Microsoft Defender SmartScreen warning upon launch.
