### ISSUE TITLE
Linux: GPU crash upon loading level using Intel integrated graphics

### ISSUE THREAD

**Issue by nicholas-rh** [o3de/o3de#15999]
**Describe the bug**
When attempting to run the Editor program and open a level while running on Fedora 38 after building the engine & project from source, the Editor will lock up and stop responding. From my limited testing, the problem happens when using Intel integrated graphics using the Mesa libraries & i915 kernel module, although when using Mesa and a discrete GPU (AMD RX480 with the amdgpu driver) on a different PC I did not encounter the problem and could load the level successfully.

**Steps to reproduce**
1.) Install Fedora (or potentially another Linux distro?)
2.) Ensure that integrated graphics are being used
3.) Download the development branch, build the engine & a project
4.) Open the Editor and launch the project
5.) Create a level or open an existing one
6.) The GPU will crash and the editor will freeze up

**Expected behavior**
The level loads successfully.

**Actual behavior**
The editor stops responding.

**Screenshot**
![image](https://github.com/o3de/o3de/assets/133678776/8430c911-a706-46ce-b880-47da5c3f2ef5)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/ad084e683febb5395d6de2893816b22b66953d87

**Desktop/Device (please complete the following information):**
 - Device: Dell Inc. Precision 5560 Laptop
 - OS: Fedora
 - Version: 38 Workstation
 - CPU: Intel i7-11850H
 - GPU: Intel(R) UHD Graphics (TGL GT1) (integrated graphics, no discrete GPU)
 - Memory: 64GB

**Additional context**

Kernel logs after crash: 
```
May 17 09:07:34 fedora gnome-shell[2943]: Window 0x2e00042 cannot be minimized, but something tried anyways. Not having it!
May 17 09:07:42 fedora kernel: i915 0000:00:02.0: [drm] Resetting rcs0 for preemption time out
May 17 09:07:42 fedora kernel: i915 0000:00:02.0: [drm] Editor[11620] context reset due to GPU hang
May 17 09:07:43 fedora kernel: i915 0000:00:02.0: [drm] GPU HANG: ecode 12:1:85dffffb, in Editor [11620]
```

vulkaninfo command output: [vulkaninfo.txt](https://github.com/o3de/o3de/files/11519245/vulkaninfo.txt)

Typical console log after a crash with the following debug flags passed in: [Editor.log](https://github.com/o3de/o3de/files/11521419/Editor.log)
```
    -rhi-device-validation="enable"
    -rhi-device-validation="verbose"
    -rhi-device-validation="gpu"
```

CPU stack trace with the AZ_FORCE_CPU_GPU_INSYNC macro enabled (unfortunately no useful Vulkan data on frame 10): [bt3.txt](https://github.com/o3de/o3de/files/11521422/bt3.txt)

**Related issues?**
https://github.com/o3de/o3de/issues/15947
https://github.com/o3de/o3de/issues/15947
https://github.com/o3de/o3de/issues/11849

**Comment by nicholas-rh** [comment]
Also tested and it seems to crash using either X11 or Wayland so display server does not seem to make a difference

**Comment by moudgils** [comment]
Hey @akioCL. When you have time please take a look at this issue and analyze if it is something deeper or trivial.

**Comment by nicholas-rh** [comment]
Also forgot to mention, but this PR did not seem to fix the issue https://github.com/o3de/o3de/pull/15832/

**Comment by 12345XuXin54321** [comment]
There is a same crash in my PC.

**Found in Branch**

development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**

[0eaa719](https://github.com/o3de/o3de/tree/0eaa71988c9d69d053cecbb2a0118547c7cbf2d7)

**Desktop/Device (please complete the following information):**
 - Device: Dell Inc. Latitude 5531
 - OS: Gentoo Linux
 - Kernel Version: Linux 6.1.31-gentoo
 - CPU: Intel i7-12800H
 - GPU: Intel Graphics (ADL GT2)
 - Memory: 24GB


**Additional context**

Kernel logs after crash:
```
7月 25 09:00:24 gentoo-latitude kernel: Asynchronous wait on fence 0000:00:02.0:gnome-shell[2112]:546e timed out (hint:intel_atomic_commit_ready [i915])
7月 25 09:00:29 gentoo-latitude kernel: i915 0000:00:02.0: [drm] GPU HANG: ecode 12:1:85dffffb, in Editor [6490]
7月 25 09:00:29 gentoo-latitude kernel: i915 0000:00:02.0: [drm] Resetting chip for stopped heartbeat on rcs0
7月 25 09:00:29 gentoo-latitude kernel: i915 0000:00:02.0: [drm] Editor[6490] context reset due to GPU hang
```
