### ISSUE TITLE
Linux: Material generated from the Material Canvas does not update consistently when changes are introduced and saved

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16034]
**Describe the bug**
If a saved Material Canvas graph is modified, it does not get updated consistently between the Material Canvas Viewport and the Editor Viewport. Sometimes the change in the graph is not recognized at all and after processing, the material remains the same as before, or the material is updated in the Material Canvas Viewport and not in the Editor. Only occasionally the material is updated properly between both Viewports.

Switching the level fixes this issue.

This issue does not occur with the materials made in the Material Editor (materials get updated instantly in both the Material Editor and O3DE Editor).

This issue does not occur on Windows.

**Steps to reproduce**
1. Go to *Tools* > *Material Canvas (Preview)*.
2. In the *Material Canvas* go to *File* > *New* > *New Material Graph Document...*.
3. Create a material graph that will be clearly visible in the Viewport (for example a node chain used in the attached video: *Time* -> *Cosine* -> *Standard PBR (Base Color input)*).
4. Save the material graph in the directory accessible to the Editor and wait for it to process.
5. In the Editor select the Shader Ball entity and add the *Material* component to it.
6. Assign the material generated from the graph saved in step 4 to the *Default Material* property of the *Material* component.
7. Compare the material between the Editor and Material Canvas (should be the same).
8. Modify the material graph saved in step 4 so that a change is visible (in the provided example, *Cosine* node can be simply disconnected from the *Standard PBR*) and save it.
9. View the material in the O3DE Editor's Viewport.

**Expected behavior**
After the material is processed, it looks the same in the Material Canvas Viewport as in the Editor Viewport.

**Actual behavior**
Materials are inconsistent with how they are viewed between Viewports.

**Video**

https://github.com/o3de/o3de/assets/86952082/d51337c9-47e4-441a-a4ef-e687182d237b

**Found in Branch**
Development (649d7e6)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
649d7e6bdda3ad26f479319d2ad8408d6ee6186b

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.2 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by moudgils** [comment]
@gadams3 This seems like a material reload issue.

**Comment by gadams3** [comment]
This should be much improved after the following PR. https://github.com/o3de/o3de/pull/16871
Most edits and changes and should update and reflect automatically in material canvas and the main editor as they are made. However, there are several assets that get generated by material canvas and the material pipeline including material types, shaders, and other files. These files are generated and processed asynchronously by the AP. In normal conditions, they should process in the correct order and produce the final material and material type assets to be displayed in both tools.  It is possible for rapid changes to cause the assets to get out of sync or display a version that is one behind. Making additional changes will cause the assets to reprocess and update in the tools. There is an option in the settings dialog to force the asset processor to reset material and material type fingerprints when processing,, which will force everything to be regenerated and reprocessed in order every time something changes. Enabling that setting can help but it will take longer to generate previewable assets. It is also helpful to disable unused RHI, render pipelines, and material pipelines so there are less assets that need to be generated and processed.
