### ISSUE TITLE
DPE Inspector: Some cases of visibility as functions not being invoked

### ISSUE THREAD

**Issue by cgalvan** [o3de/o3de#16061]
**Describe the bug**
There was a fix recently that corrected most cases of attributes being specified as invokable functions instead of directly by value, but it appears there are some remaining cases specific to the Visibility attribute that this fix didn't apply to.

This issue has been found in the following components:
Light, Material, Mesh,
Look Modification - Showing Overrides + min/max exposure fields that shouldn't be visible

**Steps to reproduce**

1. Launch the Editor with the DPE enabled:
`Editor.exe --ed_enableDPE=true`
2. Open a new or existing level.
3. Create a new entity.
4. Add a `Look Modification` component to the entity.

**Expected behavior**
Showing Overrides + min/max exposure fields shouldn't be visible.

**Actual behavior**
Showing Overrides + min/max exposure fields are visible.

**Comment by cgalvan** [comment]
This is actually the same root cause as #16079

**Comment by LB-KacperBieniek** [comment]
It was observed on the latest Stabilization/2310 ([bc8eb66](https://github.com/o3de/o3de/commit/bc8eb66f885cfa99a444703792482f169692ffdc)) that the Overrides filed is still visible when DPE is enabled. Should this issue be reopened, or should we log a new one?
![overrides](https://github.com/o3de/o3de/assets/87059746/2c767a54-9fdf-4eee-b0ac-9e9929c77fbb)
