### ISSUE TITLE
DPE Inspector: Some enum fields show value name instead of display name

### ISSUE THREAD

**Issue by cgalvan** [o3de/o3de#16076]
**Describe the bug**
Some enum fields show the actual name of the enum variable in the combo-box instead of the appropriate display name.

This issue has been found in the following components:
Image Gradient, Directional Light, PhysX Dynamic Rigid Body, Terrain Macro Material

**Steps to reproduce**

1. Launch the Editor with the DPE enabled:
`Editor.exe --ed_enableDPE=true`
2. Open a new or existing level.
3. Create a new entity.
4. Add a `Image Gradient` component to the entity.

**Expected behavior**
The "Auto-Save Mode" field should have the following options in the combo-box:
Save As..., Auto Save, Auto Save With Incrementing Names

**Actual behavior**
The "Auto-Save Mode" field has the following options in the combo-box:
SaveAs, AutoSave, AutoSaveWithIncrementalNames

**Comment by alexmontAmazon** [comment]
this is an issue with enums that don't use u64 as the base type.
