### ISSUE TITLE
DPE Inspector: Add support for container child element override label

### ISSUE THREAD

**Issue by cgalvan** [o3de/o3de#16072]
**Describe the bug**
The DPE doesn't currently support overriding the label for container child elements.

This issue has been found in the following components:
Gradient Mixer, Input Context, PhysX Heightfield Collider, Vegetation Asset List

**Steps to reproduce**

1. Launch the Editor with the DPE enabled:
`Editor.exe --ed_enableDPE=true`
2. Open a new or existing level.
3. Create a new entity.
4. Add a `Gradient Mixer` component to the entity.

**Expected behavior**
In the Layers container, the element label should be "<empty>" by default and be updated to the Entity name that layer is pointing to if one is set.

**Actual behavior**
In the Layers container the element label is always just the index (e.g. `[0]`)

**Comment by cgalvan** [comment]
This should be controlled by `ChildNameLabelOverride` attribute I believe.

**Comment by alexmontAmazon** [comment]
It seems to actually be governed by NameLabelOverride...
The investigation continues!
