### ISSUE TITLE
DepthOfField component name has no spaces in between

### ISSUE THREAD

**Issue by cgalvan** [o3de/o3de#16085]
**Describe the bug**
The DepthOfField component has no spaces between the words in its name. This is present with the RPE as well, this is just how this component is registered.

**Steps to reproduce**

1. Launch the Editor with the DPE enabled:
`Editor.exe --ed_enableDPE=true`
2. Open a new or existing level.
3. Create a new entity.
4. Add a `DepthOfField ` component to the entity.

**Expected behavior**
Component name should be "Depth Of Field"

**Actual behavior**
Component name is "DepthOfField".

**Comment by LB-MateuszSzweda** [comment]
Issue verified as fixed in Stabilization/2310 ([15764a9](https://github.com/o3de/o3de/commit/15764a9bc42fd7104ffb5a4b278c415e5e4706a5))
