### ISSUE TITLE
DPE Inspector: Physics Material container not being hidden as not container

### ISSUE THREAD

**Issue by cgalvan** [o3de/o3de#16081]
**Describe the bug**
Physics Material container is likely missing some attribute handling to prevent it from looking like a container.

This issue has been found in the following components:
PhysX Mesh Collider, PhysX Primitive Collider, PhysX Shape Collider, White Box Collider

**Steps to reproduce**

1. Launch the Editor with the DPE enabled:
`Editor.exe --ed_enableDPE=true`
2. Open a new or existing level.
3. Create a new entity.
4. Add a `White Box Collider` component to the entity.

**Expected behavior**
The Physics Material container doesn't show it as a container of elements, and element name is "Entire object"

**Actual behavior**
The Physics Material container appears as a container with a label for how many elements it contains and element index labels.

**Comment by cgalvan** [comment]
This might be a combination #16059 and #16083 . Should re-check if this is still an issue after those are resolved.

**Comment by alexmontAmazon** [comment]
@cgalvan , this seems to be fixed except for still showing "(1 element)" label, which I'll work on...
