### ISSUE TITLE
Give drakeredwind01 labeling permission

### ISSUE THREAD

**Issue by drakeredwind01** [o3de/o3de#16108]
**Is your feature request related to a problem? Please describe.**
just wanted to add this as an issue. hopefully this can be assigned to the people who need to see it.
@AMZN-Gene can vouch for me

**Describe the solution you'd like**
Allow @drakeredwind01 labeling power

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by AMZN-Gene** [comment]
I'm guessing there's a process for giving users triage privileges. @OBWANDO do you know where the doc lives for that?

**Comment by Ulrick28** [comment]
I would be more comfortable recommending we give permissions to drakeredwind01 if a sig officially sponsors them. I recommend drakeredwind01 attends a sig meeting (whichever sig he is interested in participating with) and asks there to get permissions.

**Comment by OBWANDO** [comment]
As I can see there is an indirect recommendation to give permissions, that this not an issue, but I agree with @Ulrick28 's suggestion that the person should at least attend a sig meeting

**Comment by drakeredwind01** [comment]
I have been attending sig security/networking since at least December and have hosted the sig (mostly on than off) since Jan/Feb.

**Comment by michalpelka** [comment]
As discussed in the sig-simulation triage, only @o3de/maintainers have labeling permissions. 
Please take a look at https://github.com/o3de/tsc and the corresponding policies to become a member of @o3de/maintainers.
