### ISSUE TITLE
triage/accepted needs-triage add label `triage-complete` Feature Request

### ISSUE THREAD

**Issue by drakeredwind01** [o3de/o3de#16109]
<ins>**Is your feature request related to a problem? Please describe.**<ins></ins></ins>
there are 926 open, and 1,477 closed issues that do not contain `triage/accepted` or `needs-triage` labels
is there a way to mass add labels?

<ins>**Describe the solution you'd like**</ins>
put into GitHub (or something) `is:issue is:open -label:triage/accepted -label:needs-triage `
then add labels to all issues that show up `needs-triage` or `triage-complete` RE: 
> [Add "triage-complete" label #15877](https://github.com/o3de/o3de/issues/15877)

this will show what issues are new and which aren't

<ins>**Describe alternatives you've considered**</ins>
I could slowly do it myself but I still need label write permission RE:
> [Give drakeredwind01 labeling permission #16108](https://github.com/o3de/o3de/issues/16108)

but this is slow and I would love to see an automated way of doing this

<ins>**Additional context**</ins>

**Comment by lumberyard-employee-dm** [comment]
@OBWANDO Do you have feedback on this issue?

**Comment by adamdbrw** [comment]
Assigning anything other than needs-triage means that the triage is completed, is this not sufficient @drakeredwind01 ?

**Comment by drakeredwind01** [comment]
If we have to look for things without `needs-triage` we then must scan every label instead of just looking for one.
The People who I have met in the discord from GitHub have been getting confused by this. They need to see that something has been done and completed (also the word completed really puts them at ease (especially when it is their issue). 
I myself would like to be able to search issues by searching `is:issue is:open -label:triage-complete` to ensure the most streamlined experience. After talking to a few people from networking, security, and TAC/TSC the feeling is mutual.

Digression:
Maybe triage_complete instead of triage-complete would be a better name so a double click will highlight the entire tag (underscore(_) instead of dash(-)).

**Comment by drakeredwind01** [comment]
If we have to look for things without `needs-triage` we then must scan every label instead of just looking for one.
people who have been arriving in the discord have been getting confused by this. they need to see that something has been done and completed (also the word completed really puts them at ease. 
I myself would like to be able to search issues by searching `is:issue is:open -label:triage-complete` to ensure the most streamlined experience. After talking to a few people from networking, security, and TAC/TSC the feeling is mutual.

**Comment by michalpelka** [comment]
As discussed in sig-simulation issue triage, the next steps should be as follows:
- Create an RFC which will be voted by TSC (@o3de/maintainers) 
- After successful voting only TSC can create the requested label.

**Comment by michalpelka** [comment]
This issue is a duplication of https://github.com/o3de/o3de/issues/16109.

**Comment by drakeredwind01** [comment]
@michalpelka I can't figure out where the "RFC" submission form is. could you please provide a link?
I had gone to a "Joint TSC/SIG Monthly" and they told me that one of the two places I had posted this request was the correct place to submit it and no further steps were required.
