### ISSUE TITLE
Linux (GNOME): Prevent "O3DE Editor is not responding" message during normal startup

### ISSUE THREAD

**Issue by nicholas-rh** [o3de/o3de#16124]
**Describe the bug**
This isn't necessarily a *bug* as much as it is a user experience issue. When launching the editor on Fedora 38 using the default GNOME desktop environment configuration (and presumably on other Linux distros using GNOME), a window will pop up alerting the user that the editor is not responding, even though it is still running in the background. Since the editor startup can take some time, this can be misleading and make the user think the program has frozen/locked up.

**Steps to reproduce**
1.) Launch the editor on a Fedora 38 (or any equivalent distro with GNOME installed using the same configuration?) and click on the loading window. The "O3DE Editor is not responding" message will pop up.

**Expected behavior**
This alert does not appear for as long as the editor is still responsive and running in the background.

**Actual behavior**
The alert pops up.

**Screenshots/Video**
![Screenshot from 2023-06-07 12-59-51](https://github.com/o3de/o3de/assets/133678776/83a6f4ca-5675-4b65-9c0e-545ae641158a)

**Found in Branch**
d3b922d8f9447bfbd3af8195686a85dc11291bc7

**Desktop/Device (please complete the following information):**
    Device: Dell Inc. Precision 5560 Laptop
    OS: Fedora
    Version: 38 Workstation
    CPU: Intel i7-11850H
    GPU: Intel(R) UHD Graphics (TGL GT1) (integrated graphics, no discrete GPU)
    Memory: 64GB

**Comment by Darkinggq** [comment]
I'm on F37 desktop KDE Plasma no problem detected
