### ISSUE TITLE
Linux: .deb package does not list cmake as a dependency

### ISSUE THREAD

**Issue by nicholas-rh** [o3de/o3de#16132]
**Describe the bug**
The .deb package does not list cmake as a dependency even though it is required to complete the installation (during the invocation of get_python.sh in the post installation script). This will lead to the installation failing with the vague error message:
``
dpkg: error processing package o3de (--configure):
 installed o3de package post-installation script subprocess returned error exit 
status 1
Errors were encountered while processing:
 o3de
``

I'm assuming the reason cmake is not listed as a dependency is because the version packaged for Ubuntu 20.04 is too old (there are special instructions for installing it here https://www.o3de.org/docs/welcome-guide/requirements/#linux-cmake). If that's the case a minimal version can be specified in the control file.

**Steps to reproduce**
Attempt to install the deb package on a supported distro without cmake installed

**Expected behavior**
If cmake isn't installed, the package manager will install it.

**Actual behavior**
The package manager does not attempt to install it even though it is a required dependency, and the installation will report an error.

**Desktop/Device (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS

**Comment by drakeredwind01** [comment]
what he wants: If cmake isn't installed, the package manager will install it.
> create feature: auto pip install requirements a thing for O3DE?

The .deb package does not list cmake as a dependency even though it is required to complete the installation
> update .deb package to include `cmake` and any other new features

vague error message `dpkg: error processing package o3de (--configure): installed o3de package post-installation script subprocess returned error exit  status 1 Errors were encountered while processing: o3de`
> make error messages more user friendly

**Comment by nicholas-rh** [comment]
I think for this particular issue we can take out all of those in one fell swoop. It looks like the .deb package is built using CPack, so I believe all we need to apply a patch like

```
--- a/cmake/Platform/Linux/Packaging_linux.cmake
+++ b/cmake/Platform/Linux/Packaging_linux.cmake
@@ -29,6 +29,7 @@ elseif("$ENV{O3DE_PACKAGE_TYPE}" STREQUAL "DEB")
     set(package_dependencies
         libffi7
         clang-12
+        cmake (>= 3.22.0)
         ninja-build
         # Build Libraries
         libglu1-mesa-dev                        # For Qt (GL dependency)

```

which should fix the issue in the next release of the .deb.

**Comment by lumberyard-employee-dm** [comment]
I believe kitware has a special APT repo at https://apt.kitware.com/ for pulling in newer versions of CMake, which can also be added to make sure the Debian package dependencies can pull it in

**Comment by nicholas-rh** [comment]
Looks like this was fixed in https://github.com/o3de/o3de/commit/9c92cb4ae700a7d789e36df2071e9b79d101a2db
