### ISSUE TITLE
Edit-Repo-Properties Archive Removes Download Source Uri when rezipped 

### ISSUE THREAD

**Issue by VeryKaylin-player1** [o3de/o3de#16181]
**Describe the bug**
When the download source uri is changed and user re zipped the archive, the download source uri field will automatically be revert to the fallback

**Steps to reproduce**
1. update repo.json download_source_uri field to the new uri 
2. use ./o3de.bat edit-repo-properties -rp "C:\o3de_Projects\o3deRemoteRepo\repo.json" -ag "C:\o3de_Projects\o3deRemoteRepo\Gems\KaylinGem\" --release-archive-path "C:\o3de_Projects" -f   to rezip the repo.json file 

Then the download_source_uri field would change to fallback

**Expected behavior**
The newly zipped repo.json should get zipped with the updated download_source_uri field and only change the version but not override the hosting uri

**Actual behavior**
When we rezipped the repo.json file, it will update the download_source_uri to the fallback 

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
2a7cbf1c9939e269cd95f24ffc7a71b11a238f85   6/16/2023

**Comment by AMZN-alexpete** [comment]
Without the `--download-prefix` argument, the current logic is unable to create a valid download url which is wny you are seeing `None` in the download_source_uri path.
