### ISSUE TITLE
Windows detected a Trojan virus when Building from Repo

### ISSUE THREAD

**Issue by TheOneAbis** [o3de/o3de#16183]
**Describe the bug**
Upon cloning the O3DE github repository (development branch) and generating the project files with CMake, windows defender blocked and removed this program:
![image](https://github.com/o3de/o3de/assets/26350896/078a295e-b511-43e0-8053-68d6d37826cd)

Seems like it may have made its way into the engine code unnoticed.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. clone the main development branch of the o3de repository
2. generate the project with CMake (I used Visual Studio 17, and the build folder is in a separate location from the source code folder). For me, this virus was automatically removed. for others, it may not be.

**Expected behavior**
Files generate without issue.
**Actual behavior**
Files generate without issue, but this threat shows up in the windows defender as having been blocked and removed, and labeled as a severe threat.

**Screenshots/Video**
The screenshot was posted above.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Version: 22H2
 - CPU: Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz   3.70 GHz
 - GPU: NVidia GeForce RTX 3090
 - Memory 64 GB

**Comment by Kadino** [comment]
This did not reproduce for me in development@906856a9f5 on Windows 10, using CMake 3.25.2. Neither after a fresh checkout of the code, nor after CMake Configure which pulls down dependencies, nor after MSVS project generation, nor compiling profile nor debug. However this is insufficient to prove that there is no latent issue.

There is also a chance that this Trojan has already infiltrated the user's device through another vector, and is somehow following development tools by copying itself into a sensitive location.

**Comment by amzn-changml** [comment]
I'm not able to reproduce this either on [8ef37d5](https://github.com/o3de/o3de/commit/8ef37d5bf659f1ce94bb6ff776bb7cd9be1911f0) on Windows 10, CMake 3.24, MSVS 17.6.1.

We also scan the build output in our CI nodes with Windows Defender. The debug target is done once a night and seems to have passed the build phase successfully: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/380/pipeline/1932

In addition, VirusTotal scans of the prebuilt installer binary comes up clean: https://www.virustotal.com/gui/url/8e776ef391cc91ef5cac10becc1da4cb33426e2be5e47e29cc8802375f995825?nocache=1

We'll continue investigations, though I would also double check to see if this is reproducible on your local environment, as there's a few reports of false positives from Windows Defender as a of a few days ago. Here's an example: https://github.com/marticliment/WingetUI/issues/1116

**Comment by TheOneAbis** [comment]
If neither of you were able to reproduce this, it may be a false positive.

I have cloned the repo and rebuilt the engine several times, so the fact that this only popped up once supports that argument.
Do continue investigations, but it seems that if this is a problem others have had as well only for it to not actually be the case, then I may have been overreacting for nothing. Still, thanks for looking into it.
