### ISSUE TITLE
[LINUX] Can' t stop Play In Editor with Escape key

### ISSUE THREAD

**Issue by yaakuro** [o3de/o3de#16198]
**Describe the bug**
I am having issues to escape from Play in Editor (PIE) mode. When in game mode pressing the Escape key does not react.

**Assets required**
Not required. Any project that opens the Editor will do.

**Steps to reproduce**
1. Open Project
2. Press Play Game
3. Try to stop pressing Escape key
4. Experience the issue.

**Expected behavior**
PIE to stop after pressing the Escape key.

**Actual behavior**
Does not stop the PIE and the Editor gets useless and needs to be terminated.

**Screenshots/Video**
None

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
17dacb028d41fb1c24aeb556dbaa431eab917fe8

 - Device: PC
 - OS: Linux, KUbuntu 22.04 (KDE Plasma Desktop)
 - Version 22.04
 - CPU:  Ryzen 5950x
 - GPU: AMD 6950 XT
 - Memory: 128Gb

**Additional context**
Looking into it a bit shows me somehow that the Qt events are being like 100% consumed by nativeEventFilter (runing the XcbEventHanderBus that is). So whatever got changed in the meanwhile, special keys (like stopping PIE with Escape) doesn't pass those keys to Qt widgets anymore (MainWindow for example).  For my personal usage, I added the **AzFramework::InputChannelNotificationBus::Handler** to **QtEditorApplication_linux.cpp**:

```cpp
void EditorQtApplicationXcb::OnInputChannelEvent(const AzFramework::InputChannel& inputChannel, bool& hasBeenConsumed)
{
  if(GetIEditor()->IsInGameMode() && 
    (inputChannel.GetInputChannelId() == AzFramework::InputDeviceKeyboard::Key::Escape)
  )
  {
	hasBeenConsumed = true;
	GetIEditor()->SetInGameMode(false);
  }

  InputChannelNotifications::OnInputChannelEvent(inputChannel, hasBeenConsumed);
}
```
What I am doing is, checking if the escape key is pressed during Game Play and stop it if the event occurs. I know this might be not a real solution and also not sure if this is only related to my System.

**Comment by AMZN-alexpete** [comment]
Possibly related PRs and issues 
https://github.com/o3de/o3de/pull/16074
https://github.com/o3de/o3de/issues/15958
https://github.com/o3de/o3de/pull/15891

**Comment by yaakuro** [comment]
Yes, I was doing also a bisect and that led me to: 89fe77d780d984c4d84a069dce164379c729eb34 but couldn't make any sense of it. I am using an almost empty project, meaning, even ImGui is disabled however still having the exit issue.

**Comment by AMZN-alexpete** [comment]
I think you may need to have the IMGUI gem enabled for the previous fix to work.  I'm able to repro this issue right now in a project that doesn't have the IMGUI gem enabled.

**Comment by yaakuro** [comment]
Well, as I mentioned, my workaround works for me at the moment. I hope, having ImGUI enabled isn't going to be an official fix for this issue.

**Comment by AMZN-alexpete** [comment]
Oh yeah, I definitely agree with you, this is a critical issue.

**Comment by AMZN-alexpete** [comment]
On Windows, the ESC key is detected by `AzToolsFramework::ActionContextWidgetWatcher::eventFilter` and the matching ESC QAction triggers EditorLib::MainWindow::OnEscapeAction(), but on Linux the action events are not provided/handled
