### ISSUE TITLE
DPE Inspector: Default Material cannot be unassigned from Material component

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16231]
**Describe the bug**
If `ed_enableDPE` is enabled, then *Default Material* cannot be unassigned from the *Material* component. It either is not removed at all, or it is removed, but the material remains applied and unselecting/reselecting the entity causes the material to be assigned back in the property.

It should be noted that this does not occur on RPE.

**Steps to reproduce**
1. In the *Console* execute the `ed_enableDPE=true` command.
2. Select the *Shader Ball* entity and add a *Material* component to it.
3. Assign any material to the *Default Material* property in the *Material* component.
4. Click the X to the right of the name of assigned *Default Material*.

**Expected behavior**
*Default Material* is unassigned.

**Actual behavior**
*Default Material* remains assigned, even if the field appears empty.

**Video**

https://github.com/o3de/o3de/assets/86952082/dc60ebaf-3d83-4a5b-bc12-eb3703527e2c

**Found in Branch**
Development (e6f2547)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
e6f25478821875375f209b79cd2cbc1f69829b93

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by alexmontAmazon** [comment]
writing valid (non-empty) values works, so this might be caused by some code that tries to prevent blank values being written to prefabs.

**Comment by LB-ArturZieba** [comment]
This issue seems to affect all similar properties, as this was also observed on the *Actor asset* property of the *Actor* component, as well as *Anim graph* and *Motion set asset* properties of the *Anim Graph* component. Confirmed on the Development (0eaa719) build.

**Comment by LB-MateuszSzweda** [comment]
Issue verified as fixed in Stabilization/2310 (21bc690).
