### ISSUE TITLE
[Linux] Project Manager and Editor do not work properly on one specific machine

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#16323]
**Describe the bug**
One specific machine running Ubuntu 20.04.6 LTS with RTX 3070 using the latest `NVIDIA driver metapackage from nvidia-driver-535 (proprietary)` is unable to launch the Project Manager properly (its window is colorless and templates' icons are not displayed when compared to how it looks on different machines with various specs) and the Editor has issues running as well: many .png, .tif or .fbx assets are failed by the Asset Processor and after creating a level the Viewport becomes completely black, not displaying any information.
However, on the same machine that Development does not work, the Editor from snap package installer (https://o3debinaries.org/2.1.0/Linux/o3de_2.1.0_amd64.snap) does work without any issues.
A full reinstall of the entire Ubuntu 20.04.6 LTS has been performed on the machine and after installation of all the required packages for O3DE the issue does still occur for the machine. Also attempting to use different available NVIDIA drivers did not resolve the issue.

Please refer to the attached videos of both the Development build and the snap installer of the machine and hardinfo raport for more information.

**Prerequisites**
- Fulfill all the requirements for Linux (https://docs.o3de.org/docs/welcome-guide/requirements/#linux).
- Get the latest Development build from Github and build in any configuration.
- Create and build a project.

**Steps to reproduce**
1. Launch the O3DE.
2. Observe the Project Manager.
3. Launch the Editor.
4. Create a level.

**Expected behavior**
All assets are processed without failures and the Editor is running without issues.

**Actual behavior**
Multiple assets fail processing and the Viewport remains black in the Editor on Development build on a specific machine.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/65ec601b-9552-45de-a2ee-095cbc616e33

https://github.com/o3de/o3de/assets/86953659/4ddac1c4-c6d4-4dcc-9ced-ca00b0698cfc

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/286d04db13a8c9343ace35bf589943230227e9ae

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.6 LTS
- CPU: CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Additional context**
[hardinfo_report_RTX3070.txt](https://github.com/o3de/o3de/files/11982694/hardinfo_report_RTX3070.txt)
[Editor.log](https://github.com/o3de/o3de/files/11982697/Editor.log)

**Comment by tarboss** [comment]
.fbx Assets not processing - can also happen on Windows 10.
here one typical mp4 log:

https://github.com/o3de/o3de/assets/30550163/87200bab-cde6-45d7-9d9a-cc4e8ea3c000

**Comment by spham-amzn** [comment]
Can you zip up the `user/logs` folder and attach to this issue instead of just the Editor.log?

**Comment by tarboss** [comment]
The standardpbr_generated.materialtype for the sponza.fbx was generated wrong (only 9k). I delete the file in the
inter cache file and now the bug gone. Need further investigation, why this happen.
![MaterialTypesBug](https://github.com/o3de/o3de/assets/30550163/154492b7-637a-4b5f-bc98-9dbeb4b895cd)

**Comment by LB-KacperKapusta** [comment]
Due to the newly reported https://github.com/o3de/o3de/issues/16359 issue I was not able to launch the Editor on Linux to gather and attach the `user/logs` folder. However, looking at the Project Manager it seems that the issue does no longer occur after changing the language format on my Ubuntu to **United Kingdom** from **Polish** which turns out to be caused by the https://github.com/o3de/o3de/issues/11139 issue.

**Comment by spham-amzn** [comment]
That is a good point, maybe we will need to add another environment variable to these issues: host language encoding
