### ISSUE TITLE
DPE Inspector: Issues with Vegetation Distribution Filter component

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#16338]
Whenever there is a Gradient group with a Gradient Entity Id property right after it, the DPE shown the Gradient Entity Id field as the group and an empty Gradient group at the end of the component.

RPE:
![image](https://github.com/o3de/o3de/assets/82231674/7811f512-1a9e-4735-9c4a-8c4fe0c6f555)

DPE:
![image](https://github.com/o3de/o3de/assets/82231674/01d0fc2a-b0f2-4bb7-b06f-16424f7643d6)

**Comment by AMZN-daimini** [comment]
Similar issue in the Vegetation Position Modifier component
![image](https://github.com/o3de/o3de/assets/82231674/a286675e-6ab0-452f-9de6-eb2cac25fef7)

Also note that the Preview (Inbound) group is not showing, likely tied to the group visibility issue here https://github.com/o3de/o3de/issues/16336

**Comment by alexmontAmazon** [comment]
did not occur before group rework:


![Image](https://github.com/o3de/o3de/assets/85521892/eae8da67-f7a7-4ae5-a730-4abbbd0cfb57)

**Comment by AMZN-daimini** [comment]
Fixed by https://github.com/o3de/o3de/pull/16353

![image](https://github.com/o3de/o3de/assets/82231674/6d9b7bc0-411f-4972-b69f-ea3a0997e93d)
