### ISSUE TITLE
DPE Inspector: Eye Adaptation properties in Exposure Control component not showing due to Visibility attribute of group being attached to member method

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#16336]
Attributes tied to member functions in the respective class sometimes get retrieved incorrectly. This could in some cases lead to a crash, while in other cases it leads to a class member function being called through an incorrect pointer. If the member function uses member variables, that could result in garbage values being used for testing and incorrect values being returned.

The most common result of this bug are missing fields (if the Visibility attribute calls to a member function under the hood) or fields being enabled/disabled incorrectly.

**Comment by AMZN-daimini** [comment]
RPE:
![Image](https://github.com/o3de/o3de/assets/82231674/888029ac-de83-4f3d-9dbe-5227d14d4262)

DPE:
![Image](https://github.com/o3de/o3de/assets/82231674/8eb26875-1ea3-4139-b6b9-18a2081f3882)

**Comment by alexmontAmazon** [comment]
this bug *did* occur before the group rework, so it will assumedly persist once groups are fixed

**Comment by alexmontAmazon** [comment]
Fixed by https://github.com/o3de/o3de/pull/16413

**Comment by alexmontAmazon** [comment]
I spoke too soon, this still occurs, even with the fix.
