### ISSUE TITLE
DPE Inspector: Actor component displays incorrectly in both RPE and DPE

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#16339]
RPE:
![image](https://github.com/o3de/o3de/assets/82231674/10744986-700e-4f20-ba57-dd3c41f25e15)

DPE:
![image](https://github.com/o3de/o3de/assets/82231674/a49dfae0-4f9f-406c-a1da-9e1d993275e7)

In both cases, nested groups seem to be working incorrectly.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization/2310 ([a2c1876](https://github.com/o3de/o3de/commit/a2c1876ba4d37312dc94210fae09e000e8ecfa78)) build.

**Comment by LB-KacperKapusta** [comment]
It has been observed, using the Stabilization/2310 (https://github.com/o3de/o3de/commit/15764a9bc42fd7104ffb5a4b278c415e5e4706a5) build, that in RPE the Actor component still displays incorrectly:
![RPE](https://github.com/o3de/o3de/assets/86953659/a1b10871-eeb1-49eb-aa2c-98dd972a474a)
Let us know if that should be logged as a separate issue.

It has also been noted that the **Add Material Component** button from under the "Out of view" section of the component is missing in DPE. Please let us know if that design is expected and the button is being deprecated (it is also not present on [the component's documentation page](https://docs.o3de.org/docs/user-guide/components/reference/animation/actor/#actor-component-properties))
