### ISSUE TITLE
DPE: Diffuse Probe Grid component missing Bake Textures button

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#16340]
RPE:
![image](https://github.com/o3de/o3de/assets/82231674/6d37f8c9-b93b-4435-b3dd-64c4bad4eaa8)

DPE:
![image](https://github.com/o3de/o3de/assets/82231674/d3ea18d9-6574-4874-b1f7-996df8bcfd51)

**Comment by alexmontAmazon** [comment]
Did not occur before the group rework:


![Image](https://github.com/o3de/o3de/assets/85521892/83187f32-31b4-45e4-8694-dd0900599275)

**Comment by AMZN-daimini** [comment]
Fixed by https://github.com/o3de/o3de/pull/16353

Note that the sorting is different, but functionality is not affected.

![image](https://github.com/o3de/o3de/assets/82231674/f1404c80-3afd-48e8-a415-99df998628ef)
