### ISSUE TITLE
Projects which do not have PassTemplates.azasset already successfully processed close on launch

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16359]
**Describe the bug**
`Passes/PassTemplates.azasset` fails processing in the Asset Processor and prevents projects from being launched. This was verified on:
* Windows, Linux, and Android
* Pre-built SDK and Source engines
* Minimal Template, Default Template, all Gems enabled, and AutomatedTesting projects

Additionally, `Passes/PassTemplates.azasset` fails processing on all platforms if they are enabled to be processed in the Asset Processor (`linux`, `ios`, `server`, `pc`, and `android`).

The issue also occurs if Asset Processor is launched separately and the project is run while it is active.

The only workaround for this issue is to have a project which has the `Passes/PassTemplates.azasset` asset processed successfully already. This was confirmed by rebuilding a project that was originally created using the Development build that had (050371c) as the most recent commit.

**Steps to reproduce**
1. Create a project.
2. Launch the project.

**Expected behavior**
Editor opens.

**Actual behavior**
Editor closes right after `Passes/PassTemplates.azasset` is processed in the Asset Processor.

**Video, Terminal Editor launch log, and PassTemplates.azasset log**

https://github.com/o3de/o3de/assets/86952082/3065cc24-b357-41e3-bca2-96a43fb125fa

[EditorTerminalLog.txt](https://github.com/o3de/o3de/files/12026788/EditorTerminalLog.txt)
[PassTemplates.azasset-3101315731-9612.log](https://github.com/o3de/o3de/files/12026789/PassTemplates.azasset-3101315731-9612.log)

**Found in Branch**
Development (3290d54)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
3290d5411e33d6bede23a8a57ad62746f12d8bb7

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.2 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by AMZN-alexpete** [comment]
Fix has been merged

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (0ed29d3) build.
