### ISSUE TITLE
Feature Request - Have ONLY Simulated Dynamic Rigid Bodies not update with parent transform changes

### ISSUE THREAD

**Issue by TheOneAbis** [o3de/o3de#16361]
**Is your feature request related to a problem? Please describe.**

Multiple times now I have had an issue with setting the parent of an entity with a Kinematic Dynamic Rigid Body and expecting its transform to start updating with its parent, but then it does not. After some troubleshooting, I realized I had to manually set the entity's OnParentChangedBehavior to Update. I understand why this is disabled by default for SIMULATED Rigid Bodies, but since KINEMATIC ones don't react to physics but rather direct transform changes, I expected it to have this behavior update by default.

**Describe the solution you'd like**

A very simple change - Set Dynamic Rigid Bodies to NOT update with their parent if they are set to SIMULATED (which is already the case), but set them to update with their parent automatically they are set to KINEMATIC. This feels much more intuitive, and especially useful for situations where I want a Trigger box that specifically moves around based on its parent transform behavior. I can't have a trigger box be static in this case, because since it would be moving around, it won't detect trigger collisions with other colliders that happen to be standing still. Thus, I would need a Kinematic Dynamic Rigid Body.

**Describe alternatives you've considered**

Well, the only other alternatives would be to either not do this or change Static Rigid Bodies to detect collisions if they are the ones moving into another collider, but that would kind of defeat the purpose of a Static Rigid Body.

**Additional context**

**Comment by adamdbrw** [comment]
@TheOneAbis could you provide a bit more detail on motivation for this?

**Comment by TheOneAbis** [comment]
@adamdbrw  you have a fair point. However, this can be useful because I would imagine having a trigger volume that follows an entity around would be a common thing, for example having an "interaction" volume that is always in front of a player character, this way anything that enters this volume can be interacted with in some way. I obviously can't have static rigid bodies for this because moving static rigid bodies won't detect collisions. 

From a more intuitive perspective, a "Kinematic" dynamic rigid body means that instead of reacting to physics it reacts to direct transform changes. in other words, NOT physics, which can include changes to a parent's transform. This is how I would interpret it, anyway, as kinematic bodies being the opposite of simulated ones.

Now I have no idea how frequently other people have been using kinematic rigid bodies as children of other entities that are expected to move, but this is just my 2 cents on the matter. It makes more sense intuitively to me, and would be easier to implement a trigger that moves based on a parent such as a player character.

**Comment by TheOneAbis** [comment]
Here is a screenshot of my entity:
![image](https://github.com/o3de/o3de/assets/26350896/d43666a4-5623-4cf4-9bb3-a41370681a94)

heres its hierarchy:
![image](https://github.com/o3de/o3de/assets/26350896/c4fadf3a-1c9b-4390-8030-12ea174ad6df)

The cylinder collider is on the parent (Player), and it is simulated. the sphere collider is on the Interactor child entity, and it is kinematic. I had to explicitely tell it to update with the player's transform to get it to follow correctly.

**Comment by adamdbrw** [comment]
@TheOneAbis since this is a significant change, could you prepare an RFC?

**Comment by TheOneAbis** [comment]
Sure, I will get one ready soon and wll post a link to it in Discord as well as here

Is there a specific channel in the Discord server I should post the link in once it's written?

**Comment by adamdbrw** [comment]
I think that sig-simulation channel works

**Comment by TheOneAbis** [comment]
Sorry for the delay, there were other priorities I was focusing on. The RFC is now up:

https://github.com/o3de/rfcs/issues/51
