### ISSUE TITLE
Bug Report: Material Canvas texture channel alpha in opacity mode doesn't look like MaterialPBR standard

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#16379]
**Describe the bug**
MC there alpha all different not like original MaterialPBR opacity mode: Blended/Cutout/TintedTransparent

**Steps to reproduce**
1. Open the Editor
2. Select the current texture go to the settings select presset "AlbedoWithGenericAlpha" click apply
3. Open the Material Canvas 
4. MC select opacity mode: blended
5. Result below screenshot :)

**Screenshots/Video**
![image](https://github.com/o3de/o3de/assets/17591539/35ed7744-4546-4dee-8986-7f36d5f0addc)

![image](https://github.com/o3de/o3de/assets/17591539/66b25b1b-b9d0-4f72-9193-2045c3d5fdc9)

![image](https://github.com/o3de/o3de/assets/17591539/14478ad4-d042-4287-bc3e-cfc7495bdc6e)

![image](https://github.com/o3de/o3de/assets/17591539/80683d08-ff3b-474a-8705-3101472a709e)

![image](https://github.com/o3de/o3de/assets/17591539/718d22d1-5e6e-427e-9589-a53deeaffb83)

**Found in Branch**
main (2305.0)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
8c1421e2a0d168d34ae9ca6c763270fe8395a809

**Desktop/Device (please complete the following information):**
 - Device: Linux
 - OS: Fedora
 - Version 37

**Comment by RogerShaw** [comment]
I have the same issue and try to solve it. It seems to be caused by "MaterialGraphName_Forward.azsl". When we need to render transparent object, it still use "ForwardPassVertexAndPixel.azsli" but not "TransparentPassVertexAndPixel.azsli".

**Comment by gadams3** [comment]
I've been doing some digging into this. I think I'm just going to convert the material canvas templates to use the material pipeline. This will make them conform to the new system and behave identically to the common material types and shaders as long as the Inputs are set up consistently. I have these changes working locally but I'm doing more testing and investigation to see how much reliance on the material pipeline and intermediate assets will impact iteration times and consistent updates as dependent assets change.
