### ISSUE TITLE
Bug Report - error when deleting a gem from repo.json

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#16381]
**Describe the bug**
When using `o3de.bat edit-repo-properties -rp d:/repo/repo.json -rg RemoteGemA` the gem is removed from the `repo.json` but an error is shown:
```bash
[ERROR] o3de.manifest: Invalid gem json D:\git\o3de-dev-worktree\RemoteGemA\gem.json supplied or file missing.
```

**Steps to reproduce**
1. Create a local repo and add a gem to it
2. remove the gem from the local repo using the `o3de.bat edit-repo-properties --remove-gem` command

**Expected behavior**
No errors are shown

**Actual behavior**
An error is shown similar to:
```bash
[ERROR] o3de.manifest: Invalid gem json D:\git\o3de-dev-worktree\RemoteGemA\gem.json supplied or file missing.
```

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
b4ca369207868ba025f73edd8de71769610b9b37

**Comment by VeryKaylin-player1** [comment]
The command for remove gem is called --delete-gem "gemName" and the CLI -rg stands for --replace-gem, with the gem path you want to replace with. It deletes all gems from the repo.json gems_data field and adds the given gem.
