### ISSUE TITLE
Release 23.05 fails to install required package dependencies for bundled Python

### ISSUE THREAD

**Issue by nicholas-rh** [o3de/o3de#16392]
**Describe the bug**
An error occurs when installing python package dependencies for the bundled python rev2 on release 23.05. The issue doesn't seem to happen at the tip of the development branch, which uses an updated python rev4 package. Error log obtained by running get_python.sh on Ubuntu 22.04 is attached.

**Steps to reproduce**
1. Download the release 23.05 tagged source code
2. Run python/get_python.sh

**Expected behavior**
All dependencies are successfully installed for the bundled python

**Actual behavior**
An error message occurs which causes the script to return an error code

**Found in Branch**
2305.0

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
8c1421e2a0d168d34ae9ca6c763270fe8395a809

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Fedora 38, Ubuntu 22.04

**Additional context**
Reproduced by attempting to build from source on Fedora 38, attempting to run the get_python.sh script on both Fedora 38 and Ubuntu 22.04, and when installing the deb package on Ubuntu 22.04 which runs get_python.sh as part of the post installation script.

[error.txt](https://github.com/o3de/o3de/files/12072115/error.txt)

**Comment by amzn-changml** [comment]
Looks like a downstream dependency to `Cython` (and its update to 3.0.0) and lack of wheels broke this for pyyaml: https://www.github.com/yaml/pyyaml/issues/601. Pytest may only need pyyaml as an optional, but I'm not certain if we're still using yaml files to configure tests.

We can either wait for the fix from pyyaml and bump the package version for the point release, or have folks use the various workarounds in the issue I linked (seems like either pyyaml 5.3.1 or 6.0.0 with `--no-build-isolation` may work)

**Comment by nicholas-rh** [comment]
> Looks like a downstream dependency to `Cython` (and its update to 3.0.0) and lack of wheels broke this for pyyaml: https://www.github.com/yaml/pyyaml/issues/601. Pytest may only need pyyaml as an optional, but I'm not certain if we're still using yaml files to configure tests.
> 
> We can either wait for the fix from pyyaml and bump the package version for the point release, or have folks use the various workarounds in the issue I linked (seems like either pyyaml 5.3.1 or 6.0.0 with `--no-build-isolation` may work)

Thanks, did you happen to replicate it on Windows, or only Ubuntu as well?

**Comment by amzn-changml** [comment]
It's repro'ed on Windows as well

**Comment by amzn-changml** [comment]
Interestingly, a surface scan of the codebase doesn't show any usage of pyyaml being imported: https://github.com/search?q=repo%3Ao3de%2Fo3de%20yaml&type=code. I'm running a quick experiment to verify that none of the test workflows require it.

**Comment by tonybalandiuk** [comment]
@amzn-changml  what were the results of your quick experiment?

**Comment by amzn-changml** [comment]
I found that we don't need the library and it has no effect on AR or tests involving our workflows. 

It's not in the codebase, nor are there references to it in AR. Seems like we need to do a full review of these python libraries to ensure that we are not adding additional maintenance and security burdens unnecessarily
