### ISSUE TITLE
Linux: Add project manager to PATH when installing using the deb package

### ISSUE THREAD

**Issue by nicholas-rh** [o3de/o3de#16401]
As I understand it, currently when installing the deb package it's necessary to manually cd to the install directory under /opt to run the project executables. It would be useful to add a simple script under /bin to launch the project manager, so that users can launch the project from the terminal outside of the install path, which ideally should be an implementation detail.

**Comment by nicholas-rh** [comment]
All that is needed for this is to install a very simple script named "o3de" under /bin like the following:

```
pushd /opt/o3de
bin/Linux/profile/Default/o3de
popd
```

**Comment by lumberyard-employee-dm** [comment]
Well a symlink under the /usr/bin can also be added that points to the /opt/o3de/bin folder

**Comment by nicholas-rh** [comment]
That would probably work as well, I was looking into a way to add it using cmake but was having a hard time getting cpack to work locally. I imagine it should be as simple as doing something like this (or the equivalent for a symlink)?:

```
--- a/cmake/Platform/Linux/Packaging_linux.cmake
+++ b/cmake/Platform/Linux/Packaging_linux.cmake
@@ -68,4 +68,14 @@ elseif("$ENV{O3DE_PACKAGE_TYPE}" STREQUAL "DEB")
         ${CMAKE_BINARY_DIR}/cmake/Platform/Linux/Packaging/postrm
     )
 
+    configure_file("${LY_ROOT_FOLDER}/cmake/Platform/${PAL_PLATFORM_NAME}/Packaging/o3de.in"
+        "${CMAKE_BINARY_DIR}/cmake/Platform/${PAL_PLATFORM_NAME}/Packaging/o3de"
+        @ONLY
+    )
+    ly_install(FILES
+        "${CMAKE_BINARY_DIR}/cmake/Platform/${PAL_PLATFORM_NAME}/Packaging/o3de"
+        DESTINATION /bin
+        COMPONENT ${CMAKE_INSTALL_DEFAULT_COMPONENT_NAME}
+    )
+
```

With o3de.in just being the script I wrote out above.

**Comment by lumberyard-employee-dm** [comment]
> Something else which came to mind is that it would also be useful to add the command line o3de tool under PATH as well as well somehow, so that it can also be used without needing to know the installation path of the engine, which should ideally be an implementation detail.
> 
> The problem is that is shares the "o3de" name with the project manager executable, so something would need to be renamed at least from the perspective of what is exposed to the user on the command line. Maybe one way around this would be to run the project manager only when no arguments are supplied, and run the CLI tool otherwise, although this wouldn't work if arguments needed to be passed into the project manager at some point.

Well the CLI tool does have the python extension, so it is `o3de.py`.
Also it requires using the python package downloaded by o3de during install.
The `o3de.sh` script actually calls the `o3de.py` python package script using the o3de python package.

So the extension of `o3de.sh` distinguishes it from the GUI application of `o3de`

**Comment by byrcolin** [comment]
I think the sim link is the linux way of doing things, as to the name being the same, I'm not sure you should run the scripts from any other folder than the scripts folder... and if so the current folder should always be searched first in which case the same name wont matter. However I would support renaming of the program manager from o3de to something like program manager if the scripts can be run from any folder.

**Comment by byrcolin** [comment]
@nicholas-rh I see this is assigned to you, do you want to continue on this or should we leave it to the community?
