### ISSUE TITLE
Build nodes: Configure build nodes to use Java 11 or newer

### ISSUE THREAD

**Issue by brianherrera** [o3de/o3de#16425]
**Is your feature request related to a problem? Please describe.**
Starting with v2.361.1, Jenkins requires java 11 or newer. (See: https://www.jenkins.io/blog/2022/06/28/require-java-11/) 

Updating our Jenkins pipeline to this version or newer causes our build nodes to fail to connect to Jenkins. This prevents us from upgrading Jenkins to the latest LTS version. 

**Describe the solution you'd like**
Upgrade or configure build nodes to use Java 11 or newer. Looks like some nodes already have java 11 installed based on the install scripts, but they need to default to java 11 instead of 8.

**Comment by drakeredwind01** [comment]
suggest adding `triage/accepted`

**Comment by brianherrera** [comment]
Windows build nodes updated to use Java 11 or newer. Linux was already using Java 11. 

https://github.com/o3de/o3de-jenkins-pipeline/pull/36
