### ISSUE TITLE
DPE Inspector: Changes made with Sky Atmosphere component do not take effect when DPE is enabled

### ISSUE THREAD

**Issue by LB-KacperBieniek** [o3de/o3de#16438]
**Describe the bug**
Editing Sky Atmosphere component parameters when DPE is enabled does not change anything in the viewport. Once the changes are made and user disables DPE, and then changes one additional parameter in the component, the changes are applied.
The issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Create a new level.
2. Delete the Atom Default Environment entity (for better visibility later on).
3. Create an Entity and add the Sky Atmosphere component to it.
4. In the viewport find the sun to better see the Sky Atmosphere changes.
5. Make sure DPE is disabled (enter `ed_enableDPE 0` in the Console).
6. Make a few changes in the Sky Atmosphere component to ensure they are reflected in the viewport.
7. Enable DPE (enter `ed_enableDPE 1` in the Console).
8. Make a few changes in the Sky Atmosphere component.

**Expected behavior**
The changes are reflected in the viewport..

**Actual behavior**
While DPE is enabled the changes do not take effect.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/87059746/6545b43d-5cf4-4d6c-b923-a263ae967421

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[3210473](https://github.com/o3de/o3de/commit/321047321e3b6b22d842db8fec9c4f2d4ed646b8)

**Desktop/Device:**
- Device: PC
- OS: Linux
- Version: Ubuntu 22.04.2 LTS
- CPU: Ryzen 5600H
- GPU: NVidia RTX 3070
- Memory: 16GB

**Comment by alexmontAmazon** [comment]
fixed by https://github.com/o3de/o3de/pull/16545

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (1ea0a41) build.
