### ISSUE TITLE
DPE Inspector: PostFX Layer component does not throw a warning when deleting all Camera Tags

### ISSUE THREAD

**Issue by LB-KacperBieniek** [o3de/o3de#16437]
**Describe the bug**
Attempting to remove all elements from either Select Camera Tags Only or Excluded Camera Tags containers should result in a warning pop-up prompting the user to confirm the removal. The pop-up is thrown properly while DPE is disabled, but when DPE is enabled the pop-up does not appear and all elements are removed.
Issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Create an Entity and add the PostFX Layer component to it.
2. Make sure DPE is disabled (enter `ed_enableDPE 0` in the Console).
3. Add empty elements to either Select Camera Tags Only or Excluded Camera Tags containers.
4. Attempt to remove all elements by pressing the bin icon next to Select Camera Tags Only or Excluded Camera Tags.
5. Enable DPE (enter `ed_enableDPE 1` in the Console).
6. Add empty elements to either Select Camera Tags Only or Excluded Camera Tags containers.
7. Attempt to remove all elements by pressing the bin icon next to Select Camera Tags Only or Excluded Camera Tags.

**Expected behavior**
After step 4 and 7 a warning appears prompting the user to confirm removal of all elements.

**Actual behavior**
After step 7 no warning appears and all elements are removed without confirmation from the user.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/87059746/d0c8968c-743c-428a-ba5f-31362a2b389a

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[3210473](https://github.com/o3de/o3de/commit/321047321e3b6b22d842db8fec9c4f2d4ed646b8)

**Desktop/Device:**
- Device: PC
- OS: Linux
- Version: Ubuntu 22.04.2 LTS
- CPU: Ryzen 5600H
- GPU: NVidia RTX 3070
- Memory: 16GB

**Comment by LB-ArturZieba** [comment]
This issue also occurs in all of the *Surface Data* components' Tag elements.

**Comment by LB-KacperBieniek** [comment]
Issue verified as fixed on the Development (26e6894) build.
