### ISSUE TITLE
Closing Script Canvas crashes the Editor

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#16449]
**Describe the bug**
It has been observed that closing Script Canvas crashes the Editor. This issue occurs with and without a script opened in the Script Canvas.

Please refer to the attached video, logs and .dmp file for more information.

**Steps to reproduce**
1. Open Script Canvas.
2. Close Script Canvas.

**Expected behavior**
Script Canvas closes and the editor remains stable.

**Actual behavior**
Closing Script Canvas crashes the Editor.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86952318/1e8df485-0386-4408-8067-58ee959e632e

[Editor.log](https://github.com/o3de/o3de/files/12171055/Editor.log)
[error.log](https://github.com/o3de/o3de/files/12171056/error.log)
[error.zip](https://github.com/o3de/o3de/files/12171057/error.zip)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
(c9db420)

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 7 3800X 8-Core Processor
- GPU: AMD Radeon RX 5700 XT
- Memory: 16 GB

**Comment by LB-MichalRodzos** [comment]
This issue does not occur on Stabilization/2310 (https://github.com/o3de/o3de/commit/3707b549a28229c8501e363943a064d28bb5dab7), closing the issue.

**Comment by LB-MichalRodzos** [comment]
Reopening the issue as it still occurs on Linux Development Installers (.deb: https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb and .snap: https://o3debinaries.org/2.1.0/Linux/o3de_2.1.0_amd64.snap).

**Comment by iamjbq** [comment]
I have noticed this still occurring in 24.09.2 on Windows when closing the window after saving a script canvas.

[error.log](https://github.com/user-attachments/files/19268044/error.log)

**Comment by guillaume-haerinck** [comment]
Hey ! It should be definitly closed by https://github.com/o3de/o3de/pull/18734
