### ISSUE TITLE
DPE Inspector: Both Grid modes in Diffuse Probe Grid component can be changes to Baked and Auto Select without baking the textures first, which can lead to a crash

### ISSUE THREAD

**Issue by LB-KacperBieniek** [o3de/o3de#16456]
**Describe the bug**
When DPE is enabled it is possible to change both Editor Mode and Runtime Mode of Diffuse Probe Grid component to Baked and Auto Select without baking the texture first. In 9/10 tries this leads to a crash.
The error.log file was not generated on Linux, so the attached files are from Windows.

This issue is active on both Windows and Linux.

**Steps to reproduce**
1. Create an Entity and add the Diffuse Probe Grid and Box Shape components to it.
2. Make sure DPE is disabled (enter `ed_enableDPE 0` in the Console).
3. Try to change the Editor Mode and Runtime Mode parameter.
4. Enable DPE (enter `ed_enableDPE 1` in the Console).
5. Try to change the Editor Mode and Runtime Mode parameter.

**Expected behavior**
A warning appears prompting the user to bake the textures.

**Actual behavior**
No warning appears and the Editor crashes.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/87059746/f3c17686-8fbf-4952-8e01-87449f3bfb3d

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[c9db420](https://github.com/o3de/o3de/commit/c9db420b566866897e7bc41212439fbc0e6ab018)

**Desktop/Device:**
- Device: PC
- OS: Linux
- Version: Ubuntu 22.04.2 LTS
- CPU: Ryzen 5600H
- GPU: NVidia RTX 3070
- Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/12173465/Editor.log)
[error.log](https://github.com/o3de/o3de/files/12173466/error.log)
[error.zip](https://github.com/o3de/o3de/files/12173467/error.zip)

**Comment by cgalvan** [comment]
It appears the DPE is currently missing `ChangeValidate` attribute handling, so this will need to be added.

**Comment by LB-KacperBieniek** [comment]
Issue verified as fixed on latest Stabilization/2310 ([87130af](https://github.com/o3de/o3de/commit/87130afab002db82c19506ed422c387c9aa3a3ea)).
