### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mythrz** [o3de/o3de#16467]
**Is your feature request related to a problem? Please describe.**
Lua Editor can change its settings. e.g., font colour, background, selected, etc... Closing the Editor and engine does not keep the settings saved. In other words, the settings are not stored from one session to another.

**Describe the solution you'd like**
a) Open Lua Editor, change my settings and save those settings to a file. If I close everything and the next day I start another session, all settings are restored.
b) Also, that file should be saved. So, if I format the machine and re-install the PC, I can just copy and past it. 

**Describe alternatives you've considered**
**I would rather have an extension for Visual Studio Community 2022** (probably the IDE most used for game development). Or for VS Code (second most used. Maybe first, who knows...).
I am not sure if maintaining an editor like this one has more advantages than embracing what already exists, and just make an extension to allow debugging with the O3DE engine.

**Comment by lumberyard-employee-dm** [comment]
I believe @galibzon made a Lua Extension for VSCode in this PR: https://github.com/o3de/o3de/pull/15189

I believe the extension is on the Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=lumbermixalot.o3de-lua-debug

**Comment by galibzon** [comment]
@mythrz , the VS code extension works like a breeze. Thanks to @lumberyard-employee-dm for reminding that it exists already.
