### ISSUE TITLE
DPE Inspector: Debug Rendering component certain properties do not unlock and Custom Debug Variables does not expand

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16466]
**Describe the bug**
*Override Base Color*, *Override Roughness*, and *Override Metallic* properties do not unlock properties that are greyed out by them. Additionally, on Linux, *Custom Debug Variables* does not expand properly.

**Steps to reproduce**
1. Execute `ed_enableDPE 1` command in the *Console*.
2. Select the level.prefab and add *Debug Rendering* component to it.
3. Enable *Override Base Color*, *Override Roughness*, and *Override Metallic* properties in the *Debug Rendering* component.
4. (Linux only) Expand the *Custom Debug Variables*.

**Expected behavior**
*Base Color Value*, *Roughness Value*, and *Metallic Value* are not greyed out anymore. *Custom Debug Variables* expands showing properties under it.

**Actual behavior**
*Base Color Value*, *Roughness Value*, and *Metallic Value* remain greyed out. (Only on Linux) *Custom Debug Variables* does not expand.

**Video**

https://github.com/o3de/o3de/assets/86952082/dee0cd73-dbea-4568-8dae-6bd6812f49a1

**Found in Branch**
Development (ad967c1)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
ad967c1143588abf0a75d124bd6ab6ef0ae5602d

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.2 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by LB-ArturZieba** [comment]
Issue with expanding group was also observed on the *Terrain World Debugger* level component in the *Show Terrain Queries* property.

**Comment by LB-MateuszSzweda** [comment]
Please note that on Stabilization/2310 ([bc8eb66](https://github.com/o3de/o3de/commit/bc8eb66f885cfa99a444703792482f169692ffdc)) build the issue no longer occurs.
