### ISSUE TITLE
Engine build fails with visual studio 2022

### ISSUE THREAD

**Issue by anon-oss** [o3de/o3de#16479]
**Describe the bug**
building engine fails on windows with visual studio 2022 due to compile errors

**Steps to reproduce**
1. Clone git repository and complete all steps required, and make a new project to do a source engine build
2. Generate cmake files  with physx 5 using -DAZ_USE_PHYSX5=ON and try to compile the projects source engine
3. Compile fails with errors

**Expected behavior**
Get the engine compiled without error, with or without physx 5

**Actual behavior**
A clear and concise description of what actually happened. Build failes with physx4 and physx5 

**Error Log**

_With Physx5 only_

E:/o3de/Gems/PhysX/Code/Source/ArticulationLinkComponent.cpp(274,35): error C2220: the following warning is treated as an error [E:\\GameTest\build\windows\External\PhysX-8d2f28b0\Code\P
hysX.Static.vcxproj]
          physx::PxArticulationAxis articulationAxis,
                                    ^
E:/o3de/Gems/PhysX/Code/Source/ArticulationLinkComponent.cpp(274,35): warning C4100: 'articulationAxis': unreferenced formal parameter [E:\\GameTest\build\windows\External\PhysX-8d2f28b0
\Code\PhysX.Static.vcxproj]

_Happens with physx4 and physx5_

E:/o3de/Gems/Atom/RHI/DX12/Code/Source/RHI/IndirectBufferSignature.cpp(57,36): error C2065: 'D3D12_INDIRECT_ARGUMENT_TYPE_DISPATCH_RAYS': undeclared identifier [E:\\GameTest\build\window
s\External\DX12-7523277a\Code\Atom_RHI_DX12.Private.Static.vcxproj]
                      argDesc.Type = D3D12_INDIRECT_ARGUMENT_TYPE_DISPATCH_RAYS;

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
70946e11a792dce7a966ca83ed3a3d3e2525df1b

Device: [PC]
OS: [Windows]
Version [Windows 10]
CPU [Ryzen 1800x ]
GPU [NVidia RTX 3060]
Memory [e.g. 32 GB]

**Additional context**
Compile was attempted with visual studio 2022 17.6 and cmake 3.27.1

**Comment by adamdbrw** [comment]
This is a couple of different issues:
- We need to add `[[maybe unused]] ` to avoid unused parameter warnings in Articulations. This is sig-simulation. I will add such issue after the triage.
- There is another error which traces back to RHI, which is sig-graphics.

**Comment by moudgils** [comment]
Can you add Windows build version that caused this issue. Thanks
