### ISSUE TITLE
DPE Inspector: "Create New Image..." button is missing from the Terrain Macro Material component

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#16478]
**Describe the bug**
With `ed_enableDPE` set to true the Terrain Macro Material component lacks the `Create New Image...` button. The mentioned button appears along with the `Edit` button upon assigning an asset to the `Color Texture` field. Note that in RPE the `Create New Image...` is available from the beginning.

The issue occurs on both Linux and Windows.

**Steps to reproduce**
1. Execute `ed_enableDPE 1` command in the Console. 
2. Create an entity.
3. Add the Terrain Macro Material component and the required component to the created entity.
4. Assign an asset to the `Color Texture` field.

**Expected behavior**
`Create New Image...` button is available in the component right away.

**Actual behavior**
`Create New Image...` button is not available in the component unless the `Color Texture` asset is assigned.

**Screenshots/Video**
DPE enabled:
![TerrainMacroMaterial_DPEenabled](https://github.com/o3de/o3de/assets/86953659/bd2bf4be-7771-413a-ba3a-9ddfca282a88)
DPE disabled:
![TerrainMacroMaterial_DPEdisabled](https://github.com/o3de/o3de/assets/86953659/52ddaa70-49ab-4f67-8895-26ee35a0260f)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/70946e11a792dce7a966ca83ed3a3d3e2525df1b

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.6 LTS
- CPU: CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Comment by LB-MateuszSzweda** [comment]
Issue verified as fixed in Stabilization/2310 (4f0627b) build.
