### ISSUE TITLE
DPE Inspector: Certain properties of Terrain World Renderer can exceed their bounds

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16475]
**Describe the bug**
*Terrain World Renderer* properties *Macro clipmap margin size: texels* and *Detail clipmap margin size: texels* properties can exceed their bounds [1 - 8] while DPE is enabled.

**Steps to reproduce**
1. Execute `ed_enableDPE 1` command in the *Console*.
2. Select the *level.prefab*, add a *Terrain World Renderer* and *Terrain World* components to it.
3. Select the *Terrain World Renderer* component, adjust *Macro clipmap margin size: texels* and *Detail clipmap margin size: texels* properties using the slider.

**Expected behavior**
The properties are bound at [1 - 8] values.

**Actual behavior**
The properties are not bound and accept [0 - 2147483647] values.

**Video**

https://github.com/o3de/o3de/assets/86952082/f2b7765c-4c69-4794-b5ba-5822d823e659

**Found in Branch**
Development (70946e1)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
70946e11a792dce7a966ca83ed3a3d3e2525df1b

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by alexmontAmazon** [comment]
note that the slider follows the soft min/max, and will indeed cap out at 8, but the actual maximum set is 16, so it will allow values up to 16 if you type it in directly or mousewheel in the number text box.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (74f49c8) build.
