### ISSUE TITLE
DPE Inspector: Sub Priority property's slider is broken inside the Terrain Layer Spawner component

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#16476]
**Describe the bug**
With `ed_enableDPE` set to true the Sub Priority value can be mistakenly set to values in range [-2147483648, 2147483647], while the tooltip does not include information about the correct value range. The slider cannot be moved by clicking or dragging it. Note that in RPE the value range can be set to values in range of [-10000, 10000], which matches its tooltip (the soft min of the slider is set to -100 and its soft max set to 100).

The issue occurs on both Linux and Windows.

**Steps to reproduce**
1. Execute `ed_enableDPE 1` command in the Console.
2. Create an entity.
3. Add the Terrain Layer Spawner component and the required component to the created entity.
4. Use Sub Priority's property slider.

**Expected behavior**
Sub Priority slider can be precisely adjusted by clicking or dragging it. The property's tooltip mentions the value range and it is respected by the slider.

**Actual behavior**
Sub Priority slider cannot be precisely adjusted by clicking or dragging it. The property's tooltip does not mention the value range and incorrect values can be set.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/c1c4c9be-77fe-40ae-9289-0e87263d5eba

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/70946e11a792dce7a966ca83ed3a3d3e2525df1b

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.6 LTS
- CPU: CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (74f49c8) build.
