### ISSUE TITLE
Asset Browser - thumbnails loading very slowly.

### ISSUE THREAD

**Issue by rainbj** [o3de/o3de#16480]
**Describe the bug**
It was noticed recently that after a build, the thumbnail images were not loading in. I waited 20 minutes to see if they would load in, but they did not. AP appears to be done processing all my asset, but AB thumbnails are just still showing the loading symbol.
![2023-07-31_11-29-52](https://github.com/o3de/o3de/assets/82551958/2098381a-1b6f-4bf2-ade8-7a708c0a2f74)

Things I've tried:
- Playing with the asset in the AB (right click, move,)
- Will not allow me to rename 
![2023-07-31_11-40-09](https://github.com/o3de/o3de/assets/82551958/84c5958c-6283-4a46-8e94-ff071a1c6a5c)
- changing the viewed

Thing that fixed it:
- After shutting down the editor and restarting it. It started responding and loading the thumbails.

**Steps to reproduce**
1. Downloaded latest project from DEV
2. Click on 'after the build watch the asset in the AB to view when the thumbnails show up'

**Expected behavior**
I would expect we prioritize which thumbnails that show up based on the directory you are looking at.

**Actual behavior**
When thumbnails do load (they seem to be loading in a random order.) 

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
DEV

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC] 
 - OS: [e.g. Windows]
 - Version [10, ]
 - CPU [ Ryzen 5900x, ]
 - GPU [ NVidia RTX 3090]
 - Memory [e.g. 32GB]

**Additional context**

**Comment by HydrogenC** [comment]
Bug still present in 2310, thumbnails of textures could hardly be loaded.
