### ISSUE TITLE
DPE Inspector: Properties affecting Debug Light in the Debug Rendering component are not updated in the Viewport until one of the properties that update properly is changed

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16498]
**Describe the bug**
In the *Debug Rendering* component there is a set of properties that are available only if the *Lighting Source* is set to *Debug Light*:
* *Debug Light Azimuth*
* *Debug Light Elevation*
* *Debug Light Color*
* *Debug Light Intensity*

Changing these properties while DPE is enabled is not reflected in the Viewport until one of the properties that are reflected properly is changed (for example *Enable Render Debugging* is switched off and on).

**Steps to reproduce**
1. Execute the `ed_enableDPE 1` command in the *Console*.
2. Select the `level.prefab` and add a *Debug Rendering* component to it.
3. In the *Debug Rendering* component, set the *Lighting Source* property to *Debug Light*.'
4. Change any of the *Debug Light* properties below and observe the Viewport.

**Expected behavior**
Change in the properties is reflected in the Viewport.

**Actual behavior**
Change in the properties won't be reflected in the Viewport until a property that is reflected properly is changed.

**Video**

https://github.com/o3de/o3de/assets/86952082/7353c03c-3dd2-4751-bf76-774249077090

**Found in Branch**
Development (42e8f1f)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
42e8f1f66373a0ea995a564b5ff7500df7fe9bab

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by alexmontAmazon** [comment]
this probably just needs another ChangeNotify added to the appropriate properties. The RPE gets away with not adding these because it relies on unnecessary full tree refreshes

**Comment by LB-ArturZieba** [comment]
This issue was also observed on *Exposure Control* > *Eye Adaptation* properties and all of the *HDR Color Grading* properties on the Development (d44c577) build.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (1ea0a41) build. Exposure Control and HDR Color Grading components mentioned in the comment were fixed as well.
