### ISSUE TITLE
DPE Inspector: Sliders of Atom Hair component's properties are broken

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#16490]
**Describe the bug**
With `ed_enableDPE` set to true the Local Constraint Iterations, Length Constraint Iterations, Max Shadow Fibers values can be mistakenly set to values in range [-2147483648, 2147483647], while the tooltip does not include information about the correct value range. The slider cannot be moved by clicking or dragging it. Note that in RPE the value range can be set to values in range of [1, 10] in case of Local Constraint Iterations and Length Constraint Iterations, which matches their tooltip and Max Shadow Fibers matches its tooltip with [0, 100] as well.

Please note that the issue occurs on both Linux and Windows.

**Steps to reproduce**
1. Execute `ed_enableDPE 1` command in the Console.
2. Create an entity.
3. Add the Atom Hair and Actor components to the created entity.
4. Use Local Constraint Iterations, Length Constraint Iterations or Max Shadow Fibers property slider.

**Expected behavior**
Properties' sliders can be precisely adjusted by clicking or dragging them. The properties' tooltips mention the value range and those are respected by the sliders.

**Actual behavior**
Properties' sliders cannot be precisely adjusted by clicking or dragging them. The properties' tooltips do not mention the value range and incorrect values can be set.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/913e2784-d0b7-4db4-9886-8cd4b438d4af

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/42e8f1f66373a0ea995a564b5ff7500df7fe9bab

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.6 LTS
- CPU: CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Comment by LB-MateuszSzweda** [comment]
Reopening the issue on latest Development (74f49c8). Unfortunately even though fixed on Windows platform the issue still persists on Linux.

**Comment by LB-MichalRodzos** [comment]
The same issue occurs for Perlin Noise Gradient component on Development (d44c577). However, only Random Seed and Octaves properties are affected. Also it occurs only on Linux platform.

**Comment by cgalvan** [comment]
This has been fixed with this linux fix here: https://github.com/o3de/o3de/pull/16626

**Comment by LB-MateuszSzweda** [comment]
Issue verified as fixed on Linux on the Stabilization/2310 (6f4ea1d)) branch.
