### ISSUE TITLE
Viewport click hit-test fails

### ISSUE THREAD

**Issue by ohmaya** [o3de/o3de#16494]
Cannot accurately select entities.

Since:
https://github.com/o3de/o3de/commit/20aaa7de7a99a93ebc80f10e596a4afca2ec4999
Use actual pixel resolutione for render resolution.

Thanks.

**Comment by lumberyard-employee-dm** [comment]
It looks like the DPI change for debug font might be causing a hit test issue @VickyAtAZ ?

**Comment by mbalfour-amzn** [comment]
Repro steps:
1. Set DPI to 200%
2. Open the AutomatedTesting project in the Editor.
3. Create a new level called 'ProcPrefabTest' .
4. Open the Asset Browser.
5. Search for bunny_fbx and drag bunny_fbx.procprefab into the level.
6. Try moving the bunny_fbx around with the Transform gizmo in the viewport.

At DPI=100%, the bunny_fbx is selectable and can be moved around. At DPI=200%, it can't be selected or moved.
