### ISSUE TITLE
DPE Inspector: Certain Vegetation components have empty Preview (Inbound) properties

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16508]
**Describe the bug**
With DPE enabled, *Vegetation Asset Weight Selector* and *Vegetation Distribution Filter* components' *Preview (Inbound)* property is empty. It should be noted that *Preview* property in the *Vegetation Distribution Filter* component is displaying properly.

This issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Execute the `ed_enableDPE 1` command in the *Console*.
2. Create an entity and add either *Vegetation Asset Weight Selector* or *Vegetation Distribution Filter* component to it.
3. View the *Preview (Inbound)* property on the added component.

**Expected behavior**
Preview is present (black rectangle by default).

**Actual behavior**
Preview is empty.

**Video**

https://github.com/o3de/o3de/assets/86952082/dc038d11-d05b-438b-b63b-b40d10c60e78

**Found in Branch**
Development (1ed05c8)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
1ed05c8f21ebe203712128f1e473dc9bc7d7a4ab

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by LB-ArturZieba** [comment]
This issue was also observed on a *Vegetation Position Modifier* component on the Development (1ed05c8) build.

**Comment by LB-ArturZieba** [comment]
This was also observed on *Gradient* components on the Development (4b68b1f) build.

**Comment by LB-KacperBieniek** [comment]
Issue verified as fixed on latest Stabilization/2310 ([87130af](https://github.com/o3de/o3de/commit/87130afab002db82c19506ed422c387c9aa3a3ea)).
