### ISSUE TITLE
DPE Inspector: Enable shutters and Enable shadow flags of Light component do not enable/disable their child properties until component is refreshed

### ISSUE THREAD

**Issue by LB-KacperBieniek** [o3de/o3de#16501]
**Describe the bug**
Trying to enable/disable the _Enable shutters_ and _Enable shadow_ flags when DPE is enabled results in their child properties not being enabled/disabled together with them until component is refreshed. The _Enable shadow_ property is available in two _Light types_: _Point (sphere)_ and _Spot (disk)_. The _Enable shutters_ property is only available in _Spot (disk)_ _Light type_. The remaining _Light types_ do not have flags with this issue.
This issue is active on both Windows and Linux.

**Steps to reproduce**
1. Create an Entity and add a _Light_ component to it.
2. Set the _Light type_ to _Spot (disk)_.
3. Make sure DPE is disabled (enter `ed_enableDPE 0` in the _Console_).
4. Enable/disable the _Enable shutters_ and _Enable shadow_ flags a couple of times.
5. Enable DPE (enter `ed_enableDPE 1` in the Console).
6. Enable/disable the _Enable shutters_ and _Enable shadow_ flags a couple of times.

**Expected behavior**
_Enable shutters_ and _Enable shadow_ flags enable/disable their child properties immediately.

**Actual behavior**
_Enable shutters_ and _Enable shadow_ flags do not enable/disable their child properties until the _Light_ component is refreshed.

**Video**

https://github.com/o3de/o3de/assets/87059746/1d4c7cb9-0f91-4f13-bbf7-da9a05cc3ebd

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[42e8f1f](https://github.com/o3de/o3de/commit/42e8f1f66373a0ea995a564b5ff7500df7fe9bab)

**Desktop:**
- Device: PC
- OS: Windows
- Version: 11
- CPU: Ryzen 5600H
- GPU: NVidia RTX 3070
- Memory: 16GB

**Comment by cgalvan** [comment]
This has been fixed with the change notify fix: https://github.com/o3de/o3de/pull/16545
