### ISSUE TITLE
Multiple concurrent Linux Server Launchers attempt to write to the same Server.log file

### ISSUE THREAD

**Issue by SelfishOlex** [o3de/o3de#16505]
**Describe the bug**
Multiple concurrent Linux Server Launchers attempt to write to the same Server.log file

**Assets required**
A multiplayer template project.

**Steps to reproduce**
1. Launch multiple server launchers
2. Check user/log Server.log files
3. There should be multiple Server.log, Server(1).log, etc.

**Expected behavior**
There should be multiple Server.log, Server(1).log, etc. for multiple concurrent server launchers.

**Actual behavior**
On Linux, only a single Server.log appears.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
8cd532dcd5e8dc02f2eecd30c05588d6dbb22f80

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 20.04

**Comment by lumberyard-employee-dm** [comment]
We source the "Server.log" file name from the UnifiedLauncher Server.cpp [GetLogFilename](https://github.com/o3de/o3de/blob/development/Code/LauncherUnified/Server.cpp#L22-L25) function which is just
return "@log@/Server.log";
We pass that to CrySystem SystemInit where it tries to make sure the log file name is unique if it can detect that multiple instances of an application is running inside of the [GetUniqueLogFileName](https://github.com/o3de/o3de/blob/development/Code/Legacy/CrySystem/SystemInit.cpp#L520-L550) function.
However looking at the logic for [GetApplicationLogInstance](https://github.com/o3de/o3de/blob/development/Code/Legacy/CrySystem/SystemWin32.cpp#L161-L180) it always returns an instance number of 0 if the platform is not Windows.
Therefore non-Windows platforms will use the same log filename, while Windows abuses  of [CreateMutexW](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createmutexw) function name argument to create some kind of shared memory check for the application instance.
