### ISSUE TITLE
DPE Inspector: In Reflection Probe component Inner Extents parameters can exceed upper limit and Show Visualization flag has no effect

### ISSUE THREAD

**Issue by LB-KacperBieniek** [o3de/o3de#16511]
**Describe the bug**
When DPE is enabled it is possible to exceed the upper limit (defined by _Box Shape_ component _Dimensions_) of the _Height_, _Length_, and _Width_ parameters of _Reflection Probe_ component. Additionally, the _Show Visualization_ flag does not have any visual effect. When DPE is disabled the upper limits are applied correctly, and the _Show Visualization_ flag hides/shows the _Reflection Probe_ in the viewport as expected.
As a side note, changing any of the _Box Shape Dimensions_ sets the _Inner Extents_ parameters to proper maximum values if previously they exceeded the upper limit.

This issue is active on both Windows and Linux.

**Steps to reproduce**
1. Create an Entity and add the _Reflection Probe_, and _Box Shape_ components to it.
2. Make sure DPE is disabled (enter `ed_enableDPE 0` in the _Console_).
3. Verify the limits of _Height_, _Length_, and _Width_ parameters (they upper limit should be the same as _Box Shape Dimensions_).
4. Verify that the _Show Visualization_ flag works properly.
5. Enable DPE (enter `ed_enableDPE 1` in the _Console_).
6. Repeat step 3 and 4.

**Expected behavior**
The upper limit of _Height_, _Length_, and _Width_ parameters is defined by _Box Shape_ component _Dimensions_. The _Show Visualization_ flag shows/hides the _Reflection Probe_ in the viewport.

**Actual behavior**
There is no upper limit for _Height_, _Length_, and _Width_ parameters. The _Show Visualization_ flag does nothing.

**Video**

https://github.com/o3de/o3de/assets/87059746/2bcb0664-74f9-47cc-aefe-e741df2ca893

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[1ed05c8](https://github.com/o3de/o3de/commit/1ed05c8f21ebe203712128f1e473dc9bc7d7a4ab)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 11
- CPU: Ryzen 5600H
- GPU: NVidia RTX 3070
- Memory: 16GB

**Comment by cgalvan** [comment]
This was fixed by the numeric editor attribute fixes: https://github.com/o3de/o3de/pull/16471 and https://github.com/o3de/o3de/pull/16521

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development (https://github.com/o3de/o3de/commit/ec22e96a90392793025b6b961aa228e122612ff6).
