### ISSUE TITLE
DPE Inspector: Advanced Settings for FastNoise Gradient component doesn't work

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#16527]
**Describe the bug**
Changing FastNoise Advanced Settings has no effect. This issue occurs only with DPE Inspector enabled. The issue can be observed in the component's Previewer as well as in the Viewport on Vegetation or Terrain setup.

Please note that the issue occurs on Windows and Linux platform.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Create a new entity.
2. Add a FastNoise Gradient component to the created entity.
3. Add all required components that Entity Inspector asks for.
4. Enable DPE Inspector via `ed_enableDPE 1` command in the console.
5. Under FastNoise Advanced Settings change available settings.

**Expected behavior**
Changing FastNoise Advanced Settings has result in component's Previewer and in the Viewport.

**Actual behavior**
Changing FastNoise Advanced Settings has no visible result.

**Screenshots/Video**
https://github.com/o3de/o3de/assets/86952318/c420164f-cfcf-417c-a966-ba42209af10d

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
d44c577

**Desktop/Device:**
- Device: PC
- OS: Ubuntu
- Version: 20.04
- CPU: AMD Ryzen 7 3800X 8-Core Processor
- GPU: AMD Radeon RX 5700 XT
- Memory: 16 GB

**Comment by alexmontAmazon** [comment]
fixed by https://github.com/o3de/o3de/pull/16545

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (1ea0a41) build.
