### ISSUE TITLE
DPE Inspector: Preview (Inbound) property in Gradient components does not contain a preview

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16523]
**Describe the bug**
*Preview (Inbound)* property that can be found in multiple *Gradient* components does not contain a preview if DPE is enabled. It should be noted that the *Preview (Inbound)* is not the same property as the *Preview*, and that *Preview* property is not affected by this issue (preview is displayed).

Affected components are:
* *Dither Gradient Modifier*
* *Gradient Mixer*
* *Invert Gradient Modifier*
* *Levels Gradient Modifier*
* *Posterize Gradient Modifier*
* *Smooth-Step Gradient Modifier*
* *Threshold Gradient Modifier*

**Steps to reproduce**
1. Execute `ed_enableDPE 1` command in the *Console*.
2. Create an entity and add one of the components listed in the description to it.
3. Select the component and find the *Preview (Inbound)* property.

**Expected behavior**
*Preview (Inbound)* contains a preview.

**Actual behavior**
*Preview (Inbound)* does not contain a preview.

**Video**

https://github.com/o3de/o3de/assets/86952082/52aaa196-d8e3-45c7-be7a-467837f26866

**Found in Branch**
Development (4b68b1f)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
4b68b1f53e5a0902752c685f17baf0771189de0d

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.2 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by lsemp3d** [comment]
Duplicates #16508

**Comment by LB-ArturZieba** [comment]
Confirming the issue has been closed.
