### ISSUE TITLE
DPE Inspector: Modifying Tint parameters of Bloom component when DPE is enabled is not immediately represented in viewport

### ISSUE THREAD

**Issue by LB-KacperBieniek** [o3de/o3de#16520]
**Describe the bug**
Editing _Tint_ parameters of _Bloom_ component when DPE is enabled does not change anything in the viewport. Once the changes are made and user changes either _Threshold_, _Knee_, _Intensity_, or disables and enables _Bloom_, then the changes are applied immediately and are visible in the viewport.
The issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Create a new level.
3. Create an Entity and add the _Bloom_ and _PostFX Layer_ components to it.
4. In the _Bloom_ component _Enable Bloom_ and set _Intensity_ to around 5 for better visibility.
5. Make sure DPE is disabled (enter `ed_enableDPE 0` in the _Console_).
6. Change all five of the _Tint_ parameters and verify their effect in the viewport.
7. Enable DPE (enter `ed_enableDPE 1` in the _Console_).
8. Repeat step 6.

**Expected behavior**
The changes are reflected in the viewport.

**Actual behavior**
While DPE is enabled the changes do not take effect.

**Video**

https://github.com/o3de/o3de/assets/87059746/372bede5-a9f0-4df1-9384-95533c73d367

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[74f49c8](https://github.com/o3de/o3de/commit/74f49c880d6e9a36f2e7dde5683e1a4b83fbbadb)

**Desktop/Device:**
- Device: PC
- OS: Linux
- Version: Ubuntu 22.04.2 LTS
- CPU: Ryzen 5600H
- GPU: NVidia RTX 3070
- Memory: 16GB

**Comment by LB-ArturZieba** [comment]
It should be noted that this also occurs on the *Kernel Size* properties (verified on the Development (c43aa0f) build).

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed on the Development (1ea0a41) build.
