### ISSUE TITLE
Project Centric Script References Engine Centric Script

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#16536]
**Describe the bug**
The project centric exporter script helper comment uses the engine-centric script

**Steps to reproduce**
1. View https://github.com/o3de/o3de/blob/9a2b52c02f26e20d6e1ed808d17e8e8fbfc38d0b/scripts/o3de/ExportScripts/export_standalone_monolithic_project_centric.py#L30

**Expected behavior**
Example invocation comment should refer to the script that's open (export_standalone_monolithic_project_centric.py) 

**Actual behavior**
Script refers to export_standalone_monolithic.py

**Found in Branch**
development

**Comment by tkothadev** [comment]
As of latest release this export script doesn't exist anymore. Closing this issue as outdated.
