### ISSUE TITLE
Unassigning a Parent entity property from an entity within prefab produces warnings/error and cannot be reversed

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16541]
**Describe the bug**
If *Parent entity* property in the *Transform* component is unassigned from an entity that is within a prefab, multiple warnings and an error will be printed to the *Console*:
```
[Warning] (Prefab) - Some of the patches were not successfully applied.
[Error] (Prefab) - PrefabUndoUpdateLink::Capture - Could not get the link.
[Warning] (Prefab Serialization) - The target for "replace" operation doesn't exist.
 Reason: The operation has halted during a merge operation for '/0' because a field or element has an invalid value.
```

It should also be noted that performing *Undo*/*Redo* actions does not revert this, entity will remain unassigned from the prefab.

**Steps to reproduce**
1. Create an entity.
2. Create a prefab from the entity created in step 1.
3. Select the entity within the prefab.
4. In the *Inspector* click the X button on the right of the *Parent entity* to unassign it.

**Expected behavior**
Entity is unassigned from the prefab and no warnings/errors are produced in the *Console*.

**Actual behavior**
Entity is unassigned from the prefab, but multiple warnings and an error is printed to the *Console*. Additionally this action cannot be reverted.

**Video**

https://github.com/o3de/o3de/assets/86952082/8c9846c9-f493-46b7-9b66-dc65880ecf8c

**Found in Branch**
Development (9a2b52c)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
9a2b52c02f26e20d6e1ed808d17e8e8fbfc38d0b

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.2 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by loherangrin** [comment]
The issue can still be reproduced in `stabilization/2409`, but the editor now crashes when the first `Undo` action is requested. I have reported a related error for children in issue #18052 .

**Comment by nick-l-o3de** [comment]
Fixed in Dev and stabilization
