### ISSUE TITLE
Deprecate AreaLightRequestBus::SetIntensity(float intensity, PhotometricUnit intensityMode)

### ISSUE THREAD

**Issue by TheOneAbis** [o3de/o3de#16553]
## Deprecated APIs

AZ::Render::AreaLightRequestBus::SetIntensity(float intensity, PhotometricUnit intensityMode)

## Alternatives APIs

AZ::Render::AreaLightRequestBus::SetIntensityAndMode(float intensity, PhotometricUnit intensityMode)

## Last Release

stabilization/2305

## Additional Context
Add some information about the reasons for the deprecations

EBuses do not work well with methods that have multiple overloads. There are workarounds, but these can be involved and may require extra boilerplate code. Separating the 2 SetIntensity() methods in the AreaLightRequestBus explicitely will solve this issue.

**Comment by moudgils** [comment]
Please follow the steps in this document and close this issue once resolved - https://github.com/o3de/community/blob/main/guides/o3de-deprecation-guidelines.md
