### ISSUE TITLE
Script Canvas: Certain menu options are active when no graph is present or nodes are either not present or not selected 

### ISSUE THREAD

**Issue by LB-KacperBieniek** [o3de/o3de#16599]
**Describe the bug**
Some menu options in the Script Canvas tool are active despite circumstances not being appropriate. Here is the list of options with reasons as to why they should be grayed out and not active:
`File` > `Save` - active despite no graph being opened
`File` > `Save As...` - active despite no graph being opened
`Edit` > `Align` - all options are active despite no nodes being present in the graph
`Edit` > `Select` - all options are active despite no nodes being present in the graph
`Edit` > `Clear Selection` - active despite nothing being selected
`Edit` > `Enable Selection` - active despite nothing being selected
`Edit` > `Disable Selection` - active despite nothing being selected
`View` > `Show Selection` - active despite nothing being selected
`View` > `Go To` - both options are active despite nothing being selected

The issue is active on both Windows and Linux. It also occurs on both Development and Stabilization/2310 branches.

**Steps to reproduce**
1. Open Script Canvas tool.
2. Note that `File` > `Save` and `File` > `Save As...` options are available.
3. Create a new empty graph.
4. Note that the remaining options from issue description are available. 

**Expected behavior**
Script Canvas menu options gray out under appropriate circumstances.

**Actual behavior**
Script Canvas menu options are not grayed out despite appropriate circumstances.

**Video**

https://github.com/o3de/o3de/assets/87059746/ea6444ad-33dd-4de8-8fe8-5db22c591f0a

**Found in Branch**
Development
Stabilization/2310

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Development: [b94667f](https://github.com/o3de/o3de/commit/b94667fcf56b0af11f94632b71bbedc64ae6536e)
Stabilization/2310: [d629db9](https://github.com/o3de/o3de/commit/d629db9b5b8e249cc58069fea2bcceeb50468557)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Ryzen 5600H
 - GPU NVidia RTX 3070
 - Memory 16GB

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development ([fc7f51a](https://github.com/o3de/o3de/commit/fc7f51a5748612eb069ec4623908311e2af99915)).
