### ISSUE TITLE
Script Canvas: Align shortcuts do not work

### ISSUE THREAD

**Issue by LB-KacperBieniek** [o3de/o3de#16600]
**Describe the bug**
Shortcuts for Align Top, Align Bottom, Align Left, and Align Right options from Edit > Align menu do not work. Choosing the options manually from the menu, or by using the buttons on top of the graph works as expected.

The issue is active on both Windows and Linux. It also occurs on both Development and Stabilization/2310 branches.

**Steps to reproduce**
1. Open Script Canvas tool.
2. Create a new empty graph.
3. Populate the graph with a couple of nodes and displace them.
4. Select all nodes and align them using a shortcut (Shift+Up, Shift+Down, Shift+Left, Shift+Right).

**Expected behavior**
All selected nodes are aligned accordingly to the pressed shortcut.

**Actual behavior**
Align shortcuts do not work.

**Video**

https://github.com/o3de/o3de/assets/87059746/7e8e5954-e1ee-4acc-8ee9-18ce6d32edda

**Found in Branch**
Development
Stabilization/2310

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Development: [b94667f](https://github.com/o3de/o3de/commit/b94667fcf56b0af11f94632b71bbedc64ae6536e)
Stabilization/2310: [d629db9](https://github.com/o3de/o3de/commit/d629db9b5b8e249cc58069fea2bcceeb50468557)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Ryzen 5600H
 - GPU NVidia RTX 3070
 - Memory 16GB

**Comment by l-sempe** [comment]
@AMZN-daimini @cgalvan is this an action manager issue?

**Comment by LB-KacperBieniek** [comment]
Issue verified as fixed on latest Development ([361fe2f](https://github.com/o3de/o3de/commit/361fe2feaa2d0ef1857428b4626679b5aed1612f)).
