### ISSUE TITLE
Linux: AssetBundler Fails to launch on Linux

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#16603]
**Describe the bug**
Asset Bundler fails to launch on Linux if there exists a user.cfg in the Cache folder.

**Assets required**
N/A

**Steps to reproduce**
1. On Linux, create a user.cfg and add a simple line like:
   ```ed_useNewCameraSystem = true```
2. Launch Asset Processor and make sure that the `user.cfg` file is processed and copied to the Cache/linux folder
3. Launch AssetBundler

**Expected behavior**
The AssetBundler launches with no issue

**Actual behavior**
An error popup appears saying that a read failed for 'user.cfg'

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
d3214da857efa6fe875c6c29d72a1eea92099f4c

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Linux / Ubuntu 22.04
 - CPU N/A
 - GPU N/A
 - Memory [16GB]

**Comment by lumberyard-employee-dm** [comment]
Isn't this issue fixed @spham-amzn ?

**Comment by spham-amzn** [comment]
yes, i will close it
