### ISSUE TITLE
Linux: Script Canvas: Scanning for graphs to upgrade in Upgrade Graphs tool crashes the Editor

### ISSUE THREAD

**Issue by LB-KacperBieniek** [o3de/o3de#16623]
**Describe the bug**
Trying to scan for graphs to upgrade by using the _Upgrade Graphs_ tool from the _Script Canvas_ results in Editor crash.

The issue is active only on Linux 22.04 when using the latest Stabilization/2310 github branch. Using either latest Stabilization/2310 installer acquired from https://o3debinaries.org/stabilization-2310/Latest/Linux/O3DE_latest.deb or Linux 20.04 with github branch did not reproduce the issue, hence the priority set to major.

Please refer to the attached Video and Editor.log for more information. Additionally, note that the crash.log and crash.dmp were not generated at all.

**Steps to reproduce**
1. Open _Script Canvas_ tool.
2. Go to _Tools_ > _Upgrade Graphs_.
3. Press the _Scan_ button.

**Expected behavior**
_Upgrade Graphs_ tool scans for graphs to upgrade.

**Actual behavior**
Editor crashes.

**Video**

https://github.com/o3de/o3de/assets/87059746/70c5cedb-bb56-4633-a305-9586141b0f71

**Found in Branch**
Stabilization/2310

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Stabilization/2310: [4f0627b](https://github.com/o3de/o3de/commit/4f0627b26ff41ada410ff4a222c2e1e2bb6332db)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 22.04.2 LTS
 - CPU Ryzen 5600H
 - GPU NVidia RTX 3070
 - Memory 16GB

**Additional context:**
[Editor.log](https://github.com/o3de/o3de/files/12463817/Editor.log)

**Comment by lsemp3d** [comment]
Could not reproduce on latest development commit [21c1414](https://github.com/o3de/o3de/commit/21c1414)
