### ISSUE TITLE
WWise Sound Doesn't Work in Monolithic Release Packages

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#16638]
Sound doesn't work in release packaged builds unless changing LY_WWISE_INSTALL_PATH to be the SDK path, not the install folder.

**Steps to reproduce**
1. Create a release package for a game that uses sound fx (example is using multiplayer sample)

```
D:\prj\o3de\scripts\o3de.bat export-project -es D:\prj\o3de\scripts\o3de\ExportScripts\export_source_built_project.py --project-path D:\prj\multiplayersample\ --log-level INFO --output-path D:\MPSExport --build-tools --config release --archive-output zip --seedlist D:\prj\multiplayersample\AssetBundling\SeedLists\BasePopcornFxSeedList.seed --seedlist D:\prj\multiplayersample\AssetBundling\SeedLists\GameSeedList.seed --seedlist D:\prj\multiplayersample\AssetBundling\SeedLists\VFXSeedList.seed -assets --no-unified-launcher
```

2. Open D:\MPSExport and run the GameLauncher and so to a place there should be sound.

**Expected behavior**
SoundFx are playing

**Actual behavior**
No sound

**Work around**
Change "LY_WWISE_INSTALL_PATH " to be the SDK path, not the Wwise install path...
NO `C:\Program Files (x86)\Audiokinetic\Wwise 2021.1.1.7601\`
YES `C:\Program Files (x86)\Audiokinetic\Wwise 2021.1.1.7601\SDK`

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
commit 1bafd915da6913a3149ca540f33cc416b1d657b4
Thu Aug 24 15:19:10 2023

**Comment by drakeredwind01** [comment]
Would this be a `sig-build` or `sig-release` ?
after it's figured could remove `needs-sig` and `needs-triage` and replace with `triage/accepted`

**Comment by AMZN-Gene** [comment]
Looking at cmake script I don’t think my work around is correct. I must have done something different… maybe just needed to rescan AssetProcessor? But I’m not sure why the sound would work in profile of the sound bank wasn’t processed. Either way, closing until there’s a better repro
