### ISSUE TITLE
DPE Inspector: Buttons' texts are missing from various components

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#16656]
**Describe the bug**
With the DPE flag enabled, multiple components lack text inside their buttons. The following buttons and components are affected:
* "Add non-uniform scale button" (e.g. Transform component)
* "Edit" button (e.g. PhysX Mesh Collider component, Axis Aligned Box Shape component)
* "Generate/Manage Source Materials..." button (e.g. Material component)
* "Create New Image..." button (e.g. Image Gradient component)
* "Generate Random Seed" button (e.g. Random Noise Gradient component)
* "Bake image" button (e.g. Gradient Baker component)
* "Bake Textures button (e.g. Diffuse Probe Grid component)

The issue does occur on both Linux and Windows versions of the Editor.

**Steps to reproduce**

1. Launch the Editor and create or open any level.
2. Enable DPE in Editor by inputting `ed_enableDPE 1` command in the console.
3. Select any entity.
4. Observe the Transform component (or any other component mentioned in the description).

**Expected behavior**
Buttons inside the components contain text explaining their function.

**Actual behavior**
Buttons inside the components lack text explaining their function.

**Screenshots/Video**
![DPE_MissingButtonsTexts](https://github.com/o3de/o3de/assets/86953659/b1efb6e6-0a8f-47e1-88fc-541cbaaf1d6b)

https://github.com/o3de/o3de/assets/86953659/1c4e9eeb-4762-4a6a-ae82-f9d6716e6849

**Found in Branch**
Stabilization/2310

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[7aabf7f](https://github.com/o3de/o3de/commit/7aabf7f141c3fc20a0f600f028e74d197486b47b)

**Desktop/Device**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by alexmontAmazon** [comment]
Assigning to @lumberyard-employee-dm , as he's already looking at this

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed on the Stabilization/2310 ([bc8eb66](https://github.com/o3de/o3de/commit/bc8eb66f885cfa99a444703792482f169692ffdc)) branch.
