### ISSUE TITLE
DPE Inspector: Channel Mixing properties of HDR Color Grading component are empty

### ISSUE THREAD

**Issue by LB-KacperBieniek** [o3de/o3de#16683]
**Describe the bug**
The Channel Mixing properties of HDR Color Grading component are empty when DPE is enabled. The same properties are visible and can be edited when using RPE.

Issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Create an Entity and add the HDR Color Grading and PostFX Layer components to it.
2. Make sure DPE is disabled (enter `ed_enableDPE 0` in the Console).
3. In the HDR Color Grading component find and try to edit the Channel Mixing properties.
4. Enable DPE (enter `ed_enableDPE 1` in the Console).
5. In the HDR Color Grading component find and try to edit the Channel Mixing properties.

**Expected behavior**
Channel Mixing properties are present and can be edited.

**Actual behavior**
Channel Mixing properties are empty when DPE is enabled.

**Screenshots**
DPE:
![1](https://github.com/o3de/o3de/assets/87059746/f49527c2-d507-4a20-80ac-3413f2463587)
RPE:
![2](https://github.com/o3de/o3de/assets/87059746/086ef9b8-ce34-4951-837a-971420ead39e)

**Found in Branch**
Stabilization/2310

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Stabilization/2310: [bc8eb66](https://github.com/o3de/o3de/commit/bc8eb66f885cfa99a444703792482f169692ffdc)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 11
- CPU: Ryzen 5600H
- GPU: NVidia RTX 3070
- Memory: 16GB

**Comment by LB-ArturZieba** [comment]
It should be noted that this issue was also observed on the *Cloth* component on the Stabilization/2310 (c7260f4) branch.

**Comment by cgalvan** [comment]
> It should be noted that this issue was also observed on the _Cloth_ component on the Stabilization/2310 ([c7260f4](https://github.com/o3de/o3de/commit/c7260f4dd5934ccdf2657bc1114061c85383ec73)) branch.

Thanks, I will fix those as well!

**Comment by LB-KacperBieniek** [comment]
Issue verified as fixed on Stabilization/2310 ([13f3cbe](https://github.com/o3de/o3de/commit/13f3cbe9e6acd76e5101c0c9d845c3baf986c4b5)) branch. During verification we encountered a new issue with HDR Color Grading component: https://github.com/o3de/o3de/issues/16739
