### ISSUE TITLE
Launching Stabilization/2310 installer causes Microsoft Defender SmartScreen warning

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16682]
**Describe the bug**
Downloading Stabilization/2310 installer from https://o3debinaries.org/stabilization-2310/Latest/Windows/o3de_installer.exe and running it causes Microsoft Defender SmartScreen warning to popup.

Please note that this does not occur on https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe installer.

**Prerequisites**
Windows Stabilization/2310 installer: https://o3debinaries.org/stabilization-2310/Latest/Windows/o3de_installer.exe

**Steps to reproduce**
1. Launch o3de_installer.exe mentioned in **Prerequisites**.

**Expected behavior**
Installer launches properly.

**Actual behavior**
Microsoft Defender SmartScreen warning pops up.

**Video**

https://github.com/o3de/o3de/assets/86952082/be734130-e7f6-45d0-9b6b-0bd12df2e97f

**Found in Branch**
Stabilization/2310 (bc8eb66)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
bc8eb66f885cfa99a444703792482f169692ffdc

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by Ulrick28** [comment]
This happens with stabilization often. I'll start an investigation into this, but likely just a credentials issue.

**Comment by amzn-changml** [comment]
I've regenerated the installer and it's displaying a valid digital signature now. Will be looking into starting up the codesigning automation in parallel with the installer generation.

**Comment by LB-ArturZieba** [comment]
Closing the issue. https://o3debinaries.org/stabilization-2310/Latest/Windows/o3de_installer.exe downloaded 9/12/2023 at 8:10AM GMT+2 does not cause Windows SmartScreen to popup and contains a Digital Signature in the file's properties window.
