### ISSUE TITLE
Linux: Project Manager (o3de) running from a Snap install does not open any log file

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#16697]
**Describe the bug**
When running `o3de` from a snap install, during any build or error, when clicking on 'Show Logs', nothing happens. However, when running `o3de` from a source build, the 'Show Logs' button works and displays the requested log file.

**Assets required**
N/A

**Steps to reproduce**
1. Install O3DE from the snap binary
2. Create a new Project  'NewProject' ( 'New Project'->'Create New Project' )
3. Leave 'NewProject' and the rest as default. Select 'Default Template' and click 'Create Project'
4. A message box saying "NewProject project likely needs to be rebuilt'. Click OK
5. Locate the 'NewProject' and click on 'Build Project' -> 'Build Now'
6. Click on 'Yes' when asked "Ready to build 'NewProject'?"
7. While the project is building, click on 'Show logs'

**Expected behavior**
A new text editor/viewer window will popup showing the log file

**Actual behavior**
Nothing, no response

**Screenshots/Video**

**Found in Branch**
stabilization/2310

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/bc8eb66f885cfa99a444703792482f169692ffdc

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 22.04
 - CPU N/A
 - GPU N/A
 - Memory 16GB

**Additional context**

**Comment by lumberyard-employee-dm** [comment]
It looks like the Project Manager Log file path is set in [Application.cpp](https://github.com/o3de/o3de/blob/8ffecc04d13d41f04c847ba060d4e4d70ecc3ce3/Code/Tools/ProjectManager/Source/Application.cpp#L47-L48) for the Project Manager.
Is that correct @AMZN-alexpete ?
I am wondering if because the SNAP package is immutable and the logs are written to a path such as `~/.o3de/Logs` that opening the log file fails and therefore nothing gets output.

**Comment by spham-amzn** [comment]
I believe this is the issue:
https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1876237

The logs are written to the ~/O3DE/Projects/NewProject/build/linux/CMakeFiles/CMakeProjectBuildError.log so the immutable path is not the issue.

**Comment by AMZN-alexpete** [comment]
By default the logs should be written into the users home folder like you mentioned so I would think it would have no issue writing there unless o3de inside a snap is not getting run as that user, but that seems odd that snaps get run by a user without access to the user folder.

**Comment by spham-amzn** [comment]
The issue is not related to the log file location, according to the bug, it looks related to the fact that the [file descriptor](https://github.com/qt/qtbase/blob/5.13/src/platformsupport/services/genericunix/qgenericunixservices.cpp#L202) is opened with `O_PATH`, and when its passed through the `QDBusConnection`, it is failing, maybe because the application `o3de` is running within the snap containment which is read-only.
