### ISSUE TITLE
PhysX Mesh collider fails when paired with articulation link

### ISSUE THREAD

**Issue by jhanca-robotecai** [o3de/o3de#16711]
**Describe the bug**
It is possible to pair `PhysX Mesh Collider` with `PhysX Articulation Link`, however, mesh is not imported correctly and the collider has a different shape than expected. 

**Assets required**
PhysX 5 enabled in O3DE
PhysX Articulation Link enabled

**Steps to reproduce**
1. Enable `PhysX 5` (adding -DAZ_USE_PHYSX5=ON to the cmake configuration command) 
2. Enable `PhysX Articulation Lilnk` (adding the setting Amazon/Physics/EnableReducedCoordinateArticulations set to `true` in any .setreg file).
3. Create new entity
4. Add `PhysX Mesh Collider` component and load mesh, I used: [suzanne.zip](https://github.com/o3de/o3de/files/12608298/suzanne.zip)
5. Add required component: `PhysX Articulation Link`
6. Start simulation

**Expected behavior**
Collider mesh looks as expected 

**Actual behavior**
Part of the collider mesh is missing

**Screenshots/Video**
I created two entities: one with `PhysX Dynamic Rigid Body` and one with `PhysX Articulation Link`. The first one looks as expected, the latter not.
![image](https://github.com/o3de/o3de/assets/134940295/3b55b352-fad9-4634-a066-32838d3097d9)

The video presenting game mode:
[Screencast from 14.09.2023 13:18:41.webm](https://github.com/o3de/o3de/assets/134940295/a73e4edd-32a8-486a-a59e-7c2bd9f6a068)

**Found in Branch**
`stabilization/2310`

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
55d6e4bee69752219f8562d2be34ad769c03989b

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu
 - Version 22.04
 - CPU Intel i7-12700H
 - GPU Nvidia RTX 3070
 - Memory 32 GB

**Additional context**

**Comment by michalpelka** [comment]
Note that is present when collider mesh is decomposed.

**Comment by jhanca-robotecai** [comment]
I can confirm the issue is fixed now.
