### ISSUE TITLE
Bug Report: Material Canvas BasePBR/StandardPBR immediately crashes window and Linux PC freezing this is not good

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#16735]
**Describe the bug**
Small or large nodes in Material Canvas often crash the window and even freeze the PC this is not good for Linux

**Steps to reproduce**
1. Open the Material Canvas
2. Click any BasePBR or StandardPBR
3. Add node Bool or UV any connection BasePBR
4. The window often crashes and even slows down for Linux

**Screenshots/Video**

https://github.com/o3de/o3de/assets/17591539/f448c566-3aa4-410a-a175-f6303727c66f

https://github.com/o3de/o3de/assets/17591539/2b8af708-779f-4c78-a4a2-4798d64cbcc2

**Found in Branch**
Stabilization-2310 (9/16/23)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
4ccd18c446dbce1f748f64f0cbb2f8d56b6fbdbc

**Desktop/Device (please complete the following information):**
 - Device: Linux
 - OS: Fedora
 - Version 37
  - CPU AMD Ryzen 3 3100
 - GPU AMD RT 5500 XT (8GB)
 - Memory 16GB

**Additional context**
[MaterialCanvas.log](https://github.com/o3de/o3de/files/12640292/MaterialCanvas.log)

**Comment by drakeredwind01** [comment]
could be sig-buid, sig-network, sig-graphics-audio,
