### ISSUE TITLE
DPE Inspector: Reflection Probe component's Exposure sliders do not work consistently

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16742]
**Describe the bug**
If `ed_enableDPE` is set to `true`, then *Exposure*/*Bake Exposure* property sliders on the *Reflection Probe* component work inconsistently. The sliders either defocus the component when dragged, or reset and set the properties to unexpected values.

**Steps to reproduce**
1. Execute `ed_enableDPE 1` command in the *Console*.
2. Create an entity, then add *Reflection Probe* and *Box Shape* component to it.
3. Adjust *Exposure* and *Bake Exposure* sliders by dragging them or clicking on the slider's line.

**Expected behavior**
Slider responds correctly to the users input.

**Actual behavior**
Slider either defocuses the component on dragging, or resets with setting a value in the property.

**Videos**

https://github.com/o3de/o3de/assets/86952082/8bbeb180-758b-4517-bca3-176932c91c8f

https://github.com/o3de/o3de/assets/86952082/cc8e081a-0afa-4267-8646-abf4ab73f3d3

**Found in Branch**
Stabilization/2310 (13f3cbe)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
13f3cbe9e6acd76e5101c0c9d845c3baf986c4b5

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.3 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by alexmontAmazon** [comment]
this occurs because the patch generation code attempts to replace the entire Settings sub-tree when the slider changes. I'm going to see if the the opaque values change fixes this as well...
