### ISSUE TITLE
Editor wont launch along side shaders fail to build.

### ISSUE THREAD

**Issue by TheTopHat26** [o3de/o3de#16774]
**Context**
I downloaded O3DE using the windows installer made my first project to try to get familiar with the editor.  After creating and compiling the project the editor won't run at all no matter what. **i found another issue about the editor and ran the editor with the right parameters to no avail.** If the provides screenshots aren't enough please say so.

**Screenshots**

![Zrzut ekranu 2023-09-21 203321](https://github.com/o3de/o3de/assets/115375073/8a675b0f-2754-4fad-bcda-14b5e84d28ee)
![Zrzut ekranu 2023-09-21 203329](https://github.com/o3de/o3de/assets/115375073/fa116304-f155-4e48-8d5f-707c7ee66aaa)
![Zrzut ekranu 2023-09-21 203341](https://github.com/o3de/o3de/assets/115375073/159fc226-34a2-423f-a017-9b62793580eb)

If this part of the issue is required or helpful

**PC specs**

Ryzen 9300X
RX580
32GB of ram

**Comment by Zenchuck** [comment]
Avoid pressing the "Build" button in the Project Manager for your first project. Try instead "Open CMake GUI" and press the "Configure" button. I have no technical knowledge but this allowed me to open the editor. It spent ~15 minutes downloading files into my "ThirdParty" folder.

**Comment by TheTopHat26** [comment]
Thank you for the help but that did not do it :/ . I can attempt running o3de on Linux and see if the outcome is the same.

**Comment by byrcolin** [comment]
This looks like a content issue, but it may involve graphics so I added them for visibility.

**Comment by TheTopHat26** [comment]
For context, repairing the install didn't help

**Comment by moudgils** [comment]
Are you able to provide log details from the Asset Processor related to the assets that did not build? In the Asset Processor click on the job that failed and it will show you errors in the "Event Log Details" section. Please paste that here to help us provide leads as to how to repro this locally.

**Comment by TheTopHat26** [comment]
Sure, I'll provide anything i can as soon as soon as i can

**Comment by TheTopHat26** [comment]
![Zrzut ekranu 2023-10-12 202722](https://github.com/o3de/o3de/assets/115375073/2fc3696d-5496-42bb-bd5b-7b575997f298)
![Zrzut ekranu 2023-10-12 202729](https://github.com/o3de/o3de/assets/115375073/c195de6c-d9c0-43cc-9529-e5a566b9ea21)

**Comment by TheTopHat26** [comment]
![Zrzut ekranu 2023-10-12 203052](https://github.com/o3de/o3de/assets/115375073/5d0a34cb-01fb-47ef-9a96-5b4e9fd63c75)
![Zrzut ekranu 2023-10-12 203103](https://github.com/o3de/o3de/assets/115375073/d920cbe6-6965-4109-bce2-0f9bbc3bc24e)

**Comment by TheTopHat26** [comment]
Please tell me if this is what you're looking for

**Comment by moudgils** [comment]
We did upgrade dxc recently which may have caused this. Tagging @jhmueller-huawei to see if he has seen this issue as part of upgrading dxc.

**Comment by TheTopHat26** [comment]
Thank you

**Comment by TheTopHat26** [comment]
Finally in the 23.10 update this has been patched and the editor finally opens!!!
