### ISSUE TITLE
DPE: Elements of sets are not displayed correctly and are read-only

### ISSUE THREAD

**Issue by lewandowskikacper** [o3de/o3de#16770]
**Describe the bug**
When the DPE is enabled, elements of sets become read-only.
Numerical values (`size_t`) are displayed incorrectly (looking random / corrupted).

**Assets required**
Any component with field of type `AZStd::set<size_t>` exposed in Edit Context. 

**Steps to reproduce**

1. Create empty level.
2. Create a new entity, and add component with `AZStd::set<size_t>`
3. Add some elements to the set. 

**Expected behavior**
Added elements are visible in the set. They can be modified. Number of elements is consistent with number of "add" operations.

**Actual behavior**
Value is not added correctly to the set. It is displayed incorrectly, and changes each time the entity is opened in the Inspector.  
With DPE disabled it is visible as 0, regardless of user input during insert. After the first value is inserted, the next "add" operation doesn't add a value.

Numerical values already present in the set (added when DPE was disabled) are displayed incorrectly as well.

**Screenshots/Video**

DPE enabled:
![image](https://github.com/o3de/o3de/assets/138626322/c53db0a5-8b79-48d5-a039-136cd9f37c18)

Note: the index displayed here is always 0, regardless of the number of elements. This window is also scaled incorrectly.
![image](https://github.com/o3de/o3de/assets/138626322/94757f07-1f4e-4ba5-ad5f-b75c2d66e268)

DPE disabled:
This is the same set, the values were preserved when DPE was enabled and are now correctly visible again
![image](https://github.com/o3de/o3de/assets/138626322/9b0aaf2f-e34b-4a32-a3db-0bbc60018ffc)
There is no index displayed:
![image](https://github.com/o3de/o3de/assets/138626322/22666a8a-242a-4025-99fe-5a64515ed904)

**Found in Branch**
[o3de/stabilization2310](https://github.com/o3de/o3de/tree/stabilization/2310) with https://github.com/o3de/o3de/pull/16764 applied.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/pull/16764/commits/53d2071a87236a2ffe252ef59282aafdf00c2cf7

**Desktop/Device (please complete the following information):**
 - Device: AORUS
 - OS: Ubuntu 
 - Version 22.04
 - CPU 12th Gen Intel® Core™ i5-12500H × 16
 - GPU  NVIDIA GeForce RTX 4060 Laptop GPU
 - Memory 64.0 GiB

**Comment by lumberyard-employee-dm** [comment]
Well a set is an immutable structure, so the elements within it can't be modified.

The DPE editor would need some kind of change validation mechanism to check if the user has changed a value that would cause the set the need to re-sort in that case which it current doesn't have.

The Reflected Property Editor itself allowing the set value to change is a bug and can cause data loss if one of the entries in the Set is changed to have the field that it uses for sorting to be the same as another one.
On save only the first field with a key that is seen as equivalent is serialized.

This may not seem like an issue for a `set<int>` where the key is one field.
But for something such as a set of a structure where one of the fields is what is used for sorting, data will be loss.

Such as
```c++
struct EntityPriority
{
    AZ::EntityId m_id;
    int m_orderNumber;
};

using PrioritySet = set<EntityPriority>;
```

In the above case if the operator less than only compares the `m_orderNumber` member, than by setting two entries of "EntityPriority" to the same have the same order number would result in one of them being loss silently.
