### ISSUE TITLE
PostFX Layer component inconsistently crashes the Editor when its Excluded Camera Tags elements are modified and deleted

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16789]
**Describe the bug**
Modifying and deleting elements in the *Excluded Camera Tags* property can inconsistently (it took 1 - 5+ tries on different systems) cause the Editor to crash.

Call Stack from a Windows machine:
```
Call Stack Trace:
25) 00007FFD59F1BD2C (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFD5CA3847D (ntdll) : RtlMoveMemory
23) 00007FFD5CA1F017 (ntdll) : _C_specific_handler
22) 00007FFD5CA33DFF (ntdll) : _chkstk
21) 00007FFD5C9AE456 (ntdll) : RtlFindCharInUnicodeString
20) 00007FFD5CA32DEE (ntdll) : KiUserExceptionDispatcher
19) 00007FFD2722E023 (Qt5Core) : QtSharedPointer::ExternalRefCountData::getAndRef
18) 00007FFD26042751 (Qt5Widgets) : QApplication::notify
17) 00007FFD273917CB (Qt5Core) : QCoreApplication::notifyInternal2
16) 00007FFD26045BB5 (Qt5Widgets) : QApplicationPrivate::sendMouseEvent
15) 00007FFD26090662 (Qt5Widgets) : QSizePolicy::QSizePolicy
14) 00007FFD2608E5FE (Qt5Widgets) : QSizePolicy::QSizePolicy
13) 00007FFD260449A1 (Qt5Widgets) : QApplicationPrivate::notify_helper
12) 00007FFD26043A23 (Qt5Widgets) : QApplication::notify
11) 00007FFD273917CB (Qt5Core) : QCoreApplication::notifyInternal2
10) 00007FFD23F24915 (Qt5Gui) : QGuiApplicationPrivate::processMouseEvent
 9) 00007FFD23F0EE99 (Qt5Gui) : QWindowSystemInterface::sendWindowSystemEvents
 8) 00007FFD273DA84A (Qt5Core) : QEventDispatcherWin32::processEvents
 7) 00007FFD28313799 (qwindows) : qt_plugin_query_metadata
 6) 00007FFD2738DC5F (Qt5Core) : QEventLoop::exec
 5) 00007FFD27390795 (Qt5Core) : QCoreApplication::exec
 4) C:\build\o3de\Code\Editor\CryEdit.cpp (3837) : CryEditMain
 3) C:\build\o3de\Code\Editor\main.cpp (31) : main
 2) D:\github\3p-package-source\package-system\Qt\temp\src\qtbase\src\winmain\qtmain_win.cpp (97) : WinMain
 1) D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288) : __scrt_common_main_seh
```

This issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Create an entity and add *PostFX Layer* component to it.
2. Add ten new elements to the *Excluded Camera Tags* array property.
3. Add some content to the added elements and delete them one by one.

**Expected behavior**
Editor remains stable.

**Actual behavior**
Editor crashes.

**Video, error.log, and error.dmp**

https://github.com/o3de/o3de/assets/86952082/9b07f5de-8bf5-4cff-bdbd-2aa14b165e1d

[error.log](https://github.com/o3de/o3de/files/12700645/error.log)
[error.zip](https://github.com/o3de/o3de/files/12700646/error.zip) - contains `error.dmp` file.

**Found in Branch**
Stabilization/2310 (d380ffa)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
d380ffaa3bdd7b4dad07f882acc856b64b209444

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.3 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by moudgils** [comment]
The call stack suggests the issue is with Editor/Qt/DPE.

**Comment by cgalvan** [comment]
Unable to reproduce this in latest `development` branch with `ed_enableDPEInspector` both enabled and disabled.

**Comment by LB-KacperKapusta** [comment]
Confirming the issue has been closed as it cannot be reproduced as of Development ([fc7f51a](https://github.com/o3de/o3de/commit/fc7f51a5748612eb069ec4623908311e2af99915)).
