### ISSUE TITLE
DPE Inspector: Components can inconsistently disappear when their properties are modified

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16790]
**Describe the bug**
Sometimes when changing properties on a component, the component will disappear. This has been observed on *Levels Gradient Modifier*, *Smooth-Step Gradient Modifier*, *Vegetation Distribution Filter*, *Vegetation Rotation Modifier*, and multiple other components.

Exact cause of this issue could not have been pinpointed, but quickly changing properties usually caused this issue to occur.

This issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Create an entity and add one of the components listed in the description to it (for example *Vegetation Distribution Filter*).
2. Modify all of the component's properties quickly (please refer to the video attached in the **Video** section).

**Expected behavior**
Nothing of note happens.

**Actual behavior**
Component disappears from the entity.

**Video**
Please skip to around 1:20, to see the issue occurring:

https://github.com/o3de/o3de/assets/86952082/251e7034-3f0b-4577-88d9-3887072616d3

**Found in Branch**
Stabilization/2310 (d380ffa)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
d380ffaa3bdd7b4dad07f882acc856b64b209444

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.3 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by cgalvan** [comment]
The component eventually disappears because there were enough patch issues that it eventually fails to deserialize entirely. This has been fixed now that prefab overrides are working properly with https://github.com/o3de/o3de/pull/16817

**Comment by LB-ArturZieba** [comment]
I've applied [#16817](https://github.com/o3de/o3de/pull/16817) changes to Stabilization/2310 ([3707b54](https://github.com/o3de/o3de/commit/3707b549a28229c8501e363943a064d28bb5dab7)) build, rebuilt the engine, attempted to reproduce the issue on all components listed in the description, and it did not occur.

Waiting for the merge to Stabilization/2310 branch and then we'll close the issue.

**Comment by cgalvan** [comment]
Thanks for verifying @LB-ArturZieba ! I've merged the PR now, so I will close this issue.
