### ISSUE TITLE
Asset Processor: "Skip Startup Scan" Affects All Projects

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#16791]
Using O3DE.exe to creating a new project and open editor the cache folder is empty.

**Steps to reproduce**
1. Open an existing project and change the asset processor to "Skip Startup Scan"
2. Open O3DE.exe and create a new project
3. Build new project
4. Open new project editor

**Expected behavior**
The editor opens and asset process processes all the new assets
Skip Startup Scan should be disabled by default and defined per project

**Actual behavior**
Editor fails to open because no assets are processed. 
Looking at Asset Processor, "Skip Startup Scan" is enabled, even though I never set it for this project.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
97322267ebabc07bae61167cd89dbf6fddc1ea24 (HEAD -> upstream/development, upstream/development)
Date:   Fri Sep 22 09:03

**Comment by lumberyard-employee-dm** [comment]
@o3de/sig-content Is the "Skip Startup Scan" setting stored in the Settings Registry or is it using QSettings.
The Settings Registry would be able to have per project configurations of settings.

**Comment by AMZN-Gene** [comment]
Thanks @lumberyard-employee-dm!
This would be good into to add to Asset Processor docs. Searching for "Skip Startup Scan" on o3de.org returns no result. GHI might ultimately be best for searchable documentation :P
