### ISSUE TITLE
Material Editor and Material Canvas does not open on All Gems project

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#16795]
**Describe the bug**
This problem was already reported here [#7113](https://github.com/o3de/o3de/issues/7113), but as per request this new issue was created.

Material Editor and Material Canvas does not open. This issue occurs only on projects with all gems activated. Attempting to launch any of the tools results in information printed in the Editor's console:

```
(MaterialComponent) - Launching Material Editor
(MaterialComponent) - Launching Material Canvas (Preview)
```

However, neither Material Editor or Material Canvas opens.

Launching any of the mentioned tools standalone results in errors.

Please refer to attached video, screenshot and logs for more information.

**Steps to reproduce**
1. Open project with all gems enabled.
2. Open Material Editor or Material Canvas.

**Expected behavior**
Both Material Editor and Material Canvas can be opened.

**Actual behavior**
Both Material Editor and Material Canvas does not open.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86952318/1402f5a0-8fff-4c39-8d74-60ef19db19e0
![material_editor_terminal](https://github.com/o3de/o3de/assets/86952318/c41f3264-cfe5-4e52-ab5d-3cb67da738cc)
[MaterialCanvas.log](https://github.com/o3de/o3de/files/12715209/MaterialCanvas.log)
[MaterialEditor.log](https://github.com/o3de/o3de/files/12715210/MaterialEditor.log)
[material_editor_terminal.txt](https://github.com/o3de/o3de/files/12715279/material_editor_terminal.txt)

**Found in Branch**
Stabilization/2310

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
([08cb981](https://github.com/o3de/o3de/commit/08cb981a46d7a39f8c4badc0c125c18a8b5579c4))

**Desktop/Device:**

- Device: PC
- OS: Ubuntu
- Version: 20.04
- CPU: AMD Ryzen 7 3800X 8-Core Processor
- GPU: AMD Radeon RX 5700 XT
- Memory: 16 GB

**Comment by LB-KacperBieniek** [comment]
Issue verified as fixed on Stabilization/2310 ([a90037a](https://github.com/o3de/o3de/commit/a90037a616801e69d08741870b2d49407a9b8bee)) branch.
