### ISSUE TITLE
Cannot Bundle Assets on Amazon Linux 2023: Pak Files Don't Contain Manifest.XML

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#16869]
Exporting a project on (Amazon Linux 2023) AL2023 fails due to asset bundler not generating any Manifest.xml

**Steps to reproduce**
1. Install a project on AL2023 
2. Export the project
```
 ~/o3de/scripts/o3de.sh export-project -es ~/multiplayersample/ExportScripts/export_mps.py -out ~/MPSExport_x86 -gl -assets -foa -nogame -noserver -nounified -pl linux -cfg release -ll INFO
```
3. Unzip one of the pak files. Ex: _<export_folder>/Cache/linux/engine_linux.pak_

**Expected behavior**
The pak file should contain a manifest.xml

**Actual behavior**
Manifest.xml doesn't exist

**Hack Workaround**
Generate engine.pak and game.pak on Ubuntu and copy them over to the AL2023 package.

**Found in Branch**
development

https://github.com/o3de/o3de/commit/8d89ec32f88357791283da75424e26197bd6a545
October 3rd 2023

**Desktop/Device (please complete the following information):**
Amazon Linux 2023 x86 machine

**Comment by lumberyard-employee-dm** [comment]
Have you tried running the AssetBundlerBatch as an individual command?
I believe the issue might be with the AssetBundlerBatch failing at some point when trying to create the manifest xml


My best guess is the AZ::IO::Archive creation is failing for some reason on Amazon Linux: https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/AssetBundle/AssetBundleComponent.cpp#L406-L407

**Comment by AMZN-Gene** [comment]
Aye, the manifest.xml is failing for sure. Also would be good if it returned an exit code so it was obvious when the export failed.
```
~/multiplayersample/build/tools/bin/profile/AssetBundlerBatch bundles --maxSize 1024 --platform linux --project-path ~/multiplayersample/ --allowOverwrites --outputBundlePath ~/multiplayersample/build/asset_bundling/Bundles/game_linux.pak --assetListFile ~/multiplayersample/build/asset_bundling/AssetLists/game_linux.assetlist

Setting project to ( /home/ec2-user/multiplayersample/ ).
Creating Bundle ( /home/ec2-user/multiplayersample/build/asset_bundling/Bundles/game_linux.pak )...

[ERROR] - ArchiveComponent:
File 'manifest.xml' does not exist inside archive '/home/ec2-user/multiplayersample/build/asset_bundling/Bundles/game_linux.pak'

[ERROR] - AssetBundle:
Failed to extract existing manifest from archive "/home/ec2-user/multiplayersample/build/asset_bundling/Bundles/game_linux.pak".
```

**Comment by lumberyard-employee-dm** [comment]
I guess would have to debug the `AddManifestFilesToBundle` function to figure out why the manifest.xml isn't being added to the file

**Comment by AMZN-Gene** [comment]
Hehe, I found my 'manifest.xml' was saved out to ' 0▒y'
![image](https://github.com/o3de/o3de/assets/32776221/31804329-bccc-4ede-b90e-8ded7b324a8e)

The szRelativePath string_view is wrong.
https://github.com/o3de/o3de/blob/c7d07cc2ad12d2062ad21318e04669642ae753b6/Code/Framework/AzFramework/AzFramework/Archive/NestedArchive.cpp#L141
