### ISSUE TITLE
Save and Align options in Script Canvas are not available from their menus

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#16876]
**Describe the bug**
Save`/`Save As...` and `Align` options from File and Edit menus respectively are not available in Script Canvas. Please note that the node alignment can still be done by using `Shift+Arrow` keyboard shortcut (or using the buttons above the graph), however, for saving the `Ctrl+S` shortcut does not work. Therefore, saving can only be done by closing the graph and using the popup window.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Open the Script Canvas tool.
2. Add at least 2 nodes to the graph.
3. Select the nodes.
4. Go to the `Edit` menu -> `Align` -> `Align Top`/`Align Bottom`/`Align Left`/`Align Right`.
5. Go to the `File` menu -> `Save`/`Save As...`.

**Expected behavior**
The saving and aligning options are available from their menus.

**Actual behavior**
The saving and aligning options are not available from their menus.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/f55fb0ae-1659-4d21-844b-9bc3efc1799a

 
**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[fc7f51a](https://github.com/o3de/o3de/commit/fc7f51a5748612eb069ec4623908311e2af99915)

Device: PC
OS: Windows 10 Pro
Version: 22H2
CPU: AMD Ryzen 5 3600
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 16GB

**Comment by cgalvan** [comment]
This is not a DPE issue. Issue also occurs with the DPE disabled. I've removed the mentions of DPE from this issue.

**Comment by lsemp3d** [comment]
Save is fixed in #16894  I will look into Align

**Comment by lsemp3d** [comment]
Align was fixed in #16882

**Comment by LB-KacperKapusta** [comment]
Align fix was verified in Development ([d5c1fdb](https://github.com/o3de/o3de/commit/d5c1fdb52eb78b91a1b837ca147b657a726a3001)). Save fix is still pending merge.

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development ([7291081](https://github.com/o3de/o3de/commit/72910817cc838ecf3aaae1fc0b2448ead354ee7d)).
