### ISSUE TITLE
Ui Canvas Often Break and Need Touching

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#16879]
I often find myself having to touch UI Canvas files in order to get them to work.
Some cases, the game doesn't crash, but the C++ components on the canvas won't load unless I resave the UI Canvas.
In other cases, the asset crashes.

**Steps to reproduce**
Unfortunately, I don't have good repo steps yet.
The MultiplayerSample HUD sometimes experiences the crash below.

**Expected behavior**
UI Canvas loads and the C++ component Activate() logic is called.

**Actual behavior**
C++ component never activates. Opening the ui canvas and resaving fixes the issue.
Rescanning all assets in Asset Processor doesn't fix the issue.
Product (cache folder) asset was not altered manually

**Found in Branch**
development October 3rd 2023

**Comment by lumberyard-employee-dm** [comment]
It looks like the crash is in ScriptCanvas when a UICanvas is trying to run a Script Canvas graph.

**Comment by AMZN-Gene** [comment]
> It looks like the crash is in ScriptCanvas when a UICanvas is trying to run a Script Canvas graph.

Yes, actually 2 issues here... breaking apart.

**Comment by AMZN-Gene** [comment]
Grabbing latest o3de engine fixes issue.
