### ISSUE TITLE
Snap Installer 23.10: Project configuration fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#16884]
**Describe the bug**
Project configuration fails with the following error:

```
CMake Error at /usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/usr/bin/clang-12"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/home/gpc-592/O3DE/Projects/NewProject/build/linux/CMakeFiles/CMakeScratch/TryCompile-zYjKyO'
    
    Run Build Command(s): /usr/bin/ninja -v cmTC_f28da
    [1/2] /usr/bin/clang-12 -DCMAKE_INTDIR=\"Debug\"  -g -MD -MT CMakeFiles/cmTC_f28da.dir/Debug/testCCompiler.c.o -MF CMakeFiles/cmTC_f28da.dir/Debug/testCCompiler.c.o.d -o CMakeFiles/cmTC_f28da.dir/Debug/testCCompiler.c.o -c /home/gpc-592/O3DE/Projects/NewProject/build/linux/CMakeFiles/CMakeScratch/TryCompile-zYjKyO/testCCompiler.c
    [2/2] : && /usr/bin/clang-12 -g  CMakeFiles/cmTC_f28da.dir/Debug/testCCompiler.c.o -o Debug/cmTC_f28da   && :
    FAILED: Debug/cmTC_f28da 
    : && /usr/bin/clang-12 -g  CMakeFiles/cmTC_f28da.dir/Debug/testCCompiler.c.o -o Debug/cmTC_f28da   && :
    /usr/bin/ld: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/o3de/11/usr/lib/x86_64-linux-gnu/libctf.so.0)
    /usr/bin/ld: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/o3de/11/usr/lib/x86_64-linux-gnu/libbfd-2.38-system.so)
    /usr/bin/ld: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/o3de/11/usr/lib/x86_64-linux-gnu/libbfd-2.38-system.so)
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
```

Please note that this issue occurs only for the .snap installer on Ubuntu 20.04, while using `o3de` and `sudo o3de` in the terminal. On Ubuntu 22.04 the project can be created, configured and built using the same installer. Also on .deb installer, as well as on GitHub build this issue does not occur on Ubuntu 20.04.

Please refer to attached screenshot and logs for more information.

**Steps to reproduce**
1. Open terminal window.
2. Use the `sudo snap install o3de --classic` command to install the O3DE.
3. Write `o3de` in the terminal.
4. In the Project Manager, create a new project.
5. Build the created project.

**Expected behavior**
A project can be built without any issue.

**Actual behavior**
Configuring project fails.

**Screenshots/Video**
![project_manager_terminal_output](https://github.com/o3de/o3de/assets/86952318/207e1034-026b-4457-b224-00411f44fb6b)
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/12868505/CMakeProjectBuildError.log)

**Found in Branch**
Release Installer 23.10

**Desktop/Device:**

- Device: PC
- OS: Ubuntu
- Version: 20.04
- CPU: AMD Ryzen 7 3800X 8-Core Processor
- GPU: AMD Radeon RX 5700 XT
- Memory: 16 GB

**Comment by spham-amzn** [comment]
The default SNAP installation from the snap store supports Ubuntu 22.04. There is a separate SNAP for version 20.04, but the documentation was missed. 
https://www.docs.o3de.org/docs/welcome-guide/setup/installing-linux/#installing-o3de-from-a-snap-package

**Comment by spham-amzn** [comment]
Snap is no longer supported per https://github.com/o3de/rfcs/issues/54
