### ISSUE TITLE
DPE Inspector: Comment component does not handle long text properly

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16908]
**Describe the bug**
If `ed_enableDPEInspector` is enabled and a long text (28 lines of "A lot of text" is used on the attached video) is typed into the *Comment* component, then after reselecting entity with that component, the *Comment* component will not display properly.

It should be noted that this issue occurs on both Windows and Linux, and on the Development (fa9fe53) branch.

**Steps to reproduce**
1. Execute `ed_enableDPEInspector 1` command in the *Console*.
2. Create an entity and add a *Comment* component to it.
3. Enter a long text into the *Comment* component (for example in the video 28 lines of "A lot of text" were pasted in).
4. Deselect the entity and reselect it.

**Expected behavior**
*Comment* component behaves the same as with `ed_enableDPEInspector` disabled.

**Actual behavior**
*Comment* component is not displayed properly, text field is moved to the center of the component, while the rest of the body gets stretched.

**Video**

[DPECommentLongContent.webm](https://github.com/o3de/o3de/assets/86952082/75daeddc-1f74-4d96-8dba-a0cfab2a80fa)

**Found in Branch**
Point-Release/23101 (0d490a2)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
0d490a2b4b5e04fd17edf4850c91f94361d4b836

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.3 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by AMZN-daimini** [comment]
This bug is still active.
