### ISSUE TITLE
DPE Inspector: Opening Script Events file inside the Asset Editor leads to Editor crash

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#16910]
**Describe the bug**
Opening any already existing or creating a new Script Events file inside the Asset Editor leads to a crash if the `ed_enableDPEAssetEditor` is enabled. The issue does not occur with `ed_enableDPEAssetEditor` disabled.

Note that the issue occurs on both Linux and Windows.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Execute the `ed_enableDPEAssetEditor 1` command in the Console.
2. Open the Asset Editor.
3. Go to New -> File -> Script Events.

**Expected behavior**
Script Events file is opened.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/fe09fc30-b24e-4148-9d01-8d911f43ab11

**Found in Branch**
Point-Release/23101
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Point-Release/23101 ([0d490a2](https://github.com/o3de/o3de/commit/0d490a2b4b5e04fd17edf4850c91f94361d4b836))
Development ([fa9fe53](https://github.com/o3de/o3de/commit/fa9fe5340e5cfb2be2e1eeab625c00351d7f3b26))

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 22.04.3 LTS
- CPU: CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Additional context:**
[Editor.log](https://github.com/o3de/o3de/files/13026899/Editor.log)
[error.log](https://github.com/o3de/o3de/files/13026903/error.log)
[error.zip](https://github.com/o3de/o3de/files/13026905/error.zip) (contains the `crash.dmp` file)

**Comment by alexmontAmazon** [comment]
putting into backlog, as DPE-based Asset Editor is very experimental and not currently under development.

**Comment by AMZN-daimini** [comment]
Could not reproduce this in latest development.
