### ISSUE TITLE
DPE Inspector: Certain asset properties do not find compatible assets when selecting them

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16922]
**Describe the bug**
Certain asset properties (for example *Script* property in *Lua Script* component) do not find compatible files if `ed_enableDPEInspector` is enabled. This has been confirmed on the following components:
* *Mesh* - *Model Asset*
* *Lua Script* - *Script*
* *Simple Network Player Spawner* - *Network Spawnable Asset*
Listed components were able to find compatible assets if `ed_enableDPEInspector` was disabled.

However, at least one component - *Script Canvas* - *Source* is not affected by this, meaning that compatible assets were found with 
`ed_enableDPEInspector` both enabled and disabled.

This issue occurs on both Windows and Linux, as well as the Development (https://github.com/o3de/o3de/commit/72910817cc838ecf3aaae1fc0b2448ead354ee7d) branch.

**Steps to reproduce**
1. Execute `ed_enableDPEInspector 1` command in the *Console*.
2. Create an entity and add one of the affected components listed in the description to it (for example *Mesh*).
3. Click the "pick asset" folder button in the *Model Asset* property.

**Expected behavior**
Compatible assets are shown in the *Pick Asset* window.

**Actual behavior**
No assets are shown in the *Pick Asset* window.

**Video**

[DPECertainAssetPropertiesDoNotSeeAssets.webm](https://github.com/o3de/o3de/assets/86952082/8f44c681-758e-40f3-96d1-47eae44a4333)

**Found in Branch**
Point-Release/23101 (55aa477)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
55aa477c9d6ff2eb0277f9f02a00fa53424b9f7e

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.3 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by lumberyard-employee-dm** [comment]
Note: to developer investigating.
The ScriptCanvas Asset Picker is different is for a SourceHandle class. It uses special EditContext attributes to add an Asset Picker edit button to select a ScriptCanvas Asset: https://github.com/o3de/o3de/blob/development/Gems/ScriptCanvas/Code/Editor/Framework/Configuration.cpp#L190-L197

For the other Assets, they use the traditional method of exposing an `AZ::Data::Asset<T>` type through the Edit Context.
That results in the PropertyAssetCtrl widget being used for UI selection of an Asset.
I believe the code that should be invested in that case is the [PropertyAssetCtrl::PopupAssetPicker](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp#L812-L825) function

**Comment by alexmontAmazon** [comment]
in review here:
https://github.com/o3de/o3de/pull/17062
