### ISSUE TITLE
DPE Inspector: Adding more than one element to a Surface Tag array property causes Editor to crash

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16930]
**Describe the bug**
If `ed_enableDPEInspector` is enabled and more than one element is added to a *Surface Tag* array property (for example *Surface Tags To Snap To* property in the *Vegetation Position Modifier*), the Editor will crash. This was reproduced on the following components:
* *Vegetation Position Modifier* - *Surface Tags To Snap To*
* *Gradient Surface Tag Emitter* - *Extended Tags*
* *Mesh Surface Tag Emitter* - *Generated Tags*
* *PhysX Collider Surface Tag Emitter* - *Generated Tags* and *Extended Tags*
* *Shape Surface Tag Emitter* - *Generated Tags* and *Extended Tags*

Call Stack Trace:
```
 9) 00007FFF6D07E237 (KERNELBASE) : UnhandledExceptionFilter
 8) 00007FFF6C91C888 (InProcessClient64) : (function-name not available)
 7) 00007FFF6C91C4D1 (InProcessClient64) : (function-name not available)
 6) 00007FFF6F6954B0 (ntdll) : memset
 5) 00007FFF6F67CA06 (ntdll) : _C_specific_handler
 4) 00007FFF6F6923AF (ntdll) : _chkstk
 3) 00007FFF6F6414B4 (ntdll) : RtlRaiseException
 2) 00007FFF6F690EBE (ntdll) : KiUserExceptionDispatcher
 1) C:\Builds\o3de\Code\Framework\AzCore\AzCore\DOM\DomValue.cpp (339) : AZ::Dom::Value::IsNull
```

This issue occurs on both Windows and Linux, as well as the Development (https://github.com/o3de/o3de/commit/72910817cc838ecf3aaae1fc0b2448ead354ee7d) branch.

It should be noted that on the Development build, after adding one element to a *Surface Tag* array property, the "+" button disappears. Clicking near it causes it to reappear and the issue can be reproduced. This is shown on one of the attached videos.

**Steps to reproduce**
1. Execute `ed_enableDPEInspector 1` command in the *Console*.
2. Create an entity and add any of the components listed in the description along with dependencies to it (for example *Vegetation Position Modifier*).
3. Add two elements to the *Surface Tag* property on added component (for example *Surface Tags To Snap To*).

**Expected behavior**
Editor remains stable.

**Actual behavior**
Editor crashes.

**Videos, Editor.log, error.log, and error.dmp files**
Point-Release:

[DPESurfaceTagElementsCrash.webm](https://github.com/o3de/o3de/assets/86952082/48b323c0-be6b-48b3-a80c-4fad4feb7b97)

Development ("+" disappearing):

https://github.com/o3de/o3de/assets/86952082/61aafe7e-b178-44a4-9276-9453c671b949

[Editor.log](https://github.com/o3de/o3de/files/13067413/Editor.log)
[error.log](https://github.com/o3de/o3de/files/13067436/error.log)
[error.zip](https://github.com/o3de/o3de/files/13067435/error.zip) - Contains `error.dmp`.

**Found in Branch**
Point-Release/23101 (55aa477)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
55aa477c9d6ff2eb0277f9f02a00fa53424b9f7e

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.3 LTS
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by alexmontAmazon** [comment]
In review, here:
https://github.com/o3de/o3de/pull/17011
