### ISSUE TITLE
Bug Report - Spotify logo shows YouTube tooltip

### ISSUE THREAD

**Issue by Fergal-C** [o3de/o3de#16936]
**Describe the bug**
Hovering over the Spotify logo, in the "Follow" section, at the bottom of o3de.org page, displays a YouTube tooltip.

**Screenshot**
![SpotifyYouTube](https://github.com/o3de/o3de/assets/20088633/dcc9bafd-6ac5-45a6-9194-c06f9a408637)

**Steps to reproduce**
1. Scroll to the bottom of the o3de.org page
2. Hover over the Spotify logo in the "Follow" section
3. View the tooltip

**Expected behavior**
Spotify tooltip to appear.

**Actual behavior**
YouTube tooltip appears

**Desktop/Device (please complete the following information):**
 - Windows 10 PC using Microsoft Edge

**Comment by drakeredwind01** [comment]
suggest removing `needs-triage` `needs-sig` and adding `triage/accepted`, and `sig-network`
seems like an easy fix

**Comment by AMZN-daimini** [comment]
This bug belongs to the o3de.org repo
https://github.com/o3de/o3de.org/issues

**Comment by Fergal-C** [comment]
Thanks AMZN-daimini, I have added the issue there.
