### ISSUE TITLE
DPE Inspector: Using Mid Point's slider from ACES Parameters inside the Display Mapper component resets the remaining sliders

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#16938]
**Describe the bug**
Using Mid Point's slider from ACES Parameters inside the Display Mapper component resets the remaining ACES Parameters' sliders when the `ed_enableDPEInspector` and `ed_enableInspectorOverrideManagement`  CVARs are enabled. Please note that the issue does not reproduce on Development ([c8f19bb](https://github.com/o3de/o3de/commit/c8f19bbe664a89ad92007fb7674cb8c6aa165bd9)) branch.

The issue occurs on both Linux and Windows.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Execute the `ed_enableDPEInspector 1` and `ed_enableInspectorOverrideManagement 1` command in the Console.
2. Add the _Display Mapper_ component to an entity.
3. Modify any sliders under _ACES Parameters_ except for the _Mid Point (luminance)_ slider.
4. Use the _Mid Point (luminance)_ slider.

**Expected behavior**
The sliders can be used without issues.

**Actual behavior**
Using the _Mid Point (luminance)_ slider breaks other sliders from _ACES Parameters_ of the _Display Mapper_ component.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/6304afbc-ca7d-4e45-858c-e924e9539ead

**Found in Branch**
Point-Release/23101 

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[55aa477](https://github.com/o3de/o3de/commit/55aa477c9d6ff2eb0277f9f02a00fa53424b9f7e)

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 22.04.3 LTS
- CPU: CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Comment by alexmontAmazon** [comment]
investigating how this could be be different in point release and development...

**Comment by alexmontAmazon** [comment]
we have discovered that this only occurs with the inspector overrides enabled
