### ISSUE TITLE
DPE Inspector: ChangeNotify events aren't being triggered

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#16961]
**Describe the bug**
The ChangeNotify events don't seem to be triggered when editing values in the DPE Inspector.

**Steps to reproduce**
1. Create a level.
2. Add a Terrain World Component to the Level Entity.
3. Change the Min Height to 2048.

**Expected behavior**
A Min Height that is greater than the Max Height should be disallowed (see TerrainWorldComponent.cpp).

**Actual behavior**
Value is accepted with no validation.

**Found in Branch**
point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
426a5f2c4a4312891f20bcc2cf229373307f3204

**Desktop/Device (please complete the following information):**
PC / Windows

**Comment by alexmontAmazon** [comment]
Note: these height checkers are ChangeValidate not ChangeNotify. I'm continuing to explore what's not working here...

**Comment by alexmontAmazon** [comment]
ChangeNotify seems to be firing normally, as tested on the TransformComponent's ParentChangedInspector
