### ISSUE TITLE
Unable to name, rename, move or delete assets from the Asset Browser

### ISSUE THREAD

**Issue by MacGeorges** [o3de/o3de#16998]
**Description the bug**
I am unable to name, rename, move or delete assets from the Asset Browser.

**Assets required**
Just create a new Script Canvas.

**Steps to reproduce**
Steps to reproduce the Name behavior:
1. Create a Script Canvas.
2. Type ne name of your choice.
3. Asset is still named "NewScript"

Steps to reproduce the Rename behavior:
1. Create a Script Canvas.
2. Right Click on newly created Script Canvas
3. Select "Rename asset"
4. Type the name of your choice
5. Asset is still named "NewScript"

Steps to reproduce the Delete behavior:
1. Create a Script Canvas.
2. Right Click on newly created Script Canvas
3. Select "Delete asset"

Steps to reproduce the Move behavior:
1. Create a Script Canvas.
2. Right Click on newly created Script Canvas
3. Select "Move to"

**Expected behavior**
The Asset should be named, renamed, move or deleted.

**Actual behavior**
The Asset is not named, renamed moved or deleted.

**Screenshots/Video**
https://youtu.be/M7GWKPXdG5c

**Found in**
Editor version 23.10

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Ryzen 9 5950X
 - GPU NVidia RTX 3080
 - Memory 64GB

**Additional context**
The error seems to come from Perforce. But I am not using any version control, nor it is mentionned in the System Requirements.

**Comment by AMZN-alexpete** [comment]
@MacGeorges in the bottom right corner of the Editor window on the status bar is status label and icon that says 'P4V' if you right-click on that it should open a menu that lets you turn P4V off, there is also an editor setting in `Edit, Editor Settings, Global Preferences.` called `Enable Source Control` which you can turn off:
![image](https://github.com/o3de/o3de/assets/26804013/af9d8235-f25d-4753-80e4-9b8c657df3de)

**Comment by MacGeorges** [comment]
Hi @AMZN-alexpete !
Thank you for your message. However, the P4V icon on the bottom right does not react to righ-clicks.
If I left-click on it, there is a small windows comming, saying "Status: Offline".
![bild](https://github.com/o3de/o3de/assets/23235992/38efb7d5-de2e-4845-9fe0-a5dc994995b1)

When I go the the editor settings, the "Enable Souce Control" toggle is off.
![bild](https://github.com/o3de/o3de/assets/23235992/db444182-7a56-49de-99ac-39107ae6e7b8)

I do not have installed Perforce on my computer (I only use Git), but it happears that a "PerforcePlugin" is present in the O3DE editor.
![bild](https://github.com/o3de/o3de/assets/23235992/b0b003da-9deb-486b-8379-1811ba261980)

**Comment by MacGeorges** [comment]
I'll make a fresh virtual machine and just install O3DE, to test / be sure.

**Comment by HydrogenC** [comment]
I have also encountered the problem. 
Toggling "Enable Souce Control" or P4V status doesn't fix the problem. 
Fresh install from installer, new project with default gems.

**Comment by michael-chen2010** [comment]
me too. Rename an asset and nothing happen, and asset processor debug log like this 
![image](https://github.com/o3de/o3de/assets/8923114/d973ec9b-81f6-4bcb-a4eb-e5fc46c1f323)

**Comment by MacGeorges** [comment]
Hey, I just tried again (sorry for being away this long, but I was frustrated with Open3DEngine due to this issue).

I just reinstalled a fresh install of windows, and still experience part of this issue.
(I can create, rename and delete folders, but still can't rename or delete assets such as Script Canvas)
