### ISSUE TITLE
Bug Report: Experiment 50 pieces of materials in one mesh the editor freezes on linux [23.10.0]

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#16994]
**Describe the bug**

Several materials in one mesh at once the editor freezes

file for test on o3de  [Sphere.fbx.tar.gz](https://github.com/o3de/o3de/files/13212568/Sphere.fbx.tar.gz)

**Steps to reproduce**
1. Open the editor
2. Moving the mesh to the screen
3. Select mesh
4. Add material component
5. Editor freezes

**Screenshots/Video**

![2023-10-31_08-37](https://github.com/o3de/o3de/assets/17591539/c5b849a0-c3a6-4946-a51a-133400e24a4f)

https://github.com/o3de/o3de/assets/17591539/aac1e76c-5fd2-4817-bef4-7d54e1cad162

**Found in Branch**
Main (23.10.0)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
0d490a2b4b5e04fd17edf4850c91f94361d4b836

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Fedora 
 - Version 38

**Additional context**

[Editor.log](https://github.com/o3de/o3de/files/13212632/Editor.log)

**Comment by gadams3** [comment]
There have been numerous changes and fixes related to materials, previews, and related systems that have likely addressed this. I am able to assign the model and a material component without crashing. All of the previews on the material component render and populate overtime. It is possible that the reporter could have possibly run out of memory but that should be accounted for by not generating new previews. They should be moved to disk anyway. But as of now, I am unable to reproduce on 23 .10 .1.
