### ISSUE TITLE
LyShine UI and Debug Text No Longer Render

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#17018]
LyShine UI and debug text are no longer rendering.

**Steps to reproduce**
1. Open UI Canvas and view any ui canvas

**Expected behavior**
The canvas renders its sprites/text/images

**Actual behavior**
Nothing is rendered

**Found in Branch**
development

The offending commit: https://github.com/o3de/o3de/commit/9f91681991d21dbd2e9260753d282c3021911159

**Comment by moudgils** [comment]
@antonmic Please close this issue once the PR is merged.
