### ISSUE TITLE
Bug Report Script Canvas InputHandler Node  Creates more  Pins

### ISSUE THREAD

**Issue by G13D** [o3de/o3de#17049]
**Describe the bug**
Script Canvas Input Handler Node Creates more  Pins  when Reopen Script after Save and Close On Graph

**Assets required**
[SC_InputHandlerNode.scriptcanvas.json](https://github.com/o3de/o3de/files/13329075/SC_InputHandlerNode.scriptcanvas.json) - SC_InputHandlerNode.scriptcanvas Asset

**Steps to reproduce**
1. Create New Script Canvas, add InputHandler Node
2. Save
3. Select Open Recent  Script

**Expected behavior**
    As it was before
 
**Actual behavior**
    Digital Mutant

**Screenshots/Video**
![SC_InputHandlerNode_gif](https://github.com/o3de/o3de/assets/58872135/dc954847-eee3-490a-a1cf-cd1941a84ff0)

**Found in Branch**
Latest Night Installer

 - OS: [Windows]
 - Version [10]

**Comment by lumberyard-employee-dm** [comment]
@l-sempe Would you happen to know if we are adding slots to a vector on load(perhaps `Node::InsertSlot` is being called?)

**Comment by lsemp3d** [comment]
Odd, I'll investigate
