### ISSUE TITLE
PBR Materials created in Material Canvas looks to be oversaturated.

### ISSUE THREAD

**Issue by Wc4ever** [o3de/o3de#17079]
If I try to setup Base PBR materail via Material Canvas it looks oversaturated in comparison to default Base PBR material provided by Atom Gem, with same settings. So it's hard to setup "tweaked" Base PBR material which supposed to look the same as default Base PBR but for example using metallic from Normal's alpha channel.

No assets requared can be reproduced on default asset from sdk version.

1. Create default scene with Atom Default Environment
2. Duplicate shader ball
3. Create material based on Base PBR materialtype provaided by Atom Gem. 
4. Set Base Color/Texture to Gems\Atom\Feature\Common\Assets\Materials\Presets\MacBeth\15_red_sRGB.tif
5. Set metallic - 0 roughness - 1 specular f0 - 0 
![3](https://github.com/o3de/o3de/assets/7123610/c13ac1da-83ef-46ea-bb95-f56e61546d99)
6. Apply material on Shader ball.
7. Create Base PBR material in Material Canvas. 
8. Create node Sample Texture 2d and pin it to Base Color. 
9. Set the same texture Gems\Atom\Feature\Common\Assets\Materials\Presets\MacBeth\15_red_sRGB.tif. 
10. Set the rest of the setting the same metallic - 0 roughness - 1 specular f0 - 0 ![1](https://github.com/o3de/o3de/assets/7123610/999b7b92-e450-43e6-8d70-c89b21f440bc)
![2](https://github.com/o3de/o3de/assets/7123610/e0bee268-4587-4789-b6fb-27c330b68742)
12. Apply material, processed by Material Canvas, to shader ball.

Expected behavior
Shader balls looks the same.

Actual behavior
Shader balls looks diffrent.
![4](https://github.com/o3de/o3de/assets/7123610/905e99a4-8cf3-4485-9b69-0c5e5be462d2)

Found in 23.10 sdk release

Desktop:
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU Intel(R) Core(TM) i7-10700
 - GPU NVidia RTX 3060
 - Memory 32GB

**Comment by moudgils** [comment]
Take a peek and close if fixed. Thanks.

**Comment by gadams3** [comment]
All of these other transformations are supported. https://github.com/o3de/o3de/blob/2bdadd250b7341e2e98cc222418fe6d108c1a10a/Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/ColorManagement/TransformColor.azsli

Should be able to create one node with an input and an output color and a couple of drop downs for the input and output color space. If it makes sense. Support could also be baked into the texture nodes, defaulting to LinearSrgb_To_AcesCg.
