### ISSUE TITLE
Bug Report: AssetBrowser freezes for 30 seconds when changing search asset filter

### ISSUE THREAD

**Issue by VickyAtAZ** [o3de/o3de#17091]
**Describe the bug**
It took 31 seconds for Editor to response when change the AssetBrowser filter 

**Assets required**
Create a default level in Editor.

**Steps to reproduce**
1. Go to AssertBrowser
2. Click on the asset type filter button on the right side of asset search input box.
3. Select an asset type from the list. For example, choose 'Material'
4. The Editor stopped responding for 31 seconds then back to normal.

**Expected behavior**
The Editor shouldn't be unresponsive for so long

**Actual behavior**
The Editor stopped responding for 31 seconds before it backs to normal

**Screenshots/Video**

**Found in Branch**
2310.1 release https://o3debinaries.org/point-release-23101/Latest/Windows/o3de_installer.exe

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen Threadripper 3970X 32-Core Processor 3.70 GHz
 - GPU: NVidia RTX 3070
 - Memory: 64GB

**Additional context**
NA

**Comment by drakeredwind01** [comment]
this might be a sig-networking issue

**Comment by gadams3** [comment]
What project was this?
Which asset browser view was being used?

**Comment by VickyAtAZ** [comment]
@gadams3 It was a new project created from standard project template. I just used the default asset browser view when I open Editor.

**Comment by VickyAtAZ** [comment]
The issue is gone with the latest point release build.

**Comment by VickyAtAZ** [comment]
From @gadams3 
The first one directly addresses some obvious, high level optimizations to the asset browser and filters. https://github.com/o3de/o3de/pull/17101
The second one addresses material previews being rendered excessively. https://github.com/o3de/o3de/pull/17104

**Comment by VickyAtAZ** [comment]
The issue still exists with 12.12 play test.
Right after open a level (default level with few prefabs). 
I selected "Prefab" in Asset Browser's search asset type filter. 
Then the Editor stopped response and only recovered after 3 minutes. 
After that, I have tired select different types from the type filter and each time it may take 30~40 seconds to have editor response.

**Comment by VickyAtAZ** [comment]
Same issue as https://github.com/o3de/o3de/issues/14645
