### ISSUE TITLE
Platform-dependant memory leak in Editor (Linux)

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#17102]
**Describe the bug**
I can observe a memory leak in Editor when the more complex scene is used (utilizing materials, lights with shadows, and Diffuse Probe Grid).

**Assets required**
No assets are required, but I provide a repo with reproduction:
https://github.com/michalpelka/MyProject

**Steps to reproduce**
1. Create a new project
2. Add [WarehouseAssets](https://github.com/o3de/o3de-extras/tree/development/Gems/WarehouseAssets) gem
3. Create a level
4. Instatiate prefab called `WarehouseScene.prefab`
5. Start game mode

**Expected behavior**
- Smooth rendering
- 70-100 FPS in game mode

**Actual behavior**
- Huge memory footprint (on Windows machine is no more 2.5 Gb)
- Huge memory footprint is growing (50-100 Mb/s)
- You can see drops in framerate
- Crash when the footprint is about 40 Gb.

**Screenshots/Video**
[Video](https://robotecai-my.sharepoint.com/:v:/g/personal/michal_pelka_robotec_ai/EQKvuqGm9dJBl_si0ud07E0Bc_1dQgvSUy6hzDi30QIbDA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=uJm993)

**Found in Branch**
origin/point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
4391e14f98392674ace32494945cc9a0c6cb3ac7

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Ubunut 22.04
 - Version 22.04.3
 - CPU Intel 13th Gen Core i9-13900K
 - GPU RTX 4080, 525.147.05
 - Memory 64 Gb

**Additional context**
- The bug ,most likely, was introduced in https://github.com/o3de/o3de/commit/5de2fef231c2ac7772ae4861d4dcc069b8ace2bf
- The issue was reproduced on another machine with Ubuntu
- Issue is not reproducible on Windows machines (using Vulkan and DirectX RHI),
- Issue can be platform dependant or compiler dependant.
- Bug does not manifest in gamelauncher.

**Comment by gadams3** [comment]
This should be resolved by the PR mentioned above. We have confirmed that the performance drop and memory leak no longer happen on Windows and Linux. Please comment or reopen if there are further issues. Thank you.
