### ISSUE TITLE
Bug Report - issue with deleted projects

### ISSUE THREAD

**Issue by KhaledButainy** [o3de/o3de#17113]
**Describe the bug**
I am new to this engine. I built the engine from the source code on github and I was trying to create a new project using the CLI according to the github instructions. Initially, i built the engine inside a directory called ($HOME/o3de), then I moved it to this directory ($HOME). I also built a test project then removed it using the linux commands but now I am getting errors when I try to create new projects and these errors are related to my deleted projects. 
As I was trying to fix things, I deleted everything, the source code and the projects, including the o3de_manifest.json file.
I built the engine again from scratch but now creating a new project gives errors as i demonstrated bellow.

**Steps to reproduce**
1. create a project using '''scripts/o3de.sh create-project -pp <path>'''
2. remove the project using '''sudo rm -r <project name>'''
3. create a new project will result in '''[ERROR] o3de.engine_template: Project path <project path> already exists and is not empty.'''
4. Also some times I get '''[ERROR] o3de.manifest: Invalid engine json <engine.json path> supplied or file missing

**Expected behavior**
I expected the project to be deleted and that I easily can create new project

**Screenshots/Video**

**Desktop/Device (please complete the following information):**
 - OS: Linux Ubuntu

**Comment by lumberyard-employee-dm** [comment]
When a project is created it errors if the directory it is being created in is not empty of files. to prevent the user from overwriting files without being explicit by using the `--force/-f` option.

To remove a project it needs to be unregistered with the manifest via using the `scripts/o3de.sh register --remove -pp <project-path>` path command.

**Comment by KhaledButainy** [comment]
Thank you for your comment
