### ISSUE TITLE
RTXGI (& other RT features) are broken since "Raytracing Acceleration Structure Build: Moved the BLAS barriers to right before the TLAS build"

### ISSUE THREAD

**Issue by ohmaya** [o3de/o3de#17156]
@msat-huawei 

https://github.com/o3de/o3de/commit/c7d07cc2ad12d2062ad21318e04669642ae753b6

- I have some previously saved scenes.
- With this commit, on opening the scenes, the RT effects are broken.
- The RT effects are back if moving a geometry, which should build the top-level AS.

**Comment by moudgils** [comment]
@msat-huawei are you able to take a look and address this issue as this will impact everyone using RT features. Thanks.

**Comment by msat-huawei** [comment]
This should be fixed in https://github.com/o3de/o3de/pull/17226
I think I never tested the PR in a scene without animated meshes
