### ISSUE TITLE
OpenXR gems lead to build failure

### ISSUE THREAD

**Issue by DoItForGrandpa** [o3de/o3de#17163]
**Describe the bug**
The error is one I have never seen before in the log file, and comes directly from building the XR gem on the newest dev branch of O3DE.
The part of the log file for XR build is : https://pastebin.com/wmJz6fLV

**Assets required**
OpenXR gems (two available upon typing XR in the gems menu)

**Steps to reproduce**
1. Create a project
2. Add the two XR related gems
3. Build project

**Expected behavior**
The project builds without any errors

**Actual behavior**
The project halts and has an error upon building XR related gems

**Screenshots/Video**
N/A

**Found in Branch**
Develeopment

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[5c46d85](https://github.com/DIFG-github/o3de/commit/5c46d85984eb3e8f048b4768dbaed926c07f65bc)

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]

**Comment by DIFG-github** [comment]
I can build the example project from o3de-extras, just not a new project with newly downloaded xr gems.

**Comment by moudgils** [comment]
API changes were made to ode and o3de-extra repos and as a result if there is a mismatch there will be compile errors. Make sure to get the latest on both repos.
