### ISSUE TITLE
Bug Report: Script canvas select any variable starts to lag only a lot of nodes [Point Release 23.10.1]

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#17174]
**Describe the bug**
Script canvas select any variable of large nodes the editor starts to lag

**Screenshots/Video**

https://github.com/o3de/o3de/assets/17591539/54cdbb7a-2b50-49a3-994c-48fddc28083f

**Found in Branch**
point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
1ac30e042c023f493256b2690c0b0849910e3d49 (HEAD -> point-release/23101, origin/point-release/23101)

**Desktop/Device (please complete the following information):**
 - Device: Linux
 - OS: Fedora
 - Version 38

**Comment by lsemp3d** [comment]
@Darkinggq Did you compile O3DE yourself? are you running a debug build configuration?
