### ISSUE TITLE
Bug Report: Script Canvas variable not working names from component [Point Release 23.10.1]

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#17173]
**Describe the bug**
Script canvas variable from component does not work names

**Steps to reproduce**
1. Open Script Canvas
2. Create Variable
3. Any choose variable 
4. Any name
5. Initial value source select "from component"
6. Script Canvas Saved
7. Result doesn't work names

**Screenshots/Video**

![image](https://github.com/o3de/o3de/assets/17591539/b1abe4f0-f535-4e4f-8832-303a1a7b7126)

https://github.com/o3de/o3de/assets/17591539/7a1bef9a-4804-4550-9a5d-ff18bf5a79d1

**Found in Branch**
point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
1ac30e042c023f493256b2690c0b0849910e3d49 (HEAD -> point-release/23101, origin/point-release/23101)

**Desktop/Device (please complete the following information):**
 - Device: Linux
 - OS: Fedora
 - Version 37

**Comment by alexmontAmazon** [comment]
in review here:
https://github.com/o3de/o3de/pull/17199
