### ISSUE TITLE
Fix `-nomonolithic` argument in the project export script

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#17213]
**Describe the bug**

The recently added '-nomonolithic' flag needs to be updated to follow the pattern of the command settings to support the command settings and make argument reasable. The current naked implementation 

https://github.com/o3de/o3de/blob/ccf2e781868003f5680841d5b0b523567e020391/scripts/o3de/ExportScripts/export_source_built_project.py#L385

should follow the pattern for boolean arguments, similar to 

https://github.com/o3de/o3de/blob/ccf2e781868003f5680841d5b0b523567e020391/scripts/o3de/ExportScripts/export_source_built_project.py#L371-L376

In order to support this, a new key defined for the monolithic build option should be set, similar to 

https://github.com/o3de/o3de/blob/e408302704fce1ea1b824db8a8385bfe6e50c132/scripts/o3de/o3de/export_project.py#L1110-L1113

For example. in [export_project.py](https://github.com/o3de/o3de/blob/e408302704fce1ea1b824db8a8385bfe6e50c132/scripts/o3de/o3de/export_project.py), add:

```
    SETTINGS_OPTION_BUILD_MONOLITHICALLY = register_setting(key='option.build.monolithic',
                                                             description='The option to the launchers monolithically vs non-monolithically.',
                                                             is_boolean=True,
                                                             default='True')
```
Then replace the addition of naked '-nomonolithic' argument  
```
    parser.add_argument('-nomonolithic', '--no-monolithic-build', action='store_true', help='Build the project binaries as shared libraries (as opposed to default monolithic build).')
```
to
```
        export_config.add_boolean_argument(parser=parser,
                                           key=exp.SETTINGS_OPTION_BUILD_MONOLITHICALLY .key,
                                           enable_override_arg=['--monolithic'],
                                           enable_override_desc="Build the launchers monolithically into a single executable.",
                                           disable_override_arg=['--non-monolithic'],
                                           disable_override_desc="Build the launchers non-monolithically, i.e. a single executable and individual modules per Gem.")
```
Then in the main section, follow the pattern for reading boolean args  

https://github.com/o3de/o3de/blob/e408302704fce1ea1b824db8a8385bfe6e50c132/scripts/o3de/ExportScripts/export_source_built_project.py#L426-L429

By adding after that example:

```
 option_build_monolithically = export_config.get_parsed_boolean_option(parsed_args=args,
                                                                          key=exp.SETTINGS_OPTION_BUILD_MONOLITHICALLY .key,
                                                                          enable_attribute='monolithic',
                                                                          disable_attribute='non_monolithic')
```

Finally, replace the reading of the original arg that was passed  into `export_standalone_project` with this new `option_build_monolithically` 

https://github.com/o3de/o3de/blob/e408302704fce1ea1b824db8a8385bfe6e50c132/scripts/o3de/ExportScripts/export_source_built_project.py#L461C41-L461C41

```
     monolithic_build=option_build_monolithically ,
```

**Assets required**
N/A

**Steps to reproduce**
N/A

**Expected behavior**
N/A

**Actual behavior**
A clear and concise description of what actually happened.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
https://github.com/o3de/o3de/blob/e408302704fce1ea1b824db8a8385bfe6e50c132/scripts/o3de/o3de/export_project.py

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**

**Desktop/Device (please complete the following information):**
N/A
**Additional context**

**Comment by tkothadev** [comment]
As of my PR, this issue should be resolved. Closing for now
