### ISSUE TITLE
Moving large prefab causes Editor to freeze for some time.

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#17211]
**Describe the bug**
This prefab https://github.com/o3de/o3de-extras/blob/development/Gems/WarehouseAssets/Assets/Prefabs/WarehouseScene.prefab causes the editor to freeze for a long time when is moved.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Create an empty level
2. Instantiate `WarehouseScene.prefab `
3. Try to move prefab
4. Wait for a long time.

**Expected behavior**
Should not block Editor.

**Actual behavior**
The editor is not responsive for about a minute or so.

**Screenshots/Video**
[Screencast from 12-07-2023 04:11:22 PM.webm](https://github.com/o3de/o3de/assets/3209244/e9b4b707-309e-4c4c-966e-c937fa6a19bc)

**Found in Branch**
o3de-extras main
o3de 2310.1 stabilization

**Commit ID from 
o3de-extras:f21f48125a24517bd6c29fd95ee97a85d546f675
o3de: dc6e2f7a2396aa1b9722bdae1c5453d7727266f9

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS Windows 11/ Ubuntu 22.04
 - CPU I9
 - GPU RTX 4070
 - Memory 64Gb

**Additional context**
I've tested other large prefabs (e.g. ROS2023Demo whole level and it is not causing any issues)

**Comment by AMZN-alexpete** [comment]
@michalpelka is it possible there is some kind of component in the prefab that needs to reprocess assets when moved - perhaps some kind of graphics probes are set to rebake when moved or something? You might look in the logs or asset processor to see if some processing is triggered by the move.  In any case, definitely something we want to track down.

**Comment by forkercat** [comment]
I'm still trying to set up o3de-extras. Without the actual warehouse assets, I could not repo the issue.

@michalpelka If it is related to prefab overrides, do you mind trying this?

1. Expand the `WarehouseScene` prefab tree
2. Move the prefab
3. Check overrides are generated unexpectedly for which objects? (See override icons show up for which objects, for "Movables" maybe?)
4. Undo the move
5. Delete the objects that contain the new overrides (already reverted)
6. Now move the scene again and see if it still freezes for some time

**Comment by michalpelka** [comment]
Thank you @forkercat and @AMZN-alexpete for reply.
After moving the instantiated prefab I can see few unexpected overrides in Entity Outliner:
![image](https://github.com/o3de/o3de/assets/3209244/1c533363-ffdf-46e7-9f85-f0f4196f9c95)
Many more are in level's prefab.
https://gist.github.com/michalpelka/2ceddd67fe5e6d32cadaff1f09207dd5

**Comment by forkercat** [comment]
> after initial translation everything is smooth

I can verify this too. After initial translation, following translations are smooth. I think it is prefab overrides that cause the slowdown.

These are the unexpected override patches (a lot) that are generated in the level prefab. About 2000+ patches.

```json
{
    "op": "replace",
    "path": "/Instances/Instance_[1949468953258891]/Instances/Instance_[5984635845054]/Entities/Entity_[5641038461374]/Components/Component_[7605271439870430818]/Controller/Configuration/ModelAsset/assetHint",
    "value": "assets/warehouse/models/box1.fbx.azmodel"
},
{
    "op": "replace",
    "path": "/Instances/Instance_[1949464658291595]/Instances/Instance_[260036246370750]/Entities/Entity_[5722642839998]/Components/Component_[7605271439870430818]/Controller/Configuration/ModelAsset/assetHint",
    "value": "assets/warehouse/models/box2.fbx.azmodel"
},
{
    "op": "replace",
    "path": "/Instances/Instance_[1949464658291595]/Instances/Instance_[260006181599678]/Entities/Entity_[5804247218622]/Components/Component_[7605271439870430818]/Controller/Configuration/ModelAsset/assetHint",
    "value": "assets/warehouse/models/box4.fbx.azmodel"
},
{
    "op": "replace",
    "path": "/Instances/Instance_[1949460363324299]/Instances/Instance_[5907326433726]/Entities/Entity_[5559434082750]/Components/Component_[15671223893149508584]/Controller/Configuration/ModelAsset/assetHint",
    "value": "assets/warehouse/models/warehouse_rack.fbx.azmodel"
},
{
    "op": "replace",
    "path": "/Instances/Instance_[1949460363324299]/Instances/Instance_[5907326433726]/Entities/Entity_[5559434082750]/Components/Component_[2276504649476859699]/ShapeConfiguration/PhysicsAsset/Asset/assetHint",
    "value": "assets/warehouse/models/warehouse_rack.fbx.pxmesh"
}
```

[new_override_patches.json](https://github.com/o3de/o3de/files/13669510/new_override_patches.json)

**Comment by forkercat** [comment]
Almost all patches are `assetHints` patches. Taking one override patch as an example:

```json
{
    "op": "replace",
    "path": "/Instances/Instance_[1949468953258891]/Instances/Instance_[5984635845054]/Entities/Entity_[5641038461374]/Components/Component_[7605271439870430818]/Controller/Configuration/ModelAsset/assetHint",
    "value": "assets/warehouse/models/box1.fbx.azmodel"
}
```
- Instance_[1949468953258891]: [Storage_rack2.prefab](https://github.com/o3de/o3de-extras/blob/development/Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Storage_rack2.prefab)
- Instance_[5984635845054]: [WarehouseBox1.prefab](https://github.com/o3de/o3de-extras/blob/development/Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox1.prefab)
- Entity_[5641038461374]: [Box1 Entity](https://github.com/o3de/o3de-extras/blob/development/Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox1.prefab#L55)
- Component_[7605271439870430818]: [assetHint field](https://github.com/o3de/o3de-extras/blob/development/Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox1.prefab#L110)

Looks like the prefab files that have `assetHint` fields were generated without `.fbx.` in the path value. After moving the prefab, this function [PrefabPublicHandler::GenerateUndoNodesForEntityChangeAndUpdateCache](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp#L827) will update the translation. Internally, it compares the in-memory prefab DOM (with `.fbx.` in the value) with the prefab DOM read from file (without `.fbx.`). It notices the differences between two DOMs and generates all these unexpected override patches.

Solution: I think we can open all the relevant source prefab files linked by `WarehouseScene.prefab` in editor and re-save them. This could make sure all the source prefabs have `.fbx.` in the `assetHint` path values.

**Comment by michalpelka** [comment]
@forkercat, thank you for your investigation. I will adjust the assetHints and see if a problem exists.
