### ISSUE TITLE
Required Component dropdowns are empty

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#17223]
When using a component that has dependencies on other components the dropdown to add the required components is empty. 

| ![image](https://github.com/o3de/o3de/assets/58790905/969c982f-2b34-4104-a1b3-c39dfbaadeb6) | ![image](https://github.com/o3de/o3de/assets/58790905/6f9db8a4-558f-4cdf-99a8-a6695b6693fe) |

**Expected behavior**
The dropdown should list all compatible required components 

**Actual behavior**
The dropdown is empty (See screenshots)

**Comment by lumberyard-employee-dm** [comment]
@lsemp3d Is this in the point release or development?

**Comment by lsemp3d** [comment]
> @lsemp3d Is this in the point release or development?

Development

**Comment by petrocket** [comment]
This should be fixed by https://github.com/o3de/o3de/pull/17430
