### ISSUE TITLE
Bug Report: "Camera Rig" don't expand it's options on inspector [Point Release 23.10.1]

### ISSUE THREAD

**Issue by Andre-LA** [o3de/o3de#17246]
**Description**
When adding a Camera Rig component to a camera, although I can add elements on the three lists, no expand option appears and I can't setup it.

**Steps to reproduce**
1. Just create a empty project, it can be created from the minimal template.
2. Go to camera
3. Add a camera rig
4. Try adding a target, a look-at behavior or a transform behavior
5. Although the element count changes, you can't set any element values.

**Expected behavior**
Be able to add values on elements as described on [Camera Rig](https://docs.o3de.org/docs/user-guide/components/reference/camera/camera-rig/#target-acquirers-properties) documentation.

**Actual behavior**
No expand option is shown, thus I can't set the elements.

**Screenshots and Video**
![Captura de tela de 2023-12-12 23-32-01](https://github.com/o3de/o3de/assets/8538122/d0b62ba7-f127-475f-b251-8c6d8f70cbb0)

[o3de-camera-rig-bug.webm](https://github.com/o3de/o3de/assets/8538122/bc2535ec-ead0-439f-a7d0-966f1343476b)

**Found in Branch**
`point-release/23101`
update: also present on e22213ea (`23.10.2` point release)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
851b7d8a322c84651971959582081d99c7b602bf
e22213ea946932dc2f94d9f1392e98b4bf2b2c3f

**Desktop/Device**
 - Device: PC
 - OS: Fedora Linux
 - Version: 39
 - CPU: AMD Ryzen 5 5600G × 12
 - GPU: Integrated with CPU.
 - Memory: 16GiB

**Additional context**
The engine was built from source following the ["Create Distributable Build"](https://www.o3de.org/docs/user-guide/build/distributable-engine/) documentation.

**Comment by AMZN-daimini** [comment]
This issue is still active.
@alexmontAmazon may the new fix you're working on address this as well? If not, let's add it to our sprint.

**Comment by AMZN-daimini** [comment]
Verified this now works in latest development after this fix was submitted: https://github.com/o3de/o3de/pull/17457
