### ISSUE TITLE
Bug Report: Strange behavior on adding components to prefabs

### ISSUE THREAD

**Issue by Andre-LA** [o3de/o3de#17259]
**Describe the bug**
Context: When you create a prefab from an entity, the created prefab will wrap the original entity; then, if we try to add a component to this wrapper, it only allows adding a `Comment` and `AssetCollectionAsyncLoaderTest` components.

Bug: However, if you double-click to edit the prefab, then click on the entity, and click back to the prefab, you can add **any** component.

**Steps to reproduce**
1. Select an entity and create a prefab from it.
2. Double-click on the created prefab
3. Check "Add Component" from the Outline, it only shows two options.
4. Click on the wrapped entity
5. Now click back to the prefab wrapper
6. Check "Add Component" from the Outline again, unlike step 2, it now allows any component to be added.

**Expected behavior**
A consistent behavior of the "Add Component" drop-down.

**Actual behavior**
The options on the "Add Component" drop-down are different if you click on the entity and then the prefab.

**Screenshots/Video**
![screenshot](https://github.com/o3de/o3de/assets/8538122/8daa6513-f2fa-4b21-b8a0-00f97d3f5a44)

[video.webm](https://github.com/o3de/o3de/assets/8538122/1a53ce85-7336-4645-85aa-b847a54ab5a9)

**Found in Branch**
point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
f0c150d75722b3302753972b28d73a8036b70b31

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Fedora Linux
 - Version: 39
 - CPU: AMD Ryzen 5 5600G × 12
 - GPU: Integrated with CPU.
 - Memory: 16GiB

**Comment by AMZN-daimini** [comment]
Thanks! This was fixed in latest development by this PR: https://github.com/o3de/o3de/pull/17392
