### ISSUE TITLE
Entity Inspector: Drag&drop an invalid asset

### ISSUE THREAD

**Issue by loherangrin** [o3de/o3de#17250]
**Describe the bug**
When the Asset Browser is set in List View, any asset that is drag-and-dropped to the Entity Inspector has the size of the original row. This makes the landing area inconsistent, accepting an invalid asset.

The issue doesn't happen when the Asset Browse is set to Thumbnail View.

**Steps to reproduce**
1. Create a new empty project
2. Select the `Global Sky` entity in the `Atom Default Environment`
1. Set the `List View` in the `Asset Browser` (third button in the top-right corner)
3. Navigate to `Gems/Atom/Features/Common/Assets/LightingPresets/LowContrast`
4. Drag any image with `.EXR` file to the `Cubemap Texture` field of `HDRi SkyBox` component
5. Move the mouse around the field to show the input pointer without the blue effect
6. Note that no change to the sky is happened in the viewport

**Expected behavior**
Only the valid asset must be inserted

**Actual behavior**
An invalid asset path is set, in the format: `Source|{GUID}|//<file_path>`

**Screenshots/Video**
Invalid action (note that there is only an input pointer at the start of the field and no blue effect):
![invalid-asset-1](https://github.com/o3de/o3de/assets/51530087/ffcb128c-8777-4f63-9a88-65551d62c9fe)

Valid action:
![invalid-asset-2](https://github.com/o3de/o3de/assets/51530087/c02b776c-df6d-43a5-8477-f2e2528f4d2d)

**Found in Branch**
point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
f0c150d75722b3302753972b28d73a8036b70b31

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux

**Comment by lumberyard-employee-dm** [comment]
@alexmontAmazon I believe this may be an issue with Document Property Editor Inspector.
@loherangrin Can you try with disabling the Document Property Editor inspector by setting the CVar of `ed_enableDPEInspector` to `false`?

**Comment by AMZN-daimini** [comment]
I'm not sure what caused this, but I noticed it in other cases as well. If an asset is dropped in the middle of the input field, the filename is added as text and doesn't correctly trigger the field. To make it work correctly one must drop into the border of the input.
This is very finnicky and useless, I'll look into it to see if it can be addressed for Asset control inputs.
