### ISSUE TITLE
material canvas double sided material not rendering correctly 

### ISSUE THREAD

**Issue by omacx** [o3de/o3de#17254]
when using material canvas with alpha and double sided material the back side of the material renders a cut out of the pixels that are supposed to be rendered. the sky box is visible through the cutout pixels.

**Steps to reproduce**
1 open material canvas.
2 add 2d texture node, standard pbr node.
3 assign a texture with alpha to 2d texter node.
4 connect color and alpha outs to the corresponding standard pbr inputs.
5 enable double sided on the standard pbr node in the inspector.
6 select blended from the opacity mode dropdown.
7 build shader.

**Expected behavior**
the back side of the material to render double sided like in the material editor. 

**Actual behavior**
seem to not render anything but the skybox. everything in between the entity with the double sided alpha shader is like masked using the the pixels that are on the back side of the double sided material

https://github.com/o3de/o3de/assets/51685416/228bd933-6bbc-459c-a49e-ac952ce4bd06

**Found in Branch**
downloaded nightly build on 12/9/2023 

**Desktop/Device (please complete the following information):**
 - Device: pc
 - OS: windows
 - Version 10
 - CPU amd
 - GPU NVidia RTX 3060
 - Memory 16gb

**Comment by Darkinggq** [comment]
I already forgot MC about double sided issues in github, thanks you)

**Comment by gadams3** [comment]
Looking at the videos and description in the GHI, it seemed as though the double sided flag was not working at all or correctly when enabled with transparency. There was an issue where the double sided flag was not named or treated the same as the original material types. I made changes and confirmed that worked as expected. Looking more closely at the video and comparing my example graph to another material in material editor, I can see the difference now. The double-sided flag is taking effect but the double-sided, back faces are extremely shiny/reflective, almost mirroring the IBL. I will reopen it and see if I can find the problem.
