### ISSUE TITLE
Components Performance Drops too much When Users interacting with it.

### ISSUE THREAD

**Issue by G13D** [o3de/o3de#17260]
**Describe the bug**
When moving an entity in a 3D world or editing the same component’s properties, such as colors, primitive collider box x, y, z sizes, and the entity’s many components, the FPS will be lower, making it more difficult to move.

**Steps to reproduce**
1. Move the entity in another direction and observe the FPS.
2. On high-end PCs, users may notice the performance drop less.
3. If so, add more components to the entity, such as rigid body, 3D models, etc.
4. Change the components’ random properties and observe the FPS.
5. See Error.

**Expected behavior**
Fast Responsible Editor

**Actual behavior**
like a lag sim

**Screenshots/Video**
If 
![GHIComponentsPerf_gif](https://github.com/o3de/o3de/assets/58872135/b8e4ed5a-2448-4a7f-abbb-c12ada87414f)
applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Point Release 23.10.1 , Nightly Dev

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Please provide the SHA/hash that identifies the latest commit from the o3de/o3de repository if the issue is reproducible in the development or other official branches. 
You can get the commit ID by running the `git rev-parse HEAD` command on your current branch.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Window]
 - Version [10]
 - CPU [Intel I7]
 - GPU [ NVIDIA GTX 10 Series]
 - Memory [16GB]

**Additional context**

**Comment by AMZN-alexpete** [comment]
@alexmontAmazon this might be related to DPE,  is there a simple way for @G13D to profile this and see if the performance loss is from updating the UI vs actually moving an entity or changing the sky color? I suppose if DPE was turned off and there is no performance loss with RPE?

**Comment by G13D** [comment]
If ed_enableDPEInspector is set to false, performance is better
![GHIComponentsPerf_gif_2](https://github.com/o3de/o3de/assets/58872135/75839d6f-f9a7-4197-aabe-2b2dcf85463c)

**Comment by nick-l-o3de** [comment]
I believe this is fixed or improved by https://github.com/o3de/o3de/pull/17938.
Please retest and see if its good enough now to focus on other things...
