### ISSUE TITLE
Custom gem and component: Deleting the last member of a vector makes the field unusable

### ISSUE THREAD

**Issue by mythrz** [o3de/o3de#17275]
**Describe the bug**
Custom made component.  Made a AZStd::vector<AZ::EntityId> m_exampleOfEntities; as the component input field. 

**Steps to reproduce**
1. Create a new gem and component. Followed the instructions from o3de.org: https://docs.o3de.org/docs/user-guide/programming/components/create-component/
3. header (component.h) add
 AZStd::vector<AZ::EntityId> m_exampleOfEntities;
4. source (component.cpp) add a field in the component 
->Field("Example of multiple entities IDs", &Custom088Component::m_exampleOfEntities)
6. source (component.cpp) add a field in the editcontext 
->Attribute("ChangeNotify", AZ_CRC("RefreshValues", 0x28e720d4))
->DataElement(AZ::Edit::UIHandlers::Default, &Custom088Component::m_exampleOfEntities, "Example of entities list", "")
7. Cmake, build the project, run the project.
8. Add the custom component to an entity.
9. Add an entity to the list/vector
10. Delete all members from that list/vector
11. Issue: The field is now unusable. User must remove the component and add it again.

**Expected behavior**
Deleting all members of the list/vector should return the field to its original state. Allowing the addition of new members to the list/vector.

**Actual behavior**
The field is unusable and the component must be removed and added again to return to the original state.

**Screenshots/Video of the code**
![cppComponent088test1](https://github.com/o3de/o3de/assets/44119535/6246d038-6c6e-4fe3-a929-cb4b8a34803e)

**Screenshots/Video of the component in runtime**
![cppComponent088test2](https://github.com/o3de/o3de/assets/44119535/ae674400-60eb-4821-989f-2dc65af5b58c)

**Found in Branch**
point-release/23101 and developer

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/4d025be7592121801aabbb6a0afaac20100a2ab2

**Desktop/Device:**
 - Device: [e.g. PC]
- OS: [e.g. Windows]
- Version [e.g. 11]
- CPU [e.g. AMD Ryzen 2700X ]
- GPU [ NVidia 1060]
- Memory [e.g. 32GB]

**Additional context**
It is a quality-of-life bug-fix. Nothing prevents the users from continuing their workflow

**Comment by AMZN-daimini** [comment]
@alexmontAmazon FYI

**Comment by AMZN-daimini** [comment]
This also happens on all system components that have a vector/list of elements.

![Poof](https://github.com/o3de/o3de/assets/82231674/d3a1a44a-f289-4041-8bf5-cb1a5134d871)

Good thing is, there's an easier workaround to having to delete and re-create the component - just deselect the entity, then select it again.

Still worth looking into @alexmontAmazon
