### ISSUE TITLE
Bug Report: Cannot launch /snap/o3de/13/23.10.1/bin/Linux/profile/default/o3de

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#17281]
**Describe the bug**
When you try to run the `/snap/o3de/13/23.10.1/bin/Linux/profile/default/o3de` you see an error that says:
```
A valid engine.json could not be found or loaded. Please verify a valid engine.json exists in /snap/o3de/13/23.10.1
```

A valid `engine.json` does exist, and you can launch `o3de` from the terminal.

**Steps to reproduce**
1. Install the o3de Snap from the Snap Store
2. Navigate to `/snap/o3de/13/23.10.1/bin/Linux/profile/default`
3. Double-click `o3de`
5. See error

**Expected behavior**
The O3DE project manager opens

**Actual behavior**
The application doesn't open and an error is shown instead
```
A valid engine.json could not be found or loaded. Please verify a valid engine.json exists in /snap/o3de/13/23.10.1
```

**Found in Branch**
main

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[c89678d](https://github.com/o3de/o3de/commit/c89678d6ba58271c76650e7aec180a3196f24f02)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu
 - Version 22

**Comment by spham-amzn** [comment]
Issue is no longer applicable since SNAP packaging will no longer be supported ( https://github.com/o3de/rfcs/issues/54 )
