### ISSUE TITLE
DPE, unexpected behavior with plus sign on vectors

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#17288]
**Describe the bug**
I can observe (both in development and 2310.1) some problems with populating vectors in Inspector.

**Assets required**
I've observed it in my internal repo, but I've created minimal repro here:
MySampleComponent.h:
```
#pragma once

#include <AzCore/Component/Component.h>
#include <AzCore/std/containers/unordered_map.h>

class MySampleComponent : public AZ::Component
{
public:
   AZ_COMPONENT(MySampleComponent, "{E36C4B2C-794B-46E3-8E8D-05A6C705E467}");
   MySampleComponent() = default;
   ~MySampleComponent() override = default;

   static void Reflect(AZ::ReflectContext* context);
   // AZ::Component overrides ...
   void Activate() override {};
   void Deactivate() override {};

private:
    AZStd::vector<AZStd::string> m_map;
};
```
MySampleComponent.cpp:
```
#include "MySampleComponent.h"
#include <AzCore/Serialization/SerializeContext.h>
#include <AzCore/Serialization/EditContext.h>

void MySampleComponent::Reflect(AZ::ReflectContext* context)
{
    if (auto serializeContext = azrtti_cast<AZ::SerializeContext*>(context))
    {
        serializeContext->Class<MySampleComponent, AZ::Component>()
            ->Version(0)
            ->Field("m_map", &MySampleComponent::m_map);
        if (auto editContext = serializeContext->GetEditContext())
        {
            editContext->Class<MySampleComponent>("MySampleComponent", "MySampleComponent")
                ->ClassElement(AZ::Edit::ClassElements::EditorData, "")
                ->Attribute(AZ::Edit::Attributes::Category, "SAMPLE")
                ->Attribute(AZ::Edit::Attributes::AppearsInAddComponentMenu, AZ_CRC_CE("Game"))
                ->DataElement(AZ::Edit::UIHandlers::Default, &MySampleComponent::m_map, "m_map", "m_map");
        }
    }
}
```
**Steps to reproduce**
1. Add cited code to the project's Gem (Cmake, create a descriptor)
2. Compile against development
3. Add component "MySampleComponent" to any entity
4. Click on the plus sign to populate the map with elements.
5. Some fields do not appear.
6. Click the trash can for the whole container - the plus sign is removed.
**Expected behavior**
The list should be populated with empty strings, and DPE should render fields correctly.
**Actual behavior**
It was a messy experience.

**Screenshots/Video**

[Screencast from 12-19-2023 04:35:03 PM.webm](https://github.com/o3de/o3de/assets/3209244/1761756c-84bf-41cf-95e8-15f69c9cdfa1)

**Found in Branch**
- Development and 2310.1

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
f28481174e6a8aa8be857c82fa2e720cc3f10d1d

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Linux]
 - Version [22.04]
 - CPU [ Intel I9 ]
 - GPU [NVidia RTX 4080]
 - Memory [64Gb]

**Additional context**

**Comment by michalpelka** [comment]
The problem exists on Windows as well.

**Comment by alexmontAmazon** [comment]
this should also be fixed by:
https://github.com/o3de/o3de/pull/17289

**Comment by alexmontAmazon** [comment]
fixed in development branch.

**Comment by michalpelka** [comment]
Works as expected on the development branch. Thank you @alexmontAmazon  for fixing it.
