### ISSUE TITLE
Editor: required component list missing (regression)

### ISSUE THREAD

**Issue by jhanca-robotecai** [o3de/o3de#17329]
**Describe the bug**
Some components require other components to work. Let's assume A requires B to work. If B is missing, A is disabled and an extra button to add missing components is created. B should be listed - this is the case in `2310.1`, but not in `development`. See the screenshot below for details.

**Assets required**
The code was compiled with PhysX 5, no extra assets or Gems were needed. PhysX Gem is used as an example here.

**Steps to reproduce**
1. Create new empty level
2. Create new entity
3. Add `PhysX Hinge Joint` component to the entity
4. The component is disabled due to missing `PhysX Dynamic Rigid Body` component; click on `Add Required Component` button
5. See the error: the list is empty

**Expected behavior**
There is one component, namely `PhysX Dynamic Rigid Body`, listed.

**Actual behavior**
There are no components listed.

**Screenshots/Video**
![image](https://github.com/o3de/o3de/assets/134940295/5fccf128-5262-44b3-9067-47db680683eb)

**Found in Branch**
`development`

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
7f4b560a54

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu
 - Version 22.04
 - CPU 13th Gen Intel(R) Core(TM) i9-13900K
 - GPU GeForce RTX 4080
 - Memory 64 GB

**Additional context**

**Comment by djfos** [comment]
Have the same problem, and it is introduced by #16968 .

<img width="1771" alt="image" src="https://github.com/o3de/o3de/assets/24240950/70f79d22-86f5-4e01-9141-9b717104b5e6">

lambda needs a copy but a view of local vector. @lumberyard-employee-dm

**Comment by djfos** [comment]
same as #17223

**Comment by petrocket** [comment]
[fix-required-components-list.patch](https://github.com/o3de/o3de/files/14055726/fix-required-components-list.patch)
I will open a PR with the above patch which I have verified fixes the issue.
