### ISSUE TITLE
Bug Report - 4X performance drop when moving entity with Inspector visible

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#17320]
**Describe the bug**
When the Inspector window is visible, and an entity in the scene is moved, the performance drops noticeably.

If you close the Inspector panel, the performance drop does not occur.  My theory is the performance drop is related to updating the values in the Transform component, likely due to how values are updated when DPE is enabled.

**Steps to reproduce**
1. Create an entity in the scene
2. Grab the transform in the viewport and move it around
5. See error

**Expected behavior**
No loss of performance occurs when Inspector panel is visible.

**Actual behavior**
Performance drops from 16ms -> 44ms when Inspector panel is visible

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
6d96f1bd4ab191c1f61c2e229bad2b363aa3f43d

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Threadripper
 - GPU NVidia 2080 Super
 - Memory 64GB

**Comment by nick-l-o3de** [comment]
I believe this is fixed or improved by https://github.com/o3de/o3de/pull/17938.
Please retest and see if its good enough now to focus on other things...

Note:  Fixed in the stabilization and the development branch, slated for next release 24/09

reopen if necessary.
