### ISSUE TITLE
material canvas emissive alpha problem

### ISSUE THREAD

**Issue by omacx** [o3de/o3de#17339]
**Describe the bug**
when using material canvas with emissive it seems as if the emissive is not using alpha when using blended mode

**Assets required**
![image](https://github.com/o3de/o3de/assets/51685416/3c6c103c-63ea-4261-ba27-6d9bfb3e3df6)
![image](https://github.com/o3de/o3de/assets/51685416/4fad3623-ea1e-44b0-89a0-4eac594d2db6)

**Steps to reproduce**
add a image with an alpha channel, add a standard pbr set it to blended. connect color to base color and emissive and A to to alpha. like the image provided.

**Found in Branch**
nightly build

**Desktop/Device (please complete the following information):**
 - Device:pc
 - OS: window 
 - Version 10
 - CPU amd
 - GPU NVidia RTX 3060
 - Memory 16GB

**Comment by gadams3** [comment]
@omacx Thank you for reporting this. I have reviewed the materials and shaders used in material canvas and stock types like standard PBR. The stock material types that support alpha and emissive provide extra options in the emissive group for configuring how alpha is applied to emissive lighting. We could replicate some of those options in the standard pbr material graph template or you could just multiply your emissive color by alpha in your graph. Either option is acceptable but doing it in the graph will allow greater flexibility IMO.

**Comment by omacx** [comment]
i tried to multiply the emissive color by alpha with no luck. Did I misunderstand what you were saying?
![image](https://github.com/o3de/o3de/assets/51685416/d56173c5-9f63-46df-b777-28f50c6e436f)
![image](https://github.com/o3de/o3de/assets/51685416/774f8f55-9f73-4941-a495-a9e32b88cbe5)

**Comment by gadams3** [comment]
That is interesting! So it's not even being clipped. And this does not happen with a regular standard PBR material?

**Comment by omacx** [comment]
in the material editor it looks fine but in o3de main editor it looks messed up. I'm going to try an other image with alpha to see if my file is the problem
![image](https://github.com/o3de/o3de/assets/51685416/6a6c9329-5fd3-459b-9af1-dfda1f7a09ff)

![image](https://github.com/o3de/o3de/assets/51685416/05ce7ab8-5e3c-4ff7-8d05-1cd5c7dd28d5)

**Comment by omacx** [comment]
using an other png it would seem the problem is with the file that i have been using. thanks for all the help.
