### ISSUE TITLE
SpawnableScriptAssetRef() array as input is not working

### ISSUE THREAD

**Issue by mythrz** [o3de/o3de#17365]
**Describe the bug**
At least in Lua, if I try to set as input an array of SpawnableScriptAssetRef() it will not work as expected. I cannot add elements and then select the prefab. The rest of the arrays (strings and ints) appear to be working properly. A single SpawnableScriptAssetRef() is working properly (instead of setting the input to an array).

This was reported during the changes to DPE, somewhat discussed as array corruption:
https://github.com/o3de/o3de/issues/17208#issuecomment-1853997322
Since "arrays" issue was closed and set as fixed, I opened this new issue before it was forgotten.

**Steps to reproduce**

1. Add a Lua Script
2. Add an array of SpawnableScriptAssetRef(), as input

    PrefabReferences =
    {
	    default = {SpawnableScriptAssetRef()},
	    description = "Multiple PrefabReferences to spawn."
    }
3. Notice the array does not allow the user to add elements

**Expected behavior**
It is possible to add elements to the array, and you can choose multiple prefabs.

**Actual behavior**
The user cannot select the prefabs because the array does not add elements (at least visually, because the counter is going up).

**Screenshots/Video**
![image](https://github.com/o3de/o3de/assets/44119535/56675fde-d2bd-4ecc-9e54-f2c13317f102)

**Found in Branch**
Point Release 2023102 and developer branches

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/24e677cfd2ba7f9947868e26ba7d05eaa2715879

**Desktop/Device (please complete the following information):**
- Device: [e.g. PC]
- OS: [e.g. Windows]
- Version [e.g. 11]
- CPU [e.g. AMD Ryzen 2700X ]
- GPU [ NVidia 1060]
- Memory [e.g. 32GB]

**Additional context**
This issue is very similar to the other array corruption discussed and fixed previously.

**Comment by alexmontAmazon** [comment]
This seems to be occurring because arrays of SpawnableScriptAssetRef use the AZ::DynamicSerializableField type.

The bad news is that this feature isn't yet implemented in the LegacyReflectionBridge that translates reflection data into Documents read by the DPE. 
The good news is that the container fixes that this bug references seem to be working fine, it's just that this particular type of container uses an unimplemented feature. I'm working on implementing this now...
