### ISSUE TITLE
Bug Report: Cache expired and asset processor report errors and fails when removing shaders from material pipeline

### ISSUE THREAD

**Issue by hosea1008** [o3de/o3de#17361]
**Describe the bug**
![image](https://github.com/o3de/o3de/assets/5073925/135e1f21-80ec-497e-a3cb-52e0987ac2d8)

When removing some shaders from the material pipeline, it would trigger the rebuild of a lot of shaders and material types, but this behavior would cause a lot of fails and errors in asset processor.

Actually it is because when removing shaders, the MaterialTypeBuilder will re-insert the shader products into assetdb.sqlite with a new subID, without clearing the previous products in the database, and inserting to the database is deduplicated by jobKey and subID, so there might be duplicated records inserted with the same product name.

![image](https://github.com/o3de/o3de/assets/5073925/7800c9ad-b3f2-483b-90ec-84becf10bb3c)

When the asset processor reads from the database, it is querying by product name, then it would get multiple sources for the product, and reporting errors.

**Assets required**

No assets required.

**Steps to reproduce**
1. Launch the engine and asset processor as usual.
2. Remove some of the shaders in a material pipeline (e.g., one can do this by go to MainPipelineScript.lua, comment out `context:IncludeShader("Transparent_StandardLighting")` and `context:IncludeShader("TintedTransparent_StandardLighting")` under lighting model `Standard`), this is just to pretend removing shader templates from mainpipeline's material pipeline.
3. Leave the cache unchanged, and start again or wait until the asset processor report errors.

Although removing shaders from the material pipeline might not be a regular behavior from the user, but adding/removing shaders to a material pipeline is a common behavior of material/rendering developers.

**Expected behavior**
Asset processor will process all shaders successfully.

**Actual behavior**
A lot of errors reported, and shaders failed to compile.

**Found in Branch**
development branch, I think the release branch after version 2305.0 might have this issue too.

**Desktop/Device (please complete the following information):**

This bus is unrelated to the environment

 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel Xeon 6254
 - GPU RTX8000
 - Memory 64GB

**Comment by lumberyard-employee-dm** [comment]
@gadams3 It sound like the Material Type Builder isn't producing stable subIDs, so removing parts of shaders from the Material Pipeline is causing issues.

**Comment by moudgils** [comment]
discord conversation link - https://discord.com/channels/805939474655346758/816043793576886273/1194089738441854976
