### ISSUE TITLE
Is it possible to reduce performance consumption of DoUpdate function in MeshDrawPacket.cpp

### ISSUE THREAD

**Issue by RogerShaw** [o3de/o3de#17393]
### Discussed in https://github.com/o3de/o3de/discussions/17385

<div type='discussions-op-text'>

<sup>Originally posted by **RogerShaw** January 16, 2024</sup>
My scene consists of hundreds of shaderballs, all using the same material instance. I found DoUpdate function in MeshDrawPacket.cpp comsumes a lot of cpu resources. This causes FPS drops (60fps->30~50fps)
Is it possible to reduce performance consumption of DoUpdate function in MeshDrawPacket.cpp when we change properties of material instance used in meshes?
Thanks so much!</div>

**Comment by moudgils** [comment]
Consider enabling r_meshInstancingEnabled if all the meshes use the same material instance. DoUpdate is expected to take more time if the materials are changing each frame. Consider narrowing down what parts within that method is consuming large amount of time and we can provide better guidance based on that. Tagging @VickyAtAZ @gadams3.

**Comment by AMZN-alexpete** [comment]
I think a good task here would be to create documentation around performance and specifically mesh instancing using `r_meshInstancingEnabled `

**Comment by moudgils** [comment]
Actually there is some data captured here - https://github.com/o3de/o3de/wiki/%5BAtom%5D-Mesh-Instancing:-For-Content-Creators

**Comment by RogerShaw** [comment]
> Consider enabling r_meshInstancingEnabled if all the meshes use the same material instance. DoUpdate is expected to take more time if the materials are changing each frame. Consider narrowing down what parts within that method is consuming large amount of time and we can provide better guidance based on that. Tagging @VickyAtAZ @gadams3.

Thanks for your advice. This is a good idea. I will set r_meshInstancingEnabled to be true and check performance data
