### ISSUE TITLE
Bug Report & Question

### ISSUE THREAD

**Issue by servingrobotmaster** [o3de/o3de#17401]
hello. This is none other than the Korean student who asked the question last time.
Actually, I am trying to create the file. I put the robot arm made with ROS2 into O3DE, added the necessary joint components(JointsArticulationControllerComponent, JointsManipulationRequests, JointsTrajectoryRequests), and launched it, but it still doesn't connect.
Also, I confirmed that o3de_ros2_node was created using rqt_graph, and even though I fired a topic with o3de_ros2_node, there was no message in the terminal.

[WARN] [1705650019.677339845] [o3de_ros2_node]: New subscription discovered on topic '/panda/joint_states', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY

These warning signs came up:
Is there anything I missed??

(I am using docker, and when importing the robot using bridge=network, I used 127.0.0.1 as the IP.)

**Comment by jhanca-robotecai** [comment]
I would recommend starting with the existing ROS 2 project template that implements a very similar setup, i.e., the Panda Franka robotic arm with manipulation enabled via ROS 2 communication and even motion planning software called _MoveIt_. Please have a look at this template: https://github.com/o3de/o3de-extras/tree/development/Templates/Ros2RoboticManipulationTemplate

Running this template would prove your setup (ROS 2 installation, docker setup, ROS 2 calls, etc.) is correct. You might next try to mirror the setup from the template on a new level with your specific robotic arm.

**Comment by servingrobotmaster** [comment]
I tried the template (Ros2RoboticManipulationTemplate), but even though my computer satisfies the specifications of o3de, there was a lag when building, so I would like to run the template as a docker file. Does the project have a docker executable file?

**Comment by michalpelka** [comment]
The issue was discussed in sig-simulation issue triage. Did you have an opportunity to test the suggestion from @jhanca-robotecai? Thanks for the feedback!
