### ISSUE TITLE
Bug Report - Input mappings cannot be added to Input Context (InputContextComponent) 

### ISSUE THREAD

**Issue by petrocket** [o3de/o3de#17404]
**Describe the bug**
Input mappings cannot be added to Input Context (InputContextComponent)  - possible DPE issue?

**Assets required**
n/a

**Steps to reproduce**
1. Add an Input Context component to an entity
2. Click the + button next to Input Mappings

5. See error

**Expected behavior**
The input mapping entry appears when you press the + button

**Actual behavior**
No mappings are visible

**Screenshots/Video**
![image](https://github.com/o3de/o3de/assets/3628857/12197741-3b6b-468a-b9bd-2d88246b9a44)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**

**Desktop/Device (please complete the following information):**
 - Device:PC
 - OS: [Windows
 - Version10

**Additional context**

**Comment by alexmontAmazon** [comment]
this is the same underlying cause as https://github.com/o3de/o3de/issues/17365 . The display is working as of that partial fix mentioned in the other bug, but I'm still working on the element add feature.

**Comment by alexmontAmazon** [comment]
should be fixed by #17441

**Comment by alexmontAmazon** [comment]
... but isn't. Investigating...

**Comment by alexmontAmazon** [comment]
This is another missing feature, AZ::SerializeContext::ClassElement::FLG_POINTER support. The DPE needs to be able to query for derived classes to instantiate in the case of a container of base classes. Working on this now...

**Comment by alexmontAmazon** [comment]
Fix in review:
https://github.com/o3de/o3de/pull/17457
