### ISSUE TITLE
Bug Report: Changing viewport size causes all UI's on meshes to go black

### ISSUE THREAD

**Issue by TheOneAbis** [o3de/o3de#17415]
**Describe the bug**
If the player changes the viewport size (primarily by alt-tabbing) while playing the game, any UI on a mesh in the scene will go black. These UI's fix themselves if something else in the game invokes the UI texture to redraw itself.

**Steps to reproduce**
1. In a new scene, create a new UI canvas and set it to render to a texture.
2. Create a game entity with a mesh that uses that texture with a UI asset ref
3. enter game mode and alt-tab in and out
4. See that the UI's are now blank

**Expected behavior**
UI's should still remain properly displayed after alt-tabbing

**Actual behavior**
UI's go blank after alt-tabbing

**Found in Branch**
Point release 23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
4d025be7592121801aabbb6a0afaac20100a2ab2

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Version 22H2
 - CPU Intel core i9-10900kf 3.70 GHz
 - GPU RTX 3090
 - Memory 64GB

**Comment by Ulrick28** [comment]
Can you work around this for now by detecting an alt tab and then forcing a refresh?

**Comment by TheOneAbis** [comment]
is there a quick and easy way to detect an alt tab? Like a bus of some sort we can use? If not I'll just hard-code to check if the user is pressing both keys. Either way, I'll see if we can work around this using your suggestion, thanks.

**Comment by lumberyard-employee-dm** [comment]
It sounds like UI Canvas is somehow only redrawing on the TickBus, which only ticks when the game/Editor has focus.
I think a window focus event could be used to detect when the Window gets back focus in order to force a redraw.

**Comment by AMZN-alexpete** [comment]
@VickyAtAZ do you have any thoughts on what might be going on here?

**Comment by VickyAtAZ** [comment]
@TheOneAbis do you see any assert, warning or error messages with a profile build when resize and the issue happened?

**Comment by TheOneAbis** [comment]
@VickyAtAZ No, no asserts, logs or error messages occur when this happens.

**Comment by VickyAtAZ** [comment]
@ TheOneAbis 
I have a fix for the issue for development branch. https://github.com/o3de/o3de/pull/17443

**Comment by TheOneAbis** [comment]
amazing! Thanks for getting on this quickly!

**Comment by AMZN-daimini** [comment]
Closing as fixed, feel free to re-open if necessary!
