### ISSUE TITLE
Crash when reseting log in shader management console

### ISSUE THREAD

**Issue by siliconvoodoo** [o3de/o3de#17410]
In shader management console, hitting "reset" button on the logging view
![image](https://github.com/o3de/o3de/assets/25970839/b6650851-f31d-4a74-a523-2bbfa9a63a58)

ends up in a non continuable pure virtual function call crash:
![image](https://github.com/o3de/o3de/assets/25970839/fec3f2ba-8c39-452a-bc50-29a11431602f)

steps:
repository at commit 6555c1eacc9e057831fda 
use AtomSampleViewer project
clear Cache folder
clean build Editor & shader management console in profile
start SMC
wait for asset process
"reset" in logging view

reproduced 3 times. probably deterministic.

**Comment by lumberyard-employee-dm** [comment]
This looks like a call to a pure virtual function is being invoked by the System Tick Bus. Perhaps a virtual function is being invoked on a nullptr instance of a class that was connected to the SystemTickBus

**Comment by moudgils** [comment]
Tag @gadams3. If able to repro locally please investigate further.
