### ISSUE TITLE
Bug Report - Editor does not recognize PhysX Collision Filtering changes

### ISSUE THREAD

**Issue by NanaYellen** [o3de/o3de#17427]
**Describe the bug**
Changing Collision Layers or Groups assigned to PhysX colliders via the _Collides With_ and _Collision Layer_ dropdowns do not change the entity's Group or Layer when entering Game Mode. 

However, when a different field is changed, such as the Trigger or Simulated bools, the Collision Layers and Groups changes are then recognized. 

Both Linux and Windows operating systems seem to be affected by this. 

Perhaps this is related to the recent DPE changes?

**Steps to reproduce**

1. Launch the Editor and load any level.
2. Create a new entity and add **Mesh**, **PhysX Primitive collider** and **PhysX Dynamic Rigid Body** components to it.
3. Change the entity Collision Layer or Collision Group with Collides With and Collision Layer dropdowns found in PhysX Primitive collider component.
4. Enter Game Mode
5. Change different fields in the PhysX Primitive collider component, such as Trigger or Simulated.
6. Enter the Game mode.

**Expected behavior**
Entity's Collision Layer or Collision Group is changed when selecting a different Group or Layer via the _Collides With_ and _Collision Layer_ dropdowns and entering Game Mode.

**Actual behavior**
Entity's Collision Layer or Collision Group fails to change upon entering Game Mode. 

**Screenshots/Video**
In the example video below, I am printing the box entity's Collision Layer and Collision Group to console via script. 

https://github.com/o3de/o3de/assets/112239322/a1013826-4a02-4754-9981-7a37a807199f

**Found in Branch**
Point Release 23.10.2

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10 Pro
 - CPU: Intel i5-6600k
 - GPU: NVidia GTX 1070
 - Memory: 16GB

**Comment by lumberyard-employee-dm** [comment]
Yes, this could be a DPE issue.
@NanaYellen Can you try without the DPE by setting the `ed_enableDPEInspector` option to `false` in the console?

Pinging @alexmontAmazon in case this is a DPE issue.

**Comment by NanaYellen** [comment]
@lumberyard-employee-dm setting `ed_enableDPEInspector 0` in the console doesn't seem to solve the issue unfortunately.
