### ISSUE TITLE
Bug Report - Crash on level load when level contains entity with Bloom component enabled

### ISSUE THREAD

**Issue by petrocket** [o3de/o3de#17434]
**Describe the bug**
The editor crashes when you load a level that has an enabled bloom component.

Log output before the crash:
```
<17:43:29> [Error] (ShaderResourceGroupData) - Image Input 'm_outputTexture[0]': Invalid 'Read / Write' access. Expected 'ImageReadWrite'.
System: Trace::Assert
 I:/o3de/Gems/Atom/RHI/DX12/Code/Source/RHI/DX12.cpp(281): (23612) 'bool __cdecl AZ::DX12::AssertSuccess(long)'
System: HRESULT not a success 80070057, error msg = T
```
Crash is actually in the jobmanager work stealing thread:
```
 	Editor.exe!AZ::Debug::Platform::DebugBreak() Line 90	C++
 	Editor.exe!AZ::Debug::Trace::Assert(const char * fileName, int line, const char * funcName, const char * format, ...) Line 436	C++
>	Atom_RHI_DX12.Private.dll!AZ::DX12::AssertSuccess(HRESULT hr) Line 282	C++
 	Atom_RPI.Editor.dll!AZ::RHI::FrameGraphExecuter::EndGroup(unsigned int groupIndex) Line 95	C++
 	Atom_RPI.Editor.dll!AZ::RHI::FrameScheduler::ExecuteGroupInternal(AZ::Job * parentJob, unsigned int groupIndex) Line 557	C++
 	EditorLib.dll!AZ::Internal::JobManagerBase::Process(AZ::Job * job) Line 31	C++
 	EditorLib.dll!AZ::Internal::JobManagerWorkStealing::ProcessJobsInternal(AZ::Internal::JobManagerWorkStealing::ThreadInfo * info, AZ::Job * suspendedJob, std::atomic<bool> * notifyFlag) Line 421	C++
```

workaround is to leave the bloom component disabled and only enable it while working on the level, then disable it before closing.

**Assets required**
n/a

**Steps to reproduce**
1. Create a level with a bloom component, enable the component
2. Save and close editor
3. Re-open the editor and load the level
5. See error

**Expected behavior**
Editor doesn't crash

**Actual behavior**
Editor crashes

**Screenshots/Video**
n/a

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[4e18098](https://github.com/o3de/o3de/commit/4e18098f769c05719213bf1bed6f530e8967bfa7)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version  10
 - GPU  NVidia 1070-Ti

**Additional context**
n/a

**Comment by AMZN-alexpete** [comment]
Possibly fixed by https://github.com/o3de/o3de/pull/17432 need to verify
