### ISSUE TITLE
Bug Report - Linux nightly jobs are failing

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#17431]
**Describe the bug**
Monolithic release builds are failing in the nightly development build job on Linux because of this warnings as errors:
```
21:08:06  /data/workspace/o3de/Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp:292:28: error: unused variable 'elementRemoved' [-Werror,-Wunused-variable]
21:08:06                  const bool elementRemoved = m_container->RemoveElement(m_containerInstance, elementInstance, impl->m_serializeContext);
```

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
n/a

**Expected behavior**
build succeeds

**Actual behavior**
build fails

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
4e18098f769c05719213bf1bed6f530e8967bfa7

**Comment by galibzon** [comment]
It seems @tkothadev has a fix in this PR: https://github.com/o3de/o3de/pull/17458
