### ISSUE TITLE
Bug Report - Editor crash when adding a material component

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#17506]
**Describe the bug**
The editor can crash sometimes when adding a material component - also sometimes crashes when duplicating entities.

UPDATE: In debug mode it appears that when you use the "Create Material Component" button, behind the scenes the DPE/RPE deletes the widget as it applies the changes ([related commit](https://github.com/o3de/o3de/commit/5ae4e5125253a8e1fb6a129ad302d8d0148cf5ab#diff-592b6e14ff2ebfe4552fe4fe8d5110a5790b37ea7a858332d2eae9846b2e23dfL209)), and then crashes inside the button lambda handler because it's no longer valid.  Relevant part of VERY deep call stack looks like
```
>	EditorLib.dll!AzToolsFramework::PropertyButtonCtrl::~PropertyButtonCtrl() Line 78	C++
 	EditorLib.dll!AzToolsFramework::PropertyButtonCtrl::`scalar deleting destructor'(unsigned int)	C++
 	EditorLib.dll!AzToolsFramework::RpePropertyHandlerWrapper<void *>::~RpePropertyHandlerWrapper<void *>() Line 209	C++
 	EditorLib.dll!AzToolsFramework::RpePropertyHandlerWrapper<void *>::`scalar deleting destructor'(unsigned int)	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::DocumentPropertyEditor::ReleaseHandler(AzToolsFramework::DocumentPropertyEditor::HandlerInfo & handler) Line 1915	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::DPERowWidget::HandleOperationAtPath(const AZ::Dom::PatchOperation & domOperation, unsigned __int64 pathIndex) Line 1015	C++
... many many many stack frames ...
 	Qt5Cored.dll!00007ffd6d471902()	Unknown
 	Qt5Cored.dll!00007ffd6d4cb7d8()	Unknown
 	Qt5Cored.dll!00007ffd6d4b7e77()	Unknown
 	EditorLib.dll!AzToolsFramework::PropertyButtonCtrl::buttonPressed() Line 133	C++
 	EditorLib.dll!AzToolsFramework::PropertyButtonCtrl::{ctor}::__l2::<lambda_2>::operator()() Line 47	C++
```

**Assets required**
n/a

**Steps to reproduce**
1. In the Editor AssetBrowser locate the plane.fbx in Objects, and use the FBX settings window to remove the procedural prefab, then press Save.
2. Open the DefaultLevel in the AutomatedTesting project
3. Find the plane.fbx file in the AssetBrowser and drag it into the viewport
4. Select the plane entity with the mesh component and press the `Add material component` button
5. See error

**Expected behavior**
Material component is added

**Actual behavior**
The editor crashes

**Screenshots/Video**
![image](https://github.com/o3de/o3de/assets/26804013/2cc750c1-052a-418f-9058-c5cb0d2cc868)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
1d0fddbc2300716fae37d1d675661b1abfb2acc4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
n/a

**Comment by AMZN-daimini** [comment]
Got a couple repros with the steps provided. Then reverted the PR that enabled widget recycling and I can't repro the bug with that setup.

Investigating the recycling system to see if there's any chance of conflicts there.
