### ISSUE TITLE
Update the linux documentation to deal with Ubuntu 24.04 changes

### ISSUE THREAD

**Issue by byrcolin** [o3de/o3de#17517]
Ubuntu 24.04 has been built and run successfully with minimal changes to the building instructions. However the instruction will need to be updated to account for minor naming changes.

**Comment by adamdbrw** [comment]
@spham-amzn let me know please once there are instructions and it builds with current development, we will help in testing it!

**Comment by spham-amzn** [comment]
> @spham-amzn let me know please once there are instructions and it builds with current development, we will help in testing it!

The docs were updated for the docs with this [PR](https://github.com/o3de/o3de.org/pull/2550), but I do not see it published on the site yet. There were no specific updates needed for 24.04 LTS, as the default versions of cmake, clang, etc were sufficient.

**Comment by byrcolin** [comment]
@spham-amzn @RoddieKieley Is this done?
