### ISSUE TITLE
Better widget drag visualization from Asset Browser

### ISSUE THREAD

**Issue by Getue** [o3de/o3de#17554]
**Is your feature request related to a problem? Please describe.**
When an asset i.e Material is dragged from the Asset Browser, the drag visual widget is located directly underneath the mouse cursor, obscuring view of what is underneath the mouse cursor.

**Describe the solution you'd like**
The drag widget could be offset from the mouse cursor so it does not obscure what is underneath the mouse cursor.

**Describe alternatives you've considered**
The mouse cursor itself could also be used as a drag visual (i.e a "widget pointer" style mouse cursor with the asset image being part of the cursor) or reducing the opacity of the dragged widget, making it transparent.

**Additional context**
The current behavior is particularly troublesome when dragging asset references into components.

**Comment by AMZN-daimini** [comment]
Progress. Will need some more testing, will likely have the PR up on Tuesday.
![BetterDragAndDrop](https://github.com/o3de/o3de/assets/82231674/fa30ebec-aebd-4be9-ac08-5231ed03cb00)
![image](https://github.com/o3de/o3de/assets/82231674/f7681fc0-e07b-481e-82a4-19a5ecc1c9fa)
