### ISSUE TITLE
Can't build distributable engine on linux

### ISSUE THREAD

**Issue by rainlabs** [o3de/o3de#17592]
Tried to build distributable engine on linux using command `cmake --build --preset linux-install --config profile` but it immediately fails with an error:
```
ninja: error: 'External/Compression-6bb79660/Code/CMakeFiles/Compression.Private.Object.dir/profile/Source/CompressionModuleInterface.cpp.o', needed by 'bin/profile/libCompression.Editor.so', missing and no known rule to make it
```

o3de version: 2310.2
OS: Ubuntu 22.04
cmake: 3.28.3

Project is successfully configured with command:
`cmake --preset linux-default -G "Ninja Multi-Config" -DO3DE_INSTALL_ENGINE_NAME=MyEngine -DLY_3RDPARTY_PATH=$HOME/o3de-packages -DCMAKE_INSTALL_PREFIX=$HOME/o3de-install`

Additional note, running with Editor target start to compile engine as expected, using following command:
```
cmake --build build/linux --target Editor --config profile
```

**Comment by lemonade-dm** [comment]
I believe the issue started to occur CMake 3.28.
It is caused by using the TARGET_OBJECTS generator expression in the `${gem_name}.Editor.Private.Object`  target defined in the Compression Gem CMakeLists.txt at https://github.com/o3de/o3de/blob/development/Gems/Compression/Code/CMakeLists.txt#L127
