### ISSUE TITLE
Cannot download python package

### ISSUE THREAD

**Issue by Sgiath** [o3de/o3de#17615]
**Describe the bug**
I am trying to compile O3DE from the source but it gets stuck on downloading the `python-3.10.13-rev2-linux.tar.xz` package. When I try to download it manually from https://d3t6xeg4fgfoum.cloudfront.net/python-3.10.13-rev2-linux.tar.xz I get Access Denied error.

**Assets required**
Just cloned the clean repo

**Steps to reproduce**
1. Clone the clean repo
2. Install dependencies
3. Run `python/get_python.sh`
5. See error

**Expected behavior**
Package is downloaded

**Actual behavior**
I see this error in the console:
```
CMake Error at cmake/3rdPartyPackages.cmake:287 (message):
  ly_package: - Unable to get package python-3.10.13-rev2-linux from any
  download server.  Enable LY_PACKAGE_DEBUG to debug.

  Error from server https://d3t6xeg4fgfoum.cloudfront.net - 22 - "HTTP
  response code said error"
Call Stack (most recent call first):
  cmake/3rdPartyPackages.cmake:499 (ly_package_internal_download_package)
  cmake/3rdPartyPackages.cmake:589 (ly_force_download_package)
  cmake/3rdPartyPackages.cmake:691 (ly_enable_package)
  cmake/LYPython.cmake:310 (ly_download_associated_package)
  python/get_python.cmake:33 (include)


Unable to fetch python using cmake.
- Is LY_PACKAGE_SERVER_URLS set?
- Do you have permission to access the packages?
```

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version: NixOS

**Comment by Sgiath** [comment]
Also would it be possible to provide an option to supply my own `python` executable without downloading one from the internet?

**Comment by jhanca-robotecai** [comment]
I believe it is related to https://github.com/o3de/o3de/pull/17540
@spham-amzn could you please have a look into it? Thanks!

**Comment by Sgiath** [comment]
Yeah it is probably missing the file on the server. When I try to download the old 3.10.5 version it works 
https://d3t6xeg4fgfoum.cloudfront.net/python-3.10.5-rev2-linux.tar.xz

**Comment by kursad-k** [comment]
I regularly hit issues with "https://d3t6xeg4fgfoum.cloudfront.net " or similar cloudfront end points during builds and compiles. I really hope that there is some improvement with this.

**Comment by spham-amzn** [comment]
The updated package was in the development S3 bucket but wasn't promoted to [production ](https://github.com/o3de/3p-package-source/actions/runs/8255523336)yet at the time, but that was done about 2 hours ago. The URL https://d3t6xeg4fgfoum.cloudfront.net/python-3.10.13-rev2-linux.tar.xz should work now
