### ISSUE TITLE
Script Canvas node localization missing 

### ISSUE THREAD

**Issue by carbonated-niko** [o3de/o3de#17620]
A number of nodes in O3DE aren't properly localized so the subtitle is just the title again. In the attached picture, these are two different bus calls, one for setting visibility on a particle component and one for a mesh, which is very unclear and easy to mix up. 

Additionally, they are missing localization for their parameters (note how both nodes show the default "Boolean" name rather than something descriptive)

![image](https://github.com/o3de/o3de/assets/29128124/434abcad-e0aa-402c-ae4c-7a71e0bd143a)

Note: I havent gone through all the nodes, so I don't know how deep the issue goes

**Steps to reproduce**
1. Open script canvas
2. Add a setvisibility node to the canvas

**Found in Branch**
main

**Comment by lsemp3d** [comment]
I updated the one I found, here is the documentation on how to update these [Node Text Replacement](https://www.docs.o3de.org/docs/user-guide/scripting/script-canvas/editor-reference/text-replacement/ )
