### ISSUE TITLE
material canvas inverted normal

### ISSUE THREAD

**Issue by omacx** [o3de/o3de#17650]
normal maps dont seem to work in material canvas. when hooking them up to base color the texter seems to get inverted.

![asefjkkggkg](https://github.com/o3de/o3de/assets/51685416/18bf5228-30ae-420a-a66c-1f2846c49ae8)

**Found in Branch**
nightly build

**Desktop/Device (please complete the following information):**
 - Device: pc
 - OS: windows 
 - Version 10
 - CPU Ryzen 5000 series
 - GPU NVidia RTX 3060
 - Memory16GB

**Comment by moudgils** [comment]
Material Editor has a property to invert x or y so you could use that to unblock yourself. Tagging @gadams3 to take a look if he has any down time in future.

**Comment by omacx** [comment]
it would seem that i just needed to check the "enable normal input" in the inspector so im closing this issue.
