### ISSUE TITLE
Cannot run Python scripts in Shader Managment Console

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#17660]
**Describe the bug**
I would like to build shader variants. I've created a project, build ShaderManagmentConsole and started it. 
During loading tool produced some warnings:
```
ShaderResourceGroupData: 
==================================================================
ShaderResourceGroupData: Trace::Error
 /home/michalpelka/github_develop/o3de/Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupData.h(467): 'bool AZ::RHI::ShaderResourceGroupData::ValidateImageViewAccess(TShaderInput, const AZ::RHI::ImageView *, uint32_t) const [TShaderInput = AZ::RHI::Handle<unsigned int, AZ::RHI::ShaderInputImageDescriptor>, TShaderInputDescriptor = AZ::RHI::ShaderInputImageDescriptor]'
ShaderResourceGroupData: Image Input 'm_normal[0]': The image has multisample count 1 but the shader expected more than 1.
ShaderResourceGroupData: ==================================================================
ShaderResourceGroupData: 
==================================================================
```

Next I've chosen a shader `standardpbr_mainpipeline_forwardpass_standardlighting.shader` and right-clicked,
selected  

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Build and run ShaderManagmentConsole
2. Start and wait
3. Type `standardpbr_mainpipeline_forwardpass_standardlighting.shader` in AssetBrowser
4. Right-click on ``standardpbr_mainpipeline_forwardpass_standardlighting.shader`  and select Python Script and choose CreateShaderVariantListDocumentFromShader.py 
5. See error:
```
ShaderResourceGroupData: 
==================================================================
ShaderResourceGroupData: Trace::Error
 /home/michalpelka/github_develop/o3de/Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupData.h(467): 'bool AZ::RHI::ShaderResourceGroupData::ValidateImageViewAccess(TShaderInput, const AZ::RHI::ImageView *, uint32_t) const [TShaderInput = AZ::RHI::Handle<unsigned int, AZ::RHI::ShaderInputImageDescriptor>, TShaderInputDescriptor = AZ::RHI::ShaderInputImageDescriptor]'
ShaderResourceGroupData: Image Input 'm_reflection[0]': The image has multisample count 1 but the shader expected more than 1.
ShaderResourceGroupData: ==================================================================
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation
ShaderManagementConsole: Python: PySide2/__init__.py: Unable to import shiboken2 from /home/michalpelka/github_develop/o3de/Gems/Atom/Tools/ShaderManagementConsole/Scripts, /home/michalpelka/github_develop/o3de/Gems/PythonAssetBuilder/Editor/Scripts, /home/michalpelka/github_develop/o3de/Gems/Atom/Feature/Common/Editor/Scripts, , /home/michalpelka/github_develop/o3de/python/runtime/python-3.10.5-rev4-linux/python/lib/python310.zip, /home/michalpelka/github_develop/o3de/python/runtime/python-3.10.5-rev4-linux/python/lib/python3.10, /home/michalpelka/github_develop/o3de/python/runtime/python-3.10.5-rev4-linux/python/lib/python3.10/lib-dynload, /home/michalpelka/github_develop/o3de/python/runtime/python-3.10.5-rev4-linux/python/lib/python3.10/site-packages, /home/michalpelka/github_develop/o3de/Tools/LyTestTools, /home/michalpelka/github_develop/o3de/Tools/RemoteConsole/ly_remote_console, /home/michalpelka/github_develop/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools, /home/michalpelka/github_develop/o3de/scripts/o3de, /home/michalpelka/.o3de/3rdParty/packages/assimp-5.2.5-rev1-linux/assimp/port/PyAssimp, /home/michalpelka/github_develop/o3de/Gems/Atom/RPI/Tools, /home/michalpelka/.o3de/3rdParty/packages/pyside2-5.15.2.1-py3.10-rev6-linux/pyside2/lib/python3.10/site-packages, /home/michalpelka/github_develop/o3de/Gems/WhiteBox/Editor/Scripts, /home/michalpelka/github_develop/o3de/Gems/EditorPythonBindings/Editor/Scripts, /home/michalpelka/github_develop/o3de/Gems/Atom/Feature/Common/Editor/Scripts, /home/michalpelka/github_develop/o3de/Gems/PythonAssetBuilder/Editor/Scripts, /home/michalpelka/github_develop/o3de/Assets/Editor/Scripts, /home/michalpelka/github_develop/o3de/Gems/AtomLyIntegration/CommonFeatures/Editor/Scripts, /home/michalpelka/github_develop/o3de/Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading
ShaderManagementConsole: Python: Traceback (most recent call last):
ShaderManagementConsole: Python:   File "/home/michalpelka/github_develop/o3de/Gems/Atom/Tools/ShaderManagementConsole/Scripts/CreateShaderVariantListDocumentFromShader.py", line 9, in <module>
ShaderManagementConsole: Python: import GenerateShaderVariantListUtil
ShaderManagementConsole: Python:   File "/home/michalpelka/github_develop/o3de/Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListUtil.py", line 8, in <module>
ShaderManagementConsole: Python: from PySide2 import QtWidgets
ShaderManagementConsole: Python:   File "/home/michalpelka/.o3de/3rdParty/packages/pyside2-5.15.2.1-py3.10-rev6-linux/pyside2/lib/python3.10/site-packages/PySide2/__init__.py", line 107, in <module>
ShaderManagementConsole: Python: _setupQtDirectories()
ShaderManagementConsole: Python:   File "/home/michalpelka/.o3de/3rdParty/packages/pyside2-5.15.2.1-py3.10-rev6-linux/pyside2/lib/python3.10/site-packages/PySide2/__init__.py", line 58, in _setupQtDirectories
ShaderManagementConsole: Python: import shiboken2
ShaderManagementConsole: Python:   File "/home/michalpelka/.o3de/3rdParty/packages/pyside2-5.15.2.1-py3.10-rev6-linux/pyside2/lib/python3.10/site-packages/shiboken2/__init__.py", line 27, in <module>
ShaderManagementConsole: Python: from .shiboken2 import *
ShaderManagementConsole: Python: ImportError
ShaderManagementConsole: Python: : 
ShaderManagementConsole: Python: libshiboken2.abi3.so.5.15: cannot open shared object file: No such file or directory
```

**Expected behavior**
I would like to get shader variant document with few rows.

**Actual behavior**
An error is produced to console 

**Found in Branch**
Development / main

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
eb9f4f240370e386afbdaac92d6010b4856917d5

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu 22.04
 - Version 22.04
 - CPU Intel I9-11000k ,
 - GPU RTX 4080
 - Memory 64Gb

**Additional context**
It works as expected on Windows.
Full log : https://gist.github.com/michalpelka/ce0f6e5278d5dcc586e489da38bf22e2

**Comment by nick-l-o3de** [comment]
Looks like a python import library problem, specifically its looking for a libshiboken2.so.5.15 and not finding it.  

Looking on my pc, that is technically located here:
![image](https://github.com/o3de/o3de/assets/70027408/f366b397-786c-434e-8144-eaf459e6eef0)

linked from here:
![image](https://github.com/o3de/o3de/assets/70027408/a9c07ce8-b9e1-4745-908c-5de58e906c61)

and that path `/home/michalpelka/.o3de/3rdParty/packages/pyside2-5.15.2.1-py3.10-rev6-linux/pyside2/lib/python3.10/site-packages` is in the search paths, altho not the subfolder Shiboken2, |

the file name is not the same, looking for libshiboken2.so.5.15 and the actual name is as above.  Hmm...

**Comment by spham-amzn** [comment]
I wasn't able to reproduce the problem. I enabled the QtForPython and PythonBuilder gems as well, but following the steps on ubuntu 22.04 I can't seem to replicate the issue (from the latest development branch)
<img width="648" alt="smc_no_error1" src="https://github.com/o3de/o3de/assets/82231385/9242477f-f2d9-49a0-880a-0f40cd50db23">

**Comment by spham-amzn** [comment]
I also noticed the commit tagged to the bug was before the python relocation (and bug fix).

**Comment by michalpelka** [comment]
Sorry, I probably fetched the fork. Let me test on my end.

**Comment by michalpelka** [comment]
@spham-amzn I've tested @c6c7f88578ba0aa802c58702389f4db6d2ba1410 and got the same: https://gist.github.com/michalpelka/47d6ca5a75337ba1966e30aac0fd39bd

**Comment by spham-amzn** [comment]
So one thing that is missing from my environment is pyside2. Is the QtForPython gem enabled and used in the project? I'm not sure why the SMC would bring that in.

**Comment by spham-amzn** [comment]
So I can see that PySide2 is brought in from the ShaderManagementConsole script [/GenerateShaderVariantListUtil.py](https://github.com/o3de/o3de/blob/06922669492035537409b57bc0549707bccc00bb/Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListUtil.py#L8). 

I followed the same steps and cannot reproduce the error, most likely because I do have `libshiboken2.abi3.so.5.15` in my build/linux/bin/profile folder. Can you double check if this is on your system as well?

**Comment by spham-amzn** [comment]
After some investigation, the issue is that it cannot resolve the shared library dependencies from those packages. I was able to reproduce the issue, and I was also able to work around the issue for now by setting the `LD_LIBRARY_PATH` to the bin/profile folder:
(from the build/linux/bin/profile folder)

```
LD_LIBRARY_PATH=. ./ShaderManagementConsole
```
This could be an issue with the RPATH settings in the 3rd party library for pyside2, but further investigation is needed.

**Comment by spham-amzn** [comment]
It looks like we can fix this specific error by updating the RPATH of shiboken2.abi3.so in the pyside2 package

**Comment by michalpelka** [comment]
@spham-amzn your workaround works for me. Thanks!
