### ISSUE TITLE
Bug Report: some PhysX Collider settings are not serialized correctly

### ISSUE THREAD

**Issue by pawelbudziszewski** [o3de/o3de#17669]
**Describe the bug**
Settings regarding the collision layer and group are not saved. See steps.

**Assets required**
n/a

**Steps to reproduce**
1. Create a custom collision layer and group
2. Create an entity with a rigid body and PhysX Collider 
3. Change the collision layer and group
4. Save level
5. Reload level (or inspect level.prefab file) - **layer/group settings were not saved**
6. Change the collision layer and group again
7. Switch `Trigger` checkbox and save
8. Reload level (or inspect level.prefab file) - **now all settings are saved correctly**

**Expected behavior**
Settings should be serialized

**Actual behavior**
Sometimes it's not the case

**Screenshots/Video**
n/a

**Found in Branch**
2310.2

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
e22213ea946932dc2f94d9f1392e98b4bf2b2c3f

**Desktop/Device (please complete the following information):**
Ubuntu Linux

**Additional context**
n/a

**Comment by AMZN-daimini** [comment]
This PR should fix that issue
https://github.com/o3de/o3de/pull/17543
It has been merged into development, but not into the point release yet.

@Ulrick28 should I cherrypick this in? Do I need to notify anyone specific when making a PR targeting 23.10.3?

**Comment by pawelbudziszewski** [comment]
Confirm, this PR fixes the issue. It would be nice to have it in the .3 :)

**Comment by Ulrick28** [comment]
Feel free to add to the point release branch. On Apr 3, 2024, at 6:14 AM, Paweł Budziszewski ***@***.***> wrote:﻿
Confirm, this PR fixes the issue. It would be nice to have it in the .3 :)

**Comment by AMZN-daimini** [comment]
https://github.com/o3de/o3de/pull/17670

**Comment by AMZN-daimini** [comment]
Cherry-pick was merged but this did not close automatically :)
