### ISSUE TITLE
script events to work in material canvas

### ISSUE THREAD

**Issue by omacx** [o3de/o3de#17686]
the ability to have external event effect material canvas shaders. so an example would be when getting hit or low health making the player flash red. 

script events is the existing system to communicate between scripts.
setting a script event bool to indicate a collision with script canvas to be sent to a material canvas input so it can change the behavior of the shader. 

**Describe alternatives you've considered**
changing out the material to another one to one what i want it to do. i would think its slow to do this.

**Comment by moudgils** [comment]
Material Canvas doesn't really understand script canvas events. Tagging @gadams3 to add more notes.

**Comment by DoItForGrandpa** [comment]
If I am not mistaken you should be able to get the material / shader parameters in script canvas like you can with normal material shaders, and adjust them through script canvas. I have never tried with material canvas shaders though.

**Comment by lsemp3d** [comment]
> Material Canvas doesn't really understand script canvas events. Tagging @gadams3 to add more notes.

Script Events are wrappers around EBus, it could conceivably work if there is an interface to update parameters on the material component that forwards the EBus arguments to the material property.

**Comment by gadams3** [comment]
The feature request described is already achievable without implementing script events directly inside material canvas. Material canvas has no concept of script events stored within a material graph. You can expose material properties using input nodes on the material graph that can already be set from script canvas, Lua, Python, or C++ using the material component request bus. Keep in mind that setting material properties at runtime will result in creating a new material instance that deviates from the material asset. So it might be more optimal to create a secondary material specifically for the flash that can overlay on top of the object, whenever the player gets damaged or in response to some other event. We should investigate having a generic system for these kind of overlay effects. Think there was an overlay component created recently that does this something like this to show outlines for occluded players or entities.
