### ISSUE TITLE
New PythonToolGems causes python exception in ShaderManagementConsole

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#17701]
**Describe the bug**
When a new Python Tool Gem is created from the [Python Tool Gem Template](https://github.com/o3de/o3de/tree/development/Templates/PythonToolGem), the generated [bootstrap.py](https://github.com/o3de/o3de/blob/e13898538869b87ee06007267ee7832032e4e8d3/Templates/PythonToolGem/Template/Editor/Scripts/bootstrap.py) does not handle the situation when the bootstrap in not invoked from the editor (i.e. ShaderManagementConsole or AssetBuilder), thus causing a python exception to be raised. It does not follow the same logic as the [bootstrap.py](https://github.com/o3de/o3de/blob/38261d08007a1ad14135cf790cb855ccca4d8595/Gems/QtForPython/Editor/Scripts/bootstrap.py) in the QtForPython gem to handle this scenarion.

**Assets required**
None

**Steps to reproduce**
1. Open o3de
2. Click on Gems
3. On the right button, Open and select  'Create New Gem'
4. Choose 'PythonToolGem'
5. Go through the next steps to create a custom gem
6. Add the new gem to any project
7. Build the project with this Gem configured
8. Launch the 'ShaderManagementConsole' 
9. Observe the output log

**Expected behavior**
After the initialization of the python bindings component 
```
python: Py_GetVersion=3.10.13 (tags/v3.10.13:49965601d6, Mar 11 2024, 03:06:39) [GCC 9.4.0] 
python: Py_GetPath=(null) 
python: Py_GetExecPrefix=(null) 
python: Py_GetProgramFullPath=(null) 
```
There should NOT be a python exception call stack

**Actual behavior**
A python failure occurs:
```
python: Py_GetVersion=3.10.13 (tags/v3.10.13:49965601d6, Mar 11 2024, 03:06:39) [GCC 9.4.0] 
python: Py_GetPath=(null) 
python: Py_GetExecPrefix=(null) 
python: Py_GetProgramFullPath=(null) 
ShaderManagementConsole: Python: RedirectOutput installed
ShaderManagementConsole: Python: 3.10.13 (tags/v3.10.13:49965601d6, Mar 11 2024, 03:06:39) [GCC 9.4.0]
ShaderManagementConsole: Python: Traceback (most recent call last):
ShaderManagementConsole: Python:   File "/home/o3de/O3DE/Gems/MyPyGem2/Editor/Scripts/bootstrap.py", line 11, in <module>
ShaderManagementConsole: Python: import az_qt_helpers
ShaderManagementConsole: Python:   File "/home/o3de/github/o3de/Gems/QtForPython/Editor/Scripts/az_qt_helpers.py", line 30, in <module>
ShaderManagementConsole: Python: def register_view_pane(name, widget_type, category="Tools", options=editor.ViewPaneOptions()):
ShaderManagementConsole: Python: TypeError
ShaderManagementConsole: Python: : 
ShaderManagementConsole: Python: 'NoneType' object is not callable
```

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
11f7acd48c586451fbbc90ec8f586f624c1c3753

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 22.04
 - CPU N/A
 - GPU N/A
 - Memory 16GB

**Additional context**

**Comment by lemonade-dm** [comment]
I agree that the PythonTool Template should follow the same logic as the QtForPython gem for the bootstrap.py and only register the Qt View Pane if the `azlmbr.editor` module is available.
https://github.com/o3de/o3de/blob/e13898538869b87ee06007267ee7832032e4e8d3/Templates/PythonToolGem/Template/Editor/Scripts/bootstrap.py#L12-L22
