### ISSUE TITLE
ScriptCanvas editor window hides somewhere after being closed and no longer opens

### ISSUE THREAD

**Issue by slapin** [o3de/o3de#17824]
**Describe the bug**
In the project we need any ScriptCanvas file with some data.
When we open this file in editor by double click we expect it to open in ScriptCanvas Editor.
This happens the first time. If we edit something in ScriptCanvas Editor, save and close the window and try to open the same ScriptCanvas file,
the window won't open again. Also if we see no right arrow on the icon of scriptcanvas file, the problem is reproduced successfully.

**Steps to reproduce**
1. Start Editor in existing project with .scriptcanvas.
2. Open ScriptCanvas by doubleclicking. ScriptCanvas Editor should open.
3. Edit some fields in ScriptCanvas, save and close the window. Check that right arrow on ScriptCanvas icon no longer available.
4. Try to open ScriptCanvas again.
5. See error

**Expected behavior**
I expect ScriptCanvas Editor open every time I try to open ScriptCanvas

**Actual behavior**
Sometimes text editor opens instead.

**Screenshots/Video**
https://youtu.be/arGCUwll5qY

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
045084f0bb8870165eb193f68a0cd55de9dd5a1f

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 22.04
 - CPU 13th Gen Intel(R) Core(TM) i7-13620H
 - GPU NVIDIA GeForce RTX 4050 Laptop GPU/PCIe/SSE2
 - Memory 32GB

**Comment by lemonade-dm** [comment]
The ScriptCanvas extension get registered with an opener is at https://github.com/o3de/o3de/blob/development/Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp#L269-L312.

It doesn't look like ScriptCanvas overrides the AssetBrowserInteractionNotificatoinBus [OpenAssetInAssociatedEditor](https://github.com/o3de/o3de/blob/045084f0bb8870165eb193f68a0cd55de9dd5a1f/Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp#L848-L861) event.
So it seems like the code in the [AzAssetBrowserWindow::OnDoubleClick](https://github.com/o3de/o3de/blob/045084f0bb8870165eb193f68a0cd55de9dd5a1f/Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp#L786) function is sometimes trying to delegate to OS to open the ScriptCanvas file

**Comment by slapin** [comment]
But it becomes somehow "sticky" and always open using OS (?) for that particular file and when other ScriptCanvas file is opened, it opens using ScriptCanvas Editor, but previous file still open using text editor. This is weird...
