### ISSUE TITLE
Character: Actors don't store their meshes within the .actor files anymore and refer to a .azmodel (Mesh group). Currently it is only possible to export a single actor and single mesh from an fbx. In case multiple actor groups are added, they will all refer to the first mesh

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#1785]

**Comment by CSteel22** [comment]
I was directed to this thread where it was recommended that I provide an asset for one to test importing multiple actors with different meshes from one FBX. 
[Female_Avatar_Seylenne.zip](https://github.com/o3de/o3de/files/8181727/Female_Avatar_Seylenne.zip)
