### ISSUE TITLE
Bug Report: Shader issues on opening editor in either DX12 or Vulkan.

### ISSUE THREAD

**Issue by 0x14307** [o3de/o3de#17856]
**Describe the bug**
While opening the editor, depending on the graphics API it will either crash due to a shader error or produce black lines across the viewport. This is reoccuring, even with a rebuild of both assets & the project itself.

**Steps to reproduce**
1. Launch editor.
**Expected behavior**
The editor launching without any hiccups in either DX12 or Vulkan set as the renderer API.

**Actual behavior**
If RHI is set to DX12, it produces a shader error and crashes. If it is Vulkan, the editor viewport loads but has black lines appear across the screen.

**Screenshots/Video**
![image](https://github.com/o3de/o3de/assets/56172613/14d8afd9-87c5-44b8-9eb8-97724927b59f)

![image](https://github.com/o3de/o3de/assets/56172613/8fafe589-be9a-44e7-b31b-01bffb197c97)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [11 23H2]
 - CPU [Ryzen 5 3600X]
 - GPU [AMD 6800 XT]
 - Memory [16GB]

**Additional context**

**Comment by lemonade-dm** [comment]
Could this be an issue with the version of the Windows SDK being too new or the graphics card not being detected?

**Comment by moudgils** [comment]
This feels like a driver issue. Please attach logs to the ticket as they may provide more leads. It is weird that the AP was unable to create DX12 bytecode for shaders.

**Comment by 0x14307** [comment]
Current Windows SDK version is 10.0.22621 with the current AMD driver being 24.3.1

**Comment by 0x14307** [comment]
Re-cloning source and rebuilding seemed to fix this somehow, closing.
