### ISSUE TITLE
Prefab Visibility Bug

### ISSUE THREAD

**Issue by DoItForGrandpa** [o3de/o3de#17870]
**Describe the bug**
I have a few larger prefabs, and when you toggle the visibility off in the Entity Outliner it toggles the whole prefab visibility off, it flickers and becomes visible again but with no material you had assigned to it. Once you toggle visibility back on, it flickers and the material comes back. The mesh never stays invisible when the visibility is toggled off.

**Steps to reproduce**
1. Create a mesh and add a material component
2. Toggle visibility (see that it works fine)
3. create a prefab out of that created entity 
4. Try to toggle visibility 
5. See error

**Expected behavior**
Toggling visibility toggles the mesh to be invisible when toggled on in a prefab.

**Actual behavior**
In a prefab the mesh does not toggle invisible when visibility is toggled off.

**Found in Branch**
Dev Branch

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Additional context**
N/A

**Comment by michalpelka** [comment]
Could you provide a hash of the commit you used in o3de's development branch?

**Comment by pollend** [comment]
This was recently added right https://github.com/o3de/o3de/pull/17848. Some interaction I missed with prefabs?

**Comment by pollend** [comment]
Could this be repeated to this change? https://github.com/o3de/o3de/pull/17848

**Comment by pollend** [comment]
yea not sure about the mesh visibility option seems to make this complicated to compound that with the mesh itself.
