### ISSUE TITLE
Unable to name, rename, move or delete assets from the Asset Browser

### ISSUE THREAD

**Issue by MacGeorges** [o3de/o3de#17873]
**Describe the bug**
I am unable to name, rename, move or delete assets from the Asset Browser.
The issue have already been raised[ in another Bug Report](https://github.com/o3de/o3de/issues/16998) and marked as solved by @nick-l-o3de, but while there have been improvements, I am still experiencing the issues previously described:
I can create, rename and delete folders, but still can't rename or delete assets such as Script Canvas.

I just reinstalled a fresh install of windows, P4V is disabled and the "Enable Source Control" option is off.
(Both of them were like that by default)

**Assets required**
None.

**Steps to reproduce**
Steps to reproduce the Name behavior:
1. Create a Script Canvas.
2. Type ne name of your choice.
3. Asset is still named "NewScript"

Steps to reproduce the Rename behavior:
1. Create a Script Canvas.
2. Right Click on newly created Script Canvas
3. Select "Rename asset"
4. Type the name of your choice
5. Asset is still named "NewScript"

Steps to reproduce the Delete behavior:
1. Create a Script Canvas.
2. Right Click on newly created Script Canvas
3. Select "Delete asset"

Steps to reproduce the Move behavior:
1. Create a Script Canvas.
2. Right Click on newly created Script Canvas
3. Select "Move to"

**Expected behavior**
The Asset should be named, renamed, move or deleted.

**Actual behavior**
The Asset is not named, renamed moved or deleted.

**Screenshots/Video**
 https://youtu.be/M7GWKPXdG5c (same video as previous Bug Report, the behavior and error displayed are exactly the same)

**Found in Branch**
 Editor version 2310.2

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Ryzen 9 5950X
 - GPU NVidia RTX 3080
 - Memory 64GB

**Additional context**
The test have been made on a fresh install of Windows.

**Comment by GaianHelmers** [comment]
This appears fixed by Dev branch - 92921487211bf1cf859027fedf076afafb43215e

Hopefully someone can verify these fixes have been included in the point release. Sounding off on discord now.

**Comment by GaianHelmers** [comment]
The fixes should be present in the next O3DE Point release: 23.10.03

**Comment by MacGeorges** [comment]
> The fixes should be present in the next O3DE Point release coming out next week: 23.10.03 #17817 is merged.

Ohhh ok my bad!
