### ISSUE TITLE
Spotlight shadows don't work on device in mobile render pipeline

### ISSUE THREAD

**Issue by pwalterscarb** [o3de/o3de#17919]
Spotlight shadows don't work on device in mobile render pipeline.

I did some testing, reworked the lighting so shadows should be more obvious and I don't think spotlights are casting shadows on device? They work in editor, just not on iphone. Spotlights are fairly new in the mobile render pipeline.

I can see shadows in editor in the mobile render pipeline.
<img width="1181" alt="2024-05-11 13_13_28-O3DE Editor" src="https://github.com/o3de/o3de/assets/50999342/b9b99ac7-6edb-4b59-aa01-6e3ad505a324">

This is how it looks on device, the spotlight doesn't seem to have shadows.
![MW_iPhone_lighting](https://github.com/o3de/o3de/assets/50999342/3948edad-a37e-4398-ad3a-e25a4ce98ce8)

**Found in Branch**
https://github.com/carbonated-dev/o3de
Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository
custom engine version 2310.2

**Desktop/Device:**
Device: [PC]
OS: [Windows]
Version [10]
CPU [Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz, 3501 Mhz, 6 Core(s), 12 Logical Processor(s)]
GPU [NVIDIA GeForce RTX 3090]
Memory [32GB]

To test:
- We work in our branch with vehicles that have a specific setup, so without having to jump to our branch you could try to set up a blank scene with no lights except for one spotlight, directional light and the default ground plane and shader ball.
- Add a spotlight
- Aim the spotlight at the shaderball
- Delete the directional light
- Might want to turn the skybox lighting down or off so the shadows are easier to see
- Turn shadows on for the spotlight
- Send that level to build for iphone and test on the iphone with the mobile render pipeline and see if shadows work

**Comment by moudgils** [comment]
To me this looks like the spotlight itself is not working. For example in the second picture the floor of the van is not getting lit by the spotlight. If the spotlight is somehow disabled then you will not see any shadows from it. It is possible that the spotlight may be getting culled incorrectly in this case. Tagging @akioCL for visibility.

**Comment by pwalterscarb** [comment]
I have updated the scene so the only light is the spotlight, it's not casting shadows. IOS is our primary mobile device for our game.

**Comment by moudgils** [comment]
PR - https://github.com/carbonated-dev/o3de/pull/316
