### ISSUE TITLE
script canvas camera change

### ISSUE THREAD

**Issue by omacx** [o3de/o3de#17967]
**Describe the bug**
In script canvas the "make active view" node changes the camera view for the first request but does not change again when an other request is made. 

**Steps to reproduce**
![image](https://github.com/o3de/o3de/assets/51685416/e3185349-bcd4-428d-a822-9a802fe584a1)

**Expected behavior**
change camera
**Actual behavior**
in script canvas the make active view changes the camera view for the first request but does not change again
 - OS: Windows

**Comment by lsemp3d** [comment]
I was not able to reproduce this, did you put a camera component on each of the entities that you called Make Active View on?

https://github.com/o3de/o3de/assets/58790905/5a0a8de7-ad51-4b54-bffa-4a2f0d459240

![image](https://github.com/o3de/o3de/assets/58790905/aa324442-c2c1-4ee1-ad77-8236af99421b)

**Comment by omacx** [comment]
i have a camera component on both entities 
![image](https://github.com/o3de/o3de/assets/51685416/18f768b7-e7dd-48d6-868e-21dc60f3aa44)
as my game is running the print statement is still printing and when it prints that its switching back it stays on the current camera. one of the cameras is using a lookat component.  is it normal for the entity id to be different character lengths?

**Comment by omacx** [comment]
https://youtu.be/ghV36L8oMVQ
i dont know if a video will help.

**Comment by omacx** [comment]
so my problem was that i thought i was good with just setting the entityID in script canvas like this
![image](https://github.com/o3de/o3de/assets/51685416/c20a9208-f9ee-4411-a8ce-8b367285cc80)
but i needed to set them on the script canvas component as well
![image](https://github.com/o3de/o3de/assets/51685416/3e388590-2216-45ae-9354-f157a32476b6)
