### ISSUE TITLE
Bug Report - Deleted Projects remain in "Restricted" folder.

### ISSUE THREAD

**Issue by GaianHelmers** [o3de/o3de#17988]
**Describe the bug**
After deleting a project, a folder named after the project remains in the "User > O3DE > Restricted > Projects" folder.

**Assets required**
Project Manager and a Blank Project.

**Steps to reproduce**
1. Create a new project.
2. In the Project Manager, select the project options and Delete the Project.
3. Navigate to your Restricted > Projects folder. A folder with the project name will be present.

**Expected behavior**
No remaining folders should be present related to my deleted project.

**Actual behavior**
Project folders pile up in the Restricted > Projects folder. If you use a project of the same name, it will link to the old, already present folder.

**Screenshots/Video**
![image](https://github.com/o3de/o3de/assets/55327922/15f10af0-3bcc-4e01-b3b5-161aad28d027)

**Found in Branch**
Dev - 62076e5bfb8b01b7926af964eb92dda9fa7426c2

**Comment by tkothadev** [comment]
I'm also able to duplicate this error, I will be taking a look at why the restricted folder does not get rid of this project.

**Comment by tkothadev** [comment]
What I'm noticing is that the code responsible for handling deletion code in ProjectScreen.cpp seems to only handle the Project Path, but not the restricted project path, which is a separate data point. The easiest fix is to include methods for deleting the restricted path, and then invoking that when pressing the delete project button

**Comment by tkothadev** [comment]
Once the changes are in stablization, I will close out this issue
