### ISSUE TITLE
Floating triangle or rectangle shaped shadows are displayed

### ISSUE THREAD

**Issue by alexeykostin** [o3de/o3de#17991]
**Describe the bug**
We observe two issues with floating, spurious shadows. The issues are likely have the same root cause.

A) There is a rectangle shaped shadow that moves along with the main character in every level map. The issue is very evident and easy to repro in Central Plaza.

B) While navigating the World Map, it has been observed that a triangle-shaped shadow is displayed on the map. This shadow moves along with the camera and appears to be affixed to it, maintaining a consistent position relative to the camera's movement.

**Assets required**
Please use the MW project to repro.

**Steps to reproduce**
Steps to reproduce the behavior (A):

1. Launch the app.
2. Start a mission in Central Plaza.
3. Rotate the camera to make sure the shadow is cast in front of the character.
4. Move the camera view up and down.
5. Observe the issue.

Steps to reproduce the behavior (B):

1. Launch the app.
2. Open the World Map.
3. Navigate through the map.
4. Try to move to areas that are clearer.
5. Observe the issue.

The issues are reproducible on iPhone. Models 13 pro max, 14, 15 have been tried. They don't repro on Windows, even when quality settings are the same as used on iPhones. So the issues are likely renderer-dependent.

**Expected behavior**
No spurious shadows are to displayed

**Screenshots/Video**
Available separately.

**Found in Branch**
Current dev branch of the MW project

**Desktop/Device (please complete the following information):**
 - Device: iPhone
 - OS: iOS
 - Version: iPhone 13 pro max, 14, 15

**Comment by moudgils** [comment]
Tag @akioCL
