### ISSUE TITLE
Bug Report: Engine crash attempting to access FBX details

### ISSUE THREAD

**Issue by TheOneAbis** [o3de/o3de#18034]
**Describe the bug**
When I attempt to access the FBX details of a mesh via the asset inspector window, the entire engine crashes.

**Assets required**
The asset causing the crash: 
[SteppingRock1.zip](https://github.com/user-attachments/files/15845883/SteppingRock1.zip)

**Steps to reproduce**
1. Import this asset into a project
2. click on it in the Asset Browser to bring up its details in the Inspector
3. Click on the FBX settings tab in the inspector
4. Death

**Expected behavior**
No crashes, I am able to view the FBX details

**Actual behavior**
Instant engine crash. Write access violation in qwindows.dll
![image](https://github.com/o3de/o3de/assets/26350896/ef917bd8-03c9-464f-a461-03265356226e)

Not a very helpful callstack, but this is in the Qt5Core.dll thread. I should note that the asset processor lists this as a warning that I feel may be involved with the issue: 
![image](https://github.com/o3de/o3de/assets/26350896/a162e0be-d296-420a-a4ea-c62428ad01cf)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
bb3eafe30d8291f50b69924e5b7a432c8c6f53ca

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Version 23H2
 - CPU Intel Core i9 10900k @ 3.7HGz
 - GPU NVidia RTX 3090
 - Memory 64GB

**Comment by nick-l-o3de** [comment]
I think this might be a similar problem to what I've seen during debugging, where the FBX information gathering thread creates a prefab in memory, which involves creating components and entities, and some of those created but not active components and entities interact with the real system.  This is happening in a thread.

**Comment by TheOneAbis** [comment]
I can definitely say it has something to do with the naming of the nodes within that FBX, because when we dchanged the name to not include a . the engine stopped crashing and I was able to see the details just fine.

**Comment by tkothadev** [comment]
Did the asset processor emit any extra information for that warning you posted? Iirc, the processor when running jobs also includes information about source files, and line numbers that ran when the job starts.

**Comment by TheOneAbis** [comment]
![image](https://github.com/o3de/o3de/assets/26350896/03130f1b-cd02-4eb4-84fd-966c83f8066d)

![image](https://github.com/o3de/o3de/assets/26350896/4e5139d2-06ea-4a0e-9b50-7063e08a48e7)

These are everything the AP displays. Hope this helps.

**Comment by nick-l-o3de** [comment]
This is likely fixed by https://github.com/o3de/o3de/pull/18056 - will retest once that's in dev (its currently in stabilization)
