### ISSUE TITLE
Prefab Overrides | Unparenting a child breaks the main prefab

### ISSUE THREAD

**Issue by loherangrin** [o3de/o3de#18052]
**Describe the bug**
When a child of a specific prefab instance is detached from its parent, it is moved outside the boundaries of the prefab container and re-assigned to the immediate grandparent in the scene. The invalid action is applied also to the base prefab which the instance was created from.

**Steps to reproduce**
1. Create a hierarchy of two empty entities (i.e. `Parent` > `Child`).
2. Convert it to a prefab with the name `Prefab`.
3. Select `Child` entity in the prefab instance .
4. Unassign the parent by pressing `X` in the `Parent entity` field of `Transform Component`.

![unparent-prefab-4](https://github.com/o3de/o3de/assets/51530087/d7a5507b-9304-483a-bc1f-39465a0b6015)

**Expected behavior**
`Prefab` entity is automatically assigned as the new parent of `Child`, which now is at the same level of `Parent`. This behavior is actually applied correctly when the action is performed on the main prefab instead of a specific instance (i.e. within the Focus Mode, which can be accessed by double clicking on a prefab instance).

![unparent-prefab-2](https://github.com/o3de/o3de/assets/51530087/ce2b7dad-d185-4d6b-9358-24fb38887ccc)

**Actual behavior**
`Child` is assigned to `Level`, which is an entity that is outside of the prefab scope.

![unparent-prefab-1](https://github.com/o3de/o3de/assets/51530087/3187e7e5-2ae6-499a-bc7f-bc617a112abc)

Moreover, the main prefab is marked as `edited` and the user will be prompted to apply the changes at the next save operation. This would lead to damage all the already existing instances of the prefab in the scene.

![unparent-prefab-3](https://github.com/o3de/o3de/assets/51530087/7dddfd52-c942-4275-b27c-70734f6f27d2)

**Found in Branch**
stabilization/2409

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
2b9e0da556c9c09909f1747db867899125b9aff8

**Device:**
 - Device: PC 
 - OS: Linux

**Additional Context**
A similar behavior was reported in issue #16541, which is still applicable too.

**Comment by nick-l-o3de** [comment]
Very nice catch!  I'm guessing that "clear" button needs to be made aware of the fact that prefabs exist and has to treat the prefab container entity the child lives in as the "root" rather than the level... (gets more complicated with the fact that heirarchy can be overridden)

**Comment by nick-l-o3de** [comment]
I kind of have 2 options here.

1. Disable clear button, drag and drop, and pick button, on the Entity Transform Parent field.  Allow it on all other EntityId fields.  Do it via attributes Ie, you can suppress drag and drop and pick and clear on any other entityid field by tagging them as such as you need.
2. Enable clear button, but come up with a bunch of optional callbacks to deal with a whole mess of special cases.

I started implementing #2 but actually starting to think #1 makes more sense.
In terms of the  Parent Entity, you manipulate that using the entity outliner and it can already handle drag and drop, moving, deleting, etc.  
The other thing that makes it more reasonable to use 1. is that clearing means a different thing to every entity depending on context (like you can have **multi selected 2 different entities from 2 different parent containers** and if you click clear, they actually have to take on 2 final different values, but the GUI is going to try to set them both to the same.

And this complexity explodes when you consider you can drag and drop an entity there into that field **with multiselect**, you can click clear on multiselect, and you can click the picker icon on multiselect.  The amount of complexity this would introduce seems huge in comparison to just adding some attributes like "ShowPickerButton", "ShowClearButton" (already exists), "AllowDrop".

**Comment by nick-l-o3de** [comment]
Fixed in Dev and stabilization
