### ISSUE TITLE
Bug - Asset Browser does not Update the Inspector if you click on an asset in the tree view or favorites view

### ISSUE THREAD

**Issue by nick-l-o3de** [o3de/o3de#18067]
**Describe the bug**
Clicking on product items or source items when the Asset Browser is in tree mode (instead of split view thumbnails) does not update the rest of the GUI appropriately.   since the "Favorites" live in tree side of the split view, they don't function either.

Note that you can still click on the assets in the big "thumbnail" or "list view" (right hand side of the split view) and it works, just not if you click on them on the left hand side tree view.

**Assets required**
None, you can use the built in assets of any default project

**Steps to reproduce**
1. open the editor and the asset browser panel
2. Switch it to tree view using the view mode icon
3. Make sure the editor inspector view is present somewhere else on the GUI
4. Start clicking on assets, like a FBX file, or an image file

**Alternative steps**
In this set of steps you don't even have to use "Tree view" mode to reproduce the problem.

1. Find any asset in your asset browser (even in non-tree mode) and add it as a favorite by right clicking it and adding favorite.
2. Add a few favorites
3. Go to the favorites area in the asset browser.  Note that this is in the tree area, not the icon / thumbnail area.
4. Click on any of the stored favorites in the Asset Browser, while the Inspector View is present somewhere else on the GUI

**Expected behavior**
Other GUIs in the editor update - for example, FBX files being selected causes the FBX import settings to appear.  Texture settings or previews appear for textures, other asset information is given for other types of assets.

**Actual behavior**
The UI does not "notice" that you have clicked on any asset in the favorites area or the tree view and the inspector does not update.

**Found in Branch**
Stabilization/2409 and likely development too

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux and windows

**Comment by AMZN-daimini** [comment]
Possibly related to this change: https://github.com/o3de/o3de/pull/17570

See one of the last points ("Asset information in the Inspector").
May just be a matter of replicating the same logic for the cases you list.

**Comment by nick-l-o3de** [comment]
Thanks for the info.  I might tackle this next

**Comment by nick-l-o3de** [comment]
working on this now.

**Comment by nick-l-o3de** [comment]
I have a fix for it, but I notice some other side effects this bug is causing that are related (not the fix) that I'd like to see if I can fix also as part of it.
