### ISSUE TITLE
Stabilization 2409 version of O3DE does not have compatible ROS2 and related gems for version 2.3.0

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#18071]
**Describe the bug**
Stabilization 2409 version of O3DE does not have compatible ROS2 and related gems for version 2.3.0 in o3de-extras. The following gems + versions are incompatible with stabilzation/2409 and the next release:

* ProteusRobot / 1.1.0
* ROS2 / 3.1.0
* ROS Robot Sample / 1.1.0
* WarehouseAutomation / 1.1.0

We need to create new versions for these gems and set the compatible engines to point to the next release

**Assets required**
N/A

**Steps to reproduce**
1. Open o3de (project manager)
2. Set the project name
3. select ROS2 Project
4. Download the template
5. Click on 'Configure with more Gems'
6. On filter by on the left, make sure 'Compatible' is un-checked
6. Search for 'ROS' and select it (do not enable). Notice that 'Compatible Engines' for o3de-sdk and o3de is 2.1.0 or higher for version 2.0.0
7. On the 'Version' drop-down on the right, switch from 2.0.0 to 3.1.0

**Expected behavior**
The gems listed above should all show `compatible engines: All Engines` when selected

**Actual behavior**
You will see `This version is not known to be compatible with the engine this project uses`

**Screenshots/Video**
![Screenshot from 2024-06-28 08-28-40](https://github.com/o3de/o3de/assets/82231385/f36f60e8-ec0c-4634-aaad-9e6b1f20411f)

**Found in Branch**
stabilzation/2409

**Commit ID from [o3de/o3de-extras](https://github.com/o3de/o3de-extras) Repository**
6e14f242aac8ac4dd0012d7f9239e2a9690451d3

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version : Ubuntu 22.04
 - CPU : N/A
 - GPU : N/A
 - Memory 32 GB

**Additional context**
None

**Comment by michalpelka** [comment]
Note that following is also true for project templates.

**Comment by spham-amzn** [comment]
This has been resolved with https://github.com/o3de/o3de-extras/pull/718
