### ISSUE TITLE
Linux: Mesa 24 allocator segfault

### ISSUE THREAD

**Issue by DrogonMar** [o3de/o3de#18197]
**Describe the bug**
On Linux distros with Mesa 24 O3DE will segfault when enumerating physical devices.
This should happen with any version of O3DE where the Vulkan RHI is using a custom allocator.

**Steps to reproduce**
1. Launch any project.
2. Crash.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version: Fedora 40
 - CPU: AMD Ryzen 9 7950X
 - GPU: AMD 6950XT
 - Memory: 64gb

**Additional context**
Seems to be more of an issue from Mesa when it free's data about the Vulkan icd's.
This doesn't happen in Mesa 23.

**Comment by DrogonMar** [comment]
Current temporary patch Ive been using:
https://gist.github.com/DrogonMar/72495c0ac1338383957d73315719a86d

**Comment by moudgils** [comment]
The solution needs be much more narrow in terms of disabling the allocator for the exact API (for the given firmware version + platform) that is causing the crash.

**Comment by DrogonMar** [comment]
@moudgils Heres the callstack:
```
AZStd::intrusive_multiset::erase intrusive_set.h:612
AZ::HphaSchemaBase::HpAllocator::tree_detach HphaAllocator.cpp:1773
AZ::HphaSchemaBase::HpAllocator::coalesce_block HphaAllocator.cpp:1467
AZ::HphaSchemaBase::HpAllocator::tree_free HphaAllocator.cpp:2083
loader_unload_scanned_icd 0x00007fff7d32a4f3
vkEnumeratePhysicalDevices 0x00007fff7d341886
AZ::Vulkan::PhysicalDevice::Enumerate PhysicalDevice.cpp:44
AZ::Vulkan::Instance::EnumerateSupportedDevices Instance.cpp:255
AZ::Vulkan::Instance::Init Instance.cpp:205
AZ::Vulkan::SystemComponent::Activate SystemComponent.cpp:96
AZ::Entity::ActivateComponent Entity.h:399
AZ::ModuleManager::ActivateEntities ModuleManager.cpp:758
AZStd::Internal::INVOKE<…> invoke_traits.h:177
AZStd::invoke<…> invoke.h:54
AZ::EBusEventProcessingPolicy::Call<…> Policies.h:437
AZ::Internal::EBusContainer::Dispatcher::Event<…> BusContainer.h:149
AZ::Entity::Activate Entity.cpp:218
AzFramework::Application::StartCommon Application.cpp:230
AzGameFramework::GameApplication::StartCommon GameApplication.cpp:161
O3DELauncher::Run Launcher.cpp:494
main Launcher_Linux.cpp:96
__libc_start_call_main 0x00007ffff7839088
__libc_start_main_impl 0x00007ffff783914b
_start 0x0000555555f9a6a5
```
