### ISSUE TITLE
The `CaptureMouseCursor` is ignored by Editor.

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#18208]
**Describe the bug**
The `CaptureMouseCursor` is ignored by Editor.

**Assets required**
Setreg file:
```
{
    "O3DE":
    {
        "InputSystem":
        {
            "Mouse":
            {
                "CaptureMouseCursor": false
            }
        }
    }
}
```

**Steps to reproduce**
1. Add setreg to your project / gem
2. Start Editor, hit CNTR+G 
3. Experience mouse capture event.

**Expected behavior**
With this setting mouse should not be captured.

**Actual behavior**
Mouse is captured

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Stabilization

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
commit 42cdcb76b90cb59712e3f3f13d0102808941ee75 (HEAD -> stabilization/2409, origin/stabilization/2409)

**Desktop/Device (please complete the following information):**
 Ubuntu 

**Additional context**
It does not appear in GameLauncher.

**Comment by boczekbartek** [comment]
I've also noticed this issue in O3DE Editor (on 607b907fa668a8cbe8c16eec154a79cbca2f0bad), a fix would be very appreciated!
