### ISSUE TITLE
[Stabilization 2409] Installed O3DE SDK fails to build new project

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#18222]
**Describe the bug**
From an installed O3DE SDK, creating a new project in Project Manager and clicking build will fail with the following error:

```
CMake Error at C:/O3DE/2.3.0/cmake/3rdParty.cmake:182 (message):
  Cannot find include path /External/glad/2.0.0-beta/include for
  3rdParty::glad_vulkan
Call Stack (most recent call first):
  C:/O3DE/2.3.0/cmake/3rdParty/Findglad_vulkan.cmake:10 (ly_add_external_target)
  C:/O3DE/2.3.0/cmake/LYWrappers.cmake:603 (find_package)
  C:/O3DE/2.3.0/cmake/LYWrappers.cmake:266 (ly_parse_third_party_dependencies)
  C:/O3DE/2.3.0/Gems/Atom/RHI/Vulkan/Code/Platform/Windows/Default/permutation.cmake:11 (ly_add_target)
  C:/O3DE/2.3.0/Gems/Atom/RHI/Vulkan/Code/Platform/Windows/platform_windows.cmake:12 (include)
  C:/O3DE/2.3.0/Gems/Atom/RHI/Vulkan/Code/CMakeLists.txt:9 (include)
```

**Assets required**
None

**Steps to reproduce**
1. Install the O3DE windows installer
2. Launch the O3DE Project Manager
3. Create a new project using the default template
4. Click on 'Build Project'

**Expected behavior**
The project successully builds

**Actual behavior**
The project fails to build

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
stabilization/2409

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
dfbc5d341a126a704bb54833ff13054e0bab2c9f

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU N/A
 - GPU N/A
 - Memory 32 GB

**Additional context**
The error occurs in the installer [Findglad_vulkan.cmake](https://github.com/o3de/o3de/blob/stabilization/2409/Gems/Atom/RHI/Vulkan/3rdParty/Findglad_vulkan.cmake)

```
get_property(atom_rhi_vulkan_gem_root GLOBAL PROPERTY "@GEMROOT:Atom_RHI_Vulkan@")
ly_add_external_target(
    NAME glad_vulkan
    VERSION 2.0.0-beta
    3RDPARTY_ROOT_DIRECTORY ${atom_rhi_vulkan_gem_root}/External/glad
    INCLUDE_DIRECTORIES include
)
```

**Comment by pijaro** [comment]
Looks very similar to https://github.com/o3de/o3de/issues/11207

**Comment by spham-amzn** [comment]
I figured out the root cause of the issue. It was introduced with this [PR](https://github.com/o3de/o3de/pull/18189). I will create a PR to fix it.
