### ISSUE TITLE
[Stabilization] Project Export Error with SDK + Monolithic

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#18230]
**Describe the bug**
When trying to export a project on windows from the installer SDK and Project Manager, if monolithic build is enabled, the process will fail with the following message

```
[ERROR] root: Trying to create monolithic build, but no monolithic artifacts are detected in the engine installation! Please re-run the script with '--non-monolithic' and '-config profile'.
```
![export-settings-monolithic](https://github.com/user-attachments/assets/eb23362c-88ab-4ef0-abb7-59150c284501)

**Assets required**
Default Assets

**Steps to reproduce**
1. Download and install O3DE from the installer package on windows
2. Open O3DE Project Manager
3. Create a new Default Project
4. Build the Default Project
5. Open the Editor and wait for the assets to finish processing
6. Go back to the Project Manager and for the new project options, click on 'Export Launcher->Windows`

**Expected behavior**
The project export process starts and completes without error

**Actual behavior**
An error occurs indicating that it failed and that monolithic artifacts are not available

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
stabilization/2409

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
dfbc5d341a126a704bb54833ff13054e0bab2c9f

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU N/A
 - GPU N/A
 - Memory 32 GB

**Additional context**

**Comment by spham-amzn** [comment]
It seems like we should never allow exporting monolithic packages from the installer:
https://development--o3deorg.netlify.app/docs/user-guide/packaging/windows-release-builds/

**Comment by tkothadev** [comment]
@lemonade-dm Also wanted to gather your thoughts on the monolithic issue described here.

**Comment by spham-amzn** [comment]
It looks like monolithic builds support for the SDK is suppose to be available:
https://github.com/o3de/o3de/issues/3227

**Comment by tkothadev** [comment]
Two more PRs related to this from @AMZN-alexpete:
https://github.com/o3de/o3de/pull/17231
https://github.com/o3de/o3de/pull/17412

It seems like support should have been in place since December's point release. If I recall correctly, there's some extra steps in setting up the installer SDK (artifacts have to be copied over), before the SDK can properly support monolithic builds. The O3DE release binaries should have these setup.

**Comment by spham-amzn** [comment]
Error was caused by an incomplete build of the installer that was built locally. verified the one from o3debinaries.org works
