### ISSUE TITLE
Unexpected crash on activation of PhysX and PhysX5 gem together

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#18234]
**Describe the bug**
Naturally, PhysX and PhysX5 gem cannot work together.
However, there it is frustrating experience if you choose both gems.
You get crash (similar to one without GPU drivers), and only clue is that comment:
```
Multiple 'EditorSystemComponent' found, but this component is incompatible with others of the same type.
```
**Assets required**
No assets.

**Steps to reproduce**
1. Create a empty project
2. Build
3. Add ROS 2 gem
4. Experience crash

**Expected behavior**
It can crash, but it should be more verbose.

**Actual behavior**
No info, unexpected crash, and almost no log.

**Screenshots/Video**

**Found in Branch**
stabilization2409, development

42cdcb76b90cb59712e3f3f13d0102808941ee75

**Desktop/Device (please complete the following information):**
 - Ubuntu 2204

**Comment by michalpelka** [comment]
Closed by mistake

**Comment by SammyRamone** [comment]
Just experienced the same error. Thank you for creating this issue which helped me to quickly resolve it (by deactivating the physx4 gem on my project). A better error message would help a lot. I had no idea what the error means. Simply showing the name of the problematic gem would have lead me quickly to the right path.

**Comment by Mechazo11** [comment]
Hi @michalpelka and @SammyRamone thank you very much for this solution. I had been struggling with it since the past two - three days. I can confirm once all ```Physx``` references have been changed to ```Physx5``` in ```project.json```, this problem no longer occurs.
