### ISSUE TITLE
24.09 Release - AZStd::unordered_set<AZ::u32> reflection crash

### ISSUE THREAD

**Issue by arturkamieniecki** [o3de/o3de#18348]
### Bug Description

Adding values to the reflected  AZStd::unordered_set<AZ::u32> using the editor and then deleting it causes a crash.

### Assets-Required

I've created a test component that causes the crash.
[TestComponent.zip](https://github.com/user-attachments/files/17145107/TestComponent.zip)

### Steps to Reproduce

1. Build a new project with the test component.
2. Add the test component to an entity.
3. To the TestSet field add a new value (for example 1)
4. Click on the trash can icon next to the newly added value
5. The editor crashes

### Expected Behavior

The value should be deleted.

### Actual Behavior

The Editor crashes with a segmentation fault.

### Screenshots/Videos

Not applicable.

### Found In Branch

stabilization/2409

### Commit ID From

e3b40afc66e4be90354be5aefac7e16d4606ca29

### Desktop/Device

Device: GIGABYTE AORUS 5 SE
System: Ubuntu 22.04.5 LTS
Windowing system: X11
Ram: 32.0 GiB
Processor: 12th Gen Intel® Core™ i7-12700H × 20
Graphics: NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q]

**Comment by lgleim** [comment]
@arturkamieniecki I am assuming you encounter this issue in the context of a ROS2 gem project. 
The type is used in LidarCore and not reflected to serialization. 
Try adding
`serialize->RegisterGenericType<AZStd::unordered_set<AZ::u32>>(); // register parameter type of 'ConfigureIgnoredCollisionLayers'` to the serialization context.

**Comment by Ulrick28** [comment]
Resolved by PR https://github.com/o3de/o3de/pull/18352

**Comment by nick-l-o3de** [comment]
This is now fixed in both dev and release.
