### ISSUE TITLE
24.09 Release Bug Report：Raster pass with 0 draw items

### ISSUE THREAD

**Issue by khalid-huang** [o3de/o3de#18340]
**Describe the bug**

hello, I added a pass to the mainpipeline, and added the shader configuration to the MainPipeline.materialpipeline. On the 2310.1 version of o3de, the pass node has a "Raster pass with 0 draw items" prompt, and then all attachments are black, but the same code is in 2305 Okay, what could be the reason?
![image](https://github.com/user-attachments/assets/58ce124f-8cdf-4c9c-b94b-02c6b12163e4)

**Comment by jhanca-robotecai** [comment]
Could you please check if this issue is still present in the stabilization branch (to be released in two weeks)?

**Comment by khalid-huang** [comment]
I tried using the stable/2409 branch, but I still couldn’t get any draw items. 

![image](https://github.com/user-attachments/assets/58ce124f-8cdf-4c9c-b94b-02c6b12163e4)

Let me tell you my modifications. 
1. I copy the .azsli and .template files to $O3DE_HOME/Gems\Atom\Feature\Common\Assets\Materials\Pipelines\Common in the engine directory. The template files as floows 
```
{ 
    "Source" : "TEMPLATE_AZSL_PATH",

    "DepthStencilState" :
    {
        "Depth" :
        {
          "Enable" : true,
          "CompareFunc" : "GreaterEqual"
        },
        "Stencil" :
        {
          "Enable" : true,
          "ReadMask" : "0x00",
          "WriteMask" : "0xFF"
        }
    },

    "ProgramSettings":
    {
      "EntryPoints":
      [
        {
          "name": "VertexShader",
          "type": "Vertex"
        },
        {
          "name": "PixelShader",
          "type": "Fragment"
        }
      ]
    },
    "DrawList": "gbufferCapture"
}

```
3. Modify the Gems\Atom\Feature\Common\Assets\Materials\Pipelines\MainPipeline\MainPipeline.materialpipeline file configuration in the engine directory as follows 
```
{
    "shaderTemplates": [
        ...
        // The following content has been added.
        {
            "shader": "../Common/GBufferCapture.shader.template",
            "azsli": "../Common/GBufferCapture.azsli",
            "tag": "gbufferCapture"
        }

    ]
    ...
}
```
4. The configuration of the Gems\Atom\Feature\Common\Assets\Materials\Pipelines\MainPipeline\MainPipelineScript.lua file in the engine directory is as follows
```
function MaterialTypeSetup(context)
    ...
    if(lightingModel == "Standard") then
        ...
         // The following content has been added.
        context:IncludeShader("GBufferCapture")

        return true
    end
    ...
    if(lightingModel == "Enhanced") then
    ...
         // The following content has been added.
        context:IncludeShader("GBufferCapture")

        return true
    end
```
5.  The configuration of the Gems\Atom\Feature\Common\Assets\Materials\Pipelines\Common\ShaderEnable.lua file in the engine directory is as follows:
```
function Process(context)
    ...
       // The following content has been added.
    TrySetShaderEnabled(context, "gbufferCapture", true)
end
```
6.  And There is a passData defined in my pass file as follows:
```
            "PassData": {
                "$type": "RasterPassData",
                "PipelineViewTag": "MainCamera",
                "DrawListTag": "gbufferCapture"
            }
```
