### ISSUE TITLE
I am very frustrated. I just wanted to create a default project, but it crashed and told me it was a problem with cmake, but I have no idea.

### ISSUE THREAD

**Issue by bingbingmasdhg** [o3de/o3de#18351]
I am very frustrated. I just wanted to create a default project, but it crashed and told me it was a problem with cmake, but I have no idea.

Reproduction method
direct construction

Engine version
23.10.3

cmake -B H:/O3DE/Projects/mygimax/build/windows -S H:/O3DE/Projects/mygimax -DLY_3RDPARTY_PATH=H:/.o3de/3rdParty
-- Selecting engine 'H:/O3DE/23.10.3' from 'engine_path' in '<project>/user/project.json'.
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
CMake Error at CMakeLists.txt:32 (project):
Failed to run MSBuild command:
d:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe
to get the value of VCTargetsPath:
Applicable to NET Framework MS-DOS version 17.8.3+195e7f5a3
The start time for generation is September 27, 2024 at 19:36:12.
The project "H:\O3DE\Projects\mygimax\build\windows\MakeFiles\3.30.2\VCTargets Path. vcxproj" on node 1 (default target).
PrepareForBuild:
Structured output has been enabled. The formatting of compiler diagnostics will reflect the error hierarchy. For detailed information, please refer to https://aka.ms/cpp/structured-output .
InitializeBuildStatus:
Executing Touch task on 'x64\Debug\VCTargets Path. tlog\unsuccessful build'.
PostBuildEvent:
echo VCTargetsPath=d:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\
:VCEnd
d:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft. CppCommon. targets (166,5): error MSB3073: Command "echo VCTargetsPath=d:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\[H:\O3DE\Projects\mygimax\build\Windows\MakeFiles\3.30.2\VCTargets Path. vcxproj]
d: Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft. PpCommon. targets (166,5): error MSB3073:: VCEnd "has exited with code -1073741502. [H:\O3DE\Projects\mygimax\build\windows\CMakeFiles\3.30.2\VCTargetsPath.vcxproj]
The operation to generate the project 'H:\O3DE\Projects\mygimax\build\windows\MakeFiles\3.30.2\VCTargets Path. vcxproj' (default target) has been completed - failed.
Generation failed.
H:\O3DE\Projects\mygimax\build\Windows\MakeFiles\3.30.2\VCTargets Path. vcxproj "(default target) (1) ->
(PostBuildEvent Target) ->
d:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft. CppCommon. targets (166,5): error MSB3073: Command "echo VCTargetsPath=d:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\[H:\O3DE\Projects\mygimax\build\Windows\MakeFiles\3.30.2\VCTargets Path. vcxproj]
d: Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft. PpCommon. targets (166,5): error MSB3073:: VCEnd "has exited with code -1073741502. [H:\O3DE\Projects\mygimax\build\windows\CMakeFiles\3.30.2\VCTargetsPath.vcxproj]
0 warnings
1 error
Used time 00:00:01.24
Exit code: 1
-- Configuring incomplete, errors occurred!

**Comment by nick-l-o3de** [comment]
I'm not very familiar with this but it kind of looks like cmake itself is trying to find the visual studio C++ compiler and cannot find it.

From the log, it looks like cmake is trying to use 
```
d:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe
```
and it failed with error code -1073741502 which is actually microsoft error code 0xC0000142, indicating a generic error starting that application, ie, msbuild.
I'm not sure how to diagnose it, one would be to attempt a "repair" on visual studio itself, and also to ensure you have selected the game development workload and included the c/c++ compiler toolchain, which, for some reason, is not enabled by default if you install visual studio with default settings.

**Comment by bingbingmasdhg** [comment]
> I'm not very familiar with this but it kind of looks like cmake itself is trying to find the visual studio C++ compiler and cannot find it.
> 
> From the log, it looks like cmake is trying to use
> 
> ```
> d:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe
> ```
> 
> and it failed with error code -1073741502 which is actually microsoft error code 0xC0000142, indicating a generic error starting that application, ie, msbuild. I'm not sure how to diagnose it, one would be to attempt a "repair" on visual studio itself, and also to ensure you have selected the game development workload and included the c/c++ compiler toolchain, which, for some reason, is not enabled by default if you install visual studio with default settings.

I have found the reason, because my path:
d:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/
Not appearing in the path of the system environment variable.
Firewall and proactive defense also need to be turned off, otherwise the built command-line program will be intercepted by them.
After restarting the computer, I completed the build.
