### ISSUE TITLE
Back out unnecessary fix for a mouse movement/camera issue with remote client (https://github.com/o3de/o3de/issues/18345)

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#18367]
This is an exception request to back out a fix for https://github.com/o3de/o3de/issues/18345 because it is an unnecessary change (There was a setting in the remote client that fixes this)

**Comment by spham-amzn** [comment]
PR: https://github.com/o3de/o3de/pull/18368

**Comment by jhanca-robotecai** [comment]
The release is out, closing the issue again
