### ISSUE TITLE
24.09 Release - Installation failed

### ISSUE THREAD

**Issue by Hotshot5000** [o3de/o3de#18378]
### Bug Description

Windows installation
Previously uninstalled O3DE 23.10 but didn't delete the ~/.o3de folder. Installed O3DE 24.09 but could not get the Multiplayer template to work since it seemed to still use the template for multiplayer from previous install. So I deleted ~/.o3de completely and tried to install again. It seems some settings are still there somehow and installation fails. Logs attached.
[O3DE_20241010220954.log](https://github.com/user-attachments/files/17333873/O3DE_20241010220954.log)

### Assets-Required

None

### Steps to Reproduce

Install O3DE 23.10. Delete manually both the install and ~/.o3de. Try to install 24.09.

### Expected Behavior

Installation to succeed.

### Actual Behavior

Setup fails

### Screenshots/Videos

None

### Found In Branch

Downloaded binary from https://o3debinaries.org/main/Latest/Windows/o3de_installer_2409_0.exe

### Commit ID From

None

### Desktop/Device

HP Omen 16 laptop AMD Ryzen 5800H, Nvidia RTX3070, Windows 11 23H2.

**Comment by Hotshot5000** [comment]
Restarted the PC, ran installer.exe /layout and then the installer.msi for the offline install. Worked perfectly. Also created a project using the multiplayer template and the creation of the project worked (will test server/client tomorrow). Thank you for the support! I will close the ticket then.

**Comment by shor-ofer** [comment]
![image](https://github.com/user-attachments/assets/d939fd49-332c-42fa-ae38-114dfdb1a0bc)

looking at the install log of the msi, it failed for me in the ConfigurePython ->get_python.bat action under the msi.
All the files are already on the disk, and it is almost 100% done.

Action 23:38:49: ConfigurePython. 
CustomAction ConfigurePython returned actual error code 1 (note this may not be 100% accurate if translation happened inside sandbox)
Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action ConfigurePython, location: D:\ofer\O3DE\24.09\, command: "C:\WINDOWS\SysWOW64\cmd.exe" /C set "LY_CMAKE_PATH=D:\ofer\O3DE\24.09\cmake\runtime\bin" && "D:\ofer\O3DE\24.09\python\get_python.bat" 
MSI (s) (20:38) [23:43:42:453]: Product: O3DE -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action ConfigurePython, location: D:\ofer\O3DE\24.09\, command: "C:\WINDOWS\SysWOW64\cmd.exe" /C set "LY_CMAKE_PATH=D:\ofer\O3DE\24.09\cmake\runtime\bin" && "D:\ofer\O3DE\24.09\python\get_python.bat" 

Action ended 23:43:42: InstallFinalize. Return value 3.

When I ran the get_python.bat under CMD, it worked fine. without errors.
