### ISSUE TITLE
24.09 Release - Failed to install O3DE from binary downloads

### ISSUE THREAD

**Issue by egorodet** [o3de/o3de#18376]
### Bug Description

O3DE 24.09 binary [Installer for Windows](https://o3debinaries.org/download/windows.html) fails to install the product with fatal error.

### Assets-Required

N/A

### Steps to Reproduce

1. Download Windows installer https://o3debinaries.org/download/windows.html\
2. Run the installer => installer shows error message and finishes with fatal error.

### Expected Behavior

Product installs successfully.

### Actual Behavior

Fatal error during installation.

### Screenshots/Videos

![O3DE-Install](https://github.com/user-attachments/assets/67fe33d8-0d4d-4829-9401-1aa3557ff124)

![image](https://github.com/user-attachments/assets/a4071893-62fb-40f5-9954-4c2b2414cdf6)

### Found In Branch

N/A

### Commit ID From

N/A

### Desktop/Device

**Desktop**: Microsoft Windows 11 Pro 10.0.22631 Build 22631
**CPU**: Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz, 3600 Mhz, 8 Core(s), 16 Logical Processor(s)
**GPU**: NVIDIA GeForce RTX 2070 SUPER

### Additional Context

See installer log file: [O3DE_20241009230712.log](https://github.com/user-attachments/files/17318290/O3DE_20241009230712.log)

**Comment by Ulrick28** [comment]
Hi! Do you happen to run any kind of anti-virus or have a Dell machine with the killer NIC software installed. I have had similar issues with 3rd party anti-virus and the killer NIC software.

**Comment by stevo26** [comment]
At the moment I have only windows defender. I turned it off but it still gives me the same error.

**Comment by JailbreakPapa** [comment]
@stevo26 Check Control Panel, Under Uninstall Programs. Is there a previous O3DE installation listed? You might have to remove it, then try reinstalling again.

**Comment by amzn-changml** [comment]
From the logs you provided, I noted that installation stops after this step:

```
[2824:1988][2024-10-09T23:13:01]i323: Registering package dependency provider: {CCA3BA73-A399-5126-B789-9F6BB9C66B75}, version: 24.09, package: o3de_24.09
[2824:1988][2024-10-09T23:13:01]i301: Applying execute package: o3de_24.09, action: Install, path: C:\ProgramData\Package Cache\{CCA3BA73-A399-5126-B789-9F6BB9C66B75}v24.09\o3de_24.09.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" INSTALL_ROOT="C:\O3DE\24.09"'
[2824:1988][2024-10-09T23:19:25]e000: Error 0x80070643: Failed to install MSI package.
[2824:1988][2024-10-09T23:19:25]e000: Error 0x80070643: Failed to execute MSI package.
[8514:7080][2024-10-09T23:19:25]e000: Error 0x80070643: Failed to configure per-machine MSI package.
```

A few suggestions that might help:

1. As @JailbreakPapa mentioned, previous versions of O3DE may come in conflict, notably in the `C:\ProgramData\Package Cache\{CCA3BA73-A399-5126-B789-9F6BB9C66B75}v24.09` folder, along with the `C:\o3de` install path. Try uninstalling any previous version, deleting the cache folder, and performing a restart before reinstalling

2. There might be a permissions issue with installing the dependencies that happens during the post-install phase. Verify that your user has administrator privileges

3. During the post-install phase, there is a command window that appears to install dependencies, like Python. Did this window happen to get closed during this process?

**Comment by HydrogenC** [comment]
Also encountered in this problem.

**Comment by egorodet** [comment]
> Hi! Do you happen to run any kind of anti-virus or have a Dell machine with the killer NIC software installed. I have had similar issues with 3rd party anti-virus and the killer NIC software. You can try disabling your anti-virus temporarily during the install and/or disabling the killer software during the install.

Hi @Ulrick28, yes, I had Kaspersky Antivirus installed and running. I've disabled it for the time of O3DE installation and it seemed to help! As the result, installer completed successfully! Afterall it seems like a workaround more than a fix of a real problem, especially if it reproduces with the Windows Defender out of the box. So I'd recommend to investigate it deeper and find a real root-cause and probably fix installation along with antivirus software up and running. Anyway, thank you for the correct suggestion, which helped to install the product!

**Comment by egorodet** [comment]
By the way, I've also tried to install O3DE on the work machine with Windows 10 and enterprise antivirus software. The result was the same as described in the issue - installer failed exactly at the same steps.

**Comment by Ulrick28** [comment]
Which anti-virus software?

**Comment by nick-l-o3de** [comment]
Anti Virus will tend to be picky about what is allowed to run, especially brand new executables only a day old, since a lot of them rely on seeing lots of people install the same binary from the same place with a signature before they cool down and think its ok.

**Comment by Gnumaru** [comment]
I can also reproduce this issue on windows 10. I'm using an administrator account and I have no antivirus installed besides windows defender, wich was disabled during the installation. These are the last lines of the installation log.

```
[2910:38E8][2024-10-10T12:35:42]i301: Applying execute package: o3de_24.09, action: Install, path: C:\ProgramData\Package Cache\{CCA3BA73-A399-5126-B789-9F6BB9C66B75}v24.09\o3de_24.09.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" INSTALL_ROOT="C:\O3DE\24.09"'
[2910:38E8][2024-10-10T12:59:16]e000: Error 0x80070643: Failed to install MSI package.
[2910:38E8][2024-10-10T12:59:16]e000: Error 0x80070643: Failed to execute MSI package.
[2D3C:08FC][2024-10-10T12:59:16]e000: Error 0x80070643: Failed to configure per-machine MSI package.
[2D3C:08FC][2024-10-10T12:59:16]i319: Applied execute package: o3de_24.09, result: 0x80070643, restart: None
[2D3C:08FC][2024-10-10T12:59:16]e000: Error 0x80070643: Failed to execute MSI package.
[2910:38E8][2024-10-10T12:59:16]i318: Skipped rollback of package: o3de_24.09, action: Uninstall, already: Absent
[2D3C:08FC][2024-10-10T12:59:16]i319: Applied rollback package: o3de_24.09, result: 0x0, restart: None
[2910:38E8][2024-10-10T12:59:16]i329: Removed package dependency provider: {CCA3BA73-A399-5126-B789-9F6BB9C66B75}, package: o3de_24.09
[2910:38E8][2024-10-10T12:59:16]i351: Removing cached package: o3de_24.09, from path: C:\ProgramData\Package Cache\{CCA3BA73-A399-5126-B789-9F6BB9C66B75}v24.09\
[2910:38E8][2024-10-10T12:59:17]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{f8199521-fdf1-405c-bc0c-284e50017e57}, resume: None, restart: None, disable resume: No
[2910:38E8][2024-10-10T12:59:17]i330: Removed bundle dependency provider: {f8199521-fdf1-405c-bc0c-284e50017e57}
[2910:38E8][2024-10-10T12:59:17]i352: Removing cached bundle: {f8199521-fdf1-405c-bc0c-284e50017e57}, from path: C:\ProgramData\Package Cache\{f8199521-fdf1-405c-bc0c-284e50017e57}\
[2910:38E8][2024-10-10T12:59:17]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{f8199521-fdf1-405c-bc0c-284e50017e57}, resume: None, restart initiated: No, disable resume: No
[2D3C:08FC][2024-10-10T12:59:17]i399: Apply complete, result: 0x80070643, restart: None, ba requested restart:  No
```

I have no previous version of o3de installed _currently_, but I do have installed all previous version since the first one. I'm doing some tests and I'll edit this with any updates I might get.

**Comment by Ulrick28** [comment]
Sorry your having the issue. I am investigating. Do you have the killer wifi software installed?

**Comment by Ulrick28** [comment]
Try reinstalling. There was a package mismatch on our backend. Let me know your results.

**Comment by Gnumaru** [comment]
Sorry, I was editing the previous post while you answered. I'll try to install again using the web installer.

**Comment by Ulrick28** [comment]
an offline installer located here https://o3debinaries.org/main/Latest/Windows/o3de_installer_2409_0_offline.zip

**Comment by Gnumaru** [comment]
I have tried the web installer and it failed. Now I'll try the offline.

**Comment by FenrirVR** [comment]
Heya,

maybe i have a lead, I noticed that the install at least on my end does something weird on CMAKE and then fail, I have MiniGW 64 installed and also as PATH in the Windows evironment variables, after I removed it from PATH, the installer worked fine.

**Comment by HeadClot** [comment]
> Heya,
> 
> maybe i have a lead, I noticed that the install at least on my end does something weird on CMAKE and then fail, I have MiniGW 64 installed and also as PATH in the Windows evironment variables, after I removed it from PATH, the installer worked fine.

Will give this a shot here in a moment. I think I have minigw installed due to unreal engine as part of its Linux cross compilation. Will report back then.

**Comment by ShaunaGordon** [comment]
Hey folks! Since this is such an intermittent issue (in that many users can install just fine, but a not-insignificant portion can't), can we get some system information?

Some things that I think might help contributors see if there are any patterns and track this issue down include:

- Model of computer
- Version of Windows (or OS in general, but I think it's just a Windows thing), including whether it's Home, Pro, or Enterprise
- The last time Windows update was ran
- Windows user account type
- Antivirus software installed, if any
- Did you have a previous installer version of O3DE installed? 
  - If so, which one and did you uninstall it first?
  - If so, has O3DE ever been installed on that computer under a different user account?
- Do you have another game engine (Unreal, Unity, Godot, etc) installed, or another source of build tools (except Visual Studio) or Python installed?
- What graphics card are you using?
  - Are you using the latest drivers? If not, when did you last update?
- If you rebooted and it didn't work, do you have FastBoot turned on?
  - If so, have you tried turning it off, or powering the computer completely down and restarted that way?

Also, in looking for possible causes of this error, I found a couple of other suggestions for fixing it:

- Restart the Windows Installer Service. Apparently there's a bug in it that can cause this error. (You'd think restarting Windows would do it, but 🤷🏼 )
- Run `sfc /scannow` in an Administrator Command Prompt. Does it find anything?

**Comment by Gnumaru** [comment]
I have tried installing the msi package through the command line to generate a verbose log file using the command ```msiexec.exe /i o3de_24.09.msi  /L*vx install.log```. It failed as normal and generated a 282 thousand lines long log file of 96MB in size =O. One interesting thing to note is that it seems to have failed while (or maybe right after?) using the tar command to extract a zip file containing cmake.

```
MSI (s) (68:EC) [07:56:30:373]: Executing op: ActionStart(Name=ExtractCMake,,)
Action 7:56:30: ExtractCMake. 
MSI (s) (68:EC) [07:56:30:375]: Executing op: CustomActionSchedule(Action=ExtractCMake,ActionType=3106,Source=C:\O3DE\24.09\,Target="C:\Windows\SysWOW64\cmd.exe" /C tar -x -f "C:\O3DE\24.09\Tools\Redistributables\CMake\cmake-3.22.0-windows-x86_64.zip" -C "C:\O3DE\24.09\Tools\Redistributables\CMake",)
MSI (s) (68:CC) [07:56:30:375]: System Environment : Client has accepted UAC prompt
CustomAction ExtractCMake returned actual error code 128 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (68:EC) [07:56:39:816]: Note: 1: 1722 2: ExtractCMake 3: C:\O3DE\24.09\ 4: "C:\Windows\SysWOW64\cmd.exe" /C tar -x -f "C:\O3DE\24.09\Tools\Redistributables\CMake\cmake-3.22.0-windows-x86_64.zip" -C "C:\O3DE\24.09\Tools\Redistributables\CMake" 
MSI (s) (68:EC) [07:56:39:816]: Note: 1: 2205 2:  3: Error 
MSI (s) (68:EC) [07:56:39:816]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1722 
Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action ExtractCMake, location: C:\O3DE\24.09\, command: "C:\Windows\SysWOW64\cmd.exe" /C tar -x -f "C:\O3DE\24.09\Tools\Redistributables\CMake\cmake-3.22.0-windows-x86_64.zip" -C "C:\O3DE\24.09\Tools\Redistributables\CMake" 
MSI (s) (68:EC) [07:57:12:030]: Note: 1: 2205 2:  3: Error 
MSI (s) (68:EC) [07:57:12:030]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (68:EC) [07:57:12:030]: Product: O3DE -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action ExtractCMake, location: C:\O3DE\24.09\, command: "C:\Windows\SysWOW64\cmd.exe" /C tar -x -f "C:\O3DE\24.09\Tools\Redistributables\CMake\cmake-3.22.0-windows-x86_64.zip" -C "C:\O3DE\24.09\Tools\Redistributables\CMake" 

Action ended 7:57:12: InstallFinalize. Return value 3.
```

I'm also attaching the log file

[install.zip](https://github.com/user-attachments/files/17341735/install.zip)

**Comment by Gnumaru** [comment]
I did it 🎉. I had three different sources for tar in my path, one from microsoft at C:/windows/system32, other from git bash and other from cmder (a console application). I have switched the path order so that the system32 tar came before the other ones and that solved the issue. Now I was able to install without errors 😃

![image](https://github.com/user-attachments/assets/7d5a18c8-cbfe-4dfa-8f30-694c018ce36b)

![image](https://github.com/user-attachments/assets/ea830d57-fc07-4adc-8c25-ef1d0a745c4c)

**Comment by FenrirVR** [comment]
Did some retesting and my MiniGW (winlibs.com) installation being the culprit is very reproducable (adding the folder to PATH is enough), the cmake executable that ships with my MiniGW install seem to clash with the installer trying to run the scripts short before the installation is finished, making it fail.

**Comment by HydrogenC** [comment]
> an offline installer located here https://o3debinaries.org/main/Latest/Windows/o3de_installer_2409_0_offline.zip

That's wonderful! Why isn't the link placed on <https://o3debinaries.org/download/windows.html> anyway?

**Comment by amzn-changml** [comment]
> I've never created installers using msi before , but a proper fix for this would probably be forcing the usage of microsoft tar by using `"C:\Windows\SysWOW64\cmd.exe" /C "C:\Windows\System32\tar.exe"` instead of `"C:\Windows\SysWOW64\cmd.exe" /C tar`

Thanks for chasing this down! I've incorporated this into a PR for the next point release (see https://github.com/o3de/o3de/pull/18396) and included some instructions to display debug logs through the `/log` parameter

**Comment by amzn-changml** [comment]
I'm getting reports that there's additional issues with spaces in the %userprofile% path (as in `C:\users\your name\.o3de`) during the initial python venv installation process. We're also looking to solve this in this or another PR

**Comment by amzn-changml** [comment]
This now part of the 23.09.1 release
