### ISSUE TITLE
24.09 Release - Quick Start "Scripts only" project can't be opened as expected

### ISSUE THREAD

**Issue by Andre-LA** [o3de/o3de#18388]
### Bug Description

The Script-Only template doesn't opens the project without Visual Studio installed.

### Assets-Required

No extra assets required

### Steps to Reproduce

1. Click New Project
2. Name your project (e.g. "Project")
3. Select the Quick Start "scripts only" template
4. Click Create Project
5. On My Projects grid, on "Project", click Open Editor

### Expected Behavior

The normal flow of opening a new project (splash screen, assets being processed, then editor opens)

### Actual Behavior

An error popup appears, this error is common for not built projects from Default template, clicking on Ignore doesn't helps.

### Screenshots/Videos

Error pop-up when opening a project:

![image](https://github.com/user-attachments/assets/4889b5cf-a82f-4353-a8cb-c40ef7312a8b)

### Found In Branch

`main` (installed from standalone installer from website)

### Commit ID From

e8570f9

### Desktop/Device

- Device: PC
- OS: Windows 11
- CPU: Intel i7-1165G7
- GPU: NVidia MX 330
- Memory: 16GB

**Comment by nick-l-o3de** [comment]
I have a fix for this already in the point release.
https://github.com/o3de/o3de/pull/18393
but its blocked from merge to dev by another problem (which I also have a fix for)

**Comment by Andre-LA** [comment]
I tested here now by using the 24.09.1 installer given today on Discord, it asks for Ninja if not installed as expected, but after installing ninja, it still asks for Visual Studio installation:

![image](https://github.com/user-attachments/assets/45ce7c00-34d7-4887-8fc6-d5e4903e0abf)

> [!Note]
> I also tried using the steps on an old discord discussion about this:
> - The configure and generate buttons of cmake-gui works, however the build button of project manager doesn't.

**Comment by nick-l-o3de** [comment]
Ah, I see.  It was still checking for VS, but silently.  I'll disable the check.  Incoming PR....

**Comment by Andre-LA** [comment]
Tested today, now the project builds without VS installation as expected, thanks!
