### ISSUE TITLE
Debug Configuration: Link Error Atom_RPI.Public:  LNK1189 library limit of 65535 objects exceeded

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#18409]
**Describe the bug**
On Windows, The Editor can not compile in **Debug** configuration because the Linker fails on `Atom_RPI.Public`:
```
LNK1189 library limit of 65535 objects exceeded
```

**Assets required**
N/A

**Steps to reproduce**
Try to compile the `Editor` or `Atom_RPI.Public` target in `debug` configuration.

**Expected behavior**
The `Editor` or `Atom_RPI.Public` targets compile and link successfully.

**Actual behavior**
Linker Error: LNK1189 library limit of 65535 objects exceeded

**Screenshots/Video**
N/A

**Found in Branch**
`development`

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
commit febad954207d42f196a5010c2d9923b7e5be21d2 (HEAD -> development, origin/development)
Author: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>
Date:   Fri Oct 18 11:34:14 2024 -0700

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen Threadripper 3970X 32-Core Processor    3.70 GHz
 - GPU NVidia RTX 4090 (24GB VRAM). Studio Driver Version 546.01
 - Memory 128GB
 - Storage: WD_BLACK 2TB SN850 NVMe M2 SDD PCIe 4.0

**Additional context**
Most likely caused by this PR: https://github.com/o3de/o3de/pull/18315

**Comment by mprettner-huawei** [comment]
Proposed fix in #18410.
