### ISSUE TITLE
Sky Atmosphere does not work with render to texture camera

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#18473]
**Describe the bug**
The O3DE camera can render to a texture. Unfortunately, there is a limitation of feature processors that can be used. It is not beneficial for simulation usecases (e.g. low light outdoor scenarios)
**Assets required**

https://gist.github.com/michalpelka/2bc19beb566c7a2ea869c064de4dbfed

**Steps to reproduce**
1. Create a camera
2. Create render target 
3. Set "Render to a texture" and apply render target
4. Display a render target as material or UI canvas.

**Expected behavior**
Sky atmosphere is rendered to a texture.

**Actual behavior**
Sky atmosphere is not rendered to a texture.

**Screenshots/Video**
![image](https://github.com/user-attachments/assets/4bffa43e-f5e7-4581-85b7-52094810f9e9)
**Found in Branch**
2409.0

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
e8570f9d635c0abbf3d733d0524a3c0ae75d726c (HEAD, tag: 2409.0, origin/main)

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Ubuntu]
 - Version [22.04]
 - CPU [13th Gen Intel(R) Core(TM) i9-13900K]
 - GPU [RTX 4080]
 - Memory [96GB]

**Additional context**
It does not work on Windows using DirectX.

**Comment by moudgils** [comment]
I am nopt aware of any explicit reasons why SkyBox wouldnt render to the texture. It seems like a bug.
