### ISSUE TITLE
[Linux] Current development branch hangs computer when opening level

### ISSUE THREAD

**Issue by yaakuro** [o3de/o3de#18543]
**Describe the bug**

When opening a level the O3DE hangs the whole computer and a hard reset is needed.

**Steps to reproduce**
1. Checkout the commit point: 7162989dd177946eebe0dcc5fdc7a7db846b72c4 (might also be earlier versions)
2. Open Level in Editor
3. See hang of the computer. At least on my computer.

**Expected behavior**
Not to hang the whole computer and open the level.

**Desktop/Device (please complete the following information):**

OS: KDE neon 6.2 x86_64 
Kernel: 6.8.0-45-generic 
Resolution: 1920x1080, 1920x1080 
DE: Plasma 6.2.3 
WM: KWin 
CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz 
GPU: AMD ATI Radeon RX 6950 XT 
Memory: 20905MiB / 128712MiB 

Vulkan Instance Version: 1.3.296
deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
deviceName         = AMD Radeon RX 6950 XT (RADV NAVI21)
driverID           = DRIVER_ID_MESA_RADV
driverName         = radv
driverInfo         = Mesa 24.2.4 - kisak-mesa PPA

**Actual behavior**
Not to hang the computer.

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Commit Point: 7162989dd177946eebe0dcc5fdc7a7db846b72c4

**Comment by spham-amzn** [comment]
This is more likely caused by the specific card or graphics driver. It may the related to your MESA drivers specifically and not anything that O3DE is doing in general.

**Comment by yaakuro** [comment]
Can be, but when checking out 15854a679245b5819b48736bb5f4edd6e6c5eede doesn't crash with the same driver.

**Comment by yaakuro** [comment]
So this commit: 4ad3b5609c2981a81fac83dccfdcb87e71c26803. is causing my computer freeze using the same driver. using anything before works with my drivers.

**Comment by byrcolin** [comment]
@yaakuro I don't think we can accept this at the moment. I think we need more information. From our experience this is a driver issue and if so there is not much we can do about it. I think there is a slightly newer driver you can try and see if you still have the problem. It is interesting but not tell tale that it doesn't happen at a different commit on the same driver, the problem could be coming from a different path of logic, one avoided by the previous commit... its hard to say.

**Comment by yaakuro** [comment]
Ok, I will close this. Might be that this appears only on my system. I will try to do a full Mesa update for my AMD 6950 XT and put an update here in this thread.
