### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#1866]
As a developer, I want to be able to install and configure O3DE projects without needing to download and install the code from source. This will allow me to get started in-engine more quickly, without needing to set up a specific development environment on my machine.

**Comment by kittenz** [comment]
Isn't there an installer in `cmake\Packaging.cmake` already?

**Comment by olegbc1** [comment]
@kittenz sure is! We'll release the binaries in a few weeks so folks don't have to build the engine. Stay tuned!

**Comment by hlfl1l1** [comment]
希望能有自动更新功能

**Comment by WashedUpStudio** [comment]
hlfl1l1 ;
我不认为它会立即消失，但最终它可能成为安装程序中的一个功能。

**Comment by jiangwenming2021** [comment]
how about the progress now?

**Comment by HeadClot** [comment]
Any news on this?

**Comment by Mobs1024** [comment]
@HeadClot https://github.com/o3de/sig-release/blob/main/meetings/notes/2021%20-%20August%2018 when I don't know, probably 3-4 quarter this year there will be an o3de installer for windows

**Comment by olegbc1** [comment]
We are working hard on getting O3DE out of the developer preview so folks other than engineers can put it to meaningful use. Installer is part of this effort. 

One way to get access to a nightly installer build is to sign up for the [upcoming O3DE game jam.](https://itch.io/jam/o3de-jam-1). We will be making an experimental installer available shortly before it starts on October 18th. So if you like to tinker - please sign up for the jam and [join O3DE discord](https://discord.gg/xNb2q4SJKJ).

**Comment by HeadClot** [comment]
> We are working hard on getting O3DE out of the developer preview so folks other than engineers can put it to meaningful use. Installer is part of this effort.
> 
> One way to get access to a nightly installer build is to sign up for the [upcoming O3DE game jam.](https://itch.io/jam/o3de-jam-1). We will be making an experimental installer available shortly before it starts in October. So if you like to tinker - please sign up for the jam and [join O3DE discord](https://discord.gg/xNb2q4SJKJ).

Just signed up for the jam for the nightly installer builds :)

**Comment by olegbc1** [comment]
With 21.11 releasing today, Windows installer is now available at: https://o3debinaries.org/download/windows.html. Linux package file [here](https://o3debinaries.org/download/linux.html). Give it a try and let us know what you think!
