### ISSUE TITLE
Viewport camera manipulation doesn't work with tablets

### ISSUE THREAD

**Issue by darbyjohnston** [o3de/o3de#1889]
With the mouse you can pan the viewport with the middle button and rotate it with the right button. Unfortunately this does not work with a Wacom tablet with the pen buttons mapped to middle and right mouse buttons.

According to the Qt documentation, if tablet events are not handled specifically they are treated as mouse events, so it seems like this should work:
https://doc.qt.io/qt-5/qtabletevent.html
"Qt will first send a tablet event, then if it is not accepted by any widget, it will send a mouse event. This allows users of applications that are not designed for tablets to use a tablet like a mouse."

I tried enabling "Stylus Mode" in the "Edit/Editor Settings/Global Preferences..." but that did not seem to help.

1. Setup a Wacom tablet with the pen buttons set to mouse left and right buttons (see screenshot below)
2. Middle click in the viewport to pan the camera

![WacomTabletProperties](https://user-images.githubusercontent.com/8532558/124685274-c8741700-de85-11eb-9d13-c9119e7c3b12.PNG)

 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Ryzen 1700
 - GPU AMD Radeon Pro WX 3200
 - Memory 32GB
 - Wacom Intuos PT M

**Comment by hultonha** [comment]
Hi @darbyjohnston,

Thanks for reporting this! This is definitely a blind spot where we haven't been testing. Can I ask what branch/version you're using? If you're building from source we've enabled a new camera in our `development` branch which might be worth trying. We also have a new change incoming soon (to `development`) that updates how we handle input in the viewport which might also address this issue (using Qt directly instead of relying on the native input system).

I'll ping this thread when I know the changes are in and you could give it another try. If that doesn't work we'll have to prioritize this accordingly, it would definitely be great to get this working!

Thanks for the report!

Cheers,

Tom

**Comment by darbyjohnston** [comment]
Hi Tom, sorry for not including the branch, it was the default "development" branch, compiled with VS 2019 following the steps on the GitHub page.

Is there anything I need to do to enable the new camera in the "development" branch? Otherwise I would be happy to test with the upcoming changes.

**Comment by hultonha** [comment]
No worries at all @darbyjohnston, thanks for confirming.

You _should_ already have the new camera on by default now (it's turned on in `development` but not in `stabilization/2106`). This PR https://github.com/o3de/o3de/pull/1422 has the Qt change to forward events to the camera which I'm _hopeful_ might solve your problem. If it doesn't we'll have to try and debug it but there's a chance this might work. @NicholasVanSickle (the author of the PR I mentioned) might have a gut feeling too.

This change should hopefully get merged later today so not too long to wait 🙂

**Comment by darbyjohnston** [comment]
Hi @hultonha, it looks like the PR was merged so I tried syncing and building, but unfortunately the tablet buttons are still not working.

I tried running the editor in the debugger and the tablet buttons are being properly recognized by Qt, I can see them in the QtViewport mouse events. Though it looks like the Qt mouse events are also being filtered and passed onto QtEventToAzInputMapper which I haven't dug to far into yet.

**Comment by darbyjohnston** [comment]
Doing a bit more troubleshooting it looks like the camera is still using some events directly from the system mouse instead of Qt; for example if I put a breakpoint at CameraInput.cpp:755, it breaks when I move the mouse over the viewport but not when I move the tablet. I think this is due to these lines in QtEventToAzInputMapper::HandlesInputEvent:
```
        if (channelId == AzFramework::InputDeviceMouse::Movement::X || channelId == AzFramework::InputDeviceMouse::Movement::Y)
        {
            return false;
        }
```

Which looks like the QtEventToAzInputMapper is explicitly not handling the mouse movement events?

**Comment by hultonha** [comment]
Thanks for following up on this @darbyjohnston! Perhaps @NicholasVanSickle might be able to weigh in on this one.

I would have assumed the tablet input events would have mapped to mouse events as well but it's interesting that's not the case. Are you able to see what `channelId` is passed in? Or what's in `channelId`? (if you disable optimizations in that file using `#pragma optimize("", off)` at the top you should be able to see the values in the debugger.

We might need to revisit this to make it more resilient to different sorts of input, @NicholasVanSickle might be able to explain why that snippet you added is required. I'll see if we can catch-up about it later and let you know what the outcome is 👍

**Comment by NicholasVanSickle** [comment]
Ah, yes, we did have an explicit exception for mouse movement X and Y in the `QtEventToAzInputMapper` - this was to allow smoother camera movement, as our internal framework does a mouse movement speed calculation based on how far the cursor has physically moved, not just the physical delta. This measurement unit, as a bit of trivia I was unaware of prior to implementing this, is called a "mickey" and it's meant to make viewport camera movement feel more smooth.

As this is both a behavioral regression and our one non-Qt source of viewport input, I think I'm going to go ahead and map these events from Qt as well - it should be straightforward, as I had this working in an earlier version of the input mapper.

**Comment by bosnichd** [comment]
> Ah, yes, we did have an explicit exception for mouse movement X and Y in the `QtEventToAzInputMapper` - this was to allow smoother camera movement, as our internal framework does a mouse movement speed calculation based on how far the cursor has physically moved, not just the physical delta. This measurement unit, as a bit of trivia I was unaware of prior to implementing this, is called a "mickey" and it's meant to make viewport camera movement feel more smooth.

Slight clarification just to clear up any potential confusion (spoke with Nick already and he suggested posting here for anyone else that's following); the 'mickey' unit is the 'raw' physical delta obtained directly from the mouse driver ([one mickey is the smallest resolvable distance that can be detected by the hardware](https://en.wikipedia.org/wiki/List_of_humorous_units_of_measurement#Mickey)). The OS (Windows or macOS, not sure if Linux does it also) interprets the 'raw' movement and applies smoothing to it such that the OS system cursor doesn't move 1:1 with the 'mickeys' being read in from the mouse, but rather makes it feel smoother. These are two good articles about it:
https://blog.codinghorror.com/mouse-ballistics/
https://www.microsoft.com/whdc/device/input/pointer-bal.mspx

Our internal input framework doesn't do any calculations, it just reports the 'raw' movement via the InputDeviceMouse::Movement::X and InputDeviceMouse::Movement::Y input channels, along with the normalized cursor position as reported by the OS after ballistics/smoothing has been applied via the InputDeviceMouse::SystemCursorPosition input channel.

**Comment by darbyjohnston** [comment]
Hi, I just tried out the latest code and my tablet now works for camera manipulation, thanks!

**Comment by hultonha** [comment]
That's great to hear @darbyjohnston, thank you for letting us know! And thanks @NicholasVanSickle and @alexmontAmazon for fixing it! 😄
