### ISSUE TITLE
will there be a future Linux installer of all distributions without a compiler

### ISSUE THREAD

**Issue by Mobs1024** [o3de/o3de#1896]
Example of Godot Engine and Unity they install a program for Linux no compiler to quickly launch the editor on Linux it will be easier

looking forward to #746 

despite the market share of Linux 6% + to the whole world, I really love Linux ))

**Comment by slapin** [comment]
Would be happier to get more or less clear Linux build first, then installer will be a piece of cake. Also the market share depends on availability of professional software - the more the better.
