### ISSUE TITLE
Set up and Instructions for building under Linux.

### ISSUE THREAD

**Issue by slapin** [o3de/o3de#1900]
**Describe the bug**
Current documentation and README describe only Windows build instructions
making some of us spend lots of time figuring out how to even start building under Linux.
As I guess some people might want to try it would be nice to have some (probably unofficial) instruction
for ones who want to try and contribute to Linux support.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Debian GNU/Linux]
 - Version [Bullseye/testing]
 - CPU [i7 2600k/Xeon 2678 v3]
 - GPU [Nvidia GTX660/GTX1060]
 - Memory [16GB/128GB]

**Comment by Mobs1024** [comment]
see https://o3de.org/docs/user-guide/platforms/linux/ I don't know if they work or not under ubuntu, but other distros need an experiment

**Comment by slapin** [comment]
Looks like it can't detect clang because it finds gcc (why no support building with gcc I wonder?)
```
slapin@dual:~/o3de$ ../cmake-3.21.0-rc2-linux-x86_64/bin/cmake -B build -S . -DLY_3RDPARTY_PATH=$(pwd)/3rdparty-cache -DLY_UNITY_BUILD=ON  -DCMAKE_INSTALL_PREFIX=/home/slapin/o3de/install
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/Platform/Linux/PAL_linux.cmake:31 (message):
  Compiler GNU not supported in Linux
Call Stack (most recent call first):
  cmake/PAL.cmake:238 (include)
  CMakeLists.txt:27 (include)
```
This particular problem is worked around by setting the following define: -DCMAKE_CXX_COMPILER_ID=Clang

**Comment by Mobs1024** [comment]
yeah and mine too #1904

**Comment by slapin** [comment]
Next problem is because Python is built against libffi.so.6 and latest debian does not have that in repos but it can be downloaded from http://ftp.us.debian.org/debian/pool/main/libf/libffi/libffi6_3.2.1-9_amd64.deb and requires no dependencies (ode3d might benefit from creating docker container with dependencies to fight things like that or allow building python from source).
(I'm on debian testing).

**Comment by slapin** [comment]
Another problem is with detecting threads support ```
slapin@dual:~/o3de$ ../cmake-3.21.0-rc2-linux-x86_64/bin/cmake -B build -S . -DCMAKE_CXX_COMPILER_ID=Clang -DLY_3RDPARTY_PATH=$(pwd)/3rdparty-cache -DLY_UNITY_BUILD=ON  -DCMAKE_INSTALL_PREFIX=/home/slapin/o3de/install
-- Using package /home/slapin/o3de/3rdparty-cache/packages/qt-5.15.2-rev4-linux
-- Using package /home/slapin/o3de/python/runtime/python-3.7.10-rev2-linux
-- Using Python 3.7.10 at /home/slapin/o3de/python/runtime/python-3.7.10-rev2-linux/python/bin/python
-- Python: linking /home/slapin/o3de/Tools/LyTestTools into python site-packages...
-- Python: linking /home/slapin/o3de/Tools/RemoteConsole/ly_remote_console into python site-packages...
-- Python: linking /home/slapin/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools into python site-packages...
-- Python: linking /home/slapin/o3de/scripts/o3de into python site-packages...
-- Using package /home/slapin/o3de/3rdparty-cache/packages/RapidJSON-1.1.0-multiplatform
-- Using package /home/slapin/o3de/3rdparty-cache/packages/Lua-5.3.5-rev5-linux
-- Using package /home/slapin/o3de/3rdparty-cache/packages/RapidXML-1.13-multiplatform
-- Using package /home/slapin/o3de/3rdparty-cache/packages/zlib-1.2.8-rev2-multiplatform
-- Using package /home/slapin/o3de/3rdparty-cache/packages/zstd-1.35-multiplatform
-- Using package /home/slapin/o3de/3rdparty-cache/packages/cityhash-1.1-multiplatform
-- Using package /home/slapin/o3de/3rdparty-cache/packages/googletest-1.8.1-rev4-linux
-- Using package /home/slapin/o3de/3rdparty-cache/packages/googlebenchmark-1.5.0-rev2-linux
-- Using package /home/slapin/o3de/3rdparty-cache/packages/md5-2.0-multiplatform
-- Using package /home/slapin/o3de/3rdparty-cache/packages/lz4-r128-multiplatform
-- Using package /home/slapin/o3de/3rdparty-cache/packages/SQLite-3.32.2-rev3-multiplatform
-- Using package /home/slapin/o3de/3rdparty-cache/packages/OpenSSL-1.1.1b-rev2-linux
CMake Error at /home/slapin/cmake-3.21.0-rc2-linux-x86_64/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /home/slapin/cmake-3.21.0-rc2-linux-x86_64/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/slapin/cmake-3.21.0-rc2-linux-x86_64/share/cmake-3.21/Modules/FindThreads.cmake:238 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  3rdparty-cache/packages/OpenSSL-1.1.1b-rev2-linux/FindOpenSSL.cmake:29 (find_package)
  cmake/LYWrappers.cmake:426 (find_package)
  cmake/LYWrappers.cmake:219 (ly_parse_third_party_dependencies)
  Code/Framework/AzNetworking/CMakeLists.txt:11 (ly_add_target)


-- Configuring incomplete, errors occurred!
See also "/home/slapin/o3de/build/CMakeFiles/CMakeOutput.log".
See also "/home/slapin/o3de/build/CMakeFiles/CMakeError.log".
```
which looks a bit weird. Also this version of OpenSSL might be vulnerable unless patched to CVEs and should probably be replaced by 1.1.1j...

**Comment by slapin** [comment]
Fixed that by adding the following options to command line: -DCMAKE_THREAD_LIBS_INIT="-lpthread" -DCMAKE_USE_PTHREADS_INIT=1

**Comment by slapin** [comment]
Stumbled upon the following for now:
```
'/home/slapin/cmake-3.21.0-rc2-linux-x86_64/bin/cmake' '-E' 'tar' 'xf' '/home/slapin/o3de/3rdparty-cache/downloaded_packages/unwind-1.2.1-linux.tar.xz'
-- Installed And Validated package at /home/slapin/o3de/3rdparty-cache/packages/unwind-1.2.1-linux - OK
-- Using package /home/slapin/o3de/3rdparty-cache/packages/unwind-1.2.1-linux
-- Configuring done
CMake Error in Code/Framework/AzQtComponents/CMakeLists.txt:
  No known features for CXX compiler

  "Clang"

  version .
```
Looks like some cmake script misbihaves somewhere...

**Comment by slapin** [comment]
proper cmake command line
```
cmake -B build -S . -DCMAKE_THREAD_LIBS_INIT="-lpthread" -DCMAKE_USE_PTHREADS_INIT=1 -DLY_3RDPARTY_PATH=/home/slapin/o3de/3rdparty-cache -DLY_UNITY_BUILD=ON  -DCMAKE_INSTALL_PREFIX=/home/slapin/o3de/install -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
```

**Comment by lumberyard-employee-dm** [comment]
For configuring on Linux, I normally set up a shell script to ease with the boilerplate of providing all the command line arguments

### generate_linux.sh
```
#!/bin/bash
CMAKE_CXX_COMPILER=clang++
CMAKE_C_COMPILER=clang
LY_3RDPARTY_PATH=~/3rdParty
LY_PROJECTS="AutomatedTesting"
SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})
# Run cmake configure
cmake -B ${SCRIPT_DIR}/o3de/build/linux_ninja -S ${SCRIPT_DIR}/o3de -G"Ninja Multi-Config" -DLY_3RDPARTY_PATH=${LY_3RDPARTY_PATH} -DLY_PROJECTS="${LY_PROJECTS}" "$@"
```

**Comment by amzn-pratikpa** [comment]
@slapin - is building on Linux still an issue for you?

**Comment by lumberyard-employee-dm** [comment]
This is still an issue. If a user is using libssl 1.10 or above because they are on a newer Linux distribution than Ubuntu 20.04 LTS, then it tries to use the O3DE 3rdParty openssl instead of the OS openssl, which causes an undefined symbol due to 3rdParty openssl being older:
I have filed a ticket for it here https://github.com/o3de/o3de/issues/4898
