### ISSUE TITLE
Bug Report: Release tarballs don't include git LFS files

### ISSUE THREAD

**Issue by mohkale** [o3de/o3de#1919]
**Note**: this issue doesn't fit the form of a bug in the code so I've disregarded the original issue template.

See [git-lfs#3877](https://github.com/git-lfs/git-lfs/issues/3877).

The gist of it is that the automated tarballs for release generated by github don't include any git LFS files. I just tried curling the latest release and it lacked any of the binary files checked into git lfs, instead each such file was just a plain text file with the regular git-lfs format.

Please release tarballs including these files.

**Comment by amznestebanpapp** [comment]
FYI @AMZN-alexpete @brianherrera

**Comment by brianherrera** [comment]
@amzn-changml Since I think he created the latest release.

**Comment by AMZN-alexpete** [comment]
Yup, this is a known issue and I'm not seeing a way to modify the source archives in the release so it will have to be a separate files in the release.

I'm thinking it'd be nice to have the following additional archives:
- LFS (zip)
- LFS (tar.gz)
- Source code with LFS (zip)
- Source code with LFS (tar.gz)

**Comment by AMZN-alexpete** [comment]
A fun note about this but this will push our archives over the [2GB GitHub release file limit](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas) so I'll be splitting up the archives.

**Comment by AMZN-alexpete** [comment]
LFS only archives have been added to the [2701.1 release page](https://github.com/o3de/o3de/releases/tag/2107.1).  Will upload the Source code and with LFS archives next.

**Comment by amznestebanpapp** [comment]
> LFS only archives have been added to the [2701.1 release page](https://github.com/o3de/o3de/releases/tag/2107.1). Will upload the "Source code with LFS" archives next.

Any reason to name them "2107.1-lfs" instead of "2107.1"?

**Comment by AMZN-alexpete** [comment]
> Any reason to name them "2107.1-lfs" instead of "2107.1"

The archives that GitHub creates automatically for us are called 2107.1 (https://github.com/o3de/o3de/archive/refs/tags/2107.1.zip) and so I added the -lfs suffix, but I'm open to suggestions if there's a better name option.

**Comment by amznestebanpapp** [comment]
> > Any reason to name them "2107.1-lfs" instead of "2107.1"
> 
> The archives that GitHub creates automatically for us are called 2107.1 (https://github.com/o3de/o3de/archive/refs/tags/2107.1.zip) and so I added the -lfs suffix, but I'm open to suggestions if there's a better name option.

Is there a way to delete the previous files? or are we always going to have the ones without lfs and the ones with lfs?
My suggestion is to drop the `-lfs` suffix and have e.g. `2107.1` be the name with lfs files inside.
I dont see a scenario where someone wants to download the source code and then pull the lfs files. If they are willing to pull the lfs files, they are likely willing to checkout the repo from github.

**Comment by AMZN-alexpete** [comment]
> Is there a way to delete the previous files? or are we always going to have the ones without lfs and the ones with lfs?

I do not see a way to remove the automatically generated release archives or over-write them, but perhaps we can adjust the .gitattributes somehow.

**Comment by AMZN-alexpete** [comment]
I'm testing the option to auto-add LFS files to the default source archives, but wanted to close out this issue because the remaining archives have been added to the release.  I'll update this issue with the results of the testing.

**Release files**
```
2107.1-lfs.tar.gz.aa 1000 MB
2107.1-lfs.tar.gz.ab 1000 MB
2107.1-lfs.tar.gz.ac 106 MB
2107.1-lfs.z01 1000 MB
2107.1-lfs.z02 1000 MB
2107.1-lfs.zip 109 MB
2107.1-source-and-lfs.tar.gz.aa 1000 MB
2107.1-source-and-lfs.tar.gz.ab 1000 MB
2107.1-source-and-lfs.tar.gz.ac 144 MB
2107.1-source-and-lfs.z01 1000 MB
2107.1-source-and-lfs.z02 1000 MB
2107.1-source-and-lfs.zip 
```

**Comment by AMZN-alexpete** [comment]
Unfortunately, my tests showed that GitHub does not download LFS files from external sources defined in .lfsconfig files even if the option to add them to archives is enabled:
![GitHubLFSArchives](https://user-images.githubusercontent.com/26804013/125998371-20708b71-5f74-4735-9ab4-db8d476a9da8.JPG)

**Comment by amznestebanpapp** [comment]
> Unfortunately, my tests showed that GitHub does not download LFS files from external sources defined in .lfsconfig files even if the option to add them to archives is enabled:
> ![GitHubLFSArchives](https://user-images.githubusercontent.com/26804013/125998371-20708b71-5f74-4735-9ab4-db8d476a9da8.JPG)

Maybe a ticket to github? It can be something we are missing

**Comment by AMZN-alexpete** [comment]
I've opened a ticket with GitHub Support and will update this issue when I get a response

**Comment by AMZN-alexpete** [comment]
Response from GitHub Support is that only LFS files from the GitHub application are supported.  So, I requested 3 new features:

1. As a user, I'd like the GitHub application to support including LFS files from an external service specified in the .lfsconfig file if it doesn't require authentication credentials - that is, retrieving the files from the LFS service does not require any authentication. Our LFS service does not require authentication so if the GitHub application used the same logic to fetch the LFS files as the git lfs client does, it could do so without authenticating.
2. As a user, I'd like the comments on the settings page to indicate that only LFS files stored in the GitHub application will be included in release files - not LFS files stored in an external service.
3. As a user, I'd like the GitHub documentation to indicate that only LFS files stored in the GitHub application will be included in release files - not LFS files stored in an external service.

And GitHub Support reponse:

> I've created an internal issue for consideration by the engineering team with your 3 feature requests. I can't give any indication as to whether these requests will be implemented, but can advise checking our Public Roadmap for a high level overview of the current developments and their planned release schedule and also watching our GitHub Blog in general and our Changelog in particular to stay up to date with new features, changes, bug fixes and security issues.
