### ISSUE TITLE
LoadLevel Console Command Requires Full Asset Path Instead of Level Name

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#1948]
**Describe the bug**
The LoadLevel console command requires the full asset path instead of accepting a simple level name.
It's common for users to only provide the level name, but not the full asset path
Example: "MyLevel" instead of "Levels/MyLevel/MyLevel.spawnable"

**To Reproduce**
1. Open a GameLauncher.exe
2. Open the console
3. Type console command LoadLevel <your_level_name_here>, but instead of providing a full cache asset path, just pass the name of your level as you'd find it in the level folder
Example:
    LoadLevel MyLevel
      _not_
    LoadLevel Levels/MyLevel/MyLevel.spawnable

**Expected behavior**
MyLevel should load

**Desktop/Device (please complete the following information):**
 - Device:PC

**Comment by bydwaja4** [comment]
Most of the time I used "open my map" to get mixed results, it just opened the same level as it. In fact, I don’t remember how many weeks it lasted. Should all the cards be in one? Folder or what?

**Comment by AMZN-Gene** [comment]
I think it may be possible (eventually) for levels to live in any folder since levels are really just spawnable prefabs, but the standard template uses a Levels/ folder.  Should make sense to look inside the Level/ folder first if the string passed into LoadLevel isn't actually a true asset path.

**Comment by AMZN-Gene** [comment]
https://github.com/o3de/o3de/pull/1952

**Comment by AMZN-Gene** [comment]
Waiting for Jenkins Automated Review approval before merging. See https://github.com/o3de/o3de/pull/1952
