### ISSUE TITLE
Asset Processor crash on long project names

### ISSUE THREAD

**Issue by fabioanderegg** [o3de/o3de#1962]
**Describe the bug**
The asset processor crashes when using a long project name.

**To Reproduce**
1. Create a new project in the Project Manager with a long name, e.g. `TestProjectWithAVeryLongName`
2. Compile the Project Manager
3. Click start Editor

Asset Processor will start to process some assets, but crashes after a short while.

Screenshot of stack trace:
https://i.imgur.com/pbc5mkl.png

**Expected behavior**
Asset Processor not crashing.

**Additional context**
SDK build of the `development` branch, commit `ec026963b8a6440b755aecd622864e43b0603c48`.

**Comment by lumberyard-employee-dm** [comment]
The Maximimum length of a project name should be 64 characters, but the SettingsRegistry Specialization class which adds the Project Name as a tag sets it's buffer to only be [32 characters](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Settings/SettingsRegistry.h#L49-L55)

I believe we should update that to 64 characters, as well as to limit users from typing in Projects with a name longer than 64-characters
