### ISSUE TITLE
Update Jenkins Linux fleet to Ubuntu20/clang12

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#1976]
Currently we run Ubuntu18 with clang-6.0 on Jenkins. There is a fix that was merged to `development` (#833) and is about to be cherry picked to `stabilization/2106` (#1947) to fix a clang-12 warning (as error).

We should update the Linux fleet to clang-12 to avoid regressions. However, we need to:

1. Check that all the distros being currently used have packages for clang-12
2. Ubuntu18 does not have packages for clang-12 so we would have to update it to Ubuntu20 (which could have some implications on other dependencies)

**Comment by amzn-changml** [comment]
Once #3727 goes through, the label for using this will be `linux-707531fc7`

**Comment by amzn-changml** [comment]
As #5035 is passing CI tests, we're ready to have all Linux builds to use this fleet config. The label will be used for all future builds once updated in `pipeline.json`
