### ISSUE TITLE
CMake fails when using folder with special characters

### ISSUE THREAD

**Issue by hgouveia** [o3de/o3de#1986]
**Describe the bug**

CMake fails when the folder contains special character that are wrongly interpreted when using REGEXP

**To Reproduce**
1. clone the repository inside a folder ex : `d:/c++/o3de`
2. follow the steps to generate the visual solution : https://o3de.org/docs/welcome-guide/setup/setup-from-github/
3. ex: `cmake -B  build/windows_vs2019  -G "Visual Studio 16" -DLY_3RDPARTY_PATH=../o3de-packages -DLY_UNITY_BUILD=ON -DLY_PROJECTS=AutomatedTesting `

**Expected behavior**
CMake should work with any valid windows file system folder

**Screenshots**
this is just a brief output since this repeat multiples taimes
Terminal output: 

```batch
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
CMake Error at cmake/PAL.cmake:211 (string):
  string sub-command REGEX, mode MATCH failed to compile regex
  "D:/Programacion/C++/Others/o3de/o3de-sources/Platform/([^/]*)/?(.*)$".
Call Stack (most recent call first):
  cmake/PAL.cmake:229 (ly_get_absolute_pal_filename)
  Gems/WhiteBox/Code/CMakeLists.txt:9 (ly_get_list_relative_pal_filename)


CMake Error at cmake/PAL.cmake:230 (file):
  file RELATIVE_PATH must be passed a full path to the file: /
Call Stack (most recent call first):
  Gems/WhiteBox/Code/CMakeLists.txt:9 (ly_get_list_relative_pal_filename)
```` 

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS:  Windows
 - Version 10 Pro
 - CPU: Ryzen 7 1800X
 - GPU: Nvidia GTX 1060
 - Memory: 16GB

**Additional context**
after move the source to a folder without special character, it worked ex: `D:/o3de/o3de-sources/`

**Comment by lumberyard-employee-dm** [comment]
@amznestebanpapp @AMZN-ScottR It looks like we need to escape the LY_ROOT_FOLDER when supplying it to REGEX MATCH calls in [PAL.cmake](https://github.com/o3de/o3de/blob/development/cmake/PAL.cmake#L209-L211)

There are also a couple of other places in that file where an `${object_path}` variable is being supplied to a REGEX MATCH call.
They at [here](https://github.com/o3de/o3de/blob/development/cmake/PAL.cmake#L186-L188) and [here](https://github.com/o3de/o3de/blob/development/cmake/PAL.cmake#L160-L162)

This also brings to light that we need to be cognizant of passing paths as part of the regular expressions itself.

**Comment by lumberyard-employee-dm** [comment]
I think a good solution is to use the CMake 3.20 new [cmake_path(IS_PREFIX)](https://cmake.org/cmake/help/latest/command/cmake_path.html#is-prefix) command to first filter out root portion of the path and then use the remaining part of the regex

**Comment by amznestebanpapp** [comment]
yeah, that sounds a bit better, however, if we need to pass regexes in other places would be better to just create an "escape path for regex" function and apply the same everywhere is being used
