### ISSUE TITLE
Actor Skeleton offset from mesh.

### ISSUE THREAD

**Issue by WashedUpStudio** [o3de/o3de#2005]
**Describe the bug**
Skeleton is offset from the mesh.
**To Reproduce**
1. Go to 'Go to an actor with a full skeleton with root bone one the ground.'
2. Click on 'show skeleton on the actor component'
3. See error

**Expected behavior**
When importing an fbx with a skeleton and setting up an actor the skeleton should be in the same spot you exported it like in your modeling program.
**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I5-8400]
 - GPU [NVidia 1080ti]
 - Memory [16GB]

**Additional context**

**Comment by amzn-rhhong** [comment]
The issue is because the root skeleton transform is not zeroed out.
