### ISSUE TITLE
CMake Windows: Vcpkg is unable to link because we cannot decide between Release and Debug libraries.

### ISSUE THREAD

**Issue by thoys** [o3de/o3de#2030]
1.  Follow the steps to get  the CMAKE project generated for windows on visual studio 2019
2.  Go to the Visual Studio 2019 project
3.  Select `release` as the build type and build the solution
4. Notice lots of `238>Vcpkg is unable to link because we cannot decide between Release and Debug libraries. Please define the property VcpkgConfiguration to be 'Release' or 'Debug' (currently 'release').` messages in your build logs.
This seems like a typo somewhere, it could not figure out `Release` and `release` is the same..

**Comment by amznestebanpapp** [comment]
It seems is an issue with the vcpkg plugin in Visual Studio.
@AMZN-alexpete observed the same and I think he uninstalled the plugin and the message went away. 

Looking around it seems this is something that multiple projects have hit, I will take a look to see if we can do something to prevent it. We dont use vcpkg for O3DE, we use it in some cases to build 3rdParties, but we package that prebuilt and users dont see a vcpkg script at all.

**Comment by AMZN-alexpete** [comment]
I had this same issue and the way to resolve it is to open a (possibly elevated) PowerShell window and run

`vcpkg integrate remove`

Full vcpkg integrate docs here: https://vcpkg.io/en/docs/users/integration.html#integrate-command
