### ISSUE TITLE
Editor can crash when setting viewport layout/active viewport via Python script

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#2038]
**Describe the bug**
Editor can crash when setting viewport layout/active viewport via Python script. This occurs when running the Dynamic Vegetation automated test: test_LayerSpawner_InstancesRefreshUsingCorrectViewportCamera.

**Prerequisites**
1. Editor is configured and built to launch AutomatedTesting in slice mode.
2. AutomatedTesting assets are processed in slice mode.

**To Reproduce**
1. Comment out the test skip on line 124 of AutomatedTesting\Gem\PythonTests\largeworlds\dyn_veg\test_LayerSpawner.py
2. Run test_LayerSpawner_InstancesRefreshUsingCorrectViewportCamera:

`python\python.cmd -m pytest <path to AutomatedTesting>\Gem\PythonTests\largeworlds\dyn_veg\test_LayerSpawner.py::TestLayerSpawner::test_LayerSpawner_InstancesRefreshUsingCorrectViewportCamera --build-directory <path to build directory>`

**Expected behavior**
Vegetation test runs and validates instance planting in a split viewport setup.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10 - 20H2
 - CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz   2.90 GHz
 - GPU: RTX 2080
 - Memory: 32.0 GB

**Additional context**
[error.log](https://github.com/o3de/o3de/files/6793616/error.log)
[Editor.log](https://github.com/o3de/o3de/files/6793617/Editor.log)

**Comment by jckand-amzn** [comment]
I could not tell from debugging where the crash was occurring. It seems to happen somewhere between:

`# Change the Editor view to contain two viewports
        general.set_view_pane_layout(1)
        get_view_pane_layout_success = self.wait_for_condition(lambda: (general.get_view_pane_layout() == 1), 2)
        get_viewport_count_success = self.wait_for_condition(lambda: (general.get_viewport_count() == 2), 2)
        self.test_success = get_view_pane_layout_success and self.test_success
        self.test_success = get_viewport_count_success and self.test_success`
        
and

`# Set the view in the first viewport to point down at the first box
        general.set_active_viewport(0)
        self.wait_for_condition(lambda: general.get_active_viewport() == 0, 2)
        general.set_current_view_position(first_entity_center_point.x, first_entity_center_point.y,
                                          first_entity_center_point.z + 30.0)
        general.set_current_view_rotation(-85.0, 0.0, 0.0)`

**Comment by jackalbe** [comment]
This seems to indicate that the Atom RPI  view port has an issue after the view port is changed?
maybe `m_windowContext` is in an invalid state?
```
3) 00007FFE16441454 (ntdll) : RtlRaiseException
 2) 00007FFE16490CAE (ntdll) : KiUserExceptionDispatcher
 1) D:\GitHub\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\ViewportContext.cpp (78) : AZ::RPI::ViewportContext::GetWindowContext
```

**Comment by jckand-amzn** [comment]
This no longer seems to occur on development@50588eb2ad6a7e. Closing out.
