### ISSUE TITLE
NetworkTransformComponent has parentEntityId but it's not never set on servers

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#2048]
**Describe the bug**
NetworkTransformComponent (in Multiplayer gem) has a network property "parentEntityId" of type NetEntityId, which is always invalid

**To Reproduce**
1. Using MultiplayerServer project - https://github.com/o3de/o3de-multiplayersample
2. launcher the server and a client, connect them together
2. Either capture in a debugger, or write a component that uses NetworkTransformComponent and calls GetParentEntityId on it
3. Observe that the value returned NetworkTransformComponent :: GetParentEntityId is always invalid NetEntityId

**Expected behavior**
NetworkTransformComponent :: GetParentEntityId should be set on the server, whenever a parent is set or changes
NetworkTransformComponent :: GetParentEntityId should return a value id on clients if it was set on the server

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I9-7920x
 - GPU NVidia RTX 2080 TI
 - Memory 64GB

**Additional context**
Multiplayer gem, MultiplayerSample

**Comment by AMZN-Olex** [comment]
Starting to work on this...

**Comment by lmbr-pip** [comment]
Issue believe fixed. Closing.
