### ISSUE TITLE
Allow RHI to be selected by config file, not just Command Line

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/o3de#2051]
Currently, the RHI can only be set by command line parameter --rhi=vulkan

However, the functionality to set it via a config file (regset for example) would be fairly straightforward to implement.

Currently, FactoryManagerSystemComponent does in fact have a member variable that can contain a vector of names of RHI ("vulkan", "dx12") etc called m_factoriesPriority, but it isn't reading anything into this variable at startup from anywhere, so its likely blank.

This is an ideal starting out feature because solving it would involve adding code to the Activate() function of FactoryManagerSystemComponent that reads from config file the values the user wants for that variable.  It can be read by using the Settings Registry (ie, the combination of all .setreg files in the Registry folder of project, engine, or user) by getting the intsance of the Settings Registry:

`AZ::SettingsRegistryInterface* registry = AZ::SettingsRegistry::Get();`

And then using this singleton like its used in many other places to read into the m_factoriesPriority.

Once this was done, then the user could create a config file in (project)/Registry, (engine)/REgistry, or %USERPROFILE%/.o3de/Registry to set the list of preferred RHI to use in the order to try to use them.

**Comment by akioCL** [comment]
The original idea of the FactoryManagerSystemComponent was to allow games to determinate the order in which they want to select the RHI (like this game is optimized for DX12 so we want to run that first). The m_factoriesPriority was suppose to be read from the SystemComponents reflect data (using the old game.xml editor.xml). I guess nobody updated FactoryManagerSystemComponent when that system was removed.

**Comment by lawsonamzn** [comment]
Yes.  The old System Component Editor was replaced by the new Registry Settings system.   (simple JSON files).   It can read "objects" from file using the reflection context, so if I were doing this, I'd move those settings into a (reflected) child struct like m_settings, then during activate or right before it needs to read it, I'd have it call GetObject from the registry to fill that struct.

**Comment by OBWANDO** [comment]
Add support for display adapter
