### ISSUE TITLE
All shaders fail to Process

### ISSUE THREAD

**Issue by EddieSoloProjects** [o3de/o3de#2067]
**Describe the bug**
All shaders fail to Process

**To Reproduce**
Create a Default Project
Open It
Asset Processor fails on all shaders

**Expected behavior**
To process shaders and open project

**Screenshots**
![SHADER ISSUE](https://user-images.githubusercontent.com/31143681/125153068-94f7ed80-e10e-11eb-9e73-60660451df8a.jpg)

AMD RYZEN THREADRIPPER 2950X 16 CORE 3.50 GHZ CPU

Ram 64 Gigs

Windows 10 Pro 

Nvidia Geforce RTX 2080 Ti Founders Edition

**Additional context**

**Comment by socket220** [comment]
I want to add the same case of problem above:
Compiled the engine, created default project and opened it. Having problem with compilation with next file types:
*.png; *.tif; *.prefab.
Tried to recompile the engine twice, got the same behaviour.
![61vYPVA 1](https://user-images.githubusercontent.com/8751805/125199034-1ebdcd00-e26d-11eb-990d-9100042c311a.png)

Specs:
Intel i5-8600, 16 Gb RAM, Nvidia 1070TI
Windows 10 Pro

**Comment by hendradarwin** [comment]
I also face the same issue, and I found the solution.
For image asset (`png`, `tif`) make sure you already enable `ImageProcessing` gem on the project.
Once you enable it, it will force you to rebuild the project.
After the rebuild is finish, close the editor and Asset Processor.
Relaunch the editor and reopen the project, it will trigger Asset Processor to rebuild the asset.
All image asset should be compiled successfully.

![image](https://user-images.githubusercontent.com/10397816/125927139-d7c6745b-f380-4ff8-b73e-2be87baca6a6.png)
![image](https://user-images.githubusercontent.com/10397816/125927673-b6bcd546-df42-4881-984f-3e47626e1365.png)

**Comment by socket220** [comment]
Thanks for your solution!

I tried to create minimal project, where prefab loading causes compilation error. As you said I tried to include gem _PrefabBuilder_ but it didn't help neither. In my case errors with images still remain.

**Comment by chanmosq** [comment]
The **DefaultProject** template is the best place to start if you want to go straight into the Editor and start creating. The **MinimalProject** template is better for developers who plan to customize the Gems in their project from scratch.

**Comment by OBWANDO** [comment]
Need to have Prism team look at why gems were not enabled.

**Comment by amznestebanpapp** [comment]
this should be already fixed @EddieSoloProjects can you check with latest?
there was a problem with how Atom gem was enabled

**Comment by socket220** [comment]
In my case all was fixed. Thanks!

**Comment by EddieSoloProjects** [comment]
Since I am not a coder, I have to wait for someone to make another build with the fixes for me to test this. But I look forward to checking it out as soon as I can. :)

**Comment by amznestebanpapp** [comment]
> Since I am not a coder, I have to wait for someone to make another build with the fixes for me to test this. But I look forward to checking it out as soon as I can. :)

please reopen or let us know if it doesnt work
