### ISSUE TITLE
Camera location/rotation saves when saving level.

### ISSUE THREAD

**Issue by WashedUpStudio** [o3de/o3de#2074]
**Is your feature request related to a problem? Please describe.**
When you open a level it throws the camera at 0,0,0 ; and I want it to save your camera location when saving the level.

**Describe the solution you'd like**
I want the camera location to save so when you load back into that level your camera goes to the same location you saved it at.

**Describe alternatives you've considered**

**Additional context**

**Comment by hultonha** [comment]
This is now supported with the new View Bookmark System (see https://github.com/o3de/o3de/issues/8435).

Part 1 is complete. Local View Bookmarks are stored for 'Last Known Location' (the position of the camera when saving and closing the editor and when going to/from Game Mode) and View Bookmarks can be saved and loaded with `Ctrl+Fn<num>` keys and `Shift+Fn<num>` keys respectively.

We unfortunately have not yet got to 'shared' View Bookmarks (ones you can store in the level and share with others) but support does exist, it's just not wired up yet. There also isn't a great UX experience for Local View Bookmarks, this would be great to add so we wouldn't need to use the Fn<num> keys and limit Local View Bookmarks to only store 12 locations.
