### ISSUE TITLE
3rdparty gets downloaded to .o3de even though I've specified a different folder

### ISSUE THREAD

**Issue by Srekel** [o3de/o3de#2079]
I've changed the path of the 3rdParty folder. When hitting Build on the project, it's still downloading stuff to .o3de/3rdparty, filling up my C drive.

Related issue maybe: https://github.com/o3de/o3de/issues/2045

This is a blocker as I don't have enough space on my C drive (~12gb) for the whole 3rdParty folder.

**Comment by lumberyard-employee-dm** [comment]
@AMZN-nggieber 
The Project Manager queries the 3rdParty folder from the manifest file located at `~/.o3de/o3de_manifest.json`
It should be querying the `default_third_party_folder` folder
If anything this would be an issue in the ProjectManager [ProjectBuilderWorker_Windows.cpp](https://github.com/o3de/o3de/blob/stabilization/2106/Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp#L76-L80) file where it supplies the LY_3RDPARTY_PATH option.
It should be reading the 3rdParty path via a call to `PythonBindings::GetEngineInfo`

**Comment by AMZN-nggieber** [comment]
One of the options passed in to the configure command in ProjectBuilderWorker_Windows.cpp is `"-DLY_3RDPARTY_PATH=" + engineInfo.m_thirdPartyPath` maybe its somehow getting ignored, or the flag is wrong, or the data it is getting from `PythonBindings::GetEngineInfo` is wrong?

**Comment by lumberyard-employee-dm** [comment]
@Srekel Is this occuring in the same Project Manager session.
I.e did you change the Third Party in the current section and then selected the build option?

Can you try changing the 3rdParty folder and closing Project Manager and then re-open it and see if builds to your new location.

Also which branch are you using? The development branch was just updated today from stabilization/2106, so it should have the latest fixes.
The main branch is out of date by a couple of months

**Comment by AMZN-nggieber** [comment]
I just tried changing the Third Party path in the same Project Manager session on the `stabilization/2106` branch. `engineInfo.m_thirdPartyPath` from `PythonBindings::GetEngineInfo` is the new value that was just set.

**Comment by Srekel** [comment]
Hi,

I'm pretty sure I tried many different things, including exiting o3de and restarting it. 

I synced now to latest on the development branch, rebuilt, removed my .o3de folder and the project folder, and recreated it, and now it built seemingly without the C drive.

**Comment by Srekel** [comment]
Feel free to close this issue. I've now moved on to the next blocker issue. :) 

https://github.com/o3de/o3de/issues/2172
