### ISSUE TITLE
Script Canvas doesn't load when added as a component in a UI Canvas

### ISSUE THREAD

**Issue by incisor** [o3de/o3de#2083]
**Describe the bug**
Script Canvas doesn't load when added to a UI Canvas. Logs shows a line
`RuntimeComponent::m_runtimeAsset AssetId: {74328A1B-1198-5869-860C-ABD1E7412DF0}:163310ae was valid, but the data was not pre-loaded, so this script will not run`

It will only work only if the UI Canvas is loaded in the UI Editor.

Question is if this is intended and there is a way to pre-load the script canvas.

**To Reproduce**
1. Create test project from the templates.
2. Create a test Script Canvas. Simple On Graph Start -> Print("Test")
3. Create a test UI, add a Script Canvas Component to link the SC file you created.
4. Create an entity and add an UI Asset Ref component and link the UI file you created.
4. Make sure UI Editor or even Script Canvas Editor is closed.
5. Run the level. Check the log console for the message.

**Expected behavior**
Expect the Sctipt Canvas to load even without the UI Editor.

**Additional context**
comparing the same RuntimeComponent class in LY and O3DE you will notice that LY's RuntimeComponent::Init has a check if the m_runtmeAsset is valid. If not it will load the script canvas using the AssetManager. In O3DE this part is non-existent.

**Comment by WashedUpStudio** [comment]
Not sure if this has been replicated by a developer, incisor and I both have this issue, but AMZN_ls could not seem to replicate this issue.

**Comment by NiklasHenricson** [comment]
Hey guys, could we give this some push in the priority? It starts getting some cobwebs on it :) 
on a serious note however, it's a blocking issue for our progress.

**Comment by lsemp3d** [comment]
> Hey guys, could we give this some push in the priority? It starts getting some cobwebs on it :)
> on a serious note however, it's a blocking issue for our progress.

Do you have any additional repro steps? is this using prefabs at all or directly on entities? I tried to reproduce this some time ago and wasn't able to. I recently did a small game project that used a UI canvas with Script Canvas and everything worked correctly, so it's possible I'm missing a repro step.

**Comment by WashedUpStudio** [comment]
I am on the fully updated stabilization branch, and to get this bug I added a button to the ui canvas, and a script canvas component to its own element. I add to the script canvas graph just two nodes, a Button Click to Print, and I still get the issue where the asset id is valid but the script was not preloaded.

**Comment by incisor** [comment]
> > Hey guys, could we give this some push in the priority? It starts getting some cobwebs on it :)
> > on a serious note however, it's a blocking issue for our progress.
> 
> Do you have any additional repro steps? is this using prefabs at all or directly on entities? I tried to reproduce this some time ago and wasn't able to. I recently did a small game project that used a UI canvas with Script Canvas and everything worked correctly, so it's possible I'm missing a repro step.

Just an entity with a UI Asset Ref component in it. I think the critical step must be the UI and SC Editor must be closed when running the game.

**Comment by svitlani** [comment]
Following the repro steps mentioned in the description, I was able to confirm the issue exists. I performed testing in Development branch and encountered the same issue - SC does not load with the valid asset ID in the graph

**Comment by svitlani** [comment]
This issue is more related to UI Canvas, switching the labels to keep SC backlog accurate.
