### ISSUE TITLE
Platform Settings crashes the editor.

### ISSUE THREAD

**Issue by imginimg** [o3de/o3de#2087]
"File->Edit Platform Settings..." crashes the editor.

Reproducible at least on c9ff63408 commit.

() - 00007FF93609C247 (KERNELBASE) : UnhandledExceptionFilter
() - 00007FF938795270 (ntdll) : memset
() - 00007FF93877C776 (ntdll) : _C_specific_handler
() - 00007FF93879217F (ntdll) : _chkstk
() - 00007FF938741454 (ntdll) : RtlRaiseException
() - 00007FF938790CAE (ntdll) : KiUserExceptionDispatcher
() - D:\o3de\o3de\Code\Framework\AzCore\AzCore\std\string\string.h (1851) : AZStd::operator+<char,AZStd::char_traits<char>,AZStd::allocator>
() - D:\o3de\o3de\Code\Editor\Plugins\ProjectSettingsTool\ProjectSettingsToolWindow.cpp (671) : ProjectSettingsTool::ProjectSettingsToolWindow::PlatformEnabled
() - D:\o3de\o3de\Code\Editor\Plugins\ProjectSettingsTool\ProjectSettingsToolWindow.cpp (51) : ProjectSettingsTool::ProjectSettingsToolWindow::ProjectSettingsToolWindow
() - D:\o3de\o3de\Code\Editor\QtViewPaneManager.cpp (147) : QtViewPane::CreateWidget
() - D:\o3de\o3de\Code\Editor\QtViewPaneManager.cpp (663) : QtViewPaneManager::OpenPane
() - D:\o3de\o3de-packages\packages\qt-5.15.2-rev4-windows\qt\include\QtCore\qobjectdefs_impl.h (443) : QtPrivate::QFunctorSlotObject<<lambda_94629051ac44815935e26f4617d34052>,0,QtPrivate::List<>,void>::impl
() - 00007FF8EB4E0DB9 (Qt5Core) : QObject::qt_static_metacall
() - 00007FF91EFB5DCF (Qt5Widgets) : QAction::activate
() - 00007FF91F10C698 (Qt5Widgets) : QMenu::actionGeometry
() - 00007FF91F10C473 (Qt5Widgets) : QMenu::actionGeometry
() - 00007FF91F111C51 (Qt5Widgets) : QMenu::mouseReleaseEvent
() - 00007FF91EFE7B02 (Qt5Widgets) : QWidget::event
() - 00007FF91F10DC37 (Qt5Widgets) : QMenu::event
() - 00007FF91EFC49B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
() - 00007FF91EFC28D0 (Qt5Widgets) : QApplication::notify
() - 00007FF8EB4C1B4A (Qt5Core) : QCoreApplication::notifyInternal2
() - 00007FF91EFC5BC5 (Qt5Widgets) : QApplicationPrivate::sendMouseEvent
() - 00007FF91F01024A (Qt5Widgets) : QSizePolicy::QSizePolicy
() - 00007FF91F00E80E (Qt5Widgets) : QSizePolicy::QSizePolicy

**Comment by cgalvan** [comment]
I was unable to reproduce at latest commit c4a50b9

Are you using a custom project or the default AutomatedTesting project?

**Comment by imginimg** [comment]
Clean project from the "standard" template. I'll try it at the development branch.

**Comment by AMZN-ScottR** [comment]
Knowing how the the platform settings tool works, it likely hasn't been updated to support the folder structure of new projects, which the AutomatedTesting project does not have.
