### ISSUE TITLE
SIG/Network - network spawnables do not preserve EntityId references

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#2108]
**Found in Build**: development or stab branches
**Reproducibility**: 100%

**Prerequisites**:

- Network prefabs
- MultiplayerSample

**Steps to Reproduce:**

- create a prefab with network entities in them (net bind + network transform)
- option 1: create child entities, so that their (non-network) transform components are pointing to a parent entity
- option 2: create a custom component has a AZ::EntityId field that is set in the editor at edit to point to another entity in the same prefab

Expected Result:
- entity references are preserved 
 
**Actual Result**

- entity references are NOT preserved
- network.spawnable has bad entity id values that point to nothing
- at runtime, one cant use those values to find real entities
- no network entity can points to its parent entity

 
**Additional Details**

I'm observing something weird when testing a hierarchy idea by setting the parent of an entity manually, by adding an entity field, and dragging the parent to the field, in the editor. I made a slice with TestEntity1 -> TestChild 2 -> TestChild3 structure.At runtime, I see the following pattern with my debug code:

```
(EntityHierarchyComponent) - entity 457531130047/[Test Entity 1] activated @ (X:12.927866, Y:6.703401, Z:12.253547), actual parent is 6270187913657646728/not-found/0, should be parent is 4294967295/not-found/0
(EntityHierarchyComponent) - entity 479005966527/[Test Child 2] activated @ (X:12.927866, Y:6.703401, Z:15.666367), actual parent is 6355455621451383150/not-found/0, should be parent is 6355455621451383150/not-found/0
(EntityHierarchyComponent) - entity 500480803007/[Test Child 3] activated @ (X:12.927866, Y:6.703401, Z:18.500860), actual parent is 10550055212491761467/not-found/0, should be parent is 10550055212491761467/not-found/0
```

Notice that the entities id values coming from the slice are large in value, whereas actual spawned in values are of normal range:
479005966527 versus 6355455621451383150.

These bad values are coming from network.spawnable assets, created from prefabs. I'm attached example prefab and network spawnables that I used to test this scenario.

[Test_Parent_In_LeveL.prefab.txt](https://github.com/o3de/o3de/files/6803624/Test_Parent_In_LeveL.prefab.txt)
[test_parent_in_level.network.spawnable.txt](https://github.com/o3de/o3de/files/6803625/test_parent_in_level.network.spawnable.txt)

**Comment by lmbr-pip** [comment]
@SergeyAMZN Can we can update on this issue, as this may have been fixed by you?

**Comment by SergeyAMZN** [comment]
Fixed in https://github.com/o3de/o3de/pull/4023
