### ISSUE TITLE
Project build fails outside of build folder

### ISSUE THREAD

**Issue by ratchet3789** [o3de/o3de#2113]
**Describe the bug**
If I manually set a new projects directory on my Windows system outside of the .o3de/projects directory it will always fail with a _Could not find a package configuration file provided by "o3de" with any of the following names: o3deConfig.cmake o3de-config.cmake_.
The build works successfully if it is placed in the default install location provided by the Project Config

**To Reproduce**
1. Build the engine
2. Create a new project in any folder outside of the engines ./projects folder
3. Build the project

**Expected behavior**
A successfully built project

**Screenshots**
https://i.imgur.com/wVNYGgC.png

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Intel i7 7700k
 - GPU Nvidia GTX 1070
 - Memory 32gb

**Comment by rgba16f** [comment]
![image](https://user-images.githubusercontent.com/82187279/125365998-df5db200-e33a-11eb-81fd-94f65a9f4b73.png)

**Comment by ratchet3789** [comment]
This issue only happened in stabilisation/2106 and has not appeared in main.
Now stuck with #1966
