### ISSUE TITLE
Editor crashes when attempting to connect LuaIDE to Editor

### ISSUE THREAD

**Issue by Nocxr** [o3de/o3de#2119]
**Describe the bug**
The editor will crash when attempting to connect the bundled LuaIDE to the Editor process.  Once you have selected the Editor as the target, clicking outside of the IDE results in the Editor locking up and crashing.  A "Negotiation Failed" message appears when launching the IDE when this is happening.  Earlier this morning when I was trying to replicate it was not crashing, but it was not connecting either, after messing around in the editor and then trying again I was able to reproduce the crash again.  Editor and error logs attached at bottom of post.

**To Reproduce**
1. Open project
2. Open LuaIDE and click target, choose "editor"
3. Click out of LuaIDE

**Expected behavior**
LuaIDE to connect to editor to use classes reference and debugging.

**Screenshots**
- Editor, LuaIDE, and Gridhub before clicking out of IDE:
![image](https://user-images.githubusercontent.com/72276215/125369520-3fe7f180-e331-11eb-990f-56f9375dc7e7.png)

- Negotiation Failed message:
![image](https://user-images.githubusercontent.com/72276215/125369437-17f88e00-e331-11eb-817a-461599c3253a.png)

- Screen as I have clicked out of IDE and has locked up:
![image](https://user-images.githubusercontent.com/72276215/125369352-e67fc280-e330-11eb-8d4f-f6c8bde00719.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 11 
 - Version: 21H2 22000.65
 - CPU: AMD 2700X
 - GPU: AMD 5700XT XFX THICC III
 - Memory: 32GB

**Additional context**
**Updated, original log file uploaded was incorrect**
Editor log: 
[Editor.log](https://github.com/o3de/o3de/files/6804980/Editor.log)
 Error log: 
[error.log](https://github.com/o3de/o3de/files/6804951/error.log)

**Comment by monroegm** [comment]
Going through old issues to see if they still occur. Could not reproduce this one. Note that you should not get the "Negotiation Failed" message if you launch LuaIDE.exe with the same --project-path that was used to launch Editor.exe. @Nocxr please reopen if you are still experiencing this issue.
