### ISSUE TITLE
PhysX Gem can't be used as build dependency in engine SDK Part 2

### ISSUE THREAD

**Issue by fabioanderegg** [o3de/o3de#2126]
**Describe the bug**
This is a continuation of this bug: https://github.com/o3de/o3de/issues/1971

Adding the PhysX Gem as a build dependency to an empty projects leads to the following build errors:
```
-- Build files have been written to: D:/dev/open3d/projects/PhysXTestProject/build/windows_vs2019
Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
  Checking Build System
  PhysXTestProjectSystemComponent.cpp
  PhysXTestProject.Static.vcxproj -> D:\dev\open3d\projects\PhysXTestProject\build\windows_vs2019\lib\profile\PhysXTestProject.Static.lib
  PhysXTestProjectModule.cpp

LINK : fatal error LNK1104: cannot open file '$<TARGET_PROPERTY:LmbrCentral,INTERFACE_LINK_LIBRARIES>.obj' [D:\dev\open3d\projects\PhysXTestProject\build\windows_vs2019\o3de\PhysXTestProject-84ec4707\Code\PhysXTestProject.vcxproj]
```

**To Reproduce**
The same as last time:
1. Build the engine as an SDK
2. Create a new project from the Project Manager
3. In the projects CMakeLists.txt, add `Gem::PhysX` to BUILD_DEPENDENCIES:
```
ly_add_target(
    NAME PhysXTest.Static STATIC
    NAMESPACE Gem
    FILES_CMAKE
        physxtest_files.cmake
        ${pal_dir}/physxtest_${PAL_PLATFORM_NAME_LOWERCASE}_files.cmake
    INCLUDE_DIRECTORIES
        PUBLIC
            Include
    BUILD_DEPENDENCIES
        PRIVATE
            AZ::AzGameFramework
            Gem::Atom_AtomBridge.Static
            Gem::PhysX
)
```
4. Build the project in the Project Manager or Visual Studio.

**Expected behavior**
No build errors.

**Additional context**
Commenting out all lines containing `$<TARGET_PROPERTY:LmbrCentral,INTERFACE_LINK_LIBRARIES>` in  `o3de-install\Gems\PhysX\Code\CMakeLists.txt` fixes the problem (4 lines in my case). The Gem works after this change.

**Comment by amznestebanpapp** [comment]
was able to reproduce, working on it

**Comment by amznestebanpapp** [comment]
We found a fix for this, is some magic around `$<GENEX_EVAL`: https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#id13
