### ISSUE TITLE
Project with a Minimal template setup does not launch

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#2128]
**Describe the bug**
It has been noticed that the created project with a minimal gem setup does not launch after building. Two errors are displayed related to the Module Manager and Maestro gem. Afterwards the Editor crashes.

**To Reproduce**

1. Open the Project Manager.
2. Create a new project with a "Minimal" template.
3. Build the project.
4. Launch the project

**Expected behavior**
The project launches.

**Screenshots**
![Initialization](https://user-images.githubusercontent.com/86952009/125448621-91394165-5274-4e28-a62e-76257304a60c.JPG)
![Module_Manager](https://user-images.githubusercontent.com/86952009/125448624-5e011f07-c94a-4976-bc61-501a406d693d.JPG)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I5-9600k
 - GPU RTX 2060
 - Memory 16GB

**Additional context**
[dump.zip](https://github.com/o3de/o3de/files/6808669/dump.zip)
[Editor.log](https://github.com/o3de/o3de/files/6808672/Editor.log)
[error.log](https://github.com/o3de/o3de/files/6808673/error.log)
![Initialization](https://user-images.githubusercontent.com/86952009/125448808-4dad4c07-a4d7-494f-a8f5-db902f87ca8b.JPG)

https://user-images.githubusercontent.com/86952009/125448813-4b83c438-9af7-4258-ba3a-f15daaecafec.mp4

![Module_Manager](https://user-images.githubusercontent.com/86952009/125448821-7440c17f-8b53-4cfe-a275-502f295f8722.JPG)

**Comment by lawsonamzn** [comment]
It looks like the Atom gem depends on EmotionFX (Via EmotionFXAtom) but doesn't declare this dependency to the gem system.
If you add EmotionFX to the enabled gems for your project (Code/enabled_gems.cmake) it should get past this.  May also have to add Maestro.

**Comment by lumberyard-employee-dm** [comment]
The `EMotionFXAtom_Editor` module is missing the RUNTIME_DEPENDENCIES on `Gem::EMotionFX.Editor`.

The base `EMotionFXAtom` client module correctly declares it's RUNTIME_DEPENDENCIES on `Gem::EMotionFX`

The EMotionFXAtom [CMakeLists.txt](https://github.com/o3de/o3de/blob/development/Gems/AtomLyIntegration/EMotionFXAtom/Code/CMakeLists.txt#L30-L61) needs to be updated with the EMotionFX.Editor module dependency

**Comment by lumberyard-employee-dm** [comment]
Fixed in PR #2228

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in development.
