### ISSUE TITLE
Minimal gem template fails to launch

### ISSUE THREAD

**Issue by LB-OskarMachnowski** [o3de/o3de#2129]
**Describe the bug**
It has been noticed that the created project with a minimal gem setup does not launch after building. Two errors are displayed related to the Module Manager and Maestro gem. Afterwards the Editor crashes.

**To Reproduce**

1. Open the Project Manager.
2. Create a new project with a "Minimal" template.
3. Build the project.
4. Launch the project

**Expected behavior**
The project launches.

**Screenshots**
![Initialization](https://user-images.githubusercontent.com/86950000/125451219-bb6ec9c0-099e-4b53-86d2-29eb566db98e.JPG)
![Module_Manager](https://user-images.githubusercontent.com/86950000/125451230-909fbcdc-1db8-406a-89ff-6a264ed83771.JPG)

**Desktop/Device (please complete the following information):**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Attachments**
[dump.zip](https://github.com/o3de/o3de/files/6808795/dump.zip)
[Editor.log](https://github.com/o3de/o3de/files/6808797/Editor.log)
[error.log](https://github.com/o3de/o3de/files/6808798/error.log)
https://user-images.githubusercontent.com/86950000/125451583-32eaa3d6-6163-4d3c-bb19-009c4587b61f.mp4

**Comment by lumberyard-employee-dm** [comment]
Fix has been submitted in PR #2228
