### ISSUE TITLE
Lumberyard logo shows up in dock on Editor app icon and in error popups on macOs

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#2164]
**Describe the bug**
When opening the Editor from the terminal with `open o3de/build/bin/profile/Editor.app` for the very first time, the icon on the Dock shows the Lumberyard logo. The same logo shows up whenever there is an error opening the editor. 

**To Reproduce**
1.  Build and register engine (Stabilization branch), has to be a fresh build, the icon changes after the editor has been opened once.
2. Open the O3DE Editor with `open o3de/build/bin/profile/Editor.app`
3. See old Lumberyard logo in Dock Editor Icon

Note: To recreate the error message on load, build project with a missing required gem. 
1. Create a new O3DE project
2. Remove EMotionFX from the /o3de-projects/MyProject/Code/enabled_gems.cmake
3. Build and register project
4. Open the editor with `open o3de/build/bin/profile/Editor.app --args --project-path=/o3de-projects/MyProject`
5. See old Lumberyard logo in Dock Editor Icon and in popup error msg

**Expected behavior**
The dock icon and error messages should show the O3DE logo. 

**Screenshots**
![Error Message](https://user-images.githubusercontent.com/77024386/125665489-85d0c0df-c448-400d-b181-d2fe92492415.png)

![Dock Icon](https://user-images.githubusercontent.com/77024386/125666834-218bca07-813b-4a40-b665-4514ba0bb647.png)

![App Icon](https://user-images.githubusercontent.com/77024386/125707998-2d9bdcb9-56bf-44ad-b236-168134a4e221.png)

**Desktop/Device (please complete the following information):**
 - Device: Mac
 - OS: macOS
 - Version: Big Sur 11.4
 - CPU: 2.3 GHz 8-Core Intel Core i9
 - GPU: AMD Radeon Pro 5500M 4 GB
 - Memory: 32GB

**Comment by amznestebanpapp** [comment]
Here are some paths that have old icons:

- Code\Tools\AssetProcessor\Platform\Mac\Images.xcassets\AppIcon.appiconset\icon_512x512.png
- Code\Tools\AssetProcessor\Platform\Mac\Images.xcassets\AssetProcessorAppIcon.appiconset\icon_512x512.png
- AutomatedTesting\Gem\Resources\IOSLauncher\Images.xcassets\AppIcon.appiconset*
- AutomatedTesting\Gem\Resources\IOSLauncher\Images.xcassets\AutomatedTestingAppIcon.appiconset*]
- AutomatedTesting\Gem\Resources\MacLauncher
- Code\Editor\Platform\Mac\Images.xcassets\EditorAppIcon.appiconset*
- Code\Editor\Platform\Mac\Images.xcassets\AppIcon.appiconset*

I would recommend to do a pass on any png file that is under any file path that has
- Platform\Mac
- Platform\iOS
- IOSLauncher
- MacLauncher

**Comment by rainbj** [comment]
We need to provide UX icons for mac launcher
