### ISSUE TITLE
RHI - Add support for gpu Buffer/Non-Transient Image memory visualizer as part of imgui menu

### ISSUE THREAD

**Issue by moudgils** [o3de/o3de#2165]
Problem - Currently there is no way to track where all the gpu memory is going. We need support for a visualizer to help combat bloated gpu mem usage. 

Solution - RHI actually does track and collect statistics for all the ResourcePools after the framegraph is built and encoded. So we should have all the data related to buffers (as Buffer is a Resource) but unfortunately we dont have an imgui menu to display all the statistics related to buffer memory usage (We do have a imgui menu for CPU/GPU profiler plus transient memory)

**Comment by jcbhl** [comment]
Feel free to close if the current widget addresses this issue @moudgils  (I don't have permissions to)
