### ISSUE TITLE
No editor opens after splash screen, error about not finding Gems Catalog

### ISSUE THREAD

**Issue by Srekel** [o3de/o3de#2172]
Synced latest development (on 3ea3d7a - Data integrity issue, keyframe times need to be ascending (#2130))
Built according to instructions.
Registered engine.
Modified manifest file to point to different folders.
Started o3de.exe
Created new project.
Built.
Tried to Open editor.
Splash screen did stuff, then closed, editor doesn't open.

In my task manager I have a bunch of tasks:

![image](https://user-images.githubusercontent.com/1578924/125683514-4c09a03e-ca51-4497-9743-ea6b02837a92.png)

Attaching my log file. 
[O3DE.log](https://github.com/o3de/o3de/files/6818598/O3DE.log)

It ends with:

> ~~1626289188229~~2~~00000000000034DC~~ProjectManager::GemCatalog~~Cannot find entry for gem with name '${Name}'. The CMake target name probably does not match the specified name in the gem.json.

My manifest:
```json

{
    "o3de_manifest_name": "Srekel",
    "origin": "C:/Users/Srekel/.o3de",
    "default_engines_folder": "C:/Users/Srekel/.o3de/Engines",
    "default_projects_folder": "G:/o3de/Projects",
    "default_gems_folder": "G:/o3de/Gems",
    "default_templates_folder": "G:/o3de/Templates",
    "default_restricted_folder": "C:/Users/Srekel/.o3de/Restricted",
    "default_third_party_folder": "G:/o3de/3rdParty",
    "projects": [
        "G:/o3de/Projects/NewProject"
    ],
    "external_subdirectories": [],
    "templates": [],
    "restricted": [],
    "repos": [],
    "engines": [
        {
            "path": "E:/Projects/external/o3de-install"
        }
    ],
    "engines_path": {
        "o3de-install": "E:/Projects/external/o3de-install"
    }
}

```

**Comment by jackalbe** [comment]
It is expected to have the AssetProcessor (AP) and its children AssetBuilder processes to stick around after the Editor shuts down. Did you expect that the AP and builders to shut down automatically when closing the Editor?

**Comment by Srekel** [comment]
Ah, no, that might be fair. Just to be clear (I see I wasn't in my initial post), it wasn't *I* who closed the editor. It just never started after the initial splash screen.

I tried it again now, ran o3de.exe and clicked OpenEditor. Splash screen, then nothing.

But, I'll update the title, as I'm guessing the problem then isn'tabout the AssetProcessor, but rather something to do with paths. Anything I can do to help figure out what's going wrong, let me know.

**Comment by jackalbe** [comment]
you might try to start the Editor using the --project-path option like "o3de.exe --project-path=G:/o3de/Projects/NewProject"

**Comment by Srekel** [comment]
> you might try to start the Editor using the --project-path option like "o3de.exe --project-path=G:/o3de/Projects/NewProject"

I tried this, the project loader showed up (not sure if it should?), I again clicked Open Editor.

This time the O3DE Asset Processor window showed up after a while, haven't seen it before.

I did get an error notification, and now this is shown:
![image](https://user-images.githubusercontent.com/1578924/126070967-17c9b7df-c127-408e-91c4-d7ba05b0dd19.png)
