### ISSUE TITLE
Vegetation Debugger debug text draws much larger than expected/needed

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#2174]
**Describe the bug**
Vegetation Debugger debug text draws much larger than expected/needed

**To Reproduce**
1. Create a new entity at 0,0,0
2. Add the following components to the entity:

- Vegetation Layer Spawner
- Vegetation Asset List w/ any valid prefab assigned
- Box Shape (16,16,16)

3. Select the "Ground" entity in the Entity Outliner, and add a Mesh Surface Tag Emitter component to the entity.
4. Select the top level Level entity in the Entity Outliner.
5. Add a Vegetation Debugger component, and toggle on Show Debug Stats and Show Sector Info.
6. Click Clear All Areas, and observe the debug text in the Viewport.

**Expected behavior**
Debug text appears at a reasonable size, much closer in size to the debug text that draws at the top-right corner of the Viewport.

**Screenshots**
![large_debug_text](https://user-images.githubusercontent.com/82226555/125690966-603d5849-1f5e-49fd-9124-c28c03af3910.jpg)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10 - 20H2
 - CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz   2.90 GHz
 - GPU: RTX 2080
 - Memory: 32.0 GB

**NOTES**:
Found on development@3ea3d7a436

**Comment by AMZN-daimini** [comment]
https://github.com/o3de/o3de/pull/2183
