### ISSUE TITLE
Script Canvas: Direct EntityID references are not functional

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#2190]
**Describe the bug**
It has been noticed, that entities selected using the "Pick an object in the viewport" button in Script Canvas nodes are not correctly referenced.

**To Reproduce**

1. Create two entities (Named e.g. Entity1 and Entity2).
2. Go to Tools > Script Canvas and recreate the graph attached in EntityIDReference.PNG.
3. In the Get Entity Name node press the "Pick an object in the viewport" button and select any Entity (e.g. Entity2).
4. Save the Script and attach it to another Entity (e.g. Entity1).
5. Enter the Game Mode.

**Expected behavior**
The Entity is referenced correctly in Script Canvas. The Entity name is printed to the Console.

**Screenshot and video**
![EntityIDReference](https://user-images.githubusercontent.com/86952082/125775586-f7d96c64-a238-4f27-a337-7fe4cabb8a89.png)

https://user-images.githubusercontent.com/86952082/125775365-e04aa9bd-4b1a-43ff-a704-d4e1529b97a5.mp4

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD  Ryzen 5 3600 6-Core Processor, 3600 Mhz, 6 Core(s), 12 Logical Processor(s)
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-ArturSiewniak** [comment]
The issue still occurs on Development (dcfeae1). Printing to console still returns an empty string.

**Comment by carlitosan** [comment]
@LB-ArturSiewniak  using slices or prefabs?

**Comment by carlitosan** [comment]
I have a solid repro now, and am investigating.

**Comment by carlitosan** [comment]
This is also under investigation by the prefab team

**Comment by carlitosan** [comment]
Current workaround: promote the input EntityId to a variable, set its initial value to "From Component". We're aggressively working on a full fix.

**Comment by LB-ArturSiewniak** [comment]
The workaround works, however when attempting to create a variable via Promote to Variable we encountered an issue described here: https://github.com/o3de/o3de/issues/3101. We are awaiting the final fix for verification.

**Comment by carlitosan** [comment]
Yep, the promote to variable path won't work, but Create Variable of type EntityId will work, just remember to set the initial value to "from Component"

**Comment by carlitosan** [comment]
After a serious dig in with the prefab team, we have a better conclusion. The problem has less to do with the way the Entity reference is established in the SC editor, but rather the Entity picker widget is enabled in the SC editor at all. To safely, properly set an Entity reference, one **must** do so from the Scene editor, and pick a value on the component. We're going to improve the workflow to make all of this more clear.

**Comment by LB-ArturSiewniak** [comment]
As per comment above, adding a variable with Initial Value Source set to From Component, assigning it to the Get Entity Name (as on the graph provided in the reproduction steps), then selecting another entity using the Pick an object in the viewport button next to the variable on the Script Canvas component, does work (the selected entity's name is printed to console). Issue verified as fixed on Development (bb90c4d) build.
