### ISSUE TITLE
Texture Settings Editor window is not movable untill resized

### ISSUE THREAD

**Issue by LB-BartoszStypulkowski** [o3de/o3de#2192]
**Describe the bug**
**Texture Settings Editor** window misses the title bar which allows to move it across the screen when first opened. The title bar appears after resizing the window.

**To Reproduce**
1. Open the O3DE Editor. 
2. Open any project on any level.
3. Open the **Asset Browser** and find any image.
4. RMB on the image and select **Edit Texture Settings...**
5. Try to move the window.
6. Resize the window and try to move it again.

**Expected behavior**
The **Texture Settings Editor** window should be positioned in a way that its title bar is reachable, making the window movable.

**Screenshots**
https://user-images.githubusercontent.com/87059825/125783690-533937f7-1023-436e-9df9-4aa76a8ca71a.mp4

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 7 3800X 8-Core Processor
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by cgalvan** [comment]
I have a fix for this that actually addresses this issue for any generic dialog, just waiting on development to be back in a good state.

**Comment by LB-BartoszStypulkowski** [comment]
The issue is fixed. Verified on build Development (62356b8).
