### ISSUE TITLE
AWSMetrics default Lambda resource name is too long

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#2196]
**Describe the bug**
It has been observed when deploying a CDK Applicaton that the length of Lambda resource is above 64 characters. This results in an error and prevents the User from deploying the application.
Also, the User is unable to change the name of this resource.

Resource name: 
**O3DE-AWS-PROJECT-AWSMetrics-us-east-1-AnalyticsProcessingLambdaName**

Perquisites:

- AWS CLI is installed: https://aws.amazon.com/cli/
- CDK is installed: https://aws.amazon.com/cdk/
- An IAM user with admin permissions is created under the test AWS account. Take a note of the AWS credentials for this user including the access key and secret key.

**To Reproduce**

1. Set up AWS credentials.
2. Deploy the CDK application following AWSMetrics Gem Setup:
- $ python -m venv .env
- $ source .env/bin/activate
- $ pip install -r requirements.txt
- cdk bootstrap aws://ACCOUNT-NUMBER-1/REGION-1 aws://ACCOUNT-NUMBER-2/REGION-2 ...
- $ cdk synth
- $ cdk deploy

**Expected behavior**
The CDK Application is deployed.

**Log:**
2:00:56 PM | CREATE_FAILED        | AWS::Lambda::Function                    | AnalyticsProcessin
gLambdaE9D1FED3
Resource handler returned message: "1 validation error detected: Value 'O3DE-AWS-PROJECT-AWSMetri
cs-us-east-1-AnalyticsProcessingLambdaName' at 'functionName' failed to satisfy constraint: Membe
r must have length less than or equal to 64 (Service: Lambda, Status Code: 400, Request ID: e929d
32a-6c14-4ce9-aab9-f7efb1bef1d4, Extended Request ID: null)" (RequestToken: f5970608-7ec2-d4e4-fb
61-986781d7e126, HandlerErrorCode: InvalidRequest)

	new Function (/private/var/folders/zv/hq_r89f925n6ktwntlyqh5th0000gn/T/jsii-kernel-CDhe5Z/node_mo PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack               | O3DE-AWS-PROJECT-A
dules/@aws-cdk/aws-lambda/lib/function.js:135:26)
	\_ /private/var/folders/zv/hq_r89f925n6ktwntlyqh5th0000gn/T/tmp5wu0tnrs/lib/program.js:8154:58b4d4f87b02d85b201efdd8aServiceRole9741ECFB, InputStreamCFB159EA]. Rollback requested by user.
	\_ Kernel._wrapSandboxCode (/private/var/folders/zv/hq_r89f925n6ktwntlyqh5th0000gn/T/tmp5wu0tnrs/
lib/program.js:8582:24)
	\_ Kernel._create (/private/var/folders/zv/hq_r89f925n6ktwntlyqh5th0000gn/T/tmp5wu0tnrs/lib/progr
am.js:8154:34)
	\_ Kernel.create (/private/var/folders/zv/hq_r89f925n6ktwntlyqh5th0000gn/T/tmp5wu0tnrs/lib/progra
m.js:7895:29)
	\_ KernelHost.processRequest (/private/var/folders/zv/hq_r89f925n6ktwntlyqh5th0000gn/T/tmp5wu0tnr
s/lib/program.js:9479:36)
	\_ KernelHost.run (/private/var/folders/zv/hq_r89f925n6ktwntlyqh5th0000gn/T/tmp5wu0tnrs/lib/progr
am.js:9442:22)
	\_ Immediate._onImmediate (/private/var/folders/zv/hq_r89f925n6ktwntlyqh5th0000gn/T/tmp5wu0tnrs/l
ib/program.js:9443:46)
	\_ processImmediate (internal/timers.js:464:21)

 âŒ  O3DE-AWS-PROJECT-AWSMetrics-us-east-1 failed: Error: The stack named O3DE-AWS-PROJECT-AWSMetrics-us-east-1 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:305:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:294:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:184:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:213:9)
The stack named O3DE-AWS-PROJECT-AWSMetrics-us-east-1 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
[Log.txt](https://github.com/o3de/o3de/files/6823436/Log.txt)

**Comment by lmbr-pip** [comment]
Unfortunately, AWS resources have a differing name length restrictions. Standard Lambdas can have names up to [140](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_RequestParameters) chars currently so it looks like something else may be restricting this (ie is it a custom resource). IAM roles must also be [64](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html) chars or less.

Would suggest having common set of known resource naming checkers to enforce known limits for lambda, iam and other resources created, that format and truncate names as appropriate. Not sure if boto3 or other standard libs provide anything like this but it would not be a lot of code.

**Comment by junbo75** [comment]
The restriction for the Lambda name seems from CloudFormation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-functionname

We don't have any shared util methods defined currently and it's not supported by our CDK application structure. I'll start adding the checkers in the CDK application for AWSMetrics and we can move the code to a common place once we have a better plan for linking all the CDK applications.

**Comment by junbo75** [comment]
Fix has been checked in at https://github.com/o3de/o3de/pull/2291.

**Comment by lmbr-pip** [comment]
Issue has been fixed.
