### ISSUE TITLE
Editor Settings: Failed to open editor Graphics Settings

### ISSUE THREAD

**Issue by Hsuehnj** [o3de/o3de#2198]
**Describe the bug**
Click Edit-Editor Settings-Graphics Settings，there is a warning:
Invalid custom spec file (missing sys_spec_full).

**Describe the bug**
In funciton GraphicsSettingsDialog::OnLoadConfigurationEntry(const char* strKey, const char* strValue, const char* strGroup)
    AZStd::string key = strKey;
    ICVar* cvar = gEnv->pConsole->GetCVar(strKey);  
"sys_spec_full" is used as key, sys_spec_full is not included in console commands, so that cvar is null and m_cVarTracker is not updated.

**Comment by cgalvan** [comment]
The Graphics Settings dialog has been removed in development since it was only applicable for the legacy Cry renderer:

https://github.com/o3de/o3de/pull/2109
