### ISSUE TITLE
Picking Entity ID by using dedicated picker button crashes the editor

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#2199]
**Describe the bug**
It has been observed that picking the entity in the Viewport by using the Entity ID picker button from any component or script canvas node crashes the editor.
The issue was observed on AutomatedTesting project with Prefab system disabled and enabled.
Please note that this issue only occur if user is choosing the entity in the Viewport, choosing the entity in Entity Outliner does not cause the editor to crash.
For further information please to the attached logs and video file.

**To Reproduce**
1. Open empty Script Canvas graph.
2. Add RayCastLocalSpaceWithGroup node to the graph.
3. Click on the button next to Source: Entity ID slot to choose the entity.
4. Minimalize the Script Canvas window.
5. Choose the entity with LMB in the Viewport.

**Repro rate - 6/6**

**Expected behavior**
The Editor remains stable.
**Screenshots and files**
[error.log](https://github.com/o3de/o3de/files/6823718/error.log)
[Editor.log](https://github.com/o3de/o3de/files/6823722/Editor.log)
https://user-images.githubusercontent.com/86951967/125802533-122b68a3-1029-4b9a-9544-b6f58fd80802.mp4
[error.zip](https://github.com/o3de/o3de/files/6823711/error.zip)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 7 1700 - 3,6 Ghz
 - GPU ZOTAC GeForce GTX 1060 0 AMP! 6GB GDDR5
 - Memory 16GB

**Comment by alexmontAmazon** [comment]
@cgalvan could you have a look at this please?

**Comment by hultonha** [comment]
This could be something for me too, please feel free to reach out to me @cgalvan as it's related to the new Viewport - hopefully it's a quick fix (likely just need to hook up `EditorPickEntitySelection`

**Comment by hultonha** [comment]
Okay I spent a little bit of time looking into this and know what's happening! 😅 (essentially by turning off lots of optimizations as in the original case, lot of useful information was getting inlined).

So what's happening is right when a pick happens and we stop pick mode, and decide to return to the normal viewport interaction model, we invoke `SetDefaultHandler` which instantiates `EditorDefaultSelection`, it owns `EditorTransformComponentSelection` (essentially the Viewport Interaction Model (VIM)). In its constructor, we set up Viewport UI (`CreateTransformModeSelectionCluster()`) and in doing that, it winds up internally calling a Qt function that calls `QWidget::setFocus()` (this is the first potential bug and/or fix....) this winds up triggering a Qt event which is intercepted by `QtEventToAzInputMapper::HandleFocusChanged()`, this winds up flushing all channels (inputs) one of which happens to be the in-flight mouse click we just made (this is the second potential bug/fix). This event then gets funneled through `ViewportControllerList` where it eventually winds up getting to `EditorInteractionSystemComponent` where `m_interactionRequests` is null (and then we crash).

There are several potential 'fixes' for this but I'm not 100% sure I know which is best. The first is, maybe we shouldn't actually be calling `setFocus` when creating Viewport UI (this was likely done for a reason so just removing it is risky and could break something else but long-term might be the right thing to do... The next thing is should `HandleFocusChange` flush all the channels like it is now (again this must be for a good reason and I wonder what might break if we don't, @NicholasVanSickle would you be able to add some context here? I'd be very grateful for any additional information). One other fix is just to check if `m_interactionRequests` is null to handle this rare case, or to disconnect and reconnect from `EditorInteractionSystemViewportSelectionRequestBus` potentially...

It's quite possible a mix of these is the best option, I'm considering adding the null check and also removing the `setFocus` (as I _think_ they're superfluous).

If anyone else (@cgalvan @NicholasVanSickle) have any ideas I'd love to hear them 🙂 Thanks!

**Comment by cgalvan** [comment]
Fixed by #2884

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed on Development (3fb903b).
