### ISSUE TITLE
Feature Request: Settings Registry UI Editor

### ISSUE THREAD

**Issue by lemonade-dm** [o3de/o3de#2218]
**Is your feature request related to a problem? Please describe.**
The Settings Registry is a feature of the O3DE Engine(part of the AzCore library) that provides a global repository of accessing settings within any O3DE Application that opts in to using it.
All of the main O3DE Applicatoins are using it: `Editor`, `AssetProcessor`, `${ProjectName}.GameLauncher`
It allows merging of JSON data stored in files .setreg and .setregpatch files. 
- `.setreg` which are merged using the JSON Merge Patch algorithm
- `.*setregpatch` files are merged using the JSON Patch algorithm

Simply put, The Settings Registry is a wrapper around a JSON document DOM, with Getter/Setters method for accessing particular sections using [JSON Pointer](https://www.google.com/search?client=firefox-b-1-d&q=JSON+Pointer).

Users currently edit .setreg/.setreg files with the Editor and have to take care of to make sure any modifications to the file is in valid JSON Syntax. This leads to error prone workflow, where missing a comma or ending double quote marker results in the Settings Registry file not being loaded.

To reduce the ability for users to make JSON Syntax errors, as well as to lower the bar of technical expertise when modifying Settings Registry values, a Settings Registry DOM Editor, can be added to the O3DE Editor

**Describe the solution you'd like**
Ideally the Settings Registry Editor(SR Editor) would be able to view and modify the Global Settings Registry, as well as open and edit .setreg and .setregpatch files within it. Furthermore the user should have the ability to create new in-memory only Local Settings Registry instances as well
Any Settings Registry opened up should be able to be saved to filesystem as well

**Acceptance Criteria**
- How Settings are edited should be based on the type of the setting.
1. Aggregate Types: JSON Object and JSON Array
2. Basic Types: JSON Boolean, JSON Integer, JSON Float, JSON String
- Aggregate Types can be created, removed or have children elements added to them
- Basic Types can be created, removed or edited
- It should be possible to create a setting at an arbitrary JSON Pointer Path
![image](https://user-images.githubusercontent.com/56135373/125869841-1e69d727-dcdf-4ab7-b54f-3e48dbee8789.png)
- The Global Settings Registry should be viewable and Editable with the DOM Editor. The Global Settings Registry is in the in-memory merged Settings Registry at that point
- Changes to the Global Settings Registry in the DOM should be able to be persistent back to the in-memory representations
- Local Settings Registry should be able to be created in the SR Editor.
- .setreg and .setregpatch files should be able to be opened within the SR Editor and isolated into a Local Setting Registry instance - See the [Converter.cpp](https://github.com/o3de/o3de/blob/development/Code/Tools/SerializeContextTools/Converter.cpp#L369-L413) for an example of making a local Settings Registry instance
- .setreg and .setregpatch files should also be able to be merged against an existing Settings Registry instance opened in the DOM. This allows users to see merged results of that file. This should be as simple as calling [SettingsRegistryInterface::MergeSettingsFile](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Settings/SettingsRegistry.h#L293-L301) to perform the merge.
- The SR Editor should provide an option for persisting any opened Settings Registry instance to the file system. Be that the Global Settings Registry instance or any Local Settings Registry instances.
  - The persistence capability should also support saving sections of the Settings Registry to the file system as well. The [DumpAssetProcessorUserSettingsToFile](https://github.com/o3de/o3de/blob/development/Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp#L164-L189) function as an example of how to do that.

**Describe alternatives you've considered**
None

**Additional context**
This goes over how to save a .setreg and .setregpatch file out which will be needed to fulfill the Acceptance Criteria of persisting Settings Registry instances to disk.
Using the [AZ::SettingsRegistryMergeUtils::DumpSettingsToStream](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.h#L224-L252) function is sufficient at saving a file to a .setreg extension, since [JSON Merge Patch](https://datatracker.ietf.org/doc/html/rfc7386#section-3) is compatible with normal formatted JSON.

Saving a .setregpatch file will require a little bit more work however as the `DumpSettingsToStream` doesn't specifying an output format and only dumps to regular JSON
The `DumpSettingsToStream` function should be extended to support [JSON Patch](https://www.rfc-editor.org/rfc/rfc6902.html).
The JSONSerialization.cpp [CreatePatch](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Serialization/Json/JsonSerialization.h#L105-L114) function can be used to create a JSON Patch formatted JSON document.

**Comment by amzn-leenguy** [comment]
@o3de/sig-core is planning to work on this. Please reach out to the @o3de/sig-ui-ux for help.

**Comment by Infurael** [comment]
A key feature it should have imho is to see what .setreg or .setregpatch file contributed to the value of a key. This makes it much easier for users to track down the relevant files for a key/value pair and help debug unexpected values. It has for instance come up a few times that users forgot they had a .setreg file in their user folder and they couldn't find what caused a value to be different from what they expected.
For the implementation of such a feature I wouldn't shoehorn it into the current Settings Registry but instead replicated the same rules in a separate application as the rules are pretty simple.
I would also recommend making this a tool that doesn't use AzCore or any other O3DE libraries. This will help avoid the circular dependency of having to edit the .setreg files to build the editor to edit the .setreg files. Something in Python perhaps?

**Comment by HydrogenC** [comment]
Is there any progress on this? The current way of manipulating settings is somehow tedious and unintuitive.

**Comment by lumberyard-employee-dm** [comment]
> Is there any progress on this? The current way of manipulating settings is somehow tedious and unintuitive.

There is a Technical Design for this feature posted for PR in the SIG-Content repo at https://github.com/o3de/sig-content/pull/146/files?short_path=04331d0#diff-04331d0b69fe2470098d0fd857b723d233d0ec4686c3497478aef777610ce305.

There is a prototype of being able to view the Settings that is available as part of the as well as a prototype that can view the 
Settings using the [DPEDebugViewStandalone application](https://github.com/o3de/o3de/blob/development/Code/Framework/AzQtComponents/CMakeLists.txt#L80) which can be built using the CMake DPEDebugViewStandalone build target(it will appear in Visual Studio as that target name as well if using the Visual Studio Generator) and accessed by selecting the "Settings Registry Adapter" option in the dropdown menu of the application.

However no resources are being dedicated to complete the Settings Registry UI Editor feature at this time.
