### ISSUE TITLE
Polygon light sets polygon prism shape height to 0 on play start

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#2253]
**Describe the bug**
A light component set to the polygon light type requires a polygon prism shape.
On play start, the polygon prism shape height value is set to 0.

**To Reproduce**
1. Create a new entity and add a 'Light' component to it.
![image](https://user-images.githubusercontent.com/48143120/126047003-62bdddcc-759d-4efd-88eb-ab1dcb4bd7e2.png)

2. Set its light type to 'Polygon'. A 'Polygon Prism Shape' component should be automatically added to the same entity.
![image](https://user-images.githubusercontent.com/48143120/126047010-e54748c6-0ff1-42db-aa4a-45e62e21b19a.png)

3. Set the height value of the polygon prism shape component to a valid non-zero value.
![image](https://user-images.githubusercontent.com/48143120/126047016-48672c17-ecee-46e9-b064-1673fab63e0e.png)

4. Play game (in-editor) and exit.
![image](https://user-images.githubusercontent.com/48143120/126047020-dbaefad7-a4e3-4b75-b6b0-072da13382e9.png)

4. See error: The polygon prism shape height component is 0. It should be the value you previously set in step 3.
![image](https://user-images.githubusercontent.com/48143120/126047031-b133a322-3aa9-40ca-b0c6-4feb834ae8ec.png)

**Expected behavior**
The height value of the polygon prism shape should be the value you set and not changed (to 0) after playing and exiting the game.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz
 - GPU: GeForce GTX 1070
 - Memory: 32.0 GB

**Additional context**

**Comment by invertednormal** [comment]
This is intentional behavior - the light component sets the height of the polygon prism to 0 since a polygon light does not use the height property of a polygon prism. Imo disabling or removing the height property of the polygon prism when used for a light would be preferred - why are you wanting to use the height property of the polygon prism when it doesn't affect the light?
