### ISSUE TITLE
When entering the Game Mode with UI Editor window opened, the Editor loses focus

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#2257]
**Describe the bug**
It has been noticed, that when the Game Mode is entered with the UI Editor window opened, the Editor loses focus, making it unable register input from keyboard and mouse.

**To Reproduce**
1. Create and open a new level.
2. Enter the Game Mode and verify that the default Camera entity can be moved.
3. Exit the Game Mode.
4. Go to Tools > UI Editor.
5. Enter the Game Mode, without closing the UI Editor window.

**Expected behavior**
The Game Mode works without issues.

**Video**

https://user-images.githubusercontent.com/86952082/126136688-2e32447f-d1de-40be-9418-3752c10f39a1.mp4

**Desktop**

- Device: PC
- OS: Windows
- Version 10
- CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
- GPU NVIDIA GeForce RTX 2060 SUPER
- Memory 16GB

**Comment by michabr** [comment]
This is a duplicate of #2515.

**Comment by LB-ArturSiewniak** [comment]
Closing the issue and removing the Duplicate label, as issue #2515 was reported later. Verified on build Development (3fb903b).
