### ISSUE TITLE
Variables exposed to Component in Script Canvas do not receive value from the Component

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#2261]
**Describe the bug**
Script Canvas Variables with the _Initial Value_ set to _From Component_ do not receive the value from Component and instead use the _Default Value_ set in the Variable Manager.

Please refer to the attached video for more details.

**To Reproduce**
1. Launch Script Canvas.
2. Create a new Graph.
3. Add and connect the following nodes to the graph area: _On Graph Start_ -> _Print_.
4. In the Variable Manager create a new Variable of type Number.
5. Drag and drop the Variable to the _Value_ slot on the _Print_ node.
6. In the Variable Manager change the _Initial Value_ of the Variable to _From Component_.
7. Save the graph and assign it to an Entity.
8. On the Script Canvas Component modify the Variable value to anything other than the default Value.
9. Enter the Game Mode and note that the printed value does not match the one passed to the Component.

**Expected behavior**
A value passed to the Component is printed to the Console.

**Screenshots**

https://user-images.githubusercontent.com/86953108/126158121-9076d03f-987c-4366-b7b6-ff097bcecbe0.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA RTX 2060 SUPER
 - Memory 16GB

**Comment by carlitosan** [comment]
Unable to reproduce

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as Fixed in Development (4cf384c). Verified using repro steps included in the description.
