### ISSUE TITLE
GameLauncher fails to launch due to failed initialization

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#2265]
**Describe the bug**
Launching the GameLauncher for any project results in the O3DE Initialization Failed error being displayed. After dismissing it, the Launcher only shows a white screen and is unusable.

Please refer to the attached files for more details.

**To Reproduce**
1. Run AutomatedTesting.GameLauncher.exe

**Expected behavior**
The Game Launcher starts successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/86953108/126169912-40e526e8-bd0d-45fa-a67e-3b3e77876f8c.png)

![image](https://user-images.githubusercontent.com/86953108/126169609-5b65c1a8-a281-4753-bde0-80eee3e1399f.png)

https://user-images.githubusercontent.com/86953108/126169640-7493731a-f47e-4efb-b84d-093eee81b6e3.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA RTX 2060 SUPER
 - Memory 16GB

**Comment by amzn-pratikpa** [comment]
Resolved

**Comment by LB-TomaszSerwanski** [comment]
Verified as fixed in Development (7dc5c8b).
