### ISSUE TITLE
Editor ray/scene intersection checks done while rotating the camera

### ISSUE THREAD

**Issue by amzn-jillich** [o3de/o3de#2266]
When moving the mouse inside the editor viewport EditorSelectionIntersectRayViewport() are called to check for any object intersections that are then used for possible selection.

When moving the camera forward/backward/left/right these are not called, which is good. When rotating the camera, using the right mouse button, the intersection checks get called which is drastically reducing the framerate in case some high-poly characters are visible and nearby the camera.

Steps to reproduce:
1. Create a new level
2. Add entity
3. Add actor component and select a high poly character
4. Fly around the character and notice the drop in fps when the camera is inside the frustum, close to the camera center. This is due to the fact we're checking for ray intersections with it which is a heavy operation on characters as we need to software skin them. This is already optimized and is a multi-threaded process.

The checks should be skipped for camera rotation as they are for camera movement.

**Comment by hultonha** [comment]
Looking into this some more I don't necessarily think this is the issue but I think some code in `RenderViewportWidget` can be made clearer by including the type `ViewportControllerInputEvent` when we get the signal from the `InputChannelUpdated` function:

```c++
QObject::connect(m_inputChannelMapper, &AzToolsFramework::QtEventToAzInputMapper::InputChannelUpdated, this,
    [this](const AzFramework::InputChannel* inputChannel, QEvent* event)
{
    AzFramework::NativeWindowHandle windowId = reinterpret_cast<AzFramework::NativeWindowHandle>(winId());
    if (m_controllerList->HandleInputChannelEvent(AzFramework::ViewportControllerInputEvent{GetId(), windowId, *inputChannel}))
                                                                             ^
                                    // Can we include the type here to make the instance easier to find
    {
        // If the controller handled the input event, mark the event as accepted so it doesn't continue to propagate.
        if (event)
        {
            event->setAccepted(true);
        }
    }
});
```
