### ISSUE TITLE
Created projects default to different drive than O3DE repository

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#2269]
I ran into problems with using the default settings using the "Create New Project" tool. The tool sets the default location for the new project on your C drive, but in my case my O3DE repository is located on my E drive. When I went to configure a build I received several CMake errors that looked like this:

CMake Error at cmake/Platform/Common/Install_common.cmake:580 (install):
  install DIRECTORY given no DESTINATION!
Call Stack (most recent call first):
  cmake/Platform/Common/Install_common.cmake:337 (ly_setup_others)
  CMakeLists.txt:137 (ly_setup_o3de_install)

After asking one of the engineers about it, he said that people are regularly experiencing problems when trying to work across drives.  

**To Reproduce**
1. If you have multiple drives, create a repository on a drive other than your C drive
2. Create a new project using the default settings, which should place the project here C:\Users\<YOUR_USERNAME>\.o3de\Projects
3. Configure your project for a build and CMake will complain 

**Expected behavior**
I think it might make more sense to route new projects at a very minimum to the same drive that your repo is on to avoid these issues

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**

**Comment by amznestebanpapp** [comment]
I think @lumberyard-employee-dm put a fix for the "across drives" issue

**Comment by amznestebanpapp** [comment]
@lumberyard-employee-dm did your fix tackled this?
@benblack75 can you check with latest?

**Comment by lumberyard-employee-dm** [comment]
Yes, this should have been fixed in commit https://github.com/o3de/o3de/commit/fcef9333a7b0bd4ff92cda7e3348623024779c71#diff-070e0bb8a7e1253b17cdf6be6dead7ed5bf1658c329bcf867b549e5f4274f7f5

**Comment by amznestebanpapp** [comment]
@benblack75 we are closing this since it should have been fixed, if it wasn't, let us know
