### ISSUE TITLE
Missing `.hxx` files when compiling with the `INSTALL` target

### ISSUE THREAD

**Issue by na2axl** [o3de/o3de#2276]
**Describe the bug**
Not sure if it's a bug or an intentional behavior, but it seems that when we compile O3DE with the `INSTALL` target, header files with the `.hxx` extension are not copied to the install directory. So, it's not possible to use features like the `ReflectedPropertyEditor` because the header file doesn't exist (also many other `unable to find abcd.hxx` are raised when using AzToolsFramework because of that)

**To Reproduce**
1. Follow installation instructions to get O3DE
2. Compile the code using the `INSTALL` target
3. From the install directory, move to `include\Code\Framework\AzToolsFramework\AzToolsFramework\UI\PropertyEditor` for example
4. No `.hxx` file is present

**Expected behavior**
`.hxx` files are copied to the install directory, so gems and projects using installed engines can use them.

**Additional context**
For now, adding `PATTERN *.hxx` in this install command have fixed the issue:
https://github.com/o3de/o3de/blob/6d563e2e19c8e3b8329af4b2eb7aa752d4d01f6e/cmake/Platform/Common/Install_common.cmake#L61-L68

**Comment by amznestebanpapp** [comment]
yeah, should be added to that list. 
Thanks for diving and identifying where it is. Do you want to take it and implement it?

**Comment by na2axl** [comment]
@amznestebanpapp ok I will create a PR. Should I base it on `development` or `stabilization/2106` ?

**Comment by amznestebanpapp** [comment]
> @amznestebanpapp ok I will create a PR. Should I base it on `development` or `stabilization/2106` ?

do it on `development`, I will cherrypick the change to `stabilization/2106`. Currently `stabilization/2106` is "locked" so it has to go through some approvals. I can do that part for you.

**Comment by na2axl** [comment]
@amznestebanpapp it's done, please check the PR #2282
