### ISSUE TITLE
Replicate AP open behavior from Windows in Mac

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#2286]
**Is your feature request related to a problem? Please describe.**
https://github.com/o3de/o3de/pull/2272 introduced a mechanism to have the AP close when the Editor closes. We need the same mechanism in Mac

**Describe the solution you'd like**
Similar to Windows, we need the AP to close if the Editor closes, only if the Editor opened the AP.

**Comment by byrcolin** [comment]
Aged out.
