### ISSUE TITLE
Script Canvas: Opening several scripts from Gems\PhysXSamples\Assets\ScriptCanvas directory in Script Canvas crashes the Editor

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#2296]
**Describe the bug**
It has been observed that using Script Canvas to open most of scripts located in _Gems\PhysXSamples\Assets\ScriptCanvas_ directory will crash the Editor.

The following scripts were observed to be crashing:

**\Gems\PhysXSamples\Assets\ScriptCanvas\CameraRigs\Camera_LookAt
\Gems\PhysXSamples\Assets\ScriptCanvas\CameraRigs\SetRigPosition
\Gems\PhysXSamples\Assets\ScriptCanvas\CameraRigs\TPV_Camera
\Gems\PhysXSamples\Assets\ScriptCanvas\Controllers\Sphere_Controller\Sphere_Controller
\Gems\PhysXSamples\Assets\ScriptCanvas\Controllers\Sphere_Controller\Yaw_Reference_Translation
\Gems\PhysXSamples\Assets\ScriptCanvas\Cowboy\AimingSystems
\Gems\PhysXSamples\Assets\ScriptCanvas\Cowboy\CharacterController
\Gems\PhysXSamples\Assets\ScriptCanvas\Cowboy\CowboyAnimationManager
\Gems\PhysXSamples\Assets\ScriptCanvas\Cowboy\CowboyCameraRig
\Gems\PhysXSamples\Assets\ScriptCanvas\Cowboy\CowboyInput
\Gems\PhysXSamples\Assets\ScriptCanvas\Cowboy\GravityManager
\Gems\PhysXSamples\Assets\ScriptCanvas\Projectiles\DestroySelfOnDelay
\Gems\PhysXSamples\Assets\ScriptCanvas\QuadCopterAnimate_Propellers
\Gems\PhysXSamples\Assets\ScriptCanvas\QuadCopterAttachRotorWash
\Gems\PhysXSamples\Assets\ScriptCanvas\QuadCopterFourPointStabalizer
\Gems\PhysXSamples\Assets\ScriptCanvas\QuadCopterOnGroundCheck
\Gems\PhysXSamples\Assets\ScriptCanvas\QuadCopterOnGroundCheck
\Gems\PhysXSamples\Assets\ScriptCanvas\SphereBot\SphereBot_Controller
\Gems\PhysXSamples\Assets\ScriptCanvas\Weapons\Revolver\CowboyRevolver
\Gems\PhysXSamples\Assets\ScriptCanvas\Weapons\Revolver\MuzzleFlash
\Gems\PhysXSamples\Assets\ScriptCanvas\Weapons\AttachWeapon**

For further information please refer to the attached logs and video file.
[error.log](https://github.com/o3de/o3de/files/6848578/error.log)
[Editor.log](https://github.com/o3de/o3de/files/6848579/Editor.log)
[error.zip](https://github.com/o3de/o3de/files/6848580/error.zip)

https://user-images.githubusercontent.com/86953456/126331820-3b0f1f51-75cb-4e06-886d-251474321a7a.mp4

**To Reproduce**
1. Launch the Editor and open any level.
2. Open the Tools>Script Canvas.
3. Use File>Open to open the _...\Gems\PhysXSamples\Assets\ScriptCanvas\CameraRigs\Camera_LookAt.scriptcanvas_ script.

**Expected behavior**
The script is opened and the Editor remains stable.

**Desktop/Device (please complete the following information):**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Call Stack Trace**
25) 00007FF9B717C247 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FF9B9475270 (ntdll) : memset
23) 00007FF9B945C776 (ntdll) : _C_specific_handler
22) 00007FF9B947217F (ntdll) : _chkstk
21) 00007FF9B9421454 (ntdll) : RtlRaiseException
20) 00007FF9B9470CAE (ntdll) : KiUserExceptionDispatcher
19) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Include\ScriptCanvas\Core\Connection.cpp (24) : ScriptCanvas::MatchContracts
18) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Include\ScriptCanvas\Core\Connection.cpp (124) : ScriptCanvas::Connection::ValidateConnection
17) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Include\ScriptCanvas\Core\Graph.cpp (968) : ScriptCanvas::Graph::CanConnectionExistBetween
16) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Editor\Components\EditorGraph.cpp (2949) : ScriptCanvasEditor::Graph::OnVersionConversionEnd
15) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Editor\Components\EditorGraph.cpp (3635) : ScriptCanvasEditor::Graph::DisplayGraphCanvasScene
14) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Editor\Components\EditorGraph.cpp (3476) : ScriptCanvasEditor::Graph::CreateGraphCanvasScene
13) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Editor\View\Widgets\CanvasWidget.cpp (77) : ScriptCanvasEditor::Widget::CanvasWidget::ShowScene
12) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Editor\View\Windows\MainWindow.cpp (2833) : ScriptCanvasEditor::MainWindow::RefreshActiveAsset
11) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Editor\View\Windows\MainWindow.cpp (2785) : ScriptCanvasEditor::MainWindow::SetActiveAsset
10) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Editor\View\Windows\MainWindow.cpp (1402) : ScriptCanvasEditor::MainWindow::OpenScriptCanvasAsset
 9) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Editor\View\Windows\MainWindow.cpp (1420) : ScriptCanvasEditor::MainWindow::OpenScriptCanvasAsset
 8) C:\Users\Tester\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1400) : AZ::Internal::EBusContainer<ScriptCanvasEditor::GeneralRequests,ScriptCanvasEditor::GeneralRequests,0,1>::Dispatcher<AZ::EBus<ScriptCanvasEditor::GeneralRequests,Scri
 7) C:\Users\Tester\o3de\Gems\ScriptCanvas\Code\Editor\Assets\ScriptCanvasAssetHolder.cpp (94) : ScriptCanvasEditor::ScriptCanvasAssetHolder::OpenEditor
 6) C:\Users\Tester\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\UI\PropertyEditor\PropertyAssetCtrl.cpp (728) : AzToolsFramework::PropertyAssetCtrl::OnEditButtonClicked
 5) 00007FF96A310DB9 (Qt5Core) : QObject::qt_static_metacall
 4) 00007FF9694EFE57 (Qt5Widgets) : QAbstractButton::clicked
 3) 00007FF9694EFD78 (Qt5Widgets) : QAbstractButton::click
 2) 00007FF9694F0A5D (Qt5Widgets) : QAbstractButton::mouseReleaseEvent
 1) 00007FF9695C6D2F (Qt5Widgets) : QToolButton::mouseReleaseEvent

**Comment by lsemp3d** [comment]
@LB-MateuszSzweda I submitted a fix for this, can you verify and report back if anything else still crashes? thank you!

**Comment by LB-MateuszSzweda** [comment]
@lsemp3d  I have verified the fix in development branch against "3bb62ca3f71e7ee7e8340b6a46e37be8f1f059fd" as latest commit and the issue no longer occurs. All the scripts and nodes are stable and are correctly updating upon opening.
I have also verified that no other Scripts derived from /gems and /AutomatedTesting crash upon opening.
Closing the ticket as fixed.
