### ISSUE TITLE
AWS Resource Mapping Tool can't be opened

### ISSUE THREAD

**Issue by LB-JakubWrotecki** [o3de/o3de#2298]
**Describe the bug**
AWS Resource Mapping Tool can't be opened from Editor. If AutomatedTesting project is set and a profile's name in C:\Users\ <username>\.aws\credentials file is different than "AWSAutomationTest", a prompt that says _AWS credentials are missing or invalid_ comes up. If a new project is created, a prompt _Failed to launch Resource Mapping Tool_ pops up, even if correct credentials are provided.

**To Reproduce**
1. If you're on AutomatedTesting project, ensure you have different profile name(s) than "AWSAutomationTest" in configure file.
2. Launch the Editor.
3. Click on AWS located on the toolbar.
4. Click on AWS Resource Mapping Tool.

**Expected behavior**
AWS Resource Mapping Tool is usable no matter how a profile in configure file is named.

**Videos**
- AutomatedTesting:

https://user-images.githubusercontent.com/86955026/126332465-16839d6a-775b-4db8-be48-c2b91a63765c.mp4

- new project:

https://user-images.githubusercontent.com/86955026/126335482-8c683bdd-2150-429e-a7df-08c4dc16ba43.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA RTX 2060 SUPER
 - Memory 16GB

**Comment by lmbr-pip** [comment]
The first video seems to show the correct behavior as far as I can tell; am assuming the project's awscoreconfiguration.setreg file is set to use _AWSAutomationTest_ as the default profile.

* Editor and AWSCore load, and it appears you've chosen to use the AWSAutomationTest profile
* At launch, it seems like you don't have that profile in your .aws/credentials file as you renamed to _whatever_, when the mapping tool tries to load it, it fails and gives the warning about mis-configured credentials.
* When you rename that profile back to _AWSAutomationTest_ the tool works as expected.

The second video seems to be a more a bug, would need to see the editor.log as to why things failed (unfortunately the console log in the video is not scrolling to the bottom).

**Comment by LB-JakubSkoczylas** [comment]
[Editor.log](https://github.com/o3de/o3de/files/6854784/Editor.log)

**Comment by onecent1101** [comment]
The Editor.log doesn't seem like correspond to JSNew1 project in 2nd video.
Please also share Gems\AWSCore\Code\Tools\ResourceMappingTool\resource_mapping_tool.log if possible.
Note: Please make sure these two logs correspond to 2nd video example only, as they will get override whenever you run editor or tool.

And as you created a new project, can you double check whether required binaries are generated after your project build, which should locate at <path to your project build>/bin/profile/AWSCoreEditorQtBin if your build is profile (AS expected, there should be bunch of qt dll files)

**Comment by LB-JakubSkoczylas** [comment]
Hi,
my build is profile, but I do not have Gems\AWSCore\Code\Tools\ResourceMappingTool\resource_mapping_tool.log.
To build my project, I followed this instructions: https://docs.o3de.org/docs/welcome-guide/setup/setup-from-github/
Also, here is my /bin/profile/AWSCoreEditorQtBin folder to make sure all is setup correctly.
![AWSCoreEditorQtBin](https://user-images.githubusercontent.com/86952591/126609319-e816f47a-f3ff-4106-b627-c559d1e77af9.jpg)

**Comment by onecent1101** [comment]
Without log, we can't help to debug the issue, and I can't reproduce the problem. What is the reproduce step for 2nd issue?

**Comment by LB-JakubSkoczylas** [comment]
For the 2nd issue:
The path is default for out builds. There was no tool log, so I'm adding an Editor.log.
My engine root path is C:\o3de-build\o3de\build\windows_vs2019
My Project path is C:\o3de-build\o3de\CowboyKao - this is my custom project. The AutomatedTesting project has the same path.
"C:\o3de-build" - this is my personal folder for builds. "o3de" is the folder from GitHub repository.

We all use this guide to build our projects:
https://docs.o3de.org/docs/welcome-guide/setup/setup-from-github/

All settings are set by default. We use folders: 
C:\o3de-install
C:\o3de-packages

We create our projects via o3de Project Manager and rebuild them after create them.

[Editor.log](https://github.com/o3de/o3de/files/6885360/Editor.log)

Let me know if there is more info I can give you.

**Comment by LB-JakubWrotecki** [comment]
First, it might be worth mentioning that when creating this issue we split up, due to time constraints, and recorded the vids separately: 
1) the 1st one = [AWS.Resource.Mapping.Tool.-.AutomatedTesting.mp4](https://user-images.githubusercontent.com/86955026/126332465-16839d6a-775b-4db8-be48-c2b91a63765c.mp4)  was recorded by me 
2) the other = [AWS.Resource.Mapping.Tool.-.new.project.mp4](https://user-images.githubusercontent.com/86955026/126335482-8c683bdd-2150-429e-a7df-08c4dc16ba43.mp4) by @LB-JakubSkoczylas 

When it comes to my issue _(the one from the 1st video - Resource Mapping Tool opens correctly provided that AWSAutomationTest profile's name with valid keys is present in credentials - otherwise the "AWS credentials are missing or invalid(...)" warning pops up)_ I came across it with these paths set:
- Engine root: C:/builds/o3de
- Project's: C:/builds/o3de/AutomatedTesting
And here's the log, if necessary - 
[resource_mapping_tool(1a).log](https://github.com/o3de/o3de/files/6886395/resource_mapping_tool.1a.log). Not providing builds\AutomatedTesting\user\log\Editor.log as no logs were created in this file when I was doing the steps from the 1st vid.

What might be interesting is that I've just noticed that changing the Engine's root to what @LB-JakubSkoczylas 's written recently, and then trying to open Resource Mapping Tool, results in the same warning, which is:
![theSameWarning](https://user-images.githubusercontent.com/86955026/127174442-6f48e191-f632-4ecc-a7d2-9d54f42e7c0d.JPG)

And that can be observed no matter if AWSAutomationTest profile's name with valid keys is present in credentials file or is not. It seems to depends on the path where Editor.exe was launched (in this case: Engine root=C:/o3de-install and Project's path was the same as I've written above: C:/builds/o3de/AutomatedTesting).

**Comment by onecent1101** [comment]
How do you change Engine root path?

> For the 2nd issue:
> The path is default for out builds. There was no tool log, so I'm adding an Editor.log.
> My engine root path is C:\o3de-build\o3de\build\windows_vs2019
> My Project path is C:\o3de-build\o3de\CowboyKao - this is my custom project. The AutomatedTesting project has the same path.
> "C:\o3de-build" - this is my personal folder for builds. "o3de" is the folder from GitHub repository.
> 
> We all use this guide to build our projects:
> https://docs.o3de.org/docs/welcome-guide/setup/setup-from-github/
> 
> All settings are set by default. We use folders:
> C:\o3de-install
> C:\o3de-packages
> 
> We create our projects via o3de Project Manager and rebuild them after create them.
> 
> [Editor.log](https://github.com/o3de/o3de/files/6885360/Editor.log)
> 
> Let me know if there is more info I can give you.

First, C:\o3de-build\o3de\build\windows_vs2019 is not engine root path, it seems like build path
Second, I don't understand "My Project path is C:\o3de-build\o3de\CowboyKao - this is my custom project. The AutomatedTesting project has the same path." how could AT project and your custom project have the same path?

**Comment by onecent1101** [comment]
> First, it might be worth mentioning that when creating this issue we split up, due to time constraints, and recorded the vids separately:
> 
>     1. the 1st one = [AWS.Resource.Mapping.Tool.-.AutomatedTesting.mp4](https://user-images.githubusercontent.com/86955026/126332465-16839d6a-775b-4db8-be48-c2b91a63765c.mp4)  was recorded by me
> 
>     2. the other = [AWS.Resource.Mapping.Tool.-.new.project.mp4](https://user-images.githubusercontent.com/86955026/126335482-8c683bdd-2150-429e-a7df-08c4dc16ba43.mp4) by @LB-JakubSkoczylas
> 
> 
> When it comes to my issue _(the one from the 1st video - Resource Mapping Tool opens correctly provided that AWSAutomationTest profile's name with valid keys is present in credentials - otherwise the "AWS credentials are missing or invalid(...)" warning pops up)_ I came across it with these paths set:
> 
>     * Engine root: C:/builds/o3de
> 
>     * Project's: C:/builds/o3de/AutomatedTesting
>       And here's the log, if necessary -
>       [resource_mapping_tool(1a).log](https://github.com/o3de/o3de/files/6886395/resource_mapping_tool.1a.log). Not providing builds\AutomatedTesting\user\log\Editor.log as no logs were created in this file when I was doing the steps from the 1st vid.
> 
> 
> What might be interesting is that I've just noticed that changing the Engine's root to what @LB-JakubSkoczylas 's written recently, and then trying to open Resource Mapping Tool, results in the same warning, which is:
> ![theSameWarning](https://user-images.githubusercontent.com/86955026/127174442-6f48e191-f632-4ecc-a7d2-9d54f42e7c0d.JPG)
> 
> And that can be observed no matter if AWSAutomationTest profile's name with valid keys is present in credentials file or is not. It seems to depend on the path where Editor.exe was launched (in this case: Engine root=C:/o3de-install and Project's path was the same as I've written above: C:/builds/o3de/AutomatedTesting).

I think I get the problem here, do you mean you are launching Editor from C:/o3de-install? which is the path you provide through CMAKE_INSTALL_PREFIX? This is pretty new to me, I don't think we test through this way before, and it could be the problem with this executable path.

I will give a try, and try to see whether I can reproduce it locally.

**Comment by LB-JakubWrotecki** [comment]
Yes exactly, C:/o3de-install path is what I'm setting the CMAKE_INSTALL_PREFIX variable to and launching the Editor from (and after doing so I got this _Failed to launch..._ warning).

And on the other hand - I saw the warning from my vid ([AWS.Resource.Mapping.Tool.-.AutomatedTesting.mp4](https://user-images.githubusercontent.com/86955026/126332465-16839d6a-775b-4db8-be48-c2b91a63765c.mp4) - on 0:05), only when I had set CMAKE_INSTALL_PREFIX=C:\o3de-install and run Editor from C:/builds/o3de/AutomatedTesting.

**Comment by onecent1101** [comment]
I think @lmbr-pip has responded to your question in AutomatedTesting project, tool requires you to provide correct credential before using it which is through <project path>\Registry\awscoreconfiguration.setreg. If you change your aws profile to whatever, then tool can't find it as it still expect AWSAutomationTest in awscoreconfiguration.setreg.
