### ISSUE TITLE
Editor camera is moved to 0,0,0 coordinates after entering and exiting the Play Game (Maximized) mode

### ISSUE THREAD

**Issue by LB-BartoszStypulkowski** [o3de/o3de#2323]
**Describe the bug**
**Editor camera** is moved to 0,0,0 coordinates after entering and exiting the **Play Game (Maximized)** mode. The issue is not occuring for **Play Game (Ctrl+G)** mode.

**To Reproduce**
1. Open O3DE Editor.
2. Open any level.
3. Position **Editor camera** anywhere else than starting position.
4. Click the **Play Game (Maximized)** button.
5. Hit the "Esc" button.

**Expected behavior**
**Editor camera** should be restored to the view from before entering the **Play Game (Maximized)** mode, or it should stay at the same position as we left the **Play Game (Maximized)** mode (dependant on **Restore Viewport Camera on Game Mode Exit** setting).

**Screenshots**
https://user-images.githubusercontent.com/87059825/126494088-ab99e36c-77ab-403e-8aa9-4256395f8b87.mp4

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 7 3800X 8-Core Processor
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Additional context**
_Edit -> Editor Settings -> Global Preferences
General Setting -> **Restore Viewport Camera on Game Mode Exit**_
Mentioned option has no effect on the issue. Moreover the option seems to have no effect at all, I will create another ticket for it and attach it in the comment.

**Comment by LB-BartoszStypulkowski** [comment]
https://github.com/o3de/o3de/issues/2324

**Comment by AMZN-Igarri** [comment]
Cannot longer reproduce this issue as of ff0df4b8b6e66286c12391522c4814cc7f8864f7
