### ISSUE TITLE
Changes to prefab file are not reflected by its instances spawned using script canvas

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#2325]
**Describe the bug**
It has been observed that when prefab is spawned it can have different properties than instantiated one. This issue was observed while using a prefab with a specific Script Canvas file assigned. This script is responsible for spawning the same prefab as the one it is assigned to. If none of the prefabs properties are changed, then instantiated and spawned prefabs behave in the same manner. After changing properties of the instantiated prefab and saving changes to the file, spawned prefabs remain unchanged. Their properties are changed after saving the level and restarting the editor as in the attached video. Both changing and reloading the level does not cause spawned prefabs to be updated. To this bug report there is an attached attachment.zip file in which there is a video showing an issue and folder structure including a level in which the bug occurred as well as box.prefab and random_blocks.scriptcanvas files. The folder structure is set up for AutomatedTesting project.
[attachments.zip](https://github.com/o3de/o3de/files/6856199/attachments.zip)

**To Reproduce**

1. Save attached prefab and Script Canvas within used project.
2. Launch the Editor and create a new level.
3. Instantiate box.prefab and make sure that random_blocks.scriptcanvas file is selected In its Script Canvas component.
4. Open the script and make sure that all Spawn nodes have box.prefab selected as m_spawnableAsset.
5. Change value in prefab entity (Linear dampening in PhysX Rigid Body Component).
6. Select Save prefab to file to implement changes in future instances.
7. Create entity with PhysX Collider component positioned under box.prefab and enter the Game mode.

**Expected behavior**
When prefab is saved to a file all new instances of it have the same properties.

**Desktop/Device:**
•	Device: PC
•	OS: Windows
•	Version: 10 Pro
•	CPU: Intel i7 8700k
•	GPU: Nvidia RTX 2080
•	Memory: 16GB

**Comment by AMZN-mnaumov** [comment]
I think this is the same issue I've ran into during GameJame https://github.com/o3de/o3de/issues/2988

**Comment by AMZN-mnaumov** [comment]
verified still happening

**Comment by LB-KacperSzczepanski** [comment]
Verified as fixed in Development (146b2c8)
