### ISSUE TITLE
Enabling the "Stick duplicate to cursor" preference does not stick the duplicated entity to the cursor

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#2327]
**Describe the bug**
It has been observed that enabling the "Stick duplicate to cursor" option in Editor Global Preferences does not result in sticking the duplicated entity to the cursor. Moving the cursor after duplicating the entity with "Stick duplicate to cursor" enabled does not move the entity on any axis.

**To Reproduce**
1. Go to Edit -> Editor Settings -> Global Preferences -> Selection -> Stick duplicate to cursor.
2. Enable "Stick duplicate to cursor".
3. Create an entity with Mesh component.
4. Add sphere mesh to the entity for the better view of the issue.
5. Duplicate the entity (Ctrl + D).
6. Move the cursor around Viewport.

https://user-images.githubusercontent.com/86951967/126607071-5516ea35-12dd-41fd-8cb1-4718eb9f0c3e.mp4

**Expected behavior**
The duplicated entity stick to the cursor when "Stick duplicate to cursor" is enabled.

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU AMD Ryzen 7 1700 - 3,6 Ghz
 - GPU ZOTAC GeForce GTX 1060 0 AMP! 6GB GDDR5
 - Memory 16GB

**Comment by cgalvan** [comment]
@hultonha  @NicholasVanSickle  I don't see this setting ```gSettings.deepSelectionSettings.bStickDuplicate``` actually used anywhere in the code anymore. Is something we can just remove now that the new viewport is the default, or is this a feature we'd want to reimplement with the new viewport interaction model?

**Comment by hultonha** [comment]
Hmm I'd be in favor of just removing this for now - things can be duplicated and then moved with a manipulator. The weirdness with how it worked before was you would not be pressing a mouse button to ever move the object, we now have a rule that you must always explicitly interact with a manipulator (be press/move/release) of a button with a manipulator as opposed to the viewport being in some weird state where moving the mouse moves an object - so long story short I'd just say remove this option for now - in future we might want a 'screen space' manipulator or something similar to mimic this functionality
