### ISSUE TITLE
Multiple viewport layout freezes the Editor on activation

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#2339]
**Describe the bug**
Switching the Editor viewport to 4 viewports is really slow (10+ seconds) on a debug build of the Editor. Initially I thought the Editor had just crashed, but after a bit it started working again.
This is definitely better in profile, but shows the need to optimize this system.

**To Reproduce**
1. Load the Editor
2. Open a Level
3. Right click on the top toolbar of the viewport and select "Configure Layout"
4. Select a layout (in my case, 4 windows)

**Expected behavior**
The layout changes in a reasonable time

**Screenshots**
The Editor freezes for 10+ seconds.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: latest development
 - Build config: debug]

![multi-viewport](https://user-images.githubusercontent.com/82231674/126573674-75221c9c-ce62-41be-9731-acdf36cf58a6.gif)

**Comment by cgalvan** [comment]
Still in issue in latest development c056ae7

**Comment by AMZN-daimini** [comment]
The multiple viewports layout has been disabled in latest development and will be reworked before it is re-enabled.
