### ISSUE TITLE
Any component returns an error on RMB selection in Entity Inspector

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#2347]
**Describe the bug**
It has been observed that any component added to any entity returns “_[Error] (PropertyEditor) - Entity context has no root slice_” error in editor console when selected with RMB. Issue does not occur when prefabs are disabled in <root>/AutomatedTesting/user/Registry/editorpreferences.setreg.

**To Reproduce**
1.	Launch the Editor and create a new level.
2.	Create a new entity and add any component.
3.	Press RMB in the component in the Entity Inspector.

**Expected behavior**
Error referencing slices is not displayed when prefabs in editor are enabled.

**Screenshots**
https://user-images.githubusercontent.com/86953282/126640454-af4ccd5e-b316-434f-866d-e33c5108a18f.mp4

**Desktop/Device:**
•	Device: PC
•	OS: Windows
•	Version: 10 Pro
•	CPU: Intel i7 8700k
•	GPU: Nvidia RTX 2080
•	Memory: 16GB

**Comment by cgalvan** [comment]
This is actually a more generic issue, this happens for any component, not just the PhysX Character Controller. I'll update the description as such.

**Comment by LB-KacperSzczepanski** [comment]
The issue is fixed. Verified on build Development (4cf384c).
