### ISSUE TITLE
libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b on Fedora

### ISSUE THREAD

**Issue by faizol** [o3de/o3de#2384]
OS : Fedora 34

I successfully compiled the engine using generate_linux.sh script from this link https://github.com/o3de/o3de/issues/1900#issuecomment-875755078.

However when I tried to open a project, I got "libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b" error. I did look it up on the net to find possible solution to this, and from the many links, I figured that the case was probably because the engine wasn't linked to system's libk5crypto.so.3. 

Can I get a pointer on how to use the system's libraries for linking if the shared objects are available? Or if that's not recommended, what is the best way to force the binary to use the libraries that it was compiled and linked against instead of the system's libraries?

Thanks.

**Comment by anon-oss** [comment]
Solution suggested by redhat [here](https://bugzilla.redhat.com/show_bug.cgi?id=1829790#c12) might be relevant here
