### ISSUE TITLE
Level container entity can stay collapsed and make entities stay hidden

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/o3de#2395]
**Describe the bug**
Currently, there's a change that tries to expand the level container entity after listening to the OnPrefabInstancePropagationEnd() call : https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp#L1142
But if there's an error in the prefab system and the propagation is not called, which can happen when the code hits https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.cpp#L182
it would leave the level container entity in a collapsed state. Since the 'expand' button is not present for the level container entity, the entities in the outliner stay hidden and won't show up until the next time a propagation event happens. (Like adding an entity)

**To Reproduce**
1. Force the code to hit https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.cpp#L182
2. Ensure that https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp#L1142 is not hit.

**Expected behavior**
Even if there's an error, the entities in the outliner stays visible

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version : 10
 - CPU : Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz   3.31 GHz
 - GPU : NVIDIA GeForce RTX 2070 SUPER
 - Memory : 64 GB

**Suggested fixes**
- Add the 'expand' option to the level container entity so that user can at least expand and see their entities
- Rather than figure out how to always expand on propagation, maybe prevent the level from being collapsed in the first place

**Comment by AMZN-daimini** [comment]
I made a prototype for the intended Prefabs UX, which includes forcing the prefab instance container entities expanded/collapsed state based on whether they're being edited or not. While that specific change is not going in, we're going to need a similar mechanism when we start working on isolation/edit mode in the viewport soon.

I would vote against showing the expand button on the level container, as that would set us back, and instead keep this current hack on a little longer while the actual system for prefab editing is developed (which would pretty much entail your second suggestion).

**Comment by mcphedar** [comment]
Removing the errant label. We don't want to bloat the labels list with bug/<feature> labels. Instead we should use Feature/<type> and Kind/Bug in combination.

**Comment by alexmontAmazon** [comment]
accepted as a bug, but I agree with Danilo @AMZN-daimini  on this. We'll track this issue against that new editing design.

**Comment by AMZN-daimini** [comment]
Closing as I'm haven't seen this repro in months and I'm pretty sure a couple of changes back in November solved this.
