### ISSUE TITLE
FBX Setting->Actor window lacks cloth parameter settings Modifier，Cloth(NvCloth) component cannot index the configuration Cloth  in the Actor

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#2415]
**Describe the bug**
FBX Setting->Actor window lacks cloth parameter settings Modifier，Cloth(NvCloth) component cannot index the configuration Cloth  in the Actor. Cannot combine the Cloth component in O3DE to achieve the effect of skirt fluttering when runnig.

**To Reproduce**
1. Prepare an FBX file containing Colth settings and import it to the engine
2. Right click on the FBX model to enter the FBX setting->Actor interface
3. Add Modifier.
4. There is no choice with clpth modifier

**Expected behavior**
There is no choice with cloth modifier and Cloth(NvCloth) component cannot index the configuration Cloth  in the Actor.

**Screenshots**
![image](https://user-images.githubusercontent.com/32164562/126933666-e863e1e7-df00-4d5d-bf1c-5d0d46b56c40.png)

**Desktop/Device:**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel Xeon Gold 6234]
 - GPU [NVidia RTX 5000]
 - Memory [32GB]
 - Working Branch: Main branch e7f787572e805c413115265e5873fb2425e2f41b 

**Additional context**
Lumberyard Can be configured https://docs.aws.amazon.com/zh_cn/lumberyard/latest/userguide/fbx-settings-actor-tab.html

**Comment by moraaar** [comment]
In O3DE the mesh/actor tabs in FBX Settings work differently than Lumberyard. It has been applied an unification of the model format and now they worked together.

Actor tab now only takes care of the Skeleton/Skinning part of the FBX, and it takes the model information from the mesh tab. So it's correct that that Actor tab does not have a cloth modifier, only the mesh tab has.

The O3DE documentation was updated to reflect this change:

Cloth for mesh components: https://o3de.org/docs/user-guide/interactivity/physics/nvidia-cloth/meshes/
Cloth for actor components: https://o3de.org/docs/user-guide/interactivity/physics/nvidia-cloth/actors/

Notice how for actors it now also uses the mesh tab.

Thanks,
Aaron
