### ISSUE TITLE
[Animation Editor]The effects of Mirror Motion selected in the animation engine are incorrect.

### ISSUE THREAD

**Issue by nielianpeng** [o3de/o3de#2421]
**Describe the bug**
The effects of **Mirror Motion** selected in the animation engine are incorrect. (The effects are Motion in Anim Graph, Simple Motion in Components, and Motions in Animation Editor.)

**To Reproduce**
1. Right-click an existing motion and choose Preview from the shortcut menu. Observe the effect of selecting and deselecting Mirror Motion.
2. Drag the model to the scene to add the Simple Motion component, add an action, click Preview In Editor, and observe the effect of selecting and deselecting Mirror Motion.
3. Select Motions in the animation editor and observe the effect of selecting and deselecting Mirror in Time View.

**Expected behavior**
When you select a mirror action, the action changes to the original action in the mirror.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC]
 - OS: [Windows]
 - Version [10]
 - CPU: [Intel i7-9700]
 - GPU: [Intel UHD Graphics 630]
 - Memory: [32GB]
 - Working Branch: Main branch: e7f787572e805c413115265e5873fb2425e2f41b

**Additional context**

**Comment by nielianpeng** [comment]
> Hi @nielianpeng , did you set up the mirroring information in the actor manager window before testing motion mirroring? There is a "mirror setup" at the bottom of the actor manager window where you can map the joints to their mirrored versions for an actor. This is required for motion mirroring. Can you also provide a screenshot/video and a sample asset please in case the issue still exists after testing with the mirror setup?

Follow the steps you said and the Motion Mirror function works normally. Thank you!

**Comment by amzn-jillich** [comment]
Closing the issue as @nielianpeng confirmed it works after setting up the mirroring info.
