### ISSUE TITLE
Tolerance area for manipulators highlighting not optimized for efficiency

### ISSUE THREAD

**Issue by amzn-jillich** [o3de/o3de#2425]
When I tried to move many objects arounds fastly, in various directions, the tolerance area is what slowed down the most. Can we increase the tolerance area so that users don't have to be professional e-sports players in order to efficiently work with the manipulators? ;) We don't need to be this accurate and hopefully can increase the tolerance area so that using the manipulators will be a natural experience rather than an aiming effort that requires heavy concentration.

![ManipulatorAiming](https://user-images.githubusercontent.com/43751992/126971799-be8b4101-9a9f-4958-aff3-97f4cf0c19dd.gif)

**Comment by hultonha** [comment]
I have this on my list! 😝 Sorry, also tracked here - LYN-2298 - it is trivial to fix, I just need to expose that property (it's basically just a logic cylinder we're intersecting against and it's trivial to make the radius larger). I'll try get to this first thing next week :+1:

**Comment by hultonha** [comment]
@amzn-jillich when you have a moment can you have a play around with this and just confirm you're happy things are resolved. If you'd like to adjust the bound size please go to Edit -> Global Preferences -> Editor Settings -> Manipulators and change the bound size. You can visualize it by setting `ed_manipulatorBoundDebug` to true. Any questions or problems please give me a shout. Thanks!
