### ISSUE TITLE
[FBX Setting]  Coordinate system change attribute modification does not take effect

### ISSUE THREAD

**Issue by lihongjun25** [o3de/o3de#2426]
**Describe the bug**
The translation, rotation and zooming in the advanced settings of the sub-option of modifying the character coordinate system in the FBX Setting tab cannot take effect.

**To Reproduce**
1. Open fbx setting and switch to actors interface
2. Click the "Add Modifie" button and select "Coordinate system change"
3. Modify "rotation", "scale" and "translation" properties

**Expected behavior**
The character can be adapted accordingly by modifying the translation, rotation and scaling parameters

**Screenshots**

**Desktop/Device (please complete the following information):**
Device: [PC]
OS: [Windows]
Version [10]
CPU: [Intel Xeon Gold 6234]
GPU: [NVidia RTX 5000]
Memory: [32GB]
Working Branch: Main branch e7f787572e805c413115265e5873fb2425e2f41b

**Additional context**

**Comment by jackalbe** [comment]
From https://github.com/o3de/o3de/issues/11330
> When specifying a Coordinate system change (such as scaling or rotation) in the asset importer, it are correctly applied to the visual mesh, yet ignored by the pxmesh generation. Subsequently, pxmesh and visual mesh are ill-aligned / ill-scaled.
