### ISSUE TITLE
[Animation Editor]The BlendN node of the Anim Graph is displayed incorrectly.

### ISSUE THREAD

**Issue by nielianpeng** [o3de/o3de#2427]
**Describe the bug**
If the BlendN node of the Anim Graph is set to 1, only Pose 1 takes effect. As a result, Pose 0 also takes effect. However, the action of Pose 0 in the character animation in the OpenGL Render Window does not take effect.

**To Reproduce**
1. Configure Actor and Motion Sets in the animation editor and create a Blend Tree.
2. Create the BlendN node, parameter node, and 3 action nodes in the Blend Tree.
3. Set different actions for the action nodes, and connect pose0, pose1, and pose2 of BlendN respectively. Set the value of “Blend Weight triggers” to 0 for Pose0. Set Pose1 to 1. The value of Pose2 is 2.
4. Select a float attribute (the parameter name can be motion_index) from the attribute node and connect it to the weight of BlendN.
5. Click Run and enter 0, 1, and 2 for motion_index.

**Expected behavior**
Input 0, 1, and 2 only the corresponding Pose 0, Pose 1, and Pose 2 take effect. 

**Screenshots**

**Desktop/Device (please complete the following information):**
- Device: [PC]
 - OS: [Windows]
 - Version [10]
 - CPU: [Intel i7-9700]
 - GPU: [Intel UHD Graphics 630]
 - Memory: [32GB]
 - Working Branch: Main branch: e7f787572e805c413115265e5873fb2425e2f41b

**Additional context**

**Comment by amzn-jillich** [comment]
@nielianpeng can you please provide a screenshot/video of the anim graph and the settings or sample assets? We cannot reproduce the issue without further information.

**Comment by lgleim** [comment]
@hultonha Would you know if this issue is still relevant or may have already been addressed?

**Comment by hultonha** [comment]
Unless @nielianpeng is able to follow-up and confirm I think we should mark this issue as stale and close.
