### ISSUE TITLE
Editor Camera is warping image when scaling window

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#2434]
**Describe the bug**
Editor Camera is warping image when scaling editor window. 
https://jira.agscollab.com/browse/ATOM-16032

**To Reproduce**
Steps to Reproduce:
Load Editor with Model
resize editor window.
Image is warped in editor window

**Expected behavior**
Image is not warped in editor window

**Screenshots**
![image](https://user-images.githubusercontent.com/87207603/127027546-b7412f43-a1b5-4809-83e1-040484da4ffa.png)

**Desktop/Device (please complete the following information):**
 - Device:  PC
 - OS: Windows
 - Version 10
 - CPUIntel I9-9900k
 - GPU NVidia RTX
 - Memory  16GB

**Additional context**

**Comment by AMZN-daimini** [comment]
Note that opening or closing the Viewport Camera Selector widget fixes the camera
![image](https://user-images.githubusercontent.com/82231674/128079174-d5473d44-e1ed-4df0-866d-8a5884627ecb.png)

**Comment by cgalvan** [comment]
Duplicated by #2456
