### ISSUE TITLE
Bringing in FBX models from Blender

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#2435]
In trying to bring in models created in Blender I'm seeing these issues:

[Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
[Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
[Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded.  Asset may be missing, not processed or moved.  AssetId: {F851C3EA-5164-5284-816E-AB455521F77C}:3e8
[Error] (Material) - Image asset could not be loaded
[Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
[Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
[Warning] (PhysXSystem) - [1] of [1000] frames had a deltatime over the Max physics timestep[0.100000]. Physx timestep was clamped on those frames, losing [0.015632] seconds.

The model works, but in order for it to be updated in the editor I have to manually delete the products in the Cache folder. Otherwise the changes are not processed.

[ship.zip](https://github.com/o3de/o3de/files/6879926/ship.zip)

Attached the .blend and .fbx files used

**Comment by tarboss** [comment]
ship.zip (blend and fbx) is missing the image file C:\Users\luissemp\Desktop\Blender\ships\body.png and sphere texture.

https://user-images.githubusercontent.com/30550163/127061877-e686d076-84e8-4cbd-9a1d-28c58c1a82ac.mp4

**Comment by greerdv** [comment]
I had an issue with FBX files where the texture was embedded, rather than a separate file https://github.com/o3de/o3de/issues/2430. Looking at your zip, I don't see any separate material files so I think the same thing might be happening to you.

Looks like there's a separate issue with the AP not catching updates.

**Comment by ParasiteSt** [comment]
Hey @lsemp3d is this still an investigating issue? I have not had any troubles on the newest release, but my exports might not meet the criteria to have this issue.
