### ISSUE TITLE
Create New Entity At Picked Location

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2436]
When you right-click in the viewport and "Create entity", the new entity appears at an unexpected depth, sometimes very far in the distance. This especially doesn't make sense when the user right-clicked on a point that has some geometry under it. 

The system should do a "pick" to find the depth of the closest geometric surface and use that as the new entity position. Or if the pick fails, then look for a Grid component. If that fails, use Z=0.

**Comment by monroegm** [comment]
Seems to be fixed already. CC: @AMZN-daimini
