### ISSUE TITLE
Specifying the project location when creating a new project is difficult

### ISSUE THREAD

**Issue by burelc-amzn** [o3de/o3de#2446]
**Describe the bug**
When creating a new project with the O3DE Project Manager, it is difficult to specify the project location. The Project Location field requires the selected folder to be empty, but the file browser that appears from clicking the folder icon can only select folders that exist.

**To Reproduce**
1. Run `o3de` to launch the Project Manager.
2. Click on "New Project...", "Create New Project"
3. Leave the default Project name value of "NewProject"
4. Make sure that the default folder location of `~/.o3de/Projects/NewProject` does not exist, as though you were creating this project for the first time
5. Note that the Project Location field is set to its default path of `~/.o3de/Projects/NewProject`.
6. In the Project Location field, click the Folder icon to browse for the path to place the project in
7. In the file browser that appears, click the OK button

**Expected behavior**
The Project Location field accepts the path, without editing the path

**Actual behavior**
The file dialog refuses the default path of `~/.o3de/Projects/NewProject`, because it does not exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/81821305/127040702-2bed2acd-9542-4d88-89fc-9a3ac0d85c8f.png)

**Additional context**
You can work around this problem by manually creating a new, empty folder.

**Comment by DMWeiss-divesIn** [comment]
Additionally, if you try to use a different folder name, the path location does not update the folder name. It remains NewProject
