### ISSUE TITLE
Script Canvas: Variables marked as "From Component" are not always showing the properties on the component

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#2452]
Marking a variable as "From Component" is supposed to show the property on the Script Canvas component of the entity. However, it is working inconsistently. I've had the properties show up after an editor restart, but sometimes not at all.

![image](https://user-images.githubusercontent.com/58790905/127057207-d7da6d50-b05d-4f08-ad8d-8047824ab7bf.png)

**To Reproduce**
1. Create a Script Canvas graph
2. Add a variable and set it's Initial Value Source as "From Component"
3. Create/open a level and create an entity
4. Assign a Script Canvas component to the entity and assign the newly created graph
4. The variable that was added should appear as a property on the Script Canvas component, but often it doesn't

Note: There is a workaround, clear the asset in the Script Canvas component and re-assign it, then the properties will show up

**Comment by cgalvan** [comment]
The workaround isn't working for me :(

**Comment by santorac** [comment]
I've been seeing this too. Sometimes re-saving the graph works, sometimes clearing the script assignment on the component and setting it again will work, sometimes I have to restart the editor.

**Comment by lsemp3d** [comment]
This is happening on latest, it can lead to loss of work
