### ISSUE TITLE
Script Canvas: All graphs are showing up as "User Functions" even when they don't have a function definition node

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#2453]
Every graph created is showing up as a User Function even when they don't have the required elements that make functions in a graph (function definition nodes).

Steps:
1. Create a graph, save it
2. Check the "user Functions" folder in the node palette

![image](https://user-images.githubusercontent.com/58790905/127057668-eb23f17f-9c23-41f3-adc0-dabacbba54cf.png)

**Comment by cgalvan** [comment]
Fixed by https://github.com/o3de/o3de/pull/3028
