### ISSUE TITLE
Camera Aspect Doesn't Auto Update in Level Editor

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2456]
**Describe the bug**
Resize the window and the viewport will be stretched. Apply any FOV setting and the aspect will be updated to look correct again.

**To Reproduce**
1. Open a level
2. Resize the viewport. Note things look squashed.
3. Go to the little Camera toolbar button and change the FOV setting
4. The aspect ration resets to be correct, things don't look squashed anymore.

**Expected behavior**
Resizing the viewport should automatically updated the rendered aspect ratio.

**Screenshots**
![image](https://user-images.githubusercontent.com/55155825/127066544-4e55ffcc-94b2-401b-b12c-41ab230dc100.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**
This was discovered on Amazon's development branch as of 8f35def25bd3cf977e6eb06761df9ba6b67a7152

**Comment by yuriy0** [comment]
I have fixed this (and a ton of related issues) by massively refactoring the editor viewport widget, and many related components, which used to contain a whole lot of legacy (cry) things, including refactoring the Camera gem components.

This is a pretty big change, and entirely removes various pieces of cry functionality which either don't work or never worked, we have never used, are simply confusing, or are available elsewhere in a slightly different (non-legacy) manner. But if there's interesting I will look at bringing it over. If you would like to see a rough preview of these changes, add [this](https://github.com/yuriy0/o3de) as a remote and do

```
 git diff development yuriy0/master -- Code/Framework/AzFramework/AzFramework/Components/CameraBus.h Code/Editor/2DViewport.cpp Code/Editor/2DViewport.h Code/Editor/AnimationContext.cpp Code/Editor/CryEdit.cpp Code/Editor/CryEditDoc.cpp Code/Editor/EditorViewportWidget.cpp Code/Editor/EditorViewportWidget.h Code/Editor/Export/ExportManager.cpp Code/Editor/GameEngine.cpp Code/Editor/Objects/ObjectManager.cpp Code/Editor/RenderViewport.cpp Code/Editor/RenderViewport.h Code/Editor/Settings.cpp Code/Editor/TrackView/CommentNodeAnimator.cpp Code/Editor/TrackView/SequenceBatchRenderDialog.cpp Code/Editor/TrackView/TrackViewAnimNode.cpp Code/Editor/UndoViewRotation.cpp Code/Editor/UndoViewRotation.h Code/Editor/ViewManager.cpp Code/Editor/ViewPane.cpp Code/Editor/Viewport.cpp Code/Editor/Viewport.h Code/Editor/ViewportTitleDlg.cpp Code/Framework/AzCore/AzCore/Math/MatrixUtils.cpp Code/Framework/AzCore/AzCore/Math/MatrixUtils.h Code/Legacy/CryCommon/ISystem.h Code/Legacy/CrySystem/LevelSystem/LevelSystem.cpp Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp Code/Legacy/CrySystem/System.h Code/Legacy/CrySystem/ViewSystem/DebugCamera.cpp Code/Legacy/CrySystem/ViewSystem/View.cpp Code/Legacy/CrySystem/ViewSystem/ViewSystem.cpp Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorPlugin.cpp Gems/PhysXDebug/Code/Source/SystemComponent.cpp Gems/Camera
```

**Comment by alexmontAmazon** [comment]
@NicholasVanSickle please see @yuriy0 's comment before proceeding.

**Comment by NicholasVanSickle** [comment]
@yuriy0 while I'm going to PR a local fix for this one issue, we'd definitely be interested in taking some of the refactoring! I took a quick skim through the diff and the direction looks good - the more legacy code removed, the merrier! In line with your change I expect to remove `CRenderViewport` in the near future, but there are a lot of other nice removals in there that would be great to grab.
