### ISSUE TITLE
Script Canvas Nodes Flicker On Mouse Enter Leave

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2457]
**Describe the bug**
The pins and labels on a Script Canvas node flicker as you move the mouse in and out of the node area.

**To Reproduce**
1. Open Script Canvas
2. Add a InputHandler node (probably any node will do, but not sure)
3. Move the mouse in and out of the node repeatedly.

It appears this only happens when the window has focus.

**Expected behavior**
The node appearance should be stable.

**Screenshots**
I tried to capture a video using Camtasia but it wasn't able to record the issue. 

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**
I have dual 4k monitors with windows set to 150% desktop scaling.

**Comment by santorac** [comment]
Video taken from cell phone 

https://user-images.githubusercontent.com/55155825/127068999-add9ff65-9238-430e-8c93-dbe79884a54b.mov

**Comment by lsemp3d** [comment]
Note, this happens with many nodes, it's not specific to the InputHandler events

**Comment by ParasiteSt** [comment]
@santorac can you check if this issue has been resolved, I no longer receive this issue because of this PR: https://github.com/o3de/o3de/pull/10952

**Comment by santorac** [comment]
It seems to be working fine now, thanks.
