### ISSUE TITLE
[CRITICAL] Script Canvas: Variables marked as 'From Component' display the variable type in the component properties instead of the variable name

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2458]
**Describe the bug**
Variables marked as 'From Component' display the variable type in the component properties instead of the variable name.  i.e. 'Number', 'Entity' etc.  This means that you don't know what the variable is and if you have more than one variable of the same type only one will be shown on the component. 

**To Reproduce**
1. Create two script canvas variables in a new graph that are both Numbers
2. Save the graph
3. Create a new entity and add a script canvas component
4. Assign the script canvas graph you created earlier

**Expected behavior**
The variable names are shown in the component properties, one for each number

**Screenshots**
![ScriptCanvasNames](https://user-images.githubusercontent.com/26804013/127070043-525cde5b-94bc-49a5-a54e-4d658852690e.JPG)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 0.0.0 Development branch da474357f3d0ae9d9c3e884a397ccdcaec7e9be6

Possibly Related issue: https://github.com/o3de/o3de/issues/2452

**Comment by santorac** [comment]
+1

**Comment by CStudios15** [comment]
Came across this today, glad to see it already in the issues
