### ISSUE TITLE
UI Editor: Buttons do not register the click action in the Game Mode

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#2465]
**Describe the bug**
It has been noticed that the click action assigned to the Button is not registered in the Game Mode. The issue does not occur in the UI Editor's preview mode nor in the Game Launcher. Scripts are not executed upon action nor the change of states assigned to the button in the UI Editor.
However, hovering over the button is registered correctly.

**To Reproduce**
1. Create a UI Canvas.
2. Add element and assign a Button component to it.
3. Create a child of this element and assign Text component to it.
4. In the Button component add the "Pressed" state which changes the color of the text.
5. Save the UI Canvas.
6. Create an entity, add the UI Canvas Asset Ref component to it and assign previously created Canvas.
7. Check the Load Automatically checkbox.
8. Enter the Game Mode and press the button.

**Expected behavior**
Action assigned to the button is executed upon pressing the LMB.

**Screenshots**

![button](https://user-images.githubusercontent.com/86952009/127120734-a08c28c6-6a20-4cd0-90c8-a6637ad5c98c.JPG)

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU Intel I5-9600k
GPU RTX 2060
Memory 16GB

**Additional context**

https://user-images.githubusercontent.com/86952009/127120818-d6abb8fd-802d-435a-974a-f7fcf906e17c.mp4

**Comment by sphrose** [comment]
This one looks like it's fixed, I can't get it to happen in the current development branch.

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in Development (db9d67d). Closing.
