### ISSUE TITLE
Editor crashes when selecting an entity id from the viewport in a Script Canvas node

### ISSUE THREAD

**Issue by greerdv** [o3de/o3de#2468]
**Describe the bug**
The editor crashes when clicking on the target icon in Script Canvas to select an entity, and then clicking in the viewport.

**To Reproduce**
1. Add a Script Canvas node which takes an Entity Id as an input (e.g. Get World Transform)
2. Hover over the entity id input on the node and click the target icon which appears,
3. Click on an entity in the viewport.
4. Observe crash

**Expected behavior**
The desired entity is selected in the script canvas node without crashing.

**Screenshots**
![image](https://user-images.githubusercontent.com/82226198/127156104-93477f43-d7ac-4a3a-b02c-5eb00db192e6.png)
![image](https://user-images.githubusercontent.com/82226198/127155993-3beae309-c4eb-453d-9758-0e6f3790633b.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version Windows 10 version 1909
 - CPU Ryzen Threadripper 3970x
 - GPU NVidia RTX 3080
 - Memory 64GB

**Additional context**

**Comment by cgalvan** [comment]
Fixed by #2884
