### ISSUE TITLE
Resizing the viewport messes up the aspect ratio

### ISSUE THREAD

**Issue by greerdv** [o3de/o3de#2469]
**Describe the bug**
Resizing the viewport messes up the aspect ratio

**To Reproduce**
1. Resize the viewport
2. Objects in the viewport become squashed/stretched

**Expected behavior**
Objects are not distorted.

**Screenshots**
![image](https://user-images.githubusercontent.com/82226198/127157810-febb1831-b05b-4b41-a63f-726341764c1c.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version Windows 10 version 1909
 - CPU Ryzen Threadripper 3970X
 - GPU NVidia RTX 3080
 - Memory 64GB

**Comment by lawsonamzn** [comment]
It feels like this also messes with hit detection somehow (of the icons and stuff) but I'm not sure.

**Comment by cgalvan** [comment]
Duplicated by #2456
