### ISSUE TITLE
CharacterGameplayRequestBus::IsOnGround sometimes reports false when the character is on the ground.

### ISSUE THREAD

**Issue by greerdv** [o3de/o3de#2470]
**Describe the bug**
CharacterGameplayRequestBus::IsOnGround sometimes reports false when the character is on the ground.

**To Reproduce**
1. Make an IsOnGround query when the character is on the ground.
2. The result will sometimes be false.

**Expected behavior**
The result should always be true when the character is on the ground.

**Comment by LB-MateuszSzweda** [comment]
Tagging @hultonha  as per request on PhysX issues that stand out in during exploratory testing and user workflow scenarios.

**Comment by hultonha** [comment]
This is something that's definitely on our radar @cdomingo, @greerdv might be able to provide a more detailed update. We can't yet confirm exactly when this will be resolved though I'm afraid.

**Comment by hultonha** [comment]
https://github.com/o3de/o3de/pull/10860
