### ISSUE TITLE
Editor Navigation hindered while holding Left Mouse

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#2472]
Editor Navigation hindered when holding the (Left Mouse/Alt to Zoom) key down Left click Menu pops up halting scene navigation.

Navigate inside the scene via the editor, zoom in and out while holding down the left mouse / alt to zoom. You will notice zooming stops and the left click menu keeps pop-in up, halting navigation.

**Expected behavior**
I would expect smooth scene navigation, without interruption. 

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I9-9900k
 - GPU NVidia RTX
 - Memory 16GB

**Additional context**

**Comment by cgalvan** [comment]
I can't reproduce this in latest development 9ee9730

This sounds like it was found on the installer build (stabilization branch), which is missing a lot of viewport/manipulator fixes that have been done recently.
