### ISSUE TITLE
Unable to trigger Set Is Enabled on UI Canvas Ref

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#2473]
**Describe the bug**
Script Canvas has a bug - UI Canvus Ref Set is Enabled

**To Reproduce**
Reproducibility: Have steps below. I can not get any type of bool, switch, logic to (Set is Enabled) true or false with an external node connected to Enabled. Tried many different logic paths, with bools, Switch, Ifs, Math, Etc.

Images steps attached.

**Expected behavior**
A Trigger OnEvent will set the Set is Enabled bool to true.

**Screenshots**
![Script_Can_3](https://user-images.githubusercontent.com/87207603/127174781-3a102f26-5694-47f9-a257-8d022cbfa3c1.png)
![Script_Can_1](https://user-images.githubusercontent.com/87207603/127174827-890a10b1-fa33-4550-87d8-b9eba4b742f6.png)
![Script_Can_2](https://user-images.githubusercontent.com/87207603/127174880-24fa2481-246a-49db-955f-89c7dabb66d6.png)
![Script_Can_4](https://user-images.githubusercontent.com/87207603/127174915-badf39b3-65b8-4733-ac5f-42c06c7fcd93.png)

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows
 - Version 10
 - CPU Intel I9-9900k
 - GPU NVidia RTX 3090
 - Memory 16GB

**Additional context**

**Comment by lsemp3d** [comment]
With Script Canvas issues please always include the console log, it generally will have a warning and/or error that is causing the problem. It is faster to diagnose and correct if we can see it. Thanks!

**Comment by chiyenteng** [comment]
We found out that in debug mode, creating/saving script canvas files will cause the editor crash.

I can't repro the issue in profile mode. Tried using this script canvas and worked as expected: [test3.scriptcanvas.txt](https://github.com/o3de/o3de/files/7479303/test3.scriptcanvas.txt)

Here's the screenshots for the settings I used for trying to repro:
Entity Setting: 
![Screenshot 2021-11-04 153607](https://user-images.githubusercontent.com/82238204/140430649-cf8139f2-dbd2-43d8-be65-a03ec6683248.png)

Console output:
![Screenshot 2021-11-04 153651](https://user-images.githubusercontent.com/82238204/140430691-3535d2a7-5c9f-4efc-a02d-16deeace9287.png)

Game mode result:
![Screenshot 2021-11-04 153729](https://user-images.githubusercontent.com/82238204/140430713-2638d265-33ee-47f3-8ee1-61cb93d1415f.png)

Ui canvas/element used:
![Screenshot 2021-11-04 154832](https://user-images.githubusercontent.com/82238204/140430904-72885844-fdc4-44a2-9bd6-04d2a0036335.png)

**Comment by jckand-amzn** [comment]
Using the same steps as Oscar above (and the same scriptcanvas file), I see a few things differently. While the element reports that it is enabled via the ScriptCanvas file, it fails to draw in the Viewport in Game Mode. Instead, I see an assert:

```
(System) - 
==================================================================
(System) - Trace::Assert
 D:/GitHubStabilization/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawContext.cpp(456): (37856) 'void __cdecl AZ::RPI::DynamicDrawContext::DrawIndexed(const void *,unsigned int,const void *,unsigned int,enum AZ::RHI::IndexFormat,class AZStd::intrusive_ptr<class AZ::RPI::ShaderResourceGroup>)'
(System) - Can't add draw calls after draw data was finalized
(System) - ------------------------------------------------
(System) - D:\GitHubStabilization\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\DynamicDraw\DynamicDrawContext.cpp (542) : AZ::RPI::DynamicDrawContext::DrawIndexed
(System) - D:\GitHubStabilization\o3de\Gems\LyShine\Code\Source\RenderGraph.cpp (157) : LyShine::PrimitiveListRenderNode::Render
(System) - D:\GitHubStabilization\o3de\Gems\LyShine\Code\Source\RenderGraph.cpp (983) : LyShine::RenderGraph::Render
(System) - D:\GitHubStabilization\o3de\Gems\LyShine\Code\Source\UiCanvasManager.cpp (628) : UiCanvasManager::RenderLoadedCanvases
(System) - D:\GitHubStabilization\o3de\Gems\LyShine\Code\Source\LyShine.cpp (436) : CLyShine::Render
(System) - D:\GitHubStabilization\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (146) : AZ::Internal::EBusContainer<AZ::RPI::ViewportContextNotifications,AZ::RPI::NotifyByViewportNameTraits,1,1>::Dispatcher<AZ::EBus<AZ::RPI::ViewportContextNotifica
(System) - D:\GitHubStabilization\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\ViewportContext.cpp (132) : AZ::RPI::ViewportContext::OnBeginPrepareRender
(System) - D:\GitHubStabilization\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (146) : AZ::Internal::EBusContainer<AZ::RPI::SceneNotification,AZ::RPI::SceneNotification,1,1>::Dispatcher<AZ::EBus<AZ::RPI::SceneNotification,AZ::RPI::SceneNotificatio
(System) - D:\GitHubStabilization\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\Scene.cpp (622) : AZ::RPI::Scene::PrepareRender
(System) - D:\GitHubStabilization\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\RPISystem.cpp (285) : AZ::RPI::RPISystem::RenderTick
(System) - D:\GitHubStabilization\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1365) : AZ::Internal::EBusContainer<AZ::SystemTickEvents,AZ::SystemTickEvents,0,1>::Dispatcher<AZ::EBus<AZ::SystemTickEvents,AZ::SystemTickEvents> >::Broadcast<void (_
(System) - D:\GitHubStabilization\o3de\Code\Framework\AzCore\AzCore\Component\ComponentApplication.cpp (1440) : AZ::ComponentApplication::TickSystem
(System) - D:\GitHubStabilization\o3de\Code\Editor\CryEdit.cpp (2391) : CCryEditApp::IdleProcessing
(System) - D:\GitHubStabilization\o3de\Code\Editor\CryEdit.cpp (2277) : CCryEditApp::OnIdle
(System) - 00007FFE53C70DB9 (Qt5Core) : QObject::qt_static_metacall
(System) - 00007FFE53C7FA8D (Qt5Core) : QTimer::timerEvent
(System) - 00007FFE53C7854D (Qt5Core) : QObject::event
(System) - 00007FFE4C8349B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
(System) - 00007FFE4C833A33 (Qt5Widgets) : QApplication::notify
(System) - 00007FFE53C51B4A (Qt5Core) : QCoreApplication::notifyInternal2
(System) - 00007FFE53C9C439 (Qt5Core) : QEventDispatcherWin32Private::sendTimerEvent
(System) - 00007FFE53C9A869 (Qt5Core) : QEventDispatcherWin32::event
(System) - 00007FFE4C8349B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
(System) - 00007FFE4C833A33 (Qt5Widgets) : QApplication::notify
(System) - 00007FFE53C51B4A (Qt5Core) : QCoreApplication::notifyInternal2
(System) - ==================================================================
```

**Comment by chiyenteng** [comment]
> Using the same steps as chiyenteng above (and the same scriptcanvas file), I see a few things differently. While the element reports that it is enabled via the ScriptCanvas file, it fails to draw in the Viewport in Game Mode. Instead, I see an assert:
> 
> ```
> (System) - 
> ==================================================================
> (System) - Trace::Assert
>  D:/GitHubStabilization/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawContext.cpp(456): (37856) 'void __cdecl AZ::RPI::DynamicDrawContext::DrawIndexed(const void *,unsigned int,const void *,unsigned int,enum AZ::RHI::IndexFormat,class AZStd::intrusive_ptr<class AZ::RPI::ShaderResourceGroup>)'
> (System) - Can't add draw calls after draw data was finalized
> (System) - ------------------------------------------------
> (System) - D:\GitHubStabilization\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\DynamicDraw\DynamicDrawContext.cpp (542) : AZ::RPI::DynamicDrawContext::DrawIndexed
> (System) - D:\GitHubStabilization\o3de\Gems\LyShine\Code\Source\RenderGraph.cpp (157) : LyShine::PrimitiveListRenderNode::Render
> (System) - D:\GitHubStabilization\o3de\Gems\LyShine\Code\Source\RenderGraph.cpp (983) : LyShine::RenderGraph::Render
> (System) - D:\GitHubStabilization\o3de\Gems\LyShine\Code\Source\UiCanvasManager.cpp (628) : UiCanvasManager::RenderLoadedCanvases
> (System) - D:\GitHubStabilization\o3de\Gems\LyShine\Code\Source\LyShine.cpp (436) : CLyShine::Render
>...

After pulling from stable's latest, I also saw the same result and the assert messages like @jckand-amzn commented.

**Comment by VickyAtAZ** [comment]
I have a commit from development branch which fixes this assert issue. Here is the PR to cherry pick the commit to stabilization/2110 branch: https://github.com/o3de/o3de/pull/5389

**Comment by jckand-amzn** [comment]
Verified fix on stabilization/2110@652e35b0ca231. Elements can now be set to Is Enabled via SC and render without issue. Closing this out.

**Comment by chiyenteng** [comment]
@carlitosan is still working on a fix for editor crash after saving new SC in debug mode. After that got fixed, we might want to come back to verify if we can repro this issue in debug or not.

**Comment by chiyenteng** [comment]
Just verified that in debug mode ui elements can now be set to Is Enabled via SC and rendered without issue.
