### ISSUE TITLE
IDataSerializer / AZ::IO::Path does not have JSON serialization support

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#2477]
**Describe the bug**
When creating a level with an entity that has a Script Canvas component, the component appears to have an asset selected, but the selection doesn't save.

**To Reproduce**
1. Create a new level in a project with prefabs enabled.
2. Create a new entity with a Script Canvas component.
3. Press the box with an arrow to the far right of the "Script Canvas Asset" on the component to launch the script canvas editor.
4. Create a simple script canvas and save it.  I used the following:
![image](https://user-images.githubusercontent.com/82224783/127181662-a3c03efd-0cb5-47d7-b2db-19cd9039a50d.png)
5. Go back to the regular Editor and save the level.  At this point, the component should look like this:
![image](https://user-images.githubusercontent.com/82224783/127181778-d8bdf65e-a80b-48b4-a16f-56d607fc7f53.png)
6. Close the Editor.
7. Run the Editor again and load the level.
8. Look at the entity with the Script Canvas Asset.  Notice that it is now blank:
![image](https://user-images.githubusercontent.com/82224783/127181972-8f959c92-cf5e-4073-9094-075e1c5e04cb.png)

**Expected behavior**
The Script Canvas Asset is filled in with the same asset that was there when I saved the level.

NOTE:  It also appears that while you're running the Editor for the first time, if you try and go into game mode, the Script Canvas Asset doesn't run, as if it's already been blanked out, even though it's still listed on the component.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU: AMD Ryzen 3970X
 - GPU:  NVidia GTX 1660 Super
 - Memory 64 GB

**Comment by cgalvan** [comment]
Can confirm this still happens in latest stabilization.

**Comment by carlitosan** [comment]
confirmed and in progress

**Comment by carlitosan** [comment]
this is due to missing json serialization support for AZ::IO::Path, and is getting fixed immediately.
