### ISSUE TITLE
[MAJOR] Double Click entity in Entity Outliner doesn't allow renaming

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2479]
**Describe the bug**
When double clicking on an entity name in the Entity Outliner to rename the entity, the rename text box does not appear.  Sometimes, it will appear when your mouse leaves the entity name.

**To Reproduce**
1. Open a level in the editor
2. Double click on an entity in the entity outliner

**Expected behavior**
A text box appears allowing you to rename the entity

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version commit da474357f3d0ae9d9c3e884a397ccdcaec7e9be6

**Additional context**
n/a

**Comment by alexmontAmazon** [comment]
Note that the fix involves changing both behaviors: fixing the double click entry, and making sure the mouse leave event doesn't trigger the edit.

**Comment by AMZN-daimini** [comment]
This was an intentional change, as double click is meant to become the interaction to edit a prefab.
Renaming now occurs when clicking a selected row, similarly to what happens on the Windows explorer. (Note that this behavior is a bit bugged so it does need a fix).

@rainbj

**Comment by AMZN-alexpete** [comment]
Why does double-clicking in the Entity Outliner mean 'edit a prefab'?  It appears that double-click in the entity outliner doesn't do anything.  If you mean double-clicking in the Viewport means 'edit a prefab' I can see that, but don't see why double-click in viewports means we cannot use double-click to rename an entity in the entity outliner.

**Comment by AMZN-daimini** [comment]
It's meant to become = it has yet to be implemented :)

I think the idea is to have the same behavior in both the Outliner and the Viewport. I'm sure this will be brought up soon once the Isolation Mode UX is discussed.

**Comment by cgalvan** [comment]
Closing this for now, as mentioned above this is the designed behavior since the double click is reserved for the edit prefab functionality coming soon.
