### ISSUE TITLE
Creating New Entities Don't Snap-to Ground

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#2481]
**Describe the bug**
Newly created entities are often spawned so far away, that they are hidden behind other entities in the level.  We should raycast to see if other entities are in the way so that the new entity is in-front of the other objects.

**To Reproduce**
1. Open Editor.exe and a new level
2. Use Entity Outliner to create a new entity 
![image](https://user-images.githubusercontent.com/32776221/127191611-0962ec5e-22ac-418c-a4e9-54caf8ab2389.png)
4. Notice where entity spawns
![image](https://user-images.githubusercontent.com/32776221/127192677-45d6d258-875c-4500-a3a9-cfa554b3a4dc.png)

**Expected behavior**
Entity spawns under the floor off in the distance.
We should raycast to test if other objects are in the way so that when spawn a new entity it's in-front of the other objects.

**Comment by cgalvan** [comment]
Fixed by https://github.com/o3de/o3de/pull/3094 . Verified in latest development aff3b93
