### ISSUE TITLE
Pressing Ctrl+G a second time requires that the viewport is focused again

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#2482]
If you press Ctrl+G and test your game, then press ESC to stop it, pressing Ctrl+G again does not immediately re-launch the game, instead, you need to go click on the viewport to re-establish focus and then Ctrl+G works again.

**To Reproduce**
1. Press Ctrl+G to start the game
2. Press ESC to stop the game
3.Press Ctrl+G again
4. The game does not start

**Expected behavior**
The game should start

**Comment by cgalvan** [comment]
Duplicated by #2194
