### ISSUE TITLE
[BLOCKER] When UI Editor is open, all input is consumed, ESC won't get you out of game mode

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2488]
**Describe the bug**
If UI Editor is open, ESC won't get you out of game mode and all input appears to be consumed by UI editor, even if you close the UI editor
it will still consume input and prevent leaving game mode.

If you manage to close the UI Editor, the Entity Properties window will remain disabled until you enter and exit game mode again.

**To Reproduce**
1. Open a level in the editor 
2. Open the UI Editor
3. Use CTRL+G to enter game mode
4. press ESC to exit game mode

**Expected behavior**
You can exit game mode and the game receives input events

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da474357f3d0ae9d9c3e884a397ccdcaec7e9be6 (development)

**Additional context**
n/a

**Comment by AMZN-daimini** [comment]
Just encountered this, thought my code was incorrect -.-

**Comment by Amzn-Catdo** [comment]
Same issue? https://github.com/o3de/o3de/issues/2740

**Comment by Amzn-Catdo** [comment]
Same issue?
https://github.com/o3de/o3de/issues/2740
https://github.com/o3de/o3de/issues/2712
https://github.com/o3de/o3de/issues/2515

**Comment by cgalvan** [comment]
Duplicated by #2515
