### ISSUE TITLE
When GameLift Gem is Enabled ServerLauncher Silently Fails

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#2492]
**Describe the bug**
If you try to open the ServerLauncher.exe with the GameLift gem enabled, the program will become unresponsive.  Users should use "Local GameLift" to test locally, but no errors/popups occur telling customers why their server isn't working.

**To Reproduce**
1. Enable GameLift gem
2. Build ServerLauncher
3. Run ServerLauncher
4. ServerLauncher will silently fail to load because it is waiting to connect to GameLift. It will become unresponsive.

**Expected behavior**
ServerLauncher should show a popup explaining that GameLift cannot be reached.  Explain to users that they need to run "Local Gamelift" if they want to test GameLift locally, or provide a weblink so they can research how to use GameLift.

**Comment by lmbr-pip** [comment]
Sounds like fix would be to:

* [minimum] Add error logging on timeout/connection errors
* Add controls around retrying.

Server launch should become unresponsive for any significant period of time.

**Comment by onecent1101** [comment]
The issue is GameLiftLocal has to run in advance, server application is stuck if there is no GameLiftLocal running on the background. I think there is limited stuff we can do here.

**Comment by AMZN-Gene** [comment]
Ah, so Gamelift's Init() method will simply hang an application without any callbacks.  Not much you can do... 

From a user experience standpoint it's more acceptable if "I" hang the app, meaning... if I call Gamelift Init() at least I know I did something wrong to cause the hang rather than building an exe (for which I didn't write any code), which then proceeds to hang.  I dont actually recommend forcing users to call GameLift init() themselves, since that one extra step would also get annoying :P
