### ISSUE TITLE
[MAJOR] Mouse cursor does not hide when moving in viewport

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2493]
**Describe the bug**
The mouse cursor does not hide when moving or rotating in the viewport using the mouse which is very distracting.  There doesn't appear to be any editor preference to change this behavior.

**To Reproduce**
1. Open a level in the editor 
2. Look around in the viewport by holding down the right mouse button and moving the mouse

**Expected behavior**
The mouse cursor is hidden while the right mouse button is held down and the mouse is inside the viewport window.

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da474357f3d0ae9d9c3e884a397ccdcaec7e9be6 (development)

**Additional context**
n/a

**Comment by alexmontAmazon** [comment]
so long as this only pertains to hiding during WASD or mouse movement, I don't think we need a pref.

**Comment by hultonha** [comment]
This can be turned back on at the moment by setting `ed_showCursorCameraLook` to false in your `user.cfg` file - the reason we don't to that right now is having it be captured/hidden caused this incredibly annoying context menu pop-up bug (issue #2251). Seeing the cursor is currently the lesser of two evils right now but I'm looking into a fix so we can hide the cursor and also not have the right click context menu show up after a move.
