### ISSUE TITLE
[CRITICAL] Editor does not remember level's camera transform

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2497]
**Describe the bug**
The editor does not remember the editor camera's last transform in a level (prefabs enabled) and the camera always starts off in the ground.

**To Reproduce**
1. Open a level in the editor 
2. Move the editor camera out of the ground and save the level
3. Re-open the editor and the level

**Expected behavior**
The camera position and orientation match the position and orientation last used in the level

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da474357f3d0ae9d9c3e884a397ccdcaec7e9be6 (development)

**Additional context**
n/a

**Comment by cgalvan** [comment]
Duplicated by #2074
