### ISSUE TITLE
White Box component - Can't change the Default Shape. 

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de#2505]
**Describe the bug**
In the Editor, I can't change the default shape in the White Box component. 

**To Reproduce**
1. Download o3de repo. Build the installer. Build the engine using the installer. Follow the instructions here: https://o3de.org/docs/welcome-guide/setup/setup-from-github/
2. Create an entity. 
3. Add a White Box component to the entity. 
4. Change the Default Shape property to anything other than Cube. For this example, change it to Sphere. 
5. See the error. 

**Expected behavior**
The mesh of the entity should turn into a sphere. It remains as a cube and outputs an error. 

**Screenshots**
This is the error I received: Missing `default_shapes.py`. 
![image](https://user-images.githubusercontent.com/75444793/127213002-8c178076-896b-4767-8009-cb53ed28aa18.png)

This is the White Box component. The error occurred when I tried to change the Default Shape. Cube (default) works, but the other shapes do not. 
![image](https://user-images.githubusercontent.com/75444793/127213334-31b0fc03-c550-46de-abec-200ed83c547a.png)

**Desktop/Device (please complete the following information):**
 - Device: PC/Laptop
 - OS: Windows
 - Version 10
 - CPU: Intel i9 10th Generation
 - GPU: NVidia RTX 2070 Super
 - Memory [e.g. 16GB]

**Additional context**

**Comment by cgalvan** [comment]
All default shapes now work correctly in latest development aff3b93
