### ISSUE TITLE
Usability issue - Need to save prefabs

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de#2506]
**Describe the bug**
I made some changes to a prefab in the game, and did not "save to file". Then, when I relaunched the game, the prefabs reverted to their saved file, so I lost the changes I made. I am guessing this issue occurred because I needed to save the prefab. It would be helpful to receive a warning to save your prefab before closing the Editor. 

**To Reproduce**
1. Launch O3DE and open a level in the Editor. 
2. Create a prefab. 
3. Make changes to the entity attached to the prefab. In this example, I added a new entity to the prefab. Note the asterisk (*), which means that the prefab needs to be saved. 
![image](https://user-images.githubusercontent.com/75444793/127216110-95648b68-d396-4c4b-905d-7bd9ce609dde.png)
4. Close the Editor. 

**Expected behavior**
I expect one of the following situations when I reopen the Editor:
- The changes I made are still in the prefab entity in the Editor at an "unsaved" state. 
- Before closing the Editor, I get a warning that I need to save the changes made to the prefab or else I will lose the changes. 

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [e.g. **PC (laptop)**, Mac, iPhone, Samsung] 
 - OS: [e.g. **Windows**, macOS, iOS, Android]
 - Version [e.g. **10**, Bug Sur, Oreo]
 - CPU **Intel I9 10th gen**
 - GPU **NVidia RTX 2070 Super**
 - Memory **32GB**

**Additional context**
Is it possible to make changes to a prefab that is in the level, without making changes to the prefab file?

**Comment by lawsonamzn** [comment]
This is a critical data loss problem!  I'd expect the 'save' button in the editor to save all unsaved changes, or at least there being a prompt about unsaved changes to prefabs if you try to close.

**Comment by rainbj** [comment]
MVP designs 
![Current state](https://user-images.githubusercontent.com/82551958/131596308-eea0f0e6-56cf-4a5c-9bff-2227d34bd381.png)

**Comment by rainbj** [comment]
The attached design lean toward the short term designs to help with data loss. Long term solution will be readdressed in a follow up ticket

**Comment by srikappa-amzn** [comment]
Ability to save all prefabs has been added to the development branch. 

Here's what the 'close level' dialog looks like now:
![Close Level(after changes)](https://user-images.githubusercontent.com/82230713/134403223-42057ffa-e2b6-4496-850a-11e6b943ec3f.PNG)

Here's what the 'save level(ctrl+s)' dialog looks like now:
![Save Level(after changes)](https://user-images.githubusercontent.com/82230713/134403228-8d087dbe-6669-4715-8305-f0fa7c50881d.PNG)

Here's the preference that you can update to indicate whether you want to save all prefabs by default when you hit ctrl+s:
![Global Preferences(after changes)](https://user-images.githubusercontent.com/82230713/134403226-3415a059-5d55-49e8-b6cf-f8f47e98c74a.png)

Ability to select individual prefabs for saving is not included with this change can needs to be addressed later.
