### ISSUE TITLE
Bug: Game mode does not allow UI input if UI editor has been opened

### ISSUE THREAD

**Issue by amzn-mgwynn** [o3de/o3de#2515]
**Describe the bug**
If you open the UI editor, UI elements will become unresponsive in game mode even after closing the UI editor. To get UI elements to respond you have to restart the editor and not open UI editor.

**To Reproduce**
1. Open UI editor and add a button and/or text field
2. Save UI canvas
3. Create entity in the editor, add ui canvas asset ref component to it and assign the canvas you just made
4. Enable autoload property on ui canvas asset ref component
5. run game mode. You will see your canvas
6. Interact with ui elements and observe they are unresponsive
7.  Save level and close editor
8. Reopen editor, load level and start game mode
9.  Interact with ui elements and observe they are responsive

**Expected behavior**
UI elements are responsive in game more regardless of whether UI editor is open or has previously been opened

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: i7-7820x
 - GPU: GTX 2080
 - Memory: 64 GB

**Additional context**

**Comment by Amzn-Catdo** [comment]
Same issue? 
https://github.com/o3de/o3de/issues/2488
https://github.com/o3de/o3de/issues/2740
https://github.com/o3de/o3de/issues/2712

**Comment by AMZN-alexpete** [comment]
@amzn-mgwynn this issue should be fixed in the development branch now that https://github.com/o3de/o3de/pull/2948 has been merged - can you re-test and close this issue fixed?

**Comment by Amzn-Catdo** [comment]
Verified on github development branch at commit 9579826 that this issue have been fixed.
