### ISSUE TITLE
[Blocker] ServerLauncher.exe Debug Console Doesn't Work

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#2516]
**Describe the bug**
ServerLauncher.exe Debug Console doesn't allow users to type in commands.

**To Reproduce**
1. Build and Run ServerLauncher.exe
2. Use ~ to open the Debug Console (should be opened by default)
3. Type any command and press enter
4. Notice enter doesn't execute any command.

**Expected behavior**
Debug console should allow users to execute cvars

**Comment by amzn-phist** [comment]
Also, I found and fixed an unrelated issue where `.ServerLauncher` wasn't declaring `CrySystem` as a CMake runtime dependency.  So the server launcher was failing to start if you hadn't built the game launcher beforehand .

**Comment by amzn-phist** [comment]
@lmbr-pip  The fix for the CrySystem dependency is already in the PR.  Let's just fix them both.
