### ISSUE TITLE
Update location of the Multiplayer Gem jinja templates

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#2518]
**Describe the bug**
The MultiplayerSample project is using the Multiplayer Gem templates in a PUBLIC manner, but the jinja templates are underneath the [Code/Source](https://github.com/o3de/o3de/tree/development/Gems/Multiplayer/Code/Source/AutoGen) directory within the Multiplayer Gem, which is a PRIVATE directory. This means that during the INSTALL step which creates an SDK layout, these jinja templates files are not copied over.

Without the jinja templates, that the MultplayerSample project isn't able to configure with an SDK Engine.

**To Reproduce**
1. Build an SDK Layout for the engine using `cmake -B <build-dir> --target INSTALL --config profile`
2. Examine the `Gems/Multiplayer/Code` directory in the SDK layout and notice there is no Source/AutoGen directory within the layout

**Expected behavior**
The PUBLIC jinja templates for the Multiplayer Gem are moved to the `Gems/Multiplayer/Code/Include/Multiplayer/AutoGen` directory in the engine root

**Screenshots**
![image](https://user-images.githubusercontent.com/56135373/127238604-30c19c62-a8ec-4b65-8b89-7902f586134d.png)

**Desktop/Device (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by AMZN-puvvadar** [comment]
Closed by #4321
