### ISSUE TITLE
release build generating error in Atom debug camera component

### ISSUE THREAD

**Issue by Arazu161** [o3de/o3de#2530]
**Describe the bug**
When building a release config, the following error is produced:
```
C:/O3DE/o3de/Gems/Atom/Component/DebugCamera/Code/Source/CameraComponent.cpp(238,52): warning C4100: 'orthographic': unreferenced formal parameter [C:\O3DE\o3de\build\windows_vs2019\External\Atom-bbad4b14\Component\DebugCamera\Code\Atom_Component_DebugCamera.Static.vcxproj]
```

**To Reproduce**
1. After config (following the online guide), use the following command to build from the command line:
`cmake --build build/windows_vs2019 --target INSTALL --config release
`

**Additional Notes**
The offending function definition can be found here:
https://github.com/o3de/o3de/blob/development/Gems/Atom/Component/DebugCamera/Code/Source/CameraComponent.cpp#L238

Adding ` [[maybe_unused]]` to the `bool orthographic` parameter removes the error and allows for a successful build. I'm assuming that this was omitted unintentionally, as the function definition below it for `SetOrthographicHalfWidth` is tagged with `[[maybe_unused]]` correctly.

**Comment by Arazu161** [comment]
I have created a PR to add the attribute - #2596

**Comment by superkitcath** [comment]
Resolved by @NicholasVanSickle

**Comment by superkitcath** [comment]
> If it's not going to be used, I guess I'll close my PR too?...

You can leave it open, it will be reviewed during the next monthly meeting. We will take action then, if needed. 
Thank you!
