### ISSUE TITLE
Script Canvas nodes jittery on mouse over

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#2534]
**Describe the bug**

While using Script Canvas the way the nodes resize (grow/shrink) with mouse over events can be incredibly jittery and sensitive. This makes making connections difficult and error-prone.

**To Reproduce**

1. Open a Script Canvas graph
2. Mouse over nodes and observe how they flicker larger/smaller when trying to interact with the nodes

**Expected behavior**

Nodes have reasonable tolerance and dead-zone to prevent flickering when moving mouse over inputs/outputs.

**Screenshots**

Desktop/Device (please complete the following information):

    Device: PC
    OS: Windows
    Version 10
    CPU Processor Intel(R) Xeon(R) CPU E5-1630 v4 @ 3.7GHz
    GPU NVIDA GeForce GTX 1080 Ti
    Memory 32GB

Also worth mentioning I have a DPI display which may potentially be impacting this too.

**Additional context**

https://user-images.githubusercontent.com/82228511/127344545-b1552a90-8b5c-4e79-be67-e91aed741b4f.mp4

**Comment by rbnpontes** [comment]
This is same behaviour from issue #2457

**Comment by hultonha** [comment]
Ah good spot @rbnpontes thanks, I can just close this as a dup 👍
