### ISSUE TITLE
Default Level Ground Plane Should Have Physics Collider

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2545]
**Is your feature request related to a problem? Please describe.**
When you create a new level, add some models, and add PhysX components to them, they don't interact with the ground plane but just fall through. The user must add the collider for the ground plane themselves.

**Describe the solution you'd like**
When creating a new default level, the ground plane should already have a PhysX collider component on it.

**Comment by AMZN-daimini** [comment]
Closing as the ground has a Physics collider by default in latest development.
![image](https://github.com/o3de/o3de/assets/82231674/1ac0d482-98fb-4201-b4b0-3006a3261fc9)
