### ISSUE TITLE
Script Canvas doesn't support "Get Element" for arrays of Color

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#2546]
**Describe the bug**
When you create a variable in ScriptCanvas that's of type Array<Color>, you can't use the Get Element node to get an element from it.

**To Reproduce**
1. In SC, create a new variable of type Array<Color>.  Add a few values to it.
2. In the graph, drag the variable into the scene to create a "Get (name)" node.
3. Drag a "Get Element" node into the scene.
4. Try to hook the two nodes together.

**Expected behavior**
The two nodes should be able to be hooked together.  However, they can't because Get Element is looking specifically for type "Array<String>" instead of accepting any container.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU: AMD Ryzen 3970X
 - GPU:  NVidia GTX 1660 Super
 - Memory 64 GB

**Comment by carlitosan** [comment]
![image](https://user-images.githubusercontent.com/82187351/128951521-d4173100-9cd7-450e-9ef4-1e714f6bdb87.png)

Unable to reproduce
