### ISSUE TITLE
"Save Prefab" dialog opens pointing at root of the drive instead of a reasonable start location

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/o3de#2551]
**Describe the bug**
Prefab "save as" dialog opens in the root of the drive outside any asset folders.  This only happens the first time for a new project.

**To Reproduce**
1. Create a new project
2. Open the editor
3. Click 'create entity' in viewport, select the entity
4. Click 'create prefab'.  
**Expected behavior**
The default "open location" is the project's Assets/Prefabs folder (create if not exist?)

**Actual Behavior** 
Root of your hard drive is shown, and you have to manually navigate.  If you actually save the prefab here, it will not work!

**Desktop/Device (please complete the following information):**
 - Device: Windows 10 PC
 - The project was compiled externally to the engine, project-centric, engine-as-source.

**Comment by AMZN-mnaumov** [comment]
I can't seem to repro this. I've tried creating new project several times... further more there is a code check to create Prefabs path if it's missing.
The only place I can see it go wrong is AZ::IO::FileIOBase class itself due to not being connected to AP.
