### ISSUE TITLE
Project Manager "View In Directory" link doesn't do anything

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/o3de#2553]
**Describe the bug**
The Project Manager gem selection screen has a link to "View In Directory" which should open the gem folder.  However, it does nothing.

**To Reproduce**
1. Open the Project Manager
2. Click on the hamburger menu next to a project name and choose Edit Project Settings
3. Click "Configure Gems" (top right)
4. Select any gem
5. Click the "View Documentation" or "View In Directory" links in the top right window

**Expected behavior**
Something occurs, Maybe it opens the folder containing the gem?

**Screenshots**
<img width="233" alt="image" src="https://user-images.githubusercontent.com/70027408/127376067-ed1aef9f-4716-48fa-acfe-f6b04930bc7f.png">

**Desktop/Device (please complete the following information):**
 - Windows 10 PC

**Comment by cgalvan** [comment]
In latest development aff3b93 the "View In Directory" correctly opens up a file explorer for the gem directory, and then "View Documentation" opens up the relevant documentation URL on o3de.org.
