### ISSUE TITLE
AWS Resource Mapping tool creates invalid default configuration files

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/o3de#2555]
**Describe the bug**
If you allow the AWS Resource Mapping tool to create default configuration files, it creates files that it, itself, cannot read back, which causes the UI to gray out and be non functional.

**To Reproduce**
1. Have the AWS Core gem enabled in a project.  (Project-centric workflow). 
2. Make sure you have no AWS Resource Mapping configurations already ,this is the case for the default projects.
2. Open the Editor
3. Click AWS -> Aws Resource Mapping Tool...
4. In the dialog that appears there should be no configs.  Click the "Create New" button.
5. The dropdown changes to have "Found 1 config files".  
6. Pick the newly created config file from the dropdown

**Expected behavior**
The files it generates it can read itself!

**Actual behavior*
 Instead, it generates a file it cannot read and outputs the error 
```
Found unexpected value 'aws-global' at 'root/Region', please follow expected pattern ... 
```
You can then not save, alter, etc.

**Screenshots**
<img width="917" alt="image" src="https://user-images.githubusercontent.com/70027408/127377403-cc79dc89-5dbc-4618-9da2-d68f538b2b78.png">

**Desktop/Device (please complete the following information):**
 - windows 10 desktop

**Additional context**

Example of a generated file (actual account# removed)
```
{
    "AWSResourceMappings": {},
    "AccountId": "xxxxxxxxxxx",
    "Region": "aws-global",
    "Version": "1.0.0"
}
```

**Comment by lawsonamzn** [comment]
Note that this might be user error, but I'm guessing its a pretty common case - maybe special detection required?

**Comment by onecent1101** [comment]
resource mapping tool requires local aws credential setup correctly, I guess you don't have aws profile configured properly which should include both credential and region information.
so resource mapping tool creates config file with "aws-global" (it is not really a valid aws region right now, as most of aws services are regional) which is a default region if no region info found with profile.
will check with team whether we should loose schema validation on region, or we should hardcode default region to "us-west-2" something like that.

**Comment by lmbr-pip** [comment]
This was fixed in https://github.com/o3de/o3de/pull/2856
