### ISSUE TITLE
Enabling an AWS Gem does not automatically enable the AWS Core Gem

### ISSUE THREAD

**Issue by willihay** [o3de/o3de#2563]
**Describe the bug**
When I enable an AWS Gem (e.g. AWS ClientAuth) in Project Manager, it does not automatically enable the AWS Core Gem. And so when I build the project (project-centric, SDK engine), the AWS menu does not appear in the Editor, since the runtime dependency is missing.

From what I've learned, the AWS Gems _should_ be able to be configured such that AWS Core is a runtime dependency, so that I won't have to remember to enable Core in Project Manager.

**To Reproduce**
1. Open Project Manager.
2. Create a project.
3. Configure Gems so that AWSClientAuth is enabled, but AWSCore is not.
4. Save and build the project.
5. Launch the project in Editor.

**Expected behavior**
AWS menu is available in Editor and the AWS Client Auth Gem is enabled.

**Actual behavior**
AWS menu does not appear in Editor.

**Comment by lawsonamzn** [comment]
Wierd!  The AWS Client Auth gem definitely depends on the Aws Core Gem (from its CMakeLists.txt)
```
BUILD_DEPENDENCIES
        PRIVATE
            AZ::AzCore
            AZ::AzFramework
            Gem::AWSCore
```

Maybe it also needs to be a RUNTIME_DEPENDENCIES in there??  Its supposed to implicitly enable all dependencies, even if the gui only shows user-enabled explicit ones.

**Comment by onecent1101** [comment]
AWS menu is inside AWSCore.Editor target, so project manager should add AWSCore in enabled_gems.cmake file.

**Comment by lawsonamzn** [comment]
Oh, actually, I see whats going on here!  

AWSClientAuth depends on AWSCore, which is correct.  But there is nothing in AWSClientAuth that actualy depends on AWSCore.Tools (ie, the editor module).

To make this automatic you'd have to tell the system that even though AWSClientAuth has no Editor/Tools module, it relies on AWSCore.Editor being present
```
# (in AWSClientAuth's CMakeLists.txt)
# If this gem is enabled, add Gem::AWSCore.Tools:
ly_create_alias(NAME AWSClientAuth.Tools NAMESPACE Gem TARGETS Gem::AWSCore.Tools)
```

**Comment by onecent1101** [comment]
Synced offline with @lawsonamzn, need to modify AWS gems cmake to adopt this support.
The problem is: we assume customer has to enable dependent gems manually, but actually if we define cmake target correctly with dependencies, customer just need to enable required gems and all dependent gems will be handled by system automatically.
