### ISSUE TITLE
Jumping Camera Entity Icon

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2564]
**Describe the bug**
If you "be this camera" on a camera entity, and that entity has an icon, the icon will jump around on the screen sparatically.

**To Reproduce**
1. Create a new level
2. There should be a "Camera" entity under "Atom Default Environment" (or you could create a new entity with Camera component).
3. Make sure the camera entity displays a locator icon when it isn't selected. 
    a. Select the camera entity.
    b. It might be sufficient to move the Camera component to be the first component in the list OR...
    b. Add a Script Canvas component
    c. Drag the Script Canvas component to be the first component in the list
    d. De-select the camera entity and make sure you can see a locator icon at it's location.
4. Select the camera entity
5. In the Camera component, click "Be This Camera".
6. Navigate around the scene using WASD controls
7. You will occasionally see the camera locator icon flash on the screen at random locations. It could be one every few seconds or many times per second.

**Expected behavior**
The camera entity's locator icons should be invisible whenever that camera is in use.

**Screenshots**
https://user-images.githubusercontent.com/55155825/127392916-f0955853-e26c-474a-921e-23b70f13d7ff.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by AMZN-daimini** [comment]
Seems related to this issue I reported: https://github.com/o3de/o3de/issues/2759

**Comment by AMZN-daimini** [comment]
This was fixed in the related issue above.
