### ISSUE TITLE
Script Canvas gives ParseExecutionMultipleOutSyntaxSugar error

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#2565]
**Describe the bug**
When adding a print node to my graph as a second output off of a "For Each" node, I get the error "ParseExecutionMultipleOutSyntaxSugar: null Grammar::ExecutionChild found".

**To Reproduce**
1. Create a Script Canvas graph similar to the following
2. Save it
3. See the error reported in the Graph Validation tab.

**Expected behavior**
No error, and I can print my debug output.

**Screenshots**
![image](https://user-images.githubusercontent.com/82224783/127392178-840b6898-55fe-41f3-802e-20196643dc83.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU: AMD Ryzen 3970X
 - GPU:  NVidia GTX 1660 Super
 - Memory 64 GB

**Comment by carlitosan** [comment]
Fix in review now https://github.com/o3de/o3de/pull/2582
