### ISSUE TITLE
More Options for Hiding Debug Draw Items

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2567]
**Is your feature request related to a problem? Please describe.**
I want to be able to hide physics collider shapes from the editor viewport. The "Toggle viewport helpers" toolbar button does hide them, but it hides all debug shapes like camera and light outlines. The "Visible" setting on the shape component doesn't completely hide the the debug shape, it only changes it to be not "Filled" but still affects the appearance of the mesh. Even if that did work, it's on a per-entity basis which could be useful but I also want to hide all collider shapes in the scene.

**Describe the solution you'd like**
1. Fix the shape component's "Visible" flag to actually make the shape invisible.
2. Add an option to the viewport helpers menu that can turn off all the collider shape rendering.
3. (It would probably be good to add many more options to the viewport helpers menu for fine tuning the viewport).

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/55155825/127394545-dabfde33-f2bb-4a20-a46d-bd6fda58ca95.png)

**Comment by superkitcath** [comment]
Please reopen as an RFC under the sig-presentation repo [[https://github.com/o3de/sig-presentation/tree/main/rfcs](url) 

The procedure can be found here: [https://github.com/o3de/rfcs#the-rfc-process](url)

Thank you!
