### ISSUE TITLE
Discrepancy in Project Manager gems list when opened via editor versus directly

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/o3de#2568]
**Describe the bug**
The list of enabled gems in the Project Manager is different (ie, empty) if you open it via the editor "File->Edit Project Settings..." in the editor vs if you open the project manager directly.

**To Reproduce**
1. Open the editor for any project
2. Click File->Edit Project Settings
3. Click 'Configure Gems'
--> Notice how all the gems show up as disabled even though some are actually enabled.   If you open the project manager directly instead of via the editor, it functions correctly

**Expected behavior**
Whether you open the project manager yourself or via the editor shortcut to it, it should always show you the same view of your project.

 - Device: Windows 10 PC
 
**Additional context**
It is unclear whether this was on a SDK install type of run or a in engine run or whether this matters.

**Comment by lawsonamzn** [comment]
From azic#5639 in discord:
https://discord.com/channels/805939474655346758/861713485725433857/870037712021901383

**Comment by lumberyard-employee-dm** [comment]
For reference the Code that launches the Project Manager from the "Edit Project Settings" menu is [here](https://github.com/o3de/o3de/blob/development/Code/Editor/CryEdit.cpp#L2900-L2910)
