### ISSUE TITLE
Script Canvas Change Variable Vector Size

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2571]
**Is your feature request related to a problem? Please describe.**
I created a whole graph based around a Vector2 variable and later realized it would be more convenient to use a Vector3.

**Describe the solution you'd like**
For vector types, allow the user to convert a VectorN to some other VectorN and automatically update connections where possible. Where it isn't possible, highlight the issues for the user to manually correct.

**Describe alternatives you've considered**

**Additional context**

**Comment by lsemp3d** [comment]
This is great feedback, please submit it as a feature request through an RFC, thanks!
