### ISSUE TITLE
Script Canvas Generate Screenshot

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2574]
**Is your feature request related to a problem? Please describe.**
It is sometimes necessary to share screenshots of Script Canvas graphs for collaboration. It's hard to get these screenshots since the graphs usually don't fit on the screen while maintaining readable text.

**Describe the solution you'd like**
Add an "Export graph image" that will generate an image file showing the complete shader canvas graph at a resolution where the text is readable. There could be an additional step where the user draws a box around some sub-section of the graph, and generate the image just for that area.

**Describe alternatives you've considered**
I had to take screenshots of multiple small sections of a graph and stitch them together manually in an image editor.

**Additional context**

**Comment by lsemp3d** [comment]
This already exists, there is a menu option to capture a screenshot, you can use Ctrl+Shift+P with nothing selected to capture the whole graph or it will capture whatever is selected.
