### ISSUE TITLE
Script Canvas New Vector Length Nodes

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2575]
**Is your feature request related to a problem? Please describe.**
For convenience, I'd like more nodes for working with vector length instead of having to combine multiple other nodes to perform the same operation.

**Describe the solution you'd like**
1. Set Length - takes in a vector and a scalar length value, returns the original vector resized to the request length
2. Clamp Length - takes in a vector and a scalar length value, returns the original vector but with length clamped to the requested length

**Describe alternatives you've considered**
1. Combine Normalize and Multiply nodes to set the length.
2. Combined Get Length, Greater Than, If, and Normalize nodes to clamp to 1.

**Additional context**

**Comment by lsemp3d** [comment]
This is great feedback, please submit it as a feature request through an RFC, thanks!
