### ISSUE TITLE
Script Canvas: Crashes using the target button in GetOnTriggerEventBegin node

### ISSUE THREAD

**Issue by amzn-rhhong** [o3de/o3de#2577]
**Describe the bug**
Crashes using the target button in GetOnTriggerEventBegin node

**To Reproduce**
1. Create an entity on a new level
2. Go to script canvas editor
3. Create GetOnTriggerEventBegin node
4. in the left side select entity id, select the "target" icon. I assume it is used for picking the entity id.
5. once you lick it, you can go back to ly level
6. click on any entity
7. Enter crashes

**Expected behavior**
The target entity got picked, and added to SC GetOnTriggerEventBegin node.

**Screenshots**
![image](https://user-images.githubusercontent.com/69218254/127402653-e348768f-25b4-44d2-b351-496c4ccd4af9.png)

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by cgalvan** [comment]
This is duplicated by #2199
