### ISSUE TITLE
Prefabs corrupt the entire level when trying to use the enclosed ScriptCanvas asset

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#2580]
**Describe the bug**
When using a ScriptCanvas asset that exposes a variable with an array of EntityIds, the json parser fails and leaves the level in a corrupt state.

**To Reproduce**
1. Create a new level in a project with prefabs enabled.
2. Create a new entity.  Add a ScriptCanvas component.  Point it at the attached asset.
3. Notice all the warnings printed to the console.
4. Save the level.
5. Close the Editor, restart it, load the level.
6. Notice how the level now shows up in a corrupt state (entity at the same hierarchy level as the level), and the entity is empty.

**Expected behavior**
The script can be attached and works.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU: AMD Ryzen 3970X
 - GPU:  NVidia GTX 1660 Super
 - Memory 64 GB
[Mastermind.zip](https://github.com/o3de/o3de/files/6896825/Mastermind.zip)

**Comment by AMZN-mnaumov** [comment]
looks to be the issue with BehaviorContextObject trying to serialize AZStd::any type... I thought we've had AZStd::any serialization at some point?

**Comment by mbalfour-amzn** [comment]
With Prefabs / JsonSerialization, AZStd::any isn't supported by default.  However, I believe ScriptCanvas added special support for singular variables of type AZStd::any just for serialization use within ScriptCanvas.  If so, it seems that support wasn't extended over to _arrays_ of variables.

**Comment by jckand-amzn** [comment]
Also unable to reproduce on development@2625f1a3ac5384c. Several serialization errors are thrown, however they appear to be due to the structure/setup of the ScriptCanvas asset. Entity hierarchy is unaffected, as well as the components on the entities.

**Comment by monroegm** [comment]
@monroegm to close
