### ISSUE TITLE
Collider trigger doesn't work.

### ISSUE THREAD

**Issue by amzn-rhhong** [o3de/o3de#2581]
**Describe the bug**
I tried to setup the collider trigger with collision layer and collide with, but I can't seem to get the on trigger event to fire. I'm using script canvas.

**To Reproduce**
1. Create an entity A, with physx collider
2. Create an entity B, with physx collider, turn on is trigger
3. add script canvas scripts on A, wrote some control on A, so A could move around
4. add script on B, listen to the on trigger enter event and trigger exit event. Add some debug print.
5. play the level, move A to interact with B
6. observe

**Expected behavior**
The trigger enter event fires when A enters B, and trigger exit event fires when A left B. 

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by monroegm** [comment]
@amzn-rhhong Can you provide more info about how you are moving the object?

**Comment by hultonha** [comment]
Adding RTE and WF3 label as this is a usability issue that needs to be discussed and a new design proposed. Tagging @yuyihsu for visibility.

**Comment by moraaar** [comment]
Verified this works correctly when using a Kinematic Rigid Body for entity A and a Static Rigid Body for entity B.

After [this change](https://github.com/o3de/o3de/pull/14418) the colliders require to add a rigid body, so the user won't make the mistake again of using just a collider on its own and try to move an entity.

Closing issue.
