### ISSUE TITLE
Script Canvas Inconsistent Node Names

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2586]
**Describe the bug**
Spaces are inconsistent for various nodes. This was noticed particularly in the "Entity/Transform" group. For example, "Set Local Rotation Quaternion" vs "SetWorldRotationQuaternion". We need to take a pass at all the node names and make sure we are using spaces consistently.

**To Reproduce**
1. Open Script Canvas
2. Browse the list of available nodes.

**Expected behavior**
All nodes should be name with spaces and capitals like "Set Some Value".

**Screenshots**
![image](https://user-images.githubusercontent.com/55155825/127416926-79ec9589-c8d5-4db0-b054-d56d627dfc60.png)

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by lsemp3d** [comment]
I've updated all node names and categories
