### ISSUE TITLE
Script Canvas Auto Factor Out Function

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2590]
**Is your feature request related to a problem? Please describe.**
The user can move a selection of nodes from a graph into a function script that can be reused in multiple scripts. But this requires a manual process of copying and pasting the nodes into a new script and creating input and output parameter nodes.

**Describe the solution you'd like**
It would be great if you could box-select a group of nodes, right click, Move to Function Script. This will automatically make a new script, duplicate the selected nodes into the script, add input and output parameter nodes, and replace the nodes in the original script with the new function node.

**Describe alternatives you've considered**

**Additional context**

**Comment by lsemp3d** [comment]
Since this is a feature request, we track those through RFCs, closing it here but it's valid feedback

**Comment by lsemp3d** [comment]
This is a great idea! please submit this feature request as an RFC
