### ISSUE TITLE
Resizing the viewport does not recalculate aspect ratio

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#2597]
**Describe the bug**

When resizing the viewport in the Editor the aspect ratio is not updated, resulting in the view appearing squished and deformed.

**To Reproduce**

1. Launch the Editor
2. Resize the viewport window

**Expected behavior**

As the viewport is resized the aspect ratio should be recalculated to ensure the scene does not appear squished or stretched.

**Screenshots**

Desktop/Device (please complete the following information):

    Device: PC
    OS: Windows
    Version 10
    CPU Processor Intel(R) Xeon(R) CPU E5-1630 v4 @ 3.7GHz
    GPU NVIDA GeForce GTX 1080 Ti
    Memory 32GB

**Additional context**

https://user-images.githubusercontent.com/82228511/127481630-f4e98812-51c8-45b7-a27d-821d6df1d1fa.mp4

**Comment by greerdv** [comment]
Think this is a duplicate of https://github.com/o3de/o3de/issues/2469, although yours is better worded :)

**Comment by hultonha** [comment]
Ah good spot @greerdv, I can close this as a dup, thanks! 👍
