### ISSUE TITLE
Decal behaves unintuitively with rotating parent

### ISSUE THREAD

**Issue by greerdv** [o3de/o3de#2599]
**Describe the bug**
A decal component on an entity which is a child of another entity does not behave intuitively when the parent entity is rotated.

**To Reproduce**
1. Create a parent entity with a mesh
2. Create an entity as a child of the first entity, with a decal component
3. Observe the decal projected onto the parent
4. Rotate the parent and observe the decal appears and disappears based on rotation

**Expected behavior**
The decal rotates with the parent and does not disappear

**Screenshots**
https://user-images.githubusercontent.com/82226198/127496153-b4c3cbad-d491-44f5-a559-4c8735c94a3c.mp4

**Comment by mrieggeramzn** [comment]
Checked this a few times. Looks like it was fixed. From the video there seemed to be some sort of bug where the child transform wasn't rotating with the parent.
