### ISSUE TITLE
Can only pick Emotion FX Actor from the O3DE install location

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#2607]
**Describe the bug**
Can only pick Emotion FX Actor from the o3de install location. However, my project default path is different than this path.

**To Reproduce**
Open the Animation Editor and File> Open Actor> I file browser will open, however you can only pick Emotion FX Actor from the o3de install location. However, my project default path is different than this path.

**Expected behavior**
To choose any path, or at lest your default projects path.

**Screenshots**
![FXPath](https://user-images.githubusercontent.com/87207603/127511064-400c915a-68f4-45e0-898b-33fe7b611a3b.PNG)

**Desktop/Device (please complete the following information):**
 - PC
 - OS:Windows
 - 10
 - CPU Intel I9-9900k 
 - GPU NVidia RTX
 - Memory 16GB

**Additional context**

**Comment by amzn-jillich** [comment]
Recent files are also not picked up if the location is outside of the engine/project folder, e.g. when using a custom gem from an external folder.
