### ISSUE TITLE
GameLift Scripts: GetSessionConfigs Node Fails to Accept Input

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#2623]
**Describe the bug**
The GetSessionConfigs node fails to accept input from the SearchSessions Node

**To Reproduce**
1. Add a SearchSession node
2. Take the SearchSession output and give it to GetSessionConfigs input
3. Save the graph
4. Graph gives an error
"This input is known to be null, and the node does not accept it"

![image](https://user-images.githubusercontent.com/32776221/127545347-85f6b64d-5781-4f3e-84f0-8197ccccd701.png)

**Expected behavior**
Users should be able to pass SearchSessionResponse into GetSessionsConfigs

The funny thing is, if I save the SearchSession output to a script variable, then I can pass that variable GetSessionConfigs without error

**Comment by onecent1101** [comment]
Actually the error indicates your SearchSessions node has no input assigned, and I believe it is related this issue https://github.com/o3de/o3de/issues/2615 (Please see workaround I posted and reach to scripting for help)

I guess the reason that error points to wrong node on your end maybe related to this issue https://github.com/o3de/o3de/issues/2486, please make sure your local version checkout the corresponding fix.

**Comment by onecent1101** [comment]
Close the ticket, as the issue is related to https://github.com/o3de/o3de/issues/2486 which you don't assign input to the node. Feel free to reopen the ticket if you still have issue, and please check with scripting team for solution.
