### ISSUE TITLE
Get World Translation Script Canvas Node return wrong vector

### ISSUE THREAD

**Issue by ausrobis** [o3de/o3de#2630]
**Describe the bug**
When using the "Get World Translation" Script Canvas node with a non-Self entity a zero vector (0,0,0) is returned instead of the entities world position.

**To Reproduce**
1. Create a new empty level.
2. Add two entities, A and B.
3. Move A and B away from the origin (their transforms shouldn't be the identity matrix)
3. Attach to A a Script Canvas component
4. Create a script for this component with the following nodes: On Tick -> Get World Translation -> Debug/Print -> Get World Translation -> Debug/Print
5. In the first Get World Translation leave the source EntityID blank for Self
6. In the second Get World Translation use the crosshairs button to select entity B in the Entity Outliner
7. Have each debug print the returned vector from each Get node, which produces:

> (Script Canvas) - Parse Duration:   0.2580 ms
> [Warning] (Prefabs) - Prefab - EntityIdMapper: Entity with Id [8207457610221701465] has no registered owning instance
> Entered game mode
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)
> (Script) - Self (A): (x=-8.5762825,y=3.0762053,z=-3.1729455)
> (Script) - Other (B): (x=0.0000000,y=0.0000000,z=0.0000000)

**Expected behavior**
The value returned from the second Get World Translation node should contain the position of entity B, not (0,0,0)

**Screenshots**
Script Canvas script screenshot attached below

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows
 - Version: 10
 - CPU: Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz, 3096 Mhz, 8 Core(s), 16 Logical Processor(s)
 - GPU: NVIDIA GeForce RTX 3070 Laptop GPU
 - Memory: 32GB

<img width="839" alt="Annotation 2021-07-29 135126" src="https://user-images.githubusercontent.com/86640432/127564717-fdcec755-0173-45fe-a7d9-c6205e59b1fe.png">

**Comment by lsemp3d** [comment]
This was a side-effect of the issue related to assigning values to the Script Canvas component. A fix was pushed for it.
