### ISSUE TITLE
Open Source Particle System Feature Request (short term)

### ISSUE THREAD

**Issue by WashedUpStudio** [o3de/o3de#2644]
**Is your feature request related to a problem? Please describe.**
The only available particle fx system is popcornfx, and this is an open source alternative that would not be as difficult to get up and running.
**Describe the solution you'd like**
In the long run I would love to see a particle system designed for o3de just like Unity and Unreal Engine has, both are better than alternatives you can find from other companies, mainly because they have more integration and support for the editor/engine your using. For short term, Effekseer seems like a great particle system that is open source and already has plugins for unity, unreal, and I believe godot, so it should not be impossible to get a working plugin for o3de.
**Describe alternatives you've considered**
Effekseer is the best alternative after doing a lot of searching, but in the long run again an in engine particle system like Lumberyard had, but could compete with Unity or Unreal's would be the best for everyone.
**Additional context**
This is the website to effekseer. https://effekseer.github.io/en/

**Comment by AMZN-koppersr** [comment]
Have you left a feature request with the developers of Effekseer? They might be interested on their end to integrate with O3DE, but may not be aware that O3DE exists.

**Comment by WashedUpStudio** [comment]
Yes I just made a feature request for Effekseer, I am not sure how active their development it on plugins though, but here is the request : https://github.com/effekseer/Effekseer/issues/704

**Comment by WashedUpStudio** [comment]
> Have you left a feature request with the developers of Effekseer? They might be interested on their end to integrate with O3DE, but may not be aware that O3DE exists.

It may be a bit more difficult since it is also an open source project, the developers/contributors of Effekseer do not know O3DE, so a plugin on there side does seem a little less likely, still possible if someone works on Effekseer and also has been looking into O3DE.

**Comment by superkitcath** [comment]
Please reopen as an RFC under the sig-presentation repo [https://github.com/o3de/sig-presentation/tree/main/rfcs](url) 

The procedure can be found here: [https://github.com/o3de/rfcs#the-rfc-process](url)
Thank you!
