### ISSUE TITLE
The Factor of Metallic should be hidden when a texture image is provided.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2647]
**Describe the bug**
Create a new material based upon StandardPBR.materialtype. When choose an image for metallic, we found that Factor is useless, but not hidden from Inspector.

The following code from MetallicInput.azsli reveal that factor has no use when a texture image is provided.
```
float GetMetallicInput(Texture2D map, sampler mapSampler, float2 uv, float factor, bool useTexture)
{
    if (useTexture)
    {
       // [GFX TODO][ATOM-1793]: Figure out how we want our base material to expect channels to be encoded, and apply that to the way we pack metalness.
       return map.Sample(mapSampler, uv).r;
    }
    return factor;
}
```

**To Reproduce**
1. Open Editor.
2. Click on Tools -> Material Editor
3. Wait for Material Editor to open
4. Click File -> New, select StandardPBR, and save to somewhere.
5. Modify attributes of Metallic, choose an image as texture.
6. Modify Factor of Metallic.

**Expected behavior**
The Factor of Metallic should be hidden when a texture image is provided.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by Adi-Amazon** [comment]
As per the pull request: https://github.com/o3de/o3de/pull/5095
