### ISSUE TITLE
Collider Assets which require PhysX cooking fail in Spawnables

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#2651]
**Describe the bug**

Collider Assets which require PhysX cooking fail in Spawnables. 

**To Reproduce**

1. Add a non-uniform scale component to an Entity that has a Rigid Body and Collider Component with a primitive box shape set.
2. Create a Prefab
4. Notice the .spawnable file is missing a collider component (AssetBuilder fails)

It is also possible to repro this **without** non-uniform scale, this is just one possible repro (this is not Dave's fault! 🙂)

**Expected behavior**

**Screenshots**

**Additional context**

This is printed to the log when going to Game Mode

`[Error] (Prefab) - Invalid asset found referenced in scene while entering game mode`

```
~~1627647785900~~3~~000000000000AE6C~~AssetBuilder~~E: PhysX: Trace::Error
~~1627647785902~~3~~000000000000AE6C~~AssetBuilder~~E: >	D:/gamejam/o3de/Gems/PhysX/Code/Source/Utils.cpp(276): 'class AZStd::optional<class Physics::CookedMeshShapeConfiguration> __cdecl PhysX::Utils::CreatePxCookedMeshConfiguration(const class AZStd::vector<class AZ::Vector3,class AZStd::allocator> &,const class AZ::Vector3 &)'
~~1627647785904~~3~~000000000000AE6C~~AssetBuilder~~E: >	PhysX cooking of mesh data failed
```

It appears as though the PhysX System Component is loaded by the Asset Builder but is not activated.

See attached: If this is attempted to be spawned it will reproduce the issue
[AsteroidChild.prefab.txt](https://github.com/o3de/o3de/files/6907542/AsteroidChild.prefab.txt)

**Comment by sadeghzare2580** [comment]
> **Describe the bug**
> 
> Collider Assets which require PhysX cooking fail in Spawnables.
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Add a non-uniform scale component to an Entity that has a Rigid Body and Collider Component with a primitive box shape set.
> 2. Create a Prefab
> 3. Notice the .spawnable file is missing a collider component (AssetBuilder fails)
> 
> It is also possible to repro this **without** non-uniform scale, this is just one possible repro (this is not Dave's fault! )
> 
> **Expected behavior**
> 
> **Screenshots**
> 
> If applicable, add screenshots to help explain your problem.
> 
> **Additional context**
> 
> This is printed to the log when going to Game Mode
> 
> `[Error] (Prefab) - Invalid asset found referenced in scene while entering game mode`
> 
> ```
> ~~1627647785900~~3~~000000000000AE6C~~AssetBuilder~~E: PhysX: Trace::Error
> ~~1627647785902~~3~~000000000000AE6C~~AssetBuilder~~E: >	D:/gamejam/o3de/Gems/PhysX/Code/Source/Utils.cpp(276): 'class AZStd::optional<class Physics::CookedMeshShapeConfiguration> __cdecl PhysX::Utils::CreatePxCookedMeshConfiguration(const class AZStd::vector<class AZ::Vector3,class AZStd::allocator> &,const class AZ::Vector3 &)'
> ~~1627647785904~~3~~000000000000AE6C~~AssetBuilder~~E: >	PhysX cooking of mesh data failed
> ```
> 
> It appears as though the PhysX System Component is loaded by the Asset Builder but is not activated.
> 
> See attached: If this is attempted to be spawned it will reproduce the issue
> [AsteroidChild.prefab.txt](https://github.com/o3de/o3de/files/6907542/AsteroidChild.prefab.txt)
