### ISSUE TITLE
Material editor hotkey broken

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#2664]
**Describe the bug**
The tools menu suggests the Material editor has a shortcut of M, but this hotkey does not function.

**To Reproduce**
1. Open the editor
2. Press key 'm'
3. Nothing happens

**Expected behavior**
Material editor opens

**Screenshots**
![material_m](https://user-images.githubusercontent.com/830514/127708823-aec5715c-66ea-4cd8-a14a-6ec3bef05434.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia RTX 2070
 - Memory 32GB

**Additional context**
The Track View tool shortcut shown in the same menu is functional. Removing the UI element for the Material Editor hotkey would technically resolve this.

**Comment by cgalvan** [comment]
Material Editor opens with 'M' hotkey in latest development b46a80b
