### ISSUE TITLE
Icon assets exist at o3de\Assets\Editor\Scripts\Shelves\icons\ without documentation

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#2667]
**Describe the bug**
Certain icon assets exist at o3de\Assets\Editor\Scripts\Shelves\icons\ instead of in an upper level folder such as o3de\Assets\Editor\Icons or o3de\Assets\Editor\ObjectIcons ...and there is no documentation as to why. The names of these icons suggest they are related to editor options.

**To Reproduce**
1. In the Asset Browser, search for 'fog'
2. Result appears in Assets/Tools > Scripts > Shelves > icons
3. Try to understand what this asset is currently used for by inspecting o3de\Assets\Editor\Scripts\Shelves\icons\ 
4. ???

**Expected behavior**
File path is descriptive of what it contains, or contains a README

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia RTX 2070
 - Memory 32GB

**Additional context**

**Comment by cgalvan** [comment]
These are deprecated/legacy and no longer in use, so I will remove them.  Good catch, thanks!
