### ISSUE TITLE
O3DE website does not handle search queries created by Editor

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#2668]
**Describe the bug**
The search box immediately under the 'Help' menu does not correctly work, as the O3DE documentation website does not handle the search string it creates.

**To Reproduce**
1. Open the O3DE editor
2. Click on 'Help'
3. Enter a string into the search bar and press enter

**Expected behavior**
The search query is searched for in the documentation

**Screenshots**
![websearch](https://user-images.githubusercontent.com/830514/127711602-4c9fd6ba-0073-460a-9e47-783869908f31.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia RTX 2070
 - Memory 32GB

**Additional context**

**Comment by cgalvan** [comment]
@erickson-doug The Editor is trying to query the documentation via a "query" param like this:

```https://o3de.org/docs/?query=test```

But this doesn't do anything on the website. I see under the API reference on the site there is search bar, but it doesn't seem to actually forward to a new URL it just does a search internally on the backend and then updates. Is there a way we can access the search from just a URL query?

**Comment by AMZN-daimini** [comment]
Fixing this as part of a different task (migrating the widget to the new Action Manager)
