### ISSUE TITLE
Editor Graphics Settings cannot be used

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#2673]
**Describe the bug**
Opening the Graphics Settings pane prompts an error dialog, and no settings are available to apply. Selecting a platform prompts the same dialog to open again.

**To Reproduce**
1. Open the O3DE Editor
2. Click on 'Edit > Editor Settings > Graphics Settings'
3. See error

**Expected behavior**
User can edit Graphics Settings

**Screenshots**
![graphics_settings](https://user-images.githubusercontent.com/830514/127722124-0dc2cf68-8aca-41e4-88b7-47d8abd80307.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia RTX 2070
 - Memory 32GB

**Additional context**

**Comment by cgalvan** [comment]
The deprecated Graphics Settings dialog was removed in https://github.com/o3de/o3de/pull/2109

This might've been logged on the stabilization branch.

**Comment by Kadino** [comment]
This dialog was present in a build of o3de:main
