### ISSUE TITLE
Editor Crash when selecting Edit Platform Settings

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#2674]
**Describe the bug**

**To Reproduce**
1. Open the O3DE Editor
2. Click on 'File > Edit Platform Settings...'
3. Editor freezes and then crashes.

**Expected behavior**
User can edit platform settings

**Screenshots**
N/A

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia RTX 2070
 - Memory 32GB

**Additional context**

**Comment by cgalvan** [comment]
This was fixed in development with this commit:

https://github.com/o3de/o3de/commit/7937ece77323c30def9d01bcb3748dc3d14e6795#diff-7562cb3f4a136ea9834ccf1ba15a03b78f026f39fed95d9e5a72f303826edd09
