### ISSUE TITLE
Compiled engine as SDK on Linux takes a lot of space

### ISSUE THREAD

**Issue by Shatur** [o3de/o3de#2677]
**Describe the bug**
On Windows, when building the engine as an SDK, after executing the `install` rule, the engine installation folder takes ~10GB. But on Linux it takes ~100GB!

**To Reproduce**
```bash
cmake -B build/linux -G Ninja -DLY_3RDPARTY_PATH=path/to/o3de-packages -DLY_UNITY_BUILD=ON -DLY_VERSION_ENGINE_NAME=o3de-install -DCMAKE_INSTALL_PREFIX=path/to/o3de-install -DCMAKE_BUILD_TYPE=profile -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
cmake --build build/linux --target install --config profile
```

**Expected behavior**
The folder `path/to/o3de-install` takes ~10-15GB.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: ArchLinux
 - Compiler: Clang 12

**Comment by Naia-love** [comment]
can confirm on VoidLinux with clang 12 too. on last upstream development

**Comment by Naia-love** [comment]
stripping all files in the bin/Linux/profile reduce heavily the install folder (mine is 20GB now) 
just execute `strip -s *` in it

this should be done by default/not compiled with debug info (maybe there's an option to do so, but its strange that its not the default on Linux)

**Comment by amznestebanpapp** [comment]
cmake install on Linux is now stripping:
`cmake\Platform\Linux\Install_linux.cmake`:
```
            if(CMAKE_INSTALL_DO_STRIP)
                execute_process(COMMAND @CMAKE_STRIP@ "${target_file}")
            endif()
```
