### ISSUE TITLE
Modifying Level Created Using "Save As..." Crashes in PrefabDom

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#2679]
**Describe the bug**
During the GameJam I needed to copy and edit an existing game level.  I opened the existing level and did a "File > Save As..."
Once I began removing entities, the Editor crashed. It crashes consistently so should be easy to reproduce.

**To Reproduce**
1. Take an existing level with a good amount of entities and prefabs and File > Save As...
2. In the newly saved level begin deleting some of the entities
4. After deleting 3 prefabs/entity the Editor.exe crashes inside of PrefabDom Json

**Expected behavior**
Editor.exe shouldn't crash
 	EditorLib.dll!rapidjson_ly::GenericValue<rapidjson_ly::UTF8<char>,rapidjson_ly::MemoryPoolAllocator<rapidjson_ly::CrtAllocator>>::FindMember<rapidjson_ly::MemoryPoolAllocator<rapidjson_ly::CrtAllocator>>(const rapidjson_ly::GenericValue<rapidjson_ly::UTF8<char>,rapidjson_ly::MemoryPoolAllocator<rapidjson_ly::CrtAllocator>> & name) Line 1285	C++
 	[Inline Frame] EditorLib.dll!rapidjson_ly::GenericValue<rapidjson_ly::UTF8<char>,rapidjson_ly::MemoryPoolAllocator<rapidjson_ly::CrtAllocator>>::FindMember(const char *) Line 1265	C++
>	EditorLib.dll!AzToolsFramework::Prefab::PrefabDomUtils::FindPrefabDomValue(rapidjson_ly::GenericValue<rapidjson_ly::UTF8<char>,rapidjson_ly::MemoryPoolAllocator<rapidjson_ly::CrtAllocator>> & parentValue, const char * valueName) Line 32	C++
 	EditorLib.dll!AzToolsFramework::Prefab::PrefabPublicHandler::RemoveLink(std::unique_ptr<AzToolsFramework::Prefab::Instance,std::default_delete<AzToolsFramework::Prefab::Instance>> & sourceInstance, unsigned __int64 targetTemplateId, AzToolsFramework::UndoSystem::URSequencePoint * undoBatch) Line 496	C++
 	EditorLib.dll!AzToolsFramework::Prefab::PrefabPublicHandler::DeleteFromInstance(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entityIds, bool deleteDescendants) Line 1148	C++
 	EditorLib.dll!AzToolsFramework::Prefab::PrefabPublicHandler::DeleteEntitiesAndAllDescendantsInInstance(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entityIds) Line 927	C++
 	EditorLib.dll!AzToolsFramework::EditorEntityManager::DeleteEntitiesAndAllDescendants(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entities) Line 57	C++
 	EditorLib.dll!AzToolsFramework::ToolsApplication::DeleteEntitiesAndAllDescendants(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entities) Line 823	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZStd::Internal::INVOKE(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &&) Line 177	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZStd::invoke(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &&) Line 38	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZ::EBusEventProcessingPolicy::Call(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &&) Line 446	C++
 	ComponentEntityEditorPlugin.dll!AZ::Internal::EBusContainer<AzToolsFramework::ToolsApplicationRequests,AzToolsFramework::ToolsApplicationRequests,0,0>::Dispatcher<AZ::EBus<AzToolsFramework::ToolsApplicationRequests,AzToolsFramework::ToolsApplicationRequests>>::Broadcast<void (__cdecl AzToolsFramework::ToolsApplicationRequests::*)(AZStd::vector<AZ::EntityId,AZStd::allocator> const &),AZStd::vector<AZ::EntityId,AZStd::allocator> &>(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) && func, AZStd::vector<AZ::EntityId,AZStd::allocator> & <args_0>) Line 1541	C++
 	ComponentEntityEditorPlugin.dll!SandboxIntegrationManager::DeleteSelectedEntities(bool includeDescendants) Line 1249	C++

**Comment by Amzn-Catdo** [comment]
I noticed this behavior too during the game jam and I was able to reproduce this today. Upon exiting the editor after "save as" then opening up the same level again, I noticed that the prefabs are all outside the level and can no longer be opened (side arrow for drop down is gone) 
![image](https://user-images.githubusercontent.com/82239748/128068644-ebb63ba6-0b9c-4731-8fce-40e3d5ca0c63.png)
