### ISSUE TITLE
Editor crashed when changing 'Shadow Filter Method' to 'PCF'.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2683]
**Describe the bug**
When studying 'Shadow Filter Method', I change the value to 'PCF', then Editor crashed.
With VS2019 to debug Editor, and reproduces the problem, found crash problem occurred in Gems\Atom\RHI\DX12\Code\Source\RHI\ShaderResourceGroupPool.cpp at line 220.

```cpp
        RHI::ResultCode ShaderResourceGroupPool::CompileGroupInternal(
            RHI::ShaderResourceGroup& groupBase,
            const RHI::ShaderResourceGroupData& groupData)
        {
            ShaderResourceGroup& group = static_cast<ShaderResourceGroup&>(groupBase);
            group.m_compiledDataIndex = (group.m_compiledDataIndex + 1) % RHI::Limits::Device::FrameCountMax;
            // m_compiledDataIndex is NULL pointer

            if (m_constantBufferSize)
            {
                memcpy(group.GetCompiledData().m_cpuConstantAddress, groupData.GetConstantData().data(), groupData.GetConstantData().size());   //  oops, crashed here at line 220
            }
```
and found that it failed to allocate memory at line 125.
```
        RHI::ResultCode ShaderResourceGroupPool::InitGroupInternal(RHI::ShaderResourceGroup& groupBase)
        {
            ShaderResourceGroup& group = static_cast<ShaderResourceGroup&>(groupBase);

            const uint32_t copyCount = RHI::Limits::Device::FrameCountMax;

            if (m_constantBufferSize)
            {
                group.m_constantMemoryView = MemoryView(m_constantAllocator.Allocate(m_constantBufferRingSize, RHI::Alignment::Constant), MemoryViewType::Buffer);
                CpuVirtualAddress cpuAddress = group.m_constantMemoryView.Map(RHI::HostMemoryAccess::Write);//  oops, cpuAddress is NULL pointer here at line 125
                GpuVirtualAddress gpuAddress = group.m_constantMemoryView.GetGpuAddress();
```

**To Reproduce**
1. Open Editor, and Create a new level.
2. Create a Entity.
3. Add Light component.
4. Modify Shadow filter method, to PCF.
5. Editor crashed.

**Expected behavior**
Editor dosen't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/80555200/127798726-9ae8cbf1-c07b-4949-b345-e54d53b0a917.png)

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]
 - Render backend [dx12]

**Additional context**

**Comment by Jackie9527** [comment]
With [b46a80be2cd3313dae12c387918ec955406be533](https://github.com/o3de/o3de/commit/b46a80be2cd3313dae12c387918ec955406be533), using vulkan as rendering backend to reproduce the problem, I found the following log.

```
<15:59:37> (RHI) - ****************************************************************
<15:59:37> [Warning] (Vulkan) - Suboptimal presentation of swapchain 

==================================================================
<15:59:38> (System) - 
==================================================================
Trace::Assert
 D:\O3DE\Gems\Atom\RHI\Vulkan\Code\Source\RHI/Vulkan.h(93): (33836) 'void __cdecl AZ::Vulkan::AssertSuccess(enum VkResult)'
<15:59:38> (System) - Trace::Assert
 D:\O3DE\Gems\Atom\RHI\Vulkan\Code\Source\RHI/Vulkan.h(93): (33836) 'void __cdecl AZ::Vulkan::AssertSuccess(enum VkResult)'
ASSERT: Vulkan API method failed: Suboptimal
<15:59:38> (System) - ASSERT: Vulkan API method failed: Suboptimal
```

**Comment by Jackie9527** [comment]
With the latest code [b46a80be2cd3313dae12c387918ec955406be533](https://github.com/o3de/o3de/commit/b46a80be2cd3313dae12c387918ec955406be533), editor doesn't crash any more when reproducing the problem.
But still I wonder how it is fixed.
Waiting for answers.

**Comment by mrieggeramzn** [comment]
@Jackie9527 I asked RHI but they were unsure what PR might have fixed this. It definitely does seem to be fixed on latest though.
