### ISSUE TITLE
'Normal Strength' should be hidden when it is not enabled.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2684]
**Describe the bug**
'Normal Strength' is useless, should be hidden under the following conditions:
1. Clear Coat is disabled.
2. Clear Coat is enabled, but no texture image for Normal Map is not available.
3. Clear Coat is enabled, a texture image for Normal Map is available, but Use Texture is disabled.

**To Reproduce**
1. Open Editor.
2. Click on Tools -> Material Editor
3. Wait for Material Editor to open
4. Click File -> New, select StandardPBR, and save to somewhere.
5. Make the following choices:
5.1 Disable Clear Coat.
5.2 Enable Clear Coat, no texture image for Normal Map.
5.3 Enable Clear Coat, choose a texture image for Normal Map, but Use Texture is disabled.
6. Change the value of Normal Strength.
7. Found that 'Normal Strength' is useless, no changes could be found.

**Expected behavior**
'Normal Strength' should be hidden when it is not enabled.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by santorac** [comment]
It looks like this has already been fixed. I checked commit d91d3f86cbca74783366b1805f69c01bed9a309a Tue Mar 8 15:31:39 2022
