### ISSUE TITLE
[MAJOR] (Editor) Entity outliner expand toggles sometimes expand and immediately contract

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2693]
**Describe the bug**
Sometimes clicking the 'expand' arrow in the Entity Outliner prefab (or other entity) causes it to expand and contract really quickly.  This appears to happen roughly 30% of the time in the entity outliner, and especially immediately after opening a level.

**To Reproduce**
1.  Open a level with a prefab instance in it
2.  click on the 'expand' icon in the Entity Outliner

**Expected behavior**
The outliner item expands and doesn't expand and immediately contract again

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by AMZN-daimini** [comment]
I remember this but can't seem to reproduce it anymore.
