### ISSUE TITLE
[BLOCKER] (Prefabs) Cannot destroy game entity (and descendants) in Prefab system

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2696]
**Describe the bug**
The ScriptCanvas 'Destroy Game Entity' nodes do not allow deleting the entities in-game in the editor.  When you attempt to do so you see this error:

> [Error] (GameEntityContextComponent) - Destroying a game entity and its descendants is temporarily disabled until the Spawnable system can support this.

**To Reproduce**
1. Create a spawnable prefab
2. Create a script canvas graph that spawns the prefab, then waits a tick and destroys it
3. Assign the script canvas graph to a scriptcanvas component in the scene
4. Enter game mode

**Expected behavior**
The spawnable prefab is spawned and then destroyed a tick later

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by monroegm** [comment]
Fixed by #4154
