### ISSUE TITLE
[MAJOR] (Prefabs) Error message about invalid asset does not provide any info about the asset

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2697]
**Describe the bug**
When entering game mode during the jam I frequently saw this error

> [Error] (Prefab) - Invalid asset found referenced in scene while entering game mode

This likely is coming from this code here - where it would be trivial to include the asset id: https://github.com/o3de/o3de/blob/d8c9c5178e65e9e39af984033c7165a0c473e6bf/Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp#L427

**To Reproduce**
1. Create a ui canvas that uses a script canvas component and is assigned a script canvas graph
2. Close the script canvas editor
3. Re-open the editor and the level
4. Enter game mode

**Expected behavior**
The Invalid asset found error message includes the asset ID

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by monroegm** [comment]
I couldn't repro this on development at 4cde568ea4. It's possible this has already been fixed.
