### ISSUE TITLE
[MAJOR] (Prefabs) Slice Spawner Component still exists when prefabs are enabled

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2698]
**Describe the bug**
Slice Spawner Component still exists when prefabs are enabled, this is confusing because users often look for the term 'spawn' in ScriptCanvas 

**To Reproduce**
1. Open ScriptCanvas
2. Enter spawn in the node search field

**Expected behavior**
No references to slice-only nodes appear

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by AMZN-daimini** [comment]
The Spawner Component is also available in the Add Component list in the Inspector while in Prefab mode. We should likely remove it there too.

![image](https://user-images.githubusercontent.com/82231674/131562140-be7b1d72-23e3-42ac-868e-4c139289af94.png)

**Comment by monroegm** [comment]
Fixed by #9819

**Comment by AMZN-daimini** [comment]
Done: https://github.com/o3de/o3de/issues/10585
