### ISSUE TITLE
[CRITICAL] (Atom) Editor viewport FOV aspect ratio is wrong when resizing editor viewport

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2700]
**Describe the bug**
The editor camera does not have the right viewport frustum settings when the editor viewport is resized and you have to  close/re-open editor to fix.

**To Reproduce**
1. Open a level in the editor
2. Resize the editor viewport by making it much shorter vertically

**Expected behavior**
The aspect ratio is preserved

**Screenshots**
![AtomViewportScalingIssue](https://user-images.githubusercontent.com/26804013/127895617-b6148cb8-3f03-46de-8dac-209a4d2f1cad.JPG)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by cgalvan** [comment]
Duplicated by #2456
