### ISSUE TITLE
[MAJOR] (ScriptCanvas) Node palette has 'User Functions' section that doesn't do anything

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2704]
**Describe the bug**
In the ScriptCanvas Node palette window there is a 'User Functions' section that lists other graphs, but you cannot use these graphs in any way that I can determine.

**To Reproduce**
1. Create 2 script canvas graphs
2. Expand the 'User Functions' section of the Node palette window in the script canvas editor
3. Try to drag one of the functions into the graph window
4. Right click on the function

**Expected behavior**
There is some indication how to use these functions, or some indication they are not functional (hahah) yet.

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by AMZN-daimini** [comment]
Those items will be automatically populated with any user function defined in those graphs.

To define a user function, you need to create an Execution Nodeling to define the inputs of the functions, and a second one for the outputs if needed. They can be accessed via the top toolbar:
![image](https://user-images.githubusercontent.com/82231674/127923540-bce7ffcb-9251-4e03-ad83-75db70864502.png)
![image](https://user-images.githubusercontent.com/82231674/127923572-c32dd592-1e07-4f04-9c20-c0445c9a9ff7.png)

This function node allows data inputs to be added
![image](https://user-images.githubusercontent.com/82231674/127923671-379eca53-f166-4647-b185-799441a17d82.png)
![image](https://user-images.githubusercontent.com/82231674/127923727-0616e990-9814-4157-b2d1-77eb577fd7d5.png)

Once the function is defined, it will be available under the User Functions list.
![image](https://user-images.githubusercontent.com/82231674/127923896-6f499a08-bab1-438d-9ac3-51f1f714f9e5.png)

I definitely agree this needs some work:

- I don't think it makes much sense to list all graphs if they don't have functions defined underneath;
- The functionality is currently not easy to discover, and I believe the previous Function Graph implementation was more intuitive. Although I have to say this is much more versatile and was very helpful in creating helper nodes to re-use throughout the game.

**Comment by carlitosan** [comment]
https://github.com/o3de/o3de/pull/3028

**Comment by cgalvan** [comment]
Fixed by https://github.com/o3de/o3de/pull/3028
