### ISSUE TITLE
(Networking) Projects using multiplayer gem fail to configure using engine as SDK because jinja is looking for files that don't exist.

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2705]
**Describe the bug**
Projects using multiplayer gem fail to configure using engine as SDK because jinja is looking for files that don't exist.  None of the jinja files are included in the INSTALL layout.  For example:

C:/o3de/Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Common.jinja

In fact, it appears the entire AutoGen folder is missing.

**To Reproduce**
1. Create an INSTALL layout of the engine
2. Add the Multiplayer gem to your project
3. Add any networking component that requires autogen
4. Attempt to configure and build your project

**Expected behavior**
Build succeeds

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by AMZN-alexpete** [comment]
It is very likely this recent change addresses this issue: https://github.com/o3de/o3de/pull/2643#event-5101215537

**Comment by amznestebanpapp** [comment]
It also needs Issue #2518 fixed
Those jinja are in a "private" path, they should be moved to a "public" path (to the Include folder) for #2643 to work

**Comment by lmbr-pip** [comment]
Related to https://github.com/o3de/o3de/issues/2518, should be fixed together

**Comment by lmbr-pip** [comment]
SIG triage believes this to be fixed. Please reopen and add any new relevant information if issue still persists.
