### ISSUE TITLE
[CRITICAL] (Aud0) Editor crashes when using File->Reload in Audio Controls Editor

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2707]
**Describe the bug**
The editor may crash when using File->Reload in Audio Controls Editor.  This happened to me during the jam after I added new sounds in Wwise, exported the sound bank (while the editor was open) then used the File->Reload menu in the Audio Controls Editor. I later determined this wasn't necessary, because it appears to auto-reload (which is cool)

**To Reproduce**
1. Open the editor and the Audio Controls Editor
2. In Wwise add a new sound with a play event and export the bank
3. In the Audio Controls Editor select File->Reload

**Expected behavior**
The editor does not crash

**Screenshots**
n/a
**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by amzn-phist** [comment]
Dupe of #2602
