### ISSUE TITLE
Inconsistent node naming in Script Canvas

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#2708]
[Migrated from JIRA LYN-6782]
**Describe the bug**
There does not seem to be a unified style in Script Canvas node names. A few different styles are in use, sometimes even within the same category. Examples of a few different node names, all with different styling:

- Get Height
- GetHeight
- ShapeType_Box::Getter
- Get shapeEntityId

**To Reproduce**
1. Open Script Canvas.
2. Click through the Node Palette, noting node names.

**Expected behavior**
Node name styling is consistent.

**Comment by yuyihsu** [comment]
Move priority to critical since this ticket is related to LYN-4250.
