### ISSUE TITLE
LocalPredictionPlayerInputComponent doesn't work for listen servers

### ISSUE THREAD

**Issue by NicholasVanSickle** [o3de/o3de#2711]
**Describe the bug**
When running a listen server (`sv_isDedicated false`), the player slice spawned on the server will not have a LocalPredictionPlayerInputComponentController, so local input will not function.

**To Reproduce**
From any network capable project, launch with a server.cfg like:
```
LoadLevel levels/path/to/level.spawnable
sv_isDedicated false
host
```

**Expected behavior**
Local input should work, LocalPredictionPlayerInputComponent should fire.

**Comment by NicholasVanSickle** [comment]
After investigation this was caused by `SetAllowAutonomy` being called after entity activation, preventing the component from seeing the autonomous flag. PR here: https://github.com/o3de/o3de/pull/2639

**Comment by lmbr-pip** [comment]
@NicholasVanSickle - Marking as closed per your comment. Believe fixed in https://github.com/o3de/o3de/pull/2639
