### ISSUE TITLE
Atom - Add options to have light only affect a specific entity

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#2723]
When authoring a character, I find it useful to be able to author lighting on the actor model so that the face is lit and visible even in dark conditions. In these situations, I think it would be cool if we had a way to limit the effects of a light source to specific entities.

**Expected behavior**
In the Light Component, I expected to have a way to limit a light to only a specific entity, or layer?

**Comment by superkitcath** [comment]
Please reopen as an RFC under the sig-presentation repo [https://github.com/o3de/sig-presentation/tree/main/rfcs

The procedure can be found here: https://github.com/o3de/rfcs#the-rfc-process

Thank you!
