### ISSUE TITLE
ATOM, Look Modification Component, LUT banding.

### ISSUE THREAD

**Issue by HogJonny-AMZN** [o3de/o3de#2725]
**Describe the bug**
.3dl LUT loaded in the Look Modification Component doesn't appear the same as the same LUT applied in photoshop
The LUT shaper does not appear to be applied or do anything.
There are banding artifacts present when the LUT is applied in O3DE.
^ note: you can generate LUTs from Photoshop or Nuke (but that workflow is not described here)

**To Reproduce**
1. Use Nuke (or another app) to generate a LUT
2. Currently this requires using python scripts
3. In O3DE create a Look Modification Component and load the LUT

LUT workflow: https://github.com/o3de/o3de/discussions/1963

**Expected behavior**
The LUT when applies transforms the image to look like the same image in Nuke

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windwows
 - Version Win10
 - CPU Ryzen 3970X
 - GPU NVidia RTX 3070
 - Memory, system 64BG, GPU 8GB

**Additional context**
We are investigating this further.

**Comment by HogJonny-AMZN** [comment]
[ATOM-NukeWorkflowValidation-020821-1932-316.pdf](https://github.com/o3de/o3de/files/6919212/ATOM-NukeWorkflowValidation-020821-1932-316.pdf)

**Comment by invertednormal** [comment]
Fixed in 90845313fbce4bde019ed3fe1f69696f5e30962d
