### ISSUE TITLE
Viewport - Translation manipulator position is misplaced when returning from Game Mode

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#2731]
**Describe the bug**
If an entity is selected and then Game Mode is started, the manipulator will be misplaced when Game Mode is terminated.

**To Reproduce**
1. Open a Level
2. Select the ShaderBall
3. Move the ShaderBall away from 0,0,0
4. Start Game Mode (Ctrl + G)
5. Exit Game Mode (Esc)

**Expected behavior**
The manipulator is in the same position as before (centered on the selected Entity)

**Actual behavior**
The manipulator is misplaced to 0,0,0. It behaves correctly, and is placed correctly if the selection changes.

**Screenshots**
![translationMisplaced](https://user-images.githubusercontent.com/82231674/127916048-cc65374d-7529-45ca-8904-622c65f998ae.gif)

**Comment by hultonha** [comment]
I attempted to reproduce this issue but when returning from Game Mode we now deselect all entities so this is no longer appears to be a problem. If you are able to reproduce it @AMZN-daimini, please let me know and I can reopen 👍
