### ISSUE TITLE
Be This Camera - Camera control occasionally gets stuck

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#2734]
**Describe the bug**
When multiple cameras are available in a scene, "Be This Camera" can get stuck.
I have been able to consistently reproduce the issue with the steps below, but it's very much not the only way. While working on a scene, at one point moving to a camera via the Viewport Camera Selector widget would both reset the camera to 0,0,0 facing negative Z and lock its position, making authoring camera positions much harder.

**To Reproduce**
1. Create a new level
2. Create a new entity
3. Add a camera component
4. Press on the "Be This Camera" button on the Camera component
5. This camera should work fine!
6. Now press on "Camera" on the Viewport Camera Selector widget
7. Try to move around in the viewport
 
**Expected behavior**
Moving around in the viewport works correctly, and the camera location is saved to the object we're looking through

**Actual behavior**
Trying to move the camera will not work, the current position is restored.

**Screenshots**
![beThisCamera](https://user-images.githubusercontent.com/82231674/127919728-7ca91e7e-b861-46dc-b39b-9bc45acf3872.gif)

**Comment by srikappa-amzn** [comment]
This is fixed with https://github.com/o3de/o3de/pull/5326 .

**Comment by hultonha** [comment]
I have not been able to reproduce this either, confirmed this is fixed by #5326

**Comment by hultonha** [comment]
(note: There is an issue with camera control (relating to roll) that I have on my list next to fix, but the camera transform is remembered correctly! 😅)

**Comment by AMZN-daimini** [comment]
Verified and I can no longer repro too :)
