### ISSUE TITLE
UI Editor will block the keyboard event.

### ISSUE THREAD

**Issue by amzn-rhhong** [o3de/o3de#2740]
**Describe the bug**
I build my game demo with keyboard controls. I noticed that sometimes when I have UI editor open, the keyboard control is not working. Close the UI editor doesn't solve the problem. I have to close the UI editor, then close the main editor (so the o3de editor doesn't open UI editor by default next time). Then reopen the o3de editor. 

**To Reproduce**
1. Setup a level, input binding and script canvas event to listen to keyboard input.
2. play the level, make sure keyboard event is working.
3. Open UI editor
4. With UI Editor open, go back to main level, play
5. Observe that keyboard control is not working.

**Expected behavior**
UI editor shouldn't blocks the keyboard event.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by AMZN-AlexOteiza** [comment]
We had the exact same issue in our gamejam project

**Comment by Amzn-Catdo** [comment]
Same issue? https://github.com/o3de/o3de/issues/2488

**Comment by cgalvan** [comment]
Duplicated by #2515
