### ISSUE TITLE
Prefabs - Saving level prefab via the Outliner works, but does not set the flag on Editor close

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#2743]
**Describe the bug**
It is currently possible to save the level prefab by right-clicking the Level Container in the Outliner and then pressing "Save prefab to file". Trying to close the Editor after that operation, though, will result in a prompt asking whether the level should be saved.

In my opinion, the "Save prefab to file" menu item should not appear in the Level Container context menu at all. If we want a menu item to save there, it should explicitly say "Save Level" and go through the same code path as Ctrl+S.

**To Reproduce**
1. Create a new level;
2. Create an entity;
3. Right click on the Level Container and select "Save Prefab to File";
4. Close the Editor.

**Expected behavior**
The Editor closes cleanly

**Actual behavior**
A dialog appears asking whether the changes should be saved.

**Screenshots**
![SavePrefab](https://user-images.githubusercontent.com/82231674/127928199-d5d9ece4-c5ea-4527-b8f9-754dfe6b5793.gif)

**Comment by AMZN-daimini** [comment]
Not sure about that, I think we either need to remove the Save prefab to file menu item from the level, or make it trigger the regular save flow instead of the prefab save flow (so that flags are set correctly)

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed.
