### ISSUE TITLE
Materials: Material per-instance overrides do not apply at simulation time

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#2744]
**Describe the bug**
We have a building material that applies UV tiling settings on the Material component (Edit Material Instance...) in the editor the texture has the correct UV coordinates, but at runtime (Ctrl+G or simulation mode) the UV tiling overrides do not get applied (see screenshot).

**Screenshots**
![image](https://user-images.githubusercontent.com/58790905/127931325-bbbbfee0-fb40-450e-8c90-4ec8214eef71.png)

Edit: Using prefabs (slices disabled) in case it's relevant

**Comment by santorac** [comment]
@lsemp3d does this still occur on the latest stabilization branch? I was not readily able to repro. If it's still happening, can  you provide details repro steps please?

**Comment by lsemp3d** [comment]
I was no longer able to reproduce it
