### ISSUE TITLE
Editor Camera is skewed after playing Game Mode maximized

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#2748]
**Describe the bug**
After activating Game Mode with the maximize icon and then closing it, the Editor Viewport camera will be skewed (and frankly quite dizzying).
Opening the Viewport Camera Selector and then closing the widget will restore the correct camera view.

**To Reproduce**
1. Open a level
2. Start Game Mode with "Play Game (Maximized)"
![image](https://user-images.githubusercontent.com/82231674/127932693-98833fcf-c7de-43d7-8214-d0713193df04.png)
3. Close Game Mode (Esc)

**Expected behavior**
The Editor Viewport camera displays correctly.

**Actual behavior**
The camera view is skewed.

**Screenshots**
![skewed](https://user-images.githubusercontent.com/82231674/127934594-0cfa7b41-fb82-4170-a7ab-c65e06595131.gif)

**Comment by cgalvan** [comment]
This appears to be fixed in latest development 4f9382e
Potentially fixed by the recent FOV changes
