### ISSUE TITLE
Pressing ` during game mode shows a cursor

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#2753]
**Describe the bug**
Pressing ` during game mode shows both the Windows cursor and an additional cursor. They two aren't synced (the custom one seems to be mapping the screen coordinates to the viewport). Pressing Esc removes the cursor, and pressing it again ends Game Mode.

![cursor](https://user-images.githubusercontent.com/82231674/127940470-d3cae779-9530-4a12-8490-9ba0fa01c006.gif)

**Comment by ParasiteSt** [comment]
@AMZN-daimini Is this still an issue in the latest Development branch? It seems to no longer open a cursor on ` press.

**Comment by AMZN-daimini** [comment]
I still see 2 cursors in this situation, but they're the same cursor type and overlap correctly. I think we can close this.
