### ISSUE TITLE
Prefabs - Duplicating a prefab instance does not select the new instance

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#2760]
**Describe the bug**
When duplicating a Prefab instance via Ctrl+D or the Outliner context menu, the expectaction is that the newly create duplicate is selected after the operation. Right now, though, only duplicated entities are selected.

**To Reproduce**
1. Open a level;
2. Create or instantiate a prefab;
3. Press Ctrl+D to duplicate it.

**Expected behavior**
The clone is selected after the operation.

**Screenshots**
![dup](https://user-images.githubusercontent.com/82231674/127944071-bee7c1e1-8360-4afa-ba8f-8bb93588195e.gif)

**Comment by AMZN-mnaumov** [comment]
https://github.com/o3de/o3de/pull/2995
