### ISSUE TITLE
Camera Speed value rises when mouse scroll wheel is scrolled down

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#2768]
**Describe the bug**
It has been noticed, that using mouse scroll wheel to change the camera speed value in camera settings will rise the camera speed when scroll is scrolled down and lower the camera speed when scroll is scrolled up.
This is contradictory to behavior observed with different scrollable values in Editor which rise when scroll wheel is scrolled up.

For further information please refer to the attached video file.

https://user-images.githubusercontent.com/86953456/128015904-bf1d0181-9145-4c09-9102-caa93f24f8e9.mp4

**To Reproduce**
1. Launch the Editor and open any level.
2. Navigate to _Camera Settings_ tab located in Perspective toolbar.
3. Use the mouse wheel to change the _Camera Speed_ value.

**Expected behavior**
Camera Speed rises when mouse scroll wheel is scrolled up.

**Desktop/Device (please complete the following information):**
* Device: PC
* OS: Windows
* Version: 10 Pro
* CPU: AMD Ryzen 7 2700X
* GPU: AMD Radeon Pro Duo
* Memory: 16GB

**Comment by hultonha** [comment]
I'll see if I can quickly update this @cgalvan, thanks for the info! 👍

**Comment by LB-MateuszSzweda** [comment]
Issue verified as fixed in Development (ea9f21c) Camera speed scale changes according to the direction of mouse scroll movement.
