### ISSUE TITLE
Mouse Axis input is not being registered if there is a lot of PhysX Rigid Body entities spawned

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#2770]
**Describe the bug**
It has been noticed, that if there are many PhysX Rigid Body entities present, the mouse axis input is not being registered, while keyboard/mouse keys/buttons input is still properly received.

**To Reproduce**
1. Create a new level and remove Atom Default Environment.
2. Create an Input entity with Input and Script Canvas components.
3. Create a .inputbindings file setup as seen on InputBindings.PNG and attach it to the Input entity.
4. Create a Script Canvas graph as seen on InputScriptCanvas.PNG and attach it to the Input entity.
5. Enter the Game Mode and confirm that all the keyboard, mouse click and mouse movement are properly printed to the Console. Exit the Game Mode.
6. Create a Spawn entity with components set up as seen on SpawnedEntity1.PNG and SpawnedEntity2.PNG. Right-click it and select Create Prefab..., save it.
7. Create a Spawner entity with Script Canvas component.
8. Create a Script Canvas graph as seen on SpawnRigidBodyScriptCanvas.PNG and attach it to the Spawner entity. In the Spawn node choose the prefab created in step 6.
9. Enter the Game Mode and check the console on all the keyboard, mouse click and mouse movement inputs. (Please refer to the attached video for a preview. Note that it may take different amount of time depending on the PC used for the issue to occur.)

**Expected behavior**
Mouse axis input is being properly registered.

**Screenshots and video**
InputBindings.PNG
![InputBindings](https://user-images.githubusercontent.com/86952082/128022064-4c15f5e2-0e92-44f7-bcd8-c4b270b70bdd.PNG)

InputScriptCanvas.PNG
![InputScriptCanvas](https://user-images.githubusercontent.com/86952082/128022186-104b27d5-82fc-405e-a98d-2c64c8e03813.png)

SpawnedEntity1.PNG
![SpawnedEntity1](https://user-images.githubusercontent.com/86952082/128022824-4469ff33-496e-4792-b989-030c0cf4e12d.PNG)

SpawnedEntity2.PNG
![SpawnedEntity2](https://user-images.githubusercontent.com/86952082/128022827-cb028967-415c-4492-ab8f-11ee52a19a46.PNG)

SpawnRigidBodyScriptCanvas.PNG
![SpawnRigidBodyScriptCanvas](https://user-images.githubusercontent.com/86952082/128022877-5da6cbdd-66fb-4eec-b36c-7acd995f4d98.png)

https://user-images.githubusercontent.com/86952082/128023250-37d65cd1-9d89-4cc8-b075-da3abc36d612.mp4

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by LB-MateuszSzweda** [comment]
Tagging @hultonha  as per request on PhysX issues that stand out in during exploratory testing and user workflow scenarios.

**Comment by GraphiteSIX** [comment]
I tried to reproduce with dev (#9603).
Inputs seemed to work fine and printed.
But got stuck at step 8.
Spawn component seems to have changed and I don't know how to connect or I can't find it.
Maybe I have missed something ?
![spawnNode](https://user-images.githubusercontent.com/105223355/169593598-32fb3d58-343a-4e82-a754-bf622fdac7aa.png)

**Comment by GraphiteSIX** [comment]
@SergeyAMZN Looks like the systems have updated a lot since the initial issue.
I have built with the updated components and believe that the mouse is debugging ok. 
![Spawmouse](https://user-images.githubusercontent.com/105223355/169622417-20ece931-9f55-4fc7-9cee-b743e41e097d.png)
I have zipped the assets I have used.
[Mouse_Spawn.zip](https://github.com/o3de/o3de/files/8744891/Mouse_Spawn.zip)

**Comment by GraphiteSIX** [comment]
Tested for how long the video is but only captured one screen by mistake and missed the console.
The FPS goes down real quick even without recording so I might investigate the same test with some manual garbage collection.
I could be doing something wrong but I'm guess there is a lot of physx shape mats to calculate

https://user-images.githubusercontent.com/105223355/169667284-3734283e-cadb-4231-8c3a-fdf702d0cddb.mp4

.

**Comment by GraphiteSIX** [comment]
I rigged a crude garbage collecter but If script canvas array is like or is a C++ vector it will be terribly costly as it has to move everything along after delete.
Going above 256 elements makes a real impact on FPS on my machine when recording.
Will go have a think on how to improve for performance
![Garbage_Collect](https://user-images.githubusercontent.com/105223355/169670200-9287efc4-ace3-4b4a-81ff-d2391d7a551f.png)

https://user-images.githubusercontent.com/105223355/169670304-0f369789-2193-4100-9e99-1d9657a205d6.mp4

.

**Comment by GraphiteSIX** [comment]
It seems if the spawn timer is doubled then tickets are not stored in the array as there are more cubes than 257 but the array says it only holds 257 then you will see the cubes despawn on mass like there is no ticket and lua is garbage collecting them all.
Maybe you simply cant do what I have done and there is a correct way of doing things or it needs a custom SC nodeable.
Or maybe the timer set to 0.05 is to quick for what it is doing.

If I set the spawn timer to 0.01 to make it impossible for the GC to work and when the FPS has dropped down to 15 the mouse will stop outputting to print debug.
So to clarify the issue will occur if fps is low enough and tickets are not being handled.

**Comment by hultonha** [comment]
Thank you for all the information @GraphiteSIX, this is very helpful. It might be helpful for @LB-ArturZieba to verify this issue is still occurring and update the description based on the feedback if anything isn't clear. Tagging @LB-MateuszSzweda for visibility as well. Thanks!

**Comment by hultonha** [comment]
Also @GraphiteSIX would it be possible to attach your latest scripts to the ticket if possible which might help with some of the reproduction steps. Thanks!

**Comment by SergeyAMZN** [comment]
@monroegm Is the 257 objects limit for the Spawner SC node intentional or it could be a bug? 
Could you triage please?

**Comment by GraphiteSIX** [comment]
@SergeyAMZN I set the 256 limit for when the first element of the array gets erased which came out to debug print the array length to 257.
You can increase the limit and it will increase the size of the array before the first element is deleted but performance is degraded.
Its only when you increase the spawn timer below 0.1 that tickets don't seem to go into the array and automatic garbage collection takes over.
I don't know if the issue is my script being incorrect and/or unfeasible or its a bug.

**Comment by LB-ArturZieba** [comment]
@hultonha I've reverified this issue on the Development (0fe387c) build, and it does not seem to occur anymore. The MouseAxis input gets progressively bigger on the same mouse movement, but that seems to be expeceted, as the frame rate drops more, and more the more prefabs are spawned. Here is the script I've used for the spawner:
![SpawnerSC](https://user-images.githubusercontent.com/86952082/169836027-3dcc90db-9436-40a6-abe6-d541da68da1b.PNG)

**Comment by GraphiteSIX** [comment]
@LB-ArturZieba I think I have introduced scope creep to the GHI by adding GC and agree that as frames drop the expected happens.
Interesting what happens to the spawn ticket in your script as when it is overwritten in variable_3 does it not just despawn or does it have a lifetime outside of the variable as the object is drawn ?

**Comment by hultonha** [comment]
Thanks for the update @LB-ArturZieba, if the issues as initially described does appear to be no longer occurring I suggest we close this ticket and @GraphiteSIX it might be worth creating a separate ticket that specifically describes the issues you're seeing for us to take a look at separately. Thanks!

**Comment by GraphiteSIX** [comment]
@hultonha Ok sorry about the clutter from scope creep on the GHI.
Will create a new GHI just didn't know if a bug or user error.
Only started using GH last 2 weeks so its all new to me.

**Comment by LB-ArturZieba** [comment]
Closing the issue as per https://github.com/o3de/o3de/issues/2770#issuecomment-1134787222. @GraphiteSIX The objects keep spawning, please check this issue: https://github.com/o3de/o3de/issues/8357 and the comments under it, because I think that it will clear up how the concerns that you have.

**Comment by hultonha** [comment]
> @hultonha Ok sorry about the clutter from scope creep on the GHI.
> Will create a new GHI just didn't know if a bug or user error.
> Only started using GH last 2 weeks so its all new to me.

No worries at all @GraphiteSIX, thanks for all the great info 🙂
