### ISSUE TITLE
Bug: Engine registration siliently failing in Project Manager will prevent engine setting overrides

### ISSUE THREAD

**Issue by AMZN-ScottR** [o3de/o3de#2774]
**Describe the bug**
Project Manager does not inform the user when engine registration fails.  In this event, modifying the engine settings will also fail to save with no indication. 

**To Reproduce**
1. Configure the build, e.g.
`cmake -S . -B build\windows_vs2019 -G "Visual Studio 16 2019" -DLY_3RDPARTY_PATH=<3rdPartyPath> -DLY_PROJECTS= -DLY_UNITY_BUILD=ON -DLY_DISABLE_TEST_MODULES=ON`
2. Register the engine through:
`scripts\o3de.bat register --this-engine`
3. Build the install target, e.g.
`cmake --build build\windows_vs2019 --config profile --target INSTALL`
4. Run Project Manager (o3de.exe) from the install location e.g. <RepoRoot>/install/bin/profile/Windows/o3de.exe
5. Select the Engine tab and modify one or more paths
6. Switch to the Projects tab then back to the Engine tab 
7. Notice the paths reverts to their previous state

**Expected behavior**
A popup dialog should show the user why the engine registration failed and what possible resolution steps can be taken to resolve it.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows (likely Linux and macOS as well)
 - Version: 10
 - CPU: Intel Core i7-4790k
 - GPU: NVidia GTX 980
 - Memory: 32GB

**Comment by AMZN-alexpete** [comment]
This is fixed in latest 2305 stab - verified by forcing a registration error and making sure it appears:
![image](https://user-images.githubusercontent.com/26804013/232640821-f6c7fc3f-6343-4f78-a4d3-4a49aabd417c.png)
