### ISSUE TITLE
[CRITICAL] (LyShine) Editor crashes when assigning a script canvas with an exposed variable to a UI element

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2776]
**Describe the bug**
Sometimes (50%?) when you create a script canvas graph that has an exposed variable in it and you assign that script canvas graph to a UI element with a script canvas component on it, the editor will crash.

**To Reproduce**
1. Create a UI canvas with a UI element that has a script canvas component on it
2. Create a script canvas graph with a variable and expose that variable so it shows up in the component properties section on the UI element
3. Save the graph and assign it to the script canvas component in LyShine

**Expected behavior**
The exposed property appears and the editor does not crash

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by FuzzyCarterAWS** [comment]
@AMZN-alexpete can you please provide better Repro steps and/or examples of SC Graphs and UI Canvas's?

**Comment by AMZN-alexpete** [comment]
@FuzzyCarterAWS what part of the repro steps are unclear?  This issue is old enough, I no longer have those assets.

**Comment by FiniteStateGit** [comment]
Unable to repro with nightly dev build downloaded 1/18.

**Comment by AMZN-alexpete** [comment]
Closing as cannot repro.
