### ISSUE TITLE
[CRITICAL] (Prefab) Editor crash entering game mode when prefab instance set to editor-only

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2777]
**Describe the bug**
I wanted to have a prefab instance in my level for editing, but did not want that instance included in the game so I set the prefab instance to be "editor only".  When I did this the editor failed to save the game level prefab, and when I entered game mode the editor crashed.

**To Reproduce**
1. Add a prefab instance to your level and save the level (not the prefab)
2. Enter game mode

**Expected behavior**
Editor does not crash and the prefab instance does not appear in the game.

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by sconel** [comment]
Was unable to repro crash and save issue. Verified with @rainbj that UX is currently working as expected and that the entire instance is not expected to be filtered out if marked editor only and instead only the container entity itself. @AMZN-alexpete if the issue occurs again feel free to reopen. Can also discuss future UX changes if we'd like to move toward filtering entire instances out.
