### ISSUE TITLE
[MINOR] (Editor) Editor viewport UI appears on top of other windows

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2780]
**Describe the bug**
When ALT-TABing back to the editor when the Script Canvas window is on top, the viewport UI appears on top of the Script Canvas window until you click on the Script Canvas window, giving it focus.

**To Reproduce**
1. Open the editor and the script canvas editor
2. Maximize the script canvas editor
3. ALT+TAB to a different application
4. ALT+TAB back 

**Expected behavior**
The viewport UI elements do not appear over-top of the script canvas window

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by hultonha** [comment]
This is a duplicate, I've reported this, will try find the existing issue tomorrow

**Comment by hultonha** [comment]
https://github.com/o3de/o3de/issues/2603#issue-955878335

**Comment by AMZN-alexpete** [comment]
Closing as duplicate of https://github.com/o3de/o3de/issues/2603
