### ISSUE TITLE
[MAJOR] (Editor) Editor loses focus when exiting game mode

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2787]
**Describe the bug**
Frequently after entering game mode and pressing ESC, you have to mouse click in the editor before it gets focus and commands like CTRL+G work again.

**To Reproduce**
1. In the editor enter game mode using CTRL+G
2. Press ESC to exit game mode
2. Press CTRL+G 

**Expected behavior**
The editor enters game mode

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by cgalvan** [comment]
Duplicated by #2194
