### ISSUE TITLE
Prefabs - Reparenting a Prefab container changes its World Position

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#2791]
**Describe the bug**
Reparenting entities between different prefabs (from level to nested prefabs) works as expected - the local position is updated to preserve the world position.
Reparenting prefabs between different prefabs though seem to preserve the local position instead of the world one, causing the reparented prefab to move around in the world.

**Screenshots**
![reparentMovesPosition](https://user-images.githubusercontent.com/82231674/128073723-64b3b357-b361-49bb-8c61-0b3fb2dccb5d.gif)

**Comment by monroegm** [comment]
When I tried to repro on development at 4cde568ea4, the operation put things into a weird state with the error message below, though at least it was undoable.

`[Warning] (Prefabs) - Prefab - EntityIdMapper: Entity with Id [8625705355091417536] has no registered owning instance`

**Comment by AMZN-daimini** [comment]
This operation is now unsupported.
