### ISSUE TITLE
'Be this camera' sometimes destroys the camera transform settings on the entity

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2795]
**Describe the bug**
Sometimes using 'Be this camera' changes the orientation and transform of the camera and loses the camera entity transform in a prefab.  Possibly related to these logs:
Turns out this was a patch on the prefab and is failing to apply
[Error] (Prefab) - Patch was not successfully applied.
[Error] (Prefab) - Applying the patch on the entity with alias 'Entity_[321883614944504]' in template with id '3' was unsuccessful

**To Reproduce**
1. Create a camera in the scene
2. Create a prefab that includes the camera
3. use the 'Be this camera' button on the camera component in the Prefab

**Expected behavior**
You become the camera and the transform is preserved when you return to the editor camera

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by srikappa-amzn** [comment]
This doesn't seem related to prefabs. To reproduce this, you don't even need to create a prefab. I've tested this with the camera that comes with the default atom environment in every new level, both when prefabs are enabled and disabled. In both cases, when I move the camera around and switch back to editor camera, the previous transform values on the camera are lost. The only transform values that stick are those of the editor camera

**Comment by srikappa-amzn** [comment]
This is fixed with https://github.com/o3de/o3de/pull/5326 . Feel free to reopen again if you encounter this.
