### ISSUE TITLE
[MAJOR] (Prefabs) Missing layer support

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2803]
**Describe the bug**
When prefabs are enabled there is no layer support

**To Reproduce**
1. Enable prefabs and build
2. Open the editor

**Expected behavior**
Layers can be created from the Entity Outliner

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by monroegm** [comment]
The current behavior is by design. Please open a feature request to consider adding this functionality.
