### ISSUE TITLE
[MAJOR] (Prefabs) When creating a prefab the origin of the prefab is offset

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2804]
**Describe the bug**
When making an entity a prefab, the origin of the prefab is lower than the entity origin

**To Reproduce**
1. Create an entity in the editor
2. Right click the entity in the Entity Outliner and create a prefab

**Expected behavior**
The origin of the prefab is the same as the entity

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed.
