### ISSUE TITLE
Texture atlas/animated sprite support outside of UI

### ISSUE THREAD

**Issue by AMZN-puvvadar** [o3de/o3de#2809]
**Is your feature request related to a problem? Please describe.**
I'd like to be use animated sprites in O3DE (for both 2D and 3D games) but there does not seem to be atlas support (and related support for sprite sheeting) available outside of UI.

**Describe the solution you'd like**
The ability to import a texture atlas outside of UI and to index parts of it (hugely useful for mobile to reduce draw calls) and to create sprite sheets out of an atlas (i.e. given an atlas that defines frames of a run animation, I can use that animation in game).

**Describe alternatives you've considered**
Using a purely UI driven solution for 2D but I'm uncertain how stop gap that'd be

**Comment by superkitcath** [comment]
Please reopen as an RFC under the sig-presentation repo [https://github.com/o3de/sig-presentation/tree/main/rfcs](url) 

The procedure can be found here: [https://github.com/o3de/rfcs#the-rfc-process](url)
Thank you!
