### ISSUE TITLE
Couldn't get character animation work correctly in AutomatedTesting.

### ISSUE THREAD

**Issue by xukan840730** [o3de/o3de#2811]
**Describe the bug**
In project AutomatedTesting, add an entity with an Actor component and SimpleMotion component. (using assets in AutomatedTesting)
However the character doesn't animate at all (stays TPose).

**To Reproduce**
1. Launch AutomatedTesting project.
2. Create a new test level.
3. Add an entity
4. Add Actor component, and set "actor" to AutomatedTesting\Objects\Characters\Jack\jack.actor
5. Add Simple Motion component, and set "motion" to AutomatedTesting\Animations\Motions\Jack_death_fall_back_zup.motion
6. Play Game.
7. "Jack" stays in tpose.

**Expected behavior**
I am expected to see jack play some animation.

**Screenshots**
![image](https://user-images.githubusercontent.com/19415884/128094136-113b362e-6b67-4dbb-9385-a8f56eb0966d.png)

![image](https://user-images.githubusercontent.com/19415884/128094184-304cff49-b864-44aa-bbb4-5982bdae4183.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows10

**Additional context**
I also tried previewing Jack_death_fall_back_zup.motion in ANimation Editor. It show nothing there, either.

**Comment by xukan840730** [comment]
If there's any sample project or level which has animated character, please let me know. I would like to know how to set it up.
Thanks!

**Comment by wintermute-motherbrain** [comment]
@monroegm @amzn-jillich Looks like this is an EMFX issue.

**Comment by monroegm** [comment]
@lsemp3d FYI

**Comment by amzn-jillich** [comment]
Fixed on development
![JackAnim](https://user-images.githubusercontent.com/43751992/154244465-3f8bc1a9-4e3c-4eb9-9d55-c1b2df84dc47.gif)
