### ISSUE TITLE
MainMenu Ui Canvas GameLauncher Crash

### ISSUE THREAD

**Issue by WashedUpStudio** [o3de/o3de#2818]
**Describe the bug**
If you add the GameState Samples gem to a project and start it up in the gamelauncher it crashes instantly.

**To Reproduce**
1. Go to a created project and add the GameState Samples Gem
2. Build your project to get the gem included
3. Click on Game Launcher for your project 
4. The editor should crash almost instantly with a white screen.

**Expected behavior**
If you use the mainmenu ui canvas from the GameState Samples gem it should allow you to go into the gamelauncher without a crash.
**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**
Log of my gamelauncher after the crash;
https://pastebin.com/syRX4ER7

**Comment by AMZN-mnaumov** [comment]
I can't get this to repro any more, game launcher starts and main menu loads and works. One thing to note - if launching from executable, make sure to pass command line arguments specifying project location (e.g. MyProject.GameLauncher.exe --project-path="C:/o3de/MyProject")
