### ISSUE TITLE
Unable to build project using Ninja generator

### ISSUE THREAD

**Issue by Shatur** [o3de/o3de#2820]
**Describe the bug**
When building a project using Ninja, I get the "bad $-escape (literal $ must be written as $$)" error. Looks like the `DLY_LOCK_FILE` didn't correctly parse the generator expression and it left a `$<0:` there.

**To Reproduce**
1. Open MSVC console using `%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"`
2. Configure project: `cmake -B build/windows_ninja -G Ninja -DLY_3RDPARTY_PATH="path/to/o3de-packages" -DLY_UNITY_BUILD=ON`
3. Try to build: `cmake --build build/windows_ninja --target ProjectName.GameLauncher --config profile`
4. See error: `ninja: error: build.ninja:273: bad $-escape (literal $ must be written as $$)`

**Expected behavior**
The project compiles successfully.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10

**Additional context**

Generated Ninja file:
[build.ninja](https://github.com/o3de/o3de/files/6930090/build.ninja.txt)

**Comment by lumberyard-employee-dm** [comment]
It looks like an issue with a generator expression not being resolved.
Probably missing a $<GENEX_EVAL> call

**Comment by lumberyard-employee-dm** [comment]
So the [launcher_generator.cmake](https://github.com/o3de/o3de/blob/development/Code/LauncherUnified/launcher_generator.cmake#L44-L46) is using the GENEX_EVAL generator expression for both the LOCK_FILE argument and the EXEC_COMMAND argument, but it it is resolving the `$<GENEX_EVAL:$<TARGET_FILE:AZ::AssetProcessorBatch>>` to an empty location because the `AZ::AssetProcessorBatch` is an IMPORTED target.

Also the  `-DLY_LOCK_FILE=$<GENEX_EVAL:$<TARGET_FILE_DIR:AZ::AssetProcessorBatch>>/project_assets.lock` generator expression somehow is resolving to `$<0:<Actual AssetProcessorBatch Directory>>/projects_assets.lock` which implies there is another generator expression that isn't resolving.

**Comment by Shatur** [comment]
> Also the -DLY_LOCK_FILE=$<GENEX_EVAL:$<TARGET_FILE_DIR:AZ::AssetProcessorBatch>>/project_assets.lock generator expression somehow is resolving to $<0:<Actual AssetProcessorBatch Directory>>/projects_assets.lock which implies there is another generator expression that isn't resolving.

And it works with the NMake generator only because it allows you to use `$` while Ninja requires escaping!

**Comment by jeremyong-az** [comment]
As a stopgap, it'd be good to know if something like this works: https://clangpowertools.com/blog/generate-json-compilation-database.html

**Comment by burelc-amzn** [comment]
This appears to be not working completely with the Visual Studio generator as well. Just following the default steps for creating and building a project with an installed engine [from the docs](https://o3de.org/docs/welcome-guide/create/creating-projects-using-cli/), and generating a solution with `cmake -B build/windows_msvc -DLY_3RDPARTY_PATH="E:/ws/3rdParty" -DLY_UNITY_BUILD=ON`, I get the following in `MyProject.Assets.vcxproj`:
```xml
  <ItemGroup>
    <CustomBuild Include="C:\o3de-projects\MyProject\build\windows_msvc\CMakeFiles\6748eb218e89304ed5a5aede720cbcce\MyProject.Assets.rule">
      <Message Condition="'$(Configuration)|$(Platform)'=='debug|x64'">Processing MyProject assets...</Message>
      <Command Condition="'$(Configuration)|$(Platform)'=='debug|x64'">setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DLY_LOCK_FILE=$&lt;0:C:/o3de-install/bin/Windows/profile/./project_assets.lock -P C:/o3de-install/cmake/CommandExecution.cmake EXEC_COMMAND  --zeroAnalysisMode --project-path=C:/o3de-projects/MyProject --platforms=pc
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal &amp; call :cmErrorLevel %errorlevel% &amp; goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd</Command>
      <AdditionalInputs Condition="'$(Configuration)|$(Platform)'=='debug|x64'">%(AdditionalInputs)</AdditionalInputs>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='debug|x64'">C:\o3de-projects\MyProject\build\windows_msvc\o3de\CMakeFiles\MyProject.Assets</Outputs>
      <LinkObjects Condition="'$(Configuration)|$(Platform)'=='debug|x64'">false</LinkObjects>
      <VerifyInputsAndOutputsExist Condition="'$(Configuration)|$(Platform)'=='debug|x64'">false</VerifyInputsAndOutputsExist>
      <Message Condition="'$(Configuration)|$(Platform)'=='profile|x64'">Processing MyProject assets...</Message>
      <Command Condition="'$(Configuration)|$(Platform)'=='profile|x64'">setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DLY_LOCK_FILE=C:/o3de-install/bin/Windows/profile/./project_assets.lock -P C:/o3de-install/cmake/CommandExecution.cmake EXEC_COMMAND C:/o3de-install/bin/Windows/profile/./AssetProcessorBatch.exe --zeroAnalysisMode --project-path=C:/o3de-projects/MyProject --platforms=pc
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal &amp; call :cmErrorLevel %errorlevel% &amp; goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd</Command>
      <AdditionalInputs Condition="'$(Configuration)|$(Platform)'=='profile|x64'">%(AdditionalInputs)</AdditionalInputs>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='profile|x64'">C:\o3de-projects\MyProject\build\windows_msvc\o3de\CMakeFiles\MyProject.Assets</Outputs>
      <LinkObjects Condition="'$(Configuration)|$(Platform)'=='profile|x64'">false</LinkObjects>
      <VerifyInputsAndOutputsExist Condition="'$(Configuration)|$(Platform)'=='profile|x64'">false</VerifyInputsAndOutputsExist>
      <Message Condition="'$(Configuration)|$(Platform)'=='release|x64'">Processing MyProject assets...</Message>
      <Command Condition="'$(Configuration)|$(Platform)'=='release|x64'">setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DLY_LOCK_FILE=$&lt;0:C:/o3de-install/bin/Windows/profile/./project_assets.lock -P C:/o3de-install/cmake/CommandExecution.cmake EXEC_COMMAND  --zeroAnalysisMode --project-path=C:/o3de-projects/MyProject --platforms=pc
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal &amp; call :cmErrorLevel %errorlevel% &amp; goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd</Command>
      <AdditionalInputs Condition="'$(Configuration)|$(Platform)'=='release|x64'">%(AdditionalInputs)</AdditionalInputs>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='release|x64'">C:\o3de-projects\MyProject\build\windows_msvc\o3de\CMakeFiles\MyProject.Assets</Outputs>
      <LinkObjects Condition="'$(Configuration)|$(Platform)'=='release|x64'">false</LinkObjects>
      <VerifyInputsAndOutputsExist Condition="'$(Configuration)|$(Platform)'=='release|x64'">false</VerifyInputsAndOutputsExist>
    </CustomBuild>
  </ItemGroup>
```

Notice how (after some horizontal scrolling) it gets the correct path to `AssetProcessorBatch.exe` *only for the profile configuration*.

This behavior appears to be consistent with the Ninja generator. When you tell CMake to configure the Ninja build as a `profile` build:
```
cmake -B build/windows_ninja -G Ninja -DLY_3RDPARTY_PATH="path/to/3rdParty" -DLY_UNITY_BUILD=ON -DCMAKE_BUILD_TYPE=profile
```

Then the build succeeds:
```
>cmake --build build/windows_ninja --target MyProject.GameLauncher
[3/3] Linking CXX executable bin\profile\MyProject.GameLauncher.exe
```

And trying to build the `MyProject.Assets` target in the `debug` config with the MSVC generator fails:
```
>cmake --build build/windows_msvc --target MyProject.Assets --config debug
Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  MyProject.Static.vcxproj -> C:\o3de-projects\MyProject\build\windows_msvc\lib\debug\MyProject.Static.lib
  unity_0_cxx.cxx
LINK : fatal error LNK1104: cannot open file '$<$<CONFIG:profile>:C:\o3de-install\lib\Windows\profile\AzCore.lib>' [C:\o3de-projects\MyProject\build\windows_msvc\o3de\MyProject-63f46c18\Code\MyProject.vcxproj]
```

**Comment by amznestebanpapp** [comment]
@Shatur Can you check that if you use Ninja and generate for profile you dont get this?
you can also generate Ninja Multi-Config and then build profile
Note that if your SDK was generated for profile, you can't build a different configuration. You can generate an SDK that has the 3 configurations by running the "install" target for the 3 configurations. 

Issue #2526 will make it that configurations not "installed" are not available for the project.

**Comment by Shatur** [comment]
> @Shatur Can you check that if you use Ninja and generate for profile you dont get this?

Sure, yes, it works.

**Comment by amznestebanpapp** [comment]
Thanks, closing
