### ISSUE TITLE
Script Canvas Component does not refresh immediately after saving the graph assigned to it

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#2821]
**Describe the bug**
A Script Canvas Component does not refresh correctly after the graph assigned to it is saved.

This may lead to a situation where a Variable which no longer exists in the graph is still visible and editable on the Component.

Please refer to the attached video for more details.

**To Reproduce**
1. Open Script Canvas.
2. Create any valid graph (i.e. On Graph Start -> Print("Hello World")).
3. Create two Variables of any type in the Variable Manager. 
4. Save the graph and assign it to an Entity.
5. Expand the _Unused Variables_ list on the Script Canvas Component.
6. Navigate back to the Script Canvas tool and create another Variable of any type in the graph.
7. Save the graph.
8. Navigate back to the Script Canvas Component and notice that the newly added Variable is not visible on it.

**Expected behavior**
The Script Canvas Component is automatically refreshed and updated correctly after the graph assigned to it is saved.

**Video**
https://user-images.githubusercontent.com/86953108/128156871-008f2219-20e3-47a4-94be-9769fe5b8aaf.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by CStudios15** [comment]
This is becoming more and more a pain as I create more SC

**Comment by lsemp3d** [comment]
Bumping up priority to critical, I was easily able to reproduce this

**Comment by carlitosan** [comment]
Fixed in https://github.com/o3de/o3de/pull/5296

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as Fixed in Development (4826048).
