### ISSUE TITLE
Using mouse wheel over entity inspector changes components' fields values unexpectedly.

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#2824]
**Describe the bug**

**To Reproduce**
1. Open Editor
2. Create an entity with a few components so the entity inspector has the ability to scroll up and down.
3. click on one text field to set the focus
4. hover the mouse over another text field (without clicking so the focus doesn't change) and use the mouse scroll up and down.
5. Notice how unexpectedly the text field without the focus is changed by the mouse scroll

**Expected behavior**
The mouse scroll doesn't change components' fields' values unexpectedly without having the focus.

**Comment by cgalvan** [comment]
Fixed by https://github.com/o3de/o3de/pull/3302
