### ISSUE TITLE
Improve SpawnAllEntities performance

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#2829]
While using `AzFramework::SpawnableEntitiesInterface::Get()->SpawnAllEntities` to spawn prefabs it was noted that spawning more than 5 prefabs in one frame it resulted in a stutter of the gameplay.

Spawning prefabs dynamically is a fundamental feature any game requires: to spawn enemies, loot, etc. and its critical it's performant and avoid the user having to look for workaround to have a fluent smooth gameplay experience.

**Comment by AMZN-mnaumov** [comment]
I have tested spawning 100 prefabs at a time, it works very well. Additionally ran CPU profiler just in case and have not noticed anything obvious that may cause performance problems.
