### ISSUE TITLE
Editor fails to launch - instead closes silently

### ISSUE THREAD

**Issue by AMZN-scspaldi** [o3de/o3de#2838]
**Describe the bug**
Whenever I try to launch the editor, it gets to the "loading plug-ins" splash screen and then closes silently.

**To Reproduce**
I can't get the editor to launch - each time I try, the splash screen pops up ("loading plug-ins") and then just disappears. I get the same behavior from the command line as I do the project manager.

I had no problems cloning the engine, pulling, building as sdk in profile configuration, etc. I made a new project via the Project Manager, and when I tried clicking the build button, nothing happened. Trying selecting build button via the hamburger menu, nothing. Tried creating a new project via another method, same behavior. Tried closing, re-opening the project manager, same behavior. Gave up on the project manager and switched to the CLI.I was able to build the project just fine from the CLI. Using this command to try launching any project from the CLI, and trying to launch any project from the Project Manager gives the same behavior as above. 

C:\o3de-install\bin\Windows\profile\Editor.exe --project-path C:\o3de-projects\NewProject 

I'm not getting any kind of error message from any of this - nothing from the failed builds, nothing from the failed launches, so I have no idea what's going on. No logs are generated in "<project-root>/user/logs".

This was a fresh pull on 7/27 of the repo, I just followed the steps here: https://o3de.org/docs/welcome-guide/setup/setup-from-github/ and here: https://o3de.org/docs/welcome-guide/create/ (trying both project manager and CLI). CMake 3.21.1 was installed new from the official website. Python is up to date.

**Comment by cgalvan** [comment]
Resolved this with a clean build after pulling latest from development branch
