### ISSUE TITLE
Relative texture paths in a material don't work for all project setups

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#2841]
**Describe the bug**
I created a material, which worked for me but not other team members.

I used an external project, where my engine lived in one directory and my project lived in another. I registered the project path using
scripts\o3de.bat register -pp D:\github\o3de-gamejam-0721\dogezero

Another team member had their project path inside their o3de folder.

The material and all its textures lived in a <project>/Substance/BrickBuilding folder. The material as initially created in the material editor was structured like this
{
    "description": "",
    "materialType": "Materials/Types/StandardPBR.materialtype",
    "parentMaterial": "",
    "propertyLayoutVersion": 3,
    "properties": {
        "baseColor": {
            "textureMap": "Substance/BrickBuilding/BrickBuilding_BaseColor.png"
        },
        "metallic": {
            "textureMap": "Substance/BrickBuilding/BrickBuilding_Metallic.png"
        },
        "normal": {
            "textureMap": "Substance/BrickBuilding/BrickBuilding_Normal.png"
        },
        "occlusion": {
            "diffuseTextureMap": "Substance/BrickBuilding/BrickBuilding_AmbientOcclusion.png",
            "specularTextureMap": "Substance/BrickBuilding/BrickBuilding_AmbientOcclusion.png"
        },
        "parallax": {
            "quality": "Medium",
            "textureMap": "Substance/BrickBuilding/BrickBuilding_Height.png"
        },
        "roughness": {
            "textureMap": "Substance/BrickBuilding/BrickBuilding_Roughness.png"
        }
}

with relative paths to all the textures. This worked for me with the external project, but not for my teammate using the project in the engine folder. My teammate got AP errors like this

7/30/2021 1:22 PM | ERROR | >	Could not find asset [Substance\BrickBuilding\BrickBuilding_Roughness.png] from AssetBuilder

Changing the material manually to get rid of the project-relative paths and instead use material-relative paths (since the textures live in the same folder as the material) resolved the issue and worked for the whole team.

{
    "description": "",
    "materialType": "Materials/Types/StandardPBR.materialtype",
    "parentMaterial": "",
    "propertyLayoutVersion": 3,
    "properties": {
        "baseColor": {
            "textureMap": "BrickBuilding_BaseColor.png"
        },
        "metallic": {
            "textureMap": "BrickBuilding_Metallic.png"
        },
        "normal": {
            "textureMap": "BrickBuilding_Normal.png"
        },
        "occlusion": {
            "diffuseTextureMap": "BrickBuilding_AmbientOcclusion.png",
            "specularTextureMap": "BrickBuilding_AmbientOcclusion.png"
        },
        "parallax": {
            "quality": "Medium",
            "textureMap": "BrickBuilding_Height.png"
        },
        "roughness": {
            "textureMap": "BrickBuilding_Roughness.png"
        }
}

**To Reproduce**
1. Create a material with a texture assignment, where both the material and texture live in a subdirectory of the project
2. Add that material and the associated texture to both an internal and external project
3. Let the AP run for both projects

**Expected behavior**
The material successfully processes.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by gadams3** [comment]
These issues should be addressed by the following changes that fix problems with how the material editor created material assets from source data and managed relative path references.
https://github.com/o3de/o3de/pull/11978
https://github.com/o3de/o3de/pull/11914
