### ISSUE TITLE
Enable and Disable shadows from entities.

### ISSUE THREAD

**Issue by WashedUpStudio** [o3de/o3de#2845]
**Is your feature request related to a problem? Please describe.**
There is not a way to stop an entity from casting shadows on other entities.
**Describe the solution you'd like**
I would like a way to stop shadows from being casted like on the mesh component, and actor component. Or a component of its own.
**Describe alternatives you've considered**
As of now there is no alternatives this is more of a need for a lot of projects.

**Additional context**

**Comment by HogJonny-AMZN** [comment]
Should this be a flag on the mesh component? (global to the whole model)

Individual materials in the mesh component?  (that could be done as a material instance flag / override)
^ That would already require this to be a material setting.

Do people also want non-renderable shadow proxies?
- flag shadow casting off on the high-res model
- and use a 'no draw' + 'shadow caster' material on the proxy mesh
- the proxy shadow caster mesh would probably be a child entity within a prefab

**Comment by WashedUpStudio** [comment]
The main reason I brought up the flag on a mesh component or actor component is because that is the way Lumberyard did it, but having it as a material instance flag would make it so you have more control over it since it would go by the materials and not the whole mesh itself. To be honest the reason I need this is kind of for the non-renderable shadow proxy. I have two characters the main and the proxy, and this is why I started to wonder if this was a feature in o3de yet.

**Comment by superkitcath** [comment]
Please reopen as an RFC under the sig-presentation repo [https://github.com/o3de/sig-presentation/tree/main/rfcs](url) 

The procedure can be found here: [https://github.com/o3de/rfcs#the-rfc-process](url)
Thank you!
