### ISSUE TITLE
Center on Selection command does nothing

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#2858]
**Describe the bug**
The 'Center on Selection' feature appears to no longer function

**To Reproduce**
1. Create a new external project
2. Select the default object
3. Move the editor camera away from this object
4. In the top menu select 'View > Center on Selection'
5. Camera does not move

**Expected behavior**
Camera moves to be near the selected object

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia RTX 2070
 - Memory 32GB

**Additional context**

**Comment by cgalvan** [comment]
Works in latest development 34afed6
