### ISSUE TITLE
Windows snap-to shortcuts do not function

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#2860]
**Describe the bug**
The windows operating system provides alignment mechanisms via its "Windows" meta-key. For example, pressing WIN+Left_Arrow will reshape most windows to the left half of the viewable desktop. These shortcuts do not work in O3DE, and are important to many users' workflow.

**To Reproduce**
1. Open the O3DE Editor
2. Press 'WIN + Left_Arrow' on the keyboard
3. Nothing Happens

**Expected behavior**
The Lumberyard Editor is resized to the left half of the screen.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia RTX 2070
 - Memory 32GB

**Additional context**
This may interact poorly with undocked, floating sub-panes of the editor. Users likely want to treat these as separate windows, which can also be rearranged according to OS-level workflows.

**Comment by cgalvan** [comment]
Duplicated by #2649
