### ISSUE TITLE
Crash when Modify and save the morph target weight.

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#2864]
**Describe the bug**
Crash when Modify and save the morph target weight.

**To Reproduce**
1. Import FBX with blendshape Attributes.
2. Open the morph target interface of the animation editor to modify the blendshape weight and save it.
3. Load the FBX model into the scene in the main IDE and click to run it. 
4. inevitably crash.

**Expected behavior**
There is no crash occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/32164562/128279163-a44c77de-29a3-4b3a-8fe5-ade27524f42c.png)

**Desktop/Device:**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel Xeon Gold 6234]
 - GPU [NVidia RTX 5000]
 - Memory [32GB]
 - Working Branch: main: e7f787572e805c413115265e5873fb2425e2f41b 

**Additional context**

**Additional context**

**Comment by amzn-jillich** [comment]
I couldn't reproduce the crash unfortunately on the development branch. Though, when diving into the asset, I've found an issue with that:
`Blend shape (eyelashes_eyeClose) as it contains more/less vertices (1984) than the neutral mesh (992).`

As a test to isolate and confirm, can you remove the blend shape named 'eyelashes_eyeClose' from your model, reexport the .fbx and see if that fixes the issue? If yes, we can automatically skip blend shapes where the number of vertices don't match and log a warning, to avoid the crash and also avoid failing to process the asset entirely.

**Comment by amzn-jillich** [comment]
Issue is fixed: https://github.com/o3de/o3de/commit/5c90bc0d58f359306352f845a094531b6e184c98

There is still another related issue open with a temporary workaround described at https://github.com/o3de/o3de/issues/3037
