### ISSUE TITLE
Default save location for .lua files is not located within the current project's folder

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#2865]
**Describe the bug**
It has been noticed, that the default save location of .lua files is within the o3de-install\bin\Windows folder and not the current project's folder. The file itself is saved properly, however, the Editor cannot use this file, until it is moved manually to the current project's folder. It should be noted that this does not occur on some of the other tools such as Script Canvas and UI Canvas.

**To Reproduce**
1. Go to Tools > Lua.
2. In the Lua Editor go to File > New and save the file with any name in the default location.
3. Type the file's name into the Asset Browser to try and find it.

**Expected behavior**
.lua file default save location is somewhere within the current project's folder.

**Video**

https://user-images.githubusercontent.com/86952082/128316561-ee85c7fc-9534-4bbe-bdb5-df4c2f1ba5de.mp4

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by Hsuehnj** [comment]
For the first time, Lua Editor uses ExecutableFolder as default saving path for Lua file , once a Lua file is opened in Lua Editor, it saves the file path of this Lua file and uses it as default saving path.

**Comment by guillaume-haerinck** [comment]
Fixed by https://github.com/o3de/o3de/pull/18527 as the content browser won't allow you to save outside of the project folder
