### ISSUE TITLE
[Usability] Project Manager: Show configuration drop-down menu when you right-click on project image

### ISSUE THREAD

**Issue by willihay** [o3de/o3de#2878]
**Describe the bug**
The hit target area of the project config drop-down menu in Project Manager is rather small. The project image, on the other hand, offers a large target area that a user could more easily right-click to open the project config menu. Intuitively, I actually expected to be able to right-click in the project image to open a context menu. (See attached screenshot.) Both options should be offered.

![suggestion](https://user-images.githubusercontent.com/17654918/128373914-cf1fb001-b577-4961-80d2-a5d350e6feba.png)

**Comment by AMZN-alexpete** [comment]
Fixed by https://github.com/o3de/o3de/pull/6122
