### ISSUE TITLE
AudioLogger bug.

### ISSUE THREAD

**Issue by imginimg** [o3de/o3de#2879]
s_audioLogOptions is set inside AudioSystem module from s_AudioLoggingOptions cvar but this setting is not respected outside of AudioSystem module because s_audioLogOptions  is inlined in the header.
Net effect of the bug: outside of AudioSystem module AudioLogger works only with eALT_ALWAYS flag.

**Comment by amzn-phist** [comment]
Closing this issue.  The audio gems were updated to use `AZLOG_*` macros for logging, and the audio logger code was removed.  The log verbosity is controlled by global settings now, rather than the `s_AudioLoggingOptions` Cvar.
