### ISSUE TITLE
Material Canvas

### ISSUE THREAD

**Issue by ausrobis** [o3de/o3de#2890]
**Description**
As a content author using Open 3D Engine, I want to be able to create materials using a visual, node-based tool. 

**Functionality List**
- Using the O3DE editor, I want to be able to visually create and configure a material by connecting built-in shader nodes and providing parameters to their inputs.

**Feature Points of Contact**
Product Manager: @ausrobis 
Software Manager: @galibzon 

**Guidance for Collaboration**
If you have questions about this feature, or are interested in collaborating, please leave comments in this issue.

**Comment by gadams3** [comment]
https://github.com/o3de/sig-graphics-audio/issues/51
