### ISSUE TITLE
Physics Material System Improvements

### ISSUE THREAD

**Issue by ausrobis** [o3de/o3de#2897]
### Description

The way physics material assets are stored and used will be completely updated. The physics material library asset will be removed and we will support individual physics material assets, much like render materials and other assets in O3DE. This will make working with physics materials much easier and more consistent. 

- [x] Remove physics material library and support individual physics assets

### Status

Complete

**Comment by hultonha** [comment]
Aside: We updated this ticket to better reflect recent physics work - please see original ticket details that have been migrated to https://github.com/o3de/o3de/issues/12077.

**Comment by moraaar** [comment]
PhysX Material refactor work to remove physics material library was submitted by the following PR:
- https://github.com/o3de/o3de/pull/9856

The same refactor was done for blast materials:
- https://github.com/o3de/o3de/pull/9211

**Comment by moraaar** [comment]
[Impactful Change] Physics material refactor

**What’s changing?**
Physics material assets are now managed independently. The concept of physics material library has been removed and now one asset is one physics material. A physics material is created using Asset Editor tool.

**Why is this change being made?**
To simplify the workflow of authoring and using physics materials, we're making it more like how render materials work. Having a library asset added an extra layer of complexity that users had to deal with and learn how to use within the editor. Now physics materials can be assigned to collider components directly like any other asset.

**When is this change coming to development?**
Change was merged June 8th 2022 https://github.com/o3de/o3de/pull/9856

**What actions will I need to take?**
If you work with AutomatedTesting, atomtest, atom-sampleviewer, multiplatyersample or netsoaktest, you don’t need to do anything, all physics material assets will be converted already.

For any other project, one person will need to convert assets following these steps:
  1. Run Editor. Do not open any level, just close the "Welcome to O3DE" screen.
  2. Wait until Asset Processor has finished processing all the assets
  3. Open Console: Tools > Console
  4. Enter the following console command to convert old physics material libraries: "ed_physxConvertMaterialLibrariesIntoIndividualMaterials"
  5. Wait until Asset Processor has finished processing all the assets
6. Enter the following console command to fix prefabs and fbx manifests that reference old assets: "ed_physxFixAssetsUsingPhysicsLegacyMaterials"
7. Wait until Asset Processor has finished processing all the assets
8. Commit the source assets changes into Github.

**What components are affected by this change?**
Physics materials are used in the following places:
- PhysX Collider Component
- PhysX Shape Collider Component
- PhysX Character Controller Component
- PhysX Terrain Heightfield Collider Component
- Terrain Heightfield Component
- Blast Family Component
- Actor’s Ragdoll Collider in FBX manifest
- Actor’s Hit Detection Collider in FBX manifest
- PhysX Mesh Group in FBX manifest
- White Box Collider

**Comment by hultonha** [comment]
Please see tangentially related follow-on work [here](https://github.com/o3de/o3de/issues/15093)
