### ISSUE TITLE
[Editor] The color picker option in o3de editor doesn't support alpha channel

### ISSUE THREAD

**Issue by amzn-rhhong** [o3de/o3de#2902]
The color picker in the editor doesn't seem to support alpha. But AZ::Color class is RGBA, so the alpha data is there.

**Expected behavior**
Color picker support alpha channel.

**Screenshots**
![image](https://user-images.githubusercontent.com/69218254/128422324-2e70e5cd-f83a-4d46-81bf-f6b110a3d172.png)

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by amzn-rhhong** [comment]
->Attribute(AZ_CRC("AlphaChannel", 0xa0cab5cf), true)
Apparently you can add this to turn on the alpha channel. I didn't know.

**Comment by Jackie9527** [comment]
> ->Attribute(AZ_CRC("AlphaChannel", 0xa0cab5cf), true)
> Apparently you can add this to turn on the alpha channel. I didn't know.

Sorry, cannot get your point. Just wonder where to put your code.

The RBG value from Color picker is 34,255,0, and the RBG value from input text is 4,255,0.
Why they are different? I am confused about that.

**Comment by AMZN-alexpete** [comment]
> ->Attribute(AZ_CRC("AlphaChannel", 0xa0cab5cf), true)
> Apparently you can add this to turn on the alpha channel. I didn't know.

It might be useful to examine all our uses of color attributes and determine if we should change the default to include alpha, and make the flag only necessary to hide the alpha channel setting e.g. 'HideAlphaChannel'
