### ISSUE TITLE
Difficult to use O3DE panes alongside another tool

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#2903]
**Describe the bug**
One cannot easily use a single undocked editor pane and other tools (such as a text editor) side-by-side at the same time: selecting and giving focus to any O3DE "window" brings all of the panes to the front, potentially covering other windows. The user instead needs to hand-update all panes to be the correct size, closed, or minimized. This breaks the flow of content editing, plus moving panes to be in the same area makes it quite easy to accidentally dock panes back into random parts of the editor.

This is partially related to https://github.com/o3de/o3de/issues/2860

**To Reproduce**
1. Open the O3DE Editor
2. Open (or undock) multiple panes on the left, center, and right of the screen
3. Open a text editor (or other DCC tool), and place it on the right portion of the screen
4. Move between editing text, and editing in O3DE
5. No matter which pane is selected, all focus to the front.

**Expected behavior**
Undocked panes behave like individual windows, and do not render over top of other windows when any pane is selected.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia RTX 2070
 - Memory 32GB

**Additional context**

**Comment by NicholasVanSickle** [comment]
@alexmontAmazon the docking window parentage issue strikes again! I'm unsure offhand if we have another GHI for this?

**Comment by cgalvan** [comment]
There wasn't one yet, but I have now imported it with all the discussion/comments.

Duplicated by #2930

**Comment by Kadino** [comment]
Seems quite strange to close this and add a new duplicate. I imagine if I were a public contributor I would be a bit offended.
