### ISSUE TITLE
Using non-uniform scale on a prefab entity gives a AtomViewportDisplayIconSystemComponent error

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/o3de#2911]
**Describe the bug**
When I added a non-uniform scale on a prefab entity, I get this error in the console:
[Error] (AtomViewportDisplayIconSystemComponent) - Failed to locate icon on disk: "Icons/Components/Viewport/NonUniformScale.svg"

**To Reproduce**
1. Enable prefabs
2. Create an entity and give it a non-uniform scale
3. Create a prefab out of the entity
4. You will see the above error in the console.

**Expected behavior**
No errors appear in console

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz 
 - GPU NVidia GeForce RTX Super 2700
 - Memory 64GB

**Comment by cgalvan** [comment]
Fixed by https://github.com/o3de/o3de/pull/3059
