### ISSUE TITLE
Unable to fetch collision contacts from script canvas upon collision

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/o3de#2913]
**Describe the bug**
When I add the GetContacts node in script canvas to get the contact points info of the collision, I get the below error when I save the script. Without this, I cannot easily get the info about where the collision happened.

7/28/2021 11:53 AM | ERROR | ScriptCanvasBuilder: Trace::Error from AssetBuilder
7/28/2021 11:53 AM | ERROR | >	D:/o3de/Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.cpp(362): 'void __cdecl ScriptCanvasBuilder::Worker::ProcessJob(const struct AssetBuilderSDK::ProcessJobRequest &,struct AssetBuilderSDK::ProcessJobResponse &) const' from AssetBuilder
7/28/2021 11:53 AM | ERROR | >	Graph conversion to abstract code model failed: * The input is known to be null, and the node does not accept it from AssetBuilder

**To Reproduce**
1. Create a script canvas and try to add Physics>collision event> GetContacts node
2. Try to connect the above node to an OnCollison Begin event node
3. Try to save the script. See the error

**Expected behavior**
Upon collision, you can get the contact points easily

**Screenshots**
![GetContactsAPError](https://user-images.githubusercontent.com/82230713/128429957-a0c402c4-c81b-4a7c-a36d-811ced0a6a39.PNG)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz 
 - GPU NVidia GeForce RTX Super 2700
 - Memory 64GB

**Comment by FuzzyCarterAWS** [comment]
This appears to be fixed in origin/dev after the sc-editor-asset-redux merge in my snapshot testing.

@srikappa-amzn , can you please confirm that this resolved the issue for you?

**Comment by jckand-amzn** [comment]
Verified fix on development@7c88f20e1e6bf4. Closing out.
