### ISSUE TITLE
System Component reflected property configuration in .setreg files

### ISSUE THREAD

**Issue by yuriy0** [o3de/o3de#2942]
**Is your feature request related to a problem? Please describe.**
Very often when we are creating our gems, those gems should have system-level configurations.

In the past, this could be done with zero effort by reflecting the Gem system components to the serialization context. Such data would be saved and loaded to Config/Game.xml and Config/Editor.xml. This made adding configurable properties to Gems a nearly zero effort process.

**Describe the solution you'd like**
The settings registry should replace this functionality. I should be able to write something like

```
{
   ...,
   "SystemEntity" : [ "$type" : "RPISystemComponent", value : { < reflected properties from RPISystemComponent > } ]
}
```

in some registry file. Note that `RPISystemComponent` as an example already has reflected properties.

**Describe alternatives you've considered**
Manually creating this functionality for every single configurable property in every single gem. Laborious and error prone!

**Additional context**
N/A

**Comment by ppinfel** [comment]
Looking for updates!

**Comment by yuriy0** [comment]
> @yuriy0 Please provide the acceptance criteria for this

I'm okay with having to call `AZ::SettingsRegistry::GetObject` in the `Activate` function of the component.
