### ISSUE TITLE
[Asset Browser] Cannot delete files in the right click menu in the Asset Browser window.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2973]
**Describe the bug**
When cleanuping local workspace, it is very convenient to delete unused files in the Asset Browser.

**To Reproduce**
1. Open Editor.
2. Open Asset Browser.
3. Find a unused file, such as a material file.
4. Right click it, then right click menu shows up.

**Expected behavior**
Delete shows up in the right click menu.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by AMZN-daimini** [comment]
This has been implemented with the new Asset Browser.
