### ISSUE TITLE
[Asset Browser] Cannot rename files in the right click menu in the Asset Browser window.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2974]
**Describe the bug**
When cleanuping local workspace, it is very convenient to rename a file to a valid name in the Asset Browser.

**To Reproduce**
1. Steps to reproduce the behavior:
2. Open Editor.
3. Open Asset Browser.
4. Find a unused file, such as a material file.
5. Right click it, then right click menu shows up.

**Expected behavior**
Rename shows up in the right click menu.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by AMZN-daimini** [comment]
Resolved in development https://github.com/aws-lumberyard-dev/o3de/pull/381
