### ISSUE TITLE
[Material Editor] The material file could recover when it is deleted in the Explorer window.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2975]
**Describe the bug**
When deleting file in the Explorer window, the file would show up again in the Asset Browser. That's amazing.

**To Reproduce**
1. Open Editor.
2. Open Material Editor.
3. Open Asset Browser in Material Editor.
4. Select a material file, right click on it, then click Open in Explorer.
5. Delete the file in the Explorer window.
6. Back to Material Editor, Click File -> Save.
7. Check Asset Browser, the file just deleted shows up again.

**Expected behavior**

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by gadams3** [comment]
This is missing the repro steps that the file is actually opened in the material editor.

Currently, once a document is open in the material editor it is working with the in memory representation of the data. Moving, deleting, or renaming the file on disk will have no effect on the open document, which can still be saved to the original file or a new one. This behavior is the same as something like notepad or Visual Studio, which do not react when the user moves or deletes a file outside of the application. However, they will notify you if it was edited externally and prompt for reload. On the other hand, something like Microsoft Word blocks the OS and explorer from letting the user move or delete the file.

We could create a feature RFC to request the specific behavior in response to different explorer actions.

**Comment by gadams3** [comment]
As described previously, this seems like expected behavior of resaving the file with the same filename. Without additional details, this seems as designed.
