### ISSUE TITLE
[Material Editor] The material file could recover when it is renamed in the Explorer window.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2976]
**Describe the bug**
When renaming a material file to a new name in the Explorer window, the material file with old name would show up again in the Asset Browser. 

**To Reproduce**
1. Open Editor.
2. Open Material Editor.
3. Open Asset Browser in Material Editor.
4. Select a material file, like a001.material, right click on it, then click Open in Explorer.
5. Rename the file in the Explorer window with a new name like b001.material.
6. Back to Material Editor, Check Asset Browser, b001.material shows up and a001.material disappears.
7. Click File -> Save.
7. Check Asset Browser, both a001.material and b001.material show up.

**Expected behavior**
a001.material never shows up again.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by gadams3** [comment]
Currently, once a document is open in the material editor it is working with the in memory representation of the data. Moving, deleting, or renaming the file on disk will have no effect on the open document, which can still be saved to the original file or a new one. This behavior is the same as something like notepad or Visual Studio, which do not react when the user moves or deletes a file outside of the application. However, they will notify you if it was edited externally and prompt for reload. On the other hand, something like Microsoft Word blocks the OS and explorer from letting the user move or delete the file.

We could create a feature RFC to request the specific behavior in response to different explorer actions.

**Comment by gadams3** [comment]
This is missing the repro steps that the file is actually opened in the material editor.

Currently, once a document is open in the material editor it is working with the in memory representation of the data. Moving, deleting, or renaming the file on disk will have no effect on the open document, which can still be saved to the original file or a new one. This behavior is the same as something like notepad or Visual Studio, which do not react when the user moves or deletes a file outside of the application. However, they will notify you if it was edited externally and prompt for reload. On the other hand, something like Microsoft Word blocks the OS and explorer from letting the user move or delete the file.

We could create a feature RFC to request the specific behavior in response to different explorer actions.

**Comment by superkitcath** [comment]
Thanks @gadams3 ! The procedure to create a feature RFC can be found [here](https://github.com/o3de/rfcs#the-rfc-process)

**Comment by Jackie9527** [comment]
> This is missing the repro steps that the file is actually opened in the material editor.
> 
> Currently, once a document is open in the material editor it is working with the in memory representation of the data. Moving, deleting, or renaming the file on disk will have no effect on the open document, which can still be saved to the original file or a new one. This behavior is the same as something like notepad or Visual Studio, which do not react when the user moves or deletes a file outside of the application. However, they will notify you if it was edited externally and prompt for reload. On the other hand, something like Microsoft Word blocks the OS and explorer from letting the user move or delete the file.
> 
> We could create a feature RFC to request the specific behavior in response to different explorer actions.

Sorry, my fault, I lost a step in repro.

**Comment by gadams3** [comment]
Thank you. This behavior seems as designed and consistent with what would be expected of other editors and tools, resaving or saving on top of a pre-existing file. As mentioned, some tools and operating systems lock the open files so that it cannot be modified if it is opened by another application. But I will consider this as designed without additional details.
