### ISSUE TITLE
[Editor] Entity object references a material file which is deleted.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2977]
**Describe the bug**
Entity object references a material file which is deleted.

**To Reproduce**
1. Open Editor, create a new level.
2. Create a entity, named as test001.
3. Add a Mesh component with Mesh Asset shaderball_default_1m to test001.
4. Add Material component with a existed material file test.material as Default Material to test001.
5. Open Explorer, and find the location of test.material, delete test.material.
6. Back to Editor, check Material component of test001, test001 uses default material type.
7. Check the viewport and, found that test001 still uses material defined by test.material.

**Expected behavior**
When test.material is deleted, then Editor should load the default material file for test001.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by gadams3** [comment]
Thank you for posting this issue. Could you please clarify if you think
- the material component should remove the deleted asset from its list/UI
- the deleted assets should no longer be displayed in the viewport

I do not believe we should automatically remove the entry from the material component. The editor will warn and the UI will display an indicator if the asset is invalid, allowing the user to take action to repair the data.

**Comment by gadams3** [comment]
Once an asset is loaded and applied, there are no notifications from the asset system that it has been deleted or should be removed. I don't think there are any runtime systems that behave like this. There are notifications and there is handling in place if the material or one of its textures is missing or fails to load.
