### ISSUE TITLE
Provide Bottom Toolbar and X/Y/Z Axis in the viewport.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2979]
Like [Lumberyard Editor Interface](https://docs.aws.amazon.com/lumberyard/latest/userguide/lumberyard-editor-interface.html), the X, Y, and Z in the Bottom Toolbar is very useful.
Like [Using the Viewport](https://docs.aws.amazon.com/lumberyard/latest/userguide/lumberyard-editor-viewport.html), developer could easily distinguish between X, Y, and Z axis, with their names by the axis.

**Comment by cgalvan** [comment]
@rainbj @amzn-leenguy This is a request for bringing back some items that were removed from the Viewport UI. In general, we have been trying to clean up the interface, maybe some of the future plans would address these requests?

**Comment by amzn-leenguy** [comment]
We have this UX covered in our camera navigation update, but it needs developer time to get it feature complete. Its on the roadmap for the team to get it updated and addressed.

**Comment by Jackie9527** [comment]
The features metioned are fulfilled, as follows:
![image](https://user-images.githubusercontent.com/80555200/222060972-682c778f-1592-423d-a844-ae89e75932e1.png)
