### ISSUE TITLE
Entering the Game Mode after deleting a Prefab used in the Level from disk crashes the Editor

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#2998]
**Describe the bug**
Entering the Game Mode after a Prefab which is used in the Level was deleted from disk crashes the Editor.
Please note that the crash only occurs after the Editor was restarted.

Please refer to the attached video for more details.

**To Reproduce**
1. Create or open any Level.
2. Create a new Entity.
3. Right click the Entity and select _Create Prefab..._.
4. Save the Level.
5. Close the Editor.
6. Navigate to the created Prefab file location and delete it.
7. Launch the Editor and Level from step 1.
8. Enter the Game Mode.

**Expected behavior**
The Editor does not crash.

**Video**

https://user-images.githubusercontent.com/86953108/128845950-3a433c78-a115-4db4-9498-928e711f5228.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 Super
 - Memory 16GB

**Attachments**
[Editor.log](https://github.com/o3de/o3de/files/6960600/Editor.log)
[error.log](https://github.com/o3de/o3de/files/6960601/error.log)
[error.zip](https://github.com/o3de/o3de/files/6960602/error.zip)
[LevelTest.prefab-3558160309-10689.log](https://github.com/o3de/o3de/files/6960641/LevelTest.prefab-3558160309-10689.log)

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed.

**Comment by LB-TomaszSerwanski** [comment]
Fix verified in Development (3200c2f).
