### ISSUE TITLE
Entering and exiting the regular Game Mode (not maximized) causes the input to not be registered in the Viewport

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#3000]
**Describe the bug**
It has been noticed, that entering and exiting the regular Game Mode (Play Game (Ctrl + G)) causes the input to not be registered anymore within the Viewport. The panes around the Viewport can still be interacted with. It should also be noted, that this does not occur when entering the Game Mode via Play Game (Maximized).

**To Reproduce**
1. Enter the Game Mode using the Play Game (Ctrl + G) button, or by using its hotkey.
2. Exit the Game Mode.

**Expected behavior**
The input is still being properly registered after exiting the Game Mode.

**Video**

https://user-images.githubusercontent.com/86952082/128860083-374aefbf-659a-480e-be06-395cdd36a302.mp4

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by cgalvan** [comment]
@michabr  Is this related to https://github.com/o3de/o3de/pull/2948 ?

**Comment by LB-ArturSiewniak** [comment]
Issue verified as fixed on Development (4cf384c).
