### ISSUE TITLE
[PhysX] Color preview looks different when color picker is open when selecting color for a Box Shape.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#3007]
**Describe the bug**
Set color of Box Shape to 255,0,0 with color picker, when color picker is open, then the color preview is brighter than color picker  is closed.

**To Reproduce**
1. Open Editor.
2. Create a new Entity.
3. Add PhysX Collider and Box Shape.
4. Set Shape Color with color picker, set RGB value as 255,0,0.
5. Open/Close the color picker several times, check the color preview.
6. See difference.

Also, when going into game mode, the color of box shape looks different with the color preview.
1. Open Editor.
2. Create a new Entity.
3. Add PhysX Collider and Box Shape.
4. Set Shape Color with color picker, set RGB value as 255,0,0.
5. Enable Game View.
6. Make a screen clip with the color preview in it.
7. Go to game mode, check the color of box with the color in clip.
8. See difference.

**Expected behavior**
No difference whether the color picker is open or closed.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by HogJonny-AMZN** [comment]
Just reviewing this and commenting in my own words.

1. When I create a Box Shape, the default color is yellow-ish
2. It renders this color in the viewport
3. The color swatch for the Box Shape color is brown-ish
4. If I click-on the color swatch it open the color picker
5. The color picker displays a yollow-ish color (the correct sRGB color.)
6. The color swatch of the Box Shape suddenly pops to display yellow (same as in the picker.)
7. When I hit OK and close the Color Picker, the Box Shape color swatch has the same numerical value but now remains yellow.

What this implies to me ... the brown you initially see, likely is the Linear RGB value of this yellow (many colors, such as those in materials, are converted from the color picker working color space to the renderer Linear RGB color space).  And that the Color Picker is somehow putting this swatch into a state where both the working (picking) and the display/storage state are all in the same color space of sRGB.

![Editor_WODRraZ5Bg](https://user-images.githubusercontent.com/23222931/217637108-dd341205-df1c-4bb5-b0e6-3c39de5b34bb.gif)

Whether or not this is correct, depends on the color consumer, which is in this case the Box Shape.  And what color space it's expecting to store data and feed the render component.

The Box Shape color swatch, switches from displaying yellow-ish, back to brown-ish, if you change views like switching from editor camera to another camera, etc.  Or going in and out of game mode. (note: the numerical value remains the sRGB yellow-ish.)

![Editor_T9WWIP3EYH](https://user-images.githubusercontent.com/23222931/217638375-ccec809d-5af9-4d9a-ad3d-43c94d198144.gif)

To me, this would imply that the Box Shape's storing sRGB (it's not converting the numerical value to Linear RGB), and this problem may only be what the color swatch is doing (sometimes displays sRGB, sometimes displays the color converted to Linear RGB value)?

**Comment by Jackie9527** [comment]
I have a PR #14458 to fix this issue, and it's been merged.
