### ISSUE TITLE
AWS Resource Mapping Config Location always displays an empty directory

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#3011]
**Describe the bug:**
When the User opens location of the Config files via Resource Mapping tool, the Directory looks empty. If the same directory is opened via explorer, the config files are present.

**To Reproduce**

1. Configure the AWS connection.
2. Open the Resource Mapping tool.
3. Press the Config Location button.

**Expected behavior**
An explorer window opens and the config files are visible.

**Attachments:**
![DirectoryLocation](https://user-images.githubusercontent.com/86952591/128875829-459a272f-dc62-495b-b8e4-e241746474d1.png)

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 9 3900X
GPU Nvidia RTX 2060 Super
Memory 16GB

**Comment by onecent1101** [comment]
Config Location button is letting you choose the config files folder, it is expected that files won't show up. (Only folder will show up)
