### ISSUE TITLE
[PhysX] Global wind simulated by Force Region dosen't support objects outside collider shape.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#3012]
**Describe the bug**

With the following documents, I succeeded to create entities with Cloth Component and tested with global wind and local wind.
* [Create global or localized wind forces with PhysX](https://docs.aws.amazon.com/lumberyard/latest/userguide/weather-wind-global.html)
* [PhysX Force Region](https://docs.aws.amazon.com/lumberyard/latest/userguide/component-physx-force-region.html)
* [PhysX Force Region not working with Cloth](https://forums.awsgametech.com/t/physx-force-region-not-working-with-cloth/9586)

When I try to put balls with PhysX Collider Component upon global wind and local wind, both of the balls could go up and down. Then I add a new ball to level which is outside the box shape of global wind, I guess the new ball would go up and down forced by the global wind. But it fails, just drop down to ground. 

**To Reproduce**
1. Open Editor and create a level.
2. Create a global wind entity following the links, direction is 0,0,1.
3. Create two balls, one is upon the global wind, the other is outside the global wind.
3. Go into game mode.
4. See error, the ball outside the global wind would drop down to the ground, and the ball upon the global wind would go up and down that is forced by the wind.

**Expected behavior**
The ball outside the global wind would go up and down that is forced by the global wind.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by greerdv** [comment]
The doc update is submitted, going to close this issue.
