### ISSUE TITLE
Undoing translate operations doesn't return entity icons to previous position

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#3015]
**Describe the bug**
When the user undoes a translate operation, the entities icons are left at the position before the undo, rather than following the entities back to the resulting undone position.  This is fixed if the user does another translate operation, though is confusing initially especially if there is no visual component on the entity to verify the undo worked.

**To Reproduce**
1. Open the Editor
2. Create a new level
3. Create a few entities
4. Select and move all created entities using the translate gizmo
5. Press ctrl+z to undo the movement

**Expected behavior**
Entity icons follow the entities in the world space

**Screenshots**
![image](https://user-images.githubusercontent.com/82236902/128905019-44aea4cb-e4d8-4430-80c1-454f65155ce3.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz
 - GPU: NVIDIA GeForce RTX 2080 with Max-Q Design
 - Memory: 16GB

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed.
