### ISSUE TITLE
Undoing translate operations for a large group of entities causes a noticeable hitch or "not responding" notification

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#3016]
**Describe the bug**
When the user undoes a translate operation for a larger group of entities (20+) the Editor noticeably hitches.  This increases with the number of entities.  At 40+ the hitch is multiple seconds and can cause the Editor to stop responding.

**To Reproduce**
1. Start the Editor
2. Create a new Entity
3. Duplicate the Entity several times in the same area (ideally creating 20+ entities)
4. Select all the created/duplicated Entities
5. Use the translate gizmo to move the selected entities
6. Press ctrl+z to undo

**Expected behavior**
The undo operation completes as smoothly as the initial translate (or close to it)

**Desktop/Device (please complete the following information):**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz
- GPU: NVIDIA GeForce RTX 2080 with Max-Q Design
- Memory: 16GB

**Additional context**
This could be a common operation for world building or similar changes in the Editor where the user is trying to move/nudge several entities but a mistake is made.

**Comment by monroegm** [comment]
As noted by https://github.com/o3de/o3de/issues/6599#issuecomment-1009794641 , there is no hang when doing this with the Entity Inspector closed

**Comment by chiyenteng** [comment]
Attached profiler's report about CPU usage between 'ctrl+z' pressed and all translation finished.
[Report20220308-1040.diagsession.zip](https://github.com/o3de/o3de/files/8208905/Report20220308-1040.diagsession.zip)

**Comment by chiyenteng** [comment]
Tried commenting out **InvalidateAll** from **EntityPropertyEditor::BuildSharedComponentUI** and it makes the responding time decreased to around 5 to 10 secs.
Here's the profiler's report:
[Report20220308-1145.diagsession.zip](https://github.com/o3de/o3de/files/8209246/Report20220308-1145.diagsession.zip)

**Comment by chiyenteng** [comment]
After the fix with PR #8214, right now it will take less than one sec to undo changes on 32 selected entities(before it took around 60 secs).
For more details, please check out #8214.
