### ISSUE TITLE
AssetPipelineTests.AssetBundler timeouts

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#3017]
**Describe the bug**
AssetPipelineTests.AssetBundler timeouts with the default max timeout setting. Setting it above that timeout should not be done because Jenkins' timeout can cause the test to be killed.

**Failed Jenkins Job Information:**
Failing in the periodic suite, enable the test in `AutomatedTesting\Gem\PythonTests\assetpipeline\asset_processor_tests\CMakeLists.txt` and run it through the `periodic_test_profile_vs2019` job in Jenkins

**Comment by lmbr-pip** [comment]
Stale issue, please reopen if still happening as nothing recent has been mentioned relating to this.

**Comment by AMZN-stankowi** [comment]
I verified that test still times out, I removed the test because it's not something we need.
