### ISSUE TITLE
Morph targets/blend shapes that influence multiple meshes are not working correctly

### ISSUE THREAD

**Issue by amzn-jillich** [o3de/o3de#3037]
Morph targets/blend shapes that influence multiple meshes are not working correctly.

We're seeing artefacts when increasing the weights of morph targets that influence multiple meshes at the same time.
![image](https://user-images.githubusercontent.com/43751992/128996507-c5a70a5b-f901-45a2-be03-4eed25e3cb10.png)

**Workaround until the issue is fixed:**
Merge all meshes that are deformed by any morph target together in the DCC tool and re-export the .fbx file afterwards. If you for example have different meshes for the eye brows, one for hair, another one for the head and one for the rest of the body and body is not influenced by the morph targets, only merge the meshes from the head area together and leave the body mesh still as a separate one. Mesh optimizations are not run on meshes that are morphed, so still having the body separated, will get that optimized.

**Comment by amzn-tommy** [comment]
Fixed in the development branch by https://github.com/o3de/o3de/pull/9171
