### ISSUE TITLE
It is possible to enter Maximized Game Mode when no Level is loaded which crashes the Editor 

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#3041]
**Describe the bug**
The Play Game (Maximized) button is not disabled when no Level is loaded in the Editor. Pressing it in such state results in the Editor crash after a short while (or when exiting Game Mode).

Please refer to the attached video and log files for more details.

**To Reproduce**
1. Launch Editor.
2. Dismiss the Level selection window.
3. Press the _Play Game (Maximized)_ button.
4. (Optional) Press the [ESC] key to exit Game Mode.

**Expected behavior**
The _Play Game (Maximized)_ button is disabled when there is no Level loaded in the Editor.

**Video**

https://user-images.githubusercontent.com/86953108/129032130-f35b929b-406e-436c-8dd4-0e17081e5786.mp4

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 Super
 - Memory 16GB

**Attachments**
[Editor.log](https://github.com/o3de/o3de/files/6968528/Editor.log)
[error.log](https://github.com/o3de/o3de/files/6968529/error.log)
[error.zip](https://github.com/o3de/o3de/files/6968530/error.zip)

**Comment by AMZN-daimini** [comment]
The repro steps can no longer be executed with the new Action Manager.

**Comment by LB-KacperSzczepanski** [comment]
Issue verified as fixed on Stabilization/2305 (c4dd0ce)
