### ISSUE TITLE
[Error] (AtomViewportDisplayIconSystemComponent) - Failed to locate icon on disk: "Icons/Components/Viewport/NonUniformScale.svg"

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#3053]
**Describe the bug**
When using the Non Uniform Scale component, this Warning may appear in the Console:

```
[Error] (AtomViewportDisplayIconSystemComponent) - Failed to locate icon on disk: "Icons/Components/Viewport/NonUniformScale.svg"
```

**To Reproduce**
1. Open a Level
2. Create an Entity
3. Add the Non-Uniform Scale Component
4. Keep interacting with the Editor

**Expected behavior**
No Warning is shown in the Console

**Comment by AMZN-daimini** [comment]
I created this issue for tracking purposes, but I have located the issue. The icon requested exists, but it has been added with spaces in its filename:
![image](https://user-images.githubusercontent.com/82231674/129106108-23b1a088-f559-4f9b-8d6a-91383bc955aa.png)

I will be working on a PR and I'll add it to this issue soon.

Thanks @rainbj for reporting this!

**Comment by rainbj** [comment]
Thanks for working on this
