### ISSUE TITLE
Auto-completing the inserted text by pressing TAB within Editor's Console results in a silent crash

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#3103]
**Describe the bug**
It has been observed that using TAB to auto-complete the inserted text results in a silent crash.

**To Reproduce**
1. Open Console.
2. Press TAB twice or insert any text and press TAB afterwards.
3. Observe the crash.

**Expected behavior**
Console's auto-completing functionality is working as expected and the Editor remains stable.

**Video**

https://user-images.githubusercontent.com/86953659/129357853-04358f34-d313-4f57-9925-47c11178cef1.mp4

**Desktop/Device**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel i5-9600K
- GPU: RTX 2070
- Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/6982402/Editor.log)
[error.log](https://github.com/o3de/o3de/files/6982408/error.log)
[error.zip](https://github.com/o3de/o3de/files/6982444/error.zip)

**Comment by alexmontAmazon** [comment]
@cgalvan do you have time to look at this or know a better candidate? Thanks!

**Comment by amznestebanpapp** [comment]
taking a look, this could be related to my changes

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed on Development (6b5b827) branch.
