### ISSUE TITLE
Camera shortcuts do not work

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#3129]
**Describe the bug**
Camera shortcuts do not work

**To Reproduce**
1. Open any level in the editor
2. Create a camera position shortcut with ctrl + f1
3. Move the viewport camera to a different position
4. Use the camera shortcut with shift + f1
5. The viewport camera does not move at all

**Expected behavior**
The viewport camera should move and rotate to the position where the camera position shortcut was created

**Comment by Hsuehnj** [comment]
@ppinfel  can you attach more screenshot?

**Comment by ppinfel** [comment]
![image](https://user-images.githubusercontent.com/48143120/133541352-4a8c5c42-f29e-43b9-a9d3-85981f8a5f4d.png)

**Comment by hultonha** [comment]
It's possible these shortcuts are legacy and are not wired up to the new camera system. I'll make a note to take a look 👍

**Comment by hultonha** [comment]
This is related to https://github.com/o3de/o3de/issues/3632 and is because the old way camera positions were stored and restored is no longer supported. The good news is a fix is in the works (ETA TBD) that @AMZN-Igarri is working on. We'll keep you posted on developments and reference PRs here
