### ISSUE TITLE
Invalid parameter passed to CRT function with Network Binding

### ISSUE THREAD

**Issue by Shatur** [o3de/o3de#3131]
**Describe the bug**
I have `Invalid parameter passed to CRT function` fatal error on level loading.

**To Reproduce**
1. Create a `Player.prefab`
2. Add a `Network Binding` component.
3. Save prefab to file.
4. Create a new level (created level will have a camera entity, this is important)
5. Run the game from compiled executable
6. Open console `~`
7. Execute `Host` command.
8. Execute `LoadLevel <level name from step 4>`

**Expected behavior**
Level loaded.

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10

**Additional context**
If I delete the camera object, the level is loaded successfully.

**Comment by lmbr-pip** [comment]
Sorry that this has been blocking you. Do you have the editor log (just the section around the Invalid CRT error is probably sufficient) or the call stack?

**Comment by Shatur** [comment]
Here is the callstack, but I can't access the source. Is this because I use the engine as an SDK?
![image](https://user-images.githubusercontent.com/22453358/130284631-267d6fa1-84dd-4086-8f75-aba8967698af.png)

I can reproduce it on 093a03cfbc98993d799883d9426ef3a7fda1a6a8 (development branch).
Here is a sample minimal project where you can reproduce the behavior:  https://github.com/gardum-game/gardum
To reproduce the behavior just compile the project, run the game, and execute the following commands in console:

```
Host
LoadLevel SkyRoof
```

**Comment by Shatur** [comment]
The problem was caused by a missing `Camera` gem. For unknown reasons, it is not enabled in the newly created project.
