### ISSUE TITLE
Using the 'Find slice in Asset Browser' option in Entity Outliner crashes the Editor

### ISSUE THREAD

**Issue by LB-SzymonKempinski** [o3de/o3de#3137]
**Describe the bug**
Using the 'Find slice in Asset Browser' option on any Slice object in Entity Outliner crashes the Editor.

Please refer to the attached video and log files for more details.

**To Reproduce**
1. Create or open any Level.
2. Go to 'Entity Outliner'.
3. Locate or initialize a Slice.
4. Right click the Slice and hover over the 'Find slice in Asset Browser' option.
5. Click on the Slice's name after the menu expands.
6. Observe as the crash occurs.

**Expected behavior**
No crashes occur and the Editor is stable.

**Video**

https://user-images.githubusercontent.com/88180223/129539502-68ca6982-6090-4332-9e82-6c0d668e78e0.mp4

**Desktop/Device**
- Device: PC
- OS: Windows
- Version 10
- CPU AMD Ryzen 5 3600
- GPU Nvidia RTX 2060 Super
- Memory 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/6991069/Editor.log)
[error.log](https://github.com/o3de/o3de/files/6991070/error.log)
[error.zip](https://github.com/o3de/o3de/files/6991071/error.zip)

**Comment by AMZN-daimini** [comment]
This will no longer be an issue once this RFC goes into effect: https://github.com/o3de/sig-content/issues/148
