### ISSUE TITLE
Enable / Fix Disabled Unit Tests for Linux

### ISSUE THREAD

**Issue by kinglawr** [o3de/o3de#3171]
**Requirements**

* Remove the AZ_TRAIT_DISABLE_FAILED_ARCHIVE_TESTS trait and fix related unit tests for Linux
* Remove the AZ_TRAIT_DISABLE_FAILED_ZERO_COLOR_CONVERSION_TEST trait and fix related unit tests for Linux
* Remove the AZ_TRAIT_DISABLE_FAILED_FRAMEPROFILER_TEST trait and fix related unit tests for Linux
* Remove the AZ_TRAIT_DISABLE_FAILED_FRAMEWORK_TESTS trait and fix related unit tests for Linux
* Remove the AZ_TRAIT_DISABLE_FAILED_GRADIENT_SIGNAL_TESTS trait and fix related unit tests for Linux
* Remove the AZ_TRAIT_DISABLE_FAILED_MULTIPLAYER_GRIDMATE_TESTS trait and fix related unit tests for Linux
* Remove the AZ_TRAIT_DISABLE_FAILED_EMOTION_FX_TESTS and Linux
AZ_TRAIT_DISABLE_FAILED_EMOTION_FX_EDITOR_TESTS  traits and fix related unit tests for Linux
* Remove the AZ_TRAIT_DISABLE_FAILED_METRICS_TESTS  trait and fix related unit tests for Linux

**Comment by byrcolin** [comment]
@spham-amzn Is any of this still relevant?

**Comment by spham-amzn** [comment]
> @spham-amzn Is any of this still relevant?

If any of those defines are still there, then yes.

**Comment by byrcolin** [comment]
Aged out.
