### ISSUE TITLE
As an O3DE content creator, I want a clear way to know which of the editing tools and gems that run on Windows are also available to run on Linux (Ubuntu 20.04 LTS) so that I can make decisions about my project requirements and decide on a workflow that will meet my needs. 

### ISSUE THREAD

**Issue by kinglawr** [o3de/o3de#3182]
Consider: LUA Editor, remote console application
Consider: LyTestTools, PerforcePlugin, CrashHandler, TestImpactFramework, Atom Masked Occlusion, Culling, Atom Shader Management, Console, Blast Gem, CrashReporting, LyShine UI Canvas Plugin, QtForPython gem, WhiteBox gem

**AC**:
- I need a page on the public-facing documentation on o3de.org that lists out which editing tools and gems run on Linux (compared to Windows).
- I need a readme on the object-level. AWS-owned objects needs to be updated.

**Comment by monroegm** [comment]
This is related to documentation. Rerouting to SIG-Docs-Community

**Comment by chanmosq** [comment]
For docs, we propose creating a page in docs that contains a table for supported platforms page. 
@o3de/sig-platform Can you provide us information about which platforms are supported for these tools/Gems?

Other additional solutions can be to
- Updates to the feature grid for Gems to include the supported platforms
- Updates to Readme.md per Gem about its specific tools

**Comment by chanmosq** [comment]
Can you create a ticket for o3de/o3de.org specifically for the docs request?

**Comment by spham-amzn** [comment]
This issue is outdated since we officially support Ubuntu 20.04 and Windows, meaning that there should be no feature disparity between windows and linux.
