### ISSUE TITLE
Create a readme on the object-level. AWS-owned objects needs to be updated.

### ISSUE THREAD

**Issue by kinglawr** [o3de/o3de#3183]
**Requirements**
* README.md at the AWS-owned Gem level to describe the game and supported platform(s)

**Comment by lmbr-pip** [comment]
No Gems have README.md, so its unclear what this ask is. @tonybalandiuk do you have any context here? Is this still required.

**Comment by tonybalandiuk** [comment]
@lmbr-pip the current documentation for aws-owned gems seems like it satisfies this request. Looking at the Epic here , the problem is stated mostly around platform support which you mention is covered in docs. I'm closing this request.
