### ISSUE TITLE
Create a page on the public-facing documentation on o3de.org that lists out which editing tools and gems run on Linux (compared to Windows).

### ISSUE THREAD

**Issue by kinglawr** [o3de/o3de#3184]
**Requirements**:
Editor/Gem Feature Matrix for Windows and Linux needed

**Comment by sptramer** [comment]
This should be part of the TSC feature grid provided by the SIGs - they should indicate per-platform state of features where relevant. (CC @jeremyong-az)

**Comment by jeremyong-az** [comment]
I'm removing the TSC label as this work has already been done by many (all?) sigs and the remaining work needed is to actually populate said documentation page with that data.

**Comment by chanmosq** [comment]
This is now covered by the [feature grid in the release notes](https://www.o3de.org/docs/release-notes/archive/22-05-0/feature-state/). Note the column "Platform".

Closing as resolved.
