### ISSUE TITLE
As an O3DE developer, I am able to create a Linux SDK layout for x64-based Ubuntu 20.04 LTS that can be used to author content without having to build the engine from source.

### ISSUE THREAD

**Issue by kinglawr** [o3de/o3de#3188]
**AC**:
- There should be no noticeable differences between the Editor from source build vs. the SDK build.
- I can use the project manager/configurator on Ubuntu 20.04 LTS 
- I am able to build a project using the SDK layout
- I am able to validate that a game can be executed through the launcher
- I am able to build the default level and execute the console

Confirm:
That AP for Linux also processes assets from the SDK layout

**Comment by AMZN-Liv** [comment]
This has been included in 2111.1 and is available as of today!
