### ISSUE TITLE
[Linux] Validate Project Launchers built using the SDK layout 

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#3190]
Create a Project using the SDK layout.
Create a Gem using the SDK layout and store it into the project.

That project should be able to be built using a Project-Centric SDK workflow.
Any build issues should be addressed.

A default level for the project should also be created so that it can be used with the launchers.

Running the `${project}.GameLauncher` and `${project}.ServerLauncher` applications that are built using the SDK should be verified that execute to the same level of standards as those application built using the Source Engine.

AC:
- Project can be created using the o3de python create-project script
- Project and any external gems can built using the SDK Engine
- The Project's Game and Server Launcher applications built using the SDK Engine meets the spec of using the Source Engine.

**Comment by amzn-phist** [comment]
Need to add a dependency on the Linux Native Window work that Chris (and Steve?) are working on.  That is needed if we want final verification that we can run the Launchers.

If we don't need that, I've verified everything else in this ticket: Create Project (use SDK), Add new Gem to Project, Build Project Launchers (GameLauncher only atm).

**Comment by lumberyard-employee-dm** [comment]
Your verification meets the Acceptance Criteria.
> The Project's Game and Server Launcher applications built using the SDK Engine meets the spec of using the Source Engine.
That it is why it explicitly called out, that the Linux Game and Server Launcher applications built using the SDK performs to the same specifications of those applications built using the Engine source code.
