### ISSUE TITLE
[MacOS] Create an Engine SDK Layout that contains the debug, profile and release configurations

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#3192]
Use the CMake install step for an O3DE Source Engine to generate an SDK layout containing all three build configurations for MacOS.

What to do:
Fix any issues related to creating the SDK layout if found.
Compare running the tooling applications listed in the AC below against a Source Engine MacOS build.
If the SDK Engine is exhibiting issues that are not found in the Source Engine address those.
Run the o3de registration and template instantiation scripts and fix any errors with those scripts

AC:
- Verify that the installed layout can launch the AssetProcessor, AssetProcessorBatch, Editor and Project Manager
- Validate that that the o3de python scripts are able to successfully create a project and a gems
- Verify that o3de python registration scripts work successfully

**Comment by lumberyard-employee-dm** [comment]
@amzn-sj We should be able to close this issue out, correct?

**Comment by amzn-sj** [comment]
Yes
