### ISSUE TITLE
As a game developer, I am able to extend the engine SDK layout with additional content and modules to create my own custom SDK.

### ISSUE THREAD

**Issue by kinglawr** [o3de/o3de#3198]
Intent:
Being able to build an SDK from an SDK. Being able to add other gems and projects to an SDK. Extensions to an SDK.

AC:
Content creators will able to use the SDK tools i.e. Editor/Asset Processor to build the game content and run the game launcher without building.

**Comment by lumberyard-employee-dm** [comment]
This was finished with the second phase of the O3DE as an SDK work
