### ISSUE TITLE
Add Support for creating an SDK Layout from a project using an Engine SDK Layout

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#3199]
The task here is to take a Project that is using a pre-built Engine SDK and create an SDK layout which is extended with the Project Build Artifacts and headers, which includes any additional gems the project is using, project Source Assets(`<project-path>/Assets`), as well as any files need by the project(`Config` and `Registry` folder for project settings, `Shaders` and `ShadersLib` for compiling shaders).

Since the project layout is dependent on the user/team maintaining the project, it is simpler to the steps which need to be taken.
1. The project source code isn't needed in the created SDK layout. Only the public headers, build libraries/executables are required in the layout.
2. Any Gems that build  source code with the project would needs its public headers propagated to the SDK layout, along with its build artifacts.
3. CMake scripts needed to be generated for the project build targets the same way they are generated for engine build targets when building an Engine SDK
4. The "build", "Cache" and "user" directory should be excluded as they are local directories for the user running the project
5. A `build_path.setreg` file needs to be generated into the new SDK layout `user/Registry/Platform/<Platform>` directory that indicates the relative path to the binary directory containing the complete SDK build artifacts.

AC:
- The Editor can launch and load a level from the new SDK layout without building the project
- The AssetProcessor(Batch) can successfully process all of the Project + Engine Source Assets without building the project
- The Project GameLauncher can load a level without needing to build
- Gems can still be enabled/disabled. This may require CMake to run, but no building needs to occur.

**Comment by amzn-kritinig** [comment]
which platforms are the targets?

**Comment by lumberyard-employee-dm** [comment]
The target platforms are Windows, Linux and Mac

**Comment by lumberyard-employee-dm** [comment]
This work should be finished.
