### ISSUE TITLE
As a game developer, I am able to create a project release layout with all the bundled assets that end-users are able to run the final game/simulation application.

### ISSUE THREAD

**Issue by kinglawr** [o3de/o3de#3200]
**AC**:
- We should have the layout of all of our non-restricted platforms in whatever format it is i.e. APK.
- User can then upload this package to whatever Store-equiv i.e. ApplePlay.
- It will contain all the necessary project artifacts for users to install and run their game.

**Comment by AMZN-Dk** [comment]
The task work assigned to this was completed, the testing and workflow work was moved into Jira. Closing this out.
