### ISSUE TITLE
Create a Project Game Release Layout

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#3201]
Create a "Project Game Release Layout" that can be used to run the Game/Simulation application an end-user machine.

It needs to layout the project build artifacts, the engine dependent libraries, project product assets and finally merged configurations into a directory that can be redistributed or deployed to other devices.

AC:
The GameLauncher should be able to be run from the layout directory and the required assets should load successfully.
The layout can be provided to another user and assuming they have the necessary system and 3rdParty dependencies, they should be able to run the GameLauncher successfully

**Comment by amzn-kritinig** [comment]
whats the target platform?

**Comment by lumberyard-employee-dm** [comment]
The Target platforms are `Linux` and `Windows`
