### ISSUE TITLE
As an O3DE developer, I would like to be able to make a release monolithic build using the SDK

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#3209]
The creation of the SDK layout only supports build configurations that contain non-monolithic build artifacts.
In order to release a game in a single launcher application without the need to bundle shared libraries, the SDK layout needs to support add monolithic build artifacts to it.

#### AC
- A game Launcher is able to be built and run using the SDK which is based on the `release` monolithic configuration

**Comment by amzn-kritinig** [comment]
@kinglawr can you specify which platform this Epic refers to?

**Comment by amznestebanpapp** [comment]
> @kinglawr can you specify which platform this Epic refers to?

Windows, we dont have any other platform that can produce SDK install layouts yet.
