### ISSUE TITLE
Get approved iconography for the terrain gem

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#3213]

**Comment by mcphedar** [comment]
@jjjoness @invertednormal @tjmichaels @mbalfour-amzn Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Terrain-Team-6112b58dc50a22001aa421d3/issues/o3de/o3de/3213?planning-poker)

**Comment by rainbj** [comment]
@mbalfour-amzn as this gets closer. We can reuse some of the icons I made for the components. Until we decide if we are posting assets to get hub please feel free to ping me directly for this when you are ready

**Comment by mbalfour-amzn** [comment]
This task is no longer needed, gem icons are no longer displayed or used.
