### ISSUE TITLE
Add support for creating an SDK layout from a Monolithic build

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#3226]
Monolithic builds in O3DE are builds of the final end-user applications which normally contain as few shared library as possible.
This is used to create an application that is suitable for deployment on other user's machine, avoids the need to load gem shared libraries at runtime and better helps the linker strip unneeded code.

Therefore support for creating an SDK Layout when having the monolithic CMake option(LY_MONOLITHIC_GAME) option on needs to be supported.

#### Notes:
The Monolithic builds don't include tooling applications such as the Editor or AssetProcessor, so they are normally used only for the `release` configuration.
Therefore no requirement exist to officially support an SDK Layout works with debug or profile monolithic builds.
They may work or may not, but those configurations should not be gates which prevent source code from being contributed to O3DE

#### AC:
- A Game Launcher can be built using SDK layout made from a monolithic engine.
- The Game Launcher built using the SDK layout is able to run successfully

**Comment by amzn-kritinig** [comment]
What is the target platform/s?

**Comment by amznestebanpapp** [comment]
> What is the target platform/s?

Windows

**Comment by lumberyard-employee-dm** [comment]
@amznestebanpapp We can close this again, right?

**Comment by amznestebanpapp** [comment]
Yes, closing
