### ISSUE TITLE
Add support for installing Monolithic and Non-Monolithic configurations into the same SDK layout

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#3227]
The current golden path for making a game with O3DE is to use non-Monolithic debug and profile for development and then switch to using a Monolithic release build for distribution to the end user.

This task is to add support to the SDK to the SDK layout generation via the CMake INSTALL step to take non-monolithic build CMake configuration and a monolithic CMake configuration and create an SDK layout which is the "union" of there install artifacts.

Monolithic builds only build a subset of targets that non-Monolithic builds perform, therefore the  CMake build scripts need to are common among both types of builds install layout need to be "merged" and not replaced, to make sure the proper set of build targets exist.

#### AC
- The pre-built Editor/AssetProcessor in debug and profile configurations should able to run successfully for a project using the SDK
- The GameLauncher a project builds using the SDK should be able to run in all configurations(debug, profile, release) successfully

**Comment by amzn-kritinig** [comment]
target platform/s?

**Comment by lumberyard-employee-dm** [comment]
@amznestebanpapp This task should now be complete with the following bug fix for #5225

**Comment by amznestebanpapp** [comment]
> @amznestebanpapp This task should now be complete with the following bug fix for #5225

Gotcha, will link it
