### ISSUE TITLE
Create Icons for the Terrain Mesh Component

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#3234]

**Comment by rainbj** [comment]
Hi @mcphedar, I created these awhile back for terrain system but never got used. I think the first one could work here. 
![image](https://user-images.githubusercontent.com/82551958/129774548-7c857413-5eb7-4b82-8940-bfe443bb3fee.png)

**Comment by mcphedar** [comment]
@jjjoness @invertednormal @tjmichaels @mbalfour-amzn Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Terrain-Team-6112b58dc50a22001aa421d3/issues/o3de/o3de/3234?planning-poker)
