### ISSUE TITLE
Modify renderer to composite multiple surface textures together based on blend weights

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#3271]

**Comment by superkitcath** [comment]
@mcphedar, is there more details that can be shared on this one?

**Comment by santorac** [comment]
Have you tried the StandardMultilayerPbr material type?
https://github.com/o3de/o3de/blob/development/Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.materialtype

**Comment by galibzon** [comment]
@mcphedar To try  StandardMultilayerPbr material type

**Comment by gadams3** [comment]
This should be achievable using standard multi-layer PBR as well as material canvas or custom materials and shaders
