### ISSUE TITLE
[Project Manager] Gem names are cut off and the column can't be resized to accommodate them

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#3287]
**Describe the bug**
Gem names for several gems in the configure gems page are cut off and the column can't be resized.  This makes it confusing trying to differentiate some of the gems at a glance since some of them start with the same wording but the cut off portion is more specific.

**To Reproduce**
1. Launch Project Manager
2. Select the drop down menu for a project and select Edit Project Settings
3. Select Configure Gems
4. Scroll the gems list and note the gem names

**Expected behavior**
The user should be able to resize the Gem Name column to more easily identify the gems they are looking for.

**Screenshots**
![image](https://user-images.githubusercontent.com/82236902/129805211-85c86c8b-1a5e-48fb-8e80-c6a249f25b6c.png)

**Desktop/Device (please complete the following information):**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz
- GPU: NVIDIA GeForce RTX 2080 with Max-Q Design
- Memory: 16GB

**Comment by tkothadev** [comment]
As of this PR this issue should be resolved by now: https://github.com/o3de/o3de/pull/13106


![](https://user-images.githubusercontent.com/112996779/201162530-ce9b059f-b486-4a6f-a478-efe4a2432406.gif)


Closing this issue
