### ISSUE TITLE
Deleting a prefab inside a level prefab crashes the editor

### ISSUE THREAD

**Issue by Amzn-Catdo** [o3de/o3de#3289]
**Describe the bug**
The editor would crash whenever I delete a prefab that is from inside a level prefab.
This occurs on latest development branch on commit fb05beffe3c7059f14e0a13f269b8e150ad25456

**To Reproduce**
1. Create a new level named "j1"
2. Create entity and make it into a prefab called "abc_prefab"
3. Save level
4. Create a new level called "j2"
5. Right click on entity outliner and instantiate the previous level "j1"
6. Open up the level j1 prefab and delete "abc_prefab" that is inside it

**Actual behavior**
Editor crashes (see video)

**Expected behavior**
The prefab is delete and editor does not crash

**Video**

https://user-images.githubusercontent.com/82239748/129806571-3fe477ef-29c7-45a8-b231-7f1d52fe4393.mp4

**Comment by monroegm** [comment]
This no longer crashes on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7, but it does repro #2921
