### ISSUE TITLE
[QA Cross Task]: Test Plan - O3DE Linux Support

### ISSUE THREAD

**Issue by cmoroch** [o3de/o3de#3306]
### 1. Introduction
This test plan will be used to identify the testing scope and risks of supporting O3DE on Linux. 

The initial release quality bar is that of an early release, however, the expectation is that:

1. Users can build an experience for an Ubuntu 20.04 LTS target for the application’s game client and dedicated server. 
2. Users have a clear way of knowing which of the editing tools and gems that run on Windows are also available to run on Linux
3. Users can build the O3DE Editor from source and be able to open and play the level. 
4. Users have Linux assest type successfully built. 

#### 1.1. References 
1. Zenhub Linux Project Dashboard: https://app.zenhub.com/workspaces/linux-projects-6112efe8f6ecc40015b8b505/board?repos=354743391

### 2. Linux Issues
https://github.com/o3de/o3de/issues?q=is%3Aopen+is%3Aissue+label%3Aplatform%2Flinux+label%3Asig%2Fplatform

### 3. Test Schedule and Entry Criteria
This section primarily focuses on the Test Schedule and related development activity dates.

#### 3.1 Test Schedule
**TBD** Testing should begin no later than 2 weeks before miltestone completion date. 

#### 3.2 Test Entry Criteria

Entry Criteria | Status
------------ | -------------
The branch required for testing on Linux is available | In progress
All planned feature work is complete and no build errors are present | Not Started
All necessary workflows for testing are completed and approved. <link to workflow TBA> | Not Started 
Members assisting with testing have the required hardware | In Progress

### 4. Risks
Risk | Mitigation | Detection Method | Impact | Likelihood | Risk Level
------------ | ------------- | ------------- | ------------- | ------------ | -------------
WSL will not be able to support the testing of Linux and physical ubuntu machines are needed. This will reduce the number of people who will be able to test builds and run editor.|Arrange for more hardware or dual bootable devices, plan for more time to account of reduced resources.| |High|Likey|High
The editor on Linux is in early stages so there will likely be issues blocking testing or development work | Triage newly found bugs. The quality bar for the initial release is early/experimental. | Testing | Medium | High | Medium
Team members may not have linux test hardware available | Work with teams early to get contributors set up for testing | Check with contributors | High | High | Medium
Limited Linux/Ubuntu knowledge may increase onboarding duration | Testers will need to work closely with subject matter experts. Relevant documentation should be provided early on | Check with contributors | High | Medium | Medium

### 5. In Scope
The current target is not to triple our testing.  Editor testing on Linux only requires a high-level pass
1. Editor functionality on Linux
   * Opening and running a test level
2. Building and launching a dedicated server

#### 5.1 Test Items
1. AssetProcessor functionality
   * 'Linux' asset type is available 
   * Linux-specific assets are built on Linux under the Cache folder for the project
   * AtomSampleViewer should be set as the project in the AssetProcessor GUI
   * Jobs statuses should be carefully monitored
2. Editor functionality on Linux
   * Confirming that the user can open an AtomSampleViewer level
   * User can see mesh within the Editor
3. User is able to successfully launch a game client and play the level
4. User is able to successfully launch the dedicated server without crashing.

#### 5.2 Linux QA tasks/Issues 
https://github.com/o3de/o3de/issues?q=is%3Aissue+label%3Aplatform%2Flinux+%5BQA++in%3Atitle+

### 6. Out of Scope
This is a listing of what is NOT to be tested in this test effort.

1. AutomatedTesting, AtomTest, or new projects
2. In-depth testing of the Editor. Testing will be limited to opening an AtomSampleViewer (bistro_level) level
3. In-depth testing of O3DE.exe
4. Testing on a virtualized Linux machine
   * A virtual box does not have a Vulkan enabled driver 

### 7. Test Approach
Workflows for testing will be created by Systems-Plaforms QAE's which will cover acceptance criteria

#### 7.1 Test Method
This is a listing of the test strategies that will be used for test execution. Examples of common test strategies include but are not limited to:

 * Dynamic: Exploratory testing will be used at both early and late stages of a feature development, test approach, test cases and risk analysis will adapt to new information as this testing is completed
 * Consulted: Input from the developer of the feature, and potentially from customers, will be used to help determine areas to test
 * Model-based: Common use cases and workflows will be identified and run through during testing
 
#### 7.2 Test Data and Environments
This is a listing of test data that will be required for test execution. Examples of common test data are

1. Test Assets: Assets that come with the build as well as the standard test assets used for editor testing
   * For this initial release, AtomSampleViewer assets will be needed
2. Environment: Linux systems

### 7.3 Minimum Required Hardware Specifications
|     |     |
| --- | --- |
| **Linux Hardware Specifications**      |
| **Operating System** | Ubuntu 20.04 |
| **Compiler** | clang 6.0.1+ |
| **Build Type** | Profile , Debug, Release |
| **Cmake** | 3.20 |
| **CPU** | x86\_64 bit processor |
| **RAM** | 16 GB RAM |
| **GPU** | NVidia GTX 1060 / Radeon Pro 560 / or higher |
| **GPU** **VRAM** | 4GB Recommended (Client & Editor) |

#### 7.4 Tracking and Reporting
This is a listing of the types of communication and reporting that will be performed through the test process to keep stakeholders informed of progress

* Open bugs related to the epics specified in this test plan
* Test task progress status
* Bug fix effort

Additionally what types of test deliverables will be included in this effort:

* Test plan document
* Known issues and workarounds identified
* Test runs and/or workflows created for testing

Additionally what types of test deliverables will be included in this effort:

* Test plan document
* Known issues and workarounds identified
* Test runs and/or ad hoc plan from component teams

| Exit Criteria | Status | Owner | Note |
| --- | --- | --- | --- |
| Appropriate reviews for each level of test planning have been completed | Not Started |     |     |
| All created unit tests pass (with adequate unit test coverage in place) | Not Started |     |     |
| All planned P0/P1 workflows pass | Not Started |     |     |
| All identified risks have had mitigation or deferred designations | In Progress |     |     |
| All logged Critical and Blocker defects have been fixed | Not Started |     |     |

**Comment by iMonZ** [comment]
Even if only the Ubuntu LTS is supported, can the Wayland display server still be supported in O3DE?

**Comment by amzn-kritinig** [comment]
what are minimum Linux h/w specifications ?

**Comment by cmoroch** [comment]
@spham-amzn I'm looking to add hardware specifications to the test plan. Here are some of the specs that we had previously gathered. Are there any rows that need to be updated?

|     |     |
| --- | --- |
| **Linux Hardware Specifications** |     |
| **OS** | Ubuntu 20.04 |
| **Compiler** | Clang 6.0.1+ |
| **Build Type** | Profile , Debug, Release |
| **Cmake** | 3.20 |
| **CPU** | x86\_64 bit processor |
| **RAM** | 8 GB RAM |
| **GPU** | NVidia GTX 1060 / Radeon Pro 560 / or higher |
| **GPU** **VRAM** | 4GB Recommended (Client & Editor) |

**Comment by spham-amzn** [comment]
I would bump RAM to 16 GB.

**Comment by iMonZ** [comment]
@spham-amzn

Here are the windows specs:


2.5 GHz quad-core Intel or AMD processor
8 GB RAM
2 GB VRAM DirectX 12 or Vulkan; 4 GB VRAM recommended
NVIDIA GeForce GTX 1060 with driver version 465.89 or later
AMD Radeon Pro 560 or higher with latest drivers
Intel HD 630 or higher with latest drivers
60 GB of free disk space
Visual Studio 2019


Why should the Linux version be higher?

**Comment by spham-amzn** [comment]
> 
> 
> @spham-amzn
> 
> Here are the windows specs:
> 
> 2.5 GHz quad-core Intel or AMD processor
> 8 GB RAM
> 2 GB VRAM DirectX 12 or Vulkan; 4 GB VRAM recommended
> NVIDIA GeForce GTX 1060 with driver version 465.89 or later
> AMD Radeon Pro 560 or higher with latest drivers
> Intel HD 630 or higher with latest drivers
> 60 GB of free disk space
> Visual Studio 2019
> 
> Why should the Linux version be higher?

No particular reason other than build performance to improve test iteration.
