### ISSUE TITLE
Expose PathView to Python

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#3311]
Hoping to let PathView exposed to python so that it can be used in python automated tests.

**Comment by lumberyard-employee-dm** [comment]
The PathView class itself isn't suitable for exposure to python.
Python has it's on pathlib API which is used for Path manipulation.
That maps more to the `AZ::IO::Path` class. So there more a need to map our [AZ::IO::Path](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/IO/Path/Path_fwd.h#L53) instance reflection to the [pathlib.PurePath](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath) instance

**Comment by Kadino** [comment]
Closing this issue as it appears the requested feature exists within Python. Feel free to re-open with more context on what functionality you are trying to achieve.
