### ISSUE TITLE
Qt - convert to use the 3rd party source system

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#3333]
We need to convert our Qt package to be built from source using the 3rd Party source system. There are several steps to accomplish this:

1. Migrate Qt submodule forks from internal repo to public. Need to decide where this will live. These are the current submodules that have their own forks with patches applied (Estimate: 1 week):
- qtbase - This is where most of the patches live and will need to continue
- qtimageformats - This one is needed for TGA support
- ~~qttools - Needed for some windeployqt fixes on Linux~~
    - Confirmed we no longer use any <PLATFORM>deployqt scripts, so don't need a custom fork of this submodule
- qtwebengine - Since we removed the welcome page that used QWebEngine and the other unused code, we might not need to build this anymore, so therefore might not need this custom fork anymore?
2. Create Qt package in https://github.com/o3de/3p-package-source, including migrating build.sh shell script to Python script (Estimate: 2 days)
3. Get building on Windows. This includes getting the prerequisites installed or linked (Estimate: 1 week)
- OpenSSL (This has already been converted to 3p, so should be a way to reference it somehow)
- ICU
- Jom
- Perl
4. Get building on Linux (Estimate: 3 days)
5. Get building on Mac (Estimate: 1 week)

**Comment by cgalvan** [comment]
Qt fork has been created here:  https://github.com/o3de/qt5/tree/5.15.1-az

And the submodules have all been updated so that their URLs can be resolved (in their source, they are all relative URLs which don't work in our case because we aren't going to be forking every submodule, only select ones we have modifications to).

**Comment by cgalvan** [comment]
Moved over to this branch on the fork instead:  https://github.com/o3de/qt5/tree/5.15.1-o3de

**Comment by cgalvan** [comment]
New fork of the qtimageformats submodule:

https://github.com/o3de/qtimageformats/tree/5.15.1-o3de
