### ISSUE TITLE
[Material Editor] Operations for layouts.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#3386]
**Describe the solution you'd like**
Add menuitems to support operations for layouts like Editor, such as View -> Layouts which has the following items.
* Save Layout
* Restore Default Layout

**Comment by cgalvan** [comment]
@alexmontAmazon This could be part of the initial phase of a QtViewPaneManager refactor/consolidation for re-use in tools

**Comment by gadams3** [comment]
The layout does save between sessions. There is already a restore default layout button. It should be trivial to add a save layout button.

**Comment by gadams3** [comment]
support for managing custom layouts has been added to the tools menu
