### ISSUE TITLE
[MacOS] Components from built Blast Gem are missing and can not be added to entity

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#3388]
**Describe the bug**
It has been observed that even after making sure the Blast gem and its dependency gems are built, _Blast Family_ and _Blast Family Mesh Data_ destruction components are missing from the Editor and can not be added to entities.

The issue occurs both on AutomatedTesting project and any newly created project.

This is contradictory to the behavior seen on a PC version of the Editor.

For further information please refer to the attached video file.

https://user-images.githubusercontent.com/86953456/130465351-607e3e74-6a1f-44b6-81f3-f6e94a015578.mov

**Prerequisites**
* Asset Processor and Editor has been built.
* Assets were processed in Asset Processor.

**To Reproduce**
1. Launch the Editor.
2. Create a new level.
3. Add a new entity to the level.
4. Select the entity and click _Add Component_ button in its Entity Inspector.
5. Search for _Blast Family_ or _Blast Family Mesh Data_ components.

**Expected behavior**
Destruction components are present and can be added to the entity.

**Desktop/Device (please complete the following information):**
 - Device: Mac 
 - OS: MacOS
 - Version: Big Sur 11.3.1
 - CPU: Intel Core i7 2,8 GHz
 - GPU: Radeon Pro 555
 - Memory: 16GB

**Comment by moraaar** [comment]
Blast gem is only supported on Windows. It is expected that Blast components are missing when using other platforms.

Closing issue.
