### ISSUE TITLE
[Atom] MaterialEditor - Let ShadowCatcher supports more light types and lights.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#3403]
**Describe the solution you'd like**
Currently, ShadowCatcher only supports Directional Light, and one Directional Light instance.
Suggest that:
* ShadowCatcher could support other light type, such as point/Spot/Capsule/Quad/Polygon.
* ShadowCatcher could support more light instances in scene.

**Comment by wintermute-motherbrain** [comment]
@Jackie9527 - This is in the material editor, correct?  You're not trying to use the ShadowCatcher material outside of the material editor are you?

**Comment by Jackie9527** [comment]
> @Jackie9527 - This is in the material editor, correct? You're not trying to use the ShadowCatcher material outside of the material editor are you?

Do you mean I should not use ShadowCatcher material outside material editor?
I try to use it in Editor, as a material type to an entity.

**Comment by gadams3** [comment]
This material type is only intended for use inside the material editor and similar tools viewports. After the linked PR is submitted, you should not be able to open or edit it in the material editor. This won't prevent you from assigning it though.
