### ISSUE TITLE
[Material Editor] Open material file by dragging it to viewport.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#3404]
**Describe the solution you'd like**
In Asset Browser, select one or material files and drag them to viewport, Material Editor can open them at once.
From Windows Explorer, select one or some material files and drag them to viewport, Material Editor can open them at once.

**Comment by monroegm** [comment]
Sending to graphics-audio as this seems like a feature request for the Material Editor tool

**Comment by gadams3** [comment]
This is now supported in the development branch
