### ISSUE TITLE
[Material Editor] Camera clip into the shader ball.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#3405]
**Describe the bug**
Preview the material with model like shader ball, when move and rotate the camera, sometimes the camera would clip into inside the shader ball.

**To Reproduce**
1. Open Editor.
2. Click Tools -> Material Editor.
3. Select a existed material or Create a new material, and select Shader Ball.
4. Move and rotate the camera.
5. See error, camera clip into the shader.

**Expected behavior**
The camera would move around the mesh, never clip into.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by wintermute-motherbrain** [comment]
@gadams3 you might want to sync with @santorac @jeremyong-az @Adi-Amazon

**Comment by gadams3** [comment]
@wintermute-motherbrain @santorac @Adi-Amazon @jeremyong-az @HogJonny-AMZN We originally prevented the camera from penetrating the bounds of the active model. We removed it by user and tech artist request to be able to get closer to models. We could revisit this by implementing ray intersection tests, adjusting distance as the camera moves around the model, relying on zooming and fov changes to get more detail.

**Comment by santorac** [comment]
IMO the sig should not accept this bug, close it as as-designed. The Material Editor is a dev tool, where it is normally expected that the user can move the camera wherever they like, including inside geometry. If we try and do something more elegant, we'll inevitably create knock-on bugs. I'd rather engineering time be spent elsewhere. Also, IIRC there is some effort to try and unify the camera code between the main level editor and the Material Editor, which would be more difficult if the Material Editor is doing some camera collision that the level editor will likely never want.

**Comment by gadams3** [comment]
Closing this has designed but can be resubmitted as a feature request
