### ISSUE TITLE
Clicking RMB on a slice component might cause the Editor to crash

### ISSUE THREAD

**Issue by LB-SzymonKempinski** [o3de/o3de#3410]
**Describe the bug**
When working on a slice, adding a component and using RMB on it before pushing the changes might cause the Editor to crash.

**To Reproduce**
1. Create or open any Level that uses Slices.
2. Go to 'Entity Outliner'.
3. Create or initialize a Slice.
4. Go to 'Entity Inspector'.
5. Add any Component.
6. Click RMB on the Component (might need more click attempts).
7. Observe as the crash occurs.

**Expected behavior**
No crashes occur and the Editor is stable.

**Video**

https://user-images.githubusercontent.com/88180223/130607000-8cd8475c-66c8-4bc3-9e9b-2c3515ca7a73.mp4

**Desktop/Device:**
-  Device: PC
- OS: Windows
- Version 10
- CPU AMD Ryzen 5 3600
- GPU Nvidia RTX 2060 Super
- Memory 16GB

**Additional context**
[error.zip](https://github.com/o3de/o3de/files/7038690/error.zip)
[Editor.log](https://github.com/o3de/o3de/files/7038688/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7038689/error.log)

**Comment by AMZN-daimini** [comment]
Slice system for level editing is being removed.
https://github.com/o3de/sig-content/issues/148
