### ISSUE TITLE
Lua has no way to spawn a prefab, but SC has a node for it

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#3431]
**Describe the bug**
Currently Lua has no way to spawn a prefab. However, there is a node available to do so in Script Canvas which uses `SpawnNodeable.h`

This functionality should also be exposed to Lua

**Comment by monroegm** [comment]
@ppinfel Converting to a feature request. The priority is still correct.

**Comment by srikappa-amzn** [comment]
The integration is now present in development branch. Here's the PR for your reference : https://github.com/o3de/o3de/pull/8440
