### ISSUE TITLE
BURTActor.fbx fails in Asset Processor

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#3444]
**Describe the bug**
It has been observed that BURTActor.fbx fails in Asset Processor. This issue occurs when the AtomTest project is added to the O3DE and built or just the .fbx file is copied to the AutomatedTesting project.

Please refer to attached screenshot and logs for more information.

**To Reproduce**
1. Get BURTActor.fbx from AtomTest project (https://github.com/o3de/o3de-atomtest).
2. Paste BURTActor.fbx into AutomatedTesting project.
3. Run O3DE.exe and launch AutomatedTesting project.

**Expected behavior**
BURTActor.fbx is processed by Asset Processor without issues.

**Screenshots**

![BURTActor_failed_in_AP](https://user-images.githubusercontent.com/86952318/130796623-5f58c39e-2bd0-4331-969e-5492e282b22b.jpg)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600 6-Core Processor
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

[BURTActor.fbx-1144981734-14431.log](https://github.com/o3de/o3de/files/7047191/BURTActor.fbx-1144981734-14431.log)
[BURTActor.fbx-BD8BF658-9485-4FE3-830E-8EC3A23C35F3_createJobs.log](https://github.com/o3de/o3de/files/7047192/BURTActor.fbx-BD8BF658-9485-4FE3-830E-8EC3A23C35F3_createJobs.log)

**Comment by jackalbe** [comment]
does the AtomTesting project have different assets than the engine? I noticed that "github.com/o3de/o3de/tree/development/AutomatedTesting/Assets" does not have "o3de/AutomatedTesting/Assets/BURTActor.fbx"
