### ISSUE TITLE
Add a context menu option to enter/exit Prefab editing mode

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#3452]
Note: This functionality should be mirrored in the Entity Outliner as well (ideally using the same code path if possible).

**Comment by rainbj** [comment]
Just a clarification this is to identify anything outside "esc" key. So for example. using the breadcrumb trail. Double clicking on a prefab in the outliner to drill in. Double clicking on an object in the viewport. We could also include a right click option inside the outliner and on the prefab to say close prefab or edit prefab. If I'm misunderstanding this ticker please let me know but these are the ones we have talked about as of today.

**Comment by hultonha** [comment]
Closed by https://github.com/o3de/o3de/pull/5230 (LYN-7536) - tagging @AMZN-daimini for visibility + confirmation.
