### ISSUE TITLE
When editing a Prefab, pressing Esc will move you up the hierarchy until the Prefab is no longer being edited

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#3453]
Exact design TBD - A design needs to be agreed for what ESC should do (should it move up the hierarchy one at a time or go to the upmost level)

Undo/Redo, Should this save changes
![image.png](https://images.zenhubusercontent.com/611303b8b6b16735839a5c78/ee449a7e-99dd-4de2-ab8c-b119db19fdb3)

At this time it is not clear how much of this system will be available (from Prefab/Editor team) - ideally we just plug into this but this task may be more involved if we need to implement more of this ourselves.

**Comment by yuyihsu** [comment]
This ticket should be critical. User needs an easier way to exit the editing mode. Please discuss with UX if the team disagrees with the priority.
