### ISSUE TITLE
As a user, I would like to be able to adjust the visible state of everything outside the current Prefab being edited

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#3455]
[Migrated from Jira LYN-5294]

The Editor needs to support the ability to display (at least one) type of visual feedback for editing a prefab (being inside Isolation Mode)

This ties in with #3447 and can be thought of as the first kind of visual indication the user is in this mode (e.g. Applying grayscale to objects not in the current selection).

We would like to support different sorts of visualization options in future (e.g. Hide all objects not in selection, make all objects in selection translucent etc... so this system should be designed with that in mind (don't hard-code to one type of visual style ideally)

Example way of switching view modes (note: only need one to begin with)
![image.png](https://images.zenhubusercontent.com/611303b8b6b16735839a5c78/500ad144-ef1c-44d1-a1e2-c9ee1f32c224)

Note: This task is 'connecting' existing functionality to the Prefab state.

**Comment by yuyihsu** [comment]
This is a dup of this ticket: https://github.com/o3de/o3de/issues/3597

**Comment by hultonha** [comment]
Issue is a dup, being tracked by https://github.com/o3de/o3de/issues/3458

https://github.com/o3de/o3de/pull/7638
https://github.com/o3de/o3de/pull/7678 
https://github.com/o3de/o3de/pull/7966
https://github.com/o3de/o3de/pull/7853
