### ISSUE TITLE
Stage 1 improvements to viewport editing functionality/feedback

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#3460]
1. Viewport UI for enable/disable grid snapping
2. Other customization/setting options
3. Iterate on Grid Snapping functionality in the new Viewport Interaction Model
4. Improved feedback

Vertex Snapping (interface to work with Mesh Component and White Box initially (**deferred**)

Time Estimate: 1 month

**Comment by hultonha** [comment]
Closing this issue to be replaced with more specific tasks in future - some functionality has been implemented (e.g. 1., 2. and 3. are done). Improved feedback is a wider topic and needs to be addressed more specifically on a case by case basis.
