### ISSUE TITLE
Support for custom shaders in gems

### ISSUE THREAD

**Issue by gavrmg** [o3de/o3de#3462]
Not exactly an issue, but more of a question. Are custom shaders supported in gems/projects? For example, if i wanted to have a custom mesh type which, in addition to static mesh data, would store texture indecies per vertex, then use a custom geometry shader to send all these indecies to pixel shader to use for texture blending. Is this kind of workflow supported, or is rendering pipeline fixed in this sense?

**Comment by AMZN-alexpete** [comment]
Gems, can define their own shaders.   In fact, the entire Atom renderer is comprised of many gems.  One simple example of a Gem that defines a simple shader and uses it is the [IMGUI ](https://github.com/o3de/o3de/tree/development/Gems/ImGui)and [IMGUIAtom ](https://github.com/o3de/o3de/tree/development/Gems/AtomLyIntegration/ImguiAtom)gems.  The [IMGUI gem](https://github.com/o3de/o3de/tree/development/Gems/ImGui) sets up the IMGUI thirdparty library and defines most of the business logic, and the [IMGUIAtom gem](https://github.com/o3de/o3de/tree/development/Gems/AtomLyIntegration/ImguiAtom) defines how to render it in Atom, [including providing a shader](https://github.com/o3de/o3de/tree/development/Gems/AtomLyIntegration/ImguiAtom/Assets/Shaders/ImGuiAtom).

**Comment by galibzon** [comment]
@gavrmg , yes. Gems can provide their custom shaders, materials and render passes.

The rendering pipeline is data driven & customizable.

A new API was introduced recently that allows for Gems to dynamically insert custom passes into the render pipeline:
