### ISSUE TITLE
AZ::TransformConfig.worldTransform property looks a lot like Set World Transform method, and is confusing

### ISSUE THREAD

**Issue by kinglawr** [o3de/o3de#3463]
SetWorldTransform has 2 different nodes in script canvas.  The 2nd "Set worldTransform" requires a TransformConfig, which I'm not sure is even used in script... I cannot construct one.

*Steps to Reproduce*:

1. Open script canvas and search for "Set world"

*Expected Result*:

1 Set World Transform nodes appears in the node palette 

*Actual Result*:

2 set world transform nodes appear... user's aren't sure which one to use!

[image2021-5-22_16-50-21.png](https://images.zenhubusercontent.com/6112e438ad96285a50ec2151/79f596ba-968a-43b8-b237-39eab957f1a1)

**Comment by lsemp3d** [comment]
These nodes are now properly categorized 
![image](https://user-images.githubusercontent.com/58790905/143307953-fd01610b-36e6-4c74-be09-dc57ed0d127f.png)
