### ISSUE TITLE
[UX Task] Create Early Design for Gem Creation Experience

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3491]
**Description-**
Create the early design for gem creation workflow, this includes the entry points on the catalog page and the engine page.

**Design reference**
<include the design link here>

**Comment by ParasiteSt** [comment]
Hey @yuyihsu is this still under investigation? I am going through old posts making sure these issues are being tracked, and not lost.

**Comment by yuyihsu** [comment]
This one has been done. The solution has been implemented on O3DE.

**Comment by yuyihsu** [comment]
Closing the ticket as the solution has been lmplemented as part of project manager.
