### ISSUE TITLE
Update the resolution / ratio dropdown 

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#3496]
[Migrated from JIRA LYN-4392]
We have discovered a couple issues with Ratio and resolution drop-down menu. This button currently lives under the viewport window (top, right corner).

![image](https://user-images.githubusercontent.com/75449675/131188981-be24cf37-7572-44f9-bfcb-900c8c77c846.png)

 * Currently the Game mode - play button has two options. In window experience or pop out experience.
 ** If game mode uses the pop-out window experience then this resolution menu doesn't matter and should fill the window based on your current resolution
 ** If the window is an in editor experience then this drop-down menu become important. The following step should be updated to fix this experience

1. Ratio menu items should be removed. There are no use cases where ratio on it's own make sense from the user I have spoken with. They should be combined into a single list.
2.  We should have a single drop-down menu. In this menu we will list out the most common resolutions We are suggesting the following

    1. Default - ( this will take up the entire perspective window and scale appropriately to the size of the editors viewport window)
    2.  2560x1440 (*16:9*) QHD
    3.  1920x1080  (*16:9*) FHD
    4.  1366x768 (*16:9*)HD
    5.  1280x720 (*16:9*) HD
    6.  1920x1200 (*16:10*) WUXGA
    7.  1680x1050 (*16:10*)WUXGA+
    8.  1440x900 (*16:10*) WXGA+
    9.  1280x800 (*16:10*)WXGA
    10.  1024x768 (*4:3*) XGA
    11.  800x600 (*4:3*) SVGA
    12.  640x480 (*4:3*) SVGA
    13.  Custom - Based on window drag behaviors.

1. All specific resolutions specified above should use black bars on top and bottom of the viewport (see attached [^011-Editor-Viewport-Resolution-Update-v1-0-LN.pdf] . This update might require an update from the Atom team (for visibility)
2.  If the resolution is larger than the space provided in the viewport we do not want to stretch the editors size. Customer feedback has told us this is a bad experience. We should leave the window as specified by the customer but fit the resolution within the space provided. If the customer wants "full screen" mode. Please see the attached ticket as this already is in the editor.
3.  If the user decides to re-dock this panel back into main editor the window _we should keep the resolution requested by the user_
4.  If the user drags on of the corners of the perspective window we should set the window back to default and then to custom. This way it fills the window and then they can make an adjustment to whichever resolution they would like.

 * [https://en.wikipedia.org/wiki/Computer_display_standard]  - More about standard resolutions.
 * [https://www.teamfortress.tv/11687/common-game-resolutions#9] - Common game resolutions.

 

Jonathan-  I believe the editor team will be able to make the adjustments to the window buttons and display the correct resolutions. However the black bars on top and side might be something we want to create a new ticket to track the details on. Thanks

**Comment by jjjoness** [comment]
The Jira is marked as closed - duplicate so I'll close this one.
