### ISSUE TITLE
A barebone python package/module of modules for UI controls

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#3501]
[Migrated from JIRA LYN-4090]
So users have working examples of developing O3DE GUI's in python and pyside.
 Understand how to develop python/pyside based tools and extensions fpr o3de.

**Comment by cgalvan** [comment]
Closing this as we now have a barebones gemplate for a python custom tool, that has been iterated on (last PR here):

https://github.com/o3de/o3de/pull/5100

And a full sample tool built off that gemplate which has been iterated on, here:

https://github.com/o3de/sample-code-gems/pull/4
