### ISSUE TITLE
Be able to launch the IDE (Integrated Development Enviroment) from O3DE

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#3502]
[Migrated from JIRA LYN-4089]
Confiugre IDE tool of choice as the python editor (preferences?)
From Python Scripts Panel or anywhere else we present python scripts, can launch my IDE

 

Feedback from RTE testing: [~gallowj]

**Comment by yuyihsu** [comment]
@HogJonny-AMZN can you provide more details and use cases to this ticket?
