### ISSUE TITLE
When a file is created in the Asset Editor, the browse edit should show the new file name automatically

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#3507]
[Migrated from JIRA LYN-3906]
As user, I'd like to see the "Browse Edit" UI component to capture the file I just created through the sub-tool I open from the button behind the "Browse Edit" in the text field automatically.

for example, user can trigger the Asset Editor from the Browse Edit UI component to create a new physics file, then when they close the sub-tool, the Browse Edit should capture the file name users just created.

*FOUND IN BUILD:* 8601ffa27b98e702efd4b6701654cdda16838be9

 

This bug was bulk-generated via a python script. It is based on feedback from a workflow walkthrough.

**Comment by sphrose** [comment]
Fixed by #6508 for certain asset types. Physics materials can no longer be created using the BrowseEdit control.
