### ISSUE TITLE
Improve the Gem shopping cart design and experience

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3520]
[Migrated from JIRA LYN-4408]
### *Problem description-*

When user selects the project template, and enters into the gem catalog, the shopping cart shows 0 at the moment. In the meantime, the "Selected gems" category on the left shows the number of gems that are selected. When user continue selecting more gems, the shopping cart would start tracking the selected number now. This workflow is confusing and defeat the original purpose to display the shopping cart design there.

 

### *Solution-* 

- The shopping cart should keep track of the selected gems from the beginning.
- The shopping cart panel needs to follow the current design.
-  The shopping cart panel should be open by default when users first enter into the gem catalog showing the list of selected gems in it.

**Comment by yuyihsu** [comment]
@Ulrick28 I think we've fixed this issue already. do you want to close this ticket?

**Comment by svitlani** [comment]
This issue was addressed in LYN-4408 and LYN-7745, closing this ticket.
