### ISSUE TITLE
Create the ability for user to go directly into the editor if they have an existing project

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3522]
[Migrated from JIRA LYN-4436]
Design options-
 # make the desktop icon to open the editor instead of PM, but make it when there's 0 project created, the desktop icon should open PM instead of editor.
 # Add Project menu item to ‘Create Editor desktop shortcut’ for the selected project. Add default checkbox option to ‘Create an Editor desktop shortcut’ when creating a project 

After discussing with [~joebry], we will go with the direction to add the "O3DE Editor" desktop icon right after installer.
Joe B to convert to a story instead of a bug.

**Comment by svitlani** [comment]
The solution to this problem has been implemented by @AMZN-alexpete and is tracked in JIRA LYN-4436, closing this issue.
