### ISSUE TITLE
Prism Legal: System to generate a new tags file for each release

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3523]
[Migrated from JIRA LYN-4411]
Legal has requested a system be created to generate new tags files for each release. This will need to be accomplished in conjunction with [~changml] (Pipelines). This is not a blocker for launch as we can hand create the files if needed.

**Comment by amznestebanpapp** [comment]
@amzn-changml this was already done right?

**Comment by svitlani** [comment]
@amzn-changml can you please confirm this work is done so we can close the issue appropriately? Thank you!

**Comment by amzn-changml** [comment]
Yes, this has been done as of https://github.com/o3de/o3de/pull/5214. I'll close this issue.
