### ISSUE TITLE
Add visual indicator to show user can open project from the tile

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3524]
[Migrated from JIRA LYN-4450]
Show play icon and ‘Launch Editor’ text + icon when hovering over the Project previews on the Project’s page so users know they’re buttons and what they do

**Comment by yuyihsu** [comment]
We should already fixed this issue. when user mouse over the tile, a "launch" button shows up.

**Comment by robhaco** [comment]
"Open Editor" button appears when hovering over the project card, which I believe satisfies this request.  Closing the issue.
