### ISSUE TITLE
User should have a way to view gems source by the O3DE foundation.

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3543]
[Migrated from JIRA LYN-5532]
### Description-

As a user, I want to see all gems source by the O3DE foundation.

Acceptance Criteria:
- Contributors have a mechanism to tag their O3DE gems as sourced by the O3DE foundation
- O3DE users have the ability to display all gems that are sourced by the O3DE foundation via the gem catalog

**Comment by AMZN-alexpete** [comment]
@yuyihsu  I believe this can be closed based on the functionality we have to show Open 3D Foundation gems:
![image](https://user-images.githubusercontent.com/26804013/154750354-31c11255-ce53-4593-b8e7-191aa6f0e133.png)

**Comment by forhalle** [comment]
@yuyihsu Verified it has been addressed in the builld.
