### ISSUE TITLE
Enabling Gem checkmarks and text issue

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3552]
[Migrated from JIRA LYN-4339]
|Project|LYN|
|Labels|RTE, WF6, AWSI, UX|
|Build|commit 1436ee0bd93fa57cd92e2fad99a032a33a17c210|
|Default Assignee Alias|Rainbj|
|Milestone|V1|
|Linked Issues|LYN-3515|
|Workflow|WF6|

During the rev the engine test for AWSI WF6 test with [Alex Peterson|https://jira.agscollab.com/secure/ViewProfile.jspa?name=alexpete] two issues were noticed with Prism.

[~rppotter] for visibility. 
 * If a user decides to enable a gem that has dependent gems, clicking the toggle switch doesn't automatically turn on the dependent Gems check mark too. It notes the details of the dependent Gems but the automatic checks are not being reflected.
 ** This is the same for checking the Gems on and then off again.
 ** Also consider turning on a child gem and turning off the parent gem.  What that workflow should look like
 * If a user already has a Gem installed on his system and has already built the word inside the checkbox if the user turns it off says "get". This was confusing because it was already on his system and he toggled it off for a minute and now it appears it needs to be re-downloaded. Consider changing the terminology once downloaded [~bhanujs] - Please consider this for your design docs as well.

[~yuyihsu] please forward to respective team owners on Prism.

**Comment by robhaco** [comment]
The most recent Project Manager no longer has these issues.  Closing.
