### ISSUE TITLE
[Feature Request] Right click lower right option to open project file explorer location 

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#3553]
I think it will be nice if a user can right click the `GameFolder: <project path>` for an option to open the file explorer at the project's location

![image](https://user-images.githubusercontent.com/48143120/130871719-8306a54f-6615-4b1c-9afc-0eb8aa3c4930.png)

**Comment by rainbj** [comment]
![footer](https://user-images.githubusercontent.com/82551958/131423346-def43efb-7d65-4d5a-805f-4e97ed811987.jpg)

Hey @cgalvan  not sure if you want to open another ticket for this or not but we did talk about shortening the details in the footer to reduce the noise  of showing the full URL. Maybe just a clickable link that take you there would be simpler. Let me know your thoughts. @yuyihsu for comments
