### ISSUE TITLE
Add a button on the viewport bar to display IMGUI.

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#3564]
[Migrated from JIRA LYN-3852]
There's a lot of useful IMGUI tools that are inobvious because its all hidden behind the HOME key. We should also make sure the UX and default settings of the IMGui is good.

This bug was bulk-generated via a python script. It is based on feedback from a workflow walkthrough.

**Comment by amzn-leenguy** [comment]
This has task has been completed by @jjjoness
