### ISSUE TITLE
Build Project button does not show up on newly created projects in the Project Manager

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#3575]
**Describe the bug**
It has been noticed, that the Build button does not appear on newly created projects in the Project Manager. It should be noted, that after running and failing a build, the button appears as shown on the attached BuildPromptOnFail.PNG image below. 

**To Reproduce**
1. Open the O3DE Project Manager.
2. Go to New Project > Create New Project.
3. Leave Project name and Project Location as default, select the Standard Project Template, and click Create Project.
4. Click OK on the "Project Should be rebuilt." prompt.

**Expected behavior**
The Build button should appear on the new project's tile.

**Video and screenshot**

https://user-images.githubusercontent.com/86952082/130927001-8e9db802-aec0-40f8-99d5-4b6385ff885d.mp4

BuildPromptOnFail.PNG
![BuildPromptOnFail](https://user-images.githubusercontent.com/86952082/130927041-01682951-a56e-42c7-a240-75bc85f3a923.png)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by AMZN-Phil** [comment]
Fix for this has already been merged - #5592

**Comment by LB-ArturSiewniak** [comment]
Issue verified as fixed on Stabilization_2110 (ba32937) build.
