### ISSUE TITLE
Building new projects fails on configuration

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#3576]
**Describe the bug**
It has been noticed, that new projects cannot finish building due to a failure during project configuration. Due to the issue https://github.com/o3de/o3de/issues/3575, building new projects must be selected from the hamburger button, as the Build button does not show up on newly created projects. The .log files generated after the configuration failure have been attached below - CMakeOutput.log and CMakeProjectBuildError.log respectively.

**To Reproduce**
1. Open the O3DE Project Manager.
2. Go to New Project > Create New Project.
3. Leave Project name and Project Location as default, select the Standard Project Template, and click Create Project.
4. Click OK on the "Project Should be rebuilt." prompt.
5. Click the hamburger button under the newly created project's tile and select Build from the list.

**Expected behavior**
The project builds successfully.

**Video and .log files**

https://user-images.githubusercontent.com/86952082/130928718-7d79dc9e-aa59-4d09-9f88-0deb687f263b.mp4

[CMakeOutput.log](https://github.com/o3de/o3de/files/7053600/CMakeOutput.log)
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/7053601/CMakeProjectBuildError.log)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by LB-ArturSiewniak** [comment]
It should be noted that attempting to build premade projects (e.g. AutomatedTesting) is also impossible as of Development (b065837).

**Comment by LB-ArturSiewniak** [comment]
Hi, no it does not seem to be happening on recent builds, verified today on Development (f31b47f).
