### ISSUE TITLE
The Editor allows to center the camera on a selected Layer

### ISSUE THREAD

**Issue by LB-PatrykKrajewski** [o3de/o3de#3577]
**Describe the bug**
It is possible to center camera view on a selected Layer. The Issue can be reproduced by shortcut under the [Z] button and by View > Center on Selection option. Additionally, when a Layer contains Entities, the camera does not center on them when using the center option on a parent Layer. This issue occurs only when prefab system is disabled as there is no way of creating layers while it is enabled.

**To Reproduce**
1. Run the Editor with Slices supported.
2. Create or open any Level.
3. Create a Layer.
4. Select the Layer in the 'Entity Outliner'.
5. Click the View > Center on Selected option or use the [Z] key shortcut.

**Expected behavior**
The Center on Selected option should not center the camera on a Layer.

**Video**

https://user-images.githubusercontent.com/88180143/130936764-38bb12b7-83e4-4d53-b5db-51822f5fd227.mp4

https://user-images.githubusercontent.com/88180143/130936770-f4e0ffd4-a8e1-4450-8108-11235b950007.mp4

**Desktop/Device**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600X
 - GPU AMD  RX 5700 XT
 - Memory 16 GB

**Comment by hultonha** [comment]
I am closing this issue as Slices are no longer a supported workflow
