### ISSUE TITLE
Adding Terrain World and Terrain World Debugger components drops FPS from 60 to 15-20

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#3592]
**Describe the bug**
FPS drops from stable 60 to 15-20 when Terrain World and Terrain World Debugger components are both added to the Level.prefab entity.

**To Reproduce**
1. Enable the Terrain Gem.
2. Create a new level.
3. Select the level.prefab.
4. Open the component dropdown.
5. Select Terrain World and Terrain World Debugger components.

**Expected behavior**
No significant FPS drop should be observed.

**Video**

https://user-images.githubusercontent.com/86952591/130954693-95624c09-fb18-4aba-bc44-d4f30efa9ae6.mp4

**Desktop/Devices:**
Device: PC
- OS: Windows
- Version 10
- CPU AMD Ryzen 5 3600
- GPU NVIDIA RTX 2060 SUPER
- Memory 16GB

Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600X 6-Core Processor, 3800 MHz, 6 Core(s), 12 Logical Processor(s)
- GPU: AMD Radeon RX 5700 XT
- Memory: 16GB

Device: PC
- OS: Windows
- Version: 10
- CPU: i5-9600k
- GPU: RTX 2060
- Memory: 16GB

**Comment by mbalfour-amzn** [comment]
This has been fixed in the past couple of months.
