### ISSUE TITLE
As a user, I would like to get better visual feedback for what is in my current selection

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#3594]
[Migrated from Jira LYN-5284]
Right now the visual feedback we have for what entity is in your current selection is poor.

We would like to investigate various options for improving this feedback.

The first option would be an 'outline' effect to indicate what mesh is currently selected (how might be achieve this with an effect in Atom?)

The second option (which will help with Prefab/Isolation mode) is greying out all entities not currently in your selection (or potentially not drawing them at all, or maybe even performing a DOF effect?)

This task will require some R&D and investigation but could dramatically improve the experience of using the editor day to day and be a big, obvious, visible improvement to the editor viewport/tools

![image.png](https://images.zenhubusercontent.com/611303b8b6b16735839a5c78/f34fb254-d759-4196-bc93-ccef9b3461b1)

**Comment by hultonha** [comment]
Initial work complete, moving this issue to done. See PRs for related work.

https://github.com/o3de/o3de/pull/7638
https://github.com/o3de/o3de/pull/7678 
https://github.com/o3de/o3de/pull/7966
https://github.com/o3de/o3de/pull/7853
