### ISSUE TITLE
Implement ability to enable/disable effect at edit time

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#3597]
[Migrated from LYN-5363]

Once the bare-bones effect is implemented (potentially in prototype form) there needs to be a way to enable/disable the effect at edit time given a particular event (coming from an arbitrary system but for this example may be Prefabs).

![image.png](https://images.zenhubusercontent.com/611303b8b6b16735839a5c78/f033ffb3-cc46-4cfa-8a69-ad5def25b426)

**Comment by yuyihsu** [comment]
For GA, we only need one focus mode. so the dropdown can only have two options: Normal mode, and Black and white (for example). when user enter into the editing mode, the "black and white" mode will be selected by default.

**Comment by amzn-leenguy** [comment]
Just to note: @AMZN-Liv , @hultonha mentioned that: "This is a dev task just to ensure we can apply one or more of these effects at edit them (by using the Atom API). The exact functionality of the UX (how to enable/disable) is separate but related."

Should we create a separate ticket to cater to that task?

**Comment by hultonha** [comment]
@amzn-leenguy As discussed this UX portion is tracked by this ticket - https://github.com/o3de/o3de/issues/3638 (now part of the same Epic https://github.com/o3de/o3de/issues/3458 🙂)

**Comment by rainbj** [comment]
Please keep me looped into any updates on this ticket. I want to make sure it matches all the use cases need for prefabs. Thanks!

**Comment by hultonha** [comment]
This ticket is subsumed by https://github.com/o3de/o3de/issues/3458

See related work PRs for more context

https://github.com/o3de/o3de/pull/7638
https://github.com/o3de/o3de/pull/7678 
https://github.com/o3de/o3de/pull/7966
https://github.com/o3de/o3de/pull/7853
