### ISSUE TITLE
Discuss Atom support for visual effects

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#3598]
The viewport team should discuss with the Atom team how to best use Atom capabilities to add visual effects for selecting prefabs and working in component mode to the viewport. This task is to track that conversation and notes.

**Comment by yuyihsu** [comment]
We only need focus mode in the GA release. Here's the design reference- 
![Screen 1 Copy 39](https://user-images.githubusercontent.com/75449675/131407056-0d4c7b6d-7bc6-4908-af11-c4a9caacadfc.png)

**Comment by hultonha** [comment]
This task is complete (discussion/design has happened), see following PRs for related work

https://github.com/o3de/o3de/pull/7638
https://github.com/o3de/o3de/pull/7678 
https://github.com/o3de/o3de/pull/7966
https://github.com/o3de/o3de/pull/7853
