### ISSUE TITLE
Improve component mode visual feedback

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#3599]
**Summary**
When entering Component Mode the feedback to let you know what you can and can't edit (in the viewport) is not sufficient. We need a way of informing the user they are only editing on Component. The Editor UX does a reasonable job of this now, but the viewport feedback is not clear. We need to investigate ways to improve this to reduce confusion.

As a user I want it to be obvious what Components I can and can't edit in Component Mode.

![image.png](https://images.zenhubusercontent.com/611303b8b6b16735839a5c78/90ca906c-7784-48f1-b2e7-545024cd95a7)

![image.png](https://images.zenhubusercontent.com/611303b8b6b16735839a5c78/ee57b889-ed4e-4023-aeb9-c0963d1f488a)

**Comment by yuyihsu** [comment]
Today we have two use cases for the blue border, one for the component editing mode, the other one is for prefab editing. we need to unify the two use cases and show the design solution as one. @amzn-leenguy will look into the solution and attach the proposal.

**Comment by hultonha** [comment]
@yuyihsu I believe the blue border is going to be replaced by the breadcrumb hierarchy - when it comes to other viewport scene (3D) feedback the plan is to piggyback on the work done for Focus mode to achieve the same effect but for a smaller subset of entities/components. I believe this issue should really be grouped under a future Epic as it encompasses quite a lot of work. We can sort this out in more detail once Focus Mode takes shape. Thanks!

**Comment by hultonha** [comment]
@yuyihsu @rainbj I wanted to check what the current state of this ticket is. From what I can gather we're not going to add any more visual feedback for Component Mode at this time so I'm wondering if we should close this issue and reopen it or a new one if we want to get back to it. Let me know your thoughts. Thanks!

**Comment by rainbj** [comment]
You are correct. This ticket was in the beginning when we were splitting out the use case of viewport and prefab. Everything described in this ticket appears to be fixed and can be closed. Good catch. Thanks!

**Comment by hultonha** [comment]
That's great to hear, thanks for confirming @rainbj, I'll close now 🙂
