### ISSUE TITLE
Investigate rotation issue for entities when duplicating in O3DE

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#3601]
@HogJonny-AMZN identified a bug that occurs when duplicating an Entity in the new Viewport Interaction Model in O3DE.

When duplicating an Entity, the rotation of the duplicated/cloned Entity will be wildly different to that of the Entity its duplicating.

It's possible that changes from the Math Strike Team work (decomposed transform, new math APIs) caused a break in EditorTransformComponentSelection which handles all of the new viewport functionality.

Found by: Ad-hoc test
Found In: Branch

**Comment by yuyihsu** [comment]
All duplicated entities should be shown as the same orientation in the original entities. Any new interactions please contact UI-UX sig.
