### ISSUE TITLE
Revisit auto-generated material file names

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#3614]
[Migrated from JIRA LYN-4261]
sceneprefix_materialnode_reallylonghash is a really long name, we understand the value (like avoiding collisions) but could this be improved in regard to streamlining the user experience?

**Comment by HogJonny-AMZN** [comment]
@yuyihsu @gadams3 @amzn-tommy I don't think we are going to really find a better decision, what we have avoids many edge cases and collisions and the only real draw back is the long name on the 'dcc default' materials
