### ISSUE TITLE
Building mac using the Release configuration fails

### ISSUE THREAD

**Issue by cmoroch** [o3de/o3de#3619]
**Describe the bug**
Currently testing https://github.com/o3de/o3de/issues/3192 and building Release results in a failure. See Steps below

**To Reproduce**
1. Generate the project: cmake -B <build_dir> -S . -G Xcode -DLY_3RDPARTY_PATH=$LY_3RDPARTY_PATH
2. Build Release: cmake --build <build_dir> --target install --config <config>
3. --> Notice that the build fails:
The following build commands failed:
	Ld /Users/<user>/github/o3de/build/mac/bin/release/libEditorLib.dylib normal
(1 failure)

**Expected behavior**
The build succeeds. There were no issues building Profile or Debug 

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: Mac
 - OS: mac OS
 - Version 11.5.2 (20G95)

**Additional context**

**Comment by byrcolin** [comment]
Old. No longer an issue, it builds.
