### ISSUE TITLE
[Bug Report] Project manager UI tabs gets unintended 'highlight' effect after build project confirmation popup

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#3630]
**Describe the bug**
Project manager UI tabs gets unintended 'highlight' effect after build project confirmation popup

**To Reproduce**
1. Open Project Manager
2. Click on the three strip dropdown menu icon and press `Build`
3. `Ready to build "ProjectName"?`. Click on `Yes`.

***

Highlight when `Projects` tab is selected:
![image](https://user-images.githubusercontent.com/48143120/131065104-8350bf14-ba7d-46bb-952f-33735db4c9b6.png)

***

Highlight when `Engine` tab is selected
![image](https://user-images.githubusercontent.com/48143120/131065120-b423bd95-b216-449c-9e3f-a8339958285f.png)

***

**Expected behavior**
![image](https://user-images.githubusercontent.com/48143120/131065266-a15dd365-eaa1-46b3-b50b-a9534891c359.png)

***

**Expected behavior**
![image](https://user-images.githubusercontent.com/48143120/131065302-0223597b-87cf-4dd2-b4fa-ca7cc7489ced.png)

***

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - CPU: Intel I9-9900k
 - GPU: NVidia RTX 2080
 - Memory: 64GB

**Additional context**
* On latest development branch
* Using "Source engine" setup
* It seems to be fixed by clicking on other UI elements such as the `New Project...` dropdown menu

**Comment by AMZN-nggieber** [comment]
Hmmm I couldn't actually repro this issue but I did fix the issue where the Projects tab is is "highlighted" when opening the Project Manager
