### ISSUE TITLE
[Bug Report] "[Error](CryLegacy) - Not restoring the editor viewport camera is currently unsupported"

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#3632]
**Describe the bug**
When `Restore Viewport Camera on Game Mode Exit` setting is OFF. The camera is still restored to the position before entering game mode, along with an error message saying:
![image](https://user-images.githubusercontent.com/48143120/131076302-5a1b6398-7cfd-45af-90bb-4a1ae1fd2bd7.png)

**To Reproduce**
1. Create a new default level
2. Change editor settings in `Edit`->`Editor Settings`->`Global Preferences`->`Restore Viewport Camera on Game Mode Exit = OFF`
3. Play the game and move the camera somewhere else, then exit the game
4. See error: We are back at the original camera position despite having the restore option off

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - CPU: Intel I9-9900k
 - GPU: NVidia RTX 2080
 - Memory: 64GB

**Additional context**
* Development branch
* Source engine setup

**Comment by hultonha** [comment]
@AMZN-Igarri I believe this is related to what you're working on now correct? Could you give an update here on the recent changes and what's in the pipe? Thanks!

**Comment by AMZN-Igarri** [comment]
@hultonha yes I am currently working on it, so far it should be throwing a warning instead of an error until it gets implemented.
https://github.com/o3de/o3de/pull/4343

**Comment by hultonha** [comment]
Okay perfect thanks @AMZN-Igarri :+1:

**Comment by instoneks2018** [comment]
Only the severity of the error alarm is modified from `Error` to `Warning`, however, the actual function is still not supported in the latest version,it would be better if it works soon.

**Comment by hultonha** [comment]
You are 100% right @instoneks2018, this was just a temporary change. We have a plan to address a number of camera persistence issues in the Editor with an RFC by @AMZN-Igarri that will be published soon (might be beginning of next year but the plans are well underway). It will address a lot of these problems and give a way to better store arbitrary camera positions.
