### ISSUE TITLE
DEV TASK: Creating the MVP version of Camera Controls to the top of the Viewport

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#3635]
[Migrated from JIRA LYN-3051]
*Background:*

This task is to create the MVP version of the camera controller UX. The ideal task for this ticket is https://github.com/o3de/o3de/issues/3639.

 

*Description:*

The MVP involves moving the camera controller options to a dropdown icon that sits top right of the viewport. An image is attached below of a mock up. The controls in the dropdown are only place holder. UX needs to finalize this dropdown for this ticket to be opened.

 

Details for the controls in the dropdown: 

We need to Allow users to adjust their camera controls (IA) directly inside the viewport.

Controls include:
 * Jump to destination
 ** Save point
 * Camera Speed (unique use case)
 * Camera Collision (unique use case)
 * Create camera from this view
 * Orthographic Projection
 * Switch to different camera views/entities
 * FOV controls (originally on the perspective window)

This requirement is for collecting the camera controls together in the same menu system for user to easily access. All the functions above already exist in the current engine, except "Orthographic Projection"

Another issue that was reported by ([~dmcdiar]), which should also be addressed in the improved design.

 

*Acceptance Criteria:* 

Users can control their camera smoothly and easily via the dropdown by clicking on the camera icon button top right of the viewport.

UX will confirm with [~hultonha] on the final controls we should present in this dropdown panel.

**Comment by shawstar** [comment]
Adding more ideas for Acceptance Criteria:

Camera bookmark will also save the current Camera Target Matrix, so when returning you will have the same camera point of interest to rotate, zoom around.
Camera FOV saved
Camera Near and Far Clips saved.

**Comment by hultonha** [comment]
Thanks for the updates @shawstar 👍 We'll factor these into the design as it develops (we'll link to the RFC for the feature too when it materializes, any further suggestions can be added there).

**Comment by rainbj** [comment]
@hultonha can you can follow up with what the decision points were on this ticket. Seems like part has already gone out last year and some is still pending. Should we cut new tickets and close what is here.

**Comment by hultonha** [comment]
This issue will be covered by an upcoming RFC by @AMZN-Igarri, more details will follow there, I'll let @AMZN-Igarri update this ticket once the RFC is posted.

**Comment by AMZN-Igarri** [comment]
RFC just posted: https://github.com/o3de/sig-content/issues/38

**Comment by hultonha** [comment]
This issue will be covered by this initial work (in progress here - https://github.com/o3de/o3de/pull/7855). Additional issues will be created for more specific functionality if required.
