### ISSUE TITLE
Breadcrumb hierarchy and navigation

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#3637]
[Migrated from JIRA LYN-1102]
Show hierarchy information and provide navigation for prefabs/editing modes.

Allows users to understand context of how deep they are in their files.

**Comment by yuyihsu** [comment]
We UX team suggest to move this to Critical, as it's important feature for prefab. Users need to know what they are editing, and a way to get out of the prefab editing.

**Comment by hultonha** [comment]
Understood @yuyihsu, this is something that will be cross-cutting with the Editor team. We likely should involve @AMZN-daimini in any planning for this work as this is going to be closely related to the Outliner as well as the viewport border and inside the viewport itself (tagging @jonawals for visibility too).

**Comment by hultonha** [comment]
Assigned this to you @AMZN-daimini as I know you're in the middle of this right now, we can reference this in the future PRs (feel free to close if you think it's already complete)

**Comment by hultonha** [comment]
Hey @AMZN-daimini, was just wondering is this now complete? Thanks!

**Comment by AMZN-daimini** [comment]
Hey, I think v1 is complete. We have additional action items but they were moved to v2.

**Comment by rainbj** [comment]
@AMZN-daimini  will you tag us in the new ticket created after this one has been closed.

**Comment by hultonha** [comment]
This issue is complete, if required a separate issue for updated look/design can be added
