### ISSUE TITLE
Visual presentation of controls for editing

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#3638]
[Migrated from JIRA LYN-1094]

When users are in the editing mode, they should be able to configure the visual presentation of the scene to make the selected object highlighted on the screen. This will help users to focus on the selected object.

Some controls to consider:
 * Color differentiation for Hierarchy (SketchUp reference)
 * Transparency of the background objects (Isolation Mode)

When I'm editing a prefab, which level of the prefab am I editing.
When I'm editing multiple entities, which entities am I editing.

Note: This issue is specifically for the UX to pick what _kind_ of visual feedback you would like, __not__ the visuals themselves. This work is tracked by the Epic - https://github.com/o3de/o3de/issues/3458.

**Comment by yuyihsu** [comment]
Related to 3596 (https://github.com/o3de/o3de/issues/3596)

**Comment by yuyihsu** [comment]
We need to review this ticket with @hultonha and @AMZN-Liv and @amzn-leenguy  to break this ticket down.

**Comment by amzn-leenguy** [comment]
I reviewed this ticket with @hultonha this morning, and we decided to move it to the epic https://github.com/o3de/o3de/issues/3458 . #3597 is actually very similar to this ticket, but this ticket is mostly about allocating time to brainstorm what other controls we need to do for visual presentation. 

We will keep this ticket open for the future to remind us to do that brainstorm as a team, but for now #3597 is the focus.

**Comment by hultonha** [comment]
This issue is no longer relevant and will be closed
