### ISSUE TITLE
UX - Add persistent pivot for entity selection

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#3640]
[Migrated from JIRA LYN-4218, LYN-2299]
Have a mechanism to store the per-entity pivot offset from default pivot position.

Question:  What about when multiple entities are selected.  Do we want/need to store this information?

**Comment by yuyihsu** [comment]
@rainbj , please provide related design proposal for this ticket.

**Comment by hultonha** [comment]
This issue is no longer relevant and will be closed
