### ISSUE TITLE
Failing to open project in editor

### ISSUE THREAD

**Issue by trsh** [o3de/o3de#3645]
**PLS READ MY LAST COMMENT https://github.com/o3de/o3de/issues/3645#issuecomment-907583275**

**Describe the bug**
Failing to open project in editor

**To Reproduce**
1.Fallow this tutorial https://o3de.org/docs/welcome-guide/setup/setup-from-github/ with optional step `cmake --build build/windows_vs2019 --target Editor --config profile -- /m`
2. Open `o3de.exe` from `C:\Engines\o3de\o3de\build\windows_vs2019\bin\profile`
3. When opening `o3de.exe` I get this in log:
```
~~1630076256337~~1~~00000000000025D8~~none~~/---------------------------------------------------------------------------\
~~1630076256337~~1~~00000000000025D8~~none~~| ------------ AzFramework File Logging New Run----------------------------- |
~~1630076256337~~1~~00000000000025D8~~none~~\---------------------------------------------------------------------------/

~~1630076256337~~1~~00000000000025D8~~python~~Py_GetVersion=3.7.10 (tags/v3.7.10:9b2dd1f, Feb 18 2021, 12:57:19) [MSC v.1916 64 bit (AMD64)] 
~~1630076256338~~1~~00000000000025D8~~python~~Py_GetPath=C:\Engines\o3de\o3de\build\windows_vs2019\bin\profile\python37.zip;C:\Engines\o3de\o3de\python\runtime\python-3.7.10-rev1-windows\python\DLLs;C:\Engines\o3de\o3de\python\runtime\python-3.7.10-rev1-windows\python\lib;C:\Engines\o3de\o3de\build\windows_vs2019\bin\profile 
~~1630076256338~~1~~00000000000025D8~~python~~Py_GetExecPrefix=C:\Engines\o3de\o3de\python\runtime\python-3.7.10-rev1-windows\python 
~~1630076256338~~1~~00000000000025D8~~python~~Py_GetProgramFullPath=C:\Engines\o3de\o3de\build\windows_vs2019\bin\profile\o3de.exe 
~~1630076256356~~1~~00000000000025D8~~Python~~RedirectOutput installed
~~1630076256427~~2~~00000000000025D8~~PythonBindings~~Python exception TypeError: string indices must be integers
~~1630076256430~~4~~00000000000025D8~~*ASSERT*~~Registration of this engine failed!
~~1630076256590~~1~~00000000000025D8~~System~~C:\Engines\o3de\o3de\Code\Tools\ProjectManager\Source\PythonBindings.cpp (230) : O3DE::ProjectManager::PythonBindings::PythonBindings
~~1630076256590~~1~~00000000000025D8~~System~~C:\Engines\o3de\o3de\Code\Tools\ProjectManager\Source\Application.cpp (70) : O3DE::ProjectManager::Application::Init
~~1630076256590~~1~~00000000000025D8~~System~~C:\Engines\o3de\o3de\Code\Tools\ProjectManager\Source\main.cpp (20) : main
~~1630076256590~~1~~00000000000025D8~~System~~C:\qt_build\Lumberyard3rdPartyQt\qtbase\src\winmain\qtmain_win.cpp (97) : WinMain
~~1630076256590~~1~~00000000000025D8~~System~~D:\a01\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288) : __scrt_common_main_seh
~~1630076256590~~1~~00000000000025D8~~System~~00007FF91AD27034 (KERNEL32) : BaseThreadInitThunk
~~1630076256590~~1~~00000000000025D8~~System~~00007FF91C7E2651 (ntdll) : RtlUserThreadStart
```
4. Ignore and fallow this tutorial this https://o3de.org/docs/welcome-guide/create/creating-projects-using-project-manager/
5. Then when try to open a created project, nothing happens. Its shows "Opening editor.." and then nothing. No errors in Log.

**Expected behavior**
No python biding errors and Editor should open for the project.

**Screenshots**
![2021-08-27_173658](https://user-images.githubusercontent.com/3727523/131150013-28af9197-8e34-49e8-8ae3-f021cc0bcd99.png)

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz, 3696 Mhz, 2 Core(s), 4 Logical Processor(s)]
 - GPU [GTX 750 Ti]
 - Memory [8GB]

**Comment by trsh** [comment]
Summary from yesterdays hacking of this problem:

1) By default Editor runs on dx12 and my GPU doesn't support some stuff there, so it crashes silently (what is bad). At least I think so.

2) Switching to `-rhi=vulkan` will open the Editor, IF all required Gems are enabled and project is Rebuild. By default the required Gems appear disabled in Manager and are not somhave marked as mandatory.

3) When that all is done Editor opens, but some problems with shader assets

```
C:/Engines/o3de/o3de/Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/BlendColorGradingLuts.shadervariantlist
8/27/2021 9:41 PM | ERROR | >    asset [D:\Projects\o3de\MCTest\Cache\pc] from shader source C:\Engines\o3de\o3de\Gems\Atom\Feature\Common\Assets\Shaders\PostProcessing\BlendColorGradingLuts.shader and subId 3 doesn't exist from AssetBuilder
```

4) Deleting Cache folder and re-opening editor fixed it 🤷 

5) Console is full of these

``
[Error] (StreamingImage) - AsyncUploadQueue::QueueUpload expects ImageHeight '8' to be bigger than or equal to the image's RowCount '2'.
[Error] (StreamingImage) - AsyncUploadQueue::QueueUpload expects ImageHeight '4' to be bigger than or equal to the image's RowCount '1'.
[Error] (StreamingImage) - AsyncUploadQueue::QueueUpload expects ImageHeight '512' to be bigger than or equal to the image's RowCount '128'.
```

End :)

**Comment by trsh** [comment]
> @trsh It seems like you have solved your issue. The remaining issues seems to do with the cache saving bad settings. Please make a new bug with just remaining issue

Not really. 

1. By default Editor runs on dx12 and my GPU doesn't support some stuff there, **so it crashes silently (what is bad)**. At least I think so. (this is an issue)

2. Switching to -rhi=vulkan will open the Editor, IF all required Gems are enabled and project is Rebuild. **By default the required Gems appear disabled in Manager and are not somhave marked as mandatory**. (this is an issue)

And then the one you mentioned.

**Comment by trsh** [comment]
I am lacking time and resources for such thing. This should be done by o3de core team.

**Comment by Nodoubvt** [comment]
same problem

**Comment by cad1994** [comment]
Same problem, editor never opening!
