### ISSUE TITLE
[Mac] AssetProcessor and Editor fail to open on mac for Profile and Debug Builds

### ISSUE THREAD

**Issue by cmoroch** [o3de/o3de#3658]
**Describe the bug**
AP and Editor fail to open, blocking testing for https://github.com/o3de/o3de/issues/3192

**To Reproduce**
1. Generate the project: cmake -B <build_dir> -S . -G Xcode -DLY_3RDPARTY_PATH=$LY_3RDPARTY_PATH
2. Build: cmake --build <build_dir> --target install --config <config>
3. From the build directory, attempt to open AssetProcessor.exe or Editor.exe
4. --> Notice that neither tool successfully opens

**Expected behavior**
AP and Editor open without issues

**Additional context**
commit 9e5ef08229d36ac9a4a624d0af13f91c43a8e8e5 from upstream/development

**Comment by amzn-sj** [comment]
This is being addressed in https://github.com/o3de/o3de/pull/3624

**Comment by monroegm** [comment]
We believe this has already been fixed. Please reopen if this is still an issue.
