### ISSUE TITLE
[QA Cross Task o3de for #3202]: [Win] Create Deploy Script that can copy a Project Game Release Layout to a standalone locatio

### ISSUE THREAD

**Issue by amzn-kritinig** [o3de/o3de#3668]
[Windows] The deploy script can take a Project Game Release Layout folder, gather any additional files need to run the GameLauncher standalone and copy it to location specified by the user.
Depending on how thorough the logic is to create a Project Game Release Layout, a separate deployment script might not be necessary

AC:
User is able to run the GameLauncher from the deployed location

**Comment by amzn-changml** [comment]
This sounds like a workflow enhancement for the project manager
