### ISSUE TITLE
DEV TASK: UI2.0 Bug - The image shouldn't be scaled up when the display area is larger then image itself. ( Set size limit per image) 

### ISSUE THREAD

**Issue by alexmontAmazon** [o3de/o3de#3692]
[Migrated from JIRA LYN-5588]
Provide a detailed description of the defect here and include any possible workarounds.
----
Found in Build: Latest

Reproducibility:  Yes

Prerequisites:  smaller icons, images in preview of Asset browser 

Steps to Reproduce: 
 In Asset Browser
 Browse to icon folder \dev\Editor\Icons\lc_sshot.png
 move the panel border to enlarge the preview area

*Expected Result*: 

Image only scale to its maximum size then spacing out in preview window, so image won't be pixelated. 

*Actual Result*: 

image scale up to match the size of preview panel.

![image](https://user-images.githubusercontent.com/75449675/131582988-fa782a25-383f-4657-880c-121e37a5f836.png)

**Comment by amzn-leenguy** [comment]
![image](https://user-images.githubusercontent.com/82846749/131581384-4f22bd39-f58d-4485-b3b8-66a19728f7a9.png)

Image attached for reference

**Comment by amzn-leenguy** [comment]
I actually think the image being full width to fit is fine. I would like to see a slider bar to zoom in and out from actual size to larger size is something to suggest though. 

So in conclusion: Im not aligned with the suggested result in description.

**Comment by yuyihsu** [comment]
I suggest we look into the issue with other asset browser issue together. there are other requests on the preview window, such as user wants to manipulate or zoom in to the preview image. we should look at this ticket with those behavior and resolve the problem holistically.

**Comment by yuyihsu** [comment]
We will revisit the issue with the browser revamp project that will be initiated early next year.
