### ISSUE TITLE
Prefabs Using Input Component Result in AP.exe Errors

### ISSUE THREAD

**Issue by monroegm** [o3de/o3de#3704]
[Migrated from JIRA LYN-4712]
Prefabs using Input component result in compilation errors in AP.exe 

*Steps to Reproduce*:

1.  Create a new level (or prefab)
2.  Add an entity with an Input Component
3.  Give the Input Component an Input asset
4.  Save level (or prefab)
5.  View AssetProcessor.exe

*Expected Result*:

Level (or prefab) successfully builds in AP.exe without warning/error

*Actual Result*:

Error because the InputEventBindingsAsset \{25971C7A-26E2-4D08-A146-2EFCC1C36B0C}

6/21/2021 2:07 PM | ERROR | AssetDatabase: Trace::Error from AssetBuilder6/21/2021 2:07 PM | ERROR | AssetDatabase: Trace::Error from AssetBuilder6/21/2021 2:07 PM | ERROR | > C:/prj/o3de/Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp(1161): 'class AZ::Data::Asset<class AZ::Data::AssetData> __cdecl AZ::Data::AssetManager::CreateAsset(const struct AZ::Data::AssetId &,const struct AZ::Uuid &,enum AZ::Data::AssetLoadBehaviorNamespace::AssetLoadBehavior)' from AssetBuilder6/21/2021 2:07 PM | ERROR | > No handler was registered for this asset (id=\{32C6931B-F0FA-5A80-A555-BCC091E9A1E9}:0, type=\{25971C7A-26E2-4D08-A146-2EFCC1C36B0C})! from AssetBuilder6/21/2021 2:07 PM | ERROR | AssetDatabase: Trace::Error from AssetBuilder6/21/2021 2:07 PM | ERROR | > C:/prj/o3de/Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp(1161): 'class AZ::Data::Asset<class AZ::Data::AssetData> __cdecl AZ::Data::AssetManager::CreateAsset(const struct AZ::Data::AssetId &,const struct AZ::Uuid &,enum AZ::Data::AssetLoadBehaviorNamespace::AssetLoadBehavior)' from AssetBuilder6/21/2021 2:07 PM | ERROR | > No handler was registered for this asset (id=\{32C6931B-F0FA-5A80-A555-BCC091E9A1E9}:0, type=\{25971C7A-26E2-4D08-A146-2EFCC1C36B0C})! from AssetBuilder6/21/2021 2:07 PM | ERROR | AssetDatabase: Trace::Error from AssetBuilder6/21/2021 2:07 PM | ERROR | > C:/prj/o3de/Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp(1161): 'class AZ::Data::Asset<class AZ::Data::AssetData> __cdecl AZ::Data::AssetManager::CreateAsset(const struct AZ::Data::AssetId &,const struct AZ::Uuid &,enum AZ::Data::AssetLoadBehaviorNamespace::AssetLoadBehavior)' from AssetBuilder6/21/2021 2:07 PM | ERROR | > No handler was registered for this asset (id=\{32C6931B-F0FA-5A80-A555-BCC091E9A1E9}:0, type=\{25971C7A-26E2-4D08-A146-2EFCC1C36B0C})! from AssetBuilder6/21/2021 2:07 PM | Info | AssetBuilder: Running processJob task from AssetBuilder6/21/2021 2:07 PM | Info | AssetBuilder: Source = C:/prj/MultiplayerSample/Levels/MultiplayerPong/MultiplayerPong.prefab from AssetBuilder6/21/2021 2:07 PM | Info | AssetBuilder: Platform = pc from AssetBuilder6/21/2021 2:07 PM | Info | Prefab Builder: Loading Prefab in 'C:/prj/MultiplayerSample/Levels/MultiplayerPong/MultiplayerPong.prefab'. from AssetBuilder6/21/2021 2:07 PM | Info | Prefab Builder: Sending Prefab to the processor stack. from AssetBuilder6/21/2021 2:07 PM | Info | Prefab Builder: Finalizing products. from AssetBuilder6/21/2021 2:07 PM | Info | Prefab Builder:     Serializing Prefab product 'MultiplayerPong.spawnable'. from AssetBuilder6/21/2021 2:07 PM | Info | Prefab Builder:     Storing Prefab product 'MultiplayerPong.spawnable'. from AssetBuilder6/21/2021 2:07 PM | Info | Prefab Builder: Cleaning up. from AssetBuilder6/21/2021 2:07 PM | Info | Prefab Builder: Prefab processing completed. from AssetBuilder6/21/2021 2:07 PM | Info | 3 errors, 0 warnings from AssetBuilder

*Note*

Input still appears to be working properly, this bug is only to track that AP shows an error

**Comment by lmbr-pip** [comment]
Retest issue to see if still occurring

**Comment by lmbr-pip** [comment]
Tested on latest dev, could not not reproduce.
