### ISSUE TITLE
Unmodified Prefabs UI Displays an * Asterisk

### ISSUE THREAD

**Issue by monroegm** [o3de/o3de#3715]
[Migrated from JIRA LYN-4040]
Dragging a prefab from the Asset Browser into the level and it immediately has an * asterisk saying it's been modified.
 

*Steps to Reproduce*:

1. Drag a prefab from the Asset Browser into your level

*Expected Result*:

The prefab is added and isn't modified

*Actual Result*:

The Entity Outliner saying the prefab has been modified

![image](https://user-images.githubusercontent.com/71404632/131414687-54f276b4-20a3-46e5-b329-7bab397d49e9.png)

**Comment by rainbj** [comment]
From a UX perspective. The * on the Prefabs should only be showing changes if content inside a prefab is changed (+maybe pinned modification). Anything such as transform to the entire prefab should reflect as updates to the level.prefab @AMZN-daimini is this something that should be reported as a bug and we should look into. Thanks

**Comment by AMZN-daimini** [comment]
It is, but it's more of a prefab internal bug than a UX one. Some operations during Instantiate do actually change the template from what is originally loaded from file, which is what trigger the asterisk to show. Sometimes the operations can be legitimate (as they produce changes to the template that would result in a different dom being saved from disk than what was loaded) while sometimes it's internal operations that should not dirty the template.
This can definitely be investigated, but it could be that loading a prefab sometimes makes it dirty legitimately, especially with versioning/sanitation happening on load.

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed. The only thing that gets an asterisk now is the level prefab, which makes sense.
