### ISSUE TITLE
UI Editor: Elements from Slice Library open context menus consisting of all folders starting from disk path

### ISSUE THREAD

**Issue by monroegm** [o3de/o3de#3717]
[Migrated from JIRA LYN-1874]
Hovering over the "Elements from Slice Library" in the UI Editor opens the context menu which starts from a folder that is higher in the hierarchy and the chain of context menus continues until the location of the default UI slices is reached. The first context menu name may seem incomplete, and after comparing the results with other testers we noticed that when starting from the C:\ path, exactly the first 19 characters from the full path are skipped.

*Full path 1:*
 _C:\Buildy\xxxxxxx-windows-8\Gems\UIBasics\Assets\UI\Slices\Library_
 *Displayed path 1:*
 _indows-8\Gems\UIBasics\Assets\UI\Slices\Library_
 *Full path 2:*
 _C:\Buildy\XXXXXXX\Gems\UiBasics\Assets\UI\Slices\Library_
 *Displayed path 2:*
 _ems\UiBasics\Assets\UI\Slices\Library_

For more information refer to the attached file.

*Found in Build*: test_package_upload-xxxxxxx-windows-all-8

*Reproducibility*: 5/5

*Prerequisites*:
 Build StarterGame (or any other project):
 * Open cmd in the folder with bootstrap.cfg.
 * Set 3rdParty path (_set 3RDPARTPATH=<path_to_3rdParty>_).
 * Create a windows_vs2017 folder (_mkdir windows_vs2017_).
 * cd into the created windows_vs2017 folder (_cd windows_vs2017_).
 * Configure the project (_cmake .. -G "Visual Studio 15 2017" -A x64 -T host=x64 -DLY_3RDPARTY_PATH="%3RDPARTYPATH%" -DLY_PROJECTS=StarterGame_).
 * Build the project and tools (_cmake -E time cmake --build . --target ALL_BUILD --config profile - /m:2_).
 * If a tool is missing, build it separately (_cmake -E time cmake --build . --target Code\Tools\ProjectConfigurator\ProjectConfigurator --config profile --/m:2_).

*Steps to Reproduce*:
1.  Open the Editor.
2.  Go to Tools > UI Editor.
3.  Right-click on the empty canvas and go to New > Element from Slice Library.

*Expected Result*:
 Only one context menu opens and all default UI slices are being displayed in it.

*Actual Result*:
 The context menu starts from a folder that is higher in the hierarchy and the chain of context menus continues until the location of the default UI slices is reached.

**Comment by yuyihsu** [comment]
@monroegm are we moving slices to prefabs in UI Editor? Will it solve this problem?
