### ISSUE TITLE
WF6 - Make new icons for Multiplayer Samples

### ISSUE THREAD

**Issue by alexmontAmazon** [o3de/o3de#3719]
[Migrated from JIRA LYN-4653]
{color:#000000}During the rev the engine test WF6: Multiplayer usability test, the following issue was logged.{color}

{color:#000000}We notice that there were missing icons for all the component cards for Multiplayer. UX needs to work with the Multiplayer team to create new icons have them added to the component cards{color}

{color:#000000}Please see image below as a reference for component images already in editor{color}
![image-2021-06-17-20-36-04-893](https://user-images.githubusercontent.com/61438964/182485840-91f90463-10cd-4b97-a7fa-38eb3c5cc408.png)

**Comment by lmbr-pip** [comment]
Tagging in for UX-action as unsure if icons exist. @rainbj do you know if these were ever created?

**Comment by rainbj** [comment]
Hi @lmbr-pip I'm working on improving my GitHub email filter at the moment as being the UX Chair, I get pinged on a lot of just standard updates regarding anything UX related. That's only to say I'm working on fixing this and... if you need a response sooner, please feel free to ping me directly to redirect my attention to any urgent needs.  As for the icons here, this is the most current icon sheet, and it doesn't appear your icons you need are listed. I'm assuming the ones you need are the blank ones listed under the networking channel?
![Component icons](https://user-images.githubusercontent.com/82551958/182657017-fca3c4ef-5019-40c6-96a4-4ac0334534b0.jpg)

**Comment by lmbr-pip** [comment]
Relates to: https://github.com/o3de/o3de/issues/9820

**Comment by rainbj** [comment]
@yuyihsu and @svitlani this needs to be added into the UX backlog. I'm not sure if this should be the ticket for UX to make the icons, or if this is the developer ticket for implementing them. In either case, it looks like we are missing a ticket here.

The icons that are needed are in the Pink column under "Networking" and currently have a blank space

**Comment by rainbj** [comment]
Hi @lmbr-pip. Can you verify that these are all the icons we are needing to complete this task 

![Image](https://user-images.githubusercontent.com/82551958/199312329-7166703d-4924-4587-9475-3d5cf7f7f503.png)

**Comment by rainbj** [comment]
![2022-12-22_10-46-15](https://user-images.githubusercontent.com/82551958/213340165-9b73e2c5-102a-42b5-807c-6c0ba47b6b1e.png)
Final icons after review with the team. Please let me know if you need to get access to the assets. Thanks

**Comment by cgalvan** [comment]
Added the component icons for the MPS project components as well: https://github.com/o3de/o3de-multiplayersample/pull/219
