### ISSUE TITLE
Building Python gem to O3DE is broken

### ISSUE THREAD

**Issue by alexmontAmazon** [o3de/o3de#3720]
[Migrated from JIRA LYN-4088]
There is no Gem template for a 'Python tool gem', there is manual work to set one up (not much but is self taught currently)

TASK: Can someone create a template for a Python Gem?

 

Feedback from RTE test

**Comment by HogJonny-AMZN** [comment]
https://www.o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/
