### ISSUE TITLE
When creating a new input binding from the component, the new binding is not assigned to that component automatically.

### ISSUE THREAD

**Issue by alexmontAmazon** [o3de/o3de#3722]
[Migrated from JIRA LYN-3525]
When the user adds an input component to an entity the input binding field that assigns the particular binding file to that component is empty. If the user selects to create a new input binding, the assignment field is still left empty. This is in contrast to the script canvas component which automatically adds any new canvas to the script canvas component.

*This issue is not just in the input, it's almost everywhere else other than the SC workflow. We need to make this as a standard pattern behavior across the editor. we should investigate if this can be done in the UI component level.*

 

*Build Number:* commit 93254944feea0cb1994092cb536dcb1f1fe39f94 Date: Mon May 3 14:02:39 2021 -0700

*Repro* *Steps:*
- Add an input component to an entity.
- On the input component click the "create new" button to create a new input binding file.
- Save the new file.

*Results:*

The newly created input binding file is not added to the input component.

*Expected:*

The newly created input binding file is added to the input component.

**Comment by yuyihsu** [comment]
We need to build the behavior "auto-assign the newly created file to the original text field" into the UI component. We've seen this issue in many other use cases.

**Comment by yuyihsu** [comment]
@amzn-leenguy we should include this in doc as well.

**Comment by alexmontAmazon** [comment]
@sphrose , how's this one looking?

**Comment by sphrose** [comment]
Looking good now, new version pushed.
