### ISSUE TITLE
Single key shortcuts could trigger tools when user just wants to type

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3734]
### Problem description
As a user, I expect that when I type in a key in the editor, it should intelligently know whether I am typing in a text field, or I am trying to trigger a tool.

Certain tools open with a single key press (e.g. M for material editor, T for track view). It is also easy for focus to be lost, so you think you are typing into a text box but instead you inadvertently open a tool. 

Reported by @greerdv through LY Game Jam.

**Comment by alexmontAmazon** [comment]
Yuyi, do you know which hotkeys you'd like to change for this? I assume we're going to take away one-character hotkeys, but let me know if you have a different solution in mind.

**Comment by yuyihsu** [comment]
For short-term, can we simply make sure we understand user's context (e.g. cursor focus) to perform the right action? in this case, if user's cursor focus in on the text field, it should not trigger any hotkey control because we know users are typing something.

**Comment by alexmontAmazon** [comment]
that's already the case, if you are in fact in a text field. I think the original issue is that it's easy to think that a particular widget (such as a text box) has focus when it doesn't. If anyone knows of an example where a shortcut is getting triggered while a text widget has focus, then we should definitely look into that, but I don't think that's the case.

**Comment by alexmontAmazon** [comment]
@yuyihsu , if you or someone in UX can get me a list of shortcuts they'd like us to change, I'd be happy to do that.

**Comment by yuyihsu** [comment]
After checking the build, we noticed this issue has been fixed as Alex mentioned. I'm closing this ticket.

https://user-images.githubusercontent.com/75449675/141193372-408f0ebb-9dd1-4665-8d99-fdd0ee87ff80.mp4
