### ISSUE TITLE
Color picker - confusing values

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3736]
### Problem description
The color picker displays different RGB values than the color shown on the component, even though they're both updating at the same time.  I suspect it's a color space thing instead of a bug, which is why I'm listing it as a usability issue instead of submitting to JIRA.

Reported by @mbalfour-amzn through LY game jam.

![image (16)](https://user-images.githubusercontent.com/75449675/131427626-5361e970-193e-4b87-a478-8d30e37815c1.png)

**Comment by santorac** [comment]
I think this is duplicate: https://github.com/o3de/o3de/issues/2980

**Comment by santorac** [comment]
The difference in values is intentional. https://github.com/o3de/o3de/pull/12292 should help alleviate some of the confusion, by showing more color space information in the dialog.
