### ISSUE TITLE
LuaIDE is not built when building Editor.exe (must be built separately)

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3742]
### Problem description

When building the Editor with CMake (and Editor is set as the main target) the LuaIDE is not built as part of this, so when trying to open the LuaIDE for the first time, the user is presented with an error that LuaIDE.exe could not be found. This is quite surprising and forces uses to compile the LuaIDE project separately. As this is so closely linked to the Editor, it likely makes sense make it a dependency to be built automatically, or later on make it obvious this is missing by having the user explicitly opt in or out of enabling it.

**Workaround-**
Build LuaIDE explicitly be specifying that target (in Visual Studio or from command line with CMake)

if users build from prism, they will get LuaIDE. however if users fork from github, and didn't choose to build all, then they won't get LUAIDE.

Reported by @hultonha through LY game jam

**Comment by amzn-pratikpa** [comment]
LYN-7139
