### ISSUE TITLE
Script Canvas diffs after changes

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3743]
### Problem description

When making tiny changes to Script Canvas graphs, the entire file seems to be reordered every time which makes sanity checking diffs very difficult and collaborating on the same Script Canvas graph impossible. It would be fantastic if it could use the new Json serialization to help minimize diffs or find a more consistent way of handling changes to the file

Reported by @hultonha  through LY game jam

**Comment by hultonha** [comment]
I think this might already have been done thanks to @carlitosan
