### ISSUE TITLE
Making changes to Prefabs with multiple in the level can be quite slow

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3747]
### Problem description

This is likely wrapped up with the existing performance problems in the UI (Entity Inspector) more than anything but making single value changes to a Prefab (if there are say 10 in the scene) can take around 5 seconds. I much prefer the behavior to that of Slices (all changing at once) but it would be great if the performance cost was invisible.

Reported by @hultonha through LY game jam

**Comment by monroegm** [comment]
For the November release the goal is to optimize propagation so that instead of refreshing the entire prefab (i.e. the level) only affected entities are refreshed. In a future release, we may optimize propagation even further such that only affected component/properties are refreshed.

**Comment by monroegm** [comment]
Fixed by #5355
