### ISSUE TITLE
Improve naming consistency for Script Canvas nodes

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3763]
[Migrated from JIRA LYN-6781]
### Problem description

Currently there are a lot of variations naming the same operation which looks sloppy. We have GetTranslation, Get Translation and Get translation. It would be great to do a pass over all the names to make sure they use the same consistent convention (and look into tooling to support catching these errors happening in future).

Reported by @hultonha through LY game jam

![image (21)](https://user-images.githubusercontent.com/75449675/131530259-0ad91546-e368-4232-b349-c2b9e696738e.png)

**Comment by lsemp3d** [comment]
This is now fixed through a series of updates to Script Canvas' translation data

**Comment by hultonha** [comment]
Awesome! 😄 🎉
