### ISSUE TITLE
Async IO for Linux

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/o3de#3771]
AZ::IO::Streamer on Linux needs to be updated from the current blocking IO to be asynchronous to improve performance.
On Linux AZ::IO::Streamer uses standard file IO functions that block. This reduces the performance of file streaming on Linux, requires additional memory and increases latency between file requests and completion. Instead native async file IO APIs should be used similar to what was done for Windows. The work is mostly localized to a dedicated storage drive, but will also require configuring the Settings Registry with a specific configuration for Linux and may require updating the central event to a Linux specific synchronization primitive.

AC:
- Native async file IO for Linux is used in AZ::IO::Streamer.
- The Settings Registry is updated with a configuration on Linux that's configured to use the new native async.

The expectation is that performance will be in the same range as Windows. Note though that on higher speed drives this may be more difficult to determine as O3DE does not have a project that stress tests streaming and because the scheduler is currently not optimized and comparatively expensive for high speed drives.

**Comment by kinglawr** [comment]
@amzn-pratikpa Please add AC to this for Product to review.
