### ISSUE TITLE
Script Canvas was working without 'Script Canvas Gem' being marked as enabled in project manager

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3773]
### Problem description

As a user, I want to see the related gem associated to the tool that I'm using is enabled in the Gem Catalog. Currently it's not the case.

I am confused about the Gem behavior because I was using script canvas but noticed the gem was not marked as being enabled for my project.

Reported by @AMZN-Liv through LY Game Jam

**Comment by amzn-pratikpa** [comment]
LYN-7141
