### ISSUE TITLE
Python samples gem

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3791]
Problem description

Tech artist has no examples to know how to use hydra python patterns to extend the editor. 

Goals:
- 1. create a python sample gam (sample gem repo)
- 2. add the gem to the sample project (sample project repo)
- 3. add to O3DE as a new gem template. 

The gem contains
1. editor/scripts/bootstrap.py (example: how to modify editor boot for example, activate new menu)
2. pyside2 menu class (example: how to configure a menu with actions, start a new tool)
3. pyside 2 panel (example: python tool panel)
4. TBD

**Comment by monroegm** [comment]
@yuyihsu Why is it recommended for this to be a blocker? Can you provide more information?

**Comment by yuyihsu** [comment]
@monroegm this is suggested by @HogJonny-AMZN . He'll be working on this ticket. We can move this to critical.

**Comment by HogJonny-AMZN** [comment]
I helped advise @cgalvan on this and it's been delivered along with docs: https://www.o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/
