### ISSUE TITLE
error message: should at least give user the asset ID for easy trouble shooting

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3798]
### Problem description

As a user, I want to see useful info in the error message that can help me troubleshoot the issue faster. 

For example, When running the SC to drive some game logic and an error occured, the error messages we display didn't tell user which asset is generating the errors. It should at least tell user the unique ID of the asset, so user can troubleshoot.

View video at 01:11:30

FOUND IN BUILD: 8601ffa27b98e702efd4b6701654cdda16838be9

REPORTER: genewalt

**Comment by lsemp3d** [comment]
There is not enough information on this ticket, it references a video, but there is no video attached. It also doesn't specify which error needs to be improved.

**Comment by AMZN-Gene** [comment]
Not sure what video this is referring. Will reopen if I see an issue and add details for a proper report
