### ISSUE TITLE
[QA Cross Task for #3227]: Add support for installing Monolithic and Non-Monolithic configurations into the same SDK layout

### ISSUE THREAD

**Issue by amzn-kritinig** [o3de/o3de#3804]
Add support for installing Monolithic and Non-Monolithic configurations into the same SDK layout
#3227
The current golden path for making a game with O3DE is to use non-Monolithic debug and profile for development and then switch to using a Monolithic release build for distribution to the end user.
This task is to add support to the SDK to the SDK layout generation via the CMake INSTALL step to take non-monolithic build CMake configuration and a monolithic CMake configuration and create an SDK layout which is the "union" of there install artifacts.
Monolithic builds only build a subset of targets that non-Monolithic builds perform, therefore the CMake build scripts need to are common among both types of builds install layout need to be "merged" and not replaced, to make sure the proper set of build targets exist.

AC
	• The pre-built Editor/AssetProcessor in debug and profile configurations should able to run successfully for a project using the SDK
	• The GameLauncher a project builds using the SDK should be able to run in all configurations(debug, profile, release) successfully
Add support for installing Monolithic and Non-Monolithic configurations into t

**Comment by amzn-changml** [comment]
@amzn-kritinig This ticket seems incomplete. Can you elaborate on this further and if it's still needed?
