### ISSUE TITLE
When 100 FBX models of characters are loaded in the scenario, the GPU usage of the O3DE Editor process is always 0% in the Task Manager window of the PC. However, the GPU usage of the O3DE Editor process is not 0% when other tools are used.

### ISSUE THREAD

**Issue by JonsonZhangyabing** [o3de/o3de#3818]
**Describe the bug**
When 100 FBX models of characters are loaded in the scenario, the GPU usage of the O3DE Editor process is always 0% in the Task Manager window of the PC. However, the GPU usage of the O3DE Editor process is not 0% when other tools are used.
**To Reproduce**
1. Open the O3DE.
2. Create a level.
3. Add 100 characters and actions

**Expected behavior**

**Screenshots**

**Desktop/Device (please complete the following information):**
Device: [PC]
OS: [Windows]
Version [10]
CPU [Intel I7-10700 2.90GHz (16 CPUs) ]
GPU [Intel(R) UHD Graphics 630，NVIDIA GeForce GTX 1650]
Memory [32GB]

**Additional context**

**Comment by wintermute-motherbrain** [comment]
Can you provide any additional context to this that better describes the issue?

**Comment by superkitcath** [comment]
@JonsonZhangyabing, could you provide additional context for this bug? Thanks!

**Comment by superkitcath** [comment]
Adding /needs-triage to discuss during our weekly meeting.

**Comment by superkitcath** [comment]
Hi @JonsonZhangyabing, this ticket will be closed due to inactivity. 
Please open a new ticket if the issue is not resolved. Thank you!
