### ISSUE TITLE
The bump of material rendering is not realistic

### ISSUE THREAD

**Issue by AmStao** [o3de/o3de#3829]
**Describe the bug**
Under the same model map, the bump of o3de rendering does not look as real as UE4

**To Reproduce**
1. After adding corresponding maps to the model, pay attention to the rendered bump effect

**Expected behavior**
It has a very real concave convex effect

**Screenshots**
On the left is the effect of other engines, and on the right is the effect of o3de
![image](https://user-images.githubusercontent.com/89911557/131661579-08aa8ffa-4eec-4960-8377-86b8d48dfefc.png)

**Desktop/Device (please complete the following information):**
Device: [ PC]
OS: [Windows]
Version [10]
CPU [Intel(R) Core(TM)I7-10700 CPU 2.90GHZ 2.90 GHZ ]
GPU [NVIDIA Geforce GTX 1650]
Memory [32GB]

**Additional context**

**Comment by wintermute-motherbrain** [comment]
Can you please provide more information aside from comparisons with UE4?  Specifically around "correctness"?  Textures and materials would also be useful for context.

**Comment by AmStao** [comment]
I can't provide more clear screenshots due to the operational limitations of uploads, but when I use o3de to do game scenes, UE4 works better. And the effect of normals gives the illusion of the opposite effect at certain angles.

**Comment by AmStao** [comment]
I can't provide any more screenshots due to upload limitations, but I can focus on the effect of rock and leather when normals are too strong.thank you.

**Comment by superkitcath** [comment]
@AmStao, we cannot do much at this point with the data provided. We will close it for now, let us know if you have more information on that issue in the future. Thank you!
