### ISSUE TITLE
O3de has high memory consumption but low FPS

### ISSUE THREAD

**Issue by AmStao** [o3de/o3de#3834]
**Describe the bug**
O3de has high memory consumption but low FPS，Compare UE4

**To Reproduce**
1. Create an empty scene
2. Focus on resource consumption

**Expected behavior**
Only small resource consumption

**Screenshots**

**Desktop/Device (please complete the following information):**
Device: [ PC]
OS: [Windows]
Version [10]
CPU [Intel(R) Core(TM)I7-10700 CPU 2.90GHZ 2.90 GHZ ]
GPU [NVIDIA Geforce GTX 1650]
Memory [32GB]

**Additional context**

**Comment by forhalle** [comment]
We are currently holistically investigating O3DE performance, and have other GHIs to track performance-related work, so will close this specific ticket for now. Thanks so much for your feedback.
