### ISSUE TITLE
[EmotionFX] SimulatedObjects layout displays incorrect panes

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#3841]
**Describe the bug**
It has been noticed thath changing the layout to **SimulatedObjects** results in displaying additional panes if the change was made from the layout other than **AnimGraph**. 

**To Reproduce**
1. Open the **Animation Editor**.
2. Change the layout to **Physics**.
3. Change the layout to **SimulatedObjects**.

**Expected behavior**
Correct panes are assigned to the **SimulatedObjects** layout.

**Screenshots**

![layout](https://user-images.githubusercontent.com/86952009/131673587-b6492fee-a801-43c4-8ec1-7d827cfb2c75.JPG)

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU Intel I5-9600k
GPU RTX 2060
Memory 16GB

**Additional context**

https://user-images.githubusercontent.com/86952009/131673630-c92e7b7b-c8fd-4f7d-a7f2-a2febe90bdee.mp4

**Comment by amzn-jillich** [comment]
Fixed along with https://github.com/o3de/o3de/pull/4185

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in development
