### ISSUE TITLE
[shadow] Point light (Sphere) Boundary search mode, pseudo-texture and strip shadow appeared in the scene

### ISSUE THREAD

**Issue by XiObama12** [o3de/o3de#3864]
**Describe the bug**

**To Reproduce**
1. Go to 'Point light Sphere'
2. Click on 'Boundary search'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16256324/131769586-4cab0e9f-b828-4872-ab6b-e4c58429b313.png)

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by mrieggeramzn** [comment]
This method (boundary search) is currently up for PR for removal. Bicubic will be the new default and only PCF mode.
