### ISSUE TITLE
Similarities When shadow is enabled in light source scenarios (256 and 2048),  FPS of O3DE is much lower than that of UE4, and the memory usage is higher than that of UE4

### ISSUE THREAD

**Issue by XiObama12** [o3de/o3de#3865]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by wintermute-motherbrain** [comment]
This issue needs more information aside from a comparison between UE4 and O3DE.

**Comment by superkitcath** [comment]
@XiObama12, could you please provide more information / details on this bug? Thanks!

**Comment by superkitcath** [comment]
Adding /needs-triage to discuss during our weekly meeting.
