### ISSUE TITLE
Entity outliner editing window: right click the blank space on the right of the entity outliner, select unlock entity outliner, and then drag the entity outliner back to its original position. The function is available only after a delay of about 10 seconds

### ISSUE THREAD

**Issue by gsy1993** [o3de/o3de#3876]
**Describe the bug**
Entity outliner editing window: right click the blank space on the right of the entity outliner, select unlock entity outliner, and then drag the entity outliner back to its original position. The function is available only after a delay of about 10 seconds

**To Reproduce**
1. Open the game engine
2. Open the entity outliner editing window
3. Right click the blank space on the right side of the entity outliner and select unlock entity outliner
4. Drag the entity outliner back to its original position and right-click in the blank space

**Expected behavior**
Features are available immediately

**Screenshots**
![image](https://user-images.githubusercontent.com/89908888/131802520-29f25489-35f6-4bf6-bbbd-22838efca8fd.png)

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by AMZN-daimini** [comment]
I am unable to reproduce this.
