### ISSUE TITLE
In the edit interface of the asset browser function, right-click assets / tools and assets / runtime resources and select copy name to clipboard. The displayed name is different from the actual copied name

### ISSUE THREAD

**Issue by gsy1993** [o3de/o3de#3877]
**Describe the bug**
In the edit interface of the asset browser function, right-click assets / tools and assets / runtime resources and select copy name to clipboard. The displayed name is different from the actual copied name，The assets / tools name is editor，The assets / runtime name is engine

**To Reproduce**
1. Open the game engine
2. Open the asset browser editor
3. Right click the copy name to clipboard on assets / tools and assets / runtime resources

**Expected behavior**
The name is consistent with the displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/89908888/131804525-b9c7c6fa-a8a5-496d-9120-a3f9d142fbad.png)

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by AMZN-daimini** [comment]
Could not reproduce in the new Asset Browser UI.
