### ISSUE TITLE
[Linux] Throws a library not found error from 3RDPARTY

### ISSUE THREAD

**Issue by Mobs1024** [o3de/o3de#3882]
Branch: 9a0ea2c4c5cdec19bedec4e527275c7196ea5d94

**To Reproduce**
Open terminal

need to install 
`sudo zypper in uuid-devel Mesa-devel libjbig-devel libSDL2-devel libopus-devel libwebp-devel libcurl-devel libjpeg8-devel libz1 libncurses5 libcurl4 libGLU1 libxcb-xinerama0 libxcb-xinput0 libfontconfig1` for OpenSUSE only Tumbleweed not Leap 15.X

`./python/get_python.sh` works well and the following

run `:~/o3de/o3de> cmake -B build/linux-dedicated -S . -DLY_3RDPARTY_PATH=~/o3de/3RDPARTY/ -DLY_UNITY_BUILD=ON -DCMAKE_INSTALL_PREFIX=~/o3de/PREFIX/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++`

errors 
```
-- Using package /home/xxxxxx/o3de/3RDPARTY/packages/qt-5.15.2-rev5-linux
CMake Error at /home/xxxxxx/o3de/3RDPARTY/packages/qt-5.15.2-rev5-linux/qt/lib/cmake/Qt5FontDatabaseSupport/Qt5FontDatabaseSupportConfig.cmake:91 (message):
  Library not found: fontconfig
Call Stack (most recent call first):
  /home/xxxxxx/o3de/3RDPARTY/packages/qt-5.15.2-rev5-linux/qt/lib/cmake/Qt5FontDatabaseSupport/Qt5FontDatabaseSupportConfig.cmake:264 (_qt5_FontDatabaseSupport_process_prl_file)
  /home/xxxxxx/o3de/3RDPARTY/packages/qt-5.15.2-rev5-linux/qt/lib/cmake/Qt5XcbQpa/Qt5XcbQpaConfig.cmake:96 (find_package)
  /home/xxxxxx/o3de/3RDPARTY/packages/qt-5.15.2-rev5-linux/qt/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /home/xxxxxx/o3de/3RDPARTY/packages/qt-5.15.2-rev5-linux/FindQt.cmake:64 (find_package)
  cmake/LYWrappers.cmake:478 (find_package)
  cmake/3rdPartyPackages.cmake:720 (ly_parse_third_party_dependencies)
  cmake/LYPython.cmake:39 (include)
  CMakeLists.txt:36 (include)


-- Configuring incomplete, errors occurred!
```

**Expected behavior**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux OpenSUSE
 - Version: Tumbleweed
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT
 - Memory: 16GB

**Additional context**

**Comment by amznestebanpapp** [comment]
yes, `fontconfig` is a dependency of Qt
I think the package is `fontconfig-dev`. Will become part of the Setup instructions for Linux

**Comment by Mobs1024** [comment]
@amznestebanpapp I think this should be added officially o3de in the for Linux OpenSUSE docs `build`

```sudo zypper in uuid-devel Mesa-devel libjbig-devel libSDL2-devel libopus-devel libwebp-devel libcurl-devel fontconfig-devel libxkbcommon-devel libjpeg8-devel libz1 libncurses5 libcurl4 libGLU1 libxcb-xinerama0 libxcb-xinput0 libfontconfig1```

thank you, topic closed :))

**Comment by amznestebanpapp** [comment]
Once the instructions are out, we can update the documentation if it is not included (by creating PR to the o3de,org repo)
I am pretty sure the instructions will need to be slightly different for different distros, so help there is more than welcome :)
