### ISSUE TITLE
[MacOS] AutomatedTesting: Asset Processor fails to load EditorPythonBindings, AtomLyIntegration, PythonAssetBuilder, LyShine, and AtomToolsFramework gems upon launching

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#3888]
**Describe the bug**
It has been observed that Asset Processor with AutomatedTesting set as a project will fail to load **EditorPythonBindings**, **AtomLyIntegration**, **PythonAssetBuilder**, **LyShine**, and **AtomToolsFramework** gems upon launching.
Because of this, all .fbx assets are also failing to be processed by Asset Processor and are unable to be added to components such as **Mesh** or **Actor**.
For further information please refer to the attached screenshots and log file.

[FailedGemsAssetProcessorLog.txt](https://github.com/o3de/o3de/files/7099501/FailedGemsAssetProcessorLog.txt)

**To Reproduce**
1. Use GitHub to obtain the latest O3DE build on your Mac.
2. Create a new or move your preexisting 3rdParty folder into the O3DE folder.
3. Obtain Cmake.app and move it to the created _3rdParty/CMake_ directory (create
the CMake folder if necessary).
4. In the O3DE directory right-click on python folder and select **New Terminal at Folder**.
5. Run the command:
`export PATH=$PATH:/Users//o3de/3rdParty/CMake/CMake.app/Contents/bin`
6. Run the command:
`./get_python.sh`
7. Create a folder named **_osx_build_** in the O3DE folder.
8. Open a new terminal in the created **_osx_build_** folder and set the following temporary environment variables:
    ```
    export PATH=$PATH:/Users//o3de/3rdParty/CMake/CMake.app/Contents/bin
    export LY_3RDPARTY_PATH=/Users//o3de/3rdParty
    export LY_PACKAGE_SERVER_URLS=https://d2c171ws20a1rv.cloudfront.net
    ```
9. Configure and generate Xcode solution:
`cmake .. -G "Xcode" -DLY_3RDPARTY_PATH=$LY_3RDPARTY_PATH -DLY_PROJECTS=AutomatedTesting -DLY_UNITY_BUILD=1`
10. Build with Cmake by using:
`cmake -E time cmake --build . --target ALL_BUILD --config profile -j 2` command.
11. After building process finishes launch Asset Processor of a built AutomatedTesting project with:
`/Users/<home folder name>/o3de/osx_build/bin/profile/AssetProcessor.app/Contents/MacOS/AssetProcessor --project-path=AutomatedTesting` command.

**Expected behavior**
Asset Processor loads all gems and processes all assets successfully.

**Screenshots**
![PythonAssetBuilder](https://user-images.githubusercontent.com/86953456/131858789-49b53b40-fd80-4db8-93f6-4b897392ac6f.jpg)
![EditorPythonBindings](https://user-images.githubusercontent.com/86953456/131858797-45cda773-070e-442b-a6fa-1a7ae9c47788.jpg)
![AtomLyIntegration](https://user-images.githubusercontent.com/86953456/131858808-033b0957-52fe-4547-a728-bcd10aec5d3e.jpg)
![LyShine](https://user-images.githubusercontent.com/86953456/131858816-5af6ea24-4033-4fa5-8e16-bb5d2132dbc0.jpg)
![AtomToolsFramework](https://user-images.githubusercontent.com/86953456/131858822-f296f612-1334-4465-bb62-73a0e13ae8c9.jpg)

**Desktop/Device (please complete the following information):**
**- Device:** Mac
**- OS:** MacOS
**- Version:** Big Sur 11.3.1
**- CPU:** Intel Core i7 2,8 GHz
**- GPU:** Radeon Pro 555
**- Memory:** 16GB

**Comment by amzn-sj** [comment]
PR posted here: https://github.com/o3de/o3de/pull/3905

**Comment by LB-MateuszSzweda** [comment]
The issue no longer occurs against _daf901e_ commit from development build. Closing the issue as fixed.
