### ISSUE TITLE
Improve the physics component editing mode usability issues by adopting the new viewport cluster UI framework

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#3895]
[Migrated from JIRA LYN-5431]
*Problem description-*

The Physics joint components (e.g. ball joint, hinge joint, etc.) don't function as expected.

Issues
 # when entering into the component editing mode, the move/resize/rotate controls are missing from the viewport.
 # the normal editor hotkeys for move/rotate/scale (1/2/3) dont apply to joints (why not stay consistent)  
 # when trying to change the settings from the component card, the visual feedback on the viewport is gone.
 # the viewport manipulators are hidden behind the hotkeys which is invisible to the customers. For the customers we've tested with, none of them were aware that they can use "tab" key to access the different manipulators.

**Comment by greerdv** [comment]
Most of these issues were fixed in https://github.com/o3de/o3de/pull/4352. Just waiting on one last query/fix.

**Comment by amzn-sean** [comment]
PR https://github.com/o3de/o3de/pull/4352 has been completed and merged.
