### ISSUE TITLE
Remove 3rdParty::lux_core, AZ_TRAIT_LUXCORE_SUPPORTED and any use of LuxCore

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#3915]
**Is your feature request related to a problem? Please describe.**
Currently there is a dependency to LuxCore, but all platforms have the trait `AZ_TRAIT_LUXCORE_SUPPORTED` disabled. We are also compiling that code (all code in LuxCore), so we are unnecessary adding build time for a feature that is disabled and not being used. 

**Describe the solution you'd like**
Remove the 3rdParty association so it is not downloaded anymore, remove all code/traits that are related to LuxCore

**Comment by amznestebanpapp** [comment]
@bosnichd requested that we dont remove `Atom_Feature_Traits_{Platform}.h` files since they are going to be used for something else.

**Comment by bosnichd** [comment]
> @bosnichd requested that we dont remove `Atom_Feature_Traits_{Platform}.h` files since they are going to be used for something else.

Please see https://github.com/o3de/o3de/pull/6482
