### ISSUE TITLE
Landscape Canvas: Duplicated or pasted nodes are incorrectly assigned to the graph/entity, which may result in a crash

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#3922]
**Describe the bug**
It has been noticed that duplicated or pasted nodes are added to the graph, but are not properly added to the parent entity in the **Entity Outliner**. Duplicating or deleting the previously duplicated node crashes the Editor.

**To Reproduce**
1. Open the **Landscape Canvas**.
2. Add any node to it.
3. Duplicate the node.
4. Delete or duplicate the previously duplicated node.

**Expected behavior**
The node is deleted/duplicated correctly. The Editor remains stable.

**Call stack trace:**
```
25) 00007FF94151C247 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FF943BF5270 (ntdll) : memset
23) 00007FF943BDC776 (ntdll) : _C_specific_handler
22) 00007FF943BF217F (ntdll) : _chkstk
21) 00007FF943BA1454 (ntdll) : RtlRaiseException
20) 00007FF943BF0CAE (ntdll) : KiUserExceptionDispatcher
19) C:\O3DE\o3de\Gems\LandscapeCanvas\Code\Source\Editor\MainWindow.cpp (253) : LandscapeCanvasEditor::CloneSingleEntity
18) C:\O3DE\o3de\Gems\LandscapeCanvas\Code\Source\Editor\MainWindow.cpp (722) : LandscapeCanvasEditor::MainWindow::OnEntitiesSerialized
17) C:\O3DE\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (146) : AZ::Internal::EBusContainer<GraphCanvas::SceneNotifications,GraphCanvas::SceneNotifications,1,1>::Dispatcher<AZ::EBus<GraphCanvas::SceneNotifications,GraphCanvas::SceneNotific
16) C:\O3DE\o3de\Gems\GraphCanvas\Code\Source\Components\SceneComponent.cpp (2669) : GraphCanvas::SceneComponent::SerializeEntities
15) C:\O3DE\o3de\Gems\GraphCanvas\Code\Source\Components\SceneComponent.cpp (2832) : GraphCanvas::SceneComponent::DuplicateAt
14) C:\O3DE\o3de\Gems\GraphCanvas\Code\Source\Components\SceneComponent.cpp (2807) : GraphCanvas::SceneComponent::DuplicateSelectionAt
13) C:\O3DE\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (146) : AZ::Internal::EBusContainer<GraphCanvas::SceneRequests,GraphCanvas::SceneRequests,1,1>::Dispatcher<AZ::EBus<GraphCanvas::SceneRequests,GraphCanvas::SceneRequests> >::Event<voi
12) C:\O3DE\o3de\Gems\GraphCanvas\Code\StaticLib\GraphCanvas\Widgets\EditorContextMenu\ContextMenuActions\EditMenuActions\EditContextMenuActions.cpp (111) : GraphCanvas::DuplicateGraphSelectionMenuAction::TriggerAction
11) C:\O3DE\o3de\Gems\GraphCanvas\Code\StaticLib\GraphCanvas\Widgets\EditorContextMenu\ContextMenuActions\ContextMenuAction.h (70) : GraphCanvas::ContextMenuAction::TriggerAction
10) C:\O3DE\o3de\Gems\GraphCanvas\Code\StaticLib\GraphCanvas\Widgets\GraphCanvasEditor\GraphCanvasAssetEditorMainWindow.cpp (691) : GraphCanvas::AssetEditorMainWindow::HandleContextMenu
 9) C:\O3DE\o3de\Gems\LandscapeCanvas\Code\Source\Editor\MainWindow.cpp (1150) : LandscapeCanvasEditor::MainWindow::ShowNodeContextMenu
 8) C:\O3DE\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (192) : AZ::Internal::EBusContainer<GraphCanvas::AssetEditorRequests,GraphCanvas::AssetEditorRequests,1,1>::Dispatcher<AZ::EBus<GraphCanvas::AssetEditorRequests,GraphCanvas::AssetEdit
 7) C:\O3DE\o3de\Gems\GraphCanvas\Code\Source\Components\SceneComponent.cpp (4873) : GraphCanvas::GraphCanvasGraphicsScene::contextMenuEvent
 6) 00007FF8FD97968A (Qt5Widgets) : QGraphicsScene::event
 5) 00007FF8FD6B49B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
 4) 00007FF8FD6B3A33 (Qt5Widgets) : QApplication::notify
 3) 00007FF8FDDC1B4A (Qt5Core) : QCoreApplication::notifyInternal2
 2) 00007FF8FD992161 (Qt5Widgets) : QGraphicsView::contextMenuEvent
 1) C:\O3DE\o3de\Gems\GraphCanvas\Code\StaticLib\GraphCanvas\Widgets\GraphCanvasGraphicsView\GraphCanvasGraphicsView.cpp (1157) : GraphCanvas::GraphCanvasGraphicsView::mouseReleaseEvent
```

**Desktop/Device (please complete the following information):**
**Device:** PC
**OS:** Windows
**Version** 10
**CPU** Intel I5-9600k
**GPU** RTX 2060
**Memory** 16GB

**Additional context**

https://user-images.githubusercontent.com/86952009/131978516-df128196-03f0-4721-a085-bfc2fac814b1.mp4

[Editor.log](https://github.com/o3de/o3de/files/7104588/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7104590/error.log)
[dump.zip](https://github.com/o3de/o3de/files/7104592/dump.zip)

**Comment by jckand-amzn** [comment]
This only occurs with Prefab system enabled.

**Comment by LB-MarcinKoniecki** [comment]
It is worth mentioning that on the recent Development build (34c9f41) duplicating any node and undoing this action afterwards causes a silent crash of the project. I'm attaching the error.log file for verification. As we are not sure if the root cause is the same as it is in this issue, we would like to ask if it should be considered as a separate ticket?
[error.log](https://github.com/o3de/o3de/files/8215697/error.log)

**Comment by jckand-amzn** [comment]
> It is worth mentioning that on the recent Development build ([34c9f41](https://github.com/o3de/o3de/commit/34c9f4151d8d958f23fcf80b181fe9d5024ac3ac)) duplicating any node and undoing this action afterwards causes a silent crash of the project. I'm attaching the error.log file for verification. As we are not sure if the root cause is the same as it is in this issue, we would like to ask if it should be considered as a separate ticket? [error.log](https://github.com/o3de/o3de/files/8215697/error.log)

The call stack looks to be different, so I've logged up a new issue for that as #8207. Thanks for the heads up.

**Comment by LB-BartoszDudzinski** [comment]
Hi @cgalvan. I am afraid that the issue still occurs with a slightly different repro steps. Duplicating the node and deleting it works fine but duplicating the original node after deleting the duplicated one crashes the editor. I am not entirely sure if the Fix was merged as I can still see the cut/copy/paste actions available in the Landscape Canvas on both latest Stabilization and Development branches. I attach the callstack.

[error.log](https://github.com/o3de/o3de/files/9706474/error.log)
