### ISSUE TITLE
Landscape Canvas: Undo/Redo does not work in the Graph window

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#3928]
**Describe the bug**
Undo/Redo options do not work inside the Graph window. The User cannot undo/redo the delete node operation or attach pins operation.

**To Reproduce**
1. Go to Landscape Canvas.
2. Add any new node.
3. Delete the node.
4. Press CTRL+Z or Undo in the Edit dropdown.

**Expected behavior**
The node is restored to its former state.

**Video:**

https://user-images.githubusercontent.com/86952591/131985688-3de81324-2dd6-40cc-b849-dcd59c8dc83f.mp4

**Desktop/Device (please complete the following information):**

Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA RTX 2060 SUPER
Memory 16GB

**Comment by cgalvan** [comment]
Fixed by https://github.com/o3de/o3de/pull/12182

**Comment by LB-JakubSkoczylas** [comment]
This issue no longer occurs. Verified this on build Stabilization/2210 (731cff1).
