### ISSUE TITLE
Positioning of prefabs inside Level not saving

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#3944]
Prefabs that are created/imported into a level lose their positioning once the level is saved and exited.

**To Reproduce**
1. Create a prefab out of an object or import one into a level.
2. Position the object.
3. Save the level and close it.
4. Open the level back up- the prefab will still be there, but the positioning will be lost. Prefabs will be sent back to the scene origin.

**Expected behavior**
Positioned prefabs will retain their positioning when a level is saved, so that when reopening the scene prefabs so not become positioned back to the origin of the level. 

**Screenshots**

**Desktop/Device (please complete the following information):**
 - PC
 - Windows
 - 10
 - Intel I9-9820X
 - NVidia RTX 2080]
 - 64 GB

**Comment by monroegm** [comment]
Duplicated by #2506
