### ISSUE TITLE
Instantiating a Prefab with multiple entities can shuffle their arrangement

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#3953]
**Describe the bug**
It has been noticed that creating a Prefab from multiple entities, or a parent entity with multiple child entities can shuffle their arrangement in the hierarchy. It should be noted that the entities shuffle only on their level, meaning that for example a child entity will only swap places with other child entities of the same parent. It should also be noted that this issue can be related to https://github.com/o3de/o3de/issues/3716.

**To Reproduce**
1. Create 3 entities with different names.
2. Select them all, right-click them and select "Create Prefab..." from the dropdown menu.
3. Save the Prefab.
4. Right-click in the Entity Outliner, select "Instantiate Prefab...", and select the Prefab saved in step 3. Repeat this step 3 times.
5. Check the arrangement of entities within each of the instantiated Prefabs.

**Expected behavior**
Entities in the Prefab stay in the same arrangement they were in when the Prefab was created.

**Video**

https://user-images.githubusercontent.com/86952082/132304706-91f12e88-85d9-43aa-8551-7c70f236c6e1.mp4

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (f74dca6) build.
