### ISSUE TITLE
The Editor crashes upon launching when the Install_Prefix path is set inside the engine source folder

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#3955]
**Describe the bug**
This issue occurs only on one of the machines. After setting the CMAKE_INSTALL_PREFIX="full engine source path"/install in the configuration command, any project that is created does not launch. The following errors are displayed upon launching. The Editor's crash logs are created and attached.

![SimpleTextured](https://user-images.githubusercontent.com/86952009/132318819-b45a10f7-cb57-4606-8e2d-36b2151eae24.JPG)
![rpi](https://user-images.githubusercontent.com/86952009/132318820-ec838940-8749-4f85-afbe-a9c5fc55efb7.JPG)

**To Reproduce**
1. Setup the GitHub build.
2. Execute the following commands inside the c:/o3de/o3de folder where the engine source is downloaded:

`cmake -B build/windows_vs2019 -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\O3DE\o3de-packages -DLY_UNITY_BUILD=ON -DLY_VERSION_ENGINE_NAME=o3de-install -DCMAKE_INSTALL_PREFIX=C:\O3DE\o3de\install`

and

`cmake --build build\windows_vs2019 --target INSTALL --config profile -- /m`

3. Get the python runtime, by launching the python/get_python.bat script.
4. Register the engine.
5. Navigate to C:\O3DE\o3de\install\bin\Windows\profile folder and launch the O3DE.exe.
6. Create a new project and build it afterwards.
7. Launch the project.

**Expected behavior**
The Editor launches without issues.

**Call Stack Trace:**
```
25) 00007FFD45F9C247 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFD48515270 (ntdll) : memset
23) 00007FFD484FC776 (ntdll) : _C_specific_handler
22) 00007FFD4851217F (ntdll) : _chkstk
21) 00007FFD484C1454 (ntdll) : RtlRaiseException
20) 00007FFD48510CAE (ntdll) : KiUserExceptionDispatcher
19) C:\O3DE\o3de\Gems\Atom\RHI\Code\Source\RHI.Reflect\ShaderResourceGroupLayout.cpp (442) : AZ::RHI::ShaderResourceGroupLayout::FindShaderInputBufferIndex
18) C:\O3DE\o3de\Gems\Atom\Feature\Common\Code\Source\Utils\GpuBufferHandler.cpp (28) : AZ::Render::GpuBufferHandler::GpuBufferHandler
17) C:\O3DE\o3de\Gems\Atom\Feature\Common\Code\Source\CoreLights\SimplePointLightFeatureProcessor.cpp (54) : AZ::Render::SimplePointLightFeatureProcessor::Activate
16) C:\O3DE\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\Scene.cpp (131) : AZ::RPI::Scene::Activate
15) C:\O3DE\o3de\Gems\Atom\Bootstrap\Code\Source\BootstrapSystemComponent.cpp (287) : AZ::Render::Bootstrap::BootstrapSystemComponent::GetOrCreateAtomSceneFromAzScene
14) C:\O3DE\o3de\Gems\Atom\Tools\AtomToolsFramework\Code\Source\Viewport\RenderViewportWidget.cpp (143) : `AtomToolsFramework::RenderViewportWidget::SetScene'::`2'::<lambda_1>::operator()
13) C:\O3DE\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1541) : AZ::Internal::EBusContainer<AZ::Render::Bootstrap::Request,AZ::Render::Bootstrap::Request,0,0>::Dispatcher<AZ::EBus<AZ::Render::Bootstrap::Request,AZ::Render::Bootstrap::Requ
12) C:\O3DE\o3de\Gems\Atom\Tools\AtomToolsFramework\Code\Source\Viewport\RenderViewportWidget.cpp (152) : AtomToolsFramework::RenderViewportWidget::SetScene
11) C:\O3DE\o3de\Code\Editor\EditorViewportWidget.cpp (2489) : EditorViewportWidget::UpdateScene
10) C:\O3DE\o3de\Code\Editor\EditorViewportWidget.cpp (1069) : EditorViewportWidget::SetViewportId
 9) C:\O3DE\o3de\Code\Editor\ViewPane.cpp (307) : CLayoutViewPane::AttachViewport
 8) C:\O3DE\o3de\Code\Editor\ViewPane.cpp (223) : CLayoutViewPane::SetViewClass
 7) C:\O3DE\o3de\Code\Editor\LayoutWnd.cpp (207) : CLayoutWnd::MaximizeViewport
 6) C:\O3DE\o3de\Code\Editor\LayoutWnd.cpp (518) : CLayoutWnd::LoadConfig
 5) C:\O3DE\o3de\Code\Editor\MainWindow.cpp (430) : MainWindow::InitCentralWidget
 4) C:\O3DE\o3de\Code\Editor\MainWindow.cpp (449) : MainWindow::Initialize
 3) C:\O3DE\o3de\Code\Editor\CryEdit.cpp (1697) : CCryEditApp::InitInstance
 2) C:\O3DE\o3de\Code\Editor\CryEdit.cpp (4115) : CryEditMain
 1) C:\O3DE\o3de\Code\Editor\main.cpp (32) : main
```

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU Intel I5-9600k
GPU RTX 2060
Memory 16GB

**Additional context**

[Editor.log](https://github.com/o3de/o3de/files/7120401/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7120404/error.log)
[dump.zip](https://github.com/o3de/o3de/files/7120405/dump.zip)

**Comment by anshul-bharat** [comment]
I got this exact same issue, i installed the prebuilt version for windows. And got same popups while opening new project with editor.

**Comment by HydrogenC** [comment]
Same issue with the installer version of 2409
