### ISSUE TITLE
[Feature] Additional toggle location for "Clear Console at game startup" 

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#3973]
Currently the toggle is located in `Edit > Editor Settings > Global Preferences > General Settings > Clear Console at game startup`

![image](https://user-images.githubusercontent.com/48143120/132437991-33e22222-9a46-44f8-8390-b635b61674aa.png)

I think it will be good if there is an additional toggle location that is more quick to access, like around one of these two spots:

![image](https://user-images.githubusercontent.com/48143120/132438134-0ee41d59-8153-4a29-9079-cdf9fb042b8e.png)

**Comment by AMZN-Gene** [comment]
2nd this request! This option is great, but I just learned about it today. 
Alternatively, if there was a console preferences menu with "Clear Console at game startup", "Console Background (color)", "Show Time in Console", you could also just add a button in the console to open that menu. I agree though that the "clear console at game startup" seems like a good place.
Is this a good first issue? If someone points me in the right direction I'd like to implement this myself :P

**Comment by AMZN-Gene** [comment]
Thank you @sphrose! 🔥
