### ISSUE TITLE
O3DE Core (LmbrCentral) references Lumberyard

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#4007]
**Describe the bug**
It has been noticed that the O3DE Core (LmbrCentral) still has a reference to the Lumberyard engine in its name.

**To Reproduce**
1. Go to the Project Manager and Create a new project (if no projects are present).
2. Click the hamburger next to any project's name and select Edit Project Settings...
3. In the Edit Project Settings tab click Configure Gems.
4. Search for the "LmbrCentral".

**Expected behavior**
There are no references to the Lumberyard in O3DE

**Screenshot**
![LmbrCentral](https://user-images.githubusercontent.com/86952082/132642623-273313d9-8323-4110-a508-92ffc46cb632.PNG)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by monroegm** [comment]
We are not renaming libraries, gems, classes, etc. right now

**Comment by LB-ArturSiewniak** [comment]
Closing as Won't Do.
