### ISSUE TITLE
Fly Camera Input component .svg icon file is missing

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#4013]
**Describe the bug**
It has been observed that the .svg icon file is missing from the Fly Camera Input component which is inconsistent with all other components. Editor's console throws the following error: 
`[Error] (AtomViewportDisplayIconSystemComponent) - Failed to locate icon on disk: "Icons/Components/Viewport/FlyCameraInput.svg"`

**To Reproduce**
1. Create an entity.
2. Select 'Add Component' and find the Fly Camera Input component.
3. See the issue.

**Expected behavior**
All components have their .svg icon files present.

**Screenshot**
![FlyCameraInput](https://user-images.githubusercontent.com/86953659/132674117-54bb4704-01bd-4d55-9539-176898ff757c.PNG)

**Desktop/Device**
Device: PC
OS: Windows
Version: 10
CPU: Intel i5-9600K
GPU: RTX 2070
Memory: 16GB

**Comment by lawsonamzn** [comment]
This also causes the icon for the entity to disappear in the viewport, making it more difficult to select.
