### ISSUE TITLE
[MacOS] Selecting Ragdoll Joints for Activate Ragdoll Joints node in Anim Graph crashes the Editor

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4020]
**Describe the bug**
It has been observed that using **Select Ragdoll Joint** window to select Ragdoll Joints that will be activated by Anim Graphs _ActivateRagdollJoints_ will crash the Editor.

For further information please refer to the attached logs and a video file.

https://user-images.githubusercontent.com/86953456/132706616-998e5701-29ce-4b3a-adc0-e2649092033a.mov

[Editor.log](https://github.com/o3de/o3de/files/7137439/Editor.log)

[crash.log](https://github.com/o3de/o3de/files/7137441/crash.log)

**Prerequisites**

* Asset Processor and Editor has been built.
* Assets were processed in Asset Processor.
* AutomatedTesting was set as a project to launch.

**To Reproduce**

1. Create a new level or open an existing one.
2. Open the Emotion FX Animation Editor (PREVIEW) tool.
3. Switch the layout to **Physics** .
4. Open the _cowboy_01.fbx_ actor or any other actor that can have Ragdoll colliders added.
5. Select few nodes in actors **Skeleton Outliner** and click **Add to ragdoll** in the Ragdoll pane.
6. Save the actor by clicking **File > Save Selected Actors** .
7. Switch the layout to **AnimGraph** .
8. In **Anim Graph** pane click the "+" to create a new anim graph.
9. Right click on the newly created graph and select **Create Node > Sources > Blend Tree** and
double click the created **BlendTree** node.
10. Right click on the graph and select **Create Node > Physics > Activate Ragdoll Joints** .
11. Select the created _ActivateRagdollJoints_ node and click the Selector button in **Activate Ragdoll Joints** attribute of the node.
12. In the opened **Select Ragdoll Joints** window select a few ragdoll joints and click "OK" .

**Expected behavior**
The nodes are correctly added to **Activate Ragdoll Joints** attribute and the Editor remains stable.

**Desktop/Device (please complete the following information):**
- Device: Mac
- OS: MacOS
- Version: Big Sur 11.3.1
- CPU: Intel Core i7 2,8 GHz
- GPU: Radeon Pro 555
- Memory: 16GB

**Comment by moraaar** [comment]
This issue has been fixed.

**Comment by LB-MateuszSzweda** [comment]
Verified as fixed in Development (1f1f449). The Editor did not crash on selecting and adding Ragdoll Joints to Anim Graphs. Anim graphs created this way were also verified to be usable with actors and the Editor remained stable while using them.

**Comment by moraaar** [comment]
Thanks for verifying the issue @LB-MateuszSzweda!
