### ISSUE TITLE
o3de could not initialize correctly for the follwing reason(s);

### ISSUE THREAD

**Issue by 860000023** [o3de/o3de#4038]
unable to find product asset"shaders/simpletextured.azshader",has the source asset finished building?
could not load font:Fonts/default.font.

when i open editor by automatedtesting .i got this error

**Comment by xw901103** [comment]
Duplicate of #3955

**Comment by superkitcath** [comment]
Closing this issue, as it is a duplicate of[ #3955.](https://github.com/o3de/o3de/issues/3955)
