### ISSUE TITLE
Feature Request: Improve Cvars are search and use

### ISSUE THREAD

**Issue by svitlani** [o3de/o3de#4059]
[Migrated from JIRA LYN-4640]
**Is your feature request related to a problem? Please describe.**
During the rev the engine test WF6: Multiplayer usability testing, the following issue was logged.

"there was a Cvar I couldn’t find. That was generically somehow educating people how to find Cvars. For example, all the graphics cvars start with r_

How cool would it be if components had a list of cvars that affected them… that would educate people quickly since components are things users see day 1

For example mesh component would have a drop down “r_stats” to see all triangles rendered"

**Describe the solution you'd like**
Suggested fix.

Integrate the Cvar help menu into the main search field.
Use UI 2.0 search field.
Update the Cvar helper logic to list the Cvars based on the above recommendations.
include the new ScriptCanvas CVARS into global docs page Stephen Tramer for viability.

**Comment by lmbr-pip** [comment]
All the Multiplayer and Network settings are under https://www.o3de.org/docs/user-guide/networking/settings/

**Comment by lmbr-pip** [comment]
Auto expand works in editor for variables, and we have a general namespace guide here: https://www.o3de.org/docs/user-guide/appendix/cvars/ 

Will mark as done after checking with @svitlani

**Comment by lmbr-pip** [comment]
CVAR discovery should be covered by https://github.com/o3de/o3de.org/issues/1634
