### ISSUE TITLE
Filter isn't working as expected in the node search in ScriptCanvas

### ISSUE THREAD

**Issue by svitlani** [o3de/o3de#4061]
[Migrated from JIRALYN-4649]

**Describe the bug**
During the rev the engine test WF6: Multiplayer usability testing- the following issue was logged.

Filter is not working as expected in the node search in ScriptCanvas. It just simply returned any words with the "if".

**Comment by monroegm** [comment]
@svitlani Can you provide more specific repro steps?

**Comment by monroegm** [comment]
@svitlani We will close this one on Tuesday 9/28 if we don't hear back

**Comment by lsemp3d** [comment]
Closing, not enough information
