### ISSUE TITLE
Bug Report: QoL Deleting a Script Canvas Variable Causes Nodes Using that Variable to Use a New Variable

### ISSUE THREAD

**Issue by svitlani** [o3de/o3de#4062]
[Migrated from JIRA LYN-3667]

**Describe the bug**
Deleting a Script Canvas Variable Causes Nodes Using that Variable to Use a New Variable

**To Reproduce**

Create 2 Script Canvas Number Variables
Create an OnTick node assigning the delta to one of the number variables
Delete the delta variable

**Expected behavior**
The user is warned that they are deleting a variable that's in use. If user accepts, then the OnTick delta should be cleared

**Comment by lsemp3d** [comment]
Variable gets cleared now and set to <None>, users can then set a different variable manually.
