### ISSUE TITLE
Undoing changes in Non-Uniform Scale Component Mode does not undo the actions, Component Mode turns off instead

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#4076]
**Describe the bug**
It has been noticed that undoing changes in the Component Mode of the **Non-Uniform Scale** component does not result in undoing the changes.
Performing the undo action results in turning off the Component Mode.

**To Reproduce**

1. Create new entity.
2. Add a **Non-Uniform Scale** component to the entity.
3. Enter the Component Mode of the **Non-Uniform Scale** component (Press the 'Edit' button).
4. Perform changes in Component Mode.
5. Undo the changes (Ctrl+Z).

**Expected behavior**
The changes are undone, Component Mode does not turn off.

**Video**

https://user-images.githubusercontent.com/86951967/133061356-05e478f9-785c-47f3-af06-573986e15764.mp4

**Device: PC**

 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by greerdv** [comment]
I think this should be fixed by https://github.com/o3de/o3de/pull/7199

**Comment by LB-JakubSkorupka** [comment]
Issue can be closed as we verified that this issue does not occurs on build Development (f4c59f8).

**Comment by LB-JakubSkorupka** [comment]
Closing the issue as it does not occur on build Stabilization/2305 (18f6f22).
