### ISSUE TITLE
Multiplayer AutoComponent ArchetypeProperty Init Values Aren't Used

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#4099]
**Describe the bug**
Multiplayer AutoComponent ArchetypeProperty default values aren't set by default in the editor

**To Reproduce**
1. Edit or create a new multiplayer auto-component. In the example below I'm using MultiplayerSamples' WasdPlayerMovementComponent
2. Create a new float ArchetypeProperty and give it an init value other than 0
3. Compile editor
4. Add your component to an entity
5. Notice the value of the ArchetypeProperty is 0.0 instead of what we set as the init value.

**Expected behavior**
The component's ArchetypeProperty should use the default (init) value.

**Screenshots**
![image](https://user-images.githubusercontent.com/32776221/133169078-e99c7b4e-cea2-4f8a-8eac-13497239b28a.png)

**Comment by lmbr-pip** [comment]
SIG-Net triage would like to see if this has been fixed.

**Comment by AMZN-Gene** [comment]
Still occurs. NetworkHealthComponent MaxHealth init value is 100, but Editor shows 0.0
This is a networking specific issue, because I'm able to change the edit context values of other floats and the editor properly displays the value.
![image](https://user-images.githubusercontent.com/32776221/166864042-f19624fc-af26-4a61-b360-db7d47dd949c.png)

**Comment by AMZN-Gene** [comment]
This came up again... because it's not initialized the values are crazy.
Here's my float default value: 70958467666258603766804643840.0
Going to increase this to major since it's just so visible.
