### ISSUE TITLE
Add indexed access to `SpawnableEntityContainerView` and `SpawnableConstEntityContainerView`

### ISSUE THREAD

**Issue by SergeyAMZN** [o3de/o3de#4110]
Currently programmers have to use *(begin() + index), but accessing via operator[] would be more convenient / easier to read

_Originally posted by @AMZN-koppersr in https://github.com/o3de/o3de/pull/4023#discussion_r707832107_

**Comment by AMZN-koppersr** [comment]
PR for this ticket: https://github.com/o3de/o3de/pull/4153

**Comment by AMZN-koppersr** [comment]
The implementation for this has been merged to the development branch.
