### ISSUE TITLE
Animation Editor: Creating Motion Sets does not increment them correctly

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#4111]
**Describe the bug**

Creating Motion Sets via the "+" button does not increment them correctly. Clicking the button creates every second Motion Set. If the user deselects a newly created Motion Set and then clicks the "+" button or uses _RMB -> Add Motion Set_, the Motion Sets are created correctly.

Please refer to the attached video for more information.

**To Reproduce**

1. Open the Animation Editor.
2. Go to the Motion Sets tab.
3. Click on the "+" button several times.

**Expected behavior**
Motion Sets are incremented correctly in all circumstances.

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

https://user-images.githubusercontent.com/86952318/133241622-3367efe6-e8c1-4c45-b83a-af0eea681b6a.mp4

**Comment by monroegm** [comment]
@LB-MichalRodzos is there a workaround?

**Comment by LB-MichalRodzos** [comment]
@monroegm If the user deselect created Motion Set and then create a new one via the "+" button, the new Motion Set will be created correctly. However, it will not resolve the sorting issue.
