### ISSUE TITLE
EmotionFX: Pressing the record button a couple of times when the "record states only" option is selected crashes the Editor

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#4114]
**Describe the bug**
Recording states in the Time View of the Animation Editor may result in a crash. The issue is more likely to occur when the "Record states only" option is selected right after adding the Actor, Motion Set and the Anim Graph to the Workspace. Otherwise, a crash occurs only after pressing the record button repeatedly.

**To Reproduce**
1. Open the Animation Editor.
2. Add an Actor, a corresponding Motion Set and Anim Graph.
3. In the Time View pane, press the cog icon and select "Record states only".
4. Press the record button a few times.

**Expected behavior**
The Editor remains stable.

**Call Stack Trace:**
```
25) 00007FFD45F9C247 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFD48515270 (ntdll) : memset
23) 00007FFD484FC776 (ntdll) : _C_specific_handler
22) 00007FFD4851217F (ntdll) : _chkstk
21) 00007FFD484C1454 (ntdll) : RtlRaiseException
20) 00007FFD48510CAE (ntdll) : KiUserExceptionDispatcher
19) 00007FFCC342E02D (EMotionFX.Editor) : DetachEnvironment
18) 00007FFCC342C5C8 (EMotionFX.Editor) : DetachEnvironment
17) 00007FFCC3434C34 (EMotionFX.Editor) : DetachEnvironment
16) 00007FFCF9334CEE (Qt5Widgets) : QOpenGLWidget::redirected
15) 00007FFCF9307F4A (Qt5Widgets) : QWidget::event
14) 00007FFCC3432B1E (EMotionFX.Editor) : DetachEnvironment
13) 00007FFCF92E49B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
12) 00007FFCF92E3A33 (Qt5Widgets) : QApplication::notify
11) 00007FFCF99F1B4A (Qt5Core) : QCoreApplication::notifyInternal2
10) 00007FFCF930755E (Qt5Widgets) : QWidgetPrivate::drawWidget
 9) 00007FFCF930D5B7 (Qt5Widgets) : QWidgetPrivate::paintSiblingsRecursive
 8) 00007FFCF93076B7 (Qt5Widgets) : QWidgetPrivate::drawWidget
 7) 00007FFCF930D5B7 (Qt5Widgets) : QWidgetPrivate::paintSiblingsRecursive
 6) 00007FFCF93076B7 (Qt5Widgets) : QWidgetPrivate::drawWidget
 5) 00007FFCF930D5B7 (Qt5Widgets) : QWidgetPrivate::paintSiblingsRecursive
 4) 00007FFCF93076B7 (Qt5Widgets) : QWidgetPrivate::drawWidget
 3) 00007FFCF930D5B7 (Qt5Widgets) : QWidgetPrivate::paintSiblingsRecursive
 2) 00007FFCF930D4E5 (Qt5Widgets) : QWidgetPrivate::paintSiblingsRecursive
 1) 00007FFCF93076B7 (Qt5Widgets) : QWidgetPrivate::drawWidget
```

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU Intel I5-9600k
GPU RTX 2060
Memory 16GB

**Additional context**

https://user-images.githubusercontent.com/86952009/133252198-801bc55b-d1b3-4aa1-a6d8-df49d4fb9ecd.mp4

[Editor.log](https://github.com/o3de/o3de/files/7161593/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7161594/error.log)
[dump.zip](https://github.com/o3de/o3de/files/7161595/dump.zip)

**Comment by amzn-rhhong** [comment]
I cannot repro this. I tried it on rin workspace as well as the cowboy workspace.
What are the repro rate for this crash bug? Does it just happen to the cowboy workspace or it can be reproduced with other workspace as well?

If only the cowboy workspace lead to the crash, can you attach the motionset, animgraph and workspace file?

**Comment by LB-BartoszDudzinski** [comment]
I was able to repro this on the Rin workspace as well. The repro rate for this is 90%. Most of the times the crash occurs right after the second or third click on the record button but sometimes I need to press the button quite fast to reproduce it. I've noticed that the same issue occurs when "Record all nodes" option is selected. I reproduced this on additional two different machines. It took like 20+ clicks on the first one, but only 4-5 clicks on the second one.

I've attached the cowboy workspace that I am using.

[Cowboy_01.zip](https://github.com/o3de/o3de/files/7168467/Cowboy_01.zip)
[AnimationEditorFiles.zip](https://github.com/o3de/o3de/files/7168475/AnimationEditorFiles.zip)
[Animations.zip](https://github.com/o3de/o3de/files/7168476/Animations.zip)

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in development
