### ISSUE TITLE
Instantiating any Prefab when a level is not loaded crashes the Editor

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#4115]
**Describe the bug**
Instantiating any Prefab via Viewport crashes the Editor when a level is not yet loaded.

**To Reproduce**
1. Launch the Editor.
2. Close the **Welcome to O3DE** screen.
3. Press RMB in the Viewport and select **Instantiate Prefab**.
4. Select any valid Prefab.

**Expected behavior**
Instantiating a Prefab is not possible without loading a level.

**Call Stack Trace:**
```
25) 00007FFD45F9C247 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFD48515270 (ntdll) : memset
23) 00007FFD484FC776 (ntdll) : _C_specific_handler
22) 00007FFD4851217F (ntdll) : _chkstk
21) 00007FFD484C1454 (ntdll) : RtlRaiseException
20) 00007FFD48510CAE (ntdll) : KiUserExceptionDispatcher
19) 00007FFCEABC0D44 (EditorLib) : ModuleInitISystem
18) 00007FFCEAAC8BE9 (EditorLib) : ModuleInitISystem
17) 00007FFCEAB5549A (EditorLib) : ModuleInitISystem
16) 00007FFCEAB64EC1 (EditorLib) : ModuleInitISystem
15) 00007FFCEAB68E1E (EditorLib) : ModuleInitISystem
14) 00007FFCEAB52D39 (EditorLib) : ModuleInitISystem
13) 00007FFCD7CC7AF7 (ComponentEntityEditorPlugin) : CreatePluginInstance
12) 00007FFCF9A10DB9 (Qt5Core) : QObject::qt_static_metacall
11) 00007FFCF92D5DCF (Qt5Widgets) : QAction::activate
10) 00007FFCF942C698 (Qt5Widgets) : QMenu::actionGeometry
 9) 00007FFCF942C473 (Qt5Widgets) : QMenu::actionGeometry
 8) 00007FFCF9431C51 (Qt5Widgets) : QMenu::mouseReleaseEvent
 7) 00007FFCF9307B02 (Qt5Widgets) : QWidget::event
 6) 00007FFCF942DC37 (Qt5Widgets) : QMenu::event
 5) 00007FFCF92E49B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
 4) 00007FFCF92E28D0 (Qt5Widgets) : QApplication::notify
 3) 00007FFCF99F1B4A (Qt5Core) : QCoreApplication::notifyInternal2
 2) 00007FFCF92E5BC5 (Qt5Widgets) : QApplicationPrivate::sendMouseEvent
 1) 00007FFCF933024A (Qt5Widgets) : QSizePolicy::QSizePolicy
```

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Additional context**

https://user-images.githubusercontent.com/86952009/133261956-8cb1ecad-c93a-4efc-a3c2-165a79de2533.mp4

[Editor.log](https://github.com/o3de/o3de/files/7162091/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7162092/error.log)
[dump.zip](https://github.com/o3de/o3de/files/7162094/dump.zip)

**Comment by srikappa-amzn** [comment]
This is a bug. We are providing an option for an invalid workflow. We shouldn’t even provide that option to instantiate the prefab when there is no level.

**Comment by Amzn-Catdo** [comment]
Verified on branch that this bug has been fixed. User will no longer be able to instantiate a prefab without a level.
![image](https://user-images.githubusercontent.com/82239748/134738940-fd479483-e27d-4611-8441-60d0338003ae.png)

**Comment by LB-BartoszDudzinski** [comment]
Closing as Fixed in Development
