### ISSUE TITLE
[iOS] Entities based on Cloth and Mesh components display graphical artifacts

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4118]
**Describe the bug**
**Cloth** entities based on a **Mesh** component are displaying graphical artifacts and flickering upon launching the level on an iOS device. The issue is not observed with **Cloth** entities based on an **Actor** component.

Please note that the same level launched by macOS launcher and Editor had correctly displaying Cloth entities.

For further information please refer to the attached video file.

https://user-images.githubusercontent.com/86953456/133268862-9831e5d7-5b9f-41ee-8c90-97ae35bb7741.mp4

**Prerequisites**

* A Level with a few working **Cloth** and **Mesh** based entities was created.
* autoexec.cfg containing _LoadLevel < created PhysX level name >_ line is created and moved into AutomatedTesting folder.
* iOS assets were processed by Asset Processor.
* The **AutomatedTesting** project built for iOS.

**To Reproduce**
1. Deploy the App to an iOS device with Xcode.
2. Launch the App manually on iOS device or with Xcode.

**Expected behavior**
Cloth entities based on a Mesh component do not present graphical issues.

**Desktop/Device:**
- Device: iPhone 11 Pro
- OS: iOS
- Version: 14.7.1
- CPU: A13 Bionic
- GPU: A13 Bionic
- Memory: 6GB

**Comment by moraaar** [comment]
I just run a level with the same cloth prefabs using the latest from development @98791cc6 on an iPhone XS Max (iOS 15.1), the graphics artifacts didn't appear.

**Comment by LB-MateuszSzweda** [comment]
The issue was also verified as not occuring today on Development (1c4ec5c) on IPhone X (iOS 14) device. The Meshes and Cloth based entities were glitch free.
