### ISSUE TITLE
Save all dialog does not appear even though there are unsaved prefabs

### ISSUE THREAD

**Issue by Amzn-Catdo** [o3de/o3de#4123]
**Describe the bug**
The save all dialog does not appear even though there is an unsaved prefab inside the level when I press Ctrl + S or when I go to File > Save even though my global preference is set to "Ask every time". This only occurs when you have saved the level a second time and then added an entity to a second prefab then tried to save again.

If I were to exit the editor even though there is an unsaved prefab, the save all dialog still does not appear and the prefab will remain unsaved which causes a data loss. If I were to right click and "save Prefab to file" then the prefab will be saved.

**To Reproduce**
1. Create a new level
2. Create entity then turn it to a prefab called 'p1'
3. Create a second entity then turn it into a prefab called 'p2'
4. Right click p1 and create entity underneath it
5. Go to file > save or press ctrl + s
6. Click on "Save" on the Save all dialog that will pop up
7. Noticed that the dirty * markers are gone
8. Right click p2 and create entity underneath it
9. Go to file > save or press ctrl + s
10. Noticed that the dirty * marker is NOT gone

**Expected behavior**
Save all dialog should appear when there is an unsaved prefab inside the level

**Screenshots**
![image](https://user-images.githubusercontent.com/82239748/133305083-4d9a0d39-5617-4f20-abeb-d4e128690308.png)

**Video**

https://user-images.githubusercontent.com/82239748/133305122-d4e8ddac-4a54-4801-bbc2-f67dfb97f2e8.mp4

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed.
