### ISSUE TITLE
White sphere wireframe shows up in the Viewport when holding Alt

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#4139]
**Describe the bug**
When the Alt key is pressed, a white sphere wireframe goes from the center of the camera and stops at the first mesh it collides with, or if faced away from the meshes it travels an indeterminate distance. When the Alt key is released, the white sphere wireframe expands and disappears. It should be noted that this is not present on animated .gifs on this documentation page: https://o3de.org/docs/user-guide/editor/viewport/group-selections-reference-spaces/

**To Reproduce**
1. Create a new level and set the Viewport camera to look at the Ground entity.
2. Hold Alt and release after a few seconds.

**Expected behavior**
There is no white sphere wireframe showing up.

**Video**

https://user-images.githubusercontent.com/86952082/133417733-4d967d45-5af7-44cb-9e99-18d85cbb1ae7.mp4

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by hultonha** [comment]
For the record this was intentional 😅 This was the orbit point and we decided we wanted to show users where it was.

A recent change has just gone in though (https://github.com/o3de/o3de/pull/4345) which updates how the pivot behavior works (we now use the manipulator when active and the origin if there's no selection) so the wireframe ball is now gone.

Can you please verify on latest dev? Thanks!

**Comment by LB-ArturSiewniak** [comment]
Thanks for the explanation! I've checked the changes you've described on build Development (c00a2b5) and I confirm that:

1. There's no more white wireframe sphere when holding Alt.
2. If no entity is selected the pivot for Alt + Left-click or Alt + Right-click becomes the World 0,0,0 coordinate.
3. If an entity is selected (I've selected the Shader Ball after relocating it from its original starting location), the pivot for Alt + Left-click or Alt + Right-click becomes the center of the entity.

**Comment by hultonha** [comment]
Awesome thank @LB-ArturSiewniak - just to confirm in future should I not close the issue and wait for you to verify? Thanks!

**Comment by LB-ArturSiewniak** [comment]
Either way is fine. If you fixed the issue and need the author to verify it, it will be checked regardless. If you close it first and it reoccurs, it will be reopened. Thank you!

**Comment by hultonha** [comment]
Okay perfect thanks for confirming :+1: Cheers!
