### ISSUE TITLE
AfterUndoRedo is not the last event that happens when Undo is pressed

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#4163]
**Describe the bug**

It has been observed that the Entity pivot (currently drawn when an Entity is selected) will not update with the Entity transform when Undo is pressed. The position of the Entity pivot is cached in `EditorVisibleEntityDataCache` which relies on receiving an `AfterUndoRedo` notification once all entity state has been returned to the previous undo step.

What seems to happen now is `AfterUndoRedo` is called before the entity transform has actually been updated to the previous position. This results in the pivot appearing in the incorrect position. The cause of the issue seems to be a notification ordering problem potentially.

Update: I did a little more digging an no `OnTransformChanged` is sent for the entity that moved either (this is likely correct, but the updated state of the entity after deserializing the previous undo state should be valid at the time `AfterUndoRedo` is pressed).

**To Reproduce**

1. Create an Entity in the Editor
2. Select it
3. Using the translation manipulator, move the entity
4. Press Undo

**Expected behavior**

The Entity and pivot position should return to where they were before the drag occurred.

**Actual behavior**

The Entity returns to the correct position but the pivot does not and stays where it was.

**Screenshots**

https://user-images.githubusercontent.com/82228511/133583280-dcce1906-0008-4fcb-a3b2-a73802d74e51.mp4

Update: I tested this with Prefabs disabled and Slices enabled and it works correctly (see below)

https://user-images.githubusercontent.com/82228511/133764787-8fc6d899-f8fb-4d28-aab6-ca64850e7697.mp4

**Comment by hultonha** [comment]
Thanks for fixing this @AMZN-mnaumov! 😄

**Comment by jckand-amzn** [comment]
Re-verified fix on mnaumov/LYN-7995. Tested with moving/scaling/rotating entity and undoing in both prefab/slice mode as well as saving transform changes and reloading. No issues encountered.
