### ISSUE TITLE
Launcher crashes at shutdown at camera component

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#4170]
**Describe the bug**
When running the launcher with a level that has a camera component, then running the quit command the program doesn't close nicely, it crashes.

**To Reproduce**
1. Open Editor using AutomatedTesting project
2. Create a new level called newlevel, save and click on Game > Export to Engine.
3. Close Editor
4. Create autoxec.cfg file in AutomatedTesting file to load the new level with the "LoadLevel levels\newlevel"
5. Run game launcher from Visual Studio
6. Press ` button to open up the console and enter "quit"

**Expected behavior**
The launcher closes without problems

**Screenshots**
![LauncherCrash](https://user-images.githubusercontent.com/27999040/133627898-5d2005b6-e68e-4832-b832-3f92e8036804.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Comment by jckand-amzn** [comment]
This causes a test failure in test_LayerBlender_E2E_Launcher.
