### ISSUE TITLE
Standardize the SC nodes

### ISSUE THREAD

**Issue by svitlani** [o3de/o3de#4199]
[Jira LYN-4250]

Graph Canvas has a framework that will allow for the text replacement of any visual element. This system needs to be integrated into Script Canvas in order to allow for the text entry to be fully data driven.

With this in place, every node, title, tooltip, parameter name, etc. can be customized either internally or by the community.

This requires two parts:

First part, integrate the Graph Canvas text replacement framework into Script Canvas
Second part, update the generated content to be consistent, use the proper syntax, grammar and spelling
 
Examples:

Nodes should provide a clear parameter name shown on the SC node that's comprehensible.

This ticket can go one of two ways. 1 Each component team could own their nodes to make sure the nodes have readable parameters shown on the nodes. 2 have one developer lead the charge and follow up with any team about outstanding questions.

After speaking with Gene we believe this would be most effective to have someone come through and do a first pass of all the nodes and then we could have sub teams follow up (option 2).  If we leave this to individual teams, this full body of work might not get completed. 

 Steps to solve this issue:
UX and Doc teams to define a guideline 
This most effective way is to use the parameter names in the system and  force these names to be used inside the nodes.
Suggestion is to match the parameter to how it is in C++.

All First letters should be capitalized
Secondary words should only be capitalized if it's a proper noun.
20 characters should be the max. Everything else should go into an overflow ellipsis.
Would prefer the input fields align to one another as the do in component cards. Jagged edge makes it difficult to read.
Tooltips should focus on parameters unknowns. See example 1 below " Vector3: Negative values draw forever."  Any limitations should be specified via tooltips.
Please convert any useful code comments into tooltips. Some developers put these as developer comments but they should be tooltips for everyone.

**Comment by lsemp3d** [comment]
The vast majority of node categories and names have been standardized. There is work remaining to do a complete pass on tooltips and slot labels.
