### ISSUE TITLE
[Light/Directional Light component]The RGB values are different between color picker and Color field

### ISSUE THREAD

**Issue by instoneks2018** [o3de/o3de#4210]
**Describe the bug**
In Light/Directional Light component Editor, when editing the color with Color Picker, the RGB values are different between color picker and Color field.

**To Reproduce**

1.Open Editor.
2.Create a new Entity.
3.Add `Light`/`Directional Light` Component.
4.Modify the color of Base Color with the Color Picker.
5.Select a color `R/G/B` as `110`/`110`/`110`  respectively.
6.Don't close the Color Picker, and check the value in the Color of Base color.
7.The RGB values are different. The RGB value of Color in the Base Color is `40,40,40`.

**Expected behavior**
The RGB values should be the same.

**Screenshots**
![2](https://user-images.githubusercontent.com/45937683/133882503-e8a2ca9e-b3c5-43ac-bacb-90da8bfa2c37.png)

**Desktop/Device(please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Intel I7-10700 2.90GHz (16 CPUs)]
- GPU [Intel(R) UHD Graphics 630]
- Memory [32GB]

**Additional context**

**Comment by guillaume-haerinck** [comment]
I've checked the code and it is because the Light component and the Color Picker are not using the same RGB space. It is a deliberate choice made by the atom renderer in `ColorUtils.cpp` l.30

```cpp
configuration.m_propertyColorSpaceId = ColorSpace::LinearSRGB; // Change me to SRGB to have the match
configuration.m_colorPickerDialogColorSpaceId = ColorSpace::SRGB;
```

I haven't made a pull request because there might be underlying reasons for this choice that I do not grasp yet, but I hope this awnser will save some time for the future fix.

**Comment by santorac** [comment]
The difference in values is intentional. https://github.com/o3de/o3de/pull/12292 should help alleviate some of the confusion, by showing more color space information in the dialog.
