### ISSUE TITLE
Material Editor: Opacity Mode and Alpha Source values can bet set out of range which corrupts the material

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#4235]
**Describe the bug**
In the ReflectionProbeVisualization material type, values for Opacity Mode and Alpha Source can be set out of range. Saving the material afterwards corrupts the file which cannot be opened anymore.

**To Reproduce**
1. Open the Material Editor.
2. Create a new material with the ReflectionProbeVisualization type.
3. Set either the value of Opacity Mode to 4 or Alpha Source to 3.
4. Save the material and close it.
5. Open the previously saved material.

**Expected behavior**
The material cannot be saved with invalid values. The values cannot be set out of range.

**Screenshots**

![error](https://user-images.githubusercontent.com/86952009/134156726-36865a0a-17a7-41db-b358-54354e6459bc.JPG)

https://user-images.githubusercontent.com/86952009/134156732-86c3ec53-e548-4740-9602-908cbb2d6840.mp4

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Comment by gadams3** [comment]
The reflection probe visualization material and material type will no longer appear in the material editor. https://github.com/o3de/o3de/pull/8783

They should still be updated in the future to work like standard materials

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in Stabilization and Development.
