### ISSUE TITLE
Any component can be copy-pasted to the prefab

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#4236]
**Describe the bug**
It is possible to add any component to a prefab by copy-pasting it in the **Entity Inspector**. 
The components added to a prefab this way will retain their functionality. As an example, the **UI Canvas Asset Ref** component with a UI Canvas assigned and with "Load automatically" checked, will load this UI Canvas in the **Game Mode**.

Please note that copy-pasting the components with an effect visible in the **Viewport**, like **Mesh** or **PhysX Collider** to the Level prefab will result in displaying the assigned Mesh or Collider on the : X: 0, Y: 0, Z: 0 coordinates. Also, components copy-pasted to the Level prefab are not visible in the **Entity Inspector**.

**To Reproduce**
1. Add any prefab to the level.
2. Create an Entity with a **Mesh** component.
3. Assign a Mesh asset to the **Mesh** component.
4. Copy the **Mesh** component from the **Entity Inspector**.
5. Select the prefab.
6. Paste the **Mesh** component in the **Entity Inspector**.

**Expected behavior**
Only supported components can be pasted to prefabs.

**Video:**

https://user-images.githubusercontent.com/86951967/134166947-91adc03c-97cc-482f-8c5f-19edd7eefb9f.mp4

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-8700K
- GPU: NVIDIA GeForce RTX 2080 Ti
- Memory: 16GB

**Comment by monroegm** [comment]
Still reproduces as of baf6d47fc4

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed on build Development (5dd4d9f).
