### ISSUE TITLE
Multiple Gems are not building correctly

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#4237]
**Describe the bug**
Multiple Gems fail to build correctly, and depending on a build type (Source engine or Pre-built SDK engine as per https://docs.o3de.org/docs/welcome-guide/setup/setup-from-github/) the outcome is different. These Gems are:
* Multiplayer
* Custom Asset Example
* Scene Logging Example
* Scripted Entity Tweener
* Terrain
* Test Asset Builder
* Video Playback Framework
* Virtual Gamepad
* Wwise Audio Engine

If the engine is configured and built in Pre-built SDK engine type, the Projects built with these Gems configured, successfully build in the Project Manager. Despite that, the errors (shown in the **Screenshots and log**) section pop up and the functions provided by these Gems (e.g. Terrain components) are not available.

If the engine is configured and built in Source engine type, the Project that contains all the Gems fails to build at 99%. If for example only a Terrain Gem is added in, a different error pops up (shown in **Screenshots and log**), and the Editor can't launch until the Gem is removed. A log generated when build failed at 99% is attached in the **Screenshots and log** section

**To Reproduce**
1. In the Project Manager select New Project... > Create New Project.
2. Select a Minimal Project Template.
3. Click Configure Gems and add the following Gems to the Project:
* Multiplayer
* Custom Asset Example
* Scene Logging Example
* Scripted Entity Tweener
* Terrain
* Test Asset Builder
* Video Playback Framework
* Virtual Gamepad
* Wwise Audio Engine
4. Click Create Project.
5. Click Build Project and wait for the build to finish.
6. Click Open Editor.

**Expected behavior**
No errors are displayed, the Editor opens and added Gems are working properly.

**Screenshots and log**
Pre-built SDK engine - errors of each Gem:
* Multiplayer
![E1](https://user-images.githubusercontent.com/86952082/134163399-c4446e06-e4e3-4e2f-bf13-c8e1773acaae.PNG)

* Custom Asset Example
![E2](https://user-images.githubusercontent.com/86952082/134163460-b2427893-21e7-4e04-baab-041faf9d365f.PNG)

* Scene Logging Example
![E3](https://user-images.githubusercontent.com/86952082/134163760-7a54ad90-f7e0-4394-bb40-95c1ea6ea572.PNG)

* Scripted Entity Tweener
![E4](https://user-images.githubusercontent.com/86952082/134163792-50288229-725b-44dd-9771-04a7b77a66cd.PNG)

* Terrain
![E5](https://user-images.githubusercontent.com/86952082/134163811-90f0aead-205c-48e3-bfe1-41aaef11f5b4.PNG)

* Test Asset Builder
![E6](https://user-images.githubusercontent.com/86952082/134163826-bdd4f9f6-7eac-4f38-8ed0-966002bec118.PNG)

* Video Playback Framework
![E7](https://user-images.githubusercontent.com/86952082/134163843-fbef16d8-3a11-4a8e-83a4-fe4bd5378707.PNG)

* Virtual Gamepad
![E8](https://user-images.githubusercontent.com/86952082/134163853-d716eace-52e8-4d1e-afed-ce505c794151.PNG)

* Wwise Audio Engine
![E9](https://user-images.githubusercontent.com/86952082/134163875-2b0f7806-1998-4d57-adbe-f15bc6f9c518.PNG)

* Source engine - Terrain Gem error:
![E10](https://user-images.githubusercontent.com/86952082/134172101-eb210f78-2667-4347-a6c5-44ce44fb36d7.PNG)

* Source engine - Project fail at 99% when building with all Gems enabled:
[CMakeProjectBuildError.txt](https://github.com/o3de/o3de/files/7203071/CMakeProjectBuildError.txt)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by AMZN-alexpete** [comment]
@LB-ArturSiewniak, I think the reason this is failing is the path exceeds the maximum path limit.  From the logs:


```
moc: Cannot create C:/Users/GPC-610/.o3de/Projects/Test2AllGems921/build/windows_vs2019/External/EMotionFX-6e156490/Code/EMotionFX.Editor.Static_autogen/include_profile/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/moc_MotionEventPresetCreateDialog.cpp
```

This path is 261 characters long and Windows MAXPATH is 260.

Can you attempt to create the project in a folder with a shorter path and see if that succeeds?

**Comment by LB-ArturSiewniak** [comment]
I've created two projects with one-character-long names ("a" and "b" respectively):
* "a" was created following the Pre-built SDK engine type config/build, and there was no change in what was described in the issue description.
* "b" was created following the Source engine type, and the project actually did not fail, and the Gems in question were functional at a first glance (Terrain components were present, and Wwise project was correctly added, as well as usable in engine)

The issue then could be narrowed down to "Multiple Gems are not building correctly when following the Pre-built SDK engine type configuration and build".

**Comment by LB-ArturSiewniak** [comment]
The issue does not occur on the Development (9dc8500) build.

**Comment by amznestebanpapp** [comment]
> The issue does not occur on the Development ([cdf5a05](https://github.com/o3de/o3de/commit/cdf5a0519f3afae6b6e113b6d2989a1a3044928c)) build.

Is it safe to close?

**Comment by LB-ArturSiewniak** [comment]
I've checked it once again on Stabilization_2110 (7031147) build today with the Source type configured/built and the issue does not occur. However, due to https://github.com/o3de/o3de/issues/5643, I cannot verify it on the SDK type config/build. Once that issue is fixed, I will reverify it again and close this issue or let you know if it still occurs accordingly.

**Comment by brianherrera** [comment]
@LB-ArturSiewniak after #5643 is closed feel free to resolve this issue.

**Comment by amznestebanpapp** [comment]
@LB-ArturSiewniak  #5643 is closed, could you double check this one is safe to close?

**Comment by LB-ArturSiewniak** [comment]
Closing the issue, verified on the Development (ce709b9) build. Projects with all gems enabled built in both the Source and Pre-built SDK configurations do not show these errors anymore on launch. Sorry for the wait, must have overlooked this issue while retesting other ones. Merry Christmas!

**Comment by matlemuzic** [comment]
FYI, this issue is still present for me in the latest version 2205.0
