### ISSUE TITLE
Landscape Canvas - Undo of node deletion doesn't place node in previous position

### ISSUE THREAD

**Issue by tjmichaels** [o3de/o3de#4239]
[Migrated from JIRA LYN-2974]

*Reproducibility*: 100%

*Prerequisites*:

*Steps to Reproduce*:
 Launch the Editor
 Open the Landscape Canvas tool and create a new graph
 Add a Box Node to the graph
 Delete the node
 Press Undo hotkey

*Expected Result*:

Deleted Box Node should reappear in the same position as previous

*Actual Result*:

Deleted Box Node reappears but in the wrong position

**Comment by cgalvan** [comment]
Fixed by https://github.com/o3de/o3de/pull/12182
