### ISSUE TITLE
UE4 can modify parameters and view effects in real time while the game is running, but O3DE cannot.

### ISSUE THREAD

**Issue by nielianpeng** [o3de/o3de#4310]
**Describe the bug**
UE4 can modify parameters and view effects in real time while the game is running, but O3DE cannot.

**To Reproduce**
1. Start the engine and open an existing level.
2. Run the game

**Expected behavior**
1. The parameters can be modified.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel Xeon Gold 6234]
 - GPU [NVidia RTX 5000]
 - Memory [32GB]
 - Working Branch: Main branch e7f7875

**Additional context**

**Comment by forhalle** [comment]
Sig Core: You may want to consider this for RFC.

**Comment by amzn-pratikpa** [comment]
@nielianpeng Please create an RFC or discussion for this.
