### ISSUE TITLE
[Animation Editor] When there are two Actors in the Actors of the Actor Manager, click Save Selected Actor to save one Actor, and there is a possibility that the other Actor will be squeezed out

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#4314]
**Describe the bug**
[Animation Editor] When there are two Actors in the Actors of the Actor Manager, click Save Selected Actor to save one Actor, and there is a possibility that the other Actor will be squeezed out

**To Reproduce**
1. Load an Actor in the Actors of the Actor Manager, Merge an Actor
2. Select an Actor, click Save Selected Actor
3. Another actor disappears

**Expected behavior**
Both actors will exist

**Screenshots**

**Desktop/Device (please complete the following information):**
- Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel Xeon Gold 6234]
 - GPU [NVidia RTX 5000]
 - Memory [32GB]
 - Working Branch: Main branch e7f7875

**Additional context**

**Comment by lsemp3d** [comment]
Will revisit when the atom viewport is complete

**Comment by hultonha** [comment]
Discussed this with @amzn-jillich and with the Atom viewport you can only have one character so this issue is no longer relevant
