### ISSUE TITLE
Entity in a prefab disappears if it is parented to itself in another instance of the same prefab

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#4319]
**Describe the bug**
Parenting an Entity in a prefab to itself in another instance of the same prefab, results in both instances of this Entity disappearing from the level. Using Undo restores the Entity to the prefab.
Console output :

 `[Warning] (Prefab Serialization) - The target path for "add" operation is not an index value.
    Reason: The operation has halted during a merge operation for '/0' because a field or element has an invalid value.
[Error] (Prefab) - Some of the patches were not successfully applied.`

After performing previous actions parenting the mentioned prefabs to one another **may** (the reproduction rate is inconsistent) result in temporarily emptying the **Entity Outliner** (creating an Entity with RMB in the **Entity Outliner** or selecting any object in the **Viewport** resolves this issue, the **Entity Outliner** is populated again).

Please note that above-mentioned parenting actions were performed with the dedicated button in the **Entity Inspector**.

**To Reproduce**
1. Create a prefab with a child Entity.
2. Instantiate the created prefab (so there are two instances present in the **Entity Outliner**).
3. Select the Entity in one of the prefabs.
4. In the **Entity Inspector** use the dedicated parenting button to parent the Entity in the prefab to the second instance of that Entity in the second prefab.

**Additional steps for the Entity Outliner:**
5. Select one of the prefabs.
6. In the **Entity Inspector** use dedicated parenting button to parent the prefab to the another instance of this prefab.

**Expected behavior**
Proper warnings are displayed when trying to parent an Entity to itself in another prefab instance. The **Entity Outliner** display Entities and prefabs in all circumstances.

**Video**

https://user-images.githubusercontent.com/86951967/134687571-d8c35462-c6f6-43d9-8b03-5725752b8fcf.mp4

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-8700K
- GPU: NVIDIA GeForce RTX 2080 Ti
- Memory: 16GB

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. Focus mode has made it impossible to do this with the message "Invalid Assignment: You cannot set an entity to be a child of a closed container!"
