### ISSUE TITLE
[GNU/LINUX] Creating new Projects fails.

### ISSUE THREAD

**Issue by yaakuro** [o3de/o3de#4320]
**Describe the bug**

(Might be a feature request, not sure)

Creating a new project fails because of "Clang not found". Inside ProjectUtils_linux.cpp the version of clang is hardcoded. (clang-12|clang++12).  I know that a minimum version of clang wants to be forced but not using hard-coded numbers on GNU/Linux based systems would be better. (Until better solution is found. It could be possible to provide the location(file) of clang using the manifest file). (Development Branch)

**To Reproduce**
1. Start Editor
2. Create New Project
3. See error

**Expected behavior**
A new project should be created.

**Screenshots**
![O3DEProject](https://user-images.githubusercontent.com/7720708/134700014-8f111b47-cc4c-49a7-a0ed-d57af66e7f51.png)

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [GNU/Linux]
 - Version [Ubuntu 20.04 LTS]
 - CPU [Ryzen 5950x ]
 - GPU [NVidia RTX 1070]
 - Memory [128GB]

**Additional context**
Add any other context about the problem here
.

**Comment by Mobs1024** [comment]
@yaakuro you need to install clang-12 by default and the lower version does not support 

I am now checking build in o3de

**Comment by yaakuro** [comment]
I use clang 10 and it compiles and "works".

**Comment by Mobs1024** [comment]
branch: 66a875bf7974a1aa29ea7e89a87ac2bdaa9fc9a2

https://user-images.githubusercontent.com/17591539/134734687-9e92feea-1fbb-48c0-86f0-a343df001d6d.mp4

**Comment by yaakuro** [comment]
Not sure what you are proving here. I can see that you have clang12 installed. What I am saying is its better not to use hard-coded number of the compiler into the engine.

**Comment by Mobs1024** [comment]
@yaakuro you better join Discord there discussion with AMAZON devs.

**Comment by spham-amzn** [comment]
A specific version of clang is needed to generate the project with the current state of the cmake scripts. clang-12 is hardcoded here because that will be set as the compiler for the Jenkins AR runs. There was a discussion of pulling out these hardcoded values out of the Project Manager and using settings files, or even using [cmake-presets](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) somehow

**Comment by amzn-pratikpa** [comment]
@amznestebanpapp made this change which should fix this: https://github.com/o3de/o3de/pull/5376

@yaakuro can you try with the above change?

**Comment by amznestebanpapp** [comment]
> @amznestebanpapp made this change which should fix this: #5376
> 
> @yaakuro can you try with the above change?

He will still need the change from @spham-amzn because the Project Manager is hardcoding the version of clang, so it will try to use clang-9
@spham-amzn is going to remove that from the Project Manager so my change defines the compiler to use.

**Comment by spham-amzn** [comment]
This needs to be fixed in stabilization, will get that going tomorrow

**Comment by yaakuro** [comment]
@amzn-pratikpa I tests your PR and it seems to work (at least for me). It I don't have to use my own toolchain anymore so the system picks up my installed version of clang but as @amznestebanpapp  mentioned this PR isn't changing the Project Manager where the clang number is harcoded. 
@spham-amzn I guess is going to work on that. 

Really nice, finally no extra steps needed to get the engine compiled.

**Comment by spham-amzn** [comment]
This is fixed in stabilization/2110. Once it is merged back to development I will resolve this issue
