### ISSUE TITLE
 [Directional Light component]  Distorted shadow borders with transparent broadband like water stains

### ISSUE THREAD

**Issue by instoneks2018** [o3de/o3de#4349]
**Describe the bug** 
When `Shadow Filter Method` is set to `ESM+PCF` and disable `Enable Debug Coloring`, the shadow broadband appears  some transparent broadband like water stains.

**To Reproduce**
1.Open Editor.
2.Create a new Entity.
3.Add Directional Light Component.
4.Select `Shadow Filter Method` as `ESM+PCF`.
5.disable `Enable Debug Coloring`, view the shadow broadband.

**Screenshots**
![error](https://user-images.githubusercontent.com/45937683/134914088-9796d547-7a67-4d96-9edf-4fd7f99e02c0.png)

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Intel I7-10700 2.90GHz (16 CPUs)]
- GPU [Intel(R) UHD Graphics 630]
- Memory [32GB]

**Additional context**

**Comment by mrieggeramzn** [comment]
Integrated a fix from Real Time Shadows. Should look much better. It can still happen with very low-resolution shadows, but generally seems far better.
