### ISSUE TITLE
[GNU/LINUX] Screen half black squares from Atom SSAO on AMD cards (PostFX)

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#4379]
branch-devel: 29d9abba5767b09647d080f504e04ef965b7d4c9

**Describe the bug**
black square from meshes can not look normally and console hide all meshes black screen

**To Reproduce**
Open editor
meshes weird it is related Vulkan rendering

https://user-images.githubusercontent.com/17591539/135226792-63deeea7-e203-4dd3-9ea0-50e4af76c53e.mp4

https://user-images.githubusercontent.com/17591539/135226826-72001394-ec0f-461a-bec5-77840f4676a4.mp4

https://user-images.githubusercontent.com/17591539/135226842-eb064bf8-8b51-491d-b2c6-cc6d02c16280.mp4

https://user-images.githubusercontent.com/17591539/135228575-96d17e6c-9171-4ef7-bb8c-00cfa28b1bba.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: OpenSUSE
 - Version: Leap 15.3
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 20.2.4]
 - Memory: 16GB

**Comment by Mobs1024** [comment]
yesterday tested in Ubuntu 20.04.3 LTS also a black screen with a mesh like other distros

**Comment by Mobs1024** [comment]
found a black square error from post-processing SSAO from shader, and SSAO editor there by default enabled SSAO without PostFX Layer (Vulkan render is ok)

https://user-images.githubusercontent.com/17591539/137033618-20e3f0f7-c799-4b36-9794-48683ef31d84.mp4

**Comment by mrieggeramzn** [comment]
Unable to repro this bug on Windows + AMD Radeon 6800XT + Vulkan. However I did encounter lots of crashes / assertions.

**Comment by pollend** [comment]
umm, I think its related to linux + vulkan + amd 

here is a capture from renderdoc. EID 1124 is vkcmdClearColorImage in depthDownSample. 

![image](https://user-images.githubusercontent.com/854359/141606589-b42b672b-6641-49ad-9271-162d07729021.png)

**Comment by pollend** [comment]
```
diff --git a/Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupMerged.cpp b/Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupMerged.cpp
index 84b6cafa7..3752f9e7f 100644
--- a/Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupMerged.cpp
+++ b/Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupMerged.cpp
@@ -77,9 +77,9 @@ namespace AZ
 
             const Scope* scope = m_scopes[contextIndex];
             context.SetCommandList(*m_commandList);
-
-            scope->EmitScopeBarriers(*m_commandList, Scope::BarrierSlot::Aliasing);
+            
             scope->ProcessClearRequests(*m_commandList);
+            scope->EmitScopeBarriers(*m_commandList, Scope::BarrierSlot::Aliasing);
             scope->EmitScopeBarriers(*m_commandList, Scope::BarrierSlot::Prologue);
             scope->ResetQueryPools(*m_commandList);
             scope->Begin(*m_commandList);
```

so this aliase barrier is between passes. looks like the clear is getting placed into the next pass. 

before:
![image](https://user-images.githubusercontent.com/854359/141608854-8aa544a7-6a5f-4aea-9766-d247a19ce800.png)


after:
![image](https://user-images.githubusercontent.com/854359/141608869-1c99f615-34fb-4557-b288-604596e54aba.png)

**Comment by Darkinggq** [comment]
Сheck on Arch Linux, kernel 5.18.2-zen1-1-zen, Mesa 22.1.1, O3DE 22.05.0 problems are gone

https://user-images.githubusercontent.com/17591539/175926880-0facda81-c6f7-4c24-b93c-69923ae99b96.mp4

I don't know what's up with Ubuntu 20.04/22.04 LTS (depends on the Mesa driver version).
