### ISSUE TITLE
[GNU/LINUX] Load level they do not open gray screen

### ISSUE THREAD

**Issue by Mobs1024** [o3de/o3de#4382]
branch-devel: 29d9abba5767b09647d080f504e04ef965b7d4c9

**Describe the bug**
Create new level works well, reload o3de load level still won't open

```[Warning] XML reader: Can't open file (/home/xxxx/o3de/AutomatedTesting/Levels/Map_test/Level.editor_xml)```

**To Reproduce**

https://user-images.githubusercontent.com/17591539/135237509-0102aa6c-02f7-4b8d-a0d8-7b156b8cd87b.mp4

https://user-images.githubusercontent.com/17591539/135237539-55fcc627-dd67-4f79-a67f-5e11a9596c61.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: OpenSUSE
 - Version: Leap 15.3
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 20.2.4]
 - Memory: 16GB

**Comment by monroegm** [comment]
@Mobs1024 can you provide more information? We are not sure what the exact problem is here or how to reproduce it.

**Comment by Mobs1024** [comment]
updated today branch-devel 8a1af282c415675c9a71b2c5493b0bd00915bfcc , today I'm on Ubuntu 20.04 LTS testing on O3DE

https://user-images.githubusercontent.com/17591539/135544958-13171e5e-56e7-4fcd-b060-77b62018a654.mp4

https://user-images.githubusercontent.com/17591539/135544966-0876f87e-8caa-4345-a0b8-fac09b205539.mp4


it's not sure, i'm come back to distro SUSE Leap 15.3 later

**Comment by Mobs1024** [comment]
Suse Leap 15.3/Tumbleweed not long ago happened problem CMAKE not find path x11 in xcb and distros new kernel latest version problem with OpenSSL refusal for Editor on O3DE due to different version 1.1.0X VS 1.1.1X, I don't have time to figure this out (I thought Ubuntu is good, but other distros are waiting for the official testing of binaries and then check it again if it works or not)

https://discord.com/channels/805939474655346758/816043694762754088/889993956081938462
https://discord.com/channels/805939474655346758/816043694762754088/893573997978071040


Old Ubuntu 20.04 on O3DE load level works well so you can close the topic.
