### ISSUE TITLE
Corrupted Entities may remain after undoing duplication of Atom Default Environment child entities

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#4389]
**Describe the bug**
Duplicating the **Atom Default Environment** child Entities and undoing the action may result in creating an Entity without a name in the **Entity Outliner**. Performing actions on this Entity may result in an assert being thrown or the Editor crashing, specifically:
- Renaming the corrupted Entity throws an assert.
- Deleting the corrupted Entity crashes the Editor.

Please note that the reproduction of this issue is inconsistent. On one machine simply selecting the corrupted Entity resulted in a crash, on another machine it was not possible to rename the corrupted Entity by clicking on the empty name space of the corrupted Entity (using the F2 hotkey allowed the issue to be reproduced). The amount of child Entity duplication and undo tries required to reproduce the issue varies, in most cases the corrupted Entity appeared after performing above-mentioned actions 2-3 times.

**To Reproduce**
1. Create a new Level.
2. Open the created Level.
3. Select one of the **Atom Default Environment** child Entities.
4. Ctrl+D -> Ctrl+Z (please repeat this step multiple times, so that the corrupted Entity appears in the **Entity Outliner**).
5. Rename the corrupted Entity (assert is thrown).
6. Delete the corrupted Entity (Editor crashes).

**Expected behavior**
Undoing the duplication of the **Atom Default Environment** child Entities does not result in creating corrupted Entities in the **Entity Outliner**.

**Assert:**
File:
```
C:/builds/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp(489)
```

Line: 489

**Call Stack Trace:**
```
7) 00007FF8BC8CC347 (KERNELBASE) : UnhandledExceptionFilter
6) 00007FF8BEEB51B0 (ntdll) : memset
5) 00007FF8BEE9C766 (ntdll) : _C_specific_handler
4) 00007FF8BEEB20CF (ntdll) : _chkstk
3) 00007FF8BEE61454 (ntdll) : RtlRaiseException
2) 00007FF8BEEB0BFE (ntdll) : KiUserExceptionDispatcher
1) C:\builds\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\Instance\Instance.cpp (619) : AzToolsFramework::Prefab::Instance::GetContainerEntityId
```

**Video**

https://user-images.githubusercontent.com/86951967/135273753-325e07e6-631f-4bca-b4ab-77b69a5d8204.mp4

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-8700K
- GPU: NVIDIA GeForce RTX 2080 Ti
- Memory: 16GB

**Additional context**
[error.log](https://github.com/o3de/o3de/files/7252018/error.log)
[error.zip](https://github.com/o3de/o3de/files/7252020/error.zip)
[Editor.log](https://github.com/o3de/o3de/files/7252023/Editor.log)

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed.

**Comment by LB-JakubSkorupka** [comment]
Verified that issue does not occur on build Development (0ab9aa5)
