### ISSUE TITLE
FPS in Editor significantly lower than in play mode 

### ISSUE THREAD

**Issue by markusgod** [o3de/o3de#4435]
**Describe the bug**
In default level, FPS in non play mode FPS is around 20-30, when turning on play mode goes to 50

**Screenshots**
![PlayMode](https://user-images.githubusercontent.com/20001291/135611836-435f33d3-287f-4114-91cd-1bcd7d5920a6.png)
![EditMode](https://user-images.githubusercontent.com/20001291/135611831-fede4efd-6eff-42d0-925e-e949daea9402.png)

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Fedora 34]
 - CPU [Ryzen 2700x]
 - GPU [NVidia RTX 2080 Super]
 - Memory [32GB]

**Comment by forhalle** [comment]
@markusgod  - Can you please provide some repro steps or any other information we can use to understand this issue?

**Comment by markusgod** [comment]
> @markusgod - Can you please provide some repro steps or any other information we can use to understand this issue?

I'm not sure what can i provide. I'm just created project and fps was low right away, when I pressed "play" button in upper right corner and fps goes to 60, when exiting play mode goes back to 20ish
