### ISSUE TITLE
Track View: Editor crashes after changing the name of a previously deleted prefab entity

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#4436]
**Describe the bug**
The Track View tool does not update the status of deleted entities, which are a part of a prefab. Renaming the entity in the Track View tool after deleting it in the Entity Outliner crashes the Editor.

**To Reproduce**
1. Create a prefab entity.
2. Open the Track View tool.
3. Create a new sequence in the Track View tool.
4. Add the entity from the first step to the Track View tool.
5. Delete the entity in the Entity Outliner.
6. Change the name of the deleted entity in the Track View tool.

**Expected behavior**
Entity status is correctly updated in the Track View tool. The name is changed without issues. Editor remains stable.

**Call Stack Trace:**
```
25) 00007FFA6076C347 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFA62C951B0 (ntdll) : memset
23) 00007FFA62C7C766 (ntdll) : _C_specific_handler
22) 00007FFA62C920CF (ntdll) : _chkstk
21) 00007FFA62C41454 (ntdll) : RtlRaiseException
20) 00007FFA62C90BFE (ntdll) : KiUserExceptionDispatcher
19) C:\O3DE\o3de\Code\Framework\AzCore\AzCore\std\string\string.h (305) : AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator>::assign
18) C:\O3DE\o3de\Code\Editor\TrackView\TrackViewSequenceManager.cpp (305) : CTrackViewSequenceManager::RenameNode
17) C:\O3DE\o3de\Code\Editor\TrackView\TrackViewNodes.cpp (1406) : CTrackViewNodesCtrl::OnNMRclick
16) 00007FFA222C0DB9 (Qt5Core) : QObject::qt_static_metacall
15) 00007FFA1AB6619A (Qt5Widgets) : QWidget::customContextMenuRequested
14) 00007FFA1AB67FE6 (Qt5Widgets) : QWidget::event
13) 00007FFA1AC0A090 (Qt5Widgets) : QFrame::event
12) 00007FFA1AD69428 (Qt5Widgets) : QAbstractItemView::viewportEvent
11) 00007FFA222A3BDA (Qt5Core) : QCoreApplicationPrivate::sendThroughObjectEventFilters
10) 00007FFA1AB4499C (Qt5Widgets) : QApplicationPrivate::notify_helper
 9) 00007FFA1AB430E3 (Qt5Widgets) : QApplication::notify
 8) 00007FFA222A1B4A (Qt5Core) : QCoreApplication::notifyInternal2
 7) 00007FFA1AB9096E (Qt5Widgets) : QSizePolicy::QSizePolicy
 6) 00007FFA1AB8E80E (Qt5Widgets) : QSizePolicy::QSizePolicy
 5) 00007FFA1AB449B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
 4) 00007FFA1AB43A33 (Qt5Widgets) : QApplication::notify
 3) 00007FFA222A1B4A (Qt5Core) : QCoreApplication::notifyInternal2
 2) 00007FFA219634D1 (Qt5Gui) : QGuiApplicationPrivate::processMouseEvent
 1) 00007FFA2194EE89 (Qt5Gui) : QWindowSystemInterface::sendWindowSystemEvents
```

**Screenshots**

https://user-images.githubusercontent.com/86952009/135620479-a64e07d1-e9a1-44dc-ad98-e0a634a02e24.mp4

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Additional context**
[dump.zip](https://github.com/o3de/o3de/files/7267131/dump.zip)
[Editor.log](https://github.com/o3de/o3de/files/7267133/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7267134/error.log)

**Comment by AMZN-mnaumov** [comment]
can no longer repro

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in development and stabilization.
