### ISSUE TITLE
Terrain: Configured terrain does not properly render on reloading saved levels

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#4509]
**Describe the bug**
Configured terrain does not properly render on reloading saved levels. Hiding/Un-hiding the Terrain Layer Spawner entity causes a refresh and terrain then begins to display properly.

**To Reproduce**
1. Create a new level.
2. Select the Level entity, and Add Component > Terrain World and Terrain World Renderer.
3. Create a new entity in the Outliner.
3. Add Terrain Layer Spawner, Terrain Height Gradient List, and Axis Aligned Box Shape components to the entity.
4. Create a new child entity of the Terrain entity, and add Image Gradient, Gradient Transform Modifier, and Box Shape components to the entity.
5. Assign any valid image gradient to the Image Gradient component.
6. Add a new Gradient Entity to the Terrain Height Gradient List component, and pin to the configured Image Gradient entity.
7. Save the level, and open a different level.
8. Re-open the previously saved level.

**Expected behavior**
Configured terrain renders as expected on reloading a level.

**Screenshots**
![terrain_render_reload](https://user-images.githubusercontent.com/82226555/136113718-ffe7cc87-299d-4d9c-b95e-108c57b1618a.jpg)

**Comment by jckand-amzn** [comment]
This also occurs if the user configures terrain, and then enters/exits Game Mode.

**Comment by mbalfour-amzn** [comment]
This appears to be fixed.
