### ISSUE TITLE
ATL Controls Add menu has icons to the right of the Control types instead of left

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#4542]
**Describe the bug**
ATL Controls Add menu has the icons of Control types shown to the right of their names instead of left. This is inconsistent with how it was set up in the previous versions, and how the Filters menu is currently set up. Please refer to the https://github.com/o3de/o3de.org/issues/1005 issue for more information.

**To Reproduce**
1. Go to Tools > Other > Audio Controls Editor.
2. Under the ATL Controls section select the **Filters** button.
3. Under the ATL Controls section select the **+ Add** button.

**Expected behavior**
The icons are consistently on the same side.

**Screenshots**
Current ATL Controls Add menu:
![image](https://user-images.githubusercontent.com/86952082/136361240-f612f757-09c2-48a1-9cd0-d8f3fc2a62f8.png)

Previous ATL Controls Add menu:
![image](https://user-images.githubusercontent.com/86952082/136361812-7e3214ee-2a03-402b-802d-26184b13ef16.png)

Current ATL Controls Filters menu:
![image](https://user-images.githubusercontent.com/86952082/136361916-518dacb1-9e54-4851-a930-4b81580d3603.png)

Previous ATL Controls Filters menu:
![image](https://user-images.githubusercontent.com/86952082/136361929-9e8e8927-6cc3-4989-b7cc-b6614ff54e77.png)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by amzn-phist** [comment]
The sub-menus have been updated to look like the very first image in this issue (icons on right, text on left).  This is meant to follow the layout of other menus in the Editor, but they have been updated to be more consistent.

We still need to update docs to account for these changes, the docs issue linked above is still valid.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (4d4de66) build, however it still occurs on Stabilization_2205 (a073665) build.
