### ISSUE TITLE
Landscape Canvas：repeated Entity Name while deleting the node and adding new node

### ISSUE THREAD

**Issue by Alexlau1994** [o3de/o3de#4603]
**Describe the bug**
Repeated Entity Name while deleting the node and adding new node.

**To Reproduce**
1. Open Landscape Canvas
2. Add two nodes with entity name "Entity1" and "Entity2"
3. Delete node "Entity1" 
4. Add a node, and the node has default name "Entity2", which is already used.

**Expected behavior**

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by cgalvan** [comment]
Closing as this issue no longer occurs in latest commit `1649414d5f6e027a30e8da7074fd85b127cb0a8f`

Also creating new nodes in Landscape Canvas uses the general create entity API, so it doesn't control what the name will be. It will follow the general naming behavior for creating entities in the Editor.
