### ISSUE TITLE
Project Manager does not show any registered projects on first launch after a build

### ISSUE THREAD

**Issue by willihay** [o3de/o3de#4633]
**Describe the bug**
When launching Project Manager for the first time, after building the engine and project for the first time, PM did not show any registered projects, despite having been built inside of one that was already registered. While this behavior corrects itself if you quit PM and restart it, it is a source of confusion at the user-critical moment of "first launch". Restarting PM is not necessarily an intuitive fix.

**Steps to reproduce**

1. Start with a fresh O3DE source repo.
2. Delete any existing O3DE manifest from your user directory.
3. Run `o3de.bat register --this-engine` in the o3de engine source.
4. Create a default project using `o3de.bat create-project --project-path <project-path>`.
5. Build the project and project-centric source engine in the project directory using cmake.
6. Launch `o3de.exe` from the project's build output.

**Expected behavior**
Since the project was created and registered during project creation, it should appear as a project tile in Project Manager. (The AutomatedTesting project should also have been there.)

**Actual behavior**
No projects appear in ProjectManager on first launch. Instead, we see the "Ready? Set. Create." text and no projects.

**Assets required**
just the o3de source and system requirements

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: Windows 10 (20H2)

**Additional context**
This issue was observed after a fresh re-imaging of a PC, and after the first build of an O3DE engine + project. This might truly be a "first time user experience" issue, because I've had difficulty setting up a consistent repro after that by just deleting the manifest and re-registering an existing engine and project. Is there some config file or registry entry hanging around that prevents the issue from reoccurring later?

**Comment by AMZN-alexpete** [comment]
Have you recently verified the project was registered by looking in the O3DE manifest in the user directory after step 4?
This code has likely changed since this issue was created so I'd be surprised if it reproduces, but I take an attempt to repro with latest to check.

There is a Windows Registry key that stores whether the "first time" screen should be displayed or not, but the code specifically checks if there are any projects always. So you should never see it if you have any registered projects. 

```
    bool ProjectsScreen::ShouldDisplayFirstTimeContent()
    {
        auto projectsResult = PythonBindingsInterface::Get()->GetProjects();
        if (!projectsResult.IsSuccess() || projectsResult.GetValue().isEmpty())
        {
            return true;
        }

        QSettings settings;
        bool displayFirstTimeContent = settings.value("displayFirstTimeContent", true).toBool();
        if (displayFirstTimeContent)
        {
            settings.setValue("displayFirstTimeContent", false);
        }

        return displayFirstTimeContent;
    }
```

**Comment by willihay** [comment]
I'll see if I can try to repro again too, perhaps this time after deleting that Windows registry key, in addition to uninstalling and deleting all residual manifest files in my user directory.

**Comment by AMZN-alexpete** [comment]
Thanks for confirming @AMZN-nggieber !

**Comment by willihay** [comment]
For posterity, I can also confirm that this no longer repros on a clean PC that I just tried this on. The only thing that's still odd to me is that when you start Project Manager from a project that you have **just built**, Project Manager indicates that "Building project [is] required".
