### ISSUE TITLE
AWS: Resource Mapping Tool is missing on Linux

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#4655]
**Describe the bug**
There is no Resource Mapping Tool on the Linux build. After the user selects the AWS dropdown, the Resource Mapping Tool button is not present.

This issue does not occur on Windows.

**Steps to reproduce**
1. Open the Editor
2. Select the AWS tab.

**Expected behavior**
The Resource Mapping Tool button is present.

**Actual behavior**
The Resource Mapping Tool is missing.

**Found in Branch**
Development (ccd6051)

**Desktop/Device (please complete the following information):**
Device: PC
OS: Linux
Version Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU NVIDIA RTX 2060 SUPER
Memory 16GB

**Comment by lmbr-pip** [comment]
Closing as fixed.
