### ISSUE TITLE
Linux: Asset Processor does not recognize changes made to the files automatically

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#4656]
**Describe the bug**
Making a change to a file's name or changing its location is not automatically recognized by the Asset Processor. Using "Start Scan" from the Tools tab inside the Asset Processor is required for the file to be processed.

This issue does not occur on Windows.

**Steps to reproduce**

1. Launch the Editor.
2. Find an asset in the Asset Browser (_/home/o3de/AutomatedTesting/Assets/Objects/Foliage/cedar.fbx_ was used).
3. Find the asset from Step 2. in the file browser and change its name.
4. Observe the Asset Processor.

**Expected behavior**
Asset Processor does not recognize changes made to the files automatically.

**Actual behavior**
Asset Processor automatically recognizes changes made to the files.

**Video**

https://user-images.githubusercontent.com/86953659/137128554-b8d79cb8-a800-4e39-abab-226b5d12aac1.mp4

**Found in Branch**
Development (ccd6051)

**Desktop**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU: AMD Ryzen 5 3600
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 16GB

**Comment by byrcolin** [comment]
Haven't heard this being an issue lately, not critical because of work around, but still serious if true.
