### ISSUE TITLE
Linux: Undocked panes with multiple tabs cannot be moved by left-clicking and dragging them

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#4658]
**Describe the bug**
Undocked panes that contain multiple tabs cannot be moved by holding them with the left mouse button and dragging around. It should be noted that removing tabs until there is only one left does not fix this issue. Closing the whole tab group pane and opening the panes one by one allows the single panes to be moved again this way. It should also be noted that holding Super key (Windows key) + left-mouse button allows the pane with multiple tabs to be dragged around without issue.

This issue does not occur on Windows.

**Steps to reproduce**
1. Undock any pane (e.g. Entity Outliner).
2. Undock any other pane (e.g. Entity Inspector).
3. Dock one of the panes as a tab in the other pane.
4. Attempt to move the pane with the 2 tabs by left-click dragging.

**Expected behavior**
The pane should move with the cursor.

**Actual behavior**
The pane cannot be moved by left-clicking and dragging it.

**Video**

https://user-images.githubusercontent.com/86952082/137133237-2adf3f19-9d09-4e5f-b2dc-01575f79c07a.mp4

**Found in Branch**
Development (ccd6051)

**Desktop**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by pollend** [comment]
Looks like there are two title bars. Your unable to grab the second type. Just trying to port in features into the second bar and maybe it can be unified at some point.
