### ISSUE TITLE
Linux: Editor crashes when quickly browsing assets

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#4659]
**Describe the bug**
Quickly browsing through assets inside the Editor's browsers leads to a crash. The described behavior has been reproduced in the Asset Browser and different Component's browsers.

This issue does not occur on Windows.

**Steps to reproduce**

1. Open the Asset Browser.
2. Type any letter in the search box and start scrolling the results.

or:
1. Create a Mesh entity.
2. Select the 'browse' icon next to the 'Mesh Asset' field inside the Mesh component.
3. Type any letter in the search box and start scrolling the results.

**Expected behavior**
Browsing through the assets inside the Editor's browsers does not cause any issues.

**Actual behavior**
Browsing through the assets quickly inside the Editor's browsers leads to a crash.

**Video**

https://user-images.githubusercontent.com/86953659/137143534-d3498736-68ba-4d0c-a228-e4af16b88e8e.mp4

https://user-images.githubusercontent.com/86953659/137143576-4d2c0ecd-4fd4-4680-81e7-911171ba8f65.mp4

https://user-images.githubusercontent.com/86953659/137143600-fdc31022-fbc8-41f7-b973-d63a3e65b054.mp4

**Found in Branch**
Development (ccd6051)

**Desktop**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU: AMD Ryzen 5 3600
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 16GB

**Additional context**
The crash reproduces inconsistently: it can occur right after typing the first letter into a search box, but it may require more time spent scrolling the results.

**Comment by alexmontAmazon** [comment]
@cgalvan , could you check if this is Editor or asset related please?

**Comment by spham-amzn** [comment]
This is fixed with https://github.com/o3de/o3de/pull/4878
