### ISSUE TITLE
Feature Request: AssetProcessorBatch should log the list of failed assets when it completes

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#4706]
**Is your feature request related to a problem? Please describe.**
When the AssetProcessorBatch is run on AR it outputs the number of assets that were successfully processed and ones that failed. In order to discover which assets failed to process, the log output of the AssetProcessorBatch has to be scanned in order to locate the failed jobs. Such a process is not easy as it requires a keen eye to locate which assets actually failed to process as opposed to Assets that are logging warning information to the AssetBuilder, but are not failing.

**Describe the solution you'd like**
I think it would be beneficial if the AssetProcessorBatch output the list of failed assets when it is done running.
This could be similar to how GoogleTest outputs the list of failed tests at the end: ![image](https://i.stack.imgur.com/hye5h.png)

**Describe alternatives you've considered**
An alternative is use the searchable token of `AssetProcessor: Failed` that can be grep'ed in the log output.
The issue however is depending on the length of the log, Jenkins might not have the failure line loaded and would require the user scrolling up and selecting the "Show Complete Log" button which opens up a new page

**Additional context**
This is a screenshot of how the AssetProcessorBatch log looks at the end of an AR run:
![image](https://user-images.githubusercontent.com/56135373/137373772-d3506bd5-1024-4596-8757-02fb0ae9bbc7.png)

In that case, there was 1 asset that failed to process, but to discover the name of the asset the reader must scroll up in the log in order to locate.

**Comment by monroegm** [comment]
@amzn-mike Can you check if this has already been addressed?

**Comment by amzn-mike** [comment]
@monroegm It hasn't been addressed yet, Ill bring it up with the team, but we have a lot of high priority stuff that might make it difficult to get to this.
