### ISSUE TITLE
Linux: Game Mode does not capture mouse input

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#4722]
**Describe the bug**
Entering the Game Mode does not focus the mouse, making it impossible to register its inputs - for example the Fly Camera Input can be moved around using W, S, A, and D keys, but it cannot be rotated using the mouse.

This issue does not occur on Windows.

**Steps to reproduce**
1. Create a new level.
2. Press the "Play Game" button in the top right corner.
3. Move the mouse around.

**Expected behavior**
The Camera can be rotated by moving the mouse.

**Actual behavior**
The mouse cursor does not get captured by the Editor window.

**Video**

https://user-images.githubusercontent.com/86952082/137482484-86ace72a-01c9-4e8e-af78-6fe2a5973546.mp4

**Found in Branch**
Development (16e60a9)

**Desktop**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by burelc-amzn** [comment]
Fixed by #5275.

**Comment by LB-ArturSiewniak** [comment]
Issue verified as fixed on build Stabilization_2110 (fdc56b4).
