### ISSUE TITLE
Blast materials inside a Blast Material libraries can have duplicated names 

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4779]
**Describe the bug**
It is possible to create multiple blast materials with the same name inside a Blast Material library.
Materials with duplicated names are then visible in the Blast Family component.

For further information please refer to the attached video file.

**Steps to reproduce**

1. Launch the Editor and create a new level.
2. Open the Asset Editor.
3. Select File -> New -> Blast Material.
4. Add two or more new Blast Materials to the library and make sure they share the same name
5. Save the Blast Material library.
6. Open Tools > Blast Configuration (Experimental) and assign the created Blast Material library to the
Blast global configuration.
7. Create an entity with the Blast Family component.
8. Expand the Blast Material dropdown tab in the entity's Blast Family component.

**Expected behavior**
Blast Materialsmust have unique names in Blast Material libraries.

**Actual behavior**
Blast Materials with duplicated names can be saved in a Blast Material library.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/137887778-91d58b47-35b2-4c97-a34d-431ccc1498d8.mp4

**Found in Branch**

Development (b58ae15)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Comment by greerdv** [comment]
Closing this because material libraries have been removed (tagging @moraaar to confirm).

**Comment by moraaar** [comment]
Yes, thanks @greerdv!
