### ISSUE TITLE
Crash when clicking "open in script canvas editor" button in script canvas component

### ISSUE THREAD

**Issue by greerdv** [o3de/o3de#4782]
on development 064a72bbacccc1c221b02768899966f909eab8e7

![image](https://user-images.githubusercontent.com/82226198/137901807-8de14b32-3922-4247-b11e-aae02eaf9c55.png)

**Comment by cgalvan** [comment]
I'm not seeing this issue anymore in latest stabilization or development. Can anyone else reproduce it?

**Comment by lsemp3d** [comment]
Unable to repro, closing
