### ISSUE TITLE
Blast Material dropdown of a Blast Family component does not update with new materials when Blast Material library is changed in Blast Configuration

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4783]
**Describe the bug**
Changing assigned Blast Material library in Blast Configuration (Experimental) tool does not update Blast Family component of existing entities with new Blast Materials right away.

The found workaround is to deselect the entity with Blast Family component and selecting it once again which updates the Blast Family component.

For further information please refer to the attached video file.

**Steps to reproduce**

1. Launch the Editor and create a new level.
2. Open the Blast Configuration (Experimental) Tool and make sure a
Blast Material library is assigned. 
3. Create a new entity with Blast Family component and expand Blast Material dropdown tab of the component.
4. Assign a new Blast Material library in Blast Configuration (Experimental) Tool.
5. Expand the Blast Material dropdown tab in the entity's Blast Family component once again.

**Expected behavior**
Blast Material dropdown of Blast Family component updates with new Blast Materials right away.

**Actual behavior**
Blast Material dropdown of Blast Family component does not update with new Blast Materials

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/137904301-e102a3b5-525c-47a6-8500-9c7f25aef1a5.mp4

**Found in Branch**

Development (b58ae15)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Comment by moraaar** [comment]
Closing this bug since it's no longer valid. There is no material library anymore after the blast material refactor work.
