### ISSUE TITLE
Entity Outliner - hitting assert on reordering entities

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#4798]
**Describe the bug**
When reordering entities in the Outliner and moving an entity to the bottom of the Outliner, an assert is hit: "No child found for parent".

**Steps to reproduce**
1. Open a level in Prefab mode
2. open the Atom Default Environment
3. Select an entity that is not in the last position
4. Drag the entity to the last position
5. Profit

**Expected behavior**
The reordering operation does not error.

**Actual behavior**
An assert is shown. Note that ignoring the assert does not crash the Editor, but the entity is not reordered.

**Screenshots/Video**
![reorderAssert](https://user-images.githubusercontent.com/82231674/137985277-73ab8bf6-9372-4787-b74c-e0d19c34d782.gif)

**Found in Branch**
Latest development (9f5187b) built in debug

**Comment by hultonha** [comment]
Awesome! I'll close this issue out then 🙂

**Comment by AMZN-daimini** [comment]
Re-opening, will close once the cherrypick is submitted to stabilization :)

**Comment by AMZN-daimini** [comment]
Fix is now in stabilization.
