### ISSUE TITLE
[GNU/LINUX] The editor is frozens from Atom Bloom on AMD Cards (PostFX)

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#4812]
**Describe the bug**
Post effects add bloom enable immediately freeze the entire editor will not be able to exit only restart the PC

**To Reproduce**
Run editor ->

https://user-images.githubusercontent.com/17591539/138050553-5ea5506f-91d9-43de-be39-8eb19bfba644.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 20.04.03 LTS
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 21.0.3]
 - Memory: 16GB

**Comment by Mobs1024** [comment]
stabilization/2110 ba329378677590cdad0019c476cccccb5dec102f

https://user-images.githubusercontent.com/17591539/143003764-45d2b1dd-836a-4588-857d-e5a9efa73dea.mp4

[Editor.log](https://github.com/o3de/o3de/files/7587086/Editor.log)
[crash.log](https://github.com/o3de/o3de/files/7587087/crash.log)

**Comment by Magical10240** [comment]
PostFX bloom unknown problem in ubuntu 20.04 lts the button immediately crashes, and other distro opensuse tumbleweed works does not crash this is strange

https://user-images.githubusercontent.com/17591539/154491702-92c33c01-574d-403d-82ae-05e2a674e1d4.mp4

could it be a mesa driver problem?

ubuntu 20.04 lts **Mesa 21.0.3**
VS
opensuse Tumbleweed **Mesa 21.3.6**

**Comment by Darkinggq** [comment]
enable FX Bloom works fine in other non-Ubuntu distributions, Ubuntu still crashes (development 14076b4f932a768e9d12b041ca16a13903ac6be5)

**Comment by Darkinggq** [comment]
Verified fix on stabilization 2310.0 (ubuntu 22.04 lts)
