### ISSUE TITLE
[GNU/LINUX] FBX Settings any modifier to choose immediately crashes

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#4813]
**Describe the bug**
Сlick mesh in fbx settings add modifier ->

Comment (crash)
Level of Detail (crash)
Mesh (crash)
Skin (crash)
Coordinate system change (crash)
Tangents (crash)

all these crashes after the button

**To Reproduce**
Run editor ->  fbx settings ->

https://user-images.githubusercontent.com/17591539/138058893-89b1f352-4fa8-499c-8444-8d114bce899a.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 20.04.03 LTS
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 21.0.3]
 - Memory: 16GB

**Comment by lmbr-pip** [comment]
Should repro if this still occurs.

**Comment by pollend** [comment]
I did patch this in development a while ago should be fixed I believe.
