### ISSUE TITLE
Entities cannot be deleted from a prefab

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#4815]
**Describe the bug**
The following error message pops up after an attempt of deleting entity within a prefab:

`Cannot delete entities belonging to an instance that is not being edited.`

As there is no option to edit a prefab, it is impossible to delete an entity from it. However, adding and duplicating entities still works.

**Steps to reproduce**
1. Create a prefab.
2. Select an entity within a prefab and delete it using the RMB context menu.

**Expected behavior**
The selected entity is deleted or there is an option to enter the Edit Mode for a prefab.

**Actual behavior**
Entity cannot be deleted.

**Screenshots/Video**

![Zrzut ekranu z 2021-10-20 13-22-36](https://user-images.githubusercontent.com/86952009/138085294-6b89ef19-a2fa-4f03-b31d-fee5318b0268.png)

https://user-images.githubusercontent.com/86952009/138086668-05aec18a-2c22-4ccc-849a-398acc03c83e.mp4

**Found in Branch**
development https://github.com/o3de/o3de/commit/f31b47f775a15c4a669dca28ac023eca86c7e69e

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Comment by srikappa-amzn** [comment]
This is due to [one of the recent changes](https://github.com/o3de/o3de/commit/bcf3980de6295a1cb522f20e8482c3222625542c#diff-308bb40f413fd91e92bc448b7e35af07ddb3529cce9e2d21fb83872fa4847fb4) to focus mode that's currently in development and hidden behind a 'workinprogress' flag. 
@AMZN-daimini, fyi

**Comment by AMZN-daimini** [comment]
I have verified I cannot reproduce after this change is introduced:
https://github.com/o3de/o3de/pull/4840
