### ISSUE TITLE
[macOS] Launcher fails to run created levels

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4819]
**Describe the bug**
New levels created in the macOS Editor will fail to run in the macOS launcher.

Trying to load a newly created level in the launcher via _autoexec.cfg_ ,the `LoadLevel` command  or ImGui
will always result in a gray launcher screen.

This also blocks launching new levels on iOS as after deployment the app run on iOS will display a black screen with the debug overlay.

For further information please refer to the attached video file and log.

**Prerequisites**

* autoexec.cfg containing _loadlevel <level_name>_ is present in the AutomatedTesting folder.
* macOS assets were processed by Asset Processor.
* AutomatedTesting was set as the active project and built.

**Steps to reproduce**

1. Launch the Editor and create a new level with a name mathcing the one set in th _loadlevel <level_name>_ line
in autoexec.cfg
2. Save the created level and exit the Editor.
3. Run the following command in the terminal:
/Users/<home folder name>/o3de/osx_build/bin/profile/AutomatedTesting.GameLauncher.app/Contents/MacOS/AutomatedTesting.GameLauncher --project-path=AutomatedTesting
4. After the launcher opens try to run the created level with the `LoadLevel` command and ImGui.

**Expected behavior**
The created level correctly launches in macOS launcher.

**Actual behavior**
The created level does not launch in macOS launcher.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/138106408-207e2346-2144-4810-806c-41e21bea9a3d.mov

**Found in Branch**
Development (064a72b)

**Desktop/Device:**
- Device: Mac
- OS: macOS
- Version: Big Sur 11.3.1
- CPU: Intel Core i7 2,8 GHz
- GPU: Radeon Pro 555
- Memory: 16GB

**Additional context**
[macOS launcher log.txt](https://github.com/o3de/o3de/files/7381733/macOS.launcher.log.txt)
[iOS new level launch log.txt](https://github.com/o3de/o3de/files/7382116/iOS.new.level.launch.log.txt)

**Comment by srikappa-amzn** [comment]
@LB-MateuszSzweda , do you know if  this happens with prefabs enabled too?

**Comment by amzn-sj** [comment]
I'm unable to reproduce this issue on latest development. If I build with LY_PROJECTS set to AutomatedTesting, open the Editor and create a new level, save it, export to engine, wait for the AssetProcessor to finish processing the level assets, and launch AutomatedTesting, I'm able to load the level that I created without any issues.

**Comment by LB-MateuszSzweda** [comment]
I was also unable to reproduce the issue today on Development (47af914) with both prefab system enabled and disabled.
The created levels were loading and rendering correctly in a launcher.
So the issue can be closed.
