### ISSUE TITLE
[iOS] Deployed app fails to launch AutomatedTesting project default levels

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4823]
**Describe the bug**
Default levels of the AutomatedTesting project will fail to run in the iOS  GameLauncher app.

Trying to load a default level such as NvCloth_AddClothSimulationToMesh or aws/core via _autoexec.cfg_ 
on iOS device will always result in  a black screen without the debug overlay.

This was tested on Iphone 7 and Iphone 11 Pro using Macbook Pro 17 with Big Sur 11.3.1 and XCode version 12.5 as a software.

Please note that the aforementioned levels correctly launch in macOS GameLauncher.

For further information please refer to the attached logs.

**Prerequisites**

* autoexec.cfg containing _LoadLevel NvCloth_AddClothSimulationToMesh _ or _LoadLevel aws/core _ line is created and moved into AutomatedTesting folder.
* iOS assets were processed by Asset Processor.
* The **AutomatedTesting** project built for iOS and set as the active project.

**Steps to reproduce**
1. Deploy the App to an iOS device with Xcode.
2. Launch the App manually on iOS device or with Xcode.

**Expected behavior**
Level specified in autoexec.cfg correctly launches. 

**Actual behavior**
Level specified in autoexec.cfg fails to launch and app displays a black screen without the debug overlay.

**Found in Branch**
Development (064a72b)

**Desktop/Device:**
- Device: Mac
- OS: macOS
- Version: Big Sur 11.3.1
- CPU: Intel Core i7 2,8 GHz
- GPU: Radeon Pro 555
- Memory: 16GB

**Desktop/Device:**
- Device: iPhone 11 Pro
- OS: iOS
- Version: 14.7.1
- CPU: A13 Bionic
- GPU: A13 Bionic
- Memory: 6GB

**Additional context*
[iOS NvCloth_AddClothSimulationToMesh level launch log copy.txt](https://github.com/o3de/o3de/files/7382103/iOS.NvCloth_AddClothSimulationToMesh.level.launch.log.copy.txt)
*
[iOS aws_core level launch log copy (1).txt](https://github.com/o3de/o3de/files/7382105/iOS.aws_core.level.launch.log.copy.1.txt)

**Comment by srikappa-amzn** [comment]
@LB-MateuszSzweda , do you know if  this happens with prefabs enabled too?

**Comment by LB-MateuszSzweda** [comment]
@srikappa-amzn Unfortunately not. 
Due to time constraints linked to https://github.com/o3de/o3de/issues/4818
only AutomatedTesting project with prefabs disabled was tested.

@LB-KacperKapusta could have more insight as he planned to re run the test with Atom Sample Viewer project.

**Comment by LB-MateuszSzweda** [comment]
Today I was able to verify that this still occurs on Development (57adfd7) for both AutomatedTesting (prefab disabled) and New Projects. (Prefab enabled)

**Comment by byrcolin** [comment]
We added TJ because we think he might be helpful here.

**Comment by byrcolin** [comment]
@moudgils Can you verify this is fixed?

**Comment by moudgils** [comment]
Unfortunately we dont have capacity internally to verify. Given that this is a really old bug and we have since added support for iOS/android packaging my recommendation is to close this as fixed and re-open a new issue if this workflow is broken with hopefully current logs.
