### ISSUE TITLE
Saving a Script Canvas graph causes a soft lock

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#4857]
**Describe the bug**
The Editor enters soft lock state after saving a Script Canvas graph and neither the Script Canvas tool nor the Editor itself can be closed using standard methods.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Launch Script Canvas.
2. Create a new valid graph (i.e. On Graph Start -> Print ("Hello World!"))
3. Save the graph with any name in any location.

**Expected behavior**
The graph is saved successfully.

**Actual behavior**
The graph is not saved. The Editor becomes soft locked.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/138239801-bb6789a1-f143-454e-8429-462ef3a08f43.mp4

**Found in Branch**
Development (74d7405).

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU: AMD Ryzen 5 3600
 - GPU: Nvidia RTX 2060 SUPER
 - Memory: 16GB

**Comment by lsemp3d** [comment]
I just got latest development branch and could not reproduce it
