### ISSUE TITLE
Entering the Focus Mode of the Nested Prefab prints an error in the Console

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#4860]
**Describe the bug**
When the User starts editing the Nested Prefab, the following error is printed in the Console:

`[Error] (Tools Application) - Can not create a new Undo/Redo bach while an Undo or Redo operation is running.`

Please note, that the error contains a typo (_bach_ instead of _batch_).

Please refer to the attached video and screenshot for more details.

**Steps to reproduce**
1. Open any Level.
2. Create an entity and make a Prefab out of it.
3. Double click the Prefab (or RMB -> _Edit Prefab_).
4. RMB the Entity Outliner and select _Create Entity_.
5. Make a Prefab out of the entity created in the previous step.
6. Double click the Nested Prefab (or RMB -> _Edit Prefab_).

**Expected behavior**
No errors appear in the Console.

**Actual behavior**
An error appears in the Console.

**Assets required**
N/A

**Screenshots/Video**
![Error](https://user-images.githubusercontent.com/86953108/138259906-f71a27c9-31ab-45b0-b856-2180a070a5b6.png)

https://user-images.githubusercontent.com/86953108/138259910-ba946415-68b8-410a-bc8f-7a93b5271ee6.mp4

**Found in Branch**
Development (74d7405).

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU: AMD Ryzen 5 3600
 - GPU: Nvidia RTX 2060 SUPER
 - Memory: 16GB

**Comment by AMZN-daimini** [comment]
I could not reproduce this in latest stabilization. Please re-open if the issue resurfaces.

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed on Stabilization/2305 (c4dd0ce) as well as Development(785c187) build.
