### ISSUE TITLE
Linux: Editor crashes after entering Simulate Mode when Viewport has three or more separate render windows

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#4861]
**Describe the bug**
Editor crashes upon launching Simulate Mode when a configuration layout is switched to three or more separate render windows. The same issue occurs after leaving Game Mode.

**Prerequisites:**
- Prefab System enabled.

**Steps to reproduce**
1. Create a level.
2. Navigate to View > Viewport > Configure layouts.
3. Choose any layout with at least three separate windows.
4. Launch Simulate Mode.

**Expected behavior**
Editor remains stable. Simulate Mode is enabled.

**Actual behavior**
Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/138257806-35d170ac-143e-4478-8178-f190e8683942.mp4

**Found in Branch**
development (f31b47f)

**Desktop/Device (please complete the following information):**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Additional context**
[crash.log](https://github.com/o3de/o3de/files/7388084/crash.log)
[Editor.log](https://github.com/o3de/o3de/files/7388085/Editor.log)

**Comment by hultonha** [comment]
@jiaweig-amzn (this corresponds LYN-7630) just wanted to follow-up if this in on your list of things to look at, shall I remove `feature/viewport` and add `feature/atom`? Thanks!

**Comment by jonawals** [comment]
Confirmed this appears to be Linux-specific, cannot reproduce on Windows as per commit `adf3357176d1644628a0fcf90d68ce0800ae056b`.

**Comment by hultonha** [comment]
Comment from @spham-amzn 

> This appears to be an issue with Vulkan, not specifically Linux. The Editor crashes if it is launched using vulkan
> Editor.exe -rhi=vulkan

**Comment by pollend** [comment]
> Comment from @spham-amzn 
> 
> > This appears to be an issue with Vulkan, not specifically Linux. The Editor crashes if it is launched using vulkan
> > Editor.exe -rhi=vulkan
> 
> 

I think there is some kind of resource leak. If you change the layout a couple time the system will get progressively slower.

**Comment by jiaweig-amzn** [comment]
The crash seems to be fixed by some other swapchain fixes.
https://github.com/o3de/o3de/pull/5502
https://github.com/o3de/o3de/pull/5388
But the render target doesn't fit the viewport. I am still investigating.

**Comment by hultonha** [comment]
Good to know, thanks for the update @jiaweig-amzn

**Comment by LB-BartoszDudzinski** [comment]
Closing as Fixed in Stabilization/2110 branch. The crash does not occur anymore. The new exposed issue is tracked in jira.
