### ISSUE TITLE
Projects located in .o3de directory fail to detect Blast Material libraries

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4867]
**Describe the bug**
Projects located in the default _\Users\<user name>\.o3de_ directory will fail to detect and load Blast Material libraries in the Blast Configuration (Experimental) Tool.

This affects both newly created projects and projects that can be moved from source o3de directory such as AutomatedTesting, which has no problems with detecting existing Blast Material libraries when located in source o3de directory.

The issue occurs for these projects no matter where the _.blastmaterial_ file is located.

For further information please refer to the attached video file.

**Steps to reproduce**

1. Launch the O3DE Project Manager.
2. Navigate to _New Project... -> Create New Project_.
3. Create a new project in _\Users\<user name>\.o3de_ directory and build it with
**NVIDIA Blast**, **Python Asset Builder** and **Editor Python Bindings** Gems enabled.
4. Launch the built project and create a new level.
5. Open the Asset Editor and select _New -> Blast Material_.
6. Create a new Blast Material library and save it in the project's directory.
7. Open the _Blast Configuration (Experimental)_ Tool and try to assign any Blast Material library to it.

**Expected behavior**
Blast Material library is detected and can be assigned to the Blast Configuration (Experimental) Tool.

**Actual behavior**
Blast Configuration (Experimental) Tool fails to detect any _.blastmaterial_ files .

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/138284323-ff6fec8a-8d77-4918-9b99-9cae5f93cf0b.mp4

**Found in Branch**

Development (74d7405)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Comment by greerdv** [comment]
@moraaar can this be closed now?

**Comment by moraaar** [comment]
Yes, closing this because material libraries have been removed.

@LB-MateuszSzweda if you find the same issue with the new blast material assets (creating a blast material and the asset browser is unable to find it) please open a new bug.

Thanks.
