### ISSUE TITLE
Landscape Canvas: Node titles in Debug configuration are garbage values

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#4872]
**Describe the bug**
Node titles in Debug configuration are garbage values.

**Steps to reproduce**
1. Build the Editor to launch AutomatedTesting in Debug configuration.
2. Launch the Editor.
3. Open Landscape Canvas, and add any node to the open graph.

**Expected behavior**
Node titles are legible.

**Actual behavior**
Node titles are garbage values.

**Screenshots/Video**
![landscapecanvas2](https://user-images.githubusercontent.com/82226555/138306898-fad5ff4e-1914-4410-96a9-a218d2b8cc33.png)

**Found in Branch**
development@151d0a33c20

**Comment by cgalvan** [comment]
Re-opening this issue. Please note, it only occurs in Debug mode.
