### ISSUE TITLE
“EditorMaterialSystemComponent” missing

### ISSUE THREAD

**Issue by bitTalk1** [o3de/o3de#4895]
![图片](https://user-images.githubusercontent.com/11308319/138372564-c17dcb21-0c00-486d-9d97-40045bae930b.png)
![图片](https://user-images.githubusercontent.com/11308319/138372673-a30a9df3-c576-4aa2-a058-0c9f4a832d92.png)

**Comment by monroegm** [comment]
@bitTalk1 can you provide more info about the steps to reproduce?

**Comment by monroegm** [comment]
@bitTalk1 Please reopen if you are able to provide more information
