### ISSUE TITLE
Prefabs: Unactionable Error messaging sometimes throws when working with Prefabs

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#4934]
**Describe the bug**
Unactionable Error messaging sometimes throws when working with Prefabs:

`[Error] (Prefab) - Invalid asset found referenced in scene while entering game mode`

**Steps to reproduce (Exact Steps Unknown)**
1. Instantiate/Delete/Restructure various Prefabs
2. Enter/Exit Game Mode
3. Repeat as necessary

**Expected behavior**
Error messages are actionable.

**Actual behavior**
Occasionally, an error message throws which does not point the user to any particular asset or prefab, and is difficult to pin down where/why it is throwing.

**Found in Branch**
development@f962f3d8164e522c9

**Comment by raktalen** [comment]
Is there a specific asset that you have that throws this error ? Or perhaps more specific repro steps ?
One of the ways this could happen is if an asset that was set as a reference while edit time was deleted and then a user tried to enter the game. We could try to hint the user towards the specific asset field in question.
Repro would be useful though.

**Comment by raktalen** [comment]
I'll check this out @monroegm can you assign to me ?

**Comment by jckand-amzn** [comment]
Have not encountered this particular error messaging any time in recent memory, but will keep an eye out. Repro steps being fleshed out is very difficult as (at the time) the message was seen with several different assets, but never reported which asset was actually the issue. Maybe improved error messaging could help pinpoint the actual issue.

**Comment by raktalen** [comment]
# Mini Postmortem
A Number of issues were discovered while exploring this. A summary follows

# Issues

## A few default assets are invalid
### Material component (MaterialSlots)
The default asset getter for the *Default material* field returns an invalid asset Id
### EditorTerrainPhysicsColliderComponent
The default asset getter for the *Entire object* field returns an invalid asset Id

## Default assets erroneous messaging
### Invalid default assets
Invalid default assets have incorrect messaging in the editor (This has been addressed [here](https://github.com/o3de/o3de/pull/13959) )

## Unassigned assets show an error message
Assets could be rightly unassigned , this should at best be a warning.
Ideally, the asset field communicates with the reflect context and shows an error if the asset is required.

## Assets that are assigned and then deleted do not have proper error messaging
### Asset persistence
Assets that are assigned and then deleted stay in memory for that editor session, causing the editor or game to work with an in memory image, potentially causing crashes in the editor or game (if exported in this state). This is a larger issue, perhaps something that we may just have to live with.
A sidenote on the user impact of this issue; An infrequent but frustrating situation could arise wherein team member A deletes some files and tests the game using *Play In Editor* then checks the deletions in confidently.
Then *perhaps many days later* something mysteriously stops working for Team member B.

### Deleted Asset Error messaging
There was no error messaging for assets that were assigned and deleted in previous editor sessions  (This has been addressed [here](https://github.com/o3de/o3de/pull/13959) )
