### ISSUE TITLE
FindWwise.cmake uses incompatible version of Wwise if multiple Wwise versions installed

### ISSUE THREAD

**Issue by soesin** [o3de/o3de#4945]
**Describe the bug**
A clear and concise description of what the bug is. Try to isolate the issue to help the community to reproduce it easily and increase chances for a fast fix.
If older version of wwise is installed, cmake uses older version instead of the proper version.

**Steps to reproduce**
1. Lumberyard installed with wwise.
2. Follow the instruction in Setup page.
3. At the build process, it stops while building the sound gem.

**Expected behavior**
Use proper version of wwise for build the project.

**Actual behavior**
Grab older version of the wwise.

**Assets required**
N/A

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
develop branch.[74d7405]

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Version: 21H1
 - CPU Ryzen 3850X
 - GPU Nvidia GTX 2070super
 - Memory: 32GB

**Additional context**
Posted to the discord channel of https://discord.com/channels/805939474655346758/861713485725433857/900844680089071717
and get quick solution to use LY_WWISE_INSTALL_PATH 

Ideally, FindWise.cmake should validate the version.

**Comment by lumberyard-employee-dm** [comment]
@FiniteStateGit just hit this issue with having an older version of Wwise LTX 2018 installed on his machine for using with the old Lumberyard codebase.
We should update the [is_valid_sdk](https://discord.com/channels/805939474655346758/816043576034328636/970836288938840134) function in cmake to add a [VERSION_GREATER_EQUAL](https://cmake.org/cmake/help/latest/command/if.html#version-greater-equal) to validate the Wwise version to be greater than what is listed on [o3de.org](https://www.o3de.org/docs/user-guide/gems/reference/audio/wwise/audio-engine-wwise/#enabling-the-wwise-audio-engine-gem)

**Comment by amzn-phist** [comment]
I can add that.  I have some old code somewhere where I was extracting the version string but ended up removing it because we only printed it to screen.  If we actually add a version check, then that code will be useful.
