### ISSUE TITLE
AWS: Editor does not read provided credentials

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#4952]
**Describe the bug**
After credentials are provided in any way described in the documentation, the Resource Mapping Tool displays an error "Credentials are missing or invalid."
Link to the documentation:
https://o3de.org/docs/user-guide/gems/reference/aws/aws-core/configuring-credentials/

**Steps to reproduce**
1. Download the credentials .csv file.
2. Import credentials. (e.g. "aws configure import --csv file://credentials.csv")
3. Wait for confirmation that the credentials were imported successfully.
4. Open the Editor.
5. Select AWS->Resource Mapping Tool.

**Expected behavior**
The Resource Mapping Tool opens.

**Actual behavior**
An error is displayed.

**Screenshots/Video**

![InvalidCredentials](https://user-images.githubusercontent.com/86952591/138687127-a7d79eaa-39f7-4b51-8933-f03876f2df9b.jpg)

**Found in Branch**
Development (9438fbe)

**Desktop/Device (please complete the following information):**
Device: PC
OS: Windows
Version Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU NVIDIA RTX 2060 SUPER
Memory 16GB

**Comment by forhalle** [comment]
I confirmed with @yuyihsu this bug is for WF10 only (not WF6)

**Comment by LB-JakubSkoczylas** [comment]
@junbo75 Changing the Registry manually fixed the problem. I have access to the Resource Mapping Tool.
