### ISSUE TITLE
AR Bug Report: Random jenkins build issue with AssetProcessorMessages.All test

### ISSUE THREAD

**Issue by VickyAtAZ** [o3de/o3de#4967]
**Describe the bug**
[intermittent failure] a random jenkins build issue with AssetProcessorMessages.All test

**Failed Jenkins Job Information:**
The name of the job that failed, job build number, and code snippit of the failure.
Linux test profile non-unity build 
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-4739/6/pipeline/

`[ RUN      ] AssetProcessorMessages.All[2021-10-25T06:16:36.624Z] ../../Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp:220: Failure[2021-10-25T06:16:36.624Z] Value of: finished[2021-10-25T06:16:36.624Z]   Actual: false[2021-10-25T06:16:36.624Z] Expected: true[2021-10-25T06:16:36.624Z] Timeout[2021-10-25T06:16:36.624Z] ../../Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp:303: Failure[2021-10-25T06:16:36.624Z] Value of: SendRequest(*pair.m_request.get(), *pair.m_response.get())[2021-10-25T06:16:36.624Z]   Actual: false[2021-10-25T06:16:36.624Z] Expected: true[2021-10-25T06:16:36.624Z] Message RequestAssetStatus failed to send[2021-10-25T06:16:36.624Z] ../../Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp:320: Failure[2021-10-25T06:16:36.624Z] Value of: m_assetRequestHandler->m_invoked[2021-10-25T06:16:36.624Z]   Actual: false[2021-10-25T06:16:36.624Z] Expected: true[2021-10-25T06:16:36.624Z] Message RequestAssetStatus was not received[2021-10-25T06:16:36.624Z] [  FAILED  ] AssetProcessorMessages.All (5814 ms)`

**Attachments**
Attach the Jenkins job log as a .txt file and any other relevant information.

[linuxUnitTests.txt](https://github.com/o3de/o3de/files/7412794/linuxUnitTests.txt)

**Additional context**
The issue was gone after triggers the AR again without any change.

**Comment by lmbr-pip** [comment]
Team has spent a lot of time trying to reproduce without success, marking as did not reproduce. Please reopen if this still occurs.
