### ISSUE TITLE
User can only add one character at a time in the Tag name in PhysX Collider component

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4994]
**Describe the bug**
Typing in any text inside the PhysX Collider's Tag text box defocuses the text box after the initial letter/number is inputted.

Please note that this does not affect the PhysX Shape Collider component.

For further information please refer to the attached video file. 

**Steps to reproduce**

1. Open the Editor and create a new level.
2. Add an entity to the level.
3. Add the _PhysX Collider_ component to the created Entity.
4. Try to type the Tag name in the PhysX Collider Tag text box.

**Expected behavior**
User is able to input a full Tag name.

**Actual behavior**
The Tag text box defocuses after the initial letter/character of the Tag name is inputted.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/138882394-3b783812-b661-494f-b14a-d878ccb2af24.mp4

**Found in Branch**

Development (9438fbe)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Comment by LB-MateuszSzweda** [comment]
Tagging @hultonha  as per request on PhysX issues that stand out in during exploratory testing and user workflow scenarios.

**Comment by rainbj** [comment]
@AMZN-daimini and @cgalvan. It appears tags system is missing some core details from the QT system. Typing should use autocomplete dropdown. Confirmed tags should be added as a separate row below the current input field. Same as filter for outliner. Example = [title  x] .

Can we find a way to use these two QT components as a new component to make a tagging system that is universal?

**Comment by rainbj** [comment]
Put together some of our previous ideas around using tags. Not saying we need all the layers in this design document but a direction we can head towards. Most importantly. As we start to use tags all over the editor we would like a QT component that is the main control we recommend people to use. https://www.figma.com/file/UjT2A15cdpwF4to78lOPT0/Tags?node-id=1%3A639

**Comment by cgalvan** [comment]
@hultonha  Do you know the other GHI issues for this? I was able to repro, it does seem isolated to only certain input fields, so it might be an attribute they are using. I think there are two concerns at play here:

1. There is definitely a bug where the input field is losing focus after typing a single character. We need to fix this first.
2. Looks like @rainbj has some great ideas to improve the usability of our tags system in general that we should look at incoporating!

**Comment by hultonha** [comment]
Thanks very much for the update @LB-MateuszSzweda, that's super helpful, we must be doing something odd in the PhysX Collider UX then (it's good to know it's not a wider issue). We've got this on our list and will review if we'll have to time to take a look at it early next week. Thanks!

**Comment by pollend** [comment]
> @hultonha I've think this used to happen with Tag textboxes in overall especially in Ragdoll section of Animation Editor but today I've checked all of Animation Editor, PhysX Configuration, Material Editor and Entity Inspector components textboxes in search for this and the **PhysX Collider** Tag was the only textbox that had this issue.

I looked at this momentarily that section of the view is just getting rebuilt every time you press a key. its why you see that stutter in the inspector.

**Comment by hultonha** [comment]
> > @hultonha I've think this used to happen with Tag textboxes in overall especially in Ragdoll section of Animation Editor but today I've checked all of Animation Editor, PhysX Configuration, Material Editor and Entity Inspector components textboxes in search for this and the **PhysX Collider** Tag was the only textbox that had this issue.
> 
> I looked at this momentarily, the inspector is just getting rebuilt everytime you click and change the text of the tag. you can see a stutter in the UI. There are other text fields in that don't do this seems exclusive to only Physx components?

Thanks for looking into this @pollend - this is something we know about but haven't had time to look into. If you're able to come up with a fix that doesn't cause any other unintended consequences we'd love to see it! 🙂

**Comment by LB-ArturZieba** [comment]
On the Development (99f7137) build I've noticed that this issue extends to changing any other parameter using the left-click/drag as well. If the entity also contains a PhysX Dynamic Rigid Body component, modifying its parameters the same way also causes this issue.

**Comment by LB-ArturZieba** [comment]
@cgalvan After further investigation, the issue I described was in fact caused by the presence of PhysX Mesh Collider component. This is already reported and can be found here: https://github.com/o3de/o3de/issues/10054. I have confirmed that the https://github.com/o3de/o3de/issues/10054 still occurs on both Development (50b62ea) and Stabilization/2305 (25641ec) builds.

**Comment by LB-MateuszSzweda** [comment]
Issue verified as fixed in Stabilization/2310 (25641ec) for all available PhysX Collider type components but it still occurs in Development (50b62ea) for a **Mesh Collider** component.
