### ISSUE TITLE
Some of the Script Canvas PhysX nodes attached to On Entity Activated do not execute when dynamic slice is spawned

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#5001]
**Describe the bug**
Some of the PhysX RigidBody nodes attached to _On Entity Activated_ node do not apply it’s effects on Entity if it’s spawned as dynamic slice via Spawner.

Aforementioned nodes are:
**Apply Linear Impulse
Set Linear Velocity
Apply Angular Impulse
Set Angular Velocity**

Please note that issue occurs only when Entity is spawned via spawner, the prefabs are not affected.

There is possible workaround:
Insert a 0.001 delay between the On Entity Activated and PhysX RigidBody nodes

For further information please refer to the attached video file.

**Prerequisites**

* Build o3de project with slice system enabled such as AutomatedTesting by default.

**Steps to reproduce**

1.Create Entity.
2. Add PhysX RigidBody, ScriptCanvas and Mesh components to newly created Entity.
3. Select any visible mesh in Mesh Asset property of Mesh component (primitive_cube.cgf for example).
4. In Script Canvas component press Open in Script Canvas Editor button.
5. Add On Entity Activated node to graph.
6. Add and attach to aforementioned node PhysX RigidBody Set Angular Velocity node.
7. Set Y property of Set Angular Velocity to 20.
8. Save the script.
9. In Main Editor navigate to Entity Outliner
10. Create slice from Entity created in step 1.
11. In Asset Browser find slice created in previous step and set it as Dynamic Slice.
12. Create new Entity and add Spawner component to it.
13. Set Dynamic slice property of Spawner Component to dynamic slice created in step 11.
14. Enable Spawn on activate checkbox.
15. Enter Game Mode (CTRL + G).

**Expected behavior**
Spawned entity spins in Y axis as its angular velocity is changed to 20 via script.

**Actual behavior**
Script seems to have no impact on spawned entity.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/138903962-e0d6fa26-44e6-4b0b-924e-b388d03d0189.mp4

**Found in Branch**

Development (9438fbe)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Comment by LB-MateuszSzweda** [comment]
As per the comment above the issue was re-verified today as not occurring with spawned prefabs.

**Comment by moraaar** [comment]
Thanks @LB-MateuszSzweda! That's great.
