### ISSUE TITLE
Joint component does not detect rigid body in lead entity when spawned from a dynamic slice

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#5010]
**Describe the bug**
When a dynamic slice consisting of a lead entity for joint components and its children is spawned warnings about missing rigid body components in the lead and children entities can be seen in the console.

**Steps to reproduce**

1. Launch the Editor and create a new level
2. Create an entity with 3 children entities.
3. Add tge PhysX Rigid Body and the PhysX Collider component to all entities.
4. Add the PhysX Fixed Joint component to the children entities and select the parent entity as a Lead.
5, Save the parent entity as a dynamic slice.
6. Remove all entities in the level.
7. Create a new entity with the Spawner component.
8. Select a saved dynamic slice as a Dynamic slice for the Spawner component and
enable _Spawn on Activate_
9. Enter the Game Mode.
10. Check the console.

**Expected behavior**
No warnings are printed in the console about missing rigid body components in the lead and children entities.

**Actual behavior**
Warnings are printed in the console about missing rigid body components in the lead and children entities.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/138923126-31377dbc-ca0e-421d-b9c9-d1c562a1c043.mp4

**Found in Branch**

Development (9438fbe)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Comment by greerdv** [comment]
Does this problem happen with prefabs as well? Slices will be deprecated in favour of prefabs, so bugs with slices are not heavily prioritized.

**Comment by LB-MateuszSzweda** [comment]
@greerdv  I have verified that this does not occur with prefabs against stabilization/2110 (99d0c39) and Development (7975629) .
Spawning had to be done with Script Canvas Spawning>Spawn node as the Spawner component does not support spawning prefabs.

**Comment by greerdv** [comment]
Closing since this doesn't occur with prefabs.
