### ISSUE TITLE
Remove old packaging scripts/files

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#5049]
**Is your feature request related to a problem? Please describe.**
Cleanup, we have files and scripts related to the old packaging method. Old packaging is replaced by install and installer

**Describe the solution you'd like**
Remove all files related to packaging, some examples:
- scripts\build\Platform\Windows\package_build_config.json
- scripts\build\package

**Comment by amzn-changml** [comment]
The validation scripts depend on some of the scripts contained in this path. We need to remove or disassociate this dependancy.
