### ISSUE TITLE
Viewport starts flashing when using Vulkan with vsyn_interval=0

### ISSUE THREAD

**Issue by thefranke** [o3de/o3de#5077]
**Describe the bug**
When using Vulkan as RHI and setting vsync_interval=0, the viewport randomly flashes black. I've attached a video. May also crash the Editor after a while.

**Steps to reproduce**
1. Run the Editor with Vulkan as RHI
2. Open the `Console Variables` window
3. Search for `vsync_interval` and set it to 0

**Expected behavior**
Rendering is free of artifacts.

**Actual behavior**
Seemingly random frames drop out with the viewport being black.

**Assets required**
Used the Sponza scene from the AtomTest project.

**Screenshots/Video**
https://i.imgur.com/rUTV6lO.mp4

**Found in Branch**
`development`

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: i7-8665U
 - GPU: Intel UHD 620
 - Memory: 16GB

**Comment by jiaweig-amzn** [comment]
It should be fixed by the 2 linked PRs. They will get to development branch from stabilization/2110 soon.
