### ISSUE TITLE
Surface Data changes don't trigger an OnTerrainDataChanged message

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#5092]
**Describe the bug**
Changing the data that feeds into TerrainSurfaceMaterials list doesn't cause the rendered surface data to update, since OnTerrainDataChanged is never triggered with a SurfaceData flag.

**Steps to reproduce**
1. Run the Editor with a project with Terrain enabled
2. Create a new level
3. Add Terrain World and Terrain World Renderer components to the level.
4. Create an entity at 512, 512, 50 with the following:  Axis Aligned Box Shape, Terrain Layer Spawner, Terrain Surface Materials List, and Terrain Surface Gradient List
5. Create a child entity with an Image Gradient, Gradient Transform Modifier, and Vegetation Reference Shape
6. On the child entity, set the Image Gradient to the attached image.  
7. On the child entity, set the Vegetation Reference Shape to point to the top-level entity.
8. On the top-level entity, set the Axis Aligned Box Shape to 1024, 1024, 100
9. On the top-level entity, add one entry to the Terrain Surface Gradient List.  Set the Gradient entity to the child entity, and the Surface Tag to "terrain".
10. On the top-level entity, add one entry to the Terrain Surface Materials List.  Set the Surface Tag to "terrain", and the Material Asset to any valid material.
11. In the console, set "r_terrainDebugDetailMaterials=true".
12. At this point, it should be possible to see a visualization of a giant circle on the terrain.
13. Change the tiling values on the Image Gradient.

**Expected behavior**
When changing the tiling values, the visualization of the giant circle should immediately change to reflect the changes.

**Actual behavior**
The visualization only changes as the camera moves around.

**Assets required**

![splatmap_00_gsi](https://user-images.githubusercontent.com/82224783/139290859-b1a5dbbd-8c80-4a06-a88c-dff315224bc2.png)

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82224783/139290915-16522a16-3e88-4081-8809-4df88daf2e43.png)

**Found in Branch**
development.

**Comment by LB-BartoszCwiek** [comment]
Verified the issue does not occur in Development (a53a366). Changing tiling values of the Image Gradient is now reflected instantly. The issue can be closed.
