### ISSUE TITLE
Close material editor causing crashes

### ISSUE THREAD

**Issue by amzn-rhhong** [o3de/o3de#5110]
**Describe the bug**
It is observed that close the material editor is causing a crash

**Steps to reproduce**
1. Set automatedTesting project as active
2. Open material editor
3. Close material editor
4. crashes

**Expected behavior**
Editor doesn't crash

**Actual behavior**
Editor crashes

**Assets required**
No. But I used a simple actor and material for testing.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/69218254/139346039-0bfbd3b7-0cb7-4e88-9f74-b9633e5d5ac0.png)

**Found in Branch**
Dev

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by superkitcath** [comment]
@gadams3, is this issue already fixed? Thanks!
