### ISSUE TITLE
SSAO will generates unexpected effect under the extram params settings

### ISSUE THREAD

**Issue by CGorz** [o3de/o3de#5124]
**Describe the bug**
SSAO will generates obvious point-shaped shadows and line-shaped shadows under following conditions:
large strength value, and small sampling radius & blur strength;

**Steps to reproduce**
1. Load the SponzaDiffuseGI level from [AtomTest Project](https://github.com/o3de/o3de-atomtest/tree/development/Levels/SponzaDiffuseGI); 
2. Create new entity, then attach it with SSAO component;
3. Enhance the SSAO strength value to 2.0
4. Set Sampling Radius & Blur Strength to 0.002 & 0, separately;

**Expected behavior**
Smaller radius & blur strength should reduce shadow effect 

**Actual behavior**
Extra dotted line emerge;

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [16GB]

**Additional context**

**Comment by antonmic** [comment]
This is by design, the blur reduces the pixel/line artifacts by blending the SSAO value of neighboring pixels, if you reduce the blur strength then you will end up with a very sharp SSAO and you will see the points/lines from the sampling pattern.
