### ISSUE TITLE
Animation Editor: Actor rotation is not smooth in the OpenGL Render Window

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#5125]
**Describe the bug**
Rotation mode in the Animation Editor's OpenGL Render Window is not smooth. When the user grabs one of the axes and drags it, the Actor rotates by a large angle at once, even with very slight mouse input.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Open the Animation Editor (Tools -> Animation Editor).
2. Open any available actor.
3. Select _Rotate_ from OpenGL Render Window options.
4. Rotate the character.

**Expected behavior**
The User is able to rotate actor smoothly.

**Actual behavior**
Actor's rotation is rough and lacks precision.

**Screenshots/Video**
https://user-images.githubusercontent.com/86952318/139425756-9c404926-fcbf-4344-a856-a8bde47a0be3.mp4

**Found in Branch**
Development (3738148)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600 6-Core Processor
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

**Comment by amzn-jillich** [comment]
Closing as the Atom viewport is now the default viewport for the Animation editor.
