### ISSUE TITLE
[Light component] Rotating the spot light orientation, but the shadow does not shift

### ISSUE THREAD

**Issue by instoneks2018** [o3de/o3de#5161]
**Describe the bug**
Rotating the spot light orientation, but the shadow does not shift.

**Steps to reproduce**
1.Open Editor.
2.Create a new Entity.
3.Add Light Component.
4.Select `Spot (disk)` as Light type for light component.
5. Enable shadow.
6.Rotate the light direction to see shadow changes.

**Expected behavior**
The scene and the shadow effect are correctly displayed.

**Actual behavior**
The scene does not display properly, and the shadow does not change direction with the rotation of the light source.

**Screenshots**
```
1.Shadows generated by the current light source position
```
![before2](https://user-images.githubusercontent.com/45937683/139672574-d9c0c625-3f78-4e8a-8677-8bdd6b8387b3.png)

```
2.after rotating the light direction, but the shadows do not change
```
![after2](https://user-images.githubusercontent.com/45937683/139672722-5f8c3a95-4d1c-4935-ada7-503f36d52cb0.png)

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Intel I7-10700 2.90GHz (16 CPUs)]
- GPU [Intel(R) UHD Graphics 630]
- Memory [32GB]

**Additional context**

**Comment by mrieggeramzn** [comment]
I believe this is "as expected" but you can try to bump the Disk Shape: radius higher. This offsets the projector and makes rotation feel much better.

**Comment by Adi-Amazon** [comment]
To clarify - when spot light is rotated from the same location the shadow it casts should not change shape as they are projected from the same point in space in relation to the occluders.
If the light change position or is more a complex shaped light type (hence not a point in space) then one would expect a change in shape.
As it is, Michael is right and it works as expected.
