### ISSUE TITLE
Validate CMake 3.22 works

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#5168]
**Is your feature request related to a problem? Please describe.**
Some users are seeing issues with CMake 3.22 (Currently in RC)

**Describe the solution you'd like**
Validate and fix issues that occur from CMake 3.22

**Comment by NiklasHenricson** [comment]
> **Is your feature request related to a problem? Please describe.** Some users are seeing issues with CMake 3.22 (Currently in RC)
> 
> **Describe the solution you'd like** Validate and fix issues that occur from CMake 3.22

Validated with CMake 3.21.4 and it works fine. 
However, CMake 3.22.0-rc2 causes Rapid JSON errors on compile stage.

Reverted back to 3.21 until further notice. Please update the instructions to remove the verbiage (or later...) to avoid confusion. Specify instead precise CMake versions that are supported.

Thank you,
Niklas Henricson
Epos Studios LLC
