### ISSUE TITLE
Editor_re:Invent_Bug - Warning message trying to set invalid property on Entity Outliner button

### ISSUE THREAD

**Issue by cgalvan** [o3de/o3de#5172]
**Describe the bug**
Whenever the Entity Outliner is opened, there is a warning message printed to the console because the custom stylesheet is attempting to set an invalid "flat" property on the `m_display_options` button. This warning is because the flat property only exists on a `QPushButton`, but the `m_display_options` is a `QToolButton`.

**Steps to reproduce**
1. Launch the Editor
2. Close then re-open the Entity Outliner
3. Observe console log

**Expected behavior**
No warnings are printed to the console log

**Actual behavior**
Following warning messages are printed to the console log

```
Qt: QToolButton(0x18259be10b0, name="m_display_options")  does not have a property named  "flat"
Qt: QToolButton(0x18259be10b0, name="m_display_options")  does not have a property named  "flat"
Qt: QToolButton(0x18259be10b0, name="m_display_options")  does not have a property named  "flat"
```

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Comment by cgalvan** [comment]
This would be a good first issue because all you need to do is remove the line in (both) `EntityOutliner.qss` stylesheets that try to set the `flat` property on `m_display_options`

**Comment by dvishal485** [comment]
I will like to work on the issue!
