### ISSUE TITLE
Terrain_re:Invent_Bug - Terrain World Renderer dropdown is non-functional

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#5179]
**Describe the bug**
Terrain World Renderer dropdown is non-functional. Drop-down was created as a placeholder, but the lack of functionality may be confusing.

**Pre-requisites**
1. Terrain Gem is enabled/built for the active project.

**To Reproduce**
1. Create a new level in the Editor.
2. Select the Level entity, and Add Component > Terrain World and Terrain World Renderer.
3. Adjust the "Rendered world size" dropdown on the Terrain World Renderer component.

**Expected behavior**
Dropdown changes the rendered terrain resolution.

**Actual behavior**
Nothing happens.

**Found in Branch**
stabilization/2110 installer

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10 - 20H2
 - CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz   2.90 GHz
 - GPU: RTX 2080
 - Memory: 32.0 GB

**Additional context**
It's unclear what this dropdown is intended to do even if the dropdown was functional, since the resolution of the Terrain area is set via the Terrain World component.

**Comment by invertednormal** [comment]
PR here - https://github.com/o3de/o3de/pull/5378
