### ISSUE TITLE
Terrain_re:Invent_Bug - Macro Materials don't appear to respect priority/sub-priority

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#5185]
**Describe the bug**
Macro Materials don't appear to respect priority/sub-priority.

**Pre-requisites**
1. Terrain Gem is enabled/built for the active project.

**To Reproduce**
1. Create a new level in the Editor.
2. Select the Level entity, and Add Component > Terrain World and Terrain World Renderer.
3. Create a new entity at (256, 256, 0)
4. Add the following components to the entity:
- Terrain Layer Spawner
- Terrain Height Gradient List
- Axis Aligned Box Shape(512, 512, 32)
- Terrain Macro Material (w/ any valid color/normal map assigned)
5. Add another new entity as a child of the first.
6. Add the following components to the child entity:
- Image Gradient (with any valid image gradient assigned)
- Gradient Transform Modifier
- Vegetation Reference Shape (pinned to the parent entity)
7. Pin the child entity to the Terrain Height Gradient List
8. Duplicate the above entity hierarchy, and change the configured height gradient assigned to the Terrain Height Gradient List and base/normal maps assigned to the Terrain Macro Material component.
9. Move the terrain areas so they overlap.
10. Make one area a Foreground Priority area, and the other area a Background Priority area.
11. Make one area a Sub-priority of 1 while leaving the other 0.
12. Observe how Macro Materials are prioritized.

**Expected behavior**
Higher Priority/Sub-priority areas Macro Materials take precedence over lower priority areas.

**Actual behavior**
Priority/Sub-priority doesn't appear to matter for Terrain Macro Materials. It doesn't necessarily appear that lower priority areas take priority, but moreso that whatever material is there first takes priority.

**Screenshots/Video**
![priority_macro_material](https://user-images.githubusercontent.com/82226555/139752166-8e17ae8b-04f7-4a6e-97f1-2761d53ec7cb.png)

**Found in Branch**
stabilization/2110 installer

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10 - 20H2
 - CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz   2.90 GHz
 - GPU: RTX 2080
 - Memory: 32.0 GB

**Comment by mcphedar** [comment]
Originally written as a bug, this is a feature that will be taken care of in a future terrain version. Closing this.
