### ISSUE TITLE
White Box Collider: White Box objects with White Box Colliders do not properly collide

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#5203]
**Describe the bug**
White Box objects with White Box Colliders do not properly collide. Configured entities will fall through other physics objects.

**Steps to reproduce**
1. Create a new level.
2. Add a PhysX Collider component to the default Ground entity, and set to Box Dimensions on the component to (100, 100, 1).
3. Create a new entity above the Ground entity's configured Collider area.
4. Add a White Box, PhysX Rigid Body, and White Box Collider component.
5. Enter Game Mode.

**Expected behavior**
White Box entity falls and collides with the Ground entity.

**Actual behavior**
White Box entity falls right through the Ground entity.

**Found in Branch**
stabilization/2110 installer

**Comment by greerdv** [comment]
The white box collider generates a triangle mesh, which can't be added to a dynamic PhysX rigid body.

The white box collider was made incompatible with the rigid body component to prevent that scenario in https://github.com/o3de/o3de/pull/10397
