### ISSUE TITLE
Material texture remappings

### ISSUE THREAD

**Issue by jeremyong-az** [o3de/o3de#5211]
This is a followup to an idea I had regarding #4746 (relevant snippet from the linked thread below)

> I do think it's worth considering how to convert resource bindings to "direct SRVs" instead to point to "logical SRVs" that would permit a downstream remapping in a way that is more flexible, but this will impose some complexity to the asset pipeline as well. Will give it some thought!

Essentially, the reason a custom packing is "difficult" right now is because materials are authored directly as shaders instead of a higher level of abstraction, where a texture sample can be remapped to swizzled sample of a different texture with packed channels. The idea that I'm considering is if it makes sense to supply a remapping scheme as part of the material (potentially an overridable concept). The way it would work is something like the following:

```json
{
    "TextureRemappings": [
        {
            "sourceTexture": "m_roughnessMap",
            "sourceComponents": [0],
            "destinationTexture": "m_metalRoughnessMap",
            "destinationComponents": [0],
        }
        {
            "sourceTexture": "m_metalMap",
            "sourceComponents": [0],
            "destinationTexture": "m_metalRoughnessMap",
            "destinationComponents": [1],
        }
    ]
}
```

The remappings above essentially map the R channels of the roughness and metal maps to the R and G channels of a packed map with both metal and roughness.

This material property would be overridable only at build time and would be supplied as an additional argument to AZSLc. Then, accessing `m_roughnessMap` or `m_metalMap` is done via `m_metalRoughnessMap` instead, with the appropriate swizzles applied. The source and destination component counts must always match, and it gives flexibility in how the components are swizzled. The complexity here is largely in the shader compiler, which needs to inject the appropriate swizzles into the IR stream.

Note that with the mapping example above, neither `m_roughnessMap` nor `m_metalMap` would be present in the SRG of the material (only `m_metalRoughnessMap` would be visible in the shader's reflected data)

**Comment by jeremyong-az** [comment]
Note: It may be faster/easier to actually wait to have shader canvas support before embarking on this

**Comment by HogJonny-AMZN** [comment]
Yes, having shader canvas and material graphs in place change this landscape significantly, one of the reasons (beyond resources and priorities) that we continued to delay support for 'packed textures' (aka channel packing, etc.)

In a graph world (and there is much evidence of this across tools (maya, nuke, etc.)), the file read node interprets the file data and presents output slots like RGB, R, G, B, etc. and these can be wired from the file node, to the consuming input slot on the node sampling from the texture.

my only real comment related to the map you presented would be support the following (artists think in RGB and not about array index, so this is friendlier in that vein of thought)
}
    "description": "Maps from 'split texture' channels to 'packed texture' channels using ORM (occlusion, roughness, metalness)"
    "TextureRemappings": [
        {
            "description": "Maps AO occlusion to red channel.
            "sourceTexture": "m_occlusionMap",
            "sourceComponents": "sourceTexture.r",
            "destinationTexture": "m_occlusionRoughnessMetalnessMap",
            "destinationComponents": "destinationTexture.r",
        }
        {
            "description": "Maps roughness to green channel.
            "sourceTexture": "m_roughnessMap",
            "sourceComponents": "sourceTexture.r",
            "destinationTexture": "m_occlusionRoughnessMetalnessMap",
            "destinationComponents": "destinationTexture.g",
        }
        {
            "description": "Maps metalness to green channel.
            "sourceTexture": "m_metalMap",
            "sourceComponents": "sourceTexture.r",
            "destinationTexture": "m_occlusionRoughnessMetalnessMap",
            "destinationComponents": "destinationTexture.b",
        }
    ]
}

**Comment by HogJonny-AMZN** [comment]
@jeremyong-az What I am not sure this solves is a good intuitive interface in the material reflection/editor ... that structure suggests that I have a single ORM texture asset input field, which significantly alters how the data is reflected and utilized in the interface.  That should be further explored with UX and user study to make sure it's not confusing.

**Comment by wintermute-motherbrain** [comment]
sig proposed to close this issue as it will be addressed by shader canvas.
