### ISSUE TITLE
O3DE Installer: External Project launcher fails to launch if Asset Processor is not already open

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#5224]
**Describe the bug**
External Project launcher fails to launch if AssetProcessor is not already open. An error regarding wait_for_connect appears:

![image](https://user-images.githubusercontent.com/82226555/139956610-59c8b166-4672-45a0-b59a-301119c3d84d.png)

**Steps to reproduce**
1. Install the latest build from https://o3debinaries.org/stabilization-2110/Latest/Windows/o3de_installer.exe
2. Create a new project
3. Build the project
4. Run the Project.GameLauncher.exe

**Expected behavior**
Launcher runs without issue.

**Actual behavior**
Launcher fails to open if the Asset Processor is not already launched.

**Found in Branch**
stablization/2110 installer

**Comment by lmbr-pip** [comment]
Closing out stale, have no recent reports of AP failing to launch when launching game launchers.
