### ISSUE TITLE
Before and after inputting value in the number bar is inconsistent

### ISSUE THREAD

**Issue by instoneks2018** [o3de/o3de#5234]
**Describe the bug**
When I input a data value in the number field, The displayed value is inconsistent with the input value because of precision, This is a common  problem for `o3de`.

**Expected behavior**
The value before and after the input should be the same.

**Actual behavior**
The value before and after the input are inconsistent.

**Screenshots**
The input value `25.666` is changed to `25.6665993`, as follows
 ![1](https://user-images.githubusercontent.com/45937683/140008204-73f6b245-1cf0-4ec5-951f-644957fec2d3.png) ![精度问题2](https://user-images.githubusercontent.com/45937683/140008088-ed2fa204-bd0b-417b-8502-2f1289c25bca.png)

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Intel I7-10700 2.90GHz (16 CPUs)]
- GPU [Intel(R) UHD Graphics 630]
- Memory [32GB]

**Additional context**

**Comment by monroegm** [comment]
Potentially related to #5298

**Comment by jjjoness** [comment]
@monroegm I have fixed #5298 and this still occurs. Looking at this now.

**Comment by jjjoness** [comment]
Fixed in #6859
