### ISSUE TITLE
Linux: Unable to open assetdb.sqlite file using DB Browser for SQLite v3.12.2

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#5237]
**Describe the bug**
It is not possible to open the **assetdb.sqlite** file by using the **DB Browser for SQLite v3.12.2**.
The following error is displayed when opening the above-mentioned file:
```
Could not open database file.
Reason: malformed database schema (ProductDependencies_UnresolvedPathWildcard) - functions prohibited in partial index WHERE clauses
```

**Steps to reproduce**
1. Open the **Asset Processor** and process all of the assets.
2. Run the **DB Browser for SQLite v3.12.2**.
3. Attempt to open the **assetdb.sqlite** (under directory - github/o3de/AutomatedTesting/Cache).

**Expected behavior**
The **assetdb.sqlite** file successfully opens.

**Actual behavior**
An error is displayed, the **assetdb.sqlite** file does not open.

**Video**

https://user-images.githubusercontent.com/86951967/140046679-ccd9ddb4-c761-498d-81df-65827effde74.mp4

**Found in Branch**
Stabilization_2110 (5a0b631)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by amzn-pratikpa** [comment]
@LB-JakubSkorupka can you open the file with other SQL Lite browser tools?

**Comment by LB-JakubSkorupka** [comment]
@amzn-pratikpa Yes, I was able to open the assetdb.sqlite file using an another SQL Lite browser tool - SQLiteStudio v3.3.3. I also managed to install an older version of the DB Browser for SQLite v3.11.2, which also allowed me to open the file.

**Comment by LB-JakubSkorupka** [comment]
@amzn-pratikpa Please note that the issue still occurs as described and is related to the newest version of DB browser for SQLite, which is likely to be downloaded by an O3DE user.
