### ISSUE TITLE
Terrain_re:Invent_Bug: Use Ground Plane switch has no effect on Terrain Layer Spawner

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#5246]
**Describe the bug**
When there is no Terrain Height Gradient List values, the "Use Ground Plane" switch should control whether or not a flat ground plane appears at the bottom of the Terrain Layer Spawner box.  It currently appears in the center of the box regardless of the switch setting.

**Steps to reproduce**
1. Create a new level.
2. Add a Terrain World and Terrain World Renderer component.
3. Set the Terrain World bounds to (-512, -512, -512) to (512, 512, 512)
4. Add an entity at 0,0,0 with a Terrain Layer Spawner and an Axis Aligned Box Shape.
5. Set the Axis Aligned Box Shape to (512, 512, 30)

**Expected behavior**
A ground plane appears at the bottom of the box only if the "Use Ground Plane" switch is checked.

**Actual behavior**
A ground plane appears in the center of the box regardless of the "Use Ground Plane" switch setting.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82224783/140088008-0d064148-3e72-40d0-96d3-7829a0861d77.png)

**Found in Branch**
Stabilization/2110

**Comment by mcphedar** [comment]
This is actually a feature request. It will be handled by other tasking. Closing this.
