### ISSUE TITLE
FOV Camera Setting Changes don't update

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#5249]
**Describe the bug**
When changing the FOV camera setting in the Viewport, the popup consistently is labeled with the first setting the camera was set to (in my case 40 degrees), even when you change to other values.

**Steps to reproduce**
1. Open a level
2. Click on the camera FOV combobox and change setting to something other than current value
3. Click on the combobox again, and you will see that the setting has not updated to what you last set

**Expected behavior**
After making a change to the FOV setting, the window should indicate what the current setting is. This is important for knowing the current state, and which way to go if adjustments are needed

**Actual behavior**
After making a change to this setting, it still registers at the default setting (in my case 40 degrees)

**Assets required**
No required assets

**Found in Branch**
2107.1- Initial Release

**Desktop/Device (please complete the following information):**
 - PC
 - Windows
 - 10
 - Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz   3.30 GHz
 - NVidia GeForce RTX 2080
 - 64.0 GB

**Additional context**

**Comment by hultonha** [comment]
This is related to ViewportTitleDlg, @AMZN-Igarri is going to take a quick look sometime this week (don't spend too long on it if it looks like a pain). Please feel free to reach out to me (@hultonha) for more info 👍

**Comment by hultonha** [comment]
![image](https://user-images.githubusercontent.com/82228511/157051596-ec733d0d-5610-4114-a8a9-e4aac828659c.png)
