### ISSUE TITLE
TraceMessageDrillerBus is being used when TraceMessageBus should be, leading to potential deadlocks

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/o3de#5263]
Details:

When a trace message occurs, like "AZ_TracePrintf", or "AZ_Warning", or "AZ_Error" and similar, the trace system sends the message emitted to 2 different EBUS interaces:
It sends it to TraceMessageDrillerBus.  Then it sends it to TraceMessageBus also.

Whats the difference?
Driller is what the Profiler used to be called.  Drilling is profiling. 
TraceMessageDrillerBus is an EBUS used exclusively for writing events out into a binary stream during profiler captures.  The only thing connected to this bus should be something that wants to capture events directly to an output stream (such as network or file) and then return as quickly as possible.  This is useful for example if you want to capture trace messages that occured during a session into a file for later analysis as part of a bigger trace file that also contains memory allocations and deallocations, file I/O and so on (ie, forensics).   
Because of this, a **GLOBAL MUTEX** is locked for this bus.  By global, I mean its the same actual mutex shared by the memory system, the file IO system, and many others, so that those systems can also write to the binary stream without corrupting each other.  This means that while this bus is delivering, you cannot make memory allocations, do fileIO, and many other things in the engine on any thread.  The things connecting to this bus are supposed to be really lightweight "fire and forget" functions that generally just write a few bytes to a data stream and return immediately without allocating or doing work and is largely for the mostly defunct "profiler" app.

On the other hand, the TraceMessageBus is a client facing bus for "Anyone who just wants to get notified when traces, warnings, and errors occur".  Things like writing to file, showing them on a gui, in the console, etc.  It locks a mutex, but the mutex is only locked for the TraceMessageBus itself, so memory allocations, other thread processing can still occur (although if any of those threads emit a trace message, it will wait until the current delivery finishes).  

The problem?

Several things that clearly want to listen for trace messages for client purposes are connected to the TraceMessageDrillerBus instead of the TraceMessageBus.

Specifically, the following systems should be migrated to TraceMessageBus instead of TraceMessageDrillerBus:
* Code/Framework/AzCore/Tests/StatisticalProfiler.cpp - MyTraceMessageSink
* PythonTraceMessageSink - Gems/EditorPythonBindings/Code/Tests/PythonTraceMessageSink.h
* TraceTest - Code/Framework/AzCore/Tests/Debug.cpp

In addition, since the "Trace Drilling" part of Profiler (And in fact, the PRofiler App) is essentially non functional and planned to be obsoleted by newer better profilers, we should consider eliminating the entire Driller system.  This is outside the scope of this particular issue though.

This unnecessary usage of the trace driller bus introduces potential for deadlocks if different systems (such as memory) start to issue warnings/errors during delivery of the original message.  In addition, if any listeners do things like allocate memory or trigger additional traces, it could introduce deadlocks.

No deadlocks are currently observed but its a ticking time bomb.

**Comment by AMZN-koppersr** [comment]
To add to this, the old binary stream logging originally provided by Driller has been replaced with the Event Logger. The Event Logger is a far more efficient logging solution that only requires mutex locking in rare situations. It's currently already set up to store trace message using the regular ebus (as opposed to the Driller bus).

**Comment by AMZN-ScottR** [comment]
This was resolved by #6086
