### ISSUE TITLE
Open editor crashes

### ISSUE THREAD

**Issue by amzn-rhhong** [o3de/o3de#5277]
**Describe the bug**
Open editor crashes in the latest build (11/03/2021)

**Steps to reproduce**
Get latest
Start editor (automatedTesting project)

**Expected behavior**
editor start

**Actual behavior**
editor crashes

![image](https://user-images.githubusercontent.com/69218254/140196855-cd287afc-30c0-44c2-823a-50595600f5ca.png)

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by AMZN-Olex** [comment]
https://github.com/o3de/o3de/pull/5279
