### ISSUE TITLE
Some Graphics Related Script Canvas Nodes Don't Have Proper Pin Names

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#5283]
**Describe the bug**
Script Canvas nodes are often created using reflection, but the C++ has to provide reflection data or else default names will b e used. There are multiple nodes that don't have names provided. A few are listed here, but someone should probably do a full evaluation of render related reflections to make sure all the appropriate names and descriptions are provided.

**Steps to reproduce**
Open Script Canvas and add any of the following nodes...
- FindMaterialAssignmentId
- GetPropertyOverride
- ClearPropertyOverride
- (there are probably more that are problematic)

**Expected behavior**
Nodes should have descriptive names like "LOD Index" and "Property ID"

**Actual behavior**
Nodes have default names like "Number" and "String".

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/55155825/140233410-26a151c6-6b39-44e4-a0e3-5430549b129c.png)

**Comment by sptramer** [comment]
@o3de/sig-ui-ux - Docs has triaged and accepted, we need to discuss how to manage issues like string naming, consistency, review checks, etc. to ensure that both docs and UX get a pass on source code where necessary.
