### ISSUE TITLE
Linux: Asset Bundler does not update changes made in the file explorer until it is restarted

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#5300]
**Describe the bug**
Changing a file's path or corrupting it does not update it in the Asset Bundler until it is restarted.

It should be noted that this issue does not occur on Windows Stabilization_2110 (d598a7c) and Development (cdf5a05) builds.

**Steps to reproduce**
1. Launch the Asset Bundler.
2. Right-click an asset (e.g. an Asset List) and select "Open in file browser" from the dropdown menu.
3. Move the file to a different folder or corrupt it by deleting a part of its contents in a text editor.
4. Check the Asset Builder.

**Expected behavior**
The file either disappears after moving it to a different folder, or prints an error to the Console.

**Actual behavior**
A clear and concise description of what actually happened.

**Assets required**
The file change is not recognized in the Asset Bundler until it is restarted.

**Video**

https://user-images.githubusercontent.com/86952082/140308019-ca77d536-2bc0-4363-89bd-8d4191b551f1.mp4

**Found in Branch**
Stabilization_2110 (d598a7c)

**Desktop**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by lmbr-pip** [comment]
AB is not built to watch files and reload. Needs to be a feature request.

**Comment by LB-ArturZieba** [comment]
This issue still occurs on Stabilization/2305 (392d44b).
