### ISSUE TITLE
Linux: Editor crashes when updating an .fbx asset in FBX Settings (PREVIEW) tool

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#5303]
**Describe the bug**
Updating an _.fbx_ asset in the **FBX Settings (PREVIEW)** tool will crash the Editor on Linux.

Please note that this issue does not occur on the Windows version of the Editor.

For further information please refer to the attached crash log. 

**Prerequisites**

* o3de is configured and built on the Linux platform.

**Steps to reproduce**

1. Launch the Editor and create a new level.
2. Search for any _.fbx_ object in the **Asset Browser** (ex. sphere.fbx) .
3. Right click the _.fbx_ asset and select _Edit Settings..._ .
4. Apply any change to the _.fbx_ asset and click the _Update_ button in the **FBX Settings (PREVIEW)** window.

**Expected behavior**
The asset is correctly updated and the Editor remains stable.

**Actual behavior**
The Editor crashes upon updating an _.fbx_ asset.

**Found in Branch**

stabilization/2110 (d598a7c)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: Intel I7-8700k
- GPU: RTX 2080Ti
- Memory: 16GB

**Additional context**

[fbx update Editor.log](https://github.com/o3de/o3de/files/7474875/fbx.update.Editor.log)

[fbx update crash.log](https://github.com/o3de/o3de/files/7474871/fbx.update.crash.log)

**Comment by pollend** [comment]
I think this is fixed in develop.

https://github.com/o3de/o3de/pull/4944

**Comment by LB-MateuszSzweda** [comment]
The issue was verified as fixed on both Development and stabilization/2110 branches and no longer occurs for over 10 days.
