### ISSUE TITLE
Android: AtomSampleViewer crashes upon launching after throwing an assert

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#5305]
**Describe the bug**
Launching the AtomSampleViewer deployed to a device built for Android crashes upon launching after throwing an assert.

Please refer to the attached screenshot and logs for more information.

**Prerequisites**
- AtomSampleViewer project is built for Windows.
- Assets for the Android platform are enabled and processed.
- All the required environment variables are set as described in the instructions: https://o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/

**Steps to reproduce**
1. Generate KeyStore to allow APK signing:
`keytool -genkey -keystore %O3DE_ANDROID_SIGNCONFIG_FILE% -storepass %O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD% -alias %O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS% -keypass %O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD% -keyalg RSA -keysize %O3DE_ANDROID_SIGNCONFIG_KEY_SIZE% -validity %O3DE_ANDROID_SIGNCONFIG_VALIDITY_DAYS% -dname %O3DE_ANDROID_DN%`
2. Use Python to run generate_android_project.py:
`%O3DE_ENGINE_PATH%\python\python.cmd %O3DE_ENGINE_PATH%\cmake\Tools\Platform\Android\generate_android_project.py --engine-root %O3DE_ENGINE_PATH% --project-path %O3DE_PROJECT_PATH% --build-dir %O3DE_BUILD_ROOT%\android --third-party-path %USERPROFILE%\.o3de\3rdParty --android-sdk-path %O3DE_ANDROID_SDK_PATH% --android-ndk-version %O3DE_ANDROID_NDK_VERSION% --android-sdk-platform %O3DE_ANDROID_SDK_API_LEVEL% --include-apk-assets --asset-mode %O3DE_ANDROID_ASSET_MODE% --signconfig-store-file %O3DE_ANDROID_SIGNCONFIG_FILE% --signconfig-store-password %O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD% --signconfig-key-alias %O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS% --signconfig-key-password %O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD%`
3. Build the Android Project:
`gradlew assembleProfile`
4. Deploy to an Android Device:
`%O3DE_ENGINE_PATH%\python\python.cmd %O3DE_ENGINE_PATH%\cmake\Tools\Platform\Android\deploy_android.py --build-dir %O3DE_BUILD_ROOT%\android --configuration profile --clean -t %O3DE_ANDROID_DEPLOY_TYPE%`
5. Launch the deployed application.

**Expected behavior**
The deployed Android application launches without issues.

**Actual behavior**
The deployed Android application crashes upon launching after throwing an assert.

**Assets required**
https://github.com/o3de/o3de-atom-sampleviewer

**Screenshots/Video**
![Screenshot_20211104-145123_AtomSampleViewer](https://user-images.githubusercontent.com/86953659/140331724-01a8c159-b960-4fbb-a658-a96773a06635.jpg)

**Found in Branch**
Stabilization/2110 (d598a7c)
AtomSampleViewer - Stabilization/2110 (064fbe5)

**Device**
 - Device: Samsung S20+
 - OS: Android
 - Version 11 (API 30)

**Additional context**
[adb_logcat_ASV.txt](https://github.com/o3de/o3de/files/7475591/adb_logcat_ASV.txt)
[Game.log](https://github.com/o3de/o3de/files/7475592/Game.log)

**Comment by LB-KacperKapusta** [comment]
In addition, please note that the deployed package name refers to Lumberyard, as described in the https://github.com/o3de/o3de/issues/3881.

**Comment by moraaar** [comment]
@LB-KacperKapusta Recent commits have fixed Android platform and I'm able to run a default level on Samsung Galaxy S21. This issue might be old now, can you please sync the latest and verify if this bug still happens? Thanks.

**Comment by LB-KacperSzczepanski** [comment]
Closing as the issue no longer occurs on build Development (https://github.com/o3de/o3de/commit/e4abc2abc2339af8dc1b7503ded14321ed6ff698)
