### ISSUE TITLE
test_Multiplayer_AutoComponent_NetworkInput intermittently fails

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#5310]
**Describe the bug**
test_Multiplayer_AutoComponent_NetworkInput fails intermittently, have seen it at least 3 times in different branches with changes completely unrelated to networking or codegen

**Failed Jenkins Job Information:**
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-5291/2/pipeline
```
[2021-11-04T16:26:39.303Z] ..\..\..\..\..\..\AutomatedTesting\Gem\PythonTests\Multiplayer\TestSuite_Main.py::TestAutomation::test_Multiplayer_AutoComponent_NetworkInput[windows-windows_editor-AutomatedTesting] FAILED [100%]
```
(see attached log)

**Attachments**
[jenkins_output.txt](https://github.com/o3de/o3de/files/7476568/jenkins_output.txt)

**Comment by lmbr-pip** [comment]
Will be fixed by https://github.com/o3de/o3de/pull/5313
