### ISSUE TITLE
Convert Water Gem/Infinite Ocean to O3DE

### ISSUE THREAD

**Issue by NiklasHenricson** [o3de/o3de#5321]
**Is your feature request related to a problem? Please describe.**
Originally in Lumberyard there was a "Infinite Ocean" gem that could be piggy-backed on a game project making it possible to surround your normal terrain with water. The gem was very useful and time saving gem that provided a quick way to add water mass in the game environment. Please bring it back from Lumberyard in one form or another.

The old Lumberyard documentation is located [here](https://docs.aws.amazon.com/lumberyard/latest/userguide/component-infinite-ocean.html). 

The old "Water" gem was located for example under, **C:\Amazon\Lumberyard\1.28.0.0\dev\Gems\Water** and is a code-based gem that has some integration to the editor,

<img src="https://navaria-online.com/assets/images/water-gem.PNG">

I made an attempt to convert it over on my own but it refers to "OceanConstants.h" "OceanEnvironmentBus.h" and "I3DEngine.h". While the first two are a non-issue to bring over, the "I3DEngine.h" is referring in its turn to "CryThreadSafeRendererContainer.h" which has been disposed by the Core team, as Atom replaces modules in the engine. However, looking at the old code, it is just basic functionality and someone with Atom-engine knowledge should be able to nail this core-engine class conversion to suit Atom's needs.

Underwater Effects Video:
[![Watch the video](https://navaria-online.com/assets/images/underwater-preview.png)](https://www.youtube.com/watch?v=2CLvOyO2QEc)

<img src="https://docs.aws.amazon.com/lumberyard/latest/userguide/images/component/infiniteocean/infinite-ocean-component-1.png">

<img src="https://docs.aws.amazon.com/lumberyard/latest/userguide/images/component/infiniteocean/infinite-ocean-component-5.png">

<img src="https://docs.aws.amazon.com/lumberyard/latest/userguide/images/component/infiniteocean/infinite-ocean-component-17.png">

<img src="https://docs.aws.amazon.com/lumberyard/latest/userguide/images/component/infiniteocean/infinite-ocean-component-example-script.png">

**Comment by HeadClot** [comment]
I do agree it was useful. I would like to see this make a return as well.

**Comment by chanmosq** [comment]
Adding `sig/graphics-audio` to get more insight for @NiklasHenricson.

**Comment by NiklasHenricson** [comment]
> Adding `sig/graphics-audio` to get more insight for @NiklasHenricson.

Thank you Chanelle, I also spoke to Doug and Jon in regards to this. I appreciate your quick response. I would volunteer in this conversion but all I need to know is some information from the core engine Atom guys which content can be moved, and which one is off limits due to licensing issues.

Please let me know.


Sincerely,
Niklas Henricson

**Comment by NiklasHenricson** [comment]
@chanmosq @forhalle @HeadClot 

Issue converted to an RFC per Jon B's request here: https://github.com/o3de/sig-graphics-audio/issues/22
