### ISSUE TITLE
Atom gems define the server target and are built for the dedicated server

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#5327]
**Describe the bug**
From my recent test, Atom gems are built for the [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample) dedicated server target, but they are not required to run the server. This issue increases the build time and package size for the server target. Ideally the dedicated server should only require NullRender.

**Steps to reproduce**
1. Clone [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample)
2. Configure and build the MultiplayerSample.ServerLauncher target
3. Check the build folder for all the Atom related DLLs

**Expected behavior**
- Gems that are not used by the dedicated server should exclude themselves from the .server targets (Specify nothing for the .Server target in their CMake files).
- Unused libraries are not built for the server launcher.

**Actual behavior**
13 Atom libraries were built for the server launcher but may not actually be in use.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/68558268/140412518-c258d950-64bf-447f-ad84-e978ea055b6c.png)

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Additional context**
I tried to remove the server targets defined in Atom CMake files and rebuilt the server. Verified that the dedicated server could launch without issue.

**Comment by moudgils** [comment]
It seems like MPSample needs to run the NullRenderer backend for the Server and hence it can exclude dx12/vulkan/metal (for mac) gems. We would need to modify the cmake for MPSample's Server target to exclude other RHI gems and only bring in Atom_Rhi_null gem. The RHI code is dynamic enough to use that gem as only NullRHI backend would be registered when this change is made.   
As an FYI you would still need other Atom gems like RPI, bootstrap, RHI.private as the core code still expects a Renderer and we are just forcign it to use the null rhi as oppose to dx12 or vulkan or metal (for mac).

**Comment by wintermute-motherbrain** [comment]
@lmbr-pip can you review @moudgils comment?  We can offer guidance but seems this is straightforward work that can be done by someone from sig/network.

**Comment by junbo75** [comment]
Another question is raised during the recent team discussion: Whether we should keep the null render inside Atom or move it out.

**Comment by moudgils** [comment]
> Another question is raised during the recent team discussion: Whether we should keep the null render inside Atom or move it out.

The current implementation of Null renderer is implemented by introducing a new null backend at the RHI so it can not be pulled out of Atom. I think what you may be talking about is Null Renderer at a much higher level where it skips RPI completely. That is a bigger feature and will require a bigger discussion with other Atom folks as it will be considered a new feature.

**Comment by lmbr-pip** [comment]
Issue conflated a number of points:
* Requirements for MultiplayerSample wrt to gems that should be enabled/used in server including null renderer setup.
* If null renderer should bring in any parts of ATOM - Server teams will need to make a feature request here.
* Guidance to gem owners to setup Gems with correct client/server split, which depends on https://github.com/o3de/sig-network/issues/32

**Comment by lmbr-pip** [comment]
SIG-network will provide new guidance to Gem owners once https://github.com/o3de/sig-network/issues/32 has been accepted and implemented. 

In agreement with @junbo75 these gem split stories will be resolved, and new issues created once we have guidance on client, server separation.
