### ISSUE TITLE
[GNU/LINUX] Add modifier Level of Detail error in FBX settings

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#5330]
**Describe the bug**
Asset Processor scolds something wrong with model in fbx, does not work with LOD

download [sphere_lod.tar.gz](https://github.com/o3de/o3de/files/7478337/sphere_lod.tar.gz)  test modeling

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/140414033-83b6667a-2de7-497f-9499-8f03c9311c00.mp4 

**Found in Branch**
development 600bb5b34ec8592a4c73817c04fb9bf2b947f890

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 20.04.03 LTS
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 21.0.3]
 - Memory: 16GB

**Comment by micronAMZN** [comment]
I can replicate this issue on Windows 10. Adding any LODs in an LOD modifier results in a failure in Asset Processing.

Branch: Development commit eecf6ab920ea3688e2430e7ac885380685610492

    Device: PC
    OS: Windows 10
    Version: 19042.1288
    CPU: Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz   3.10 GHz
    GPU: GeForce RTX 3070 Mobile
    Memory: 32.0 GB

**Comment by Darkinggq** [comment]
verified fixed (development 14076b4f932a768e9d12b041ca16a13903ac6be5)
