### ISSUE TITLE
Mesh/Terrain related gems define the server target and are built for the dedicated server

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#5335]
Atom gems define the server target and are built for the dedicated server

**Describe the bug**
From my recent test, the following Mesh/Terrain related gems are built for the [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample) dedicated server target, but they are not required to run the server. This issue increases the build time and package size for the server target.
- SurfaceData
- GradientSignal
- FastNoise
- Vegetation

**Steps to reproduce**
1. Clone [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample)
2. Configure and build the MultiplayerSample.ServerLauncher target
3. Check the build folder for the dynamic libraries built for the gems above

**Expected behavior**
- Gems that are not used by the dedicated server should exclude themselves from the .server targets (Specify nothing for the .Server target in their CMake files).
- Unused libraries are not built for the server launcher.

**Actual behavior**
Mesh/Terrain related libraries were built for the server launcher but may not actually be in use.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Additional context**
I tried to remove the server targets defined for the gems above and rebuilt the server. Verified that the dedicated server could launch without issue.

**Comment by lmbr-pip** [comment]
Need input from sig-content/sig-graphics-ux if mesh/terrain should offer client / server split

**Comment by mbalfour-amzn** [comment]
@junbo75 can you provide more information here?  I don't believe MultiplayerSample currently uses Vegetation or Terrain at all, so I could see why everything would work fine without building these Gems, but there's nothing preventing a server from using these systems.  What's the expected fix here - removing the Gems from MultiplayerSample entirely until they're used by the sample?

**Comment by lmbr-pip** [comment]
Have two issues:
* MPS currently includes Terrain and Vegetation and could remove the use of these gems.
* But, problem still exists, that gems have no client/server split for inclusion in other multiplayer projects.

**Comment by junbo75** [comment]
Based on the comments from @kberg-amzn , if these impact gameplay in any significant way, they will be required to run on the server. Foliage or vegetation that block movement or weapons fire, terrain features that affect motion or line-of-sight calculations, etc

**Comment by lmbr-pip** [comment]
This work is blocked upon https://github.com/o3de/sig-network/issues/32

**Comment by lmbr-pip** [comment]
SIG-network will provide new guidance to Gem owners once o3de/sig-network#32 has been accepted and implemented.

In agreement with @junbo75 these gem split stories will be resolved, and new issues created once we have guidance on client, server separation.
