### ISSUE TITLE
Scripting related gems are enabled by default and built for the dedicated server target

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#5336]
**Describe the bug**
From my recent test, the following scripting related gems are enabled by default and built for the [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample) dedicated server target, but they are not required to run the server. This issue increases the build time and package size for the server target. These gems shouldn't be enabled by default for the dedicated server and investigation is needed to check whether they need to define a server target actually:
- ScriptEvents
- ScriptCanvas
- ScriptCanvasPhysics
- ExpressionEvaluation

**Steps to reproduce**
1. Clone [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample)
2. Configure and build the MultiplayerSample.ServerLauncher target
3. Check the build folder for scripting related libraries

**Expected behavior**
- Gems that are not used by the dedicated server should exclude themselves from the .server targets (Specify nothing for the .Server target in their CMake files).
- Unused libraries are not built for the server launcher.

**Actual behavior**
Scripting related libraries were enabled by default and built for the server launcher but may not actually be in use.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Additional context**
I tried to remove the server targets defined for the scripting related Gems and rebuilt the server. Verified that the dedicated server could launch without issue.

**Comment by lsemp3d** [comment]
Adding sig/network, I expect that if the MultiplayerSample is using ScriptCanvas, then those gems are correctly enabled. Sig/network to confirm

**Comment by lmbr-pip** [comment]
This issue combines 2 concerns. 1) Gems do not have mechanisms for client/server splits, this will be addressed in o3de/sig-network#32 and 2) MPS should cleanup what gems and binaries are included as an example project.

Closing issue in light of this. New issues will be created once o3de/sig-network#32 is accepted.
