### ISSUE TITLE
TextureAtlas gem define the server target and are built for the dedicated server

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#5340]
**Describe the bug**
From my recent test, the TextureAtlas gem is built for the [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample) dedicated server target, but it is not required to run the server. This issue increases the build time and package size for the server target.

**Steps to reproduce**
1. Clone [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample)
2. Configure and build the MultiplayerSample.ServerLauncher target
3. Check the build folder for TextureAtlas.dll

**Expected behavior**
- Gems that are not used by the dedicated server should exclude themselves from the .server targets (Specify nothing for the .Server target in their CMake files).
- Unused libraries are not built for the server launcher.

**Actual behavior**
TextureAtlas.dll was built for the server launcher but may not actually be in use.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Additional context**
I tried to remove the server targets defined for the TextureAtlas gem and rebuilt the server. Verified that the dedicated server could launch without issue.

**Comment by lsemp3d** [comment]
Added to sig/network to review the MultiplayerSample cmake configuration

**Comment by lmbr-pip** [comment]
This issue combines 2 concerns. 1) Gems do not have mechanisms for client/server splits, this will be addressed in o3de/sig-network#32 and 2) MPS should cleanup what gems and binaries are included as an example project.

Closing issue in light of this. New issues will be created once o3de/sig-network#32 is accepted.
