### ISSUE TITLE
WhiteBox gem define the server target and are built for the dedicated server

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#5343]
**Describe the bug**
From my recent test, the WhiteBox gem is built for the [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample) dedicated server target, but it is not required to run the server. This issue increases the build time and package size for the server target.

**Steps to reproduce**
1. Clone [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample)
2. Configure and build the MultiplayerSample.ServerLauncher target
3. Check the build folder for WhiteBox.dll

**Expected behavior**
- Gems that are not used by the dedicated server should exclude themselves from the .server targets (Specify nothing for the .Server target in their CMake files).
- Unused libraries are not built for the server launcher.

**Actual behavior**
WhiteBox.dll was built for the server launcher but may not actually be in use.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Additional context**
I tried to remove the server targets defined for the WhiteBox gem and rebuilt the server. Verified that the dedicated server could launch without issue.

**Comment by lmbr-pip** [comment]
This issue really conflate two issues:

* MultiplayerSample currently includes Whitebox and could remove the use of these gems for the server.
* Whitebox gem has no client/server split for inclusion in other multiplayer projects, this is blocked upon https://github.com/o3de/sig-network/issues/32

**Comment by lmbr-pip** [comment]
SIG-network will provide new guidance to Gem owners once o3de/sig-network#32 has been accepted and implemented.

In agreement with @junbo75 these gem split stories will be resolved, and new issues created once we have guidance on client, server separation.
