### ISSUE TITLE
PhysXDebug gem define the server target and are built for the dedicated server

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#5344]
**Describe the bug**
From my recent test, the PhysXDebug gem is built for the [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample) dedicated server target, but it is not required to run the server. This issue increases the build time and package size for the server target.

**Steps to reproduce**
1. Clone [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample)
2. Configure and build the MultiplayerSample.ServerLauncher target
3. Check the build folder for PhysXDebug.Gem.dll

**Expected behavior**
- Gems that are not used by the dedicated server should exclude themselves from the .server targets (Specify nothing for the .Server target in their CMake files).
- Unused libraries are not built for the server launcher.

**Actual behavior**
PhysXDebug.Gem.dll was built for the server launcher but may not actually be in use.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Additional context**
I tried to remove the server targets defined for the PhysXDebug gem and rebuilt the server. Verified that the dedicated server could launch without issue.

**Comment by junbo75** [comment]
Based on the comments from @kberg-amzn , if this includes the PVD integration this will be required for the server.

**Comment by lmbr-pip** [comment]
This issue really conflate two problems:

* MultiplayerSample currently includes PhysXDebug and could remove the use of the gem for the server (depending if PVD is required or not)
* PhysXDebug gem has no client/server split for inclusion in other multiplayer projects, this is blocked upon: https://github.com/o3de/sig-network/issues/32

**Comment by lmbr-pip** [comment]
SIG-network will provide new guidance to Gem owners once o3de/sig-network#32 has been accepted and implemented.

In agreement with @junbo75 these gem split stories will be resolved, and new issues created once we have guidance on client, server separation.
