### ISSUE TITLE
[GNU/LINUX] Track View part 2 (Render output)

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#5362]
**Describe the bug**
Video recording FFMPEG camera does not support in Linux, and there is no `tif/tga/jpg/png` format

![2021-11-05_11-18](https://user-images.githubusercontent.com/17591539/140483995-2f19528f-3910-4fe6-bad9-9a7adb81e046.png)

![image](https://user-images.githubusercontent.com/17591539/140484775-4065d442-6907-41e0-8fb5-92ad247a9378.png)

**Steps to reproduce**
https://youtu.be/Ri_tYbwqk9A?t=238

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/140483675-00bb2ed1-77a8-4afe-aac9-70f04030571b.mp4

**Found in Branch**
stabilization/2110 fdc56b4a57f2f076bc97b5be79048ae377e0f41a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 20.04.03 LTS
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 21.0.3]
 - Memory: 16GB

**Comment by baothientran** [comment]
For FFMPEG, it can be added to the engine by modifying Windows' Registry Editor:
- You can open Start menu and find Registry Editor
- In the `Computer\HKEY_CURRENT_USER\SOFTWARE\O3DE\O3DE\`, create Keys `Settings`
- In the `Settings`, right click to add string value `FFMPEG_PLUGIN` and modify it to point to the path of ffmpeg executable
- You can reopen the editor, and the error message will disappear
