### ISSUE TITLE
[macOS] New projects cannot be created from Project Manager GUI

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#5370]
**Describe the bug**
After the user presses the "Create Project" button, the following error message is displayed:
"Unable to detect CMake on this host"

The New Project can be created from CLI.

**Steps to reproduce**
1. Configure O3DE:
  cmake -B <build_dir> -S . -G "Xcode" -DLY_VERSION_ENGINE_NAME=o3de-install -DCMAKE_INSTALL_PREFIX="Engine Directory"
2. Build O3DE:
  cmake --build <build_dir> --target install --config <config>
3. Open Project Manager.
4. Select the "Create New Project" option.
5. Press the "Create Project" button.

**Expected behavior**
The new project is created.

**Actual behavior**
An error is displayed.

**Screenshots/Video**

![CMakeHost](https://user-images.githubusercontent.com/86952591/140524858-701f9772-7504-4e33-a918-f6882c90aa32.jpg)

**Found in Branch**
Stabilization_2110 (fdc56b4)

**Desktop/Device:**
Device: Mac
OS: macOS
Version: Big Sur 11.5.1
CPU: Intel Core i7 2,8 GHz
GPU: Radeon Pro 555
Memory: 16GB

**Comment by amzn-sj** [comment]
The ProjectManager GUI isn't a priority on Mac at this point. I updated the instructions to use the CLI for now. Sorry about the confusion!
I'll still try to see under what circumstances this fails in the GUI. Assigning to myself.

**Comment by amzn-sj** [comment]
@LB-JakubSkoczylas Whenever you get back to testing O3DE as an SDK on MacOS, can you check the following?

1. Before launching O3DE_SDK.app, open terminal and run: 
`sudo "<path_to_cmake>/CMake.app/Contents/bin/cmake-gui" --install` 
where `<path_to_cmake>` is the path to your CMake.app bundle. Most common location is /Applications. It will prompt for password. 
2. Once step 1 is completed successfully, see if creating a new project by using the ProjectManager GUI works.
3. If step 2 was successful, check if building by clicking on the "Build" button in ProjectManager GUI works.
4. If step 3 was successful, check if clicking on the "Editor" button in the ProjectManager GUI launches the Editor/AP.

Thanks!

**Comment by byrcolin** [comment]
Probably fixed already. Confirm and close.
