### ISSUE TITLE
Bug Report: Cmake fails generating engine.pak

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#5390]
**Describe the bug**
The cmake install release command fails because cmake attempts to remove files using an empty container after generating the engine.pak in the generated install cmake script. 

**Steps to reproduce**
1. Run the cmake install release command per the instructions in the release and packaging documentation.

**Expected behavior**
The release install layout is generated

**Actual behavior**
The command fails with a cmake error

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by amznestebanpapp** [comment]
Solved by PR #5380
