### ISSUE TITLE
Linux: Attempting to open UI Canvas after saving a Canvas outside of the Project folder results in a system malfunction

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#5398]
**Describe the bug**
Saving a UI Canvas outside of the Project folder (i.e. in the engine root folder, which is a default path suggested by the UI Canvas on Linux) and attempting to open the UI Canvas tool from the _UI Canvas Asset Ref_ Component shuts down all the applications and logs the User out of Ubuntu.

Please note the issue does not always reproduce, also sometimes it occurs after closing the Editor instead.

Please note that no logs are generated after the issue occurs.

**Steps to reproduce**
1. Create or load any Level.
2. Launch UI Canvas tool.
3. Create any Canvas.
4. Save the Canvas into the engine root folder (the default path, i.e. home/<pc_name>/o3de).
5. Close the UI Canvas tool.
6. Create a new entity.
7. Add the _UI Canvas Asset Ref_ component to the entity.
8. Without assigning any asset to the component, click the _Open in UI Editor_ icon (to the right of the _Canvas Pathname_ field).
9. (optional) repeat steps 3-8.
10. (optional) close the Editor.

**Expected behavior**
UI Canvas tool launches. System and the Editor remain stable.

**Actual behavior**
User is logged out of the system, all applications open shut down.

**Assets required**
N/A

**Screenshots/Video**
We are unable to record a video due to the system malfunction.

**Found in Branch**
Stabilization_2110 (621194e)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version: 20.04
 - CPU: AMD Ryzen 5 3600
 - GPU: Nvidia RTX 2060 SUPER
 - Memory: 16GB

**Comment by spham-amzn** [comment]
Unable to reproduce on development (766cb40585b239f9bfc5901f16312a4f0a5371f8)

**Comment by spham-amzn** [comment]
Unable to reproduce on development ( 766cb40585b239f9bfc5901f16312a4f0a5371f8 )
https://user-images.githubusercontent.com/82231385/165386552-18a55afd-7fc2-4a2f-9e29-c27e86dfb572.mp4

**Comment by LB-TomaszSerwanski** [comment]
Reopening the issue as it still occurs in the latest Development (1e96ca4). However, it now requires the UI Editor to be launched three times and not two to occur. There are also other ways to reproduce it, i.e. launch both the Animation Editor and the UI Editor and restart one of these tools. This results in either the O3DE crash or the system malfunction as described in the ticket.

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as Fixed in Development (146b2c8).
