### ISSUE TITLE
Linux: UI Editor flickering when opened and moved

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#5408]
**Describe the bug**
Opening the **UI Canvas** tool and moving its window will result in it flickering.
Please note that the tool does not flicker if left in the default position after opening.

**Steps to reproduce**
1. Load a level.
2. Open the **UI Editor**.
3. Move the UI Editor's window.

**Expected behavior**
The UI Canvas does not flicker.

**Actual behavior**
UI Canvas is flickering after opening and moving the UI Editor window.

**Video**

https://user-images.githubusercontent.com/86951967/140763940-58bd361f-b967-4d7c-a067-ee3037e33029.mp4

**Found in Branch**
Stabilization_2110 (621194e)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by jiaweig-amzn** [comment]
It should be fixed by
https://github.com/o3de/o3de/pull/5388

**Comment by LB-JakubSkorupka** [comment]
Verified as fixed in Stabilization_2110 (551e601).
