### ISSUE TITLE
Linux: .fbx assets are processed indefinitely on updating

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#5415]
**Describe the bug**
Updating an _.fbx_ asset in the **FBX Settings (PREVIEW)** tool results in a blank _File Progress_ window with _File processing..._
text. The file processing never finishes soft locking the Editor as a result.

Enabling/Disabling P4 and replacing _.assetinfo_ name casings as shown in https://github.com/o3de/o3de/pull/5371/commits/84c5796a126073bc53d8f81b9c8101e29735294b
did not resolve the issue for any asset.

Please note that this issue does not occur on the Windows version of the Editor.

**Prerequisites**

* o3de is configured and built on the Linux platform.

**Steps to reproduce**

1. Launch the Editor and create a new level.
2. Search for any _.fbx_ object in the **Asset Browser** (ex. sphere.fbx) .
3. Right click the _.fbx_ asset and select _Edit Settings..._ .
4. Apply any change to the _.fbx_ asset and click the _Update_ button in the **FBX Settings (PREVIEW)** window.

**Expected behavior**
The asset is correctly updated.

**Actual behavior**
The asset is processed indefinitely soft locking the Editor.

**Found in Branch**

stabilization/2110 (a1d9a2c)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: Intel I7-8700k
- GPU: RTX 2080Ti
- Memory: 16GB

**Comment by LB-MateuszSzweda** [comment]
Today on stabilization/2110 (0ae2d75) the issue stopped reproducing for me. I was able to successfully update .fbx assets and perform tests.

**Comment by moraaar** [comment]
I've fixed the casing of all .fbx.assetinfo files that didn't match their .fbx (#5490)
I've also testing the logic of FBX Setting creating .fbx.assetinfo files from .fbx files and it generates the correct casing.

**Comment by moraaar** [comment]
I've also fixed them in other repos:
o3de-multiplayersample: https://github.com/o3de/o3de-multiplayersample/pull/84
o3de-atomtest: https://github.com/o3de/o3de-atomtest/pull/80
o3de-atom-sampleviewer: all .fbx.assetinfo files had the correct casing.
