### ISSUE TITLE
Spot instance interruption retry failure

### ISSUE THREAD

**Issue by amzn-changml** [o3de/o3de#5425]
**Describe the bug**
Windows 2019 spot instances are occasionally aborting the AR Windows profile pipeline stage due to a retry failure during the setup stage

**Failed Jenkins Job Information:**
Failing build URL: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/stabilization%2F2110/104/pipeline/483

Error message:

```
[2021-11-08T20:28:37.489Z] Starting post-build common steps...
[2021-11-08T20:28:37.728Z] EC2 (us-west-2) - WIN2019_INC_3_M (sir-5pay89qm) was marked offline: Node is being removed
Unable to create live FilePath for EC2 (us-west-2) - WIN2019_INC_3_M (sir-5pay89qm)[2021-11-08T20:28:38.051Z] Unmount script error java.io.IOException: Unable to create live FilePath for EC2 (us-west-2) - WIN2019_INC_3_M (sir-5pay89qm)
FAILURE: org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
```

**Additional context**
Autocut ticket here: https://github.com/o3de/o3de/issues/5160

**Comment by brianherrera** [comment]
Running some tests. Looks like Jenkins is hitting the prebuild step timeout before it's able to properly fail the setup stage. So the exception cause is TimeoutStepExecution$ExceededTimeout which we ignore in the retry.

**Comment by amzn-changml** [comment]
Note that #5450 fixes the timeout issue with the development branch, but the error message we got in Stabilization is not a timeout
