### ISSUE TITLE
Add New Component Labels to sig/graphic-audio

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#5430]
**Is your feature request related to a problem? Please describe.**
As the number of issues increase within the sig/graphic-audio, it is harder for the community and internal staff to identify quickly the component impacted. The title of the issue or feature is not always clear either, which makes it difficult to quickly pull an issue / bug to work on. Currently, we only have feature/atom.

**Describe the solution you'd like**
I suggest to add the following labels for features and bugs, to narrow the search within the sig/graphics-audio:

- feature/graphics/tools
- feature/graphics/shaders
- feature/graphics/rpi
- feature/graphics/rhi
- feature/graphics/mesh
- feature/graphics/materials
- feature/graphics/lighting
- feature/graphics/asset

and modify the feature/atom to feature/graphics and add feature/audio.

To distinguish bugs from features, the label kind/bug already exists.

I propose to add the request to our next monthly.

**Comment by superkitcath** [comment]
This RFC was approved during our monthly Sig meeting, on November 17, 2021, at 10:00 PST

**Comment by forhalle** [comment]
@superkitcath - feature/audio already exists. I created the below labels, however, with the Descriptions below. Please review these Descriptions before closing this issue as complete.

feature/graphics/asset- This item is related to graphics assets.
feature/graphics/lighting - This item is related to graphics lighting.
feature/graphics/materials - This item is related to graphics materials.
feature/graphics/mesh - This item is related to graphics mesh.
feature/graphics/rhi - This item is related to graphics rhi.
feature/graphics/rpi - This item is related to graphics rpi.
feature/graphics/shaders - This item is related to graphics shaders.
feature/graphics - This item is related to the ATOM and 3D rendering subsystems.
feature/graphics/tools - This item is related to graphics tools.

**Comment by superkitcath** [comment]
@forhalle, here the reviewed descriptions:feature/graphics/asset- Items related to assets or content creation
 feature/graphics/lighting - Items related to lighting such as punctual lights, GI, shadows, area lights, etc.
 feature/graphics/materials - Items related to materials and the material system
 feature/graphics/mesh - Items related to meshes including static meshes, skinned meshes, LODs, etc
 feature/graphics/rhi - Items related to the rendering backend including API integrations such as DX12, Vulkan, or Metal
 feature/graphics/rpi - Items related to the rendering pipeline interface or pass system
 feature/graphics/shaders - Items related to shaders, shader authoring, or the shader compiler.
 feature/graphics - General items related to the Atom renderer or graphics.
 feature/graphics/tools - Items related to graphics tools such as Material Editor, Atom Sample Viewer, DCCSI, etc.

**Comment by forhalle** [comment]
@superkitcath - I updated the descriptions, but slightly different than you detail above. All of the other descriptions start with "This item is", so I updated yours to be parallel. For example "This item is related to lighting...." vs. "Items related to lighting". If this is acceptable, please close this issue. Happy to discuss if there is a reason to deviate from the established pattern. Thanks!

**Comment by superkitcath** [comment]
Closing this issue; all additional labels requested were created. Thanks @forhalle !
