### ISSUE TITLE
Linux: Profile configuration built with DLY_UNITY_BUILD=ON argument has multiple issues

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#5445]
**Describe the bug**

Linux profile configuration configured and built with the DLY_UNITY_BUILD=ON argument has multiple issues that can appear with a varying reproduction rate.

1. Editor failing to build around 75% build progress with a _build stopped: subcommand failed_ output.
Repro rate 2/5

2. Asset Processor failing to find assets to process for a project even with the custom.setreg file specifying the projectpath.
Repro rate 3/5

3. Editor crashing on launch. Repro rate 5/5

Please note that the issue does not occur when configuring and building with  _DLY_UNITY_BUILD=OFF_ argument and occurs only on Linux.

Command used to configure:

`cmake -B build/linux -S . -G"Ninja Multi-Config" -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12 -DLY_PROJECTS=AutomatedTesting -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLY_UNITY_BUILD=ON`

Command used to build:

`cmake --build build/linux --config profile -j 8`

For further information please refer to the linux failing build logs and a crash log.

**Prerequisites**

* Linux is setup to configure and build O3DE.

**Steps to reproduce**

1. Navigate to the _o3de/python_ directory and run the  `./get_python.sh` command in the terminal.
2. Navigate to the _o3de/scripts_ directory and run the `./o3de.sh register --this-engine` command in the terminal.
3. Navigate to the o3de directory and run `cmake -B build/linux -S . -G"Ninja Multi-Config" -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12 -DLY_PROJECTS=AutomatedTesting -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLY_UNITY_BUILD=ON` command in the terminal.
4. When configuring finishes run `cmake --build build/linux --config profile -j 8` command in the terminal.

**Expected behavior**
Building finishes and the user is able to run the Editor of the built project.

**Actual behavior**
Building fails or the Editor crashes upon launching.

**Found in Branch**

stabilization/2110 (dcc2890)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: Ubuntu 20.04.3 LTS
- CPU: Intel I7-8700k
- GPU: RTX 2080Ti
- Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/7505
[CMakeProjectBuildErrorAutomatedTesting.log](https://github.com/o3de/o3de/files/7505495/CMakeProjectBuildErrorAutomatedTesting.log)
494/Editor.log)

[crash.log](https://github.com/o3de/o3de/files/7505492/crash.log)

**Comment by LB-MateuszSzweda** [comment]
Today I was able to configure and  build the Editor for AutomatedTesting project by using the

{code:java}
-DLY_PARALLEL_LINK_JOBS=4
{code}
which prevented the building proccess from being killed due to running out of memory.

However the issue with AP not processing assets persisted for both AutomatedTesting and New projects.
The AP was directed to the correct project paths and _o3de.sh register --this-engine --force_ command proved futile to resolve the issue.

What did resolve it although was deleting the hidden _.o3de_ folder and configuring and building once again.
After this step AP correctly processed the assets and the Editor launched.

**Comment by amzn-pratikpa** [comment]
@LB-MateuszSzweda see LYN-8107
