### ISSUE TITLE
Linux: Saving Script Canvas scripts crashes the Editor

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#5446]
**Describe the bug**
Opening or creating and then saving a .scriptcanvas file in the Script Canvas tool crashes the Editor.

Please note that this issue does not occur on Windows.

For further information please refer to the attached crash log.

**Steps to reproduce**

1. Launch the Editor and create a new level.
2. Open _Tools>Script Canvas_ and create or open any graph.
3. Modify the graph and select _File>Save_ .

**Expected behavior**
The script is saved and the Editor remains stable.

**Actual behavior**
Editor crashes when the script is saved.

**Found in Branch**

stabilization/2110 (dcc2890)

**Desktop/Device:**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.3 LTS
- CPU: Intel I7-8700k
- GPU: RTX 2080Ti
- Memory: 16GB

**Additional context**

[crash.log](https://github.com/o3
[Editor.log](https://github.com/o3de/o3de/files/7505589/Editor.log)
de/o3de/files/7505585/crash.log)

**Comment by Hsuehnj** [comment]
There is same problem on Windows:https://github.com/o3de/o3de/issues/5392

**Comment by LB-MateuszSzweda** [comment]
Today on stabilization/2110 (0ae2d75) the issue stopped reproducing for me.

**Comment by lsemp3d** [comment]
Closing as it's been marked 'not reproducible' for over 2 weeks
