### ISSUE TITLE
Move Code\Framework\AzCore\AzCore\Android to a PAL folder

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#5452]
**Is your feature request related to a problem? Please describe.**
Code in `Code\Framework\AzCore\AzCore\Android` is not in a PAL directory

**Describe the solution you'd like**
Move code from `Code\Framework\AzCore\AzCore\Android` to some folder inside `Code\Framework\AzCore\Platform\Android`

**Comment by byrcolin** [comment]
was done a while ago
