### ISSUE TITLE
Camera locking does not work

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#5477]
**Describe the bug**
If I want to position a camera and ensure that it stays locked to its position, there is no way to ensure a lock. There is a context menu item you can get by right clicking over Translate or rotate in the Transform component (on an entity that contains an added Camera)- selecting "Lock Transform Values" grays out the transform values so that they are not editable by numerical input into the fields, but this doesn't stop you from tumbling in the viewport and changing those values unimpeded.

**Steps to reproduce**
1. Create a new entity
2. Add a camera component to the entity and click on the "Be this Camera" button
3. Move it to a new position
4. Right click in the Transform Component on the Translate or Rotate Values and select "Lock Transform Values"
5. Now try to move in the viewport- you will see the position change in the supposed locked values

**Expected behavior**
Once locked, you should not be able to move in the viewport unless you switch cameras into one that is NOT locked

**Actual behavior**
The locking functionality locks the input field, but not the camera.

**Assets required**
You can test this on a completely empty scene and verify just by watching recorded translational/rotational values

**Found in Branch**
Latest Development

**Desktop/Device (please complete the following information):**
 - PC
 - Windows
 - 10
 - Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz   3.30 GHz
 - NVidia GeForce RTX 2080
 - 64.0 GB

**Additional context**

**Comment by hultonha** [comment]
@monroegm This is definitely a pain but I'm not sure this qualifies as Critical, I propose dropping this to Major and the viewport team will get to this soon
