### ISSUE TITLE
Whenever duplicating an object, camera switches back to Editor Camera (if not already looking through it)

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#5478]
**Describe the bug**
I was working on a scene recently that required the duplication of elements, and I found that even though I'd created a shot camera to view the scene from a constant vantage point, whenever I duplicated an element, the viewport would switch out of my shot camera and back to the Editor Camera.

**Steps to reproduce**
1. Create a new entity, add a mesh component, and search for sphere. When the sphere.fbx comes up, select it to add to the viewport
2. Create a new entity, add a camera component and click on "Be this Camera".  Then frame the sphere just created in the viewport.
3. Select the first created entity that contains the sphere, and press ctrl-d. When you do this you will see the camera switch back to the Editor Camera

**Expected behavior**
The duplication is successful, but the active camera does not change.

**Actual behavior**
The duplication happens AND the camera changes to the Editor Camera.

**Assets required**
Just the stuff mention above which ships with O3DE

**Found in Branch**
Latest Development

**Desktop/Device (please complete the following information):**
 - PC
 - Windows
 - 10
 - Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz   3.30 GHz
 - NVidia GeForce RTX 2080
 - 64.0 GB

**Additional context**
This bug makes it very difficult to construct scenes with recurring elements like trees that need to be instanced multiple times

**Comment by monroegm** [comment]
@AMZN-Igarri @hultonha FYI

**Comment by AMZN-Igarri** [comment]
> @AMZN-Igarri @hultonha FYI

Just tested it and I can't replicated. Thks was fixed with #5650
