### ISSUE TITLE
Transform Manipulator Hotkey Scaling

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#5515]
**Is your feature request related to a problem? Please describe.**
Yes- when working on scenes sometimes it is hard to grab handles of the transform manipulator due to its size. 

**Describe the solution you'd like**
A lot of DCC applications will allow the +/- buttons as hotkeys to scale up or down the size of the manipulator

**Describe alternatives you've considered**
The only way to circumvent this problem is by moving your camera position or switching to another camera. I've been running into issues with camera position not being retained lately so sometimes this is a big impediment to constructing a scene- especially when wanting to manipulate objects in the distance or when the handles are just offscreen from the camera frustrum

**Comment by monroegm** [comment]
@hultonha Is currently looking into the possibility of this

**Comment by hultonha** [comment]
This is related to an ongoing task around issues selecting manipulators, this is definitely a nice idea and something I think we can support pretty easily. I'm working on a number of viewport/manipulator polish items over the next little while so will be sure to take a look at this :+1:

**Comment by hultonha** [comment]
@benblack75 Please see this PR for updates to manipulators and manipulator bounds - https://github.com/o3de/o3de/pull/5959. This PR doesn't put the Translation Manipulator scaling on a hotkey (yet...) but it does add a new settings value - `ManipulatorViewBaseScale`. This can be modified in the Manipulator tab of `Edit -> Global Preferences -> Editor Settings`. The default value is 1.0 and be adjusted from 0.5 to 2.0. Feel free to have a play around with these settings (and the existing `LineBoundWidth`).

If this addresses the problem I think we can close this issue, if you're certain a shortcut key would be useful we can leave it open and potentially add that too in future.

**Comment by hultonha** [comment]
I'm closing this for now as the functionality is now available from the settings menu. If a shortcut is really required we can add this as a separate task.
