### ISSUE TITLE
Table Information getting cut off

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#5516]
**Is your feature request related to a problem? Please describe.**
I've seen many instances of QT Tables with information that is being cut off inside of fields in several different areas of O3DE. On most of these tables the option is turned off for allowing resizing of columns (usually driven by column headers) so that the user can see the information contained inside any obscured field. 
![configure_gems_cutoff](https://user-images.githubusercontent.com/50616575/141194520-8034be5e-c7fb-43aa-81a2-223fdad880c6.png)

**Describe the solution you'd like**
Allow for some way to see information obscured inside table items

**Comment by tkothadev** [comment]
As of PR  https://github.com/o3de/o3de/pull/13106, this should be resolved:


![](https://user-images.githubusercontent.com/112996779/201162530-ce9b059f-b486-4a6f-a478-efe4a2432406.gif)
