### ISSUE TITLE
Prefabs: Unable to reparent an external entity into a prefab unless an entity within the prefab is selected

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#5527]
**Describe the bug**
Unable to reparent an external entity into a prefab unless an entity within the prefab is selected.

**Pre-requisities**
1. Prefabs are enabled for the current project.

**Steps to reproduce**
1. Launch the Editor.
2. Create a new level.
3. Create 2 new entities under the Level root entity.
4. Create a prefab of one of the entities.
5. Enter Prefab Editing mode on the newly created prefab.
6. Without selecting an entity in the Prefab Editing mode, attempt to reparent the other entity into the prefab.

**Expected behavior**
External entities can be added to prefabs in focus mode without any entities selected.

**Actual behavior**
An entity in the prefab in focus mode must be selected before the user can drag an external entity in.

**Found in Branch**
stabilization/2110 installer

**Comment by AMZN-daimini** [comment]
This was recently fixed as part of this PR: https://github.com/o3de/o3de/pull/7559

Verified on latest development:
![dragWithNoSelection](https://user-images.githubusercontent.com/82231674/154570371-a9758696-c741-4045-9b14-a576a97bc287.gif)
