### ISSUE TITLE
Prefabs: Renaming the root entity of a prefab does not propagate to other instances

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#5528]
**Describe the bug**
Renaming the root entity of a prefab does not propagate to other instances.

**Pre-requisites**
1. Prefabs are enabled for the current project.

**Steps to reproduce**
1. Launch the Editor.
2. Create a new level.
3. Create an entity in the Outliner.
4. Create a prefab from the new entity.
5. Right-click the root entity of the new prefab, and rename.
6. Save the changes, and instantiate a new copy of the prefab.

**Expected behavior**
Root entity rename propagates to other prefab instances.

**Actual behavior**
Root entity rename only sticks with the edited instance.

**Found in Branch**
stabilization/2110 installer

**Comment by monroegm** [comment]
Current behavior appears to be correct. Renaming the container entity should not propagate because it is unique to the instance. Renaming entities underneath the container propagates.
