### ISSUE TITLE
Texture Settings Preset List Is Not Sorted

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#5534]
**Describe the bug**
In the Texture Settings Editor dialog, the "Active preset" combo box items are not sorted in any apparent order. They should be alpha-sorted.

**Steps to reproduce**
1. Run Material Editor
2. Find an image in the Asset Browser
3. Right-click, Edit Texture Settings...
4. Expand the "Active preset" combo box

**Expected behavior**
Items should be sorted alphabetically so they are easy to find.

**Actual behavior**
Items are not in alphabetical order.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/55155825/141217614-c8e72619-0158-4972-8905-54d250aacfb0.png)

**Found in Branch**
stabilization/2110

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen Threadripper 3970X 32-Core Processor    3.69 GHz
 - GPU GTX 1660 Super
 - Memory 64.0 GB

**Comment by VickyAtAZ** [comment]
Close the issue since the fix was submitted 6 weeks ago
