### ISSUE TITLE
[Light component] The parameter Height for the Polygon light is set to 0 improperly when operating any other parameter

### ISSUE THREAD

**Issue by instoneks2018** [o3de/o3de#5541]
**Describe the bug** 
the parameter Height for the Polygon light is set to `0.0` improperly when operating any other parameter on the `Light` panel,
and then, I try to fix this（delete the line of code https://github.com/o3de/o3de/blob/23faf4d36aafdb9f2fc38186d090d9143946e29d/Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/PolygonLightDelegate.cpp#L22 ), the `Height` value is unchanged, PTAL.      
**To Reproduce**
1.Open Editor.
2.Create a new Entity.
3.Add Light Component.
4.Select `Polygon` as Light type for light component.
5.Change the `Height` value in `Polygon Prism Shape`.
6.Change any other parameter on the `Light` panel.

**Expected behavior**
 The `Height` value set previously  is unchanged
**Screenshots**
1.Before changing  parameter, the `Height` value is `10.0` .
![before](https://user-images.githubusercontent.com/45937683/141291544-395512d2-11d2-4bea-813d-6e8e5a58f735.png)

2.After changing the change `Mode` from `Automatic` to `Explicit`，  the `Height` value is changed from `10.0` to `0.0`. If you change any other parameter on `Light` panel, the result is also the same.
![after](https://user-images.githubusercontent.com/45937683/141291638-2edab4f6-51f8-44b3-ab58-b3768caac096.png)
**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Intel I7-10700 2.90GHz (16 CPUs)]
- GPU [Intel(R) UHD Graphics 630]
- Memory [32GB]

**Additional context**

**Comment by invertednormal** [comment]
This isn't a bug, the behavior is intentional. Extruding the polygon doesn't change the lighting - polygon lights can only emit from a polygon plane, not a 3d surface. Perhaps we should create some way for the polygon light to disable or hide the height field to avoid this confusion.

**Comment by invertednormal** [comment]
Created a new issue for the UX problem #14472. Closing this one .
