### ISSUE TITLE
Changing which dll to use in a 3rdParty cmake file doesn't trigger a copy to the output folder when building

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#5542]
**Describe the bug**
The code that copies 3rdParty dlls to the output folder only checks timestamps to do the copy or not. This lead to situation that when the 3rdParty is modified to use a different dll (same name, different source folder), next time the project is built will not realize that the dll is different and it will not copy the dll, leaving the old one in the output folder.

**Steps to reproduce**
1. Configure and Build AutomatedTesting project in profile.
2. In a third party that has dlls, change its cmake file to use a different dll (which has the same name but different folder). For example, let's change PhysX 3rdParty, in your 3rdParty folder, open "packages\PhysX-4.1.2.29882248-rev3-windows\FindPhysX.cmake" file and change this:
````
set(PATH_TO_STATIC_LIBS ${_PACKAGE_DIR}/$<IF:$<CONFIG:debug>,debug/,$<$<CONFIG:profile>:profile/>>lib)
set(PATH_TO_SHARED_LIBS ${_PACKAGE_DIR}/$<IF:$<CONFIG:debug>,debug/,$<$<CONFIG:profile>:profile/>>bin)
````
to this:
````
set(PATH_TO_STATIC_LIBS ${_PACKAGE_DIR}/$<IF:$<CONFIG:debug>,debug/,$<$<CONFIG:profile>:debug/>>lib)
set(PATH_TO_SHARED_LIBS ${_PACKAGE_DIR}/$<IF:$<CONFIG:debug>,debug/,$<$<CONFIG:profile>:debug/>>bin)
````
Notice how the libs for profile should be using the debug dlls, not the profile ones.
3. Configure and Build AutomatedTesting project in profile again.

**Expected behavior**
The debug version of the dll (PhysX_64.dll) is copied into the output folder (bin\profile) from the 3rdParty package (packages\PhysX-4.1.2.29882248-rev3-windows\PhysX\pxshared\debug\bin\PhysX_64.dll)

**Actual behavior**
The dll (PhysX_64.dll)  of the debug version was not copied to the output folder (bin\profile), it still has the version from profile  (packages\PhysX-4.1.2.29882248-rev3-windows\PhysX\pxshared\profile\bin\PhysX_64.dll).

**Device**
Tested on windows, but it's likely it occurs in all platforms.

**Comment by moraaar** [comment]
This bug is important to be solved for this to work: https://github.com/o3de/3p-package-source/pull/66

The user can enable the macro `LY_PHYSX_PROFILE_USE_CHECKED_LIBS` during cmake configuration of O3DE so PhysX uses the "checked" version of dlls (instead of "profile"), which is useful to check errors inside PhysX SDK. 

But due to this bug, when the macro is enabled the checked version of dlls are not copied to the output folder.

**Comment by amznestebanpapp** [comment]
We currently just check that the library being copied is newer than the target, we can add a check there for size. I wouldnt do a hash check because will take too much time. 
If the size is not enough or takes too much, we can store the source path in the lock file and use that to compare if it is coming from a different place.

**Comment by moraaar** [comment]
Thanks for fixing this @amznestebanpapp 

I can confirm that now switching `LY_PHYSX_PROFILE_USE_CHECKED_LIBS` between on and off it does trigger the copy of the right dlls to the output folder.
