### ISSUE TITLE
AssetProcessorBatch work time is O(n^2), where n is new files count

### ISSUE THREAD

**Issue by oleksiiterekhov** [o3de/o3de#5545]
**Describe the bug**
Cleanup Cache folder or starting work with new really asset-rich project stuck on first asset processing.
When add files incrementally -> AssetProcessor processing time is significantly reduced

**Steps to reproduce**
1. Create 200 000 empty .bk2(or WWISE .bnk) files in Asset folder
2. Clean Cache folder
3. Measure AssetProcessorBatch runtime
4. Remove all .bk2/.bnk files
5. Clean Cache folder
6. Measure time of (Run AP -> add 20k files -> Run AP -> add 20k files ->....) with same amount of files

**Expected behavior**
Processing time for new files must be ~ O(n)

**Actual behavior**
Processing time O(n^2)

```
o3de:
new files	processing time, seconds 
1468		423
21468		625
41468		874
61468		1336
81468		1884
101468		2711
121468		3481

Lumberyard:
new files	processing time, seconds 
1401		30
19647		195
37893		448
56139		811
74385		1274
92631		1877
110877		2519
129123		3341
147369		4066
165615		4978
256845		11213
366321		22305
```
o3de:
Cleanup -> Run AP -> add 20k files -> Run AP -> add 20k files ->.... for 120k files: processing time 3481s -> 852s on same rig(speedup x4.0)!

Lumberyard:
Cleanup -> Run AP -> add 20k files -> Run AP -> add 20k files ->.... for 360k files: processing time 22305s -> 3480s on same rig(speedup x6.5)!

**Assets required**
All assets created by python one-liner
```
import sys
from pathlib import Path

files_count = int(sys.argv[1])

for current_file in range(files_count):
    name = f'{current_file:06}'

    folder = Path(f'{name[0:2]}/{name[2:4]}')
    file_name = folder / f'{name[4:]}.bk2'
    if not file_name.exists():
        folder.mkdir(exist_ok=True, parents=True)
        with open(file_name, 'w') as f:
            f.write(f'{current_file}\n')
```

**Screenshots/Video**

![AssetProcessor_time](https://user-images.githubusercontent.com/87365970/141300615-2dec73c6-c998-4ccc-87df-e0aa52388d94.png)

**Found in Branch**
o3de main/development, Lumberyard 1.26/1.28

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I5-7400, Intel i7-8700, AMD Ryzen 9 3900X
 - GPU -
 - Memory 16/32/64 GB

**Additional context**
All tests completed on SSD (one SATA drive, three NVME drives in RAID)
All data processing skipped - AssetProcessor use simple copy-rule for .bk2 and .bnk files
In my project ~650k assets, clean rebuilds ~15-18h

Bonus: I can predict the time very accurately for my Intel i7-8700 (12 threads, SSD, 64GB) by formula: 
```
time = (1/6) * (files/1000)^2 
```

**Comment by lmbr-pip** [comment]
This may be fixed, we should try to repro with latest.

**Comment by amzn-mike** [comment]
I've re-run this test locally with the following results:

| File Count|	Time (s)|
|-----|-----|
|0|	25.47|
|2000	|33.45|
|20000	|107.91|
|40000	|192.33|
|60000	|288.15|

![image](https://user-images.githubusercontent.com/80125227/176558596-835d415c-4c78-4d04-a216-e4a4820057ae.png)

This seems to have already been fixed by previous work, likely work done at the end of last year to improve dependency resolution which had a n^2 problem.

**Comment by oleksiiterekhov** [comment]
@amzn-mike 
Please re-check on bigger scale 100k-200k-300k

My results:
Files|Time, seconds
----:|---:
50k|956
75k|1306
100k|2021
125k|2867
150k|3984
175k|5225
200k|6693
225k|8152
250k|9967

In general: time ~ (n/2600)^2

Blue: AssetProcessor time
Orange: (n/2600)^2 + constanta
![image](https://user-images.githubusercontent.com/87365970/177034219-6003ee6c-4d8f-43ff-9259-b895fd292311.png)
