### ISSUE TITLE
Prefabs: Toggling Visibility/Lock for a prefab instance dirties all other instances

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#5556]
**Describe the bug**
Toggling Visibility/Lock for a prefab instance dirties all other instances. When visibility is toggled, all instances react to the toggle. When lock is toggled, only the instance that was locked is locked. When either option is toggled, all instances are dirtied.

**Pre-requisites**
1. Prefabs are enabled for the current project.

**Steps to reproduce**
1. Launch the Editor.
2. Create a new level.
3. Create a simple prefab with a visual element, duplicate it several times, and position the instances so you can see them all.
4. Save the prefab.
5. Toggle on Visibility on one instance.
6. Save the prefab.
7. Toggle on Lock on one instance.

**Expected behavior**
Only the specified instance is affected by Visibility/Lock toggling.

**Actual behavior**
When visibility is toggled, all instances react to the toggle. When lock is toggled, only the instance that was locked is locked. When either option is toggled, all instances are dirtied.

**Found in Branch**
stabilization/2110 installer

**Comment by monroegm** [comment]
Current behavior appears to be correct. Toggling visibility or locking the container entity should not propagate because it is unique to the instance. Toggling visibility or locking entities underneath the container propagates.
