### ISSUE TITLE
Add support for configuring (default) PAK Modes via a CMake Cache Variable

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#5574]
**Is your feature request related to a problem? Please describe.**
Currently the default mode that O3DE uses when loading files via the Archive system is that in Release configuration the default mode for searching for files is mounted PAK files only, while in non-Release configurations the default is search the file system followed by searching mounted PAKs.

This is actually controllable via the [sys_PakPriority](https://github.com/o3de/o3de/blob/development/Code/Framework/AzFramework/AzFramework/Archive/ArchiveVars.h#L-45-47) Console Variable.

In release configuration it is quite hard to set override the `sys_PakPriority` variable to search the file system, as the only .cfg/.setreg files that are loadable must be placed within a Pak. The current way to override the Archive system search mode is by 
1. Running the configuration with the parameter `sys_PakPriority=0` or
2. Adding a `<project-path>/Registry/<name>.game.setreg` or `<project-path>/autoexec.cfg` that sets the sys_PakPriority CVAR to `0` and then running the AssetProcessor to make sure the Project Cache is updated with those files.

In the opposite vein, it is a easier to override the Archive system file search to be mounted Pak files only in debug/profile as those configurations can load any `<name>.game.setreg` files directly from the <project-path>/Registry without it needing to be in the cache.

**Describe the solution you'd like**
Add a CMake Cache variable that allows the user to configure the Archive system file search mode directly through it.
The release build configuration can still indirectly set the default PAK mode to build by initializing the Cache variable, but that Cache variable would be overridable by the user, 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by oleksiiterekhov** [comment]
Prediction: Cheaters will use this feature for easy asset mangling in game-as-a service and competitive games.

**Comment by lumberyard-employee-dm** [comment]
> Prediction: Cheaters will use this feature for easy asset mangling in game-as-a service and competitive games.

The feature is only available at build time of GameLauncher itself.
The development team that builds the GameLauncher source code would be the people determining what the default PAK mode is in release.

The behavior of `sys_PakPriority` being changable via setting the CVar via a command line option already exists and this feature will not change that.
Disabling of running console commands via the command line should be disabled by the `AZ::Console` code itself.
That is actually orthogonal to this work.
