### ISSUE TITLE
Camera Dolly Issues

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#5602]
**Describe the bug**
Sometimes when I am trying to dolly the camera, the dolly does not move in the expected direction towards/away from directed aim of the camera, but more in a way approaching perpendicular to what it should.

**Steps to reproduce**
The only way to ensure that you will see this error is to use any scene populated with several elements and just start dollying at different elements in the scene. It happens enough that you are likely to see it, even though what causes it seems arbitrary. I will note that I usually see it when I'm already close to an object but am attempting to edge in just a little closer- the distances are usually right on the cusp of dollying too far, pushing through/beyond the object.

**Expected behavior**
The direction of the dolly should always move parallel to the direction the camera is pointed. This error runs noticeably counter to that- you don't necessarily move closer or farther away from where the camera is pointed, but instead move laterally. See video

https://user-images.githubusercontent.com/50616575/141540459-c95cc6e4-b22e-4f2b-b6e0-1482a7d366e5.mp4

**Actual behavior**
The camera is not moving towards or away from the direction that the camera is pointed towards

**Found in Branch**
Latest Development

**Desktop/Device (please complete the following information):**
- PC
 - Windows
 - 10
 - Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz   3.30 GHz
 - NVidia GeForce RTX 2080
 - 64.0 GB

**Comment by monroegm** [comment]
I don't believe this is a bug with the implementation. There may be a UX conversation to be had about if the feature behaves the way users expect

**Comment by hultonha** [comment]
This should be fixed by https://github.com/o3de/o3de/pull/5658 I'm pretty sure

This is a problem with the 'Be this camera' feature - fix should be in stabilization soon

**Comment by hultonha** [comment]
This is now merged to stabilization - https://github.com/o3de/o3de/pull/5658. Could you please confirm the issues is fixed @benblack75. Thanks!

**Comment by hultonha** [comment]
Closing as fixed per #5658
