### ISSUE TITLE
Building any project using the Project Manager built with target INSTALL fails

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#5611]
**Describe the bug**
It is not possible to build any project via the Project Manager when it is launched from the o3de-install folder (after following the [Pre-built SDK engine guide](https://o3de.org/docs/welcome-guide/setup/setup-from-github/#:~:text=Use%20CMake%20to%20build,target%20INSTALL%20--config%20profile%20--%20/m)) due to the following error:
```
CMake Error at C:/o3de-install/cmake/LYWrappers.cmake:690 (if):
  Maximum recursion depth of 1000 exceeded
Call Stack (most recent call first):
  C:/o3de-install/cmake/SettingsRegistry.cmake:66 (ly_de_alias_target)
  C:/o3de-install/cmake/SettingsRegistry.cmake:72 (ly_get_gem_load_dependencies)
```
Please note that the Project Manager built following the instructions for building the [Source Engine](https://o3de.org/docs/welcome-guide/setup/setup-from-github/#:~:text=The%20following%20example,Editor%20--config%20profile%20--%20/m) does build projects successfully without the mentioned issue.

Please refer to the attached video and logs for more information.

**Steps to reproduce**
1. Follow the [Pre-built SDK engine guide](https://o3de.org/docs/welcome-guide/setup/setup-from-github/#:~:text=Use%20CMake%20to%20build,target%20INSTALL%20--config%20profile%20--%20/m).
2. Launch O3DE.exe from the o3de-install/bin/Windows/profile/Default folder.
3. Create a new project.
4. Build the created project.

**Expected behavior**
The project is built without any issues.

**Actual behavior**
The project is not built due to the errors.

**Video**

https://user-images.githubusercontent.com/86953659/141764735-10954811-9ef3-44cf-954a-f7b33a2fc2ce.mp4

**Found in Branch**
Stabilization/2110 (76b7e73)

**Desktop**
Device: PC
OS: Windows
Version: 10
CPU: Intel i5-9600K
GPU: RTX 2070
Memory: 16GB

**Additional context**
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/7537837/CMakeProjectBuildError.log)
[CMakeOutput.log](https://github.com/o3de/o3de/files/7537839/CMakeOutput.log)

**Comment by amznestebanpapp** [comment]
May be related to https://github.com/o3de/o3de/pull/5581
@lumberyard-employee-dm for awareness

**Comment by lumberyard-employee-dm** [comment]
@lumberyard-employee-dm is now aware.
It looks some kind of circular dependency between two gem targets
```
  C:/o3de-install/cmake/SettingsRegistry.cmake:72 (ly_get_gem_load_dependencies)
  C:/o3de-install/cmake/SettingsRegistry.cmake:72 (ly_get_gem_load_dependencies)
```

**Comment by amznestebanpapp** [comment]
`Multiplayer.Builders` has a runtime dependency to `Multiplayer.Editor`
`Multiplayer.Editor` has a build dependency to `Multiplayer.Builders`

@AMZN-Olex is taking a look at that dependency
I will add a check so we get a better error message of the problem.
