### ISSUE TITLE
AssetProcessor: no WWISE sound files in cache when wwise_config.json exists

### ISSUE THREAD

**Issue by oleksiiterekhov** [o3de/o3de#5617]
**Describe the bug**
No sound files in cache if you fill wwise_config.json

**Steps to reproduce**
1. Create and fill sounds/wwise/wwise_config.json 
2. Process sounds with WWISE (sounds/wwise/windows, sounds/wwise/linux, ...)
3. Run AssetProcessorBatch
4. No sound files files in Cache

**Expected behavior**
**PC** sound files in Cache/**pc**/sounds/wwise/**windows**
**restricted-platform provo** sound files in Cache/**provo**/sounds/wwise/<restricted-platform>
**restricted-platform xenia** sound files in Cache/**xenia**/sounds/wwise/<restricted-platform>

**Actual behavior**
No .bnk/.wem files in Cache

I think bug in builder CreateJob() function:
Gems\AudioEngineWwise\Code\Source\Builder\WwiseBuilderWorker.cpp
```
   if (AZ::StringFunc::StartsWith(sourceFile, platformConfig.m_wwisePlatform, true))
```

In Gems\AudioEngineWwise\Code\Source\Engine\AudioSystemImpl_wwise.cpp we use **m_bankSubPath** instead **m_wwisePlatform**
```
    AZ::StringFunc::AssetDatabasePath::Join(bankPath.c_str(), platformMap.m_bankSubPath.c_str(), platformPath);
```

**Assets required**
N/A

**Screenshots/Video**
N/A

**Found in Branch**
main and development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel I5-7400
 - Memory: 16GB

**Additional context**
Same problem with Lumberyard 1.26 1.27.1 1.28

**Comment by amzn-phist** [comment]
@oleksiiterekhov  Can you please post your `wwise_config.json` here?  I just tested it on my end and I'm able to get the cache looking correct:
![wwise_multi_platform_cache](https://user-images.githubusercontent.com/52085794/143082803-6d6c1e7f-08b5-4561-86c8-9e2dbd725a06.png)

**Comment by oleksiiterekhov** [comment]
> @oleksiiterekhov Can you please post your `wwise_config.json` here? I just tested it on my end and I'm able to get the cache looking correct: ![wwise_multi_platform_cache](https://user-images.githubusercontent.com/52085794/143082803-6d6c1e7f-08b5-4561-86c8-9e2dbd725a06.png)

Hi!

```
{
    "platformMaps": [{
            "assetPlatform": "provo",
            "altAssetPlatform": "",
            "enginePlatform": "PS4",
            "wwisePlatform": "PS4",
            "bankSubPath": "ps4"
        },
        {
            "assetPlatform": "pc",
            "altAssetPlatform": "",
            "enginePlatform": "Windows",
            "wwisePlatform": "Windows",
            "bankSubPath": "windows"
        },
        {
            "assetPlatform": "xenia",
            "altAssetPlatform": "",
            "enginePlatform": "XboxOne",
            "wwisePlatform": "XboxOne",
            "bankSubPath": "xboxone"
        }
    ]
}
```
generated by 
https://github.com/o3de/o3de/blob/development/Gems/AudioEngineWwise/Tools/WwiseConfig/setup_wwise_config.py

**Comment by amzn-phist** [comment]
I tried again with a newly created project and ran `AssetProcessorBatch` rather than `AssetProcessor`.  My `wwise_config.json` looks "similar" to yours, at least the pc/windows platform which I'm testing on.  I get the expected files in my cache again:
![wwise_multi_platform_cache_2](https://user-images.githubusercontent.com/52085794/143131884-8d65bb5e-fa27-4a9e-bc70-ea08db392c61.png)

If you have any more information about your setup/configuration that you can give, please do.  Right now I'm unable to reproduce this and I don't have any suspicions about what may be causing your issue.

**Comment by oleksiiterekhov** [comment]
Maybe in your case works default code path in https://github.com/o3de/o3de/blob/development/Gems/AudioEngineWwise/Code/Source/Builder/WwiseBuilderWorker.cpp:
```
            // If there are no platform mappings (i.e. there was no config file), we want to
            // process the job anyways.
            bool createJob = m_wwiseConfig.m_platformMappings.empty();
```
and the createJob is always **true**

Please try with my config file and with several subfolders in sounds\wwise
```
wwise\ps4
wwise\windows
wwise\xboxone
```
And look on pc Cache folder - if you receive all three (ps4 + windows + xboxone) subfolders - your wwise_config.json skipped

Or in your case templates in `Gems/AudioEngineWwise/Tools/WwiseConfig/Platform/` contains same value for `wwisePlatform` and `bankSubPath`? 

Because AssetProcessor use `wwisePlatform` to detect valid subfolder:
```
                    // If the source file now begins with the right Wwise platform folder, create the job...
                    if (AZ::StringFunc::StartsWith(sourceFile, platformConfig.m_wwisePlatform, true))
                    {
                        createJob = true;
                        break;
                    }
```
But game use `bankSubPath`:
```
    AZ::StringFunc::AssetDatabasePath::Join(bankPath.c_str(), platformMap.m_bankSubPath.c_str(), platformPath);

```

Or for some reason all checks in AZ::StringFunc::StartsWith were case-insensitive? 

I tried to add debug logging to WwiseBuilderWorker.cpp (`WwiseBuilderWorker::CreateJobs`) and received empty Cache with wwise_config.json or saw sounds from all platforms in each `Cache/<platform>` without wwise_config.json

**Comment by amzn-phist** [comment]
Both my screenshots show that I have a `wwise_config.json` file there and I did have multiple platforms of banks.

The call to `AZ::StringFunc::StartsWith(sourceFile, platformConfig.m_wwisePlatform, true)` is a case-sensitive check - the last bool parameter controls case sensitivity.  That's checking the source path, maybe you can try it with that bool turned false.

If you are able to debug, I would suggest this:
Set `AssetBuilder` as your startup project, and add debugging parameters like this:
`--project-path=<your_project_path> --task=debug --platform=pc --input=sounds/wwise/windows/init.bnk`

Run an instance of AssetProcessor first, then launch AssetBuilder in the debugger, you should be able to hit breakpoints in the `CreateJobs` and `ProcessJob` functions.

**Comment by amzn-phist** [comment]
FYI: Stepping through the Wwise Builder code led me to find and fix some other minor things, unrelated to this issue: #6048
