### ISSUE TITLE
Atom_TestSuite_Main fails on Linux

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#5628]
**Describe the bug**
Tests in the module Atom_TestSuite_Main were failing at the time that the Linux Automated Review pipeline enabled python-based tests, and these were disabled from running in AR.

When this module is passing, make sure to re-enable these tests in AR by removing AutomatedTesting::Atom_TestSuite_Main from both https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Linux/build_config.json#L86 ***AND*** https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Linux/build_config.json#L99

**Steps to reproduce**
To reproduce the failures seen in these tests, take the following steps on a machine running Ubuntu 20.04 LTS:

1. Acquire, configure, and build O3DE in the profile configuration ([guide](https://o3de.org/docs/welcome-guide/setup/setup-from-github/)) 
2. Run the AssetProcessorBatch binary to pre-process all assets
3. Execute CTest targeting this module, from inside working directory `../o3de/build/linux`
   - `ctest -C profile -R AutomatedTesting::Atom_TestSuite_Main --no-tests=error`

**Expected behavior**
All tests pass

**Actual behavior**
One or more tests fail

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04 LTS

**Additional context**
If a test seems to be randomly failing, please follow [this intermittent failure guide](https://github.com/o3de/sig-testing/blob/main/intermittent_failures.md)

If a specific test is not intended to execute on Linux, conditionally disable it by adding the following [pytest marker](https://docs.pytest.org/en/6.2.x/skipping.html#skipping-test-functions): `@pytest.mark.skipif(ly_test_tools.Linux, reason="Some reason this is not available")`

If an entire feature is not intended to be available Linux, then conditionally disable that module's registration and test-registration in its CMakeLists.txt files following the Platform Abstraction Layer (PAL).

**Comment by jromnoa** [comment]
Atom_TestSuite_Main fails due to this issue: https://github.com/o3de/o3de/issues/8380

No test code changes are required. Will re-activate the tests when this issue is resolved.

**Comment by jromnoa** [comment]
To help resolve this issue and re-add the tests until https://github.com/o3de/o3de/issues/8380 is fixed, we are going to comment out the Sort Key property portion of the test and un-comment it once its fixed.

**Comment by jromnoa** [comment]
Resolved in https://github.com/o3de/o3de/pull/8386 - bug will be fixed in https://github.com/o3de/o3de/issues/8380

Closing.
