### ISSUE TITLE
[Animation] In Audio Animation, the Evnet drop-down list box should be used to select an existing event. The joint function needs to be specified.

### ISSUE THREAD

**Issue by nielianpeng** [o3de/o3de#5642]
**Is your feature request related to a problem? Please describe.**
[Animation] In Audio Animation, the Evnet drop-down list box should be used to select an existing event. The joint function needs to be specified.

**Describe the solution you'd like**
1. You can directly select an existing event.

**Describe alternatives you've considered**
1. You have to enter events by yourself. If you enter events that do not exist, no corresponding prompt is displayed.

**Additional context**
[Test Procedure] Mandatory
1. Open S1Demo in UCDDemoDev.
2. Choose Scripts > Character > nz_01 under Entity Outlook.
3. Click Add Component under Entity Inspector.
4. Enter audio and select Audio Animation.
5. Click Add of the Audio Animation component.
6. Select an event on the right of Event.

**Comment by AMZN-daimini** [comment]
@nielianpeng Can you provide more information? If this is related to the audio system, then maybe this should be redirected to the graphics-audio sig.

**Comment by monroegm** [comment]
Closing due to lack of response. Please reopen or file a new ticket in the future if this is still a desired feature.
