### ISSUE TITLE
Editor crashes after leaving Game Mode for a second time in a custom level

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#5646]
**Describe the bug**
Leaving Game Mode twice in a level with a script targeting an UI canvas and containing multiple Input Handlers and Repeater nodes with short intervals crashes the Editor. Disabling Input Handler nodes in the assigned script prevents the issue from occurring. However, the Editor does not crash with a script created only with the mentioned Input Handlers and the specific cause of the crash could not be pinpointed.

**Steps to reproduce**
1. Extract the attached level and assets to your project folder.
2. Launch the Editor.
3. Load the UI level.
4. Enter and leave the Game Mode twice.

**Expected behavior**
The Editor remains stable.

**Actual behavior**
The Editor crashes.

**Assets required**

[assets_and_level.zip](https://github.com/o3de/o3de/files/7546309/assets_and_level.zip)

**Call Stack Trace:**
```
25) 00007FF8AFD8B7F7 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FF8B22751B0 (ntdll) : memset
23) 00007FF8B225C766 (ntdll) : _C_specific_handler
22) 00007FF8B22720CF (ntdll) : _chkstk
21) 00007FF8B2221454 (ntdll) : RtlRaiseException
20) 00007FF8B2270BFE (ntdll) : KiUserExceptionDispatcher
19) C:\o3de\o3de\Code\Framework\AzCore\AzCore\Memory\HphaSchema.cpp (1597) : AZ::HpAllocator::coalesce_block
18) C:\o3de\o3de\Code\Framework\AzCore\AzCore\Memory\HphaSchema.cpp (2104) : AZ::HpAllocator::tree_free
17) C:\o3de\o3de\Code\Framework\AzCore\AzCore\Memory\HphaSchema.cpp (2643) : AZ::HphaSchema::DeAllocate
16) C:\o3de\o3de\Code\Framework\AzCore\AzCore\Script\ScriptContext.cpp (1466) : LuaMemoryHook
15) 00007FF85951C187 (EditorLib) : luaM_realloc_
14) 00007FF85951D714 (EditorLib) : luaF_freeproto
13) 00007FF85951F5DB (EditorLib) : luaC_upvdeccount
12) 00007FF85951F785 (EditorLib) : luaC_upvdeccount
11) 00007FF85951E3F0 (EditorLib) : luaC_runtilstate
10) 00007FF85951E1EC (EditorLib) : luaC_fullgc
 9) 00007FF859516D47 (EditorLib) : lua_gc
 8) C:\o3de\o3de\Code\Framework\AzCore\AzCore\Script\ScriptSystemComponent.cpp (301) : AZ::ScriptSystemComponent::GarbageCollect
 7) C:\o3de\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1541) : AZ::Internal::EBusContainer<AZ::ScriptSystemRequests,AZ::ScriptSystemRequests,0,0>::Dispatcher<AZ::EBus<AZ::ScriptSystemRequests,AZ::ScriptSystemRequests> >::Broadcast<void (
 6) C:\o3de\o3de\Gems\ScriptCanvas\Code\Editor\Components\EditorScriptCanvasComponent.cpp (486) : ScriptCanvasEditor::EditorScriptCanvasComponent::OnStopPlayInEditor
 5) C:\o3de\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1360) : AZ::Internal::EBusContainer<AzToolsFramework::EditorEntityContextNotification,AzToolsFramework::EditorEntityContextNotification,0,1>::Dispatcher<AZ::EBus<AzToolsFramework::Ed
 4) C:\o3de\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Entity\EditorEntityContextComponent.cpp (539) : AzToolsFramework::EditorEntityContextComponent::StopPlayInEditor
 3) C:\o3de\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1541) : AZ::Internal::EBusContainer<AzToolsFramework::EditorEntityContextRequests,AzToolsFramework::EditorEntityContextRequests,0,0>::Dispatcher<AZ::EBus<AzToolsFramework::EditorEnti
 2) C:\o3de\o3de\Code\Editor\GameEngine.cpp (596) : CGameEngine::SwitchToInEditor
 1) C:\o3de\o3de\Code\Editor\GameEngine.cpp (701) : CGameEngine::SetGameMode
```

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/141987126-40dfd793-0074-45d0-a106-9591e18707f9.mp4

**Found in Branch**
The issue occurs in Development ([3791149](https://github.com/o3de/o3de/commit/3791149c6bb18d007ee375f592bdd031871f793d)) and Stabilization_2110 ([7031147](https://github.com/o3de/o3de/commit/7031147e324602fb20fcfe2070a942bf9eb4594a))

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/7546358/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7546359/error.log)
[dump.zip](https://github.com/o3de/o3de/files/7546360/dump.zip)

**Comment by carlitosan** [comment]
How did disabling the input nodes stop the issue? Which graph did you disable them in? I still get the issue myself.

**Comment by carlitosan** [comment]
I also get this, after stopping game mode the first time, and it seems problematic:


Enable Accelerators
Exited game mode
(System) - 
==================================================================
(System) - Trace::Assert
 E:/github/o3de/Gems/LyShine/Code/Source/UiCanvasManager.cpp(519): (13580) 'void __cdecl UiCanvasManager::ReleaseCanvasDeferred(class AZ::EntityId)'
(System) - Canvas entity not found by ID
(System) - ------------------------------------------------
(System) - E:\github\o3de\Gems\LyShine\Code\Source\UiCanvasManager.cpp (519) : UiCanvasManager::ReleaseCanvasDeferred
(System) - E:\github\o3de\Gems\LyShine\Code\Source\World\UiCanvasAssetRefComponent.cpp (246) : UiCanvasAssetRefComponent::Deactivate
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\Component\Entity.h (400) : AZ::Entity::DeactivateComponent
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\Component\Entity.cpp (239) : AZ::Entity::Deactivate
(System) - E:\github\o3de\Code\Framework\AzFramework\AzFramework\Entity\GameEntityContextComponent.cpp (314) : AzFramework::GameEntityContextComponent::DestroyGameEntityInternal
(System) - E:\github\o3de\Code\Framework\AzFramework\AzFramework\Entity\GameEntityContextComponent.cpp (251) : AzFramework::GameEntityContextComponent::DestroyGameEntity
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\typetraits\invoke_traits.h (178) : AZStd::Internal::INVOKE<void (__cdecl AZ::Data::AssetCatalogRequests::*)(AZ::Uuid const &),AZ::Data::AssetCatalogRequests * &,AZ::Uuid const &,void>
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\function\invoke.h (39) : AZStd::invoke<void (__cdecl AZ::Data::AssetCatalogRequests::*)(char const *),AZ::Data::AssetCatalogRequests * &,char const (&)[6]>
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\EBus\Policies.h (438) : AZ::EBusEventProcessingPolicy::Call<void (__cdecl AZ::Data::AssetCatalogRequests::*)(AZ::Uuid const &),AZ::Data::AssetCatalogRequests * &,AZ::Uuid const &>
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1541) : AZ::Internal::EBusContainer<AzFramework::GameEntityContextRequests,AzFramework::GameEntityContextRequests,0,0>::Dispatcher<AZ::EBus<AzFramework::GameEntityContextRequests,A
(System) - E:\github\o3de\Code\Framework\AzFramework\AzFramework\Spawnable\SpawnableEntitiesManager.cpp (487) : AzFramework::SpawnableEntitiesManager::ProcessRequest
(System) - E:\github\o3de\Code\Framework\AzFramework\AzFramework\Spawnable\SpawnableEntitiesManager.cpp (210) : `AzFramework::SpawnableEntitiesManager::ProcessQueue'::`4'::<lambda_1>::operator()<AzFramework::SpawnableEntitiesManager::DespawnAllEntitiesCommand &>
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\typetraits\invoke_traits.h (209) : AZStd::Internal::INVOKE<`AzFramework::SpawnableEntitiesManager::ProcessQueue'::`15'::<lambda_2>,AzFramework::SpawnableEntitiesManager::DespawnAllEntitiesCommand &>
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\function\invoke.h (39) : AZStd::invoke<`AzFramework::SpawnableEntitiesManager::ProcessQueue'::`4'::<lambda_1>,AzFramework::SpawnableEntitiesManager::DespawnAllEntitiesCommand &>
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\containers\variant_impl.h (375) : AZStd::variant_detail::visitor::variant::value_visitor<`AzFramework::SpawnableEntitiesManager::ProcessQueue'::`4'::<lambda_1> >::operator()<AZStd::variant_detail::alternati
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\typetraits\invoke_traits.h (209) : AZStd::Internal::INVOKE<AZStd::variant_detail::visitor::variant::value_visitor<`AzFramework::SpawnableEntitiesManager::ProcessQueue'::`4'::<lambda_1> >,AZStd::variant_deta
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\function\invoke.h (39) : AZStd::invoke<AZStd::variant_detail::visitor::variant::value_visitor<`AzFramework::SpawnableEntitiesManager::ProcessQueue'::`4'::<lambda_1> >,AZStd::variant_detail::alternative_impl
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\containers\variant_impl.h (246) : AZStd::variant_detail::visitor::impl::dispatcher<2>::dispatch<AZStd::variant_detail::visitor::variant::value_visitor<`AzFramework::SpawnableEntitiesManager::ProcessQueue'::
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\containers\variant_impl.h (209) : AZStd::variant_detail::visitor::impl::visit_alt<AZStd::variant_detail::visitor::variant::value_visitor<`AzFramework::SpawnableEntitiesManager::ProcessQueue'::`15'::<lambda_
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\containers\variant_impl.h (340) : AZStd::variant_detail::visitor::variant::visit_alt<AZStd::variant_detail::visitor::variant::value_visitor<`AzFramework::SpawnableEntitiesManager::ProcessQueue'::`15'::<lamb
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\containers\variant_impl.h (357) : AZStd::variant_detail::visitor::variant::visit_value<`AzFramework::SpawnableEntitiesManager::ProcessQueue'::`15'::<lambda_2>,AZStd::variant<AzFramework::SpawnableEntitiesMa
(System) - E:\github\o3de\Code\Framework\AzCore\AzCore\std\containers\variant.inl (298) : AZStd::visit<`AzFramework::SpawnableEntitiesManager::ProcessQueue'::`15'::<lambda_2>,AZStd::variant<AzFramework::SpawnableEntitiesManager::SpawnAllEntitiesCommand,AzFramework:
(System) - E:\github\o3de\Code\Framework\AzFramework\AzFramework\Spawnable\SpawnableEntitiesManager.cpp (233) : AzFramework::SpawnableEntitiesManager::ProcessQueue
(System) - E:\github\o3de\Code\Framework\AzFramework\AzFramework\Spawnable\SpawnableEntitiesManager.cpp (190) : AzFramework::SpawnableEntitiesManager::ProcessQueue
(System) - E:\github\o3de\Code\Framework\AzFramework\AzFramework\Spawnable\SpawnableSystemComponent.cpp (127) : AzFramework::SpawnableSystemComponent::ProcessSpawnableQueue
(System) - ==================================================================

**Comment by carlitosan** [comment]
I don't think this is a script issue. If one disables all of the nodes, and simply continues start/stop in editor, eventually it will crash. I think the : UiCanvasManager::ReleaseCanvasDeferred issue needs to be solved first.

**Comment by LB-BartoszDudzinski** [comment]
Disabling both Input Handler or maybe both groups with them resulted for me in stable GM. I couldn't repo this issue. At least when leaving GM 3-4 times.

The Assert is already reported in the Jira.

**Comment by monroegm** [comment]
Depends on #2782

**Comment by lsemp3d** [comment]
Hi @monroegm! can you comment why it was re-assigned to @carlitosan ? It does not appear to be related to scripting, but more of a low level lyshine issue?

**Comment by AMZN-mnaumov** [comment]
it's been reassigned to me just updated gh

**Comment by AMZN-mnaumov** [comment]
I've done some investigating, it does not look like this issue depends on #2782 it looks like just an unnecessary assert that happens in any scene with UI Canvas and could probably be removed.

**Comment by michabr** [comment]
I have a PR up for #2782 here https://github.com/o3de/o3de/pull/6260. However that does not seem to affect the outcome of this issue. After further investigation, this appears to be related to memory corruption that occurs during the initialization of the ScriptCanvas runtime component.

Defining DEBUG_ALLOCATOR in Code\Framework\AzCore\AzCore\Memory\HphaSchema.cpp shows the memory problem occurs during ScriptCanvas::RuntimeComponent::InitializeExecution().

With above steps, the crash occurs when exiting game mode because that's when garbage collection happens but if you uncomment the DEBUG_ALLOCATOR define you can see that the problem manifests during initialization and not shutdown.

If the attached script canvas is modified to remove some nodes such as the input node groups, the problem goes away. So it could be that this script canvas is exceeding a maximum of some array capacity and overwriting memory.

**Comment by svitlani** [comment]
@LB-BartoszDudzinski, can you please verify is the fix mentioned above relevant for this issue? Do you still encounter this problem? Thank you!

**Comment by LB-BartoszDudzinski** [comment]
Hi, @svitlani ! I am afraid that the mentioned Fix did not fix this problem. The issue still occurs in development (https://github.com/o3de/o3de/commit/d6c419d6304536d9bb1e4b44a47118b28584c920)

**Comment by svitlani** [comment]
Thanks so much for checking, @LB-BartoszDudzinski !! @michabr ,@carlitosan, @lsemp3d for your visibility.

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed. I played through the intro twice in a row without issue.

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in development.

Thanks a lot :)
