### ISSUE TITLE
Newly applied texture disappears

### ISSUE THREAD

**Issue by olegbc1** [o3de/o3de#5666]
Submitting on behalf of a customer. See recording. After applying a texture to an object and creating a new entity, the texture disappears. Using stabilization build from approx. 2 wks ago. 

https://user-images.githubusercontent.com/9222334/142054997-2a95b794-00b2-4e17-8828-ca4f0063e18e.MOV

**Comment by superkitcath** [comment]
Hi @olegbc1! This should have been fixed in the latest stab; can you verify and confirm? Thanks!

**Comment by wintermute-motherbrain** [comment]
@olegbc1 this should be fixed in both stabilization and development.  Can you please confirm this issue no longer occurs?

**Comment by olegbc1** [comment]
@wintermute-motherbrain thanks for confirming. I will reach out to the customer next week and reopen if the issue persists.
