### ISSUE TITLE
Editor crashes after restoring the default layout

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#5699]
**Describe the bug**
Restoring the default layout of the Editor silently crashes it.

This issue does not occur on Stabilization_2110 (551e601) build.

This issue was created as requested in this comment: https://github.com/o3de/o3de/issues/4364#issuecomment-970516207.

**Steps to reproduce**
1. Create a new level.
2. Go to View > Layouts > Restore Default Layout.

**Expected behavior**
The default layout is restored.

**Actual behavior**
The editor silently crashes to the desktop.

**Video, Editor.log, error.log, error.dmp**

https://user-images.githubusercontent.com/86952082/142196607-20825a4e-2faf-4a05-a476-1f8d6aa82cf0.mp4

[Editor.log](https://github.com/o3de/o3de/files/7554442/Editor.log)

[error.log](https://github.com/o3de/o3de/files/7554443/error.log)

[error.zip](https://github.com/o3de/o3de/files/7554449/error.zip)

**Found in Branch**
Development (f245c0a)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by monroegm** [comment]
We should also add a test for this

**Comment by jjjoness** [comment]
After taking the development branch on 12/3 this no longer occurs.

**Comment by LB-ArturSiewniak** [comment]
Issue verified as fixed on Development (9698047) build.

**Comment by LB-PatrykKrajewski** [comment]
Reopening this issue, as it occurs on Development (a8ef23e). It should also be noted that View > Layouts > Component Entity Layout crashes the Editor in the same way - please refer to the attached video. Should this be logged as a separate issue?

https://user-images.githubusercontent.com/88180143/145227611-7829abd4-d8c4-4e03-805b-de9b0ea690e7.mp4

**Comment by jjjoness** [comment]
Hi,

                Can you make a separate issue and let me know the number and I’ll work on them together.

John

**Comment by jjjoness** [comment]
Just posted a fix in https://github.com/o3de/o3de/pull/6386. This fixes both bugs.

**Comment by jjjoness** [comment]
The above PR will fix both the bugs you found.

**Comment by LB-ArturSiewniak** [comment]
Both issues verified as fixed on Stabilization/2111RTE (d7dc257) and Development (8dc5f9b) builds.
