### ISSUE TITLE
Lucy_High.fbx and Lucy_Low.fbx assets have the same model as Hermanubis.fbx

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#5705]
**Describe the bug**
Assets listed below use the same "Hermanubis" model. Lucy asset used to be an angel-like statue in past builds.
o3de\Gems\Atom\Tools\MaterialEditor\Assets\MaterialEditor\ViewportModels\Hermanubis.fbx;
o3de\Gems\AtomLyIntegration\CommonFeatures\Assets\Objects\Lucy\Lucy_High.fbx;
o3de\Gems\AtomLyIntegration\CommonFeatures\Assets\Objects\Lucy\Lucy_low.fbx;

This issue also occurs on Development (f245c0a) build.

**Steps to reproduce**
1. Create a new level.
2. Type "lucy" into the Asset Browser's search bar.

**Expected behavior**
Hermanubis.fbx, Lucy_High.fbx, and Lucy_Low.fbx assets use the same model.

**Actual behavior**
Hermanubis.fbx, Lucy_High.fbx, and Lucy_Low.fbx assets use different models.

**Screenshots**
Hermanubis.fbx:
Thumbnail:
![Hermanubis](https://user-images.githubusercontent.com/86952082/142219244-32308a9a-a645-4bed-a241-894f1d211408.PNG)
Engine:
![HermanubisMesh](https://user-images.githubusercontent.com/86952082/142220309-e692ad62-4967-4520-b22e-794b9b7d4bfa.PNG)

Lucy_High.fbx:
Thumbnail:
![Lucy_High](https://user-images.githubusercontent.com/86952082/142219284-2cfeaf89-023f-408c-980d-e83168eff3c8.PNG)
Engine:
![Lucy_HighMesh](https://user-images.githubusercontent.com/86952082/142220327-77f9720d-9e57-4969-8eee-89890fd6a4b3.PNG)
Lucy_Low.fbx:
Thumbnail:
![Lucy_Low](https://user-images.githubusercontent.com/86952082/142219312-d1d8dacf-f652-4c2f-a8c6-0fbf4dc88959.PNG)
Engine:
![Lucy_LowMesh](https://user-images.githubusercontent.com/86952082/142220376-d4d1dc15-c30a-4d2f-9208-eeca0bd359c6.PNG)

**Found in Branch**
Stabilization_2110 (551e601)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by monroegm** [comment]
Sending over to graphics-audio for triage as we believe they own the assets in question

**Comment by HogJonny-AMZN** [comment]
@LB-ArturZieba There is historical context here.
Lucy is not a open source permissible asset ... and was originally added as a test asset many years ago.
When we moved the code base and assets to public open source we had to remove the asset.
However, the Lucy asset was being used in several automated tests.
The quickest resolve at the time was to leave the files but replace the internals.

@SWMasterson recently updated the files names and tests (please verify in a response)
@wintermute-motherbrain and @thefranke I think this issue can be closed.

**Comment by SWMasterson** [comment]
@HogJonny-AMZN 

Confirmed, all references to Lucy were renamed to Hermanubis. The reason the models are different is because I couldn't simply rename the Lucy.fbx files, but instead had to export the models, causing a new file to be generated - they are otherwise identical.

**Comment by HogJonny-AMZN** [comment]
@superkitcath this can be closed

**Comment by LB-ArturZieba** [comment]
Hi, thanks for the information! On the Development (e19dc40) build I have also verified that there is no "o3de\Gems\AtomLyIntegration\CommonFeatures\Assets\Objects\Lucy\" folder anymore (only the Hermanubis.fbx is left), so the issue can be considered fixed.
