### ISSUE TITLE
Feature Request: Enable monolithic build for the server target

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#5726]
**Is your feature request related to a problem? Please describe.**
Monolithic build is disabled for the server target currently:
https://github.com/o3de/o3de/blob/development/cmake/Monolithic.cmake

This is a risk because of larger builds and adds operational complexity due to DLL corruption, missing dependencies etc. 

**Describe the solution you'd like**
Enable monolithic build for the server target

**Comment by lmbr-pip** [comment]
Issue accepted by sig-network but needs work from sig-build to provide feature.

Users expect have monolithic builds for servers, it avoids DLLS issues (corruption, missing DLLS etc.) and aids relocation/speed improvements.
