### ISSUE TITLE
Linux: Asset Processor fails to process number of _dev_Sedan_r0-b.fbx scene compilation jobs

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#5746]
**Describe the bug**
The following 4 scene compilation jobs fail processing for the .fbx asset:
```
Levels/Physics/Physics_WorldBodyBusWorksOnEditorComponents/PhysXSedan/_dev_Sedan_r0-b.fbx
Levels/Physics/ForceRegion_PxMeshShapedForce/PhysXSedan/_dev_Sedan_r0-b.fbx
Levels/Physics/ForceRegion_ImpulsesPxMeshShapedRigidBody/PhysXSedan/_dev_Sedan_r0-b.fbx
Levels/Physics/RigidBody_COM_ComputingWorks/PhysXSedan/_dev_Sedan_r0-b.fbx
```
Please refer to the attached JobLogs for more information.

**Prerequisites**
- AutomatedTesting is built for Linux using the instructions: https://o3de.org/docs/user-guide/platforms/linux/ 

**Steps to reproduce**
1. Launch the Asset Processor.
2. Wait until all assets are processed.

**Expected behavior**
All assets are processed without failure.

**Actual behavior**
Number of _dev_Sedan_r0-b.fbx scene compilation jobs fail processing.

**Screenshots**
![AP_failed](https://user-images.githubusercontent.com/86953659/142422961-3d6c70f5-a693-4c44-b09d-ab150d614c42.png)

**Found in Branch**
Stabilization/2110 (d222aee)

**Desktop/Device:**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU: AMD Ryzen 5 3600
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 16GB

**Additional context**
[_dev_Sedan_r0-b.fbx-3290225084-13383.log](https://github.com/o3de/o3de/files/7563062/_dev_Sedan_r0-b.fbx-3290225084-13383.log)
[_dev_Sedan_r0-b.fbx-1438749276-13385.log](https://github.com/o3de/o3de/files/7563063/_dev_Sedan_r0-b.fbx-1438749276-13385.log)
[_dev_Sedan_r0-b.fbx-4016690796-13387.log](https://github.com/o3de/o3de/files/7563064/_dev_Sedan_r0-b.fbx-4016690796-13387.log)
[_dev_Sedan_r0-b.fbx-1474979051-13389.log](https://github.com/o3de/o3de/files/7563065/_dev_Sedan_r0-b.fbx-1474979051-13389.log)

**Comment by spham-amzn** [comment]
Closing issue, can no longer reproduce as of commit efc3762
![Screenshot from 2022-09-13 12-28-36](https://user-images.githubusercontent.com/82231385/189992860-cd116532-51ed-4e20-8248-acab789356d0.png)

**Comment by LB-JaroslawGaweda** [comment]
Reopening the ticket as we were able to reproduce the issue on Development (5f71fd1) and Stabilization/2210 (04e3edb) builds.

**Comment by spham-amzn** [comment]
Was the test done on an existing Cache? Did you try to clear the Cache? Attaching log of the above asset (which doesnt show an error)

[_dev_Sedan_r0-b.fbx-1474979051-7588.log](https://github.com/o3de/o3de/files/9568987/_dev_Sedan_r0-b.fbx-1474979051-7588.log)

**Comment by spham-amzn** [comment]
Attached video based on current commit efc3762
https://user-images.githubusercontent.com/82231385/190256148-8d135284-0b93-47dd-a62a-6479a1773615.mp4

**Comment by byrcolin** [comment]
Cannot repro
