### ISSUE TITLE
Texture Settings dialog box crashes in the Editor

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#5766]
**Describe the bug**
When trying to edit Texture Settings for an image asset, the preview in the Texture Settings dialog box either shows garbage, a "Conversion failed" message, or crashes.

**Steps to reproduce**
1. Run the Editor with the AutomatedTesting project enabled
2. Create or open a level
3. Open the Asset Browser
4. Go to Assets/Engine/textures/default_icon.png, right-click, and choose "Edit Texture Settings..."

**Expected behavior**
The texture shows up with a reasonable preview.

**Actual behavior**
It starts with just garbage data that changes every time you choose "Edit Texture Settings...":
![image](https://user-images.githubusercontent.com/82224783/142505750-750571d6-e207-4441-b920-1bff03c4ad7a.png)

Many other choices in the Active preset dropdown, like "Greyscale", give "Conversion failed, please check console for more information."
![image](https://user-images.githubusercontent.com/82224783/142505816-7df59ab2-a19b-458f-8499-b68877bf48ab.png)

If you keep switching between "ReferenceImage_HDRLinear" and "AlbedoWithGenericAlpha" (it can take 0-20 tries) you eventually get a crash with the following callstack:
 	vcruntime140.dll!00007ffa05811470()	Unknown
 	Qt5Gui.dll!00007ff99dbba9dd()	Unknown
>	ImageProcessingAtom.Editor.dll!ImageProcessingAtomEditor::TexturePreviewWidget::GenerateChannelImage(ImageProcessingAtomEditor::PreviewMode channel) Line 301	C++
 	ImageProcessingAtom.Editor.dll!ImageProcessingAtomEditor::TexturePreviewWidget::UpdatePreview() Line 240	C++
 	[External Code]	
 	ImageProcessingAtom.Editor.dll!ImageProcessingAtom::ImageProcessingSystemComponent::OpenSourceTextureFile(const AZ::Uuid & textureSourceID) Line 122	C++
 	[External Code]	
 	EditorLib.dll!AzToolsFramework::AssetBrowser::AssetBrowserTreeView::OnContextMenu(const QPoint & point) Line 399	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 4197	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 38	C++
 	Editor.exe!main(int argc, char * * argv) Line 32	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++

**Found in Branch**
development

**Comment by VickyAtAZ** [comment]
@mbalfour-amzn this issue is fixed in stabilization/2110 branch.
