### ISSUE TITLE
Attempt of deleting root level prefab throws assert

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#5783]
**Describe the bug**
Selecting Delete from a context menu when the level prefab is selected throws the following assert:
```
(System) - Trace::Assert
 C:\o3de\o3de\Code\Framework\AzCore\AzCore/std/optional.h(119): (232) 'class std::reference_wrapper
<class AzToolsFramework::Prefab::Instance> &__cdecl AZStd::Internal::OptionalImplBase<class std::reference_wrapper
<class AzToolsFramework::Prefab::Instance> >::value(void) &'
(System) - Optional does not have a value
```
Additionally, the following message pops up:
```
Delete selected entities error
Cannot delete entities belonging to an instance that is not being edited.
```

When the **Delete** key is used instead, the error message does not appear.

**Steps to reproduce**
1. Open or create a level.
2. Select the level prefab.
3. Press RMB on it and select **Delete**.

**Expected behavior**
A warning message is displayed. No errors occur.

**Actual behavior**
An assert is thrown.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/142608626-843b7205-8c91-4326-9064-729573fdeed5.mp4

**Found in Branch**
Stabilization_2110 (https://github.com/o3de/o3de/commit/d30fdb759d07e54d36309680ffa4247f1481ceb2)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Comment by monroegm** [comment]
@AMZN-daimini Already fixed?

**Comment by AMZN-daimini** [comment]
Tested on latest stabilization, "Delete" is not displayed in the RMB menu.

This fix from last Friday should have fixed this: https://github.com/o3de/o3de/pull/5794

Will close, but feel free to re-open if you still repro :)

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in Stabilization.
