### ISSUE TITLE
Level prefab can be detached which may lead to a crash

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#5785]
**Describe the bug**
"Detach Prefab..." option is available from the context menu of Level prefabs and leads to a crash when it is used.

**Steps to reproduce**
1. Create a new level.
2. Select the level prefab.
3. Press RMB and notice **Detach Prefab...** option being available.
4. Select the **Detach Prefab...** option.

**Expected behavior**
"Detach Prefab..." option is not available from the context menu of the Level prefab.

**Actual behavior**
"Detach Prefab..." option is available and leads to a crash when it is used.

**Video**

https://user-images.githubusercontent.com/86953659/142627712-db4eb817-f059-476c-8e6e-78df8bd6285a.mp4

**Found in Branch**
Stabilization/2110 (d30fdb7)

**Desktop:**
Device: PC
OS: Windows
Version: 10
CPU: Intel i5-9600K
GPU: RTX 2070
Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/7570418/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7570419/error.log)
[dump.zip](https://github.com/o3de/o3de/files/7570420/dump.zip)

**Comment by AMZN-daimini** [comment]
This is a regression introduced by https://github.com/o3de/o3de/pull/5762
I have fixed the oversight and will have a PR for this soon. Thank you for finding this :D

**Comment by jckand-amzn** [comment]
Verified fix on stabilization/2110@3cf3e45b38d6626. Closing out.

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed in Stabilization/2110 (a0ab592).
