### ISSUE TITLE
Animation Editor: Opening Atom Render Window throws asserts

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#5787]
**Describe the bug**
Opening the Atom Render Window in EMotionFX throws 3 asserts:

`C:/Builds/o3de/Code/Framework/AzCore/AzCore/Component/Entity.cpp(194)`
`void __cdecl AZ::Entity::Activate(void)`
`Entity should be in Init state to be Activated!`

`C:/Builds/o3de/Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp(92)`
`float __cdecl AZ::Render::CascadeShadowCameraConfiguration::GetDepthCenter(float,float) const`
`m_depthCenterRatio has not been initialized properly.`

`C:/Builds/o3de/Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp(110)`
`float __cdecl AZ::Render::CascadeShadowCameraConfiguration::GetDepthCenterRatio(void) const`
`m_depthCenterRatio has not been initialized.`

Additionally, two errors about camera configuration are printed in the Editor's console. The asserts are printed in the console as well.

Please refer to the attached screenshots and console log for more information.

**Steps to reproduce**

1. Add "sys_asserts=2" to the game.cfg file of the active project.
2. Open the Animation Editor (Tools -> Animation Editor).
3. Go to View -> Atom Render Window (PREVIEW).

**Expected behavior**
Atom Render Window opens without any errors or asserts.

**Actual behavior**
Opening Atom Render Window throws asserts.

**Screenshots/Video**

![atom_render_window_assert1](https://user-images.githubusercontent.com/86952318/142634383-a66d775b-d691-44b3-bff3-7ad5e6910017.jpg)
![atom_render_window_assert2](https://user-images.githubusercontent.com/86952318/142634390-2ba73aae-b9ca-4bb3-a263-111c679a66f4.jpg)
![atom_render_window_assert3](https://user-images.githubusercontent.com/86952318/142634394-c5859e62-df7e-4fd6-949d-07fb8957911c.jpg)

**Found in Branch**
Development (e804fd2), Stabilization_2110 (d30fdb7)

**Desktop/Device (please complete the following information):**

- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

**Additional context**
If the user does not add "sys_asserts=2" to the game.cfg file of the active project, the asserts will not be thrown. However, a spike in memory usage can be observed. The Editor's memory usage increases to 7 GB and decreases to around 1k after ca. 15 minutes.

[console_output_atom_render_window.txt](https://github.com/o3de/o3de/files/7570673/console_output_atom_render_window.txt)

**Comment by amzn-rhhong** [comment]
@LB-MichalRodzos should be fixed in the latest. Please verify again.

**Comment by LB-MichalRodzos** [comment]
Verified this issue in Development (bfb1d0a) build using repro steps included in the description. Opening Atom Render Window does not throw any assert or cause any memory spike usage.
