### ISSUE TITLE
Installer: Title bars on installer windows still list [Developer Preview]

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#5793]
**Describe the bug**
Title bars on the latest installer windows still list [Developer Preview].

**Steps to reproduce**
1. Download the latest installer build: https://o3debinaries.org/stabilization-2110/Latest/Windows/o3de_installer.exe
2. Open the installer and observe the title bars

**Expected behavior**
Installer lists [Stable 21.11]

**Actual behavior**
Installer lists [Developer Preview]

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82226555/142661251-5528ea9b-5c7e-41a4-b9a1-c1355f03716a.png)

**Found in Branch**
Latest stabilization/2110 installer

**Comment by AMZN-alexpete** [comment]
Could be a cache issue or the installer is using cached files

**Comment by AMZN-Phil** [comment]
This is part fixed - [Developer Preview] should be [Stable] from the next build. I'll keep track of this until I have confirmation that the builds have been set up to pass through the correct version number.

**Comment by AMZN-alexpete** [comment]
The title appears fixed in the latest installer.

**Comment by AMZN-Phil** [comment]
This should be fixed in the latest installer.
