### ISSUE TITLE
Prefab Focus Mode: "Create camera entity from view" and "Instantiate prefab" options creates the new entity/prefab outside of the focused prefab

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#5809]
**Describe the bug**
"Create camera entity from view" and "Instantiate prefab" options creates the new entity/prefab outside of the focused prefab

**Steps to reproduce**
1. Launch the Editor.
2. Open a new or existing level.
3. Create a new prefab or instantiate an existing prefab.
4. Double-click the prefab to enter Focus Mode
5. Right-click in the Viewport and select "Create camera entity from view".

**Expected behavior**
Newly added entity with Camera component is added to the prefab that is focused.

**Actual behavior**
Newly added entity is added to the end of the Entity Outliner list, outside of the prefab in focus.

Additional note to whoever fixes this:
Both options, when called without a target parent, should instantiate or create entities under the current focus root.
Since it's not possible to instantiate or create entities while focusing on a procedural/read-only prefab, those options should simply not appear of be disabled in that case.

**Comment by AMZN-daimini** [comment]
I looked into these and it doesn't look like they're regression, sounds like they were just missed during testing. Luckily another recent fix makes these just a nuisance but they should not cause crashes.

@monroegm Should we list these as known issues? Alternatively, a fix for these looks extremely simple and with a very small blast radius, so if we want to get an exception to fix this I'm up for it too.

**Comment by AMZN-daimini** [comment]
Both options, when called without a target, should instantiate or create entities under the current focus root.
Since it's not possible to instantiate or create entities while focusing on a procedural/read-only prefab, those options should simply not appear of be disabled in that case.

**Comment by LB-TomaszSerwanski** [comment]
Please note that undoing the creation of a camera entity from view while being in a prefab's Focus Mode crashes the Editor in Development (4826048). Should this possibly be reported as a separate issue?

**Comment by monroegm** [comment]
I did not encounter the crash when undoing on on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7.
