### ISSUE TITLE
Asset Browser tab gets corrupted when searching for an asset using the Search field

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#5832]
**Describe the bug**
If the User inputs more than 4 characters when searching for a certain asset, the Asset Browser becomes corrupted.
This makes all the results disappear until the Asset Browser tab is resized or undocked.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Open the Asset Browser tool.
2. Start searching for an asset by typing a part of its name into the _Search..._ field (i.e. type in _hermanubi_).
3. Try to select an asset from the results list.

**Expected behavior**
The results list does not disappear.

**Actual behavior**
The results list disappears.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/142862499-a1d23ce0-154a-4674-ad9c-2d0ee1d9087e.mp4

**Found in Branch**
Stabilization_2110 (a0ab592)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600
 - GPU: Nvidia RTX 2060 SUPER
 - Memory: 16GB

**Comment by monroegm** [comment]
@AMZN-Igarri FYI

**Comment by hultonha** [comment]
Tagging @yuyihsu to check if we would like to try and get this into RTE-Stabilization or if we leave this in development
