### ISSUE TITLE
ViewportEditorModeNotifications::Reflect method seems to not be called

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#5848]
**Describe the bug**
I have a script that deletes file contents in search for unused code. Was surprised to find that `ViewportEditorModeNotifications::Reflect` seems to not be called at all.
To reproduce you can delete the implementaion of the method, if it was called from some place, it would give a linking error.

**Expected behavior**
Call it or remove the method

**Comment by monroegm** [comment]
@hultonha Good first issue?

**Comment by hultonha** [comment]
This could be one for @jonawals to take a look at as I believe he added this code. If someone else is able to pick it up before that's also great (it might be tricky as a first issue to know where best to call it).

**Comment by jonawals** [comment]
Fixed [here](https://github.com/o3de/o3de/pull/5900).

**Comment by amznestebanpapp** [comment]
Awesome that this ended up actually finding a bug!
