### ISSUE TITLE
Linux: Building Projects using the Project Manager fails with the "ninja: build stopped: subcommand failed"

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#5862]
**Describe the bug**
Building Projects via the Project Manager may fail due to ninja: build stopped: subcommand failed. As stated in [#5445](https://github.com/o3de/o3de/issues/5445), this is due to the system running out of memory, however, unlike in the command line, it is not possible to pass building parameters (i.e. DLY_PARALLEL_LINK_JOBS=4) to the Project Manager.

The workaround is to build the same project again after it fails for the first time.

Please refer to the attached log file for more details.

**Steps to reproduce**
1. Build O3DE by following the [Building for Linux guide](https://o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/).
2. Launch Project Manager.
3. Create a new Project.
4. Build the new Project.

**Expected behavior**
The user is able to provide optional build parameters or warned about the possibility of running out of memory and asked to build through the command line with the DLY_PARALLEL_LINK_JOBS set to a lower value.

**Actual behavior**
The Project fails to build due to running out of memory.

**Assets required**
N/A

**Screenshots/Video**
N/A

**Found in Branch**
Stabilization_2110 (ba32937)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version: 20.04.3 LTS
 - CPU: AMD Ryzen 5 3600
 - GPU: Nvidia RTX 2060 SUPER
 - Memory: 16GB

**Attachments**
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/7587215/CMakeProjectBuildError.log)

**Comment by AMZN-nggieber** [comment]
There is a work around you can easily do that should solve this issue on systems with less RAM <~16GB. 

CMAKE variables are already used for the build process and you can open the CMAKE GUI for each project. From there the DLY_PARALLEL_LINK_JOBS variable can be set to 4. It will then be used in a build. A potential issue with this is the cmake gui is a separate package on Debian based Linux, this can be solved with:
`sudo apt install cmake-qt-gui`
From there the Open CMake GUI... option from the project tile dropdown should work on linux and you can set the DLY_PARALLEL_LINK_JOBS variable.

You can also fix this through the command line by changing directories to the project directory and entering:
`cmake -DLY_PARALLEL_LINK_JOBS=4`

If you have any configurations with large amounts of logical cores and little ram this issue could come up. Tuning to another number other than 4 may be required but it seems to work well on systems with 16GB of RAM.
