### ISSUE TITLE
Editor crashes upon adding Diffuse Global Illumination component to the Level Inspector

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#5864]
**Describe the bug**
Adding the Diffuse Global Illumination component to the Level Inspector results in a crash.

Please refer to the attached logs and Visual Studio Call Stack Trace for more information.

**Prerequisites**

- Prefabs are disabled.

**Steps to reproduce**
1. Create a new level.
2. Open Level Inspector.
3. Press **Add Component**.
4. Select **Diffuse Global Illumination** component.

**Expected behavior**
All available components can be added to the Level Inspector and the Editor remains stable.

**Actual behavior**
Editor crashes upon adding the Diffuse Global Illumination component to the Level Inspector.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/143018831-6cc06a1b-f47d-4b79-9ba9-976118bf0a0c.mp4

![VS](https://user-images.githubusercontent.com/86953659/143018849-9dafd5a4-6b5d-45a6-9ebd-34d3f596c894.PNG)

**Found in Branch**
Stabilization/2110 (ba32937)
Development (ebd679d)

**Desktop/Device**
Device: PC
OS: Windows
Version: 10
CPU: Intel i5-9600K
GPU: RTX 2070
Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/7587712/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7587713/error.log)
[error_dmp.zip](https://github.com/o3de/o3de/files/7587792/error_dmp.zip)
[VisualStudioCallStackTrace.txt](https://github.com/o3de/o3de/files/7587827/VisualStudioCallStackTrace.txt)

**Comment by amzn-tommy** [comment]
I have a PR with a fix https://github.com/o3de/o3de/pull/5918

In the meantime if you are trying to use GI, note that global illumination will still function without the DiffuseGlobalIllumination component as long as you use the Diffuse Probe Grid component. You just won't be able to configure the quality level, which is done via the DiffuseGlobalIllumination component.

**Comment by wintermute-motherbrain** [comment]
Given this is with slices and we have deprecated the slices workflow, we will close this issue.  Folks should now be using prefabs.
