### ISSUE TITLE
Using "-DLY_PROJECTS=" argument when creating new Visual Studio project for the engine and a new O3DE project results in configuration failure

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#5870]
**Describe the bug**
The **"-DLY_PROJECTS=_ProjectName_"** argument used during creation of a Visual Studio project for the engine and new O3DE project results in "Configuring incomplete, errors occurred!" - please refer to the attached logs for further details:

[CmakeVSProjectGenFIRST.txt](https://github.com/o3de/o3de/files/7587099/CmakeVSProjectGenFIRST.txt)

Attempting to create an Visual Studio project for the engine without this argument after the above-mentioned error occurs also results in incomplete configuration:

[CmakeVSProjectGenSECOND.txt](https://github.com/o3de/o3de/files/7587122/CmakeVSProjectGenSECOND.txt)

Please note that project specified in the **"-DLY_PROJECTS=_ProjectName_"** argument has been created by following the instructions for **"Creating Projects using CLI"** - [Link](https://o3de.org/docs/welcome-guide/create/creating-projects-using-cli/creating-windows/)

It has been also noticed that using **"-DLY_PROJECTS=AutomatedTesting"** when creating Visual Studio project and building the engine will result in the AutomatedTesting project requiring a rebuild in the **Project Manager**.

**Steps to reproduce**
1. Clone the O3DE repository
2. Open the CLI in the engine source directory.
3. Execute `python\get_python.bat`
4. Register the engine using `scripts\o3de.bat register --this-engine`
5. Create new O3DE project using CLI (skip the "Create a Visual Studio project" and "Build the O3DE project" steps - to generate Visual Studio project for the project in the same time as creating it for the engine by using - **"-DLY_PROJECTS=_ProjectName_** argument - **[Instructions](https://o3de.org/docs/welcome-guide/create/creating-projects-using-cli/creating-windows/)**)
6. Execute `cmake -B build/windows_vs2019 -S . -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\o3de-packages -DLY_PROJECTS=MyProject`

**Expected behavior**
Configuration of the Visual Studio project for a new project is completed successfully.

**Actual behavior**
Configuration of the Visual Studio project is incomplete for the newly created project due to errors.

**Found in Branch**
Stabilization_2110 (ba32937)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by amznestebanpapp** [comment]
@LB-JakubSkorupka where are you running step (6) from? if you are running it from the engine, LY_PROJECTS need to have a relative path to the project. The engine doesnt know how to find the project.
If you are running it from the project, you dont need to pass LY_PROJECTS

I couldn't find "-DLY_PROJECTS=ProjectName" argument in the documentation to update it, it should be "ProjectPath" and a note that the path can be absolute/relative, and if relative, its relative to the engine root folder.

**Comment by LB-JakubSkorupka** [comment]
@amznestebanpapp I ran step (6) from the engine root directory, so the relative path to the project is correct as the AutomatedTesting project folder is present in the engine root folder.
I also was not able to find this argument in the documentation, the "ProjectName" was an assumption based on how this argument was usually used when building.

**Comment by amznestebanpapp** [comment]
> @amznestebanpapp I ran step (6) from the engine root directory, so the relative path to the project is correct as the AutomatedTesting project folder is present in the engine root folder. I also was not able to find this argument in the documentation, the "ProjectName" was an assumption based on how this argument was usually used when building.

Thanks. In the logged issue its passing `-DLY_PROJECTS=MyProject`, so my guess is that is the problem, you can pass a relative path to the engine or an absolute path.
Is this ok to close then?

**Comment by LB-JakubSkorupka** [comment]
@amznestebanpapp thanks for clarifying. After using an absolute path to the project in "-DLY_PROJECTS" argument I did not encounter this issue. Using a relative path still results in configuration errors. AutomatedTesting and any manually created project in CLI by following [documentation](https://o3de.org/docs/welcome-guide/create/creating-projects-using-cli/creating-windows/) still requires a rebuild in the Project Manager after building the engine. Would you like me to create a separate ticket for that issue?

**Comment by amznestebanpapp** [comment]
> @amznestebanpapp thanks for clarifying. After using an absolute path to the project in "-DLY_PROJECTS" argument I did not encounter this issue. Using a relative path still results in configuration errors. AutomatedTesting and any manually created project in CLI by following [documentation](https://o3de.org/docs/welcome-guide/create/creating-projects-using-cli/creating-windows/) still requires a rebuild in the Project Manager after building the engine. Would you like me to create a separate ticket for that issue?

Create one to follow up, however, after building the engine it will require to rebuild of the projects because the binaries in the engine changed. This should be a quick build if you have your "install" engine registered. If you have your source engine registered, each project will build against the engine source code, therefore would build the engine as well (on each project).
