### ISSUE TITLE
Test output in source tree

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#5878]
**Describe the bug**
Found some files that are being stored in the source tree by testing:
```
VALIDATOR_FAILED: GeneratedFilesValidator E:\o3de\o3de\Testing\Temporary\CTestCostData.txt::GeneratedFilesValidator FAILED - Autogenerated CMake file detected by name.
VALIDATOR_FAILED: GeneratedFilesValidator E:\o3de\o3de\Testing\Temporary\LastTest.log::GeneratedFilesValidator FAILED - Execution artifact detected by extension.
```
As noted, this fails validation, it doesnt trigger in Jenkins because the validation job runs in a different volume than the tests. But this would fail in a developer's local machine.
We should not be outputting temporary data into the source tree, this complicates developers, e.g. is not in gitignore. Besides that, is also not being deleted by Jenkins when cleaning output directory. All temporal artifacts that are result of build or test need to go into the build dir.

**Steps to reproduce**
Run tests
Run the validation script: 
```
python\python.cmd scripts\commit_validation\validate_file_or_folder.py --path .
```

**Expected behavior**
- Validations to pass
- Tests to not write in source tree

**Actual behavior**
- Tests are writing into the source tree

**Comment by Kadino** [comment]
Definitely strange that CTest is not placing these files into the output directory. Perhaps this is a quirk of pwd management inside build scripts.

@amznestebanpapp can you clarify the method(s) used to run these tests, in the repro steps?

**Comment by amznestebanpapp** [comment]
@Kadino running the tests from the ci_build script (same as how Jenkins run it), e.g. in Windows:
```
python\python.cmd scripts\build\ci_build.py --platform Windows --type test_cpu_profile
```

**Comment by Kadino** [comment]
Suggests something ci_build.py may be redirecting this. That should be the place to start looking for path/output changes

**Comment by amznestebanpapp** [comment]
'Testing' seems to be coming from `scripts\ctest\result_processing\result_processing.py`, and that is just from the `ctest_driver_test.py` test. That test is registered here: `scripts\ctest\CMakeLists.txt` and is passing the `CMAKE_BINARY_DIR`

There is also `TestResults` in the source dir, that seems to have been done on purpose, its being excluded in gitignore and also in the Jenkinsfile (to upload results). This folder should also be moved to the build dir

**Comment by Kadino** [comment]
Pinging @evanchia-ly-sdets who may have recent context on those files (regardless of who picks up this task)

**Comment by amznestebanpapp** [comment]
Actually, I tried to reproduce again with latest and I am not able to, I also run different ways (e.g. using ctest directly) and both folders are inside the build folder. Closing for now, I will keep an eye on it, if it shows up again will provide better repro
