### ISSUE TITLE
Add support for "unhandled exceptions" in Linux

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#5886]
**Is your feature request related to a problem? Please describe.**
O3DE for Windows intercepts unhandled exceptions through  `AZ::Debug::Platform::HandleExceptions`, but we dont have a similar implementation in Linux. However, there is some code from Cry that does it and its wrapped with `AZ_TRAIT_USE_CRY_SIGNAL_HANDLER`. 

**Describe the solution you'd like**
Add support for signal handlers in Linux behind that  `AZ::Debug::Platform::HandleExceptions` interface. Make it consistent with Windows and remove code within `AZ_TRAIT_USE_CRY_SIGNAL_HANDLER` (and remove the trait)

**Comment by forhalle** [comment]
This was closed with the above commit.
