### ISSUE TITLE
Feature Request: Add end-to-end tests for AWS Gems on Linux

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#5892]
**Is your feature request related to a problem? Please describe.**
AWS gems (AWSCore, AWSClientAuth and AWSMetrics) have end-to-end tests that can verify the gem basic functionalities on Windows, but there're no such automation tests defined for Linux and developers have to test the gems manually on Linux.

**Describe the solution you'd like**
Same automation tests are enabled on Linux to simply the PR verification on Linux.

**Comment by lmbr-pip** [comment]
@junbo75 Believe you are working on this with SIG-Build.

**Comment by junbo75** [comment]
@lmbr-pip Correct. I'm currently working with SIG-Build on setting up the PR verifications.

**Comment by junbo75** [comment]
Linux automation tests have been set up successfully with the following PRs and the help from sig-build:
https://github.com/o3de/o3de/pull/6278
https://github.com/o3de/o3de/pull/6518
@lmbr-pip We should be able to close this issue now.
