### ISSUE TITLE
Quad lights can produce abnormal values when intersecting a surface

### ISSUE THREAD

**Issue by Bindless-Chicken** [o3de/o3de#5912]
**Describe the bug**

Quad lights can produce abnormal values when intersecting with a surface.

**Steps to reproduce**

1. Create a scene with a cube, a quad light, and a bloom post process.
2. Activate the bloom post process.
3. Move the quad light so that it collides with the cube.
4. Move the camera around the intersection point.
5. Observe the black squares.

**Expected behavior**

Light target is clean of any abnormal (`nan`, `INF`) values after the rendering pass when quad lights contacting a surface are present in the scene.

**Actual behavior**

Abnormal values are produced by the quad light into both the light and specular target.  
This behaviour is easily noticeable when used with a bloom postprocess where the `INF` value will get blown into sharp black squares.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/1039134/143293606-a695e9d4-61b4-42a1-ab20-5b3a549c0e7f.png)

**Found in Branch**

`development`

**Desktop/Device (please complete the following information):**

 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel i7-4790K
 - GPU: Nvidia GTX980
 - Memory: 4GB

**Additional context**

This bug is caused by the edge integration functions in `Ltc.azsli` where the inverse square root component will be `rsqrt(0)` under certain circumstances like described above.  
See: [IntegrateEdgeDiffuse#118](https://github.com/o3de/o3de/blob/development/Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ltc.azsli#L118)

That behaviour is prevented in Heitz's [original implementation](https://blog.selfshadow.com/sandbox/ltc.html) through the use of ternary check of theta before the division.

**Comment by Bindless-Chicken** [comment]
I'm currently working on a fix for it.
CC @invertednormal for visibility.

**Comment by invertednormal** [comment]
Nice catch, guess the plan is to add max(x, epsilon) to the rsqrt() functions in IntegrateEdge() and IntegrateEdgeDiffuse()?

**Comment by Bindless-Chicken** [comment]
At the moment I'm rocking a `cosTheta = clamp(cosTheta, -0.9999, 0.9999);` but I'm hoping to find something a little more elegant.

**Comment by invertednormal** [comment]
Honestly looking at this again I'd just saturate the result of the rsqrt. IntegrateEdge() has a saturate on the inside that can be moved outside, so both IntegrateEdge() and IntegrateEdgeDiffuse() could just use `satuarte(rsqrt(1.0 - cosTheta * cosTheta))`. Saturate will convert the NaN into 0 for free, which is a perfectly fine thing to do in this case.
