### ISSUE TITLE
Feature Request: Support for hard client/server split

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#5919]
**Is your feature request related to a problem? Please describe.**
For some games it's not acceptable to ship server code to clients, it creates a massive security risk. O3DE needs to address that concern while also still supporting the client hosted server case.

Ideally O3DE can support the following two modes:
1. One is for console titles, where they're prone to single purchase titles that feature single player campaigns with client hosted multiplayer sessions for long term engagement.. there's no desire for the publisher to foot the bill for server hosting since it's a one and done purchase.
2. The other is for live service games, where they micromonetize various aspects of gameplay and any potential for clients to stand up their own gray servers and bypass the games payment mechanisms risks the games financial success.

**Describe the solution you'd like**
Based on the proposal from @amznestebanpapp and @kberg-amzn, we should:
- Add a new CMake flag (cache variable) called `LY_MULTIPLAYER_SERVER_UNIFIED` which decides the mode to enable for the current gem/project.

- Add the following two compile definitions in gem/project CMake configuration:
    - `GENERATE_CLIENT` Whether the target can behave like a client.
    - `GENERATE_SERVER` Whether the target can behave like a server.

- Emit a _.server_ and _.client_ static target for the multiplayer gem and any dependent gems that contain multiplayer components, including multiplayer sample.

Take the MultiplayerSample project as an example, usage of the new CMake flag and compile definitions in the CMake file is like below:

```
    create target MultiplayerSample.Server.static
        COMPILE_DEFINITIONS
            GENERATE_SERVER=1
        BUILD_DEPENDENCIES
            PRIVATE
                Gem::Multiplayer.Server.Static
    create target MultiplayerSample.Client.static
        COMPILE_DEFINITIONS
            GENERATE_CLIENT=1
            GENERATE_SERVER=${LY_MULTIPLAYER_SERVER_UNIFIED}
        BUILD_DEPENDENCIES
            PRIVATE
                Gem::Multiplayer.Client.Static
```

So the server is always a server and the client can behave as a server if LY_MULTIPLAYER_SERVER_UNIFIED is enabled. The only cost is for unified games they'll be compiling an extra server target that goes unused, but there's actually a benefit to this as well as it will end up actually making their code a bit safer.

**Additional context**
CMake flag `PAL_TRAIT_BUILD_SERVER_SUPPORTED` defines if server is supported or not. Developers can remove the server target using this flag.

**Comment by kberg-amzn** [comment]
I'd recommend a better name for `LY_MULTIPLAYER_SERVER_UNIFIED`, as this is not particularly descriptive and is confusing as to what behaviour might change were this flag toggled. Perhaps 'LY_MULTIPLAYER_ALLOW_CLIENTHOST` or something similar?

**Comment by kberg-amzn** [comment]
Perhaps we should unify this flag with `PAL_TRAIT_BUILD_SERVER_SUPPORTED`? It's much better to have only a single flag if possible.

**Comment by lmbr-pip** [comment]
Discuss with sig-platform, should be an RFC

**Comment by lmbr-pip** [comment]
Issue moved to RFC: https://github.com/o3de/sig-network/issues/32
