### ISSUE TITLE
Linux: Script Canvas softlocks when saving any graph

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#5928]
**Describe the bug**
After saving any graph in the Script Canvas tool it enters a softlock state, and cannot be closed using regular means. The saved .scriptcanvas also cannot be found in the Editor at this point. After killing the Editor process via the System Monitor and reopening it, the Script Canvas tool remains functional and the .scriptcanvas can be used.

**Steps to reproduce**
1. Go to Tools > Script Canvas.
2. Create a new graph.
3. Save the graph under any name.

**Expected behavior**
The Script Canvas tool remains functional.

**Actual behavior**
The Script Canvas tool softlocks.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Video**

https://user-images.githubusercontent.com/86952082/143440277-f40a812c-ee67-42e6-82d8-9ca098816948.mp4

**Found in Branch**
Stabilization_2110 (99d0c39)

**Desktop**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by lumberyard-employee-dm** [comment]
@burelc-amzn I know you were looking at reducing the number of `inotify` handles to make sure the AssetProcessor OnAssetReloaded event is being sent via the AssetNotification messages.

**Comment by burelc-amzn** [comment]
I see fixing #4656 as a workaround to fixing this bug. The Editor should not assume that the Asset Processor is running. You should be able to reproduce this on Windows with:
1. Open the Editor, the AP is launched in the background
2. Open Script Canvas
3. Make a new graph
4. Add a node to the graph
5. Open the AP's window, and exit it with Ctrl+Q
6. Switch back to the Editor window, ignore any prompts about being unable to communicate with AP
7. Save your graph in the Script Canvas window

**Comment by spham-amzn** [comment]
This defect is old and a lot has changed since last reported. As of https://github.com/o3de/o3de/commit/3be72a62466ba2fca643e0d8bd5ee49c4d60d0c0 this cannot be reproduced.

https://user-images.githubusercontent.com/82231385/169920954-2610a663-f481-4ee0-b02e-1eda6bdcd053.mp4
