### ISSUE TITLE
[Polygon light]the Polygon light source has illumination at  height of 0.0, but may not have  illumination at other location of other height

### ISSUE THREAD

**Issue by instoneks2018** [o3de/o3de#5931]
**Describe the bug**
The `Polygon light` source has illumination at  height of 0.0, but may not have  illumination at other location of height.

**Steps to reproduce**
1.Open Editor.
2.Create a new Entity.
3.Add Light Component.
4.Select `Polygon` as Light type for light component.
5. Change the `Height` value in `Polygon Prism Shape`.
6.Move the height of the light source and observe the illumination effect.

**Expected behavior**
The `Polygon light` source illumination is not affected by height position,each height point should be illuminated.

**Screenshots**
```
1. The height position is 0.0,  the objects (cube and rabbit) in the scene have bright illumination.
```
![before2](https://user-images.githubusercontent.com/45937683/143442955-24f21165-eed0-44ed-86a8-50df3333fe4a.png)
]
```
2. Translate the `Polygon light` from right to left，the height position is 10.0,  the object cube and rabbit of the scene are dimmed and the dividing line in both directions is also at height of 0.0.
```
![after2](https://user-images.githubusercontent.com/45937683/143443296-31a75ae8-8e87-4cd9-b860-08790392e4b3.png)

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10

- CPU [Intel I7-10700 2.90GHz (16 CPUs)]
- GPU [Intel(R) UHD Graphics 630]
- Memory [32GB]

**Additional context**

**Comment by invertednormal** [comment]
The polygon light only emits light from the 2d surface of a flat polygon plane. The fact that height is adjustable is just an artifact of using the polygon prism component to define the polygon shape. This is why the height is always set back to 0 whenever you make some change to the light settings. I've created #14472 to help clear up the UX issue.
