### ISSUE TITLE
Undoing deletion of an active Camera entity throws error in the Console

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#5951]
**Describe the bug**
The following error is displayed in the Console after undoing the deletion of an active Camera entity:

`[Error] (EditorViewportWidget) - Internal logic error - active view changed to an entity which is not an editor camera. Please report this as a bug.`

Please refer to the attached video for more details.

**Steps to reproduce**
1. Create a new default Level.
2. Select the Camera entity.
3. Press the _Be this camera_ button on the Component.
4. Delete the Camera entity.
5. Press CTRL+Z or select Edit -> Undo.

**Expected behavior**
No errors are displayed in the Console.

**Actual behavior**
An error is displayed in the Console.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/143568181-66fc2f07-7d75-437a-bd31-245530b4f81f.mp4

**Found in Branch**
Stabilization_2110 (99d0c39)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600
 - GPU: NVIDIA RTX 2060 SUPER
 - Memory: 16GB

**Comment by hultonha** [comment]
Maybe this is something you can look at @AMZN-Igarri?

**Comment by LB-KacperKapusta** [comment]
It has been observed in the Stabilization/2111RTE (ac03b6f) build that the same error:
`[Error] (EditorViewportWidget) - Internal logic error - active view changed to an entity which is not an editor camera. Please report this as a bug.`
is displayed every time the User creates/duplicates/deletes an entity with 'Be This Camera' selected. 
The issue does only occur with the Prefab system enabled. Please let us know if this should be logged as a separate issue.

**Comment by hultonha** [comment]
Thank you for the update @LB-KacperKapusta. After this week the plan is for @AMZN-Igarri to take a look at this and resolve it once and for all (along with some tests). We'll let you know when it's ready to test again, thanks!

**Comment by hultonha** [comment]
@LB-KacperKapusta I believe this issue has been resolved by https://github.com/o3de/o3de/pull/15119.

I am seeing this error printed (see below), but I believe this is a separate problem and should be logged as a new issue for `feature/prefabs`. Thanks!

```bash
[Error] (Prefab) - Failed to find an owning instance for entity with id 15335441214724945613.
```
