### ISSUE TITLE
O3DE engine needs to support vertex animation(current support skeleton animation and morph target animation)

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#5962]
**Is your feature request related to a problem? Please describe.**
Use DCC tool to make a FBX model with vertex animation, After the model is imported into O3DE and then loaded into the scene, the animation cannot be played.

**Describe the solution you'd like**
First, Assimp SDK supports parsing UV data, and then the engine supports driving these UV data.

**Describe alternatives you've considered**

**Additional context**

**Comment by monroegm** [comment]
@sysuNie We could do this for completeness but we don't think this would benefit many users.
