### ISSUE TITLE
O3DE does not provide movement modes such as swimming and flying like UE does

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#5963]
**Is your feature request related to a problem? Please describe.**
There will be scenes of swimming and flying in the animation. Open the level with the river, and you can directly use the related components to achieve it. But currently there are no such things.

**Describe the solution you'd like**
Provide swimming and flying movement modes.

**Describe alternatives you've considered**

**Additional context**

**Comment by monroegm** [comment]
Moving to SIG-Docs-Community as this is related to providing gameplay samples

**Comment by sptramer** [comment]
@monroegm - Does sig-docs-community actually own gameplay samples in this regard? This is part of the terrain/world/"large worlds" work - perhaps not valid yet?

**Comment by monroegm** [comment]
We've come to the consensus that animation system should not provide this built in. We need to figure out where requests for content go and if they should be part of the O3DE repo
