### ISSUE TITLE
[Animation Ragdoll] Realize a ragdoll effect affected by gravity. After the character falls on the ground, walk to a specific position and rotate the angle of view, leaving only the shadow of the character

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#5966]
**Describe the bug**
Realize a ragdoll effect affected by gravity. After the character falls on the ground, walk to a specific position and rotate the angle of view, leaving only the shadow of the character

**Steps to reproduce**
1. Go to 'Realized ragdoll feature level
2. Click on 'Run button'
3. Scroll down to 'Move to the person on the ground, zoom in the lens, make the person on the ground close to the edge of the lens, and rotate the lens left and right'

**Expected behavior**
When the fallen character is in the lens, there will not be only shadows

**Actual behavior**
Rotate the perspective, sometimes only the shadow of the character is left

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Gold 6234]
- GPU [NVidia RTX 5000]
- Memory [e.g. 128GB]

**Additional context**

**Comment by monroegm** [comment]
Hello @sysuNie can you provide a video or a screenshot of the issue?

**Comment by monroegm** [comment]
Closing for now. Feel free to reopen or create a new issue when there is more information.
