### ISSUE TITLE
seedList.seed in Gem/Atom/RPI/Assets needs to be rebuilt

### ISSUE THREAD

**Issue by incisor** [o3de/o3de#5970]
**Describe the bug**
Running `AssetBundlerBatch.exe assetLists --addDefaultSeedListFiles` shows some errors due to missing assets.
I think the issue is using "shader" instead of "shaders".

**Steps to reproduce**
1. Run AssetBundlerBatch.exe with default seeds
2. See error like 
[ERROR] - AssetSeedManager:
Could not find asset with id ({454C374E-E2FA-5DD3-81D8-08BE5904112C}:0) on platform (pc) from Seed List (F:\Work\o3de\Gems\Atom\RPI\Assets\seedList.seed) Asset Hint (shader/decomposemsimage.azshader)

**Expected behavior**
No missing assets or error and create the asset list

**Actual behavior**
Asset list is created but assets in Gem/Atom/RPI are not included

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Comment by AMZN-alexpete** [comment]
Fixed in https://github.com/o3de/o3de/pull/16926 as of 0189233d62703dce6aea6eb20a4012e31698924e
