### ISSUE TITLE
[Animation] When 100 FBX models are loaded in the scenario, the GPU usage of the O3DE Editor process is always 0% in the Task Manager window of the PC. However, the GPU usage of the O3DE Editor process is not 0% when other tools are used.

### ISSUE THREAD

**Issue by nielianpeng** [o3de/o3de#5985]
**Describe the bug**
[Animation] When 100 FBX models are loaded in the scenario, the GPU usage of the O3DE Editor process is always 0% in the Task Manager window of the PC. However, the GPU usage of the O3DE Editor process is not 0% when other tools are used.

**Steps to reproduce**
1. Add 100 characters and actions.

**Expected behavior**
1. The CPU, GPU, memory, and FPS of the O3DE are normal.

**Actual behavior**
1. Choose Task Manager > Processes on the PC. The GPU usage of the Editor process of O3DE is always 0%. However, the GPU usage of the O3DE Editor process is not 0% when other tools are used.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel Xeon Gold 6234]
 - GPU [NVidia RTX 5000]
 - Memory [32GB]
 - Working Branch: Main branch e7f7875

**Additional context**

**Comment by monroegm** [comment]
Hi @nielianpeng, can you please explain why this causes an issue for you? What is the user scenario?

**Comment by monroegm** [comment]
Closing for now. Feel free to reopen or create a new issue when there is more information.
