### ISSUE TITLE
Entity Inspector:  Numerical parameters cannot be set in the input box

### ISSUE THREAD

**Issue by Hsuehnj** [o3de/o3de#5997]
**Describe the bug**
In the Entity Inspector, the numerical parameters of components cannot be set directly, can only be set by clicking the up or down indicator arrows.

**Steps to reproduce**
1. Create an entity
2. Add component Actor, Simple Motion, Attachment
3. For Actor component, select an fbx file locally and set it as an actor asset
4. Set numerical parameters of component Simple Motion, Attachment or Transform

**Expected behavior**
The numerical parameters can be set if enter a value in the input box.

**Actual behavior**
The numerical parameters can not be set if enter a value in the input box, only can be set by clicking the up or down indicator arrows.

**Assets required**
A fbx file, such as ValenaActor.fbx.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/41571619/143874797-78dfbd3c-0c95-42ec-91db-f14afe9aae8c.png)

**Found in Branch**
stabilization/2110

**Desktop/Device (please complete the following information):**
Device: PC,
OS: Windows
Version 10,
CPU Intel xeon
GPU NVidia RTX 5000
Memory 128GB

**Additional context**

**Comment by sphrose** [comment]
This is fixed in the development.
