### ISSUE TITLE
Linux: Script Canvas nodes using Vector3 data pin are not functional and throw an error in the Console when executed

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#5998]
**Describe the bug**
Executing the Script Canvas nodes using Vector3 data pin does not work as expected and results in an error being thrown in the Console:
```
[Error] (Script) - Vector3() accepts only 1 or 3 arguments, not 6!
 ---------- START STACK TRACE ----------
=[C](-1): Vector3
=?(-1): ?
 ---------- END STACK TRACE ----------
```
Please note that the same Script Canvas graphs using the same .inputbindings file are executed without any issues on Windows.

**Steps to reproduce**
1. Launch the Editor.
2. Create an entity.
3. Add Input, Script Canvas, Mesh and PhysX Rigid Body components to the entity.
4. Assign the attached space.inputbindings to the Input component.
5. Assign one of the attached Script Canvas graphs to the Script Canvas component.
6. Enter the Game Mode.
7. Press the 'space' keyboard button.

**Expected behavior**
The nodes using Vector3 data pin are executed without issues.

**Actual behavior**
The nodes using Vector3 data pin are not functional and throw an error in the Console.

**Assets required**
[space-inputbindings.zip](https://github.com/o3de/o3de/files/7618937/space-inputbindings.zip)
[ApplyLinearImpulse-scriptcanvas.zip](https://github.com/o3de/o3de/files/7618938/ApplyLinearImpulse-scriptcanvas.zip)
[MultiplyByVector3-scriptcanvas.zip](https://github.com/o3de/o3de/files/7618939/MultiplyByVector3-scriptcanvas.zip)

**Screenshots/Video**
![apply](https://user-images.githubusercontent.com/86953659/143889980-74084453-ff6d-4460-a82c-c2ee4f21b1a4.png)

https://user-images.githubusercontent.com/86953659/143890249-68090493-70b3-4eb8-898a-6639d2e72072.mp4

Windows for reference:

https://user-images.githubusercontent.com/86953659/143890344-100d4e5a-f1be-4f17-8ce9-7902c4394acd.mp4

**Found in Branch**

Stabilization/2110 (4d36fb9)

**Desktop/Device**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU: AMD Ryzen 5 3600
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 16GB

**Additional context**
Please refer to the attached assets and videos for more information.

**Comment by spham-amzn** [comment]
Cannot reproduce errors displayed in the console. Using the attached binding and script (ApplyLinearImpulse), with the default shader ball (with some modifications), the script does run, and no error appears in the console. Also, when applying MultiplyByVector3 is used, pressing space will show the vector values in the console as expected.

https://user-images.githubusercontent.com/82231385/170787687-61fb4f18-3167-454b-8f44-0cdefaa82b6b.mp4
