### ISSUE TITLE
[Animation] Some bugs about the rotation parameter in the animation editor:

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#6025]
**Describe the bug**
Some bugs about the rotation parameter in the animation editor:

**Steps to reproduce**
Screenshot box 1: I think this input is an Euler angle instead of quaternion, but the engine regards it as a quaternion type
In the screenshot box 2: I think this is a quaternion, but the quaternion is incorrectly converted, and there are still problems with the display. I haven't found the corresponding conversion position yet.
Screenshot box 3: I think it is the Euler angle value displayed. This value theory is consistent with the value set in the Rotation parameter mine, but in fact it is not. 
For Screenshot box 3: I used CreateFromEulerAnglesDegrees instead of MCore::AzQuaternionToEulerAngles to calculate the angles. There seems to be some problems in the calculation of MCore::AzQuaternionToEulerAngles. 

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Found in Branch**
development.

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Gold 6234]
- GPU [NVidia RTX 5000]
- Memory [e.g. 128GB]

**Additional context**

**Comment by monroegm** [comment]
@amzn-jillich Some info is missing for this bug to be worked on by anyone

**Comment by lgleim** [comment]
Revisited in today's SIG Simulation issue triage. With the limited amount of information provided, this report is non-actionable at this time. As such I am closing the report. Feel free to reopen with additional information.
