### ISSUE TITLE
[Linux] ninja: error: unknown target 'INSTALL'

### ISSUE THREAD

**Issue by xsellier** [o3de/o3de#6026]
**Describe the bug**
Cannot build O3DE on Linux binogure 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

**Steps to reproduce**

### Prerequisite
- Open a terminal and type
```sh
sudo apt-get install cmake clang-12 curl libglu1-mesa-dev libxcb-xinerama0 libxcb-xinput0 libxcb-xinput-dev libxcb-xfixes0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libcurl4-openssl-dev libsdl2-dev zlib1g-dev mesa-common-dev ninja-build git git-lfs

pushd /tmp

LIBFFI_PACKAGE_NAME=libffi6_3.2.1-8_amd64.deb
LIBFFI_PACKAGE_URL=http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/

curl --location $LIBFFI_PACKAGE_URL/$LIBFFI_PACKAGE_NAME -o $LIBFFI_PACKAGE_NAME

sudo apt install ./$LIBFFI_PACKAGE_NAME
popd
cmake --version
# cmake version 3.21.3
# 
# CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

### Compilation time
```sh
mkdir -p $HOME/o3de-packages
git clone https://github.com/o3de/o3de.git

cd o3de
python/get_python.sh
cmake -B build/linux -S . -G "Ninja Multi-Config" -DLY_3RDPARTY_PATH=$HOME/o3de-packages -DLY_VERSION_ENGINE_NAME=o3de-install -DCMAKE_INSTALL_PREFIX=$HOME/o3de-install
cmake --build build/linux --target INSTALL --config profile -j 8
# output
# ninja: error: unknown target 'INSTALL'
```

Since the target `INSTALL` doesn't exist, I tried with `install`:
```sh
cmake --build build/linux --target install --config profile -j 8
```

Output is too long, here a pastebin link:
https://pastebin.com/ysunjqB0

**Expected behavior**
> Compilation Done

**Actual behavior**
![image](https://user-images.githubusercontent.com/6616005/144062538-99b546c5-3049-435f-9921-c9b714112c7e.png)

**Found in Branch**
development Commit: 4424b4d51ec71a66be41a74accb743ea3460b4e5

**Desktop/Device (please complete the following information):**
- Linux binogure 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux
- 
![image](https://user-images.githubusercontent.com/6616005/144062723-8134f95a-f5cc-4019-8931-b433004c38bb.png)

**Comment by xsellier** [comment]
Nevermind, had to remove clang 3.8 before compiling.
Documentation works pretty well

**Comment by Lucretia** [comment]
I've got this error too, on Gentoo testing/unstable. I don't understand what you mean about removing "clang 3.8," do you mean cmake? Your clang is 12, mine is 13, but I also have 11 and 12 installed.
