### ISSUE TITLE
Feature Request: Support for servers on macOS (for testing in Editor)

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#6033]
**Is your feature request related to a problem? Please describe.**
If a platform supports the O3DE Editor it should support servers for that platform so I can edit and run multiplayer games. Without local server support I cannot check my work in a multiplayer game in the editor (play in editor mode will be broken).

**Describe the solution you'd like**
* O3DE to support mac servers for local testing work.
& `cmake\Platform\Mac\PAL_mac.cmake` flag `PAL_TRAIT_BUILD_SERVER_SUPPORTED` to be set to true for mac
* Will also require a PAL flag for the AWS GameLift gem as [Amazon Gamelift](https://aws.amazon.com/gamelift/) does not support mac servers, currently the server part of this gem is tied to `PAL_TRAIT_BUILD_SERVER_SUPPORTED`, we do not provide 3P server SDK packages for mac so build will fail otherwise.
* Have periodic AR build for mac servers, if supported by O3DE

**Describe alternatives you've considered**
* None

**Additional context**
Have tested and confirmed mac servers work with minor modifications, need build guidance on new flag to guard Gamelift server definition. Screen shot of game + server running on macOS.
<img width="1440" alt="Screen Shot 2021-11-29 at 5 14 04 PM" src="https://user-images.githubusercontent.com/61438964/144089078-cab26942-376b-4441-93d5-e076ba31f8f1.png">
* Will require use of multiplayer enabled project such as MultiplayerSample for testing.
* Local server must be run with null renderer on underpowered macs otherwise will crash due to GPU loads: `open -n ./build/mac/bin/profile/MultiplayerSample.ServerLauncher.app --args --console-command-file=server.cfg --rhi=null`

**Comment by lmbr-pip** [comment]
sig/build: looking for any concerns, suggestions around cmake
sig/platform: would be looking for concerns, approval to add mac servers as an o3de supported platform
sig/network: would be looking for concerns, approval to support mac servers (or provide them with some kind of status).

**Comment by amznestebanpapp** [comment]
Moving back to triage so someone else takes it

**Comment by lmbr-pip** [comment]
Will bring to TSC to make decision and then assign out issues to SIGs.

**Comment by lmbr-pip** [comment]
Finally remembered to ask for TSC input. Expect to have update post 4/19 TSC meeting

**Comment by lmbr-pip** [comment]
TSC feedback is this should be supported (for editor support).
