### ISSUE TITLE
[SliceDeprecation] Convert Network related automated tests to use prefab system

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#6039]
Convert all level and slice files used in the following automated tests into prefab format:

- test_anonymous_credentials
- test_password_signin_credentials
- TestAWSCoreAWSResourceInteraction
- test_realtime_and_batch_analytics
- test_unauthorized_user_request_rejected

Test Conversion Procedure Suggested: 

- Search the target test script to see which "*.slice" files are used in the test, and use the converter tool to convert those files to "*.prefab" files. Remember to also change the script to use the converted prefab files instead.
- Open the test level used by target test script, list slice assets used by slice instances in the test level, and convert them into prefab ones with the converter tool.
- Convert the test level file("*.ly") into prefab file format by using the converter tool.
- Replace words related to slice terminology to prefab one.
- Run the converted test locally to see if the target test passed or not.
- If tests failed/can't run, make any changes needed.

**Comment by junbo75** [comment]
This issue should have been resolved with https://github.com/o3de/o3de/pull/6278.
