### ISSUE TITLE
[SliceDeprecation] Convert Graphics related automated tests to use prefab system

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#6040]
Convert all level and slice files used in the following automated tests into prefab format:

- AtomEditorComponents_Decal_AddedToEntity
- AtomEditorComponents_DepthOfField_AddedToEntity
- AtomEditorComponents_DirectionalLight_AddedToEntity
- AtomEditorComponents_DisplayMapper_AddedToEntity
- AtomEditorComponents_ExposureControl_AddedToEntity
- AtomEditorComponents_GlobalSkylightIBL_AddedToEntity
- AtomEditorComponents_Light_AddedToEntity
- AtomEditorComponents_PhysicalSky_AddedToEntity
- AtomEditorComponents_PostFXRadiusWeightModifier_AddedToEntity
- hydra_GPUTest_AtomFeatureIntegrationBenchmark.py
- TestAtomEditorComponentsMain

Test Conversion Procedure Suggested: 

- Search the target test script to see which "*.slice" files are used in the test, and use the converter tool to convert those files to "*.prefab" files. Remember to also change the script to use the converted prefab files instead.
- Open the test level used by target test script, list slice assets used by slice instances in the test level, and convert them into prefab ones with the converter tool.
- Convert the test level file("*.ly") into prefab file format by using the converter tool.
- Replace words related to slice terminology to prefab one.
- Run the converted test locally to see if the target test passed or not.
- If tests failed/can't run, make any changes needed.

**Comment by chiyenteng** [comment]
**enable_prefab_system = False** still not removed for the following tests:

- test_MaterialEditorBasicTests
- test_AtomFeatureIntegrationBenchmark
- test_MaterialEditorLaunch_AllRHIOptionsSucceed
- AtomEditorComponents_DisplayMapperAdded
- AtomGPU_BasicLevelSetup_SetsUpLevel
- AtomGPU_LightComponent_AreaLightScreenshotsMatchGoldenImages
- AtomGPU_LightComponent_SpotLightScreenshotsMatchGoldenImages

**Comment by smurly** [comment]
tests which use launch_and_validate_result will need to update EditorPythonTestTools/editor_python_test_tools/hydra_test_utils.py since these currently fail attempting to set prefab system True because workspace is undefined when calling workspace.paths.engine_root()
MaterialEditor doesn't load levels so probably doesn't care about prefab/slice but it uses the launch_and_validate_result helper.

**Comment by superkitcath** [comment]
@jromnoa ATOM-17295 for internal tracking

**Comment by jromnoa** [comment]
Fixed in https://github.com/o3de/o3de/pull/8004

**Comment by chiyenteng** [comment]
#8124 for converting test_AtomFeatureIntegrationBenchmarkTest_UploadMetrics.
