### ISSUE TITLE
[SliceDeprecation] Convert Script/Physics related automated tests to use prefab system

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#6041]
Convert all level and slice files used in the following automated tests into prefab format:

- ~~ScriptCanvas_CollisionEvents~~
- ~~ScriptCanvas_GetCollisionNameReturnsName~~
- ~~ScriptCanvas_GetCollisionNameReturnsNothingWhenHasToggledLayer~~
- ~~ScriptCanvas_MultipleRaycastNode~~
- ~~ScriptCanvas_OverlapNode~~
- ~~ScriptCanvas_PostPhysicsUpdate~~
- ScriptCanvas_PostUpdateEvent
- ScriptCanvas_PreUpdateEvent
- ~~ScriptCanvas_SetKinematicTargetTransform~~
- ScriptCanvas_ShapeCast
- ~~ScriptCanvas_TriggerEvents~~

Test Conversion Procedure Suggested: 

- Search the target test script to see which "*.slice" files are used in the test, and use the converter tool to convert those files to "*.prefab" files. Remember to also change the script to use the converted prefab files instead.
- Open the test level used by target test script, list slice assets used by slice instances in the test level, and convert them into prefab ones with the converter tool.
- Convert the test level file("*.ly") into prefab file format by using the converter tool.
- Replace words related to slice terminology to prefab one.
- Run the converted test locally to see if the target test passed or not.
- If tests failed/can't run, make any changes needed.

**Comment by hultonha** [comment]
Tagging @FuzzyCarterAWS for visibility

**Comment by FuzzyCarterAWS** [comment]
Added to my taskwork.

**Comment by FuzzyCarterAWS** [comment]
@chiyenteng will be tackling the tests ONLY in the Periodic test suite.

I will be tackling all other tests NOT in the Periodic test suite

**Comment by chiyenteng** [comment]
This test is broken after conversion, so leave it unconverted for now:
- ScriptCanvas_PostUpdateEvent

**Comment by chiyenteng** [comment]
PR #7886 helped convert the following tests:
- ScriptCanvas_SetKinematicTargetTransform
- ScriptCanvas_OverlapNode

**Comment by chiyenteng** [comment]
PR #7974 helped convert the following tests:

- ScriptCanvas_GetCollisionNameReturnsName
- ScriptCanvas_GetCollisionNameReturnsNothingWhenHasToggledLayer

**Comment by chiyenteng** [comment]
PR #7869 helped convert the following tests:
- ScriptCanvas_PostPhysicsUpdate
- ScriptCanvas_TriggerEvents
