### ISSUE TITLE
[SliceDeprecation] Convert Terrain/Physics related automated tests to use prefab system 

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#6042]
Convert all level and slice files used in the following automated tests into prefab format:
(From Physics test folder)
- ~~Terrain_AddPhysTerrainComponent~~
- ~~Terrain_CanAddMultipleTerrainComponents~~
- ~~Terrain_CollisionAgainstRigidBody~~
- ~~Terrain_MultipleResolutionsValid~~
- ~~Terrain_MultipleTerrainComponentsWarning~~
- **Terrain_NoPhysTerrainComponentNoCollision**
- ~~Terrain_TerrainTexturePainterWorks~~

~~==========(New test added)===========~~
- ~~test_AxisAlignedBoxShape_ConfigurationWorks~~
- ~~test_Terrain_SupportsPhysics~~
- ~~test_TerrainHeightGradientList_AddRemoveGradientWorks~~
- ~~test_TerrainSystem_VegetationSpawnsOnTerrainSurfaces~~
- ~~test_TerrainMacroMaterialComponent_MacroMaterialActivates~~
- ~~test_TerrainWorld_ConfigurationWorks~~

Test Conversion Procedure Suggested: 

- Search the target test script to see which "*.slice" files are used in the test, and use the converter tool to convert those files to "*.prefab" files. Remember to also change the script to use the converted prefab files instead.
- Open the test level used by target test script, list slice assets used by slice instances in the test level, and convert them into prefab ones with the converter tool.
- Convert the test level file("*.ly") into prefab file format by using the converter tool.
- Replace words related to slice terminology to prefab one.
- Run the converted test locally to see if the target test passed or not.
- If tests failed/can't run, make any changes needed.

**Comment by chiyenteng** [comment]
@jckand-amzn will help converting the following newly added tests:

- test_AxisAlignedBoxShape_ConfigurationWorks
- test_Terrain_SupportsPhysics
- test_TerrainHeightGradientList_AddRemoveGradientWorks
- test_TerrainSystem_VegetationSpawnsOnTerrainSurfaces
- test_TerrainMacroMaterialComponent_MacroMaterialActivates
- test_TerrainWorld_ConfigurationWorks

**Comment by chiyenteng** [comment]
> @jckand-amzn will help converting the following newly added tests:
> 
> * test_AxisAlignedBoxShape_ConfigurationWorks
> * test_Terrain_SupportsPhysics
> * test_TerrainHeightGradientList_AddRemoveGradientWorks
> * test_TerrainSystem_VegetationSpawnsOnTerrainSurfaces
> * test_TerrainMacroMaterialComponent_MacroMaterialActivates
> * test_TerrainWorld_ConfigurationWorks

Done. See #7360.

**Comment by jckand-amzn** [comment]
Completed in 7360.

**Comment by chiyenteng** [comment]
The following tests need to be converted(Physics related):
- Terrain_AddPhysTerrainComponent
- Terrain_CanAddMultipleTerrainComponents
- Terrain_CollisionAgainstRigidBody
- Terrain_MultipleResolutionsValid
- Terrain_MultipleTerrainComponentsWarning
- Terrain_NoPhysTerrainComponentNoCollision
- Terrain_TerrainTexturePainterWorks

**Comment by hultonha** [comment]
Tagging @FuzzyCarterAWS for visibility

**Comment by FuzzyCarterAWS** [comment]
Added to my taskwork.

**Comment by FuzzyCarterAWS** [comment]
@chiyenteng will be tackling the tests ONLY in the Periodic test suite.

I will be tackling all other tests NOT in the Periodic test suite

**Comment by chiyenteng** [comment]
PR #7886 helped convert the following tests:
- Terrain_TerrainTexturePainterWorks
- Terrain_CollisionAgainstRigidBody
- Terrain_AddPhysTerrainComponent
- Terrain_CanAddMultipleTerrainComponents
- Terrain_MultipleTerrainComponentsWarning
- Terrain_MultipleResolutionsValid

Unconverted test:
- Terrain_NoPhysTerrainComponentNoCollision

**Comment by chiyenteng** [comment]
Test Terrain_NoPhysTerrainComponentNoCollision has been converted with PR #7869.
All tests listed in this GHI have been converted. 
Closing this issue.
