### ISSUE TITLE
[SliceDeprecation] Convert Core/Physics related automated tests to use prefab system

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#6043]
Convert all level and slice files used in the following automated tests into prefab format:

- ~~TestPythonAssetProcessing~~
- ~~BaseDamageTest.py~~
- ~~Blast_ActorSplitsAfterCollision~~
- ~~NvCloth_AddClothSimulationToActor~~
- ~~NvCloth_AddClothSimulationToMesh~~
- ~~CharacterController_SwitchLevels~~
- ~~Collider_AddColliderComponent~~
- ~~Collider_AddingNewGroupWorks~~
- ~~Collider_CheckDefaultShapeSettingIsPxMesh~~
- Collider_ColliderPositionOffset
- Collider_ColliderRotationOffset
- ~~Collider_CollisionGroupsWorkflow~~
- Collider_DiffCollisionGroupDiffCollidingLayersNotCollide
- ~~Collider_MultipleSurfaceSlots~~
- ~~Collider_NoneCollisionGroupSameLayerNotCollide~~
- ~~Collider_PxMeshAutoAssignedWhenAddingRenderMeshComponent~~
- ~~Collider_PxMeshConvexMeshCollides~~
- ~~Collider_PxMeshErrorIfNoMesh~~
- ~~Collider_PxMeshNotAutoAssignedWhenNoPhysicsFbx~~
- Collider_SameCollisionGroupDiffLayersCollide
- ~~Collider_SameCollisionGroupSameCustomLayerCollide~~
- ~~Collider_SameCollisionGroupSameLayerCollide~~
- Collider_TriggerPassThrough
- ForceRegion_CapsuleShapedForce
- ForceRegion_DirectionHasNoAffectOnTotalForce
- ~~ForceRegion_HighValuesDirectionAxesWorkWithNoError~~
- ~~ForceRegion_ImpulsesBoxShapedRigidBody~~
- ForceRegion_ImpulsesCapsuleShapedRigidBody
- ForceRegion_ImpulsesPxMeshShapedRigidBody
- ForceRegion_LinearDampingForceOnRigidBodies
- ForceRegion_LocalSpaceForceOnRigidBodies
- ForceRegion_MovingForceRegionChangesNetForce
- ForceRegion_MultipleComponentsCombineForces
- ForceRegion_MultipleForcesInSameComponentCombineForces
- ForceRegion_NoQuiverOnHighLinearDampingForce
- ForceRegion_ParentChildForcesCombineForces
- ForceRegion_PointForceOnRigidBodies
- ForceRegion_PositionOffset
- ForceRegion_PxMeshShapedForce
- ForceRegion_RotationalOffset
- ForceRegion_SimpleDragForceOnRigidBodies
- ~~ForceRegion_SmallMagnitudeDeviationOnLargeForces~~
- ForceRegion_SphereShapedForce
- ForceRegion_SplineForceOnRigidBodies
- ForceRegion_SplineRegionWithModifiedTransform
- ~~ForceRegion_WithNonTriggerColliderWarning~~
- ForceRegion_WorldSpaceForceOnRigidBodies
- ForceRegion_ZeroLinearDampingDoesNothing
- ForceRegion_ZeroLocalSpaceForceDoesNothing
- ForceRegion_ZeroPointForceDoesNothing
- ForceRegion_ZeroSimpleDragForceDoesNothing
- ForceRegion_ZeroSplineForceDoesNothing
- ForceRegion_ZeroWorldSpaceForceDoesNothing
- ~~Joints_Ball2BodiesConstrained~~
- ~~Joints_BallBreakable~~
- Joints_BallLeadFollowerCollide
- ~~Joints_BallNoLimitsConstrained~~
- Joints_BallSoftLimitsConstrained
- ~~Joints_Fixed2BodiesConstrained~~
- ~~Joints_FixedBreakable~~
- Joints_FixedLeadFollowerCollide
- ~~Joints_GlobalFrameConstrained~~
- ~~Joints_Hinge2BodiesConstrained~~
- ~~Joints_HingeBreakable~~
- Joints_HingeLeadFollowerCollide
- ~~Joints_HingeNoLimitsConstrained~~
- Joints_HingeSoftLimitsConstrained
- ~~Material_CanBeAssignedToTerrain~~
- ~~Material_CharacterController~~
- ~~Material_ComponentsInSyncWithLibrary~~
- ~~Material_DefaultLibraryConsistentOnAllFeatures~~
- ~~Material_DefaultLibraryUpdatedAcrossLevels_after~~
- ~~Material_DefaultLibraryUpdatedAcrossLevels_before~~
- ~~Material_DefaultMaterialLibraryChangesWork~~
- Material_DynamicFriction
- Material_EmptyLibraryUsesDefault
- ~~Material_FrictionCombine~~
- ~~Material_FrictionCombinePriorityOrder~~
- ~~Material_LibraryChangesReflectInstantly~~
- ~~Material_LibraryClearingAssignsDefault~~
- ~~Material_LibraryCrudOperationsReflectOnCharacterController~~
- ~~Material_LibraryCrudOperationsReflectOnCollider~~
- ~~Material_LibraryCrudOperationsReflectOnRagdollBones~~
- ~~Material_LibraryCrudOperationsReflectOnTerrain~~
- ~~Material_LibraryUpdatedAcrossLevels~~
- Material_NoEffectIfNoColliderShape
- ~~Material_PerFaceMaterialGetsCorrectMaterial~~
- ~~Material_RagdollBones~~
- ~~Material_Restitution~~
- ~~Material_RestitutionCombine~~
- ~~Material_RestitutionCombinePriorityOrder~~
- ~~Material_StaticFriction~~
- ~~Physics_UndoRedoWorksOnEntityWithPhysComponents~~
- Physics_VerifyColliderRigidBodyMeshAndTerrainWorkTogether
- ~~Physics_WorldBodyBusWorksOnEditorComponents~~
- ~~Ragdoll_AddPhysxRagdollComponentWorks~~
- Ragdoll_LevelSwitchDoesNotCrash
- ~~Ragdoll_OldRagdollSerializationNoErrors~~
- Ragdoll_WorldBodyBusWorks
- RigidBody_AddRigidBodyComponent
- RigidBody_AngularDampingAffectsRotation
- RigidBody_ComputeInertiaWorks
- RigidBody_COM_ComputingWorks
- RigidBody_COM_ManualSettingWorks
- RigidBody_COM_NotIncludesTriggerShapes
- RigidBody_EnablingGravityWorksPoC
- RigidBody_EnablingGravityWorksUsingNotificationsPoC
- RigidBody_InitialAngularVelocity
- RigidBody_InitialLinearVelocity
- RigidBody_KinematicModeWorks
- ~~RigidBody_LinearDampingAffectsMotion~~
- RigidBody_MassDifferentValuesWorks
- RigidBody_MaxAngularVelocityWorks
- RigidBody_MomentOfInertiaManualSetting
- RigidBody_SetGravityWorks
- RigidBody_SleepWhenBelowKineticThreshold
- RigidBody_StartAsleepWorks
- RigidBody_StartGravityEnabledWorks
- ~~UtilTest_Physmaterial_Editor.py~~
- ~~ShapeCollider_CanBeAddedWitNoWarnings~~
- ShapeCollider_CylinderShapeCollides
- ~~ShapeCollider_InactiveWhenNoShapeComponent~~
- ~~ShapeCollider_LargeNumberOfShapeCollidersWontCrashEditor~~

Test Conversion Procedure Suggested: 

- Search the target test script to see which "*.slice" files are used in the test, and use the converter tool to convert those files to "*.prefab" files. Remember to also change the script to use the converted prefab files instead.
- Open the test level used by target test script, list slice assets used by slice instances in the test level, and convert them into prefab ones with the converter tool.
- Convert the test level file("*.ly") into prefab file format by using the converter tool.
- Replace words related to slice terminology to prefab one.
- Run the converted test locally to see if the target test passed or not.
- If tests failed/can't run, make any changes needed.

**Comment by lsemp3d** [comment]
Removing animation and setting back to needs-triage for physics visibility

**Comment by chiyenteng** [comment]
**enable_prefab_system = False** still not removed for the following tests:
In AutomatedTesting\Gem\PythonTests\Blast\TestSuite_Main.py: 

- Blast_ActorSplitsAfterCollision
- Blast_ActorSplitsAfterRadialDamage
- Blast_ActorSplitsAfterCapsuleDamage
- Blast_ActorSplitsAfterImpactSpreadDamage
- Blast_ActorSplitsAfterShearDamage
- Blast_ActorSplitsAfterTriangleDamage
- Blast_ActorSplitsAfterStressDamage

Note: Make sure to use prefab system(DON'T use enable_prefab_system = False) while adding new automated tests.

**Comment by chiyenteng** [comment]
Tests might failed after conversion(like **Collider_AddColliderComponent**): https://github.com/o3de/o3de/issues/7431 .

**Comment by chiyenteng** [comment]
Following test will be converted with PR #7416:

- BaseDamageTest.py
- Blast_ActorSplitsAfterCollision
- Blast_ActorSplitsAfterRadialDamage
- Blast_ActorSplitsAfterCapsuleDamage
- Blast_ActorSplitsAfterImpactSpreadDamage
- Blast_ActorSplitsAfterShearDamage
- Blast_ActorSplitsAfterTriangleDamage
- Blast_ActorSplitsAfterStressDamage
- CharacterController_SwitchLevels
- Ragdoll_AddPhysxRagdollComponentWorks
- Collider_PxMeshConvexMeshCollides
- ShapeCollider_InactiveWhenNoShapeComponent
- Collider_CheckDefaultShapeSettingIsPxMesh
- ShapeCollider_LargeNumberOfShapeCollidersWontCrashEditor
- ForceRegion_WithNonTriggerColliderWarning
- Material_LibraryClearingAssignsDefault
- Collider_PxMeshAutoAssignedWhenModifyingRenderMeshComponent
- Collider_PxMeshAutoAssignedWhenAddingRenderMeshComponent
- Collider_MultipleSurfaceSlots
- Collider_PxMeshNotAutoAssignedWhenNoPhysicsFbx
- ShapeCollider_CanBeAddedWitNoWarnings

**Comment by chiyenteng** [comment]
Test converted with PR #7499:

- Collider_AddColliderComponent

**Comment by chiyenteng** [comment]
Note: We should probably convert tests with the following order:

1. Tests in **TestSuite_Main** test suite.
2. Tests in **TestSuite_Periodic** test suite.
3. Tests in TestSuite_Sandbox / TestSuite_Utils / TestSuite_InDevelopment test suites.

For each test converted, we should also convert its duplicate in **TestSuite_Main_Optimized** test suite.

**Comment by hultonha** [comment]
Tagging @FuzzyCarterAWS for visibility

**Comment by FuzzyCarterAWS** [comment]
Added to my taskwork.

**Comment by FuzzyCarterAWS** [comment]
@chiyenteng will be tackling the tests **ONLY** in the **Periodic** test suite.

I will be tackling all other tests **NOT** in the **Periodic** test suite

**Comment by chiyenteng** [comment]
PR #7886 helped convert the following tests:
- Material_RagdollBones
- Material_CanBeAssignedToTerrain
- Material_DefaultLibraryConsistentOnAllFeatures
- Ragdoll_OldRagdollSerializationNoErrors
- Material_StaticFriction
- RigidBody_LinearDampingAffectsMotion
- Physics_WorldBodyBusWorksOnEditorComponents
- Material_LibraryCrudOperationsReflectOnRagdollBones
- Material_ComponentsInSyncWithLibrary
- Material_LibraryCrudOperationsReflectOnTerrain
- Material_DefaultMaterialLibraryChangesWork
- Material_LibraryCrudOperationsReflectOnCollider
- Material_LibraryCrudOperationsReflectOnCharacterController
- Material_LibraryChangesReflectInstantly
- Material_LibraryUpdatedAcrossLevels
- ForceRegion_HighValuesDirectionAxesWorkWithNoError
- Collider_SameCollisionGroupSameLayerCollide
- Collider_PxMeshErrorIfNoMesh
- ForceRegion_ImpulsesBoxShapedRigidBody
- ForceRegion_SmallMagnitudeDeviationOnLargeForces

Also removed ShapeCollider_CylinderShapeCollides since it is already in Main/Main_Optimized test suite.

**Comment by chiyenteng** [comment]
PR #7974 helped convert the following tests:
- test_physmaterial_editor

Also removed two tests having no test modules:
- UtilTest_Tracer_PicksErrorsAndWarnings
- UtilTest_Managed_Files

**Comment by chiyenteng** [comment]
#8049 helped convert these tests:

- Material_DefaultLibraryUpdatedAcrossLevels_after
- Material_DefaultLibraryUpdatedAcrossLevels_before

**Comment by chiyenteng** [comment]
#8146 helped convert the test Physics_UndoRedoWorksOnEntityWithPhysComponents.

**Comment by chiyenteng** [comment]
#7869 helped convert the rest of the tests.

**Comment by hultonha** [comment]
This is awesome to see, fantastic work @chiyenteng!

**Comment by chiyenteng** [comment]
PR to fix/convert tests from TestSuite_Utils: #8496
