### ISSUE TITLE
[GNU/LINUX] Script canvas moving vector3 still curves

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#6111]
**Describe the bug**
Script canvas moving vector3 (X working, Y vice versa Z top, Z does not work at all)

![image](https://user-images.githubusercontent.com/17591539/144517098-585ca97c-c07d-46c4-ac61-b5461825c666.png)

tutorials -> https://youtu.be/4zwZcVQskGg?list=PLCQwFpnHSZQhhsr6iJqyeYqKe6dexnHh9&t=528

**Steps to reproduce**
Open Editor
Сreate file Script Canvas 
Added `On Entity Activated` -> `InputHandler` -> `Create From Values` -> `Move Entity`
Object movement vector3  `X` correct, `Y `-> `Z`, `Z` nothing works

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/144516820-bd573032-f543-44d2-a220-dc8bdcea323e.mp4

**Found in Branch**
21.11.1 stable 6480041944b0fb022d90c9f014be3b48cdc1ef24

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 20.04.03 LTS
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 21.0.3]
 - Memory: 16GB

**Comment by monroegm** [comment]
We need clearer repro steps to be able to triage the bug. @lsemp3d offered to help investigate.

**Comment by pollend** [comment]
when you delete connections they don't seem to get actually removed.

![image](https://user-images.githubusercontent.com/854359/145726032-a040d5e7-cc8c-4712-a973-d29720f016aa.png)

**Comment by pollend** [comment]
some times you have phantom connections you can delete the connections but if you reload the script canvas the connections will show up. there seems to be a breakdown when you delete a connection.

**Comment by Altair1024** [comment]
axis bug related canvas script not clear reason, download --> [mini project](https://drive.google.com/file/d/1tgN_9KlXCTJ4EMbRZ6M0OSerQ4GGVkIW) (Ubuntu 20.04 LTS)

**Comment by pollend** [comment]
so there are two Graphs being maintained. Graph.h and SceneComponent.h

the data between the two can get out of sync?

**Comment by Darkinggq** [comment]
I'm checking today development de005a0632638c2aa01de773b6ab8ef29feda0ea works well vector 3 looks like it's already been fixed on Linux Manjaro (topic can be closed)
