### ISSUE TITLE
Polygon light type height value is reverted to 0 after leaving Game Mode

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#6127]
**Describe the bug**
Polygon Prism Shape in an entity with a Light component has it's height value reset after leaving the Game Mode. This issue only occurs if a Polygon Prism Shape component is used in conjunction with a Light component.

**Steps to reproduce**
1. Create an entity.
2. Add a Light component to it.
3. Select Polygon as the light type.
4. Change the height value.
5. Enter and leave the Game Mode.

**Expected behavior**
The height value does not change.

**Actual behavior**
The height value is reverted to 0.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/144581439-9bc4ce4c-bea3-4149-ad65-e42ccc4d06da.mp4

**Found in Branch**
Development ([cfb426b](https://github.com/o3de/o3de/commit/cfb426b86c34be6474095433c10844610fcbd070))
The issue occurs in O3DE Stable 21.11 Release.

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Comment by monroegm** [comment]
Sending to Graphics-Audio, the owners of the component

**Comment by invertednormal** [comment]
The polygon light only emits light from the 2d surface of a flat polygon plane. The fact that height is adjustable is just an artifact of using the polygon prism component to define the polygon shape. This is why the height is always set back to 0 whenever you make some change to the light settings, or enter/exit game mode. I've created https://github.com/o3de/o3de/issues/14472 to help clear up the UX issue.

**Comment by LB-BartoszDudzinski** [comment]
Confirming the issue has been closed and will be tracked in [#14472](https://github.com/o3de/o3de/issues/14472).
