### ISSUE TITLE
Asset Browser Collapse All

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#6141]
**Is your feature request related to a problem? Please describe.**
Asset Browser can have a large tree of assets with folders that are all expanded by default. This makes it difficult to browse.

**Describe the solution you'd like**
Add a collapse all feature. I think there should be a toolbar button to collapse all, as well as a context menu item for collapsing a specific subtree.

**Comment by rainbj** [comment]
toggle switch to support tree view vs list view. We also need to look at all these item holistically. @amzn-leenguy  for follow up.

**Comment by santorac** [comment]
Sorry, I didn't mean tree view vs list view. When you open asset browser it's in tree view which is good, but all folders are open. If I want to browse I have to scroll _way_ down. There should be a way to collapse all folders in a single step. Like this in Visual Studio...
![image](https://user-images.githubusercontent.com/55155825/145498711-4e2bc67e-bcc5-4224-9be0-c3b61cd14659.png)

**Comment by amzn-leenguy** [comment]
Thanks for the clarification. I have a meeting about this on Monday to talk to the contributor that has previously worked on this. I will report back if we can agree on a time he can investigate this for us.

**Comment by amzn-leenguy** [comment]
The meeting has been moved to the 20th of December. I will report back after that date on the status update.

**Comment by amzn-leenguy** [comment]
Update: Our developer has made the update to this (coded the request). We will wait until the new year until it gets pushed up into main. Thanks

**Comment by amzn-leenguy** [comment]
Assigning to @AMZN-Igarri when he has pushed the update.
