### ISSUE TITLE
AssetBrowserTest.CheckCorrectNumberOfEntriesInTableView cannot be run in debug

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#6148]
**Describe the bug**
`AssetBrowserTest.CheckCorrectNumberOfEntriesInTableView` causes an assert within Qt that causes a C++ runtime dialog to pop up to try to attach a debugger. This makes running the unit test in debug impossible.
The following tests also trigger it:
- `AssetBrowserTest.CheckCorrectNumberOfEntriesInTableViewAfterStringFilter`
- `AssetBrowserTest.CheckScanFolderAddition`

**Steps to reproduce**
Run the test `AssetBrowserTest.CheckCorrectNumberOfEntriesInTableView` from AzToolsFramework.Tests in debug mode

**Expected behavior**
To be able to run unit tests

**Actual behavior**
When this test is run, a dialog interrupts the run and prevents to continue testing. Ignoring does not solve it because its being hit repeatedly. 
Lots of entries like:
```
ASSERT: "!parent.isValid()" in file E:/o3de/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableModel.cpp, line 98
````
during the execution of the tests (if pressing "Ignore").
I also noticed:
```
QSortFilterProxyModel: inconsistent changes reported by source model
```

**Comment by monroegm** [comment]
@alexmontAmazon FYI

**Comment by AMZN-daimini** [comment]
@hultonha @AMZN-Igarri Is that test related to the flattened view?

**Comment by hultonha** [comment]
Yes this is most likely related, @AMZN-Igarri is out this week but I'm sure can take a quick look next week
