### ISSUE TITLE
Asset Browser Filter String Fails To List Target File

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#6149]
**Describe the bug**
The file I was looking for "CC3_Example_Character_Gamebase_v6_O3DE.fbx" did not show up when filtering for "Character" but did show up when filtering for "\_Character\_"

**Steps to reproduce**
1. Use AutomatedTesting as the active project
2. Make an fbx file (just copy some other file is fine) to "Gems\Atom\TestData\TestData\TEMP\CC3_Example_Character_Gamebase_v6\CC3_Example_Character_Gamebase_v6_O3DE.fbx"
3. Run the Editor
4. Scroll through the Asset Browser to confirm that this fbx file is present.
5. Type "Character" in the filter box.
6. Scroll through the list in the Asset Browser; the file "CC3_Example_Character_Gamebase_v6_O3DE.fbx" is not listed.
7. Change the filter string to be "\_Character\_"
8. Scroll through the list in the Asset Browser and you will find "CC3_Example_Character_Gamebase_v6_O3DE.fbx" is now present (probably at the very bottom).

**Expected behavior**
Searching for "Character" should find "CC3_Example_Character_Gamebase_v6_O3DE.fbx".

**Actual behavior**
For some reason you have to search for "\_Character\_" to get "CC3_Example_Character_Gamebase_v6_O3DE.fbx" to show up.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/55155825/144682916-5505a0cb-68d5-4be6-8f67-97d24b8953ef.png)

**Found in Branch**
development
commit cfb426b86c34be6474095433c10844610fcbd070

**Comment by AMZN-Igarri** [comment]
Hi @santorac I'm looking into this and I am not experiencing the same behavior. Can you provide any additional details that you think might be causing this issue?
What OS were you using?
Thanks a lot!
![image](https://user-images.githubusercontent.com/82394219/148058804-35154f4f-2a92-4fb8-95fd-46031092a082.png)

**Comment by santorac** [comment]
I can no longer reproduce this issue as of a690c76ad4716233f726f60277f72636eebaf295
