### ISSUE TITLE
Engine crash because gems cache not found

### ISSUE THREAD

**Issue by Cesio137** [o3de/o3de#6157]
**Describe the bug**
Open 3D Engine dont open after compile project.

Python~~ERROR:root:Could not find cached repository json file for

**Steps to reproduce**
1. Install open3dengine by installer
2. Create a new project
3. Compile
4. Click Open
5. Editor apear for a little time but close and error report show in task manager

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/29849613/144693585-603034f9-3f21-4884-a978-852d1d03eb0b.png)

[O3DE.log](https://github.com/o3de/o3de/files/7653156/O3DE.log)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: WINDOWS 10 21H2
 - CPU i3-7100
 - GPU 750 TI
 - Memory 8GB

**Comment by forhalle** [comment]
Was this performed through Project Manager or through the command line?

**Comment by lmbr-pip** [comment]
"ERROR:root:Could not find cached repository json file for . Try refreshing the repository." is last line in log

**Comment by Cesio137** [comment]
> @Cesio137 - Was this performed through Project Manager or through the command line?

Both

**Comment by Cesio137** [comment]
> "ERROR:root:Could not find cached repository json file for . Try refreshing the repository." is last line in log

How i can do that?

**Comment by monroegm** [comment]
"ERROR:root:Could not find cached repository json file for . Try refreshing the repository." Might be SIG-Core

**Comment by Icaro-Lima** [comment]
Same problem here. Any workaround?

**Comment by Cesio137** [comment]
> Same problem here. Any workaround?

Sorry, just wait for more updates until O3DE be more mature

**Comment by robhaco** [comment]
Checked with both project templates in a recent development installer (from 7/7) and this doesn't appear to be happening any longer.  Unless this is gem specific, the issue appears to be fixed.
