### ISSUE TITLE
Custom Python Tool which contains an error in its .py file crashes the Editor when opened

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#6167]
**Describe the bug**
Attempting to open the Custom Python Tool which .py file contains an error (i.e. a missing import module statement or an attempt to call a non-existing method) crashes the Editor. This was observed when following the [Create a Custom Tool Gem in Python to Extend Open 3D Engine Editor](https://o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/) due to [#1275](https://github.com/o3de/o3de.org/issues/1275). 

Please note that the crash does not occur when attempting to run the custom tool from the _Python Scripts_ window and only happens when attempting to do so via pressing its Icon on the Toolbar or the _Tools/Examples_ menu.

Please also note that the crash seems to only occur when the error is in the _Qt_ part of the code (i.e. missing import of a _QtWidget_).

Please refer to the attached video and log files for more details.

**Steps to reproduce**
1. Clone the [PyShapeExample](https://github.com/o3de/sample-code-gems/tree/main/py_gems/PyShapeExample) repository.
2. Open the _<cloned_repository_location>/py_gems/PyShapeExample/Editor/Scripts/pyshapeexample_dialog.py_ file in a text editor.
3. Remove one of the imported _QtWidgets_ Modules, i.e. _QCheckBox_ and save the file.
4. Register and enable the _PyShapeExample_ Gem for your Project.
5. Rebuild the Project.
6. Launch the Editor.
7. Attempt to run the _PyShapeExample_ tool from the Toolbar or the _Tools/Examples_ menu.

**Expected behavior**
The Error is displayed in the Console. The Editor remains stable.

**Actual behavior**
The Editor crashes.

**Call Stack Trace**
```
25) 00007FF87855B7F7 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FF87A8151B0 (ntdll) : memset
23) 00007FF87A7FC766 (ntdll) : _C_specific_handler
22) 00007FF87A8120CF (ntdll) : _chkstk
21) 00007FF87A7C1454 (ntdll) : RtlRaiseException
20) 00007FF87A810BFE (ntdll) : KiUserExceptionDispatcher
19) D:\Git\o3de\Code\Editor\Core\LevelEditorMenuHandler.cpp (1172) : LevelEditorMenuHandler::checkOrOpenView
18) 00007FF822C90DB9 (Qt5Core) : QObject::qt_static_metacall
17) 00007FF8236F5DCF (Qt5Widgets) : QAction::activate
16) 00007FF82384C698 (Qt5Widgets) : QMenu::actionGeometry
15) 00007FF82384C473 (Qt5Widgets) : QMenu::actionGeometry
14) 00007FF823851C51 (Qt5Widgets) : QMenu::mouseReleaseEvent
13) 00007FF823727B02 (Qt5Widgets) : QWidget::event
12) 00007FF82384DC37 (Qt5Widgets) : QMenu::event
11) 00007FF8237049B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
10) 00007FF8237028D0 (Qt5Widgets) : QApplication::notify
 9) 00007FF822C71B4A (Qt5Core) : QCoreApplication::notifyInternal2
 8) 00007FF823705BC5 (Qt5Widgets) : QApplicationPrivate::sendMouseEvent
 7) 00007FF82375024A (Qt5Widgets) : QSizePolicy::QSizePolicy
 6) 00007FF82374E80E (Qt5Widgets) : QSizePolicy::QSizePolicy
 5) 00007FF8237049B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
 4) 00007FF823703A33 (Qt5Widgets) : QApplication::notify
 3) 00007FF822C71B4A (Qt5Core) : QCoreApplication::notifyInternal2
 2) 00007FF8230B34D1 (Qt5Gui) : QGuiApplicationPrivate::processMouseEvent
 1) 00007FF82309EE89 (Qt5Gui) : QWindowSystemInterface::sendWindowSystemEvents
```

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/144853616-0ddc0aea-efdb-4fd3-979d-b92a15e180ca.mp4

**Found in Branch**
Development (86b397f)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600
 - GPU: Nvidia RTX 2060 SUPER
 - Memory: 16GB

**Attachments**
[Editor.log](https://github.com/o3de/o3de/files/7660894/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7660895/error.log)
[error.zip](https://github.com/o3de/o3de/files/7660896/error.zip)

**Comment by LB-TomaszSerwanski** [comment]
Please note that the similar thing happens with the C++ template Tool when for example a _QtWidget_ include is missing. However, instead of crashing it fails on the Project building stage. Please let us know if this should be reported as a separate issue?

**Comment by cgalvan** [comment]
Those imports are needed. If you delete them, then yes it will crash. The missing import is noted in the crash.

**Comment by LB-TomaszSerwanski** [comment]
Issue accepted as Closed based on the comment above. Please refer to [#1275](https://github.com/o3de/o3de.org/issues/1275) for the progress on fixing the documentation issue.
