### ISSUE TITLE
Duplicating and Renaming a project doesn't update name in launcher UI

### ISSUE THREAD

**Issue by Ifelsethendo** [o3de/o3de#6187]
**Describe the bug**
Duplicating and Renaming a project doesn't update name in launcher UI

**Steps to reproduce**
1. launch o3de
2. duplicate a project to a new folder with the desired new project name
3. edit project settings
4. change the project name of the duplicated project
5. Save
6. Note: you still have two projects of the same name

**Expected behavior**
When duplicating the project and choosing a new folder name, the folder should determine the project name so steps 3, 4, and 5 can be skipped.  The o3de launcher should reflect the changes made during the duplication process.

**Actual behavior**
Project name does not update in launcher UI.
If o3de is exited and restarted the changes made in steps 3, 4 and 5 are reflected.

**Assets required**
Any project on your local machine should see the same results.

**Desktop/Device (please complete the following information):**
 - PC
 - OS: Windows
 -10
 -Intel 
 - NVIDIA GTX 1060
 - 12GB

**Comment by AMZN-daimini** [comment]
May be related to https://github.com/o3de/o3de/issues/6188 ?

**Comment by robhaco** [comment]
This is still occurring as of 7/7 but also seems related to https://github.com/o3de/o3de/issues/4079 for part of the issue.
