### ISSUE TITLE
Duplicating Project Breaks Projects

### ISSUE THREAD

**Issue by Ifelsethendo** [o3de/o3de#6188]
**Describe the bug**
Duplicating Project leaves project broken

**Steps to reproduce**

1. Open o3de
2. duplicate a project
3. rebuild BOTH projects
4. try to open editor on either project
5. See error...exactly

**Expected behavior**
Duplicating a project should not require the chosen project to be rebuilt at all.
The dupe should work exactly as the initial project worked.

**Actual behavior**
Asset builder throws a whole bunch of errors on a project (PONG tutorial) that was working 100% before the duplication process.
Attempting to open the project in editor throws errors for about 40 minutes beause thousands of assets are being rebuilt...for a simple Pong tutorial.
Finally "O3DE could not be initialized correctly for following reasons:
Could not load font: Fonts/default.font
could not load font : Fonts/default-ui.font"
Clicking OK on the dialog then crashes the Editor.

On the duplicated version of the project:
O3DE coul dnot be initialized correctly for the following reasons:
Unable to find product asset 'Shaders/SimpleTexture.azshader'.  Has the source asset finished building?

Why would it need building in the first place when it was built the first time before choosing to duplicate the project?

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel
 - GPU NVidia 
 - Memory [e.g. 12GB]

**Comment by AMZN-alexpete** [comment]
I think one issue is when a project is duplicated, the new project has the same name and the Project Manager is assuming unique project names for storing information about whether a project needs to be compiled or not.

**Comment by AMZN-alexpete** [comment]
I wasn't able to reproduce the crash after building the duplicated project - the Editor for both projects opened OK and without errors  and I could load a level without issue.  I was using the stabilization/2205 branch and suspect the shader issue has been fixed since this issue was created, but the Project Manager naming issue still remains.

**Comment by robhaco** [comment]
Unable to reproduce the crashes mentioned in this issue in recent development.  With that, I believe the remaining issue of the naming is covered by https://github.com/o3de/o3de/issues/7691
