### ISSUE TITLE
Close Prefab option is available from the context menu of Level prefabs

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6191]
**Describe the bug**
A redundant "Close Prefab" option is available from the context menu of Level prefabs and does seemingly nothing.

**Steps to reproduce**
1. Create a new level.
2. Press RMB on the level prefab entity and notice Close Prefab option being available.
3. Select the Close Prefab option.

**Expected behavior**
No redundant options are available from the context menu of the Level prefab.

**Actual behavior**
"Close Prefab" option is available from the context menu of the Level prefab.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/144995895-b879917a-8628-46c3-a6f1-02be07f23b49.mp4

**Found in Branch**
Development (9698047)

**Desktop/Device**
Device: PC
OS: Windows
Version: 10
CPU: Intel i5-9600K
GPU: RTX 2070
Memory: 16GB

**Comment by monroegm** [comment]
@LB-KacperKapusta What happens when you click on Close Prefab?

**Comment by LB-KacperKapusta** [comment]
@monroegm Clicking on Close Prefab from the level entity's context menu does seemingly nothing.
