### ISSUE TITLE
Switch Camera options are not functional

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6193]
**Describe the bug**
Options available from the main Editor's toolbar under View -> Viewport -> Switch Camera are not functional.

Please note that **Default Camera**, **Sequence Camera**, **Selected Camera Object** options from the described submenu are grayed out and unavailable to use. An option to **Cycle Camera** (Ctrl+`) can be selected but does nothing.

**Steps to reproduce**
1. Launch the Editor.
2. From the toolbar select View -> Viewport -> Switch Camera.
3. Press Cycle Camera or use the Ctrl+` shortcut.

**Expected behavior**
Switch Camera options are working properly.

**Actual behavior**
Switch Camera options are not functional.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/145000350-f4ceb2ff-883d-465b-9025-ba29c36d8eba.mp4

**Found in Branch**
Development (9698047)

**Desktop/Device**
Device: PC
OS: Windows
Version: 10
CPU: Intel i5-9600K
GPU: RTX 2070
Memory: 16GB

**Comment by hultonha** [comment]
This could be a good issue for @AMZN-Igarri to take a look at. These menu options (along with everything under 'Go to selection') should be removed as they're all legacy and non-functional. These options will be replaced with the new Camera Bookmark system @AMZN-Igarri is working on (RFC incoming soon). We'll link to it on this ticket when it's ready to view.

**Comment by LB-KacperKapusta** [comment]
Verified using Development (3f3f133) that the issue does still occur.

**Comment by hultonha** [comment]
Hmm so using Ctrl+F<num> keys to place transforms and Shit+F<num> keys to return to them works, but the UI elements aren't hooked up? 🤔 Is that right @LB-KacperKapusta? Thanks!

**Comment by LB-KacperKapusta** [comment]
The Ctrl+F and Shift+F keys work and their UI elements also do. The elements from under the Switch Camera tab like Cycle Camera do not work - as shown in the video attached.

**Comment by hultonha** [comment]
Hmm I'm of the opinion we just remove that option entirely as it's much clearer to simply use the Viewport Camera Selector window, does that seem reasonable? 🤔

**Comment by LB-KacperKapusta** [comment]
The submenu could be removed but in my opinion a shortcut for switching cameras would still be useful in the Viewport Camera Selector for bigger projects.

**Comment by hultonha** [comment]
> The submenu could be removed but in my opinion a shortcut for switching cameras would still be useful in the Viewport Camera Selector for bigger projects.

That's a good point, so you mean move the existing functionality to the Viewport Camera Selector window (to move between saved camera positions?)

This is something hopefully @amzn-ahmadkrm might be able to take a look at soon 🙂

**Comment by LB-KacperKapusta** [comment]
@hultonha Yeah, exactly what I was meaning.

**Comment by hultonha** [comment]
Okay perfect thanks! 🙂 I think short-term we remove, and migrate functionality to the Viewport Camera Selector Window. I'll keep you posted 👍

**Comment by spham-amzn** [comment]
Closing issue since the option was removed. If cycle camera is still desired, create a new GHI based on the suggestion above.
