### ISSUE TITLE
[macOS] Editor crashes upon launching with AutomatedTesting project set as active

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6209]
**Describe the bug**
Launching the Editor with the AutomatedTesting project set as active results in a crash. 

Please refer to the attached crash.log and ProblemReportForEditor.rtf generated during crash for more information.

**Prerequisites:**

-  Asset Processor and Editor have been built.
-  Assets were processed in Asset Processor.
-  AutomatedTesting was set as a project to launch.

**Steps to reproduce**
1. Launch the Editor.

**Expected behavior**
The Editor launches without any issues for the active project.

**Actual behavior**
The Editor crashes upon launching with AutomatedTesting project set as active.

**Found in Branch**
Development (9698047)

**Desktop/Device**
Device: MacBook Pro
OS: macOS
Version: Big Sur 11.3.1
CPU: Intel Core i5 2.0GHz Quad-Core
GPU: Intel Iris Plus Graphics 1536 MB
Memory: 16GB

**Additional context**
[crash.log](https://github.com/o3de/o3de/files/7669156/crash.log)
[ProblemReportForEditor.zip](https://github.com/o3de/o3de/files/7669161/ProblemReportForEditor.zip)
[ProblemReportForEditor.log](https://github.com/o3de/o3de/files/7669162/ProblemReportForEditor.log)

**Comment by LB-KacperKapusta** [comment]
The issue has also been confirmed as occurring on the following device:

Device: MacBook Pro
OS: macOS
Version: Big Sur 11.5.1
CPU: Intel Core i7 2,8 GHz
GPU: Radeon Pro 555
Memory: 16GB

**Comment by amzn-sj** [comment]
I'm unable to reproduce this issue with latest from development. I'm starting from a new clone of the repo so it's from a clean state with no previous assets processed. When I launch the Editor, it launches AP and once the critical assets finish processing, it opens the Editor as expected. I'm also able to open the PrefabLevel_OpensLevelWithEntities level. Built with AutomatedTesting set as the game project.

**Comment by LB-KacperKapusta** [comment]
Please note that the original ticket has been reported after starting from a new clone of the repo and attempting to launch the Editor after all assets have been processed.

Attempting to reverify the issue on Development (a8ef23e) today, however, resulted in the building failing reported as a separate issue - [#6209](https://github.com/o3de/o3de/issues/6209).
