### ISSUE TITLE
[Assert] Refreshing Audio causes an assert to pop up

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6248]
**Describe the bug**
Performing the Game > Audio > Refresh Audio action causes an assert to pop up. It should be noted that this was verified on new projects with all gems enabled.

File:
```
C:/Builds/o3de/Gems/AudioEngineWwise/Code/Source/Engine/AudioSystemImpl_wwise.cpp
```
Condition:
```
(7620) 'void __cdecl Audio::CAudioSystemImpl_wwise::OnAudioSystemRefresh(void)'
<Wwise> Failed to load init.bnk!
```
Line: 365

**Steps to reproduce**
1. Execute the sys_assert 2 command in the Console.
2. Perform the Game > Audio > Refresh Audio action.

**Expected behavior**
Audio is refreshed or a message is printed to the Console if it is not set up.

**Actual behavior**
Assert pops up.

**Video, assert, and Editor.log**

https://user-images.githubusercontent.com/86952082/145205965-11d345bb-cc5f-4f09-9b2c-70c7d4e73855.mp4

Assert:
![Assert](https://user-images.githubusercontent.com/86952082/145206116-bfa7ab87-7904-47ce-81a5-274fc59d5af5.PNG)

[Editor.log](https://github.com/o3de/o3de/files/7675889/Editor.log)

**Found in Branch**
Development (a8ef23e)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by amzn-phist** [comment]
In the development branch, this no longer produces an Assert, even with `sys_asserts 2` as stated in the repro steps.  It has been reduced to an ERROR message instead.

This is happening because there aren't any banks in the project to reload.  There are adequate error messages printed to Console when it fails in such a way:

```
sys_asserts 2
sys_asserts=2 [  ]
(Logger) - Beginning to refresh the AudioSystem...
(Logger) - <Wwise> Cannot open file: init.bnk ErrorCode: 0 PlayingID: 0 GameObjID: 18446744073709551615
(Logger) - <Wwise> Bank Load Failed ErrorCode: 55 PlayingID: 0 GameObjID: 18446744073709551615
[Error] (AudioTranslationLayer) - ATL RefreshAudioSystem - Failed to load fresh global banks!
(Logger) - Done refreshing the AudioSystem!
```
