### ISSUE TITLE
Decal Sort Key property has a wrong value clamp stated in its tooltip

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6249]
**Describe the bug**
Decal Sort Key property in engine has its value clamp stated as [0, INF] (Tooltip: "Decals with a larger sort key appear over top of smaller sort keys. [0, INF]"). In actuality its value is clamped at [0, 255]. It should be noted that under the Property section of the Decal documentation page (https://o3de.org/docs/user-guide/components/reference/atom/decal/), the values for the Sort Key property are listed as "0 to 255" as well.

**Steps to reproduce**
1. Create an entity and add a Decal component to it.
2. Hover over the Sort Key property and check its allowed values.
3. Attempt to enter a value higher than 255 in the Sort Key's text box.

**Expected behavior**
Tooltip correctly reflects the allowed values to use in the parameter.

**Actual behavior**
Tooltip has an incorrect allowed values listed.

**Video**

https://user-images.githubusercontent.com/86952082/145209082-fe56e30d-4378-42d7-8711-07531fffa394.mp4

**Found in Branch**
Development (a8ef23e)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by mrieggeramzn** [comment]
Good catch, fixed

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on Development (f026e54) build.
