### ISSUE TITLE
Editor freezes indefinitely after loading a level

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6254]
**Describe the bug**
Opening a level inside the Editor may result in the Editor becoming not responding.
Please note that the issue occurs with 100% reproduction rate when using the Source Engine build type and is much less likely to occur on Pre-built SDK engine (1/5 in our case).

We have verified that the issue does not occur on the o3de_installer_2111_1 build.

Editor does not crash therefore it does not create any logs.
Please refer to the attached video and Visual Studio output for more information.

**Prerequisites**
- Clone the O3DE GitHub repo.
- Follow the instructions for building the Source Engine (https://o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/).

**Steps to reproduce**
1. Open the O3DE.
2. Create and build a new project.
3. Launch the Editor.
4. Create a new level (or open an already existing one).

**Expected behavior**
A level opens and the Editor remains stable.

**Actual behavior**
A level opens and the Editor becomes unresponding.

**Screenshots/Video**
https://user-images.githubusercontent.com/86953659/145225682-e0fef28c-20bd-44cd-b5e6-96d2970040f5.mp4

**Found in Branch**
Development (f9f11d9)

**Desktop/Device**
Device: PC
OS: Windows
Version: 10
CPU: Intel i5-9600K
GPU: RTX 2070
Memory: 16GB

**Additional context**
![VS_MainThread](https://user-images.githubusercontent.com/86953659/145226106-c2766f1c-8104-46fa-abd1-73af95d7c528.PNG)
[VS_OutputWindow.txt](https://github.com/o3de/o3de/files/7676678/VS_OutputWindow.txt)

**Comment by AMZN-daimini** [comment]
Sounds like a deadlock on the Atom RPI? Adding Graphics for triage.

**Comment by rgba16f** [comment]
PR to fix the issue: https://github.com/o3de/o3de/pull/6323

**Comment by rgba16f** [comment]
Fix has been committed to the development branch.

**Comment by rgba16f** [comment]
This should now be fixed.

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed in Development (d951e1f).
