### ISSUE TITLE
Material saved in the o3de-install directory fails processing in the Asset Processor

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6289]
**Describe the bug**
Saving a Material in the o3de-install directory results in the Asset Processor failing to process the Material.

Please note that a Material saved under _o3de-install/Assets_ directory is not processed by the Asset Processor at all and a Material saved under the project directory is processed without the failure.

Please refer to the attached JobLog and video for more information.

**Prerequisites**

- Follow the instructions for building the Pre-built SDK engine (https://o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/).

**Steps to reproduce**
1. Create a new level.
2. Select the Ground entity.
3. Press on the preview of the Material inside the Material component.
4. Select 'Edit Material Instance...'.
5. Select the hamburger icon in the top-left corner of the Material Property Inspector.
6. Select 'Save Material'.
7. Save Material in the o3de-install directory.

**Expected behavior**
Material saved in any directory is processed successfully by the Asset Processor.

**Actual behavior**
Material saved in the o3de-install directory fails processing in the Asset Processor

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/145418132-7acd6f0c-2d5e-4087-bfe1-3963d685e8a5.mp4

**Found in Branch**
Stabilization/2111RTE (667512c)

**Desktop/Device**
Device: PC
OS: Windows
Version: 10
CPU: Intel i5-9600K
GPU: RTX 2070
Memory: 16GB

**Additional context**
[test2.material-2777402568-8758.log](https://github.com/o3de/o3de/files/7686018/test2.material-2777402568-8758.log)

**Comment by santorac** [comment]
It looks like the material is referencing the material type using a path like
```
 "materialType": "../Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR.materialtype"
```
The Material Editor is incorrectly detecting the possibility of a relative path. It needs to disallow relative paths that step up out of a project or gem. This is something I think @gadams3 can fix. 

If you put your material a couple levels deeper in another folder it should alleviate the problem. (The relative path support is configured to allow only 2 steps up for "..", so if it's three steps it will give up and use the proper asset path instead). For example, put it under  Pong\Materials\TestMaterials or Pong\Assets\Materials, something like that.

**Comment by gadams3** [comment]
On the development branch, the material editor no longer saves material relative paths. references are now relative to the source asset folder, which will eliminate this problem unless someone manually enters a path that jumps across unsupported boundaries. Saving references relative to the material file is less critical because we now support processing and opening materials with bad references so the user will know and be able to update their textures.
