### ISSUE TITLE
Prefab Focus Mode: Toggle pivot/Instantiate Prefab/Instantiate Procedural Prefab context menu options are available on prefab containers

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#6307]
**Describe the bug**
Toggle pivot/Instantiate Prefab/Instantiate Procedural Prefab context menu options are available on .procprefab containers. This allows editing of read-only entities.

**Pre-requisites**
1. Procedural Prefabs are enabled in AutomatedTesting\user\Registry\editorpreferences.setreg:

```
{
    "Amazon": {
        "Preferences": {
            "EnablePrefabSystem": true,
            "EnablePrefabSystemWipFeatures": true
        }
    },
    "O3DE": {
        "Preferences": {
            "Prefabs": {
                "SaveAllPrefabs": "Ask every time",
                "UseProceduralPrefabs": true
            }
        }
    }
}
```

**Steps to reproduce**
1. Launch the Editor and open a new or existing level.
2. Instantiate any .procprefab into the Entity Outliner.
3. Right-click the .procprefab container and Instantiate Prefab...

**Expected behavior**
Toggle pivot/Instantiate Prefab/Instantiate Procedural Prefab context menu options are not available on read-only entities.

**Actual behavior**
Toggle pivot/Instantiate Prefab/Instantiate Procedural Prefab context menu options are available on .procprefab containers when not in Focus Mode. If the .procprefab is in Focus Mode, the operations are unavailable.

**Found in Branch**
development@a8a96d3e66853fdd

**Comment by AMZN-daimini** [comment]
Oh this sounds like a regular prefab issue too - you shouldn't be able to instantiate a prefab inside a prefab while not in focus mode. Will give it a quick look.
