### ISSUE TITLE
Looking at the character running from the side view, there is obvious jitter

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#6324]
**Describe the bug**
Looking at the character running from the side view, there is obvious jitter

**Steps to reproduce**
1. Go to 'Make a basic character control scene'
2. Click on '...'
3. Select attached asset '...'
4. Scroll down to '...'
5. See error

**Expected behavior**
Seeing the character running from the side angle of view, no obvious jitter

**Actual behavior**
Looking at the character running from the side view, there is obvious jitter

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**

**Found in Branch**
development.

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Gold 6234]
- GPU [NVidia RTX 5000]
- Memory [e.g. 128GB]

**Additional context**

**Comment by lsemp3d** [comment]
Not enough details, but also seems related to the opengl render window which is deprecated
