### ISSUE TITLE
Click Scale under the OpenGL Render Window of the animation editor to modify the scale of the model, and it is found that the bones and the skin cannot be scaled synchronously

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#6325]
**Describe the bug**
Click Scale under the OpenGL Render Window of the animation editor to modify the scale of the model, and it is found that the bones and the skin cannot be scaled synchronously

**Steps to reproduce**
1. Open the animation editor
2. Click File->Open Actor, select a model
3. Click Scale under OpenGL Render Window to stretch or compress the X, Y, and Z axes
4. Scroll down to '...'
5. See error

**Expected behavior**
Bone and skin can be scaled synchronously

**Actual behavior**
Bone and skin can not be scaled synchronously

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**

**Found in Branch**
development.

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Gold 6234]
- GPU [NVidia RTX 5000]
- Memory [e.g. 128GB]

**Additional context**

**Comment by lsemp3d** [comment]
The OpenGL Render window is deprecated, resolving as "wont-do"
