### ISSUE TITLE
Prefab Focus Mode: Lock Transform and Reset Transform Appear Usable Within Read-Only Entity Components

### ISSUE THREAD

**Issue by LesaelR** [o3de/o3de#6338]
**Describe the bug**
The Lock and Reset Transform buttons appear usable when expanding the hamburger menu within read only entity components inside the Entity Inspector

**Pre-requisites**

1. Procedural Prefabs are enabled in AutomatedTesting\user\Registry\editorpreferences.setreg:

```
{
    "Amazon": {
        "Preferences": {
            "EnablePrefabSystem": true,
            "EnablePrefabSystemWipFeatures": true
        }
    },
    "O3DE": {
        "Preferences": {
            "Prefabs": {
                "SaveAllPrefabs": "Ask every time",
                "UseProceduralPrefabs": true
            }
        }
    }
}

```
**Steps to reproduce**

1.     Launch the Editor and open a new or existing level.
2.     Instantiate any .procprefab into the Entity Outliner.
3.     Enter Focus Mode on the .procprefab, and select a read-only entity. 
4.     In the Entity Inspector, expand the transform component's hamburger menu (or right-click the transform component)

**Expected behavior**
Only the "Copy Component" field is available for components within a read-only entity. 

**Actual behavior**
Lock Transform and Reset Transform appear usable.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/89800757/145628807-57860edd-fbe7-4148-acfd-bf58ddbafc4c.png)

**Found in Branch**
development@a8a96d3e66853fdd

**Comment by AMZN-daimini** [comment]
Must have missed this, will fix asap :D Good spot.
