### ISSUE TITLE
[SliceDeprecation] Convert Vegetation(largeworlds\dyn_veg) related automated tests to use prefab system

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#6339]
Make all the following automated tests to use new dynveg.create_prefab_vegetation_area function in order to utilize prefab system:

- AssetListCombiner_CombinedDescriptorsExpressInConfiguredArea
- AssetWeightSelector_InstancesExpressBasedOnWeight
- DistanceBetweenFilterOverrides_InstancesPlantAtSpecifiedRadius
- DistanceBetweenFilter_InstancesPlantAtSpecifiedRadius
- EmptyInstanceSpawner_EmptySpawnerWorks
- InstanceSpawnerPriority_LayerAndSubPriority
- LayerBlender_E2E_Editor
- LayerBlocker_InstancesBlockedInConfiguredArea
- LayerSpawner_FilterStageToggle
- LayerSpawner_InheritBehaviorFlag
- LayerSpawner_InstancesPlantInAllSupportedShapes
- LayerSpawner_InstancesRefreshUsingCorrectViewportCamera
- MeshBlocker_InstancesBlockedByMesh
- MeshBlocker_InstancesBlockedByMeshHeightTuning
- PositionModifier_AutoSnapToSurfaceWorks
- PositionModifier_ComponentAndOverrides_InstancesPlantAtSpecifiedOffsets
- RotationModifierOverrides_InstancesRotateWithinRange
- RotationModifier_InstancesRotateWithinRange
- ScaleModifierOverrides_InstancesProperlyScale
- ScaleModifier_InstancesProperlyScale
- ShapeIntersectionFilter_FilterStageToggle
- ShapeIntersectionFilter_InstancesPlantInAssignedShape
- SlopeAlignmentModifierOverrides_InstanceSurfaceAlignment
- SlopeAlignmentModifier_InstanceSurfaceAlignment
- SlopeFilter_ComponentAndOverrides_InstancesPlantOnValidSlopes
- SurfaceMaskFilterOverrides_MultipleDescriptorOverridesPlantAsExpected
- SurfaceMaskFilter_ExclusionList
- SurfaceMaskFilter_InclusionList
- SystemSettings_SectorPointDensity
- SystemSettings_SectorSize
- VegetationInstances_DespawnWhenOutOfRange
- SpawnerSlices_SliceCreationAndVisibilityToggleWorks
- PhysXColliderSurfaceTagEmitter_E2E_Editor
- DynamicSliceInstanceSpawner_DynamicSliceSpawnerWorks
- DynamicSliceInstanceSpawner_Embedded_E2E
- DynamicSliceInstanceSpawner_External_E2E

Here are the converted tests that can be used as reference:

- AltitudeFilter_ComponentAndOverrides_InstancesPlantAtSpecifiedAltitude
- AltitudeFilter_FilterStageToggle
- AltitudeFilter_ShapeSample_InstancesPlantAtSpecifiedAltitude

Related PR for reference:
- https://github.com/o3de/o3de/pull/6179

Note:
- If Physics/Base.prefab is used in tests to convert, replace it with Base.prefab.
- Rename tests/variables/... to prevent using deprecated term `slice`. Use `prefab` instead.

**Comment by jckand-amzn** [comment]
This is complete, and all converted tests are running successfully in AR.

**Comment by chiyenteng** [comment]
PR: https://github.com/o3de/o3de/pull/7034

**Comment by chiyenteng** [comment]
PR to remove DynamicSliceInstanceSpawner_DynamicSliceSpawnerWorks: #8404
