### ISSUE TITLE
Procedural Prefabs: Entities Appear as Read-Only when Parenting an Entity to a Procedural Prefab Using the Re-Targetting Icon

### ISSUE THREAD

**Issue by LesaelR** [o3de/o3de#6343]
**Describe the bug**
When using the Re-Target button to parent an entity to a Procedural Prefab, the entity displays as Read-Only within the Entity Outliner, the editable entity is given a Read-Only status, and the Procedural Prefab displays an "*" as if it it had changes that could be saved.

**Pre-requisites**

1. Procedural Prefabs are enabled in AutomatedTesting\user\Registry\editorpreferences.setreg:

```
{
    "Amazon": {
        "Preferences": {
            "EnablePrefabSystem": true,
            "EnablePrefabSystemWipFeatures": true
        }
    },
    "O3DE": {
        "Preferences": {
            "Prefabs": {
                "SaveAllPrefabs": "Ask every time",
                "UseProceduralPrefabs": true
            }
        }
    }
}
```

**Steps to reproduce**

1. Launch the Editor and open a new or existing level.
2. Create an prefab.
3. Instantiate any .procprefab into the prefab.
4. Create an entity.
5. Select the entity in the Entity Outliner.
6. With the entity selected, click on the re-targetting icon next to the Parent field within the Entity Inspector's Transform component.
7. Click on the procedural prefab within the Entity Outliner
8. Place a second instance of the prefab containing the procedural prefab into the world (to refresh the read-only status)

**Expected behavior**
Edit: It should not be possible to move entities under a procedural prefab.

**Actual behavior**
The read-only status propagates to the parented entity and the procedural prefab displays unsaved changes. 

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/89800757/145639426-f5c3c41e-2b43-4fac-aa87-2c5a2df523b7.png)
![image](https://user-images.githubusercontent.com/89800757/145639646-89247e37-74ce-4b56-9560-42567fdcb210.png)

**Found in Branch**
development@a8a96d3e66853fdd

**Comment by AMZN-daimini** [comment]
> When using the Re-Target button to parent an entity to a Procedural Prefab
The operation listed is invalid. It should not be possible to move entities under a procedural prefab, in any way.
Fixing that will prevent the rest of the issues.
