### ISSUE TITLE
Networking component names are inconsistent with other component names

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#6353]
to be more consistent the networking component names should have space in them too

![image](https://user-images.githubusercontent.com/48143120/145657342-3edb71ed-02b5-4034-83d1-db86af13269a.png)

**Comment by lmbr-pip** [comment]
sig-ui-ux: Need input on name format changes.

**Comment by lmbr-pip** [comment]
Assume this is just a display name change, but maybe in the autocomponent code of networking.

Action Items:
* Need to understand if this a breaking change at all
* Need to scope documentation changes (screenshots or references to components)

**Comment by AMZN-Gene** [comment]
There's already a method to add spaces to CamelCaseStrings: ScriptCanvas::TranslationDeneration::SplitCamelCase. Let's move this method to AZ::StringFunc so any gem can reach it without depending on ScriptCanvas. Seems like a good util type method lots of ppl might use.

**Comment by lmbr-pip** [comment]
@lmbr-pip Please followup with SIG-UI-UX and then bring back to triage.

**Comment by lmbr-pip** [comment]
This is somewhat tricky to solve, will use `LocalPredictionPlayerInputComponent` as an example:

* Has an autogen file called `LocalPredictionPlayerInputComponent.AutoComponent.xml`
* In autogen has the property ` OverrideComponent="true" ` set
* This auto generates an `LocalPredictionPlayerInputComponentBase` component with a `ReflectToEditContext` method
* LocalPredictionPlayerInputComponent`'s reflect calls `LocalPredictionPlayerInputComponentBase::Reflect(context)` which setups edit context for both `LocalPredictionPlayerInputComponentBase` and  `LocalPredictionPlayerInputComponent` in autogenerated code.

There is no automated way currently to enable autogen code to take:
* Display name or generate display name from component, in this case it should be *Local Prediction Player Input*
* Nor to provide component description

**Comment by AMZN-Gene** [comment]
Right now autogen will take the AutoComponent name raw... example:
  editContext->Class<LocalPredictionPlayerInputComponent>("LocalPredictionPlayerInputComponent", "")

We could run this raw name thru a method which camel cases and add spaces to the class name (like the method TranslationDeneration::SplitCamelCase), and then also strip off the word "Component" if it finds it at the end of the name.

**Comment by lmbr-pip** [comment]
Confirmed that naming changes are ok with sig-ui-ux. Remarking for triage so we can re-discuss next steps.
