### ISSUE TITLE
Bug Report - Inconsistency between project creation and gem creation using CLI regarding directory

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#6357]
When creating a project, you can use an empty folder as the directory and that is where the project will be created

However, when creating a gem if you tried to specify an empty folder it will say can't write to existing thingy
"Cannot create a file when that file already exists"

I think that they should be the same behavior so it is not unexpected

**Comment by forhalle** [comment]
@AMZN-Phil - Rumor has it you may have already fixed this. Can you confirm and close if so?

**Comment by AMZN-Phil** [comment]
Yes, this is fixed. I'll tag the PR and close this out
