### ISSUE TITLE
Can't rebuild

### ISSUE THREAD

**Issue by watchmax3** [o3de/o3de#6358]
> > I installed CMake and vs2019 last version. I installed o3de but after 19% rebuild stopped and I don't find any clue in internet and I try somethings and I see need for python but I did not choose any python gems. Anyway, I installed python too but again i see that don't find target file and rebuild stopped. in good old days in lumberyard version 20 with cmd everything was fine....anyway I unistalled o3de for now. If someone care, it's great if someone help me. Maybe I waste my years and I should choose another game engine with real bigger Community. This is log of my last try. I also opened another page in github as error MSB8066. I think this is main problem.                                                            -- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.29.30137.0
-- The CXX compiler identification is MSVC 19.29.30137.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/zlib-1.2.11-rev5-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows
-- Using package C:/O3DE/0.0.0.0/python/runtime/python-3.7.10-rev2-windows
-- Using Python 3.7.10 at C:/O3DE/0.0.0.0/python/runtime/python-3.7.10-rev2-windows/python/python.exe
-- Python: Getting/Checking packages listed in C:/O3DE/0.0.0.0/python/requirements.txt
-- Python: Getting/Checking packages listed in C:/O3DE/0.0.0.0/python/requirements.txt - Already up to date.
-- Python: linking C:/O3DE/0.0.0.0/scripts/o3de into python site-packages...
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/RapidJSON-1.1.0-rev1-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/Lua-5.3.5-rev5-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/RapidXML-1.13-rev1-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/zstd-1.35-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/cityhash-1.1-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/lz4-1.9.3-vcpkg-rev4-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/googletest-1.8.1-rev4-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/googlebenchmark-1.5.0-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/SQLite-3.32.2-rev3-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/OpenSSL-1.1.1b-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/expat-2.1.0-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/md5-2.0-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/tiff-4.2.0.15-rev3-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/AWSNativeSDK-1.7.167-rev4-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/squish-ccr-deb557d-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform
-- Python: linking C:/Users/SARV GAMES/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform/assimp/port/PyAssimp into python site-packages...
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/xxhash-0.7.4-rev1-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/Crashpad-0.8.0-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/pybind11-2.4.3-rev2-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/astc-encoder-3.2-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/ISPCTexComp-36b80aa-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/ilmbase-2.3.0-rev4-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/mcpp-2.7.2_az.2-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/DirectXShaderCompilerDxc-1.6.2104-o3de-rev3-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/SPIRVCross-2021.04.29-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/azslc-1.7.34-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/d3dx12-headers-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/libpng-1.6.37-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/freetype-2.10.4.16-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/pyside2-qt-5.15.1-rev2-windows
-- Python: linking C:/Users/SARV GAMES/.o3de/3rdParty/packages/pyside2-qt-5.15.1-rev2-windows/pyside2 into python site-packages...
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/AWSGameLiftServerSDK-3.4.1-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows
-- Found OpenGL: opengl32   
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/civetweb-1.8-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/libsamplerate-0.2.1-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/NvCloth-v1.1.6-4-gd243404-pr58-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/poly2tri-7f0487a-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/v-hacd-2.3-1a49edf-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/mikkelsen-1.0.0.4-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/OpenMesh-8.1-rev3-windows
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/SARV GAMES/O3DE/Projects/NewProject/build/windows
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System

  Building Custom Rule C:/Users/SARV GAMES/O3DE/Projects/NewProject/Code/CMakeLists.txt

  unity_0_cxx.cxx

  NewProject.Static.vcxproj -> C:\Users\SARV GAMES\O3DE\Projects\NewProject\build\windows\lib\profile\NewProject.Static.lib

  Copying NewProject runtime dependencies to output...

  CMake Error at C:/Users/SARV GAMES/O3DE/Projects/NewProject/build/windows/runtime_dependencies/profile/NewProject.cmake:34 (file):

    file problem touching file: C:/Users/SARV

  

  

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\SARV GAMES\O3DE\Projects\NewProject\build\windows\CMakeFiles\91c4d59051c464745e1eff34ee31f20f\NewProject.stamp.rule' exited with code 1. [C:\Users\SARV GAMES\O3DE\Projects\NewProject\build\windows\o3de\NewProject-3f65cd6b\Code\NewProject.vcxproj]

**Comment by AMZN-AlexOteiza** [comment]
Hi @watchmax3, do you have any logs of what went wrong? Also keep in mind that compilation first time takes a very long time as its a big codebase.

**Comment by watchmax3** [comment]
> Hi @watchmax3, do you have any logs of what went wrong? Also keep in mind that compilation first time takes a very long time as its a big codebase.
>-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.29.30137.0
-- The CXX compiler identification is MSVC 19.29.30137.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/zlib-1.2.11-rev5-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows
-- Using package C:/O3DE/0.0.0.0/python/runtime/python-3.7.10-rev2-windows
-- Using Python 3.7.10 at C:/O3DE/0.0.0.0/python/runtime/python-3.7.10-rev2-windows/python/python.exe
-- Python: Getting/Checking packages listed in C:/O3DE/0.0.0.0/python/requirements.txt
-- Python: Getting/Checking packages listed in C:/O3DE/0.0.0.0/python/requirements.txt - Already up to date.
-- Python: linking C:/O3DE/0.0.0.0/scripts/o3de into python site-packages...
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/RapidJSON-1.1.0-rev1-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/Lua-5.3.5-rev5-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/RapidXML-1.13-rev1-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/zstd-1.35-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/cityhash-1.1-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/lz4-1.9.3-vcpkg-rev4-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/googletest-1.8.1-rev4-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/googlebenchmark-1.5.0-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/SQLite-3.32.2-rev3-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/OpenSSL-1.1.1b-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/expat-2.1.0-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/md5-2.0-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/tiff-4.2.0.15-rev3-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/AWSNativeSDK-1.7.167-rev4-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/squish-ccr-deb557d-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform
-- Python: linking C:/Users/SARV GAMES/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform/assimp/port/PyAssimp into python site-packages...
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/xxhash-0.7.4-rev1-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/Crashpad-0.8.0-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/pybind11-2.4.3-rev2-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/astc-encoder-3.2-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/ISPCTexComp-36b80aa-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/ilmbase-2.3.0-rev4-multiplatform
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/mcpp-2.7.2_az.2-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/DirectXShaderCompilerDxc-1.6.2104-o3de-rev3-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/SPIRVCross-2021.04.29-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/azslc-1.7.34-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/d3dx12-headers-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/libpng-1.6.37-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/freetype-2.10.4.16-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/pyside2-qt-5.15.1-rev2-windows
-- Python: linking C:/Users/SARV GAMES/.o3de/3rdParty/packages/pyside2-qt-5.15.1-rev2-windows/pyside2 into python site-packages...
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/AWSGameLiftServerSDK-3.4.1-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows
-- Found OpenGL: opengl32   
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/civetweb-1.8-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/libsamplerate-0.2.1-rev2-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/NvCloth-v1.1.6-4-gd243404-pr58-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/poly2tri-7f0487a-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/v-hacd-2.3-1a49edf-rev1-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/mikkelsen-1.0.0.4-windows
-- Using package C:/Users/SARV GAMES/.o3de/3rdParty/packages/OpenMesh-8.1-rev3-windows
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/SARV GAMES/O3DE/Projects/NewProject/build/windows
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



  Checking Build System

  Building Custom Rule C:/Users/SARV GAMES/O3DE/Projects/NewProject/Code/CMakeLists.txt

  unity_0_cxx.cxx

  NewProject.Static.vcxproj -> C:\Users\SARV GAMES\O3DE\Projects\NewProject\build\windows\lib\profile\NewProject.Static.lib

  Copying NewProject runtime dependencies to output...

  CMake Error at C:/Users/SARV GAMES/O3DE/Projects/NewProject/build/windows/runtime_dependencies/profile/NewProject.cmake:34 (file):

    file problem touching file: C:/Users/SARV

  

  

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\SARV GAMES\O3DE\Projects\NewProject\build\windows\CMakeFiles\91c4d59051c464745e1eff34ee31f20f\NewProject.stamp.rule' exited with code 1. [C:\Users\SARV GAMES\O3DE\Projects\NewProject\build\windows\o3de\NewProject-3f65cd6b\Code\NewProject.vcxproj]

**Comment by watchmax3** [comment]
> Hi @watchmax3, do you have any logs of what went wrong? Also keep in mind that compilation first time takes a very long time as its a big codebase.

> hi. Thanks for care and answering. I think main problem is error MSB8066

**Comment by AMZN-AlexOteiza** [comment]
@watchmax3 
From the logs It seems that the problem is in: `file problem touching file: C:/Users/SARV`
the folder seems to be "C:/Users/SARV GAMES/". My guess it that O3DE is not playing well with spaces in your directory.

Can you try to use a username and directory that doesn't have any spaces in the path?

**Comment by watchmax3** [comment]
> @watchmax3 
> From the logs It seems that the problem is in: `file problem touching file: C:/Users/SARV`
> the folder seems to be "C:/Users/SARV GAMES/". My guess it that O3DE is not playing well with spaces in your directory.
> 
> Can you try to use a username and directory that doesn't have any spaces in the path?

> thank u ❤️. I change directories of folders of engine and problem solved and I finally built a project.
