### ISSUE TITLE
[Animation] Footplant IK Feature, the characters shake very badly when going up and down the stairs

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#6363]
**Describe the bug**
 Footplant IK Feature, the characters shake very badly when going up and down the stairs

**Steps to reproduce**
1. Create a new level, drag the stair model onto the ground, and add the PhysX Collider component to the ground and stairs to ensure that the stairs and the ground have physical collisions
2. Drag in a prefab that can control the movement of characters and set up FootIK
3. Run the game and control the characters to go up and down the stairs

**Expected behavior**
Characters do not shake when going up and down the stairs

**Actual behavior**
The character jitters up and down the stairs very badly

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development.

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Gold 6234]
- GPU [NVidia RTX 5000]
- Memory [e.g. 128GB]

**Additional context**

**Comment by lsemp3d** [comment]
@FuzzyCarterAWS are you able to reproduce this and add more details?

**Comment by FuzzyCarterAWS** [comment]
I've been unable to repro. I've sync'd with multiple sig/content team members and have determined that we need more info and access to the assets used to replicate this issue.

Marking as needs more info.

@sysuNie , could you please provide more info and provide any assets that can assist us in replicating this issue?

**Comment by monroegm** [comment]
@sysuNie Please reopen if you are able to provide more information. Thanks!
