### ISSUE TITLE
Bug Report - LuaIDE using Edit > Comment Selected Block is buggy

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#6364]
When using the LuaIDE and selecting a block of code, then using comment selected block often leads to incorrect behavior, such as duplicated lines, and not correctly commenting out lines

**Comment by pollend** [comment]
ref: https://github.com/o3de/o3de/pull/6210

**Comment by guillaume-haerinck** [comment]
fixed by https://github.com/o3de/o3de/pull/6210
