### ISSUE TITLE
New project cannot directly connect to Asset Processor that has been opened

### ISSUE THREAD

**Issue by dnqbob** [o3de/o3de#6400]
**Describe the bug**

![bug1](https://user-images.githubusercontent.com/13763394/145941826-1a688934-a0eb-4ad2-9445-2f288a3542c7.PNG)

**Steps to reproduce**
**Updated**
1. Change Project Path in o3de_manifest.json to another path (for storage huge project files)
2. Create & Open a project first
3. Create another new project 
4. without closing the Asset Processor, try "Open Editor" on new project

**On Branch and commit**
Happens on branch stabilization/2111RTE commit a2bb968

**Desktop/Device:**
Windows 10 x64
GeForce RTX 2070

**Comment by dnqbob** [comment]
error log
[error.log](https://github.com/o3de/o3de/files/7709804/error.log)

**Comment by dnqbob** [comment]
OK in today's test, I found actually if I close the Asset Processor before open the project, the project can open normally (it will open and connect to Asset Processor without the crash before)

**Comment by dnqbob** [comment]
OK in today's test, I found actually if I close the Asset Processor before open the project, the project can open normally (it will open and connect to Asset Processor without the crash before)

**Comment by amzn-pratikpa** [comment]
During triage, it was mentioned that a lot of users are running into this problem. It seems like the workflow needs to be documented and we need a plan to get the asset processor to gracefully handle switching projects OR be able to handle multiple projects by acting like a coordinator

**Comment by greerdv** [comment]
The default behaviour now is for the asset processor to close when the editor is closed, so it should be harder to encounter this behaviour.

**Comment by amznestebanpapp** [comment]
@dnqbob Can you get latest and try to reproduce? There was a change recently that ties the lifetime of the asset processor to the editor, which would close it when the Editor for the first project is closed and open it again when the new project is opened.
Thanks

**Comment by dnqbob** [comment]
Fixed in development but not in stabilization/2111RTE
