### ISSUE TITLE
Atom Sample Viewer project fails building

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6409]
**Describe the bug**
Building the Atom Sample Viewer project following the instructions (https://o3de.org/docs/atom-guide/setup-atom-projects/) fails with numerous errors being listed in the Visual Studio.

Attempting to build the project by adding it to the Project Manager has also failed but without a clear error.

Please refer to the attached Visual Studio error list and output for more information.

**Prerequisites**
- O3DE is installed.

**Steps to reproduce**

1. Clone the Atom Sample Viewer project's repo:
`git clone https://github.com/o3de/o3de-atom-sampleviewer.git C:\AtomSampleViewer`
2. Update the local project repo:
```
cd C:\AtomSampleViewer
git pull origin main
```
3. Generate CMake project:
`cmake -B "C:\AtomSampleViewer\build" -S "C:\AtomSampleViewer" -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\o3de-packages`
4. Open the solution file AtomSampleViewer.sln in Visual Studio.
5. In the Solution Explorer panel, navigate to the project _AtomSampleViewer/Standalone/AtomSampleViewerStandalone_. Right-click it and choose Build.

**Expected behavior**
The Atom Sample Viewer builds successfully.

**Actual behavior**
The Atom Sample Viewer fails building.

**Screenshot**
![ASV_ErrorListVS](https://user-images.githubusercontent.com/86953659/146018211-7ccfcd7c-3d1f-490b-acdc-0d6c933c3265.png)

**Found in Branch**
Stabilization/2111RTE (a2bb968)
Atom Sample Viewer: Development (4798752)

**Desktop/Device**
Device: PC
OS: Windows
Version: 10
CPU: AMD Ryzen 5 3600
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 16GB

**Additional context**
[ASV_OutputVS.txt](https://github.com/o3de/o3de/files/7712395/ASV_OutputVS.txt)

**Comment by rgba16f** [comment]
AtomSampleViewer needs to be on it's Stabilization/2111RTE branch to build with o3de Stabilization/2111RTE.

**Comment by wintermute-motherbrain** [comment]
ASV does not have an RTE branch.  You need to use the Stabilization branch.

**Comment by LB-KacperKapusta** [comment]
It has been verified that the Atom Sample Viewer builds successfully using stabilization/2110 (c2c170b)
branch as mentioned in the comment. The issue can be closed.

**Comment by AMZN-Dk** [comment]
Closing this based on the comment above.
