### ISSUE TITLE
Editor freezes after adding enhancedPBR material to entity

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#6447]
**Describe the bug**
This issue occurs only on one machine with i5-9600k processor. Assigning an enhancedPBR material to the material component freezes the Editor indefinitely. It does not occur with other material types.

Please note that no crash logs are created, even when the Visual Studio debugger is attached.

**Steps to reproduce**
1. Create a material with the enhancedPBR type selected.
2. Create an entity.
3. Add a Mesh component and a Material component to it.
3. Assign the enhancedPBR material to the Material component.

**Expected behavior**
The material is assigned without issues.

**Actual behavior**
The Editor freezes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/146384860-cfb1c782-18ce-42dd-b1ff-c603f7a1e133.mp4

**Found in Branch**
Stabilization/2111RTE https://github.com/o3de/o3de/commit/fb36145e2e1f34574948233aa65eaa97f20e6e67

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU Intel I5-9600k
GPU RTX 2060
Memory 16GB

**Comment by monroegm** [comment]
Rerouting to SIG-Graphics-Audio for triage since this is related to meshes and materials

**Comment by gadams3** [comment]
Unable to reproduce in point release 23 .10 .1
