### ISSUE TITLE
Script Canvas node shrinks on mouseover

### ISSUE THREAD

**Issue by evanchia-ly-sdets** [o3de/o3de#6459]
When mousing over certain nodes in script canvas, the node will temporarily shrink causing a flickering sensation. The bug does not occur on all node types, but seems to be larger nodes.

1. Open the Editor
2. Open Script Canvas and create a new script
3. Place larger nodes into the script
4. Mouse over the nodes

**Expected behavior**
The nodes do not shrink

**Actual behavior**
The nodes temporarily shrink

https://user-images.githubusercontent.com/80914607/146440908-8cf8568c-8e65-4181-99d1-8416deebddbb.mp4

**Found in Branch**
Used installer for O3DE 21.11

**Comment by monroegm** [comment]
@lsemp3d Possible duplicate

**Comment by lsemp3d** [comment]
duplicate of #2457
