### ISSUE TITLE
Script Canvas asset processing crash in AP

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#6464]
**Describe the bug**
Script Canvas with AZ::Event logic fails to get processed by AP.

**Steps to reproduce**
Created a script canvas with AZ::Event assignment and use.

**Expected behavior**
A script canvas asset can be processed in AP.

**Actual behavior**
AP errors on the sc asset.
Script Canvas editor crashes when trying to modify the asset to attempt to fix it.

**Assets required**

[path_to_entity_VM - Copy.lua.txt](https://github.com/o3de/o3de/files/7731010/path_to_entity_VM.-.Copy.lua.txt)

[path_to_entity - Copy.scriptcanvas.txt](https://github.com/o3de/o3de/files/7731012/path_to_entity.-.Copy.scriptcanvas.txt)

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/5432499/146463737-44305078-1e35-4732-a76b-ffcbd3b01fad.png)

**Found in Branch**
21.11 Installer

**Comment by carlitosan** [comment]
should be fixed by: https://github.com/o3de/o3de/pull/6625
