### ISSUE TITLE
Moving cursor while holding any mouse button repeatedly expands and collapses tree views

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#6475]
**Describe the bug**
Holding any mouse button while moving the cursor expands and collapses the tree view in the Entity Outliner.

**Steps to reproduce**
1. Open any level.
2. Navigate to the Entity Outliner.
3. Put the cursor over any of the collapse/expand buttons.
4. Hold any mouse button and move the cursor over the button.
5. Observe the tree expanding and collapsing.

**Expected behavior**
Moving the mouse while holding any button does not activate the collapse/expand buttons in the Entity Outliner.

**Actual behavior**
Moving the mouse while holding any button collapses and expands tree views in the Entity Outliner.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/146552033-fe81f2bf-1143-47e4-80cb-4fd6b32fba04.mp4

**Found in Branch**
stabilization/2111RTE

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Ryzen 3600
 - GPU RTX 2060 SUPER
 - Memory 16GB

**Comment by AMZN-daimini** [comment]
This was recently fixed https://github.com/o3de/o3de/pull/7559
