### ISSUE TITLE
[macOS] Editor freezes upon opening a level on a MacBook Pro 2020

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6476]
**Describe the bug**
Opening a level from AtomTest project on MacBook Pro 2020 (Intel Core i5 / Intel Iris Plus Graphics) causes the Editor to become not responsive. The same issue occurred when creating a new level and opening an already existing one (e.g. MeshTest).

Please note that similar behavior has been observed when running AutomatedTesting on the same machine described in [this comment](https://github.com/o3de/o3de/issues/6209#issuecomment-992567214). 

Please refer to the attached video, Editor.log and ProblemReportForEditor.log generated during 'Force Quit' for more information.

**Prerequisites:**

- O3DE python installed and the source engine registered.
- Asset Processor and Editor have been built inside the AtomTest project root.
- Assets were processed in Asset Processor.

**Steps to reproduce**
1. Launch the Editor.
2. Create a new level or open an already existing one.

**Expected behavior**
Level is opened and the Editor is functional.

**Actual behavior**
The Editor becomes not responding upon opening a level.

**Video**

https://user-images.githubusercontent.com/86953659/146550741-5c4c31b2-dd2a-436e-8824-8850c31068fe.mov

**Found in Branch**
Stabilization/2111RTE (d7dc257)
AtomTest: Development (d14f88e)

**Desktop/Device:**
Device: MacBook Pro
OS: macOS
Version: Big Sur 11.3.1
CPU: Intel Core i5 2.0GHz Quad-Core
GPU: Intel Iris Plus Graphics 1536 MB
Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/7735382/Editor.log)
[ProblemReportForEditor.log](https://github.com/o3de/o3de/files/7735381/ProblemReportForEditor.log)

**Comment by LB-KacperKapusta** [comment]
While verifying the fix for the #6908 I unfortunately still encounter this issue. I reported it with Critical priority but after some reconsideration, as it effectively blocks all Editor functionality on the mentioned macOS machine, I would move it to Blocker if it is alright with you. The Editor becoming unresponsive has been confirmed for AutomatedTesting, AtomSampleViewer and newly created projects on MacBook Pro 2020 (Intel Core i5 / Intel Iris Plus Graphics).
I'm attaching the video and logs showing the state of the Editor as of Development (76ff7ae).


https://user-images.githubusercontent.com/86953659/149780782-d03ea567-d409-4958-89df-8e136b3bb216.mov

[Editor.log](https://github.com/o3de/o3de/files/7882261/Editor.log)
[ProblemReportForEditor.log](https://github.com/o3de/o3de/files/7882284/ProblemReportForEditor.log)

**Comment by forhalle** [comment]
SIG - Can you please re-prioritize given that Mac is an experimental platform?

**Comment by LB-KacperKapusta** [comment]
As of Development ([d9efce5](https://github.com/o3de/o3de/commit/d9efce5613fbea2df9eaf984e0bc979e29d2e508)), the Editor crashes immediately after the launch even before the previously encountered freeze happened on the described machine: MacBook Pro 2020 (Big Sur 11.3.2, CPU: Intel Core i5 2.0GHz Quad-Core, GPU: Intel Iris Plus Graphics 1536 MB, Memory 16GB).

https://user-images.githubusercontent.com/86953659/212349964-43194ce0-d905-433c-b86c-ff2ade6fe3c6.mov

Please refer to the attached logs for more information:
[ProblemReportForEditor.txt](https://github.com/o3de/o3de/files/10412605/ProblemReportForEditor.txt)
[OutputFromXcode.txt](https://github.com/o3de/o3de/files/10412607/OutputFromXcode.txt)

Please note that on the same build, the following machine runs the Editor without the described issue: Macbook Pro 2019 (Big Sur 11.6.1, CPU: Intel i9, GPU: AMD Radeon Pro 5500M 4 GB, Memory: 16GB).
