### ISSUE TITLE
MouseMove under AzToolsFrameworkHelper maps cursor to global twice

### ISSUE THREAD

**Issue by pollend** [o3de/o3de#6481]
`AzToolsFrameTestHelper::MouseMove` does not work correctly since the position of the cursor ends up mapping to global twice. `QTest::mouseMove` expects the position to be local to the widget not a global cursor position. There is a patched version of this method in this PR: https://github.com/o3de/o3de/pull/5155

`mapToGlobal` is getting called twice once for `nextPosition` and again with `QTest::mouseMove`

The relevant qt code related to `QTest::mouseMove`: https://code.woboq.org/qt5/qtbase/src/testlib/qtestmouse.h.html#182

```
 auto mouseMoveFix = [](QWidget* wid, QPoint globalPos, QPoint deltaPos)
        {
            QPoint globalPosition = globalPos + deltaPos;
            QPoint localPosition = wid->mapFromGlobal(globalPosition);
            QTest::mouseMove(wid, localPosition);
            QMouseEvent mouseMoveEvent(QEvent::MouseMove, localPosition, globalPosition, Qt::NoButton, Qt::NoButton, Qt::NoModifier);
            QApplication::sendEvent(wid, &mouseMoveEvent);
        };
```

_Originally posted by @pollend in https://github.com/o3de/o3de/pull/5155#discussion_r771130614_

**Comment by hultonha** [comment]
Would you be able to add a full snippet with the code that is incorrect please? If you fix it do any existing tests fail that have incorrect expectations?

**Comment by pollend** [comment]
> Would you be able to add a full snippet with the code that is incorrect please? If you fix it do any existing tests fail that have incorrect expectations?

I think the existing test work because the widget is placed at (0,0) so the global and local positions are the same.

**Comment by hultonha** [comment]
> > Would you be able to add a full snippet with the code that is incorrect please? If you fix it do any existing tests fail that have incorrect expectations?
> 
> I think the existing test work because the widget is placed at (0,0) so the global and local positions are the same.

Ah okay interesting - with the fix what would be awesome is making a test that fails because of the incorrect assumption (so ensure the widget is not at (0,0)) and then with the fix (https://github.com/o3de/o3de/pull/6497) we can then see it pass. Good catch and apologies for the bug, totally my bad.

**Comment by pollend** [comment]
> I think leaving #6497 as a draft makes sense as it's now a blend of this PR, it'll be easier to review when these changes are in.
> 
> It would be great to open a completely new PR without any of these changes and have it just include the fix for MouseMove (+ a test) we can get that in first then and not have to add the workaround lambda that's in this PR.

already have a separate PR: https://github.com/o3de/o3de/pull/6493. I will write a test to validate the behavior.

**Comment by hultonha** [comment]
Fixed by https://github.com/o3de/o3de/pull/6493
