### ISSUE TITLE
Transparency doesn't work for image components in UI

### ISSUE THREAD

**Issue by NiklasHenricson** [o3de/o3de#6492]
**Describe the bug**
The transparency is not working for PNG, TIFF images in UI editor and subsequently when you enter game mode to test your UI or UI Editor's preview mode. It shows always with a solid background.

**Steps to reproduce**
1. Create a transparent image with a shape in it (Pass)
2. Save it in your game project folder structure for the asset processor to process it (Pass)
3. Open UI Editor (Pass)
4. Create a new empty entity (Pass)
5. Add a new image component (Pass)
6. Browse the transparent image in "Pick StramingImage" (Pass)
7. View the image on the canvas (Failed)

<img src="https://navaria-online.com/assets/images/Transparency1.png">
<img src="https://navaria-online.com/assets/images/Transparency2.png">
<img src="https://navaria-online.com/assets/images/Transparency3.png">

**Comment by cgalvan** [comment]
This should be fixed by this commit:
https://github.com/o3de/o3de/commit/b640f6d691b97ae608081c9a4dd7cbddb019721a

**Comment by NiklasHenricson** [comment]
> This should be fixed by this commit: [b640f6d](https://github.com/o3de/o3de/commit/b640f6d691b97ae608081c9a4dd7cbddb019721a)

Awesome, thanks for the quick reply!
