### ISSUE TITLE
Build and publish from GUI

### ISSUE THREAD

**Issue by makemefeelgr8** [o3de/o3de#6495]
There's no way to build the project from GUI. I imagine, having a Unity-like publish menu with some settings is a must. Something like this should do:
- Publish...
- - Android
- - Windows
- - Linux

**Comment by monroegm** [comment]
@makemefeelgr8 are you talking about the project manager or the main editor?

**Comment by makemefeelgr8** [comment]
> @makemefeelgr8 are you talking about the project manager or the main editor?

Idk whats the difference between those two. I'm talking about the app where one can create levels. I mean, take a look at any other IDE/game engine on the market. Each of those has gui to build projects.

**Comment by monroegm** [comment]
There is some crossover with sig/platform here

**Comment by rainbj** [comment]
![ResourceIMG0245](https://user-images.githubusercontent.com/82551958/157922919-1bbf250c-c5a1-45bf-a360-bb6686975702.jpg)

Reviewed by Sig-UX-UI Sig. So this appears to be on the right track. we would like to add the dropdown menu but also force the use to go through a wizard that includes the current output settings. This way we can confirm all the content has been completed. Please circle back with any questions

**Comment by yuyihsu** [comment]
Our suggestion is to run the Walk the Engine research on the WF9 Packaging and Deployment process understand the customer pain points and possible solutions. SIG UI-UX will add this ticket to the UX roadmap and we will plan the research work accordingly.

**Comment by AMZN-stankowi** [comment]
Triage: I've removed the asset-pipeline label for now. I think the high level ask here isn't asset pipeline. There may be some features needed in the asset pipeline later, but those should be smaller, tightly scoped tickets.

**Comment by tkothadev** [comment]
We are currently working on the underpinnings of this feature:
https://github.com/o3de/sig-content/issues/123

Although this is CLI based, it will be how we power the UI based interactions. Current trajectory is that we plan on making the build and publish GUI as the "Project Export" workflow, and it'll occur in the Project Manager (since that is currently where all project details are managed).

Once the CLI is implemented we will be taking a further look at UX implementation of this request.

**Comment by makemefeelgr8** [comment]
Hi guys, it's been 2 years, and you still haven't even added the "build" button. It's 2023, not 1993. The age of AI is coming. Imagine having to manually install Android prerequisites, manually edit some cmake files or whatever, manually run commands in console. Man! Even writing this makes me feel tired. And, at the same time, all your competitors had a build button since version 0.001!
I was rather hopeful about trying o3de, but having to go through hell to just make it generate an executable file? There's no way I'm doing that. Good luck getting any new users.
See you in another 2 years. I'm sure you'll add the button by that time... lmao, no you won't.
Seriously, though, who sets these priorities? Like, don't you guys have weekly meetings? Can't someone just escalate this a little? Ask a question: "hey, it's impossible to actually build a project with our engine, how about we spend 2 hours to automate all these 50 build steps"? Guys? Please?
