### ISSUE TITLE
CustomTool Gem Templates contain a broken link

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#6509]
**Describe the bug**
The _CppToolGem_ and _PythonToolGem_ Templates contain a broken link.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Create a new Gem from _PythonToolGem_ Template.
2. Enable the above Gem in the Project.
3. Launch the Editor.
4. Open the example tool provided by the Gem from the _Tools -> Examples_.
5. Click the _UI Development_ link at the bottom of the tool.

**Expected behavior**
The link leads to a correct page.

**Actual behavior**
The link is broken.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/146757509-8b00bf20-d5eb-492c-b2f9-c30e124bf410.mp4

**Found in Branch**
Development (798a847)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by cgalvan** [comment]
Fixed by https://github.com/o3de/o3de/commit/26190a47eb51a5c5ff8694dd5bdaf81bd6152abc

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed in the latest Development (522b935) branch.
