### ISSUE TITLE
Shape components become invisible in Edit-time when made into prefabs

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6511]
**Describe the bug**
If an entity with a Shape component (e.g. Box Shape component) is made into a prefab, its Shape component becomes invisible, unless the Prefab is in Focus mode. It should be noted that the Shape components are visible in the Game Mode if the Game View property is enabled.

**Steps to reproduce**
1. Create an entity.
2. Add a Box Shape component to it.
3. Right-click the created entity and select "Create Prefab..." from the dropdown menu.

**Expected behavior**
The Shape component on the entity remains visible.

**Actual behavior**
The Shape component on the entity becomes invisible.

**Video**

https://user-images.githubusercontent.com/86952082/146782417-8b6b85e3-5666-4503-94f4-f71b0befec69.mp4

**Found in Branch**
Development (798a847)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by AMZN-daimini** [comment]
Fixed by [#8248](https://github.com/o3de/o3de/pull/8248)

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (bc74b3b) build.
