### ISSUE TITLE
Camera control is not functional in Features/Checkerboard sample from Atom Sample Viewer 

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#6520]
**Describe the bug**
The Camera Control in Features/Checkerboard sample is broken.

Please refer to the attached video for more details.

**Prerequisites**
[AtomSampleViewer built ](https://o3de.org/docs/atom-guide/setup-atom-projects/)

**Steps to reproduce**
1. Launch AtomSampleViewerStandalone.exe.
2. Run Samples -> Features/Checkerboard.
3. Attempt to move or zoom in the Camera.

**Expected behavior**
Camera controls are functional.

**Actual behavior**
Camera controls are not functional.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/146902341-0a80cb87-9b81-46c6-b78c-5e685223722a.mp4

**Found in Branch**
O3DE: Development (366a711)
AtomSampleViewer: Development ([15d6365](https://github.com/o3de/o3de-atom-sampleviewer/commit/15d636566b90cfec4fcea486be281768fe0aeaac))

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by monroegm** [comment]
Rerouting to SIG-Graphics-Audio. If you find this to be a more widespread issue with input or camera systems in general, feel free to send it back.

**Comment by VickyAtAZ** [comment]
The fix is submitted in commit https://github.com/o3de/o3de-atom-sampleviewer/commit/430895c9eddfcd6dd2352434c786b5310b9e2de8

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as Fixed in O3DE: Development (f026e54) / AtomSampleViewer: Development (739066e).
