### ISSUE TITLE
Linux: Input Bindings and Script Canvas assets cannot be viewed in engine until it is restarted

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6521]
**Describe the bug**
After creating a new .inputbindings or .scriptcanvas asset it cannot be viewed in engine until it is turned off and on again. It should be noted that this issue was made in order to make https://github.com/o3de/o3de/issues/5956 easier to track.

Used configuration/build instruction set:
```
mkdir $HOME/o3de-packages
python/get_python.sh
cmake -B build/linux -S . -G "Ninja Multi-Config" -DLY_3RDPARTY_PATH=$HOME/o3de-packages
cmake --build build/linux --target Editor --config profile -j <number of parallel build tasks> (on my system cmake --build build/linux --target Editor --config profile -j 6)
scripts/o3de.sh register --this-engine

After that the Project Manager is launched using the o3de executable under /home/o3de/build/linux/bin/profile/.
A new project configured with all gems enabled is created and successfully built via the Project Manager and launched from it.
```

**Steps to reproduce**
1. Configure and build O3DE as per official O3DE Source engine command set and create a new project. (https://o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/ - instruction set can be found in the description as well.).
2. Create an entity and add Script Canvas and Input components to it.
3. Go to Tools > Asset Editor.
4. In the Asset Editor go to File > New > Input Bindings.
5. Add a new child element, name it, add an Event Generator to it, and save it.
6. Go to Tools > Script Canvas.
7. In the Script Canvas go to File > New Script, add a node to it (e.g. On Graph Start), and save it.
8. Look for the created .inputbindings and .scriptcanvas files in the Asset Browser, or attempt to attach them to the Input/Script Canvas components of the entity created in step 2.

**Expected behavior**
Saved .inputbindings and .scriptcanvas should be visible to the user.

**Actual behavior**
Saved .inputbindings and .scriptcanvas are not visible to the user until the Editor is restarted.

**Video**

https://user-images.githubusercontent.com/86952082/146909719-545763a8-232f-400e-a935-7f380d915cee.mp4

**Found in Branch**
Development (366a711)

**Desktop**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by byrcolin** [comment]
Not sure this still exists
