### ISSUE TITLE
Linux: Updating an .fbx asset with a physxmesh causes the Editor to freeze

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6522]
**Describe the bug**
Attempting to update an .fbx asset with a physxmesh results in an Editor freeze. After closing and restarting the Editor, the physxmesh is properly saved, and can be used in e.g. PhysX Collider component. It should be noted that this issue was made in order to make https://github.com/o3de/o3de/issues/5956 easier to track.

Used configuration/build instruction set:
```
mkdir $HOME/o3de-packages
python/get_python.sh
cmake -B build/linux -S . -G "Ninja Multi-Config" -DLY_3RDPARTY_PATH=$HOME/o3de-packages
cmake --build build/linux --target Editor --config profile -j <number of parallel build tasks> (on my system cmake --build build/linux --target Editor --config profile -j 6)
scripts/o3de.sh register --this-engine
After that the Project Manager is launched using the o3de executable under /home/o3de/build/linux/bin/profile/.
A new project configured with all gems enabled is created and successfully built via the Project Manager and launched from it.
```

**Steps to reproduce**
1. Configure and build O3DE as per official O3DE Source engine command set and create a new project. (https://o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/ - instruction set can be found in the description as well.).
2. In the Asset Browser, find an .fbx asset that does not contain a physxmesh (e.g. <root>/Gems/Atom/Tools/MaterialEditor/Assets/MaterialEditor/ViewportModels/Cube.fbx).
3. Right-click the asset and select Edit settings... from the dropdown menu.
4. In the Fbx Settings (PREVIEW) window navigate to the PhysX tab.
5. Click on the Select meshes button next to the Select meshes parameter.
6. In the Select nodes window check the checkbox next to the Select all, and click Select in the bottom-right corner.
7. Click the Update button in the bottom-right corner.

**Expected behavior**
The .fbx assets gets updated with the physxmesh asset.

**Actual behavior**
The Editor freezes indefinitely.

**Video**

https://user-images.githubusercontent.com/86952082/146914654-a77e5085-7137-471a-b692-918cea0d474e.mp4

**Found in Branch**
Development (366a711)

**Desktop**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by hultonha** [comment]
Removing sig-simulation from this issues as this seems more precisely related to a Linux/platform issue.

@LB-ArturZieba could you please retest this when you have a moment as Linux has come a long way since Dec 2021 and this problem may have already been resolved. Thanks!

**Comment by hultonha** [comment]
Great to hear! Thanks @LB-KacperMetelski 👍
