### ISSUE TITLE
Project tiles are not rearranged after deleting a project

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#6523]
**Describe the bug**
Project tiles do not occupy the space left after deleting a project in the Project Manager, leaving blank spaces. Tiles do get rearranged after resizing the window or restarting the Project Manager.

**Steps to reproduce**
1. Open the Project Manager.
2. Create three or more projects.
3. Delete any project in the middle.
4. Observe that the project tiles do not get rearranged.

**Expected behavior**
Tiles get rearranged, leaving no blank spaces.

**Actual behavior**
Rearrangement only happens after restarting the Project Manager or resizing the window.

**Screenshots/Video**
https://user-images.githubusercontent.com/86951905/146920753-7b48f63d-38c4-4ec5-837a-4219a16d01c5.mp4

**Found in Branch**
Development (366a711)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Ryzen 5 3600
 - GPU GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by AMZN-alexpete** [comment]
I've noticed this as well, the projects page should refresh after deleting the project instead of just hiding the deleted project and leaving a gap.

**Comment by AMZN-nggieber** [comment]
Oh I saw this once but wasn't able to repro it again. Looks like this is a good repro so we will look into fixing this!

**Comment by LB-RostyslavGavryliuk** [comment]
Issue no longer occurs on Development (7581967).
