### ISSUE TITLE
Animation Editor: Actor Bounding Boxes show only one box in Atom Render Window

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#6525]
**Describe the bug**
Enabling the Actor Bounding Boxes option in the Atom Render Window shows only one bounding box. A similar option can be found for the OpenGL Render Window, but enabling it shows two bounding boxes.

Please refer to the attached screenshot for more information.

**Steps to reproduce**

1. Open the Animation Editor (Tools -> Animation Editor).
2. Open an actor (e.g. Jack).
3. Enable the Atom Render Window.
4. In the Atom Render Window choose View (eye icon) and enable Actor Bounding Boxes.
5. Enable Actor Bounding Boxes for the OpenGL Window

**Expected behavior**
Both Actor Bounding Boxes are visible in the Atom render Window.

**Actual behavior**
Only one Actor Bounding Box is visible in the Atom render Window.

**Screenshots/Video**
![actor_bounding_boxes](https://user-images.githubusercontent.com/86952318/146936054-ed579e19-1c0b-48c6-9def-afa673ffe143.jpg)

**Found in Branch**
Development (798a847)

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

**Comment by amzn-rhhong** [comment]
https://github.com/o3de/o3de/pull/6685 https://github.com/o3de/o3de/commit/55fb63da48bae2efeb76478480b09e0e1b8d70e3 this should fixed the problem
Please check and verify @LB-MichalRodzos

**Comment by LB-MichalRodzos** [comment]
Issue does not occur. Verified in Development (f09055a) build using repro steps included in the description.
