### ISSUE TITLE
Entity Outliner becomes empty after a child entity with a Gradient component is deleted

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#6526]
**Describe the bug**
The Entity Outliner shows no elements after the User deletes an entity that contains a Landscape Canvas component. The Landscape Canvas has to contain Shape and Gradient elements.

The entities in the Entity Outliner are **not** deleted, just invisible.

**Workaround:** Use Select all for Entity Outliner.

**Steps to reproduce**
1. Create an entity with the Landscape Canvas component.
2. Edit the Landscape Canvas in the Landscape Editor.
3. Add Shape and Gradient elements (as seen in the video).
4. Return to the Viewport.
5. Select the Landscape Canvas entity in the Entity Outliner.
6. Delete the entity.

**Expected behavior**
The entity is deleted.

**Actual behavior**
The entity is deleted and the Entity Outliner is emptied.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/146938016-290f91b2-3ec3-46de-8385-9e0c1d205f89.mp4

**Found in Branch**
Development (366a711)

**Desktop/Device (please complete the following information):**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA RTX 2060 SUPER
Memory 16GB

**Comment by jckand-amzn** [comment]
This appears to be due to the gradient components on child entities. Reproduced by simply:

1. Creating a new entity
2. Create a child entity, and add any gradient component to it
3. Delete the parent entity

**Comment by cgalvan** [comment]
Can no longer reproduce this issue in commit [1905697](https://github.com/o3de/o3de/commit/19056977eb1a0f8260afe2c4c733e9bb90337ec6)

**Comment by LB-JakubSkoczylas** [comment]
This issue no longer occurs. Verified this on build Stabilization/2210 (731cff1).
