### ISSUE TITLE
Saving a new graph in Script Canvas does not cause the save location prompt to pop up

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6538]
**Describe the bug**
In the previous versions, when a new Script Canvas file was saved for the first time using the File > Save action (Ctrl + S), a prompt allowing the user to choose a save location and the .scriptcanvas file's name. Currently this does not happen and the graph is saved directly to the default Script Canvas graph folder (e.g. C:\Users\<user>\O3DE\Projects\<project name>\scriptcanvas\) under its placeholder name (e.g. Untitled-1). This happens regardless of whether the graph is empty, or contains some nodes.

**Steps to reproduce**
1. Go to Tools > Script Canvas.
2. (If a graph is not present) In the Script Canvas go to File > New Script.
3. Go to File > Save.

**Expected behavior**
A prompt allowing the user to select the file save location and its name appears.

**Actual behavior**
The graph is saved to the default location with its placeholder name.

**Video**

https://user-images.githubusercontent.com/86952082/147076871-15330197-c6f8-44bf-ad88-1d3303ba3ec8.mp4

**Found in Branch**
Development (436709b)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by carlitosan** [comment]
Fixed with: https://github.com/o3de/o3de/pull/6490

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (7581967) build.
