### ISSUE TITLE
ScriptCanvas: Editor crashes after slot corruption

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#6540]
Performing any standard action (undo/redo, copy/paste, add/remove nodes) leads to slot corruption in the nodes. Pasted nodes are disconnected and cannot be reconnected. Undoing the last action or deleting the corrupted node results in a crash.

Please note that the issue was observed when working on a large script only.

Visual Studio call stack attached below.
[callstack.txt](https://github.com/o3de/o3de/files/7762348/callstack.txt)

**Steps to reproduce**
1. Open the attached script.
2. Modify the script by adding, pasting, duplicating and deleting nodes.

**Expected behavior**
The Script Canvas tool remains stable and the node's slots work correctly.

**Actual behavior**
Node's slots become corrupted, which leads to a crash.

**Assets required**
[P2.zip](https://github.com/o3de/o3de/files/7762150/P2.zip)

**Screenshots/Video**

![exception](https://user-images.githubusercontent.com/86952009/147081958-9f8eeb9e-1b31-4ddd-b975-82abec7b01e6.JPG)

https://user-images.githubusercontent.com/86952009/147081971-78885644-2c41-46ab-adf8-193ee07d0742.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/436709b1a8a62bcfcd10202ef2f09942c43ef8f0)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel I5-9600k
- GPU RTX 2060
- Memory 16GB

**Additional context**
[dump.zip](https://github.com/o3de/o3de/files/7762163/dump.zip)

**Comment by carlitosan** [comment]
https://github.com/o3de/o3de/pull/6734

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in Development.
