### ISSUE TITLE
Animation Editor: Editor crash after deleting actor instance when Atom Render Window is enabled

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#6542]
**Describe the bug**
Removing an actor instance crashes the Editor. This issue occurs only when the Atom Render Window is enabled, and user is removing the selected instance. Removing all instances via the _Remove all_ option works as expected. Please note that only removing the first actor instance crashes the Editor every time. For other instances, the crash may not occur.

Please refer to attached video, logs and .dmp file for more information.

**Steps to reproduce**

1. Open the Animation Editor (Tools -> Animation Editor).
2. Enable the Atom Render Window.
3. Open an actor (e.g. Jack).
4. Go to the Actor Manager tab.
5. Click RMB on one of the _Instances_ and select _Remove selected_.

**Expected behavior**
The actor's instance is deleted.

**Actual behavior**
The Editor crashes.

```
Call Stack Trace:
25) 00007FF9C1DCB7F7 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FF9C45951B0 (ntdll) : memset
23) 00007FF9C457C766 (ntdll) : _C_specific_handler
22) 00007FF9C45920CF (ntdll) : _chkstk
21) 00007FF9C4541454 (ntdll) : RtlRaiseException
20) 00007FF9C4590BFE (ntdll) : KiUserExceptionDispatcher
19) C:\Builds\o3de\Gems\EMotionFX\Code\EMotionFX\Source\MeshDeformerStack.cpp (63) : EMotionFX::MeshDeformerStack::Update
18) C:\Builds\o3de\Gems\EMotionFX\Code\EMotionFX\Source\ActorInstance.cpp (397) : EMotionFX::ActorInstance::UpdateMeshDeformers
17) C:\Builds\o3de\Gems\AtomLyIntegration\EMotionFXAtom\Code\Source\AtomActorDebugDraw.cpp (57) : AZ::Render::AtomActorDebugDraw::DebugDraw
16) C:\Builds\o3de\Gems\EMotionFX\Code\Source\Integration\Components\ActorComponent.cpp (581) : EMotionFX::Integration::ActorComponent::OnTick
15) C:\Builds\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1360) : AZ::Internal::EBusContainer<AZ::TickEvents,AZ::TickEvents,0,2>::Dispatcher<AZ::EBus<AZ::TickEvents,AZ::TickEvents> >::Broadcast<void (__cdecl AZ::TickEvents::*)(float,AZ::S
14) C:\Builds\o3de\Code\Framework\AzCore\AzCore\Component\ComponentApplication.cpp (1426) : AZ::ComponentApplication::Tick
13) C:\Builds\o3de\Code\Editor\GameEngine.cpp (834) : CGameEngine::Update
12) C:\Builds\o3de\Code\Editor\CryEdit.cpp (2351) : CCryEditApp::IdleProcessing
11) C:\Builds\o3de\Code\Editor\CryEdit.cpp (2259) : CCryEditApp::OnIdle
10) 00007FF96C810DB9 (Qt5Core) : QObject::qt_static_metacall
 9) 00007FF96C81FA8D (Qt5Core) : QTimer::timerEvent
 8) 00007FF96C81854D (Qt5Core) : QObject::event
 7) 00007FF96C0E49B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
 6) 00007FF96C0E3A33 (Qt5Widgets) : QApplication::notify
 5) 00007FF96C7F1B4A (Qt5Core) : QCoreApplication::notifyInternal2
 4) 00007FF96C83C439 (Qt5Core) : QEventDispatcherWin32Private::sendTimerEvent
 3) 00007FF96C83A869 (Qt5Core) : QEventDispatcherWin32::event
 2) 00007FF96C0E49B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
 1) 00007FF96C0E3A33 (Qt5Widgets) : QApplication::notify
```

**Screenshots/Video**

https://user-images.githubusercontent.com/86952318/147110982-72cf01a7-4e14-4a44-b4fb-c179650f002c.mp4

**Found in Branch**
Development (436709b)

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

**Additional context:**
[Editor.log](https://github.com/o3de/o3de/files/7763328/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7763329/error.log)
[error.zip](https://github.com/o3de/o3de/files/7763348/error.zip)

**Comment by LB-MichalRodzos** [comment]
I repeated repro steps from the description in the Development (95245e2) build. The issue does not occur anymore.

**Comment by amzn-rhhong** [comment]
Fixed with https://github.com/o3de/o3de/pull/6442
Verified by @LB-MichalRodzos
