### ISSUE TITLE
Editor silently crashes after deleting a Script Canvas node from a node chain in a graph assigned to a component

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6543]
**Describe the bug**
If a Script Canvas graph that is assigned to a Script Canvas component contains a chain of nodes, one of these nodes is removed, and the script is saved, then Editor crashes silently. It should be noted that the reproduction of this issue is similar to https://github.com/o3de/o3de/issues/6540 issue, however the Visual Studio call stacks are different.

**Steps to reproduce**
1. Create an entity and add a Script Canvas component to it.
2. Go to Tools > Script Canvas, and recreate the script shown below under the "Script Canvas graph" title.
3. Save the Script Canvas graph.
4. Attach the script created in step 2 to the entity from step 1.
5. Delete the Delay node from the graph.
6. Save the graph again.

**Expected behavior**
The graph is saved.

**Actual behavior**
The Editor silently crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952082/147106608-45f78ae5-f1ed-4d08-b8e9-bc21cf41f4b6.mp4

Script Canvas graph
![ScriptCanvasGraph](https://user-images.githubusercontent.com/86952082/147107304-13ae1b8e-efea-4493-b25b-1390cf199d61.PNG)

Visual Studio Exception screenshot
![VSException](https://user-images.githubusercontent.com/86952082/147106845-1b7d2530-2596-4615-922b-a1f805e40d2e.PNG)
[VSCallStack.txt](https://github.com/o3de/o3de/files/7763129/VSCallStack.txt)

**Found in Branch**
Development (436709b)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Additional context**
[error.log](https://github.com/o3de/o3de/files/7763121/error.log)
[error.dmp](https://github.com/o3de/o3de/files/7763122/error.zip)

**Comment by carlitosan** [comment]
https://github.com/o3de/o3de/pull/6734

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on Development (f09055a) build. However another silent crash occurs right after attempting to reattach the Delay node on the graph. Please refer to the attached video for more information, and note the Graph Validation warnings printed in the moment the crash described in the issue occured ("The target node with id [(id)] is not a part of this graph, a connection cannot be made"). Should this issue be reopened, or should a new issue be created in order to track the crash shown in the video?

https://user-images.githubusercontent.com/86952082/148919355-3a7fb0eb-d4f9-40ce-aa83-fa0f6355bbcc.mp4
