### ISSUE TITLE
Build fails if the engine is installed in a directory with spaces

### ISSUE THREAD

**Issue by AlexOteiza** [o3de/o3de#6544]
It seems that CMake fails to configure and generate project if the engine is in a directory that contains spaces:
https://github.com/o3de/o3de/issues/6358

Removing spaces in the directory solves the problem but may be good as QOL improvement to find out the cmake scripts that will need to be fixed for this.

**Comment by PavlovTM** [comment]
Push: Also happend on my side

**Comment by amzn-pratikpa** [comment]
@o3de/sig-docs  we should include in the docs that spaces should not be used until this is fixed

**Comment by sptramer** [comment]
@amzn-pratikpa - Does this only affect INSTALL targets, or does it also affect O3DE clone directories or project directories?

**Comment by lumberyard-employee-dm** [comment]
> @amzn-pratikpa - Does this only affect INSTALL targets, or does it also affect O3DE clone directories or project directories?

I believe this would affect the source engine as well.
Since it looks like the issue happens in the runtime dependencies system we use for copying over build artifacts.

**Comment by sptramer** [comment]
What's the over/under on this bug being fixed pretty quickly? We try and avoid documenting bugs on the website - either they're open github issues a user can search for, or should be in known issues for a given release.

**Comment by lumberyard-employee-dm** [comment]
I wouldn't imagine it wouldn't take that long, we just need to be cognizant to check how this issue manifest on non-Windows platforms as well to catch any edge cases on those OS.

**Comment by amznestebanpapp** [comment]
I wouldnt bet this can be fixed quickly, besides the building part, there could be other things in the AP/Editor that also makes paths with spaces unusable.
I am going to give it a try, already seeing some issues with some scripts

**Comment by amznestebanpapp** [comment]
There is likely a lot more broken, this just fixes the reported problem of building

**Comment by lumberyard-employee-dm** [comment]
> There is likely a lot more broken, PR #6757 just fixes the reported problem of building

That is all this issue is about.

If there was an issue with running, that should be put into a new issue.
