### ISSUE TITLE
Script canvas:Time-related nodes are still processed when exiting the game mode, which may cause Editor crash

### ISSUE THREAD

**Issue by Hsuehnj** [o3de/o3de#6564]
**Describe the bug**
Time-related nodes in the Script canvas library are still processed by OnTick when exiting the game mode, after the time trigger conditions in these nodes are met, the execution of subsequent nodes will be triggered. When exiting the game mode, it may cause abnormal data access and cause Editor crash.

**Steps to reproduce**
1. Go to 'Entity Outliner'
2. Create an entity
3. Add Script Canvas compoent, and bind a script (on entity activated-delay 4 seconds-deactive entity-delay 5 seconds-active entity)
4. Run the game then exit game mode
5. See error

**Expected behavior**
There is no error when exiting game mode, and no Editor crash.

**Actual behavior**
There is error when exiting game mode, and Editor crash occasionally,

**Assets required**
see attachemnt

**Screenshots/Video**
see attachment

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
Device: PC,
OS: Windows
Version 10,
CPU Intel xeon
GPU NVidia RTX 5000
Memory 128GB

**Additional context**
![script_entity](https://user-images.githubusercontent.com/41571619/147441129-f1973760-f256-4e20-963f-ff305b069acf.png)
[error.log](https://github.com/o3de/o3de/files/7778691/error.log)

**Comment by Hsuehnj** [comment]
When exiting the game mode, if the script executes the “Delay" node after the "Deactivate game entity" node, when the delay time is reached, because the entity has been deactivated and game mode exit, the "Activate game entity" node cannot find the entity, resulting in the following warning:
<14:56:09> [Warning] (System) - Can't get component 0000027B28F9E9B0 entity ID as it is not attached to an entity yet!
<14:56:09> [Warning] (GameEntityContext) - Entity with id 15336328251241 does not belong to the game context.

Whether it is possible to add the judgment of the game mode in the OnTick function entry of the time-related node, if current is not in game mode, do not continue processing?

**Comment by carlitosan** [comment]
what does variable 1 refer to in this graph?

**Comment by carlitosan** [comment]
I am unable to reproduce this with a nearly exact graph that deactivates and activates another entity in the scene

**Comment by Hsuehnj** [comment]
> what does variable 1 refer to in this graph?

This variable is associated with the entity(ie. self) that binds this script.
