### ISSUE TITLE
Feature Request: Add a node in Script Canvas to translate a cursor position to world translation

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6578]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to have an easy way of implementing casting a cursor in a world. This could be useful in any game using an isometric camera perspective, that also would want to use a mouse as one of its input devices. It should be noted that there already is such a way of casting cursor position to the world in engine - the Translate mode entity gizmo has a yellow cube in the center of it that snaps the entity to a surface that the cursor "points" to (please refer to the video attached in the **Additional context** section).

**Describe the solution you'd like**
Add a Script Canvas node that would return a world translation that the cursor points to, similar to the described gizmo yellow cube.

**Describe alternatives you've considered**
Add a documentation or YouTube tutorial that would show how such setup could be achieved with the current nodes.

**Additional context**

https://user-images.githubusercontent.com/86952082/147556582-13a61735-aa3c-4199-b1eb-157deaf567d7.mp4

**Comment by LB-ArturZieba** [comment]
I belive that this Feature Request can be closed as it was effectively implemented via the https://github.com/o3de/o3de/pull/6903. Screen To World and World To Screen nodes can work as the node I've described in this Feature Request.

**Comment by lsemp3d** [comment]
#6903 indeed adds this feature, closing
