### ISSUE TITLE
The camera angle should not be the same as previously set when switched the game level

### ISSUE THREAD

**Issue by instoneks2018** [o3de/o3de#6584]
**Describe the bug**
In the scene A, set the camera angle to tilt, then enter the current angle of view and switch to the scene B. Unexpectedly, the angle of view is still tilted.

**Steps to reproduce**
1.Open Editor.
2.Select the level of the game scene A to be tested.
3.In scene A, set the camera angle to tilt and enter the current camera angle.
4.Switch to open the level of the game scene B, in this case, the angle of view is still tilted.

**Expected behavior**
The camera angle in scene  B is displayed properly,not tilted.

**Screenshots**
If applicable, add screenshots and/or a video to help explain your problem.
```
1. Open the level of the game as 'default', set the camera angle to tilt,the angle of view is still tilted.
```
![1](https://user-images.githubusercontent.com/45937683/147645956-5405ea1e-e6dc-4377-8125-d9a666c85c26.png)
```
2. Switch to open the level of the game as 'test',the angle of view is still tilted.
```
![2](https://user-images.githubusercontent.com/45937683/147646066-3f962f7b-d28b-45a2-a252-323f8defe7c3.png)

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Intel I7-10700 2.90GHz (16 CPUs)]
- GPU [Intel(R) UHD Graphics 630]
- Memory [32GB]

**Additional context**

**Comment by monroegm** [comment]
@hultonha @AMZN-Igarri FYI
