### ISSUE TITLE
[GNU/LINUX] Ubuntu 21.10 atom render vulkan noise with very bad geometry in meshs

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#6598]
**Describe the bug**
20.04 LTS render everything is fine
21.04 did not check
21.10 atom rendering is very bad due to newer kernel and new distro versions

i'm remember opensuse tumbleweed also a problem with noise with rendering https://github.com/o3de/o3de/issues/4379#issuecomment-944315890

**Screenshots/Video**

![2021-12-30_12-22](https://user-images.githubusercontent.com/17591539/147739852-d351f24d-7ed3-4ca0-b822-2b19427c01fc.png)

https://user-images.githubusercontent.com/17591539/147740841-f3e48f6a-7f01-4c94-ae2c-46bacc7722f5.mp4

**Found in Branch**
21.11 Stable

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 21.10
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 21.2.2]
 - Memory: 16GB

**Comment by Magical10240** [comment]
I think that on April 21 the release of Ubuntu 22.04 LTS will be released state in o3de if nothing has changed and there will be atom noise very bad :)

**Comment by Darkinggq** [comment]
verified fixed (development https://github.com/o3de/o3de/commit/14076b4f932a768e9d12b041ca16a13903ac6be5)
it is no longer appearing noise everything is fine it seems fixed atom rendering
