### ISSUE TITLE
Performing an Undo action after moving a few mesh entities causes the Editor to become unresponsive

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6599]
**Describe the bug**
If an undo action is performed after moving a few entities with a Mesh or Actor components, the component list in the Entity Inspector starts folding and unfolding, while the Editor remains unresponsive. While it is expected for the Editor to lose performance temporarily when performing undo action on bigger changes, this freezing occurs on reverting only 12 mesh entities, and small freezes can be noticed on reverting as little as 6.

**Steps to reproduce**
1. Create an entity and add a Mesh component to it.
2. Assign a Mesh Asset to it (e.g. Cube.fbx).
3. Duplicate the entity until you have 12 of them.
4. Duplicate the 12 entities and move the duplicated ones.
5. Undo the action.

**Expected behavior**
Entity Inspector remains static, the Editor remains responsive.

**Actual behavior**
Entity Inspector folds and unfolds continuously, the Editor eventually freezes for a while.

**Video**

https://user-images.githubusercontent.com/86952082/147740972-66ffaaaa-f11e-470b-8ac0-45e919a8424c.mp4

**Found in Branch**
Development (2f1346c)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by monroegm** [comment]
@LB-ArturZieba If you have time, can you try it with the Entity Inspector closed?

**Comment by LB-ArturZieba** [comment]
I reproduced this issue with the Entity Inspector closed on the Development (f09055a) build, and performing Undo on the entities' movement is very quick. Reproducing the issue with the Entity Inspector opened as in the original issue still results in the same Actual behavior.
