### ISSUE TITLE
Duplicating an entity containing variables with "Initial Value Source" set to "From Component" doubles the variables in Script Canvas component

### ISSUE THREAD

**Issue by LB-PatrykKrajewski** [o3de/o3de#6602]
**Describe the bug**
When a script containing variables with the "Initial Value Source" set to the "From Component" is assigned to the entity and that entity is duplicated, the variables are doubled inside the "Script Canvas" component. The effect is applied to all variables in this particular script. Variables can be doubled infinitely and they are only removed when the whole "Script Canvas" component is deleted.

**Steps to reproduce**
1. Create a new script.
2. Add a few variables.
3. Set their "Initial Value Source" to the "From Component".
4. Save the script and attach it to any entity.
5. Duplicate the enity with previously created script attached.
6. Observe the Variables list in the "Script Canvas" component.

**Expected behavior**
Additional instance of cariables are not showing up in Script Canvas component when the node is duplicated.

**Actual behavior**
Duplicating an entity containing variables with "Initial Value Source" set to "From Component" doubles the variables in the Script Canvas component.

**Screenshots/Video**

https://user-images.githubusercontent.com/88180143/147755153-6c32f836-dd57-4c8b-aa9a-b9d69aa2bd8b.mp4

**Found in Branch**
Development (2f1346c)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600X
- GPU: AMD RX 5700 XT
- Memory: 16 GB

**Comment by carlitosan** [comment]
PR going up momentarily
