### ISSUE TITLE
Attempting to Edit Script Canvas from Entity Outliner context menu crashes the Editor  

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#6615]
**Describe the bug**
Attempting to _Edit Script Canvas_ via the context menu opened by right-clicking an entity in _Entity Outliner_ crashes the Editor.

Please refer to the attached video and editor.log for more details (please note that the error.log and error.dmp files are not generated after this crash).

**Steps to reproduce**
1. Create a new entity.
2. Add the Script Canvas component to the entity.
3. Assign any valid Script Canvas graph to the component.
4. Right click the entity in Entity Outliner.
5. Select _Edit Script Canvas_ -> <attached_script_name>_.

**Expected behavior**
The graph attached to entity opens in Script Canvas tool.

**Actual behavior**
The Editor crashes.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/147938450-b5198a75-65cf-4e83-adeb-36db9e399faf.mp4

**Found in Branch**
Development (4826048)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU AMD Ryzen 5 3600
- GPU Nvidia RTX 2060 Super
- Memory 16GB

**Attachments**
[Editor.log](https://github.com/o3de/o3de/files/7802225/Editor.log)

**Comment by carlitosan** [comment]
Fixed by https://github.com/o3de/o3de/pull/6686
