### ISSUE TITLE
[Planning] Ensure high-level release schedule is published

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#6621]
Ensure the Release SIG determines and publishes a high-level release schedule to all SIGs. 

The Release SIG should work with all SIGs involved in the release to determine the schedule (e.g. sig/release, sig/testing, sit/docs-community, etc.).

This schedule should include, at minimim, the following dates:
- Point Release Branch Creation - The date in which the point release branch is created off of the previous release branch.
- Feature Complete - The date in which all features in the point release, if any, are submitted and verified in the point release branch. 
- Point Release Branch Stabilization - The period in which testing occurs, and blocker / critical bug fixes are made. Bug fixes will be made in the development branch, and cherry picked to the point release branch. 
- Point Release Branch confirmed Stable - The date the Testing SIG confirms the code in the point release branch is stable.
- Release - The date the release will take place.

The Release SIG is responsible for communicating this schedule, and will likely communicate it via. the #sig-release and #sig-all Discord channels.

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by forhalle** [comment]
I reminded @Ulrick28 to communicate out the move of release date to 1/27.

**Comment by Ulrick28** [comment]
- Point Release Branch Creation (11/23 for the point release) - The date in which the point release branch is created off of the previous release branch.
-     Feature Complete (12/17 for the point release) - The date in which all features in the point release, if any, are submitted and verified in the point release branch.
-     Point Release Branch Stabilization (12/18 - 1/8 for the point release) - The period in which testing occurs, and blocker / critical bug fixes are made. Bug fixes will be made in the development branch, and cherry picked to the point release branch.
-     Point Release Branch confirmed Stable (1/8 for the point release) - The date the Testing SIG confirms the code in the point release branch is stable.
-     Release - The date the release will take place. Thursday 1/27/2022 for the 21.11.2 point release.

**Comment by forhalle** [comment]
@Ulrick28  - Can you please confirm you have communicated this out? Would you mind also detailing here how this was communicated (i.e. what channels you used) for the benefit of future RMs reading this ticket?

**Comment by forhalle** [comment]
I see @Ulrick28 communicated this in #sig-all [here](https://discord.com/channels/805939474655346758/821692567355523152/930492884317257798).

**Comment by forhalle** [comment]
@Ulrick28 - My understanding from today's discussion is you plan to also post this schedule in #sig-release. Can you please update this task to Closed once you have completed this?

**Comment by Ulrick28** [comment]
Release communicated in sig-release, sig-all, and the calendar. Closing issue.
