### ISSUE TITLE
[GNU/LINUX] Lua script offline debugging classes reference does not work

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#6623]
**Describe the bug**
Target in Lumberyard(ffffffff) and red debugging offline I can not find out in the classes reference and there is no documentation about the Lua api there we do not know yet

debugging online would be the appearance of classes reference

**Steps to reproduce**

https://user-images.githubusercontent.com/17591539/147982670-cb192707-19d7-49c1-bafa-e1835b793d75.mp4

**Found in Branch**
development: 48260486fb606020f4715f4299e46b26faa0c0cd and 21.11 stable

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 21.10

**Comment by monroegm** [comment]
@monroegm By design

**Comment by Darkinggq** [comment]
Verified fix on stabilization 2310.0, gem enable "remote tools connection" works well
