### ISSUE TITLE
[Pre Release] Confirm release branch is stable

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#6634]
Confirm the Testing SIG has completed all testing requirements, the release branch is stable, and meets the quality bar for what is expected in a release. Also verify all exception requests (i.e. any requests to merge to stabilization post code lock) are merged per the Exception Request Dashboard. Ensure the exact commit id to be used for the merge to main is noted as a comment in this issue.

- Related Task: [#7032]

**Comment by Kadino** [comment]
@AMZN-Dk let's discuss what requirements are owned by sig-testing

**Comment by forhalle** [comment]
Notes from @o3de/sig-testing meeting:

**Comment by forhalle** [comment]
@AMZN-Dk - My understanding is the testing must complete by EOD 1/21 because the pull request for stabilization/2111RTE to main is to be created 1/24.

**Comment by AMZN-Dk** [comment]
These changes have been validated in the stabilization/2111RTE branch, we will be looking to run a regression pass with the installed build once we have installers available.

**Comment by forhalle** [comment]
I am closing this issue, @AMZN-Dk , since there is a separate issue for the installers (#6932). Please contact me if you are concerned with this approach.

**Comment by forhalle** [comment]
@AMZN-Dk - Per our discussion, I'm reopening this issue since we have some new exception requests coming through, which will need to be tested. These requests will be added to [[stabilization/2111RTE - Exception Requests](https://github.com/o3de/o3de/projects/7) shortly. Please be on the lookout.

**Comment by AMZN-Dk** [comment]
Closing this out, we have confirmed the last of the exception fixes, we are ready to go for final installer creation.
