### ISSUE TITLE
Changing the level while the Simulate mode is enabled silently crashes the Editor

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6641]
**Describe the bug**
If a level is changed while the Simulate mode is active, the Editor silently crashes.

**Steps to reproduce**
1. Create a level.
2. Create another level.
3. Enable the Simulate mode (Ctrl + P).
4. Go to File > Open Level...
5. Open the level created in step 1.

**Expected behavior**
The level is changed.

**Actual behavior**
The Editor crashes.

**Video, Editor.log, error.log, and error.dmp**

https://user-images.githubusercontent.com/86952082/148049282-739e515c-ad9d-49de-bc4c-7cc4e5a644fb.mp4

[Editor.log](https://github.com/o3de/o3de/files/7807068/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7807070/error.log)
[error.zip](https://github.com/o3de/o3de/files/7807084/error.zip)

**Found in Branch**
Development (7581967)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (3200c2f) build.
