### ISSUE TITLE
Feature Request: Revert the changes to the right-click dropdown in Entity Outliner

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6656]
**Is your feature request related to a problem? Please describe.**
Currently on a project with Prefabs System enabled, there are only two options available when right-clicking in the Entity Outliner without clicking on an entity: Create entity and Toggle pivot. Up until recently that same menu had some additional options - most notably "Instantiate Prefab..." - which was a bit more intuitive. Currently to instantiate a Prefab in the Entity Outliner, an existing entity or level must be right-clicked for that option. It should be noted that on the same project with the Prefabs System disabled, the old dropdown containing multiple options (such as "Create layer" or "Instantiate slice...") is still present.

**Describe the solution you'd like**
Revert the changes to the right-click dropdown menu when clicking inside the Entity Outliner, but not on an entity.

**Describe alternatives you've considered**
Add an "Instantiate Prefab..." back to the current dropdown.

**Additional context**
Old dropdown Prefabs System enabled:
![OldDropdown](https://user-images.githubusercontent.com/86952082/148063807-ea424214-fd3d-48c4-a2ab-2070d8f54b8b.png)

Current dropdown Prefabs System enabled:
![CurrentPrefabsOn](https://user-images.githubusercontent.com/86952082/148063831-ab4946bc-2c90-45c8-b98e-df8e7cdd0826.png)

Current dropdown Prefabs System disabled:
![CurrentPrefabsOff](https://user-images.githubusercontent.com/86952082/148063856-16ea0188-bfef-4fc4-a477-04b70c36f8bc.png)

**Comment by AMZN-daimini** [comment]
Instantiate Procedural Prefab should follow the same rules as Instantiate Prefab

**Comment by monroegm** [comment]
@AMZN-mnaumov can this be closed?

**Comment by LB-ArturZieba** [comment]
Verified this as implemented on Development (611598c) build on both Windows and Linux. Both the "Instantiate Prefab..." and "Instantiate Procedural Prefab..." options are available in the Entity Outliner's right-click dropdown menu without an entity selected.
