### ISSUE TITLE
Linux: Windows clients are immediately disconnecting from o3de-multiplayersample dedicated servers hosted on Linux and vice versa

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#6666]
**Describe the bug**
Trying to connect a Windows client to the o3de-multiplayersample dedicated server hosted on Linux and a Linux client to the server hosted on Windows via direct IP connection on opened udp port will result in immediate disconnection from the host due to the stream error:

`Disconnecting from remote address XX.XXX.XX.XX:33450 due to StreamError`

 preceded by several asserts that can be observed in the GameLauncher game.log file.

Running the GameLauncher and ServerLauncher with _cl_streamerDevMode=true_ argument did not resolve the issue.

Please note that Linux client was able to connect to dedicated server hosted on Linux machines and Windows was able to connect to dedicated servers hosted on Windows machines.

For further information please refer to the attached screens and log files.

**Prerequisites**

* o3de-multiplayersample project was cloned to o3de directory and built with profile configuration on both
Windows and Linux machines.
* 33450  or other specified port with UDP protocol was opened on both Windows and Linux machines. 

**Steps to reproduce**

1. Launch the Asset Processor with o3de-multiplayersample project path specified and process all assets.
2. On Linux machine launch the _MultiplayerSample.ServerLauncher.app_ followed by _host_ and _loadlevel samplebase_
commands.
3. On Windows machine launch the _MultiplayerSample.GameLauncher.exe_ followed by _cl_serveraddr < Linux machine IP >_ and _connect_ commands.

**Expected behavior**
Windows machine correctly connects to the dedicated server hosted on Linux machine.

**Actual behavior**
Windows machine disconnects from the Linux machine shortly after connection is established due to the stream error.

**Screenshots/Video**
![PC client Stream Error disconnect](https://user-images.githubusercontent.com/86953456/148073095-14dd0dce-681a-49be-afae-5736adc95534.png)

**Found in Branch**
Development (7581967)

**Desktop/Device :**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.3 LTS
- CPU: Intel I7-8700k
- GPU: RTX 2080Ti
- Memory: 16GB

**Additional context**
[Game.log](https://github.com/o3de/o3de/files/7808200/Game.log)
[Server.log](https://github.com/o3de/o3de/files/7808202/Server.log)

**Comment by lmbr-pip** [comment]
sig-network is attempting a reproduction

**Comment by lmbr-pip** [comment]
Whenever an old process of either client or server is hanging around in the background, it causes disconnect issues for new clients. This occurs on Windows but can occur when connecting to Linux or another Windows machine.

See https://github.com/o3de/o3de/issues/7469
