### ISSUE TITLE
Indirect Lighting from Global Skylight IBL is broken

### ISSUE THREAD

**Issue by HogJonny-AMZN** [o3de/o3de#6680]
**Describe the bug**
Indirect Lighting from Global Skylight IBL is broken.

**Steps to reproduce**
1. Create a new default level
2. Inspect the Global Sky entity
3. Note that the 'Global Skylight (IBL) component is loading both the diffuse and specular cubemaps
4. Note that in the 'Asset Picker' or the 'Asset Browser' you can see the input .exr is generating the cubemap product outputs
5. in the viewport visually inspect the shaderball

**Expected behavior**
The shaderball should include indirect color lighting contribution coming from the skylight (ambient)

**Actual behavior**
The shadowed areas on the Shaderball are dark/black

**Assets required**
Any project from the default template should exhibit this.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/23222931/148125110-4dc6b7c7-ff53-42e0-8ced-7f13a70579dc.png)

**Found in Branch**
Latest in 'development': commit 95245e2424681d2b86c35cb1c7f9847540ff2451

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU threadripper 32 cores
 - GPU 3070
 - Memory 64GB system

**Comment by rgba16f** [comment]
PR to revert the original change - https://github.com/o3de/o3de/pull/6681

**Comment by dmcdiarmid-ly** [comment]
The DiffuseCompositePass renders the diffuse global IBL, so it cannot be disabled.

**Comment by dmcdiarmid-ly** [comment]
PR to revert has been merged into the development branch.

**Comment by HogJonny-AMZN** [comment]
@wintermute-motherbrain @thefranke we can close this?

**Comment by galibzon** [comment]
@HogJonny-AMZN is this bug still present?

**Comment by HogJonny-AMZN** [comment]
it no longer occurs in the latest dev branch as of today 
![image](https://user-images.githubusercontent.com/23222931/183738698-f0c19185-80d4-47d6-8b2e-f1213beff63f.png)
