### ISSUE TITLE
The Editor crashes when saving script after removing Bus Handler and enabling any other node

### ISSUE THREAD

**Issue by LB-PatrykKrajewski** [o3de/o3de#6699]
**Describe the bug**
Saving a script after the user removes the Bus Handler and enables any other node crashes the Editor. The script needs to be attached to any entity, otherwise the Editor does not crash. The second node can be anything, including different bus handlers. Shortly before the Editor crash the Editor freezes and throws the Asset Processor parse failed error.

**Steps to reproduce**
1. Create an entity.
2. Add Script Canvas component to it.
3. Create a new script and attach it to the entity created in step 1.
4. Add a Bus Handler and any other node.
5. Disable the node which is not the Bus Handler.
6. Save the graph.
7. Delete the Bus Handler.
8. Enable the second node.
9. Save the graph.

**Expected behavior**
The Editor is stable and the script is saved.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/88180143/148235091-c046271b-8abe-4356-b521-8d8d55ead06b.mp4

**Found in Branch**
Development (bfb1d0a)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600X
- GPU: AMD RX 5700 XT
- Memory: 16 GB

**Comment by alexmontAmazon** [comment]
@lsemp3d have you seen this one? I just want to make sure scripting knows about this one. I keep seeing it in my triaging and freaking out that I missed a critical. I guess I'm just trying to pass that panic on to you :P
