### ISSUE TITLE
VS2022 Support

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#6707]
**Is your feature request related to a problem? Please describe.**
Add support for Visual Studio 2022

**Describe the solution you'd like**
O3DE already compiles for VS2022, we need to add some things to officially support it:
- [x] #10680
- [x] #10681
- [x] #11541
- [x] #11540

**Comment by lumberyard-employee-dm** [comment]
I added a link to the requirements documentation page.

Here is the markdown page in source control that needs to be updated: https://github.com/o3de/o3de.org/blob/main/content/docs/welcome-guide/requirements.md#microsoft-visual-studio

**Comment by Bindless-Chicken** [comment]
There is just one small compilation issue on VS2022 but PR is already up: #6745

**Comment by thefranke** [comment]
I'm currently testing o3de-atomtest, but I have a variety of issues popping up in the AssetProcessor, including a missing `.azsl` extension in `TestNormalMapping.shader` and a missing subId in the LightCullingTilePrepare shadervariant.

**Comment by lumberyard-employee-dm** [comment]
Side Requirement.
We also need to update Project Manager to not hardcode the IDE by removing the [Generator(-G) option](https://github.com/o3de/o3de/blob/663ed5632447fa70040557c407ed15f29ae7f1ef/Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp#L22)

**Comment by oscarbg** [comment]
+1

**Comment by amzn-changml** [comment]
All tasks have been completed, with documentation pointing to the development branch. Once we merge into main for release, it will be generally available in the installer.
