### ISSUE TITLE
Test Tools: Editor.log is blank when running tests using TestAutomationBase or EditorTestSuite

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#6710]
**Describe the bug**
Editor.log is blank when running tests using TestAutomationBase or EditorTestSuite.

**Steps to reproduce**
1. Run a suite of tests using TestAutomationBase or EditorTestSuite (e.g. python\python.cmd -m pytest --build-directory build\bin\profile .\AutomatedTesting\Gem\PythonTests\editor\TestSuite_Main.py)
2. Navigate to AutomatedTesting\user\log and open Editor.log
3. Navigate to your test artifacts directory, and open any of the available Editor.log files

**Expected behavior**
Editor logs are available for every test run in the suite.

**Actual behavior**
The Editor.log in AutomatedTesting/user/log is completely blank. The Editor.log files that are included with test artifacts are incomplete, partial outputs from seemingly random individual tests.

[pytest_results.zip](https://github.com/o3de/o3de/files/7818041/pytest_results.zip)

**Found in Branch**
development@89067fe667d481f43

**Comment by evanchia-ly-sdets** [comment]
https://github.com/o3de/o3de/pull/7058
