### ISSUE TITLE
Prefab system: one entity change triggers all entities within instance reloaded

### ISSUE THREAD

**Issue by Hsuehnj** [o3de/o3de#6743]
**Describe the bug**
In prefab mode, create a new entity or duplicated an entity in Entity Outliner, all entities in the prefab(level prefab) are reloaded. When there are many entity in the scene (for example, more than 200), it takes about 4 seconds to create a new entity. 

**Steps to reproduce**
1. Create a new entity, duplicate an entity, delete an entity, create a new prefab or instantiate a prefab,
2.  All the entities or prefabs within same instance are reloaded.

**Expected behavior**
Only the entities or prefabs that are affected by the changes are reloaded,

**Actual behavior**
All the entities or prefabs within same instance are reloaded.

**Assets required**
N/A

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
Device: PC,
OS: Windows
Version 10,
CPU Intel xeon
GPU NVidia RTX 5000
Memory 128GB

**Additional context**

**Comment by lsemp3d** [comment]
Added sig/core, it likely requires low level optimizations
