### ISSUE TITLE
The release layout built by 2111RTE cannot run properly

### ISSUE THREAD

**Issue by dnqbob** [o3de/o3de#6744]
**Describe the bug**
The release layout (source engine version) cannot run properly -- it just takes up a lot of resource in computer and run in backstage without a window.
![bug1](https://user-images.githubusercontent.com/13763394/148519969-b28f62af-cec9-407e-bd4d-175f2990b4e6.PNG)

**Steps to reproduce**
Build a program using Source Engine follow the step of [user guide](https://docs.o3de.org/docs/user-guide/packaging/windows-release-builds/)
1. Build the engine (source engine)
2. Use GUI (O3DE Editor on this source engine) create a project, build it
3. Open this project, waiting for Asset Processor done all its job
4. Add a new level on Editor, save the level, close the editor
5. Add `autoexec.game.setreg` to `<Project>/Registry/`, AND make sure when open `<Project>/build/windows_vs2019/bin/profile/<ProjName>.GameLauncher.exe`, the game windows runs the level we set in 4.
6. Use "Source engine -> Non-monolithic build" command line under `<Project>/`
7. After build, make sure the `engine.pak` is built

Then I run both `<Project>/build/windows_vs2019/bin/release/<ProjName>.GameLauncher.exe` and `<Project>/install/bin/profile/<ProjName>.GameLauncher.exe` only get the GameLauncher running in run in backstage without a windows

**Found in Branch**
stabilization/2111RTE

**Desktop/Device (please complete the following information):**
 - Device: Dell PC
 - OS: Windows 10 x64
 - CPU Intel Xeon W-1250p CPU
 - GPU NVIDIA RTX 2070
 - Memory 32GB

**Comment by dnqbob** [comment]
Btw, I tried the "Pre-built SDK engine -> Non-monolithic/Monolithic build" in docs but even the engine.pak is not generated.

**Comment by dnqbob** [comment]
Btw, I tried the "Pre-built SDK engine -> Non-monolithic/Monolithic build" in docs but even the engine.pak is not generated.

**Comment by dnqbob** [comment]
Btw, I tried "--config profile" and only get a error about Asset Processor like in #6400

**Comment by dnqbob** [comment]
Is the document still up2date?

**Comment by amzn-changml** [comment]
@lumberyard-employee-dm for awareness

**Comment by dnqbob** [comment]
Then I tried use Monolithic build, only get a windows without anything inside it.

**Comment by lumberyard-employee-dm** [comment]
So by default the `profile` configuration build will load loose assets followed by assets with *.pak files, while the `release` configuration build will load assets only from *.pak files.

I am assuming when you built the project you created using the  steps for the [Source Engine non-monolithic](https://docs.o3de.org/docs/user-guide/packaging/windows-release-builds/#non-monolithic) section of the Crating a Project Game Release Layout for Windows document, you have a 
`<Project>/install/bin/Windows/release/Default/<ProjName>.GameLauncher.exe` and a `<Project>/install/bin/Windows/release/Default/Cache/pc/engine.pak` file.

The engine.pak file gets generated when building the `INSTALL` target in when at least one project is configured with the engine for the `release` configuration. The cmake logic is [here](https://github.com/o3de/o3de/blob/development/cmake/Projects.cmake#L151).

The engine.pak file does not get generated when building the profile or debug configuration.

Also FYI the search mode for Pak files can be changed via CMake when configuring the project via the [LY_ARCHIVE_FILE_SEARCH_MODE](https://www.o3de.org/docs/user-guide/build/reference/#asset-configuration) Cache Variable.

So it is possible to configure `release` configuration to be able to load loose asset files via setting `LY_ARCHIVE_FILE_SEARCH_MODE=0` when configuring a project.
Such as 
```
cmake -B build\windows_vs2019 -S . -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\o3de-packages -DLY_ARCHIVE_FILE_SEARCH_MODE=0
```

Finally the white screen is an indicator that the Atom BootstrapSystemComponent hasn't initialized yet, which probably means the `BootstrapSystemComponent` didn't Activate. That would hook up the component to listen to the [CriticalAssetsCompiled ](https://github.com/o3de/o3de/blob/development/Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp#L150-L159) event, which is used to create the viewport context used for rendering.

**Comment by dnqbob** [comment]
Yesterday I tried use the development branch and problem solved. I think some newly fixed things also fix the building error here.

**Comment by amznestebanpapp** [comment]
Issue seems to be fixed in development, needs to be merged into next stabilization

**Comment by forhalle** [comment]
This was fixed last year.
