### ISSUE TITLE
Feature Request: implement AZStd::span

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#6749]
**Is your feature request related to a problem? Please describe.**
The current implementation of AZStd::array_view matches extremely early versions of the span proposal, in which array_view was read-only.  However, array_view eventually became span in the standards because it allows writing back to the data as well.  I'd like to have a class like span available in which I can write back to the data without owning the storage.

**Describe the solution you'd like**
An implementation of AZStd::span that matches the proposed standards.

**Describe alternatives you've considered**
The alternative is modifying array_view to become writable, but in trying out this path, it will cause a giant ripple effect of const changes in the Atom code, and would still leave the class name as "array_view".  It would be less intrusive to simply create a new standards-compliant span class, and migrate Atom over to it as separate lower-priority cleanup work.

**Comment by invertednormal** [comment]
Worth mentioning we're currently working around this by const-casting values from an array_view so that the terrain APIs don't need to dictate container type, but we can still write the data. Pretty ugly though, would much rather have AZStd::span
