### ISSUE TITLE
[GNU/LINUX] Play Game Maximized half black screen

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#6764]
**Describe the bug**
Play maximized and game exit mouse disappeared and editor black screen small size i had to killer Editor (keyboard Ctrl+Shift+G)

**Steps to reproduce**

https://user-images.githubusercontent.com/17591539/148647030-c8739411-d13c-447b-9f97-5c65e3df5592.mp4

**Found in Branch**
development: 5e8c1aab298e3de08851ea5f47be7c0c7db3f302 and 21.11 stable

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 21.10
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 21.2.2]
 - Memory: 16GB

**Comment by lsemp3d** [comment]
We're not sure if this is a graphics issue or a platform issue

**Comment by jeremyong-az** [comment]
Sort of looks like the viewport is out of sync with the actual framebuffer size

**Comment by rainbj** [comment]
Sig-UX-UI appears not to need further follow up on this issue.

**Comment by jiaweig-amzn** [comment]
This happens on a few Atom samples as well on Linux. The current workaround for after existing game mode is to resize the editor.
I'll investigate together.

**Comment by moudgils** [comment]
https://github.com/o3de/o3de/pull/8436 fixed the issue related to incorrect swap chain size but I have not tested this specific use case. Feel free to sync up, retry and close this issue.

**Comment by Magical10240** [comment]
@moudgils I checked today nothing has changed maximized mode (development: ea5f2d7a6479e72875c197f456add8f57ff7fcfb)

**Comment by Magical10240** [comment]
https://user-images.githubusercontent.com/17591539/160006884-da02bc88-f01f-40fe-81fe-11b01a3f1539.mp4

**Comment by spham-amzn** [comment]
The black rectangle/resizing issue should be solved with https://github.com/o3de/o3de/pull/9776 
The missing mouse cursor is still an issue and reported in  https://github.com/o3de/o3de/issues/9841
