### ISSUE TITLE
Wrinkle Layers not taking effect

### ISSUE THREAD

**Issue by liukaikai-g** [o3de/o3de#6766]
**Describe the bug**
In skin material type, the Wrinkle Layers property doesn't work .

**Steps to reproduce**
1. Create a new Skin material type
2. Enable Wrinkle Layers, set Base Color and Normals
3. See error

**Expected behavior**
The Wrinkle Layers property takes effect.

**Actual behavior**
The Wrinkle Layers property not taking effect.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.
![image](https://user-images.githubusercontent.com/55627654/148725376-6133b333-1969-42c4-aa9c-88bc87e1158a.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel(R)_Xeon(R)_W-2245
 - GPU NVIDIA Quadro RTX 4000
 - Memory 32GB

**Additional context**

**Comment by amzn-tommy** [comment]
@liukaikai-g The wrinkle layers are blended in 1 of two ways - either by the vertex color on the mesh, or by wrinkle masks that are driven by morph targets. So unless you have vertex colors on the mesh you are using, you won't see any impact. If you're just looking to modify the normals/bascolor with a single layer in a way that is uniform across all of the mesh, you can use the detail layer.

We don't have a UI for using custom models in the material editor a this time. You can apply the material to a mesh component in the main editor viewport, or the typical workaround is to replace one of the models in o3de\Gems\Atom\Tools\MaterialEditor\Assets\MaterialEditor\ViewportModels with your own, renamed model.

I'm seeing that the morph target driven wrinkle mask workflow documentation does not appear to be on the website, so I will make sure that gets added. If you'd like to use that in the meantime, ping me here or on discord and I can help out.

**Comment by amzn-tommy** [comment]
@liukaikai-g I've been corrected about the UI for custom models in the material editor. You can add your own custom model via the viewport settings panel in the material editor. https://www.o3de.org/docs/atom-guide/look-dev/materials/material-editor/#model

**Comment by liukaikai-g** [comment]
@amzn-tommy Thanks for a lot,  I followed your method and  it take effect
