### ISSUE TITLE
System shortcuts crash the Editor when Global Preferences are open

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#6768]
**Describe the bug**
System shortcuts crash the Editor when Preferences window is open in the Editor. This includes: Win, Alt + Tab, Ctrl + Alt + Tab, Win + G. On Linux only Alt + Tab combination results in a crash.

**Steps to reproduce**
1. Open the Editor.
2. Navigate to Edit -> Editor Settings.
3. Open Global Preferences...
4. Perform any of the system shortcuts mentioned in the description.

**Expected behavior**
The Editor is stable.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/148772445-b1d2ba67-b1d4-4616-9687-739029135497.mp4

**Found in Branch**
Development (5e8c1aa)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Ryzen 3600
 - GPU NVidia RTX 2060 SUPER
 - Memory 16GB

**Comment by AMZN-daimini** [comment]
I managed to reproduce the issue. Looks like this is due to a recent change that overrides event handling for the preferences windows, but the new code causes an infinite loop when the focus is changed.

https://github.com/o3de/o3de/pull/6296

@jjjoness FYI

Working on a fix :)

**Comment by LB-RostyslavGavryliuk** [comment]
Verified the issue as fixed on build Development (f5fcab7)
