### ISSUE TITLE
Script Canvas graphs are not executed by Script Canvas components

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6771]
**Describe the bug**
Script Canvas graphs are not executed when attached to a Script Canvas component on an entity. Instead an error is printed to the Console - "[Error] (ScriptCanvas) - RuntimeComponent::m_runtimeAsset AssetId: {<ID>} was valid, but the data was not pre-loaded, so this script will not run. It should be noted that no workaround has been found for this issue.

**Steps to reproduce**
1. Go to Tools > Script Canvas.
2. Create a new graph.
3. Create a simple script in it (e.g. On Graph Start -> Print) and save it.
4. Create an entity and add a Script Canvas component to it.
5. Attach the Script Canvas graph saved in step 3 to the Script Canvas component.
6. Enter the Game Mode.

**Expected behavior**
The Script Canvas asset is executed.

**Actual behavior**
An error is printed to the Console and the script does not execute.

**Video**

https://user-images.githubusercontent.com/86952082/148772161-39b27f2c-c8ca-418e-80e6-b30a50ba3197.mp4

**Found in Branch**
Development (5e8c1aa)

**Desktop**
* Device: PC
* OS: Windows
* Version 10
* CPU AMD Ryzen 5 3600
* GPU NVIDIA GeForce RTX 2060 SUPER
* Memory 16GB

**Comment by carlitosan** [comment]
in progress

**Comment by FiniteStateGit** [comment]
I cannot reproduce this with the nightly development build downloaded on 1/18.

**Comment by BytesOfPiDev** [comment]
I also suffer from this in the development branch. My scripts work in the stable branch.

**Comment by carlitosan** [comment]
I just reproduced it this morning with latest.

**Comment by AMZN-Gene** [comment]
![image](https://user-images.githubusercontent.com/32776221/150855592-55e1b1d5-9f37-44fb-93da-7fea950dcaf4.png)

After grabbing latest I tried running a simple Hello World scriptcanvas in Editor (CTRL+G) and it failed. ServerLaunch and GameLauncher run the script just fine
Editor CTRL+G : FAILED
Server Launcher: SUCCESS
Game Launcher: SUCCESS

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (e19dc40) build.
