### ISSUE TITLE
DebugDraw Sphere component has its normals flipped

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6773]
**Describe the bug**
Normals on a sphere drawn by the DebugDraw Sphere component are flipped.

**Steps to reproduce**
1. Create an entity and add a DebugDraw Sphere component to it.
2. Place the created entity so that it intersects a mesh (e.g. Ground child entity from the Atom Default Environment).

**Expected behavior**
Faces of the DebugDraw Sphere are drawn on its exterior.

**Actual behavior**
Faces of the DebugDraw Sphere are drawn on its interior.

**Video**

https://user-images.githubusercontent.com/86952082/148778324-c0fc656a-414b-4d7d-8944-e231133a0162.mp4

**Found in Branch**
Development (5e8c1aa)

**Desktop**
* Device: PC
* OS: Windows
* Version 10
* CPU AMD Ryzen 5 3600
* GPU NVIDIA GeForce RTX 2060 SUPER
* Memory 16GB

**Comment by LB-ArturZieba** [comment]
It should be noted that on the Stabilization_2205 (a073665) build this was noticed on the Sphere Shape component as well. The issue can be seen on the attached SphereShape.PNG image.
![SphereShape](https://user-images.githubusercontent.com/86952082/168073820-3df2f32e-0ced-44c6-b0da-ff6640c34226.PNG).

**Comment by rgba16f** [comment]
I believe this is fixed and can be closed now.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization/2210 (441e2b3) build.
