### ISSUE TITLE
Linux: Asset Processor fails to process GlobalGameData.scriptcanvas job for AutomatedTesting project

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6774]
**Describe the bug**
The following Script Canvas Process Job has failed:
`Levels/Multiplayer/Autocomponent_RPC/GlobalGameData.scriptcanvas`

Please refer to the attached .log for more information.

**Prerequisites**

- O3DE is built for Linux as Source engine following the instructions: https://o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/
- AutomatedTesting is built using the Project Manager.

**Steps to reproduce**

1. Launch the Asset Processor.
2. Wait until all assets are processed.

**Expected behavior**
All assets are processed without failure.

**Actual behavior**
The GlobalGameData.scriptcanvas job fails processing.

**Screenshots/Video**
![AP_Failed](https://user-images.githubusercontent.com/86953659/148780771-8fd35b3b-ccb2-429e-8c02-ad680c64effa.png)

**Found in Branch**
Development (5e8c1aa)

**Desktop/Device:**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU: AMD Ryzen 5 3600
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 16GB

**Additional context**
[GlobalGameData.scriptcanvas-3768394923-29894.log](https://github.com/o3de/o3de/files/7839451/GlobalGameData.scriptcanvas-3768394923-29894.log)

**Comment by monroegm** [comment]
Sending over to SIG-Network due to the location of the asset in the Automated Testing project.

**Comment by spham-amzn** [comment]
As of commit 24086ab3946d6d7257938f4643d81562349c8747, unable to reproduce
![AT_GlobalGameData](https://user-images.githubusercontent.com/82231385/151605063-8a1b60c9-da14-4e32-8a9f-27bf73b6b231.png)

**Comment by LB-KacperKapusta** [comment]
It has been reverified using Development (f5fcab7) that the mentioned .scriptcanvas file still fails for Linux.
![AP_FailsStill](https://user-images.githubusercontent.com/86953659/151952022-a20bae48-4c18-47be-b5b4-94ac3cbecaab.png)

**Comment by spham-amzn** [comment]
Will need more repro information since I am unable to reproduce the error. Was the Cache and user folder under the AutomatedTesting cleared and a clean run attempted? (it could have a stale artifact)

**Comment by LB-KacperKapusta** [comment]
@spham-amzn The issue does reproduce for today's Development (d6c419d) build after a clean install, after making sure there were no Cache and user folders left to have any impact.

**Comment by lmbr-pip** [comment]
Believe fixed, please reopen if still occurring.
