### ISSUE TITLE
Linux AP Monitor

### ISSUE THREAD

**Issue by macy12825** [o3de/o3de#6775]
In Linux, the AP monitor does not process the failure of the notify_add_watch function (return -1 and errno 28). Is there a good solution to this problem? Would it be inappropriate to ask the customer to set the system parameter "fs.inotify.max_user_watch parameter"?

**Comment by AMZN-Dk** [comment]
@Kadino Can we take a look into this a bit more?

**Comment by AMZN-Dk** [comment]
@FuzzyCarterAWS is going to look into this with the Helios team.

**Comment by Kadino** [comment]
This appears to be an issue for SIG-Content

**Comment by FuzzyCarterAWS** [comment]
Assigning to @LesaelR  since he works with the Asset Pipeline team.

**Comment by lmbr-pip** [comment]
Maybe fixed by https://github.com/o3de/o3de/pull/11248

**Comment by lmbr-pip** [comment]
@macy12825 Trying to catch up to this older issue, its unclear what you mean by " " as the code errors out if response is -1. See https://github.com/o3de/o3de/blob/bfb1d0ad9e3ee9d39c0661fba3a84ab5337ae5bb/Code/Tools/AssetProcessor/Platform/Linux/native/FileWatcher/FileWatcher_linux.cpp#L70

**Comment by FuzzyCarterAWS** [comment]
Pinging @macy12825 again to get clarification called out by @lmbr-pip above.
