### ISSUE TITLE
Linux: An error prompt window displayed upon launching the Asset Processor

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6776]
**Describe the bug**
The following error prompt window is displayed upon launching the Asset Processor for any project:
`WARNING: CPU random generator seems to be failing, disabling hardware random number generation`

The described information could previously only be spotted in the terminal log from launching the Asset Processor.
The issue has been reproduced on 2/3 machines.

Please refer to the attached screenshot for more information.

**Steps to reproduce**
1. Build any project on Linux.
2. Launch the Asset Processor or Editor for the project built.

**Expected behavior**
No error prompts are displayed.

**Actual behavior**
An error prompt with the warning is displayed.

**Screenshots/Video**
![CPU_RandomGenerator](https://user-images.githubusercontent.com/86953659/148783988-ae68cfe6-ad44-4ca1-8e2e-0988f6aab952.png)

**Found in Branch**
Development (5e8c1aa)

**Desktop/Device:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU: AMD Ryzen 5 3600
 - GPU: NVIDIA GeForce RTX 2060 SUPER
 - Memory: 16GB

**Comment by spham-amzn** [comment]
Looked into it, it doesnt appear to be an O3DE issue, but rather an issue with the CPU

https://askubuntu.com/questions/1264439/warning-cpu-random-generator-seem-to-be-failing-disable-hardware-random-number

Try to update the BIOS on that machine

**Comment by amzn-pratikpa** [comment]
Please see note above about updating the BIOS
