### ISSUE TITLE
[SliceDeprecation] Convert Asset Processing related automated tests to use prefab system

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#6779]
Remove slice related tests/checks/validation/verification from the following AP python automated tests, and then add the tests for prefab system:

- test_AllSupportedPlatforms_CorruptSlice_BatchReportsProcessingFail
- test_AllSupportedPlatforms_DeleteBadAssets_BatchFailedJobsCleared
- test_AllSupportedPlatforms_DeleteCachedAssets_AssetsReprocessed
- test_WindowsAndMacPlatforms_AssetBuilderDebug_ShowProcessStatus
- test_ProcessAndChangeSource_APBatchShouldReprocess
- test_AllSupportedPlatforms_AddScanFolder_AssetsProcessed
- test_WindowsAndMac_AssetReportsAllButOneReference_ReportsOneMissingDependency
- TestsMissingDependencies_WindowsAndMac
- Any other python automated tests related to AP that might using deprecated slice system

Here are the converted tests that can be used as reference:
- test_WindowsMacPlatforms_MoveCorruptedSliceFile_MoveSuccess

Related PR for reference:
https://github.com/o3de/o3de/pull/6426

**Comment by LesaelR** [comment]
#7826 
Updating all but 2 of AP tests using slices - these two will require a custom builder. 
These two missing tests are currently sandboxed:
test_validateDirectPreloadDependency_Found
test_validateNestedPreloadDependency_Found

**Comment by chiyenteng** [comment]
> #7826 Updating all but 2 of AP tests using slices - these two will require a custom builder. 
These two missing tests are currently sandboxed: 
test_validateDirectPreloadDependency_Found 
test_validateNestedPreloadDependency_Found

Please delete slice relate files and replace slice related terms (like `testa.dynamicslice`) with prefab/spawnable for these two tests. Create GHIs/internal tickets for these tests, and lastly add the GHIs/tickets ids to the reason of **@pytest.mark.skip**.
