### ISSUE TITLE
[Pre Release] Confirm all technical requirements are complete

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#6799]
Confirm with the Release SIG all features and bug fixes targeted for the release are complete and merged into the stabilization branch. Also verify all exception requests (i.e. requests to merge to stabilization post code lock) are merged per the Exception Request Dashboard. 

- Successor Task: [#6827]
- Related Task: [#7032]

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by forhalle** [comment]
@Ulrick28 - For tracking purposes, would you mind please confirming all requirements are complete?

**Comment by Ulrick28** [comment]
This action item is vague. Which technical requirements are you referring to?

**Comment by forhalle** [comment]
Thank you for the feedback, @Ulrick28 ... I have updated the description to be more specific as follows: "Confirm with the Release SIG all features and bug fixes targeted for the release are complete and merged into the stabilization branch."

Please confirm and close this issue.

**Comment by forhalle** [comment]
@Ulrick28 sent @sptramer list of known issues on 1/25.

**Comment by Ulrick28** [comment]
Closing as no new issues have come in
