### ISSUE TITLE
Feature Request: Setup security@o3de.org email for reporting security vunerabilities

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#6802]
**Is your feature request related to a problem? Please describe.**
Need to setup security reporting email address for secure vulnerability reporting. Work with SIG-Security to setup team that has access. See https://github.com/o3de/sig-security/issues/12

**Describe the solution you'd like**
Users can report vulnerabilities via security@o3de.org

**Describe alternatives you've considered**
See associated RFC: https://github.com/o3de/sig-security/issues/12

**Additional context**
None

**Comment by amzn-changml** [comment]
Will create a ticket with Linux Foundation IT to provision security@o3de.org

**Comment by amzn-changml** [comment]
As per https://github.com/o3de/sig-security/issues/16, this has been completed. This has been linked to the mailing list on lists.o3de.org, which @dshmz has control over.
