### ISSUE TITLE
Feature Request: Setup security section on o3de.org

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#6803]
**Is your feature request related to a problem? Please describe.**
As per https://github.com/o3de/sig-security/issues/12 setup security reporting section on https://o3de.org ie https://o3de.org/security that is easily discoverable

See https://kubernetes.io/docs/reference/issues-security/security/#report-a-vulnerability as an example

**Describe the solution you'd like**
Need to have clear set of instructions that cover security vulnerability reporting for O3DE.

**Describe alternatives you've considered**
n/a - See https://github.com/o3de/sig-security/issues/12

**Additional context**
None

**Comment by amzn-changml** [comment]
Cross cutting task with docs to open a new section

**Comment by sptramer** [comment]
@amzn-changml - Please discuss with sig-docs-community on the Discord, create an RFC, or attend a SIG meeting (next schedule for 2nd Tuesday of March)

**Comment by lmbr-pip** [comment]
Started a conversation on sig-docs-community to find where page should live. Will deliver draft of this content and get o3de.org url setup, can then link in the SECURITY.md file (https://github.com/o3de/o3de/issues/6805)

**Comment by lmbr-pip** [comment]
Looks like best alignment will be https://www.o3de.org/docs/contributing/security/  - wait to see if there any objections  from sig-docs-community for location. SIG-Security will draft content and look for reviews from security and docs teams.

**Comment by willihay** [comment]
> Looks like best alignment will be https://www.o3de.org/docs/contributing/security/ - wait to see if there any objections from sig-docs-community for location. SIG-Security will draft content and look for reviews from security and docs teams.

No objections here. I support this approach.

**Comment by FiniteStateGit** [comment]
> Looks like best alignment will be https://www.o3de.org/docs/contributing/security/ - wait to see if there any objections from sig-docs-community for location. SIG-Security will draft content and look for reviews from security and docs teams.

@sptramer I'll second.

**Comment by lmbr-pip** [comment]
Will close issue once https://github.com/o3de/o3de.org/pull/1431 is accepted (can't auto close when PR is in external repro).

**Comment by lmbr-pip** [comment]
Added: https://www.o3de.org/docs/contributing/security/
