### ISSUE TITLE
O3DE installer does not unregister the engine on uninstall

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#6835]
**Describe the bug**
When the user uninstalls O3DE using the installer, the engine path and name is still present in the `o3de_manifest.json`

**Steps to reproduce**
1. Install O3DE using the installer
2. Open the Project Manager
3. Close the Project Manager and uninstall O3DE
4. open `%USER%/.o3de/o3de_manifest.json` in a text editor

**Expected behavior**
The engine that was uninstalled is no longer listed in `engines` or `engines_path`

**Actual behavior**
The engine is still listed in `engines` or `engines_path`

**Comment by AMZN-alexpete** [comment]
Likely need to edit and add an extra step in here: https://github.com/o3de/o3de/blob/development/cmake/Platform/Windows/Packaging/Template.wxs.in

**Comment by monroegm** [comment]
Install/uninstall belongs to SIG-Release
