### ISSUE TITLE
About button in Material Editor is not functional

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#6838]
**Describe the bug**
The "About" button in the Material Editor "Help" menu does not trigger any action.

**Steps to reproduce**
1. Open the Material Editor.
2. Navigate to Help.
3. Select the About... button.

**Expected behavior**
Information about the Material Editor is displayed.

**Actual behavior**
No information about the Material Editor is displayed. No other action is triggered.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/149124394-9b8d1281-678c-49c7-81f9-488b6b9cae8c.mp4

**Found in Branch**
Development (44908a8)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 3600
 - GPU Nvidia GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment]
i cannot find the PR where this was resolved searching for "about" but the tools have a standard minimal about dialog
