### ISSUE TITLE
[Assert] 10KEntityCpuPerfTest and 10kVegInstancesTest levels of AutomatedTesting project throw asserts

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6878]
**Describe the bug:**
Opening 10KEntityCpuPerfTest level and entering Game Mode results in two asserts being thrown one after the other. Opening 10kVegInstancesTest level results in the same asserts being throw but entering the Game Mode is not necessary in this case. 
Please note that opening either of the mentioned levels causes Editor to freeze slightly for several seconds.

Refer to the attached Editor logs for more information.

**Assert 1:**

**File:**

`C:/o3de/Gems/Atom/RHI/DX12/Code/Source/RHI/DescriptorContext.cpp`

**Condition:**

```
(9448) 'enum AZ::RHI::ResultCode __cdecl AZ::DX12::DescriptorContext::CompactDescriptorHeap(void)'
(System) - Descriptor heap Compaction not allowed. Please consider increasing number of handles allowed for the second valueof DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV or enabling AllowDescriptorHeapCompaction within platformlimits.azasset file for dx12.
```

**Line:** `570`

**Assert 2:**

**File:**

`C:/o3de/Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp`

**Condition:**

```
(9448) 'void __cdecl AZ::RHI::FrameScheduler::CompileShaderResourceGroups(void)'
(System) - SRG compaction failed and this can lead to a gpu crash.
```

**Line:** `382`

**Prerequisites:**

- AutomatedTesting project is built.

**Steps to reproduce:**
1. Open _10KEntityCpuPerfTest_ level.
2. Enter Game Mode (Ctrl+G).
or
1. Open _10kVegInstancesTest_ level.

**Expected behavior:**
Levels open and run the Game Mode without issues.

**Actual behavior:**
Asserts are thrown upon entering Game Mode or opening level.

**Screenshots:**
**Assert 1:**
![Assert1](https://user-images.githubusercontent.com/86953659/149339729-e55c7f1c-9079-4e4e-84df-31a11974ff0d.PNG)
**Assert 2:**
![Assert2](https://user-images.githubusercontent.com/86953659/149339734-747d42dc-fd68-4dd4-a637-b2d2a45345cf.PNG)

**Found in Branch:**
Development (e224fc2)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel i5-9600K
 - GPU: RTX 2070
 - Memory: 16GB

**Additional context**
[Editor_10KEntityCpuPerfTest.log](https://github.com/o3de/o3de/files/7863122/Editor_10KEntityCpuPerfTest.log)
[Editor_10kVegInstancesTest.log](https://github.com/o3de/o3de/files/7863124/Editor_10kVegInstancesTest.log)

**Comment by monroegm** [comment]
I couldn't repro this on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7. It's possible this has already been fixed.
