### ISSUE TITLE
It is possible to edit level name so it contains invalid characters

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#6879]
**Describe the bug**
The project's folder name can be changed in the file explorer even with special characters. The level can be loaded and saved afterwards without any restrictions regarding it's name.

**Steps to reproduce**
1. Create a level.
2. Close the Editor.
3. Change the level folder's name in the file explorer.
4. Launch the Editor.
5. Load the level.
6. Navigate to File > Save As and verify that the invalid characters can be used.

**Expected behavior**
There is a prompt about invalid characters during level creation.
A level containing special characters in it's name is not selectable in the Open a level window.

**Actual behavior**
Levels with special characters can be selected, loaded and saved later on, without restrictions regarding it's name.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/149342192-dc8f921f-061c-40f1-a061-c0cdd35f0b93.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/e224fc2ee5ec2a12e75a10acae268b7b38ae3a32)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by LB-KacperMetelski** [comment]
Verified as Fixed in development (d9efce5).
