### ISSUE TITLE
Audio Controls Editor: It is impossible to undo renaming the folder in the ATL Controls

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#6880]
**Describe the bug**
In the **Audio Controls Editor**, the action of renaming the folder in **ATL Controls** tab cannot be undone.
Attempting to undo renaming the folder results in undoing the previous action.

Please note that the Wwise Gem must be enabled to use the **Audio Controls Editor**.

**Steps to reproduce**
1. Create a new level.
2. Open the **Audio Controls Editor** tool. (Tools -> Other -> Audio Controls Editor)
3. Create a new folder in the **ATL Controls** tab.
4. Rename the previously created folder.
5. Undo the action. (Ctrl+Z)

**Expected behavior**
It is possible to undo the action of renaming the folder in the **ATL Controls** tab.

**Actual behavior**
Using Undo after renaming a folder in the **ATL Controls** tab does not result in undoing that action.

**Video**

https://user-images.githubusercontent.com/86951967/149350686-af29ba94-15ab-44ad-9c2c-6819373167bf.mp4

**Found in Branch**
Development (e224fc2)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed on build Development (58adaf9).

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed using Stabilization/2210 (https://github.com/o3de/o3de/commit/99608ffd4f7d3d347cb015b243046a3438da23c7) build.
