### ISSUE TITLE
Cannot create new seed asset list for AutomatedTesting project

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#6889]
**Describe the bug**
In an attempt to get rid of the warning `"Failed to locate record for bundle <levelname>` I attempted to create a record in a bundle following the instructions for https://www.o3de.org/docs/user-guide/packaging/windows-release-builds/ the AssetBundler will not let you select the `levels` folder because it does not contain the required `assetcatalog.xml` file.  When attempting to use the `assetcatalog.xml` file in `AutomatedTesting\Cache\pc` the following error is issued: `Asset catalog does not know about the asset (.) on platform (pc)`

**Steps to reproduce**
1. Using the AutomatedTesting project following the instructions here to create a build https://www.o3de.org/docs/user-guide/packaging/windows-release-builds/
2. When you get to the `Create a new seed asset list` section try to follow steps 6 and 7 "In File Explorer, browse to the levels folder.  In the Add Seed Asset dialog, click Add Seed"

**Expected behavior**
You can add the seed

**Actual behavior**
You cannot use the levels folder because it doesn't have the required `assetcatalog.xml` file
You cannot use the `assetcatalog.xml` in `AutomatedTesting\Cache\pc` the following error is issued: `Asset catalog does not know about the asset (.) on platform (pc)`
If you select contents in a level folder `Generate Asset Lists` fails, stating the "list is empty"

**Assets required**
n/a

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/26804013/149398214-bd95ace2-d2ee-4d5a-8f5c-1b12f24730dd.png)

When trying to add the level and file list xml to a seed list and pressing `Generate Asset Lists`:
![image](https://user-images.githubusercontent.com/26804013/149399334-826c9d48-453e-40bb-8f3c-44719afa0c8f.png)

This is the error popup I'm trying to prevent:
![image](https://user-images.githubusercontent.com/26804013/149399631-fe8c76af-17d1-4087-9ab4-71d349a2711a.png)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Additional context**
n/a

**Comment by AMZN-stankowi** [comment]
Resolving as "Won't fix", this is an issue with legacy levels. Automated Testing no longer processes these by default, and the use of these legacy levels is now deprecated. I verified that I could add prefab based levels to seed asset lists without issue.
