### ISSUE TITLE
Bug Report: Script Canvas - Pressing Delete key cause nodes unable to connect.

### ISSUE THREAD

**Issue by rainbj** [o3de/o3de#6922]
**Describe the bug**
During the most recent LBC we were creating a Script Canvas script. It was noticed that if a user presses the delete key instead of the shortcut "shift + click", this causes the nodes to freak out and starts saying,  "unable to connect" when trying to connect two valid node connections. If you completely close the editor and restart; sometimes this will resolve the issue. However it's almost as if the script doesn't recognize what you have done. 
 
In some other instances (not the same as above), disconnecting node via the delete key would cause the editor to hang and eventually crash. This crash happened often during my work.

![image](https://user-images.githubusercontent.com/82551958/149600683-ae10966a-0ec2-4b5a-9df6-3dcd80cb5c2e.png)

**Steps to reproduce**
2. Click on '...'
3. Select attached asset '...'
4. Scroll down to '...'
5. See error

**Expected behavior**
I would expect that Del would work the same as "Shift + Click"  OR completely remove the ability to use the "delete" key.

**Comment by lsemp3d** [comment]
The screenshot shows an invalid connection, even without pressing DEL, that connection is not valid. A Transform value does not implement the ability to Add (+) to another Transform. I tried to reproduce the behavior with valid types and was unable to.
