### ISSUE TITLE
[Pre Release] Ensure final release notes are documented

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#6926]
Ensure the Release SIG documents the final customer-facing release notes in preparation for release, using the draft release contents as input.

- Predecessor Task: [#6827]

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by forhalle** [comment]
Per discussion with @Ulrick28, the target completion date for these notes is 1/19.

**Comment by forhalle** [comment]
Hi @Ulrick28 - Can you please confirm we are on track to complete this today?

**Comment by forhalle** [comment]
@Ulrick28  will complete these tonight, and will then provide to @sptramer for an editing pass (target to complete by 1/26)

**Comment by forhalle** [comment]
From @Ulrick28: "I have two known issues I need to send to documentation, and we just found a fatal linux issue"

**Comment by forhalle** [comment]
PR: https://github.com/o3de/o3de.org/pull/1381

**Comment by Ulrick28** [comment]
Closing as final release notes have been created
