### ISSUE TITLE
[Pre Release] Ensure installers are created

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#6932]
Ensure the Build SIG creates the signed installers for Windows and Linux in preparation for testing.

- Successor task: [#7018]

Discord: [#sig-build](https://discord.com/channels/805939474655346758/816043576034328636)
Build SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Build SIG meeting agendas: [GHI](https://github.com/o3de/sig-build/issues)

**Comment by forhalle** [comment]
Per conversation with @Ulrick28, "Sig Build signoff on schedule for creating a new main installer build and date determined for removal of the stabilization/RTE2111 branch to main ETA 1/19"

**Comment by forhalle** [comment]
Per @Ulrick28, this task doesn't need to be split up into separate tasks, since the same person will perform all actions.

**Comment by forhalle** [comment]
Upon further discussion w/ @Ulrick28, I will split this into three separate tasks.

**Comment by forhalle** [comment]
@amzn-changml will create the installers by 1/24

**Comment by amzn-changml** [comment]
Confirmed that the 2111.2 installer has been created and showing the correct version in the splash screen
