### ISSUE TITLE
[Post Release] Ensure LFS binary objects are added and tested

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#6933]
- Related Task: [#6635]

GitHub does not include the objects in its release zip (Anything that is bigger than a few MB and isn't text - e.g. images, fbx models, test files, etc. - are not included). To account for this, ensure the Release SIG coordinates with the Build SIG to pull down the LFS objects for the tagged release, generate a zip file, upload the zip file to the release on [this page](https://github.com/o3de/o3de/releases), and obtain QA signoff that the tag looks good and includes the LFS binary objects on all of the following 5 repos:
- o3de
- o3de-atomtest
- o3de-atom-sampleviewer
- o3de-multiplayersample
- o3de-netsoaktest

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by amzn-changml** [comment]
o3de LFS objects uploaded. Awaiting the rest of the repos

**Comment by amzn-changml** [comment]
atom-sampleviewer LFS objects uploaded. Other repos have no new LFS objects to add for this release, so will close this issue.
