### ISSUE TITLE
Bug ReportEditor hangs when starting UI Editor and kills off X server when killed.

### ISSUE THREAD

**Issue by slapin** [o3de/o3de#6938]
Hi guys! So great progress! Thank you for all the work done!

**Describe the bug**
I was following some entry level tutorial which showed how to create some in game menu which
required the use of UI Editor, so I was trying to run it. It displayed the window, but did not draw the canvas part and
UI stopped reacting to mouse hovers and presses, however all the window elements draw when I hide/show it
via my desktop environment (MATE). When I killed the process my X11 session died too. This bug persists.
**Steps to reproduce**
1. Open Editor, click on UI Editor button
2. Try to do anything
3. ...
4. Kill the Editor process
5. Lose all your windows (careful!)

**Expected behavior**
I never tried it before but I expect UI editor not to hang and not to crash X server when killed.

**Actual behavior**
UI Editor hangs, Editor process when killed crashes X server

**Assets required**
Default template project is enough to reproduce the issue/

**Found in Branch**
development branch on 76ff7aec29ad67f11f0dc84e47702cc8757dcdd2

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Debian testing (Currently around 11/bullseye)
 - CPU i7 2600k
 - GPU NVIDIA 1060
 - Memory 16GB

**Additional context**

**Comment by slapin** [comment]
I tested again on commit 5e85e0e397ffcf32dc2634533d51020109bab840 the problem is still there however it looks like killing the process no longer kills X server.

**Comment by spham-amzn** [comment]
This should be fixed with https://github.com/o3de/o3de/pull/9645
