### ISSUE TITLE
The BlendTwo node always displays only the information about the receive interface.

### ISSUE THREAD

**Issue by lihongjun25** [o3de/o3de#6940]
**Describe the bug**
[Animation] If Display Play Speeds is selected for Visualization under Anim Graph in the animation editor, the BlendTwo node always displays only the information about the upper receiving port. If BlendN is involved in animation blending, only the information about the upper receiving port is displayed, and the lower speed is forcibly changed to the upper speed.

**Steps to reproduce**
1. Open the edited Anim Graph, run the Anim Graph, and select Display Play Speeds under Visualization.
2. Adjust the parameters to change the weight of the action, and observe the displayed information such as BlendTwo and BlendN.

**Expected behavior**
1. The information such as BlendTwo and BlendN is correct.

**Actual behavior**
1. The BlendTwo node always displays only the information about the receive interface.
2. When BlendN involves animation blending, only the information of the upper receiving port is displayed, and the speed of the lower part is changed to the speed of the upper part.

**Desktop/Device (please complete the following information):**
- Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel Xeon Gold 6234]
 - GPU [NVidia RTX 5000]
 - Memory [32GB]
 - Working Branch: Main branch e7f7875

**Comment by amzn-jillich** [comment]
@lihongjun25 can you please upload a screenshot of the situation you're describing? I assume motion syncing is disabled, correct? Do you have several different playspeeds set on the motion nodes that are plugged into the blend N node?

**Comment by lgleim** [comment]
Revisited in today's SIG Simulation issue triage. With the limited amount of information provided, this report is non-actionable at this time. As such I am closing the report. Feel free to reopen with additional information.
