### ISSUE TITLE
Bug Report：【Vegetation System】How to use parameters of Vegetation Asset List component

### ISSUE THREAD

**Issue by qq260105064** [o3de/o3de#6946]
**Describe the bug**
External parameter of source type of Vegetation Asset List component, Instance Spawner parameter prefab under embedded assets, Override Model parameter Extend under Surface Mask Filter do not know how to use it, please locate.

**Steps to reproduce**
1. Using Vegetation Asset List
2. Modify External parameter of source type
3. Modify Instance Spawner parameter prefab under embedded assets
4. Modify Override Model parameter Extend under Surface Mask Filter

**Expected behavior**
Changes in vegetation after modification.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by monroegm** [comment]
Can you please open a discuss for help on how to use the vegetation system?
