### ISSUE TITLE
Procedural prefab can be modified by duplicating read-only entity inside it

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#6967]
**Describe the bug**
A read-only entity can be duplicated inside a procedural prefab and modified afterwards.

**Steps to reproduce**
1. Instantiate a procedural prefab.
2. Inspect the procedural prefab and select the entity inside it.
3. Duplicate the entity.
4. Modify the duplicated entity.

**Expected behavior**
The procedural prefab cannot be edited.

**Actual behavior**
The procedural prefab can be edited after duplicating the entity inside it.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/149939534-5ffe7412-b706-487c-867f-13d07f12cc25.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/4cd3568d7b110b8e962f373a6c0c2b701ee25d30)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by AMZN-daimini** [comment]
Verified, I can reproduce - the "Duplicate..." menu item is not available on read-only entities, but Ctrl+D still works.
I will add two checks, one on the shortcut side, one on the prefab side, to make sure duplicating read-only entities is disabled.

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in Development.
