### ISSUE TITLE
Running automated tests generates a TestResults folder in o3de root folder

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#6971]
**Describe the bug**
A `TestResults` folder is created under o3de root folder when running automated tests.

The engine root should be treated as immutable when it comes to testing.

We should update the TestResults method in the [abstract_resource_locator.py](https://github.com/o3de/o3de/blob/development/Tools/LyTestTools/ly_test_tools/_internal/managers/abstract_resource_locator.py#L294-L299) and the UnitTest within the [test_abstract_resource_locator.py](https://github.com/o3de/o3de/blob/development/Tools/LyTestTools/tests/unit/test_abstract_resource_locator.py#L187-L192) to write to write the test results the `<project-user>/user` directory.

**Steps to reproduce**
1. Build O3DE for AutomatedTesting project
2. Run automated tests from o3de root folder as indicated in the documentation: https://www.o3de.org/docs/user-guide/testing/lytesttools/getting-started/
Example:
`o3de>.\python\python.cmd -m pytest .\AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Main.py --build-directory=AutomatedTesting\build\windows\bin\profile\`

**Expected behavior**
`TestResults` folder is created somewhere under the project.

**Actual behavior**
`TestResults` folder is created in o3de root folder.
As an annoying side effect, all the files under that folder will appear in github as untracked files, since TestResults is not under .gitignore.

**Comment by AMZN-Dk** [comment]
@dshmz This is something we should change, assigning to you to help prioritize and schedule.

**Comment by Kadino** [comment]
This does not occur when run through CMake / CTest, but I agree it would be proper for running tests directly through Python to have the same behavior.

**Comment by Kadino** [comment]
Testing a proposed fix to the defaulting behavior when the user does not set the output path.
