### ISSUE TITLE
Need a mechanism to identify and track issues that break minimum stability bar for development branch

### ISSUE THREAD

**Issue by tjmichaels** [o3de/o3de#6981]
Over the weekend we had issues creating new projects, which should be considered as below the minimum stability level expected in the development branch.  This was likely caused by a lack of testing in Automated Review that could have gated this.  This indicates we need mechanisms to ensure we identify and prioritize the creation tests to cover areas that impact the basic stability of any branch.

**Comment by Kadino** [comment]
Recommend filling this gap with additional automated tests. What SIG maintains project creation? SIG-Content?

**Comment by Kadino** [comment]
@tjmichaels is this pointing toward a mechanism for classifying and recording escaped bugs?

**Comment by Kadino** [comment]
This may point to a documentation for a gap-analysis process, to help clarify verifications which are missing from the automated test suite.

**Comment by Kadino** [comment]
Up to each SIG to recommend how to cover gaps in their coverage. SIG-Testing can consult with them on their ownership/design of automated tests.
