### ISSUE TITLE
[Pre Release] Ensure PRs are created for branch merge

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#6992]
Ensure the Release SIG creates PRs for the final merge from the stabilization branch to main for each of the following repos:
- o3de
- o3de-atomtest
- o3de-atom-sampleviewer
- o3de-multiplayersample
- o3de-netsoaktest

Replace all the [PR] placeholders in the below successor task with the correct information for this release.
- Successor Task: [#6635]

**Comment by forhalle** [comment]
@Ulrick28 - Can you please confirm which repos require a PR for this point release? Is it only o3de (not o3de-atomtest, etc.)?

**Comment by forhalle** [comment]
@cgalvan - Can you please provide a target date for completing the work to create these PRs?

**Comment by forhalle** [comment]
Per conversation with @Ulrick28,
The Pull Request for stabilization/2111RTE to main will be created 1/24 by @cgalvan

**Comment by cgalvan** [comment]
I've created the PR for the merge of `stabilization/2111RTE` to `main`:

https://github.com/o3de/o3de/pull/7120

This won't actually be merged until the point release launch day
