### ISSUE TITLE
Performing Undo action after deleting certain Animation Script Canvas nodes causes the Editor to crash

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#7000]
**Describe the bug**
Performing Undo action on certain Animation Script Canvas nodes (Categories: Animation > IAnimation Data, Animation > IBlend Shape Animation Data, and IBlend Shape Data) causes the Editor to silently crash. It should be noted that if the node categories listed are not present on the first Editor launch, the Editor should be restarted.

**Steps to reproduce**
1. Go to Tools > Script Canvas.
2. Create a new Graph.
3. Drag in any node from mentioned Script Canvas node categories (e.g. Get Key Frame (IAnimation Data Category))
4. Delete the added node.
5. Use the Edit > Undo action.

**Expected behavior**
The Editor remains stable.

**Actual behavior**
The Editor crashes silently.

**Video**

https://user-images.githubusercontent.com/86952082/150154749-3c9d828a-2055-42a3-9149-632c3abb7a1e.mp4

**Found in Branch**
Development (3bbb8d7)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by carlitosan** [comment]
duplicates https://github.com/o3de/o3de/issues/2191

**Comment by carlitosan** [comment]
@alexmontAmazon  just a heads up on the dupe
