### ISSUE TITLE
[Pre Release] Ensure installers are tested

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#7018]
Ensure the Build SIG tests the signed installers for Windows and Linux.

Note: Ensure the version number is reflected accurately upon installation.

- Predecessor task: [#6932]
- Successor task: [#7019]

Discord: [#sig-build](https://discord.com/channels/805939474655346758/816043576034328636)
Build SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Build SIG meeting agendas: [GHI](https://github.com/o3de/sig-build/issues)

**Comment by forhalle** [comment]
@AMZN-Dk - Please plan to have this tested 1/25 - 1/26

**Comment by AMZN-Dk** [comment]
Closing this ticket out, installer test matrix was completed with no new or blocking issues found.

**Comment by AMZN-Dk** [comment]
https://github.com/o3de/sig-testing/blob/main/installer-test-matrix.md 

Adding a link to the installer test matrix that was run on Windows for this as a reference for future installer testing.
