### ISSUE TITLE
[Pre Release] Ensure installers are uploaded to S3

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#7019]
Ensure the Build SIG uploads the installers for Windows and Linux  to the below S3 buckets:

Windows s3://o3de-prism-prod-us-west-2/main/Latest/Windows/

Linux s3://o3de-prism-prod-us-west-2/main/Latest/Linux/

- Predecessor task: [#7018]

Discord: [#sig-build](https://discord.com/channels/805939474655346758/816043576034328636)
Build SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Build SIG meeting agendas: [GHI](https://github.com/o3de/sig-build/issues)

**Comment by forhalle** [comment]
@amzn-changml will upload the insallers to S3 on 1/26

**Comment by amzn-changml** [comment]
The installer has been pre-staged for upload as of 1/24, unless anything changes with the 2111RTE branch

**Comment by forhalle** [comment]
@amzn-changml  - It sounds like this issue is closed, so I'm closing it. Poke me if this is not correct.
