### ISSUE TITLE
Linux: Moving Editor causes buttons in the Viewport to be displaced outside of their boundaries

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#7028]
**Describe the bug**
If the Editor window is moved left, up or down, the two groups containing Translate/Rotate/Scale mode buttons and World/Parent/Local space lock buttons are moved outside the Viewport's boundaries in the direction the window is being moved.

**Steps to reproduce**
1. Make sure the Editor window is not maximized, but you can still see the Viewport clearly.
2. Move the Editor window in each direction.

**Expected behavior**
Editor window looks consistently when moving around.

**Actual behavior**
Two groups containing Translate/Rotate/Scale mode buttons and World/Parent/Local space lock buttons are moved outside the Viewport's boundaries when the window is moved.

**Video**

https://user-images.githubusercontent.com/86952082/150341751-ca95812f-0a8d-42df-8144-c28cc9265049.mp4

**Found in Branch**
Development (63d755b)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-MarcinKoniecki** [comment]
A similar issue has been spotted on the Development Branch (e19dc40). After undocking the Entity Outliner (or any of the internal Tools) and placing it in the top bar, the area of the Entity Outliner collides with the buttons in the Viewport. Should this be reported as a separate issue?
![TopBenchOverlapping](https://user-images.githubusercontent.com/93910638/151534806-9ece5251-d918-49bd-ad37-e8d1b643effa.png)
