### ISSUE TITLE
[Post Release] Ensure the stabilization branch is deleted

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#7033]
Ensure the Release SIG deletes the stabilization branch (ideally 1 week post release).

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by forhalle** [comment]
@Ulrick28 - This task is due 2/3.

**Comment by forhalle** [comment]
Due date updated to Monday, 1/31

**Comment by amzn-changml** [comment]
The notice to delete was sent out last Friday. The branch has been deleted as scheduled @ 10am PST. @Ulrick28 Please feel free to confirm.

**Comment by Ulrick28** [comment]
Confirmed
