### ISSUE TITLE
Simplify/Refactor AWSApiRequestJob and ServiceRequestJob

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#7047]
Recently, updates were made to [AWSApiRequestJob](https://github.com/o3de/o3de/commit/59e43813f0b091f4456a0a90892bf08f7e7b5141#diff-39852cc6865d1ea1f5bd2a812a0ec07be036fe0bb0176ef7198e365bd8ecb218) and [ServiceRequestJob](https://github.com/o3de/o3de/commit/59e43813f0b091f4456a0a90892bf08f7e7b5141#diff-d45732876461be69d2c6c718d6821d37cf7373f63a7dc969454491fb41e1f1d7) to fix a GCC compilation error caused by an inner class attempting to inherit from its outer class ( `error: invalid use of incomplete type 'class AWSCore::AwsApiRequestJob<RequestTraits>`) 

The inner 'Function' class for both of these Request Job classes were simply just to override the base class's behavior to queue the delete for Success, Failure, and Cleanup events rather than to do the default (optional) auto delete. So to solve this problem, the functionality that was in the original inner derived 'Function' class (to queue the actions and to optionally call callback functions) was moved into the base class and is controlled by flags instead of creating an instance of an inner base class.

These architecture for these 2 classes needs to be re-examined and simplified if possible

**Comment by lmbr-pip** [comment]
Blocked on https://github.com/o3de/o3de/pull/6906, need to pull in changes to identify concrete next steps.

**Comment by lmbr-pip** [comment]
Fixed in https://github.com/o3de/o3de/pull/7088

**Comment by onecent1101** [comment]
Issue is never fixed, we just fix the GCC compiler error right now. Still need to investigate and find out a better way to simplify these two classes, which requires have better testing coverage as well.
