### ISSUE TITLE
[Pre Release] Ensure version number updates to CMake parameters are complete

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#7048]
Ensure the Build SIG updates CMake parameters with the new version number.

- Successor task: [#7018]

Discord: [#sig-build](https://discord.com/channels/805939474655346758/816043576034328636)
Build SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Build SIG meeting agendas: [GHI](https://github.com/o3de/sig-build/issues)

**Comment by forhalle** [comment]
This is required by EOD today 1/21.

**Comment by forhalle** [comment]
I asked @Ulrick28 if this is the work @AMZN-Phil is doing today.

**Comment by AMZN-alexpete** [comment]
Was this resolved by #6429?

**Comment by AMZN-alexpete** [comment]
This version appears to show correctly in the editor splash 
![image](https://user-images.githubusercontent.com/26804013/150619473-d1e8f730-013a-479e-bbd3-12bece71a7b0.png)

**Comment by amzn-changml** [comment]
Just an update, the parameters for `2111.2` were set as of 1/21. Feel free to close this if there are no further changes

**Comment by Ulrick28** [comment]
Closing as it has been verified the editor and installer show the correct version numbers.
