### ISSUE TITLE
Project with name containing over 25 characters creates a gap between tiles in the Project Manager

### ISSUE THREAD

**Issue by LB-PatrykKrajewski** [o3de/o3de#7067]
**Describe the bug**
Naming a project with over 25 characters creates a gap in the Project Manager between this particular tile and the next one.

**Steps to reproduce**
1. Create a project with name extending 25 characters.
2. Add another project which will be on the right side of the project created in step 1.

**Expected behavior**
A long project name is cut off.

**Actual behavior**
A long name moves the next tile so a gap between them appears.

**Screenshots/Video**

Long project name gap:
![long project name issue](https://user-images.githubusercontent.com/88180143/150498975-fa6fe6e7-e77e-4ba1-a443-3143829dafd5.jpg)

**Found in Branch**
Development (63d755b)
Stabilization/2111RTE installer

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600X
- GPU: AMD RX 5700 XT
- Memory: 16 GB

**Comment by AMZN-alexpete** [comment]
Fixed by PR #9228
