### ISSUE TITLE
Script Canvas: Nodes Stays Connected after Unpin and Save (Ctrl+S)

### ISSUE THREAD

**Issue by G13D** [o3de/o3de#7100]
**Describe the bug**
Nodes Stays Connected after Unpin and Save (Ctrl+S)

1. Unpin Nodes , Save   
2. Restart Editor
3. Open Script
4. See Error

**Expected behavior**
Unpinned and Disabled Node

**Screenshots/Video**

![SC1](https://user-images.githubusercontent.com/58872135/150630070-1716784e-bc5e-4e8c-a660-c5e6ef699381.png)

![V](https://user-images.githubusercontent.com/58872135/150630084-2dbad785-51c2-48ac-b3a6-cabb801508f8.png)

**Comment by pollend** [comment]
I have a comment that describes the problem here: https://github.com/o3de/o3de/issues/6111

**Comment by carlitosan** [comment]
![image](https://user-images.githubusercontent.com/82187351/151854754-d212108e-dad6-4f93-a991-56e15414f1f9.png)

I was unable to reproduce this in development as of 25878f9487 . Are the repro steps correct? I was able to save connected and enabled nodes. Then I disconnect them, and disabled the last one, and saved again, closed graph. When I re-opened the graph, the nodes were still disconnected and disabled as desired.

**Comment by G13D** [comment]
> ![image](https://user-images.githubusercontent.com/82187351/151854754-d212108e-dad6-4f93-a991-56e15414f1f9.png)
> 
> I was unable to reproduce this in development as of [25878f9](https://github.com/o3de/o3de/commit/25878f9487f8f562a8fa7e2ebb7a437cd44a3002) . Are the repro steps correct? I was able to save connected and enabled nodes. Then I disconnect them, and disabled the last one, and saved again, closed graph. When I re-opened the graph, the nodes were still disconnected and disabled as desired.

Correct , this only are  in Release Versions as i didn't saw it in later Nightly builds , after 2111.1 is Released...
