### ISSUE TITLE
Feature Request: Add support for Project to reference external gems via an identifier

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#7108]
**Is your feature request related to a problem? Please describe.**
When a gem is registered with one of the O3DE manifest files(project.json, engine.json, o3de_manifest.json) it does so by registering it's path within the "external_subdirectories" array field of those manifest files.
If the gem is registered within the engine.json or project.json its path is stored relative to those files if the gem resides within the engine or project respectively.
Otherwise an absolute path is stored.
The issue is that for gems that are not within a subdirectory within an engine or project, there is no portable way to reference that gem in the O3DE object.

Below are several options for solving for trying to improve portability

**Describe the solution you'd like**
 Register the gem name as an identifier in the "project.json" or "engine.json"

This approach involves having a level of indirection for a project or engine to reference a gem by name instead of bypath,
It uses the gem_name as an "identifier" .
This would work in a similar manner to how the project.json references the engine via the "engine" key identifier, which corresponds the "engine_name" field inside of the engine.json.
In order to keep backwards compatibility, the introduction of "gems_name" key can be added to the project.json and engine.json.
The "gem_names" key will be used to look up the paths of gems registered in any of the o3de manifest files.
Candidate Manifest Files `project.json`, '`engine.json`, `o3de_manifest.json`

### project.json
```json
{
    "project_name": "NewProject",
    "engine": "o3de-sdk",
    "external_subdirectories": [
        "Gems/IComeWithTheProject"
    ],
    "gem_names": [
        "KytheraAI"
    ]
}
```
### o3de_manifest.json
```json
{
    "projects": [
        "D:/NewProject"
    ],
    "external_subdirectories": [
        "C:/Users/newuser/.o3de/Gems/KytheraAI",
        "C:/Users/newuser/.o3de/Gems/PopcornFX"
    ]
}
```

**Describe alternatives you've considered**
Add support for a URI scheme when parsing the "external_subdirectories" field. This URI scheme can be used to reference gems in the o3de_manifest.json without using an absolute path

### project.json
```json
{
    "project_name": "NewProject",
    "engine": "o3de-sdk",
    "external_subdirectories": [
        "Gems/IComeWithTheProject",
        "manifest://KytheraAI"
    ]
}
```

**Additional context**
The biggest issue this addresses, is the ability to portabilty share a project with other users, without having the project.json registered with an absolute path to external gems it references. By referencing the "gem_name" as an identifier, the project maintainer can share the project with other users, without requiring the users to re-register external gems with the project after receiving the project.
As long as the user has the external gem registered in any manifest file, including the o3de_manifest.json, those gems can reside anywhere on disk.

**Comment by AMZN-alexpete** [comment]
In the case where a team distributes a project and gems via the same source control, would they be able to register the gem as an external_subdirectory entry in their project like this?

project.json
```
{
    "gem_names": [
        "KytheraAI"
     ],
    "external_subdirectories": [
        "../relative/path/to/KytheraAI"
    ]
}
```

**Comment by lumberyard-employee-dm** [comment]
> In the case where a team distributes a project and gems via the same source control, would they be able to register the gem as an external_subdirectory entry in their project like this or do they even need the "gem_names" entry?
> 
> **project.json**
> 
> ```
> {
>     "gem_names": [
>         "KytheraAI"
>      ],
>     "external_subdirectories": [
>         "../relative/path/to/KytheraAI"
>     ]
> }
> ```

The "external_subdirectories", functionally still works as is.
So a team can still register paths in which the project isn't a prefix of to the "external_subdirectories" key and it will still work.
In that case, as you surmised, the "gem_names" entry wouldn't be needed.
The "gem_names" entry is only needed for gems registered in a manifest outside of the `project.json` and `engine.json` for the current project or engine, which just happens to only be the `o3de_mainfest.json` for now.
