### ISSUE TITLE
It is possible to launch multiple instances of Project Manager from the Editor

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#7112]
**Describe the bug**
It is possible to launch multiple instances of Project Manager from the Editor when using "New Project..." or "Open Project..." button multiple times. Issue occurs on both Linux and Windows. 

**Steps to reproduce**
1. Open the Editor.
2. Navigate to File -> New Project...
3. Once Project Manager launches repeat step 2.
4. Observe 2 instances of Project Manager running. 

**Expected behavior**
Project Manager window is brought on top of other windows if user attempts to open already running Project Manager. 

**Actual behavior**
New instance of Project manager is started instead.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/150799843-2b330ae3-3065-413d-b453-02e6f4534e50.mp4

**Found in Branch**
stabilization/2111RTE Installer

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Ryzen 3600
 - GPU NVidia RTX 2060 SUPER
 - Memory 16GB

**Comment by robhaco** [comment]
Still occurring as of dev 6/29
