### ISSUE TITLE
Editor crashes upon adding entity to Procedural Prefab via Landscape Canvas or Track View tools

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#7139]
**Describe the bug**
While the Focus Mode for a Procedural Prefab is enabled, creating an entity by using the Editor tools results in a crash. The issue occurs upon creation of a new sequence in the Track view tool or by creating a new graph in the Landscape Canvas tool.

The issue also occurs on Linux.

**Steps to reproduce**
1. Instantiate a procedural Prefab.
2. Enable the Focus Mode.
3. Launch the Track View tool.
4. Create a new sequence.

**Expected behavior**
The Editor remains stable. Creation of a new sequence is aborted.

**Actual behavior**
The Editor crashes.

**Call Stack Trace:**
```
25) 00007FF90F07B857 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FF9116751B0 (ntdll) : memset
23) 00007FF91165C766 (ntdll) : _C_specific_handler
22) 00007FF9116720CF (ntdll) : _chkstk
21) 00007FF911621454 (ntdll) : RtlRaiseException
20) 00007FF911670BFE (ntdll) : KiUserExceptionDispatcher
19) C:\o3de\o3de\Code\Editor\TrackView\TrackViewDialog.cpp (1050) : CTrackViewDialog::OnAddSequence
18) 00007FF8D7960DB9 (Qt5Core) : QObject::qt_static_metacall
17) 00007FF8D83C5DCF (Qt5Widgets) : QAction::activate
16) 00007FF8D849FD0D (Qt5Widgets) : QAbstractButton::click
15) 00007FF8D84A0A5D (Qt5Widgets) : QAbstractButton::mouseReleaseEvent
14) 00007FF8D8576D2F (Qt5Widgets) : QToolButton::mouseReleaseEvent
13) 00007FF8D83F7B02 (Qt5Widgets) : QWidget::event
12) 00007FF8D83D49B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
11) 00007FF8D83D28D0 (Qt5Widgets) : QApplication::notify
10) 00007FF8D7941B4A (Qt5Core) : QCoreApplication::notifyInternal2
 9) 00007FF8D83D5BC5 (Qt5Widgets) : QApplicationPrivate::sendMouseEvent
 8) 00007FF8D842088A (Qt5Widgets) : QSizePolicy::QSizePolicy
 7) 00007FF8D841E80E (Qt5Widgets) : QSizePolicy::QSizePolicy
 6) 00007FF8D83D49B0 (Qt5Widgets) : QApplicationPrivate::notify_helper
 5) 00007FF8D83D3A33 (Qt5Widgets) : QApplication::notify
 4) 00007FF8D7941B4A (Qt5Core) : QCoreApplication::notifyInternal2
 3) 00007FF8D7D834D1 (Qt5Gui) : QGuiApplicationPrivate::processMouseEvent
 2) 00007FF8D7D6EE89 (Qt5Gui) : QWindowSystemInterface::sendWindowSystemEvents
 1) 00007FF8D798AACA (Qt5Core) : QEventDispatcherWin32::processEvents
```

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/150975336-1228583d-7ec4-4206-a717-d03cd39934b9.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/e1cb40fa33a97b9fefe2cfd4a7cdff80e46d38cb)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Additional context**
[dump.zip](https://github.com/o3de/o3de/files/7933469/dump.zip)
[Editor.log](https://github.com/o3de/o3de/files/7933470/Editor.log)
[error.log](https://github.com/o3de/o3de/files/7933471/error.log)

**Comment by AMZN-daimini** [comment]
Got a repro locally, it is related to read-only entities.
When the TrackView tries to add a sequence to a procprefab, the prefab system correctly denies the creation of a new entity
![image](https://user-images.githubusercontent.com/82231674/151034777-d26932b7-e1ba-4022-b362-af66b50b30cc.png)
Apparently though the TrackView does not handle this failure correctly and crashes.

Looking into a better way to handle this (preventing the crash, and possibly just greying out the option to add a sequence?). Will check Landscape Canvas too.
