### ISSUE TITLE
Editor: Lua Editor tool window fails to close out when exiting Editor

### ISSUE THREAD

**Issue by dm-amzn** [o3de/o3de#7180]
**Describe the bug**
Editor: Lua Editor tool window fails to close out when exiting Editor.

**Steps to reproduce**
1. Launch the Editor
2. Create a new level, or load an existing level
3. Open Lua Editor tool (Tools > Lua Editor)
4. Exit and close out the Editor
5. Observe issue

**Expected behavior**
Tool windows close out when exiting the Editor

**Actual behavior**
Lua Editor tool window fails to close out when exiting Editor

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/97991771/151262876-36471692-7a2d-423f-b44e-dba42274e4d5.png)

**Found in Branch**
development b98bc34

**Comment by alexmontAmazon** [comment]
@AMZN-daimini , do you know if closing the LuaIDE is the correct behavior here or if it's meant to stand alone once opened?

**Comment by AMZN-daimini** [comment]
LUA Editor is a standalone tool, so it not closing alongside the Editor is the expected behavior.

**Comment by dm-amzn** [comment]
Verified as by design. Closing.
