### ISSUE TITLE
Asset Processor fails to process AutoComponent_RPC_NetLevelEntity.scriptcanvas job for AutomatedTesting project

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#7196]
**Describe the bug**
The following Script Canvas Process Job has failed:
`Levels/Multiplayer/Autocomponent_RPC/AutoComponent_RPC_NetLevelEntity.scriptcanvas`

Please note that the same issue is present for both Windows and Linux OS.

Please refer to the attached .log file for more information.

**Prerequisites**

- AutomatedTesting project is built.

**Steps to reproduce**

1. Launch the Asset Processor.
2. Wait until all assets are processed.

**Expected behavior**
All assets are processed without failures.

**Actual behavior**
The AutoComponent_RPC_NetLevelEntity.scriptcanvas job fails processing.

**Screenshots/Video**
Windows:
![AP_fail_PC](https://user-images.githubusercontent.com/86953659/151370153-f2d00254-7aab-453c-90ba-db9e8e91dd78.PNG)

Linux:
![AP_fail_Linux](https://user-images.githubusercontent.com/86953659/151370203-a6fde708-6e7e-41d0-9374-8d4b16663fb7.png)

**Found in Branch**
Development (e2c4c0e)

**Desktop/Device**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU: AMD Ryzen 5 3600
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 16GB

**Additional context**
[AutoComponent_RPC_NetLevelEntity.scriptcanvas-3262521804-19832.log](https://github.com/o3de/o3de/files/7950863/AutoComponent_RPC_NetLevelEntity.scriptcanvas-3262521804-19832.log)

**Comment by AMZN-Gene** [comment]
I'll investigate!

**Comment by AMZN-Gene** [comment]
I can't repro from Tuesday's build. commit ea55c6d5e5b30d995d8849c5aca43d2ecd0bc393, Tue Jan 25 16:56:58 2022
![image](https://user-images.githubusercontent.com/32776221/151425461-a5bed852-b35b-45bd-b064-13caa0b54836.png)

I'll grab latest and try again.

**Comment by AMZN-Gene** [comment]
Repro'd! I had to re-save \AutoComponent_RPC_NetLevelEntity.scriptcanvas.

**Comment by LB-KacperKapusta** [comment]
Closing the issue. Verified as fixed in Development (e19dc40) for both Windows and Linux OS.
