### ISSUE TITLE
Gem Catalog text not formatted correctly

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#7223]
**Describe the bug**
When opening the Project Manager from the Editor main menu `Edit Project Settings` option, the Gem Catalog text is not formatted correctly and difficult to read

**Steps to reproduce**
1. Open the Editor
2. Click on `File`->`Edit Project Settings` 
3. When the Project Manager opens, click on `Configure Gems`
5. See error

**Expected behavior**
The text is formatted the same as if you open the Project Manager from outside the Editor.

**Actual behavior**
The text is dark and difficult to read

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/26804013/151466951-e5765ab3-4a2f-4521-af34-fceead70fa79.png)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Comment by robhaco** [comment]
Confirmed this is still occurring as of dev 6/29
