### ISSUE TITLE
Feature Request: General O3DE AZ Component Template

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#7225]
**Is your feature request related to a problem? Please describe.**
The creation of AZ Components within O3DE could be streamlined with a template that the o3de.py create-from-template command can use to provide the file structure and needed for new users to create new component.

The [O3DE documentation](https://www.o3de.org/docs/user-guide/programming/components/create-component/)  shows an example have of how to have create a component, which I imagine most user would users copy-and-paste the snippets to get started.
Furthermore that documentation has several additional pages on how to specify component services, add EBus support and reflect the component for serialization. The documentation is not updated with the new practices for interfacing with components. (i.e Instead of a component acting as a notification bus handler, it can alternatively store [AZ::Events](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Module/ModuleManagerBus.h#L134-L135) which subscribers can register only for a specific event).

A template will also provide a better mechanism for developers to create components which uses newer best practices and paradigms. 

I believe most developers create a new component by copying and pasting an existing one and then adjusting from their.

**Describe the solution you'd like**
Having a component template within the [Templates](https://github.com/o3de/o3de/tree/development/Templates) directory that a user can instantiate to create a component a new component.
i.e
```
scripts\o3de.bat create-from-template -tn DefaultComponent -dp <Gem-Root>/Code
```

The template could contain the an interface file for communicating with the component across modules, as well as the implementation files
```
<template root>
    Include/
        ${Name}Interface.h or ${Name}Bus.h
   Source/
       ${Name}Component.h
       ${Name}Component.cpp
```

The inteface file itself could contain the following boilerplate
### ${Name}Interface.h
```cpp
#pragma once

#include <AzCore/EBus/EBus.h>

namespace ${SanitizedCppName}
{
    class ${SanitizedCppName}Requests
    {
    public:
        AZ_RTTI(${SanitizedCppName}Requests, "{${Random_Uuid}}");
        virtual ~${SanitizedCppName}Requests() = default;
        // Put your public methods here

       // Put notification events here
       //  void RegisterEvent(AZ::EventHandler<...> notifyHandler);
       // AZ::Event<...> m_notifyEvent1;
    };
    
    class ${SanitizedCppName}BusTraits
        : public AZ::EBusTraits
    {
    public:
        //////////////////////////////////////////////////////////////////////////
        // EBusTraits overrides
        using BusIdType = AZ::EntityId;
        static constexpr AZ::EBusHandlerPolicy HandlerPolicy = AZ::EBusHandlerPolicy::Multiple;
        static constexpr AZ::EBusAddressPolicy AddressPolicy = AZ::EBusAddressPolicy::ById;
        //////////////////////////////////////////////////////////////////////////
    };

    using ${SanitizedCppName}RequestBus = AZ::EBus<${SanitizedCppName}Requests, ${SanitizedCppName}BusTraits>;
    inline namespace ${SanitizedCppName}Interface
    {
        inline constexpr auto Get = [](${SanitizedCppName}BusTraits::BusIdType busId) {return ${SanitizedCppName}RequestBus::FindFirstHandler(busId); };
    }

} // namespace ${SanitizedCppName}
```

**Describe alternatives you've considered**
Have users Use AzAutoGen to generate the Component from XML.

**Additional context**
None

**Comment by willihay** [comment]
Ideas for types of components ( from @amzn-phist ) :
Game Component
Editor Component (relates to the Game Component)
Builder Component
System Component
Level Component
