### ISSUE TITLE
Linux: Mouse pointer disappears after defocusing Editor several times when Game Mode is enabled

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#7240]
**Describe the bug**
When the Game mode is enabled, defocusing the Editor several times results in the cursor disappearing, and displaying a pop up window claiming that the "O3DE Editor" is not responding, despite the Editor remaining functional.
Leaving the Game Mode or reloading the Ubuntu interface afterwards does not fix the issue. The Editor must be closed for the mouse pointer to be visible again.

Please note, that the mouse pointer disappears from the screen but is visible on the attached video capture.

**Steps to reproduce**
1. Launch the Editor.
2. Create a new level.
2. Enter the Game Mode.
3. Press Alt+Tab several times to switch focus between the Editor and another app.

**Expected behavior**
The mouse pointer is visible after defocusing the Editor.

**Actual behavior**
The mouse pointer is not visible on the screen after switching focus to another application.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/151559310-4088bacb-5d64-4ee5-9fa1-6b91b2cbfac5.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/e19dc409946fcc0223d00910b23724168d7dec0f)

**Desktop/Device:**
- Device: PC
- OS: Ubuntu
- Version 20.04
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by monroegm** [comment]
@LB-BartoszDudzinski did you attach the correct video?

**Comment by LB-BartoszDudzinski** [comment]
@monroegm hello! Yes, as I have mentioned in the description, the mouse pointer is visible in the video but not visible on the monitor screen.

**Comment by spham-amzn** [comment]
Issue resolved with the above mentioned PRs

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in Development and Stabilization branches.
