### ISSUE TITLE
Eye material type

### ISSUE THREAD

**Issue by santipaprika** [o3de/o3de#7247]
**Is your feature request related to a problem? Please describe.**
Rendering eyes realistically is hard to achieve with the current material types available in O3DE, because there are many visual features that are specific to the nature of eyes, like the cornea refraction, wetness, pupil aperture, etc.

**Describe the solution you'd like**
Add a new Eye material type supporting the features mentioned above (among others) and exposing artist-friendly parameters in the material inspector.

Most engines have a specific shader for eyes ([Unity](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.2/manual/eye-shader.html), [UE](https://docs.unrealengine.com/4.27/en-US/Resources/Showcases/PhotorealisticCharacter/), [Cryengine](https://docs.cryengine.com/display/CEMANUAL/Eye+Shader)). 
There are many ways to gather the information necessary to render the eyes properly. I propose the following approach:
- The eye textures must be iris-centered (see [Unity](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.2/manual/eye-shader.html))
- Use separate textures for the sclera and the iris (see [Unity](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.2/manual/eye-shader.html))
- The eye geometry must be spherical with a bulb in the front part (cornea) or use a cornea-specific normal map (see [Cryengine](https://docs.cryengine.com/display/CEMANUAL/Eye+Shader)).
- The iris depth position is exposed to let the user calibrate it properly. Alternatively, the distance between the cornea and the iris could be fetched from a precomputed texture.
- Use a separate mesh with a texture encoding reflections occlusion (eyelids, etc) and AO (see [UE](https://docs.unrealengine.com/4.27/en-US/Resources/Showcases/PhotorealisticCharacter/)).
- Use meshes for wetness (see [Cryengine](https://docs.cryengine.com/display/CEMANUAL/Eye+Shader)).

Simpler parameters to expose:
- Refraction strength
- Pupil radius
- Sclera/Iris roughness
- Sclera/Iris specularity
- ...

**Describe alternatives you've considered**
A workaround to render realistic eyes with the EnhancedPBR material could be to use two separate meshes, one for the cornea (with the bulb) and one for the sclera/iris. An additional pass might be required to apply the corresponding refraction/lighting to the iris region depending on the cornea normal at that point, making the process a bit cumbersome. Furthermore, other features like the pupil aperture would need even more complex operations to be achieved.

**Comment by santipaprika** [comment]
I am currently working on this feature (in [this branch](https://github.com/santipaprika/o3de/tree/eye-shader)).

**Comment by santipaprika** [comment]
Demo showing the progress on this work:

https://user-images.githubusercontent.com/44426596/154351985-6a73039c-6157-44ca-a78e-1554744d3485.mp4



The main reference is the [Next Generation Character Rendering](http://www.iryoku.com/stare-into-the-future) presentation by Jorge Jimenez. Also, the eye shaders of other popular engines have been explored to check the parameters being used.

**Comment by superkitcath** [comment]
Assigning to you, @santipaprika, as per @thefranke's message. Thanks!

**Comment by santipaprika** [comment]
Closing this as the PR associated to it just got merged.
