### ISSUE TITLE
Multiplayer gem: "connect" command doesnt accept IPv4 or even localhost

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#7258]
**Describe the bug**
Using o3de-multiplayersample, I am connecting a client to the server via server ip address. However, "connect <ip-address>" doesn't work.

**Steps to reproduce**
1. Using o3de-multiplayersample setup
2. Launch the server
3. Launch the client
4. Note the server ip address
5. Open imgui console on the client and run: "connect <server-ip-address>"

**Expected behavior**
"connect" command should connect the client to the desired server on the given ip address.

**Actual behavior**
The "connect" command returns "Remote address 192.168.4.22 was malformed". The same errors with "localhost" as well.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/5432499/151619894-3cf134f6-7965-4622-9b13-58b8c477e6af.png)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 21.10

**Comment by AMZN-Gene** [comment]
Workaround is to use the cl_serverAddr before calling connect.

**Comment by AMZN-Olex** [comment]
I think I found the cause: connect require both ip and the port number.
