### ISSUE TITLE
MultiplayerSample project, the game process cannot exit and enter infinite loop

### ISSUE THREAD

**Issue by xiapeng78** [o3de/o3de#7270]
**Describe the bug**
Windows platform, MultiplayerSample project, the game process cannot exit and enter infinite loop
This issue is related with issue #7272

**Steps to reproduce**
1. Open MultiplayerSample.ServerLauncher.exe, and the process is running.
2. Click on close button on window. The window of process is closed.
3. Open the task manager, we can find the process is still running in the background. And the CPU utilization of this process is 100%.

**Found in Branch**
The latest code of development branch.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel i7-10700]
 - GPU [NVidia 1650]
 - Memory [32GB]

**Problem analysis**
We found the infinite loop is at the procedure of the destructor of the globle variable 'g_ignoredAsserts'.
And we do some modifications show blow, the problem solved.
In Trace::Destroy() function:
Modify
g_ignoredAsserts.Reset();
to
g_ignoredAsserts->clear();

**Comment by lmbr-pip** [comment]
Assign to @AMZN-Olex to triage and see if related to known issues relating to processes remaining in the background.
