### ISSUE TITLE
[Material Editor] A crash happened when clicking a material file in Asset Browser within Editor to open it in the Material Editor.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#7274]
**Describe the bug**
A clear and concise description of what the bug is. Try to isolate the issue to help the community to reproduce it easily and increase chances for a fast fix.

**Steps to reproduce**
1. Open O3DE.sln with Visual Studio 2019.
2. Set Editor as startup project.
3. Press F5 to start debug Editor.
4. When Editor is ready, click on 'Tools -> Material Editor' to open Material Editor.
5. Wait for a few seconds, then Material Editor is ready to work.
6. Browse files in Asset Browser within Editor, click a material file to view its content in Material Editor.
7. Check Process View in Visual Studio 2019, a second Material Editor process is running and failing to exit.
8. See error in Visual Studio 2019.

**Expected behavior**
The second Material Editor process could exit after its job is done.

**Actual behavior**
The second Material Editor process fails to exit normally. It crashed at end of `~AtomToolsApplication()` in AtomToolsApplication.cpp.

**Assets required**
NA

**Screenshots/Video**
NA

**Found in Branch**
development
main
stabilization/2111RTE

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I9-9900k]
 - GPU [NVidia RTX 3090]
 - Memory [32GB]

**Additional context**

**Comment by gadams3** [comment]
This is not occurring in the latest development branch

**Comment by Jackie9527** [comment]
> 

If debugging Editor with [Microsoft Child Process Debugging Power Tool](https://marketplace.visualstudio.com/items?itemName=vsdbgplat.MicrosoftChildProcessDebuggingPowerTool) enabled, and follow my repo steps, then crash would show up.

**Comment by any1way** [comment]
Add issure pic：
![20220421-222122](https://user-images.githubusercontent.com/5445138/164480749-3a4d7302-9761-4e78-b1ae-87c0bf2af39f.png)
![20220421-222156](https://user-images.githubusercontent.com/5445138/164480782-8847f050-5409-4324-bfce-29d891d5d732.png)
