### ISSUE TITLE
3rdParty::md5 could be replaced by algorithm functions provided by 3rdParty::OpenSSL.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#7280]
**Is your feature request related to a problem? Please describe.**
3rdParty::md5 is simple but redundant.
3rdParty::OpenSSL is powerful and already integrated within 3rd-party libraries. And it provides the same functions as 3rdParty::md5 does.

**Describe the solution you'd like**
Replace 3rdParty::md5 by 3rdParty::OpenSSL.

**Describe alternatives you've considered**
Follow the guides [MD5](https://www.openssl.org/docs/man1.1.1/man3/MD5.html), the functions, that are dependent on 3rdParty::md5, could be reimplemented.

**Additional context**

**Comment by spham-amzn** [comment]
OpenSSL is a dependency for AzNetworking and Gridmate at the moment.  Atom/RHI and CrySystem has a dependency on MD5. I'd be reluctant to make OpenSSL a dependency of Atom just for Md5

**Comment by spham-amzn** [comment]
The MD5 library is really just a single .c file that was compiled separately into a lib. An alternative to this is to add md5.c as a source compile into the something like AzFramework or AzCore

**Comment by Jackie9527** [comment]
> The MD5 library is really just a single .c file that was compiled separately into a lib. An alternative to this is to add md5.c as a source compile into the something like AzFramework or AzCore

With [-fdata-sections](https://www.keil.com/support/man/docs/armclang_ref/armclang_ref_ysm1476093575636.htm) and [-ffunction-sections](https://www.keil.com/support/man/docs/armclang_ref/armclang_ref_sam1445342406709.htm), compiler could remove unused function and data from target dll/so/exe.
So, it's not a big deal to have a dependance upon a lib such as OpenSSL.

**Comment by Jackie9527** [comment]
`3rdParty::md5` is removed according to #14849.
