### ISSUE TITLE
Viewport is not loading after creating level

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#7285]
**Describe the bug**
Creating a level does not load the Viewport, which stays grayed out. The Editor is responsive as entities can be added to the level. The workaround for this issue is to reload the level.

**Steps to reproduce**
1. Launch the Engine.
2. Create a level.

**Expected behavior**
The new level is loaded in the Viewport.

**Actual behavior**
The Viewport stays gray and does not update its contents.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/151795445-1cfc7403-9dac-4613-86dd-a16bf319702c.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/79f4fee96014d7b4c7508fd00ef6ca059f7f8034)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by alexmontAmazon** [comment]
@hultonha not sure if this is editor or viewport. What do you think?

**Comment by cgalvan** [comment]
> @hultonha not sure if this is editor or viewport. What do you think?

I think this due to my recent performance fix, checking real quick

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in Development.
