### ISSUE TITLE
Linker Warnings

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#7326]
**Describe the bug**
Compiling the Editor results in linker warnings 

**Steps to reproduce**
1. Build Editor
2. Notice linker warnings
```
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library 
[C:\prj\o3de\build\External\ImageProcessingAtom-f29376cd\Code\ImageProcessingAtom.Editor.vcxproj]        
 LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library  
[C:\prj\o3de\build\External\AtomToolsFramework-3623ae96\Code\AtomToolsFramework.Editor.vcxproj]
```
**Expected behavior**
No linker warnings

**Actual behavior**
Linker warnings in various (Atom, Lua, Editor) vcprojects

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32776221/152025474-4078db7a-e2af-465b-a51e-d4acf35f4a16.png)

**Found in Branch**
2/1/2022 development branch

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Comment by Jackie9527** [comment]
Same issue.
I think there is something wrong with new version of sqlite3.

**Comment by kreaninw** [comment]
I have the same issue. I am on Windows 11, CMake 3.23.0-rc1.

**Comment by amzn-changml** [comment]
We'll need to research this, but it may have something to do with the version of CMake. If anyone is experiencing this issue, please try this with the latest stable, non-release candidate version of CMake.

**Comment by AMZN-Gene** [comment]
I'm using cmake version 3.22.0

**Comment by dshmz** [comment]
CMake version has been upgraded to 3.24, the latest version should not have this issue.

**Comment by dshmz** [comment]
Also, it is a warning and not an error/bug, the warning could be due to an older version of CMake.

**Comment by Jackie9527** [comment]
> Also, it is a warning and not an error/bug, the warning could be due to an older version of CMake.

There is nothing wrong with cmake.

Here is the [problem](https://github.com/o3de/3p-package-source/blob/1d23ad1512a6e4edba5b50a721edf05fd7960420/package-system/sqlite/build_windows.cmd#L23).
```
call nmake /f ..\src\Makefile.msc TOP=..\src libsqlite3.lib DEBUG=0
```

When building sqlite, `USE_CRT_DLL=1` shoud be added to build options, to let dynamically link to the MSVC runtime library.
```
call nmake /f ..\src\Makefile.msc TOP=..\src libsqlite3.lib DEBUG=0 USE_CRT_DLL=1
```

Here is the [comments](https://github.com/sqlite/sqlite/blob/3f4795a391597456f260f38012aa5cd8f26b4924/Makefile.msc#L127) from source code of sqlite.
```
# Set this non-0 to dynamically link to the MSVC runtime library.
#
!IFNDEF USE_CRT_DLL
USE_CRT_DLL = 0
!ENDIF
```
