### ISSUE TITLE
Script Canvas: Container Element Node Warnings

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#7335]
**Describe the bug**
The HasElements and GetFirstElements nodes in my script canvas graph is causing warnings in the Editor console when saving. The warnings seem harmless since the script still runs fine.

**Steps to reproduce**
1. Add this script to AutomatedTesting project
[AutoComponent_RPC_NetLevelEntity.zip](https://github.com/o3de/o3de/files/7982706/AutoComponent_RPC_NetLevelEntity.zip)
2. Open script, move a node (or something minor to allow saving), and save the graph
3. See warnings in the Editor console
```
[Warning] (Script Canvas) - SlotId {2E76F3FD-28FB-4ADA-95EE-8FA5713799B4} is not a part of Node Get First Element
[Warning] (Script Canvas) - SlotId {81D263BA-CEAB-4EFB-806C-4432387D5232} is not a part of Node Get First Element
[Warning] (Script Canvas) - SlotId {BB719F1B-D39D-4277-9685-0777F02A7656} is not a part of Node Has Elements
[Warning] (Script Canvas) - SlotId {7E993D2D-4E90-4082-84B8-FFD976E2430A} is not a part of Node Has Elements

```
**Expected behavior**
No warnings

**Actual behavior**
[Warning] (Script Canvas) - SlotId {2E76F3FD-28FB-4ADA-95EE-8FA5713799B4} is not a part of Node Get First Element
[Warning] (Script Canvas) - SlotId {81D263BA-CEAB-4EFB-806C-4432387D5232} is not a part of Node Get First Element
[Warning] (Script Canvas) - SlotId {BB719F1B-D39D-4277-9685-0777F02A7656} is not a part of Node Has Elements
[Warning] (Script Canvas) - SlotId {7E993D2D-4E90-4082-84B8-FFD976E2430A} is not a part of Node Has Elements

**Assets required**
[AutoComponent_RPC_NetLevelEntity.zip](https://github.com/o3de/o3de/files/7982706/AutoComponent_RPC_NetLevelEntity.zip)

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32776221/152072271-0a4419bc-4189-453b-bfa9-d6271c6d267f.png)

**Found in Branch**
Feb/1/2021 development branch

**Comment by LB-KatarzynaDylska** [comment]
We encountered a similar problem on the stabilization build (https://github.com/o3de/o3de/commit/9b1b23c0593aaaa04891c2d3eb524b5e7ae8539e) on Windows and Linux. The issue can be reproduced on a default project using the following repro steps:
1. Open Script Canvas.
2. Create a new script: On Entity Activated->Print.
3. Connect the Entity output from On Entity Activated to Print as input.
4. Change the Print node to accept no inputs and just print text, e.g. "Test".
5. Save the script in the project folder.

The script works as expected, but this results in warnings being printed to the console:

```
[Warning] (Script Canvas) - SlotId {0270281A-2C30-4CD9-A994-0645A441EA99} is not a part of Node Print
[Warning] (Script Canvas) - SlotId {0270281A-2C30-4CD9-A994-0645A441EA99} is not a part of Node Print
```

![warnings](https://user-images.githubusercontent.com/99388484/232016019-8eb3dffb-5ea0-4930-bf27-37602e7eff00.png)

Should we reopen this issue or file a new one?
