### ISSUE TITLE
Linux: mouse_button_right and mouse_button_middle inputs are inverted

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#7342]
**Describe the bug**
The _mouse_button_right_ and _mouse_button_middle_ inputs are reverted in O3DE on Linux. 
This causes the events assigned to _RMB_ to be fired after pressing _MMB_ and vice-versa.

Please note that the issue does not occur on Windows.
Please refer to the attached video for more details.

**Steps to reproduce**
1. Open any level.
2. Launch _Asset Editor_ and create a new _Input Bindings_ file with an event assigned to _mouse_button_right_ and another event assigned to _mouse_button_middle_ (refer to screenshots or attached files).
3. Assign the created _Input Bindings_ to any entity.
4. Launch _Script Canvas_ and create a graph which prints any text on the created event pressed actions (refer to screenshots or attached files).
5. Enter Game Mode.
6. Press the _Right Mouse Button_.
7. Press the _Middle Mouse Button_.

**Expected behavior**
The _mouse_button_right_ and _mouse_button_middle_ events are fired after pressing correct corresponding inputs.

**Actual behavior**
The _mouse_button_right_ and _mouse_button_middle_ inputs are reverted. 

**Assets required**
[mouse_inputs.zip](https://github.com/o3de/o3de/files/7985319/mouse_inputs.zip)

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/152132214-bd8922b8-947b-44bf-8ec6-b3e034216075.mp4

![input_bindings](https://user-images.githubusercontent.com/86953108/152132246-d4cae441-7f61-4146-851f-fdbb16a101dc.png)

![script_canvas](https://user-images.githubusercontent.com/86953108/152132254-1f206656-7bed-4924-835f-1baf2465eb29.png)

**Found in Branch**
Development (d6c419d)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version 20.04 LTS
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by monroegm** [comment]
Need to find an owner for input

**Comment by monroegm** [comment]
Moving to SIG-Platform as this is a specific Linux issue with the input system

**Comment by LB-TomaszSerwanski** [comment]
Fix verified in Development (b4b7e5a).
