### ISSUE TITLE
Lua Editor: Prev Document Tab option from the View menu is misspelled

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#7345]
**Describe the bug**
In the Lua Editor View menu the "Prev Document Tab" option is misspelled, it should be called "Previous Document Tab". It should also be noted that none of the other options in the Lua Editor View menu are shortened.

**Steps to reproduce**
1. Go to Tools > Lua Editor.
2. Open the View dropdown menu and check the "Prev Document Tab" option.

**Expected behavior**
The option is called "Previous Document Tab".

**Actual behavior**
The option is called "Prev Document Tab".

**Screenshot**
![PrevDocumentTab](https://user-images.githubusercontent.com/86952082/152146405-27f9ff39-eeaf-4cf8-8bb5-153f0ca8a1b0.png)

**Found in Branch**
Development (d6c419d)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by suryanshsangwan** [comment]
working on it

**Comment by guillaume-haerinck** [comment]
closed by https://github.com/o3de/o3de/pull/7402
