### ISSUE TITLE
Linux: CameraController_AutomaticDemo.scriptcanvas fails in the Asset Processor

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#7350]
**Describe the bug**
The Levels/MotionMatching_AutomaticDemo/CameraController_AutomaticDemo.scriptcanvas from MotionMatching Gem fails in the Asset Processor.

Please note that the issue does not occur on Windows.
Please refer to the attached log file and screenshot for more details.

**Steps to reproduce**
1. Create and build a Project with the MotionMatching Gem enabled.
2. Launch the Editor.

**Expected behavior**
All assets are successfully processed by the Asset Processor.

**Actual behavior**
The CameraController_AutomaticDemo.scriptcanvas fails in the Asset Processor.

**Assets required**
N/A

**Screenshots/Video**

![image (2)](https://user-images.githubusercontent.com/86953108/152169644-b3d6b4b8-b7f7-4bc7-96aa-0c3481325791.png)

**Found in Branch**
Development (d6c419d)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version 20.04 LTS
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Attachments**
[CameraController_AutomaticDemo.scriptcanvas-311243051-14051.log](https://github.com/o3de/o3de/files/7987132/CameraController_AutomaticDemo.scriptcanvas-311243051-14051.log)

[CameraController_AutomaticDemo_VM.txt](https://github.com/o3de/o3de/files/8013927/CameraController_AutomaticDemo_VM.txt)

**Comment by amzn-jillich** [comment]
@lsemp3d for awareness

**Comment by FuzzyCarterAWS** [comment]
[CameraController_AutomaticDemo_VM.lua](https://github.com/o3de/o3de/files/8007011/CameraController_AutomaticDemo_VM.txt)

**Comment by FuzzyCarterAWS** [comment]
I was unable to repro this on my Linux machine.

@LB-TomaszSerwanski , can you confirm that this isn't still an issue on your end?

If it is, can you find the debug .lua under `o3de\AutomatedTesting\user\Cache\DebugScriptCanvas2LuaOutput` and attach it to this issue?

**Comment by LB-TomaszSerwanski** [comment]
@FuzzyCarterAWS yes, it still occurs on our machines. I have attached the requested file into the issue
([CameraController_AutomaticDemo_VM.txt](https://github.com/o3de/o3de/files/8013931/CameraController_AutomaticDemo_VM.txt)). 
Please note that we have used the Pre-built SDK to build the engine and created a brand new project with the MotionMatching Gem enabled.

**Comment by carlitosan** [comment]
local Result_output_scvm = (1,000000 * Number_input_scvm)

The to string result coming out with a comma is causing the trouble.

**Comment by LB-TomaszSerwanski** [comment]
Fix verified in Development (a3ebe61).
