### ISSUE TITLE
Entity Outliner , UI , Prefab

### ISSUE THREAD

**Issue by G13D** [o3de/o3de#7361]
More Prefabs in Entity Outliner makes visual effect like blurred italic text ,  also not the best font for render...

**Describe the solution you'd like**
i would prefer an font that takes short space This will Reduce eye fatigue and not much bold not much curved also if font  design has specific forms little bit for people who has dyslexia symptoms...

 prefabs has two Separating visual feedback this (  ) and italic text looks cool but italic font slowing My interacting process on Entity Outliner...

**Additional context**
also maybe modular asset creators find hard to read their asset names...

![image](https://user-images.githubusercontent.com/58872135/152235736-ba6873bc-5fbe-4d4e-8074-f2b5e12e2123.png)
https://www.gamedeveloper.com/design/skyrim-s-modular-approach-to-level-design

**Comment by monroegm** [comment]
We would need a spec from @o3de/sig-ui-ux to move forward with this
