### ISSUE TITLE
UI Editor: Slice Library appears empty with all of the requisite Gems added

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#7366]
**Describe the bug**
Slice Library appears empty with all of the requisite Gems added. If the user wishes to instantiate one of the premade UI slices, they can do so through _New > Element from Slice Browser..._ but _New > Element from Slice Library_ appears empty.

**Steps to reproduce**
1. Launch the Editor with the AutomatedTesting project active (this has all needed Gems already configured).
2. Launch the UI Editor (Tools > UI Editor).
3. Right-click on the empty canvas area, and select New > Element from Slice Library

**Expected behavior**
Slices from the UiBasics Gem are populated and selectable by the user.

**Actual behavior**
Slice Library appears empty.

**Found in Branch**
development@5509764fc2b793

**Additional context**
The UiBasics Gem appears enabled as a dependency of the LyShine Gem.

**Comment by monroegm** [comment]
@michabr FYI

**Comment by jckand-amzn** [comment]
Took a look this morning, and I am no longer able to reproduce the issue with a clean cache on development@d0e5f9d20b4555070540838cc456face3838d5b0. Closing out.
