### ISSUE TITLE
Model Materials are not updated in the Viewport upon their removal until the last slot is removed

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#7397]
**Describe the bug**
Removing Model Materials from their slots in the Material component is not reflected in the Viewport until the last material slot is removed. Note that the Model Materials are updated properly when performing Undo/Redo actions.

The issue occurs for both Windows and Linux version of the Editor.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Add an .fbx asset with more than 1 Model Material slot to the level.
2. Assign the Model Materials to their slots in the Material component of the added entity.
3. Remove the assigned Materials from the slots while inspecting the model in the Viewport.

**Expected behavior**
The model in the Viewport is updated on each Model Material removal.

**Actual behavior**
The model is the Viewport is only updated on the last Model Material removal or when performing Undo/Redo actions.

**Assets required**
[chicken.fbx.zip](https://github.com/o3de/o3de/files/7994298/chicken.fbx.zip)
[4mat.fbx.zip](https://github.com/o3de/o3de/files/7994302/4mat.fbx.zip)

**Video**

https://user-images.githubusercontent.com/86953659/152339843-0835435d-66cb-49e1-93b1-af56413fd98e.mp4

**Found in Branch**
Development (611598c)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i5-9600K
 - GPU: Nvidia Geforce RTX 2070
 - Memory: 16GB

**Comment by gadams3** [comment]
resolved by this change https://github.com/o3de/o3de/pull/8628
