### ISSUE TITLE
[Project Manager] User wants to be able to type directly on the "Location" text field

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#7417]
**Describe the bug:**
_(Feedback from the walk the engine session with a customer)_

When creating a project in the Project Manager, when user types in a new project name, the "Location" text field below doesn't change its folder name to be the same as the project name user enters above. When users click on the "Location" field intended to type in the folder name, it doesn't nothing either. User has to click on the folder icon to trigger the window's folder selection dialog.

**Expected behavior/Acceptance criteria:**

1. User expected that when changing the project name, they would see the folder name is changed with the same name automatically. 
2. If the folder name for some reason already exists in the directory, the text field can change to red for error handling.
3. When clicking on the "Location" text field, it should allow user to type in directly. instead of doing nothing.

**To reproduce**
1. go through the regular creating a project workflow on Project Manager
2. change the project name to something else.
3. see the folder name still stays the same as the default project name from before.

**Comment by AMZN-alexpete** [comment]
This functionality has been implemented for a while now.
