### ISSUE TITLE
[Project Manager] Want to be able to view the full name of the Gem without click on it

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#7418]
**Describe the bug**
(Feedback from the walk the engine session with an external customer)

In the Gem Catalog page, there is no way to resize the column width when viewing the Gems. For those gems with long gem names, their names will be cut without ... due to the limited column width. User has to manually select those gems and view their names on the right hand panel, which isn't ideal, because user couldn't easily view all gem names in one view on the gem catalog page.

**Expected behavior/Acceptance criteria**
1. When user maximize the Gem Catalog page, the column should be expanded with the right proportion of the columns, where the column name can be displayed fully.
2. User should be able to adjust the column width on the column header.

**Comment by robhaco** [comment]
The gem name column can now be resized, closing this issue.
