### ISSUE TITLE
Write unit tests for PythonBindings methods

### ISSUE THREAD

**Issue by Ulrick28** [o3de/o3de#7420]
[Migrated from JIRA LYN-9779]
We need unit tests for the PythonBindings in Project Manager. Set as critical due to the amount of engineer time being lost for changes to the CLI causing a mismatch, breaking functionality in Project Manager,

Need to check that the functions exist and if possible have the correct (expected) number of parameters. Python functionality should already be tested in Python by their own unit tests, this task is for the binding to Project Manager only.

AC:

* Unit tests exist for all pythonbinding methods

**Comment by AMZN-nggieber** [comment]
Closed by #7552
