### ISSUE TITLE
Can not add a repository and then download gems

### ISSUE THREAD

**Issue by Ulrick28** [o3de/o3de#7421]
[Migrated from JIRA LYN-10008]
Can not add any repository or download gems.

*Steps to reproduce:*
 # Open Project Manager
 # Navigate to repositories
 # Attempt to add a repository (for example [https://downloads.popcornfx.com/o3de-repo])
 # If a repository already exists try navigating to the gem catalog and downloading a gem

*Expected result:*

Repository is added and available gems can be downloaded

*Actual result:*

A new repository can not be added. For existing repositories either available gems do not display or it is not possible to download them.

**Comment by AMZN-Phil** [comment]
This was due to some functions being removed accidentally during a large merge and has since been fixed.
