### ISSUE TITLE
Terrain: Newly created Terrain Spawner prefab displays incorrect Transform values when instantiated

### ISSUE THREAD

**Issue by dm-amzn** [o3de/o3de#7445]
**Describe the bug**
Newly created Terrain Spawner prefab displays incorrect Transform values when instantiated.
- Issue still occurs whether choosing to move or retain External Entity References

**Steps to reproduce**
1. Launch the Editor
2. Create a new level, or load an existing level
3. In Entity Outliner, add a Terrain World Renderer level component
4. Create a Terrain Spawner entity (with generated terrain)
5. Save Terrain Spawner Entity as a prefab
6. Delete the newly created Terrain Spawner prefab
7. Instantiate the newly created Terrain Spawner prefab
8. Observe issue

**Expected behavior**
Prefabs display original world position values when instantiated.

**Actual behavior**
Newly created Terrain Spawner prefab displays incorrect Transform values when instantiated.

**Screenshots/Video**
https://user-images.githubusercontent.com/97991771/152620548-ea11138b-ba33-46c8-b97f-c4a118e0e49c.mp4

**Found in Branch**
commit b98bc34eb1dd2e665a7228f6d66fd87d1b426a8a

**Comment by mcphedar** [comment]
This is as currently designed. Closing this. - Terrain Triage.
