### ISSUE TITLE
MaterialEditor crashed within the dtor of AssetPickerDialog.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#7453]
**Describe the bug**
MaterialEditor crashes within the dtor of AssetPickerDialog.

**Steps to reproduce**
1. Open MaterialEditor.
2. Open an existed material file, named like x.material.
3. Click to select a texture file for baseColor, then a dialog pops up.
4. Using VSCode or notepad to edit x.material outside MaterialEditor.
5. Make small changes to x.material, and save.
6. MaterialEditor pops a dialog, asks to confirm whether to reload x.material, then click 'yes'.
7. See error.

**Expected behavior**
No crash happens.

**Actual behavior**
MaterialEditor crashes within the dtor of pick material dialog.

**Assets required**
NA

**Screenshots/Video**
NA

**Found in Branch**
[117cb11](https://github.com/o3de/o3de/commit/117cb11505e008f841be1672c5dc72f7e8e31d23) on development.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I9-9900k]
 - GPU [NVidia RTX 3090]
 - Memory [32GB]

**Additional context**

**Comment by gadams3** [comment]
Resolved by this change https://github.com/o3de/o3de/pull/8625
