### ISSUE TITLE
It is possible to modify a Prefab entity without being in its Focus Mode using the Pinned Inspector

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#7455]
**Describe the bug**
If the User opens the _Pinned Inspector_ for an entity inside the Prefab when being in its _Focus Mode_, the entity can still be edited even after exiting the _Focus Mode_.

Please note that editing the entity this way does not dirty the Prefab (there is no indication of unsaved changes on the Prefab). Also, there is no _Save Prefab to file_ option in the right-click context menu of the Prefab.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Open any Level.
2. Create an entity.
3. Make a Prefab out of the entity.
4. Enter the _Focus Mode_ of the Prefab.
5. RMB the entity inside the Prefab and select _Open Pinned Inspector_.
6. Exit the _Focus Mode_ of the Prefab.
7. Add a new Component to the entity using the _Pinned Inspector_

**Expected behavior**
It is not possible to modify an entity inside the Prefab without being in the Prefab's _Focus Mode_.

**Actual behavior**
It is possible to modify an entity inside the Prefab without being in the Prefab's _Focus Mode_ using the _Pinned Inspector_.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/152804699-24d748ce-8d31-4b75-abb1-c735f03225f3.mp4

**Found in Branch**
Development (b1df4c9)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by jjjoness** [comment]
@AMZN-daimini @srikappa-amzn @rainBJ I am looking at this and wanted to get a definitive way this should be fixed.

**Comment by AMZN-daimini** [comment]
> 1. the pinned window should be greyed out when the prefab looses focus and when focus is back make it editable again.

This is how I would fix it, yes.

Do note that the pinned property editor should be disabled in two separate cases

- the pinned entity is not in the focused branch of the entity hierarchy (Editor Focus Mode)
- the pinned entity is a child of a closed container (Container Entities)

Both of these are editor concepts, please use the editor-side interfaces and not the prefab ones to add those checks :D

**Comment by jjjoness** [comment]
@AMZN-daimini Thanks for that, I'll fix it that way.

**Comment by LB-TomaszSerwanski** [comment]
Fix verified in Development (df44775).
