### ISSUE TITLE
Undoing the Unparent action on an entity inside the Prefab crashes the Editor

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#7456]
**Describe the bug**
Unparenting an entity inside the Prefab results in it being reparented to the Level entity and multiple errors and warnings to appear in the Console (refer to Editor.log file).

Additionally, undoing such action crashes the Editor.

Please note that the error.log or .dmp files are not generated after the crash.
Refer to the attached video file for more details.

**Steps to reproduce**
1. Open any level.
2. Create an entity.
3. Make a Prefab out of the entity.
4. Enter the _Focus Mode_ of the Prefab.
5. Select the entity inside the Prefab.
6. Click the _X_ button in the _Parent_ section of the _Transform_ component in the _Entity Inspector_.
7. Press _CTRL+Z_ or select _Edit_ -> _Undo_.

**Expected behavior**
No errors or warnings appear in the Console. The Editor remains stable. 

**Actual behavior**
Multiple errors and warnings appear in the Console. The Editor crashes.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/152806671-1b5c618c-5cee-4517-b6bf-9735f9d013d1.mp4

**Found in Branch**
Development (b1df4c9)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Attachments**
[Editor.log](https://github.com/o3de/o3de/files/8015987/Editor.log)

**Comment by alexmontAmazon** [comment]
@AMZN-daimini , could you have a look at this please? :)

**Comment by AMZN-daimini** [comment]
Could repro, trying to figure out what's going wrong :)

**Comment by LB-TomaszSerwanski** [comment]
Fix verified in Development (a3ebe61).
