### ISSUE TITLE
Terrain: Editor crash occurs when adding both Physics Heightfield Collider and Terrain Physics Heightfield Collider components

### ISSUE THREAD

**Issue by dm-amzn** [o3de/o3de#7466]
**Describe the bug**
Editor crash occurs when adding both Terrain Physics Heightfield Collider and Physics Heightfield Collider components.
- Issue occurs when adding either component first.
- No callstacks/dumps generated.

**Steps to reproduce**
1. Launch the Editor
2. Create a new level, or load an existing level
3. In Entity Outliner, add a Terrain World Renderer level component
4. Create a Terrain Spawner entity (with generated terrain)
5. In Terrain Spawner entity, add a PhysX Heightfield Collider component
6. Observe component dependecy warning
7. Click on Add Required Component button
8. Select the Terrain Physics Heightfield Collider
8. Observe issue

**Expected behavior**
Editor is stable.

**Actual behavior**
Editor crash occurs when adding both Physics Heightfield Collider and Terrain Physics Heightfield Collider components.

**Screenshots/Video**
![Capture](https://user-images.githubusercontent.com/97991771/152869963-42868bba-9f86-4292-bfde-4ffb24f5cbc1.JPG)

**Found in Branch**
commit b98bc34eb1dd2e665a7228f6d66fd87d1b426a8a

**Comment by jckand-amzn** [comment]
Does this still occur for you @dm-amzn ? I'm able to add both components without issue on development@d16a742b8ade1b1e0d20aefd877cf106150fc2a7.

**Comment by dm-amzn** [comment]
Nope, I'm seeing a different issue now but it's no longer yeilding a crash. We can close this one out.
