### ISSUE TITLE
default skybox does not appear in level when running game launcher

### ISSUE THREAD

**Issue by Broganab** [o3de/o3de#7479]
**Describe the bug**
default skybox does not appear in level when running game launcher.

**Steps to reproduce**
1. Launch editor and create a new level
2. Verify the default skybox appears (should be desert and blue sky)
3. Run the GameLauncher which is located within the project build folder at <project-root>\build\windows_vs2019\bin\profile
4. Observe skybox

**Expected behavior**
User should see the same skybox in editor and launcher

**Actual behavior**
launcher doesn't render the skybox, instead the background is just gray.

**Screenshots/Video**
![launcher_vs_editor](https://user-images.githubusercontent.com/41299597/152866989-df788fb1-fbe8-41fc-b0c2-85a98947f341.png)

**Found in Branch**
Found on development 2d8b4d8285
Does not occur on installer: O3DE Stable 21.11

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5900x
 - GPU  NVidia RTX 3070
 - Memory 65546MB

**Comment by galibzon** [comment]
@NeilGitGud , can you please check if this bug is still real?

**Comment by NeilGitGud** [comment]
Issue no longer occurs, closing.

ASV:
commit ed962c5513322871571d788859e046ed9e424197

O3de:
commit 9410b57d55fb735bef8e64c30ca09a735f56ffbf
