### ISSUE TITLE
Race condition in DynamicVegetationTests_Main_Optimized

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#7485]
**Describe the bug**
Locally executing DynamicVegetationTests_Main_Optimized results in unexpected intermittent failures, which are not (currently) reproducing in Automated Review. Logs suggest that the failure is occurring due to `E   [FAILED ] Failure: Instance count was unexpectedly affected by Allow Empty Assets toggle` however this is inconclusive, and may not be the root cause. Local testing failed on 19/20 executions, with similar logs each time.

**Steps to reproduce**
1. Locally build O3DE in the profile configuration
2. Open a terminal and navigate into the CMake build directory
3. Run the following command `ctest -C profile -R AutomatedTesting::DynamicVegetationTests_Main_Optimized.main --output-on-failure --repeat until-fail:100`
4. See intermittent error

**Expected behavior**
Test execution consistently succeeds

**Actual behavior**
Test intermittently fails

**Found in Branch**
Development @ 4982787043a45449ef37a1435e37402611918ceb 

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia
 - Memory 32GB

**Additional context**
Logs are attached below:
[DynVeg.txt](https://github.com/o3de/o3de/files/8025723/DynVeg.txt)
[DynVeg2.txt](https://github.com/o3de/o3de/files/8025724/DynVeg2.txt)
[DynVeg3.txt](https://github.com/o3de/o3de/files/8025725/DynVeg3.txt)
[DynVeg4.txt](https://github.com/o3de/o3de/files/8025726/DynVeg4.txt)
[DynVeg5.txt](https://github.com/o3de/o3de/files/8025727/DynVeg5.txt)

**Comment by Kadino** [comment]
Tested again and saw this again at c46c55803860cec45f2bb197c159116e90604ec6

**Comment by jckand-amzn** [comment]
Updating to a Major priority as this is not currently failing in AR. Will investigate on similar hardware to RCA.

**Comment by jckand-amzn** [comment]
Ran the entire DynVeg suite 100 times with 0 failures on a relatively equivalent machine. This test has also not had any issues in AR. Will run the suite on another set of hardware, and may close this issue out if no failures are encountered.

**Comment by jckand-amzn** [comment]
Ran another 100 times on a lower-spec Alienware laptop with 0 failures. Test instability appears to have been fixed by Editor/Dyn Veg optimizations. Closing out.
