### ISSUE TITLE
LyTestTools screenshot_compare_qssim.py invalid screenshot compares positively to any golden image

### ISSUE THREAD

**Issue by smurly** [o3de/o3de#7493]
Through some investigation and testing, it was determined that some tests failed to take screenshots and yet called qssim compare anyway. The mean quaternion returned by this module was much greater than 1.0 so logic which looked for a mean match greater than 0.99 indicated the result was a valid match (even though no screenshot was taken). further the golden image was swapped for another and the test still passed (if an image was somehow taken, this should have failed)

**Steps to reproduce**
1. Build development at around commit c3c79b25c21f5590a6b4aad6ba4935ffe3e26abf
2. from the command line in the o3de folder run the Atom GPU tests on windows
`.\python\python.cmd -m pytest --build-directory YOURBUILDFOLDER/bin/profile  .\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_GPU.py`
3. Review the editor logs for the test AtomGPU_LightComponent_AreaLightScreenshotsMatchGoldenImages confirming the lines
`Screenshot failed`
4. replace AreaLight_1.ppm in o3de\AutomatedTesting\Gem\PythonTests\Atom\golden_images with any other ppm in the folder
5. run the tests again

**Expected behavior**
the test should fail since no screenshot was taken, and then the golden image is certainly not the one that would be taken.

**Actual behavior**
The test passes

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows
 - Version 10

**Additional context**
(https://github.com/o3de/o3de/blob/development/Tools/LyTestTools/ly_test_tools/image/screenshot_compare_qssim.py)
line 88 contains the comment `# check im1 and im2 are same size`, but no size compare happens
documentation for imageio.imread does not indicate any errors returned so it is likely that an invalid image returns an empty array
comparing images assumes they are the same size. we should warn or something if the images are not the same size
we should check if screenshot is empty and return 0 to indicate that it can't match an image `if not img1: return 0` or some other empty check since any compare would be invalid.

**Comment by Kadino** [comment]
This tool was originally developed by graphics engineers, so I would request an engineer from @o3de/sig-graphics-audio own its maintenance.

**Comment by smurly** [comment]
Looks like Atom automation code didn't even call qssim earlier. I was now able to reach the following error
`ValueError: could not broadcast input array from shape (1080,1920,3) into shape (30,100,3)`
It has been recommended that we not use qssim. I'll investigate an alternative possibly the c++ code used by AtomSampleViewer.

**Comment by superkitcath** [comment]
Assigning this ticket to you @smurly; we were under the impression that you were working on this? If not, let me know! Thanks!

**Comment by smurly** [comment]
The could not broadcast input array from shape error was by caused by -Batchmode launch parameter on editor.
after resolving the code to reach a viewport state, another could not broadcast input array error was encountered, this time:
E   ValueError: could not broadcast input array from shape (1080,1920,3) into shape (1890,3360,3)
this was caused by windows accessibility scaling.
Test implementation issues were resolved https://github.com/o3de/o3de/pull/7596

- `-autotest_mode` was used and `-BatchMode` was removed
- code for screen compare was implemented within wrap_run function where it will be executed
- setup now contains all setup functions since code outside of the functions setup, teardown and wrap_run is not executed.
- the calls to compare_screenshot_to_golden_image now execute as expected.

These issues are likely not a true defect with qssim. when called correctly this module appears to work.
ownership of the qssim modules is not resolved by this work.
