### ISSUE TITLE
Bug Report: AssetProcessor ignores specified project path and scans upwards

### ISSUE THREAD

**Issue by onecent1101** [o3de/o3de#7494]
**Describe the bug**
When there is project.json file in parent directory of project path, AP will treat the parent directory as project folder

**Steps to reproduce**
1. Have your project folder setup correctly in sub directory like E:\o3de-projects\MyTestProject
2. Copy project.json file and put into E root directory
3. Run AssetProcessor or AssetProcessorBatch with specified project path
```
$ .\<path_to_your_build>\AssetProcessor.exe --project-path=E:\o3de-projects\MyTestProject
```
or
```
$ .\<path_to_your_build>\AssetProcessorBatch.exe --project-path=E:\o3de-projects\MyTestProject
```
4. See error like following
Project path "E:\Lumberyard\o3de\"" -engine-path="E:\Lumberyard\o3de" -port=45643 --register -module="E:\Lumberyard\o3de\windows_vs2019_MP\bin\profile\Builders" --regset="\Amazon\AzCore\Bootstrap\project_path=E:\Lumberyard\o3de-multiplayersample" --regset="\Amazon\AzCore\Bootstrap\project_path=E:"" does not exist. Is the "/Amazon/AzCore/Bootstrap/project_path" registry setting set to a valid absolute path?

**Expected behavior**
AP gets executed against specified project path

**Actual behavior**
AP gets executed against the parent directory which has project.json

**Screenshots/Video**
![apstuck](https://user-images.githubusercontent.com/5900509/153059523-98da6041-d750-4e2b-965a-4cf69c338c15.PNG)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
Considering put step 2 before step 1 to check specified project path first?
https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp#L294-L314

**Comment by AMZN-Gene** [comment]
I still see this occur when using engine as SDK. If I open AP.exe and provide --project_path=D:\prj\MyGame the AP still opens up with Automated Testing
![image](https://user-images.githubusercontent.com/32776221/226267018-51c6de84-07f6-41d0-b4e5-f30adafe327a.png)
