### ISSUE TITLE
SQLite errors being reported when process assets on macOS

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/o3de#7497]
**Describe the bug**
Errors are being reported by the Asset Processor when generating assets for macOS

**Steps to reproduce**
1. Build latest code from development on macOS
2. Start the asset processor

**Expected behavior**
No SQLite errors are reported

**Actual behavior**
No SQLite errors are reported

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
Macbook Pro

**Comment by galibzon** [comment]
I get this error:
