### ISSUE TITLE
Severing and Reestablishing connections between Vector3 nodes causes exception

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#7500]
**Describe the bug**
Severing and reestablishing connections between Set Vector3 variable and Set Entity X/Y/Z nodes causes the editor to throw exceptions

**Steps to reproduce**
1. launch the editor from VS 2019
2. load the attached level2 file in the editor
3. open canvas editor and load the attached FollowCamera script file
4. navigate to the end of the FollowCamera script. there are 4 nodes vector3 variable setter -> print- > entity setx/y 
5. delete the x/y value connections between the 4 nodes
6. save the file
7. attempt to reconnect the 4 nodes' x/y values

**Expected behavior**
the connectors snap together allowing you to feed the x/y values of the vector3 setter into the entity set world x/y values

**Actual behavior**
The editor console displays exceptions in step 6. VS 2019 will bring you to the following exception in step 7
![image](https://user-images.githubusercontent.com/98843754/153086547-a6800219-d832-4c3a-9ff0-c3b58300ba25.png)

**Assets required**
[BugFiles.zip](https://github.com/o3de/o3de/files/8028073/BugFiles.zip)

**Screenshots/Video**
Sever the yellow connectors
![image](https://user-images.githubusercontent.com/98843754/153086678-ab7e9aee-bd5e-4ea1-86c2-dc5be86439ef.png)

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Ryzen 9 5950x
 - GPU NVidia RTX 3070
 - Memory 32GB

**Additional context**

**Comment by carlitosan** [comment]
unable to repro the crash, what branch?

**Comment by michleza** [comment]
This was likely related to dragging connections over +Add input buttons. It is no longer occurring.
