### ISSUE TITLE
AR build:  Gradle aborts

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#7501]
**Describe the bug**
Some AR builds have been failing due to an abort on the Gradle step.  The specific log snippet from the aborted Gradle step looks like this:
![image](https://user-images.githubusercontent.com/82224783/153088742-e16ab460-3a17-4715-8281-3c4ca1d68e97.png)

Also note that 50 minutes passed between the "Cannot contact EC2" message and the actual abort. There might need to be some detection logic added to help this fail instead of timeout.

**Comment by amzn-changml** [comment]
As discussed, this may be an issue with setting our timeouts. @mbalfour-amzn can you provide a link to the AR run, so that we can pull more details?

**Comment by mbalfour-amzn** [comment]
https://jenkins.build.o3de.org/job/O3DE/job/PR-7468/2/

**Comment by mbalfour-amzn** [comment]
It's from a PR that has since been submitted, so I'm not sure how long the job link will be valid.

**Comment by brianherrera** [comment]
In this case, the pipeline should have retried the build if the underlying node went offline. I'll need to look if it hit the inactivity timeout while it was attempting to retry. 

Most of the gradle timeout issues I've seen have looked like this build: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-7490/2/pipeline 

```
[2022-02-08T22:47:40.893Z] > Task :app:copyNativeLibsProfile
[2022-02-08T23:22:30.577Z] Sending interrupt signal to process
[2022-02-08T23:22:49.274Z] script returned exit code -1
``` 
After the 30min of inactivity after `Task :app:copyNativeLibsProfile` the pipeline aborts the build. Looks like android builds are hanging somewhere around this step.

**Comment by jeremyong-az** [comment]
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-7545/1/pipeline Here's another data point in case it's useful

**Comment by santorac** [comment]
https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-7537/2/

**Comment by lawsonamzn** [comment]
I'm getting this too.
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-7592/1/pipeline/334

**Comment by shirangj** [comment]
I think Gradle daemon probably caused out of memory issue, we can try increase JVM memory limit for Gradle build.
Testing this PR now https://github.com/o3de/o3de/pull/7598

**Comment by amzn-rhhong** [comment]
Getting this https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-7610/1/pipeline/349 too today

**Comment by shirangj** [comment]
Resolving this issue as we haven't seen this issue for several days.

**Comment by shirangj** [comment]
There is a know issue of Gradle that copy task hangs when destination is mapped network drive on windows https://github.com/gradle/gradle/issues/1344
The hanging issue doesn't seem to be related to our code, I suspect there was some issue with EBS/EC2 and it's fixed now.

**Comment by spham-amzn** [comment]
> There is a know issue of Gradle that copy task hangs when destination is mapped network drive on windows [gradle/gradle#1344](https://github.com/gradle/gradle/issues/1344) The hanging issue doesn't seem to be related to our code, I suspect there was some issue with EBS/EC2 and it's fixed now.

It appears that its not always happening in the copy task:

* The first failure happens as a timeout from `app:copyNativeLibsProfile`
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-7971/1/pipeline/271

* But the next build times outs from `app:mergeProjectDexProfile`
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-7971/2/pipeline/271
