### ISSUE TITLE
Providing Set Entity World Translation a Set Vector3 output value causes Lua error.

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#7502]
**Describe the bug**
Using a Vector3 variable's setter output for the Set Entity World Translation value input will generate a lua error when the game is run

**Steps to reproduce**
1. Launch the editor via VS 2019
2. open level2 provided in the attached zip file
3. open the script canvas editor and load moverscript also included in the zip file.
4. pan over to the last node in the sequence (Set MovementVector)
5. drag the node's Out connector to an empty part of the canvas
6. find and add a Set World Translation(Entity) node
![image](https://user-images.githubusercontent.com/98843754/153091608-f2a1298e-b52a-4a2e-a158-b17dba4f624b.png)

7. Save the script
8. Return to the editor and run the game

**Expected behavior**
The game runs and the Agent entity moves to its destination

**Actual behavior**
The console output reports a Lua type conversion error.
![image](https://user-images.githubusercontent.com/98843754/153091658-fdd35352-6bf9-4077-9f3e-6f4a851b185f.png)

**Assets required**
[BugFiles.zip](https://github.com/o3de/o3de/files/8028187/BugFiles.zip)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Ryzen 9 5950x
 - GPU NVidia RTX 3070]
 - Memory 32GB

**Comment by carlitosan** [comment]
unable to reproduce this

**Comment by michleza** [comment]
https://user-images.githubusercontent.com/98843754/153100312-cbbdddb4-de3e-427f-a90d-e0e6a0396d57.mp4

**Comment by carlitosan** [comment]
I was able to reproduce, in progress
