### ISSUE TITLE
Launching the AutomatedTesting 10KEntityCpuPerfTest level on a machine with AMD GPUs crashes the Editor

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#7546]
**Describe the bug**
Opening the _10KEntityCpuPerfTest_ level from the _AutomatedTesting/Levels/Performance_ directory on a machine which has an AMD GPU will crash the Editor shortly after the level starts to load.

The specifications of machines which were used to reproduce the issue were:
GPC-375: **AMD Ryzen 7 2700X / AMD Radeon Pro Duo Polaris 32GB**
GPC-559: **AMD Ryzen 7 3800X / AMD Radeon RX 5700 XT**
GPC-808: **AMD Ryzen 7 3600X / AMD Radeon RX 5700 XT**

Please note the issue did not reproduce when the level was launched on machines with Nvidia GPUs.

An Intel CPU/AMD GPU configuration was not tested due to a lack of such a machine. 
As a consequence of this, we were unable to confirm if the issue only occurs on systems with both an AMD CPU and GPU, or if it occurs on all systems with an AMD GPU.

The issue occurs in both the Editor and the Launcher.

For further information please refer to the attached video and crash logs.

**Prerequisites**

* AutomatedTesting was built and set as a project to launch on a
machine with AMD CPU / AMD GPU configuration.

**Steps to reproduce**

1. Launch the Editor and wait until Asset Processor processes all assets.
2. Open the _10KEntityCpuPerfTest_ level.

**Expected behavior**
The Editor remains stable and the level loads successfully.

**Actual behavior**
The Editor crashes shortly after the level starts to load.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/153404723-8fcd2db7-56a4-4718-8645-c35a88c58f17.mp4

**Found in Branch**
Development (1c3a619)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Additional context**
[error dmp GPC-375.zip](https://github.com/o3de/o3de/files/8040732/error.dmp.GPC-375.zip)
[error log GPC-375.log](https://github.com/o3de/o3de/files/8040733/error.log.GPC-375.log)
[Editor log GPC-375.log](https://github.com/o3de/o3de/files/8040736/Editor.log.GPC-375.log)
[error log GPC-559.log](https://github.com/o3de/o3de/files/8040743/error.log.GPC-559.log)
[error dmp GPC-559.zip](https://github.com/o3de/o3de/files/8040744/error.dmp.GPC-559.zip)

**Comment by rgba16f** [comment]
PR - https://github.com/o3de/o3de/pull/7829

**Comment by rgba16f** [comment]
This should be resolved by commit https://github.com/o3de/o3de/commit/e4ab99eed36f8cd7064cfe239a157e83c6d62c03

**Comment by LB-MateuszSzweda** [comment]
Verified as fixed on Development (b4db237) build. _10KEntityCpuPerfTest_ level launched correctly and remained stable on the machines with AMD gpu's.
