### ISSUE TITLE
Linux: Editor crashes silently upon deleting Script Canvas nodes instantly after they are selected

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#7579]
**Describe the bug**
Deleting Script Canvas nodes from the graph instantly after selecting them results in the Editor's silent crash. Note that the more Script Canvas nodes are selected at once before deleting, the easier it is to reproduce the crash, but it has also been successfully reproduced with only one node used.

We were not able to reproduce the crash on the Windows version of the Editor.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Open the Script Canvas tool.
2. Add different nodes to the graph.
3. Select all of the nodes and instantly press 'Delete'.

**Expected behavior**
The selected Script Canvas nodes are deleted without any issues.

**Actual behavior**
Editor crashes silently.

**Video**

https://user-images.githubusercontent.com/86953659/153608249-f05965c1-03ac-4f3a-b0fa-8e344f32202a.mp4

**Found in Branch**
Development (257f3cb)

**Desktop/Device:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU: AMD Ryzen 5 3600
 - GPU: NVIDIA GeForce RTX 2060 SUPER
 - Memory: 16GB

**Comment by amzn-pratikpa** [comment]
@LB-KacperKapusta can you attach your log file please?

**Comment by LB-KacperKapusta** [comment]
[Editor.log](https://github.com/o3de/o3de/files/8059973/Editor.log) - log captured after reproducing the issue on the latest Development (a3ebe61).
Please note that the crash.log file has not been generated.

**Comment by spham-amzn** [comment]
Cannot reproduce on development (766cb40585b239f9bfc5901f16312a4f0a5371f8)

https://user-images.githubusercontent.com/82231385/165388801-944028a3-7f32-4bbf-901a-57152a930d1b.mp4

**Comment by LB-KacperKapusta** [comment]
Reopening the issue, as it has been confirmed still occurring for the latest Stabilization_2205 (3f37ff7) build:

https://user-images.githubusercontent.com/86953659/166904588-612670cf-d64d-4916-96f3-0a2aad17b7b0.mp4

Please make sure to use the "Delete" as fast as possible after the nodes selection - has to be done within ~0,5sec to trigger the crash. Seems like the crash occurs when the nodes are deleted before their information is fully loaded into Node Inspector.

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed using Stabilization/2210 (https://github.com/o3de/o3de/commit/99608ffd4f7d3d347cb015b243046a3438da23c7) build.
