### ISSUE TITLE
Meshes with varying mesh group vertex layouts assigned to a single material should not be merged, but should still process

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#7588]
**Describe the bug**
Sub-meshes that have multiple mesh groups sharing one material are automatically merged, If they have different vertex layouts, they should still process, but as individual sub-meshes instead of a merged mesh

The existing solution has an AZ_Error, but does not prevent the asset from processing and merging the meshes.

**Steps to reproduce**
1. Create a mesh asset with some faces that have multiple uv sets, and others that don't
2. Assign the same material to all of those faces
3. Process the asset in o3de and try to render it

**Expected behavior**
The resulting model has 2 meshes, which both use the same material slot in the material component
If a material that uses a sub-set of vertex streams that exist for both meshes (e.g., only one uv set), it should render properly.
If a material that uses vertex streams that don't exist for one of the meshes (e.g., two uv sets, even though one mesh has only one uv set), there should be an error.

**Actual behavior**
The mesh fails to process with an error: VertexStream 'xxx' does not match the expected vertex count. This typically means multiple sub-meshes have mis-matched vertex stream layouts (such as one having more uv sets than the other) but are assigned the same material in the dcc tool so they were merged.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development (this bug has existed since the repo was first created)

**Desktop/Device (please complete the following information):**
This issue is device independent

**Additional context**

**Comment by amzn-tommy** [comment]
Additionally, if the influences per-vertex are different between two meshes, they should not be merged.

**Comment by hwwxj** [comment]
hi, about this issue, how to fix this? and is there any workaround for this issue?

**Comment by amzn-tommy** [comment]
There are two workarounds that can be done modifying the content in a dcc tool like Blender:
1. Make the vertex format match for all meshes that use the same material. For example, if you have two meshes that use the same material, mesh A has multiple uv sets, and mesh B only has one uv set, either delete the extra uvs in mesh A or add additional uvs to mesh B so they have the same uv set count.
2. Assign unique materials to mesh A and mesh B

The real fix is to modify the model builder to not merge the meshes when their vertex formats don't match.

**Comment by amzn-tommy** [comment]
Oh, there is an additional workaround I hadn't thought of, for anyone who can't wait for the PR to go through or is working using the release build instead of the development branch. You can explicitly disable mesh merging in the Mesh (Advanced) rule in the scene settings https://www.o3de.org/docs/user-guide/assets/scene-settings/meshes-tab/#mesh-advanced

This will result in more draw calls, but should be feasible for anyone who is not working with an asset that has a massive amount of sub-meshes.

**Comment by amzn-tommy** [comment]
Fixed by https://github.com/o3de/o3de/pull/11082
