### ISSUE TITLE
Can't create project

### ISSUE THREAD

**Issue by riyadhuddin** [o3de/o3de#7614]
Tried to create a project but create project button is not there.
**Steps to reproduce**
1. Go to 'Project Manager'
2. Click on 'Create a project
3. Select 'Project Name, Location, a template'
4. Scroll down 
5. See no 'button to config or create a project'

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [ intel i5 3470 ]
 - Memory [10GB]
<img width="960" alt="o3dem" src="https://user-images.githubusercontent.com/13874736/153753349-3f2f62f7-406e-4bf0-9220-b8f11bbfea1d.png">

**Comment by robhaco** [comment]
It's possible this is a scaling/resolution thing. Going off a hunch, I set the resolution to 1080 with 175% scaling and it managed to push the "Create Project" and "Configure Gems" buttons off screen/made them unreachable.  Anything lower with resolution and there would be further issues.  It seems there's a minimum vertical height for the window that enables this scenario.
