### ISSUE TITLE
Attempting to create materials in the default location results in a crash

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#7619]
**Describe the bug**
Creating a new material in the default location crashes the Material Editor, due to a lack of write permissions. The default location is set as the root of the partition where O3DE is installed. On Windows, clicking the folder browsing button and then attempting to save the material warns the user about the missing permissions and suggests the user's personal folder as an alternative save location.On Linux, the “Document could not be saved” prompt is absent. The “Select Material Filename” prompt suggesting the user folder as an alternative save location is also absent.

**Steps to reproduce**
1. Open Material Editor.
2. Navigate to File → New.
3. Press “OK”.
4. Observe the error prompt and a crash.

**Expected behavior**
New materials are not saved to restricted locations by default.

**Actual behavior**
By default, new materials are saved to the root of the disk, where the user may not have write permissions.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/153863757-189f49d4-df71-4c6b-963d-cf075d273e50.mp4

**Found in Branch**
Development (a3ebe61)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version 18.04
 - CPU AMD Ryzen 3600
 - GPU Nvidia GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment]
Should be addressed by the following PR https://github.com/o3de/o3de/pull/8701
