### ISSUE TITLE
Script Canvas: Changes made inside the nodes are only saved once for each node unless the Editor is restarted

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#7621]
**Describe the bug**
Changes made inside most of the Script Canvas nodes are only saved once for each node - changing the values again and resaving the graph does not register changes. To workaround the issue the Editor has to be restarted, but then again, the values for each node can only be changed once.

It has been observed that nodes like Print or Math Expression save information correctly on each attempt. We were not able to verify all the available nodes due to the time constraints.
 
Please refer to the attached video for more information.

**Steps to reproduce**
1. Open Script Canvas.
2. Create a new graph.
3. Add a node to the graph, e.g. Delay node.
4. Save the graph.
5. Reopen the Script Canvas tool.
6. Open the graph saved in Step 4.
7. Made any changes inside the node added during Step 3.
8. Save the graph.
9. Reopen the Script Canvas tool.
10. Open the graph saved in Step 8.

**Expected behavior**
The latest saved changes are reflected in the Script Canvas graph.

**Actual behavior**
The latest saved changes are not reflected in the Script Canvas graph.

**Video**

https://user-images.githubusercontent.com/86953659/153881162-5496cd2a-70aa-4c5a-8ea1-4823aa6f6176.mp4

**Found in Branch**
Development (a3ebe61)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i5-9600K
 - GPU: NVIDIA GeForce RTX 2070
 - Memory: 16GB

**Comment by lsemp3d** [comment]
@michleza can you verify if this is still active after @carlitosan 's recent fixes? thanks!

**Comment by michleza** [comment]
This is no longer occurring.

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development (3200c2f).
