### ISSUE TITLE
Levels and transform value fields are initially greyed-out after enabling them in Gradient Modifier components

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#7637]
**Describe the bug**
The values in the **Levels** and **Transform** properties in specific Gradient Modifier components cannot be edited immediately after being enabled. Deselecting the entity with these components and selecting that entity again is a workaround for this issue - the **Levels** and **Transform** value fields are editable.

Affected Gradient Modifier components:
 - Invert Gradient Modifier
 - Levels Gradient Modifier
 - Posterize Gradient Modifier
 - Smooth-Step Gradient Modifier
 - Threshold Gradient Modifier

**Steps to reproduce**
1. Create a new entity.
2. Add one of the Gradient Modifier components specified in the description to the entity.
3. Enable **Levels** and **Transform** in the Gradient Modifier component.

**Expected behavior**
The **Levels** and **Transform** value fields are editable after initially enabling them in specific Gradient Modifier components.

**Actual behavior**
The **Levels** and **Transform** value fields are **not** editable after initially enabling them in specific Gradient Modifier components.

**Screenshot**
![GradientModifiersComponentIssue](https://user-images.githubusercontent.com/86951967/154035645-ae49b2a9-08ff-42e6-aa3c-71f6f7489c6a.png)

**Found in Branch**
Development (dff7d74)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by mbalfour-amzn** [comment]
This should be fixed with #10924 .

**Comment by LB-JakubSkorupka** [comment]
Verified that issue is fixed on build Development (966848d).
