### ISSUE TITLE
AtomFeatureIntegrationBenchmark unexpectedly fails attempting to upload artifacts

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#7652]
**Describe the bug**
Tests in are failing in the Main suite while attempting to upload artifacts from the user's local machine. Artifact upload is an action that should not be taken during test execution, and should instead be handled by a separate script configured to run only in a CI pipeline. Tests should not fail

**Steps to reproduce**
1. Locally build O3DE in the profile configuration, with the AutomatedTesting project enabled
2. Open a terminal and navigate into the CMake build directory
3. Run the following command `ctest -C profile -R AutomatedTesting::Atom_TestSuite_Main_GPU --output-on-failure`

**Expected behavior**
Test passes (or fails) and then waits for another pipeline script to upload any artifacts at a later time. No data attempts to upload from a user's local machine.

**Actual behavior**
The primary part of the test completes, then an error is raised when trying to directly contact a metrics back-end:
```
C:\gitly\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_GPU.py:151: in test_AtomFeatureIntegrationBenchmark
    aggregator = BenchmarkDataAggregator(workspace, logger, 'periodic')
c:\gitly\o3de\tools\lytesttools\ly_test_tools\benchmark\data_aggregator.py:75: in __init__
    self.filebeat_client = FilebeatClient(logger)
c:\gitly\o3de\tools\lytesttools\ly_test_tools\mars\filebeat_client.py:25: in __init__
    self._open_socket()
c:\gitly\o3de\tools\lytesttools\ly_test_tools\mars\filebeat_client.py:54: in _open_socket
    raise FilebeatExn("Failed to connect to Filebeat") from None
E   ly_test_tools.mars.filebeat_client.FilebeatExn: Failed to connect to Filebeat
```

**Found in Branch**
Development @ aaa8b9df7c

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia
 - Memory 32GB

**Additional context**

**Comment by jromnoa** [comment]
Those errors probably have to do without a local filebeat service running on the machine. So to fix, we will be moving the benchmark metrics to a different job, but if someone were to run that job locally they will probably see this same error unless they have a filebeat service running locally. Even if they do, they will need ES credentials as well for filebeat to send the data off correctly. Ultimately, they shouldn't be run locally but we do have to move them out of the same files and jobs as the existing tests.

**Comment by superkitcath** [comment]
Internal ticket for follow up : ATOM-17309

**Comment by jromnoa** [comment]
Will be resolved in https://github.com/o3de/o3de/pull/8314
