### ISSUE TITLE
Upgrade VS version to 16.11 and higher.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#7665]
**Is your feature request related to a problem? Please describe.**
According to [Support ends for older versions of Visual Studio](https://devblogs.microsoft.com/visualstudio/support-ends-for-older-versions-of-visual-studio-feb2022/).
>Visual Studio 2019 version 16.7: [support ends April 12, 2022](https://docs.microsoft.com/lifecycle/products/visual-studio-2019). We recommend users move to the version 16.11 supported baseline, or to Visual Studio 2022.

**Describe the solution you'd like**
Project Manager should move to 16.11 and 17, to build projects.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by dshmz** [comment]
This issue will need an RFC to be worked by SIG-Build.
