### ISSUE TITLE
Prefabs: Newly created prefab fails to retain original world position when instantiated

### ISSUE THREAD

**Issue by dm-amzn** [o3de/o3de#7668]
**Describe the bug**
Newly created prefab fails to retain original world position when instantiated.
-  Newly instantiated world position values are consistently retained.

**Steps to reproduce**

1. Launch the Editor
2. Create a new level, or load an existing level
3. In Entity Outliner, create an entity
4. Add a Mesh component to the entity (ex: Cylinder)
5. Save current entity as a Prefab
6. Observe current world position values
7. Delete newly created prefab
8. Instantiate newly created prefab
9. Observe issue

**Expected behavior**
Prefabs retain original world position values during creation.

**Actual behavior**
Newly created prefab fails to retain original world position when instantiated.

**Screenshots/Video**
https://user-images.githubusercontent.com/97991771/154196877-987622a7-d30d-48b7-acf3-ee7dcb947bd4.mp4

**Found in Branch**
commit 4bf6b6ba15e435f7ebd6aace4123b5d2f7e14ff7

**Comment by monroegm** [comment]
By design
