### ISSUE TITLE
Project Manager: Editing a projects name is not reflected in the Project Manager until restarting it

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#7686]
**Describe the bug**
If the user edits the project settings to change the name of the project, the name change is not reflected in the project list until the user restarts the Project Manager

**Steps to reproduce**
1. Launch the Project Manager
2. Create a new project
3. Open the project hamburger/drop down menu and select "Edit Project Settings..."
4. Change the project name
5. Select "Save"

**Expected behavior**
The newly saved name appears in the Project Manager project list

**Actual behavior**
The newly saved name does not display for the project until the user restarts the Project Manager

**Found in Branch**
Release Installer 2111.2

**Comment by AMZN-alexpete** [comment]
The Project Preview is also blank until the Project Manager is restarted:
![NewProjectNameNotUsed-2](https://user-images.githubusercontent.com/26804013/165397290-f53c3cb5-f4ea-4e49-8f07-58a91d45d1ad.JPG)
