### ISSUE TITLE
Feature Request: [Project Manager]Add way to interact with the gem catalog without the requirement to create a project first

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#7688]
**Is your feature request related to a problem? Please describe.**
Currently there is no way for a user to view/visit the Gem Catalog without creating a project first. This may cause problems in the long term, if O3DE plan to allow users to do workflows that are not attached to a specific project like; Creating a Gem, just viewing the Gems Catalog or adding your own Custom Gem Plugin that the user has acquired themself. 

**Describe the solution you'd like**
Reconsider the tier structure of the tabs at the top of the page, and add Gem Catalog as an option up there as well. We suggest that; Projects and Gem Catalogue could sit on the same tier as they are both views of assessing specific list of  items, while potentially O3DE could consider tucking the 'Engine' tab into an icon (e.g. a settings cog or engine icon) since it will be less frequented then Projects and Gem Catalogue. 

**Additional context**
![image](https://user-images.githubusercontent.com/82236902/154333977-4283f1d6-be34-47b6-a9ba-79b7b395fd5f.png)

**Comment by AMZN-alexpete** [comment]
Fixed by #6122

**Comment by AMZN-alexpete** [comment]
Should be fix in #9920
