### ISSUE TITLE
Linux Editor Viewport Small 

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#7711]
**Describe the bug**
The editor viewport on Linux is tiny

**Steps to reproduce**
1. Open any level in Editor on Ubuntu
2. Notice viewport

**Expected behavior**
The level renderer takes up the entire viewport

**Actual behavior**
The viewport is only rendered tiny in the top left

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32776221/154413703-aea306ab-ab00-46f2-b6f0-e94de933d0d4.png)

**Found in Branch**
development branch, Feb 16, 2022

**Desktop/Device (please complete the following information):**
 - OS: Ubuntu

**Work Around**
Resizing the viewport fixes the issue

**Comment by Magical10240** [comment]
Opensuse Tumbleweed [Mesa 21.3.6] 
development: e57b854fcabb65afa24894a1929dbab2d37bc4d9

![image](https://user-images.githubusercontent.com/17591539/154489928-79d46385-0192-4dc8-9f54-c3fd0185b397.png)

**Comment by AMZN-Gene** [comment]
cannot repro anymore
