### ISSUE TITLE
Linux: Physics Materials > Library property on PhysX components is grayed out

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#7719]
**Describe the bug**
Physics Material Library is grayed out, and cannot be changed from the PhysX components themselves, while it can still be changed via Tools > PhysX Configuration (PREVIEW).

**Steps to reproduce**
1. Go to Tools > PhysX Configuration (PREVIEW).
2. In the PhysX Configuration (PREVIEW) window go to Physics Materials > Physics Material Library and click the button on the right with the folder icon.
3. Create an entity and add a PhysX component with a collider to it (e.g. PhysX Shape Collider + Shape Box components).
4. View the Physics Materials > Library property on the component and attempt to click the button with the folder icon on it.

**Expected behavior**
Physics Material Library is not grayed out and can be changed on the component itself.

**Actual behavior**
Physics Material Library is grayed out and cannot be changed on the component itself.

**Video**

https://user-images.githubusercontent.com/86952082/154481382-34848d33-e221-49f3-b1a6-d4e3649fd7ac.mp4

**Found in Branch**
Development (3f2aa74)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by moraaar** [comment]
After physics material refactor work there are no physics material libraries anymore, 1 asset is 1 material so there is no library property anymore. Closing this bug.
