### ISSUE TITLE
Import cube format GLTF from Blender 3.0 not visible geometry disappeared and size reduced 1cm a should be 1m

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#7722]
**Describe the bug**
3D Blender export `glb`(gltf) format import cube and model move mouse on screen geometry no and very small size 1.0 centimeter not original 1.0 meter

testing [Cube.glb.tar.gz](https://github.com/o3de/o3de/files/8089501/Cube.glb.tar.gz)

**Steps to reproduce**

https://user-images.githubusercontent.com/17591539/154504870-a7407171-9113-439d-ba2d-d939179dc8c0.mp4

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/17591539/154502433-7b489000-4d95-4a50-8fb0-63a682c0b61d.png)
![image](https://user-images.githubusercontent.com/17591539/154502490-0eadcaa3-133e-47db-bdd4-0fa83ebcd832.png)

**Found in Branch**
development: e57b854fcabb65afa24894a1929dbab2d37bc4d9

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: OpenSUSE
 - Version Tumbleweed

**Comment by AMZN-stankowi** [comment]
Did https://github.com/o3de/o3de/pull/12112 fix this issue?

**Comment by Darkinggq** [comment]
@AMZN-stankowi I'm already checking version 22.10.0 gltf does not work, but I haven't checked it in development yet due to build problems, I'm waiting for it to be fixed and then I'll check it again

**Comment by Darkinggq** [comment]
![image](https://user-images.githubusercontent.com/17591539/196171716-82c6e614-eef2-41bc-b393-da9692fc94a9.png)
verified fixed (development 14076b4f932a768e9d12b041ca16a13903ac6be5)
