### ISSUE TITLE
-DLY_MONOLITHIC_GAME=1 argument causes the build configuration to fail

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#7771]
**Describe the bug**
Using argument `-DLY_MONOLITHIC_GAME=1` in a configuration command causes it to fail build generation and throws multiple cmake/LYWrappers.cmake errors into the Command Line. It should be noted that this effectively prevents the Monolithic release from being built on either Source Project-centric engine or Pre-built SDK builds. 

It should also be noted that Non-monolithic build or executing the configuration with the `-DLY_MONOLITHIC_GAME=0` argument instead does not cause this issue. 

Please refer to the Command Line log attached below under the **Command Line log** section. There are two configurations executions shown in the attached MonolithicConfiguration.txt - both use the same arguments (taken from https://www.o3de.org/docs/user-guide/packaging/windows-release-builds/), but one of them has the -DLY_MONOLITHIC_GAME argument set to 1 and the other to 0.

**Steps to reproduce**
1. Follow the Monolithic build instruction on the https://www.o3de.org/docs/user-guide/packaging/windows-release-builds/ for either Source or Pre-built SDK configuration.
2. (Optional) If there is already a build present run the `cmake -B build\windows_mono -S . -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\o3de-packages -DLY_MONOLITHIC_GAME=1` command in either the o3de folder or the project folder (depending on it's configuration).

**Expected behavior**
Build configuration command successfully finishes.

**Actual behavior**
Build configuration fails on generation, and multiple errors are printed.

**Command Line log**
[MonolithicConfiguration.txt](https://github.com/o3de/o3de/files/8109551/MonolithicConfiguration.txt)

**Found in Branch**
Development (60adc09)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by lumberyard-employee-dm** [comment]
Looking at the MonolithicConfiguration.txt, it looks like this is an issue with the Atom_RHI_Vulkan.Private.Static linking against the AzTest module which should not occur.

**Comment by lumberyard-employee-dm** [comment]
This looks like this is due to the change to use the [AZ::Test::SetEnv](https://github.com/o3de/o3de/commit/4bf6b6ba15e435f7ebd6aace4123b5d2f7e14ff7) function inside of Vulkan RHI Instance code.

The SetEnv/GetEnv function would have to be moved to AzCore in order to use it in the Vulkan RHI non-test code.
[AzCore/Utils/Utils.h](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Utils/Utils.h) would be a good place to relocate those function to.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (a3ea07f) build.
