### ISSUE TITLE
Track View: missing UI for setting key values

### ISSUE THREAD

**Issue by windbagjacket** [o3de/o3de#7774]
**Describe the bug**
The UI is missing for modifying key values on tracks in TrackView, so for example it can't be used for changing cameras during a sequence.

**Steps to reproduce**
1. Create a sequence and add a Director node
2. Add keys to the Camera track
3. Select a key.

**Expected behavior**
The interface for modifying key values should appear.

**Actual behavior**
The interface for modifying key values does not appear. Only the key ID and time appear.

**Screenshots/Video**
Highlighted in red:
Expected (screenshot from an old video):
![expected](https://user-images.githubusercontent.com/24273995/154991627-c06d300c-0f6d-4cb2-95dd-21a5a36efeb4.png)

Actual:
![result](https://user-images.githubusercontent.com/24273995/154991648-c304cdd3-ef7d-46f1-be49-59437825a925.png)

**Found in Branch**
Development built from source on 16/02/2022

**Desktop/Device (please complete the following information):**
 - Device: PC
 -  OS: Windows
 - Version: 10
 - CPU: Intel i7-10750H
 - GPU: NVidia RTX 2080 Super
 - Memory: 32GB

**Comment by rainbj** [comment]
After Sig-UX-UI group review it  appears we just need to restore older functionality and no new UX is needed. removing UX.
