### ISSUE TITLE
[Project Manager] "Projects" tab color changes unexpectedly when building a project

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#7789]
**Describe the bug**
When the user starts the project build process in the Project Manager, the background color of the tab in the top left corner becomes a strange different color that is unusual and inconsistent.

**Steps to reproduce**
1. Launch Project Manager
2. Create a new project
3. Select Build Project

**Expected behavior**
"Projects" tab remains the darker background color

**Actual behavior**
"Projects" tab background color becomes a lighter grey

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82236902/155004770-d11ab0c8-79bb-43c5-83b6-d525c93d6c81.png)

**Found in Branch**
Release Installer 2111.2

**Comment by AMZN-alexpete** [comment]
Verified as still an issue in stabilization/2205
