### ISSUE TITLE
Linux O3DE Project Manager App Missing Icon

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#7799]
**Describe the bug**
The project manager is missing an icon

**Steps to reproduce**
1. Open build/bin/profile/o3de on Linux
2. View the app icon

**Expected behavior**
The ProjectManager app is open and should have an icon on the Ubuntu side bar 

**Actual behavior**
The icon isn't there

**Screenshots/Video**
![NoIconOnLinux](https://user-images.githubusercontent.com/32776221/155034675-0332b989-e04d-42ec-a07d-8852d57f0a9a.png)

**Desktop/Device (please complete the following information):**
 - OS: Ubuntu

**Comment by rainbj** [comment]
@amzn-leenguy  to add resources. No other UX work needed on this ticket

**Comment by amzn-leenguy** [comment]
![Project-Manager-Icon](https://user-images.githubusercontent.com/82846749/155810206-388cac9d-2e4d-47f2-b53f-94743cae8647.png)
![Project-Manager-Icon](https://user-images.githubusercontent.com/82846749/155810207-2992f17a-5d04-484e-916f-4387778e1d06.svg)

I've attached the icons above as SVG and PNG at 256x256px. Let me know if this works for you.
