### ISSUE TITLE
Play mode cannot get the right transform

### ISSUE THREAD

**Issue by gmnail** [o3de/o3de#7807]
In Editor mode, it goes well and I can get the right transform interface; But in play mode, I get the null ptr of the interface, it works well in previous versions;
Here is my mainly active code:
class MyComponent
        : public AZ::Component
        , private AZ::TransformNotificationBus::Handler
    {
    public:
        template<typename, typename>
        friend class LmbrCentral::EditorWrappedComponentBase;
        ......
}

void MyComponent::Activate()
{
        m_entityId = GetEntityId();
        m_transformInterface = AZ::TransformBus::FindFirstHandler(m_entityId);
        AZ::TransformNotificationBus::Handler::BusConnect(m_entityId);
        auto transform = m_transformInterface != nullptr ? m_transformInterface->GetWorldTM() : AZ::Transform::CreateIdentity();
        ......
}

So, I don't know it is a bug or I need to change the use, and how?

**Comment by lumberyard-employee-dm** [comment]
This component might need to depend on the `TransformService`
