### ISSUE TITLE
Open Multiplayer Networking Stats in ImGUI get assertion failed report.

### ISSUE THREAD

**Issue by xiapeng78** [o3de/o3de#7808]
**Describe the bug**
MultiplayerSample project. Open Multiplayer Networking Stats in ImGUI got assertion failed report.

**Steps to reproduce**
1. Run MultiplayerSample.ServerLauncher.exe
2. Press HOME key to open ImGUI
3. Click Multiplayer and open menu, then click Networking Stats option
4. Click MultiplayerNetworkInterface bar, then we get the assertion failed report
5.

**Comment by lmbr-pip** [comment]
@xiapeng78 Can we provide the platform and either logs or screenshot please so folks can see what the issue is?

**Comment by lmbr-pip** [comment]
Looking for volunteer to repro to get missing information.

**Comment by AMZN-Gene** [comment]
I'll take a look at repro'ing this...
