### ISSUE TITLE
Improve thumbnail rendering performance

### ISSUE THREAD

**Issue by KK-5** [o3de/o3de#7817]
**Is your feature request related to a problem? Please describe.**
When I use a lot of materials and image files, especially images like .exr, the thumbnail generation in O3ED is slow and may cause Asset Browser to freeze.

**Describe the solution you'd like**
I would like the performance of thumbnail rendering to improve.

**Describe alternatives you've considered**
Alternatively, we can save the generated thumbnails to the Cache folder for future use.

**Additional context**

**Comment by gadams3** [comment]
As mentioned, this predominantly occurs with exr files and other large images. They should be loaded asynchronously but there may also be a large memory cost loading several of them. Processing once and storing to the cache folder instead of keeping them in memory is probably also a good idea.
