### ISSUE TITLE
[Linux] Script Canvas: Deleting a node that has a data slot connection results in a silent Editor crash

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#7849]
**Describe the bug**
Editor may crash when a node that has a data slot connection is deleted from a Script Canvas graph chain.
The issue does reproduce on a newly created project using standard template. The crash.log file is not generated.

Note that the issue does reproduce 2 out of 3 times on Linux and does not reproduce on Windows.
It has been observed, but only once, that the User has been logged out of Ubuntu when the described crash occurred.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Launch the Script Canvas.
2. Create a new graph (On Graph Start -> Get Color -> Set Color -> Print).
3. Delete the Set Color node.

**Expected behavior**
All nodes can be deleted without any issues.

**Actual behavior**
Deleting a node that has a data slot connection results in a silent Editor crash.

**Video**

https://user-images.githubusercontent.com/86953659/155320365-ac398bdf-0fb6-4b08-a590-437269cf1af7.mp4

https://user-images.githubusercontent.com/86953659/155320397-ae4bee48-b267-4d30-92bf-d683653e96f0.mp4

**Found in Branch**
Development (a3ea07f)

**Desktop/Device:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU: AMD Ryzen 5 3600
 - GPU: NVIDIA GeForce RTX 2060 SUPER
 - Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/8124291/Editor.log)

**Comment by carlitosan** [comment]
Is there a way to get callstacks off of ubuntu machines after a crash?

**Comment by AMZN-Gene** [comment]
I'm trying to get a callstack... VS Code, CodeLite, and even lldb fails to be able to debug on Ubuntu.

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed using Stabilization/2210 (https://github.com/o3de/o3de/commit/99608ffd4f7d3d347cb015b243046a3438da23c7) build.
