### ISSUE TITLE
Dropdown menu opens after rotating camera in EMotion FX Animation Editor

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#7854]
**Describe the bug**
A dropdown menu in Atom Renderer Window does not work correctly. After rotating the camera with the right mouse button a dropdown menu opens once the button is released. We were unable to verify this issue on Linux due to https://github.com/o3de/o3de/issues/6800 still being active. Please refer to the attached video for more information.

 **Steps to reproduce**
 1. Open the EMotion FX Animation Editor tool.
 2. Open any actor from File menu.
 3. Press the right mouse button and drag the cursor around the Atom Renderer Window.
 4. Release the right mouse button.
 
**Expected behavior**
 Camera stops following the cursor and no menu is opened.

**Actual behavior**
 Dropdown menu opens every time when the right mouse button is released.
 
**Video**

https://user-images.githubusercontent.com/86953282/155336042-50bcd222-c676-4a5e-881d-77774dab461a.mp4

**Found in Branch**
 Development (a3ea07f)
 **Desktop/Device:**
 • Device: PC
 • OS: Windows
 • Version: 10 Pro
 • CPU: Intel Core i7 8700k
 • GPU: Nvidia RTX 2080
 • Memory: 16GB

**Comment by LB-KacperSzczepanski** [comment]
The issue is does not occur on build Development (5270254) and can be closed.

**Comment by amzn-jillich** [comment]
This does not happen in the latest development anymore and seems fixed with follow character enabled or disabled.
