### ISSUE TITLE
On clients multiplayer entities spawn at the origin before being placed in the right location

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#7857]
**Describe the bug**
This is easy to spot in SpawningPerfTest level in o3de-multiplayersample where boxes are spawned several times and it's visible that they they first appear at the origin before being moved to the right position.

**Steps to reproduce**
1. o3de-multiplayersample, server and client
2. Observe where the boxes first spawn on a client

**Expected behavior**
Boxes appear in the right location on clients upon first activating.

**Actual behavior**
Boxes DO NOT appear in the right location on clients when first activating.

**Assets required**
o3de-multiplayersample

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Ryzen 5900x
 - GPU NVidia RTX 3090
 - Memory 64GB

**Comment by AMZN-daimini** [comment]
Could potentially be related to https://github.com/o3de/o3de/issues/2762 if it's verified that it's not just reproduced with multiplayer.

**Comment by AMZN-puvvadar** [comment]
That's interesting though we're fairly sure it's MP specific. https://github.com/o3de/o3de/pull/7060/commits/275d58d53a7a2df96a30c1390b47b5f11a33f6ec should address this

**Comment by AMZN-puvvadar** [comment]
https://github.com/o3de/o3de/pull/7060 should have fixed this
