### ISSUE TITLE
[WTE research] WF1: Onboarding experience

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#7861]
**Is your feature request related to a problem? Please describe.**
We need to gather user's feedback and sentiment on their O3DE onboarding experience to see how O3DE is performing. The feedback will help us further improve the experience.

**Describe the solution you'd like**
We will conduct this research with the following
1. Send out CSAT survey to the community to gather broader feedback.
2. Interview 3-4 customers to gather their feedback and contexts

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by bhanuja-s** [comment]
@amzn-leenguy is this task complete?

**Comment by amzn-leenguy** [comment]
Yes
