### ISSUE TITLE
Show in Explorer option of Python Script does not open the scripts location

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#7876]
**Describe the bug**
Show in Explorer option of Python Script does not open the scripts location. On Windows “This PC” is opened instead, Linux opens the home folder of the current user together with an "Unable to find requested file. Please check the spelling and try again" prompt. On macOS nothing happens after using that option.

**Steps to reproduce**
1. Launch the Editor.
2. Tools -> Other -> Python Scripts.
3. RMB any of the Python scripts.
4. Select “Show in Explorer” option.

**Expected behavior**
A file manager window is opened in the location of the script.

**Actual behavior**
A file manager window is opened in the root of the partition (Windows), in the Home folder (Linux) or nothing happens (macOS).

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/155519215-1c8051b6-01bd-4cbb-8cad-0c1fd91b58d7.mp4

**Found in Branch**
Development (b4db237) 

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version 18.04
 - CPU AMD Ryzen 3600
 - GPU Nvidia GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development ([ecf542f](https://github.com/o3de/o3de/commit/ecf542f6482081c25abf314853f97a76a83d1997)).
