### ISSUE TITLE
DynamicVegetation PositionModifier test instability

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#7888]
**Describe the bug**
A test in DynamicVegetationTests_Main_Optimized failed during a soak test, with a 1/50 (2%) failure rate. Please compensate for this nondeterminism, to prevent the main test suite from degrading. The only test in this module to fail was test_PositionModifier_ComponentAndOverrides_InstancesPlantAtSpecifiedOffsets

**Steps to reproduce**
1. Locally build O3DE in the profile configuration, with the AutomatedTesting project enabled
2. Open a terminal and navigate into the CMake build directory
3. Run the following command `ctest -C profile -R AutomatedTesting::DynamicVegetationTests_Main_Optimized --output-on-failure --repeat until-fail:100`
4. See intermittent error

**Expected behavior**
All tests consistently pass

**Actual behavior**
1/50 failure with log snippet:
```
E   Failed: Test test_PositionModifier_ComponentAndOverrides_InstancesPlantAtSpecifiedOffsets:
E   Test FAILED
E   ------------
E   |  Output  |
E   ------------
E   Test PositionModifier_ComponentAndOverrides_InstancesPlantAtSpecifiedOffsets finished.
E   Report:
E   [SUCCESS] Success: Initial instance count is as expected
E   [SUCCESS] Success: Found instances at all expected locations with Position Modifier offsets configured
E   [FAILED ] Failure: Failed to find all expected instances at all locations with Position Modifier offset overrides configured
E   Test result:  FAILURE
```

**Found in Branch**
Development @ b4db237c94

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10 Enterprise 64-bit, 20H2 build 19042.1526, Experience Pack 120.2212.4170.0
 - CPU AMD 3970X
 - GPU NVidia RTX 3070 Ti
 - GPU Driver: 511.56
 - Memory 64GB

**Additional context**
Initial test results were collected by running the entire set of main and smoke tests.
[PositionModifier_failure.txt](https://github.com/o3de/o3de/files/8137055/PositionModifier_failure.txt)

**Comment by jckand-amzn** [comment]
Ran the entire DynVeg suite 100 times with 0 failures on a relatively equivalent machine. This test has also not had any issues in AR. Will run the suite on another set of hardware, and may close this issue out if no failures are encountered.

**Comment by jckand-amzn** [comment]
Ran another 100 times on a lower-spec Alienware laptop with 0 failures. Test instability appears to have been fixed by Editor/Dyn Veg optimizations. Closing out.
