### ISSUE TITLE
JSONDecodeError from ly_test_tools in AssetPipelineTests

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#7893]
**Describe the bug**
An infrequent JSON error was detected while executing the AssetPipelineTests package. This appears to be emitted from the Test Tools, and not the test itself.  This test is executed in parallel with other tests, and the JSON file in question may be tampered with by other tests.

**Steps to reproduce**
1. Locally build O3DE in the profile configuration, with the AutomatedTesting project enabled
2. Open a terminal and navigate into the CMake build directory
3. Run the following command `ctest -C profile -L "(SUITE_main|SUITE_smoke)" --output-on-failure -j 32`
4. Intermittent error

**Expected behavior**
Tests in this module consistently pass

**Actual behavior**
Intermittent test failure with log snippet:
```
_ ERROR at setup of TestsAssetProcessorBatch_DependenycyTests.test_WindowsMacPlatforms_BatchCheckSchema_ValidateErrorChecking[windows-C16877168-Environment.xml-AutomatedTesting] _
c:\gitly\o3de\tools\lytesttools\ly_test_tools\_internal\pytest_plugin\test_tools_fixtures.py:347: in workspace
    request, build_directory, project, record_property, record_build_name, output_path, asset_processor_platform)
c:\gitly\o3de\tools\lytesttools\ly_test_tools\_internal\pytest_plugin\test_tools_fixtures.py:366: in _workspace
    output_path=output_path,
c:\gitly\o3de\tools\lytesttools\ly_test_tools\builtin\helpers.py:60: in create_builtin_workspace
    output_path=output_path,
c:\gitly\o3de\tools\lytesttools\ly_test_tools\_internal\managers\platforms\windows.py:92: in __init__
    _WindowsResourceLocator(build_directory, project),
c:\gitly\o3de\tools\lytesttools\ly_test_tools\_internal\managers\abstract_resource_locator.py:106: in __init__
    self._project_json = _find_project_json(engine_root, project)
c:\gitly\o3de\tools\lytesttools\ly_test_tools\_internal\managers\abstract_resource_locator.py:60: in _find_project_json
    json_data = json.load(manifest_file)
C:\gitly\o3de\python\runtime\python-3.7.12-rev1-windows\python\lib\json\__init__.py:296: in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
C:\gitly\o3de\python\runtime\python-3.7.12-rev1-windows\python\lib\json\__init__.py:348: in loads
    return _default_decoder.decode(s)
C:\gitly\o3de\python\runtime\python-3.7.12-rev1-windows\python\lib\json\decoder.py:337: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
C:\gitly\o3de\python\runtime\python-3.7.12-rev1-windows\python\lib\json\decoder.py:355: in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
E   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Found in Branch**
Development @ b4db237c94

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD 3970X
 - GPU NVidia
 - Memory 64GB

**Additional context**

- Virtually all parallel modules were started during this test, due to the high core-count on the test machine.
- LyTestTools is infrequently used by CTest modules that execute in parallel, which explains why this is not seen in other modules.
- It may be appropriate to log more information about why the failure occurred, to be able to find the actual misbehaving test module

**Comment by AMZN-scspaldi** [comment]
Review to add logging: https://github.com/o3de/o3de/pull/8444

**Comment by AMZN-scspaldi** [comment]
8444 has finally been merged, the logging should be sufficient to resolve this if it crops up again.
