### ISSUE TITLE
AP handles asset dependencies performance issues

### ISSUE THREAD

**Issue by macy12825** [o3de/o3de#7901]
AP processing the following assets is very stuck, debugging found that the function method of RetryDeferredDependencies is very slow, and further printing the log trace found that the function of SetProductDependency is very slow.
![image](https://user-images.githubusercontent.com/97455291/155694452-97c62a25-81b9-4dc7-8c74-9c0e9992b3cc.png)
![image](https://user-images.githubusercontent.com/97455291/155694778-40a335d8-4166-4fb6-9dd3-c1f040b617a2.png)
![image](https://user-images.githubusercontent.com/97455291/155694848-8c718f5a-08a0-4514-98fe-6909ee0878f9.png)

<EngineDependencies versionnumber="1.0.0">
	<Dependency path="passes/*.azasset" optional="false" />
	<Dependency path="passes/*.pass" optional="false" />
	<Dependency path="shader/*.*" optional="false" />
	<Dependency path="shaders/*.*" optional="false" />
	<Dependency path="levels/CartoonAnchor/CartoonAnchor.spawnable" optional="false" />
</EngineDependencies>

**Comment by lmbr-pip** [comment]
@macy12825 - Do you have details about platform (windows, linux etc.), build (debug, profile etc.), branch and current commit? Also need steps to reproduce ideally as it seems like this is with your own assets.

Have you tried debugging on the specific assets to get more details: https://www.o3de.org/docs/user-guide/assets/asset-processor/debugging/

**Comment by macy12825** [comment]
> @macy12825 - 你有关于平台（windows、linux 等）、构建（调试、配置文件等）、分支和当前提交的详细信息吗？还需要步骤来理想地重现，因为这似乎是您自己的资产。
> 
> 您是否尝试过调试特定资产以获取更多详细信息：[https ://www.o3de.org/docs/user-guide/assets/asset-processor/debugging/](https://www.o3de.org/docs/user-guide/assets/asset-processor/debugging/)

Here the xml asset with name *_Dependencies.xml, the content of the asset is as follows：

<EngineDependencies versionnumber="1.0.0">
	<Dependency path="passes/*.azasset" optional="false" />
	<Dependency path="passes/*.pass" optional="false" />
	<Dependency path="shader/*.*" optional="false" />
	<Dependency path="shaders/*.*" optional="false" />
</EngineDependencies>

put the xml asset in ScanFolders, Then restart the AP, and immediately find the problem.

**Comment by macy12825** [comment]
Here the xml asset with name *_Dependencies.xml, the content of the asset is as follows：
<EngineDependencies versionnumber="1.0.0">
	<Dependency path="passes/*.azasset" optional="false" />
	<Dependency path="passes/*.pass" optional="false" />
	<Dependency path="shader/*.*" optional="false" />
	<Dependency path="shaders/*.*" optional="false" />
	<Dependency path="levels/CartoonAnchor/CartoonAnchor.spawnable" optional="false" />
</EngineDependencies>
put the xml asset in ScanFolders, Then restart the AP, and immediately find the problem.

> @macy12825 - 你有关于平台（windows、linux 等）、构建（调试、配置文件等）、分支和当前提交的详细信息吗？还需要步骤来理想地重现，因为这似乎是您自己的资产。
> 
> 您是否尝试过调试特定资产以获取更多详细信息：[https ://www.o3de.org/docs/user-guide/assets/asset-processor/debugging/](https://www.o3de.org/docs/user-guide/assets/asset-processor/debugging/)

**Comment by macy12825** [comment]
@lmbr-pip  Here the xml asset with name *_Dependencies.xml, the content of the asset is as follows：
![image](https://user-images.githubusercontent.com/97455291/155992614-bb84e46a-b611-4758-a466-724480615f79.png)
put the xml asset in ScanFolders, Then restart the AP, and immediately find the problem.

**Comment by macy12825** [comment]
<EngineDependencies versionnumber="1.0.0">
	<Dependency path="passes/*.azasset" optional="false" />
	<Dependency path="passes/*.pass" optional="false" />
	<Dependency path="shader/*.*" optional="false" />
	<Dependency path="shaders/*.*" optional="false" />
	<Dependency path="levels/CartoonAnchor/CartoonAnchor.spawnable" optional="false" />
</EngineDependencies>

**Comment by macy12825** [comment]
<--EngineDependencies versionnumber="1.0.0">
	<Dependency path="passes/*.azasset" optional="false" />
	<Dependency path="passes/*.pass" optional="false" />
	<Dependency path="shader/*.*" optional="false" />
	<Dependency path="shaders/*.*" optional="false" />
<--/EngineDependencies>

**Comment by macy12825** [comment]
--<EngineDependencies versionnumber="1.0.0">
--	<Dependency path="passes/*.azasset" optional="false" />
--	<Dependency path="passes/*.pass" optional="false" />
--	<Dependency path="shader/*.*" optional="false" />
--	<Dependency path="shaders/*.*" optional="false" />
--	<Dependency path="levels/CartoonAnchor/CartoonAnchor.spawnable" optional="false" />
--</EngineDependencies>

**Comment by macy12825** [comment]
`<--EngineDependencies versionnumber="1.0.0">
	<--Dependency path="passes/*.azasset" optional="false" />
	<--Dependency path="passes/*.pass" optional="false" />
	<--Dependency path="shader/*.*" optional="false" />
	<--Dependency path="shaders/*.*" optional="false" />
<--/EngineDependencies>`

**Comment by macy12825** [comment]
`<--EngineDependencies versionnumber="1.0.0">`
`      <--Dependency path="passes/*.azasset" optional="false" />`
`      <--Dependency path="passes/*.pass" optional="false" />`
`      <--Dependency path="shader/*.*" optional="false" />`
`      <--Dependency path="shaders/*.*" optional="false" />`
`<--/EngineDependencies>`

**Comment by amzn-mike** [comment]
Hi @macy12825, the wildcard dependency system is meant as a last resort to include things which are loaded by hardcoded paths in the code.  Dependencies of this type will always be slower than a dependency on an exact file name since the AP has to keep checking every file to see if it matches.  There was some work done in the past few months to optimize this though.

Do you mind explaining what you're trying to accomplish?  It looks like you're trying to include some renderer shader files.  There are builders for the shader files which should already be handling all these dependencies, so it shouldn't be necessary to include these files.  If they're not included already and need to be, that seems like an issue needs to be filed for that.

**Comment by macy12825** [comment]
Hi@amzn-mike @lmbr-pip 
This is the case. I initially suspected the problem of operating the database, but it is not. I am sorry for this. I will describe this problem in detail below. I think it is a serious problem.

When I delete the Cached assets and recompile the assets including the above *_Dependencies.xml asset, we find that the AP is very stuck after running for a period of time, but the CPU usage of the AP is not high (Win platform, 16 cores 32g). It may take many mins if all asset is compiled.
![image](https://user-images.githubusercontent.com/97455291/156309143-366c2625-58e7-46b1-aea0-924825e26450.png)
![image](https://user-images.githubusercontent.com/97455291/156309151-a4fecd51-fd0c-4218-a709-0ba4d2334a8b.png)
![image](https://user-images.githubusercontent.com/97455291/156309161-6a27fc58-21cb-4252-8c9d-59a3ab2df8a8.png)

**Comment by macy12825** [comment]
And there is another problem, the asset dependencies of compiling xml assets alone are not the same as compiling all assets together.
![image](https://user-images.githubusercontent.com/97455291/156354980-aec6c29f-8e3c-44d4-9835-4313f754ade7.png)

**Comment by macy12825** [comment]
> Hi @macy12825, I did some testing and can confirm the issue with the different number of outgoing product dependencies and am looking into that. I also can confirm that the Assets tab does have a performance issue when displaying a large number of dependency entries.
> 
> I'm not seeing any performance issue when processing the assets however. It sounded like you were having issues with that in the initial post. Can you please confirm what version of O3DE you're using (or the commit hash if you pulled from Git)?



> Hi @macy12825, I did some testing and can confirm the issue with the different number of outgoing product dependencies and am looking into that. I also can confirm that the Assets tab does have a performance issue when displaying a large number of dependency entries.
> 
> I'm not seeing any performance issue when processing the assets however. It sounded like you were having issues with that in the initial post. Can you please confirm what version of O3DE you're using (or the commit hash if you pulled from Git)?

@amzn-mike Yes, my version is too old, and then I found out that you fixed this performance issue after #6619.
However, you know there are currently two problems：
1.Inconsistent number of product asset dependencies.
2.Performance issue when displaying a large number of dependencies.

**Comment by amzn-mike** [comment]
The 1st one is fixed here: https://github.com/o3de/o3de/pull/8089
I've filed an issue for the 2nd one: https://github.com/o3de/o3de/issues/8215

**Comment by amzn-mike** [comment]
I'm marking this issue as closed since the primary concern (performance of dependency analysis) was already fixed and the 2 additional issues have been split out.
