### ISSUE TITLE
In the Material Editor, some imported custom models display errors in the  viewport

### ISSUE THREAD

**Issue by liukaikai-g** [o3de/o3de#7903]
**Describe the bug**
Some imported custom models display errors in the Material Editor.

**Steps to reproduce**
1. Open the Material Editor
2. Create a material and change the model in the Viewport Settings
3. See error

**Expected behavior**
Viewport displays normally after changing the model.

**Actual behavior**
Model display error in Viewport after model change.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/55627654/155701519-69d69688-0df1-477c-9860-a227ec1573e2.png)
The model in levels.
![image](https://user-images.githubusercontent.com/55627654/155702132-ef9f4e40-f7af-4c6a-850c-91ae52ad9aaf.png)
The model in Material Editor.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel(R)_Xeon(R)_W-2245
 - GPU NVIDIA Quadro RTX 4000
 - Memory 32GB

**Additional context**

**Comment by superkitcath** [comment]
Hi @liukaikai-g! Could you please attach the model asset and `<your asset..modelpreset.azasset` (json) file?

**Comment by liukaikai-g** [comment]
I realized it was the model I was using that was wrong, not the Material Editor ：）

**Comment by liukaikai-g** [comment]
I realized it was the model I was using that was wrong, not the Material Editor  : )
