### ISSUE TITLE
Landscape Canvas: Undo does not remove nodes

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#7909]
**Describe the bug**
The Undo option removes the entity connected to the node, but the node itself. It is possible to connect the node with other nodes after the entity is deleted. The corrupted node is removed after the Landscape Canvas is reopened.

**Steps to reproduce**
1. Go to Landscape Canvas.
2. Create any node.
3. Use the Undo option.
4. Add some new nodes.
5. Connect the new nodes to the existing ones.

**Expected behavior**
The Undo option removes added nodes.

**Actual behavior**
The entity tied to the node is removed, but the node itself remains in the Landscape Canvas.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/155721008-92c2e485-f649-46ec-843b-945907e010e8.mp4

**Found in Branch**
Development (1c4ec5c)

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU Nvidia RTX 2060 SUPER
Memory 16GB

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as Fixed in Stabilization/2210 (7fa9f5d), however it still occurs in Development (6b9465d).
