### ISSUE TITLE
Linux: Flaky Test and AssetProcessorConnection::ConnectThread Fail

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#7926]
Whenever my network automation test fails, the Server.log is filled with AssetProcessorConnection::ConnectThread trace warnings

**Steps to reproduce**
1. On Linux build AutomatedTesting project Editor and AutomationTesting.ServerLauncher
2. Run Test: _python/python.sh -m pytest --build-directory ./build/bin/profile/ ./AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py::TestAutomation::test_Multiplayer_AutoComponent_RPC_
3. Run test until it fails... 50% failure rate on my machine.
4. Open /AutomatedTesting/user/log/Server.log

**Expected behavior**
AssetProcessor should be able to connect to the server

**Actual behavior**
Server.log shows that it couldn't connect to AssetProcessor
```
==================================================================
(AssetProcessorConnection::ConnectThread) - Trace::Warning
 /home/gene/prj/o3de/Code/Framework/AzFramework/AzFramework/Network/AssetProcessorConnection.cpp(231): 'void AzFramework::AssetSystem::AssetProcessorConnection::ConnectThread()'
(AssetProcessorConnection::ConnectThread) - Network connection attempt failure, Connect returned error AzSockError::eASE_ECONNREFUSED
(AssetProcessorConnection::ConnectThread) - ==================================================================
```

**Desktop/Device (please complete the following information):**
 - OS: Ubuntu

**Comment by AMZN-Gene** [comment]
AssetProcesser fail is a red-herring. The server is launched from the Editor so AP is already running and all the assets are processed. Disabling the server from connecting to AP (--bg_ConnectToAssetProcessor false) and the test still flakes.

**Comment by lmbr-pip** [comment]
Maybe related to test framework issues?

**Comment by AMZN-Gene** [comment]
I'll upgrade multiplayer tests to the new testing standard found here:
https://www.o3de.org/docs/user-guide/testing/parallel-pattern/#test-structure

**Comment by AMZN-Gene** [comment]
Opening the editor server with commandline parameter "--bg_ConnectToAssetProcessor false" removes the spam about connecting to AP. Closed.
