### ISSUE TITLE
Material Editor: An entirely black ghost pane of Viewport Settings titled "Inspector" opens along with the Material Editor

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#7938]
**Describe the bug**
Opening the Material Editor does result in an additional entirely black pane titled "Inspector" being opened along with it, which has been observed to be a ghost pane of the Viewport Settings - whenever the Viewport Settings pane is resized the ghost black pane does resize with it.

The same issue does occur for both Windows and Linux versions of the Editor.

Please refer to the attached video and logs for more information.

**Steps to reproduce**
1. Launch the Material Editor.

**Expected behavior**
Material Editor opens properly.

**Actual behavior**
Material Editor opens along with an additional entirely black ghost pane.

**Video**

https://user-images.githubusercontent.com/86953659/155969792-12bda62e-42eb-4cde-8ff1-42ceb98779b5.mp4

**Found in Branch**
Development (b64cce7)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600
 - GPU: NVIDIA GeForce RTX 2060 SUPER
 - Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/8152648/Editor.log)
[MaterialEditor.log](https://github.com/o3de/o3de/files/8152650/MaterialEditor.log)

**Comment by gadams3** [comment]
Resolved by the following PR https://github.com/o3de/o3de/pull/8187

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed in both the Development (721ca79) and the Stabilization_2205 (3f37ff7) builds.
