### ISSUE TITLE
Material Editor: Settings window is blank

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#7943]
**Describe the bug**
Settings of Material Editor open as a completely blank window.

The issue does occur for both Windows and Linux versions of the Editor.

Please refer to the attached screenshot for more information.

**Steps to reproduce**
1. Open Material Editor.
2. From the toolbar select Edit -> "Settings...".

**Expected behavior**
Material Editor Settings open correctly.

**Actual behavior**
Material Editor Settings open as a blank window.

**Screenshot:**
![MaterialEditorSettings](https://user-images.githubusercontent.com/86953659/155999815-4e31001d-c008-47e0-94d8-116a376361e4.PNG)

**Found in Branch**
Development (b64cce7)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600
 - GPU: NVIDIA GeForce RTX 2060 SUPER
 - Memory: 16GB

**Comment by gadams3** [comment]
a new settings window has been added to all of the atom tools https://github.com/o3de/o3de/pull/10378

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (dea526c) build.
