### ISSUE TITLE
Linux: Mouse buttons do not work properly in the Entity Outliner context menu 

### ISSUE THREAD

**Issue by monroegm** [o3de/o3de#7951]
[Migrated from JIRA LYN-7289]
Entity context menu in the Entity Outliner appears before RMB is released. Additionally, releasing the RMB is recognized as clicking the LMB in the context menu, creating a possibility of unintended user input for the selected entity.

The issue does not occur on Windows platform.
----
*Found in Build*: O3DE Development (029ad32)

*Reproducibility*: 3/3

*Steps to Reproduce*: 
 1. Open any project and any level.
 2. Create an entity.
 3. Right click on the entity without releasing the button.
 4. Move cursor to the Delete option.
 5. Release the RMB.
 6. Entity gets deleted.

*Expected Result*: 
 Context menu appears only after releasing the RMB.

*Actual Result*: 
 Menu appears before releasing the RMB. Releasing the RMB is treated as clicking the LMB.

**Comment by burelc-amzn** [comment]
This is the default behavior provided by Qt.

To test this, I made the following Python script using PySide2:
```py
#!/usr/bin/env python3
from PySide2 import QtCore, QtGui, QtWidgets

app = QtWidgets.QApplication()
w = QtWidgets.QWidget()
w.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
action = QtWidgets.QAction('Some action', w)
w.addAction(action)
action.triggered.connect(lambda: print('Some action triggered'))
w.show()
app.exec_()
```

When you run this application, it creates a new window. Right clicking on this window will bring up a context menu. The specific behaviors necessary to show that context menu change per platform.

Linux
-----

1. On Linux, pressing and releasing the RMB quickly will show the context menu. After you click and release the RMB, you can use any mouse button to activate items in the context menu.
2. Alternatively, you can RMB press and hold for a few seconds to bring up a context menu. When the context menu is shown in this manner, the user can then RMB drag the mouse to different items, and upon RMB release, the item will be activated.

Windows
-------

On Windows, holding down the RMB does not bring up the context menu. If you RMB click and hold, nothing happens, until you release the button. On RMB up, the context menu appears, and you can click on the item to trigger it. It doesn't matter which button you use to click on the item, left, right, or even middle, the associated action is still triggered.

I don't think we need to go out of our way to change Qt's default platform abstraction here. I looked a bit in Qt's source to see if I could find where this is defined, but the way that context menu events are created from right click events is a bit difficult to trace.
