### ISSUE TITLE
O3DE Stable 21.11 Release - Editor fails to launch server

### ISSUE THREAD

**Issue by adamarjian1** [o3de/o3de#7976]
**Describe the bug**
Followed the information found on the following YouTube link: https://www.youtube.com/watch?v=3pWckmuHPSg&list=PLCQwFpnHSZQgkw7MdNQwagKKKvywt6b80&index=41

 when I run the server I get the following error in the console:
[Warning] (MultiplayerEditor) - Could not connect to server targeted by Editor. If using a local server, check that it's built and editorsv_launch is true.

When running the server 

**Steps to reproduce**
1.Type editorsv_enabled= true [  ] in the console
2.Press CTRL +G to run the project. 

The above error should appear.

**Comment by lmbr-pip** [comment]
@adamarjian1 - Can you confirm you have the server launcher built and in your binary folder?

Can you confirm:
* Which project are your running?
* Can you provide platform and build information?

**Comment by AMZN-Olex** [comment]
I can confirm this. I was able to repro this as well.

**Comment by AMZN-Olex** [comment]
There is a bug that is being fixed in development branch:
https://github.com/o3de/o3de/pull/8236

Until then try specifying editorsv_process to the full path to the server launcher.

**Comment by AMZN-Gene** [comment]
@AMZN-Olex provided work around (use _editorsv_process_ to point the editor to the server found inside of the _project/build/bin_ folder. Development branch now looks inside BOTH the engine and project folder :) 
@adamarjian1 feel free to open if you have further questions.
