### ISSUE TITLE
Import fbx crash

### ISSUE THREAD

**Issue by lihongjun25** [o3de/o3de#7980]
**Describe the bug**
When the FBX file is imported to O3DE, a message is displayed indicating that the parsing fails and the connection between the slave generator and the asset generator is interrupted. The generator indicates that the job has failed.

**Steps to reproduce**
1. Import fbx files

**Expected behavior**
Import succeeded.

**Actual behavior**
Import failed.

**Assets required**
Crash Code:   genTangSpace from AssetBuilder

Desktop/Device (please complete the following information):

Device: [PC]
OS: [Windows]
Version [10]
CPU [Intel Xeon Gold 6234]
GPU [NVidia RTX 5000]
Memory [32GB]
Working Branch: Main branch https://github.com/o3de/o3de/commit/e7f787572e805c413115265e5873fb2425e2f41b

**Comment by monroegm** [comment]
@lihongjun25 Can you provide more detailed steps to reproduce and perhaps a sample FBX?
