### ISSUE TITLE
UI not hiding property subgroups when folding parent group in the Material Inspector

### ISSUE THREAD

**Issue by santipaprika** [o3de/o3de#7983]
**Describe the bug**
The latest refactor in material types (https://github.com/o3de/o3de/pull/7762) introduces support for nested property groups (each property group can contain any number of property subgroups). This behavior works correctly, but is not properly reflected in the material inspector, in the sense that folding a group does not hide its child subgroups (see video).

**Steps to reproduce**
1. Create/modify a material type with nested property groups, e.g.
```json
"description": "...",
"version": "...",
"propertyLayout": {
        "propertyGroups": [
            {
                "name": "iris", 
                "shaderInputsPrefix": "m_iris_",
                "shaderOptionsPrefix": "o_iris_",
                "displayName":  "Iris",
                "description":  "Material properties for the iris.",
                "propertyGroups": [
                    {
                        "$import": "MaterialInputs/BaseColorPropertyGroup.json"
                    },
                    {
                        "$import": "MaterialInputs/NormalPropertyGroup.json"
                    }
                ]
            },
            ...
```
2. Create a material with this type, and check the inspector

**Expected behavior**
Hide subgroups when folding parent group in the material inspector

**Actual behavior**
Folding/unfolding the parent group does not have any effect on the subgroups visibility

**Screenshots/Video**

https://user-images.githubusercontent.com/44426596/156133696-b61ca7a5-c0b5-4815-b9a9-9d817be541df.mp4

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel i7-11850H
 - GPU: NVidia RTX 3080
 - Memory: 16 GB

**Comment by gadams3** [comment]
the UI is now hiding the empty parent groups
