### ISSUE TITLE
Editor crashes after using Undo/Redo when cursor is above hide or lock button in Entity Outliner

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#7985]
**Describe the bug**
The Editor crashes after undoing or redoing an action when cursor is above hide/show or lock/unlock entity button in **Entity Outliner**. Undo/Redo of selecting or deselecting an entity does not cause the crash to occur.

Please note that on Linux OS error.dmp and error.log files are **not** created after the crash occurs, although we provided the logs from a machine with Windows OS (please refer to the attached log.zip file).

**Steps to reproduce**
1. Create a new entity.
2. Hover the cursor over hide/show or lock/unlock entity.
3. Undo the action.

Alternative steps for redo:
1. Create a new entity.
2. Undo the action.
3. Hover the cursor over hide/show or lock/unlock entity.
4. Redo the action.

**Expected behavior**
The Editor remains stable.

**Actual behavior**
The Editor crashes after undoing or redoing the action when the cursor is placed above hide/show or lock/unlock entity button in **Entity Outliner**.

**Video**

https://user-images.githubusercontent.com/86951967/156177987-599e6ae3-adeb-444b-bb6f-6b53239b1535.mp4

**Found in Branch**
Development (f74dca6)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Additional context**
[log.zip](https://github.com/o3de/o3de/files/8161900/log.zip)

**Comment by LB-JakubSkorupka** [comment]
We attempted to reproduce the issue on Linux and Windows machine, and the issue no longer occurs on the latest Development (3200c2f) build.

**Comment by AMZN-daimini** [comment]
Thanks for verifying again. Closing the issue.
