### ISSUE TITLE
Script Canvas: Script Canvas Editor crashes when opening files

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#7991]
**Describe the bug**
If you save a save a complex graph (longer than 3 nodes) the script canvas editor will crash when you try to open the file

**Steps to reproduce**
1 - Create a new Script Canvas file
2 - Drag any 4 nodes onto the canvas and connect them
3 - Save the file
4 - Close the graph
5 - Attempt to open the file 

**Expected behavior**
The file is opened in the state it was saved at.

**Actual behavior**
The project is halted with an exception

**Assets required**

**Screenshots/Video**

https://user-images.githubusercontent.com/98843754/156225252-b7b31bbf-6e6b-40cd-8cda-106d35649a0a.mp4

[editorCallStack.txt](https://github.com/o3de/o3de/files/8171548/editorCallStack.txt)

**Found in Branch**
Development

Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win10
 - CPU AMD ryzen 9 5950
 - GPU nvidia 3070
 - Memory 32gb

**Comment by michleza** [comment]
[editorCallStack.txt](https://github.com/o3de/o3de/files/8171537/editorCallStack.txt)

**Comment by onecent1101** [comment]
Fix has been merged https://github.com/o3de/o3de/pull/8032, feel free to reopen if issue still exists.
