### ISSUE TITLE
A blank screen is displayed during program startup.

### ISSUE THREAD

**Issue by lihongjun25** [o3de/o3de#8012]
**Describe the bug**
White Screen Occurs When a Project Is Opened

**Steps to reproduce**
1. Startup Procedure

**Expected behavior**
The main page is normal.

**Actual behavior**
A blank screen is displayed on the home screen.

Desktop/Device (please complete the following information):

Device: [PC]
OS: [Windows]
Version [10]
CPU [Intel Xeon Gold 6234]
GPU [NVidia RTX 5000]
Memory [32GB]
Working Branch: Main branch https://github.com/o3de/o3de/commit/e7f787572e805c413115265e5873fb2425e2f41b

**Comment by forhalle** [comment]
If ux is needed, please add sig/ui-ux label. Thanks!

**Comment by monroegm** [comment]
@lihongjun25 Can you provide more details about the steps to reproduce this issue?

**Comment by srikappa-amzn** [comment]
Closing due to lack of response. Please reopen if needed
