### ISSUE TITLE
Linux: Deleting the AZ::Event node together with the Event handler node from a Script Canvas crashes the Editor

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#8016]
**Describe the bug**
The issue does not occur on Windows.

Adding the AZ::Event node to the Script Canvas also adds the Event handler node connected to it. Deleting both of these nodes at once crashes the Editor.

Examples of the AZ::Events nodes in Script Canvas:
- GetOnClientDisconnectedEvent
- GetOnTriggerEnterEvent
- GetOnTriggerExitEvent
- GetOnCollisionBeginEvent
- GetOnCollisionPersistEvent
- GetOnCollisionEndEvent

Please note that the issue has inconsistent reproduction rate. The easiest way to reproduce it is by box-selecting both nodes starting from the AZ::Event node (as shown on the attached video).

Please refer to the attached video for more details, and note, that the error.log file was not generated for the crash.

**Steps to reproduce**
1. Launch Script Canvas.
2. Add the GetOnClientDisconnectedEvent node from Multiplayer/Multiplayer category.
3. Select both added nodes using the box selection.
4. Delete both nodes.
5. (optional) If the Editor does not crash, restart it and repeat steps 1-4.

**Expected behavior**
The Editor remains stable.

**Actual behavior**
The Editor crashes.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/156334534-c7453dac-97b3-4337-bf74-7065eef25688.mp4

**Found in Branch**
Development (0ab9aa5) 

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version 20.04 LTS
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Attachments**
[Editor.log](https://github.com/o3de/o3de/files/8168405/Editor.log)

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed using Stabilization/2210 (99608ff) build.
