### ISSUE TITLE
O3DE's Jenkins instance exposed to internet https://52.88.209.197/

### ISSUE THREAD

**Issue by Traitor00** [o3de/o3de#8041]
**Describe the bug**
 I am able to acess https://52.88.209.197/ this jenkins instance and able to login using my github. I don't know this is a valid vulnerabiltiy or not. But decided to submit here.

**Steps to reproduce**
1. Go to ' https://52.88.209.197/'

Thanks,

**Comment by amzn-changml** [comment]
This should not be accessible, and we've prevented any further behavior from a bare IP.
