### ISSUE TITLE
Adding or removing the Fly Camera Input Component while in Be this camera mode throws Error in the Console

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#8045]
**Describe the bug**
Adding or removing the _Fly Camera Input_ to a _Camera_ entity while the _Be this camera_ is active results in the following error to be printed in the Console:
`[Error] (EditorViewportWidget) - Internal logic error - active view changed to an entity which is not an editor camera. Please report this as a bug.`

Please note that the issue occurs both on Linux and Windows.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Open a default Level.
2. Select the _Camera_ entity and click the _Be this camera_ button on the _Camera_ component.
3. Delete the _Fly Camera Input_ component from the _Camera_ entity.

**Expected behavior**
No errors appear in the Console.

**Actual behavior**
An error appears in the Console.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/156554121-60ffe488-0f6f-4330-ab8e-648406f1c505.mp4

**Found in Branch**
Development (d5b592c) 

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version 20.04 LTS
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-MateuszPlatakis** [comment]
Issue verified as fixed on latest Stabilization/2305 (602a599) and Development (beb8bce).
