### ISSUE TITLE
Feature Request: Find project root in EditorTest

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#8051]
**Is your feature request related to a problem? Please describe.**
As described in https://github.com/o3de/o3de/pull/8049 there is a need to easily refer to resources within a project from inside the Editor python.

**Describe the solution you'd like**
There should be a library in ly_test_tools that inspects the manifest of registered projects, and returns the path to the root of a given project.

**Describe alternatives you've considered**
- ly_test_tools._internal.managers.abstract_resource_locator._find_engine_root can be used for projects bundled with O3DE, but is also in multiple protected subpackages and thus quite difficult to find.
- It may be possible to use scripts/o3de.py to access the intended values
  - This interface is nontrivial and should be either wrapped by a more-specific call from a helper function or have such usage documented in a testing guide

**Additional context**

**Comment by cgalvan** [comment]
@Kadino You should be able to use the `azlmbr.paths.projectroot` which gets populated with the path to the current project path. That would make the tests future-proof if they were ever moved to a project besides `AutomatedTesting`

**Comment by Kadino** [comment]
@FuzzyCarterAWS looks like this already exists.
