### ISSUE TITLE
Test Tools: Optimized Editor test runs can fail with an "UnboundLocalError: local variable 'regex_match' referenced before assignment"

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#8074]
**Describe the bug**
Optimized Editor test runs can fail with an "UnboundLocalError: local variable 'regex_match' referenced before assignment". This appears to be possible if a log_path can't be found for _check_log_errors_warnings() in Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py.

**Steps to reproduce** (Low Repro)
1. Run any optimized test suite.
2. Repeat as needed.

**Expected behavior**
Test suite does not fail due to tooling.

**Actual behavior**
Test suite can overall fail if the log_path can't be found, resulting in an UnboundLocalError.

**Found in Branch**
development@2e52dcc4c1557e0d3f6080529fe42d64ba384591

**Comment by evanchia-ly-sdets** [comment]
https://github.com/o3de/o3de/pull/8139
