### ISSUE TITLE
Multiplayer Sample Does Not Compile If Using the O3DE Installer

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#8105]
Multiplayer Sample cannot compile when using the O3DE installer.

**Steps to reproduce**
1. Install the O3DE Installer https://o3debinaries.org/download/windows.html 
2. Clone https://github.com/o3de/o3de-multiplayersample
3. Open Project Manager App
4. Add Multiplayer Sample
5. Press the Build Button

**Expected behavior**
MultiplayerSample project should build.
_Unknown CMake command "o3de_pal_dir"_

**Actual behavior**
Project fails to build

**Comment by AMZN-Olex** [comment]
Duplicate of https://github.com/o3de/o3de-multiplayersample/issues/118

**Comment by AMZN-Gene** [comment]
The work around is to use MultiplayerSample main branch instead of development branch.

**Comment by AMZN-Gene** [comment]
Closed as dupe
