### ISSUE TITLE
AP 'Show in Asset Browser' Bug

### ISSUE THREAD

**Issue by macy12825** [o3de/o3de#8133]
Currently this function is invalid for any version (win platform 32g 16cores)
![image](https://user-images.githubusercontent.com/97455291/157255279-c7fc7fb6-1eb1-4d85-8d00-31e07cfedc2e.png)

**Comment by lmbr-pip** [comment]
Can confirm that In development (#c64f2bf21759bfc3c805bd984f07d18fab712301), this is still broken on Linux. Clicking "Show in Asset Browser" does nothing from AssetProcessor UX

**Comment by AMZN-stankowi** [comment]
This works on Windows on commit 34d4f25e5219af6375bc35187bdc738d16557565 (upstream/stabilization/2305)

This is an old ticket, so it's probably been fixed by another commit in the last 12 months.
