### ISSUE TITLE
[windows][test_gpu_profile] AutomatedTesting::Atom_TestSuite_Main_GPU.main tests time out for Vulkan RHI

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8171]
[Migrated from JIRA LYN-10330]
 
{noformat}
Start  18: AutomatedTesting::Atom_TestSuite_Main_GPU.main::TEST_RUN
Test  #18: AutomatedTesting::Atom_TestSuite_Main_GPU.main::TEST_RUN ..........***Timeout 1200.02 sec{noformat}

**Comment by jromnoa** [comment]
These tests now pass once again. Closing out this issue.
