### ISSUE TITLE
Fix OpenEXR library issue on debug builds

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8175]
[Migrated from JIRA ATOM-17423]
Error shows:
{code:java}
1>------ Build started: Project: ImageProcessingAtom.Editor, Configuration: debug x64 ------
1>LINK : fatal error LNK1000: Internal error during LIB::Search
{code}
Work-around: Enable Incremental Linking on ImageProcessingAtom.Editor (Debug)
----
Found in Build: development branch, commit 515d50ae033b3c984d17060f8a15ae30bf4d71b6

Reproducibility:

Prerequisites:

Steps to Reproduce:

Expected Result: There should be no linker error when building editor

Actual Result: There is a linker error when building editor that can be resolved by enabling incremental linking for that specific code.

**Comment by lawsonamzn** [comment]
Struggling to reproduce this on windows with any version of MSVC2019.  More details on environment would be super helpful here.

**Comment by santorac** [comment]
This was happening for me. I'm not sure what's different about my setup that leads to this issue.

Windows 10
Processor	AMD Ryzen Threadripper 3970X 32-Core Processor    3.69 GHz
Installed RAM	64.0 GB (63.9 GB usable)

Microsoft Visual Studio Professional 2019
VisualStudio.16.Release/16.11.2+31624.102

Cmake command: 
```
cmake .. -G "Visual Studio 16 2019" -A x64 -T host=x64 -DLY_3RDPARTY_PATH=D:\Lumberyard\3rdparty -DLY_PROJECTS="AtomTest;AtomSampleViewer;AutomatedTesting" -DLY_UNITY_BUILD=ON -DLY_PIX_ENABLED=ON -DLY_RENDERDOC_ENABLED=ON
```

**Comment by lawsonamzn** [comment]
Its possible its an out of memory issue or something like that.   Jiggling it around by enabling incremental linking could just shuffle stuff.  In which case jiggling anything might cause it to work or not work.

**Comment by santorac** [comment]
It looks like updating to the latest patch of VS 2019 resolved this issue for a couple of us. I'm now at "VisualStudio.16.Release/16.11.11+32228.343" and not seeing the issue anymore.
