### ISSUE TITLE
o3de Editor - Trackview - Adding an Animation Sequence seemed to add a Error to my Level Prefab.

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8176]
Provide a detailed description of the defect here and include any possible workarounds.
----
Found in Build: Development

Reproducibility: Maybe...

Prerequisites: o3de Editor and Animation.

Steps to Reproduce: Adding an Camera animation to Level with Trackview. 

Expected Result: The animation works fine... but there just is an error log message.

Actual Result:  !image-2022-03-02-15-51-52-386.png|width=547,height=369!

**Comment by monroegm** [comment]
This is a stale issue with not enough details. Please reopen if you have more details in the future
