### ISSUE TITLE
o3de Editor - Skin Attachment - Not working when attaching a target entity.

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8182]
[Migrated from JIRA ATOM-17299]

Provide a detailed description of the defect here and include any possible workarounds.

Found in Build: Latest Development Build

Reproducibility: Yes

Prerequisites: Attach a Skin Attachment to an Animated Model with a Skin

Steps to Reproduce: Attach a Skin Attachment to an Animated Model with a Skin

Expected Result: The Attached Mesh entity will move with animated model.

Actual Result: See Video. (Will not attach)

https://user-images.githubusercontent.com/82228511/162928967-daaf6c07-e96e-4660-b25b-6c44344fc9a1.mp4

**Comment by hultonha** [comment]
@amzn-tommy myself and @amzn-jillich wanted to check if you're still working on this (is this an Atom issue) or is this something the character team could investigate? Thanks!

**Comment by amzn-jillich** [comment]
There have been a few fixes to attachments and this one is not reproducable anymore, closing as fixed.
