### ISSUE TITLE
[Linux] Asset Processor fails to process grass_flower_pink.fbx and grass_flower_purple.fbx for AutomatedTesting project

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#8195]
**Describe the bug**

The following 2 scene compilation jobs fail processing for the .fbx assets:
`Assets/Objects/Foliage/grass_flower_pink.fbx`
`Assets/Objects/Foliage/grass_flower_purple.fbx`

Please refer to the attached .log files for more information.

**Prerequisites**

- AutomatedTesting project is built via Source engine Project Manager.

**Steps to reproduce**

1. Launch the Asset Processor.
2. Wait until all assets are processed.

**Expected behavior**
All assets are processed without failure.

**Actual behavior**
The grass_flower_pink.fbx and grass_flower_purple.fbx scene compilation jobs fail processing.

**Screenshot**
![AP_FailedFBXs](https://user-images.githubusercontent.com/86953659/157446333-11896c76-2761-4c21-948b-b4b37b30bace.png)

**Found in Branch**
Development (34c9f41)

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.3 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[grass_flower_purple.fbx-3145494050-16966.log](https://github.com/o3de/o3de/files/8214826/grass_flower_purple.fbx-3145494050-16966.log)
[grass_flower_pink.fbx-3686476770-16964.log](https://github.com/o3de/o3de/files/8214827/grass_flower_pink.fbx-3686476770-16964.log)

**Comment by byrcolin** [comment]
This could be related to: https://github.com/o3de/o3de/issues/8771
