### ISSUE TITLE
Linux: Editor crashes upon changing Display Mapper component's type to Reinhard when the assets are still being processed

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/o3de#8218]
[Migrated from JIRA LYN-9730]
Changing Display Mapper component's type to Reinhard while the AP is still processing project's assets results in a crash.

The issue does not occur on Windows installer build and on the newest Development branch build (63d755b) on Linux.

Please refer to the attached video and log files for more information.
----
*Found in Build*: Stabilization/2111RTE installer

*Reproducibility*: 3/3

*Prerequisites*: N/A

*Steps to Reproduce*:
 # Launch the O3DE Project Manager.
 # Create a new project.
 # Press 'Build Project' in the created project's tab.
 # Press 'Open Editor' for the project built.
 # Create a new level or open an existing one.
 # Make sure that project's assets are still being processed.
 # Add Display Mapper component to an entity.
 # Change component's type to Reinhard.

*Expected Result*:
The Editor remains stable.

*Actual Result*:
The Editor crashes upon changing Display Mapper component's type to Reinhard while the AP is still processing the project's assets.

**Comment by spham-amzn** [comment]
Cannot reproduce with release 22.05.0 (Linux)
