### ISSUE TITLE
Linux: Closing Editor while AP is still processing assets results in a crash upon relaunching it

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/o3de#8219]
[Migrated from JIRA LYN-9729]
Editor crashes upon relaunching after it has been closed while the AP was still processing assets for a project.

To workaround the issue it is required to launch the Asset Processor via Terminal using the following command:
{code:java}
sudo /opt/O3DE/0.0.0.0/bin/Linux/profile/Default/AssetProcessor --project-path=<path_to_the_project>{code}
After all assets are processed, the project can be relaunched using the O3DE Project Manager without issues. 

The issue does not occur on Windows installer build and on the newest Development branch build (63d755b) on Linux.
  
 Please refer to the attached video and log files for more information.
----
*Found in Build*: Stabilization/2111RTE installer

*Reproducibility*: 3/3

*Prerequisites*: N/A

*Steps to Reproduce*:
 # Launch the O3DE Project Manager.
 # Create a new project.
 # Press 'Build Project' in the created project's tab.
 # Press 'Open Editor' for the project built.
 # Close the Editor while it is still processing project's assets.
 # Repeat step 4.

*Expected Result*:
 The Editor relaunches without issues and the Asset Processor continuous to process the remaining assets.

*Actual Result*:
 The Editor crashes upon relaunching.

**Comment by spham-amzn** [comment]
Cannot reproduce with o3de_2205_0.deb. Repeated the repo step 4 consecutive times.
