### ISSUE TITLE
Linux: Reinstalled O3DE Editor fails to launch after it has been closed once

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/o3de#8221]
[Migrated from JIRA LYN-8678]
The Editor for each Project only launches once. After it has been closed, it crashes immediately.
 Please note that the issue only occurs on 3 out of 5 of our machines.

Please also note that the issue starts occurring after the O3DE was uninstalled and reinstalled again.

Please refer to the attached files for more details.
----
*Found in Build*: o3de_installer_2111_1

*Reproducibility*: 3/5

*Prerequisites*: 
 - O3DE was previously reinstalled on the system.

*Steps to Reproduce*: 
 # Launch Project Manager.
 # Create a new Project.
 # Launch the Editor.
 # Close the Editor.
 # Launch the Editor again.

*Expected Result*: 
 The Editor launches successfully.

*Actual Result*: 
 The Editor fails to launch.

*Call Stack Trace*:
{code:java}
<2021-12-01 11:50:08> : Error: signal Segmentation fault:
/opt/O3DE/21.11/bin/Linux/profile/Default/libCrySystem.so(+0x1f133d)[0x7fd0f241b33d]
/lib/x86_64-linux-gnu/libc.so.6(+0x4620f)[0x7fd2f6b5720f]
/opt/O3DE/21.11/bin/Linux/profile/Default/libAtomToolsFramework.Editor.so(+0x1115dae)[0x7fd2d57f8dae]
/opt/O3DE/21.11/bin/Linux/profile/Default/libAtomToolsFramework.Editor.so(+0x116b73e)[0x7fd2d584e73e]
/opt/O3DE/21.11/bin/Linux/profile/Default/libAtomToolsFramework.Editor.so(+0x43c0b2)[0x7fd2d4b1f0b2]
/opt/O3DE/21.11/bin/Linux/profile/Default/libAtomToolsFramework.Editor.so(+0x42a945)[0x7fd2d4b0d945]
/opt/O3DE/21.11/bin/Linux/profile/Default/libEditorLib.so(+0x692e94)[0x7fd2f2808e94]
/opt/O3DE/21.11/bin/Linux/profile/Default/libEditorLib.so(_ZN11CCryEditApp12InitInstanceEv+0x5e7)[0x7fd2f2c3eae7]
/opt/O3DE/21.11/bin/Linux/profile/Default/libEditorLib.so(CryEditMain+0x5e4)[0x7fd2f2c462f4]
/opt/O3DE/21.11/bin/Linux/profile/Default/Editor[0x433876]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2)[0x7fd2f6b380b2]
/opt/O3DE/21.11/bin/Linux/profile/Default/Editor[0x4336ed]
{code}

**Comment by spham-amzn** [comment]
Cannot reproduce with release 22.05 (Linux)
