### ISSUE TITLE
Disabling Focus Mode and Edit Mode by clicking level name in top left corner of Viewport is inconsistent

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#8231]
**Describe the bug**
When **Edit mode** of any component is enabled and **Focus mode** of a prefab instance is also enabled, disabling the previously mentioned modes by clicking the **level** name in the top left corner of the **Viewport** tool, the behavior of the **Editor** is inconsistent.

The blue border present in the **Viewport** window disappears, but other tools (Entity Outliner, Asset Browser) remain greyed out. In the **Tool** dropdown menu of the Editor, tools are also greyed out as Focus/Edit mode is still enabled.

Also, when a shape component is used to reproduce this issue, the shape disappears in the **Viewport** after pressing the level name.

Please note that this issue is temporary and can be worked around by undoing the action (Ctrl + Z) or pressing the **Esc** key.

**Steps to reproduce**
1. Create a prefab in the level.
2. Enter the **Focus mode** of the created prefab.
3. Add any component, in which **Edit mode** can be enabled (e.g. Non-uniform scale, shape components).
4. Enter the **Edit mode** of the component added in step 3.
5. Press the **level** name in the top left corner of the **Viewport** window.

**Additional step (to work around the issue)**
6. Press **Esc** key or undo the action (Ctrl + Z).

**Expected behavior**
Pressing the **level** name in top left corner of the **Viewport** window disables **Focus mode** and/or **Edit mode**.

**Actual behavior**
Pressing the **level** name in top left corner of **Viewport** window does **not** disable **Focus mode** and/or **Edit mode**. Only the blue border in **Viewport** window disappears.

**Video**

https://user-images.githubusercontent.com/86951967/157667711-fa350be0-d751-477f-b3bf-d7a2c1034e30.mp4

**Found in Branch**
Development (7a75e34)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by LB-KacperMetelski** [comment]
Issue verified as fixed on commit adc2f3f.
