### ISSUE TITLE
Test_chunks.fbx file crashes the Editor for AutomatedTesting project

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#8233]
**Describe the bug**
This issue occurs only on AutomatedTesting Project.

In order for this issue to occur the test_chunks.fbx file has to be set as mesh for the Mesh component. Then open the Fbx scene settings for this mesh and, while opened, move the Mesh entity so it becomes a child to another entity.

**Steps to reproduce**
1. Create 2 entities.
2. Add a Mesh component to the first one.
3. Set Test_chunks.fbx file as a mesh.
4. Open the Fbx scene settings.
5. Move the first entity (in Entity Outliner) to make it a child entity to the other one.

**Expected behavior**
The Editor remains stable. The entity becomes a child entity.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/157674753-5dc6a13b-e996-4563-8753-b814534f49d7.mp4

**Found in Branch**
Development (7a75e34)

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU Nvidia Geforce RTX 2060 SUPER
Memory 16GB

**Additional context**
[error.log](https://github.com/o3de/o3de/files/8223942/error.log)
[error.zip](https://github.com/o3de/o3de/files/8223943/error.zip)

**Comment by AMZN-stankowi** [comment]
Based on the log message, this looks like a prefab bug. The crash's call stack has the prefab trying to apply a patch and crashing.
`17) C:\Builds\Branch\Dev\o3de\Code\Framework\AzCore\AzCore\Serialization\Json\JsonMerger.cpp (289) : AZ::JsonMerger::ApplyPatch_Add
16) C:\Builds\Branch\Dev\o3de\Code\Framework\AzCore\AzCore\Serialization\Json\JsonMerger.cpp (84) : AZ::JsonMerger::ApplyPatch
15) C:\Builds\Branch\Dev\o3de\Code\Framework\AzCore\AzCore\Serialization\Json\JsonSerialization.cpp (128) : AZ::JsonSerialization::ApplyPatch
14) C:\Builds\Branch\Dev\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\PrefabDomUtils.cpp (333) : AzToolsFramework::Prefab::PrefabDomUtils::ApplyPatches
13) C:\Builds\Branch\Dev\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\Instance\InstanceToTemplatePropagator.cpp (168) : `

**Comment by srikappa-amzn** [comment]
This seems like an unintentional side effect of https://github.com/o3de/o3de/blob/b3ba73db3bd562f30e7e7e11b77ac16d2243c956/Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp#L365 which gets called after opening FBX scene settings. It will remove all templates from PrefabSystemComponent, which also includes the templates of any levels and prefabs loaded in the editor. Looks like the function should be doing something more scene-specific than removing all the templates.
Pinging @amzn-mike and @jackalbe to understand what that logic is doing.
