### ISSUE TITLE
Document and setup docker container (Ubuntu 20) for the current O3DE environment on Linux

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/o3de#8241]
Consider using this script as a starting point: https://github.com/o3de/o3de/blob/development/scripts/build/build_node/Platform/Linux/Dockerfile

**Comment by byrcolin** [comment]
A community member worked on some similar stuff here: https://github.com/loherangrin/o3tanks/wiki/cheat-sheet

**Comment by byrcolin** [comment]
No longer relevent
