### ISSUE TITLE
Creating new materials is followed by “Document opened with warnings” window

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#8254]
**Describe the bug**
Creating new materials is followed by “Document opened with warnings” window. Newly create materials can be edited and saved without any issues. Warning window appears with Perforce set to both Online and Offline.

**Steps to reproduce**
1. Launch Material Editor.
2. Navigate to File → New.
3. Create new material by pressing “OK”.

**Expected behavior**
New material is being created without any warnings.

**Actual behavior**
Multiple warnings appear when creating a new material.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/157868151-5ce8da0f-af2a-4d66-bb69-4168e3cc393d.mp4

**Found in Branch**
Development (487c454)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 3600
 - GPU Nvidia GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by monroegm** [comment]
Rerouting to SIG-Graphics-Audio because this has to do with the Material Editor
