### ISSUE TITLE
Edit Mode blue frame stuck there after deleting component

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#8255]
[Migrated from JIRA LYN-8142]

Provide a detailed description of the defect here and include any possible workarounds.
----
**Found in Build**: Daily installer from game jam.

**Reproducibility**: Yes

**Prerequisites**:

Add a component that has editing mode. (in the video example attached, I added non-uniform scale)

**Steps to Reproduce**:

1. Add a component that has editing mode. (in the video example attached, I added non-uniform scale)

2. Enter editing mode via Entity Inspector.

3. Delete the component from the Entity inspector while still in editing mode.

**Expected Result**:

I expected the viewport to exit editing mode and reset back out of editing mode, now that the component that activated it is now deleted.

**Actual Result**:

The blue frame is still present and editing mode is still active. The user can't click done in the entity inspector, because it has been deleted. 

So the only way to exit editing mode with the blue frame to return back to where we came from is to know that ESC is the exit button.

This is not idea, since our editing mode frame does not have it's own exit pattern (I suggested an X in the corner of the frame)

Video attached for reference

https://user-images.githubusercontent.com/82228511/157877148-7a3147ee-e0ad-48b5-97d7-37c3ac2399d3.mp4

**Comment by hultonha** [comment]
@jonawals Could you please verify this issue as I believe it is most likely fixed

(tagging @AMZN-daimini and @amzn-leenguy for visibility too)

**Comment by amzn-leenguy** [comment]
I will check now with a new install of the editor im doing now. Will report back in a few hours.

**Comment by hultonha** [comment]
> I will check now with a new install of the editor im doing now. Will report back in a few hours.

Awesome thank you @amzn-leenguy!

**Comment by amzn-leenguy** [comment]
Just checked this and validated with @AMZN-daimini . The hamburger menu is now not clickable when in edit mode. So this issue doesn't occur anymore. Consider this fixed @hultonha .

**Comment by hultonha** [comment]
Awesome stuff, thank you @amzn-leenguy! 😄
