### ISSUE TITLE
Destruction: Inside/outside mesh chunks are loaded in the Blast Family Mesh Component 

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#8260]
[Migrated from JIRA LYN-735]

Provide a detailed description of the defect here and include any possible workarounds.

**Found in Build**: 

(_note: Blast is currently disabled, review when Blast is enabled again_)

**Reproducibility**: 

100%

**Prerequisites**: 

Have a .fbx and .blast asset.

**Steps to Reproduce**: 

Create a blast family mesh component. In the component, select the .blast_slice file produced for the blast asset.

**Expected Result**:

The inside/outside mesh chunks should not be loaded in the component. 

**Actual Result**: 

The inside/outside mesh chunks are loaded in the component. 

This may require a fix on the Houdini plugin to export blast assets.

**Comment by moraaar** [comment]
Houdini plugin is not supported on O3DE, so there is no way to test.

At the moment the only existing assets are in `o3de\AutomatedTesting\Assets\Destruction` and they work as expected.

I'll close this bug since there is no way workflow supported yet to generate blast assets.
