### ISSUE TITLE
Setting rotation in the Transform Component for Ragdoll entities affects their scale

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#8261]
[Migrated from JIRA LYN-403]

Setting certain rotation values in the *Transform* component for entities with the *Ragdoll*, *Actor* and *Anim Graph* components is affecting their scale on tick in *Editor Mode* and *Game Mode*.

The most noticeable deviations are for rotations 90, 210 and 270 degrees.

For more information please refer to the attached videos.

**Found in Build:** lumberyard-0.0-1071912-pc-3729 (old build)

**Reproducibility:** 3/3

**Prerequisites:**

 * Download the attached files (_.animgraph, .fbx, .fbx.assetinfo_).
 * ~~Active project is *SamplesProject*.~~
   * _Note: This project is not longer available, but Automated Testing should be able to be used instead_

**Steps to Reproduce:** 

 1. Create an entity with the *Actor*, *Anim Graph* and *Ragdoll* components.
 2. Assign the *Actor asset* as the _rin_skeleton_newgeo.fbx_ and the *Material* as the _rinActor.mtl_ in the *Actor* component.
 3. Assign the *Anim graph* as the _Ragdoll_onActivate.animgraph_ and *Motion set asset* as the _Advanced_RinLocomotion.motionset_ in the *Anim Graph* component.
 4. Set the Z rotation in the *Transfrom* component to the 90 degrees.
 5. Deselect the ragdoll entity and wait for a while.
 6. Select the ragdoll entity again, click on the X or Y scale and observe the value.

**Expected Result:**

 Once the entity’s rotation is set, it not affects scale of the this entity.

**Actual Result:**

 Once the entity’s rotation is set, it affects scale of this entity.

https://user-images.githubusercontent.com/82228511/157884683-c66e5faf-ade5-43ab-8acd-9cee0989c67f.mp4

https://user-images.githubusercontent.com/82228511/157884696-ab4ff5c4-863f-4a2b-bd32-4456bb890478.mp4

**Comment by hultonha** [comment]
Tagging @greerdv for visibility

This needs to be verified ideally (tagging @LB-BartoszDudzinski) with the latest transform changes (moving to uniform scale with a non-uniform scale component)

**Comment by LB-BartoszDudzinski** [comment]
Hi @hultonha! I verified this issue and didn't notice any uniform scale changes after rotating the actor. However, I could not verify this with a non-uniform scale component as it is not compatible with actor and ragdoll components.

**Comment by hultonha** [comment]
Hey @LB-BartoszDudzinski, okay awesome! I believe non-uniform scale being incompatible with actor and ragdoll components is intentional so I'd be inclined to close this issue as fixed. Thanks for checking, I'll review with @greerdv in case there is something else we should follow-up on 👍

**Comment by greerdv** [comment]
Yeah, the NUS component being incompatible is intended. Looking again at the video showing the original issue, I'm fairly convinced it was due to a combination of the old matrix-based transform and the poor accuracy in the old trig implementations, both of which have been updated, so I'm happy with closing this.

A separate thing which might be interesting to test would be repeated applying a small rotation through script canvas on an entity and see if there is any scale drift. My guess is that that could still occur as a result of the quaternion becoming badly normalized, but it would be interesting to find out.

**Comment by LB-BartoszDudzinski** [comment]
@hultonha sure, I will try to take care of it this week.

**Comment by LB-BartoszDudzinski** [comment]
@hultonha even after changing the rotation by a script, the scale was unaffected. I've tried the normal rotation and quaternion with the same result. I will test around it for a day or two but it looks like it works well with the uniform scale.

**Comment by hultonha** [comment]
That's great to hear @LB-BartoszDudzinski, thank you very much for the update 👍
