### ISSUE TITLE
White Box Entities created via the Python Script are always cube shaped

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#8264]
[Migrated from JIRA LYN-4720]

*This issue only occurs with Prefabs system enabled.*

Creating a White Box Entity using the Scripts included in `Gems/WhiteBox/Editor/Scripts` always results in a cube shaped Entity being created.

Please refer to the attached video for more details.

**Found in Build**: (unavailable) use development

**Reproducibility**: 3/3

**Prerequisites**: 

 - Prefabs System enabled.

**Steps to Reproduce**:

 - Create or open any Level.
 - Open the Python Scripts window (Tools -> Other -> Python Scripts).
 - Execute any of the White Box Scripts (i.e. `Gems/WhiteBox/Editor/Scripts/Staircase.py`).

**Expected Result**: 

 A correctly shaped White Box Entity is created depending on executed Script.

**Actual Result**: 

 A cube shaped White Box Entity is created.

**Comment by hultonha** [comment]
Tagging @LB-TomaszSerwanski, would you please be able to verify this issue to see if it still happens please? Thank you!

**Comment by LB-TomaszSerwanski** [comment]
Hi @hultonha, we have just verified, that the issue does not occur both on Windows and Linux in the latest Development (487c454).

**Comment by hultonha** [comment]
Oh awesome! 😄 Thank you very much @LB-TomaszSerwanski, if that's the case then I'll close this issue 👍 Cheers!
