### ISSUE TITLE
[Animation Editor] Click Scale under the OpenGL Render Window of the animation editor, modify the model scale, and find that the bones and the skin cannot be scaled synchronously.

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#8289]
**Describe the bug**
Click Scale under the OpenGL Render Window of the animation editor, modify the model scale, and find that the bones and the skin cannot be scaled synchronously.

**Steps to reproduce**
1. Open the animation editor
2. Click File->Open Actor and select a model
3. Click Scale under the OpenGL Render Window to stretch or compress the X, Y, and Z axes

**Expected behavior**
Bone and skin can be scaled in sync

**Actual behavior**
Bone and skin can not be scaled in sync

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

Desktop/Device:

Device: [PC]
OS: [Windows]
Version [10]
CPU [Intel Xeon Gold 6234]
GPU [NVidia RTX 5000]
Memory [32GB]
Working Branch: developement
Additional context

**Comment by monroegm** [comment]
Please reopen or create a new ticket if you are able to provide more information
