### ISSUE TITLE
[Animation] When using the animation blend node, when mixing the animation of walking and running, slowly increase the parameters that control the switching of the mixed animation. When the parameter is at a certain value, the coexistence of the two states of walking and running occurs, and the transition and convergence between the UE4 mixing actions relatively smooth and natural

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#8290]
**Describe the bug**
When using the animation Blendnode, when mixing the animation of walking and running, slowly increase the parameters that control the switching of the mixed animation. When the parameter is at a certain value, the coexistence of the two states of walking and running occurs, and the transition and convergence between the UE4 mixing actions relatively smooth and natural

**Steps to reproduce**
1. Use the Ease animation node to mix walking and running animations
2. Adjust the parameters that control the switching of the mixed animation and watch the effect
3. See error

**Expected behavior**
The transitions and transitions between mixed movements are smooth and natural

**Actual behavior**
There is a phenomenon that two states of walking and running coexist, and the animation transition is blunt

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
Device: [PC]
OS: [Windows]
Version [10]
CPU [Intel Xeon Gold 6234]
GPU [NVidia RTX 5000]
Memory [32GB]
Working Branch: developement

Additional context

**Comment by monroegm** [comment]
@sysuNie Can you take a video of the issue or provide a sample asset?

**Comment by monroegm** [comment]
Please reopen or create a new ticket if you are able to provide more information
