### ISSUE TITLE
[Animation] The movement of characters is stuck and the shaking is obvious, which is inferior to UE4

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#8292]
**Describe the bug**
The movement of characters is stuck and the shaking is obvious, which is inferior to UE4.

**Steps to reproduce**
1. The animation state machine action was added successfully
2. Click Run to enter the running state, operate the character state to view the effect
3. See error

**Expected behavior**
The running animation is smooth and natural, and the picture is not stuck or shaken.

**Actual behavior**
The overall effect is poor, and the movement of characters is stuck and shakes.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Intel Xeon Gold 6234]
- GPU [NVidia RTX 5000]
- Memory [32GB]
- Working Branch: developement

**Additional context**

**Comment by monroegm** [comment]
@sysuNie Can you take a video of the issue or provide a sample asset?
