### ISSUE TITLE
CMake configuration error on Linux due to OpenEXR update.

### ISSUE THREAD

**Issue by neXyon** [o3de/o3de#8302]
**Describe the bug**

Since 2855c9197521363ab3b731ea549ee04f6b70b149, trying to configure o3de for building on linux (with `-G Ninja_MultiConfig` following the documentation) I repeatedly get errors regarding `IMPORTED_LOCATION` not being set for the imported targete `OpenEXR::OpenEXR`:

**Steps to reproduce**
1. `git checkout 2855c9197521363ab3b731ea549ee04f6b70b149` in the source directory
2. `cmake .` in the build directory

**Expected behavior**
CMake configuration and generation done without errors.

**Actual behavior**
```
-- Configuring done
CMake Error in Gems/Atom/Asset/ImageProcessingAtom/Code/CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "OpenEXR::OpenEXR"
  configuration "debug".

CMake Error in Gems/Atom/Asset/ImageProcessingAtom/Code/CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "OpenEXR::OpenEXR"
  configuration "profile".

CMake Error in Gems/Atom/Asset/ImageProcessingAtom/Code/CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "OpenEXR::OpenEXR"
  configuration "release".

CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "OpenEXR::OpenEXR"
  configuration "profile".

CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "OpenEXR::OpenEXR"
  configuration "release".

CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "OpenEXR::OpenEXR"
  configuration "debug".

... [errors repeat a couple of times]

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Found in Branch**
2855c9197521363ab3b731ea549ee04f6b70b149

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Arch Linux
 - Version: latest
 - CPU: Intel i7-11800H
 - GPU: Nvidia GeForce RTX 3080 Laptop GPU
 - Memory: 32 GB

**Comment by jhmueller-huawei** [comment]
I temporarily fixed this with this patch:

```diff
diff --git a/FindOpenEXR.cmake b/FindOpenEXR.cmake
index f6712e3..aa9af7e 100644
--- a/FindOpenEXR.cmake
+++ b/FindOpenEXR.cmake
@@ -26,6 +26,14 @@ set(OpenEXR_COMPONENTS
     OpenEXR::OpenEXR
 )
 
+if (${PAL_PLATFORM_NAME} STREQUAL "Linux")
+	set(OpenEXR::Iex_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/OpenEXR/lib/libIex-3_1.a)
+	set(OpenEXR::IlmThread_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/OpenEXR/lib/libIlmThread-3_1.a)
+	set(OpenEXR::OpenEXRCore_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/OpenEXR/lib/libOpenEXRCore-3_1.a)
+	set(OpenEXR::OpenEXRUtil_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/OpenEXR/lib/libOpenEXRUtil-3_1.a)
+	set(OpenEXR::OpenEXR_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/OpenEXR/lib/libOpenEXR-3_1.a)
+endif()
+
 foreach(component ${OpenEXR_COMPONENTS})
     if(TARGET ${component})
         # convert the includes to system includes
@@ -43,12 +51,16 @@ foreach(component ${OpenEXR_COMPONENTS})
 		
 		# inside the loop where it sets the system includes for each component
 		foreach(conf IN LISTS CMAKE_CONFIGURATION_TYPES)
+			if (NOT ${component} MATCHES "Config$")
+				set_target_properties(${component} PROPERTIES IMPORTED_LOCATION_${UCONF} ${${component}_LIBRARY})
+			endif()
+
 			string(TOUPPER ${conf} UCONF)
 			if (${UCONF} STREQUAL "DEBUG" AND ${CMAKE_SYSTEM_NAME} STREQUAL Windows)
 				set_target_properties(${component} PROPERTIES 
```

**Comment by lawsonamzn** [comment]
This is interesting. 
the packages do set IMPORTED_LOCATION_RELEASE and they do set IMPORTED_LOCATION_${UCONF} RELEASE
so its unclear to me why this would fail on linux?  See the lines just below your patch - they are supposed to set IMPORTED_LOCATION_${UCONF} RELEASE

Where ${UCONF} is pretty much every configuration that is being input.  So everything should map to RELEASE and pull from IMPORTED_LOCATION_RELEASE.

You can check the config files - in the 3p package folder, they're in OpenEXR/lib/cmake

Perhaps it cached the wrong package ver?  Do you have cache vars OpenEXR_DIR and if you clear them, does it change?

**Comment by lawsonamzn** [comment]
I'm about to issue a new Open EXR package (rev3) which has a significantly different FindOpenEXR file.

But I'm still unable to repro this on Ubuntu 20.04 even with Ninja Multi-Config on linux in debug.   It should work - the existing (rev2) script imports the auto-generated CMake Config Files that ship with OpenEXR's install.  Those config files use the standard CMake config generation utility, which always declares IMPORTED_LOCATION_xxxxx for each config the package is built in.

Then our find script loops over every element in CMAKE_CONFIGURATION_TYPES (which will be the list 'debug', 'profile', 'release' in O3DE, and 'Debug', 'Profile', and 'RelWithDebInfo' in other projects for example) and defines  the mapping such that that configration uses the RELEASE version of the package.

If you're still getting this information it'd be good to know which version of cmake is being used.  Perhaps this relies on some feature we're not at yet?

**Comment by jhmueller-huawei** [comment]
On rev2: how does that even work? I put a `message` call at the beginning of all files in `OpenEXR/lib/cmake/OpenEXR/` and they are never called, because the files are not included anywhere (e.g. in the FindOpenEXR file).

I'm running cmake version 3.22.3.

**Comment by lawsonamzn** [comment]
rev2 should be finding those configs by doing this:
```
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ${CMAKE_CURRENT_LIST_DIR}/OpenEXR/lib/cmake)
find_package(Imath MODULE REQUIRED) # will bring in the FindImath.cmake in the same folder
find_package(OpenEXR CONFIG REQUIRED)
```

it adds that folder to the end of the prefix path, then calls find_package but explicitly puts it in CONFIG mode.

IMath also does this:
```
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ${CMAKE_CURRENT_LIST_DIR}/OpenEXR/lib/cmake)
find_package(Imath CONFIG)
```

By asking for CONFIG mode, it should go hunting in those folders in the prefix path list for the config files.  However, putting them at the end of the prefix path means that other folders containing openEXR configs might be grabbed first if in the user's prefix folder which makes it vulnerable to environmental differences.

The new revision (3) is currently in PR to solve this.  Instead of doing the above, it does this:
```
macro(o3de_import_existing_config_files package_name search_dir)
    # some platform toolchains switch CMake into a mode where it will not search
    # sysroot or the CMAKE_PREFIX_PATHs, so we use the FIND_ROOT_PATH.
    # for other platforms, we set the xxxx_ROOT value.
    set(_old_find_root_path ${CMAKE_FIND_ROOT_PATH})
    set(CMAKE_FIND_ROOT_PATH ${search_dir} ${CMAKE_FIND_ROOT_PATH})
    set(${package_name}_ROOT ${search_dir})
    # its also possible that an older version of _DIR has been cached.
    unset(${package_name}_DIR CACHE)
    unset(${package_name}_DIR)
    find_package(${package_name} CONFIG REQUIRED)
    # reset these variables back to what they were.
    set(CMAKE_FIND_ROOT_PATH ${_old_find_root_path})
    if (NOT ${package_name}_FOUND)
        message(FATAL_ERROR "Could not import configs for ${package_name} from ${search_dir}")
    endif()
    mark_as_advanced(${package_name}_DIR) # Hiding from GUI
endmacro()
```

Which makes it search that dir preferentially, without using the system path.

**Comment by jhmueller-huawei** [comment]
> rev2 should be finding those configs by doing this:
> 
> ```
> set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ${CMAKE_CURRENT_LIST_DIR}/OpenEXR/lib/cmake)
> find_package(Imath MODULE REQUIRED) # will bring in the FindImath.cmake in the same folder
> find_package(OpenEXR CONFIG REQUIRED)
> ```

That's the issue as you describeid it, since cmake now finds my system installed OpenEXR first. If I swap the command to:

```
set(CMAKE_PREFIX_PATH ${CMAKE_CURRENT_LIST_DIR}/OpenEXR/lib/cmake ${CMAKE_PREFIX_PATH})
```

and unset the `OpenEXR_DIR` in the cache, it works. When the PR for rev3 goes through, this problem should be fixed.

**Comment by lawsonamzn** [comment]
Thanks for getting back to us on this.  I'll try to get rev3 out soon.  The PR has some stuff folks have asked to fix.  Once that's done and tested it will get pushed to development, which would auto update to rev3 next pull.

**Comment by lawsonamzn** [comment]
This was fixed by the above commit to development.
