### ISSUE TITLE
AR fails due to outdated script assets when ScriptCanvas runtime changes, even with Builder version bump

### ISSUE THREAD

**Issue by carlitosan** [o3de/o3de#8313]
When the ScriptCanvas Builder version is incremented, the AP automatically detects this, and re-builds all of the ScriptCanvas assets, including their runtime implementation. This is easily reproduced locally, even without clearing the cache. However, when submitting these code changes, including an incremented builder version, the AP on the AR run does NOT re-build all of ScriptCanvas. If the old version of the SC runtime assets is no longer operable in the altered SC runtime, the AR will fail.

The problem is specifically indicated here in the console output:
`Access to undeclared global variable 'OverrideNodeableMetatable' `

That global function, OverrideNodeableMetable was from the SC runtime, and the translation system. The builder version was bumped, to make sure and rebuild every graph that may attempt to call this no longer available function. I then tested this by adding and removing deliberately failing runtime asserts, and submitting builder version bumps with the new AR passes. The AR would always run the previous compiled version of the asset, where as locally, the AP would start up, and re-build every graph.

**Comment by FuzzyCarterAWS** [comment]
AssetDB from #8002 

[Cache-GHI-8002.zip](https://github.com/o3de/o3de/files/8256170/Cache-GHI-8002.zip)

**Comment by AMZN-stankowi** [comment]
Triage: We discussed this in our standup, this is something the asset pipeline group will look to. I confirmed with amzn-changml
