### ISSUE TITLE
[Landscape Canvas] Entity Name does not update

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#8324]
**Describe the bug**
If the Entity Name is changed in the Entity Outliner, the old name in the Landscape Canvas remains.
To change the name to the correct one, the user has to manually retarget the entity in the Node properties or
remove the entity from the Landscape Canvas hierarchy in the Entity Outliner and then add it again.

**Steps to reproduce**
1. Go to Landscape Canvas.
2. Add any Node.
3. Close the Landscape Canvas.
4. Go to Entity Outliner.
5. Rename the corresponding entity.
6. Reopen the Landscape Canvas.

**Expected behavior**
The Entity Name is updated.

**Actual behavior**
The old Entity Name remains.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/158378426-731404c2-dbdf-4ee7-87f9-8e2becc23a7c.mp4

**Found in Branch**
Development (54ecb02)

**Desktop/Device:**
Device: PC
OS: Linux
Version Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU Nvidia Geforce RTX 2060 SUPER
Memory 16GB

**Comment by LB-BartoszDudzinski** [comment]
Issue verified as Fixed in the latest development branch (4df30e4).
