### ISSUE TITLE
Asset Processor fails to process MinimalPBR .material files for AtomSampleViewer project

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#8327]
**Describe the bug**
The following 3 Atom Material Builder jobs fail processing for the .material assets (all platforms):
`Materials/MinimalPBR/MinimalPBR_BlueMetal.material`
`Materials/MinimalPBR/MinimalPBR_RedDielectric.material`
`Materials/MinimalPBR/MinimalPBR_Default.material`

Please refer to the attached .log files for more information.

**Prerequisites:**

- AtomSampleViewer is built via Visual Studio following the instructions under https://www.o3de.org/docs/atom-guide/setup-atom-projects/.

**Steps to reproduce**
1. Enable additional platforms by modifying the _/o3de/Registry/AssetProcessorPlatformConfig.setreg_ file.
2. Launch the AssetProcessor.exe from the _/AtomSampleViewer/build/bin/profile/_ directory.
3. Wait until all the assets are processed.

**Expected behavior**
All assets are processed without failure.

**Actual behavior**
The MinimalPBR Atom Material Builder jobs fail processing.

**Screenshot**
![AP_MinimalPBR_Failed](https://user-images.githubusercontent.com/86953659/158399450-f9a3c713-0a7d-4121-abd1-cbf554b23e53.PNG)

**Found in Branch**
Development (54ecb02)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i5-9600K
 - GPU: NVIDIA GeForce RTX 2070
 - Memory: 16GB
 
**Additional context**
[MinimalPBR_BlueMetal.material-1530288221-29080.log](https://github.com/o3de/o3de/files/8254191/MinimalPBR_BlueMetal.material-1530288221-29080.log)
[MinimalPBR_RedDielectric.material-2110423946-33086.log](https://github.com/o3de/o3de/files/8254194/MinimalPBR_RedDielectric.material-2110423946-33086.log)
[MinimalPBR_Default.material-2030197664-31188.log](https://github.com/o3de/o3de/files/8254196/MinimalPBR_Default.material-2030197664-31188.log)

**Comment by superkitcath** [comment]
Hi @LB-KacperKapusta; we believe that this was fixed yesterday in the afternoon, could you check again? Thanks!!

**Comment by LB-KacperKapusta** [comment]
Hi @superkitcath; it has been confirmed using the latest Development of O3DE and AtomSampleViewer that the described issue does no longer occur, therefore it can be closed. A new issue has been logged under https://github.com/o3de/o3de/issues/8375 for AP failing .shader files.
