### ISSUE TITLE
Bug Report: [Linux] Frame rate in the editor is lower than when in game mode

### ISSUE THREAD

**Issue by amzn-pratikpa** [o3de/o3de#8334]
**Describe the bug**
This was observed on a machine used by @adamdbrw. The FPS in the editor was ~44 and ~60 after pressing CTRL+G.

**Steps to reproduce**
1. Go to the editor on Linux and create the default level
2. Observe FPS
3. Press CTRL+G
4. Observe FPS
5. The two FPS readings are different.

**Expected behavior**
The two FPS numbers should be the same.

**Desktop/Device (please complete the following information):**
 - Device: Desktop 
 - OS: Ubuntu 20.04LTS
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU RTX 3060
 - Memory [e.g. 16GB]

**Additional context**

**Comment by burelc-amzn** [comment]
I can't repro this with a RTX 2060. I only get ~30 FPS in both Editor and Game mode.

**Comment by adamdbrw** [comment]
CPU: Intel Core i7-10750H
Memory 16 GB
GPU: NVIDIA GeForce RTX 2070 (Super with Max-Q Design) - _I thought this laptop had RTX 30xx but I was wrong._
The Editor build configuration: **_profile_**.

I can also look into it on my machine if it can't be reproduced on similar setup.

**Comment by byrcolin** [comment]
This is not a bug. The Editor naturally has more thing running than the runtime alone.

**Comment by adamdbrw** [comment]
@byrcolin: Just for clarity, that was not the issue since the level was empty. I believe there was an artificial hard limit at that time but perhaps it is not there anymore.
