### ISSUE TITLE
Nightly Build Failure: test_ScriptCanvas_PreUpdateEvent fails after prefab conversion

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#8341]
**Describe the bug**
 test_ScriptCanvas_PreUpdateEvent fails after prefab conversion 

**Failure type**
Test

**To Reproduce Test Failures**
 * A freshly processed cache
 * Execute Python Test
 ```
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Periodic.py::TestAutomation::test_ScriptCanvas_PreUpdateEvent --build-directory <build_dir_path>\bin\profile
```

**Expected behavior**
Test passes

**Logs**
https://jenkins-pipeline.agscollab.com/blue/rest/organizations/jenkins/pipelines/O3DE-LY-Fork-development_nightly-clean/runs/290/nodes/1749/log/?start=0

**Additional context**
After investigation, this appears to be due to a bad starting position of test objects and a dereferenced SC Entity Variable Reference

**Comment by FuzzyCarterAWS** [comment]
PR #8342

**Comment by hultonha** [comment]
@FuzzyCarterAWS it looks like PR #8342 is merged now, can this issue be closed? Thanks!
