### ISSUE TITLE
o3de Editor - FBX with Bones now has two Components added at once.

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8345]
[Migrated from JIRA ATOM-17445]
Provide a detailed description of the defect here and include any possible workarounds.
----
Found in Build: Development Build as of 3/14/22

Reproducibility: Yes

Prerequisites: Latest build

Steps to Reproduce: Draw an .FBX with a skinned mesh with bones.

Expected Result: You would only get the Actor Component. 

Actual Result: You get both the Actor and Mesh Component. 

!image-2022-03-14-10-11-21-915.png|width=361,height=1112!

**Comment by nick-l-o3de** [comment]
https://github.com/o3de/o3de/pull/18119 does not fix this, but I can no longer reproduce this on stabilization or on development.  Please retest and close?
