### ISSUE TITLE
HttpRequestor calls and additional documentation

### ISSUE THREAD

**Issue by NiklasHenricson** [o3de/o3de#8351]
When you apply a Broadcast call via HttpRequestor (let's say in an Active() or an Init() method); unfortunately our custom back-end AZ_COMPONENT gets activated and its methods (Init, Activate) get called before the HttpRequestor System Component retrieves the response from the REST call.

Therefore its lost in the void, since there's no listener for the EBus at that point. To workaround (so I can be able to test it), we did a delayed call in the OnTick method (around 10 seconds or so). That's the only way to get the JSON printed out in the console.

If this is intended, please provide information on how to test properly REST calls in the future. This is kinda paramount to get things done before the system loads. An architectural diagram would help to figure out how this is intended to be used. Thank you.

Code example on the delayed call,

```cpp
    void FancySystemComponent::OnTick([[maybe_unused]] float deltaTime, [[maybe_unused]] AZ::ScriptTimePoint time)
    {
        if (timeAggregator > 10.0f) //Calling this session every 10 seconds.
        {
            AZ_Warning("FancySystemComponent", false, "FancySystemComponent::OnTick() 10 Seconds");
            mySuperDuperAwesomeDataProvider.GetSomeCoolDataRightHere();
            timeAggregator = 0;
        }
        timeAggregator += deltaTime;
    }

```

Example on the diagram I'm talking about ,

https://docs.unity3d.com/Manual/ExecutionOrder.html[](https://unity3d.com/files/images/ogimg.jpg)

**Comment by lumberyard-employee-dm** [comment]
Moving to @o3de/sig-network for triaging.

**Comment by NiklasHenricson** [comment]
Ended up using our own EBus implementation instead and listen to whenever the response and data transformation was done beign processed.

Currently our issue is try to figure out when,

A. Game Mode (the system is running, and in this case the server/back-end part of O3DE)
B. Game Mode is terminated
C. Whether or not we're in editor mode, or actively running the system outside the editor

**Comment by lumberyard-employee-dm** [comment]
> Ended up using our own EBus implementation instead and listen to whenever the response and data transformation was done being processed.
> 
> Currently our issue is try to figure out when,
> 
> A. Game Mode (the system is running, and in this case the server/back-end part of O3DE) B. Game Mode is terminated C. Whether or not we're in editor mode, or actively running the system outside the editor

We actually have events for when Game Mode start and ends as a well as a way to check them
For detecting whether Game mode is running the [EditorEntityContextRequests::IsEditorRunningGame](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextBus.h#L123-L124) function can be invoked.

For detecting whether when Game Mode is entered or exited, the EditorEntityNotifications [OnStartPlayInEditor and OnStopPlayInEditor](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextBus.h#L180-L184) can be handled via an EBus handler.

Now for Determining if the application is running outside of the Editor, the ComponentApplicationRequests interface can be used to [query the Application Type](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextBus.h#L180-L184)
```
AZ::ApplicationTypeQuery applicationType;
if (auto componentApplicationRequests = AZ::Interface<ComponentApplicationRequests>::Get();
    componentApplicationRequests != nullptr)
{
    componentApplicationRequests->QueryApplicationType(applicationType);
}

if (applicationType.IsEditor())
{
     // Do stuff
}
```
```

**Comment by lmbr-pip** [comment]
@NiklasHenricson - Did @lumberyard-employee-dm  response answer your questions?

**Comment by AMZN-Olex** [comment]
Your custom system component can also express dependency requirement on the http system component. This way http system component is ready before your component.

**Comment by lmbr-pip** [comment]
Convert to docs story at this point, break out any engineering work into separate issues.

**Comment by lmbr-pip** [comment]
Closing this out as we have documentation task created.
