### ISSUE TITLE
Sprite Editor button is invisible and non-functional

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#8355]
**Describe the bug**
There is an invisible button on the Image UI component which should bring up the Sprite Editor tool (as per https://www.o3de.org/docs/user-guide/interactivity/user-interface/editor/sprite-editor/. Currently, clicking a place where it should be, with a Sprite path assigned causes an error to pop up:
![Error](https://user-images.githubusercontent.com/86952082/158584167-586993e6-5aeb-46c3-a42b-1d902ffae00b.PNG)

It should be noted that no logs mentioned in the error were found, nor were they e.g. printed to the Console/Editor.log

**Steps to reproduce**
1. Go to Tools > UI Editor.
2. Click the "New..." button in the top left corner to add an element, and add an Image component to it.
3. Add a compatible asset to the "Sprite path" property (e.g. <project directory>/preview.png).
4. Click a spot to the right of the folder button in the "Sprite path" property to open the Sprite Editor (please refer to the **Deprecated Image component and video** section for an image where the Sprite Editor button is located). 

**Expected behavior**
Sprite Editor is opened.

**Actual behavior**
An error pops up, and the Sprite Editor does not open.

**Deprecated Image component and video**

Deprecated Image component (Source: https://www.o3de.org/docs/user-guide/interactivity/user-interface/editor/sprite-editor/):
![ui-editor-sprite-editor-1](https://user-images.githubusercontent.com/86952082/158582117-01d97fc7-2cff-487d-8446-e5e371da7b42.png)

https://user-images.githubusercontent.com/86952082/158580724-c855b227-2fa5-440e-ba01-cd4b35ce1622.mp4

**Found in Branch**
Development (b90a8f3)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by AlkanetSmorgas** [comment]
The log file this case seem to be AP_GUI.log.
```
~~1668006039238~~0~~0000000000002A6C~~Debug~~GetFullSourcePath no result, returning original textures/test.jpg...
~~1668006039238~~1~~0000000000002A6C~~AssetProcessor~~Could not find full source path from the relative product path (textures/textures/test.jpg).
```
