### ISSUE TITLE
AR Bug Report: Android asset_profile job red due to materialtype assets failing to be processed

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#8373]
**Describe the bug**
AR job Android asset_profile is failing with errors when processing materialtype assets.

**Failed Jenkins Job Information:**
Android asset_profile
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/2002/pipeline/741/

````
AssetProcessor: Failed TestData/Materials/Types/AutoBrick.materialtype, (android)... 
AssetProcessor: Failed TestData/Materials/Types/MinimalPBR.materialtype, (android)... 
AssetProcessor: Failed Materials/Terrain/PbrTerrain.materialtype, (android)... 
AssetProcessor: Failed Materials/Types/Skin.materialtype, (android)... 
AssetProcessor: Failed Materials/Types/StandardPBR.materialtype, (android)... 
AssetProcessor: Failed Materials/Types/EnhancedPBR.materialtype, (android)... 
AssetProcessor: Failed Materials/Types/StandardMultilayerPBR.materialtype, (android)... 
AssetProcessor: Failed Materials/Types/BasePBR.materialtype, (android)... 
````

This is the first error reported in all of them:
````
ERROR | >	All shaders in a material must use the same object ShaderResourceGroup. from AssetBuilder
````

**Attachments**
[log.txt](https://github.com/o3de/o3de/files/8284043/log.txt)

**Comment by superkitcath** [comment]
@moraaar ; can you check if this was fixed? Thanks!

**Comment by moraaar** [comment]
This is a random failure that has been seen in AR, which was worked around by running AR again. But it'd be appropriate for sig/graphics-audio to take a deeper look at this to verify if this was a one time error or if there is something else going on here that must be fixed.

**Comment by galibzon** [comment]
@moraaar This bug was triggered by some stale shader assets. After cleaning the asset cache on the incremental builds it's been resolved.
