### ISSUE TITLE
Linux: Mesh components lack the ability to modify the "Sort Key" property value. 

### ISSUE THREAD

**Issue by jromnoa** [o3de/o3de#8380]
**Describe the bug**
The Mesh component "Sort Key" property value cannot be set when using a Linux build of o3de.

**Steps to reproduce**
1. Assuming your AutomatedTesting project build is in /home/new_user/git/o3de/build/linux/bin/profile use the following command to launch the Editor:
```
./home/new_user/git/o3de/build/linux/bin/profile/Editor
```
2. Once the Editor launches, create a new entity and attach a Mesh component.
3. Assign a random material path to the Mesh Asset property value and observe the Sort Key property.
4.  *Conclusion:* Can't set Sort Key property value. This causes the main suite Atom tests to fail when the _C:\git\o3de\AutomatedTesting\Gem\PythonTests\Atom\tests\hydra_AtomEditorComponents_MeshAdded.py_ test is run.

**Expected behavior**
Sort Key can have its property value set on a Mesh component with a Mesh Asset property value set.

**Actual behavior**
Sort Key cannot have its property value set.

**Assets required**
None.

**Screenshots/Video**
https://i.imgur.com/HrkD7NH.png

**Found in Branch**
commit 66bfacdc99c51565f6077c2a94b71bcd888ca3ed on branch development using Linux (ubuntu 20.04.4)

**Desktop/Device (please complete the following information):**
 - Device: g4dn.2xlarge
 - OS: Linux
 - Version: Ubuntu 20.04.4
 - CPU: Intel® Xeon(R) Platinum 8259CL CPU @ 2.50GHz × 8 
 - GPU: NVIDIA Corporation TU104GL [Tesla T4]
 - Memory: 30.9 GB

**Additional context**
This blocks the completion of https://github.com/o3de/o3de/issues/5628 until fixed.

**Comment by spham-amzn** [comment]
Unable to repro with Linux deb installer 2310.2
