### ISSUE TITLE
Linux:  Mouse Pointer Disappears If Closing Server while in Editor Gamemode

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#8403]
Shutting down the server app without stopping game-mode in editor causes the mouse pointer to disappear.

**Steps to reproduce**
1. Open any project with Multiplayer Gem enabled (AutomatedTesting or Multiplayer Sample will work)
2. Set cvar: **editorsv_enabled = true**
3. Run game-mode (CTRL+G)
4. Once the server app opens and takes focus press F4 (closing the server)

**Expected behavior**
I should be able to see my mouse pointer after exiting game mode.

**Actual behavior**
Linux mouse pointer disappeared.
The only way to see my mouse again is to close (F4) the Editor

**Desktop/Device (please complete the following information):**
 - OS: Linux (Ubuntu)

**Comment by rainbj** [comment]
Great issue. Was found as part of UX testing for building a multiplayer . Issue verified by UX.

**Comment by lmbr-pip** [comment]
Relates to https://github.com/o3de/o3de/issues/9841

**Comment by Darkinggq** [comment]
ref:#11491

**Comment by thesmallcreeper** [comment]
https://github.com/o3de/o3de/pull/11491 might do the trick.

**Comment by thesmallcreeper** [comment]
https://github.com/o3de/o3de/pull/11491 which merged, might do the trick.

**Comment by AMZN-Gene** [comment]
Verified fixed.
