### ISSUE TITLE
Improved subsurface scattering rendering in Skin materialtype

### ISSUE THREAD

**Issue by liukaikai-g** [o3de/o3de#8411]
**Is your feature request related to a problem? Please describe.**
When used skin materialtype I found that the sub-surface scattering effect of O3DE is not as good as Unreal, especially the transmission, are there any plans to improve this effect.

**Describe the solution you'd like**
Improved subsurface scattering rendering in Skin materialtype.

**Describe alternatives you've considered**

**Additional context**
O3DE
![image](https://user-images.githubusercontent.com/55627654/159232458-778769d5-bcd6-4d08-9168-217999485131.png)

UE
![image](https://user-images.githubusercontent.com/55627654/159232542-a9b11bed-b763-462e-82d8-a7bbb99f1ed0.png)

The original
![image](https://user-images.githubusercontent.com/55627654/159232709-324df0af-7f47-4c09-85fd-01034f361fa9.png)

**Comment by santorac** [comment]
@antonmic you were working on some custom SS improvements last year, did those ever make it back into the engine? I wonder if that would address the concern here.

@liukaikai-g do you have test assets that you could provide, attached to the Issue?

**Comment by galibzon** [comment]
Action item: @Bindless-Chicken  to create RFC to define rendering standards against a DCCTool like Blender, etc.
