### ISSUE TITLE
[Linux] Editor crashes after pressing Capture CubeMap button within component

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#8456]
**Describe the bug**
Capturing the CubeMap crashes the Editor. The issue occurs only on the Linux platform.

Please note that the crash logs were not created inside the user/log folder.

**Steps to reproduce**
1. Create an entity.
2. Add the CubeMap Capture component.
3. Press the Capture CubeMap button.

**Expected behavior**
The CubeMap is captured. The Editor remains stable.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/159701051-71b554b7-1581-4daa-a3e1-61a1d0d2aaa0.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/9e96dcf500d5ed25728d1fca7f1a77bf73eaa5d9)

**Desktop/Device:**

- Device: PC
- OS: Ubuntu
- Version 20.04
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by rgba16f** [comment]
Pinging @dmcdiarmid-ly, he owns the Cubemap capture component

**Comment by LB-BartoszDudzinski** [comment]
hi! @jeremyong-az I was unable to get a crash dump with the instructions you provided. I even change the sysctl kernel.core_pattern path manually to different folder with no results. No crash logs were available. I checked also /var/crash, var/spool and /var/lib/systemd/coredump folders.
When I tried to attach the Editor process to the debugger (tried both GDB and LLDB) the Editor freezes and after a while the process is being killed. The command I used for that was:
`sudo GDB -p EditorID`
I've verified that the simple c++ hello world script works fine with the debugger.

**Comment by LB-BartoszDudzinski** [comment]
Please note, that the Editor crashes also when the Bake Reflection Probe button is being pressed in the Reflection probe component.

**Comment by spham-amzn** [comment]
Closing this issue. As of commit https://github.com/o3de/o3de/commit/0369b4a9298d306e7c2f06754208f4f399deba63 this is not reproducible from both AutomatedTesting or a New project.

https://user-images.githubusercontent.com/82231385/169604004-1608b904-434f-4c29-afb5-f17578d4d324.mp4

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in Development.
