### ISSUE TITLE
[Linux] [ROS2 Gem] Cmake support for ros2 dependencies

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de#8457]
As a ROS2 Gem user, I would like my Projects using the Gem to build and link with ros2 with minimum effort. 

**Describe the solution you'd like**
A solution that:
- allows the user to specify which ros2 packages to include. Custom messages are a good example of a package that users would want to use with O3DE on the project level.
- requires a minimal amount of added cmake code, is clear in intention.
- respect ros2 packages visibility in a typical ros2 fashion (through [environment sourcing](https://docs.ros.org/en/rolling/Tutorials/Configuring-ROS2-Environment.html)). 
- detects whether ros2 is installed and sourced while building the Gem, warns and returns if this is not the case 

I propose a cmake function to add ros2 dependencies to a given target.
- defined in ROS2 Gem and included there
- available in each Project with the Gem enabled.

Alternatives
An advanced user can setup a project to use ros2 without cmake utilities. This effort would be repeated among many users so it is not optimal.

**Additional context**

To enable the best solution, Gems need to be able to either make .cmake files available for Projects using them, or for Project build to first visit Gem top-level cmake which would include the required file with a defined function. Update: this is already done.

**Comment by lumberyard-employee-dm** [comment]
Hello @adamdbrw could you add an RFC to the @o3de/sig-core issues for review of adding the ROS2 gem using the RFC Template that is located [here](https://github.com/o3de/sig-core/issues/new?assignees=&labels=rfc-feature&template=rfc-feature.md&title=Proposed+RFC+Feature+%3Ddescription%3D)

**Comment by lumberyard-employee-dm** [comment]
@adamdbrw 
Also the work to re-order how external subdirectories are visited when using a project is now in development: https://github.com/o3de/o3de/pull/8388.
Gems will be included before a project's CMakeLists.txt is visited.

Furthermore the add_subdirectory can be adjusted based on using the "Dependencies" field within the gem.json.
This is explained more in the following post in the "impactful-changes" channel in Discord: https://discord.com/channels/805939474655346758/852574203437121586/959143431639294022

**Comment by adamdbrw** [comment]
> Hello @adamdbrw could you add an RFC to the @o3de/sig-core issues for review of adding the ROS2 gem using the RFC Template that is located [here](https://github.com/o3de/sig-core/issues/new?assignees=&labels=rfc-feature&template=rfc-feature.md&title=Proposed+RFC+Feature+%3Ddescription%3D)

Thank you for this suggestion, I have submitted the [RFC Issue](https://github.com/o3de/sig-core/issues/33).

**Comment by lumberyard-employee-dm** [comment]
Thanks @adamdbrw.
The @o3de/sig-core group will provide feedback on it.

**Comment by adamdbrw** [comment]
Fixed by https://github.com/RobotecAI/o3de-ros2-gem/pull/20
