### ISSUE TITLE
AR Bug Report: Multiplayer Flaky Test

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#8467]
**Describe the bug**
Multiplayer Flaky test was reported during a pull request automated review.

[FAILED ] Failure: Failed to find expected line: MultiplayerEditorConnection: Editor-server activation has found and connected to the editor.

Note: This is the same issue seen that was originally resolved after rotating the port after for each test.

**Failed Jenkins Job Information:**
https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-8424/1/execution/node/527/log/?consoleFull

**Attachments**
Attach the Jenkins job log as a .txt file and any other relevant information.

**Additional context**

**Comment by AMZN-Gene** [comment]
@AMZN-alexpete might have a solid repro of this on his local machine

**Comment by willihay** [comment]
I'm getting a consistent repo in my failed AR runs too:
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-8462/7/pipeline/672

**Comment by AMZN-Gene** [comment]
Throwing up a PR to move the tests back into sandbox until we can resolve this issue: https://github.com/o3de/o3de/issues/8605
