### ISSUE TITLE
Cannot build project from Project Manager with only Visual Studio 2022 installed.

### ISSUE THREAD

**Issue by mattiascibien** [o3de/o3de#8478]
**Describe the bug**
After adding support for Visual Studio 17 I have noticed that, when having only VS2022 installed, it is not possible to build the project using the Build menu in the project manager. Building from the command line using cmake manually is working and running fine.

I have identified the problem in the following lines: https://github.com/o3de/o3de/blob/development/Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp#L21-L25. Project manager in fact forces the usage of `Visual Studio 16` as the CMake Generator.

I cannot open an MR at the moment as I do not know which direction should be taken in order to fix this. 

**Steps to reproduce**
1. Go to 'Project Manager'
2. Click on 'Project Hamburger Menu -> Build'

**Expected behavior**
The project builds using the correct version of Visual Studio

**Actual behavior**
The project does not build and the following log is produced

```
CMake Error at CMakeLists.txt:5 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/src/MyTest/build/windows/CMakeFiles/CMakeOutput.log".
````

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Comment by AMZN-nggieber** [comment]
@mattiascibien If some of the reviewers were able to provide a direction for implementation of this feature, would you or anyone else be interesting in implementing it?

**Comment by mattiascibien** [comment]
@mattiascibien I could do it. Just need to know what the general idea on this could be.

I was thinking maybe by providing a new setting inside the project creator. What do you think?

**Comment by amzn-leenguy** [comment]
@mattiascibien did you maybe one to pop into one of the SIG UI UX office hours to talk to this feature request more? Maybe @AMZN-nggieber can also join to brainstorm for 30 mins. What do you think?

**Comment by HydrogenC** [comment]
> This is more of a feature request as we currently don't officially support VS2022

Now I get "Visual Studio 2019 version 16.9.2 or higher not found." on project creation. There was no VS version check in 21.11.0 and I succeeded in building with VS2022 without exceptions, so is there an option to disable the VS version check while creating a project?

**Comment by mattiascibien** [comment]
> @mattiascibien did you maybe one to pop into one of the SIG UI UX office hours to talk to this feature request more? Maybe @AMZN-nggieber can also join to brainstorm for 30 mins. What do you think?

Sorry. For some strange reason GitHub did not send me a notification about this mention. Very nice that the CMAKE uses the latest VS withkut specifying a generator. Good to know.
