### ISSUE TITLE
Proposed RFC Feature: Audio Requests Refactor

### ISSUE THREAD

**Issue by amzn-phist** [o3de/o3de#8503]
# RFC - Audio Requests Refactor

## Summary:

This proposes to refactor and rewrite the implementation of Audio Requests in the Audio System Gem.

## What is the relevance of this feature?

The current implementation of audio requests is not easy to maintain, use, and extend.  For programmers, adding a new request type to the system is more complicated than it should be.  It is important to simplify the design of audio requests so that programmers can spend more time writing the interesting code and less time attaching it to the system.

## Feature design description:

The following diagram gives an overview of how audio requests are processed by the Audio System Gem.

| <img width="1035" alt="AudioRequestFlowDiagram" src="https://user-images.githubusercontent.com/52085794/157327268-fcc2904f-5d6e-4d43-b514-8b011643dafe.png"> |
|:--:|
| *Audio Request Flow* |

It should be noted that this flow diagram describes the behavior in the current implementation, and the proposed implementation changes will not change the flow of audio requests at this granularity.  What *is* going to change are implementation details.

Here are contrived examples of how new audio requests will look after the refactor:

```cpp
if (auto* audioSystem = AZ::Interface<Audio::IAudioSystem>::Get();
    audioSystem != nullptr)
{
    // Simple example: loading a bank...
    Audio::SystemRequest::LoadBank loadBank;
    loadBank.m_bankId = myBankId;
    loadBank.m_asyncLoad = true;
    audioSystem->PushRequest(AZStd::move(loadBank));

    // Complex example: requesting an audio object ID...
    // A local 'audioObject' needs an ID plugged into it.
    // Capture the 'audioObject' in the callback lambda.
    // The callback is part of the audio request data.
    Audio::SystemRequest::ReserveObject reserveObject;
    reserveObject.m_objectName = "NewAudioObject1";
    reserveObject.m_callback =
        [&audioObject](const Audio::SystemRequest::ReserveObject& request)
        {
            // Assign the obtained ID to the 'audioObject'
            audioObject.m_audioObjectId = request.m_objectId;
        };
    audioSystem->PushRequest(AZStd::move(reserveObject));
}
```

## Technical design description:

The first thing to notice in the code example above is the use of `AZ::Interface`.  This is a fundamental change, whereas the current `IAudioSystem` API is defined as an EBus.  This change is proposed so C++ move semantics can be used, which is not supported in EBus interfaces.

The bank loading example shows what a simple request looks like.  Simply declare the request object, set member data, then transfer ownership of the request to the audio system via `PushRequest`.

The next example shows the addition of a callback lambda, but again it is straightforward and easy to understand.

So far, there are three things changed about the public API:
- Change the `IAudioSystem` EBus to an `AZ::Interface`
- Make new classes for audio request types
- Change the `IAudioSystem::PushRequest` function to accept the new request type.

These proposed changes form the core defining characteristics of this proposal.  Additional changes made during implementation will be made in service to these goals.

The new audio request types are objects with their own "payload" data.  This is commonly known as the `Command Pattern`.  The public-facing API should not have to change in order to accommodate new request types that are added in the future.  So `PushRequest` needs to be a generic entry point that works for many different concrete request types.  One way to achieve this is through the use of `AZStd::variant`, which is like a type-safe `union`.

These changes suggested are aimed at platform-independent code.  No platform-specific changes are expected.

## What are the advantages of the feature?

- The use of move semantics simplifies the transfer of ownership of the audio requests as they move from thread to thread.
- "Internal" requests are no longer dynamically allocated inside `PushRequest` (which is also a consequence of move semantics).
- There's no longer a need to have two ("external" and "internal") definitions of audio request types.
- No longer need to use switch statements and `reinterpret_cast` in order get to the underlying request data.

## What are the disadvantages of the feature?

- The main disadvantage is the change of public APIs, which have the potential to break user code.  Breaking change notifications will be presented to the community detailing how to update code.

## How will this be implemented or integrated into the O3DE environment?

The aim of this is to change implementation details in such a way that fundamental features of the Audio System Gem work as they did before.  No changes to data or third-party libraries are needed.  Existing audio middle-ware integrations should only require minimal code changes.

## Are there any alternatives to this feature?

An alternative to this approach is to not use the `Command Pattern` at all and turn each type of audio request into its own function on the `IAudioSystem` interface.  The current interface already supports audio requests as Commands, so this alternative would be quite a departure.  However, this approach would make the public interface much more inflexible to future changes.

## How will users learn this feature?

Most users will not need to make any changes after this change.  Raw audio requests are frequently found in the Audio System Gem itself and in a few other Gems and Systems.  All existing occurrences will be replaced during this refactor.  In the case that a user encounters a breaking change in their personal code, simple update instructions will be provided.

Since this change's intended audience is programmers, the best way to learn about using the new requests is to look at examples in code and reference the new set of audio request objects (and their member data).

For anyone wanting to add a new request type, fortunately this proposal addresses that too, making it much simpler than before.  Hooking up a new request type should only require 1) defining the new request class, and 2) writing the "handler" code.  So it should get you to writing the business logic much quicker than before.

## Are there any open questions?

- *Will external teams need to update their API calls to the Audio System?  If so what is the deprecation pattern?*

If a team is manipulating raw audio requests, then yes they will need to update to the newer code.  Audio classes at higher layers may also have minor updates to account for, but these should have minimal impact.  Deprecation can be provided for certain areas if the community expresses deeper concerns over the changes.

- *Will any resources need updates in order to support this change?*

No content or third-party libraries need updates with these changes.  An update to documentation should be made to fix anything that becomes outdated.

- *Will this affect O3DE's Wwise integration?*

There will be minimal code changes to the Wwise integration Gem, since it does contain occurrences where audio requests are being created and pushed.  The Wwise integration will continue to work as before.

- *Will there be any fundamental differences in functionality with this change?*

The goal of this proposal is to change as little as possible in terms of before and after functionality.  The inner mechanics of the implementation will change, but the expectation is that feature behaviors will be nearly identical.

**Comment by superkitcath** [comment]
This RFC was moved from sig/graphics-audio for visibility

Previous comments: 

[jeremyong-az](https://github.com/jeremyong-az) commented [16 days ago](https://github.com/o3de/sig-graphics-audio/issues/31#issuecomment-1062327479)[](https://github.com/amzn-phist)
Thanks for writing this! I think the one main thing for the community consider is what the deprecation path might look like.

We could, for example, retain the existing ebus event, issue a deprecation flag/assert, then forward the request to the new mechanism.

@[amzn-phist](https://github.com/amzn-phist)
 
Member
Author
amzn-phist commented [16 days ago](https://github.com/o3de/sig-graphics-audio/issues/31#issuecomment-1062386619) • 
Indeed, we can discuss whether a deprecation path is needed for safer migration and what that would look like. To get a sense if there's a need for it in the first place, I'll put forth these questions to the community, and chime in if these apply to you or your team/group:

Have you written any new code that calls PushRequest (PushRequestBlocking etc) on the AudioSystemRequestBus?
Have you written any new code that gets an IAudioProxy pointer from the audio system to play, move, and manipulate sounds?
These are the hot-spots that have the highest potential for friction. If people are doing these kinds of things in their code, we should discuss migration and what options we have there.

Ideally if there are teams that are at risk for breaking changes we can come up a solution that best fits their needs.
