### ISSUE TITLE
Add support for splash screen rendering

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8505]
[Migrated from JIRA ATOM-3093]
Description:

CSystem::Init attempts to render the splash screen via this block of code:

// make sure it's rendered in full screen mode when triple buffering is enabled as well
 for (size_t n = 0; n < 3; n++)

{     m_env.pRenderer->BeginFrame();   m_env.pRenderer->SetCullMode(R_CULL_NONE);   m_env.pRenderer->SetState(GS_BLSRC_SRCALPHA | GS_BLDST_ONEMINUSSRCALPHA | GS_NODEPTHTEST);   m_env.pRenderer->Draw2dImageStretchMode(true);   m_env.pRenderer->Draw2dImage(x ** vx, y ** vy, w ** vx, h ** vy, pTex->GetTextureID(), 0.0f, 1.0f, 1.0f, 0.0f);   m_env.pRenderer->Draw2dImageStretchMode(false);   m_env.pRenderer->EndFrame(); }

This currently crashes during BeginFrame in the AtomShim due to the fact that the BootstrapSystemComponent has not yet initialized the DefaultRenderPipeline. 

Helios is working on a change to initialize the AssetCatalog earlier, which will result in earlier initialization of the DefaultRenderPipeline, since that is initialized in response to the OnCatalogLoaded event. But we also need Draw2dImage to work if we want to render the splash screen.

Add the ability to render a splash screen during Launcher startup and disable the Cry splash screen if Atom is active.

Details:

Acceptance Criteria:

When running the AtomDemo launcher, the splash screen renders.

Additional Information:

**Comment by jiaweig-amzn** [comment]
> Any movement on this? A splash screen would been great. The default should say something like "O3DE" instead of seeing a blank white screen whenever loading GameLauncher or ServerLauncher.

I'll get to work on this after LBC week.

**Comment by mcphedar** [comment]
@jiaweig-amzn Is this work expected to be completed prior to 2/28? Wed like to add a splash screen to the MPS if possible.

**Comment by jiaweig-amzn** [comment]
> @jiaweig-amzn Is this work expected to be completed prior to 2/28? Wed like to add a splash screen to the MPS if possible.
Yes. I think the work can be done by 2/28.

**Comment by AMZN-Gene** [comment]
@jiaweig-amzn is this still on track for 2/28? no pressure, just checking :)

**Comment by jiaweig-amzn** [comment]
> @jiaweig-amzn is this still on track for 2/28? no pressure, just checking :)
RP here:
https://github.com/o3de/o3de/pull/14706
