### ISSUE TITLE
As a dev I want to set the materials on multiple components at once

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8514]
[Migrated from JIRA ATOM-15224]
**Description:** 

Sometimes I want to select 100 entities and set all their material components to use the same material

**Acceptance Criteria:**

Allow users to select the material file on the material component when multiple entities are selected

 

Currently what happens is this...

!image-2021-04-09-22-02-48-503.png!

**Comment by galibzon** [comment]
Assigned to @gadams3
