### ISSUE TITLE
o3de Material Editor - Custom Material View-port Preview .FBX with Multi-Material ID Support.

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8516]
[Migrated from JIRA ATOM-17424]
Description: Custom Material View-port Preview .FBX with Multi-Material ID Support.

Details: You can currently in View-port Settings add a custom model asset to the Material Editor. However, you can only preview one material at a time on a mesh, and if your mesh has more than one material, as say a character. It would be nice to support material IDs so you can work on many materials on the one preview mesh at once.

Acceptance Criteria: If .FBX has more than one material assigned, let each material be viewed and edited in the material editor.

**Additional Information:**

**So... this also could go the opposite way, and prevent a .FBX to have more than one material added as a Preview Primitive.**

**Stress in UV that this is a "Preview Primitive" and that its only for a single material.**

**Comment by gadams3** [comment]
This is now duplicated by the following issue https://github.com/o3de/o3de/issues/10016
