### ISSUE TITLE
Refactor the Sun Trajectory Tool to not pump the message queue

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8523]
[Migrated from JIRA ATOM-3236]
Currently the Sun Trajectory tool uses the CWaitProgress class, which pumps the message queue every time it steps. This is so that it can update the progress bar along the status bar at the bottom of the main window.

This results in the Sun Trajectory tool being able to be closed while it's still generating a light map, which deletes an object at the top of the callstack while something lower, back up the top of the callstack is still using that object.

The code needs to be refactored so that it doesn't do this, and steps using a QTimer event or something else.

**Comment by cgalvan** [comment]
The Sun Trajectory tool was actually removed since it was deprecated, so I will close this task.
