### ISSUE TITLE
Material Component UV Overrides Are Not Saved

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#8525]
**Describe the bug**
If you apply a UV override on a Material Component, save, and reload the level, the changes will not be restored.

**Steps to reproduce**
1. Create a new level.
2. Select the shaderball entity in the default scene.
3. In the material inspector on the Mesh Component, click "Add Material Component".
4. On the "shaderball_01" slot, click "Edit Material Instance UV Map..."
5. Change the "Tiled" to "UV_packed". Notice the texture will change to be mapped differently in the viewport.
6. Save the level and close the editor
7. Run the editor and open the level again

**Expected behavior**
The shaderball should still have the updated appearance, using the "UV_packed" UV set.

![image](https://user-images.githubusercontent.com/55155825/160065043-c77e1e07-377c-4819-8889-afc05d24db16.png)

**Actual behavior**
The shaderball still has its original default appearance.

![image](https://user-images.githubusercontent.com/55155825/160065205-67a65548-0af9-4b01-ab21-7ddde7993633.png)

**Found in Branch**
development

**Comment by gadams3** [comment]
Resolved by this change https://github.com/o3de/o3de/pull/8657
