### ISSUE TITLE
Unassigning the Model Asset in the Material Editor's Viewport Settings does not remove it from its viewport

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#8530]
**Describe the bug**
If a Model Asset is removed from the Material Editor's Viewport Settings it keeps being rendered in its viewport. Restarting the Material Editor restores the mesh assigned as the Model Asset.

**Steps to reproduce**
1. Go to Tools > Material Editor.
2. Go to View > Viewport Settings.
3. In the Viewport Settings unassign the asset used under the Model Settings > Model Asset.

**Expected behavior**
No mesh is drawn in the Material Editor's viewport.

**Actual behavior**
Unassigned asset keeps being drawn in the Material Editor's viewport.

**Video**

https://user-images.githubusercontent.com/86952082/160124863-6b6a1300-5cd4-4cf4-9332-51f061fb7f4b.mp4

**Found in Branch**
Development (1f1f449)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment]
Resolved by this change https://github.com/o3de/o3de/pull/8628

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on both the Development (d4f993e) and Stabilization_2205 (3e47df2) builds.
