### ISSUE TITLE
Failed to load resource mapping config file json schema on Android

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#8535]
**Describe the bug**
When tried to load the Levels/AWS/Core level on Android, resource mapping config file couldn't be loaded successfully and the level failed to run.
**Steps to reproduce**
1. Build Asset Processor for AutomatedTesting project
2. Add autoexec.cfg under the project root folder with the following content: 
```
cl_awsAccessKey=<your_aws_access_key>
cl_awsSecretKey=<your_aws_secrete_key>
loadlevel Levels/AWS/Core/Core.spawnable
```
3. Deploy CDK application for AWS Core and import AWSCore.ExampleBucketOutput, AWSCore.ExampleDynamoTableOutput and AWSCore.ExampleLambdaOutput using the Resource Mapping Tool
4. Run Asset Processor to process all the Android assets
5. Build AutomatedTesting project for Android following O3DE instructions
6. Deploy AutomatedTesting project to Android
7. Run AutomatedTesting project on Android

**Expected behavior**
Resource mapping file is loaded and AWS requests are fulfilled successfully

**Actual behavior**
Resource mapping file json schema and the resource mapping file itself were failed to be loaded. 
```
2022-03-23 12:00:15.819 31274-31773/org.o3de.automatedtesting I/AWSResourceMappingManager: ==================================================================
2022-03-23 12:00:15.819 31274-31773/org.o3de.automatedtesting I/AWSResourceMappingManager: Trace::Error
     D:/github/o3de/Gems/AWSCore/Code/Source/ResourceMapping/AWSResourceMappingManager.cpp(253): 'bool AWSCore::AWSResourceMappingManager::ValidateJsonDocumentAgainstSchema(const rapidjson_ly::Document &)'
2022-03-23 12:00:15.819 31274-31773/org.o3de.automatedtesting I/AWSResourceMappingManager: Failed to load resource mapping config file json schema.
2022-03-23 12:00:15.819 31274-31773/org.o3de.automatedtesting I/AWSResourceMappingManager: ==================================================================
```

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: Samsung
 - OS: Android

**Additional context**
[android_log.txt](https://github.com/o3de/o3de/files/8352213/android_log.txt)

**Comment by lmbr-pip** [comment]
Needs further investigation to see if:
* Mapping file is missing or in wrong location for Android
* Or actual issue with loading json doc on Android (ie rapidjson issue).

**Comment by junbo75** [comment]
Note that the resource_mapping_schema.json file is copied to the build\android_gradle\app\build\intermediates\cmake\profile\obj\arm64-v8a\profile\Gems\AWSCore directory but not included in the final pak.

Changes were made at https://github.com/o3de/o3de/pull/5799 since we wanted to share the schema file between C++ and Python code.

**Comment by junbo75** [comment]
Based on the Android build script, we only copy over *.so files to the lib folder so that the schema file is excluded during the copy task:

https://github.com/o3de/o3de/blob/development/cmake/Tools/Platform/Android/android_support.py#L360
https://github.com/o3de/o3de/blob/development/Code/Tools/Android/ProjectBuilder/build.gradle.in
This seems by design and it doesn't make too much sense to add a new copy task for this schema file in the general Android build script since the file is only required when the AWSCore gem is enabled. We may consider to revert the change in https://github.com/o3de/o3de/pull/5799 and investigate whether we can find a better solution for sharing the schema file between C++ and Python code.
