### ISSUE TITLE
Simple wind interaction

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8552]
[Migrated from JIRA ATOM-15080]
Description: Simple wind interaction

Details:

Artists should have the ability to have wind effect their meshes which can be used for vegetation.  Add support in vertex shader for handling wind.

Acceptance Criteria:

Additional Information:

**Comment by santorac** [comment]
I'm not sure where this ticket originated, was a user requesting it? There's no indication on the original jira ticket. I recommend we close this issue (unless a user is asking for it, maybe).

Also, see this video which shows how to make a custom material type that at least partially addresses this use case: https://www.youtube.com/watch?v=97dBMZXDNA4

**Comment by galibzon** [comment]
Closing this issue. For now, for a basic random wind effect, checkout the video that @santorac shared above.
