### ISSUE TITLE
[Shader Options] - Create a protection / warning mechanism from running over shader bits before submitting a shader / command list

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8558]
[Migrated from JIRA ATOM-13689]
Currently setting the shader options will overrun the entire set.

With single bit setting in place, we now want to implement a mechanism that will identify setting a bit more than once for every command list / shader set.

**Comment by santorac** [comment]
This comes from a pretty old ticket and I'm not aware of any real-world problems related to this request. I suggest we close this ticket unless a specific real-world use case is presented.
