### ISSUE TITLE
Script Canvas: The AWSMetrics nodes are corrupted

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#8581]
**Describe the bug**
The AWSMetrics Attribute nodes have corrupted names for input nodes.

**Steps to reproduce**
1. Go to Script Canvas.
2. Drag any node from the Metrics Attribute group.

**Expected behavior**
The nodes are described correctly and work as expected.

**Actual behavior**
The nodes are corrupted and the input names are illegible.

**Screenshots/Video**

![nodes](https://user-images.githubusercontent.com/86952591/160400628-7676ca46-9803-47d1-9a29-df4b90c5e169.JPG)

**Found in Branch**
Development (9e96dcf)

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU Nvidia RTX 2060 SUPER
Memory 16GB

**Comment by onecent1101** [comment]
This issue is possibly related to https://github.com/o3de/o3de/commit/999fb761630d0f43d4b35525234631c74b5805df
Seems like translation file has to be regenerated

**Comment by onecent1101** [comment]
For example the difference on required translation file:
```diff
             "methods": [
                 {
                     "base": "Getattributes",
+                    "context": "Getter",
                     "details": {
-                        "name": "Get Attributes"
+                        "name": "Getattributes"
                     },
                     "params": [
                         {
@@ -26,15 +27,16 @@
                         {
                             "typeid": "{1C1ABE6D-94D2-5CFD-A502-8813300FEC8D}",
                             "details": {
-                                "name": "Metrics Attribute"
+                                "name": "attributes"
                             }
                         }
                     ]
                 },
                 {
                     "base": "Setattributes",
+                    "context": "Setter",
                     "details": {
-                        "name": "Set Attributes"
+                        "name": "Setattributes"
                     },
                     "params": [
                         {
@@ -46,7 +48,7 @@
                         {
                             "typeid": "{1C1ABE6D-94D2-5CFD-A502-8813300FEC8D}",
                             "details": {
-                                "name": "Metrics Attribute"
+                                "name": "attributes"
                             }
                         }
                     ]
```

**Comment by lmbr-pip** [comment]
Assume this means that ScriptCanvas\Assets\TranslationAssets\Classes\AWSMetrics_MetricsAttribute.name needs to be updated?

**Comment by onecent1101** [comment]
please make sure you are on up-to-date development branch, there is a fix for translation file path.
Verified on latest dev branch, once you click the "Generate Translation", you should get folder opened with translation file located.

**Comment by lmbr-pip** [comment]
I am on latest from this morning (3/28), can sync again.

**Comment by onecent1101** [comment]
Have a fix to show default slot name at least when translation file doesn't provide detailed info.
If you can't generate translation file on your side, i will regenerate as it can work for me.

**Comment by onecent1101** [comment]
Reopen, as the PR just fixes the default slot name, the translation file is still off. Pending on requestor response.
