### ISSUE TITLE
o3de crashes when building a new project from project manager 

### ISSUE THREAD

**Issue by amzn-kritinig** [o3de/o3de#8594]
Describe the bug
o3de crashes when building a new project from project manager. Project was being created from default setting.

1. Go to https://o3debinaries.org/download/linux.html to install nightly build (3/28/22)
2. install the engine and launch peoject manager
3. Provide Project name and location.
4. Select Default template and click to create new project.
5. Once the project is created, click build now
6. Expected behavior
7. project gets built successfully
8. Actual behavior
9. o3de crashes - logs not avilable. 

Screenshots/Video
If applicable, 

https://user-images.githubusercontent.com/82232747/160500012-09ae6504-8ccc-4375-a210-ccbe9b646350.mp4

add screenshots and/or a video to help explain your problem.

Found in Branch
Nightly build (3/28/2022)
Desktop/Device (please complete the following information):

Device: Linux PC
OS: Ubuntu 20.04
Version [e.g. 10, Bug Sur, Oreo]
CPU: Intel® Xeon(R) Platinum 8259CL CPU @ 2.50GHz × 8
GPU [AMD 6800 XT, NVidia RTX 3090]
Memory [e.g. 16GB]
Additional context

**Comment by spham-amzn** [comment]
Unable to repro from nightly build download on 5/23/2022

https://user-images.githubusercontent.com/82231385/169880263-dd74c1a1-acde-47df-8111-877b56df0652.mp4
