### ISSUE TITLE
macOS: Asset Processor fails to process TerrainMacroTextureClipmapGenerationPass.shader

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#8601]
**Describe the bug**

A failing TerrainMacroTextureClipmapGenerationPass.shader can be observed in the Asset Processor when launched with the Automated Testing project.

As a result, the terrain texture for the **Terrain World Renderer** component is missing.

Please note that the issue occurs only on the macOS platform.

For further information please refer to the attached video file and an asset job log.

**Prerequisites**

* The AutomatedTesting project was built and prepared to launch on macOS device.

**Steps to reproduce**

1. Launch the Editor and create a new level.
2. Check the Asset Processor window for failing assets.
3. Select the _Level_ prefab entity in the Entity Outliner and add a **Terrain World** and **Terrain World Renderer** component to it.

**Expected behavior**
No terrain related assets are failing and a terrain texture is visible after adding **Terrain World Renderer** component to the _Level_ prefab entity.

**Actual behavior**
Asset Processor fails processing TerrainMacroTextureClipmapGenerationPass.shader and no terrain texture is visible after adding **Terrain World Renderer** component to the _Level_ prefab entity.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/160617228-f550ea05-faae-45c9-9b0b-8371a2457694.mov

**Found in Branch**
Development (b4b7e5a)

**Desktop/Device:**

- Device: Mac
- OS: macOS
- Version: Monterey 12.0.1
- CPU: M1
- GPU: M1
- Memory: 16GB

**Additional context**
[TerrainMacroTextureClipmapGenerationPass.shader-931285366-1585.log](https://github.com/o3de/o3de/files/8371609/TerrainMacroTextureClipmapGenerationPass.shader-931285366-1585.log)

**Comment by invertednormal** [comment]
Currently Terrain is not supported on mac. We need bindless texture support for it to work on that platform. For now we'll just turn off the shaders so they don't try to compile on mac, and once bindless textures are supported on mac we'll reenable.

**Comment by invertednormal** [comment]
The fix for the shader issue has been merged in. Terrain is currently unsupported on mac though until we have bindless texture support there.

**Comment by LB-MateuszSzweda** [comment]
Verified as fixed on Development (db9d67d). TerrainMacroTextureClipmapGenerationPass.shader is no longer failing in Asset Processor.
