### ISSUE TITLE
EditorServer INetworkInterface::Connect Returns InvalidConnectionId

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#8605]
Multiplayer editor tests are sometimes failing because the editor-server fails to connect to the editor. This was found during AR and seems to occur more often when connecting multiple times rapidly (within a few seconds delay), but sometimes happens on the first try.

MultiplayerEditorConnection.cpp
        _const ConnectionId editorServerToEditorConnectionId =
            m_networkEditorInterface->Connect(IpAddress(LocalHost.data(), editorsv_port, ProtocolType::Tcp));_

The repro happens often on Linux, but there are some instances of this occurring on Windows.

**Steps to reproduce**
1. Run Multiplayer AR tests on Linux
    -  .\python\python.sh -m pytest --build-directory .\build\linux\bin\profile\  $pyfile .\AutomatedTesting\Gem\PythonTests\Multiplayer\TestSuite_Main.py::TestAutomation
    - Note: The above commandline might not work if tests have been moved from TestSuite_Main to TestSuite_Sandox
3. Notice some tests fail with error **[FAILED ] Failure: Failed to find expected line: MultiplayerEditorConnection: Editor-server activation has found and connected to the editor.**

**Expected behavior**
Editor-server should be able to connect to the editor

**Actual behavior**
Editor server fails to connect to editor

**Desktop/Device (please complete the following information):**
 - OS: Linux (often), Windows (rarely)

**Comment by AMZN-alexpete** [comment]
Seeing this failure in multiple AR runs on windows too: 
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-8424/5/pipeline/
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-8424/4/pipeline/625
Also Linux: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-8424/1/pipeline

**Comment by AMZN-Gene** [comment]
https://github.com/o3de/o3de/pull/8606
Moving Multiplayer automated-review tests (except 1) into Sandbox, until this issue is fixed. See PR for more details.

**Comment by AMZN-Gene** [comment]
Failed to bind new incoming connection to socket manager, failed socket file descriptor: -1
