### ISSUE TITLE
Material Editor: Log tab X button has different icon styling 

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#8607]
**Describe the bug**
In the Log tab the 'X' button icon styling is inconsistent with all other close button icons.

**Steps to reproduce**
**Steps to reproduce the behavior:**
1. Go to Tools > Material Editor.
2. Select Tools > Logging.
3. Hover over the X button of the Log tab.

**Expected behavior**
'X' button has the same styling as all other buttons.

**Actual behavior**
'X' button icon has inconsistent styling as to compared with all other close buttons.

**Screenshot**

![inconsistentXButton](https://user-images.githubusercontent.com/100559077/160823012-8cc08a93-0109-4114-9028-cf2b2fdec798.png)

**Found in Branch**
Development (61f1dc1)

Device: PC
OS: Windows
Version: 10
CPU: Intel Core i7-11700F
GPU: NVIDIA GeForce RTX 3070
Memory: 32GB

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed in Development (3f3f133).
