### ISSUE TITLE
Linux: Projects cannot be properly built via Project Manager on the Pre-built SDK engine configuration

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#8608]
**Describe the bug**
When attempting to build a project (no matter the Gems used) created in the Project Manager on the Pre-built SDK engine configuration it seemingly fails. The build is interrupted at the start and a log is created (the log can be found under the **Video and log** section), suggesting that it failed. It should be noted however, that the Editor can be opened after the build failure by clicking on the Open Editor button (it might require a restart if it does not launch after the Asset Processor processes all the assets).  While the Editor's basic functions such as level creation, and viewport navigation work on that project, we are not discounting a possibility that some tool or other functionality may be affected by this build failure.

It should be noted that this does not occur on Windows OS.

**Steps to reproduce**
1. Configure, and build a Pre-built SDK configuration engine.
2. Launch the Project Manager.
3. Create a Project.
4. Build the Project created in step 3 via the Project Manager.

**Expected behavior**
The Project builds without issues.

**Actual behavior**
The Project seemingly fails the build.

**Video and log**

https://user-images.githubusercontent.com/86952082/160815274-7fa9f8c6-56a1-4da2-bf09-3ebf35b8e138.mp4

[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/8379801/CMakeProjectBuildError.log)

**Found in Branch**
Development (61f1dc1)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by lumberyard-employee-dm** [comment]
This is looks like an issue with setting the 3rdParty::OpenSSL target on linux

```
CMake Error at /home/gpc-610/o3de-install/cmake/LYWrappers.cmake:174 (add_executable):
  Target "NewProject2.GameLauncher" links to target "3rdParty::OpenSSL" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /home/gpc-610/o3de-install/LauncherGenerator/launcher_generator.cmake:90 (ly_add_target)
  /home/gpc-610/o3de-install/cmake/FindLauncherGenerator.cmake:11 (include)
  /home/gpc-610/o3de-install/cmake/Findo3de.cmake:24 (find_package)
  /home/gpc-610/o3de-install/CMakeLists.txt:78 (ly_find_o3de_packages)
  ```

**Comment by LB-JakubSkoczylas** [comment]
This issue also occurs on Stabilization_2205 (3e47df2)

**Comment by lmbr-pip** [comment]
Believe this is fixed by https://github.com/o3de/o3de/issues/8732

**Comment by lumberyard-employee-dm** [comment]
No that change has not.
@junbo75 is cherry-picking it in PR https://github.com/o3de/o3de/pull/8949#pullrequestreview-943557411

**Comment by LB-RostyslavGavryliuk** [comment]
Issue no longer occurs on latest Stabilization downloaded from https://o3debinaries.org/stabilization-2205/Latest/Linux/O3DE_latest.deb
