### ISSUE TITLE
Material Editor: Log tab is misaligned compared to the Logging tab

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#8609]
**Describe the bug**
Log tab positions is misaligned with the Logging tab by a few pixels.

**Steps to reproduce**
**Steps to reproduce the behavior:**

1. Go to Tools > Material Editor.
2. Select Tools > Logging.

**Expected behavior**
All tabs are properly aligned to the edges.

**Actual behavior**
Log tab is misaligned compared to the Logging tab.

Screenshot

![LoggingTabMisalligned](https://user-images.githubusercontent.com/100559077/160839947-c9217ae5-4caa-4e3b-85fb-7ce150a50a26.png)

Found in Branch
Development (61f1dc1)

Device: PC
OS: Windows
Version: 10
CPU: Intel Core i7-11700F
GPU: NVIDIA GeForce RTX 3070
Memory: 32GB

**Comment by gadams3** [comment]
The style has been changed so this is no longer visible

**Comment by LB-HubertUberman** [comment]
Verified as fixed in Stabilization (https://github.com/o3de/o3de/commit/021d32ab66ee4daebfe55eb7804b3b6bba1d9ed9) and development (https://github.com/o3de/o3de/commit/511a88c6ab7a3ed54898f568816e76708a6c9455) branches.
