### ISSUE TITLE
NetworkRigidBodyComponent Doesn't Force NetTransform Dependency

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#8616]
**Describe the bug**
The networkrigidbody component requires net transform component to properly function, but the component isn't marked as dependent

**Steps to reproduce**
1. Open a project with Multiplayer Gem enabled and installed (Ex: AutomatedTesting)
2. Add NetworkRigidBodyComponent to an empty entity

**Expected behavior**
The component outline should show the "Add Required Component" menu

**Actual behavior**
No warning about needing a net-transform

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Additional context**
Easy fix, just add the dependency to the auto-component XML

**Comment by AMZN-puvvadar** [comment]
To add a little more detail here, NetworkRigidBodyComponent does define NetworkTransformComponent as a ComponentRelation constraint. This means that NetworkTransformComponent is a dependency in NetworkRigidBodyComponentBase. NetworkRigidBodyComponent implements its own GetRequiredServices however.

There are two viable fixes here:
1. Manually specify the dependency in NetworkRigidBodyComponent's GetRequiredServices
2. Call NetworkRigidBodyComponentBase::GetRequiredServices from NetworkRigidBodyComponent::GetRequiredServices

**Comment by AMZN-Gene** [comment]
Ohh, we should update the Jinja derived class comment to include networkrigidbodycomponent::GetRequiredService.
I’d like it to call the base class, in case the relation is ever changed after the derived class is created.
