### ISSUE TITLE
Project Manager: Blue highlight remains on the buttons

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#8633]
**Describe the bug**
When the User selects any of the buttons and deselects it, a blue highlight appears around it. This highlight remains after going back and forth between menus.
This concerns e.g. hamburger menus, Back button, Filter by checkboxes, Configure Gems button.

**Steps to reproduce**
Steps to reproduce the behavior
1. Go to Project Manager.
2. Select hamburger menu and Edit Project Settings.
3. Go back to main menu.
4. Observe the result.
5. Select hamburger menu and Configure Gems.
6. Select and deselect any of the Filter by button.
7. Press Back button.
8. Go back to Configure Gems.

**Expected behavior**
Blue highlight disappears after clicking the button.

**Actual behavior**
Blue higlight remains on the buttons.

**Video**

https://user-images.githubusercontent.com/100559077/161026730-ec6da7d7-a93c-44ff-9310-3d07ff029259.mp4

**Found in Branch**
Development (9b24dc9)

Device: PC
OS: Windows
Version: 10
CPU: Intel Core i7-11700F
GPU: NVIDIA GeForce RTX 3070
Memory: 32GB

**Comment by AMZN-alexpete** [comment]
The blue highlight is OK to remain as it usually denotes the active focus element and is useful for accessibility. e.g. if you could not use a mouse as input.
