### ISSUE TITLE
Icons and Launchscreens missing from iOS Platform Settings for newly created projects

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#8640]
**Describe the bug**
Platform Settings lack **Icons** and **Launchscreens** under iOS tab for newly created projects, which is inconsistent with the same settings for the Android platform. Note that the issue only occurs for newly created projects and it is not active for AutomatedTesting project, which seems to be only missing the following:

 **Icons:** 
- App Store (1024px)
- iPhone Notification (40px)
- iPhone Notification (60px)
- iPad Notification (20px)
- iPad Notification (40px)

**Launchscreens:**
- iPhone (750x1334px)
- iPhone (1125x2436px)
- iPhone (2436x1125px)
- iPhone (1242x2208px)
- iPhone (2208x1242px)

Please refer to the attached screenshots for more information.

**Steps to reproduce**
1. Navigate to _File_ -> _Edit Platform Settings_ (or use Ctrl+Shift+P).
2. Switch the active tab to **iOS**.
3. Expand and examine the **Icons** and **Launchscreens**.

**Expected behavior**
Settings are consistent between the platforms.

**Actual behavior**
iOS is missing Icons and Launchscreens for newly created projects.

**Screenshots**
Newly created project iOS:
![EditPlatformSettings_NewProject_iOS_Icons](https://user-images.githubusercontent.com/86953659/161050671-9fbe1061-0c61-4af4-9d80-9d6c91e0167a.PNG)

Newly created project Android:
![EditPlatformSettings_NewProject_Android_Icons](https://user-images.githubusercontent.com/86953659/161050696-feca4c51-65d1-4a36-aaba-2c4cfc1d36df.PNG)

AutomatedTesting iOS Icons:
![EditPlatformSettings_AutomatedTesting_iOS_Icons](https://user-images.githubusercontent.com/86953659/161050706-89512dfe-eb2c-45dd-9b8e-cc5fc1f76100.PNG)

AutomatedTesting iOS Launchscreens:
![EditPlatformSettings_AutomatedTesting_iOS_Launchscreens](https://user-images.githubusercontent.com/86953659/161050734-3aa73781-38c2-426c-8f15-431a4d377df3.PNG)

**Found in Branch**
Development (9b24dc9)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i5-9600K
 - GPU: NVIDIA GeForce RTX 2070
 - Memory: 16GB

**Comment by AMZN-alexpete** [comment]
@AMZN-nggieber might have an idea what's going on here.

**Comment by AMZN-nggieber** [comment]
The templates have moved these images to another location without. The code is only checking the old location. Automated testing still has them in the old location.

https://github.com/o3de/o3de/blob/8907681d7ae05f76fcf4ae1ad0b521d2d769bdda/Code/Editor/Plugins/ProjectSettingsTool/Utils.cpp#L191

https://github.com/o3de/o3de/tree/development/AutomatedTesting/Gem/Resources/IOSLauncher/Images.xcassets

https://github.com/o3de/o3de/tree/development/Templates/DefaultProject/Template/Resources/Platform/iOS/Images.xcassets

Notice how the Resources directory used to be under the Gem directory, now its under the root project directory.

**Comment by jckand-amzn** [comment]
This is now affecting both Android and iOS for newly created projects after the logo was updated. Tested on development@0dbd6f1c092475a655f38df4568b9b5f99b90daf.

**Comment by LB-MateuszSzweda** [comment]
Unfortunately on Development (a88f38d) in built new projects as well as AutomatedTesting project the:

**Icons:**
App Store (1024px)
iPhone Notification (40px)
iPhone Notification (60px)
iPad Notification (20px)
iPad Notification (40px)

**Launchscreens:**
iPhone (750x1334px)
iPhone (1125x2436px)
iPhone (2436x1125px)
iPhone (1242x2208px)
iPhone (2208x1242px)

are still missing which can be observed on the video below.

https://user-images.githubusercontent.com/86953456/183914089-e3ff75a1-90b1-47d7-aa15-84c06aa5892d.mp4

Therefore the issue is reopened.

**Comment by LB-MateuszSzweda** [comment]
In that case indeed the issue can be treated as fixed as the only icons and launchscreens missing are those from AutomatedTesting. Sorry for reopening.

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed using Stabilization/2210 (https://github.com/o3de/o3de/commit/99608ffd4f7d3d347cb015b243046a3438da23c7) build according to the above comments.
