### ISSUE TITLE
Material Editor: Alt+MMB control to move camera on its XY plane is redundant

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#8644]
**Describe the bug**
"Move camera on its xy plane" control in the Material Editor has two options available: MMB and Alt+MMB. Seeing as the base input for this control is the Middle Mouse Button, and there is no other control that uses another <button>+MMB combination it seems redundant, as e.g. "orbit camera around target" uses different buttons as a base control and alternative (RMB or Alt+LMB). 

**Steps to reproduce**
1. Go to Tools > Material Editor.
2. Hold Middle Mouse Button in the viewport and move the mouse around.
3. Hold Alt+Middle Mouse Button in the viewport and move the mouse around.

**Expected behavior**
Steps 2 and 3 show different camera movement.

**Actual behavior**
In both the step 2 and step 3 the movement is the same.

**Video**

https://user-images.githubusercontent.com/86952082/161065744-c4b2ecf8-b992-4765-92f5-6b7e2878e25e.mp4

**Found in Branch**
Development (9b24dc9)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by HogJonny-AMZN** [comment]
Firstly, there are two layers of controls for the Material Editor.
1. no Alt key
2. Alt key ... 'Industry Standard': Like Maya, or like Blender when using the 'Industry compatible keymap: https://docs.blender.org/manual/en/latest/interface/keymap/industry_compatible.html

We prefer not to change #2 as it has had a lot of User study, and Alt+MMB as a camera xy pan is the common action.

Also it is OK to have redundant actions in the two modes, what is most important is that Users can intuit the controls in either mode, that they are familiar and consistent.

The MMB and Alt-MMB both also perform a pan in the Main Editor Viewport.

In many common 2D tools, for instance Adobe Illustrator, the MMB is tied to panning around the canvas.  And this is true for O3DE canvas tools, like Script Canvas, where MMB pans around the canvas.

So what is intuitive to more people, is that they expect MMB to perform some type of pan. 

This is the historical basis; there have been a lot of User study and many iterations on improving viewport controls.

**Comment by LB-ArturZieba** [comment]
Thanks for the explanation, did not consider that angle when creating this issue.
