### ISSUE TITLE
[ROS2 Gem] Robot control component

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de#8645]
**Is your feature request related to a problem? Please describe.**
Users want to control their robots in simulation. Simulation developers could use flexible component(s) and abstractions to efficiently develop their desired control behaviors.

**Describe the solution you'd like**
A component which:
- [x] Handles subscription to a topic, flexible as to message type (Twist, AckermannDrive, etc.)
- [x] Allows customization of topic name, qos, method and implementation of control
- [x] Provides an example implementation which works out of the box. This could be Twist message subscription that looks for a RigidBody component in its entity and applies linear and angular velocity to it.
- [ ] Allows to change how robot control is handled in several aspects: type of control message, which component it applies to, how it applies (allowing for very custom behaviors). A way to "register" such behaviors as component extensions would be desirable.

**Describe alternatives you've considered**
No alternatives

**Additional context**
Work in progress

**Comment by hultonha** [comment]
Hi @adamdbrw, this popped up in our triage session, we're removing the `needs-triage` label and I've assigned it to you for now. I've also added the `kind/feature` label as well, please feel free to add any other relevant labels. Thanks!

**Comment by adamdbrw** [comment]
First iteration Robot Control Component has been merged. The follow up work regarding the remaining subtask is in a new issue: https://github.com/RobotecAI/o3de-ros2-gem/issues/75
