### ISSUE TITLE
Game Launcher: Debug Console background does not consistently draw

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#8647]
**Describe the bug**
Debug Console background does not consistently draw. The background remains invisible the majority of the time, but sometimes flashes when clicking On/Off the Options button.

**Steps to reproduce**
1. Launch the GameLauncher.exe for your current project.
2. Open the Console with ~
3. Click the Options button, and then click off of the Options button onto the Console window area.

**Expected behavior**
Debug Console background consistently draws.

**Actual behavior**
Debug Console background does not consistently draw. The background remains invisible the majority of the time, but sometimes flashes when clicking On/Off the Options button.

**Screenshots/Video**
![launcher_console_bg](https://user-images.githubusercontent.com/82226555/161101529-5ab4cf58-91f5-4051-984f-a6bb108a8186.jpg)

**Found in Branch**
development@9b24dc9b68ed8d2b844eb1a421c1217c07f7fcba

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by AMZN-alexpete** [comment]
This issue still exists in stabilization/2205 commit https://github.com/o3de/o3de/commit/3600aa095fcbf46ad1da9f323f17cab95abf524c

**Comment by galibzon** [comment]
Assigned to @VickyAtAZ , as may be related to https://github.com/o3de/o3de/issues/8649

**Comment by VickyAtAZ** [comment]
Fix: https://github.com/o3de/o3de/pull/9077
