### ISSUE TITLE
If AWS credentials cannot be retrieved from the AWS config, the Resource Mapping Tool does not appear

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/o3de#8651]
**Describe the bug**
If you have a problem with your AWS Credentials retrieval, then the Resource Mapping Tool does not open but also does not indicate what went wrong.

**Steps to reproduce**
1. With the AWS Core Gem enabled for your proejct
2. Add a problematic aws credential_process to your aws config file and use that profile
3. Try to open the Resource Mapping Tool from the editor
```
[profile some-profile]
region = us-west-2
credential_process = some-bogus-program-that-does-not-exist
```
Credential-process is often used by companies to fetch credentials using a custom process (ie, a program) but this may also fail for any failure to get credentials.

You may also have to update your project's default aws profile to use, see https://www.o3de.org/docs/user-guide/gems/reference/aws/aws-core/getting-started/#project-settings on how to make it use this "some-profile" profile.

**Expected behavior**
The resource mapping tool or the editor pops up a dialog indicating that something went wrong, and lets you see the logs or shows other information to help you diagnose.

**Actual behavior**
Nothing occurs.  No dialog pops up, no error is output, and no resource mapping tool appears

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Windows PC

**Additional context**
THis is because the resource mapping tool encounters an unhandled python exception:
botocore.exceptions.CredentialRetrievalError
during its call
```
File "...\Gems\AWSCore\Code\Tools\ResourceMappingTool\utils\aws_utils.py", line 72, in get_default_account_id
    sts_client: BaseClient = _initialize_boto3_aws_client(AWSConstants.STS_SERVICE_NAME)
  File "...\Gems\AWSCore\Code\Tools\ResourceMappingTool\utils\aws_utils.py", line 56, in _initialize_boto3_aws_client
    boto3_client: BaseClient = default_session.client(service)
```

and is not listening for it.

**Comment by junbo75** [comment]
Fix has been checked into the stabilization. I'll close this issue.
