### ISSUE TITLE
Bug Report In the Asset Browser window, create new Lua file and rename Lua file  both cannot be updated in real time.

### ISSUE THREAD

**Issue by luoweiqiao** [o3de/o3de#8659]
**Describe the bug**
In the Asset Browser window, create new Lua file and rename Lua file  both cannot be updated in real time..

**Steps to reproduce**
1. open o3de.exe.'
2. open 'Asset Browser' window
3. Select any directory
4. Right-click the mouse
5. Select 'Create New Lua Script'

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.
![image](https://user-images.githubusercontent.com/53386482/161185600-8a583c1f-696b-4f97-bf6e-45b3abfd7403.png)
![image](https://user-images.githubusercontent.com/53386482/161185665-b8b0b988-b7c0-4851-bc42-886d93f431e2.png)

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by srikappa-amzn** [comment]
@luoweiqiao , can you try to clarify what it is that you see as a bug here? Please update these sections with more accurate information:

Expected behavior
A clear and concise description of what you expected to happen.

Actual behavior
A clear and concise description of what actually happened.

**Comment by srikappa-amzn** [comment]
Closing for a lack of response. Please feel free to reopen after answering the previous question.
