### ISSUE TITLE
 When the Material name in the FBX model contains special symbols (such as ':' ),  Grenerate/Manage Source Material will be failed

### ISSUE THREAD

**Issue by liukaikai-g** [o3de/o3de#8661]
**Describe the bug**
When the Material name in the FBX model contains special symbols (such as ':' ),  Grenerate/Manage Source Material will be failed.

**Steps to reproduce**
1. Create an Entity
2. Add Mesh Component and Material Component to entity
3. Assign a FBX model which has the special symbols in material name to Mesh Component
4. Use the Grenerate/Manage Source Material to generate material files.
5. See error

**Expected behavior**
Material files are generated.

**Actual behavior**
Material files are not being generated..

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/55627654/161228625-db49ddd7-8ba6-4964-90e3-37fdc22db959.png)
![image](https://user-images.githubusercontent.com/55627654/161228958-760e8fb7-5181-464b-928d-3d0b95f17b20.png)

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel(R)_Xeon(R)_W-2245
 - GPU NVIDIA Quadro RTX 4000
 - Memory 32GB

**Additional context**

**Comment by santorac** [comment]
This issue was already fixed, see https://github.com/o3de/o3de/pull/8083
