### ISSUE TITLE
Material Editor: Adding Lighting or Model Settings results in a duplicated name in the selection list

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#8666]
**Describe the bug**
When the User adds a new Lighting Settings or Model Settings it duplicates itself in the selection list.

**Steps to reproduce**
Steps to reproduce the behavior
1. Go to Tools > Material Editor.
2. Go to Tools > Viewport Settings.
3. Add a new Lighting or Model Settings.
4. Expand the selection list.

**Expected behavior**
One name displays for each created Lighting or Model Settings.

**Actual behavior**
Name of the newly created setting is duplicated in the selection list.

**Video**

https://user-images.githubusercontent.com/100559077/161241346-40f147b0-cfbf-4603-8134-667cb11a6988.mp4

**Found in Branch**
Development (8077789)

Device: PC
OS: Windows
Version: 10
CPU: Intel Core i7-11700F
GPU: NVIDIA GeForce RTX 3070
Memory: 32GB

**Comment by gadams3** [comment]
This fix has been submitted to stabilization. It will not prevent duplicate names if the same file name is used in different folders. But they will point to the correct assets.

**Comment by LB-BartoszCwiek** [comment]
Verified as fixed on Development (b7fa50e). Closing the issue.
