### ISSUE TITLE
[Script Canvas][Spawnables]Undo operations when Prefab Spawn and Despawn nodes are present break their functionality

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#8686]
**Describe the bug**
If the user is editing a script canvas graph that includes the Prefab Spawn and Despawn nodes, and they undo any operations while editing the graph, it creates extra Spawn Ticket output nodes that break the Spawn and Despawn nodes.

**Steps to reproduce**
1. Launch Script Canvas
2. Add the Prefab > Spawning > Spawn or Despawn node to the graph
3. Click to drag the node on the graph
4. Press ctrl+z to undo the movement
5. Repeat steps 3 and 4 a few times

**Expected behavior**
The Spawn and Despawn nodes remain unchanged when graph operations are undone

**Actual behavior**
The Spawn and Despawn nodes begin accumulating extraneous outputs that break the node

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82236902/161349765-9b35666c-4b30-47b3-8cf2-93580ef6f797.png)

**Found in Branch**
o3de/development

**Comment by srikappa-amzn** [comment]
@AMZN-mnaumov , fyi
