### ISSUE TITLE
Material Editor should not show ReflectionProbeVisualization material type

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de#8700]
**Describe the bug**

This issue is created in response to this issue: 
https://github.com/o3de/o3de.org/issues/1512

The Material Editor should not show **ReflectionProbeVisualization** material type, as it's not a material type for users to edit or use directly. 

**Steps to reproduce**
1. Open Material Editor. 
2. Click on **Create a new material** from the file menu. 
3. In the pop-up menu, navigate to the **Select Material Type** drop-down list. 

**Expected behavior**
ReflectionProbeVisualization should not appear. 

**Actual behavior**
ReflectionProbeVisualization appears.

**Assets required**
Atom Gem

**Found in Branch**
`development` as of April 4, 2022. Latest commit was `8d7eb89e82991eca8edaa71abf821be6d629149e`.

**Additional context**
This is another related issue, not sure if it's still applicable or has been addressed. https://github.com/o3de/o3de/issues/4235

**Comment by santorac** [comment]
Yes, we've talked about needing some kind of filter list for the Material Editor, to hide special purpose material types that users won't care about. This is probably something that @gadams3 will take care of, related to work that @invertednormal has been doing.
