### ISSUE TITLE
Verify dedicated server release build for O3DE

### ISSUE THREAD

**Issue by junbo75** [o3de/o3de#8706]
**Is your feature request related to a problem? Please describe.**
Developers may want to upload their release build package of the Windows/Linux dedicated server for running the server on GameLift. We need to verify that the server target can be built in release and packaged with necessary assets. Note that we tested the release server build in Dec 2021 but failed to launch the server.

**Describe the solution you'd like**
- Windows/Linux dedicated server can be built in release
- Follow up with the corresponding sig for any build or runtime failures

**Additional context**
Attached are the server and visual studio logs we got during our previous testing.
[Server.log](https://github.com/o3de/o3de/files/8413682/Server.log)
[visual_studio_log.txt](https://github.com/o3de/o3de/files/8413683/visual_studio_log.txt)

**Comment by lmbr-pip** [comment]
Related to https://github.com/o3de/o3de/issues/8703

**Comment by AMZN-puvvadar** [comment]
Related to #8685

**Comment by AMZN-puvvadar** [comment]
Closing as duplicates of the above issue. This issue encapsulates concerns around release build packaging and packaging for GameLift which the above referenced issues separately focus on.
