### ISSUE TITLE
Create AtomSampleViewer Regression Test for Eye Material Type

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#8721]
**Is your feature request related to a problem? Please describe.**
A new Eye.materialtype was recently added (https://github.com/o3de/o3de/pull/8129). We should have a screenshot test for this in AtomSampleViewer to make sure it doesn't get broken in the future.

**Describe the solution you'd like**
At a minimum, we need to add a new screenshot step to AtomSampleViewer\Scripts\MaterialScreenshotTests.bv.lua, using an Eye model. This should be very quick and easy, provided that we already have an Eye model and default eye textures available. See also https://github.com/o3de/o3de/issues/8719

**Describe alternatives you've considered**
Another option that would be nice to have is a new ASV sample dedicated to the eye material type, where the user can adjust the various properties, maybe show/hide a head for the eye(s), things like that. Then we can make a screenshot test of this sample instead of adding one to MaterialScreenshotTests.bv.lua.
(We might want to split this into two separate tickets. I'm happy with whatever direction you want to take @thefranke @santipaprika)

**Additional context**

**Comment by superkitcath** [comment]
@santipaprika; I am still trying to figure out why I can't assign this one to you. WIP :-)

**Comment by santipaprika** [comment]
I can work on this :)
