### ISSUE TITLE
Moving an entity with a White Box component attached causes the Editor to crash

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#8741]
[Migrated from JIRA LYN-11862]

When an entity with the White Box component is moved, the editor will lock up for a brief moment and then crash. This _could_ be related to SPEC-6158, but there's no obvious causal link.

**Found in Build**: dd1e77124c8a4c43d4b9932c278ec6e4d82f47c0 (Mon Apr 5 20:17:26 2021 +0000)

**Reproducibility**: 8/8

**Prerequisites**: A new project with a White Box gem.

**Steps to Reproduce**:

 - Launch the editor and enter a level
 - Create a new entity
 - Assign it a White Box component
 - Move the entity

**Expected Result**:

The entity moves to a new transform location

**Actual Result**:

The editor crashes

**Comment by LB-MateuszSzweda** [comment]
The issue was verified as not occuring on both Stabilization_2205 (3e47df2) and Development (63aadae) branches on both PC and Linux versions of the Editor.

**Comment by hultonha** [comment]
Awesome thanks @LB-MateuszSzweda! 😄
