### ISSUE TITLE
White Box component's default material does not render

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#8742]
[Migrated from JIRA LYN-11863]

When creating or editing a White Box component an error appears in the console and no material on the White Box itself renders. It can be re-shaped without issue, but only shows up via debug.

**Found in Build**: dd1e77124c8a4c43d4b9932c278ec6e4d82f47c0 (Mon Apr 5 20:17:26 2021 +0000)

**Reproducibility**: 8/8

**Prerequisites**: A new project with the White Box gem enabled.

**Steps to Reproduce**:
 - Create a new entity.
 - Add a White Box component
 - Observe that entity and component via the viewport

**Expected Result**:

The White Box entity renders with basic materials

**Actual Result**:

The White Box entity does not render at all, outside of debug highlighting

**Comment by hultonha** [comment]
Hi @LB-RobertBaczkowski, this looks very similar to https://github.com/o3de/o3de/issues/8741, if you'd please be able to let me know who the best contact is for the White Box Tool and get them to verify I'd really appreciate it.

(Also tagging @Broganab for visibility as well)

**Comment by LB-MateuszSzweda** [comment]
The issue was verified as not occuring on both Stabilization_2205 (3e47df2) and Development (63aadae) branches on both PC and Linux versions of the Editor.

**Comment by hultonha** [comment]
Awesome thank you @LB-MateuszSzweda! Much appreciated :+1:
