### ISSUE TITLE
AssetBuilders are crashing in Linux asset_profile_nounity

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#8744]
**Describe the bug**
Several PRs are blocked by Linux asset_profile_nounity.
Examples:
https://jenkins.build.o3de.org/job/O3DE/job/PR-8495/
https://jenkins.build.o3de.org/job/O3DE/job/PR-8544/

**Failed Jenkins Job Information:**
It seems the AssetBuilders are running out of memory and crashing.
```
BuilderManager: Lost connection to builder F4EB40FB911D49E7BF2AE8066246015B
ProcessWatcher: Child process id 40667 terminated prematurely (signal 9)
BuilderManager: Lost connection to builder E26CF23B790C4BA6A42BC0AEEDC4FC12
ProcessWatcher: Child process id 44412 terminated prematurely (signal 9)
BuilderManager: Lost connection to builder 431F613550AF4E89B51363FC1280596A
ProcessWatcher: Child process id 45054 terminated prematurely (signal 9)
BuilderManager: Lost connection to builder 54F59B7AF1A942D4BA5DEA5BA8DD2E41
ProcessWatcher: Child process id 46338 terminated prematurely (signal 9)
BuilderManager: Lost connection to builder 214B3F0265A94B0A8DA3C3D399F14E59
ProcessWatcher: Child process id 42379 terminated prematurely (signal 9)
BuilderManager: Lost connection to builder 7D1E7273A379479299FE337CBC046FC6
ProcessWatcher: Child process id 45910 terminated prematurely (signal 9)
BuilderManager: Lost connection to builder E26121FB972A445BB8760B80CBD6C8CB
ProcessWatcher: Child process id 46124 terminated prematurely (signal 9)
```

**Attachments**
When ran locally on  my WSL2 Ubuntu virtual machine. It seems the unity build is more stable as it didn't failed.
[unitybuild_my_ap_batch.log](https://github.com/o3de/o3de/files/8427268/unitybuild_my_ap_batch.log)  
But nounity build failed as in Jenkins:
[nounitybuild_my_ap_batch.log](https://github.com/o3de/o3de/files/8427275/nounitybuild_my_ap_batch.log)  

**Additional context**
So far there are two avenues:
1- Disable the  Linux asset_profile_nounity until it is made stable  again.
REMARK:
Setting `"maxJobs"` to 4 or so in `o3de/Registry/AssetProcessorPlatformConfig.setreg` **could** help, but I tried locally with `maxJobs` set to 4 and it still crashed.

**Comment by jackalbe** [comment]
interestingly, the crash happens during "python/python.sh -u scripts/build/ci_build.py --platform Linux --type asset_profile_nounity"

**Comment by galibzon** [comment]
> interestingly, the crash happens during "python/python.sh -u scripts/build/ci_build.py --platform Linux --type asset_profile_nounity"

Will in my local tests I just configured like this:
`cmake -B build -S . -G"Ninja Multi-Config" -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12 -DLY_3RDPARTY_PATH=/mnt/d/LY3RDPARTY/lyengine/3rdParty -DLY_PROJECTS="AutomatedTesting;AtomSampleViewer" -DLY_UNITY_BUILD=OFF`  
Built like this:   
` cmake --build build --config profile --target AssetProcessorBatch -j 64`  
And ran AssetProcessorBatch as this:  
`./build/bin/profile/AssetProcessorBatch /zeroAnalysisMode --gamefolder=AutomatedTesting --platforms=server`
