### ISSUE TITLE
Script Assets fail to reload on prefabs

### ISSUE THREAD

**Issue by AMZN-mnaumov** [o3de/o3de#8760]
There's currently a bug within asset/prefab system which releases m_script asset in Code/Framework/AzFramework/AzFramework/Script/ScriptComponent.cpp meanwhile keeping it cached on prefab.

**Steps to reproduce**
1. Download [Assets.zip](https://github.com/o3de/o3de/files/8430815/Assets.zip) and extract in your project folder
2. In ScriptComponent.cpp undo temp fix (around line 567 delete the following code):
```
            AZ::Data::AssetLoadParameters loadParams;
            m_script = AZ::Data::AssetManager::Instance().GetAsset<AZ::ScriptAsset>(
                    m_script.GetId(),
                    m_script.GetAutoLoadBehavior(),
                    loadParams);
```
3. Build and run Editor
4. Open LuaSpawningBug level
5. Run Game Mode and observe "(Script) - This is a test 1." printed in console window
6. Exit Game Mode.
7. Make a change to PrintSomething.lua script (e.g. `Debug.Log("This is a test 2.")`)
8. Run game mode again

**Expected behavior**
Lua script works with updated change and prints updated message

**Actual behavior**
The Lua script on spawned entity will no longer work at all and nothing will be printed in console

**Assets required**
[Assets.zip](https://github.com/o3de/o3de/files/8430815/Assets.zip)

**Screenshots/Video**
-

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**
This is happening because m_script gets released by asset manager (in OnAssetReloaded) as it doesn't account for the asset reference of the script attached to the prefab. However when we run Game Mode again, and spawn the same prefab, its script asset is also cloned and is now in 'Ready' state (but missing from AssetManager!). So it never gets properly loaded and never gets activated.

**Comment by carlitosan** [comment]
Assigning to me, I think this may have nothing to do with prefabs
