### ISSUE TITLE
PhysSystem warning spams console when no simulation is running

### ISSUE THREAD

**Issue by carlitosan** [o3de/o3de#8762]
[Warning] (PhysXSystem) - [1] of [1000] frames had a deltatime over the Max physics timestep[0.100000]. Physx timestep was clamped on those frames, losing [0.830421] seconds.  

This appears in the console when the editor is opened and no level is running at all. This timings should be configured to run as profiling is truly necessary.

**Comment by hultonha** [comment]
We have discussed this on the Physics team and agree this should be on _opt-in_ option. We can move this behind a setting. One option is to use an `AZ_CVAR` but it might be better to move the option to the Physics Debug Settings.

The other option (which might be the best option) is to use the Settings Registry to store these values (where that lives is another question). This is definitely something we can remove though.
