### ISSUE TITLE
[Linux] Animation Editor: Modified Motion Event on event track in Time View pane returns to the state before modification after deselecting the motion

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#8766]
**Describe the bug**
In the **Animation Editor**, the modified **Motion Event** on event track in **Time View** pane returns to the state before modification after deselecting the motion. Saving the motion after modifying the **Motion Event** does **not** resolve this issue, the **Motion Event** still returns to its state before modification after deselecting it.

Please note that this issue did not reproduce on Windows Stabilization_2205 (3e47df2) and on Windows Development (d40e085) builds.

**Steps to reproduce**
1. Open **Animation Editor**.
2. Load an **Actor** and its motion.
3. Select the motion.
4. In the **Time View** pane, place the **Motion Event** on event track.
5. Modify the **Motion Event** placed on event track (move or expand **Motion Event**).
6. Save the motion by clicking RMB on it and selecting "Save Selected Motions" from the context menu.
7. Deselect the motion.
8. Select the motion.

**Expected behavior**
The modified **Motion Event** on event track in **Time View** pane retains modifications after deselecting the motion.

**Actual behavior**
The modified **Motion Event** on event track in **Time View** pane returns to the state before modification after deselecting the motion.

**Video**

https://user-images.githubusercontent.com/86951967/162158053-188cc3a2-423a-490f-ac3a-568171232e60.mp4

**Found in Branch**
Stabilization_2205: installer

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by amzn-jillich** [comment]
This got fixed with the consolidation of the motion and motion set windows (https://github.com/o3de/o3de/pull/9854) and is not happening anymore. The workflow also changed as saving motions now happens within the motion set window.

**Comment by LB-JakubSkorupka** [comment]
Verified on Development (25425ba) build that this issue no longer occurs.
