### ISSUE TITLE
[Linux] Asset Processor fails to process random number of files during its first scan of a project

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#8771]
**Describe the bug**
Random number of assets fail processing during first run of the Asset Processor for a newly created project with the following error:
`| Info | Child process id 47357 terminated prematurely (signal 9) from ProcessWatcher`

Note that all assets complete without a failure when the processing is rerun.

Please note that each time a new project is created or project's cache is deleted, different assets seem to be failing on each run.

Please refer to the attached screenshots and the attached .log files from one of the Asset Processor runs for more information .

**Steps to reproduce**
1. Create and build a project.
2. Run the Asset Processor or open the Editor for the created project.
3. Wait for the assets to complete processing.

**Expected behavior**
All assets are processed without failure.

**Actual behavior**
A random number (from 3 to 15) of assets fail processing during the first Asset Processor run.

**Screenshots**

**Scan 1:**
![1](https://user-images.githubusercontent.com/86953659/162207185-4771555a-d362-4b3d-8d5c-e3ad8865bf7b.png)

**Scan 2:**
![2](https://user-images.githubusercontent.com/86953659/162207206-d1c76e4d-130b-4c5c-9335-a4ed1078fd7f.png)

**Scan 3:**
![3](https://user-images.githubusercontent.com/86953659/162207237-f93ac988-d55f-40d2-8c6f-ab5badbab500.png)

**Found in Branch**
Stabilization_2205 (3e47df2)
Stabilization_2205: installer

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.3 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[02_light_skin.material-3889609072-1915.log](https://github.com/o3de/o3de/files/8443105/02_light_skin.material-3889609072-1915.log)
[02_light_skin_tex.material-1760708917-8191.log](https://github.com/o3de/o3de/files/8443106/02_light_skin_tex.material-1760708917-8191.log)
[14_green_tex.material-707694613-6109.log](https://github.com/o3de/o3de/files/8443107/14_green_tex.material-707694613-6109.log)
[17_magenta_tex.material-2489927473-8656.log](https://github.com/o3de/o3de/files/8443108/17_magenta_tex.material-2489927473-8656.log)
[21_neutral_6-5_0-44D_tex.material-912383098-8193.log](https://github.com/o3de/o3de/files/8443109/21_neutral_6-5_0-44D_tex.material-912383098-8193.log)
[metal_gold_matte.material-380123344-5436.log](https://github.com/o3de/o3de/files/8443110/metal_gold_matte.material-380123344-5436.log)
[PlatonicSphere.fbx-166773121-4027.log](https://github.com/o3de/o3de/files/8443111/PlatonicSphere.fbx-166773121-4027.log)

**Comment by lmbr-pip** [comment]
May relate to https://github.com/o3de/o3de/issues/8744

**Comment by spham-amzn** [comment]
Can no longer reproduce as of https://github.com/o3de/o3de/commit/51120f6dd5e59a7af960ed7dc408991c907dd0de

![Screenshot from 2022-09-13 13-56-12](https://user-images.githubusercontent.com/82231385/190007708-31b314e2-588c-4eec-8b08-1434f6cb0462.png)

**Comment by LB-BartoszDudzinski** [comment]
Verified as Fixed in Development and Stabilization branches.
