### ISSUE TITLE
Terrain: Terrain World Debugger wireframe intermittently displays rendering issue when adjusting Height Query Resolution

### ISSUE THREAD

**Issue by dm-amzn** [o3de/o3de#8815]
**Describe the bug**
Terrain World Debugger wireframe will intermittently display a rendering issue, within Viewport, after adjusting Height Query Resolution.

- Issue only seems to occur when the input value is either not the default (1.0) or adjusted by the power of 2 (2.0, 4.0, 8.0, etc.).

**Steps to reproduce**

1. Launch the Editor
2. Create a new level, or load an existing level
3. Create generated Terrain
4. In the Entity Outliner, select the level.prefab
5. In the Entity Inspector, within the Terrain World Debugger component, toggle on 'Show Wireframe'
6. In the Terrain World component, observe Height Query Resolution is set to 1.0
7. Adjust input value to 2.0
8. Adjust input value to 3.0
9. Observe issue

**Expected behavior**
No Rendering issues when adjusting input values.

**Actual behavior**
Terrain World Debugger wireframe will intermittently display a rendering issue when adjusting Height Query Resolution.

**Screenshots/Video**

![2022-04-09 21_40_32-Greenshot](https://user-images.githubusercontent.com/97991771/162602023-41568faa-a244-44f3-9987-153a1bc9e042.png)

**Found in Branch**
development commit cefcb653ad1d7187a44f281738502e88c9de5775

**Comment by srikappa-amzn** [comment]
@dm-amzn , can you add more details on what the issue exactly is?

**Comment by jckand-amzn** [comment]
Issue no longer occurs on development@ 64c947064d3765907dbffec4ccc53ed57c809211. Closing out.
