### ISSUE TITLE
EditorSingleTest Error When Using @pytest execution_number'

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#8818]
**Describe the bug**
I wanted to run a test multiple times so I used the pytest "execution_number" decorator, but this resulted in python errors

**Steps to reproduce**
1. Modify any EditorSingleTest pytest to include @pytest.mark.parametrize('execution_number', range(10))
2. Run the pytest

**Expected behavior**
PyTest runs 10 times

**Actual behavior**
Pytest runtime errors and aborts

**Comment by Kadino** [comment]
This is a valid feature request for the test framework to expose, which should default to the number of cores on a machine.

It will need to be exposed through a PyTest Plugin as an optional param in o3de\Tools\LyTestTools\ly_test_tools\_internal\pytest_plugin\test_tools_fixtures.py via pytest_addoption(parser)

Interestingly, Python's os.cpu_count() will return the number of logical cores, not only physical cores.

**Comment by Kadino** [comment]
Oh, wait, I thought this was trying to set the number of parallel tests that execute when running EditorSharedTest.  For repeating tests, I recommend looking at https://pypi.org/project/pytest-repeat/ or parameterizing the test:

```
@pytest.mark.parametrize('unused', range(5))
def my_test(unused):
```

**Comment by Kadino** [comment]
Deleting my misleading comments above.  This looks like a bug in pytest parameterization and collection, with regards to the EditorTest framework. This is likely due to it overriding the normal collection mechanism of pytest.

**Comment by AMZN-Gene** [comment]
> Deleting my misleading comments above. This looks like a bug in pytest parameterization and collection, with regards to the EditorTest framework. This is likely due to the way EditorTest overrides the normal collection mechanism of pytest.

Thanks for the help! This all came about trying to run a test multiple times which is also possible using CTest, although CTests are unfortunately not generated under certain build conditions. I create a separate bug here: #8828

**Comment by jckand-amzn** [comment]
Thought I had a solution to this issue, however locally was using a similar type of temporary, one-off change that @AMZN-Gene worked out in #8819.

**Comment by AMZN-scspaldi** [comment]
Closing this as I clarified that it was a user misunderstanding with the user.

**Comment by AMZN-Gene** [comment]
For anyone wondering the solution…
Parameterize could have any name;  "execution_count" was just the name they chose because it makes sense. It could have been
@pytest.mark.parametrize( "potato_salad", range(5))
Parameterize will run the test as many times as is in the range. 
The python error is:
`function uses no argument 'execution_number'`

If that ‘execute_number” parameter is added to the test, it will work.
