### ISSUE TITLE
Fix Skipped Scripting Test FileMenu_Default_NewAndOpen

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#8839]
The scripting test `FileMenu_Default_NewAndOpen` is failing with a message of _Test fails to find expected lines, it needs to be fixed._

Investigate why this test is failing an fix it so the skip can be removed.

**Source File**: _o3d3\AutomatedTesting\Gem\PythonTests\scripting\FileMenu_Default_NewAndOpen.py_

**Test Suites**:
* TestSuite_Periodic.py

**Comment by michleza** [comment]
This was fixed with PR: https://github.com/o3de/o3de/pull/9288
