### ISSUE TITLE
Modifying Material Instance does not have any effect after enabling LOD Materials

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#8864]
**Describe the bug**
If the _LOD Materials_ are enabled in the _Material_ component, any changes made to the _Material Instance_ are not applied to the model.

Please note that the issue does not occur on Linux.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Open any Level.
2. Create a new entity with _Mesh_ and _Material_ components.
3. Assign any asset to the _Mesh_ component (i.e. _beveledcube_).
4. Check the _Enable LOD Materials_ box in the _Material_ component.
5. Press the _Generate/Manage Source Materials..._.
6. Press _OK_ to confirm.
7. Click the arrow next to the _Default_ material under _Model Materials_ and select _Edit Material Instance..._.
8. Modify any value (i.e. change the _Color_).
9. Click the arrow next to the _Default_ material under _LOD Materials_ / _LOD 0_ and select _Edit Material Instance..._.
10. Modify any value (i.e. change the _Color_).

**Expected behavior**
Changes made to Material Instance are applied to the model.

**Actual behavior**
Modifying the Material Instance does not have any effect.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/162903687-32e25c07-f160-4571-ab9e-c9889f85e02a.mp4

**Found in Branch**
Stabilization_2205: installer

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment]
This issue should be resolved by the PR that was just submitted to the stabilization branch. Beyond that, LOD materials take precedence over model materials hand the default fall back material. If there are any overrides in LOD materials they will need to be cleared to see the effect of model and default materials
