### ISSUE TITLE
Windows clients are immediately disconnecting from o3de-multiplayersample dedicated servers

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#8870]
**Describe the bug**
Connecting a Windows client to the o3de-multiplayersample dedicated server hosted on another Windows machine via IP connection on opened UDP port will result in immediate disconnection from the host due to the following errors:

`Disconnecting from remote address XX.XXX.XX.XX:33450 due to StreamError` on the client side

and 

`ScheduledEventHandle event pointer doesn't match to the pointer of handle to the client` on the host side.

Please note that making sure to avoid https://github.com/o3de/o3de/issues/7469 the client and host machine were restarted
and no residual ServerLauncher and GameLaunchers were found in the task manager.

For further information please refer to the attached screenshots and log files.

**Prerequisites**

* o3de-multiplayersample project was cloned to o3de directory and built with profile configuration on both
Windows machines.
* 33450  or other specified port with UDP protocol was opened on the Windows host machine. 

**Steps to reproduce**

1. Launch the Asset Processor with o3de-multiplayersample project path specified and process all assets.
2. On Windows host machine launch the _MultiplayerSample.ServerLauncher.app_ followed by _host_ and _loadlevel samplebase_
commands.
3. On Windows client machine launch the _MultiplayerSample.GameLauncher.exe_ followed by _cl_serveraddr < host machine IP >_ and _connect_ commands.

**Expected behavior**
Windows machine successfully connects to the dedicated server hosted on another machine.

**Actual behavior**
Windows machine disconnects from the host machine shortly after connection is established due to the stream error.

**Screenshots**
![multiplayer client](https://user-images.githubusercontent.com/86953456/162969678-ebf358ce-20c0-44b3-8d8f-6ccadc0cc9f2.png)

![multiplayer server](https://user-images.githubusercontent.com/86953456/162969958-d24347c1-668a-484f-80d1-2cc221b8ab4c.png)

**Found in Branch**
Stabilization_2205 (3e47df2)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Additional context**
[GameClient log.log](https://github.com/o3de/o3de/files/8473155/GameClient.log.log)
[Serverhost.log](https://github.com/o3de/o3de/files/8473161/Serverhost.log)

**Comment by junbo75** [comment]
I couldn't repro this if the client and server run on the same Window machine. I do see the following warning if I run the "disconnect" command to disconnect the client manually:
`ScheduledEventHandle event pointer doesn't match to the pointer of handle to the client`
![image](https://user-images.githubusercontent.com/68558268/163037341-f70b2f9e-9700-48c0-8a48-3b0972a48699.png)

**Comment by junbo75** [comment]
Note that I can get a different type of errors when test this issue with the following steps:

**Comment by junbo75** [comment]
Note that this might be related to https://github.com/o3de/o3de/issues/8862. I got the exact same error when disconnect and reconnect a second client to the server.

**Comment by AMZN-Olex** [comment]
Note, by default a dedicated server closes itself when the last player disconnect. Try setting sv_isTransient to false, otherwise dedicated server stops hosting when the last player leaves.

```
        // Signal to session management when there are no remaining players in a dedicated server for potential cleanup
        // We avoid this for client server as the host itself is a user and non-transient dedicated servers
        if (sv_isTransient && m_agentType == MultiplayerAgentType::DedicatedServer && connection->GetConnectionRole() == ConnectionRole::Acceptor)
        {   
            if (m_networkInterface->GetConnectionSet().GetActiveConnectionCount() == 0)
            {
                Terminate(DisconnectReason::TerminatedByServer);
            }
        }
```

**Comment by lmbr-pip** [comment]
Blocked as we need two windows machines to reproduce this.

**Comment by LB-MateuszSzweda** [comment]
@lmbr-pip 

I had the same result as written in the ticket on the first launch of MultiplayerSample.GameLauncher and MultiplayerSample.ServerLauncher on the Stabilization_2205 (95dbd13) today.

However after setting **sv_isTransient** to false on the server side as mentioned by @AMZN-Olex I was able to connect successfully and the connection remained stable.

Each time connecting with server with **sv_isTransient** argument set to false resulted in working, playable connection if this is expected the issue can be closed.

**Comment by AMZN-Olex** [comment]
I am currently working on a local repro. One of my laptops is pretty slow, though, so building test code takes time.

**Comment by AMZN-Olex** [comment]
I am unable to repro this issue outside of VPN. 

HOWEVER, if a client is on VPN, it will fail to connect to a local server. The moment the client leaves VPN, even without restarting, the client can connect to the local server yet again.

**Comment by AMZN-Olex** [comment]
The same issue occurs if either the server or a client is on VPN.

**Comment by AMZN-Olex** [comment]
Given my finding, I am resolving this as Does Not Repro.
