### ISSUE TITLE
[22.05.0 release requirement] Update O3DE logo throughout the editor, project manager, and installer

### ISSUE THREAD

**Issue by Ulrick28** [o3de/o3de#8886]
**Is your feature request related to a problem? Please describe.**
For the 22.05.0 release all instances of the O3DE Logo must be updated in the editor, project manager, and installer. We will also need to make sure the application icons are correct for both Windows and Linux.

**Comment by rainbj** [comment]
UX will help track which locations need to be updated.

**Comment by AMZN-daimini** [comment]
Changes were submitted to stabilization. This should be ready for a QA pass first thing next week.

**Comment by Ulrick28** [comment]
@AMZN-daimini Ok to resolve this issue?

**Comment by jckand-amzn** [comment]
Editor:
- Icon
- Taskbar Icon
- Splash Screen Logo/BG
- About O3DE Splash
- Platform Settings page: splash screen/icon logos for Android/iOS

Issues:
1. Windows taskbar and explorer icon for Editor used old logo for awhile after building, but looked correct in the Windows preview on hover of taskbar icon, and in the Task Manager (incremental build/cache issue?)

______________________________________


O3DE.exe:
- Logo
- Background
- Gem Icon
- Project Icon

Issues:
1. Existing projects and gems in O3DE.exe have the old logo if they used defaults

_______________________________________


Installer:
- Logo
- Taskbar Icon

Issues:
1. None

**Comment by Ulrick28** [comment]
Existing projects and gems will have the old logo. This is known and not something we will change for the 22.05.0 release.

**Comment by AMZN-daimini** [comment]
Sounds good. I think there's still some more testing going on, but I feel confident enough to close this issue now. Thanks everyone!
