### ISSUE TITLE
Script Canvas: Variable type changing not present in stabilization build

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#8901]
**Describe the bug**
Warsaw Lionbridge team is not seeing the variable type change feature recently added to development.  

**Steps to reproduce**
1. Download and install the o3de engine from this url:  https://o3debinaries.org/stabilization-2205/Latest/Windows/o3de_installer.exe
2. Launch o3de
3. Make and build a new project with a new level
4. Open script canvas editor
5. Open a new graph file
6. In the variable manager click 'Create Variable'
7. Give the variable a name and type then confirm your selections
8. Right click the new variable in the variable manager list

**Expected behavior**
The context menu lists Configure <variable name> in the context menu 

**Actual behavior**
Configure <variable name> is missing from the context menu
Link to Lionbridge team findings; https://wiki.agscollab.com/pages/viewpage.action?pageId=139090371

**Desktop/Device (please complete the following information):**
 - Device: PC win 10
 - CPU Ryzen 5950
 - GPU Nvidia 3070
 - Memory 32gb]

**Comment by carlitosan** [comment]
The changes will be in the new stabilization build.
