### ISSUE TITLE
DetailMaps Screenshot Test Broken

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#8903]
**Describe the bug**
AtomSampleViewer material screenshot test 102_detailmaps_all.png is failing

**Steps to reproduce**
Run AtomSampleViewer's materialscreenshottests.bv.lua

**Expected behavior**
Pass with tolerance Level H

**Actual behavior**
Failed, would need tolerance level I. The screenshot comparison shows a clear difference, it's not just a hardware difference.

**Assets required**
AtomSampleViewer project

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/55155825/163259318-02bb83b0-3443-4911-a605-bb88d8a099da.png)
![image](https://user-images.githubusercontent.com/55155825/163259399-3bc13c54-2583-4b60-af03-729a7879ec11.png)
![DetailMaps](https://user-images.githubusercontent.com/55155825/163260094-e6165ffc-f80e-453c-a097-e6402f6e1355.gif)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen Threadripper 3970X 32-Core Processor    3.69 GHz
 - GPU: RTX 3070 Ti (driver 472.84)
 - Memory: 64.0 GB

**Comment by rgba16f** [comment]
is that the Hermanubis model?

**Comment by VickyAtAZ** [comment]
The development branch should be updated to have change in commit 553ca7a59434165624dbe5125d871f917b5603d6

**Comment by santorac** [comment]
> The development branch should be updated to have the change in commit [553ca7a](https://github.com/o3de/o3de/commit/553ca7a59434165624dbe5125d871f917b5603d6)

That commit on affects the processing of "_thickness" texture maps. 102_detailmaps_all.material does not use any textures with that preset mask, so it should not be affected by those changes.

I opened 102_detailmaps_all.material in the Material Editor, and checked out the image that's being used as the detail layer mask. See how the bottom half is black?
![image](https://user-images.githubusercontent.com/55155825/163327156-14e4d1cd-57b5-4964-aa69-aad536c5f2a2.png)

Here's what the original file looks like:
![image](https://user-images.githubusercontent.com/55155825/163327347-d4106c69-ce41-4c8e-8f60-ddfc1222d9ad.png)

**Comment by santorac** [comment]
My AP shows this error for Hermanubis_ao.tif:
```
ZIPDecode: Trace::Error
>	D:/o3de/Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageLoader/TIFFLoader.cpp(32): 'void __cdecl ImageProcessingAtom::TIFFLoader::ImageProcessingTiffErrorHandler(const char *,const char *,char *)'
>	Decoding error at scanline 2047, incorrect data check
```

**Comment by santorac** [comment]
I suspect the problem was introduced with this PR that added average-color calculation to the image asset processing pipeline: https://github.com/o3de/o3de/pull/7687/files#diff-1e94079bd536962c43b7f4c9ef315d7c186c38d669f47e5c6e0acdc536b06998

**Comment by RoaldFre** [comment]
The error in AP for that file also seems to occur in 6dc665e6a7, which is the development branch parent of the latest development merge in the feature branch of PR #7687, so it seems like the problem already existed in the dev branch before PR #7687 was merged in?

**Comment by santorac** [comment]
@VickyAtAZ is looking into this, suspects it's related to https://github.com/o3de/o3de/commit/a351ba40a3df166dcf4ec53b725fcbe955f4621d
