### ISSUE TITLE
Update button in Scene Settings needs to be a primary (blue) button when active.

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de#8911]
From Actor Workflow Evaluation. It wasn't clear to the user he needed to press the Update button after making changes in Scene Settings.

The Update button in Scene Settings is deactivated until the user makes a change to the settings. When a change is made, the button becomes active, but because it is a secondary button, it is still gray. This should be a primary button (blue) to better notify the user that they need to click it to update their `.assetinfo` file.

**Comment by srikappa-amzn** [comment]
@o3de/sig-ui-ux , please provide guidance on whether this can be accepted.

**Comment by amzn-leenguy** [comment]
@micronAMZN Any chance you could provide a video recording of this workflow?

**Comment by amzn-leenguy** [comment]
From what Im reading in the description though; we do have a inactive state for primary buttons (blue). Image reference attached below from our design library:
![buttons](https://user-images.githubusercontent.com/82846749/163464731-0d445cc2-1e42-4523-8168-67b28156897c.png)

**Comment by AMZN-stankowi** [comment]
![image](https://user-images.githubusercontent.com/4838196/195865598-ffeaf327-32fa-4b36-be2f-4fe7ea62e293.png)

This has been updated as part of a UI overhaul of this tool, which has had UX approval.
