### ISSUE TITLE
Scene Settings UX very confusing on Update/Exit

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de#8914]
When using the Scene Settings tool the last two things the user does are:

1. Click the **Update** button
2. Exit **Scene Settings**.

The UX here is *VERY* confusing.

* When the user clicks **Update**, the `.assetinfo` file is generated or updated. Then, a black overlay appears on the **Scene Settings** interface with the message "Close the processing report to continue editing settings."
* At the same time, a **File Progress** window opens with a table header, an empty white table, and an *OK* button. This window does nothing, displays no useful info at all, and must be closed.
* At this point, the Asset is processing in the background with no feedback provided to the user.
* There is no button to close Scene Settings other than the **X** in the title bar. When **X** is clicked, a message box appears notifying the user there are unsaved changes (not true, the changes were saved when **Update** was clicked). The message box has buttons confusingly labeled **Discard** and **Cancel**. Discard exits, and Cancel returns to Scene Settings.

The following image is what the user sees when **Update** is clicked. No information ever appears in the progress window.

![SceneSettingsProgress](https://user-images.githubusercontent.com/58789750/163292751-bd15c71c-a14d-43c4-98a5-271af09f6bd9.png)

The following image is what is shown when the user tries to close Scene Settings. This is after clicking **Update** which saves the changes, and after closing the Progress window.

![UnsavedChanges](https://user-images.githubusercontent.com/58789750/163293024-4154ea66-3aed-44de-af9a-b937c01fce56.png)

**Expected behavior**

1. The Scene Settings tool should probably have **Save** or **Apply** and **Close** buttons to mimic other similar tools like Texture Settings.
2. The **Save** or **Apply** buttons should be primary (Blue).
3. Buttons should always be active. The current Scene Settings tool doesn't accurately track whether the settings have been saved to activate/deactivate the **Update** button. Make an always active **Apply** or **Save** button and always save settings when clicked. 
4. Get rid of the File Progress Windows since it does nothing and would only be a less useful version of Asset Processor if it did work.
5. Remove the black overlay on Scene Settings. It's a bad solution for a problem that shouldn't exist.
6. Maybe add a status line to the Scene Settings main UI that notifies the user the settings have been saved and the FBX is processing. Tell the user to check Asset Processor for more info.
7. The unsaved changes dialogue needs improvement. It should only appear when there are unsaved changes. Follow the model most other applications use. Have a message box that requesting the user to save with **Yes**, **No**, and **Cancel** or **Save**, **Don't Save**, and **Cancel** buttons.

**Comment by srikappa-amzn** [comment]
@o3de/sig-ui-ux , can you review the requirements here and provide guidance?

**Comment by lmbr-pip** [comment]
Need to break down feature into a number of tasks as this is potentially a large amount of work. Currently this is "working as designed" but is confusing, so would be interested in ui-ux suggestions in this space.

**Comment by amzn-leenguy** [comment]
I'd like to see a video of the workflow if possible @micronAMZN . Or if you could visit our office hours, we may be able to give better guidance.

**Comment by lmbr-pip** [comment]
Removed the kind/bug as this is really a request to improve this feature (and as called out it will be delivered as a number of tasks that incrementally improve the experience).

**Comment by micronAMZN** [comment]
I disagree with this assessment. I think this is a usability bug. Here the user is presented with a black box, a white box, a button labeled "OK", and instructed to close the processing report when nothing on the screen is labeled "processing report". The tool is providing no useful information, forcing the user to intuit what action to take and close a window that has no function.

**Comment by yuyihsu** [comment]
@lmbr-pip @micronAMZN , Suggest we address the issue in two steps: 
1. In short-term, we should fix the usability bug as @micronAMZN mentioned above. The second image above showed the problem clearly. The message is written in a reversed way, with the "Discard" button set as the primary color, which will lead the user to click on it, and in turn their changes will not be saved. We should write the message as below:

"You have unsaved changes. Would you like to save it?
[Save] [Discard]" with the [Save] button set as the primary button.

2. Long-term, we will need to revisit the Scene settings design in general. I know the content sig has a plan to improve the Asset Browser, which will incorporate the Scene Settings UI in the property window and improve the overall UX on this workflow. I'd suggest we break the long-term part into a separate feature request ticket.

**Comment by rainbj** [comment]
Hi team. I've picked up this task from the UX side of things. I've already started making some design mock. Will send updates shortly with more details. Thanks

**Comment by rainbj** [comment]
Let me step through my thinking, and we can have a follow-up conversation if there are any questions or disagreement on direction. 

First and foremost, long term, we would like to move all these settings to the new AB inspector panel. In the short term, we can make a decision; would we like to; fix this issue more like a patch or would like to take on this work now.

![Asset tagging](https://user-images.githubusercontent.com/82551958/176982048-81bd2eff-254f-4528-8caa-b0d79ebb1d95.png)

My assumption here is that we will want to fix the current workflow, so this is the current-suggested plan. 

1. Before 
![2022-06-27_16-08-02](https://user-images.githubusercontent.com/82551958/176982933-d19ee0c2-4529-41c2-9d78-dc2eba529b8d.png)
After
![FBX settings menu1](https://user-images.githubusercontent.com/82551958/176982943-8513c651-ac36-45ba-a928-32d7a3a93d65.png)

2. Before 
![before2](https://user-images.githubusercontent.com/82551958/176982995-9c0ef90f-cff7-4ae6-998d-13d8041cb834.png)
After
![after2](https://user-images.githubusercontent.com/82551958/176983011-61f3cb1d-983f-4ae4-85cf-735ec9be245d.png)

3. Before
![before3](https://user-images.githubusercontent.com/82551958/176983027-c6c1049d-f7be-4d16-9a28-ae24fb0cf681.png)
After
![after3](https://user-images.githubusercontent.com/82551958/176983032-4e94c381-f28f-403e-9cc5-6383661e2aa1.png)

4:Before
![before4](https://user-images.githubusercontent.com/82551958/176983055-a6bac0b2-8a01-4cfb-8548-c431d1b3f0a3.png)
After
![after4-a](https://user-images.githubusercontent.com/82551958/176983060-239d325e-568e-4e30-a6cd-e3b309ae48fb.png)
![after4-b](https://user-images.githubusercontent.com/82551958/176983062-442ee8fe-2305-4f4d-b515-544755f4d039.png)
![after4-c](https://user-images.githubusercontent.com/82551958/176983065-b7d8171b-8358-40ba-bfa0-16952545fec4.png)

5. Before
![before5](https://user-images.githubusercontent.com/82551958/176983088-2b5aede2-a01a-480c-a7cc-f006cfbc7ee2.png)
After
![after5](https://user-images.githubusercontent.com/82551958/176983091-6da282d5-2e4a-4292-80ea-2a6b5dbd0205.png)

**Comment by lmbr-pip** [comment]
Relates also to https://github.com/o3de/o3de/issues/8915

**Comment by AMZN-stankowi** [comment]
This pull request should address the core issue here, with the closing window popup being confusing. https://github.com/o3de/o3de/pull/10967

We have several other tickets to cover other work to improve the experience of using this tool.

**Comment by AMZN-stankowi** [comment]
https://github.com/o3de/o3de/pull/10967 is merged, it addresses the main concern of this ticket. We have separate tickets to cover the other improvements to make to the Scene Settings tool, so I'm closing this ticket as done.

**Comment by rainbj** [comment]
Hey @AMZN-stankowi would you mind putting together as a demo for me and @yuyihsu, so we can see what's in and out
