### ISSUE TITLE
Feature Request: Better indication Asset is Processing from Scene Settings/Editor and when there is an error.

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de#8915]
During the Character Workflow Review, there were errors in processing an FBX asset. It wasn't clear to the user that the asset was being processed or that there was an error.

Related: #8914 

After making changes in Scene Settings and clicking **Update**, the `.assetinfo` is updated, the asset begins processing and a file progress window opens that shows no useful information. In Asset Browser, an animated **Busy** icon appears while the asset processes. If there is an error, it appears in console, which might not be open, or in Asset Processor, which is probably not visible.

Is it possible to add a status to Scene Settings that provides simple status about the asset such as whether it's processing, or if there is an issue? Maybe if an asset fails to process it could display an error icon in Asset Browser.

**Comment by yuyihsu** [comment]
Dup of this ticket: https://github.com/o3de/o3de/issues/8914. There's been a UX solution provided in 8914.

**Comment by lmbr-pip** [comment]
There is a general proposal to improve the Editor + AP integration here: https://github.com/o3de/o3de/issues/9534 including toast popups for failures etc.

At this time I do not believe there is a proposal to provide any dynamic AP information during a reload in the scene settings tools.

**Comment by svitlani** [comment]
This work is addressed in https://github.com/o3de/o3de/issues/8914, closing as a dup.
