### ISSUE TITLE
Modifications made to the Material Instance are not visible in GameLauncher

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#8920]
**Describe the bug**
Any changes made to the Material Instance are only visible in the Editor. When launching the level in the GameLauncher, all the materials instances are set to default.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Create a new, default level.
2. Add a _Material_ component to the _Shader Ball_ entity.
3. Click the arrow next to _shaderball_01_ under _Model Materials_ and select _Edit Material Instance..._.
4. Make any change that is easily visible in the Viewport (i.e. change the _Color_ value).
5. Save the level.
6. Open the level in GameLauncher.

**Expected behavior**
Changes made to the Material Instance are visible in the GameLauncher.

**Actual behavior**
Changes made to the Material Instance are not visible in GameLauncher.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/163380670-06616485-f6ce-484e-b553-a8a3183a2b25.mp4

**Found in Branch**
Development (eaef42a)
Stabilization_2205 (d25f305)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-TomaszSerwanski** [comment]
Reopening the issue as it still occurs in the latest Stabilization/2205 branch (commit ddedb53).

**Comment by gadams3** [comment]
Hello! Can you please provide more information or reconfirm that this is still happening on the latest stabilization? I am able to change materials in the material component, set different property overrides, like color, enter and exit game mode without any issues, and save the level to open the game launcher, load the level multiple times, and see the materials applied consistently. I have tested with the editor and game launcher open simultaneously, saving the level with different material states, reopening it in the launcher to see all modifications applied correctly. I see the same shutting down and restarting the game launcher.

**Comment by gadams3** [comment]
![image](https://user-images.githubusercontent.com/82461473/165985172-fce56343-2971-4141-acfb-61e970c193b1.png)

**Comment by LB-TomaszSerwanski** [comment]
Hi @gadams3, I have recorded a video showing the issue (still active in Stabilization_2205 (a2a15da)): 

https://user-images.githubusercontent.com/86953108/166229444-9306f93b-e55a-49d8-a939-8e03aa5f4821.mp4

A modified material instance is never transferred to the GameLauncher for us (also verified on the second machine). The changes apply to the GameLauncher when editing the source material (as shown on the video - on the very last mesh) or applying another material to it but not when modifying instances. 
Please also note that we have confirmed that this is active both on the prebuilt-sdk as well as the source engine.

**Comment by gadams3** [comment]
Thank you. I see it now. The property overrides were not applied when there was no material override assigned to the slot. I will take a closer look at that specific case.

**Comment by AMZN-Gene** [comment]
Reproduced @ #10940

**Comment by gadams3** [comment]
Resolved by the following PR https://github.com/o3de/o3de/pull/11325

**Comment by LB-TomaszSerwanski** [comment]
Verified as fixed in Stabilization (021d32a) and development (511a88c) branches.
