### ISSUE TITLE
Dyn_Veg_TQO_Bug - Landscape Canvas nodes labels are shown as invalid text

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#8932]
**Describe the bug**
When creating a new Landscape Canvas asset, nodes dragged from the palette show an invalid title label.

**Steps to reproduce**
1. Create a new level
2. Open the Landscape Canvas tool
3. Create a new Asset
4. Drag nodes from the palette to the graph viewport

**Expected behavior**
The nodes have correct labels

**Actual behavior**
Labels are shown correctly

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82231674/163467861-1555696a-8b6e-49dd-9885-01b509f27034.png)

**Found in Branch**
Stabilization/2205

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen Threadripper 3970X 32-Core
 - GPU NVidia RTX 3070
 - Memory 64GB

**Additional context**

**Comment by AMZN-daimini** [comment]
Discussed with @cgalvan , sounds like this only reproduces in Debug (which is how I built the branch)

**Comment by cgalvan** [comment]
Duplicated by https://github.com/o3de/o3de/issues/4872
