### ISSUE TITLE
Terrain_TQO_Bug: Editor can crash when moving Terrain Layer Spawner setups

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#8936]
**Describe the bug**
Editor can crash when moving Terrain Layer Spawner setups. NOTE: This has not been solidly reproduced.

**Prerequisites**
1. Terrain Gem is enabled for the current project.

**Steps to reproduce**
1. Open a new or existing level in the Editor.
3. Click on the root Level entity, and add the Terrain World, Terrain World Renderer, and Terrain Debugging level components.
4. Create a new entity.
5. Add an Axis Aligned Box Shape component to the entity.
6. Add a Terrain Layer Spawner component to the entity.
7. Adjust the Spawner setup's translation via the Entity Outliner.

**Expected behavior**
Spawner area is moved as specified by translate values.

**Actual behavior**
Editor can crash.

```
Call Stack Trace:
19) 00007FFB5E5FB857 (KERNELBASE) : UnhandledExceptionFilter
18) 00007FFB60A951B0 (ntdll) : memset
17) 00007FFB60A7C766 (ntdll) : _C_specific_handler
16) 00007FFB60A920CF (ntdll) : _chkstk
15) 00007FFB60A41454 (ntdll) : RtlRaiseException
14) 00007FFB60A90BFE (ntdll) : KiUserExceptionDispatcher
13) D:\GitHub\o3de\Gems\Terrain\Code\Source\TerrainSystem\TerrainSystem.cpp (326) : Terrain::TerrainSystem::MakeBulkQueries
12) D:\GitHub\o3de\Gems\Terrain\Code\Source\TerrainSystem\TerrainSystem.cpp (413) : Terrain::TerrainSystem::GetHeightsSynchronous
11) D:\GitHub\o3de\Gems\Terrain\Code\Source\TerrainSystem\TerrainSystem.cpp (1229) : Terrain::TerrainSystem::ProcessHeightsFromRegion
10) D:\GitHub\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1541) : AZ::Internal::EBusContainer<AzFramework::Terrain::TerrainDataRequests,AzFramework::Terrain::TerrainDataRequests,0,0>::Dispatcher<AZ::EBus<AzFramework::Terrain::TerrainDataR
 9) D:\GitHub\o3de\Gems\Terrain\Code\Source\TerrainRenderer\TerrainFeatureProcessor.cpp (292) : Terrain::TerrainFeatureProcessor::UpdateHeightmapImage
 8) D:\GitHub\o3de\Gems\Terrain\Code\Source\TerrainRenderer\TerrainFeatureProcessor.cpp (417) : Terrain::TerrainFeatureProcessor::ProcessSurfaces
 7) D:\GitHub\o3de\Code\Framework\AzCore\AzCore\Jobs\Internal\JobManagerBase.cpp (31) : AZ::Internal::JobManagerBase::Process
 6) D:\GitHub\o3de\Code\Framework\AzCore\AzCore\Jobs\Internal\JobManagerWorkStealing.cpp (421) : AZ::Internal::JobManagerWorkStealing::ProcessJobsInternal
 5) D:\GitHub\o3de\Code\Framework\AzCore\AzCore\std\parallel\thread.h (193) : AZStd::Internal::thread_info_impl<`AZStd::thread::thread<`AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads'::`4'::<lambda_1> >'::`2'::<lambda_1> >::execute
 4) D:\GitHub\o3de\Code\Framework\AzCore\Platform\Common\WinAPI\AzCore\std\parallel\internal\thread_WinAPI.cpp (38) : AZStd::Internal::thread_run_function
 3) 00007FFB5E2B1BB2 (ucrtbase) : configthreadlocale
 2) 00007FFB5F0B7034 (KERNEL32) : BaseThreadInitThunk
 1) 00007FFB60A42651 (ntdll) : RtlUserThreadStart
```

**Found in Branch**
stabilization2205 installer

**Comment by jckand-amzn** [comment]
Unable to reproduce on stabilization/2205@af75b10590969bf7038bf4acb4ea10e1663bd420, however this issue was difficult to reproduce as written. If we can confirm the expected fix went in (believe this was expected to be due to the same root cause as #8934, I think this can be safely closed.

**Comment by mbalfour-amzn** [comment]
I can confirm that the expected fix went in: https://github.com/o3de/o3de/commit/523f3988e14af7ec07be865f452a509c2218ebc5 . 

The specific fixes from that commit that should have fixed this bug:

1. The addition of an empty check to ProcessHeightsFromRegion() in TerrainSystem.cpp
```
    if (inPositions.empty())
    {
        return;
    }
```

2. The addition of an empty check to TerrainFeatureProcessor::UpdateHeightmapImage() in TerrainFeatureProcessor.cpp:
```
            // If there aren't any samples in the region, there's nothing to update, so just return.
            if ((updateWidth == 0) || (updateHeight == 0))
            {
                m_dirtyRegion = AZ::Aabb::CreateNull();
                return;
            }
```

Both of these functions appear in the callstack in the bug above, so I feel reasonably confident that these changes fixed the bug.
