### ISSUE TITLE
Terrain_TQO_Bug: Visual glitch with the PhysX Heightfield Collider

### ISSUE THREAD

**Issue by cgalvan** [o3de/o3de#8937]
**Describe the bug**
There is a flashing visual glitch when drawing the PhysX Heightfield collider.

**Steps to reproduce**

1. Setup a simple physicalized terrain setup following these instructions:
  https://o3de.org/docs/user-guide/components/reference/physx/collider/
2. Make sure your entity has both a Terrain Physics Heightfield Collider and PhysX Heightfield Collider
3. Enable the "Draw collider" field on the PhysX Heightfield Collider component

**Expected behavior**
Collider is drawn as expected.

**Actual behavior**
There is visual flashing glitch when drawing the collider (see image below):

![PhysXHeightfieldColliderVisualGlitch](https://user-images.githubusercontent.com/7519264/163480932-3b270566-205d-48f8-8b3c-3f9e339887e6.gif)

**Found in Branch**
stabilization2205 installer

**Comment by mbalfour-amzn** [comment]
The workaround of defaulting the debug drawing to 'off' is in stabilization/2205. We have a separate bug (#8989) for the long-term fix, where the debug drawing itself is improved, so this bug can be closed.
