### ISSUE TITLE
Windows Asset Processor Rename Issues

### ISSUE THREAD

**Issue by macy12825** [o3de/o3de#8943]
The problem of renaming assets on windows platform is as follows：
win platform（16core32g）
![image](https://user-images.githubusercontent.com/97455291/163504712-df8bc7b4-4a0b-4b2a-9e83-a50c1f7a0059.png)

**Comment by lmbr-pip** [comment]
@macy12825 To be clear, your expectation is that Windows should be case insensitive by default? 

Can you also provide branch and commit information, or installer information?

**Comment by macy12825** [comment]
> 


Any branch has this problem under the win platform.

**Comment by monroegm** [comment]
@macy12825 Can you please add more standard information to this bug report such as steps to reproduce, expected outcome and actual outcome. Thanks!
