### ISSUE TITLE
Issue moving a Project to another Build of o3de engine. Project JSON needs manual adjustment. 

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#8953]
**Describe the bug**
Moving a Project to another Build of o3de engine, there are no Project Manager menu items to update the Projects first assigned engine, only a over all engine, This will cause build errors building the project and also project not being able to launch.

The Project.json must be manually adjusted for the project to build and load properly. 

Please see an example, this illustrates two projects in my o3de projects folder, but with mixed engines per project. These must manually be edited to match the current running engine.

**Steps to reproduce**
1. Move a project from one engine to another.
2. Try and build and launched project with different engines in project.json
3. Please see attached.

**Expected behavior**
If you rebuild a project from another build of the engine, the project.json will update the engine to the current engine being used with the project manager.

**Actual behavior**
The project manager has no idea about the loaded projects.json with an engine entry that is not mathing the project managers engine.

**Assets required**
Projects from two different engine builds.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/87207603/163621144-44b889f3-da56-4b4a-bbfa-b3c61915a148.png)

**Found in Branch**
Production and Development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I9-9900k
 - GPU  NVidia RTX 2080ti
 - Memory 16GB

**Additional context**

**Comment by robhaco** [comment]
Dug into this a bit to get some clarity:
Project's project.json is not updated with a new engine value when added as an existing project through Project Manager.  If the user then builds the project while the old engine is still around, they will likely not see an issue, though it will be secretly using the old engine, and not the one that o3de.exe was launched from.  If they try to build an added project and the old engine is no longer there/registered, then a build error will occur and the project can't be used without manually changing the engine value as stated in the ticket.

**Comment by AMZN-alexpete** [comment]
This is a known issue that the versioning efforts should address - not only showing the engine version for each project, but the ability to "upgrade" a project to use a different engine.  Do you have any suggestions of things we can do in the meantime to make it easier for users to move a project to a new engine?  My thoughts are
1. Display engine version for any project added in the Project Manager - and show some warning icon if it is not compatible with the engine version the Project Manager is using.
2. When adding an existing project - check the engine field and if it doesn't match, ask the user if they want us to update their project to use this new engine for them.  If they say yes, we'll change the engine field entry in project.json for them.
3. Display the engine version in the Project Settings page and let the user change that property and save the setting, which should update the project.json file

**Comment by monroegm** [comment]
Putting this in the Release backlog as it seems like it could impact customers upgrading to the upcoming version, but please feel free to remove it from the Release backlog if people who know more about Project Manager disagree. @Ulrick28 @AMZN-alexpete

**Comment by monroegm** [comment]
Followed up with @Ulrick28 offline and decided to downgrade the priority and remove the Release/2205 milestone.
