### ISSUE TITLE
Prefabs: Failing to despawn a spawnable results in spawned entity remaining in world with no way to interact

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#8958]
**Describe the bug**
Failing to despawn a spawnable results in spawned entity remaining in world with no way to interact. This persists through other levels loaded in the Editor until the Editor is restarted.

**Steps to reproduce**
1. Create a new entity, and add a Mesh component and any valid mesh asset to it.
2. Create a prefab from the entity.
3. Create another new entity with a Script Canvas component.
4. Open Script Canvas and create a new graph.
5. Create 2 new variables--a SpawnableAsset variable, and a SpawnTicketInstance variable
6. Setup the graph as seen below:
![image](https://user-images.githubusercontent.com/82226555/163630395-9060be0a-ff88-404f-a8d4-b75f9d9db8d0.png)
7. Save the Script Canvas graph, and assign it to the entity created in step 3.
8. Enter Game Mode to allow the script to run, then Exit Game Mode.

**Expected behavior**
Spawnables spawned at runtime are cleaned up regardless of whether they were despawned properly by the user.

**Actual behavior**
Spawnables stick around if not despawned, even persisting through other levels. This continues until the Editor is relaunched.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
[2022-04-15 15-48-18.zip](https://github.com/o3de/o3de/files/8498222/2022-04-15.15-48-18.zip)

**Found in Branch**
stabilization2205@4cd22af1558aef3fa03b056297092cdb59f0a07c

**Comment by NicholasVanSickle** [comment]
SpawnTickets in SC don't seem to despawn when they're unreferenced, either (contrary to the RAII semantics of their C++ types). I have a graph that has a container of SpawnTickets, e.g. here:
![image](https://user-images.githubusercontent.com/760096/163651476-dd919482-bc03-435f-83cc-8aa249475796.png)
I would expect erasing the ticket from a container (the only reference to the ticket) to trigger a despawn, but I instead have to call Despawn manually.
