### ISSUE TITLE
Warning in console when creating a prefab from the Entity Outliner

### ISSUE THREAD

**Issue by michabr** [o3de/o3de#8968]
**Describe the bug**
When an entity is turned into a prefab in the editor, a warning is output to the console:

[Warning] (Prefabs) - Prefab - EntityIdMapper: Entity with Id [10041142070320831894] has no registered owning instance

**Steps to reproduce**
1. Create a new level
2. Right click in the entity outliner and select "Create entity"
3. Select the new entity, right click and select "Create prefab..."
4. Save prefab
5. Notice the warning in the console

**Expected behavior**
No warnings when creating a prefab.

**Actual behavior**
Warning when creating a prefab.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by forkercat** [comment]
Looks like this has been fixed in this PR: https://github.com/o3de/o3de/pull/12506

I do not see this happening again.
