### ISSUE TITLE
Multiplayer CreateInput Never Called in ScriptCanvas

### ISSUE THREAD

**Issue by adamarjian1** [o3de/o3de#8969]
**Describe the bug**
I am currently using the Multisample project. Project builds fine.

I create the attached scriptcanvas script and attach it to a network prefab. Within the script I am checking for network create and process inputs, but they never getting called.

**Steps to reproduce**
1. Build the multiplayersample file
2. Create a network Prefab
3. Add a scriptcanvas component 
4. press ctrl + G to run the project

**Expected behavior**
I expect my character to move and the print statements "Yo Create Input" in the script to fire off

**Actual behavior**
Character does not move and the print statement does not print

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.
![image](https://user-images.githubusercontent.com/82278244/163645741-064e15ea-e9c0-4aaf-af44-0d6742be6256.png)

**Desktop/Device (please complete the following information):**
 - Device: PC, Mac, iPhone, Samsung] 

**Additional context**
[DamarjianScriptcanvas.zip](https://github.com/o3de/o3de-multiplayersample/files/8498457/DamarjianScriptcanvas.zip)
[DamarjianController.AutoComponent.zip](https://github.com/o3de/o3de-multiplayersample/files/8498765/DamarjianController.AutoComponent.zip)

**Comment by AMZN-Gene** [comment]
Posting chat conversation here with @carlitosan:
_We've got sort of a general problem with prefabs holding on to all Lua/SC assets. Lua has a band aid in dev, SC has a bandaid in PR. That should help. If the script is building, and not getting called at all, forcing a rebuild of the prefab/spawnable or a cache cleaning may be your only option, please document what you get in detail, we need data for @lawsonamzn ._

**Comment by lmbr-pip** [comment]
@adamarjian1 - Did a rebuild help here? See AMZN-Genes comments.

**Comment by AMZN-Olex** [comment]
I am adding sig/content for visibility as at this point, we are not seeing anything new to add from sig-network.

**Comment by lmbr-pip** [comment]
Believe fixed, please re-open if issue still occurs.
