### ISSUE TITLE
Improve SpawnableAsset ScriptCanvas usage

### ISSUE THREAD

**Issue by NicholasVanSickle** [o3de/o3de#8974]
**Is your feature request related to a problem? Please describe.**
Currently "SpawnableAsset" gets connected to a "Prefab" pin for spawning, which is a bit confusing:
![image](https://user-images.githubusercontent.com/760096/163652669-a16d9280-89c1-45cd-a5db-bfba95f7a758.png)
Additionally, when you add a SpawnableAsset variable, you have to expand a field named after the variable to reveal an opaquely named "m_asset" field to set the Prefab.
![image](https://user-images.githubusercontent.com/760096/163652728-2e38b11b-956c-450f-bb08-a21662896d47.png)

**Describe the solution you'd like**
I suggest we change the user-facing name of "SpawnableAsset" to "Prefab" and bubble up "m_asset" in the property editor and just expose it as "Prefab" or "Prefab Asset"

**Comment by srikappa-amzn** [comment]
@NicholasVanSickle , since this refers to the state of things in stabilization/current release rather than development, can you look at the current state of SC-Spawnables in development and see if any changes are still required?

**Comment by monroegm** [comment]
@NicholasVanSickle closing for now based on @srikappa-amzn 's comment. If you find that something still needs to be done after reevaluating feel free to reopen or file a new ticket
