### ISSUE TITLE
Feature Request: Need some API to get original material data

### ISSUE THREAD

**Issue by KK-5** [o3de/o3de#8982]
**Is your feature request related to a problem? Please describe.**
I find that there are only  API for getting material's override data like GetPropertyOverride, no API for original material data. If I don't edit the material property with Editor Material Instance, I can't get the value of that property.

**Describe the solution you'd like**
Provide API to get original material data.

**Describe alternatives you've considered**

**Additional context**

**Comment by galibzon** [comment]
@santorac , can you please confirm if We have the requested API already?

**Comment by santorac** [comment]
I think @liukaikai-g is right. This ticket is about the Material Component API, not the material data itself. The only function that is currently available that might help is MaterialComponentRequests::GetOriginalMaterialAssignments, but that's not very convenient to use. We should probably add a function like MaterialComponentRequests::GetMaterialAssignment(MaterialAssignmentId), then you can get the original material asset from the MaterialAssignment struct. Would that satisfy the use case?

**Comment by liukaikai-g** [comment]
@santorac Yes, it is my feature request

**Comment by gadams3** [comment]
Addressed by the following changes
https://github.com/o3de/o3de/pull/9963
https://github.com/o3de/o3de/pull/10035
https://github.com/o3de/o3de/pull/10094
