### ISSUE TITLE
Terrain_TQO_Bug: Visual glitch with the PhysX Heightfield Collider (long term fix)

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#8989]
This is a bug related to #8937. In 8937 debug was turned off by default to as a work around. For this bug we need to address the z-fighting issues.

**Describe the bug**
There is a flashing visual glitch when drawing the PhysX Heightfield collider.

**Steps to reproduce**

1. Setup a simple physicalized terrain setup following these instructions: https://o3de.org/docs/user-guide/components/reference/physx/collider/ 
3. Make sure your entity has both a Terrain Physics Heightfield Collider and PhysX Heightfield Collider
4. Enable the "Draw collider" field on the PhysX Heightfield Collider component

**Expected behavior**
Collider is drawn as expected.

**Actual behavior**
There is visual flashing glitch when drawing the collider (see image below):

[PhysXHeightfieldColliderVisualGlitch](https://user-images.githubusercontent.com/7519264/163480932-3b270566-205d-48f8-8b3c-3f9e339887e6.gif)

Found in Branch
stabilization2205 installer

**Comment by jckand-amzn** [comment]
The flashing no longer occurs on development@ 64c947064d3765907dbffec4ccc53ed57c809211 even with the debug draw on. Closing out.
