### ISSUE TITLE
Non-Windows Platform Unit Tests

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#899]
Build and unit testing in pipeline jobs for Linux, Mac, iOS, Android, and Linux Server. This provides criteria and information for the development workflow and pull request acceptance.

**Comment by Kadino** [comment]
Appears to not be a SIG-Testing request, please clarify if there are requests to extend the test tooling to support more platforms. If the requests are for expanding the build pipeline, such as running existing tests on additional supported platforms, assign to SIG-Build.

**Comment by byrcolin** [comment]
This issue is probably more for sig-testing however this is old and no longer the case. closing.
