### ISSUE TITLE
Level load readiness signal for testing

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#8992]
**Is your feature request related to a problem? Please describe.**
The lack of a reliable level load / test-readiness signal results in most tests relying on blindly waiting for in hope that the level will idle. This can be seen in https://github.com/o3de/o3de/blob/6ed9dc74766af825a8b8a3972fbb76b6ffcc6d3d/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py#L96

This is not only inefficient, it cannot assure readiness in the case where level load takes longer than expected.

**Describe the solution you'd like**
Level load (which can result in iteratively streaming in additional content) provides a signal, callback, or promise mechanism to eliminate blind waits. Ideally this readiness signal is available in both the Editor as well as in Launchers. This will require editor (or test framework) logging that clarifies whether the level loaded, however the logging should not be the primary (or only) readiness signal.

**Describe alternatives you've considered**
Tests can be required to solely rely on setting up levels during execution, and not on loading prebuilt levels.

**Additional context**
* Pain from this inefficiency will significantly increase as more tests load levels.
* This mechanism may require architectural input from sig-core and sig-testing, and may be relevant to sig-content for use in scripting and gameplay.

**Comment by Kadino** [comment]
Moving to a feature request of SIG-Core

**Comment by amzn-pratikpa** [comment]
@carlitosan - is the level load signal bound to scripting yet?

**Comment by lumberyard-employee-dm** [comment]
There is an OnGameEntitiesStarted event that can be used to listen for a level load via the Behavior Context: https://github.com/o3de/o3de/blob/development/Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp#L310-L311

**Comment by amzn-pratikpa** [comment]
@carlitosan Please see above - we need more information

**Comment by carlitosan** [comment]
Agreed, that is all that is necessary.
