### ISSUE TITLE
Prefabs: ScriptCanvas graphs created using the spawnables API before Lua integration changes no longer open

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#8994]
**Describe the bug**
ScriptCanvas graphs using the spawnables API before Lua integration changes no longer open in the ScriptCanvas Editor. Opening the graphs requires manual changes to the ScriptCanvas JSON file. Even after the manual changes are made, the script may not run as expected, and can cause an Editor crash. This applies only to scripts created in development or stabilization after the 2111 release.

**Prerequisites**
1. Editor is configured and built to launch AutomatedTesting.
2. The attached level is downloaded and unzipped to AutomatedTesting/Levels:
[SpawnablesStabToDev.zip](https://github.com/o3de/o3de/files/8507219/SpawnablesStabToDev.zip)

**Steps to reproduce**
1. Launch the Editor and open the SpawnablesStabToDev level.
2. Note the Spawner entity's ScriptCanvas component (prior to spawnables API changes, the SimpleSpawnDespawn.scriptcanvas file was assigned)
3. Open ScriptCanvas, and then click File > Open and open the SimpleSpawnDespawn.scriptcanvas file.

**Expected behavior**
Previously saved graphs are still able to be opened in ScriptCanvas.

**Actual behavior**
Graph no longer opens, and presents the user with an Invalid Source File error:

```
'D:/GitHub/o3de/AutomatedTesting/Levels/SpawnablesStabToDev/SimpleSpawnDespawn.scriptcanvas' failed to load properly.
Failure: XML and JSON load attempts failed: Unable to find type id with the provided string. '/m_scriptCanvas/Components/Component_[15361467309603179796]/m_variableData/m_nameVariableMap/0/Datum' 
DatumSerializer::Load failed to load the AZ TypeId of the value '/m_scriptCanvas/Components/Component_[15361467309603179796]/m_variableData/m_nameVariableMap/0/Datum' 
Loading of element has failed. '/m_scriptCanvas/Components/Component_[15361467309603179796]/m_variableData/m_nameVariableMap/0/Datum' 
Failed to read value for associative container. '/m_scriptCanvas/Components/Component_[15361467309603179796]/m_variableData/m_nameVariableMap/0' 
Loading of element has failed. '/m_scriptCanvas/Components/Component_[15361467309603179796]/m_variableData/m_nameVariableMap' 
Loading of element has failed. '/m_scriptCanvas/Components/Component_[15361467309603179796]/m_variableData' 
Failed to read value for associative container. '/m_scriptCanvas/Components/Component_[15361467309603179796]' 
Failed to load entity information. '/m_scriptCanvas' 
Failed to read data for smart pointer. '/m_scriptCanvas' 
Loading of element has failed. '/m_scriptCanvas' 
```

**Assets required**
See level file linked in Prerequisites

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82226555/163868956-2d9d656c-e92e-47eb-9f58-b6cdf835f804.png)

**Found in Branch**
development@6ed9dc74766af825a8b8a3972fbb76b6ffcc6d3d

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by srikappa-amzn** [comment]
This PR will provide a workaround: https://github.com/o3de/o3de/pull/9492

**Comment by chiyenteng** [comment]
Resolved by https://github.com/o3de/o3de/pull/9492
