### ISSUE TITLE
Script Canvas "+" Not showing up in search field.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#9036]
**Describe the bug**
In script canvas if you type "+" in the search field it does not show the node Add (+) although that node has the character in it.

**Steps to reproduce**
1. Go to Script Canvas Editor
2. Click on Search Field or Right Mouse Click in open area
3. Type "+"
4. No Add (+) node shows up
5. See error

**Expected behavior**
When I type a "+" I should be shown the Add (+) node and any others that may come with a + in the name.

**Actual behavior**
When I type a "+" no nodes are visible to choose from.

**Assets required**
N/A

**Screenshots/Video**
N/A

**Found in Branch**
Developer Branch from 4/16/22

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
N/A

**Comment by onecent1101** [comment]
Looks like escape character issue
