### ISSUE TITLE
[Material]After setting the base color texture UV mode to Tiled, the effect of the texture after the model is scaled is not taken into account

### ISSUE THREAD

**Issue by liukaikai-g** [o3de/o3de#9063]
**Describe the bug**
After setting the base color texture UV mode to tiled, the effect of the texture after the model is scaled is not taken into account.
After scaling the model, the UV mode actual becomes unwrapped.

**Steps to reproduce**
1. Create an entity and assign a material to it.
2. Set Material base color map and set the texture UV mode to tiled.
3. Double the length of the model by non-uniform  scale

**Expected behavior**
Expected effect
![image](https://user-images.githubusercontent.com/55627654/164358838-c748f878-9bb1-490e-be29-a4469b13deaa.png)

**Actual behavior**
Actual effect
![image](https://user-images.githubusercontent.com/55627654/164358893-20e05475-841f-40c4-9f8e-a3d6b90d0015.png)

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel(R)_Xeon(R)_W-2245
 - GPU NVIDIA Quadro RTX 4000
 - Memory 32GB

**Additional context**

**Comment by gadams3** [comment]
@liukaikai-g Could you please provide the assets used to test this? Which material type was used? Assuming standard PBR, after changing the UV mode to tiling, were the UV transform tiling properties updated for the number of times you wanted the texture to be tiled? They can be found near the bottom of the material property inspector under the UVs section.

**Comment by liukaikai-g** [comment]
Thanks, this material property solved my problem
