### ISSUE TITLE
Fbx Settings: When the User opens .fbx file and selects some of the root nodes the Engine crashes

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#9065]
**Describe the bug**
After opening an .fbx file and selecting specific root nodes the Engine crashes. Here is a list of root nodes examples with .fbx files that cause the crash:

-  BeveledCone.fbx - Default
-  ReflectionProbeSphere.fbx - Reflected Probe
-  Shaderball.fbx - blinn1
-  _Sphere_1x1.fbx - map1, lambert3
-  groundplane_512x512m.fbx - map1

**Steps to reproduce**
Steps to reproduce the behavior
1. Go to Edit > Editor Settings > Global Preferences.
2. In the search bar type Scene Inspector.
3. Enable Scene Inspector.
4. Go to Tools > Asset Browser.
5. In the search bar search for any .fbx file from the list above the steps.
6. Double click LMB on the file.
7. Go to Help > Inspect.
8. Select any root node from the above list in the description.

**Expected behavior**
The Editor remains stable.

**Actual behavior**
The Editor crashes.

**Video**

https://user-images.githubusercontent.com/100559077/164409487-7c10921c-8354-4dc5-8b71-5abc109e520f.mp4

**Found in Branch**
Stabilization_2205 (651a5a3)
Development (c56c04d)

**Desktop:**

- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Attachments:**

[Editor.log](https://github.com/o3de/o3de/files/8528974/Editor.log)
[error.log](https://github.com/o3de/o3de/files/8528975/error.log)
[error.zip](https://github.com/o3de/o3de/files/8528989/error.zip)

**Comment by AMZN-daimini** [comment]
Building stabilization to try and repro this.

**Comment by AMZN-daimini** [comment]
Got a repro.
![image](https://user-images.githubusercontent.com/82231674/164522578-e37159b4-0cb0-4739-a7a3-a9721dd37afd.png)

If it's simple enough I will try and get a quick fix going, else I'll redirect to the appropriate feature :)

**Comment by AMZN-daimini** [comment]
Not sure why merging the issue did not close this, but the fix is now in the stabilization branch!

**Comment by LB-BartoszCwiek** [comment]
Verified the issue does not occur in Stabilization_2205 (ddedb53) branch.
