### ISSUE TITLE
Building a project on Windows with a name that contains 44 characters or more results in error

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#9068]
**Describe the bug**
In the log file the error states that the 260 character path limit was exceeded, but the path highlighted in the attached screenshot consists of 153 characters. Additionally, the path which consists of 151 characters is working properly. Issue does not occur on Linux.

**Steps to reproduce**
1. Go to Project Manager.
2. Select New Project > Add New Project.
3. Name the project with minimum 44 characters.
4. Build the project.

**Expected behavior**
Project is built properly.

**Actual behavior**
Building project with the name that has 44 characters or more results in error.

**Screenshot:**
![LongPath](https://user-images.githubusercontent.com/87059746/164444923-2767f078-14f2-4356-bd5d-c8001d3a9ac0.png)

**Video:**

https://user-images.githubusercontent.com/100559077/164451519-fb8c523c-a9d9-44a7-845c-10d1e1d14ea3.mp4

**Found in Branch**
Stabilization_2205 (651a5a3)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Attachments**
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/8530555/CMakeProjectBuildError.log)

**Comment by amzn-pratikpa** [comment]
This is a hard limit in the OS that we can't do anything about. We use a number of 3rd party libraries that have a hard coded MAX_PATH which cannot be changed.
