### ISSUE TITLE
Editor hangs or crashes when hitting a breakpoint when debugging through LuaIDE

### ISSUE THREAD

**Issue by robhaco** [o3de/o3de#9075]
**Describe the bug**
If the user sets a breakpoint in the LuaIDE and runs game mode in the Editor, the Editor becomes unresponsive and often crashes, even after attempting to continue past the breakpoint.

**Steps to reproduce**
1. Launch the Editor
2. Create a new level
3. Create a new Entity
4. Add the Lua component
5. Assign an existing lua script or create a new one
6. Within the LuaIDE, connect to the Editor as the target
7. Assign a breakpoint in the selected or created script
8. In the Editor, enter Game Mode

**Expected behavior**
The Editor regains functionality after continuing past a breakpoint

**Actual behavior**
The Editor hangs and often crashes after hitting a breakpoint, despite continuing from the LuaIDE

**Found in Branch**
Development@ddf5800c2b

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10

**Comment by robhaco** [comment]
Confirmed the hang issue existed prior to Rajiv's changes related to gridhub/mate deprecation.

**Comment by galibzon** [comment]
I'm getting the same problem. Can not debug Lua code anymore.

**Comment by monroegm** [comment]
Per @robhaco removing SIG-Network

**Comment by lmbr-pip** [comment]
@robhaco  do you have logs for this?

**Comment by galibzon** [comment]
I debugged a little bit this past Monday, and found that the LuaIDE is sending messages everytime I click "Step Over". I placed a breakpoint in the Editor and nothing arrives. Interestingly, I noticed that when hitting the breakpoint there are events being sent between Editor and LuaIDE. But once you click "Step Over" then the exchange stops and LuaIDE is just there waiting to hear back from the Editor.

**Comment by GraphiteSIX** [comment]
I repo'd this first time but thought I would provide some dumps via procdump of the editor and LuaIDE.
Produced on development commit https://github.com/o3de/o3de/commit/917aba465b2390a5a52fc8413e0ffd86a7db7e1d
[Proc_dump.zip](https://github.com/o3de/o3de/files/8834910/Proc_dump.zip)

**Comment by allisaurus** [comment]
I've been poking at this and don't have a fix yet, but wanted to record some debugging observations here in case they flip on a light bulb for anyone else:

* The Editor gets stuck in this `while` loop [here](https://github.com/o3de/o3de/blob/development/Code/Framework/AzFramework/AzFramework/Script/ScriptRemoteDebugging.cpp#L424) (repros observation by @lsemp3d )
* `TargetManagementComponent::DispatchMessages` never sees any messages to process (so m_executionState never gets flipped back to SDA_STATE_RUNNING), even though the "StepOver" event _is_ firing when clicked from the Lua IDE
* messages _are_ getting processed from `m_outbox` on [TickThread](https://github.com/o3de/o3de/blob/development/Code/Framework/AzFramework/AzFramework/TargetManagement/TargetManagementComponent.cpp#L678), so presumably the Editor should see something? (but doesn't)

... from there it gets harder to debug deeper into specific events across the diff threads (and my Visual Studio-fu is lacking), but following the "Editor" `StepOver` event through to processing across the TCP socket is the next step to verify it's actually getting fired.

**Comment by GraphiteSIX** [comment]
@allisaurus Another issue but don't know if there connected
1.) Start a new level.
2.) Create a new entity
3.) Add Rot.lua script
4.) Check it works
5.) Swap script with Check.lua
6.) Observe error

The scripts are the same apart from a variable changed.
[Lua_IDE_File_Swap_Bug.zip](https://github.com/o3de/o3de/files/8864301/Lua_IDE_File_Swap_Bug.zip)

**Comment by AMZN-puvvadar** [comment]
I've managed to diagnose the error to this while loop: https://github.com/o3de/o3de/blob/development/Code/Framework/AzFramework/AzFramework/Script/ScriptRemoteDebugging.cpp#L424-L429

Presently this loop does not exit without receiving a continue breakpoint message. This loop has the side effect of stalling out all Ticks (including SystemTick) so that no network traffic is ever received. I'll look into a more effective way of handling this.

**Comment by galibzon** [comment]
I took latest "development" branch, as of this morning, and cherry-picked this PR into it:
https://github.com/o3de/o3de/pull/10132  
Loaded AutomatedTesting. Upon entering a breakpoint only "Run/Continue" option works (an improvement).
Unfortunately both "Step Over" and "Step In" don't work, but this time around they open a `LUADockWidget` tab, along with a large animated and semi-transparent progress bar saying "Loading". Here is a picture oh how it looks:
![image](https://user-images.githubusercontent.com/66021303/173827604-bcfc8c19-eb50-4895-829d-86b3a5e6b675.png)

**Comment by AMZN-puvvadar** [comment]
That seems to have nothing to do with the network layer as it turns out. It's likely pre-existing. What's happening here is the implicit breakpoint generated to handle Steps are searching for their target file by lua vs luac which is failing Asset lookup. Unsure when or why that became the case but I added a quick and dirty catch to https://github.com/o3de/o3de/pull/10132 to handle it.

**Comment by galibzon** [comment]
Validated the new version of the PR and it works! Thanks a lot @AMZN-puvvadar .
