### ISSUE TITLE
Mouse Input When Game Is Maximized is Different Than Editor View.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#9087]
**Describe the bug**
Using Script canvas when setting up an input handler to rotate node you use the held pin and in game the object this script is on will rotate when the mouse is moved on the x axis, if you go into maximized mode it only picks up the input one in a while, but if you use the Pressed pin from Input Handler the maximized mode works the same as the editor player.

**Steps to reproduce**
1. Go to Script Canvas and create a graph with Input Handler into a From Values (Vector3) and out to a Rotate node. 
2. Click on The entity you will be adding this script to, and add the script you just created with an input bindings with the same input for Mouse X
3. Play the game in editor view and the object should rotate each way depending on which way your mouse is moving.
4. Play in Maximized mode and it will no longer work correctly until you use the pressed pin not the held pin in script canvas.
5. See error

**Expected behavior**
With the Held pin your object should rotate in both maximized and normal play mode.

**Actual behavior**
The object will only rotate in one mode or the other unless you set both pins Pressed, and Held into the same create values node.

**Assets required**
N/A

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Dev Branch 4/16/22

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
N/A

**Comment by monroegm** [comment]
@amzn-jillich mentioned this may be by design CC: @lsemp3d @carlitosan,

**Comment by ParasiteSt** [comment]
I gave this another go after a few months and the issue no longer occurs. If you try to use Pressed and not Held for the Input handler on either Maximized or Viewport runtime it does not work and you must use Held now going forward for both which makes the most sense and fixes the difference between the two.
