### ISSUE TITLE
Create a project which enabled Script Canvas Gem, first open the editor failed

### ISSUE THREAD

**Issue by Hsuehnj** [o3de/o3de#9088]
**Describe the bug**
Create a project with Mini Template, then enable Script Canvas Gem of the project, build project, open the editor, the project stays at “Loading Plugins” state.

**Steps to reproduce**
1. Create a project with Mini Template
2.  Enable Script Canvas Gem of the project, build project
3. Open the editor

**Expected behavior**
The editor can be opened successfully.

**Actual behavior**
 The project stays at “Loading Plugins” state. 

**Assets required**
N/A

**Screenshots/Video**

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
Device: PC
OS: Windows
Version 10
CPU Intel xeon
GPU NVidia RTX 5000
Memory 128GB

**Additional context**
Add any other context about the problem here
[callstack.txt](https://github.com/o3de/o3de/files/8536224/callstack.txt)
.

**Comment by FuzzyCarterAWS** [comment]
I've been unable to repro this using both SDK buildspec and Editor buildspec processes.

**Comment by FuzzyCarterAWS** [comment]
Closing as no repro
