### ISSUE TITLE
[linux] add support for launching an image diff viewer on linux in AtomSampleViewer

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#9119]
[Migrated from JIRA ATOM-17541]
Description:Currently ASV doesn't try on linux because the run diff tool function just returns fals.

 
{code:java}
        bool RunDiffTool(const AZStd::string& filePathA, 
                         const AZStd::string& filePathB)
        {
            return false;
        }
{code}
Details:

Acceptance Criteria:

Additional Information:

**Comment by galibzon** [comment]
The plan is to move all these image diff based tests to AutomatedTesting
