### ISSUE TITLE
[Transform]Drag some models into the scene, and add various components to them. You will find that except for X, Y, and Z of Transform, you can manually input values. Other input boxes cannot manually input values. You can only change the value by clicking the arrow on the right side of the input box.

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#9139]
**Describe the bug**
Drag some models into the scene, and add various components to them. You will find that except for X, Y, and Z of Transform, you can manually input values. Other input boxes cannot manually input values. You can only change the value by clicking the arrow on the right side of the input box.

**Steps to reproduce**
1. Create a new level, drag the character model into the scene
2. Add any component with an input value box to the model
3. Enter the value in the input box
4. Scroll down to '...'
5. See error

**Expected behavior**
Can be entered manually

**Actual behavior**
Can not be entered manually

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by monroegm** [comment]
@sysuNie To reproduce this, does it require an actor and a simple motion/anim graph component? Also, if you could provide a video that would be helpful

**Comment by rainbj** [comment]
UX reviewed agreed with @monroegm we need more info to proceed
