### ISSUE TITLE
[camera system] "Find in Viewport" more than 2 times between two entities will make the camera angle of view abnormal

### ISSUE THREAD

**Issue by fufushang** [o3de/o3de#9151]
Describe the bug
 In prefab mode, focusing more than 2 times between two entities will make the camera angle of view abnormal

Steps to reproduce

1. Open the test scene (you can directly use the newly created default scene)
2. Entity sun (0, 0, 13.4), entity shader ball (0, 0, 0)
3. Right-click the entity and select 'find in viewport' (or press the 'Z' key) to switch back and forth between the sun and the shader ball at least 3 times
4. Move and rotate the camera to see if the camera angle is displayed normally

Expected behavior
Ability to move and rotate the camera angle normally

Actual behavior
Unable to adjust camera angle to normal angle by moving and turning

Assets required
Provide sample assets needed to reproduce the issue.

Screenshots/Video

Found in Branch

Desktop/Device (please complete the following information):
Device: PC
OS: Windows
Version 10
CPU Intel xeon
GPU NVidia RTX 5000
Memory 128GB

Additional context

**Comment by fufushang** [comment]
![image1](https://user-images.githubusercontent.com/7249380/165015469-2b34534c-f112-4011-9234-ce8ce3d214d4.png)
![image2](https://user-images.githubusercontent.com/7249380/165015472-030a02a2-7a15-4c28-b8a8-5c9c0da02119.png)
![image3](https://user-images.githubusercontent.com/7249380/165015490-78ef9a56-eccb-4266-85da-9b24a39be0da.png)

**Comment by hultonha** [comment]
Fixed by https://github.com/o3de/o3de/pull/15362
