### ISSUE TITLE
ui canvas not usable with terrain.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#9153]
**Describe the bug**
Once you add a terrain world, and terrain renderer to your level.prefab, any ui canvases you are using become useless since they do not activate or render.

**Steps to reproduce**
1. Add a ui canvas reference component to an entity and set load automatically.
2. Check to make sure it does load automatically once you play game.
3. Select your root level entity in the entity outliner
4. Add two components, the Terrain World Renderer, and Terrain World
5. Click play game again, and the ui canvas will no longer render or load automatically.

**Expected behavior**
The ui canvas should load with or without a terrain world being rendered, and should not break once one is added.

**Actual behavior**
The ui canvas will no longer activate, even once the Terrain World components are removed.

**Assets required**
Terrain Gem

**Screenshots/Video**
N/A

**Found in Branch**
Dev Branch

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
N/A

**Comment by AMZN-alexpete** [comment]
I"ve verified that this issue is fixed by the following PR that has been merged to development https://github.com/o3de/o3de/pull/8946
