### ISSUE TITLE
Re-enable the Editor_LayerEntity_Works Python Editor auto test

### ISSUE THREAD

**Issue by jackalbe** [o3de/o3de#9190]
**Is your feature request related to a problem? Please describe.**
The automated tests for the Python hooks in the Editor need to be updated to properly regress Editor automation API.

**Describe the solution you'd like**
the pytest AutomatedTesting/Gem/PythonTests/EditorPythonBindings/TestSuite_Periodic.py should enable the Editor_LayerEntity_Works test

**Additional context**
log shows "Exception: [FAIL] layer was not created : FAILED" when it attempts the layer API

**Comment by monroegm** [comment]
We don't have layer support in O3DE is the test necessary? Can it be removed.
