### ISSUE TITLE
Feature Request: Deleting history should not be required for Actor export from Maya.

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de#9191]
In the Actor workflow evaluation (WF3) the user notes that it's required to delete history when exporting actors from Maya as FBX so they can be processed without issue. If history is not deleted, the skinweights are incorrect in O3DE. Requesting that the Asset Pipeline handle FBX files with history better and not require the user to delete history.

**Comment by rainbj** [comment]
If anything comes up inside O3DE regarding UX about deleting history or new workflows around how we are managing the new import process please into conversation

**Comment by hultonha** [comment]
Tagging @amzn-rhhong - @amzn-jillich mentioned that this issue may already be resolved, would you please be able to verify this if so? Thanks!

**Comment by amzn-rhhong** [comment]
@shawstar I talked with Starr offline. This issue is caused by turning on/off the SubD mesh option on DCC tool. I don't believe there is anything we can act on in the engine side.

**Comment by lmbr-pip** [comment]
@shawstar Is this covered by other work ie DCC plugins to aid export O3DE? During recent game building efforts folks were still running into issues with history not being cleared. While we can cover this with documentation, I thought there were other efforts to address this, but I don't see links in this story.

**Comment by shawstar** [comment]
The next update to this tool that is now in PR will help users export Animation with the proper settings as well warn them if there are issues with the transforms etc. However, this tool is only for Blender at the moment. We still need to work on a tool for Maya. https://github.com/o3de/o3de/tree/development/Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter @lmbr-pip
