### ISSUE TITLE
Terrain Height Query Resolution exposed in script canvas.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#9219]
**Is your feature request related to a problem? Please describe.**
Yes, the terrain when going into runtime runs relatively smoothly for how new it is, but the PhysX collision makes everything bog down and is too slow to work with when working on large terrains, if the Terrain Height Query can be exposed in script canvas it could allow for changing the resolution at runtime to help performance while developing.

**Describe the solution you'd like**
Script canvas has the Terrain Height Query Resolution exposed in a node.

**Describe alternatives you've considered**
Changing it in the components settings, but this does not allow for the end product resolution while testing certain locations of the terrain.

**Additional context**
N/A

**Comment by rainbj** [comment]
Is the final state going to be a node that will allow you to query the results? (Input/Output). Can we review this component/ node when work is complete. Thanks

**Comment by ParasiteSt** [comment]
I am going to close this Feature Request, as the terrain has come a long way, and the main reason for this new feature was to save time while developing with the terrain, but with where the terrain is at right now, and most likely moving forward having this new node would not be needed, and most likely ignored.
