### ISSUE TITLE
[Planning] Get to know your Stakeholders

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#9233]
Welcome to O3DE Release Management!

Below is a list of Stakeholders you may need to interact with while running an O3DE release. The specific SIG you will interact with for each GHI issue is listed in the issue, but here is a summary:

* Royal O'Brian (@OBWANDO) - The Linux Foundation (LF) GM that can connect you, as needed, with representatives from LF Legal (e.g. Scott Nicholas), and Security
* Docs-Community SIG - Responsible for release notes and any community requirements associated with the release (e.g. tutorials, demos, etc.)
* O3DE Marketing Committee 
  * @Nicole Huesman [LF] - Responsible for any marketing requirements associated with the release. (e.g. blogs, social media posts, etc.).
  * @Khalil (LF) responsible for website updates
* Build SIG - Responsible for installers, and CMake updates.
* Release SIG - Responsible for just about everything else.

There are many options for interacting with these stakeholders, including: (1) assigning issues to them in the O3DE or SIG repos, (2) communicating via. Discord, and (3) attending the recurring SIG meetings to discuss agenda topics. The method you use will vary by SIG. To help you, the contact information for each SIG is included in each release task in this project.

**Comment by tonybalandiuk** [comment]
1. Overall Release
	1. On Track/Green
	2. Feature list posted.
	3. Release notes: In progress
	
2. SIG-Docs Community  (Stephen, Finchy)
	1. Identify any launch blocking requirements https://github.com/o3de/o3de/issues/9268
	    - none
	2. . Any non-launch blocking requirements https://github.com/o3de/o3de/issues/9273
	   - Motion Matching blog - authoring and posting 
	   - Discord, Github, Reddit? announcement
	   - Any title/release art? Joe - No.  Nicole - would be good to have a release name in the future. Tony - see  https://github.com/o3de/sig-release/issues/20 and https://github.com/o3de/sig-release/issues/39 for the previous naming discussions
	
3. Marketing  (Nicole)
	1. Identify any launch blocking requirements https://github.com/o3de/o3de/issues/9253
	  - none
	
	2. Any non-launch blocking requirements (no GHI)
	- O3DF, O3DE Website Updates - Khahil
	    - on track, designer will work this weekend. Question about colors for the project - per Nicole, there's 3 colors: o3df foundation (green), project and o3de.org (blue), O3DCon event (purple)
	    - Khahil to schedule a review of the website hopefully next week of 5/2
	- Blogs (released over a period of time, not all at once)
	    - Overview blog
	    - Features and capabilities blog
	    - motion matching blog
	    - 2 other blogs
	 - Social
	    - Twitter
	    - Facebook
	    - Linked In
	    - Reddit
	    - Discord
	  - Video content
	      - sizzle reel 
              - Multiplayer demo - @Ulrick28 , docs team

4. Operations - merging the codebase (Chris)
5. Operation - release tagging (Mike)


Other
In the future, a blog around releases and stabilization process

**Comment by amzn-changml** [comment]
Something brought up by @Ulrick28: We may want to update the logo and any other branding on the O3DE Github org along with the release. The timing can follow the operational steps. I can followup with Khahil on the actual files needed for the update.

**Comment by tonybalandiuk** [comment]
captured Marketing non-launch-blocking issues under #9392
captured Marketing website changes under #9253 
captured sig-docs-community launch blocking issues under #9268 
captured sig-docs-community non-launch-blocking issues under #9273 
operations tasks will be captured under #9255
