### ISSUE TITLE
Script Canvas graph which contains an AZ::Event node increases its size significantly every time the script is reopened and saved in Script Canvas  

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#9243]
**Describe the bug**
The AZ::Event node in Script Canvas graph file contains a list of _m_parameterSlotIds_ under _m_azEventEntry_. Values inside this list are duplicated every time the graph is reopened and saved in Script Canvas, even when no changes were made to the graph.

This results in the massive increase in the .scriptcanvas file size. After the graph is reopened and saved multiple times, the User may end up with a .scriptcanvas file which weighs over 500MB and contains millions of values under the _m_parameterSlotIds_.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Open Script Canvas.
2. Create a new graph which contains an AZ::Event node (refer to the attached screenshot for an example).
3. Save the graph.
4. Open the .scriptcanvas file in a text editor and navigate to the line which contains _m_parameterSlotIds_ under _m_azEventEntry_.
5. Return to Script Canvas and close the graph.
6. Reopen the graph.
7. Save the graph.
8. Return to the .scriptcanvas file and observe the values under _m_parameterSlotIds_.

**Expected behavior**
The values under _m_parameterSlotIds_ are not duplicated every time the graph is reopened and saved.

**Actual behavior**
The values under _m_parameterSlotIds_ are duplicated every time the graph is reopened and saved which increases the file size significantly.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/86953108/165755721-7a561e72-3b19-4ecf-ac60-fca358bda2ef.png)

https://user-images.githubusercontent.com/86953108/165755746-e1e08830-2d0e-4d62-ac2d-57d5f2b66736.mp4

![image](https://user-images.githubusercontent.com/86953108/165756943-a3f3683f-fbe0-4406-970e-21c2250f0db8.png)

**Found in Branch**
Stabilization_2205 (c9e6799)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600
 - GPU: Nvidia RTX 2060 SUPER
 - Memory: 16GB

**Comment by carlitosan** [comment]
Fixed by #9393 and #9407

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed in Stabilization_2205 (32e9143).
