### ISSUE TITLE
[Pre Release] Ensure PR is created for applying the generated API reference to the docs site

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#9256]
Ensure the Docs-Community SIG creates a PR for applying the generated API reference to the docs site.

Replace the [PR] placeholder in the below successor task with the correct information for this release.
- Successor Task: #9255

Discord: [#sig-docs-community](https://discord.gg/FxmvF5x8)
SIG Docs-Community meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
SIG Docs-Community agendas: [GHI](https://github.com/o3de/community/issues)

**Comment by tonybalandiuk** [comment]
Micron will handle this

**Comment by micronAMZN** [comment]
https://github.com/o3de/o3de/issues/9256

**Comment by tonybalandiuk** [comment]
resolved by https://github.com/o3de/o3de.org/pull/1605
