### ISSUE TITLE
[Pre Release] Ensure PRs are created for branch merge

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#9258]
Ensure the Release SIG creates PRs for the final merge from the stabilization branch to main for each of the following repos:
- o3de
- o3de-atomtest
- o3de-atom-sampleviewer
- o3de-multiplayersample
- o3de-netsoaktest

Replace the [PR] placeholders in the below successor task with the correct information for this release.
- Successor Task: #9255

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by cgalvan** [comment]
The PRs have been created and I've updated the successor task with the PR links accordingly.
