### ISSUE TITLE
[Pre Release] Ensure installers are uploaded to S3

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#9259]
Ensure the Build SIG uploads the installers for Windows and Linux  to the below S3 buckets:

Windows s3://o3de-prism-prod-us-west-2/main/Latest/Windows/

Linux s3://o3de-prism-prod-us-west-2/main/Latest/Linux/

- Predecessor task: #9260 

Discord: [#sig-build](https://discord.com/channels/805939474655346758/816043576034328636)
Build SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Build SIG meeting agendas: [GHI](https://github.com/o3de/sig-build/issues)

**Comment by tonybalandiuk** [comment]
installers have been tested. Ok to upload to S3

**Comment by amzn-changml** [comment]
Installers uploaded to the main/Latest/ bucket
