### ISSUE TITLE
[Pre Release] Ensure installers are created

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#9261]
Ensure the Build SIG creates the signed installers for Windows and Linux in preparation for testing.

- Successor task: #9260

Discord: [#sig-build](https://discord.com/channels/805939474655346758/816043576034328636)
Build SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Build SIG meeting agendas: [GHI](https://github.com/o3de/sig-build/issues)

**Comment by amzn-changml** [comment]
The latest versions of the stabilization installers can be found here, as of a073665f466701bd946c9366b569e0e32a63c550

https://o3debinaries.org/stabilization-2205/Latest/Windows/o3de_installer.exe
https://o3debinaries.org/stabilization-2205/Latest/Linux/O3DE_latest.deb

When promoted, they will be copied to the main folder under their respective 2205_0 version numbers

**Comment by AMZN-Dk** [comment]
Confirmed that I can download using those links, will run tests overnight.

**Comment by tonybalandiuk** [comment]
closing this since downloading is confirmed.
