### ISSUE TITLE
[Pre Release] Ensure version number updates to CMake parameters are complete

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#9262]
Ensure the Build SIG updates CMake parameters with the new version number.

- Successor task: #9260

Discord: [#sig-build](https://discord.com/channels/805939474655346758/816043576034328636)
Build SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Build SIG meeting agendas: [GHI](https://github.com/o3de/sig-build/issues)

**Comment by amzn-changml** [comment]
The cmake parameters are configured for the stabilization/2205 branch installer with the following:

```
O3DE_VERSION = 22.05.0
O3DE_BUILD_VERSION = 2205.0
```
