### ISSUE TITLE
[Pre Release] Ensure final release notes are documented, and a PR is created

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#9263]
Ensure the Release SIG documents the final customer-facing release notes in preparation for release (using the draft release contents as input), and creates a PR to have the release notes merged on launch day.

Replace the [PR] placeholder in the below successor task with the correct information for this release.
- Successor Task: #9255

- Predecessor Task: release contents drafted

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by tonybalandiuk** [comment]
micron will own the PR for this

**Comment by micronAMZN** [comment]
https://github.com/o3de/o3de.org/pull/1607
