### ISSUE TITLE
[Pre Release] Confirm release branch is stable

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#9265]
Ensure the Release SIG has completed all testing requirements, and has confirmed the release branch is stable and meets the quality bar for what is expected in a release. Also verify all exception requests (i.e. any requests to merge to stabilization post code lock) are merged per the Exception Request Dashboard. Ensure the exact commit id to be used for the merge to main is noted as a comment in this issue.

- Related Task: #9235 

Discord: [#sig-release](https://discord.gg/ne59x9bc)
Release SIG meetings: [O3DE Calendar](https://lists.o3de.org/g/o3de-calendar/calendar)
Release SIG meeting agendas: [GHI](https://github.com/o3de/sig-release/issues)

**Comment by AMZN-Dk** [comment]
All testing and planned issue fixes have been confirmed, closing this as the release branch is stable.
