### ISSUE TITLE
[Pre Release] Ensure version number updates to o3de.org are staged (Required for Major Releases Only)

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#9267]
Ensure the O3DE marketing-committee stages the version number updates to the [o3de.org download page](https://www.o3de.org/download/) in advance of the release. Note: This is required for Major Releases Only, and is not needed for point releases.

- Successor Task: #9255

**Comment by tonybalandiuk** [comment]
this is something khahil will do

**Comment by theheels** [comment]
Confirmed, I am on this with the developer making changes.

**Comment by theheels** [comment]
@tonybalandiuk We just got a note back: Regarding, [o3debinaries.org](http://o3debinaries.org/). We don't seem to have access to change that. Doing some quick investigation, looking at the header response for https://o3debinaries.org/, I see references to Cloudfront. Is this in a different repo?

**Comment by amzn-changml** [comment]
o3debinaries.org is on a different repo, hosted on a O3DE controlled AWS account. I'm looking into doing work post release to expose this repo and automation for other members to push changes

**Comment by tonybalandiuk** [comment]
The update to o3debinaries.org is being tracked under a separate issue #9254

**Comment by tonybalandiuk** [comment]
The version update for o3de.org (this GHI) are encompassed by this PR -> https://github.com/o3de/o3de.org/pull/1626 Closing this issue.
