### ISSUE TITLE
Viewport Camera Speed does not affect mouse wheel scrolling.

### ISSUE THREAD

**Issue by SWMasterson** [o3de/o3de#9277]
**Describe the bug**
Viewport camera speed only affects movement of the camera via the WASD keys, and does not affect the distance moved with the mouse wheel. Users find that this causes the mouse wheel scrolling to be disorienting and difficult to use.

**Steps to reproduce**
1. Open Viewport Camera Settings (camera icon at the top right of the viewport)
2. Adjust the Camera Speed setting to a low value (1.0)
3. Move the camera with the WASD keys within the viewport.
4. Zoom in and out with the mouse wheel.

**Expected behavior**
Mouse wheel zooming should be affected similarly to the camera movement speed.

**Actual behavior**
Mouse wheel zooming is unaffected, which is very jarring when there is a large discrepency between camera movement speed and the distance covered by mouse wheel scrolling.

**Found in Branch**
WTE5

**Comment by hultonha** [comment]
Dropping to major as this is not a critical issue but would be a very nice to have fix

**Comment by hultonha** [comment]
Fixed by https://github.com/o3de/o3de/pull/12882
