### ISSUE TITLE
ServerLauncher does not load on starting the Game Mode, until the Editor is focused first

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#9300]
**Describe the bug**
If the ServerLauncher is launched via entering the Game Mode in the Editor, its window remains blank until the user clicks inside the Editor itself.

**Steps to reproduce**
1. Make sure the <ProjectName>.ServerLauncher.exe is built for the tested project, if not, then build it (e.g. for the Pre-built SDK engine and project built in the Project Manager, run the `cmake --build build/windows --target <ProjectName>.ServerLauncher --config profile` command via Command Line opened inside the project's folder).
2. Run `Editorsv_enabled true` command in the Console.
3. Enter the Game Mode.

**Expected behavior**
ServerLauncher window loads properly.

**Actual behavior**
The Editor window has to be focused (e.g. Alt+Tab to its window and left-click it) in order for the ServerLauncher to load properly.

**Video**

https://user-images.githubusercontent.com/86952082/165930417-e34c5ed8-5ba9-4cbf-afd5-1fc1cb55b245.mp4

**Found in Branch**
Stabilization_2205 (ddedb53)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by lmbr-pip** [comment]
Need help from sig-core / sig-content as this is ticking issue with window focus and not a networking issue. Please advise who should own this fix.

**Comment by lsemp3d** [comment]
Adding SIG-Simulation, please see lmbr-pip's question above

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (b7fa50e) build.
