### ISSUE TITLE
Asset failed to hot reload after importing new version of asset.  Restarting the Editor caused the model to load properly.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#9310]
**Describe the bug**
Asset failed to hot reload after importing new version of asset.  Restarting the Editor caused the model to load properly.
I notice this if there are changes like extra verts are added or removed, the change is large enough for the hot reload to need the level to be restarted to see the changes.

**Steps to reproduce**
Use the below attached assets. In o3de import SimpleSkinedMesh_with_non_deform_history_removed.fbx as an Entity.
In a DCCs tool load SimpleSkinedMesh_with_non_deform_history_removed_hotReload.fbx and export it to your o3de project and replace SimpleSkinedMesh_with_non_deform_history_removed.fbx forcing a Hot Reload Live. As shown in the video, the new asset is to complex for the Hot Reload to occur, thus forcing you to close the level and reopen the level to see updates.

**Expected behavior**
Hot Reload will work as expected, or a notification or banner in o3de editor informing you Hot Reload worked or didn't work.

**Actual behavior**
It's not clear what took place as the mesh did not refresh or sometimes disappears completely. 

**Assets required**
Sample Assets
[SimpleSkinedMesh_with_non_deform_history_removed_hotReload.zip](https://github.com/o3de/o3de/files/8592260/SimpleSkinedMesh_with_non_deform_history_removed_hotReload.zip)

**Screenshots/Video**
https://user-images.githubusercontent.com/87207603/165984755-1eeb2b60-bd34-4b03-b25b-1964e5cd8572.mp4

**Found in Branch**
Nightly 4/29/22

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I9-9900k
 - GPU NVidia RTX 2080ti
 - Memory [e.g. 16GB]

**Additional context**

**Comment by amzn-rhhong** [comment]
@shawstar I'm investigating the hot loading issue right now and it indeed pretty tricky. The animation is still playing (in fact you can check the skeleton it's still animated) but the mesh goes back to a T-pose
https://user-images.githubusercontent.com/69218254/166014303-39e3794f-42d2-45ef-a4e6-f1eaa1d79dac.mp4

FYI a better alternative workaround than 'restart the editor' is to re-assign the actor asset in the actor component.
.

**Comment by yuyihsu** [comment]
UX suggest the following solutions to address this issue:
1. Hot-reload should be triggered automatically when user makes changes to the assets in the DCC tools
2. Add a "Asset Refresh" button to the toolbar allowing users to manually trigger the hot-reload of the selected assets. After clicking on the button, a progress bar should be displayed on the bottom of the editor to show the process has been triggered. If the assets failed to be updated, an error status should be displayed on the UI, and error messages should be displayed in the console and in the asset processor.

**Comment by lmbr-pip** [comment]
1. AP should re-process source asset, so we have to look at where hot reload is failing. Assume this is on sig/simulation and animation team to dig into.
2.  This needs UI/UX treatments for where this refresh button is. Is it per Editor tool window, in the asset browser etc.

**Comment by FuzzyCarterAWS** [comment]
#9042 was closed as duplicate to this issue. Additional information found within.

**Comment by amzn-rhhong** [comment]
https://github.com/o3de/o3de/pull/9955 closing as this should resolve it.
