### ISSUE TITLE
Client disconnects from server despawning everthing in server.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#9328]
**Describe the bug**
When you disconnect a client from a server using "disconnect" in the console you disconnect like expected, but the server despawns all boxes with your player, and renders the server useless since no other client can connect to it anymore.

**Steps to reproduce**
1. Launch both a server and client from command prompt using the commands ; 
**MyGame**.ServerLauncher.exe --console-command-file=server.cfg 

**MyGame**.GameLauncher.exe --console-command-file=client.cfg

2. Run around and touch a few boxes with your player
3. disconnect your player on the client

**Expected behavior**
If I disconnect my player from the client it should disconnect my player and leave everything else in the server as is.

**Actual behavior**
Clients can disconnect removing everything from the server.

**Assets required**
Multiplayer Sample Project

**Found in Branch**
Development Branch

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Comment by ParasiteSt** [comment]
If you add two clients to a server and disconnect one with this command it does seem that the server sometimes continues to hold all the other entities and just removes the player and the server is still usable. But every time you remove all clients the server basically becomes a shell of a level with no use.

**Comment by AMZN-Olex** [comment]
This is by design. This behavior can be controlled with sv_isTransient.
```
AZ_CVAR(bool, sv_isTransient, true, nullptr, AZ::ConsoleFunctorFlags::DontReplicate, 
    "Whether a dedicated server shuts down if all existing connections disconnect.");
```
