### ISSUE TITLE
Material Editor: Incorrect Tooltip on blue arrow icon that indicates that property has been changed

### ISSUE THREAD

**Issue by NeilGitGud** [o3de/o3de#9339]
**Describe the bug**
Material Editor: Incorrect Tooltip on blue arrow icon that indicates that property has been changed. Tooltip should inform that user that it shows the value has been changed, and now differs from the source/parent material.

**Steps to reproduce**
1. Launch Material editor
2. Select any material
3. Change any value within the "Inpector" UI pane
4. Mouse over the blue arrow icon that appears

**Expected behavior**
Icon tooltip informs the user that the value has been changed, and now differs from the source/parent material.

**Actual behavior**
The tooltip for the icon is inaccurate. It appears to contain the same tooltip as the property it appears next to, and does not describe its actual function.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

![ME_blue_arrow_icon_tooltip](https://user-images.githubusercontent.com/79114701/166268001-761966a9-c107-41d9-aa4b-3e0c6f5df794.png)

**Found in Branch**
WTE5 session, using latest Stab 2205 release build

**Additional context**
Was encountered during the WTE5 session

**Comment by gadams3** [comment]
The tooltip text and its values are data driven and come directly from the material type source file. Tooltips do not reflect the state of the property value. The tooltip in this screenshot is not for the blue modified property arrow. It is for the entire row.

If the user wants to display additional information in the tooltip about the property being modified, this is a feature request and not a bug. However, it would probably be fairly quick and easy to extend the tooltip message to say that the property has been modified.

**Comment by gadams3** [comment]
Searching for AtomToolsFramework::ConvertToPropertyConfig and places that it is called in the material editor and instance inspector should provide an example and location to extend the tooltip description as values are edited.

**Comment by santorac** [comment]
Rather than updating the tooltip for the entire row, I think it would be better if a different tooltip were displayed when hovering over the arrow.

**Comment by gadams3** [comment]
There is no mechanism exposed through the reflected property editor to get access to the indicator for a given property row widget. That would probably be very easy with the document property editor that's actively being developed. It will eventually replace the RPE. I do not think it would be practical to do deep plumbing into the RPE to add support for indicator specific tooltips. Adding the information to the existing dynamic property description is a trivial amount of work, providing the same information. Not very common, but it should also be possible to embed images into tooltips using HTML tags.
