### ISSUE TITLE
Duplicate mesh components added for each new FBX

### ISSUE THREAD

**Issue by rainbj** [o3de/o3de#9344]
**Describe the bug**
Every time I add a new FBX to the level it automatically adds to Mesh components on every entity at the exact same time. See video below.

**Steps to reproduce**
1. Open the editor
2. view your asset browser.
3. Click an drag FBX from your AB to your viewport window
4. Notice the newly created entity automatically has two duplicate meshes components on the same entity.
5. You can delete the duplicate without error

**Expected behavior**
I would expect only one Mesh component to show up per FBX/Entity by default

**Actual behavior**
Two Mesh component show up per FBX/Entity by default

**Assets required**

https://user-images.githubusercontent.com/82551958/166306279-fcf7149a-5a83-4ca2-b7a1-1838749f52e0.mp4

Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Dev - 05/02/2022 build

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I9-9900k  ]
 - GPU [NVIDIA GeForce RTX 3070]
 - Memory [e.g. 32GB]

**Additional context**

**Comment by lmbr-pip** [comment]
This appears to be a long standing issue where things are working as designed after unification of the drag & drop behavior for FBX source assets from asset browser to viewport and outliner.  It makes a single entity and creates a component for each product in the drag list but it has some unsolved issues, for example if multiple products use the same component it only sets it on the first component, which I believe what is happening here.

See https://github.com/o3de/o3de/pull/7858 for the related change.

So theres a number of things to unpack but mainly we need a UX design for how this should work, for example import options dialog when you drag in FBX files, hiding source assets by default in the asset browser etc.

**Comment by yuyihsu** [comment]
Dup of https://github.com/o3de/o3de/issues/9885, which has provided a UX solution.

**Comment by AMZN-stankowi** [comment]
Drag and drop for FBX files was updated since this was created.

If the FBX has a procedural prefab product asset, it will now instantiate that and detach it on a drag and drop event. If it does not have a procedural prefab, it will instead create an entity with a mesh component and assign the first mesh group it finds to that mesh component.
