### ISSUE TITLE
AutomatedReview Launchers have 100s of Shader Errors 

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9347]
**Describe the bug**
ServerLauncher in AutomatedReview is seeing lots of shader spam on startup. It makes it hard to debug tests, and might even lead to flaky test due to the large amount of std::out and tests which parse logs. 

**Steps to reproduce**
I'm not sure what Jenkins is doing to get all these errors, but it's easy to reproduce locally if you pass a bogus adapter as follows...
1. Run > ./build/linux/bin/profile/AutomatedTesting.GameLauncher --rhi=null --forceAdapter=bogus
2. See error

**Expected behavior**
No shader errors

**Actual behavior**
100's of errors spam
_==================================================================
Serialize: Trace::Error
 /home/gene/prj/o3de/Code/Framework/AzCore/AzCore/Serialization/SerializeContext.cpp(2880): 'void AZ::SerializeContext::ErrorHandler::ReportError(const char *)'
Serialize: Element 'NULL'(0x41405e39) with class ID '{A10B0F03-F43D-4462-9306-66195B4EFC46}' found in 'AZStd::intrusive_ptr' is not registered with the serializer!
If this class was removed, consider using serializeContext->ClassDeprecate(...) to register classes as having been deprecated to avoid this error.  File shaders/diffuseglobalillumination/diffuseprobegridclassification.azshader_

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - OS: Ubuntu 

[forceAdapter_intel_stdout.log](https://github.com/o3de/o3de/files/8606523/forceAdapter_intel_stdout.log)

Note: Works for GameLauncher or ServerLauncher

**Comment by AMZN-Gene** [comment]
[forceAdapter_intel_stdout.log](https://github.com/o3de/o3de/files/8606523/forceAdapter_intel_stdout.log)

**Comment by AMZN-Gene** [comment]
Force adapter is a red-herring... that was just the only way for me to repro the errors AR is seeing... 
Even so, maybe fixing the spam when using a bogus adapter will also fix the spam for AR?
Maybe the RT sahders are out of date or something. Basically your problem is that in null RHI it is trying to load DX12 rhi related data which is wrong. Pinging @dmcdiarmid-ly 

Snippet from AR Log:
```
Module: Attempting to load module:libvulkan.so
Module: Failed with error:
libvulkan.so: cannot open shared object file: No such file or directory
Module: Attempting to load module:libvulkan.so.1
Module: Success!
RHISystem: Initializing RHI...
RHISystem: 	Enumerated physical device: 
RHISystem: 	Using physical device: 

```

**Comment by lmbr-pip** [comment]
Is this related to https://github.com/o3de/o3de/issues/9186 ?

**Comment by AMZN-Gene** [comment]
> 

Different issue. These are errors during launcher runtime, the other are warnings during asset processor time

**Comment by AMZN-Gene** [comment]
cannot repro

**Comment by santorac** [comment]
I think this issue is a duplicate of https://github.com/o3de/o3de/issues/7898 so I'm surprised you couldn't repro it. Anyway, I'm working on a fix.
