### ISSUE TITLE
Mac OS Template icons have not been updated to use the new logo

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#9359]
**Describe the bug**
Mac OS Template icons have not been updated to use the new logo

**Steps to reproduce**
1. Download the latest development or stabilization installer.
2. Navigate to 

```
Templates\DefaultProject\Template\Resources\Platform\Mac\Images.xcassets\TestDPAppIcon.appiconset
```
and
```
Templates\MinimalProject\Template\Resources\Platform\Mac\Images.xcassets\TestDPAppIcon.appiconset
```
and
```
AutomatedTesting\Gem\Resources\MacLauncher\Images.xcassets\AppIcon.appiconset
```
and
```
o3de\Code\Editor\Platform\Mac\Images.xcassets\EditorAppIcon.appiconset
```

**Expected behavior**
Logos are updated.

**Actual behavior**
Old logo remains.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82226555/166516160-196dc25b-fdc2-464f-9bd5-0b7382917dbb.png)

**Found in Branch**
development@0dbd6f1c092475a655f38df4568b9b5f99b90daf

**Comment by AMZN-daimini** [comment]
This is addressed by the linked PR, closing.
