### ISSUE TITLE
AR Bug Report: ForceRegion_NoQuiverOnHighLinearDampingForce periodically fails AR

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#9365]
**Describe the bug**
ForceRegion_NoQuiverOnHighLinearDampingForce fails with the following information

```
156 - AutomatedTesting::PhysicsTests_Main.main::TEST_RUN (Failed)
ForceRegion_NoQuiverOnHighLinearDampingForce
E   Report:
E   [SUCCESS] Success: Entered game mode
E   [SUCCESS] Success: Found sphere
E   [SUCCESS] Success: Found force region
E   [SUCCESS] Success: Sphere heading to force region
E   [SUCCESS] Success: Sphere is above force region
E   [SUCCESS] Success: Sphere has entered force region
E   [FAILED ] Failure: Sphere final velocity invalid
E   [SUCCESS] Success: Sphere still above force region
E   [SUCCESS] Success: Sphere is not quivering
E   [SUCCESS] Success: Exited game mode
E   Test result:  FAILURE
```

**Additional context**
This test is not passing due to the velocity not stopping within 1 second on the automation node. I will have to dig in and attempt to replicate locally. This may be fixed by increasing the timeout, but we must first analyze if this a reasonable step to take.

**Comment by FuzzyCarterAWS** [comment]
Spent some time doing some perf testing around this on my machine by adding some timers and reporting around the failing check.

```
tic = time.perf_counter()
Report.result(Tests.sphere_stopped_moving, helper.wait_for_condition(lambda: sphere.velocity.IsZero(VELOCITY_THRESHOLD), 
     TIMEOUT))
toc = time.perf_counter()
Report.info(f"Velocity threshold found in {toc - tic:0.4f} seconds")
```

After running through this test 10 times I wound up with times between .2 & .8 seconds on a HIGH SPEC dev machine (AMD 5950x w/ RTX 3060).

This tells me that there's a chance that on a LOW SPEC or MID SPEC environment, it's entirely possible for the condition check to take longer than 1.0 seconds.

Going to switch the waits over to a general 3 second wait. If it takes longer than that for these conditions to pass, we should re-evaluate our automation approach or determine if the performance of the behaviors under test need to be improved (likely in this case).

**Comment by moraaar** [comment]
Physics tests are going through a major refactor. The tests will be redone. Closing this GHI.
Tagging @FuzzyCarterAWS
