### ISSUE TITLE
ScriptCanvas SourceHandle Serializes Non-Relative Paths

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9384]
**Describe the bug**
ScriptCanvas’s SourceHandle class serializes out absolute file path instead of relative file path.

    void SourceHandle::Reflect(AZ::ReflectContext* context)
    {
        if (auto serializeContext = azrtti_cast<AZ::SerializeContext*>(context))
        {
            serializeContext->Class<SourceHandle>()
                ->Version(1)
                ->Field("id", &SourceHandle::m_id)
                ->Field("path", &SourceHandle::m_relativePath)
                ;
        }
    }

**Steps to reproduce**
1. Open Multiplayer Samples BaseSample level https://github.com/o3de/o3de-multiplayersample/blob/development/Levels/SampleBase/SampleBase.prefab
2. Notice the “SpawnIfAuthority” entity has a script canvas component attached 
3. Save the level
4. Open the level .prefab file and look for SpawnIfAuthority
5. Notice the “path” field for SpawnIfAuthority 

**Expected behavior**
Path is relative

**Actual behavior**
Path is stored as an absolute path 

**Assets required**
https://github.com/o3de/o3de-multiplayersample/blob/development/Levels/SampleBase/SampleBase.prefab

**Screenshots/Video**
![](https://user-images.githubusercontent.com/32776221/166522025-78ab29cf-c486-48bf-b80c-329505376532.png)

**Found in Branch**
Development latest (May 3 2022)

**Desktop/Device (please complete the following information):**
 - OS: Ubuntu
**Additional context**

**Comment by monroegm** [comment]
Rerouting to scripting. Looks like the script canvas serializer needs to be updated.

**Comment by carlitosan** [comment]
closed by https://github.com/o3de/o3de/pull/10167
