### ISSUE TITLE
Scene Setting Exit Dialog Presents Users With Confusing Actions

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#9402]
**Describe the bug**
Scene setting exist dialog presents users with the wrong primary option. It should offer to *save* work and not discard work. This issue was split from https://github.com/o3de/o3de/issues/8914 as a short term fix to make workflow less confusing to users.

**Steps to reproduce**
1. When using the Scene Settings tool the last two things the user does are:
2. Click the Update button
3. Exit Scene Settings.

Exit dialog message is written in a reversed way, with the "Discard" button set as the primary color, which will lead the user to click on it, and in turn their changes will not be saved.

**Expected behavior**
Offers to save any unsaved changes.

UX should offer (from sig-ui-ux):
"You have unsaved changes. Would you like to save it?
[Save] [Discard]" with the [Save] button set as the primary button.

**Actual behavior**
See screenshot, offers to Discard changes which is confusing to uses. To easy for user to select Discard as they expect this to be a save dialog.

**Assets required**

**Screenshots/Video**
![163293024-4154ea66-3aed-44de-af9a-b937c01fce56](https://user-images.githubusercontent.com/61438964/166963989-727a9408-7a25-49a2-b113-b8ff3145443e.png)

**Found in Branch**
Dev

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**
* Scene setting discard dialog is sometimes showing up, even after user has saved. Would be good to understand what is causing the scene to marked "dirty" after saving. Mostly likely this needs to be own issue with clear reproduction steps.

**Comment by yuyihsu** [comment]
The UX solution has been provided in the original ticket "https://github.com/o3de/o3de/issues/8914". Please check there for the details.

**Comment by lmbr-pip** [comment]
Note: Discard is there to prevent a loop so we may need to have save attempt and then discard

1. In the "happy" case, something went wrong during initial save, editor notices files are dirty, we show save dialog and things save. No work is lost.
2. In the "unhappy" case,. something went wrong, we show save to try and save, things still go wrong, at this point things are probably unrecoverable, and so we need to flip to showing "potential" error if known and all user can do is discard at this point.

**Comment by AMZN-stankowi** [comment]
https://github.com/o3de/o3de/pull/10967
