### ISSUE TITLE
Core dump size limit for Linux 

### ISSUE THREAD

**Issue by Black-Drama** [o3de/o3de#9439]
There is a operation which modify limit for core dump size on Linux.Under normal circumstances, only root user allowed to execute this operation, if we wanna run engine or application by business user, how can avoid this restriction?
We have tried to modify limit to unlimited in /etc/security/limits.conf, 
`bool IncreaseMaxToInfinity(rlimit& limit)
    {
        if (limit.rlim_max != RLIM_INFINITY)
        {
            limit.rlim_max = RLIM_INFINITY;
            return true;
        }
        return false;
    }`
it worked, but are there any better way to achieve this? Or another way of thinking, do we really need to set it?

**Comment by byrcolin** [comment]
I think this is the only way to do it as it is a system issue, however we should do some due diligence and research it a bit and see if there isn't a better way to do it.
