### ISSUE TITLE
AR Bug Report

### ISSUE THREAD

**Issue by amzn-jillich** [o3de/o3de#9454]
**Describe the bug**
125 - Gem::ScriptAutomation.Tests.main::TEST_RUN (Failed)

**Failed Jenkins Job Information:**
Windows
cpu_test_profile

**Additional context**
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/2308/pipeline/

[log.txt](https://github.com/o3de/o3de/files/8661034/log.txt)

**Comment by monroegm** [comment]
Closing old issue
