### ISSUE TITLE
FBX compilation failed

### ISSUE THREAD

**Issue by macy12825** [o3de/o3de#9461]
Some fbx files will fail to compile  for the first time. If they are deleted and imported again, they will compile successfully.

![image](https://user-images.githubusercontent.com/97455291/167667305-13b262ca-091f-4533-9df8-f7352514da1c.png)

**Comment by lmbr-pip** [comment]
@macy12825 - Can you provide more details (branch, build, platform etc) and link to a FBX that exhibits this behaviour? Need to understand how we can reproduce what you are seeing.

**Comment by monroegm** [comment]
@macy12825 Please reopen or file a new issue if you are able to provide more information
