### ISSUE TITLE
[Multiplayer]NetworkTransformComponent does not support teleport movement

### ISSUE THREAD

**Issue by xiapeng78** [o3de/o3de#9472]
**Describe the bug**
NetworkTransformComponent does not support teleport movement. In some case, we have the scenario of moving one entity from position A to position B immediately. But entity still is smoothing movement with NetworkTransformComponent component.

**Steps to reproduce**
1. Set one entity to network entity
2. Add NetworkTransformComponent
3. Add NpcMove.scriptcanvas
4. Run ServerLauncher and GameLauncher
5. See entity movement

**Expected behavior**
Entity move forward for a wile and return 0 position immediately

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-11700]
 - GPU [NVidia RTX 3060 Ti]
 - Memory [32GB]

**Additional context**
![image](https://user-images.githubusercontent.com/17897322/167755757-079435ab-8e52-48ec-81a1-17a41031b403.png)
[NpcMove.zip](https://github.com/o3de/o3de/files/8666262/NpcMove.zip)

**Comment by lmbr-pip** [comment]
Need support in NetworkCharacterComponent, may need a TryTeleport for characters.

**Comment by AMZN-puvvadar** [comment]
This warrants testing but incrementing `m_resetCount` in NetworkTransformComponent should cause `m_syncImmediate` to flip to true which would disable interpolation on the next update.

**Comment by AMZN-puvvadar** [comment]
This is possible in code with `m_resetCount` by doing something along the lines of

```
GetEntity()->GetTransform()->SetWorldTranslation(AZ::Vector3(0, 150.f, 0));
GetNetworkTransformComponentController()->ModifyResetCount()++;
```
on the authority. This is a very minimal example. I'll see if I can add a more substantial example to MultiplayerSample.

For ScriptCanvas, you can try exposing `m_resetCount` by modifying the `ExposeToScript` field of `resetCount` in `NetworkTransformComponent.AutoComponent.xml`.

**Comment by kberg-amzn** [comment]
> For ScriptCanvas, you can try exposing `m_resetCount` by modifying the `ExposeToScript` field of `resetCount` in `NetworkTransformComponent.AutoComponent.xml` and then applying similar logic.

Rather than directly expose reset count, it would be better for us to expose a teleport method or RPC (server to authority at most for security reasons) that does the set position and reset increment atomically.

**Comment by lmbr-pip** [comment]
As there maybe game specific changes here  (ie reset velocity, don't reset velocity), sig-nework proposes

* Adding a sample to MPS + documentation (short change)
* Add as sample in Multiplayer sample toolkit gem: https://github.com/o3de/o3de/issues/8281

**Comment by lmbr-pip** [comment]
@xiapeng78 - SIG decided to split work to two other open requests. Closing this issue out as work is now covered elsewhere.

Please reopen with comments if you have thoughts or would like to propose a different set of changes.
