### ISSUE TITLE
Reflected property editor element ordering incorrect when using groups and buttons

### ISSUE THREAD

**Issue by amzn-jillich** [o3de/o3de#9478]
**Describe the bug**
The ordering of the elements in the reflected property editor is incorrect when using AZ::Edit::UIHandlers::Button along with a AZ::Edit::ClassElements::Group when filling the edit context.

**Steps to reproduce**
1: Adjust an edit context that can be disaplayed in an RPE and add a AZ::Edit::UIHandlers::Button somewhere as well as one or more AZ::Edit::ClassElements::Group.
2. Open up the RPE.

**Expected behavior**
The elements coming after the group should be within the group.
Elements should be ordered the way they are in the code.
The button should show up on the position it is in the code.

**Actual behavior**
Groups are not ordered in the order they are in the code. The button appears on the top (sometimes within a group).

**Found in Branch**
development

**Comment by cgalvan** [comment]
@amzn-jillich Found this actually isn't restricted to only being an issue with using groups and `UIElement`, is a more general issue that is exposed by trying to reflect anything on an `AZ::Component` and also have a `UIElement` with no backing data element.
