### ISSUE TITLE
Reflected property editor/Edit context: It is impossible to put elements at root level after a group

### ISSUE THREAD

**Issue by amzn-jillich** [o3de/o3de#9479]
**Describe the bug**
There is no way to put a data element/widget at the root level of the RPE after using AZ::Edit::ClassElements::Group.

One way to solve this would be adding a new attribute to close an opened group. One other way I heared about is just adding the class to the edit context again, which concatenates the elements.

The concatenation works, but comes with a variety of other issues: Groups and buttons don't show up at all anymore.

**Expected behavior**
There is a way to close a group and the elements added to the edit context after that are back at the parent/root level).

**Actual behavior**
Described above.

**Found in Branch**
development

**Comment by cgalvan** [comment]
Turns out there is a way to do this:
```
->ClassElement(AZ::Edit::ClassElements::Group, "") // end previous group by starting new unnamed expanded group
```
A few places in the code-base make use of it. It's not self-discoverable though, so I'm going to add a helper method to the ClassBuilder that will do this for you.
