### ISSUE TITLE
AZStd::tuple has inconsistent and abbreviated names generated in BehaviorContext

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#9488]
**Describe the bug**
When AZStd::pair<int, float> is reflected to the behavior context, it gets the name `AZStd::pair<int, float>`. However, when `AZStd::tuple<int, float>` is reflect to the behavior context, it gets the name `tuple<int float >`. It is missing the AZStd:: prefix, commas between the template parameters, and has a trailing space after the last template parameter.

Also, if the name becomes longer than 128 characters, the name gets truncated, which makes construction of different types of tuples that only vary at the final parameters impossible through the BehaviorContext.

**Steps to reproduce**
1. Call `serializeContext.RegisterGenericType<AZStd::tuple<int, float>>();`
2. From Python, call `test_tuple = azlmbr.object.create('AZStd::tuple<int, float>')`

**Expected behavior**
The create call produces a valid tuple.

**Actual behavior**
No tuple is produced because the name is incorrect. You need to instead use:
`test_tuple = azlmbr.object.create('tuple<int float >')`

**Comment by lumberyard-employee-dm** [comment]
We should update the AZStd::tuple reflection to be consistent with the naming of other AZStd container types.

Now for the argument length, I think a workaround is to use a struct instead and reflect that in order to support a BehaviorContext method that returns multiple values.
