### ISSUE TITLE
As a Developer I Want an IMGUI Option to Become the Multiplayer Host

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9497]
**Is your feature request related to a problem? Please describe.**
Every time I run server launcher I either need to remember to start it using --console-command-file=server.cfg or make my own .cmd to run it. This assumes users even know this option is available, most people will just want to open the ServerLauncher.exe.

**Describe the solution you'd like**
Most people will just open ServerLauncher.exe when they want to host a multiplayer game. IMGUI menu is a good place for discovery. Let's provide a Multplayer option for hosting.
Sure it's an easy command ("host"), but why not provide a GUI which seems more user friendly. The host option should also provide a list of available levels to load into upon hosting since that's what most people will do (call host followed by loadlevel)
It should also allow users to open gamelaunchers that automatically connect as well.

> host
> load level xyz
> run GameLauncher.exe --connect

**Additional context**
This came up during a walk-the-engine meeting. Actually running a server and client was tricky.

**Comment by lmbr-pip** [comment]
Fixed in https://github.com/o3de/o3de/pull/9650
