### ISSUE TITLE
[Linux] Unable to launch tools (Asset Processor, Editor, Project Manager, Game Launcher) executables from file explorer

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#9502]
**Describe the bug**
It is not possible to launch the Editor, Project Manager, Asset Processor, or other executables from the file explorer.
When attempting to launch one of above mentioned tools by using its executable an error is displayed - Please refer to the attached screenshot.
Note that that "<tool_name>" depends on executable launched.
The workaround is available for this issue - It is possible to launch the above mentioned tools via CLI, e. g. `sudo ./o3de` launched from executable directory.

**Steps to reproduce**
1. Setup the build from Github repository or install the engine using installer.
2. Build the engine and register it.
3. Navigate to the directory with engine executables in file explorer.
4. Launch the "o3de" executable or other tool executable.

**Expected behavior**
The executables work, it is possible to launch the tools by using its executables.

**Actual behavior**
It is not possible to launch executables.

**Screenshots**

![Executables_Issue](https://user-images.githubusercontent.com/86951967/168049831-75b152f2-d337-4806-bc96-f9cd60973a1d.png)

**Found in Branch**
Development (3fa483b)
Stabilization_2205 installer

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Additional context**
Older closed issue - https://github.com/o3de/o3de/issues/7589

**Comment by tonybalandiuk** [comment]
How reproducible is this issue? Does it only occur on certain machines. (Example 1 machine out of 5?)

**Comment by LB-JakubSkorupka** [comment]
@tonybalandiuk The issue occurred on 4 out of 4 machines we tested it on. We did not noticed any differences, it occurred with the same result on every machine.

**Comment by forhalle** [comment]
@spham-amzn - Can you please confirm next steps and close if necessary?

**Comment by spham-amzn** [comment]
This is no longer supported by default by Nautilus ( https://www.omgubuntu.co.uk/2018/05/nautilus-remove-ability-launch-binaries-apps ). There are work-arounds ( https://fostips.com/double-click-run-elf-ubuntu/ ) but it is not standard behavior and not something we should try to hack
