### ISSUE TITLE
Intermittent failure of AutomatedTesting::MultiplayerTests_Main.main::TEST_RUN on Linux test_profile_nounity 

### ISSUE THREAD

**Issue by invertednormal** [o3de/o3de#9508]
AutomatedTesting::MultiplayerTests_Main.main::TEST_RUN failed in an AR run on Linux that the previous 3 tests all succeeded at with no changes in code (note there are other failures in the previous tests, but not this one).

Failed run:
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-9452/5/pipeline/419/

Runs without this failure:
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-9452/2/pipeline/730/
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-9452/3/pipeline/643/
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-9452/4/pipeline/204/

```
[2022-05-11T19:30:36.216Z] ../../../../../../AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py::TestAutomation::test_Multiplayer_SimpleNetworkLevelEntity[linux-crash_log_watchdog0-windows_editor-AutomatedTesting] ERROR [100%]
```
(the full error log is quite long, see above URL)

**Comment by lmbr-pip** [comment]
All the multiplayer tests are disabled currently (all moved to sandbox) so issue has been resolved.
