### ISSUE TITLE
Bug Report: Cannot register project to engine with O3DE.sh

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#9509]
**Describe the bug**
On fresh install, try and register project to an engine as described here: https://www.o3de.org/docs/user-guide/project-config/cli-reference/#register

Unsure if this is a docs bug or feature is expected to work

**Steps to reproduce**
1. Try to register engine to project ie `scripts/o3de.sh register -pp PROJECT_PATH  --engine-path ENGINE_PATH`

**Expected behavior**
* Can register project to engine as per docs

**Actual behavior**
* Fails with `o3de.py register: error: argument -ep/--engine-path: not allowed with argument -pp/--project-path`

**Assets required**
N/a

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Dev (latest)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 20 LTS version supported by O3DE

**Additional context**

**Comment by byrcolin** [comment]
The script is executed from an engine so that specifying the engine is not needed in this case, but I will check into it and make sure.

**Comment by byrcolin** [comment]
maybe just a documentation error of trying to register two objects at he same time
