### ISSUE TITLE
NetworkPlayerSpawnerComponent Asset Field Says ".network"

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9511]
**Describe the bug**
When choosing NetworkPlayerSpawnerComponent player prefab, the editor field shows ".network".
This is confusing because users should be interacting with the .prefabs at edit time and not the individual products (spawnables). Also, "player.network" doesn't actually exist, the product name is "player.network.spawnable" so this adds some confusion when devs are looking for the asset in the Asset Browser.

**Steps to reproduce**
1. Add a entity with NetworkPlayerSpawnerComponent 
2. Choose a prefab for the SpawnableAsset 
3. Notice asset name inside the "SpawanableAsset" field

**Expected behavior**
Field should match the name of the asset, ie: <prefabname>.prefab

**Actual behavior**
Field says, "<prefabname>.network"

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32776221/168132538-5df46290-9740-4190-b0a9-6f34ec782219.png)

**Comment by lmbr-pip** [comment]
Need to decide on path forward here:
* Are we filtering out anything but .network spawnables and fixing just this UI
* Or changing asset selection to enable prefab selection and tooling finds right product dependency to use?

**Comment by AMZN-Gene** [comment]
Closing this out. We wont pass around prefabs.
