### ISSUE TITLE
NetworkPlayerSpawnerComponent Allows Users to Select Non-Network Prefabs

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9513]
**Describe the bug**
NetworkPlayerSpawnerComponent allows users to select non-network prefabs, Net-players will always need a net-binding so we should enforce only prefabs which contain a .network product. 

**Steps to reproduce**
1. Add an entity with NetworkPlayerSpawnerComponent 
2. Select a non-network prefab for the SpawnableAsset field

**Expected behavior**
Editor should give a warning, or block the user from selecting non-net prefabs

**Actual behavior**
Editor gladly accepts an non-net prefab

**Found in Branch**
development 5/10/2022

**Comment by lmbr-pip** [comment]
Relates to https://github.com/o3de/o3de/issues/9511

**Comment by AMZN-Gene** [comment]
blocked by #11239
