### ISSUE TITLE
As a Dev it's Hard to Tell if a Launcher is Host or Client

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9514]
**Describe the bug**
It's hard to tell if a launcher.exe is a host or client. The window always just says the game name.

**Steps to reproduce**
1. Open ServerLauncher.exe and run the "host" command
2. Open GameLauncher.exe and run the "connect" command
3. Move the 2 windows around and try to tell which is host and client

**Expected behavior**
There should be some UI that it very visible so users can quickly tell if they are host or client

**Actual behavior**
No way to tell which launcher is host and which is client

**Suggestion**
Consult with UX team on a design.
Suggestion 1: Change the window title to match the exe name. So the window will say MyProject.GameLauncher or MyProject.ServerLauncher. Note: This might not be good since when shipping the game you probably want to see the game name, not the ".GameLauncher.exe". 

Suggestion 2: Add some viewport debug text saying "host" or "client". This might be noisy and conflict with other debug information.

![image](https://user-images.githubusercontent.com/32776221/168139729-8dbeaaf8-1a92-43a8-9f13-5ceecbcdc47f.png)

**Found in Branch**
development May 10 2022

**Comment by lmbr-pip** [comment]
Triage thoughts are that title window is insufficient as a fix.

**Comment by AMZN-Gene** [comment]
Added cl_viewportConnectionStatus. Lower-left corner of clients display connection status and the host's ip address. 
Example:
![image](https://user-images.githubusercontent.com/32776221/180912648-0cb0b94f-713e-49f1-9f4c-8d8a00045435.png)

**Comment by lmbr-pip** [comment]
Need help here from SIG/build as this appears to be hardwired through CMake to how the window title is set.

**Comment by AMZN-Gene** [comment]
@lmbr-pip we'll go with UX's suggestion instead of changing the window title, we'll put text in the corner of the screen on both client and servers.
