### ISSUE TITLE
As a dev I want the Default Level Ground to Have a Collider

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9516]
**Is your feature request related to a problem? Please describe.**
Developers are always having to add a collider to the default level's ground

**Describe the solution you'd like**
Add a collider to the default ground

**Comment by hultonha** [comment]
Adding feature/prefabs as they may be able to update the default scene prefab

**Comment by hultonha** [comment]
Adding `sig-content` to review this in their triage setting to see if this can be assigned to another team to implement
