### ISSUE TITLE
[Linux] Editor splash screen on load displays "Development Build" instead of "Version 22.05.0" as the version 

### ISSUE THREAD

**Issue by amzn-kritinig** [o3de/o3de#9519]
**Describe the bug**
Incorrect Build Name on the "About Open 3D Engine Editor Page" 

**Steps to reproduce**
1. Download and install the release installer from https://o3debinaries.org/download/linux.html
2. Open the Project Manager (o3de executable) from /opt/O3DE/22.05.0/bin/Linux/profile/Default/o3de
3. Click on "Open Editor" for the default project
4. While the AP is processing the assets, check the details of the splash screen.

Part II 
From the editor window > file menu > Help > About o3de > 
The "About 03de" screen incorrectly mentions "Development build" 

**Expected behavior**
The splash screen should have correct release name and version number. 

**Actual behavior**
o3de splash screen reads "Development Build".
![image](https://user-images.githubusercontent.com/82232747/168155352-881ed940-d483-4429-af16-35b93339efd5.png)

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82232747/168155512-0e114ee3-edf0-4962-aa58-b78b01a2ed99.png)
![image](https://user-images.githubusercontent.com/82232747/168155538-84d94168-df59-4777-a89d-5fbaba6f9acf.png)

**Found in Branch**
Release Installer https://o3debinaries.org/download/linux.html

**Desktop/Device (please complete the following information):**
 - Device: Linux PC
 - OS: Ubuntu 20.04
 

**Additional context**

**Comment by AMZN-Dk** [comment]
![image](https://user-images.githubusercontent.com/83721425/168157411-a0c98619-2933-47b9-8691-896fc852bf0b.png)

For reference here is the Windows version of this screen

**Comment by amzn-changml** [comment]
Does it state the correct version in the Engine configuration screen?

![image](https://user-images.githubusercontent.com/62353586/168158775-6bc26cd1-4fe5-4f1e-9fd3-1d2888e3009f.png)

**Comment by amzn-kritinig** [comment]
Yes the engine settings are correct 
![image](https://user-images.githubusercontent.com/82232747/168174009-9a94177a-b4db-4568-ac4f-64a5f49a4f7b.png)

**Comment by AMZN-Dk** [comment]
Looking into this further, the Linux splash screen may have been like this in our previous release Version 2111.2, we are trying to verify that now.

**Comment by LB-RobertBaczkowski** [comment]
We investigated this issue today; we could not reproduce it on Linux, but we managed to have the same result on a single machine on Windows by having two instances of different branches of the engine in a single location. Here are the steps:

1. Setup the Development branch build from GitHub; set its main path to C://o3de .
2. Download the release installer for 22.05.0 (https://www.o3de.org/download/).
3. Install 22.05.0 using default settings. This should create a new folder: C://o3de/22.05.0.
4. Launch the 22.05.0 editor by confirming the prompt that appears after the installation or by using the desktop shortcut (which redirects to the .exe file in the 22.05.0 folder).
5. (optional) Note that when project Manager launches, the list of projects will include projects previously created on Development, if you have them.
6. See Engine -> General. Data displayed there will be referring to the 22.05.0 version:
![EngineGeneral](https://user-images.githubusercontent.com/80751316/168289446-bf58660e-9a48-454b-8893-681b174a8253.png)
7. Launch a project. The splash screen will say "Development Build":
![Splash](https://user-images.githubusercontent.com/80751316/168289534-03c29886-13f2-4ead-8736-ae9c5a9e7976.png)
8. Go to Help -> About O3DE. The information displayed there will also mention the Development Build:
![About](https://user-images.githubusercontent.com/80751316/168289599-59ac84ad-b496-4ba6-96f2-a667fbad59e5.png)

The conflict here seems to be related to the o3de_manifest.json file in the .o3de folder: [o3de_manifest.zip](https://github.com/o3de/o3de/files/8687310/o3de_manifest.zip); it's attached in the shape it was in after launching the installer version of the editor. The information there includes a project previously created on the Development branch, named "Test".

Again, please note that we were able to get this result only on a single machine. It did not occur on another one, both in the same or a different build location (C://o3dev/o3dev); we were also unable to reproduce it on Linux, with both builds in /opt/O3DE. There was a separate issue here, as the installer build does not launch. It does display the splash screen, however, and it shows the correct version (22.05.0). The Development build does not seem to be effected by the installer build.

Obviously having two builds effectively in the same location is not an optimal course of action, but it may be the reason behind the original issue here - this is as close as our team got to it during our investigation. However, it cannot be reproduced consistently.

To safeguard against this, warnings may be added to the installer for situations in which existing build files are found in the installation path. As a large-scale solution, a tool could be implemented for managing multiple versions of the engine existing on the same machine.

**Comment by AMZN-daimini** [comment]
The version value displayed there is not from the manifest, but is set at build time from the CMake configuration

![image](https://user-images.githubusercontent.com/82231674/168321510-241dab54-624b-42c0-b4bf-a5cc3cc00810.png)

**Comment by amzn-changml** [comment]
`LY_VERSION_BUILD_NUMBER` was set in the environment during the installer build. I confirmed it to be the case, as the installer filename depends on that variable to be set as well.

**Comment by AMZN-daimini** [comment]
Got it. here is the PR that introduced that changed, maybe it will help detecting why it doesn't pick it up in Linux?
https://github.com/o3de/o3de/pull/8913

**Comment by Ulrick28** [comment]
> Got it. here is the PR that introduced that changed, maybe it will help detecting why it doesn't pick it up in Linux? #8913

From reading the comments, this appears to be a windows/Linux issue when two versions of O3DE are installed in the same spot (ie, development and 22.05.0). It appears that the first one installed will take precedent for version on the screen.

**Comment by monroegm** [comment]
Rerouting to SIG-Build/SIG-Release as this is less of an issue with the splash screen and more of a CMake issue

**Comment by spham-amzn** [comment]
No longer an issue with the current release (2310.2)
