### ISSUE TITLE
Lyshine: Editor crash can occur with UI Canvas Asset Ref component when entering Game Mode

### ISSUE THREAD

**Issue by dm-amzn** [o3de/o3de#9525]
**Describe the bug**
Lyshine: Editor crash can occur with UI Canvas Asset Ref component when entering Game Mode.
- Issue only seems to occur when using a .uicanvas with a Render to texture > Render Target selected via Canvas Properties.

**Steps to reproduce**
1. Launch the Editor
2. Create a new level, or load an existing level
3. Create an entity
4. In the Entity Inspector, add a UI Canvas Asset Ref component
5. In the UI Canvas Asset Ref component, add a .uicanvas (with a Render to texture > Render Target) and toggle on Load Automatically
6. Enter Game Mode
7. Observe issue

**Expected behavior**
Editor is stable.

**Actual behavior**
 Editor crash occurs with UI Canvas Asset Ref component when entering Game Mode.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/97991771/168185193-3971e57e-b4be-4ee7-b323-04621dfe15cb.png)
![2022-05-11 22_43_39-Greenshot](https://user-images.githubusercontent.com/97991771/168180212-15432dd1-51a1-47df-989c-fadc479505f9.png)

**Found in Branch**
Development commit ac7dd1bfb86ad9c118c62c2534e59766b38480b0

```10) 00007FFF3064B857 (KERNELBASE) : UnhandledExceptionFilter
 9) 00007FFF32DE2109 (ntdll) : TpDbgDumpHeapUsage
 8) 00007FFF32DE2BC2 (ntdll) : TpDbgDumpHeapUsage
 7) 00007FFF32D752ED (ntdll) : memset
 6) 00007FFF32D5C766 (ntdll) : _C_specific_handler
 5) 00007FFF32D6C95E (ntdll) : RtlUnhandledExceptionFilter
 4) 00007FFF32D720CF (ntdll) : _chkstk
 3) 00007FFF32D21454 (ntdll) : RtlRaiseException
 2) 00007FFF32D70BFE (ntdll) : KiUserExceptionDispatcher
 1) D:\o3de_repo\o3de\o3de\Code\Framework\AzCore\AzCore\Debug\Trace.cpp (229) : AZ::Debug::Trace::Crash```

**Comment by dm-amzn** [comment]
This issue is not reproducing with a newly created level after getting latest. Closing for now.

**Comment by GraphiteSIX** [comment]
I repro'd this twice in a row doing the same thing with the same assets but got different stacktraces.
I have saved both dumps and logs and captured the crash on video the second time.
The dumps and logs are below:

https://user-images.githubusercontent.com/105223355/169388511-47b594e1-2b32-4300-a22a-b9f5292c13d3.mp4

[LyshineGM_CRASH.zip](https://github.com/o3de/o3de/files/8733742/LyshineGM_CRASH.zip)

@dm-amzn Let me know if you need anymore info.

**Comment by GraphiteSIX** [comment]
I just rebuilt a clean source development build (#9603).
Repro'd it first go same way with the same assets.
