### ISSUE TITLE
Procedural Prefabs- Sub-object accessibility issue

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#9529]
**Describe the bug**
FBX files that are generated from Maya with the intended output to be "Procedural Prefabs", do not appear to be working as expected. The root of the problem is that Procedural Prefabs _should_ have allowed access to each of the single components that comprised the larger whole (in this case it was an FBX file containing approximately 25 different rock meshes, grouped under a single node and exported). Inside of O3DE, the sub-objects were present visually, but accessing any of them individually was not possible. They were represented by a single locked node that was unable to be expanded for further access/manipulation (see attached image). This was not was expected when we set to review them. 

**Steps to reproduce**
1. Import export_shapes_01.fbx into the editor
2. right click on the viewport and select instantiate Procedural prefab
3. double click on the icon on the left side of the entity outliner listing of the prefab to expand

**Expected behavior**
User should have access to all individual elements contained inside procedural prefab

**Actual behavior**
User has access to none of the underlying elements, and they are collectively represented by one locked node

**Assets required**
Provide sample assets needed to reproduce the issue.
[export_shapes_01.zip](https://github.com/o3de/o3de/files/8683149/export_shapes_01.zip)

**Screenshots/Video**
![prefab_issue](https://user-images.githubusercontent.com/50616575/168185258-8a838055-fcfe-446e-b185-4fe437394f1b.png)

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - PC
 - Windows
 - 10
 - Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz   3.30 GHz
 - NVidia GeForce RTX 2080
 - 64.0 GB

**Additional context**

**Comment by lmbr-pip** [comment]
https://github.com/o3de/o3de/pull/9546

**Comment by monroegm** [comment]
Should be fixed now by the above PR.
