### ISSUE TITLE
[material API] Getpropertyoverride < type > can't get the correct color information. The result is R G B a value 0 0 0 0

### ISSUE THREAD

**Issue by qq260105064** [o3de/o3de#9541]
**Describe the bug**
If clear the modified information in the material instance，the Getpropertyoverride API unable to return the correct color value.

**Steps to reproduce**
1. Clear changes in material instances
2. Canvas script editing obtains the material slot information through the materiallassignmentid node, and getpropertyoverride < type > related nodes obtain the specified output content
3. Print view get results

**Expected behavior**
It is consistent with the actual results.

**Actual behavior**
Inconsistent with the actual results.

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by gadams3** [comment]
Hello. Thank you for posting this request. Can you please elaborate on the behavior you're looking for or problem that you're experiencing? Material component request bus “override” functions currently only return the values that have been explicitly set through the editor or using script. It does not currently return the values from the material if no override has been applied. Are you requesting that functionality? Returning the values directly from the material instance even if no overrides are applied? If so, I think it should be possible to update those functions to return the values from the active material asset even if there is no override applied.

**Comment by qq260105064** [comment]
> 你好。感谢您发布此请求。您能否详细说明您正在寻找的行为或遇到的问题？材质组件请求总线“覆盖”函数目前仅返回已通过编辑器或使用脚本显式设置的值。如果没有应用覆盖，它当前不会从材质返回值。您是否要求该功能？即使没有应用覆盖，也直接从材质实例返回值？如果是这样，我认为应该可以更新这些函数以从活动材料资产返回值，即使没有应用覆盖。

Yes, what I want is to return values from material instances without applying overrides. Which functions need to be updated? thank you

**Comment by qq260105064** [comment]
> 你好。感谢您发布此请求。您能否详细说明您正在寻找的行为或遇到的问题？材质组件请求总线“覆盖”函数目前仅返回已通过编辑器或使用脚本显式设置的值。如果没有应用覆盖，它当前不会从材质返回值。您是否要求该功能？即使没有应用覆盖，也直接从材质实例返回值？如果是这样，我认为应该可以更新这些函数以从活动材料资产返回值，即使没有应用覆盖。

Yes, what I want is to return values from material instances, even if no overrides are applied. What features need to be updated? Thank you.
