### ISSUE TITLE
Prefabs: Assigning an Actor asset to an Actor component inside of a Prefab breaks the entity's parent

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#9550]
**Describe the bug**
Assigning an Actor asset to an Actor component inside of a Prefab breaks the entity's parent.

**Steps to reproduce**
1. Create a new level.
2. Create a new entity and make a prefab from the entity.
3. Enter Focus Mode on the prefab, and create a new child entity.
4. Add an Actor component to the new child entity.
5. Assign any Actor asset to the Actor component.
6. Observe the entity hierarchy.

**Expected behavior**
Actor asset is assigned, and entity hierarchy is unaffected.

**Actual behavior**
Actor asset is assigned, however the child entity then jumps out of the prefab and has no parent info in the Transform component. This can result in further undesired behavior, such as an Editor crash when entering Game Mode, likely due to the invalid parent.

**Assets required**
AutomatedTesting project has Actor assets that can be used.

**Screenshots**
![image](https://user-images.githubusercontent.com/82226555/168390249-d437f409-6345-4215-91ec-a2eff5387a79.png)

**Found in Branch**
development@a9963ff5405d81fcb583bc58ecf9af6c8e958899

**Comment by jckand-amzn** [comment]
Updating this to Critical priority. Currently it's very difficult to work with the Actor component as any parent/child relationship is not retained. Additionally, after entering/exiting Game Mode, the Actor entity won't only lose it's parent, but will randomly change Transform, moving it potentially very far away from it's intended parent entity. Fixing the issue is a band-aid as it will again break after entering Game Mode.

**Comment by hultonha** [comment]
@jckand-amzn would it be possible to please add a video of the issue so we can more clearly see what's happening please. Thanks!

**Comment by hultonha** [comment]
Update: Discussed briefly in sig-simulation triage, did not have time to fully diagnose.

@LB-MateuszSzweda Is this something you could please verify for us with any additional details. Thanks!

**Comment by LB-MateuszSzweda** [comment]
@hultonha 

I've tested around this today. In fact like @jckand-amzn written in comments this is not only isolated to prefab based hierarchies but also to simple nested enties.

So simply:
1. Creating a non prefab entity with a child
2. Adding actor component with specified asset to the child 

Reproduces the same issue. The child detaches from the parent and lacks a parent entity in its Transform component.

In fact adding an actor asset to a singular non nested entity is enough to detach it from "Level" parent entity.

Interestingly enough the entity with actor component and actor asset assigned can be manually added as a child to other entities in Entity Outliner but will detach from them upon entering and exiting the Game Mode.

I've tested that creating prefabs from such manually created hierarchies also detaches them.

So no working workaround for creating nested entities/prefabs with actor based component entities was found.

On the upside I did not encounter any crashes when testing all of the above.

**Comment by hultonha** [comment]
Thank you for the updates @LB-MateuszSzweda, this something I'll ping @amzn-jillich and @amzn-rhhong when they're back, this sounds like there is something going on with Actor Components and their interaction with the Prefab system 🤔

**Comment by hultonha** [comment]
Adding @amzn-jillich as assignee to do an initial investigation to help determine the root cause. Thanks!

**Comment by amzn-jillich** [comment]
PR ready: https://github.com/o3de/o3de/pull/9881
