### ISSUE TITLE
[Linux] Configuring new projects fails

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#9581]
**Describe the bug**
The configure command fails for a new projects. Building project also fails when building via Project Manager.

**This issue occurs on Development installer**

**Steps to reproduce**
1. Create a project: $O3DE_ENGINE/scripts/o3de.sh create-project --project-path $O3DE_PROJECT_PATH.
2. Register the Project: scripts/o3de.sh register --project-path.
3. Generate the build folder (configure): cd $O3DE_PROJECT_PATH  cmake -B build/linux -S . -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12 -DCMAKE_BUILD_TYPE=profile

**Expected behavior**
The Build folder is generated and the Project is ready for building.

**Actual behavior**
The configure command fails.

**Screenshots**

![Errors](https://user-images.githubusercontent.com/86952591/168799759-970ae5b4-f14e-4a8b-b1ff-8bd759adb3be.png)

**Found in Branch**
Development installer

**Desktop/Device:**
Device: PC
OS: Linux
Version Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU Nvidia Geforce RTX 2060 SUPER
Memory 16GB

**Additional context**
[CMakeError.log](https://github.com/o3de/o3de/files/8707872/CMakeError.log)
[CMakeOutput.log](https://github.com/o3de/o3de/files/8707873/CMakeOutput.log)

**Comment by LB-ArturZieba** [comment]
This issue also occurs on the Development (3e42c6a) build on Linux when engine is built using the Pre-built SDK configuration. It should be noted that on the Source configuration this issue does not occur.

**Comment by LB-JakubSkoczylas** [comment]
This issue is still active for Development Installer version. We will re-verify this after the merge is implemented into the installer.

**Comment by LB-KacperKapusta** [comment]
Verified the issue as fixed using Stabilization/2210 (https://github.com/o3de/o3de/commit/99608ffd4f7d3d347cb015b243046a3438da23c7) build.
