### ISSUE TITLE
AR Bug Report: ForceRegion_WorldSpaceForceOnRigidBodies periodically fails AR

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#9582]
**Describe the bug**
ForceRegion_WorldSpaceForceOnRigidBodies fails with the following information

Platform: linux

````
Failed: Test ForceRegion_WorldSpaceForceOnRigidBodies:
Test FAILED
------------
|  Output  |
------------
Test ForceRegion_WorldSpaceForceOnRigidBodies finished.
Report:
[SUCCESS] Success: Entered game mode
[SUCCESS] Success: Ball entity found
[SUCCESS] Success: Box entity found
[SUCCESS] Success: Ball fell
[SUCCESS] Success: Ball triggered force region
[SUCCESS] Success: Ball moved up
[FAILED ] Failure: The net force magnitude on the ball is not close to expected value
[SUCCESS] Success: Exited game mode
Test result:  FAILURE
````

Editor log:

````
(python_test) - Info: Entering game mode
(python_test) - 
Disable Accelerators
Entered game mode
(python_test) - Success: Entered game mode
(python_test) - 
(python_test) - Success: Ball entity found
(python_test) - 
(python_test) - Success: Box entity found
(python_test) - 
(python_test) - Info: Starting Height of the ball: 44.820796966552734
(python_test) - 
(python_test) - Info: Ball position is now lower than the starting position
(python_test) - 
(python_test) - Success: Ball fell
(python_test) - 
(python_test) - Info: Trigger entered
(python_test) - 
(python_test) - Info: Trigger exited
(python_test) - 
(python_test) - Success: Ball triggered force region
(python_test) - 
(python_test) - Success: Ball moved up
(python_test) - 
(python_test) - Info: NetForce magnitude is 0, Force Region magnitude is 1000.0
(python_test) - 
(python_test) - Failure: The net force magnitude on the ball is not close to expected value
(python_test) - 
(python_test) - Info: Exiting game mode
(python_test) - 
Enable Accelerators
(Logger) - > disconnect : <empty>
[Warning] (CryLegacy) - Not restoring the editor viewport camera is currently unsupported
Exited game mode
(python_test) - Success: Exited game mode
(python_test) - 
(python_test) - Test ForceRegion_WorldSpaceForceOnRigidBodies finished.
Report:
[SUCCESS] Success: Entered game mode
[SUCCESS] Success: Ball entity found
[SUCCESS] Success: Box entity found
[SUCCESS] Success: Ball fell
[SUCCESS] Success: Ball triggered force region
[SUCCESS] Success: Ball moved up
[FAILED ] Failure: The net force magnitude on the ball is not close to expected value
[SUCCESS] Success: Exited game mode
Test result:  FAILURE
````

**Comment by hultonha** [comment]
@moraaar Could you please add a link to the job failure and attach the .log files as well please?

**Comment by moraaar** [comment]
> @moraaar Could you please add a link to the job failure and attach the .log files as well please?

The link will stop working soon at some point, but here it is: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/2358/pipeline/531

The interesting part of the log is already in the description, but here is the full log: [log.txt](https://github.com/o3de/o3de/files/8710165/log.txt)

**Comment by hultonha** [comment]
Thank you @moraaar, the log.txt is the most useful thing for sure, just good to have all the context. Much appreciated!

**Comment by hultonha** [comment]
Visited this issue in sig-simulation triage and bumping to critical to ensure this issue is prioritized and looked at asap. Thanks for taking this on @FuzzyCarterAWS!

**Comment by FuzzyCarterAWS** [comment]
Figured out what's going on here.

Occasionally, the test execution happens so fast that after detecting that the collision with the force region happened, the system had not actually applied the the magnitude to the ball yet.

This is a simple fix to put the check for the ball's magnitude to be the expected in 1s. This should take a fraction of the time, but will also prevent us from ever running into the situation where the automation runs faster than the system.

**Comment by hultonha** [comment]
Thanks for the update @FuzzyCarterAWS - be worth syncing with @SergeyAMZN and/or @greerdv when the PR is ready to go 👍

**Comment by FuzzyCarterAWS** [comment]
After further analysis and inputting the solution, these test is rife with timing issues and is going to need a redesign. Currently looking into ways to eliminate the timing issues.

**Comment by hultonha** [comment]
Downgrading to major as these have a all temporarily disabled. The are being reviewed and will be restored after validating they are still useful and no longer flaky.

**Comment by moraaar** [comment]
All physics tests are going through a major refactor and all these tests won't be used. Closing this bug.
Tagging @hultonha @FuzzyCarterAWS
