### ISSUE TITLE
Image Gradient: Updating component properties in the Advanced category via script clears the asset from the component

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#9602]
**Describe the bug**
Updating component properties in the Advanced category via script clears the asset from the component. This only appears to occur via script.

**Steps to reproduce**
1. Open the following test file in a text editor:
```
AutomatedTesting/Gem/PythonTests/largeworlds/gradient_signal/EditorScripts/ImageGradient_BilinearFiltering.py
```
2. Comment out the asset re-assignment lines in steps 5 and 6 of the test (lines 118 and 126):
```
vegetation.ImageGradientRequestBus(bus.Event, "SetImageAssetPath", image_gradient_entity.id, test_img_gradient_path)
```
3. Run the test:
```
python\python.cmd -m pytest --build-directory <Path to Profile Directory> AutomatedTesting\Gem\PythonTests\largeworlds\gradient_signal\TestSuite_Periodic.py::TestAutomation::test_ImageGradient_BilinearFiltering
```

**Expected behavior**
Test runs and completes as expected. The asset is initially assigned on line 107.

**Actual behavior**
The test fails without re-assigning the asset following making changes to the Advanced component properties.

**Found in Branch**
development@3d0f942eae1d7caf5eeedbfc3207af4e5223c1e2

**Comment by mbalfour-amzn** [comment]
Should be fixed with #11340
