### ISSUE TITLE
Multiplayer Connection Wont Work Unless Server Already Has Level Loaded

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9622]
**Describe the bug**
Multiplayer wont properly replicate to the client if the server isn't already inside a level when the player joins. This is confusing since you'd expect servers to be able to switch levels

**Steps to reproduce**
1. Open ServerLauncher and run > host
2. Open GameLauncher and run > connect
3. ServerLauncher > loadlevel SampleBase

**Only a very specific order of commands will work:**
Server > host > loadlevel
Game > connect

**Expected behavior**
A player spawns into client and server and client is able to control the player in the new level

**Actual behavior**
After loading into the level no player is spawned. Network entities (include level entities and player) dont spawn in for the client
ServerLauncher warning occurs "No active NetworkPlayerSpawnerComponents were found on player spawn request."

**Found in Branch**
Development latest (May 19, 2022)

**Desktop/Device (please complete the following information):**
 - OS: Ubuntu

**Comment by lmbr-pip** [comment]
Need to be hosting before loading a level (that part is not an issue).

**Comment by lmbr-pip** [comment]
@AMZN-Gene - please split into two issues.

**Comment by AMZN-Gene** [comment]
Splitting into 2 issues, see related: https://github.com/o3de/o3de/issues/9666

**Comment by yuyihsu** [comment]
@AMZN-Gene I assigned a priority to this ticket just for reporting purpose. please adjust the priority as you see fit.

**Comment by lmbr-pip** [comment]
Lets discuss, may need to migrate to feature request. Need to understand workflow. 

Unclear if this is by design, is unsupported.

**Comment by AMZN-Gene** [comment]
This is related to #10824. By not allowing hosts to change levels after a client has joined because the network spawnable isn't available, this means that ServerClients are broken as well since they both host and create a player immediately before the level is opened.
