### ISSUE TITLE
Feature Request: Clock icon on "Game Entity" event node is not meaningful for starting a node

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#9625]
**Is your feature request related to a problem? Please describe.**
Users are getting confused on how to use the Game Entity event node for starting a graph and assuming that the clock icon is referencing a timer making the icon become a mystery meat icon.

**Describe the solution you'd like**
Additional text next to the clock icon can help drive proper meaning to the field and drive better usage. Additionally, if nodes are able to link off to documentation on the node, this will additionally help users get to proper usage of a node. This portion of this suggestion is covered more in #9624.

**Comment by AMZN-daimini** [comment]
For context:
![image](https://user-images.githubusercontent.com/82231674/170557079-f0ba4f52-1e64-47ba-a199-b72e01161f44.png)
