### ISSUE TITLE
As a Dev I'm Confused Why Client.cfg and Server.cfg Aren't AutoLoaded

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9630]
**Describe the bug**
During a walk-the-engine session user was wondering why we dont automatically load client.cfg and server.cfg when opening GameLauncher and ServerLauncher. Really, cfg's are independent of launcher and are just a way to start the app and push cvars. 
This came up with the user was simply trying to host a game and let some clients join.

I think the real issue was that it requires too many steps to host and join. Ex: Open ServerLauncher > host > loadlevel > open game > connect.  This is 5 steps for a very common workflow, also these steps take time (opening apps, starting levels) further adding to stressful UX.

Suggestion: Add an IMGUI and cvar to host a level and start a client via one cmd or ImGui button.

**Comment by rainbj** [comment]
Hey @AMZN-Gene amd @lmbr-pip this sounds related to the tnew preferences panel settings that we are working but unable to deliver until RPE is done. Lets chat about this task so we can provide designs.

**Comment by AMZN-Gene** [comment]
@rainbj this is different from the new editor play mode preference panel. This is generally that in order to start multiplayer using launchers you must execute certain cvars every time they are opened. In that respect, playing multiplayer thru the editor is actually a smoother experience than via launchers. The ask here would be around improving the UX so that users don’t need to run cvars.

**Comment by lmbr-pip** [comment]
Should move .cfg files to setreg rather than invest in this area.

**Comment by AMZN-Gene** [comment]
The ImGui option to "Host Level" and "Launch Client" hopefully resolves some of the pain in having to deal with cfg since the actions to start up a host and client are now really easy. 

However, there still might be a need for cfg when developing:
With cfg's I can create multiple cfg's for different actions I want to take. For example, having a _headless_server.cfg_ and a _gui_server.cfg_ paired up with a _launch_headless_server.bat_ and _launch_gui_server.bat_.

Question: Should MultiplayerSample remove server.cfg and client.cfg? If we keep them, I propose adding a launch_server.bat and launch_client.bat just to avoid the confusion from developers wondering how they are used.

**Comment by lmbr-pip** [comment]
If we are following a .bat approach, need .sh files too for Linux/mac

Case for autoloading is complicated by server.cfg and editor spawned levels. CFGs for client and server are context sensitive so can't autoload.

Did not consider remove .cfgs due to the way .setreg rolls files up (could interfere with the autoloading behaviour). Setreg does not support some older cvar settings.
