### ISSUE TITLE
Multiplayer Editor: Server Connection Status Viewport UI

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9634]
**Is your feature request related to a problem? Please describe.**
It's hard to tell if a server is running during multiplayer editor-game mode; especially if the server is headless/running in the background

**Steps to reproduce**
1. Open a project with multiplayer gem installed
2. Ensure editorsv_enabled=true and editorsv_launch=true so that server is launched during CTRL+G 
3. Set editorsv_rhi_override=null so that the server is headless
4. CTRL+G

Once the game is running I'm unsure if the server is connected; I'm forced to either check task manager, or alt+tab over to the server window, open the console, and read logs to make sure the server is running okay

**Describe the solution you'd like**
There should be some persistent ui that is always visible while the server is connected

**Comment by lmbr-pip** [comment]
Debug text will patch this in the short term.

**Comment by AMZN-Gene** [comment]
UI should always exist in Editor, in the GameLauncher it's okay too, but needs to be removed the release.

**Comment by rainbj** [comment]
Hey @AMZN-Gene I think this would be a great idea to talk about where you think this visualization would like and where this item should live. Can we have a brainstorming session about this topic. Please invite both @bhanuja-s and @rainbj to this conversation. Thanks

**Comment by lmbr-pip** [comment]
@AMZN-Gene added Debug draw debug which shows these messages clearly in the Game viewport, when playing-in-editor mode. Text progression is:

1. Launching server
2. Editor tcp connection attempt
3. Editor is sending level server the level data packet 

cid:262164*image001.png@01D88496.60A497F0


This gives really useful guidance to the user. We could make some minor edits ie:
1. Launching server
2. Attempting to connect to server
3. Sending level data to server

**Comment by lmbr-pip** [comment]
Still needs a persistent UI element to show connection status (address and port).

**Comment by yuyihsu** [comment]
Sig-networking will propose the text to display on viewport, and sig-ui-ux will review and approve.
