### ISSUE TITLE
Feature Request : Multiplayer components in Gem for use in any project.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#9639]
**Is your feature request related to a problem? Please describe.**
Multiplayer right now is very difficult to do inside of O3DE compared to other engines. Your best bet right now is to use the multiplayer sample project for your base and work off of it, but multiplayer should be more gem based and not on a per project basis having to use templates.

**Describe the solution you'd like**
A solution is more long term, but for a start to make multiplayer more excessible to start working with it on a broader project range would be making all components that are in the multiplayer sample universal (if they are not yet) and add them in a Multiplayer Starter Content Gem. This would be a great start, and more components that come in the future can be added to this gem to allow for a more universal way of utilizing multiplayer in O3DE.

**Describe alternatives you've considered**
The only alternatives right now is using the Multiplayer Samples Project, or following the 3+ hour tutorial on youtube and edit C++ code on your project.

**Additional context**
N/A

**Comment by lmbr-pip** [comment]
SIG/Network has discussed making a starter kit: https://github.com/o3de/o3de/issues/8281 

Template request is https://github.com/o3de/o3de/issues/5730
