### ISSUE TITLE
Add Integration test for verifying PrefabPublicNotifications::OnRootPrefabInstanceLoaded sent

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#9662]
We don't have current tests in AzToolsFramework around level loading. A fixture needs to be setup and call PrefabEditorEOS. We can either build a quick json for the level in the test itself or do something like
```
AZStd::vector<char> charBuffer;
AZ::IO::ByteContainerStream<AZStd::vector<char>> stream(&charBuffer);
AZ::Utils::SaveObjectToStream<AZ::Entity>(stream, AZ::ObjectStream::ST_XML, levelObject, m_app->GetSerializeContext());
stream.Seek(0, AZ::IO::GenericStream::ST_SEEK_BEGIN);
```
to build the stream and pass it to LoadFromStream().

Once we have the above test fixture, it will be easier to add test for verifying notifications like `PrefabPublicNotifications::OnRootPrefabInstanceLoaded`.

Related GHI: #9599

**Comment by hultonha** [comment]
Bumping to critical as I believe this test infrastructure is essential and should be added sooner rather than later.
