### ISSUE TITLE
Multiplayer: As a Dev I want a Warning When Loading Network Levels At Bad Times Depending on Multiplayer Status

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9666]
**Is your feature request related to a problem? Please describe.**
The following workflow won't work, but is very easy to mistake as possible. As a dev, I want a warning whenever attempting to do the following...
_Server > loadlevel > host_

The reason this order of operation doesn't work is that when loading a networked level, the Multiplayer System still is uninitialized (ie the app doesn't know if it's a client, dedicatedserver, or clientserver).

**Describe the solution you'd like**
Check whenever a prefab (level) is loaded, and if that prefab is associated with a network.spawnable then check if the IMultiplayer system is initialized to be a client or server. If it's uninitialized, then display a prominent warning.

**Describe alternatives you've considered**
It might be good even to block loading the prefab entirely. Why would you load a network spawnable if there's no network?

**Comment by AMZN-Gene** [comment]
This came up again in WF6. There's general confusion around when it's okay to loadlevel while hosting a multiplayer session

**Comment by lmbr-pip** [comment]
Have log warnings now, need to add onscreen debug text to make this more visible
