### ISSUE TITLE
Visual artifacts are displayed after editing terrain

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#9684]
**Describe the bug**
Editing the terrain with the height value changed leaves some visual artifacts.
Entering and leaving Game Mode removes the artifacts.

**Steps to reproduce**
1. Add Terrain Gem and rebuild the project.
2. Create a new level.
3. Add Terrain World and Terrain World Renderer to the Level.prefab.
4. Create an Entity (A) and add Constant Gradient component to it.
5. Create an Entity (B) and add components: Terrain Layer Spawner, Axis Aligned Box Shape and Terrain Height Gradient List.
6. Set the Entity (A) as a target for Terrain Height Gradient List component.
7. Move Entity (B) so it collides with the terrain.
8. Use Translate Manipulator to move the Entity (B) around the horizontal plane.

**Expected behavior**
The hill borders are adjusted to the Box Shape component.

**Actual behavior**
Visual artifacts are left in the Viewport after moving the Entity (B).

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/169526166-e6836a7a-5092-477e-94df-2b7c7ff5d131.mp4

**Found in Branch**
Development (0038f82)

**Desktop/Device:**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU Nvidia GeForce RTX 2060 SUPER
Memory 16GB

**Comment by mbalfour-amzn** [comment]
A few of the commits from last week fixed this.
