### ISSUE TITLE
bone based animations do not import properly

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de#9695]
the way animations are supposed to look: fbx file format - actor just has 1 root bone
translation only
![ApplicationFrameHost_85Bs6xBdSf](https://user-images.githubusercontent.com/48143120/169616205-8aa9cd35-a245-4052-8f2b-2e70bc27ac0a.gif)

rotation only
![ApplicationFrameHost_RuPLPqiYhA](https://user-images.githubusercontent.com/48143120/169616213-e0f2d354-9a51-41d4-9a9c-e186bcccf66f.gif)

scale only
![ApplicationFrameHost_7aoDRO1824](https://user-images.githubusercontent.com/48143120/169616220-7d70da59-a707-4b67-9f20-f49074b0d832.gif)

how it looks in game: actor component with simple motion
![Editor_abqkxwCGGC](https://user-images.githubusercontent.com/48143120/169616527-92618603-40ba-4aa3-8b80-f3f8a516d960.gif)

as u can see, the rotations are multiplied by a lot so it completely breaks the animations

idk whats happening with the scaling version

translation only is working as i expect

please fix please since it is super important... the engine is completely unusable for me for this reason

currently the only animations that work is some mixamo stuff with a 3rd party blender plugin fix and the default included animations otherwise everything iv tried imported animations fbx doesnt work

blender default, houdini, maya - all have similar problems when importing animation into o3de, so it should be o3de side problem

**Comment by GraphiteSIX** [comment]
Hey I want to help test this issue but it be really helpful if you can upload the assets and the repro steps.
I have searched GHI and couldn't find a repro for these issues and the assets I have made in blender do not show the skin when upgraded/converted to an actor.
It is possibly my inexperience in 3d modelling techniques.
I am fairly new but have a decent amount of time to test, analyse and provide evidence  just need that seed to start it off,
I understand if you can't supply the assets and the repro and I will still pursue this GHI.

**Comment by lmbr-pip** [comment]
@ppinfel Please let us know if you can share assets to test this with

**Comment by shawstar** [comment]
Well. I did a test and found that Blender will have the Default Apply Scalings set to 'All Local' and seems to tilt the root bone node rotation. It should be set to 'FBX Unity Scale' instead. This seems to solve the Rotation issue.
![image](https://user-images.githubusercontent.com/87207603/169917169-81c50cd5-92aa-4e38-ada1-31f47133a3a7.png)

**Comment by hultonha** [comment]
@ppinfel Could you please respond to the questions for more info. If we don't hear anything back by 2022/06/27 we will close this issue.

If additional info is added after that date we will reopen the issue. Thanks for your time!

**Comment by hultonha** [comment]
Closing as no further information has been provided.
