### ISSUE TITLE
Broken fbx asset that failed to compile crashes editor when skinning changed to linear.

### ISSUE THREAD

**Issue by GraphiteSIX** [o3de/o3de#9700]
**Describe the bug**
I will be honest I have no idea what I'm doing with fbx models and animations but I'm sure that the simple location transform should work in the editor.
I tried to convert fbx model to an actor and failed but when evaluating the actor tool menu I had a crash when changing skinning to linear.
On further testing even if the asset doesn't fail the editor still crashes.
Looking at the documentation "The source asset must contain at least one bone and a skinned mesh." so I think this might be an issue when no check or warning is given.

**Steps to reproduce**
1. Transfer fbx model into asset folder
2. Create actor from model
3. Create entity 
4. Select fbx actor.
5. Choose linear from dropdown menu

**Expected behavior**
A Warning.

**Actual behavior**
Editor Crash
**Assets required**

[21-05_Anim.zip](https://github.com/o3de/o3de/files/8747228/21-05_Anim.zip)

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Development (#9670)

**Desktop/Device:**
 - Device: [PC] 
 - OS: [Windows]
 - Version [Microsoft Windows 11 Pro Version 10.0.22000 Build 22000]
 - CPU [AMD Ryzen 7 3800X ]
 - GPU [Radeon RX 580]
 - Memory [32GB]

**Comment by GraphiteSIX** [comment]
When importing an actor in the viewport nothing is shown and you cannot apply a material to it.
I compared to the 2205 release and the asset was visible.
So something has happened since 2205 and now.

**Comment by hultonha** [comment]
Poking @amzn-tommy to see if there's any update on this or if you need support from the character/animation team. Thanks!

**Comment by GraphiteSIX** [comment]
@hultonha 
I am just revisited this and believe it is partially my fault in not knowing how to export from DCC and how to import to o3de.
Saying that the model should fire off warnings and fail to import if possible and not crash the editor.
What was confusing is it is visible in 22.05.
Commit https://github.com/o3de/o3de/commit/7c0e902a8a01f652345a29be68050d5bba52f4ec  currently adds asserts:
<17:20:16> [Error] (ProcessSkinInfluences) - Actor 'cube_loc.actor' lod '0' has no skin influences, and will be stuck in bind pose.
<17:20:16> [Error] (SkinnedMeshInputBuffers) - Out of memory to create a skinned mesh instance. Consider increasing r_skinnedMeshInstanceMemoryPoolSize
<17:20:16> [Warning] (AtomActorInstance) - Failed to create target skinned model. Will automatically attempt to re-create when skinned mesh memory is freed up.
<17:20:16> [Warning] (Mesh) - Mesh does not have all the required input streams. Missing 'SKIN_JOINTINDICES0'.
<17:20:16> [Warning] (Mesh) - Mesh does not have all the required input streams. Missing 'SKIN_WEIGHTS0'.
<17:20:16> [Error] (ProcessSkinInfluences) - Actor 'cube_loc.actor' lod '0' has no skin influences, and will be stuck in bind pose.
<17:20:16> [Error] (SkinnedMeshInputBuffers) - Out of memory to create a skinned mesh instance. Consider increasing r_skinnedMeshInstanceMemoryPoolSize
<17:20:16> [Warning] (AtomActorInstance) - Failed to create target skinned model. Will automatically attempt to re-create when skinned mesh memory is freed up.

And still crashes when changing skinning but to be fair the model isn't up to o3de spec and changing the skinning is referencing nothing so it will crash.

**Comment by hultonha** [comment]
Thanks for the additional info @GraphiteSIX, this is really helpful. Tagging @amzn-rhhong and @amzn-tommy for visibility. I know Roman has been looking at this recently but might not have time right now to dig into it. We'll keep you updated :+1:

**Comment by amzn-jillich** [comment]
Closing as https://github.com/o3de/o3de/pull/11189 fixed the issue.
