### ISSUE TITLE
Release 2205 (EMotionFX.Editor) : UninitializeDynamicModule) Crash

### ISSUE THREAD

**Issue by GraphiteSIX** [o3de/o3de#9701]
**Describe the bug**
While using emotionfx editor and testing out features I attempted to extract motion data with record and the editor crashed. 

**Steps to reproduce**
Extract data and record.

**Expected behavior**
Not to crash.

**Actual behavior**
A crash.

**Assets required**
In the zip below
[2205_Install_Crash.zip](https://github.com/o3de/o3de/files/8747715/2205_Install_Crash.zip)

**Found in Branch**
Release 2205

**Desktop/Device:**
 - Device: [PC] 
 - OS: [Windows]
 - Version [Microsoft Windows 11 Pro Version 10.0.22000 Build 22000]
 - CPU [AMD Ryzen 7 3800X ]
 - GPU [Radeon RX 580]
 - Memory [32GB]

**Additional context**
Sorry no full repro or media capture but only can log dumps/assets/logs at this time, I will revisit and try to make a clearer repro instructions soon

**Comment by hultonha** [comment]
Tagging @amzn-rhhong for visibility to take a look at this issue if possible (also tagging @amzn-jillich for visibility)

**Comment by hultonha** [comment]
@GraphiteSIX - we reviewed this in sig/simulation triage, if you do have any additional info or repro steps to add that would be very helpful

**Comment by GraphiteSIX** [comment]
@hultonha Unfortunately I haven't any steps to repro this and didn't have the understanding I do now of how important It is to capture and supply all the info.
I totally understand and advise to close this as there has been so many updates to the emotionfx editor I doubt the dump is relevant now but leave that up to you.

**Comment by hultonha** [comment]
> @hultonha Unfortunately I haven't any steps to repro this and didn't have the understanding I do now of how important It is to capture and supply all the info.
> I totally understand and advise to close this as there has been so many updates to the emotionfx editor I doubt the dump is relevant now but leave that up to you.

No worries @GraphiteSIX, thanks for the info! I'll leave this open for now and see if it comes up again, if we don't see it again anytime soon we can close in a couple of weeks. Thanks for your help!

**Comment by amzn-jillich** [comment]
Closing as there is no known way to reproduce the issue.
