### ISSUE TITLE
Material preview in Material component is not updated after editing source material

### ISSUE THREAD

**Issue by LB-HubertUberman** [o3de/o3de#9709]
**Describe the bug**
After editing source material, the preview in the Material component is not updated with the saved changes. Note that after re-assigning the material, the preview is displayed with no issue. The issue occurs both on Windows and Linux.

**Steps to reproduce**

1. Create an entity.
2. Add the Mesh component and assign any mesh asset to it.
3. Add the Material component and assign any material asset to it.
4. Right-click on the material preview and select Edit Source Material.
5. In Material Editor make any changes to the material and save.

**Expected behavior**
Material preview in the Material component is updated with changes made to the source material.

**Actual behavior**
Material preview in the Material component is not updated with changes made to the source material.

**Video**

https://user-images.githubusercontent.com/96232062/169785519-30a8c4ea-ce12-4abf-9b41-daa092699ad4.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/0fe387cd1dc05deaee8456d2c53cf691f3526fc4)

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by lmbr-pip** [comment]
Assuming this could be related to hot reload so adding feature/asset-pipeline so we can track issue. Please remove label if not related to hot reload

**Comment by amzn-mike** [comment]
I'm not that familiar with the material editor, but I just wanted to add, if you instead click "edit material instance" everything works as expected.  There might be a missing notification from source update -> instance

**Comment by gadams3** [comment]
Correct. Handling the source file change notification in the editor material component should take care of this.
