### ISSUE TITLE
Track View keyframe attributes cannot be modified

### ISSUE THREAD

**Issue by lanbingluyu** [o3de/o3de#9712]
Describe the bug
In Track View, right-click a key frame and choose Edit On Spot from the shortcut menu. The black box is displayed. The key frame attributes cannot be modified. The properties screen cannot be displayed.

Steps to reproduce
1.Open Track View.
2.Create a new sequence "seq".
3.Add Shader Ball to the sequence.
4.Add keyframes to Shader Ball's Position.
5.Right-click the keyframe.

Expected behavior
The attributes of the Position key of Shader Ball can be modified.

Actual behavior
The attributes of the Position key of Shader Ball cannot be modified.

**Comment by Ulrick28** [comment]
Transferred issue to O3DE, where it can be triaged to the appropriate sig.

**Comment by monroegm** [comment]
@lanbingluyu  Is this still an issue on latest development?
