### ISSUE TITLE
No warning or assert in script canvas when part of it not functioning.

### ISSUE THREAD

**Issue by GraphiteSIX** [o3de/o3de#9736]
**Describe the bug**
Looked into this but its way above my abilities.
The script I have made doesn't seem good quality because I am just haphazardly deleting the first element and this could be an issue with a weak pointer but if you set the delay timing too quick (< 0.03) then the (de)spawn and erase part of the graph ceases to function there is no assert or warning for this but the on screen evidence is obvious proof.
Not sure what is happening in the background as processes must be being dumped somewhere is this a mem leak?
**Steps to reproduce**
1. Transfer supplied script and prefab into project folder
2. Create new level
3. Import  prefabs and select script in spawner
4. Start level observe
5. Change delay and start level and observe

**Expected behavior**
Assert when part of the script is not functioning
**Actual behavior**
No assert when (de)spawn and erase not functioning below a level

**Assets required**
[Timer_Too_Quick.zip](https://github.com/o3de/o3de/files/8761610/Timer_Too_Quick.zip)

**Screenshots/Video**
I can update if needed

**Found in Branch**
Development pull (#9603)

**Desktop/Device:**
 - Device: [PC] 
 - OS: [Windows]
 - Version [Microsoft Windows 11 Pro Version 10.0.22000 Build 22000]
 - CPU [AMD Ryzen 7 3800X ]
 - GPU [Radeon RX 580]
 - Memory [32GB]

**Additional context**
Any other details required let me know

**Comment by GraphiteSIX** [comment]
I retested this issue firstly with a different setup.
![MultiColorSpawner](https://user-images.githubusercontent.com/105223355/172051906-3ce16e36-a828-4198-9ec9-b8d487242312.png)
![SpawnMe_SC](https://user-images.githubusercontent.com/105223355/172051912-2b29f6c1-f72d-40a9-b7cd-18c34f273763.png)
As you can see it is much more complex and has no delay and I thought the issue had been taken care of.
But to make sure I reimported the original assets in and retested and found the same original issue.
Making the setup more complex added small amounts of delay to it it seems but not noticeable
With the more complex setup I can get 1400 shapes in editor without frame drop but with the original I can get 256.
I thought It maybe a mistake or inefficiency in the scriptcanvas which there was a couple but after rebuilding from scratch it made no difference.
![Spawn_After](https://user-images.githubusercontent.com/105223355/172051943-cdb51b83-c588-46b8-87ae-fe2b661b575a.png)
Not sure on suggesting a way forward here but believe this issue needs addressing at some point in time.
Here are the updated scriptcanvas.
[SuperSpawner_Logic.zip](https://github.com/o3de/o3de/files/8840007/SuperSpawner_Logic.zip)

**Comment by onecent1101** [comment]
I have tested the delay node without spawning prefab, the behavior looks correct to me.
There are some guesses for your graph:
1. Both Spawn and Despawn complete are asynchronous actions, and you are nested these two actions, so the behavior is hard to control (which may not behave as you expect, and you should know as you try to Despawn prefab under OnSpawnComplete, you basically queue up bunch of async jobs)
2. Not sure what you want to achieve here, but if you want to limit 1400 spawned prefabs in your scene, one simple approach is to have an array size check before Spawn like check array size <= 1400, and use OnTick node to remove oldest prefab with check like array size >= 1400

**Comment by GraphiteSIX** [comment]
@onecent1101 I understand the suggestions to improve the graph and will test them.
Regards the 1400 I was just investigating managing manual garbage collection of prefab spawning and seeing the max amount before frames drop below 60fps.
What I couldn't understand is why a a less complex graph with more set delay was unable to produce less than quarter of the spawned objects.
This suggestion maybe a feature so out of scope of this GHI and I understand checks can hit performance but maybe if possible the debugger detects queued events that haven't fired.
Also I believe there has been talk about documenting managing spawn tickets and your advice and suggestions should really be included.
 I will close this issue if you think no action needs to be taken.
Thanks.

**Comment by GraphiteSIX** [comment]
Ok I found why there is a performance difference.
I found if you have a box shape with game view set to true as the spawning object it takes a massive performance hit.
If you have a mesh added also you don't have the performance hit.
Interesting that if you have the filled option on the shape set to false it doesn't show the wireframe and doesn't seem to be as inefficient but still loses frames really early compared to the mesh spawn object.
Not sure if another GHI needs to made to highlight this issue

**Comment by onecent1101** [comment]
I don't think you need to do GC manually, as ScriptCanvas translated graph into LUA script and execute script directly on backend. (And LUA does automatic memory management, refer to https://www.lua.org/pil/17.html)

But ScriptCanvas won't help to despawn entity unless you specifically ask system to do it by using Despawn node. In your graph, you just remove the SpawnEntityTicket from list (which you will lose the track of spawned entity ticket) but don't despawn corresponding entity, so spawned entity will still be there until it hits certain cap of spawning system if there is.

I have modified your graph which can provide better result by spawning entities in rows and columns, feel free to use it.
[SuperSpawner_Logic.scriptcanvas.zip](https://github.com/o3de/o3de/files/8855581/SuperSpawner_Logic.scriptcanvas.zip)

![superspawn](https://user-images.githubusercontent.com/5900509/172450409-690fc1bc-26ad-4ac9-89e0-ddddc93d4c3d.PNG)


https://user-images.githubusercontent.com/5900509/172453059-1bac8c93-ddc0-4f19-8c76-7c932c0868f1.mp4

I think there is no further question regarding ScriptCanvas, but feel free to check with @AMZN-mnaumov for prefab spawning questions

**Comment by GraphiteSIX** [comment]
@onecent1101 Your right I totally missed the despawn I have fixed now.
![Corrct_DeSpawning](https://user-images.githubusercontent.com/105223355/172461723-2313a9f4-97ef-4c8c-a13f-4b06096f257a.png)

Sorry by manual garbage collection I mean the SpawnTicket gets cleaned up by Lua after some arbitrary time so you need to cache it and dispose of it yourself.
Otherwise The entity just despawns whenever Lua feels like cleaning up.
I don't think there is a spawn cap I haven't hit one anyway.
What about the perfomance hit that when a shape gameview is true it decreases perfomance to 25% ?
I didn't think a mesh and material would outperform a basic filled shape or is that incorrect.

**Comment by GraphiteSIX** [comment]
https://user-images.githubusercontent.com/105223355/172471154-993d0778-d44f-4b5e-8d5d-c9928b412609.mp4

https://user-images.githubusercontent.com/105223355/172471197-4dfd73b3-32e2-43f4-91af-ec04f0fc1b04.mp4

**Comment by AMZN-mnaumov** [comment]
> @onecent1101 Your right I totally missed the despawn I have fixed now. ![Corrct_DeSpawning](https://user-images.githubusercontent.com/105223355/172461723-2313a9f4-97ef-4c8c-a13f-4b06096f257a.png)
> 
> Sorry by manual garbage collection I mean the SpawnTicket gets cleaned up by Lua after some arbitrary time so you need to cache it and dispose of it yourself. Otherwise The entity just despawns whenever Lua feels like cleaning up. I don't think there is a spawn cap I haven't hit one anyway.

Yes you are correct, using Despawn node forces entity to despawn immediately, however losing reference to a ticket lets Lua GC take care of it. On C++ side when tickets are destroyed, anything spawned by them will get automatically despawned. There is no limit to number of entities you can spawn at once.

Regarding game view, setting it looks like once enabled it adds BoxShapeDebugDisplayComponent, Ill check with rendering team to see what's going on there and why it's slow.

**Comment by GraphiteSIX** [comment]
@AMZN-mnaumov Thanks for looking into this and sorry about all the questions.
One other thing to ask the rendering team is the wireframe does not show with visible or gameview set to true.
 I believe it should show the wireframe in both editor and gameview.

**Comment by AMZN-mnaumov** [comment]
from rendering team:
```
It's not ideal that AuxGeom is slower than a native mesh but also not totally surprising.
AuxGeom geometry data is generated on the gpu and then transfered to the gpu. That is generally a slower operation that just sending a draw ref to existing gpu data.
It's worth filing a ghi on the perf issue, but I'm not sure how high AuxGeom is on our performance optimization priority list.
```

**Comment by GraphiteSIX** [comment]
Thanks for the response and sorry for the lack of knowledge on my part I will close this issue now.
