### ISSUE TITLE
Game Controller Assignment not visible normally

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#9759]
[Migrated from JIRA LYN-10929]

Provide a detailed description of the defect here and include any possible workarounds.

----

Found in Build: EMotionFX/MeshSerialization

**Reproducibility**: 3/3 

Prerequisites: Game Controller plugged in

Steps to Reproduce:
1. Open Animation Editor
2. Choose an Actor and Animgraph
3. Open Game Controller Window
4. Try to assign a parameter to a controller button or position

**Expected Result**:

Pos X, Pos Y immediately Visible

**Actual Result**:

Have to expand the window to 3x the original size to see the options

![_thumb_210584](https://user-images.githubusercontent.com/82228511/170283951-4c2bea41-f1df-468f-bb9b-1e2e85af1e05.png)

https://user-images.githubusercontent.com/82228511/170283954-3f408275-5354-41a6-975e-2fb3f0ff3412.mp4

**Comment by hultonha** [comment]
@amzn-jillich This issue may soon no longer be relevant with the unified inspector window work, just making you aware. Thanks!

**Comment by amzn-jillich** [comment]
Closing as the game controller window got removed already as part of the unified inspector window. Script Canvas is the way to hook in input to the animation system.
