### ISSUE TITLE
Editor Crashes When Placing a Skinned Actor Without UV Maps

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#9768]
[Migrated from JIRA LYN-8966]

----

**Found in Build**: Development 9ee60e6eba

**Reproducibility**: 5/5

**Prerequisites**: 
 * Project built
 * Editor built

**Steps to Reproduce**:
 - Launch the Editor
 - Create a new level
 - Drag&Drop a skinned entity which does not have UVs (no uvs have been mapped for the entity in the DCC tool)

**Expected Result**:

Entity loads correctly or error message requiring UV's for skinned meshes is presented.

**Actual Result**:

Editor crashes.

[AP_GUI.log](https://github.com/o3de/o3de/files/8772087/AP_GUI.log)
[Editor.log](https://github.com/o3de/o3de/files/8772091/Editor.log)
[error.log](https://github.com/o3de/o3de/files/8772092/error.log)
[bean.fbx.txt](https://github.com/o3de/o3de/files/8772094/bean.fbx.txt) (remove .txt extension to load)

**Comment by nick-l-o3de** [comment]
I actually get a GPU DEVICE REMOVED if I use that asset, weird

**Comment by nick-l-o3de** [comment]
This is fixed around https://github.com/o3de/o3de/pull/18119 - not sure if that fixes it, but it doesn't crash for me.
