### ISSUE TITLE
Upgrade NumPy to version 1.21 or later

### ISSUE THREAD

**Issue by allisaurus** [o3de/o3de#9770]
**Describe the bug**
NumPy needs to be updated to version 1.21 or later. For example: `numpy>=1.21`

See https://github.com/advisories/GHSA-6p56-wp2h-9hxr . Advisory rates this as a "Moderate", so suggest treating as "priority/major".

**Steps to reproduce**
1. Go to https://github.com/o3de/o3de/blob/development/python/requirements.txt#L110
2. See that NumPy is at 1.18.1

**Expected behavior**
* known python issues are patched

**Actual behavior**
* issue is not patched

**Assets required**
N/A

**Screenshots/Video**
N/A

**Found in Branch**
All branches

**Comment by allisaurus** [comment]
Assigning to `sig/testing` as I've seen for previous issues with _requirements.txt_, but please reroute if appropriate.

**Comment by lmbr-pip** [comment]
Should we move issue to sig-graphics-audio or sig-testing? Dependabot can auto update: https://github.com/o3de/o3de/pull/9863 but obviously this needs testing.

**Comment by Kadino** [comment]
If automated tests pass when https://github.com/o3de/o3de/pull/9863 is run through Jenkins, then it should be good to go. I see no other testing requirements, as this is only used by Graphics automated tests.

**Comment by Kadino** [comment]
In my opinion, the automated tests should be sufficient. As far as those other Atom tools scripts, I'm tempted to say "if you liked it then you should have put a test on it"

**Comment by lmbr-pip** [comment]
Numpy was updated to 1.23.0  - https://github.com/o3de/o3de/blob/development/python/requirements.txt#L110
