### ISSUE TITLE
UI Canvas asset uses ui editor instead of game view for changes.

### ISSUE THREAD

**Issue by KylerSF** [o3de/o3de#9771]
**Describe the bug**
When you use a ui canvas asset and say you hook up an image on button click to change color, if you go into game view and click the button, the image will change color, if you have the asset opened up in the ui editor and play in game view and click the button nothing happens in the editor, but in the ui editor the image changes color. So it prioritizes changes even in game view to the editor's ui editor, and these changes get saved after leaving game view.

**Steps to reproduce**
1. Go to UI Editor and make a new graph with an image, and tag component, and another with script canvas component.
2. Click on the script canvas component and create a new graph that has On Graph Start --> Time Delay (1 tick) --> Get entity by tag (tag name from ui image) --> change color (ui image) and pick a color.
3. Close the UI Editor and play the game in game view, everything should work fine.
4. Now open the UI Editor and try again in game view and you should see nothing happen in game view, but look at the ui editor and see how it has changed their instead. Which also saves the changes made so the color will stay when leaving game view.
5. See error

**Expected behavior**
All game view actions are done in game view, and not utilizing other editors (ui editor) while in game view.

**Actual behavior**
A clear and concise description of what actually happened.
The UI editor when opened with the canvas is used instead of game view which alters any parameter changed in game view which makes development with the ui impossible in most use cases.

**Assets required**
Provide sample assets needed to reproduce the issue.
N/A

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.
N/A

**Found in Branch**
Name of or link to the branch where the issue occurs.
Development Branch

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
N/A

**Comment by ParasiteSt** [comment]
I believe this will also solve this issue https://github.com/o3de/o3de/issues/9209
