### ISSUE TITLE
Jinja2 should be upgraded to 2.11.3 or later

### ISSUE THREAD

**Issue by allisaurus** [o3de/o3de#9775]
**Describe the bug**
Jinja2 needs to be upgraded to version 2.11.3 or later. For example: `jinja2>=2.11.3`

See https://github.com/advisories/GHSA-g3rq-g295-4j3m . Advisory rates this as a "Moderate", so suggest treating as "priority/major".

**Steps to reproduce**
1. Go to https://github.com/o3de/o3de/blob/development/python/requirements.txt#L63
2. See that Jinja2 is at 2.11.2

**Expected behavior**
* known python issues would be patched.

**Actual behavior**
* issue is not patched.

**Assets required**
N/A

**Screenshots/Video**
N/A

**Found in Branch**
All branches

**Comment by dshmz** [comment]
sig/core, do we have any updates on this issue?

**Comment by byrcolin** [comment]
Done. upgraded to 3.1.2
