### ISSUE TITLE
Set Material Override needs Slice?

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#9777]
**Describe the bug**
In Script Canvas the Set Material Override node has an Asset ID, but brings up a menu to pick a dynamic slice which is no longer supported in O3DE.

**Steps to reproduce**
1. Go to Script Canvas and make a new graph
2. Create a new node called "Set Material Override"
3. Select the Asset ID folder in the node

**Expected behavior**
It brings up the correct menu when opening the Asset ID up.

**Actual behavior**
It brings up an old Dynamic Slice menu.

**Assets required**
N/A

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/100494538/170416973-448588a5-95c5-421b-becc-514e3a0f9b3a.png)

**Found in Branch**
Development Branch

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows
 - Version 10
 
**Additional context**
N/A

**Comment by gadams3** [comment]
This issue is now duplicated by https://github.com/o3de/o3de/issues/11307
