### ISSUE TITLE
Axis Aligned Box Shape and PhysX Heightfield Collider indicate generated collision inconsistently

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#9781]
**Describe the bug**
Neither the Axis Aligned Box Shape, nor the PhysX Heightfield Collider colliders show accurate representation of the generated collision area on the Terrain. Only the wireframe generated by the `physx_debug 1` command shows the true colliders. When exiting the Game Mode, the wireframe drawn by the Terrain World Debugger's Show World Bounds property is also distorted around the area indicated by the PhysX Heightfield Collider's Draw collider property.

**Prerequisites**
* Terrain Gem and PhysX Debug Gem added to the project.
* Terrain World, Terrain World Debugger, and Terrain World Renderer components added to the <level>.prefab

**Steps to reproduce**
1. Create "Rigid Body" entity, add Box Shape (Game View enabled), PhysX Shape Collider, and PhysX Rigid Body components to it.
2. Create "Heightfield Collider" entity, add Axis Aligned Box Shape (Dimensions set to [5, 5, 5], Game View enabled), PhysX Heightfield Collider (Draw collider enabled), Terrain Physics Heightfield Collider, Terrain Layer Spawner, and Terrain Height Gradient List (add an element to the Gradient Entities, and choose any entity with the element's entity picker).
3. Execute `physx_debug 1` command in the Console.
4. Place the "Heightfield Collider" entity so that it intersects with the Terrain generated by the level mentioned in the **Prerequisites**.
5. Place the "Rigid Body" entity so that it is above the edges of the collider drawn by the `physx_debug 1` (magenta color).
6. Enter the Game Mode.
7. Exit the Game Mode.

**Expected behavior**
All of the drawn colliders show the same area of the terrain. The wireframe drawn by the Terrain World Debugger's Show World Bounds property is consistent when entering/exiting the Game Mode.

**Actual behavior**
All drawn colliders show different area, and only the `physx_debug 1` shows the real collider. On exiting the Game Mode the wireframe drawn by the Terrain World Debugger's Show World Bounds property gets distorted.

**Video**

https://user-images.githubusercontent.com/86952082/170483164-c60bbbf0-1482-4d4f-8bb4-08eacab9a381.mp4

**Found in Branch**
Development (146b2c8)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by greerdv** [comment]
Tagging @mbalfour-amzn and @SergeyAMZN

**Comment by mbalfour-amzn** [comment]
@LB-ArturZieba I believe this got fixed last week with https://github.com/o3de/o3de/commit/2c966ccac8dfbf0cecf9ccfa6adc36e87bfb6c56, can you please retest it?

**Comment by monroegm** [comment]
@LB-ArturZieba please reopen if this is not fixed

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization/2210 (021d32a) build.
