### ISSUE TITLE
Script Canvas assets fail to save due to JSON serialization error

### ISSUE THREAD

**Issue by BytesOfPiDev** [o3de/o3de#9788]
**Describe the bug**
Adding the Script Canvas node "Entity/Game Entity/On Entity Deactivated" or  "Entity/Game Entity/On Entity Deactivated" to any Script Canvas file, saved or unsaved, generates an error:

`Failed to save Untitled-1^: Save asset data to temporary file failed: JSON serialization failed to save source: The operation has taken a partially alternative approach for a retrieve info operation because the action was unsupported`

**Steps to reproduce**
1. Open a new or existing Script Canvas file.
2. Add the node: Entity/Game Entity/On Entity Activated.
3. CTRL + S to save or save from the file menu.
4. See error.

**Expected behavior**
After adding a node to a graph, I should be able to save the asset.

**Actual behavior**
Adding the mentioned node prevents the asset from being saved.

**Assets required**
Any script canvas asset - new or existing.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/47983418/170535433-d3644a41-189d-4ca9-b92c-cc088591ddec.png)

**Found in Branch**
Nightly build downloaded on 5/25/22.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 7 3700x
 - GPU Nvidia 3070 FE
 - Memory 64GB

**Additional context**
When the file fails to save, it leaves a file behind where I tried to save it, such as "$tmp3548_Untitled-1.scriptcanvas":

![image](https://user-images.githubusercontent.com/47983418/170536191-1c56ab2a-fa4b-4bff-90d2-baae172572d6.png)

They're all empty files.

I also had this happen when I created a custom Script Canvas node using the NodeFunctionGeneric macros: https://github.com/o3de/o3de/blob/f8379e7c24dacb03fe9faeadb4c046205ee8b545/Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/NodeFunctionGeneric.h

**Comment by BytesOfPiDev** [comment]
It looks like the following line of code causes the issue:
```
serializeContext->Class<AZStd::vector<AZ::Crc32>>()->Attribute(AZ::Edit::Attributes::EnableForAssetEditor, true);
```

I was attempting to make an array of Tags(Crc32) available for use in the AssetEditor. 

(Sorry for the close/re-open, misclick)

**Comment by carlitosan** [comment]
@BytesOfPiDev is the bug still active?

**Comment by BytesOfPiDev** [comment]
> @BytesOfPiDev is the bug still active?

No, it's no longer active. It seemed to stem from me improperly trying to reflect `AZStd::vector<AZ::Crc32>` for use in the asset editor as a parameter. Which I still can't do, but that's a separate issue.
