### ISSUE TITLE
Terrain: Setting specific fractional values at Height Query Resolution results in crash

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#9801]
**Describe the bug**
When both Terrain World Renderer and Terrain World components are added, setting fractional values at Height Query Resolution may result in crash, but not in all of the cases. Reproduction rate was 8/10 and it occurred randomly with no specific values found that did not cause the crash (except for any values with .5).
Issue is active on Linux with lower reproduction rate. It did not occur on Windows when engine was built with a source configuration.

**Prerequisites:**
1. O3DE built with the Pre-Built SDK configuration on Windows or Source on Linux.
2. Project with Terrain Gem added.

**Steps to reproduce**
1. Create an entity, add Terrain World and Terrain World Renderer components.
2. Set Height Query Resolution value to any fractional value (other than .5).
3. If crash did not occur, delete components, add them again and repeat step 2.

**Expected behavior**
Editor remains stable.

**Actual behavior**
Editor crashes.

**Callstack**
```
Call Stack Trace:
 7) 00007FFAD897FF27 (KERNELBASE) : UnhandledExceptionFilter
 6) 00007FFADAB951B0 (ntdll) : memset
 5) 00007FFADAB7C766 (ntdll) : _C_specific_handler
 4) 00007FFADAB9209F (ntdll) : _chkstk
 3) 00007FFADAB41454 (ntdll) : RtlRaiseException
 2) 00007FFADAB90BCE (ntdll) : KiUserExceptionDispatcher
 1) C:\o3de\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\Model\Model.cpp (62) : AZ::RPI::Model::GetLods
Exception Code: 0xC0000005
Exception Addr: 0x0033:0x00007FFA2A4D7E07
Exception Module: 
Exception Description: EXCEPTION_ACCESS_VIOLATION, Attempt to read from address 0x00000208

The memory could not be "read"
```

**Video**

https://user-images.githubusercontent.com/100559077/170658313-6de7bc8f-03ea-4802-98ad-b9cd91bb72d6.mp4

**Found in Branch**
Development (58adaf9)

**Desktop:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Additional files**
[Editor.log](https://github.com/o3de/o3de/files/8784998/Editor.log)
[error.log](https://github.com/o3de/o3de/files/8784999/error.log)
[error.zip](https://github.com/o3de/o3de/files/8785006/error.zip)

**Comment by mbalfour-amzn** [comment]
I suspect this was already fixed last night with https://github.com/o3de/o3de/pull/9731 - it no longer uses RPI Models, and it doesn't seem to exhibit the same behavior. I can't reproduce locally with this change, and is also likely why you couldn't reproduce from source, since the commit you're using contains that change (https://github.com/o3de/o3de/commit/58adaf902fe46cdea187efd6766faf7c3d807364) . Maybe the pre-built version was built prior to this commit?

**Comment by jckand-amzn** [comment]
I'm unable to reproduce this on development@0572ff0c9c8d3eae92392c97cd427e7a319fd710. Was hitting some asserts before grabbing latest, but no crash. Change 2c966ccac8dfbf0cecf9ccfa6adc36e87bfb6c56 appears to have resolved the asserts.

**Comment by LB-BartoszCwiek** [comment]
Verified the issue does not occur in Development (a53a366). Unable to reproduce the crash by setting fractional values at Height Query Resolution. Closing the issue.
