### ISSUE TITLE
PhysX Heightfield Collider component has different properties before adding required components

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#9804]
**Describe the bug**
If the PhysX Heightfield Collider component is added to an entity that does not contain its required components (Terrain Physics Heightfield Collider, and in turn Axis Aligned Box Shape), it shows different properties, than those that are available to use when all required components are added. It should be noted that removing required components does not change the properties of the PhysX Heightfield Collider component back.

At the end of the attached video there is an unrelated assert shown. The relevant issue can be found here: https://github.com/o3de/o3de/issues/9735.

**Prerequisites**
Terrain Gem added to the project.

**Steps to reproduce**
1. Create an entity, and add PhysX Heightfield Collider component to it (note what properties it contains).
2. Click on the Add Required Component button, and add the required Terrain Physics Heightfield Collider component (note what properties the PhysX Heightfield Collider component contains). 
3. In the Terrain Physics Heightfield Collider component click on the Add Required Component button, and add the required Axis Aligned Box Shape component (note what properties the PhysX Heightfield Collider component contains).

**Expected behavior**
PhysX Heightfield Collider component shows the same properties when first added, as when all required components are added.

**Actual behavior**
PhysX Heightfield Collider component shows different properties when first added to an entity without the required components.

**Video**

https://user-images.githubusercontent.com/86952082/170698061-b52332cf-d067-41fe-9606-0b8532035fc5.mp4

**Found in Branch**
Development (58adaf9)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by amzn-leenguy** [comment]
These screenshots are from the video: The component card changes from offering a particular group of fields to a new set after. Very strange!

![Screen Shot 2022-05-27 at 9 11 32 AM](https://user-images.githubusercontent.com/82846749/170737885-e3bd7b81-2ce3-45fa-9198-b26a2f4c31c8.png)
![Screen Shot 2022-05-27 at 9 11 39 AM](https://user-images.githubusercontent.com/82846749/170737897-a926d4e0-d0f0-45e7-85f3-8320f66c23e2.png)

**Comment by amzn-leenguy** [comment]
@o3de/sig-simulation Since this feature belongs to you, can you confirm this is working correctly?

**Comment by amzn-leenguy** [comment]
I have a feeling that the second screenshot i posted should be the default value when a user creates this component, but i may be wrong.

**Comment by SergeyAMZN** [comment]
Thanks for discovering the issue. I confirmed & fixed it (PR coming shortly)

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (a53a366) build.
