### ISSUE TITLE
[Linux] Adding component to entity - do it twice(on windows problem not exists)

### ISSUE THREAD

**Issue by L4exp** [o3de/o3de#9813]
**Describe the bug**
After adding component to entity, it duplicates added component.

**Steps to reproduce**
Add component to any entity

**Expected behavior**
Component adds one time

**Actual behavior**
Component adds twice

**Assets required**
-

**Screenshots/Video**
![Duplicated components](https://user-images.githubusercontent.com/102804753/170781823-40b337f1-410a-4ac7-97c8-d22337e06e85.png)

**Found in Branch**
Development(build 27.05)

**Desktop/Device (please complete the following information):**
 - Device:PC
 - OS: Linux
 - Version: Calculate 22
 - CPU: dual intel xeon 2699v3
 - GPU: AMD Radeon VII
 - Memory: 192Gb

**Additional context**

**Comment by mbalfour-amzn** [comment]
@L4exp does this happen with _any_ component, or just with Image Gradient?

**Comment by L4exp** [comment]
Seems, that problem dissapeared
