### ISSUE TITLE
Script Canvas Array tags

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#9823]
**Describe the bug**
If you make an array variable of type tag, you are not able to set new elements in the array from the node inspector.

**Steps to reproduce**
1. Open a script canvas graph.
2. Add a new variable of type Array
3. Select Tag as the type.
4. Go to the node inspector with the Array Variable selected
5. Add a new element to the array
6. No type area shows up to add tag
7. See Error

**Expected behavior**
Using tags in an array should allow for adding the tags in the inspector.

**Actual behavior**
No input field available to add tag name in the inspector.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/100494538/170893421-34c567ab-30e4-496e-9499-80697fc75f90.png)

**Found in Branch**
Development Branch

**Desktop/Device (please complete the following information):**
 - Device: PC]
 - OS: Windows
 - Version 10

**Comment by ParasiteSt** [comment]
This does in a way seem to be fixed. You are now able to see and interact with a text box to add tags in, the only issue is it only takes the CRC value, and does not convert a string to CRC value which makes it hard to use tags you are already using.
For example say I have a tag Player1 on my character entity, I myself do not know what the CRC value of Player1 is so adding this tag to an array seems nearly impossible. But the bug report here is fixed in terms of what was said is wrong with it.

**Comment by pollend** [comment]
> This does in a way seem to be fixed. You are now able to see and interact with a text box to add tags in, the only issue is it only takes the CRC value, and does not convert a string to CRC value which makes it hard to use tags you are already using. For example say I have a tag Player1 on my character entity, I myself do not know what the CRC value of Player1 is so adding this tag to an array seems nearly impossible. But the bug report here is fixed in terms of what was said is wrong with it.

yep I do realize that :(. just didn't think it was in the scope of the change need to figure out how to store some like meta data ...

**Comment by ParasiteSt** [comment]
I completely understand, what you did is amazing work and is allowing for the use of the tag array.
I am curious if you could get what you are looking for in the Get Entity By Tag node? This node utilizes a text input field that takes a string value and turns it into a CRC value. I am not sure if the logic behind this node could be utilized and reused for the array tag text field.
