### ISSUE TITLE
Textures cannot be assigned to materials

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de#9827]
**Describe the bug**
Assigning textures to a material does not work. Material cannot be modified to include any texture through both Material Editor and Material Instance Inspector. Both Pick Texture window and dragging a texture file to texture property does not work.  Please refer to the attached video for more information.

 **Steps to reproduce**
 1. Open the Material Editor tool.
 2. Create a new material.
 3. Click on folder icon of any Texture property in the Inspector tool.

**Expected behavior**
Available textures are displayed in in the Pick Texture window.

**Actual behavior**
 Pick Texture window does not display any content.
 
 **Video**

https://user-images.githubusercontent.com/86953282/170976484-4af3f3d5-3a7d-4bb9-81a7-5fa6d9f5202f.mp4

**Found in Branch**
Development (a53a366)

**Desktop/Device:**
• Device: PC
• OS: Windows  
• Version: 10 Pro
• CPU: Intel Core i7 11700F
• GPU: Nvidia RTX 3070 LHR
• Memory: 32GB

**Comment by gadams3** [comment]
this will be addressed once the following pull request is submitted  https://github.com/o3de/o3de/pull/9893
