### ISSUE TITLE
Bug Report: The PhysX rigid body UI component falsely computes the inverse of the inertia

### ISSUE THREAD

**Issue by ManosAgelidis** [o3de/o3de#9829]
**Describe the bug**
The PhysX rigid body UI component falsely computes the inverse of the inertia that is provided by the user. It might be that the inverse is shown to the UI, but internally the correct value is stored

**Steps to reproduce**
1. Launch the O3DE editor
2. Add a mesh component e.g. a cyilinder 
3. Add a PhysX rigid body component e.g. a 
4. Add a hinge joint between the entity and its parent
5. Deselect the 'compute mass' property from the rigid body component's menu
6. Deselect the 'compute CoM' property from the rigid body component's menu
7. Deselect the 'compute inertia' property
8. Try to add a small value in the X-inertia box e.g. 0.0005.  
9. The UI will automatically compute the inverse of the inertia e.g. 1/0.0005 and show it in the checkbox. It is unclear whether the inertia value is properly stored, meaning this is a purely UI bug

**Expected behavior**
The UI should read the value provided by the user and display it correctly, the internally stored inertia matrix should store the value provided by the user

**Actual behavior**
The UI displays the inverse of the inertia value provided by the user, unclear whether the internal inertial matrix is receiving the user's input 

**Assets required**
No special assets required

**Screenshots/Video**
Attached Video

**Found in Branch**
Found on the development branch , tag fb1fe7534f2c532b5a0e079c34b55368a70c6203

**Desktop/Device (please complete the following information):**
 - Device:  PC
 - OS: Ubuntu
 - Version: 20.04
 - CPU: Intel I9-11900H
 - GPU: NVidia GeForce RTX 3080
 - Memory: 32GB

**Additional context**
No additional contetx

https://user-images.githubusercontent.com/17083612/171013868-7d9b5728-93a0-4656-a660-f1dcbd800df7.mp4

**Comment by greerdv** [comment]
Note that while looking into this issue, I found another problem which leads to inertia values not being correctly serialized https://github.com/o3de/o3de/issues/10341
