### ISSUE TITLE
Blast legacy materials deprecation

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#9839]
According to [deprecation policy](https://github.com/o3de/community/blob/main/guides/o3de-deprecation-guidelines.md), legacy code can be removed after 1 full release. 
Blast legacy material code marked as deprecated should be removed 1 release after its original release.

Timeline:
- O3DE 22.05.0 release didn't include blast material refactor.
- O3DE 22.10.0 will include new new blast materials and legacy code is marked as deprecated.
- The release after O3DE 22.10.0 will NOT include blast legacy materials.

This task is a reminder to remove legacy blast materials and its conversion tools on the release after O3DE 22.10.0.

To remove:
- o3de\Gems\Blast\Code\Source\Editor\Material

`O3DE_DEPRECATION_NOTICE(GHI-9839)` comments has been added to the code too.

**Comment by sptramer** [comment]
https://github.com/orgs/o3de/teams/sig-simulation - When deprecated, an issue must be created on o3de.org to remove any materials related to the deprecated content.

**Comment by moraaar** [comment]
Updated description to reflect the latest deprecation policy of 1 full release (instead of 2). https://github.com/o3de/community/blob/main/guides/o3de-deprecation-guidelines.md

**Comment by moraaar** [comment]
https://github.com/o3de/o3de-extras/pull/95
