### ISSUE TITLE
Physics legacy materials deprecation

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#9840]
According to [deprecation policy](https://github.com/o3de/community/blob/main/guides/o3de-deprecation-guidelines.md), legacy code can be removed after 1 full release. 
Physics legacy material code marked as deprecated should be removed 1 release after its original release.

Timeline:
- O3DE 22.05.0 release didn't include physics material refactor.
- O3DE 22.10.0 will include new physics materials and legacy code is marked as deprecated.
- The release after O3DE 22.10.0 will NOT include physics legacy materials.

This task is a reminder to remove legacy physics materials and its conversion tools on the release after O3DE 22.10.0.

To remove:
- o3de\Code\Framework\AzFramework\AzFramework\Physics\Material\Legacy
- o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Physics\Material\Legacy
- o3de\Gems\PhysX\Code\Editor\Source\Material\Conversion
- o3de\Gems\EMotionFX\Code\EMotionFX\Pipeline\SceneAPIExt\Utilities\LegacyPhysicsMaterialFbxManifestConversion.h.cpp

`O3DE_DEPRECATION_NOTICE(GHI-9840)` comments has been added to the code too.

**Comment by sptramer** [comment]
@micronAMZN To evaluate for docs and see if the work has already been done on o3de.org; Still a valid engineering task (?).

**Comment by moraaar** [comment]
Updated description to reflect the latest deprecation policy of 1 full release (instead of 2). https://github.com/o3de/community/blob/main/guides/o3de-deprecation-guidelines.md

**Comment by moraaar** [comment]
Documentation was updated as part of the release (https://github.com/o3de/o3de.org/pull/1970), so no further changes are needed.
