### ISSUE TITLE
Mouse cursor disappears after exiting full screen game mode on Linux

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#9841]
**Description**
When going from maximized game mode from the Editor back to Editor mode, the mouse cursor disappears for the entire system. The mouse pointer is there but is invisible.

**Steps to reproduce**
1. Launch the Editor
2. Open or create a level
3. Click on 'Play Controls' and select 'Play Game (Maximized)'
4. After the game goes into a maximized screen, press the 'Esc' key to return to the Editor

**Expected behavior**
The Editor mode is restored with the mouse cursor visible and in a usable state

**Actual behavior**
The Editor mode is restored, but the mouse cursor is invisible. Moving the mouse around will confirm that the pointer does hover over other windows, but no cursor is visible making it extreme difficult to use. The only way to restore the cursor is to somehow close the Editor completely

**Found in Branch**
development @ 1660c73d73962195ed810f0d880c8be975191e21

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 20.04.3 LTS
 - CPU AMD Thread Ripper
 - GPU RTX 3070
 - Memory 64 GB

**Comment by amzn-tmryan** [comment]
We tried to reproduce this issue on an EC2 instance and could not. The mouse cursor is present even when in GameMode, so we suspect this might not be reproducible using remote desktop. Tried running both unmaximized and maximized GameMode windows.

**Comment by spham-amzn** [comment]
> We tried to reproduce this issue on an EC2 instance and could not. The mouse cursor is present even when in GameMode, so we suspect this might not be reproducible using remote desktop. Tried running both unmaximized and maximized GameMode windows.

That is probably related to an EC2 instance vs hardware. I suspect its a timing issue, for some reason Qt on Linux is ignoring the set_cursor call when game mode ends

**Comment by Darkinggq** [comment]
ref:#11491

**Comment by thesmallcreeper** [comment]
With https://github.com/o3de/o3de/pull/11491 merged, I think this issue should have been resolved.

**Comment by gralco** [comment]
I can confirm #11491 fixes it in Fedora 36.

**Comment by spham-amzn** [comment]
Also verified #11491 fixes this issue, great work!
