### ISSUE TITLE
Skinned Mesh Faces not rendering correcly due to Bone Names in Blender.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#9843]
**Describe the bug**
I have tested and found a solution to an issue where using Blender Default Bone names on a Skined Mesh will result in faces not rendering correctly. O3DE will say default Blender Bone names such as Bone.001 is invalid when checking the FBX settings, and will attempt to rename it. This will not correct the issue unless you go back to the source DCCs tool and manually rename them, see examples below.

![image](https://user-images.githubusercontent.com/87207603/171270164-1b5662b3-6c43-45ca-8b8d-06e7e190d604.png)

**Steps to reproduce**
1.Create a mesh with a few skinned bones. Could be as simple as a cylinder.
2. Export with default names.
3. View in o3de
4.Now Export with more o3de friendly names without the invalid characters in the bone names.
5. View in o3de

**Expected behavior**
Maybe would be cool to except some special characters in the bone string name such as .

**Actual behavior**
If there is a invalid character in the bones names.. you will only see the error if you open the FBX settings, but it will not correct the issue. You will have to do this manually. 

**Assets required**
[TestFiles.zip](https://github.com/o3de/o3de/files/8808770/TestFiles.zip)

This is the invalid, but default naming convention blender uses:
![image](https://user-images.githubusercontent.com/87207603/171269260-3f1f69f1-80b9-455e-b8ff-73ec054b04f7.png)

If Changed to this, the mesh will render correctly:
![image](https://user-images.githubusercontent.com/87207603/171269520-86587f4f-e114-47f5-8ccd-2038d9bc33d3.png)

**Found in Branch**
Nightly 5/31/2022

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel I9-9900k
 - GPU NVidia RTX 2080ti
 - Memory [e.g. 16GB]

**Comment by GraphiteSIX** [comment]
I Imported the assets into the editor and asset justF2  shows partial wireframe as described above.
Looking into the logs, the converted azmodel dot character are replaced with underscore but animation editor uses the fbx.
There are other errors but it seems the parser doesn't produce accurate data import because of the dot character. 
[Logs_JustF.zip](https://github.com/o3de/o3de/files/8809527/Logs_JustF.zip)

**Comment by lmbr-pip** [comment]
Allowed characters are in the documentation, '.' would be invalid for a node name for O3DE. Maya does not allow these characters so we defer to the Maya naming convention.

This may be a sig-content feature/asset-pipeline issue.

**Comment by amzn-rhhong** [comment]
https://github.com/o3de/o3de/pull/9852 should address this issue.

**Comment by hultonha** [comment]
Could this please be verified @shawstar as we believe https://github.com/o3de/o3de/pull/9852 fixes it, please reopen if not. Thanks!
