### ISSUE TITLE
Improve default configuration used by PhysX Collider component

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#9867]
**Is your feature request related to a problem? Please describe.**
When adding a PhysX Collider to an entity, the shape didn't appear at first. This is because the shape property was set to be the shape "PhysicsAsst". 

![image](https://user-images.githubusercontent.com/87207603/171508517-7730b917-810c-4740-97ab-c945cedd286e.png)

This is great to have if you happen to have built a mesh and created a collider in your DCCs too with an ext "_phys"
However, if this is not the case, debug draw doesn't generate a shape to visualize, as there is none. User will need to pick a new shape to have this Collider working.

![image](https://user-images.githubusercontent.com/87207603/171510799-87147ad2-d10b-4368-9d4a-9f6f65ac3d46.png)

So, it would be ideal to detect if there is no supplied _phys mesh in the asset, if this is not the case automatically chose a shape, such as a Cube. The user will be able to start immediately visualization of the component.

**Comment by hultonha** [comment]
Adding needs-ux-info. Tagging @rainbj for visibility. Could this please be added to the agenda to discuss in the sig-ui-ux bi-weekly office hours.

**Comment by yuyihsu** [comment]
related to https://github.com/o3de/o3de/issues/9883

**Comment by yuyihsu** [comment]
No UX required for this ticket. Please follow the suggestion described in the comment section to fix the issue. Please check back with @o3de/sig-ui-ux to review the final implementation.

**Comment by moraaar** [comment]
This issue has been sorted out with the work of splitting PhysX Collider component in 2 (Primitive and Mesh Colliders): https://github.com/o3de/o3de/pull/14418

So now if the user chooses a Primitive Collider component the box shape is the default and it'll work right away (as the GHI description says). Only if the user chooses a Mesh Collider they will use this specific component (whose asset field gets automatically assigned if the fbx of the mesh has a valid physx mesh asset produced).
