### ISSUE TITLE
[Linux] Clicking the Editor with mouse buttons causes the Select Color window to flicker

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#9877]
**Describe the bug**
If the Select Color window is in focus, and the user clicks the Editor with any mouse button, it can cause the Select Color window to flicker, and the Ubuntu system pop-up (O3DE Editor - "O3DE Editor" is ready) to show up briefly in the top-middle of the screen.

It should be noted that this does not occur on Windows.

**Steps to reproduce**
1. Create an entity, and add any component to it that contains a property with a color picker included (e.g. White Box).
2. Click the color on the color picker property (Tint property on the White Box component) to open the "Select Color" window.
3. While "Select Color" window is in focus, click on the Editor window repeatedly.

**Expected behavior**
Nothing happens.

**Actual behavior**
Select Color flickers when clicking, and an Ubuntu system pop-up shows up occasionally.

**Video**

https://user-images.githubusercontent.com/86952082/171618706-891da79c-96d4-450b-bc3d-8fa55f8ae344.mp4

**Found in Branch**
Development (9cf4dff)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by byrcolin** [comment]
I'm not sure we can even fix this, it might be qt behavior on linux. needs investigation.
