### ISSUE TITLE
[Linux] Memory usage displayed in the Editor is always zero

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#9879]
**Describe the bug**
Memory usage displayed in the Editor always shows 0 Mb on Linux. 

It should be noted that this does not occur on Windows.

**Steps to reproduce**
1. Launch any level in the Editor.
2. Look to the bottom right at the Memory usage.

**Expected behavior**
Memory usage is displayed to the user.

**Actual behavior**
Memory usage displayed is always 0 Mb.

**Video**

https://user-images.githubusercontent.com/86952082/171628819-753e55c3-af55-4ad2-abe1-ca781b6acb08.mp4

**Found in Branch**
Development (9cf4dff)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-ArturZieba** [comment]
The memory usage is now shown on Linux (verified on the Development (1212214) build), however when first launched or restarted, the Editor can display a very large memory amount (please refer to the attached screenshot). While this was reproduced on three different machines (O3DE was built with Pre-built SDK configuration, and with Default Template project), one of the machines could not reproduce it with the Default Template project, and had to use a project with all Gems enabled. Please let us know if this should be reported separately.

![LinuxMemoryUsage](https://user-images.githubusercontent.com/86952082/179766338-35aa9b12-d2a3-424b-95bb-91041dd2f208.png)

**Comment by pollend** [comment]
> The memory usage is now shown on Linux (verified on the Development ([1212214](https://github.com/o3de/o3de/commit/1212214c89bde6249dccfb6bfc32a588471c5948)) build), however when first launched or restarted, the Editor can display a very large memory amount (please refer to the attached screenshot). While this was reproduced on three different machines (O3DE was built with Pre-built SDK configuration, and with Default Template project), one of the machines could not reproduce it with the Default Template project, and had to use a project with all Gems enabled. Please let us know if this should be reported separately.
> 
> ![LinuxMemoryUsage](https://user-images.githubusercontent.com/86952082/179766338-35aa9b12-d2a3-424b-95bb-91041dd2f208.png)

umm, looks like something is happening when is parse `/proc/self/status`.

**Comment by pollend** [comment]
looks like this was already fixed?
