### ISSUE TITLE
Bug: Shadow Artifacts On Terrain

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#9882]
**Describe the bug**
In the editor, as the camera move above the terrain, there are some visible shadow artifacts where some triangles get considerable darker than what they should be.

**Steps to reproduce**
Build the Editor, with `AutomatedTesting`, and load the attached level.

**Expected behavior**
No shadow artifacts in the terrain

**Actual behavior**
Some triangles are rendered darker as the camera moves in the Editior.

**Assets required**
[goal_9ks_1kd.zip](https://github.com/o3de/o3de/files/8824883/goal_9ks_1kd.zip)

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/66021303/171654898-6980beea-bc0f-4558-8074-f23dd0baf867.png)

**Found in Branch**
`development` branch:
commit f648fe91c71e824798ad06a2eea3a17e686e121e (HEAD -> development, upstream/development)
Author: Allen Jackson <23512001+jackalbe@users.noreply.github.com>
Date:   Thu Jun 2 08:31:26 2022 -0500

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [AMD ThreadRipper 32/64]
 - GPU [NVidia RTX 3070]
 - Memory [64GB]

**Additional context**

**Comment by galibzon** [comment]
FYI @mbalfour-amzn , @invertednormal , @jiaweig-amzn

**Comment by mbalfour-amzn** [comment]
Note - this artifact is specifically related to the Shadow Filter method. It happens with "None" and "PCF", but not with "ESM".

**Comment by invertednormal** [comment]
@antonmic I noticed this as well, I don't _think_ It's anything in particular that terrain is doing wrong, especially considering that esm filtering fixes the problem Do you have any more insight here?

**Comment by invertednormal** [comment]
Another example - 
![image](https://user-images.githubusercontent.com/1105143/176021658-e2af8e80-bbef-4bcf-bc0c-53663c86a323.png)

**Comment by galibzon** [comment]
@antonmic Today I noticed the terrain was not rendering the shadow artifacts, but the code I have is 10 days old. Then I noticed I had MSAA set to 1 (aka NOMSAA). Just a lead.

**Comment by ParasiteSt** [comment]
> Note - this artifact is specifically related to the Shadow Filter method. It happens with "None" and "PCF", but not with "ESM".

ESM does still have the shadow artifacts, but they are barely visible unless you have a lot of artifacts showing up. 

Example without and with ESM Filtering
![image](https://user-images.githubusercontent.com/100494538/194970291-41e1db53-7505-443a-a95c-b2d0ec67a2c0.png)
![image](https://user-images.githubusercontent.com/100494538/194970308-de69ad29-5bbd-487f-ac19-49541dfe04da.png)
There is still shadows being drawn, they are just very light with ESM. (easier to see with the box shadow artifact.)

**Comment by forhalle** [comment]
Reopening - fix was rolled back
