### ISSUE TITLE
[Linux] Spline component's Spline Type property is blank

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#9904]
**Describe the bug**
On Linux, the Spline component's Spline Type property is blank, and clicking the dropdown does not do anything. As per documentation (https://www.o3de.org/docs/user-guide/components/reference/shape/spline/), there should be three Spline Types available: Linear, Bezier, and Catmull-Rom.

It should be noted that this issue does not occur on Windows.

**Steps to reproduce**
1. Create an entity, and add a Spline component to it.
2. Attempt to change it's Spline Type property.

**Expected behavior**
Different Spline Types are available in the property dropdown.

**Actual behavior**
No Spline Type is shown in the property, and clicking the dropdown does not do anything

**Video and screenshot**

https://user-images.githubusercontent.com/86952082/171820357-63e74958-d1ea-481c-b034-64b0d0c7f08a.mp4

Spline component on Windows:
![SplineWindows](https://user-images.githubusercontent.com/86952082/171819905-11b39253-e166-4da5-81f5-70d0e8029387.png)

**Found in Branch**
Development (771b1d1)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by hultonha** [comment]
@pollend is actively working on fixing this issue and has a PR here - https://github.com/o3de/o3de/pull/9923

**Comment by pollend** [comment]
@LB-ArturZieba  here are some other places that will probably be broken in the same way. 

- PhysicsSceneQueries.cpp
- EditorMeshComponent.cpp
- EditorPostFxLayerComponent.cpp
- UiCheckboxComponent.cpp
- UiDropdownComponent.cpp
- UiDropdownOptionComponent.cpp
- UiMaskComponent.cpp
- UiNavigationSettings.cpp
- UiRadioButtonComponent.cpp
- PopulateChildEntityList.cpp
- TerrainLayerSpawnerConfig.cpp
- EditorTerrainPhysicsColliderComponent.cpp
- EditorTerrainSurfaceGradientListComponent.cpp
- GetSelectableLayers.cpp
- VirtualGamepadThumbStickComponent.cpp

**Comment by hultonha** [comment]
Thanks for the extra info @pollend, I'm closing this specific issue now though as your PR has been successfully merged (Fixed by https://github.com/o3de/o3de/pull/9923)

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (b0cfce0) build.
