### ISSUE TITLE
[Linux] Incorrect camera behavior for multiple Viewports

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#9906]
**Describe the bug**
After leaving the Game Mode, the viewport camera activates for two viewports at once. Changing the selection of viewports restores the correct behavior. For more than two viewports, two randomly selected viewports are chained together.

**Steps to reproduce**
1. Create a new level.
2. Configure the Viewport Layout to render two windows.
3. Enter/exit Game Mode.
4. Hold RMB over one of the viewports and move the camera.

**Expected behavior**
Only the camera of the selected viewport is activated.

**Actual behavior**
Both viewport cameras are activated.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/171855810-d1da2b6d-28ea-43a4-a29a-de84546cc29e.mp4

**Found in Branch**
Development (771b1d1)

**Desktop/Device:**
Device: PC
OS: Linux
Version Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU Nvidia Geforce RTX 2060 SUPER
Memory 16GB

**Comment by monroegm** [comment]
Related to #9809

**Comment by hultonha** [comment]
Multiple viewports have been disabled so I recommend closing this issue as it is no longer relevant

**Comment by LB-JakubSkoczylas** [comment]
Confirming the issue has been closed due to the feature being deprecated.
