### ISSUE TITLE
PhysXMaterialRefactor: Physics Materials from Linux Gems\PhysX\Assets\PhysX directory have different physical values than materials from PC build

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#9927]
**Describe the bug**
The physical values of Physics Materials located in_ Gems\PhysX\Assets\PhysX_ differ between Linux and PC build. For instance it can be observed that _rubber.physxmaterial_ has a restitution value of *0.85* on PC build ,whereas on Linux build the restitution value for the material for its _Gems\PhysX\Assets\PhysX\rubber.physxmaterial_ is *0.0* generating no bounciness in entities assigned with this material.

All of _.physxmaterials_ from _Gems\PhysX\Assets\PhysX_are affected.

Please note the materials work the same as on PC builds when the values are manually corrected.

For further information please refer to the attached screenshot and .zip file with screenshots of all PC and Linux.physxmaterials from Gems\PhysX\Assets\PhysX directory.

**Prerequisites**:
 * PhysXMaterialRefactor branch build with AutomatedTesting project was built and prepared to launch on both Linux and PC machine.

**Steps to Reproduce**:
 1. Launch the Editor on PC machine and create a new level.
 2. Open the Asset Editor.
 3. Open the _Gems\PhysX\Assets\PhysX\rubber.physxmaterial_ and take a note of its
 restitution value.
 4. Launch the Editor on Linux build and repeat the above steps.

**Expected behavior**
Physical values of _.physxmaterials_ from Gems\PhysX\Assets\PhysX directory are the same on PC and Linux build.

**Actual behavior**
Physical values of _.physxmaterials_ from Gems\PhysX\Assets\PhysX directory are not the same on PC and Linux build.

**Screenshots/Video**

![PCvsLinux Vehicle physxmaterial](https://user-images.githubusercontent.com/86953456/172832890-9bd48145-0010-4ae8-8ef8-37ce44bfc772.png)

**Found in Branch**
PhysXMaterialRefactor (5e78b35)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Additional context**
[PC and Linux .physxmaterials screenshots.zip](https://github.com/o3de/o3de/files/8869736/PC.and.Linux.physxmaterials.screenshots.zip)

**Comment by moraaar** [comment]
I couldn't reproduce this bug using development branch (commit 0c633652f4), all the materials under  Gems\PhysX\Assets\PhysX showed the right value in linux.

FYI @LB-MateuszSzweda, AutomatedTesting project has many materials asset using the same names under its source folders. Please double check you're opening the materials under  `o3de\Gems\PhysX\Assets\PhysX\` and not from any other folder, where they might have different values just for certain automated tests. Also, please double check there are no local changes done to the files.

Closing this bug, if you still have issue feel free to reopening with further information.

Thanks.

**Comment by LB-MateuszSzweda** [comment]
Today I've rechecked this on Development (b0cfce0) on two separate PC and Linux machines.

Again when physics materials from o3de\Gems\PhysX\Assets\PhysX folders were opened in Asset Browser different values were observed on PC and Linux.

Freshly cloned PC build was built with source engine workflow and run AutomatedTesting project with new level
and freshly cloned Linux build was built with source engine workflow but a new default template project was created and run.

I've recorded the discrepancy between the Rubber and Wood materials on PC and Linux builds in the video files below.

**Linux:**

https://user-images.githubusercontent.com/86953456/173850320-1ccd6513-8282-4981-b872-2cd2b4195227.mp4

**PC:**

https://user-images.githubusercontent.com/86953456/173850397-6bb2e7ef-5499-4853-93de-44d0cf6bc3bf.mp4

**Comment by moraaar** [comment]
You mention in linux you've tested it with a new project. I tested it in linux with AutomatedTesting project, like you did on PC and it worked. Maybe it has something to do with a new project and being separate from the engine.

Can you test it on pc using a new project @LB-MateuszSzweda?
I'll test linux using a new project and see if I can reproduce your bug.

Thanks

**Comment by LB-MateuszSzweda** [comment]
I've tested it today on another PC machine copying the Linux workflow and building new project. The values for materials were just like previously spotted in PC Automated Testing so **Dynamic Friction:0.85**, **Static Friction:0.85** and **Restitution:1.0** in case of rubber material.

I've also tried to clone and build linux again, cleaning every O3DE possible residue together with o3de-packages but again on built AutomatedTesting and new project the values for materials were different than on PC so **Dynamic Friction: 1**, **Static Friction: 1** and **Restitution: 0** in case of rubber material.

**Comment by moraaar** [comment]
Thanks @LB-MateuszSzweda, this is an odd one.

On the Linux machine, can you open with a text editor the files (.physxmaterial) inside `o3de\Gems\PhysX\Assets\PhysX` and check if they are the same as in pc?

Also, on linux, once the Asset Processor has finished processing the assets of your project, please go and open with a text editor the files (.physicsmaterial and .physxmaterial) inside your project's cache (eg for AutomatedTesting project it'd be in `AutomatedTesting\Cache\pc\physx`) and check they still have the right values.

Thanks

**Comment by LB-MateuszSzweda** [comment]
@moraaar  I've compared the .physicsmaterial and .physxmaterial files from both PC and Linux directories and strangely enough they indeed were the same and uniform values for material properties. Yet again when opened in Asset Editor on Linux the values were differing.

[PC AutomatedTesting PhysX.zip](https://github.com/o3de/o3de/files/8941494/PC.AutomatedTesting.PhysX.zip)
[Linux AutomatedTesting Physx.zip](https://github.com/o3de/o3de/files/8941496/Linux.AutomatedTesting.Physx.zip)

**Comment by pollend** [comment]
sounds like another pathing issue. the path was probably changed to all lower case, I'm not sure exactly where this is happening but I've seen similar problems in the past.

**Comment by LB-MateuszSzweda** [comment]
@moraaar  No. Unfortunately they behave according to the values shown in Asset Editor not the .physxmaterial file.
So Rubber.physxmaterial which shows Restitution: 0 in Linux Asset Editor will not trigger bouncing behavior in entities when assigned. 

In fact this is how the issue was initially found. I've noticed that very similar entities with assigned \Gems\PhysX\Assets\PhysX materials behaved differently on Linux (rubber not bouncing,concrete having no friction) and PC (correct material behaviors) which led me to inspecting them with Asset Editor.

**Comment by moraaar** [comment]
@LB-MateuszSzweda I just tested latest development (commit 8d04988aa0) on my Linux machine, using both AutomatedTesting and a new default project, and the materials have valid values. I've also assigned the materials to an sphere collider and it bounces as expected. So I can't still reproduce this bug.

From this point I suggest the following:
1. I think it'd be great to ask another person to try to reproduce this with another linux machine, see if they can reproduce it.
2. Please zip your linux project and send it to me, I'll try to build it and reproduce the error.
3. Please send me all the steps you do in a very detailed manner, every step, command run, etc. So I can follow those steps to the letter, I'd like to do exactly the same steps you do in your linux machine as if it's a clean build.

If you can think of other actions we can do to get to the bottom of this, please let me know. We'll find out what's going on here :)

Thanks @LB-MateuszSzweda

**Comment by moraaar** [comment]
@LB-MateuszSzweda sorry for the delay. I followed your detailed steps using development 7c01c4035f today on my Linux laptop (Ubuntu 20.04.4 LTS) with a clean build, syncing git from scratch and deleting my user/.o3de, and still can't reproduce the issue. When I open the physics materials with the Asset Editor they have the correct values.

Opening the editor in step 8 did crash a couple of times, the OS reports the editor doesn't respond and suggests to force quit, but this is because the Asset Processor is taking all the resources of the laptop processing the assets, leaving the editor unresponsive.

Please try doing this, between steps 7 and 8, let's call it 7.5, run the Asset Processor first (_home/user/o3de/build/linux/bin/profile/AssetProcessor_) and wait until it's finished processing assets, then do step 8 to launch the editor. Let's see if that makes a difference for you (it shouldn't, but we are running out of options to try).

Thanks

**Comment by LB-MateuszSzweda** [comment]
@moraaar 

I've set up the machine once again clearing very trace of o3de from registry and O3DE/.o3de folders from user and root directories.
Then I've run the Asset Processor prior to launching the Editor as described above as step 7.5.

However to no avail. The Physics materials values from Gems\PhysX\Assets\PhysX\ were still wrong when opened with Asset Editor.

The only ideas of the culprit I have are:

1. This is caused by dual boot configuration we use with Windows installed on the first drive and Linux on the second.

2. Most if not all of the tested machines had an AMD Ryzen CPU which seems to have a certain problem linked to its hardware RNG with Ubuntu 20.04 (https://github.com/o3de/o3de/issues/6776) 
and it looks that on some machines even with updated BIOS this problem persists and 

`[0.000000] RDRAND gives funky smelling output, might consider not using it by booting with “nordrand”`

line can be observed on system launch.

I've reached out to my team to search for a linux machine with Intel CPU to compare results.
I will update as soon as the steps are repeated on it.

**Comment by LB-MateuszSzweda** [comment]
Unfortunately the issue was reproduced on machines with AMD CPU as well as Intel CPUs.

**Comment by LB-MateuszSzweda** [comment]
The culprit of the issue was found to be linked to the set language format and was logged as https://github.com/o3de/o3de/issues/11139.

As the above issue is a part of broader https://github.com/o3de/o3de/issues/11139 with the authorization from @moraaar I am closing the above,
