### ISSUE TITLE
[Linux] Engine register command provided by cmake build command error is missing file extension

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#9947]
**Describe the bug**
CMake error that occurs when attempting to build a project without a registered engine contains an engine register command that is missing the .sh file extension.

It should be noted that this issue only applies to Linux, as the command is functional on Windows.

**Steps to reproduce**
1. Install the latest .deb package.
2. Do not register the new engine.
3. Create a project `$O3DE_ENGINE/scripts/o3de.sh create-project --project-path $O3DE_PROJECT_PATH`
4. Switch to the project directory.
5. Register the project `~/github/o3de/scripts/o3de.sh register --project-path .`
6. Generate the build folder `cmake -B build/linux -S . -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12 -DCMAKE_BUILD_TYPE=profile`
7. Observe the error and attempt to address it with the provided command.

**Expected behavior**
Provided command registers the Engine.

**Actual behavior**
Provided command is missing the file extension and does not execute without adding it.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/86951905/172371579-cad58c40-f17d-4ab1-9809-8192a99bbdf7.png)

**Found in Branch**
Development installer

**Desktop/Device:**
- Device: PC
- OS: Ubuntu
- Version 18.04
- CPU AMD Ryzen 3600
- GPU Nvidia GeForce RTX 2060 SUPER
- Memory 16GB

**Comment by amzn-changml** [comment]
@LB-RostyslavGavryliuk this is the correct behavior under Linux, as all commands require the full path, including any extensions.

We can either drop this, or if we want to be consistent with documentation, we would have to remove the extension from all shell scripts (would break existing build scripts) or symlink extension-less versions

**Comment by amzn-changml** [comment]
Closing this issue as no-fix. The documentation states the full extension for the `o3de` script as `o3de.sh`: https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/#register-the-engine
