### ISSUE TITLE
Editor crashes when double-clicking the prefab icon in the upper left corner of the Viewport after changing the layout and using the Maximized option

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de#9950]
**Describe the bug**
Editor crashes when double-clicking the prefab icon in the upper left corner of the Viewport after changing the number of Viewport windows in the Layout Configuration and using the Maximized option on the Viewport window.

It should be noted that Linux build does not generate error.log or error.dmp. 

It should also be noted that Windows editor.log contains asserts that are not present in Linux. Please refer to the attached Editor.log, error.log, and error.dmp files for more information.

**Call Stack Trace:**
```
25) 00007FFBF0BBFF27 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFBF34151B0 (ntdll) : memset
23) 00007FFBF33FC766 (ntdll) : _C_specific_handler
22) 00007FFBF341209F (ntdll) : _chkstk
21) 00007FFBF33C1454 (ntdll) : RtlRaiseException
20) 00007FFBF3410BCE (ntdll) : KiUserExceptionDispatcher
19) C:\o3de\Code\Framework\AzCore\AzCore\EBus\EBus.h (1461) : AZ::Internal::IdHandler<AZ::RPI::ViewportContextNotifications,AZ::RPI::NotifyByViewportIdTraits,AZ::Internal::EBusContainer<AZ::RPI::ViewportContextNotifications,AZ::RPI::NotifyByViewportIdTraits,
18) C:\o3de\Gems\Atom\Tools\AtomToolsFramework\Code\Source\Viewport\ViewportInteractionImpl.cpp (28) : AtomToolsFramework::ViewportInteractionImpl::Disconnect
17) C:\o3de\Gems\Atom\Tools\AtomToolsFramework\Code\Source\Viewport\RenderViewportWidget.cpp (116) : AtomToolsFramework::RenderViewportWidget::~RenderViewportWidget
16) 00007FFBA2E261C4 (EditorLib) : AtomToolsFramework::RenderViewportWidget::`scalar deleting destructor'
15) C:\o3de\Code\Editor\EditorViewportWidget.cpp (902) : EditorViewportWidget::SetViewportId
14) C:\o3de\Code\Editor\ViewPane.cpp (303) : CLayoutViewPane::AttachViewport
13) C:\o3de\Code\Editor\LayoutWnd.cpp (201) : CLayoutWnd::MaximizeViewport
12) C:\o3de\Code\Editor\ViewportTitleDlg.cpp (956) : CViewportTitleDlg::eventFilter
11) 00007FFBAC6C388C (Qt5Core) : QCoreApplicationPrivate::sendThroughObjectEventFilters
10) 00007FFBAD17498D (Qt5Widgets) : QApplicationPrivate::notify_helper
 9) 00007FFBAD1728C0 (Qt5Widgets) : QApplication::notify
 8) 00007FFBAC6C17CB (Qt5Core) : QCoreApplication::notifyInternal2
 7) 00007FFBAD175BB5 (Qt5Widgets) : QApplicationPrivate::sendMouseEvent
 6) 00007FFBAD1C0662 (Qt5Widgets) : QSizePolicy::QSizePolicy
 5) 00007FFBAD1BE5FE (Qt5Widgets) : QSizePolicy::QSizePolicy
 4) 00007FFBAD1749A1 (Qt5Widgets) : QApplicationPrivate::notify_helper
 3) 00007FFBAD173A23 (Qt5Widgets) : QApplication::notify
 2) 00007FFBAC6C17CB (Qt5Core) : QCoreApplication::notifyInternal2
 1) 00007FFBACB14EF5 (Qt5Gui) : QGuiApplicationPrivate::processMouseEvent
```

**Steps to reproduce**
1. Right-click on the Viewport top bar and select the Configure Layout.
2. Select any option with multiple Viewports.
3. Right-click on the Viewport top bar and select Maximized.
4. Double-click on the Prefab icon in the upper left Viewport corner.
5. Double-click again.

**Expected behavior**
Double-clicking should switch between the Layout configurations.

**Actual behavior**
The editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/99716227/172376009-2b36dc05-6b37-4a81-99a3-9b5f2f87500f.mp4

**Found in Branch**
Development (a9c9b02)

**Desktop/Device:**
• Device: PC
• OS: Ubuntu
• Version: Ubuntu 20.04.4 LTS
• CPU Intel Core i7-9700K
• GPU Nvidia GeForce RTX 2070
• Memory 16GB

**Additional context**
Linux:
[Editor.log](https://github.com/o3de/o3de/files/8853188/Editor.log)

Windows:
[error.log](https://github.com/o3de/o3de/files/8853043/error.log)
[Editor.log](https://github.com/o3de/o3de/files/8853045/Editor.log)
[error.zip](https://github.com/o3de/o3de/files/8853064/error.zip)

**Comment by LB-JaroslawGaweda** [comment]
We also found that when launching the Editor with multiple Viewport layout, and using the "Maximized" option, the Viewports become unresponsive on Linux, and greyed out on Windows. It should be noted that the Editor is still responsive after using the "Maximized" option again. Should this be reported as a separate issue?

**Comment by hultonha** [comment]
@LB-JaroslawGaweda Could you please create a separate issue for this as this does sound slightly different though it is related. Thanks!

**Comment by hultonha** [comment]
It would be helpful to link the issues though to help see they're related, thanks!

**Comment by LB-JaroslawGaweda** [comment]
Thanks for the response, the issue reported can be found here: https://github.com/o3de/o3de/issues/9978.
