### ISSUE TITLE
Entities re-activate when component properties are changed

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#9956]
**Describe the bug**
When component properties are changed the entire entity is deactivated and re-activated

**Assets required**
n/a

**Steps to reproduce**
1. Set a breakpoint in Entity::Deactivate()
1. Open the editor and create a new level
2. Select the Atom Default Environment entity in the Entity Outliner
3. In the Entity Inspector, toggle the "Static" Transform Component setting

**Expected behavior**
The component property is changed without the entire entity being deactivated and re-activated

**Actual behavior**
The entire entity is deactivated and re-activated.
Note that the entity is not re-activated if the Translate or Rotate values are changed, just for some of the properties like Static, Parent Activation, etc.  This same behavior seems to be happening for many components.

**Found in Branch**
development

**Comment by AMZN-alexpete** [comment]
Possibly related issue #9855

**Comment by srikappa-amzn** [comment]
Closed by https://github.com/o3de/o3de/pull/9994

Feel free to reopen if you still see some issues.

**Comment by AMZN-alexpete** [comment]
Looks like the issue is fixed, thanks!
