### ISSUE TITLE
Actor Component Messes with Entity Outliner.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#9960]
**Describe the bug**
If you add an actor component to an entity that has a child entity and assign an actor to the actor component the arrow for dropdown to child entities disappears.

**Steps to reproduce**
1. Add an entity with a child entity attached to it.
2. Add an actor component and assign an actor asset to the component on the parent entity.
3. The dropdown for the child entity will disappear in the Entity Outliner.
4. See error.

**Expected behavior**
If you add an actor to the actor component it should add the actor without losing the dropdown for child entities of the parent entity.

**Actual behavior**
When a actor is assigned to an actor component the dropdown arrow and dropdown button disappear.

**Found in Branch**
Development (#9796)

**Desktop/Device**
 - Device: PC
 - OS: Windows
 - Version: 10

**Comment by monroegm** [comment]
@ParasiteSt can you get latest and see if #9881 resolves your issue?

**Comment by monroegm** [comment]
@amzn-jillich FYI
