### ISSUE TITLE
Unit tests fail intermittently when trying to access o3de_manifest.json file

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/o3de#9969]
**Describe the bug**
Some unit tests fail when trying to access o3de_manifest.json file

**Failed Jenkins Job Information:**
The name of the job that failed, job build number, and code snippit of the failure.
Name of the job : test_profile_nounity (Linux)
job build number : 2477
Failure snippet:
```
/data/workspace/o3de/Code/Framework/AzCore/./AzCore/UnitTest/UnitTest.h:175: Failure
[2022-03-10T19:20:58.860Z] Unable to read registry file "/home/lybuilder/.o3de/o3de_manifest.json".
```

**Attachments**
[test_failure_log.txt](https://github.com/o3de/o3de/files/8857305/test_failure_log.txt)

**Additional context**
This happened 3 months ago on build no. 1954 too.

**Comment by lumberyard-employee-dm** [comment]
The error occured in the AzFramework.Tests `SpawnableEntitiesManagerTest.SpawnAllEntities_Call_AllEntitiesSpawned` test which is maintained by sig/core, so adding that label as well as sig/testing for the issue

```
[2022-06-07T22:50:01.789Z] The following tests FAILED:

[2022-06-07T22:50:01.789Z] 	  5 - AZ::AzFramework.Tests.main::TEST_RUN (Failed)

[2022-06-07T22:50:01.789Z] Errors while running CTest
```

My preliminary hypothesis is that there is a python test that is writing to the o3de_manifest.json file that is running in parallel

The tests with the most likely hood to be writing to the o3de_manifest.json are the "AZ::ProjectManager.Tests.main::TEST_RUN" test and the "o3de_*.smoke::TEST_RUN" test, which are the ones registered in this [CMakeLists.txt](https://github.com/o3de/o3de/blob/development/scripts/o3de/tests/CMakeLists.txt)
