### ISSUE TITLE
AR Bug Report: test_EditorWorkflow_ParentEntityTransform_Affects_ChildEntityTransform 

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#9971]
**Describe the bug**
Test `test_EditorWorkflow_ParentEntityTransform_Affects_ChildEntityTransform` from `AutomatedTesting::EditorTests_Main.main` test run failed in AR.

**Failed Jenkins Job Information:**
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/2482/pipeline/617 

**Attachments**
[log.txt](https://github.com/o3de/o3de/files/8859817/log.txt)

**Additional context**
This happened before here https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/2425/pipeline/617 and a PR was submitted trying to make the test more solid https://github.com/o3de/o3de/pull/9848, but it has happened again.

**Comment by srikappa-amzn** [comment]
This seems to be happening for one other test as well. 
test_EditorWorkflow_ChildEntityTransform_Persists_After_ParentEntityTransform

Something about the setup of these tests could be causing these failures.
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/2479/pipeline
