### ISSUE TITLE
Gems: Dependencies not working in 22.05.0 installed version

### ISSUE THREAD

**Issue by ValPKFX** [o3de/o3de#9979]
**Describe the bug**
Adding gem dependencies in the gem.json prevents to build the project with 22.05.0 installed version downloaded here : [https://o3debinaries.org/download/windows.html]()
It works correctly with the Github version.

**Steps to reproduce**
1. Create an external gem: `C:\O3DE\22.05.0\scripts\o3de.bat create-gem -gp C:\o3de-gems\TestGem`
2. Add LmbrCentral as a dependency in the gem.json of the newly created gem
3. Register the gem in a project and try to build it

```
CMake Error at C:/O3DE/22.05.0/cmake/Subdirectories.cmake:182 (message):
  The gem "LmbrCentral" could not be found in any gem.json from the following
  list of registered external subdirectories:

  C:/o3de-gems/TestGem

  C:/Users/BuildServer/O3DE/Projects/NewProjectSDK/Gem
Call Stack (most recent call first):
  C:/O3DE/22.05.0/cmake/Subdirectories.cmake:234 (query_gem_paths_from_external_subdirs)
  C:/O3DE/22.05.0/cmake/Subdirectories.cmake:261 (reorder_dependent_gems_with_cycle_detection)
  C:/O3DE/22.05.0/cmake/Subdirectories.cmake:315 (reorder_dependent_gems_before_external_subdirs)
  C:/O3DE/22.05.0/cmake/Subdirectories.cmake:327 (get_external_subdirectories_in_use)
  C:/O3DE/22.05.0/CMakeLists.txt:78 (add_subdirectory_on_external_subdirs)
```

**Found in Branch**
22.05.0

**Additional context**
It seems to be related to #8388

**Comment by byrcolin** [comment]
fixed

**Comment by lumberyard-employee-dm** [comment]
The PR with the fix is https://github.com/o3de/o3de/pull/11213
