### ISSUE TITLE
Prefab content is not saved

### ISSUE THREAD

**Issue by NiklasHenricson** [o3de/o3de#9991]
When editing a network prefab (e.g. Multiplayer Example) and change the initial movement speeds and then save, you exit the prefab-edit mode by pressing ESC.

The values are not saved. Checking the JSON file all settings are not only reverted to previous values, but completely gone (using code versioning and comparing with repo version).

This happens also on our own project (the issue is reproducible). This issue seems to be content-related and not specific to the Multiplayer example only. 

Kinda a blocker since this prevents working with any prefabs at this point.

**Comment by lmbr-pip** [comment]
Reviewed by sig/network but it seems this is entirely prefab related for now. Please let us know if there is anything specific to networked prefabs.

**Comment by AMZN-alexpete** [comment]
Possibly related PR #9795

**Comment by NiklasHenricson** [comment]
Hello,

1. From the entity outlines instantiate a network prefab
![image](https://user-images.githubusercontent.com/5524755/173286024-a9fbb7bb-34f4-486f-9991-07cc3ec3cd89.png)
2. From the 'Pick Prefab' screen select the network prefab
![image](https://user-images.githubusercontent.com/5524755/173286125-7156e572-34c0-478c-ae2c-b58e57bbca83.png)
3. Double-click the prefab in the entity outliner to enter its edit mode
![image](https://user-images.githubusercontent.com/5524755/173286189-b44e4fdc-9ed0-4fde-ab1d-f65062a87c54.png)
4. We have basic player-entity moving speeds (initially all set to 5.0) at the bottom that we are changing to different values (similarly to the multiplayer project provided by O3DE)
![image](https://user-images.githubusercontent.com/5524755/173286434-318719f2-8755-43fc-8127-0ebfad94943d.png)

Changed to these values (not that it matters in this case)
![image](https://user-images.githubusercontent.com/5524755/173286610-9af14912-93c9-4afc-8bd5-c4d8b0b0caff.png)

5. Either CTRL+S or File | Save
![image](https://user-images.githubusercontent.com/5524755/173286713-1f8b5ff4-378e-4656-b877-80bf8cae49ef.png)
Notice that the asterisk is disappearing after saving (indicating the save went through)
![image](https://user-images.githubusercontent.com/5524755/173286824-48ca2d20-f86c-4a42-b51d-afd523df2ce3.png)
![image](https://user-images.githubusercontent.com/5524755/173286864-133d8229-3d20-430d-afb8-11c0d114f033.png)

6. Right click to Delete the prefab and re-add it
7. Delete option doesn't exist in the right-click menu
![image](https://user-images.githubusercontent.com/5524755/173287415-88829371-6534-4c5e-b069-ebe6422993d9.png)


The times we succeeded when the "Delete" option shows up, our values have been wiped out to their initial values, 5.0, 5.0, 5.0, etc...

**Comment by michabr** [comment]
Hi @NiklasHenricson, could you check with latest development if this issue is still occurring? We are unable to reproduce given the steps provided.

**Comment by lmbr-pip** [comment]
@NiklasHenricson Any update here? Otherewise we will consider this fixed.

**Comment by NiklasHenricson** [comment]
> @NiklasHenricson Any update here? Otherewise we will consider this fixed.

Hi @lmbr-pip please close this. I haven't experienced it ever since. I'm sorry for my late reply.
