### ISSUE TITLE
[MultiplayerSample]Destroy network entity on server, but client does not remove it immediately

### ISSUE THREAD

**Issue by xiapeng78** [o3de/o3de#9999]
**Describe the bug**
Destroy network entity on server, but client does not remove it immediately. Sever has one network entity with script that will destroy it after 30 seconds. The network entity destroyed on server, but client does not remove it immediately, client still display it for a few seconds.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.
[DestroyEntity.zip](https://github.com/o3de/o3de/files/8870232/DestroyEntity.zip)

**Steps to reproduce**
1. Create one network entity, add DestroyEntity.scriptcanvas
![image](https://user-images.githubusercontent.com/17897322/172846950-a8677c29-37c6-45d0-a6d0-a6ea3cb646f6.png)

2. Run MultiplayerSample.ServerLauncher.exe, and run MultiplayerSample.GameLauncher.exe before entity destroy
3. After 30 seconds, the network entity destroyed on server, but client does not remove it immediately, client still display it for a few seconds

**Expected behavior**
Client should remove network entity synchronously.

**Found in Branch**
Latest code of development branch.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-11700]
 - GPU [NVidia RTX 3060 Ti]
 - Memory [32GB]

**Comment by AMZN-Olex** [comment]
The right way to delete an entity on the server is to call MarkForRemoval API. I am not sure this is exposed to BehaviorContext, though.

**Comment by xiapeng78** [comment]
Review code we found the deleting process has a timer, and the code in figure set the interval.
![image](https://user-images.githubusercontent.com/17897322/175505066-8b6ad155-d7ab-4181-bbe2-e15330532ccf.png)
